### ISSUE TITLE
distribution: 3.16 tracking issue

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#10069]
## Work

@beyang

- [x] Update OKRs in handbook [#10070](https://github.com/sourcegraph/sourcegraph/issues/10070) 
- [ ] ~Docs: Kubernetes installation instructions should indicate how much cpu/memory is needed~ [#10008](https://github.com/sourcegraph/sourcegraph/issues/10008) 
- [ ] ~k8s: Deploy jaeger-agent as a Daemonset instead of sidecar container~ [#10052](https://github.com/sourcegraph/sourcegraph/issues/10052) 
- [ ] ~docs: Clarify that Sourcegraph schema migrations require postgres user to be admin, include advice on how to workaround~ [#5087](https://github.com/sourcegraph/sourcegraph/issues/5087) 
- [ ] ~Docs: document that NFS storage should be avoided~ [#10010](https://github.com/sourcegraph/sourcegraph/issues/10010) 

@davejrt

- [ ] ~move away from Prometheus alertmanager on Sourcegraph.com specifically~ [#5370](https://github.com/sourcegraph/sourcegraph/issues/5370) 
- [x] Sourcegraph.com should use *_CONFIG_FILE via Kubernetes [#4156](https://github.com/sourcegraph/sourcegraph/issues/4156) 
- [x] [deploy-sourcegraph] Use rollout strategy Recreate for stateful singleton deployments. [#2076](https://github.com/sourcegraph/sourcegraph/issues/2076) 🧶
- [x] Updating user settings fails on sourcegraph.com [#10235](https://github.com/sourcegraph/sourcegraph/issues/10235) 🐛

@ggilmore

- [ ] ~spike: investigate dhall for deploy-sourcegraph~ [#10145](https://github.com/sourcegraph/sourcegraph/issues/10145) __3d__ 🕵️
- [ ] ~spike: investigate cue for deploy-sourcegraph~ [#10143](https://github.com/sourcegraph/sourcegraph/issues/10143) __3d__ 🕵️
- [ ] ~placeholder issue~ [#10104](https://github.com/sourcegraph/sourcegraph/issues/10104) __3d__ 
- [ ] ~spike: investigate caddy issues in dev environment~ [#10103](https://github.com/sourcegraph/sourcegraph/issues/10103) __1.5d__ 🕵️
- [ ] ~Create scaling recommendation guide~ [#10102](https://github.com/sourcegraph/sourcegraph/issues/10102) __2d__ 
- [x] RFC 141: Prototype generating manifests, rather than directly editing deploy-sourcegraph [#10100](https://github.com/sourcegraph/sourcegraph/issues/10100) 
- [x] [ci] Investigate Cue and Dhall [#10063](https://github.com/sourcegraph/sourcegraph/issues/10063) 
- [x] [ci] our database backcompat tests have been broken for a while  [#9921](https://github.com/sourcegraph/sourcegraph/issues/9921) 
- [ ] ~Issues with Docker Compose on AWS installation docs~ [#9829](https://github.com/sourcegraph/sourcegraph/issues/9829) __1d__ 
- [x] ~Write sourcegraph/server -> docker compose migration guide~ [#9602](https://github.com/sourcegraph/sourcegraph/issues/9602) 
- [ ] ~Set ephemeral storage resource requests and limits in deploy-sourcegraph~ [#9604](https://github.com/sourcegraph/sourcegraph/issues/9604) __1d__ 

@slimsag: __1.00d__

- [ ] ~**STRETCH**: Ping select Prometheus performance, etc. metrics back to us~ [#10053](https://github.com/sourcegraph/sourcegraph/issues/10053) __1d__ 🕵️
- [ ] ~Update resource estimator to include precise-code-intel service breakout~ [#10050](https://github.com/sourcegraph/sourcegraph/issues/10050) __1d__ 🐛
- [ ] ~observability: server/dev should always run latest grafana/prometheus~ [#9983](https://github.com/sourcegraph/sourcegraph/issues/9983) __1d__ 
- [ ] ~Grafana: add an alert for gitserver failing to clone~ [#9966](https://github.com/sourcegraph/sourcegraph/issues/9966) __0.5d__ 
- [x] jetbrains editor configuration [#9925](https://github.com/sourcegraph/sourcegraph/issues/9925) __0.5d__ 
- [ ] ~observability: Add ping performance stats to frontend dashboard~ [#9867](https://github.com/sourcegraph/sourcegraph/issues/9867) __0.5d__ 
- [ ] ~observability: Improve ping logging~ [#9866](https://github.com/sourcegraph/sourcegraph/issues/9866) __0.5d__ 🐛
- [x] (release docker compose 3.15) merge and test deploy-sourcegraph-docker#93 [#9839](https://github.com/sourcegraph/sourcegraph/issues/9839) __0.5d__ 
- [ ] ~Alert when repository updates are failing~ [#9782](https://github.com/sourcegraph/sourcegraph/issues/9782) __0.5d__ 
- [ ] ~observability: Add monitoring to signal whether instance is underprovisioned or not~ [#7529](https://github.com/sourcegraph/sourcegraph/issues/7529) __1d__ 
- [ ] ~Setup new Grafana alerting on k8s.sgdev.org and sourcegraph.com to go to Slack~ [#7527](https://github.com/sourcegraph/sourcegraph/issues/7527) __1d__ 
- [ ] ~observability: Grafana: CSRF token invalid error~ [#6075](https://github.com/sourcegraph/sourcegraph/issues/6075) __1d__ 
- [ ] ~observability: add kubernetes resource monitoring / unified set of container metrics across deployment types~ [#5547](https://github.com/sourcegraph/sourcegraph/issues/5547) __1.5d__ 
- [ ] Start releasing Docker Compose in-band [#10486](https://github.com/sourcegraph/sourcegraph/issues/10486) 
- [x] 3.15 Docker container shuts down after 5min (consistently) [#10187](https://github.com/sourcegraph/sourcegraph/issues/10187) 
- [ ] ~observability: Add monitoring for when zoekt indexing fails on repos~ [#8309](https://github.com/sourcegraph/sourcegraph/issues/8309) __0.5d__ 
- [ ] ~test bed for $CUSTOMER monorepo~ [#10106](https://github.com/sourcegraph/sourcegraph/issues/10106) __4d__ 
- [x] monitoring: generate solutions documentation from Go monitoring definitions [#10142](https://github.com/sourcegraph/sourcegraph/pull/10142) :shipit:
- [x] monitoring: add very narrowly targeted sharing of observables [#10139](https://github.com/sourcegraph/sourcegraph/pull/10139) :shipit:

@uwedeportivo: __14.50d__

- [ ] ~test bed for $CUSTOMER monorepo~ [#10106](https://github.com/sourcegraph/sourcegraph/issues/10106) __4d__ 
- [x] Use net/http/httptrace to trace HTTP client requests [#10007](https://github.com/sourcegraph/sourcegraph/issues/10007) __2d__ 
- [ ] Move e2e tests into regression test suite [#9814](https://github.com/sourcegraph/sourcegraph/issues/9814) __4d__ 
- [x] Implement NetworkPolicy [#9726](https://github.com/sourcegraph/sourcegraph/issues/9726) __2d__ 
- [x] deploy-sourcegraph: Separate manifests for non-admin users [#9723](https://github.com/sourcegraph/sourcegraph/issues/9723) __1d__ 
- [ ] deploy-sourcegraph: include k8s secret that's mounted into gitserver [#9722](https://github.com/sourcegraph/sourcegraph/issues/9722) __2d__ 
- [x] Update docs for how to upgrade sourcegraph.com [#9607](https://github.com/sourcegraph/sourcegraph/issues/9607) __1.5d__ 
- [x] Merge k8s docs into main docs site [#7285](https://github.com/sourcegraph/sourcegraph/issues/7285) __2d__ 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
### End of week update

This week we did the following:

- Uwe:
     - Requests we've heard from admins about Kubernetes a lot ([NetworkPolicies](https://github.com/sourcegraph/sourcegraph/issues/9726), [setting up Sourcegraph when installer does not have cluster admin](https://github.com/sourcegraph/sourcegraph/issues/9723), 
     - Internal infrastructure: [docs for updating Sourcegraph.com](https://github.com/sourcegraph/sourcegraph/issues/9607), upgrading k8s.sgdev.org with Dave, acting as our release captain, resolving e2e test issues, testing features.
    - [Migrating all Kubernetes docs to docs.sourcegraph.com](https://github.com/sourcegraph/sourcegraph/issues/7285)
- Dave:
   - Helping/listening in on customer upgrades
   - Moving Sourcegraph.com site configuration to file
   - Learning our infrastructure, upgrading k8s.sgdev.org with Uwe
   - Now getting started on: [making it possible to load alerting config from disk](https://github.com/sourcegraph/sourcegraph/issues/10641)
- Robert:
    - Finished onboarding
    - Deployed Sourcegraph to EKS and updated docs to reflect how to today
    - Discussing implementation for [notifying us of unexpected AWS/GCP resource expenses](https://github.com/sourcegraph/sourcegraph/issues/10116)
    - Started work on [including recently-fired alerts in the report-a-bug-page](https://github.com/sourcegraph/sourcegraph/issues/7657), with draft PR up.
- Geoffrey:
    - Resolved k8s.sgdev.org rollout pipeline issues
    - Initial prototype of RFC 141 complete, reviewed and discussed next steps with Stephen
    - [Prototype ready for deployment to k8s.sgdev.org](https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/1531), just working on keeping continuous deployment in place via [a script Stephen wrote](https://github.com/slimsag/update-docker-tags)
- Dax:
    - Helping/listening in on customer upgrades
    - Learning Sourcegraph codebase, draft PR up for [notifying users when Sourcegraph is out of date](https://github.com/sourcegraph/sourcegraph/issues/9708)
- Stephen:
     - Currently writing extensive documentation for how we do monitoring
     - 30% of my time spent supporting customers
     - 80% of my time spent reviewing PRs and answering questions or helping: Dax, Robert, Geoffrey, Eric, Dan/Tomas, Rijnard, Uwe
      - 15% of my time spent contributing actual code/docs.
      - If you've noticed that adds up to 125%, that number is wrong it's probably about 150%. I am aggressively pushing things off my plate to others.
