### ISSUE TITLE
improve our issue tracking process

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#10082]
- [ ] create a prototype of an improved issue tracker
- [ ] review with relevant parties
- [ ] decide whether to scrap or update and move to
