### ISSUE TITLE
Tracking issue: OKR > Distribution > Admin Experience

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#10159]
### Work

@Unassigned

- [ ] Tracking issue: OKR > Distribution > Admin Experience [#10159](https://github.com/sourcegraph/sourcegraph/issues/10159) 

@beyang

- [ ] k8s: Deploy jaeger-agent as a Daemonset instead of sidecar container [#10052](https://github.com/sourcegraph/sourcegraph/issues/10052) 
- [ ] Docs: Kubernetes installation instructions should indicate how much cpu/memory is needed [#10008](https://github.com/sourcegraph/sourcegraph/issues/10008) 
- [ ] docs: Clarify that Sourcegraph schema migrations require postgres user to be admin, include advice on how to workaround [#5087](https://github.com/sourcegraph/sourcegraph/issues/5087) 

@ggilmore: __10.00d__

- [ ] spike: investigate dhall for deploy-sourcegraph  [#10145](https://github.com/sourcegraph/sourcegraph/issues/10145) __3d__ 🕵️
- [ ] spike: investigate cue for deploy-sourcegraph  [#10143](https://github.com/sourcegraph/sourcegraph/issues/10143) __3d__ 🕵️
- [ ] Create scaling recommendation guide [#10102](https://github.com/sourcegraph/sourcegraph/issues/10102) __2d__ 
- [ ] RFC 141: Generate manifests, rather than directly editing deploy-sourcegraph [#10100](https://github.com/sourcegraph/sourcegraph/issues/10100) 
- [ ] Issues with Docker Compose on AWS installation docs [#9829](https://github.com/sourcegraph/sourcegraph/issues/9829) __1d__ 
- [ ] Set ephemeral storage resource requests and limits in deploy-sourcegraph [#9604](https://github.com/sourcegraph/sourcegraph/issues/9604) __1d__ 

@slimsag

- [ ] Grafana: add metric for open file descriptors and alert when approaching fd limit [#10009](https://github.com/sourcegraph/sourcegraph/issues/10009) 
- [ ] monitoring for container restarts [#9793](https://github.com/sourcegraph/sourcegraph/issues/9793) 
- [ ] monitoring for containers being down [#9792](https://github.com/sourcegraph/sourcegraph/issues/9792) 
- [ ] monitoring for CPU and memory usage [#9791](https://github.com/sourcegraph/sourcegraph/issues/9791) 
- [ ] monitoring: generate solutions documentation from Go monitoring definitions [#10142](https://github.com/sourcegraph/sourcegraph/pull/10142) :shipit:
- [x] monitoring: add very narrowly targeted sharing of observables [#10139](https://github.com/sourcegraph/sourcegraph/pull/10139) :shipit:

@uwedeportivo: __7.00d__

- [ ] Use net/http/httptrace to trace HTTP client requests [#10007](https://github.com/sourcegraph/sourcegraph/issues/10007) __2d__ 
- [ ] Implement NetworkPolicy [#9726](https://github.com/sourcegraph/sourcegraph/issues/9726) __2d__ 
- [ ] deploy-sourcegraph: Separate manifests for non-admin users [#9723](https://github.com/sourcegraph/sourcegraph/issues/9723) __1d__ 
- [ ] Merge k8s docs into main docs site [#7285](https://github.com/sourcegraph/sourcegraph/issues/7285) __2d__ 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
