### ISSUE TITLE
Tracking Issue: Long tail of monitoring metric improvements

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10164]
Tracking issue for the long-tail of monitoring metrics improvements.

@bobheadxi: __2.00d__

- [x] monitoring for CPU and memory usage in Kubernetes [#9791](https://github.com/sourcegraph/sourcegraph/issues/9791) __2d__ 

@daxmc99: __0.50d__

- [x] Add monitoring for syntax highlighting vs. gitserver perf [#10049](https://github.com/sourcegraph/sourcegraph/issues/10049) __0.5d__ 

@slimsag: __9.50d__

- [ ] Grafana: add metric for open file descriptors and alert when approaching fd limit [#10009](https://github.com/sourcegraph/sourcegraph/issues/10009) 
- [ ] Disk space of all containers is not monitored [#9919](https://github.com/sourcegraph/sourcegraph/issues/9919) __0.5d__ 
- [ ] Missing monitoring to signal if requests are not hitting search index [#9838](https://github.com/sourcegraph/sourcegraph/issues/9838) __0.5d__ 
- [ ] Alert if the number of repositories not cloned is high [#9837](https://github.com/sourcegraph/sourcegraph/issues/9837) __0.5d__ 
- [ ] observability: src_graphql_field_seconds histogram sometimes produces NaN values [#9834](https://github.com/sourcegraph/sourcegraph/issues/9834) __1d__ 🐛
- [ ] Unindexed search archive cache is not monitored [#9796](https://github.com/sourcegraph/sourcegraph/issues/9796) __0.5d__ 
- [ ] Alert admins if containers are crashing/restarting [#9793](https://github.com/sourcegraph/sourcegraph/issues/9793) 
- [ ] Alert if containers are entirely down/missing [#9792](https://github.com/sourcegraph/sourcegraph/issues/9792) 
- [ ] If configuration becomes invalid for any reason, no alert fires for all repositories being removed [#9790](https://github.com/sourcegraph/sourcegraph/issues/9790) __0.5d__ 
- [ ] Missing monitoring to notify admins of mass recloning events [#9789](https://github.com/sourcegraph/sourcegraph/issues/9789) __0.5d__ 
- [ ] observability: gitserver: monitor command execution latency [#9788](https://github.com/sourcegraph/sourcegraph/issues/9788) __0.5d__ 
- [ ] Frontend dashboard: "non-200 indexed search responses every 5m" should be by (category,code) [#9744](https://github.com/sourcegraph/sourcegraph/issues/9744) __0.5d__ 🐛
- [x] Expose # of code host API requests in Grafana Dashboards [#8581](https://github.com/sourcegraph/sourcegraph/issues/8581) __0.5d__ 
- [x] Ensure defined Grafana alerts do not disappear without data [#7623](https://github.com/sourcegraph/sourcegraph/issues/7623) __0.5d__ 
- [x] Determine missing alerts between alertmanager and grafana [#7528](https://github.com/sourcegraph/sourcegraph/issues/7528) __0.5d__ 
- [ ] Identify further inter-service communication metrics missing from new Grafana dashboards + alerts [#7525](https://github.com/sourcegraph/sourcegraph/issues/7525) __1d__ 
- [x] Identify further service-specific metrics missing from new Grafana dashboards + alerts [#7524](https://github.com/sourcegraph/sourcegraph/issues/7524) __1d__ 
- [ ] Missing monitoring for when gitserver fetches/execs/clones are slow [#6675](https://github.com/sourcegraph/sourcegraph/issues/6675) __0.5d__ 
- [ ] monitoring for how many repos are indexed/nonindexed missing [#4197](https://github.com/sourcegraph/sourcegraph/issues/4197) __0.5d__ 
- [ ] alerting for when external service connections are failing [#11595](https://github.com/sourcegraph/sourcegraph/issues/11595) 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by slimsag** [comment]
Closing in favor of individual issues which better communicate priority of each.
