### ISSUE TITLE
Tracking Issue: RFC 136 MVP: Navigating version contexts

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#10197]
[RFC 136](https://docs.google.com/document/d/1-Hn3bSVmwZ9iY0nfztXMoDfzWMdOHYTKrhK2F5ZJZI8/edit#): Navigating version contexts

I don't think we can hit 3.16. We can either release in 3.17, or do a special build during the 3.17 build cycle. This plan targets what our target customer wants:

@asdine

- [x] Version context configuration and graphql integration [#10194](https://github.com/sourcegraph/sourcegraph/issues/10194) 

@attfarhan: __4.00d__

- [x] Implement RFC 150: Version contexts UI and frontend work [#10196](https://github.com/sourcegraph/sourcegraph/issues/10196) __4d__ 

@efritz

- [x] basic-code-intel uses version contexts [#10195](https://github.com/sourcegraph/sourcegraph/issues/10195) 

@keegancsmith: __10.00d__

- [x] Index multiple (non-master) branches [#6728](https://github.com/sourcegraph/sourcegraph/issues/6728) __10d__ [👩](https://app.hubspot.com/contacts/2762526/company/554338610)

@rrhyne: __2.50d__

- [x] RFC 136: Version context design [#10518](https://github.com/sourcegraph/sourcegraph/issues/10518) __2d__ 
- [ ] RFC 136: Version context design testing [#10574](https://github.com/sourcegraph/sourcegraph/issues/10574) __0.5d__

**Comment by keegancsmith** [comment]
> Keegan: Index multiple (non-master) branches #6728

This has potential to be worked on by more than one person. In my mind this is the main issue on the critical path, the other parts should be functioning (but maybe not polished) sooner.

**Comment by tsenart** [comment]
@keegancsmith: Added the tracking label so that the work section is managed automatically.

**Comment by keegancsmith** [comment]
I've rolled back the tracking issue usage since RFC-136 label is tracking work unrelated to the MVP.

**Comment by attfarhan** [comment]
Will the GraphQL integration work in https://github.com/sourcegraph/sourcegraph/issues/10194 also include updates to the APIs the webapp will use? For example, will it update the search API to accept a `versionContext` parameter?

**Comment by nicksnyder** [comment]
What is the long tail of work here? Even if there are parts that can't get done until 3.17, I want to make it clear that we should prioritize finishing the other parts sooner rather than later.

**Comment by keegancsmith** [comment]
> Will the GraphQL integration work in #10194 also include updates to the APIs the webapp will use? For example, will it update the search API to accept a `versionContext` parameter?

Yes. I'll prioritise sending out a MVP graphql schema change.

> What is the long tail of work here? Even if there are parts that can't get done until 3.17, I want to make it clear that we should prioritize finishing the other parts sooner rather than later.

I would regard the MVP as very functional, and would rely on feedback were it falls short. My best guess on the feedback after the MVP:
- Users want to set contexts (not just admins)
- More expressive ways to specify contexts (purposely static at the moment). EG regex or search query.
- version contexts in search queries. eg doing set operations on version contexts.

**Comment by nicksnyder** [comment]
Will the MVP be done in the 3.16 cycle?

**Comment by keegancsmith** [comment]
> Will the MVP be done in the 3.16 cycle?

Unlikely it will all be ready, which is why we are targeting 3.17. The part I am most worried about is indexing multiple branches as mentioned above in https://github.com/sourcegraph/sourcegraph/issues/10197#issuecomment-619882252

**Comment by rvantonder** [comment]
https://github.com/sourcegraph/sourcegraph/issues/10111 was mentioned by this issue but got dropped. I assume it is missing the RFC-136-MVP label.

**Comment by rvantonder** [comment]
https://github.com/sourcegraph/sourcegraph/issues/9712 Was also previously mentioned and dropped. Intentional? Seems like it has important context for what we're working towards with the MVP.

**Comment by keegancsmith** [comment]
Both of those issues being descoped was intentional. They were accidentally mentioned when we switched to using the tracking bot. See the original issue description in the edit history. I can't remember were we discussed this, likely the RFC as a comment. The reason is those issues are independent of version contexts (although are useful in general). So we are not bundling it in with the MVP. See the RFC or #10194's PR for how an admin will specify a version context. It doesn't depend on our search syntax, its a static list of exact repo names and refs.

**Comment by rvantonder** [comment]
Caught up with Keegan over a call. Summary is that the query syntax solution proposed in #9712 (and related notes in #10111), while generally useful, is not on the critical path to the MVP. It's sensible that I dedicate my efforts to critical parts of the MVP where possible (cc @dan, just want to make explicit that `or` syntax for repos will then not be a priority for the MVP and will happen at some other time in the future, unless someone says otherwise). 

So, my next TODO will be catching up with the MVP work and scope here (mostly Farhan's RFC and backend work), and Keegan pointed to subtasks part of https://github.com/sourcegraph/sourcegraph/issues/6728#issuecomment-617248959 that I could potentially help with.

**Comment by dadlerj** [comment]
FYI my handle is @dadlerj :)

**Comment by keegancsmith** [comment]
The MVP shipped. Closing this out :)
