### ISSUE TITLE
src-cli 3.16 meta

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#10283]
This issue is here so that I can track src-cli issues planned for 3.17:

- [x] https://github.com/sourcegraph/src-cli/issues/189 (No estimate, already completed)
- [x] https://github.com/sourcegraph/src-cli/issues/190 (1d)
- [x] https://github.com/sourcegraph/src-cli/issues/156 (0.5d)
- [x] https://github.com/sourcegraph/src-cli/issues/187 (0.5d)
- [x] https://github.com/sourcegraph/src-cli/issues/202 (0.5d)
- [x] Release new version of sc-cli

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by ryanslade** [comment]
New version of `src-cli` released: https://github.com/sourcegraph/src-cli/releases/tag/3.15
