### ISSUE TITLE
Extensions engineering plan

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#10556]
This is a tracking issue with a plan to implement our extension goals, extracted from our conversations. We would take issues out of this roadmap each iteration to work towards our goals.

- [ ] **1. Improving the platform**
  _These are requirements to ship code insights to customers (without a feature flag)._
  - [ ] Overhaul the extension API architecture ([RFC 155](https://docs.google.com/document/d/1ikrUNVe3YVbR-JpegxhjrFdmRkTGzTLcOMkKHnOyjuE/edit))
    - [ ] Solve flakiness like #10558
  - [ ] Debugging
    - [ ] Logging system in webapp #9944
    - [ ] Logging API in extension API #9694
  - [ ] Registry improvements
    - [ ] Performance #10554
    - [ ] Easily enable extensions for all users #1874
    - [x] Clarity _(to be specified)_
  - [ ] Measure performance of extensions: End-to-end instrumentation of e.g. time to first hover, e.g. through OpenTracing/OpenTelemetry on the client.  (old issue: #1423)
  - [ ] Add metrics to track extension usage (which extensions are enabled)
  - [ ] Solve UX pains, e.g.:
    - [x] Command palette empty state #1841
    - [ ] Clicking action item toggles has long-delayed UI feedback #10555
    - [ ] Better empty states in general, e.g. for code insights
    - [ ] Different states for the registry when you come from different sources (e.g. filter to insight extensions when linked from insights empty state)
- [ ] **2. Building great content on top of the platform**: with code insights, but also generally great extensions
  - [x] Do [RFC 148: Extension Feature Effort](https://docs.google.com/document/d/1VmvYjhNOV7_Yga7vF234ug2rg6n8IPfXWwyIaOt8u5c/edit)
- [ ] **3. Improving the platform as a 3rd-party developer platform**
  - To be specified.
  - Ideas: Better docs, online “API explorer” UX

**Comment by jeanduplessis** [comment]
@Joelkw can you give me a read on the accuracy of this plan and whether it aligns with the goals we've updated recently? I.e. should we use this as a roadmap for the extensions work?

**Comment by Joelkw** [comment]
@jeanduplessis thanks for asking – hadn't come across this yet and at a glance it looks inaccurate – some of this is now down, not sure some of this is still relevant, etc.  (For time's sake I had to stop going through the web backlog and just move on what I'd found so far, but please do tag me into anything pre August/July 2020 that I might not have seen that your'e wondering about!) 

Since we don't really use this system anymore, I've gone through these issues and updated/commented/moved the ones that still seem relevant. I'm closing this "index of issues" and will continue on those individual issues.
