### ISSUE TITLE
Campaigns: 3.17 Tracking issue

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#10630]
### Status

This tracking issue is being prepared.

### Availability

Period is from **May 21st** to **June 18th**. Please write the days you won't be working and the number of working days for the period.

- @mrnugget: ~19 days (1st June & 11th June are public holidays, plus some half-days of childcare duties)
- @ryanslade: 20 days (16th June is a ZA holiday)
- @eseliger: ~20 days

### Workload

@LawnGnome: __2.00d__

- [x] Trying to publish a failed changeset again is noop [#10795](https://github.com/sourcegraph/sourcegraph/issues/10795) __0.5d__ 🐛
- [x] Publishing a campaign with failed jobs fails [#10797](https://github.com/sourcegraph/sourcegraph/issues/10797) __0.5d__ 🐛
- [x] Hard reload required after enabling campaigns feature flag with no indication [#10715](https://github.com/sourcegraph/sourcegraph/issues/10715) __1d__ 🧶
- [ ] ~Cache diffstat for external changesets~ [#11075](https://github.com/sourcegraph/sourcegraph/issues/11075) __1.5d__ 
- [ ] ~Clearer error message for improper JSON escape sequence in `src actions scope-query`~ [#10541](https://github.com/sourcegraph/sourcegraph/issues/10541) __0.5d__ 🐛

@eseliger: __10.00d__

- [ ] ~WIP: Frontend: New campaigns flow~ [#10986](https://github.com/sourcegraph/sourcegraph/issues/10986) __3d__ 
- [x] Frontend: Remove the concept of a top-level "draft campaign" [#10983](https://github.com/sourcegraph/sourcegraph/issues/10983) __2d__ 
- [x] Frontend: Repository permissions for campaigns [#10982](https://github.com/sourcegraph/sourcegraph/issues/10982) __1.5d__ 
- [ ] ~Show diff on merged changesets~ [#10959](https://github.com/sourcegraph/sourcegraph/issues/10959) __2d__ 
- [x] Frontend: permission levels for campaigns [#10817](https://github.com/sourcegraph/sourcegraph/issues/10817) __1.5d__ 🛠️
- [x] Campaign patches with binaries don't apply [#10815](https://github.com/sourcegraph/sourcegraph/issues/10815) __0.5d__ 🐛
- [x] Burndown chart is off [#10802](https://github.com/sourcegraph/sourcegraph/issues/10802) __0.5d__ 🐛
- [x] worries about diff highlighting [#10616](https://github.com/sourcegraph/sourcegraph/issues/10616) __2d__ 🧶
- [x] Branch field is cleared in edit mode for campaigns [#10266](https://github.com/sourcegraph/sourcegraph/issues/10266) __0.5d__ 🐛
- [x] A repository being removed from Sourcegraph breaks campaigns [#9641](https://github.com/sourcegraph/sourcegraph/issues/9641) 🐛
- [x] "Close" and "Delete" popups show "open changesets" even though they are merged [#9393](https://github.com/sourcegraph/sourcegraph/issues/9393) __0.5d__ 🐛
- [x] Campaigns: Add backlink to Sourcegraph in PR description [#9061](https://github.com/sourcegraph/sourcegraph/issues/9061) __0.5d__ 
- [x] Changeset.nextSyncAt not populated when changeset is queried by ID [#11227](https://github.com/sourcegraph/sourcegraph/issues/11227) __0.5d__ 🐛

@mrnugget: __9.00d__

- [ ] ~WIP: Backend: New campaign flow~ [#10985](https://github.com/sourcegraph/sourcegraph/issues/10985) __10d__ 
- [ ] ~WIP: Remove hard distinction between manual and patchset campaigns~ [#10984](https://github.com/sourcegraph/sourcegraph/issues/10984) __2d__ 
- [x] Backend: Remove the concept of a top-level "draft campaign". [#10953](https://github.com/sourcegraph/sourcegraph/issues/10953) __2d__ 🛠️
- [ ] ~WIP: Perform code host interactions with user accounts~ [#10813](https://github.com/sourcegraph/sourcegraph/issues/10813) 🛠️
- [x] Backend: Repository permissions for campaigns [#10809](https://github.com/sourcegraph/sourcegraph/issues/10809) __5d__ 🛠️
- [x] Backend: permission levels for campaigns [#10808](https://github.com/sourcegraph/sourcegraph/issues/10808) __2d__ 🛠️
- [ ] ~Replace "automation" feature flag with "campaigns" toggle and remove configuration flags~ [#10713](https://github.com/sourcegraph/sourcegraph/issues/10713) __1d__ 🛠️

@ryanslade: __15.00d__

- [x] Repo-updater can fall into infinite retry loop [#10798](https://github.com/sourcegraph/sourcegraph/issues/10798) __0.5d__ 🐛
- [x] Branch names are not validated [#10718](https://github.com/sourcegraph/sourcegraph/issues/10718) __0.5d__ 🐛
- [x] When changeset creation fails spinner does not disappear [#10717](https://github.com/sourcegraph/sourcegraph/issues/10717) __1d__ 🐛
- [x] Synchronously try upserting webhooks for BBS [#10635](https://github.com/sourcegraph/sourcegraph/issues/10635) __1d__ 🧶
- [x] Campaigns show "Revision not found" error when merged changeset's branch is deleted upstream [#10542](https://github.com/sourcegraph/sourcegraph/issues/10542) __2d__ 🐛
- [x] Reduce usage of raw string for external service kind [#10296](https://github.com/sourcegraph/sourcegraph/issues/10296) __1d__ 🧶
- [x] src-cli 3.16 meta [#10283](https://github.com/sourcegraph/sourcegraph/issues/10283) __2.5d__ 
- [x] Add configuration option to disable automatic creation of Bitbucket Server webhooks [#10217](https://github.com/sourcegraph/sourcegraph/issues/10217) __1d__ 
- [x] Validate unique rate limit configuration [#10026](https://github.com/sourcegraph/sourcegraph/issues/10026) __0.5d__ 
- [x] Reduce coupling in campaign store tests [#10022](https://github.com/sourcegraph/sourcegraph/issues/10022) __1d__ 🧶
- [x] Use internal rate limiters for all source requests [#9953](https://github.com/sourcegraph/sourcegraph/issues/9953) __2d__ 
- [ ] `src actions exec` can cause frontend to be OOMKilled [#10540](https://github.com/sourcegraph/sourcegraph/issues/10540) __2d__ 🐛

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by mrnugget** [comment]
@LawnGnome when we were planning this iteration RFC157 was still a bit of a black box, so we were off with a few estimates. The end result is that @eseliger now has a few too many tickets and to be super cautious and avoid stress: could you take on 2 of his tickets?

- https://github.com/sourcegraph/sourcegraph/issues/10797
- https://github.com/sourcegraph/sourcegraph/issues/10715

Both are fairly straight forward and @eseliger can assist you and answer questions you have.

If you don't feel confident taking them on (which I'd totally understand, considering it's your first week), I'd also be able to help out and I bet @ryanslade is too.

**Comment by mrnugget** [comment]
@LawnGnome since #10607 is on your onboarding plan, @eseliger and I thought that https://github.com/sourcegraph/sourcegraph/issues/11075 might go hand in hand with that — if you run out of things to do :)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
