### ISSUE TITLE
Code intelligence: 3.17 tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#10687]
### Status

**Milestone Focus**: We are trying to increase adoption of precise code intelligence by implementing an auto-indexing strategy, improving the UI related to codeintel, and increasing performance of queries and index conversion, and expanding indexer support. We are improving stability of the precise code intel backend and ensuring it does not regress by implementing a set of integration tests. We are also expanding the code intel API surface with diagnostics, which is a critical part of code insights.

### Availability

Period is from **2020-05-20** to **2020-06-20**. Please write the days you won't be working and the number of working days for the period.

- Eric: 21d (off memorial day 5/25)
- Garo: 14d

### Workload

@efritz

- [x] Codeintel xrepo data is not updated properly [#11003](https://github.com/sourcegraph/sourcegraph/issues/11003) 🐛
- [x] Add basic support for LSIF diagnostics [#10838](https://github.com/sourcegraph/sourcegraph/issues/10838) 
- [x] Infinitely processing malignant uploads [#10755](https://github.com/sourcegraph/sourcegraph/issues/10755) 
- [x] LSIF plaintext hover support [#7099](https://github.com/sourcegraph/sourcegraph/issues/7099) 
- [x] Improve LSIF root boundaries [#8383](https://github.com/sourcegraph/sourcegraph/issues/8383) 
- [ ] Create docs page for codeintel showcase repos [#9609](https://github.com/sourcegraph/sourcegraph/issues/9609) `docs` 
- [ ] Code intelligence integration tests [#10832](https://github.com/sourcegraph/sourcegraph/issues/10832) 
- [x] Update worker transaction bookkeeping [#10831](https://github.com/sourcegraph/sourcegraph/issues/10831) 
- [x] Connection between bundle manager and worker is flaky [#10913](https://github.com/sourcegraph/sourcegraph/issues/10913) 🐛
- [x] Collapse precise-code-intel-api-server into frontend [#10873](https://github.com/sourcegraph/sourcegraph/issues/10873) 
- [x] Document LSIF data expectations [#9719](https://github.com/sourcegraph/sourcegraph/issues/9719) `docs` 
- [x] Automatic LSIF indexing [#10833](https://github.com/sourcegraph/sourcegraph/issues/10833) 
- [x] API for LSIF auto index records [#10834](https://github.com/sourcegraph/sourcegraph/issues/10834) 
- [x] UI for LSIF uploads (global scope) [#10835](https://github.com/sourcegraph/sourcegraph/issues/10835) 
- [x] UI for automatic LSIF indexing (repo scope) [#10836](https://github.com/sourcegraph/sourcegraph/issues/10836) 
- [x] UI for automatic LSIF indexing (global scope) [#10837](https://github.com/sourcegraph/sourcegraph/issues/10837) 
- [x] RFC 122: Integrate LSIF indexing into supportive Go and TypeScript repositories [#9288](https://github.com/sourcegraph/sourcegraph/issues/9288) 
- [x] Update and expand the code intelligence team roadmap [#9922](https://github.com/sourcegraph/sourcegraph/issues/9922) 🛠️
- [x] Bundle manager janitor: do not stop on first error [#11006](https://github.com/sourcegraph/sourcegraph/issues/11006) 
- [ ] ~TypeScript cross-repository go to definition broken with LSIF~ [#9952](https://github.com/sourcegraph/sourcegraph/issues/9952) 🐛

@gbrik

- [x] Write RFC for precise code intel mono repo support [#10087](https://github.com/sourcegraph/sourcegraph/issues/10087) `planning` 
- [ ] Prototype a new LSIF indexer for C++ based on clangd-indexer [#10175](https://github.com/sourcegraph/sourcegraph/issues/10175) `in progress` 
- [ ] ~Minor: Retry lsif index upload when clone is in progress~ [#9700](https://github.com/sourcegraph/sourcegraph/issues/9700) `in progress` 
- [ ] Index a super cool Go repo and its transitive dependencies [#9746](https://github.com/sourcegraph/sourcegraph/issues/9746) `blocked` 
- [x] Improve visual clarity and add CTAs re code intel [#10083](https://github.com/sourcegraph/sourcegraph/issues/10083) `planning` 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by efritz** [comment]
**Completed 2020-05-20/22**

- Collapsed api-server into frontend
- Prototyped auto-indexer

**Planned 2020-05-26/29**

- (Not working Monday)
- Get auto-indexer deployed into dotcom
- Continue to clean up api-server/frontend collision
- Look into supporting diagnostics

**Comment by gbrik** [comment]
### Week 0 Done 2020-05-18
- [x] doc updates before release
- [x] split & specced RFC 158
- [x] worked on mono indexing RFC

### Week 1 Planned 2020-05-25
- [ ] publish mono indexing RFC
- [ ] lsif cppppp

**Comment by efritz** [comment]
**Completed 2020-05-26/29**

- Have a running version of the auto-indexer in dot com (with limited functionality, bugs)
- Fixed network issue between bundle-manager/worker that was affecting dot-com (reported by private instance)
- Performance improvements

**Planned 2020-06-01/05**

- Add support for diagnostics
- Iron out bugs in auto-indexer as they appear
- Add UI page for index status

**Comment by gbrik** [comment]
### Week 1 Done 2020-05-25
- [x] iterated on incremental indexing RFC
- [x] worked on lsif cpp

### Week 2 Planned 2020-06-01
- [ ] fix outstanding seg faults in lsif cpp
- [ ] start work on RFC 158 implementation #10891

**Comment by efritz** [comment]
**Completed 2020-06-01/05**

- Drafted diagnostic support
- Auto-indexed ~150 repositories w/o intervention
- Drafted UI changes

**Planned 2020-06-08-12**

- Land https://github.com/sourcegraph/sourcegraph/pull/11320, https://github.com/sourcegraph/sourcegraph/pull/11319, and https://github.com/sourcegraph/sourcegraph/pull/11214
- Tackle remaining bug tickets
- Draft blog post about improvements and new features

**Comment by gbrik** [comment]
**Completed 2020-06-01/05**
- [x] iterated on lsif-cpp
- [x] started working on RFC 158 implementation
- [x] hiring brainstorming

**Planned 2020-06-08-12**

- [ ] finish lsif-cpp
- [ ] finish RFC 158 tooltips
- [ ] start RFC 158 find-refs pane

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
End of week! See our nest tracking issue at https://github.com/sourcegraph/sourcegraph/issues/11412.
