### ISSUE TITLE
Broken e2e tests on 3.16 branch

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#10709]
Some e2e tests are broken on the 3.16 release branch, preventing us from creating the release candidate: https://buildkite.com/sourcegraph/e2e/builds/9888#93153ac7-4aed-437c-bce2-b004dc3935d8/699-1839

The broken tests are:

- [x] External services AWS CodeCommit: `TimeoutError: waiting for function failed: timeout 30000ms exceeded` (screenshot shows a 500 internal server error) @unknwon Fixed in #10761 and #10762
- [x] External services Bitbucket Server: `TimeoutError: waiting for function failed: timeout 30000ms exceeded` (screenshot shows a 500 internal server error) @unknwon Fixed in #10761 and #10762
- [x] Visual tests Search visibility:private|public `Expected: ArrayContaining ["github.com/sourcegraph/e2e-test-private-repository"] Received: ["", ""]` )(private repo does show up in the screenshot) @lguychard fixed in #10716 
- [x] Repository component file tree responds to keyboard shortcuts: `Error: Node is either not visible or not an HTMLElement` @lguychard fixed in #10716 
- [x] Repository component directory page shows a row for each file in the directory: `TimeoutError: waiting for selector ".tree-page__entries-directories" failed: timeout 30000ms exceeded` @lguychard fixed in #10716 
- [ ] ~~"before each" hook for "shows commit information on a row": `Error: Evaluation failed: TypeError: Failed to fetch`~~

**Comment by unknwon** [comment]
@lguychard I'll take a look at first three today. (added myself in the list)

**Comment by lguychard** [comment]
Pushed some fixes in https://github.com/sourcegraph/sourcegraph/pull/10716.

@unknwon I found along the way that `Visual tests Search visibility:private|public` failed due to a DOM issue, not due to a permissions issue. It is fixed in #10716.

So far I have not been able to reproduce the `"before each" hook for "shows commit information on a row"` failure locally. This is the before hook that fails:

```typescript
    beforeEach(async () => {
        if (driver) {
            // Clear local storage to reset sidebar selection (files or tabs) for each test
            await driver.page.evaluate(() => {
                localStorage.setItem('repo-rev-sidebar-last-tab', 'files')
            })

            await driver.resetUserSettings()
        }
    })
```

**Comment by lguychard** [comment]
@unknwon the logs seem to contain relevant errors to the AWS Codecommit & Bitbucket Server failures:

```
2020-05-15T10:57:46.412524423Z 10:57:46                          frontend \| t=2020-05-15T10:57:46+0000 lvl=eror msg="ui HTTP handler error response" method=GET request_uri=/aws/test/-/blob/README status_code=500 error="non-absolute commit ID: \"\"" error_id=BPU6Wf trace=#tracer-not-enabled
2020-05-15T10:58:22.440108321Z 10:58:22                          frontend \| t=2020-05-15T10:58:22+0000 lvl=eror msg="ui HTTP handler error response" method=GET request_uri=/bbs/SOURCEGRAPH/jsonrpc2/-/blob/.travis.yml status_code=500 error="non-absolute commit ID: \"\"" error_id=1NuO4c trace=#tracer-not-enabled
```

**Comment by lguychard** [comment]
We've got a new one in https://buildkite.com/sourcegraph/e2e/builds/9889#4e00a964-c177-4652-802b-e6652b1b8d0c:

`regexp toggle appears and updates patternType query parameter when clicked `

**Comment by lguychard** [comment]
@unknwon @tsenart the last two failing tests here are AWS CodeCommit & Bitbucket Server. https://buildkite.com/sourcegraph/e2e/builds/9890#9907d7e0-0255-4d8d-aa2b-ebbcda9a496b

There's actually a real bug / race condition being hit here: when navigating to a blob page very shortly after adding repositories, even if the repository is already listed on the "repository status" page, the backend may return 500 `non-absolute commit ID: \"\"` instead of a 200 queued for cloning / clone in progress response. Once the repo starts cloning, this goes away.

**Comment by unknwon** [comment]
> There's actually a real bug / race condition being hit here: when navigating to a blob page very shortly after adding repositories, even if the repository is already listed on the "repository status" page, the backend may return 500 `non-absolute commit ID: \"\"` instead of a 200 queued for cloning / clone in progress response. Once the repo starts cloning, this goes away.

That's very helpful finding! Thanks, I have been trying to reproduce this.

**Comment by lguychard** [comment]
I have (unreliably, 2/10) reproduced it in local runs.

**Comment by unknwon** [comment]
@uwedeportivo and I found the root cause of 500 for AWS CodeCommit and Bitbucket Server, will send out a PR to fix this tomorrow.

**Comment by unknwon** [comment]
Fixed all e2e tests, closing now.
