### ISSUE TITLE
Replace "automation" feature flag with "campaigns" toggle and remove configuration flags

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#10713]
Extracted from [RFC 157](https://docs.google.com/document/d/1-Ed6s3yiB-pmL7Up8H6nMlUhgmLn5BVu34Zpvf-_YNo/edit#).

### Tasks

- [ ] The `experimentalFeatures: {automation: "enabled"}` flag needs to be removed.
- [ ] New site-config property: `campaigns.enabled: true|false`.
- [ ] Add "Disable campaigns" quick action in config editor
- [ ] Make sure to disable on dotcom

If `campaigns.enabled == false`:

- [ ] Campaigns are not visible in UI
- [ ]  Every campaigns resolver needs to check for the flag (see `allowReadAccess` check right now) and return error if campaigns are disabled.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
@sourcegraph/campaigns I promised to write up a little state-of-campaigns-feature-flag thing, so here it goes:

Before this ticket (before merging: https://github.com/sourcegraph/sourcegraph/pull/11621)

- Campaigns are marked as a beta feature
- Campaigns are not available on Sourcegraph.com
- Campaigns are **not enabled by default**
- Campaigns can be enabled by using the `"experimentalFeatures": { "automation": "enabled" }}` site config setting
- Once enabled **only site-admins can create and view campaigns** (read/write access)
- Read access for non-site-admins can be enabled by setting the `automation.readAccess.enabled` (old name) or the `campaigns.readAccess` site config setting

After this ticket is fixed by merging https://github.com/sourcegraph/sourcegraph/pull/11621:

- Campaigns are marked as a beta feature
- Campaigns are not available on Sourcegraph.com
- Campaigns are **enabled by default**
- Campaigns can be disabled by using the `"campaigns.enabled"` site config setting
- Once enabled **site-admins can create and view campaigns** (read/write access)
- Once enabled **non-site-admins can view campaigns** (read access)

---

I think we should go one step further in #11621 and give **non-site-admins read/write access**. The reason why we didn't plan to do this in _this ticket here_ or in #11621 was that we didn't have repository permissions in place. Now that we have had repository permissions for two releases, I think we should simplify this and commit to what's described in https://docs.sourcegraph.com/user/campaigns/managing_access — which is **wrong** right now:

> Any person with a user account can create a campaign.

That's only the case if we merge #11621 and give non-site-admins write access.
