### ISSUE TITLE
RFC 157 Tracking Issue

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#10711]
### Status

[RFC 157: Campaigns authorization model](https://docs.google.com/document/d/1-Ed6s3yiB-pmL7Up8H6nMlUhgmLn5BVu34Zpvf-_YNo/edit#) is in preview mode and still being worked on.

We're already creating tickets and collecting them here.

### Work

@mrnugget

- [ ] Permission levels for campaigns [#10808](https://github.com/sourcegraph/sourcegraph/issues/10808) 🛠️
- [ ] Repository permissions for campaigns [#10809](https://github.com/sourcegraph/sourcegraph/issues/10809) 🛠️

@ryanslade: __1.00d__

- [ ] Replace "automation" feature flag with "campaigns" toggle and remove configuration flags [#10713](https://github.com/sourcegraph/sourcegraph/issues/10713) __1d__ 🛠️

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
