### ISSUE TITLE
Core Services: 3.17 Tracking issue

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#10786]
### Status

This tracking issue is being worked on.

### Availability

Period is from 21st May to 20th of June. Please write the days you won't be working and the number of working days for the period.

- @keegancsmith 
- @tsenart: **10d**
- @unknwon: **22d**

### Workload

@bobheadxi: __0.50d__

- [x] `src config` commands fail [#10419](https://github.com/sourcegraph/sourcegraph/issues/10419) __0.5d__ 🐛

@keegancsmith

- [x] errors seen in indexed-search on bigdata cluster with 250k repos [#11200](https://github.com/sourcegraph/sourcegraph/issues/11200) 
- [ ] ~Index multiple (non-master) branches~ [#6728](https://github.com/sourcegraph/sourcegraph/issues/6728) __10d__ [👩](https://app.hubspot.com/contacts/2762526/company/554338610)

@ryanslade: __5.50d__

- [x] Download raw file fails on large repos [#10466](https://github.com/sourcegraph/sourcegraph/issues/10466) __1d__ 🐛
- [x] Reduce usage of raw string for external service kind [#10296](https://github.com/sourcegraph/sourcegraph/issues/10296) __1d__ 🧶
- [x] Validate unique rate limit configuration [#10026](https://github.com/sourcegraph/sourcegraph/issues/10026) __0.5d__ 
- [x] Use internal rate limiters for all source requests [#9953](https://github.com/sourcegraph/sourcegraph/issues/9953) __2d__ 
- [ ] RFC 132: Use rate limit data when scheduling changeset syncs [#9105](https://github.com/sourcegraph/sourcegraph/issues/9105) __1d__ 

@tsenart

- [x] No Git file history for binary files [#10999](https://github.com/sourcegraph/sourcegraph/issues/10999) 🐛
- [x] gitlab-org/gitlab ResolveRev errors with 504 Gateway Timeout on sourcegraph.com [#10960](https://github.com/sourcegraph/sourcegraph/issues/10960) 🐛
- [x] repo-updater: Use per HTTP request timeouts [#11105](https://github.com/sourcegraph/sourcegraph/pull/11105) :shipit:👩
- [x] repo-updater: Change Postgres isolation level to default [#10957](https://github.com/sourcegraph/sourcegraph/pull/10957) :shipit:
- [x] Add golangci-lint GitHub Action [#10858](https://github.com/sourcegraph/sourcegraph/pull/10858) :shipit:🧶

@unknwon: __16.00d__

- [x] Background permissions syncing should not rely on `ServiceID` to match authz provider [#11023](https://github.com/sourcegraph/sourcegraph/issues/11023) __4d__ 🐛
- [x] Background permission fetching causes repos from 2nd code host to be inaccessible [#11318](https://github.com/sourcegraph/sourcegraph/issues/11318) __1d__ 🐛
- [x] Detect GitHub 404 errors during background permissions syncing [#11007](https://github.com/sourcegraph/sourcegraph/issues/11007) __0.5d__ 
- [x] Update GraphQL mutation to support multi-level permissions [#10952](https://github.com/sourcegraph/sourcegraph/issues/10952) __0.5d__ 🐛
- [x] Ping investigation: Instances are offline [#10598](https://github.com/sourcegraph/sourcegraph/issues/10598) __1d__ 
- [x] License expired notice is not showing up for users [#10363](https://github.com/sourcegraph/sourcegraph/issues/10363) __1d__ 🐛
- [x] Ensure that we are tracking Go test coverage correctly [#10356](https://github.com/sourcegraph/sourcegraph/issues/10356) __2d__ 🛠️
- [x] Docs: How background permissions syncing works [#10190](https://github.com/sourcegraph/sourcegraph/issues/10190) __1d__ 
- [x] RFC 142: Migrate backend e2e test with unit tests [#10067](https://github.com/sourcegraph/sourcegraph/issues/10067) __4d__ 🛠️
- [x] authz: better heuristic of `NextSyncAt` by `PermsSyncer` [#9098](https://github.com/sourcegraph/sourcegraph/issues/9098) __1d__ 
- [ ] ~PoC: src-expose push based~ [#10045](https://github.com/sourcegraph/sourcegraph/issues/10045) __2d__ 🕵️

@uwedeportivo

- [x] repo-updater: make handleStatusMessages log entry shorter and more useful [#11203](https://github.com/sourcegraph/sourcegraph/issues/11203) 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by unknwon** [comment]
### Last week

- Some polish work to be ready for making background permissions syncing as the default method.
- Integrated rate limit into background permissions syncing. Waiting for review #10950.
- Fixed license expired notice is not showing to users. Waiting for review #10951.

### W20 Plan [2020-05-25]

- RFC 142: Migrate backend e2e test with unit tests.
- Turn on background permissions syncing by default.
- PoC: src-expose push based.
- Docs: How background permissions syncing works.

**Comment by ryanslade** [comment]
## Last Week

Focused on campaign related work, specifically around webhook syncing.

## This week

Will continue working on campaign work by finishing of webhook sync changes and then move onto work on src-cli

**Comment by unknwon** [comment]
### Last week

- Made our GraphQL APIs support multi-level permissions.
- Made background permissions syncing as the default.
- Added docs and links to background permissions syncing in UI.
- Finished PoC of cloning Git repo over WebSocket.

### W21 Plan [2020-06-01]

- Finish migrating/adding unit tests derived from backend e2e tests, also help restructure the code of #10362 and add tests.
- Detect GitHub 404 errors during background permissions syncing.
- Ensure that we are tracking Go test coverage correctly.
- Remove dead code in the usage stats and db package.

**Comment by ryanslade** [comment]
### Last Week

* Added a progress bar to `src-cli` as well as a few minor cleanups
* Removed Bitbucket webhook syncing

### This week

* Finish off `src-cli` issues
* Fix infinite retry bug: https://github.com/sourcegraph/sourcegraph/issues/10798
* Finally get around to finishing off some dangling rate limiter issues

**Comment by unknwon** [comment]
### Last week

- Finished migrating applicable backend e2e tests to unit tests.
- Finished detecting GitHub 404 errors during background permissions syncing.
- Removed dead code in the usage stats and db package.
- Investigated `-coverpkg` option to increase our Go test coverage but it took 16m (vs 2m) to finish and only increased 3%. #11332

### W22 Plan [2020-06-08]

- Fix background permission fetching causes repos from 2nd code host to be inaccessible.
- Fix background permissions syncing should not rely on ServiceID to match authz provider.
- Start migrating backend e2e tests to integration tests.
- Start drafting RFC 178: Sourcegraph Cloud authorization model

**Comment by ryanslade** [comment]
### Last Week

* Fixed a few campaign bugs
* Made a bunch of changes to `src-cli`
* Sped up the raw archive file endpoint. It no longer needs to download an entire archive, just the requested file
* Debt task to remove uses of raw external service kinds and type strings

### This week

* Campaign OOM bug
* Rate limiter tasks

**Comment by tsenart** [comment]
> Start drafting RFC 178: Sourcegraph Cloud authorization model

@unknwon: Bear in mind that I asked @sqs to help with this since he did a great job thinking about this for campaigns recently. I'd wait for Quinn's initial proposal before, and you'd take it from there. This, however, was in the context of `RFC 162: Devolve the site admin role`. Did you have something slightly different in mind?

**Comment by unknwon** [comment]
> Bear in mind that I asked @sqs to help with this since he did a great job thinking about this for campaigns recently. I'd wait for Quinn's initial proposal, and you'd take it from there. This, however, was in the context of `RFC 162: Devolve the site admin role`. Did you have something slightly different in mind?

@tsenart: Thanks for the reminder! It would be more like my brain-dump of some rough ideas I've been keeping in my TODO (more technical, and site-admin is only one aspect for example), I can get busy enough with migrating e2e tests this week so no problem limit my initial effort on this RFC and wait for @sqs.

**Comment by unknwon** [comment]
### Last week

- Fixed background permission fetching causes repos from 2nd code host to be inaccessible.
- Fixed background permissions syncing should not rely on ServiceID to match authz provider.
- Finished e2e test prototype, started migrating browser-based e2e tests.

### W23 Plan [2020-06-15]

- Finish Spike: Use Postgres intarray to store permissions `object_ids`.
- RFC 142: Migrate backend e2e test with integration tests.

**Comment by ryanslade** [comment]
### Last week

* Clean up raw strings used for external service "kind" and "type"
* Add code to estimate rate limit "cost" for GitHub
* Move internal rate limiting into code host clients
* Simplify code after the above change

### W23 Plan

* Not working on Tuesday
* Focusing on a few performance related issues: https://github.com/sourcegraph/sourcegraph/issues/11466,
https://github.com/sourcegraph/sourcegraph/issues/10540, https://github.com/sourcegraph/sourcegraph/issues/11029
* Planning for next iteration

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
