### ISSUE TITLE
Distribution: 3.17 Tracking issue

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10788]
### Status

This tracking issue is being prepared.

### Workload

@Unassigned

- [ ] ~Add an option to force plaintext (no syntax highlighting) for debugging~ [#8433](https://github.com/sourcegraph/sourcegraph/issues/8433) __3d__ 

@bobheadxi: __19.00d__

- [x] Script to flag GCP and AWS resources that are unexpected / wasteful [#10116](https://github.com/sourcegraph/sourcegraph/issues/10116) __4d__ 
- [x] monitoring for CPU and memory usage in Kubernetes [#9791](https://github.com/sourcegraph/sourcegraph/issues/9791) __2d__ 
- [x] observability: Add monitoring to signal whether instance is underprovisioned or not [#7529](https://github.com/sourcegraph/sourcegraph/issues/7529) __4d__ 
- [x] Prevent admins from saving site config if it doesn't pass validation [#10883](https://github.com/sourcegraph/sourcegraph/issues/10883) __1d__ 
- [x] resources-report: add whitelist functionality for certain resources [#11005](https://github.com/sourcegraph/sourcegraph/issues/11005) __0.5d__ 
- [x] `src config` commands fail [#10419](https://github.com/sourcegraph/sourcegraph/issues/10419) __0.5d__ 🐛
- [x] Make conf.DeployType() differentiate between k8s and docker compose [#10399](https://github.com/sourcegraph/sourcegraph/issues/10399) __0.5d__ 🐛
- [x] observability: Alerting should be easily configured through a file or site configuration [#10641](https://github.com/sourcegraph/sourcegraph/issues/10641) __4d__ 
- [x] monitoring: container monitoring should exclude jaeger side-car containers [#11270](https://github.com/sourcegraph/sourcegraph/issues/11270) __0.5d__ 🐛
- [x] Automate creation of the Go third-party licenses CSV [#9973](https://github.com/sourcegraph/sourcegraph/issues/9973) __2d__ 
- [ ] ~Setup new Grafana alerting on k8s.sgdev.org and sourcegraph.com to go to Slack~ [#7527](https://github.com/sourcegraph/sourcegraph/issues/7527) __1d__ 

@davejrt

- [ ] ~move away from Prometheus alertmanager on Sourcegraph.com specifically~ [#5370](https://github.com/sourcegraph/sourcegraph/issues/5370) 

@daxmc99: __4.00d__

- [x] Warn users when Sourcegraph is out of date [#9708](https://github.com/sourcegraph/sourcegraph/issues/9708) __0.5d__ 
- [x] Cannot start on docker for windows (prometheus crashed) [#6577](https://github.com/sourcegraph/sourcegraph/issues/6577) 
- [x] Address golangci-lint complaints about monitoring/generator.go [#10915](https://github.com/sourcegraph/sourcegraph/issues/10915) __0.5d__ 
- [x] jaeger should be accessible via app proxy [#10491](https://github.com/sourcegraph/sourcegraph/issues/10491) __1d__ 
- [x] k8s: Deploy jaeger-agent as a Daemonset instead of sidecar container [#10052](https://github.com/sourcegraph/sourcegraph/issues/10052) __1d__ 
- [ ] ~observability: server/dev should always run latest grafana/prometheus~ [#9983](https://github.com/sourcegraph/sourcegraph/issues/9983) __1d__ 
- [ ] ~add terraform configuration for sourcegraph.com's infrastructure~ [#10455](https://github.com/sourcegraph/sourcegraph/issues/10455) __2d__ 
- [x] Add monitoring for syntax highlighting vs. gitserver perf [#10049](https://github.com/sourcegraph/sourcegraph/issues/10049) __0.5d__ 
- [ ] ~observability: Add ping performance stats to frontend dashboard~ [#9867](https://github.com/sourcegraph/sourcegraph/issues/9867) __0.5d__ 
- [x] observability: Improve ping logging [#9866](https://github.com/sourcegraph/sourcegraph/issues/9866) __0.5d__ 🐛

@ggilmore: __3.50d__

- [ ] ~Set ephemeral storage resource requests and limits in deploy-sourcegraph~ [#9604](https://github.com/sourcegraph/sourcegraph/issues/9604) __1d__ 👩
- [x] sourcegraph/security-issues [#68](https://github.com/sourcegraph/security-issues/issues/68) __0.5d__ 
- [ ] ~RFC 141: spike: Implementation Round 2: Dhall~ [#10936](https://github.com/sourcegraph/sourcegraph/issues/10936) __3d__ 🕵️
- [x] RFC 141: spike: Implementation Round 2: Cue [#10937](https://github.com/sourcegraph/sourcegraph/issues/10937) __3d__ 🕵️

@slimsag

- [ ] ~Deploy and release: Replace Renovate with GitHub Actions~ [#10011](https://github.com/sourcegraph/sourcegraph/issues/10011) __0.5d__ 
- [ ] ~verify "syntax highlighting sometimes doesn't work" is fixed on customer instance~ [#9557](https://github.com/sourcegraph/sourcegraph/issues/9557) __1d__ 🐛
- [ ] ~release: Docker Compose in-band~ [#10486](https://github.com/sourcegraph/sourcegraph/issues/10486) 
- [ ] ~Alert when repository updates are failing~ [#9782](https://github.com/sourcegraph/sourcegraph/issues/9782) __0.5d__ 
- [ ] ~RFC 128: Investigate and propose a solution for how the Slack /release command could be implemented behind the scenes~ [#9252](https://github.com/sourcegraph/sourcegraph/issues/9252) __3d__ 
- [ ] ~patch release process requires high context switching~ [#7148](https://github.com/sourcegraph/sourcegraph/issues/7148) 
- [ ] ~observability: improve/restructure admin documentation~ [#9773](https://github.com/sourcegraph/sourcegraph/issues/9773) __0.5d__ 

@uwedeportivo

- [ ] ~Move e2e tests into regression test suite~ [#9814](https://github.com/sourcegraph/sourcegraph/issues/9814) __2d__ 
- [ ] ~deploy-sourcegraph: include k8s secret that's mounted into gitserver~ [#9722](https://github.com/sourcegraph/sourcegraph/issues/9722) __1d__ 
- [ ] ~support $CUSTOMER~ [#10942](https://github.com/sourcegraph/sourcegraph/issues/10942) __8d__ 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by slimsag** [comment]
### End of week update

**Legend:**

- 💬 Discussion & advice
- 💪Progress
- 🎉Completed
- 🏃Working towards

**This week we did the following:**

- Uwe:
    - 🎉Released v3.16.0
    - 💪Working with Dave on $CUSTOMER GHE replica, great progress so far
    - 🏃**Now focused on:** $CUSTOMER replication
- Dave:
    - 💪Working with Uwe on $CUSTOMER GHE replica, great progress so far
    - 💬Researching on the side "switch away from site24x7 or find a way to make it more reliable #10742"
    - 🏃**Now focused on:** $CUSTOMER replication
- Robert:
    - 🎉Merged "siteAdmin: include alerts data in bug report page #10704"
    - 💪Working on "distribution: resources report #10784" and making excellent progress despite terrible GCP/AWS APIs
    - 💪Adding cadvisor (cpu/memory metrics) to kubernetes deployment sourcegraph/deploy-sourcegraph#707
    - 💪Looking into https://github.com/sourcegraph/security-issues/issues/68
    - 🏃**Now focused on:** above
- Geoffrey:
    - 💬Giving ghe.sgdev.org guidance to Uwe/Dave
    - 💬Guiding Robert on https://github.com/sourcegraph/security-issues/issues/68
    - 🎉Merged [PR to update-docker-tags](https://github.com/slimsag/update-docker-tags) so we can rollout RFC 141 prototype to k8s.sgdev.org
    - 💪Planned next steps for RFC 141: https://github.com/sourcegraph/sourcegraph/issues/10937 and https://github.com/sourcegraph/sourcegraph/issues/10936
    - 🏃**Now focused on:** Pulling trigger to deploy RFC 141 prototype on k8s.sgdev.org
- Dax:
    - 💪Continued work on "Warn users when Sourcegraph is out of date #9708" (turned out to be much more involved than Stephen initially thought, worked with Stephen, Joe, and others to find path forward)
    - 🎉Resolved "Cannot start on docker for windows (prometheus crashed) #6577"
    - 🏃**Now focused on:** Finishing up "Warn users when Sourcegraph is out of date #9708"
- Stephen:
    - 📆 We made a first draft of [our planned work for 3.17](https://github.com/sourcegraph/sourcegraph/issues/10788) (to be finalized by EOD Wed).
    - 💬Planning $CUSTOMER deployment and replica
    - 💬Joining $CUSTOMER2 deployment call and providing scaling advice
    - 💬Interviewed ~3 candidates
    - 💪Reviewing ~25 PRs and helping with ongoing-work for Robert, Dax, Dave, Uwe, Geoffrey, Rijnard, Eric, Keegan, Quinn.
    - 🎉Released Docker Compose v3.16.0
    - 🏃**Now focused on:** Finalizing 3.17 planning, planning RFC 141 w/Geoffrey, giving direction to Robert & Dax

cc @christinaforney @nicksnyder

**Comment by slimsag** [comment]
### End of week update

**This week we did the following:**

- Uwe & Dave:
    - 🎉Identified issues in (1) indexing (2) repository status page (3) postgres resource advice (4) indexer (fixed by Tomas, thank you!); see `bigdata` and `rfc151` issue label
    - 🎉New ghe-feeder tool and [handbook entry](https://about.sourcegraph.com/handbook/engineering/distribution/tools/ghe_feeder)
    - 💪$CUSTOMER GHE and Sourcegraph replicas set up. 178k of 210k repos cloned (1k+ orgs)
    - 💪Assisting $CUSTOMER in loading repos
    - 🏃**Now focused on:** above
- Robert:
    - 🎉 Resource reporting bot (see #distribution slack) #10784
    - 🎉 [Resource reporting handbook docs](https://about.sourcegraph.com/handbook/engineering/distribution/tools/resources_report)
    - 🎉[Improvements to resource reporting](https://github.com/sourcegraph/sourcegraph/pull/11061) ([working on more](https://github.com/sourcegraph/sourcegraph/pull/11107))
    - 🎉Cadvisor to Kubernetes deployments (container CPU/memory metrics) https://github.com/sourcegraph/deploy-sourcegraph/pull/707
    - 💪Mostly finished https://github.com/sourcegraph/security-issues/issues/68
    - 🔎Updating dot-com deployment: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/2642
    - 🔎Adding over/under-provisioning alerts/monitoring to all deployments: https://github.com/sourcegraph/sourcegraph/pull/11082
    - 🔎Fixed `src config`: https://github.com/sourcegraph/src-cli/pull/211
    - 🏃**Now focused on:** https://github.com/sourcegraph/sourcegraph/issues/10641 and https://github.com/sourcegraph/sourcegraph/issues/10399
- Geoffrey:
    - 🎉Set up automated builds and homebrew for [update-docker-tags](https://github.com/slimsag/update-docker-tags/pull/3).
    - 🎉Added [generation checks](https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/blob/release/.buildkite/check-generated-up-to-date.sh) to k8s.sgdev.org CI pipeline
    - 🎉Deployed RFC 141 prototype to k8s.sgdev.org for dogfooding/comparison
    - 💪Began work on "spike: RFC 141 Implementation Round 2: Cue #10937"
    - 🏃**Now focused on:** RFC 141
- Dax:
    - 🎉Exorcised golanci-lint errors #10949
    - 🎉Made Jaeger easier for customers to access (no more port-forwarding) #11002
    - 💬Investigated moving Jaeger to daemonset deployment model and discussed tradeoffs with team https://github.com/sourcegraph/sourcegraph/issues/10052
    - 🔎Waiting for Stephen's final review on "Warn users when Sourcegraph is out of date #9708"
    - 🏃**Now focused on:** server/dev should always run latest grafana/prometheus #9983
- Stephen (not working Mon/Tue):
    - 🎉 Finalized [our planned work for 3.17](https://github.com/sourcegraph/sourcegraph/issues/10788).
    - 🎉 Finalized RFC 141 planning w/Geoffrey
    - 🎉 Reviewed managed instances approach
    - 💪 Investigating https://github.com/sourcegraph/customer/issues/60
    - 💬 Discussed resource reporting goals with Robert
    - 💬 Discussed over-under-provisioning monitoring approach with Robert
    - 💬 Discussed Jaeger operators with Dax/Beyang
    - 💬 Answering resource estimation questions
    - 💪 Various Interviews, debriefs, syncs, and other long conversations.
    - 💪 Working with [$CUSTOMER](https://app.hubspot.com/contacts/2762526/company/768958891/) on resource advice & HA deployment model across multiple AZs
    - 💪 Assisting Uwe/Dave with $CUSTOMER when needed
    - 🏃**Now focused on:** Reviewing changes by Robert & Dax (#9708); planned work (sourcegraph-intellij changes for $CUSTOMER)

**Legend:**

- 💬Discussion & advice
- 💪Progress
- 🎉Completed
- 🏃Working towards
- 🔎In review

cc @christinaforney @nicksnyder

**Comment by slimsag** [comment]
https://github.com/sourcegraph/sourcegraph/issues/11122

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by bobheadxi** [comment]
**Robert update**

* 🎉 Landed automated Grafana notifier deployment (https://github.com/sourcegraph/sourcegraph/pull/11483)
* 🎉 Landed provisioning monitoring (https://github.com/sourcegraph/sourcegraph/pull/11082)
* 🎉 Landed new licenses workflow (https://github.com/sourcegraph/sourcegraph/pull/11321, https://github.com/sourcegraph/about/pull/1067)
* 🎉  Misc fixes on dev tooling (https://github.com/sourcegraph/sourcegraph/pull/11486, https://github.com/sourcegraph/sourcegraph/pull/11540) 
* 💬 Planned some follow-up improvements Grafana alerts
* 🔍 Fixes for provisioning monitoring (https://github.com/sourcegraph/sourcegraph/pull/11542)
* 🔍 Support for Grafana SMTP configuration and email notifiers (https://github.com/sourcegraph/sourcegraph/pull/11554)

**Comment by ggilmore** [comment]
Geoffrey update:
- Completed PoC of https://github.com/sourcegraph/sourcegraph/issues/10936, we saw enough to continue investigating it
- Moved Dhall RFC 141 PoC into https://github.com/sourcegraph/deploy-sourcegraph-dhall
- Added more services to https://github.com/sourcegraph/deploy-sourcegraph-dhall to get a better idea of what the initial performance will look like 
- Will continue to add services and consult the Dhall slack to improve performance 
- Next milestone - replace subset of services on k8s.sgdev.org with Dhall customization pipeline

**Comment by daxmc99** [comment]
Dax update:

- Completed https://github.com/sourcegraph/sourcegraph/issues/10049, we can now observe and determine the time to highlight vs fetch a file.
- Completed https://github.com/sourcegraph/sourcegraph/issues/9866, add a prefix to ping logs to make the debugging experience cleaner
- Finished https://github.com/sourcegraph/sourcegraph/issues/9867, I added a dashboard and clarified the metrics being sent back to Sourcegraph. I left the issue open though because I believe these metrics should be removed after they are used to determine which methods take the most time. These metrics have a high level of cardinality. 
- Fixed https://github.com/sourcegraph/sourcegraph/pull/11536, docker build should work on Mac again 😄 
- Terraform infrastructure for Sourcegraph.com https://github.com/sourcegraph/sourcegraph/issues/10455. The code is ready to merge but we still need to coordinate with the cloud team to perform the migration to ensure the Sourcegraph.com infrastructure is captured in the state file. 
- Next steps: Focusing on Sourcegraph.com cloud HA Postgres as part of https://github.com/sourcegraph/sourcegraph/issues/11496
