### ISSUE TITLE
Backend: permission levels for campaigns

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#10808]
Taken from [RFC 157](https://docs.google.com/document/d/1-Ed6s3yiB-pmL7Up8H6nMlUhgmLn5BVu34Zpvf-_YNo/edit).

### Tasks

Distinguish between admin- and read-permissions
 - authors of a campaign (`author_id`) have admin permission
 - site admins also have admin access
 - everybody else read

Check for admin permissions would be (for now): `campaign.author_id == currentUser.id || currentUser.IsSiteAdmin()`

- [x] Check for admin permissions in these mutations:
    - `publishCampaign`
    - `publishChangeset`
    - `retryCampaign`
    - `updateCampaign`
    - `addChangesetsToCampaign`
    - `syncChangeset`
    - `closeCampaign`
    - `deleteCampaign`
- [x] Hide errors: return empty array in `campaign.status.errors`
- [x] Add a `viewerCanAdminister` flag to `Campaign` to display/hide controls in the UI

**Comment by mrnugget** [comment]
Just for the record: @eseliger realized that we need to extend the `campaigns()` queries to accept an additional `viewerCanAdminister: Boolean` arg so that on the "Preview update" we can only show the campaigns the user can actually update.
