### ISSUE TITLE
Backend: Repository permissions for campaigns

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#10809]
Taken from [RFC 157](https://docs.google.com/document/d/1-Ed6s3yiB-pmL7Up8H6nMlUhgmLn5BVu34Zpvf-_YNo/edit).

**Status**: Tasks are final.

### Backend Tasks

- [x] Split up the `Patch` and `ExternalChangeset` types in the GraphQL schema into `Patch`/`HiddenPatch` and `ExternalChangeset`/`HiddenExternalChangeset`. The types should implement the same interface, respectively, which only has the fields that the "hidden" version should contain:
    - `HiddenPatch`: only has the `id` field
    - `HiddenExternalChangeset`: only has the `id`, `createdAt`, `updatedAt`, `nextSyncAt`, `campaigns`
- [x] In every `ChangesetsConnection` return a `HiddenExternalChangeset` when the user doesn't have access to the underlying repository
- [x] In every `PatchesConnection` return a `HiddenPatch` when the user doesn't have access to the underlying repository
- [x] In `ChangesetByID`,`PatchByID` return "not found" if the user doesn't have access to the repository
- [x] In `Campaign.status.errors` filter out the errors if the user doesn't have access to the underlying repositories.
- [x] In `Campaign.diffStat` do not include stats for patches/changesets the user doesn't have access to
- [x] In `PatchSet.diffStat` do not include stats for patches/changesets the user doesn't have access to
- [x] Updating a campaign:
    - filter out all the existing changesets the user does _not_ have access to, keep them untouched.
    - Do not close/update/create changesets the user does not have access to.
    - Make sure that this applies to "update changeset with new title/description" too!
- [x] Check repository permissions for access in following mutations and return an error if user has no access:
    - [x] `publishChangeset` - return "not found" if user has no access
    - [x] `publishCampaignChangesets` - only publish the changesets the user has access to
    - [x] `addChangesetsToCampaign` - filter out changesets user doesn't have access to and return error (see existing error for "not found")
    - [x] ~`createCampaign` - Skip publication of all patches from patchset the user doesn't have access to.~ (Invalid now that draft campaigns have been removed)
    - [x] `retryCampaign` — same as `publishCampaignChangesets`: only retry the changesets the user has access to
    - [x] `updateCampaign` - see previous task 
    - [x] `createChangesets` - filter out repositories dosn't have access to and return error (see existing error for "not found")
    - [x] `syncChangeset` - return "not found" if user has no access 
    - [x] `closeCampaign` - leave changesets untouched if user has no access to them
    - [x] `deleteCampaign` - leave changesets untouched if user has no access to them
- [x] Filter out hidden changesets when using filters other than `status`.
- [x] Include hidden changesets in `openChangesets` query resolver.
- [x] Filter out patches in `CreatePatchSetFromPatches`

### Notes

`authzFilter` is the canonical way to filter a list of `*types.Repo` down to a subset of repositories a user has access to. [See here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4ab650e5a239303ff8537216b11b8fffeba4d785/-/blob/cmd/frontend/db/repos.go#L198:9)

**Comment by mrnugget** [comment]
@eseliger Based on our discussion yesterday I tried my hand at a schema that uses two types for visible and hidden changesets/patches: https://github.com/sourcegraph/sourcegraph/pull/10845/files Can you comment in that draft PR on whether you think it'll work for you or not?

**Comment by mrnugget** [comment]
After playing around with the Go code in #10845 I think the solution I originally proposed in this ticket (making the fields nullable and adding a `userCanView: bool` field would be _a lot_ easier to implement in the backend and get performant.

With two separate connection-resolvers that accept connection args and can be reached through campaigns and (for now at least) patchsets, I don't see a way to avoid querying for repositories and putting them through the `authzFilter` multiple times.

**Comment by eseliger** [comment]
two more ideas:

- We could mock out the UI first, so we see how we would actually query them
- We could have an interface and two types implementing it, like the following:

```graphql
interface Changeset {
id:ID!
.. other visible fields
}
type ExternalChangeset implements Changeset {...}
type HiddenChangeset implements Changeset {...}
type ChangesetConnection {
  nodes: [Changeset!]!
}
```

that way we could hardly distinguish them but show them in 1 list view, instead of two. Another benefit: we could add `onlyVisible: Boolean` as a filter to the list, allowing users to hide the hidden ones

**Comment by mrnugget** [comment]
>     * We could mock out the UI first, so we see how we would actually query them

Good idea! Can you do that?

> We could have an interface and two types implementing it, like the following:

I don't understand the code snippet: how would `HiddenChangset` implement the `other visible fields?

> but show them in 1 list view, instead of two.

But that makes me wonder how the filtering of that list would work. Do we show all changesets by default and if I, for example, filter by approval-status or CI-check-status, then hidden changesets will never be included?

**Comment by eseliger** [comment]
> Good idea! Can you do that?

Yep


> I don't understand the code snippet: how would HiddenChangset implement the other visible fields?

only the visible fields fields would be on the common interface, the non visible fields are only on the external changeset

> But that makes me wonder how the filtering of that list would work. Do we show all changesets by default and if I, for example, filter by approval-status or CI-check-status, then hidden changesets will never be included?

No answer yet, I think from a UI clutter perspective, two more list views on that page would be really bad. Maybe, if the hidden changesets show clearly enough what they don't know, it's obvious. I'll try that in the mock

**Comment by mrnugget** [comment]
> only the visible fields fields would be on the common interface, the non visible fields are only on the external changeset

Got it! I'll try that in a second branch.

**Comment by mrnugget** [comment]
@eseliger Take a look: https://github.com/sourcegraph/sourcegraph/pull/10856/files What do you think?

**Comment by eseliger** [comment]
Looks good, much cleaner than just all nullable, WDYT?

**Comment by mrnugget** [comment]
Agree. I'll play around with this some more and update the backend tasks. Once you have the mockup done, we can hop on a call and go through the ticket here again and update the tasks for backen and frontend. Okay?

**Comment by mrnugget** [comment]
@eseliger We also need to hide patches — I assume we use the same pattern, right? `Patch` and `HiddenPatch`?

**Comment by mrnugget** [comment]
Updated https://github.com/sourcegraph/sourcegraph/pull/10856 to now have `Patch` and `HiddenPatch` types in the GraphQL schema, both implementing a `PatchInterface` (better names welcome!).

I also updated the backend tasks in this ticket.

@eseliger let me know when you have the mockup ready so we can talk about this ticket here.

**Comment by mrnugget** [comment]
Closed by all of the above PRs.
