### ISSUE TITLE
Search: 3.17 Tracking issue

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#10805]
### Status

This tracking issue is being prepared.

### Availability

Period is from **May 21st** to **June 19**. Please write the days you won't be working and the number of working days for the period.

- Farhan: 21d (out May 25)
- Rijnard: working all days (how many work days are there in this period?)
- Teammate ...

### Workload

@asdine

- [ ] More efficient and-operator evaluation [#11281](https://github.com/sourcegraph/sourcegraph/issues/11281) 
- [x] Lift 14-character limit on version context names [#11591](https://github.com/sourcegraph/sourcegraph/issues/11591) 

@attfarhan: __2.50d__

- [x] version contexts feedback: include warning when URL changes context [#10769](https://github.com/sourcegraph/sourcegraph/issues/10769) __1d__ 
- [x] Question mark button doesn't do anything on version context popup [#10781](https://github.com/sourcegraph/sourcegraph/issues/10781) __0.5d__ 🐛
- [x] Hide 'Select context' placeholder label after first use [#10877](https://github.com/sourcegraph/sourcegraph/issues/10877) __1d__ 

@keegancsmith

- [ ] ~Index multiple (non-master) branches~ [#6728](https://github.com/sourcegraph/sourcegraph/issues/6728) __10d__ [👩](https://app.hubspot.com/contacts/2762526/company/554338610)
- [x] errors seen in indexed-search on bigdata cluster with 250k repos [#11200](https://github.com/sourcegraph/sourcegraph/issues/11200) 

@rvantonder: __9.50d__

- [ ] Improve documentation for and/or queries [#9969](https://github.com/sourcegraph/sourcegraph/issues/9969) __1.5d__ 🛠️
- [x] Propose and implement and/or queries in literal search [#9968](https://github.com/sourcegraph/sourcegraph/issues/9968) __2d__ 🛠️
- [x] Add integration tests for and/or queries [#9937](https://github.com/sourcegraph/sourcegraph/issues/9937) __2d__ 🧶
- [x] Refine and/or query validation for different searches [#9971](https://github.com/sourcegraph/sourcegraph/issues/9971) __2d__ 
- [x] search: unquote field values for validation [#9818](https://github.com/sourcegraph/sourcegraph/issues/9818) __2d__ 🧶

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by rvantonder** [comment]
My planned work items are set for this iteration.

**Comment by rvantonder** [comment]
Status update

**Last week**

Implemented the literal search parser with the new parser/scanner logic and translated existing tests. This means that all search kinds can be performed using the new search parser, so we are in a position to migrate fully to the new implementation. I also spent some time on the side adding repogroups to Sourcegraph.com for popular repositories.

**Planned this week**

There are a few minor things to add for the new query parser to be feature complete (interpreting quotes of parameter values and detecting `patterntype:...` fields). After that, I'll be doing a lot of testing (integration tests, etc.) so that we can fully migrate to the new unified implementation and release and/or queries with confidence. If I get a chance I'd also like to add an endpoint to the GQL schema for the parsed query, but if that falls through I'll get to it next week.

I have an idea to do something on the side for the repogroups/scopes page to showcase some example searches, will see if I get a chance this week.

**Comment by attfarhan** [comment]
*Last week* (4-day week)
* Interviews: 1 follow-up call, 1 architecture interview, 2 coding challenges
* Demo for https://app.hubspot.com/contacts/2762526/company/3401593764/
* Version contexts video for 3.16 release
* Opened PRs for fixes/improvements to version contexts: 
  * https://github.com/sourcegraph/sourcegraph/pull/10907
  * https://github.com/sourcegraph/sourcegraph/pull/10934
* Opened PR to add Enzyme for snapshot tests: https://github.com/sourcegraph/sourcegraph/pull/10859

*Planned this week*
* Fix https://github.com/sourcegraph/sourcegraph/issues/10877
* 3.17 planning: create issues and goals for version contexts + onboarding work (meeting set with Christina and Rob tomorrow AM)
  * work on above issues

**Comment by rvantonder** [comment]
**Last week**

Focused on getting and/or heuristics to feature parity with our current implementation, and integration testing search behaviors end-to-end. During this testing I realized there are some parts of query interpretation that need more attention, especially for surfacing suggestions.

**Planned this week**

Similar to last week: more tests, address issues to migrate/implement full and/or search behavior. Additionally, I plan to:

- Put up the RFC to track literal search with and/or queries
- See if I can grab time this week to add or propose the parsing result/suggestions to GQL API
- Put some time aside for the repogroups/scopes page to showcase some example searches, will see if I get a chance this week.

**Comment by attfarhan** [comment]
**Last week** (4 day week)
* Web debt items: 
  * worked on Enzyme snapshots PR
  * worked on converting components to Reach UI (local WIP branch)
* 2 coding challenges, 1 candidate call
* Web teammate 1:1 calls
* Planning for 3.17: 
  * Planning call w Christina and Rob 
  * Reviewed RFC 159

*This week*
* Merge enzyme PR https://github.com/sourcegraph/sourcegraph/pull/10859
* Continue replacing reactstrap components w Reach UI 
* Fix https://github.com/sourcegraph/sourcegraph/issues/10877
* Work on RFC 159 when approved

**Comment by asdine** [comment]
### Last week

I was off for 3 days, the rest of the time I worked on making Sourcegraph indicate to Zoekt which branches need to be indexed based on the content of version contexts.

### Next week

I will pair with @keegancsmith on Zoekt improvements

**Comment by rvantonder** [comment]
**Last week**

- Put up RFC 176 for literal search with and/or queries, improved logic for handling heuristics, added search optimizations, and tests.
- Scratched an itch to improve search documentation and made progress on some nice looking railroad diagrams for our query language 😎 

**This week**

- Complete integration tests and activate literal search mode with and/or queries on dot com. Will turn "default off" to "default on" for and/or queries in 3.17 release when test suite is comprehensive, which I'm aiming to do by end of week
- Will try merge the search docs update into our main docs page, will post in progress soon
- Wish: add GQL API for query parsing,  work repogroups/scopes page to showcase
- Stretch: support basic `or` operators on `file:` and `repo:` fields.

**Comment by attfarhan** [comment]
**Last week**
* Researched frontend guided-tour libraries
* Reviewed RFCs: 159, 177
* Web tech debt:
  * Merged Enzyme-to-JSON PR
  * Made progress on Reach UI replacing reactstrap
* Opened PR to fix #10877 (https://github.com/sourcegraph/sourcegraph/pull/11261)
* 1 coding exercise

**This week**
* Wrap up Reach UI replacing reactstrap
* Get started on RFC 159 implementation

**Comment by keegancsmith** [comment]
*Last two weeks*

- Scattered work time, so been hard to focus. Most important to notice is I have not made much progress on multiple branch indexing. Going forward I have child-care again so should improve.
- Lots of smaller tasks due to the above.
- Some planning work/thinking for dotcom and the future.

*This week*

- Focussed on shipping multiple branch indexing.
- Next week (June 15th-19th) I'll be taking a vacation.

**Comment by asdine** [comment]
### Last week

I started working on improving the AND operator evaluation

### This week

I will keep working on AND operator improvement and on Zoekt improvements

**Comment by rvantonder** [comment]
**Last week**

- Added support for and/or queries in literal search mode, RFC 176. 
- Worked on search docs to provide a query language reference page. 
- Testing the full spectrum of literal/regexp/structural search for release.

**This week**

- I'll be changing the default off -> default on for and/or queries on search contents and testing between branch cut and release
- Add query transformations to simplify regexp/literal queries for `or`
- Polish and merge query language reference page
- Videos for and/or operators to accompany release
- Stretch: I'd like to support full hierarchical search, and feature flag it

**Comment by attfarhan** [comment]
**Last week**
- Interviews:
  - 3 coding challenges
  - 1 follow-up call
- Worked on replacing all reactstrap dropdowns with Reach UI, added storybook tests, opened PR https://github.com/sourcegraph/sourcegraph/pull/11404. Unfortunately doesn't seem like the correct solution, so back to the drawing board.
- Reviewed RFC 159 wireframes, search doc updates

**This week**
- Providing feedback on any RFC 159 wireframes/prototype. Start implementing if it's ready.
- Continue reactstrap + testing work -- more research on possible alternatives and implementations. 
- Work on other bugs that can be fixed:
  - https://github.com/sourcegraph/sourcegraph/issues/11298
  - https://github.com/sourcegraph/sourcegraph/issues/10610
  - https://github.com/sourcegraph/sourcegraph/issues/10457
  - Other assigned issues: https://github.com/sourcegraph/sourcegraph/issues/assigned/attfarhan

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by asdine** [comment]
### Last week

- Improved the AND operator performance for large result sets

### This week

- See if it is possible to use pagination internally for more memory efficient AND queries
- Improve Zoekt performance by providing an alternative structure for trigram indexes
