### ISSUE TITLE
Campaign patches with binaries don't apply

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#10815]
- **Sourcegraph version:** master
- **Platform information:** macOS 10.15.4, Chrome 81
#### Steps to reproduce:

1. Create an action that touches a binary file (ie. compress images in `docs/` folder)
2. Create campaign

#### Expected behavior:
It 
- works
- or warned me that it can't work
- or skips binaries so it doesn't fail
#### Actual behavior:
It fails with errors like

> creating commit from patch for repository "X": gitserver: applying patch: exit status 1
```
$ git apply --cached -p0 --unidiff-zero
error: cannot apply binary patch to 'binary.ttf' without full index line
error: binary.ttf: patch does not apply
```

Corresponding diff (see that binary content is not inlined):
```
diff --git binary.ttf binary.ttf
index 563872c..3d12770 100644
Binary files binary.ttf and binary.ttf differ
```

**Comment by eseliger** [comment]
Findings:
+ adding `--binary` to `git diff` in src-cli inlines the file, which should make it applicable. 
- our `go-diff` parser doesn't understand that and skips that file. It should also account for a `GIT binary patch` header. In that case, the whole binary content needs to be decoded and set on the diff, so we can use it in the `newFileContent` function in `patch_sets.go`, making it correctly return `binary: true` in the resolver.

**Comment by eseliger** [comment]
## Tasks

For binary patches to work, these need to be done:

- [ ] Merge https://github.com/sourcegraph/src-cli/pull/206
- [ ] Merge https://github.com/sourcegraph/go-diff/pull/46
- [ ] Update go-diff in sourcegraph/sourcegraph
