### ISSUE TITLE
RFC 158: Code Intel UI Tracking Issue

### ISSUE THREAD

**Issue by shrouxm** [sourcegraph/sourcegraph#10891]
Tracks work on [RFC 158](https://docs.google.com/document/d/1LkliTY4l-_S63hObBuiZ6g_izfF9IKrxnA9gEMK1FqA/edit#)

@unassigned

Completed
- [x] (🏁 861 days ago) https://github.com/sourcegraph/sourcegraph/issues/10927    🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)

@jjinnii

Completed
- [x] (🏁 468 days ago) https://github.com/sourcegraph/sourcegraph/issues/10926    🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)

@oleggromov

Completed
- [x] (🏁 581 days ago) https://github.com/sourcegraph/sourcegraph/issues/31953 
- [x] (🏁 504 days ago) https://github.com/sourcegraph/sourcegraph/issues/31071

**Comment by gbrik** [comment]
General question for web re: implementing all of this:

As-is, this will require duplicate design + implementation work for the browser extension and on dot-com. Was it a conscious decision to style them differently than the equivalent UI elements on dot-com, and would it be possible to unify them and use the same components on dot-com and the extension?

**Comment by felixfbecker** [comment]
> As-is, this will require duplicate design + implementation work for the browser extension and on dot-com. Was it a conscious decision to style them differently than the equivalent UI elements on dot-com, and would it be possible to unify them and use the same components on dot-com and the extension?

We do use the same components, but give them different CSS classes, which was indeed a conscious decision. The browser extension UI should "fit into" the code host UI and not look alien. E.g. a button on GitHub should look like other buttons on GitHub, not like a button in our webapp.

**Comment by gbrik** [comment]
OK, if they use the same components then my main concern is resolved.

It wasn't obvious to me whether they should or shouldn't be styled that way so I was curious if there was any prior discussion about it. I'll raise the issue again in a separate thread if I still have qualms after further thought.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
