### ISSUE TITLE
Backend: Remove the concept of a top-level "draft campaign".

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#10953]
From [RFC 157](https://docs.google.com/document/d/1-Ed6s3yiB-pmL7Up8H6nMlUhgmLn5BVu34Zpvf-_YNo/edit#)

### Backend

- [x] Remove the Campaign.publishedAt field (and the concept of a campaign being a draft vs. non-draft/published).
- [x] Remove the publishCampaign mutation.
- [x] Add the publishCampaignChangesets mutation: publish all existing campaign changesets that you are permitted to publish.
- [x] Rename `retryCampaign` to `retryCampaignChangesets`
- [x] Don't publish changesets when campaign is created (user needs to explicitly publish changesets/campaign)

### src CLI

- [x] Remove draft option in `src campaign create` https://github.com/sourcegraph/src-cli/pull/217

**Comment by mrnugget** [comment]
A lot of the tasks here have been fixed in https://github.com/sourcegraph/sourcegraph/pull/11130
