### ISSUE TITLE
Frontend: New campaigns flow

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#10986]
RFC: [RFC 157 - Campaigns authorization model](https://docs.google.com/document/d/1-Ed6s3yiB-pmL7Up8H6nMlUhgmLn5BVu34Zpvf-_YNo/edit#heading=h.m2a6qvh96dy8)

Docs PR (including links to Figma): https://github.com/sourcegraph/sourcegraph/pull/10921
Backend issue: #10985

#### Tasks
- [x] Create new Figma mockup based on most-recent concept and get confirmation from product
- [x] Ask Design if there are open questions or missing pieces
- [x] Throw out old components
- [x] Add stories for components that are retained
- [x] Add campaign spec preview page
  - [x] Visible changeset spec node
  - [x] Hidden changeset spec node
- [x] Campaign header
- [x] Campaign status component
- [x] Combined changeset list
- [x] Tabbed changeset/burndown chart UI
- [x] Campaign page on user/org site
- [x] Changeset mode should support publication and reconciler state

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by eseliger** [comment]
Moved to 3.18, requirements were not finalized this iteration.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
