### ISSUE TITLE
Code intelligence: 3.18 tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#11412]
### Plan

Our Q2 OKR is to increase the number of WAU of LSIF code intelligence actions.

Here are the problems that we want to solve this iteration:

1. Users aren't configuring repositories to upload LSIF data.

    1. LSIF is a non-trivial amount of technical work to setup, which is a barrier to adoption.

        **SOLUTION: Expand the number of languages and cases where we can automatically index repositories with LSIF. Use data from sourcegraph.com to determine which repositories are the source of the most search based code intel queries.**

    1. Even though the technical work to setup LSIF is straightforward, we have observed that engineers who are motivated to do this work get blocked due to how their organization functions (e.g., adding stuff to CI is hard and/or requires approvals).

        **SOLUTION: Make it possible to configure LSIF auto-indexing within Sourcegraph without needing to make a change to your company's CI system for common cases.**

1. We have multiple customers who want precise C++ code intel and current DXP approach is not sufficient.

    **SOLUTION: Ship MVP of new clangd indexer to [C1](https://app.hubspot.com/contacts/2762526/company/2931649618/), [C2](https://app.hubspot.com/contacts/2762526/company/947819054/)**

1. Users don't understand that there are two kinds of code intelligence. When they encounter issues with imprecise code intel, they don't know how to enable precise code intel. When precise code intel is configured, but is unavailable for multiple possible reasons, it is not clear to the user why they are seeing imprecise code intel.

    **SOLUTION: Improve hover tooltips to include more information on the state/source of code intel.**

1. [C1](https://app.hubspot.com/contacts/2762526/company/464956351/) and [C2](https://app.hubspot.com/contacts/2762526/company/554275594/) are blocked from adopting LSIF because they have large repositories with high commit rates.

    **SOLUTION: Design incremental indexing (start validating assumptions next month). Design scalable find-nearest queries (stretch begin implementing this month)**

### Availability

Period is from **2020-06-20** to **2020-07-20**. Please write the days you won't be working and the number of working days for the period.

- Eric: 21d
- Garo: 12d

### Workload

@aidaeology

- [ ] Collect regular data about code intel activity  [#11746](https://github.com/sourcegraph/sourcegraph/issues/11746) 

@efritz

- [x] LSIF tree data query for repository root returns null [#11490](https://github.com/sourcegraph/sourcegraph/issues/11490) 
- [x] Deleting repos stops code intel UI from rendering [#11637](https://github.com/sourcegraph/sourcegraph/issues/11637) 
- [x] Code intelligence integration tests [#10832](https://github.com/sourcegraph/sourcegraph/issues/10832) 
- [x] Minor: Retry lsif index upload when clone is in progress [#9700](https://github.com/sourcegraph/sourcegraph/issues/9700) 
- [x] Improve Postgres backcompat check [#11797](https://github.com/sourcegraph/sourcegraph/issues/11797) 
- [x] LSIF uploads can get stuck in "uploading" [#11622](https://github.com/sourcegraph/sourcegraph/issues/11622) 
- [x] Enable search by repo name in code intel UI [#11638](https://github.com/sourcegraph/sourcegraph/issues/11638) 
- [x] Write RFC to support better nearest-commit queries [#11627](https://github.com/sourcegraph/sourcegraph/issues/11627) 
- [x] Clean up lsif data for deleted repos [#11696](https://github.com/sourcegraph/sourcegraph/issues/11696) 
- [x] Tune auto-index schedule heuristic [#11624](https://github.com/sourcegraph/sourcegraph/issues/11624) 
- [x] Preload precise code intel data on the client [#10869](https://github.com/sourcegraph/sourcegraph/issues/10869) `specced` 
- [x] HTTP 522 on large LSIF uploads [#11876](https://github.com/sourcegraph/sourcegraph/issues/11876) 
- [x] Hovering a symbol should highlight visible references to that symbol [#10868](https://github.com/sourcegraph/sourcegraph/issues/10868) `specced` 
- [x] Allow user to supply http headers for requests src-cli sends [#238](https://github.com/sourcegraph/src-cli/issues/238) 
- [x] Add ability to schedule repos for indexing outside of event log heuristics [#11625](https://github.com/sourcegraph/sourcegraph/issues/11625) 
- [x] Run worker jobs concurrently [#11643](https://github.com/sourcegraph/sourcegraph/issues/11643) 
- [x] Create docs page for codeintel showcase repos [#9609](https://github.com/sourcegraph/sourcegraph/issues/9609) `docs` 
- [x] Extract codeintel's background job processing into an internal library [#11786](https://github.com/sourcegraph/sourcegraph/issues/11786) 
- [x] Write RFC to horizontally scale auto-indexer [#11635](https://github.com/sourcegraph/sourcegraph/issues/11635) 
- [x] Write RFC to scale the bundle manager [#11634](https://github.com/sourcegraph/sourcegraph/issues/11634) 
- [x] Write RFC to enable additional build steps in auto-indexer [#11626](https://github.com/sourcegraph/sourcegraph/issues/11626) 
- [x] Write developer expectations for rolling deployments [#1126](https://github.com/sourcegraph/about/issues/1126) 

@gbrik

- [x] Fix incremental indexing RFC 170 [#11639](https://github.com/sourcegraph/sourcegraph/issues/11639) `planning` 
- [x] Prototype a new LSIF indexer for C++ based on clangd-indexer [#10175](https://github.com/sourcegraph/sourcegraph/issues/10175) `in progress` 
- [x] Provide convenient distribution formats for lsif-clang [#11641](https://github.com/sourcegraph/sourcegraph/issues/11641) `not started` 
- [x] Create a "code intelligence source" tooltip [#10925](https://github.com/sourcegraph/sourcegraph/issues/10925) `in progress` 
  - [x] Add extension API for hover alerts [#12123](https://github.com/sourcegraph/sourcegraph/pull/12123) :shipit:
- [ ] Create a code intel user survey [#11747](https://github.com/sourcegraph/sourcegraph/issues/11747) 
- [x] hover source code intel tooltips [#423](https://github.com/sourcegraph/code-intel-extensions/pull/423) :shipit:

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by felixfbecker** [comment]
@sourcegraph/code-intel could https://github.com/sourcegraph/sourcegraph/issues/11490 make it onto the plan for 3.18? Would love to make use of diagnostics but this is blocking it :)

**Comment by efritz** [comment]
@felixfbecker I added it.

**Comment by efritz** [comment]
**2020/06/22-26 Complete**

TODO

**2020/06/29-07/03 Complete**

TODO

**Comment by gbrik** [comment]
### 2020/06/22-26 Complete

- [x] RFC 170 incremental indexing
- [x] Milestone project planning
- [x] Interviews
- [x] lsif-clang mvp

### 2020/06/29-07/03 Planned

- [ ] package, distribute & ship lsif-clang

**Comment by nicksnyder** [comment]
Thanks for the updates!

I just wanted to share that I really like the format of the updates in these other tracking issues (i.e., more prose less lists):
- https://github.com/sourcegraph/sourcegraph/issues/11523#issuecomment-651177855
- https://github.com/sourcegraph/sourcegraph/issues/11494#issuecomment-651120375
- https://github.com/sourcegraph/sourcegraph/issues/11613#issuecomment-650936066

Handbook docs: https://about.sourcegraph.com/handbook/engineering/tracking_issues#progress-updates

**Comment by gbrik** [comment]
@nicksnyder :+1: :-1: ?

### 2020/06/22-26 Complete
#### Milestone planning
Eric and I split up work, and I did some initial planning for the user research I want to get done this quarter.
#### RFC 170 incremental indexing
I spent ~day iterating with Eric & solidifying thoughts into a new draft, and Eric approved. No more work planned this milestone, next step for the RFC will be feasibility study.
#### Interviews
Took up 4+ hours, which is unfortunately a big chunk of my week. We just had a lot of candidates last week :shrug: 
#### lsif-clang MVP
Since Eric found my bug I've been moving quickly again, I now have valid LSIF indexes produced for the llvm project and Linux kernel (2 and 4 gigs uncompressed respectively). The only remaining implementation work is coaxing clangd to output a bit more information (certain symbols aren't getting output), and making the CLI a bit more pleasant (I may actually just use a wrapper CLI instead of continuing to fiddle with clang).

### 2020/06/29-07/03 Planned

#### Package, distribute, ship lsif-clang
Now that lsif-clang is reliably producing indexes, I need to figure out how to make it easy for users to download a release of our forked version. Docker might not work since most builds will likely rely on local header files. Hopefully a statically linked binary will  be good enough. Uncharted territory here for me, so the ~1week timeline is pretty arbitrary.

I also want to reach out to the llvm folks to see what they think about upstreaming this: this is our first indexer which is a fork of a community run OSS project, so would be a good first candidate for an indexer we don't have to maintain.

**Comment by efritz** [comment]
@nicksnyder I'm also updating this to better reflect the desired format.

### 2020/06/22-26 Complete

#### Scaling nearest commit queries 🎉 

Wrote [RFC 186](https://docs.google.com/document/d/1NiAQG4muTljgk8qirYs2aN5Zt3lfk4lgwNqOm9WOH4s) about scaling nearest-commit queries and discussed with Garo 1-on-1. This RFC has been approved by Garo and members of the cloud team. This work is necessary to support customers with high commit frequency (mostly monorepo customers) as the current limit of 100 commits ahead/behind will be too little to capture data where users are likely to browse. Implementation on this will begin in 3.19, but I may start to tackle it a bit sooner if the rest of this milestone goes quickly.

There is more cross-team discussion around (but not directly related) to this RFC, as the @sourcegraph/cloud team is also beginning to track some commit data in Postgres. We've decided to move ahead on this effort and, if we have the same needs after this is implemented, try to merge data together. Cloud currently doesn't need to track every commit, which is an absolute necessity on the code intel side (hence the current split).

#### Integration tests 🎉 

I've updated our [integration tests](https://github.com/sourcegraph/sourcegraph/issues/10832) so that it can be more easily ran in the release captain to test for regressions. This now stores indexes in Google Cloud Storage instead of needing the user to clone and index a bunch of code before testing. Should make it easier for any member of the engineering team to run the tests and give high confidence that precise code intel is not affected by an unrelated change.

#### Smaller features/fixes 🚀 

Still gotta make progress on the lil' fellers. Added a way to [filter by repository name](https://github.com/sourcegraph/sourcegraph/issues/11638) when viewing index and upload lists from the site admin pages. This previously wasn't possible because there's no repository name in the record (only an ID).

Additionally fixed some issues with [retaining uploads for deleted repos](https://github.com/sourcegraph/sourcegraph/issues/11696), [crashing the UI when trying to resolve uploads for deleted repos](https://github.com/sourcegraph/sourcegraph/issues/11637), and [retaining uploads that never finished uploading](https://github.com/sourcegraph/sourcegraph/issues/11622). Finally fixed another paper cut where [clone in progress repositories are rejected](https://github.com/sourcegraph/sourcegraph/issues/9700) when uploading indexes on sourcegraph.com. Fixed an issue for @felixfbecker that he caught late last milestone where [repository roots for diagnostics were wrong](https://github.com/sourcegraph/sourcegraph/issues/11490). 

Little stuff but it all adds up.

![add some polish](https://res.cloudinary.com/yourmechanic/image/upload/dpr_auto,f_auto,q_auto/v1/article_images/Should_you_wax_or_polish_your_car)

### 2020/06/29-07/03 Planned

#### Auto indexing 

My main task will be to [improve the auto-indexer schedule heuristic](https://github.com/sourcegraph/sourcegraph/issues/11624), which will do a better job at keeping indexed repositories up-to-date if successful. Right now there's only heuristic for when a repo should begin to be indexed, and I believe that the current behavior is kind of crummy:

- there's a lot of search-based code intel on a repo
- auto-index it
- there's no longer a lot of search-based code intel: it's probably fine!
- the project has a sufficient number of commits that the LSIF index doesn't cover much anymore
- repeat the cycle

This has the _real bad_ effect of having good intel for a while, degraded intel for a while, no intel for a short while, and then good intel again. It makes it seem real flaky.

#### Blog post

I spent most of today in meetings and trying to finish up my responses to @beyang's edits on [https://github.com/sourcegraph/about/pull/1118](the performance improvement blog post). We plan to re-publish this sometime this week and re-post after a few days to some of the same channels.

#### Side tracked (a wild task appeared!)

Had a discussion with distribution and some members of cloud about [RFC 181](https://docs.google.com/document/d/1pReWeznvPWQQknXdsK4z7zyhaVzdAcB1FhdDA_b1b24), which surfaces some issues I have with the current CI Postgres backcompat check. I've taken ownership of [improving it for the cloud use case](https://github.com/sourcegraph/sourcegraph/issues/11797) and will do that early this week. Will also update our documentation in the handbook on [what developers need to do to allow friction-less upgrade and downgrade paths](https://github.com/sourcegraph/sourcegraph/issues/11637) where possible.

I've also volunteered to try to [generalize some of the queue/worker processing code](https://github.com/sourcegraph/sourcegraph/issues/11786) to aid in the [widening need for background processing](https://github.com/sourcegraph/sourcegraph/issues/11672). This will be my lowest priority this week, but I still plan to get it started.

**Comment by gbrik** [comment]
### 2020/06/29-07/03 Completed

I successfully ~indexed the linux kernel and llvm project. Or at least, the index holds up to manual scrutiny. Eric helped me get the linux index uploaded to sg cloud, but I wasn't  able to get code intel because processing failed. I suspect this is because the index is 11GB uncompressed and our backend can't quite handle that yet, not that the index is corrupt.

I successfully built a statically linked binary of the indexer and used it to index the opencv project. This binary will likely be the distribution format for the tool.

Eric & I did a call with customer to help them set up lsif-go. A variety of issues led to the call being mostly unsuccessful. My takeaway: bazel support might be more necessary than we previously thought, and having a robust indexer is only part of the solution when an overarching build system exists.

### 2020/07/06 Planned

Do some final validation on lsif-clang (use docker to check the binary's portability, get an index processed on dot-com) and then ship the binary to existing users to see if it improves their use case.

Rest of week is focused on opening a PR for hover tooltips.

**Comment by efritz** [comment]
### 2020/06/29-03 Complete

I added document highlight to the extension API and am waiting to merge the initial draft in the extensions (I'm no longer blocked, I didn't understand how to bump the version in npm even though I've done it before).

![reference highlights](https://user-images.githubusercontent.com/103087/86259862-2c347780-bb82-11ea-9dd2-256042992ed2.gif)

Updated indexing heuristics of the auto-indexer so that things don't fall out of sync quickly for indexed repos. I believe this is a low-effort change that will make a big improvement in how users feel about the reliability of the feature as repos should no longer "degrade" as they stray from the last index.

Implemented batching of code intelligence queries to make the common path in the extensions quick with fewer network requests. This should reduce the general load on the frontend as well when users are browsing a single blob page (only data that falls out of a pre-loaded range, doesn't have LSIF, or is a find ref or xrepo def will hit the API).

Garo and I identified an issue with large uploads resulting in a 522 response. I have previously applied remedies for this by splitting large uploads into multiple chunks. In https://github.com/sourcegraph/sourcegraph/issues/11876, we are continuing to make this process more robust by implementing retries in src-cli (we already do retries for service-to-service transfers) and making the final stitch request faster so that a timeout is far less likely. These PRs are ready for review.

### 2020/07/06-10 Planned

There a good number of tasks that are waiting to be merged (there are five unchecked tasks above that can be checked soon without much effort, just waiting for approvals or feedback from users). 

This week I'm planning to explore adding concurrency back into the worker so we can process more than one thing at a time. I'm also planning to add the ability to schedule repositories with the auto-indexer that falls outside of the usage heuristic. This won't have an API or UI page to go with it yet, but will lay that groundwork.

Many of my remaining tasks are documentation, RFCs, or things that don't need to make branch cut, so It appears that I'm on track to finish everything listed in this milestone.

**Comment by nicksnyder** [comment]
@gbrik Can you clarify whether the lsif-clang indexer is "done" (if so, would it be appropriate to close the issue?). How are you feeling about the tooltip work being merged by release branch on Tuesday?

**Comment by gbrik** [comment]
@nicksnyder I just closed the issue after finally getting an index running on dot-com (you can play around with it on this file: https://sourcegraph.com/github.com/sourcegraph/lsif-clang@04b419bd5749c05b14c5cea3ac3e5a491c9c9ecb/-/blob/clang-tools-extra/clangd/CodeComplete.cpp). Tooltips are working, I just need to polish and do a bit more backend work before putting them up for review by beginning of day Monday, so I'm expecting them to be done.

**Comment by efritz** [comment]
### 2020/07/06-10 Complete

Added ability to enable a repository for auto-indexing regardless of its popularity in [#11625](https://github.com/sourcegraph/sourcegraph/issues/11625). Requires direct database access for now.

Added support for >1 worker process per container in [#10912](https://github.com/sourcegraph/sourcegraph/pull/10912). Discovered an existing bug that occurs for any pair of worker processes/pods processing an upload for the same repository, filed in [#12095](https://github.com/sourcegraph/sourcegraph/issues/12095). This shouldn't block the merge (concurrency is off by default and it's not a new issue), but will wait until @gbrik sees the changes before committing.

Improved the batching endpoints for code intel queries in [#12028](https://github.com/sourcegraph/sourcegraph/pull/12028). The first draft was written in a naive way that depends on cached values. This created a few ten-thousand opentracing spans per request. This PR changed the access pattern so that we request only what's needed. Reduced spans but didn't change efficiency drastically. Supported using the batching endpoints in the code intel extensions in [#414](https://github.com/sourcegraph/code-intel-extensions/pull/414). This is waiting to be merged until @gbrik glances at it. This should drastically decrease the total number of API requests made from the extension, and make much of the results faster as they're bulk loaded into memory.

Merged [#409](https://github.com/sourcegraph/code-intel-extensions/pull/409), which added support for document highlights in the code intel extension side. @gbrik first noticed noticed this during our sync while browsing around with lsif-cpp 😛

Updated src-cli behaviors to help with customers:
- [src-cli #239](https://github.com/sourcegraph/src-cli/pull/239) allows usage to instances behind authenticating proxies
- [src-cli #243](https://github.com/sourcegraph/src-cli/pull/243) adds retry logic to src lsif uploads
- [#11958](https://github.com/sourcegraph/sourcegraph/pull/11958) improves stitch endpoints that join partial upload files (turns out you can concat gzip files without decoding/re-encoding)

Finally, started paying off some tech debt (umbrella issue [#11676](https://github.com/sourcegraph/sourcegraph/issues/11676)) by implementing a base store class in [#12056](https://github.com/sourcegraph/sourcegraph/pull/12056). This will allow multiple store implementations to share transactions, which has been a pain point for both code intel as well as campaigns code for a while now.

### 2020/07/13-18 Planned

I'll be writing the three RFCs that are listed in the issue description.

**Comment by gbrik** [comment]
### 2020/07/06-~10 Complete

lsif-clang is ready to go, just want to ask folks to dog food a bit before pushing it out. https://github.com/sourcegraph/lsif-clang Building portable binaries turned out to be a waste of time, so I had to learn some cmake to split it off as an external library that can be compiled against prebuilt LLVM installs. Intention is for customers to clone & build in their own env, which is standard for cpp and matches the behaviour of the old indexer. This also will make it easier to build against other forks of LLVM, specifically it might be possible to also provide Swift LSIF indexing via Apple's LLVM fork, but that's completely unexplored ATM.

Hover tooltips got pushed a bit by above taking extra time and one of the components I was relying on missing unexpected features, but I have a PR up now: #12123. I would need to merge an additional backend change to close all the issues, but this will resolve the most important one: #10925.

### 2020/07/13-18 Planned

Merge #12123 hover tooltips and the related code-intel-extension changes. Try to make backend changes so that the remaining hover tooltip issues #10926 #10927 make it.

Rest of time will be spent on the user research issues #11746 #11747, and Q3/3.19 planning.

### 2020/07/21-25 :tent: 

Reminder I'm away the week after next!

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
Finished milestone!

**Comment by efritz** [comment]
Continued in https://github.com/sourcegraph/sourcegraph/issues/12132.
