### ISSUE TITLE
RFC 174: HA Postgres for Sourcegraph Cloud

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#11496]
#### Context

This is an umbrella issue to capture work and ideas around [RFC 174: HA Postgres for Sourcegraph Cloud](https://docs.google.com/document/d/1zNy-9QTAS4-i4C-ooFsfSwLf-kdnIJlTE8-uyub6-Ik).

## Testing
- [x] Setup Cloud SQL Postgres deployment
- [x] Configure access to the instance via Cloud SQL Proxy
- [x] Backup current dotcom postgres database as SQL Dump
- [x] Import that data into Cloud SQL instance
~~- [ ] Configure preferred maintenance window ( bigger question, what is the best time for Sourcegraph.com to undergo maintenance based on where our users are located)~~
- [x] Manually test connectivity from a pod in the prod namespace to the Cloud SQL instance **Service** with psql and Cloud SQL Proxy.
- [x] Manually test that failover works smoothly (i.e. Sourcegraph keeps working)

## Rollout

- Use Terraform to create the instance
- Use a gradual rollout strategy to update pods with Cloud SQL Proxy to minimize disruption
- Make production sql instance read-only
- Export data from psql pods -> GCS bucket
- Import data into Cloud SQL
- Rollout update `PG*` env vars to change the database
- Take on-call for 2 hrs to ensure the rollout was successful on Sourcegraph.com

## Cleanup
- [ ] Remove pgsql deployment from Sourcegraph.com after 48 hours of Cloud SQL being deployed
- [x] Ensure PGTUNE values are migrated as well
- [ ] Remove persistent disk in GCP

**Comment by tsenart** [comment]
@daxmc99: You should own this RFC in this iteration, refine it, and convert all work that needs to be done to a task list in here.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
