### ISSUE TITLE
Improved Sourcegraph extension documentation

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1151]
Create and update documentation that covers the most essential concepts and API use-cases.

## TODO

- [x] Document extension manifest (`package.json`)
- [x] Tutorial for adding actions, commands and buttons
- [x] Tutorial for conditional activation and display of UI elements using expressions
- [x] Document contributions, actions, action items and menus
- [ ] Tutorial for configuration
- [ ] Tutorial for context and template usage 
- [ ] Add FAQs

**Comment by sqs** [comment]
Most of these are done. We can file issues and prioritize specific needs for new docs as they come up.
