### ISSUE TITLE
RFC 159: Stage 1 - repository group pages tracking issue

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#11526]
Tracks work on [RFC 159](https://docs.google.com/document/d/16ANfXRaJmsiYCPZSPlyAc8Zu-sY6plO6_eRDZ09C_SY/edit#heading=h.trqab8y0kufp)

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/11560 

Completed
- [x] (🏁 1203 days ago) https://github.com/sourcegraph/sourcegraph/issues/11652 
- [x] (🏁 1202 days ago) https://github.com/sourcegraph/sourcegraph/issues/11649 

@attfarhan: __10.50d__

Completed: __10.50d__
- [x] (🏁 1207 days ago) https://github.com/sourcegraph/sourcegraph/issues/11529    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 1207 days ago) https://github.com/sourcegraph/sourcegraph/issues/11513    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 1195 days ago) https://github.com/sourcegraph/sourcegraph/issues/11555    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 1195 days ago) https://github.com/sourcegraph/sourcegraph/issues/11537    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 1184 days ago) https://github.com/sourcegraph/sourcegraph/issues/11700    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 1177 days ago) https://github.com/sourcegraph/sourcegraph/issues/11799    🏳️ [3.19](https://github.com/sourcegraph/sourcegraph/milestone/44)
- [x] (🏁 1147 days ago) https://github.com/sourcegraph/sourcegraph/issues/12137  __10.00d__
- [x] (🏁 1142 days ago) https://github.com/sourcegraph/sourcegraph/issues/12276  __0.50d__   🏳️ [3.19](https://github.com/sourcegraph/sourcegraph/milestone/44)

@christinaforney

- [ ] https://github.com/sourcegraph/sourcegraph/issues/10621 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/11698 

Completed
- [x] (🏁 1207 days ago) https://github.com/sourcegraph/sourcegraph/issues/11529    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 1207 days ago) https://github.com/sourcegraph/sourcegraph/issues/11513    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 1187 days ago) https://github.com/sourcegraph/sourcegraph/issues/12057 (PRs: ~[#12084](https://github.com/sourcegraph/sourcegraph/pull/12084)~)   🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 1184 days ago) https://github.com/sourcegraph/sourcegraph/issues/11725    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 1184 days ago) https://github.com/sourcegraph/sourcegraph/issues/11538    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 1153 days ago) https://github.com/sourcegraph/sourcegraph/issues/11539    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 733 days ago) https://github.com/sourcegraph/sourcegraph/pull/11920 

@keegancsmith

Completed
- [x] (🏁 1183 days ago) https://github.com/sourcegraph/sourcegraph/pull/11961 

@lguychard

Completed
- [x] (🏁 1207 days ago) https://github.com/sourcegraph/sourcegraph/issues/11513    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)

@poojaj-tech

Completed
- [x] (🏁 1207 days ago) https://github.com/sourcegraph/sourcegraph/issues/11513    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 1184 days ago) https://github.com/sourcegraph/sourcegraph/issues/11538    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 1153 days ago) https://github.com/sourcegraph/sourcegraph/issues/11539    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)

@rrhyne

- [ ] https://github.com/sourcegraph/sourcegraph/issues/11698 

Completed
- [x] (🏁 1207 days ago) https://github.com/sourcegraph/sourcegraph/issues/11529    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 1184 days ago) https://github.com/sourcegraph/sourcegraph/issues/11725    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)

@rvantonder

Completed
- [x] (🏁 1191 days ago) https://github.com/sourcegraph/sourcegraph/pull/11939 

@sqs

Completed
- [x] (🏁 1207 days ago) https://github.com/sourcegraph/sourcegraph/issues/11513    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)

## Project status and roll out tasks

- [ ] Notifiy marketing when feature flag is enabled

**Comment by ebrodymoore** [comment]
@attfarhan could you add two logged events with these additions:
- `ViewRepositoryGroup` for when any of these individual repo group page is viewed
- `RepositoryGroupSuggestionClicked` when a suggested search is clicked (in red below)
<img width="886" alt="Screen Shot 2020-06-25 at 3 25 02 PM" src="https://user-images.githubusercontent.com/25422491/85801651-2d842100-b6f8-11ea-9cc6-21edad0e821f.png">

**Comment by attfarhan** [comment]
@ebrodymoore this is using our existing eventLogger, to go to Looker, right?

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
