### ISSUE TITLE
CTO: 3.18 Tracking Issue

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#11532]
### Podcast

[Roadmap doc](https://docs.google.com/document/d/1mxzMYIsSSwQqO1GiB1wGke0UBW2o8VTDHHaNCNl1oyU)

- [ ] Release episode 2: Ryan Djurovich
- [ ] Release episode 3: Charity Majors
- [ ] Release episode 4: Evan Culver

### Code intelligence
- [ ] Release bash code intelligence extension
- [ ] Bash exploration blog post
- [ ] Take a deep dive into LSIF and see if you can improve Java indexer

**Comment by tsenart** [comment]
Removing the tracking label since this issue is not meant to be updated by the tracking issue tool.

**Comment by tsenart** [comment]
OK, re-adding since I'm fixing the tracking issue tool to skip tracking issues such as these.
