### ISSUE TITLE
Elizabeth Stirling: On-boarding plan

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#11605]
### Week 1

- [x] General [onboarding](https://about.sourcegraph.com/handbook/people-ops/onboarding).
  - [x] Add yourself to the [team page](../../../company/team/index.md).
  - [x] Watch the [new team member intro from the CEO](https://www.youtube.com/watch?v=EVHUGZe5uts)
  - [x] Set up a recurring weekly 25-minute [1-1 meeting](../../leadership/1-1.md) with your manager (e.g., `1-1 $YOURNAME-$MANAGERNAME`).
  - [x] If you are not familiar with Git, complete the [Git introduction](git_intro.md).
  - [x] Read the first page of [Sourcegraph's user documentation](https://docs.sourcegraph.com/user).
  - [x] It might not be immediately necessary, but if you ever need to click a HubSpot link just ask for access in #sales.
  - [x] Go through the [analytics onboarding](https://sourcegraph.looker.com/projects/sourcegraph_events/files/1_home.md). This onboarding is within Looker, so if you don't have an account you can ask for access in #analytics. 
  - [x] [Add your working hours to Google Calendar](https://calendar.google.com/calendar/r/settings) so your teammates know when it is safe to add meetings to your calendar.
- [x] Engineering [onboarding](https://about.sourcegraph.com/handbook/engineering/onboarding)
- [x] Review https://docs.sourcegraph.com/dev/architecture
- [x] Chat with each team and understand what they own / do.
- [x] Big picture: Review RFC 52 (State of security) and RFC 196 (secrets encryption)

### Week 2 - 8

Learn Go and parts of our code base by completing a subset of these tasks:

- [x] Send new users (added by site admin) the password reset URL over email #1519
- [x] Auth: explicit session invalidation #1126
- [x] [Security Issue #74](https://github.com/sourcegraph/security-issues/issues/74)
- [x] Send email notifications when important user account information is changed #7517

**Comment by unknwon** [comment]
In case not mentioned in any of linked pages, I think security hire should also own/be-part-of "security" mailing list? cc @nicksnyder

**Comment by nicksnyder** [comment]
Yes, I think this is captured by our handbook docs on the security team: https://about.sourcegraph.com/handbook/engineering/security#contact

**Comment by chayim** [comment]
For _Chat with each team and understand what they own / do._ I found it extremely helpful to have specific members, adding some here:

- [ ] @felixfbecker 
- [ ] Web: **@marekweb** 
- [ ] Code Intelligence: **@gbrik** 
- [ ] Distribution: @slimsag

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by nicksnyder** [comment]
@ElizabethStirling instead of adding this to the milestone, can you individually add issues that you plan on doing in 3.20 to the milestone directly?
