### ISSUE TITLE
Web 3.18 Tracking issue

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#11619]
#### OKRs

1. **Product: Surface value metrics and [code insights](https://drive.google.com/a/sourcegraph.com/open?id=1EHzor6I1GhVVIpl70mH-c10b1tNEl_p1xRMJ9qHQfoc) for engineering leaders.** \
   KR: Sales uses prototypes or design mocks in 10+ demo calls. \
   KR: Compile list of top 10 questions engineering leaders have about their organization’s code. \
   KR: Code insights feature is validated and included with deals in Q3 pipeline with [*$N<sub>3</sub>*][N3] weighted IARR.
1. **Product: Deliver on projects to grow awareness and usage.** \
   KR: [Sourcegraph.com WAU](https://sourcegraph.looker.com/looks/521) grows by 5x to [*N<sub>6</sub>*][N6] WAU. \
   KR: MQLs from Sourcegraph.com contribute [*$N<sub>7</sub>*][N7] weighted pipeline (closing in Q3 and earlier). \
   KR: ≥[*N<sub>9</sub>*][N9] WAU total for [code host integrations](https://sourcegraph.looker.com/explore/sourcegraph_events/server_weekly_usage?qid=168XAjjRvou3zkSc2gvpeK&origin_space=129&toggle=vis) at customers, and ≥[*N<sub>10</sub>*][N10] WAU each for public code hosts (GitLab.com, GitHub.com)
1. **Web: Pay down tech/design debt.** \
   KR: Each web team member devotes 2d per milestone to work on tech debt issues. \
   KR: The web team devotes 3d per milestone to work on design debt issues.
1. **Web: Increase test coverage and reliability.** \
   KR: Increase TypeScript test coverage from 34% to 55%. ![TypeScript coverage](https://codecov.io/gh/sourcegraph/sourcegraph/branch/master/graph/badge.svg?flag=typescript) \
   KR: Grow number of Percy snapshots from 8 to 40. [![Storybook screenshots](https://sourcegraph.com/search/badge?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+f:%5C.story%5C.+add%28&patternType=literal&label=storybook+screenshots)](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+f:%5C.story%5C.+add%28&patternType=literal)

#### Plan

This iteration, we want to **improve our confidence in shipping releases without relying on e2e/e2e regression tests**. In order to do this, we will:
- Build out an [integration tests infrastructure](https://github.com/sourcegraph/sourcegraph/issues/10037) that meets the following criteria:
    - Easy to add
    - Easy to update
    - Reliable
    - Fast
- Port relevant e2e regression tests to this infrastructure.

We are taking notes on our day-to-day work in this [living document](https://docs.google.com/document/d/10T_S8cGyBrudMlXSOeSsfh8aioHbIcw0uRAYTNRB9yk/edit#heading=h.fbz0159iowk2).

### Availability

Period is from **June 22d** to **July 17th**. Please write the days you won't be working and the number of working days for the period.

- @lguychard: 13d (off July 4th through 14th)
- @twop: 19d (July 3rd)
- @attfarhan: 15d (out July 6th through 10th)
- @felixfbecker: 19d
- @marekweb:

### Planned Work

@felixfbecker

- [x] Update to the new Sourcegraph logo [#12008](https://github.com/sourcegraph/sourcegraph/issues/12008) 
- [x] Use mocha directly for integration tests and move to shared/ [#12130](https://github.com/sourcegraph/sourcegraph/pull/12130) :shipit:

@lguychard: __0.50d__

- [x] sourcegraph/security-issues [#72](https://github.com/sourcegraph/security-issues/issues/72) 
- [x] Improve privacy messaging before requesting addition of repository [#11044](https://github.com/sourcegraph/sourcegraph/issues/11044) __0.5d__ 
- [ ] ~Improve clarity of the extensions registry~ [#11743](https://github.com/sourcegraph/sourcegraph/issues/11743) 
- [x] Add UI integration tests backed by Polly [#11898](https://github.com/sourcegraph/sourcegraph/pull/11898) :shipit:

@marekweb: __4.00d__

- [ ] ~Bitbucket Server native integration prevents file header text from wrapping~ [#11110](https://github.com/sourcegraph/sourcegraph/issues/11110) 🐛
- [ ] ~Phabricator: hover tooltips showing on wrong line in diff views~ [#11378](https://github.com/sourcegraph/sourcegraph/issues/11378) [👩](https://app.hubspot.com/contacts/2762526/company/554275594)🐛
- [x] Add puppeteer integration tests [#10037](https://github.com/sourcegraph/sourcegraph/issues/10037) __4d__ 

@rrhyne: __0.50d__

- [x] External services banner message is unclear [#11640](https://github.com/sourcegraph/sourcegraph/issues/11640) __0.5d__ 

@tsenart

- [ ] ~Add 'activity histogram' to admin usage stats + rearrange~ [#11063](https://github.com/sourcegraph/sourcegraph/issues/11063) __2d__ 

@twop

- [x] Audit current e2e / regression tests, and identify which should be ported to integration tests [#11869](https://github.com/sourcegraph/sourcegraph/issues/11869)

**Comment by nicksnyder** [comment]
Can you please add a section at the top to describe "why" we are working on these things and how these things tie back to OKRs.

Here is an example for code intel: https://github.com/sourcegraph/sourcegraph/issues/11412

**Comment by felixfbecker** [comment]
@nicksnyder added a section. @sourcegraph/web if I missed anything, please add it :)

**Comment by lguychard** [comment]
## Week 26 update
- Code review and pairing on RFC 155 (extensions) and RFC 173 (Firefox) tasks
- Fixed an issue in the frontend query parser: https://github.com/sourcegraph/sourcegraph/pull/11524
- Tackled some work on https://github.com/sourcegraph/sourcegraph/issues/10899 to free up some focus for the rest of the team: https://github.com/sourcegraph/sourcegraph/pull/11782, https://github.com/sourcegraph/sourcegraph/pull/11784 (to be continued)
- Working with the web team on 3.18 priorities.
- Documented target team structure for the web team https://github.com/sourcegraph/about/pull/1108

## Week 27 plan
- On holiday next week: tying up loose ends before that.
- Work on changes to hiring process.

**Comment by felixfbecker** [comment]
### W26 update

- Worked and trigrammed on RFC155
- Planned code insights for https://app.hubspot.com/contacts/2762526/company/557692737
- Worked on CSS-based draggable grid for persistable dashboards

### W27 plan

Will update after web sync

**Comment by marekweb** [comment]
### W26 update

- Finished work on #11535 to fix issues #11369, #11371

### W27 plan

- Fix two bugs which have been flagged as high priority
  - #11110
  - #10595 

- Phabricator issue #11378

- rest of week TBD

**Comment by lguychard** [comment]
## Team update

- We identified pains with split focus slowing the team down.
- To solve this, we made the decision to focus the team on **delivering comprehensive integration tests for the Sourcegraph frontend**, to help alleviate the pains of release testing.
- Given this change in focus, will **not** meet the following OKR:
> KR: ≥[N9][N9] WAU total for code host integrations at customers, and ≥[N10][N10] WAU each for public code hosts (GitLab.com, GitHub.com)
- We deprioritized:
    - Feature work on the browser extension (#10589, #10409, #10595) 
    - Feature work on code insights
- We completed all engineering work towards [making our Firefox extension compliant with AMO guidelines](https://docs.google.com/document/u/1/d/1YN9xdRD7RhAkCrR2RYbIQpYrC_wrVNteuzp_nCguuoI/edit). We are awaiting a response from AMO on that front, as we're currently blocked from submitting updates.

**Comment by nicksnyder** [comment]
Thanks for the updates!

@twop @felixfbecker @marekweb I just wanted to share that I really like the format of the updates in these other tracking issues (i.e., more prose less lists):
- https://github.com/sourcegraph/sourcegraph/issues/11523#issuecomment-651177855
- https://github.com/sourcegraph/sourcegraph/issues/11494#issuecomment-651120375
- https://github.com/sourcegraph/sourcegraph/issues/11613#issuecomment-650936066

**Comment by twop** [comment]
### W26 update
Worked on RFC 155 paired(teamed up?) with @lguychard and @felixfbecker  to work on hover provider registry (tnx!)

- making extestionAPI be available as a Promise to simplify bootstapping + fixed raced condition for query transformers
(#11669)

- Move hover provider registry to the web worker (#11570). Rewrote/added tests and extracted common functionality into `callProviders` function.

### W27 plan
landed today (#11570)
Going to research how to stub out graphQL queries/responses in a typesafe manner for our focus this iteration: integration/e2e tests.

**Comment by lguychard** [comment]
**Last week**: The week started with a bit of firefighting caused by a ["fun" caching problem](https://sourcegraph.slack.com/archives/C07KZF47K/p1593507822492200).

My main goal for the week was to tackle all the small misc issues left in our iteration plan, so that the team could focus on integration tests next week. Two of my branches are outstanding, please review and merge (https://github.com/sourcegraph/sourcegraph/pull/11850, https://github.com/sourcegraph/sourcegraph/pull/11784)!

I handed off the [current state of my work on integration tests](https://github.com/sourcegraph/sourcegraph/pull/11898) for the team to take over in the next 1.5 weeks, and had two catch-ups with the team to talk about approaches & task breakdown on that front.

Two disappointing news:
- I worked on updates to the site admin usage stats page, but it turns out the direction has changed here, so this will not ship: https://github.com/sourcegraph/sourcegraph/pull/11936
- I worked on the extension registry clarity task, but the most impactful change (hiding code intel extensions by default) turned out to be a bit more complicated than I expected, so I could not fit it in: https://github.com/sourcegraph/sourcegraph/issues/11743#issuecomment-653610728

**Next week**: holidaying 🌴 , back on July 15th!

**Comment by twop** [comment]
**Last week**

landed "Move hover provider registry to the web worker" (#11570). After that I switched to working on integration tests.

Made a research on how to mock graphQL queries in a typesafe manner here https://github.com/twop/gql-api-stub-demo. I haven't presented the research to the team yet but it is probably going to happen on Monday, depending on our conversation I might invest more into documenting my ideas (either in the repo or in our docs).

That week is my first experience being on-call, which was not bad but stressful for me. As it turned out neither of the alerts were actionable nor descriptive, thanks @slimsag for the help! <3

started auditing our regression and e2e test with an aim to port them as UI tests with stubbed backend #11570, thus the research. Most of regression tests make sense as regression tests but less suitable for UI testing needs, we will probably port some but also write new UI tests.

Had a fun and productive tripod coding session working on @lguychard branch #11898, thanks @felixfbecker and @marekweb!

**Comment by felixfbecker** [comment]
**Last week** I worked together with Loic to finish the remaining APIs to refactor for [RFC 155](https://docs.google.com/document/d/1ikrUNVe3YVbR-JpegxhjrFdmRkTGzTLcOMkKHnOyjuE/edit) in a [branch](https://github.com/sourcegraph/sourcegraph/pull/11879). We made a lot of progress, but deliberately paused to focus on our iteration goal and not distract us with potential bugs popping up after merging. Plan is to wrap this up after branch cut.

We kicked off work on integration tests together in a trigramming session.

**This week** I will work with the team to build those integration tests. In addition to actually writing tests, this means solving these problems together:
- How we store, generate and invalidate mocked GraphQL responses.
- How we can simulate backend state changes.
- How we can write integration tests for the browser extension.

**Comment by marekweb** [comment]
*Last week*: I worked on getting Sourcegraph for Firefox finalized and approved for review. I followed up with AMO a few times to move the process along. They didn't finish the compliance review.

I worked on the small fixes for this cycle (affecting Bitbucket and Phabricator) and I got more familiar with how to set up and configure Phabricator.

*This week* I'm finishing the small fixes, I'm following up with AMO to make sure Sourcegraph for Firefox gets through and to address any issues that they may bring up, and I'm working with @felixfbecker and @twop on the integration tests.

For the integration tests I'll be targeting the browser extensions in particular.

**Comment by twop** [comment]
**Last week**
Worked primarily on codegenaration for typesafe stubbing of graphQL queries for integration tests. Landed on Friday https://github.com/sourcegraph/sourcegraph/pull/11983. As a part of it I made all queries have unique names.

I'm not super happy with the custom code I wrote based on https://github.com/Quramy/ts-graphql-plugin. We need to either upstream changes fully or maintain a proper fork of it. I think I would love us to move to https://graphql-code-generator.com/ sometime soon, but that may require some workflow changes.

On Friday I haven't had time to investigate graphql-code-generator because I was dealing with issues after rebase and tried to help @marekweb to ramp up on our progress with integration tests.

Plus, some code reviews.

**Next week**
Monday is going to be dedicating writing more tests before the fork, and I want to spend some time researching graphQl tools to reduce technical debt I introduced with codegen. The rest of the week is TBD.

**Comment by felixfbecker** [comment]
**Last week** I executed on our integration test plan. I implemented a way to mock GraphQL responses, mock index.html and `window.context` and added mock responses for the two test suites we have with the new API. I also added our new integration tests to CI with coverage tracking.
In between I had meetings with members of the design team for the new breadcrumb design, the repogroup homepages/new web-style pages and our design/engineering process/infrastructure. Also did a small PR to handle the logo update.
**This week** I will invest a bit of time (<1D) to try to refactor the helpers so the browser extension can be tested too. I'll invest the rest before branch cut (>1D) to write as many tests as possible in the new suite and bring it into a state where the distribution team can rely on it this iteration for testing (docs and relevant e2e/regression tests deleted).
For the rest of the week the plan is not set yet, but I'm thinking to pick up the last remaining work on RFC155, and look at actionable tasks from the discussions with design.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by lguychard** [comment]
**Last week** was a short week for me, and I spent most of it catching up / reading on what happened while I was gone. I also pitched in to help with fixing regression tests prior to the release -- really looking forward to getting rid of those 🙂 

**This week** I want to plan the [3.19 milestone for the web team](https://github.com/sourcegraph/sourcegraph/issues/12293), by working with the team on defining [goals](https://github.com/sourcegraph/about/pull/1177).
