### ISSUE TITLE
Distribution: 3.18 Tracking issue

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11646]
#### Support new and existing deployments

This is an ongoing expense, and based on the current state of customers we anticipate this taking taking no more than 10d of work spread across the entire team.

#### Reduce upgrade overhead

Upgrading Kubernetes deployments requires customers spend a lot of engineering time to converge our released Kubernetes manifests with their fork as documented in [RFC-141](https://docs.google.com/document/d/1tsksAlqe77NmdPLw7oyy2u0-1rYDQeVpPeDo1T0Xt50).

We have evaluated and eliminated Bash and Cue as solutions to this problem, and have partially evaluated [Dhall](https://dhall-lang.org/). We will continue to evaluate [Dhall](https://dhall-lang.org/) more extensively this iteration by dogfooding it on k8s.sgdev.org.

#### Reduce support burdens

Investigating and troubleshooting problems with deployments currently requires a lot of overhead to retrieve all necessary information. We will improve documentation around tooling and services to simplify data collection in customer issue reports and streamline observability tooling.

#### Onboard @pecigonzalo

As the team grows, the management overhead of the teams makes it harder for engineers to focus on our objectives and OKRs. We will finalize the initial onboarding and handover of processes to @pecigonzalo.

#### Improve reliability sourcegraph.com alerts

Sourcegraph.com alerting does not use our new monitoring stack we ship to customers and has flaky alerts due to that and site24x7. We will begin using the new monitoring stack on Sourcegraph.com and explore more reliable replacements to site24x7 such as [blackbox exporter](https://github.com/prometheus/blackbox_exporter). This supports [RFC 189](https://docs.google.com/document/d/1noZf86g2QwTbFNt3XSSbMg36D-_HCptP1thMzZsgt2Q/edit)

### Availability

Period is from **June 22nd** to **July 17th**. Please write the days you won't be working and the number of working days for the period.

- @daxmc99: 1d
- @ggilmore: 1d
- @slimsag: 1d
- @bobheadxi: 1d

### Workload

@bobheadxi: __14.00d__

- [x] monitoring: provisioning alerts not consistently applied [#11571](https://github.com/sourcegraph/sourcegraph/issues/11571) __2d__ 🐛
- [x] monitoring: update sourcegraph/server to use prom-wrapper [#11473](https://github.com/sourcegraph/sourcegraph/issues/11473) __1d__ 
- [x] monitoring: automatically configure Alertmanager SMTP from site config [#11454](https://github.com/sourcegraph/sourcegraph/issues/11454) __3d__ 
- [x] monitoring: granular alerts notifications with Alertmanager [#11452](https://github.com/sourcegraph/sourcegraph/issues/11452) __2d__ 
- [x] siteAdmin: report-a-bug sometimes doesn't render alerts [#11806](https://github.com/sourcegraph/sourcegraph/issues/11806) __0.5d__ 🐛
- [x] license check failing in CI: mdi-react [#11866](https://github.com/sourcegraph/sourcegraph/issues/11866) __0.5d__ 
- [x] explore solutions for "impossible to silence monitoring alerts" [#11210](https://github.com/sourcegraph/sourcegraph/issues/11210) __2d__ 
- [ ] ~Dogfood the monitoring we ship with Sourcegraph~ [#5370](https://github.com/sourcegraph/sourcegraph/issues/5370) __2d__ 
- [x] Direct admins to Grafana when critical alerts have fired recently [#11517](https://github.com/sourcegraph/sourcegraph/issues/11517) __1d__ 
- [x] monitoring: reassess flakey/unactionable critical alerts [#12011](https://github.com/sourcegraph/sourcegraph/issues/12011) 
- [x] monitoring: alerting followups [#12026](https://github.com/sourcegraph/sourcegraph/issues/12026) __2d__ 

@davejrt: __10.00d__

- [x] Improve reliability of Sourcegraph.com site24x7 ping alerts [#10742](https://github.com/sourcegraph/sourcegraph/issues/10742) __8d__ 
- [x] Set up $BIGCUSTOMER replica with TLS and DNS  [#11875](https://github.com/sourcegraph/sourcegraph/issues/11875) __2d__ 

@daxmc99: __3.00d__

- [x] add terraform configuration for sourcegraph.com's infrastructure  [#10455](https://github.com/sourcegraph/sourcegraph/issues/10455) __2d__ 
- [ ] Prevent releasing server without latest grafana/prometheus changes [#9983](https://github.com/sourcegraph/sourcegraph/issues/9983) __1d__ 
- [ ] Sourcegraph.com - add redis-store & precise-code-intel-bundle-manager snapshotting [#10450](https://github.com/sourcegraph/sourcegraph/issues/10450) 

@ggilmore: __3.00d__

- [ ] reduce k8s upgrade merge conflicts: RFC 141: Dhall investigation [#10936](https://github.com/sourcegraph/sourcegraph/issues/10936) __3d__ 🕵️
- [ ] ~Prevent services from running out of ephemeral storage space and being evicted~ [#9604](https://github.com/sourcegraph/sourcegraph/issues/9604) __1d__ 👩
- [ ] deploy-sourcegraph-dhall: extend configuration layer for subset of services on k8s.sgdev.org [#11830](https://github.com/sourcegraph/sourcegraph/issues/11830) 
- [x] deploy-sourcegraph-dhall: bring resources up-to-date with latest deploy-sourcegraph commits [#11829](https://github.com/sourcegraph/sourcegraph/issues/11829) 
- [ ] RFC 141: prepare k8s.sgdev.org infrastructure for dhall-based pipeline  [#12104](https://github.com/sourcegraph/sourcegraph/issues/12104) 
- [ ] ~deploy-sourcegraph-dhall: frontend: implement new configuration logic for k8s.sgdev.org~ [#12105](https://github.com/sourcegraph/sourcegraph/issues/12105) 
- [ ] ~deploy-sourcegraph-dhall: grafana: implement new configuration logic for k8s.sgdev.org~ [#12109](https://github.com/sourcegraph/sourcegraph/issues/12109) 

@pecigonzalo

- [x] Run Distribution team syncs from July 6 onward [#11817](https://github.com/sourcegraph/sourcegraph/issues/11817) 
- [x] Plan 3.19 work ahead of time [#11818](https://github.com/sourcegraph/sourcegraph/issues/11818) 
- [ ] ~Reduce the impact of unplanned work~ [#11904](https://github.com/sourcegraph/sourcegraph/issues/11904) 
- [x] sourcegraph/customer [#63](https://github.com/sourcegraph/customer/issues/63) 👩

@slimsag: __4.50d__

- [ ] License report for syntect_server & its dependencies [#11269](https://github.com/sourcegraph/sourcegraph/issues/11269) __1d__ 👩
- [ ] Deploy and release: Replace Renovate with GitHub Actions [#10011](https://github.com/sourcegraph/sourcegraph/issues/10011) __0.5d__ 
- [ ] verify "syntax highlighting sometimes doesn't work" is fixed on customer instance [#9557](https://github.com/sourcegraph/sourcegraph/issues/9557) __0.5d__ 🐛
- [ ] observability: improve/restructure admin documentation [#9773](https://github.com/sourcegraph/sourcegraph/issues/9773) __0.5d__ 
- [ ] Docker Compose should be released on the 20th [#10486](https://github.com/sourcegraph/sourcegraph/issues/10486) __0.5d__ 
- [x] not possible to upgrade from 3.17.0 ("0.0.0+dev") -> next patch release [#11666](https://github.com/sourcegraph/sourcegraph/issues/11666) 
- [x] 3.17.2 patch release [#11724](https://github.com/sourcegraph/sourcegraph/issues/11724) 
- [x] 3.17.1 patch release [#11642](https://github.com/sourcegraph/sourcegraph/issues/11642) 
- [ ] sourcegraph/customer [#53](https://github.com/sourcegraph/customer/issues/53) __0.5d__ 👩
- [ ] sourcegraph/customer [#49](https://github.com/sourcegraph/customer/issues/49) __0.5d__ 🐛👩
- [ ] sourcegraph/customer [#62](https://github.com/sourcegraph/customer/issues/62) __0.5d__ 👩

@uwedeportivo: __4.50d__

- [x] keep e2e tests in functional state during iteration [#11886](https://github.com/sourcegraph/sourcegraph/issues/11886) __2d__ 
- [x] Release patch v3.17.3 [#11881](https://github.com/sourcegraph/sourcegraph/issues/11881) __0.5d__ 
- [x] ~deploy-sourcegraph-dhall: cadvisor: implement generate reading from config~ [#12065](https://github.com/sourcegraph/sourcegraph/issues/12065) __0.5d__ 
- [x] deploy-sourcegraph-dhall: gitserver: implement generate reading from config [#12067](https://github.com/sourcegraph/sourcegraph/issues/12067) __0.5d__ 
- [x] ~deploy-sourcegraph-dhall: github-proxy: implement generate reading from config~ [#12066](https://github.com/sourcegraph/sourcegraph/issues/12066) __0.5d__ 
- [x] deploy-sourcegraph-dhall: indexed-search: implement generate reading from config [#12068](https://github.com/sourcegraph/sourcegraph/issues/12068) __0.5d__ 
- [ ] ~deploy-sourcegraph-dhall: postgres: implement generate reading from config~ [#12070](https://github.com/sourcegraph/sourcegraph/issues/12070) __0.5d__ 
- [x] ~deploy-sourcegraph-dhall: jaeger: implement generate reading from config~ [#12069](https://github.com/sourcegraph/sourcegraph/issues/12069) __0.5d__ 
- [x] ~deploy-sourcegraph-dhall: query-runner: implement generate reading from config~ [#12072](https://github.com/sourcegraph/sourcegraph/issues/12072) __0.5d__ 
- [ ] ~deploy-sourcegraph-dhall: precise-code-intel: implement generate reading from config~ [#12071](https://github.com/sourcegraph/sourcegraph/issues/12071) __0.5d__ 
- [x] ~deploy-sourcegraph-dhall: searcher: implement generate reading from config~ [#12075](https://github.com/sourcegraph/sourcegraph/issues/12075) __0.5d__ 
- [x] ~deploy-sourcegraph-dhall: symbols: implement generate reading from config~ [#12076](https://github.com/sourcegraph/sourcegraph/issues/12076) __0.5d__ 
- [x] ~deploy-sourcegraph-dhall: replacer: implement generate reading from config~ [#12074](https://github.com/sourcegraph/sourcegraph/issues/12074) __0.5d__ 
- [x] ~deploy-sourcegraph-dhall: repo-updater: implement generate reading from config~ [#12073](https://github.com/sourcegraph/sourcegraph/issues/12073) __0.5d__ 
- [x] deploy-sourcegraph-dhall: prometheus: implement generate reading from config [#12063](https://github.com/sourcegraph/sourcegraph/issues/12063) __1d__ 
- [ ] admin docs: describes experimental validation command in the src-cli [#12001](https://github.com/sourcegraph/sourcegraph/pull/12001) :shipit:
- [ ] test validates instance [#687](https://github.com/sourcegraph/deploy-sourcegraph/pull/687) :shipit:
- [ ] validate command [#200](https://github.com/sourcegraph/src-cli/pull/200) :shipit:

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by nicksnyder** [comment]
As part of the process to finalize this tracking issue, can you please add a section at the top to describe "why" we are working on these things and how these things tie back to OKRs.

Here is an example for code intel: https://github.com/sourcegraph/sourcegraph/issues/11412

**Comment by slimsag** [comment]
What I worked on this week:

- 60% of my time spent in discussions / calls / interviews, onboarding Gonza, 1:1s with many people, extensive discussion around alerting solutions / product direction with Robert, talks about e2e/regression testing, CE pipeline review, customer support calls etc.
- 5% of my time spent writing distribution roadmap: https://github.com/sourcegraph/about/pull/1104
- 10% of my time spent onboarding Gonza
- 20% of my time spent supporting $CUSTOMER (Uwe was out this week)
- 5% of my time spent shipping 3.16.0 to $CUSTOMER and docker-compose 3.17.0

What I will focus on next week:

- Support $CUSTOMER with Uwe, transferring back to him
- Support $CUSTOMER's upgrade to 3.16.0 https://sourcegraph.slack.com/archives/CMB6K7SMN/p1593221812024100
- Distribution team sync, retrospective, planning kickoff
- Update Distribution team OKRs
- Finish Distribution roadmap PR: https://github.com/sourcegraph/about/pull/1104
- Review Nick's PR about writing Distribution weekly team updates

Things I think will not get finished:

- I am running behind on all Distribution team topics above.

**Comment by ggilmore** [comment]
This week I mainly focused on https://github.com/sourcegraph/deploy-sourcegraph-dhall for RFC 141:
- I imported the rest of the deploy-sourcegraph services
- Wrote scripts to set up a proper dev environment (linting, formatting, compiling on save)
- Added CI (also rendered in Dhall)
- Added benchmarks and opened https://github.com/dhall-lang/dhall-haskell/issues/1890 to ask for help investigating performance issues

I'm in the process of:
- incorporating the configuration layer into the newly added services
- generating a diff between https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s and https://github.com/sourcegraph/deploy-sourcegraph-dhall so that we can migrate over and do proper dogfooding

**Comment by davejrt** [comment]
**Things I worked on this week:**

- Supported $CUSTOMER with help from Stephen
- Worked on #10742 by installing prometheus blackbox exporter and alert manager on an internal replica to help correlate any errors seen by site24.x7

**Things I will focus on next week:**

- Continue to focus on $CUSTOMER with Uwe
- Extend the alerting to cover all cases in site24x7 where possible.
- Likely pick up a "good first issue" to start levelling up on GO

I will be out 30/6 for a national holiday

**Comment by bobheadxi** [comment]
**This week (week of june 22)**

* Worked on Grafana alerting follow-up pull requests (https://github.com/sourcegraph/sourcegraph/pull/11612, https://github.com/sourcegraph/sourcegraph/pull/11554), but will closing those in favour of a [new approach to alerting](https://github.com/sourcegraph/sourcegraph/issues/11452#issuecomment-648652514) after discussion with Stephen
* Was away Thursday, Friday

**Next week**

* Implement [new approach to alerting](https://github.com/sourcegraph/sourcegraph/issues/11452#issuecomment-648652514)

**Comment by nicksnyder** [comment]
Thanks for the updates!

I just wanted to share that I really like the format of the updates in these other tracking issues (i.e., more prose less lists):
- https://github.com/sourcegraph/sourcegraph/issues/11523#issuecomment-651177855
- https://github.com/sourcegraph/sourcegraph/issues/11494#issuecomment-651120375
- https://github.com/sourcegraph/sourcegraph/issues/11613#issuecomment-650936066

**Comment by bobheadxi** [comment]
## This week (week of june 29)

I [fixed a bug in our bug report page](https://github.com/sourcegraph/sourcegraph/issues/11806) and investigated a [license check issues](https://github.com/sourcegraph/sourcegraph/issues/11269). I also [implemented alertmanager configuration](https://github.com/sourcegraph/sourcegraph/pull/11832) and [found a fix (hopefully) for inconsistently applied cAdvisor alerts](https://github.com/sourcegraph/sourcegraph/issues/11571).

## Next week

Get the above PRs wrapped up so that I can implement improvements to round off the alerting experience (alert silencing, sourcegraph/server support, etc)

**Comment by pecigonzalo** [comment]
## Previous week
I have been working on the roadmap sync with Stephen to get an idea of the tasks we are working on at the moment and their respective priority. As part of my general onboarding tasks, I continue to go through our supported deployment methods and use cases to get a better understanding of each service, I successfully tested Docker (with compose), Kubernetes (with `kind`/`k3d`), local dev. I have been creating a document on each one to update any missing documentation item.

## This week
I would like to close the scope of 3.18 and start working on the plan for 3.19, aside from this I'll continue documenting each service parameters and requirements which is in line with my onboarding.

## Team updates
There will be some changes to the workload assigned to @davejrt and @uwedeportivo as we start onboarding a new customer.

**Comment by slimsag** [comment]
## Previous week

Around 60-75% of my time spent in meetings of some sort; Remainder spent onboarding Gonza, prioritizing Distribution team work, putting together our roadmap and 3.18 tracking issue, helping with security review of Sourcegraph / onboarding Chayim, and just generally helping point a lot of people in the right direction.

## This week

Aiming to finish 3.18 tracking issue, onboard Gonza more, discuss RFC 141 with Gonza/Geoffrey, review Robert's recent monitoring work, merge the distribution roadmap, sort out next steps for https://github.com/sourcegraph/customer/issues/62 and just generally play a support role to the Distribution team.

**Comment by bobheadxi** [comment]
## This week (week of jul 6)

Landed a lot of PRs around alerting (Alertmanager, dogfooding, `sourcegraph/server` alerting, fixed provisioning alerts), and have since continued to work on improvements and follow-ups in this area based on observed issues and feedback.

## Next week

Wrap up current PRs that make further improvements to alerting (https://github.com/sourcegraph/sourcegraph/pull/12046, https://github.com/sourcegraph/sourcegraph/pull/12087) to make sure the features are in a good state for 3.18, and continue expanding on [dogfooding our alerts](https://github.com/sourcegraph/sourcegraph/issues/5370) 

Considering punting [flakey/unactionable alerts assessment](https://github.com/sourcegraph/sourcegraph/issues/12011) to 3.19 - it seems that many of the alerts are real problems that are not as easy to "fix" as simply adjusting thresholds

**Comment by uwedeportivo** [comment]
## this week

worked on the validate and transitioned to dhall

## next week

help with the release and finish up with geoffrey the dhall implementation of k8s dogfood customizations

**Comment by pecigonzalo** [comment]
## Last week
Started planning of 3.19, to be discussed today. I have done some extra testing with Kustomize and `kind` to try and mimic the upgrade difficulties. I have also started having conversations with Dan on how do we route support requests and Chayim on some of the security topics.
I have closed #63 as there have been no updates, will re-open once we have more information.

## This week
Ill focus on finishing the plan for 3.19 and find a way to label unplanned tasks.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
pretend this is last friday:

this week:

mainly release with dax and i finished all my dhall assignments

next week:

3.19 planning, some small remainders from release process, continue with geoffrey on dhall (we will probably start converting dog-food and start capturing all the kustomize customizations and twitter and apple customization)

**Comment by slimsag** [comment]
## Last week

I spent ~60% of my time on https://github.com/sourcegraph/customer/issues/62#issuecomment-661266320 and made great progress but with many context switches / interruptions throughout. I was sidetracked regularly by::

- team sync, seven 1:1s
- assisting with the release process (adding docker-compose release docs, debugging CI failures, etc)
- (~6h) debugging customer issues [1](https://sourcegraph.slack.com/archives/CTQ5LTF8D/p1595024750050300) [2](https://sourcegraph.slack.com/archives/C0B2RU51Q/p1595017746022600?thread_ts=1594949170.013000) [3](https://sourcegraph.slack.com/archives/CJX299FGE/p1595010997073000?thread_ts=1595010607.071900) [4](https://sourcegraph.slack.com/archives/CJX299FGE/p1594949631025100?thread_ts=1594949631.025100) [5](https://sourcegraph.slack.com/archives/CTGBWCKM0/p1594938548021600?thread_ts=1594924448.020600) [6](https://sourcegraph.slack.com/archives/CJX299FGE/p1594929560008800?thread_ts=1594929412.008000)
- helping devs here: [test their changes](https://sourcegraph.slack.com/archives/CJX299FGE/p1594951982030300?thread_ts=1594949711.026400), [debug dot-com issues](https://sourcegraph.slack.com/archives/CMBA8F926/p1594935782146100?thread_ts=1594934056.141800), [collecting some usage data](https://sourcegraph.slack.com/archives/CJX299FGE/p1594926820493600?thread_ts=1594926820.493600), [adding architecture diagrams](https://sourcegraph.slack.com/archives/CJX299FGE/p1594919940478700?thread_ts=1594919940.478700), and more.

## This week

I intend to:

- Finish and merge the distribution roadmap. 
- Finish and merge https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/1
- Assist several customers and devs.
