### ISSUE TITLE
☂️ Clean up the database package

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#11676]
There are some issues with our current database layer, including:

1. Use of global connection which must be set up properly in app startup. This bit me recently in [#11648](https://github.com/sourcegraph/sourcegraph/pull/11648/files#diff-aa0ae9081968857088900bb25af6bf6fR95) when I needed to be able to get a repo record to pass to ResolveRev from the precise-code-intel-worker.
2. Use of global singleton values for the db interface, which requires the global connection be first set up. This also affects how we can test, which pollutes the called code (not the calling code) with mock checks. This may be a point of opinion contention (https://github.com/sourcegraph/about/pull/1060#issuecomment-647959911), but I think this makes testing dependent code more difficult and makes the called code more difficult to read due to the mock conditions at the top of each function.
3. Bad package location: the db package exists in cmd/frontend/db, but is imported by repo-updater, etc. This should be moved into internal (and, if necessary, guard the imports with CI checks if it's still an issue, again see #11648 above).
4. Bad interop with other db packages. I'm a fan of not having a "god" package for db interaction, which means I would prefer to keep campaigns, codeintel, repo (etc) stores separated where possible. However, the callers often need two or more of these (code intel and campaigns both need their own stores and also need some repository data). It's currently not possible to use two stores within the same transaction. cc @mrnugget 

**Issues**

- [x] @asdine Link to an issue/plan description for de-globalizing the stores here
- [x] [Move the database package (#11677)](https://github.com/sourcegraph/sourcegraph/issues/11677)
- [x] [Make store interfaces interoperable (#11678)](https://github.com/sourcegraph/sourcegraph/issues/11678)
- [ ] [Investigate github.com/cockroachdb/copyist for faster tests](https://github.com/sourcegraph/sourcegraph/issues/12097)
- [ ] [Testing packages](https://github.com/sourcegraph/sourcegraph/issues/12129)
- [ ] Investigate switching to pgx (https://github.com/jackc/pgx)

**Comment by mrnugget** [comment]
Another issue:

5. The `db` package is the only one with `authz` support. So if you need to respect repository permissions in our own package (as we do in `campaigns`), you either need to port `authzFilter` (which you shouldn't do and which would probably pull in many other dependencies from `db`) to your own package or you need to use `db.Repos.*` in your own package, mixing it with another store implementation.

**Comment by mrnugget** [comment]
Another problem that's not a huge problem with the status quo but could make cleaning up & refactoring harder:

6. The `campaigns` code needs to stay in `enterprise/`. We can't move it to a non-enterprise package. That limits the options we have in regards to unifying store implementations in a single package. (An option might be to have sub-stores, like `db.Repos`, which are only initialised at runtime. That has its own problems, but might be a way.)

**Comment by tsenart** [comment]
Thanks for writing this up! For as long as we have a shared database between services with foreign key relationships between different tables, I think that having a single Store package makes sense:

- Joins between different tables and specialized queries become OK.
- More code reuse.
- Single place to enforce authorization.
- Easy for new engineers to query any data they need and learn how to read/write to "the database".

**Comment by efritz** [comment]
> I think that having a single Store package makes sense
 
 I’m actually advocating against combining stores due to #4 and #6. My proposal is to keep them separate but make them be able to interoperate (see the linked issue in the issue description).

Campaigns and codeintel are both enterprise-only so we’d need at least an enterprise and OSS db package. 

Additionally, I am having other pain points with large packages due to ownership - the current frontend db and graphql packages are already too large. Having separate stores based on feature lines make a lot of sense as that’s how the engineering team is organized.

**Comment by mrnugget** [comment]
Orthogonal to the problems discussed above, but related:

- We have `dbtest.NewDB` and `dbtesting.SetupGlobalTestDB`. Both do the same thing: create a new test DB. The former, though, drops the DB at the end of the test, whereas the latter truncates the table in every test if the test db already exists. We should have a single package to create a test DB. Ideally one that doesn't create/drop tables in between tests all the time, because it's cumbersome having to nest Go tests that use the DB because using separate `func Test*` functions would be too costly (since they require new DB instances).

**Comment by tsenart** [comment]
@efritz: @asdine has the bandwidth to work on this now so I think it'd be good for him to pick this up. Would you have a chat with him to provide all the context needed?

**Comment by efritz** [comment]
No problem. I’ll look out for a meeting invite.

**Comment by asdine** [comment]
Here is a summary of the discussion with @efritz:

### First step

The first step would be to pass a reference of each store wherever they're needed instead of using the globals. These stores would be instantiated in each program's respective main function and be carried out as parameters / struct fields to the rest of the code. Internally each store would still be using the global `dbconn` though, which could be renamed into something embarrassing to avoid forgetting about it.
Each store would be transformed one by one in separate PRs.

### Second step

Once a store is not being used globally anymore, change its API so it makes use of the common `store` interface (see #11678)

### Third step

Once all the stores have been migrated and `dbconn` isolated, remove the global `dbconn` and instead instantiate it in each program's main function and pass it to the each store that needs it.

**Comment by efritz** [comment]
Remaining issues seem to have diverged from new goals. We've done it! 🎉
