### ISSUE TITLE
Bigdata customer Tracking issue

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#11717]
### Status

This tracking issue is being prepared.

### Workload

@Unassigned

- [x] repo-updater organization synching takes forever [#11684](https://github.com/sourcegraph/sourcegraph/issues/11684) 👩
- [ ] cloning never "finishes" [#11397](https://github.com/sourcegraph/sourcegraph/issues/11397) 
- [ ] indexing never "finishes" [#11396](https://github.com/sourcegraph/sourcegraph/issues/11396) 
- [ ] searching for rare strings with count:x qualifier in large installation (xxx k repos) times out [#11395](https://github.com/sourcegraph/sourcegraph/issues/11395) 
- [ ] Support repo refresh via github webhook [#11391](https://github.com/sourcegraph/sourcegraph/issues/11391) 
- [ ] progress indicator of state of indexing [#11202](https://github.com/sourcegraph/sourcegraph/issues/11202) 
- [ ] code host status panel text should be selectable [#11201](https://github.com/sourcegraph/sourcegraph/issues/11201) 
- [x] cloning does not restart after gitservers are replaced [#11091](https://github.com/sourcegraph/sourcegraph/issues/11091) 

@asdine: __4.00d__

- [ ] repository status page with "cloning" filter is extremely slow [#11029](https://github.com/sourcegraph/sourcegraph/issues/11029) __4d__ 

@keegancsmith

- [x] errors seen in indexed-search on bigdata cluster with 250k repos [#11200](https://github.com/sourcegraph/sourcegraph/issues/11200) 
- [ ] Failing index continues to retry without indication of problems on UI [#11045](https://github.com/sourcegraph/sourcegraph/issues/11045) 

@uwedeportivo

- [x] repo-updater: make handleStatusMessages log entry shorter and more useful [#11203](https://github.com/sourcegraph/sourcegraph/issues/11203) 
- [ ] default log level should not be "debug" [#11119](https://github.com/sourcegraph/sourcegraph/issues/11119) 
- [ ] sourcegraph/customer [#57](https://github.com/sourcegraph/customer/issues/57) 👩
- [x] repoupdater: do not log big data structures [#11092](https://github.com/sourcegraph/sourcegraph/pull/11092) :shipit:

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
