### ISSUE TITLE
Update browser extension toolbar UI

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#1178]
The browser extension toolbar is currently very crowded and needs to have a reworked UI.

This will also include HIG for Sourcegraph extensions that contribute to the toolbar.

## 3.0 Milestone

- [x] "Inline discussions" should not be a long text label, it should be an icon
- [x] "View file (base/head)" should be a single button and link to the Sourcegraph diff

## 3.1 Milestone
- [ ] Create HIG for extensions on the toolbar @francisschmaltz 
- [ ] Further UI/UX improvements

Designs:
https://app.zeplin.io/project/5bc77dcbe0bf72191e780d3c/screen/5c14420c2e3f28242489dbcb

**Comment by nicksnyder** [comment]
IIRC we decided against moving in this direction.

**Comment by ijsnow** [comment]
I don't recall that decision. I think it will be imperative that we do this. It's already bad and the number of extensions is just going to keep going up.

**Comment by nicksnyder** [comment]
@sqs Can you comment?

**Comment by sqs** [comment]
@francisschmaltz 	and I just talked about this, and he is going to fix the situation as is by:

1. recommending changes to existing extensions to improve this immediately without needing to write any more code (eg "Inline discussions" should not be a long text label, it should be an icon; "View file (base/head)" should be a single button and the label can be shortened or just made into an icon)
2. writing a HIG for extension authors (even a quick one is good) in the `doc/extensions/` dir to describe how they should make their extensions to avoid this problem (eg "don't use long labels, use an icon instead")

Next up will be letting extensions put their action in a dropdown menu, like VS Code does.

**Comment by francisschmaltz** [comment]
I'll work on writing HIG for extensions in code hosts, but this will be targeted for 3.1. @ijsnow Can you get the updated designs integrated by 3.0?

**Comment by francisschmaltz** [comment]
Working on the HIG for extensions in code editors and here are the main points:

**Comment by sqs** [comment]
Correct - @francisschmaltz please update this issue accordingly and either address those 2 issues or reassign to someone else

**Comment by francisschmaltz** [comment]
@nicksnyder can you assign someone to do the following:

**Comment by nicksnyder** [comment]
> "View file (base/head)" should be a single button

What happens when you click this button?

**Comment by francisschmaltz** [comment]
The single diff button should link to the Sourcegraph diff page.

**Comment by nicksnyder** [comment]
@attfarhan can you do the two 3.0 milestone items here?

**Comment by attfarhan** [comment]
What's HIG? @ijsnow

**Comment by nicksnyder** [comment]
https://en.m.wikipedia.org/wiki/Human_interface_guidelines

**Comment by attfarhan** [comment]
I opened a [PR](https://github.com/sourcegraph/sourcegraph-code-discussions/pull/11) to solve this:

>  "Inline discussions" should not be a long text label, it should be an icon

@francisschmaltz suggested punting this particular item to 3.1 because theming of icons is not possible right now without some css hacks. Francis can you either open an issue or explain here how you suggest/propose we handle theming?

**Comment by sqs** [comment]
It is better to have an icon that doesn't look great in one of our themes, vs. having a long label. So please change it to the icon (and do the best you can to find a color that is at least visible in both themes). Prefer it working ok in the light theme because all code hosts are in the light theme.

**Comment by francisschmaltz** [comment]
@sqs this is worse. We should just replace it with “discussions” until we can do it right. The icon looks bad.

**Comment by francisschmaltz** [comment]
We should be able to use an SVG for the icon so we can change the fill color with the theme.

**Comment by sqs** [comment]
Great, go make one or both of those happen :)

**Comment by slimsag** [comment]
Something else I forgot: when making changes to the discussions extension rendering, be careful about how it displays on sourcegraph.com; if we went with the icon we would have had two discussion-like icons in the toolbar:

![image](https://user-images.githubusercontent.com/3173176/51090480-c52ac500-1739-11e9-8011-55c4126a55d1.png)

Because inline discussions is different than showing discussions for the file.

**Comment by slimsag** [comment]
Filed https://github.com/sourcegraph/sourcegraph/issues/1851

**Comment by sqs** [comment]
The 3.0 issues in the issue description are checked off. Moving to milestone 3.1.

**Comment by nicksnyder** [comment]
It is unclear to me what work remains here since the unchecked boxes in the original issue description are pretty vague.

I am going to close this issue. If there is unfinished work hear, please open new and separate issues for each work item.
