### ISSUE TITLE
Backend debt tracking issue

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#11792]
This issue is intended to be used to aggregate backend debt and at the moment is just a first pass of keeping the list of ideas in one place.

For now, just copied @efritz's list from Slack

- [ ] Globals (enterprise setup, db layer, mocks)
- [ ] Legacy mocks patterns and dependency injection are kind of a mess
- [ ] Multiple store layers have the same txn pattern with no code reuse (and is hard to share txns between different stores - campaigns is hitting this pain point)
- [ ] There are issues with the graphql resolvers (I know they’re related to the library we use, but I’m not sure what particular issues we want to address here - @keegan please elaborate if you could here)
- [ ] our dev scripts are giant inaccessible ball of intra-referential chaos
- [ ] not sure if we still define some images in sg/infrastructure instead of here, maybe that’s cleared up by now
