### ISSUE TITLE
Checklist for 3.0-preview on Sourcegraph.com

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1187]
Tasks that must be completed before removing lsp-proxy from Sourcegraph.com and switching over to extensions for everything:

- [x] @chrismwendt  `lang-go`: Increase concurrency of external references
- [x] @sqs Sourcegraph extension API: add support for extensions emitting external refs https://github.com/sourcegraph/sourcegraph/pull/1191
- [x] @chrismwendt `lang-go`: uncomment `registerExternalReferencesProvider` (in addition to the normal references provider)
- [x] @chrismwendt `/go/` links: reimplement using https://golang.org/pkg/go/doc/#Package.Filter https://github.com/sourcegraph/sourcegraph/pull/1197
- [x] @chrismwendt Add HTTPS support to gddo-proxy https://github.com/sourcegraph/infrastructure/pull/752
- [x] @chrismwendt Fix erroneous assumption that import paths are the same as repos in [lang-go](https://github.com/sourcegraph/lang-go/blob/2944f6e9cea0effe0487b97347983554c7abe17e/src/lang-go.ts#L371)
- [x] @ijsnow Codecov extension: disable by default; run migrations to enable for anyone who has entered a token
- [x] @ijsnow Browser extension: always use extensions when Sourcegraph URL is Sourcegraph.com (disregarding the checkbox)
- [x] @ijsnow DB migration to enable the Codecov extension for any user that also has other `codecov.*` settings
- [x] @sqs Blog post https://github.com/sourcegraph/about/pull/64 and tweet
- [x] @sqs Python #959 
- [x] @sqs Enable basic code intel for all users https://github.com/sourcegraph/sourcegraph/pull/1240  https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/8 https://twitter.com/srcgraph/status/1070628324542603265
- [x] @sqs add more basic-code-intel langs

**Comment by ijsnow** [comment]
Can’t think of anything immediately worrying about enabling extensions for browser extensions pointed at sourcegraph.com but I'm adding sentry to the browser extension to monitor errors (we should have this either way).

**Comment by sqs** [comment]
Tomorrow, I'll get the `ext-codeintel` branch (#584) ready with test plans for other people to start testing, in advance of switching Sourcegraph.com over and cutting the release this week.

I will also merge the external references provider stuff tonight (Mon night). The remaining things assigned to me in this issue won't take beyond Tue afternoon.

**Comment by ijsnow** [comment]
I've

1. Added a migration to the browser extension to enable codecov in client settings if we can tell they've used the extension *
2. Enabled codecov for users on sourcegraph.com if we can tell they've used the extension*
3. Removed codecov from the global settings on sourcegraph.com

* E.g. added a token, toggled coverage
