### ISSUE TITLE
Feedback for Custom Search Pages and new Homepage Design

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#11922]
#### High priority bugs

- [x] 404 bug: #11961
- [x] Dark theme Kubernetes icon fix
   - Issue: #11956 
   - PR: #12038
- [x] Remove fancy quotes in message 
   - Issue: #11953 
   - [PR #12061](https://github.com/sourcegraph/sourcegraph/pull/12061#discussion_r452519930)
- [x] Lots of content fixes! #11939
- [x] Fix responsiveness for sections below list of repository groups 
   - Issue: #12040
   - PR: #12080 
   - Context:
      - #11783 (comment)
      - [Slack convo](https://sourcegraph.slack.com/archives/C0HMGV90V/p1594171649071100)
- [x] Indexing repos #11962
- [x] Border-radius on repogroup page #11955 
- [x] Fix contrast in dark theme, headings, links
   - PR: #12078
   - Design: [New styles updated in Figma ](https://www.figma.com/file/Xc4M24VTQq8itU0Lgb1Wwm/RFC-159-Visual-Design?node-id=0%3A1&viewport=-4312%2C-352%2C1)
- [x] Repogroup page copy feedback: #12057
   - PR: #12084 
- [x] Repogroup page search bar should be populated with the repogroup #12083 
- [x] [RepogroupPage should wrap responsively](https://github.com/sourcegraph/sourcegraph/pull/11783#discussion_r449064515)
- [x] Distinguish code and non-code text by font 
- Issue: [#12057](https://github.com/sourcegraph/sourcegraph/issues/12057#issue-654306195)(bullet 2)
- PR: https://github.com/sourcegraph/sourcegraph/pull/12078/

#### Original PR feedback

- [x] [Represent exampleQuery as JSX expression not HTML string](https://github.com/sourcegraph/sourcegraph/pull/11783#discussion_r449047593)
- [ ] [Use all SVG logos, and use JSX expression](https://github.com/sourcegraph/sourcegraph/pull/11783#discussion_r449049081)
- [x] [Fix leading whitespace](https://github.com/sourcegraph/sourcegraph/pull/11783#discussion_r449049691)
- [ ] [Update repogroup filenames to have proper casing](https://github.com/sourcegraph/sourcegraph/pull/11783#discussion_r449050247)
- [ ] [Search page growth](https://github.com/sourcegraph/sourcegraph/pull/11783#discussion_r449056041)
- [ ] [Use classNames() for better readability](https://github.com/sourcegraph/sourcegraph/pull/11783#discussion_r449063728)
- [ ] [Color and Font related manual overrides and inconsistencies](https://github.com/sourcegraph/sourcegraph/pull/11783#discussion_r449052724)

#### Feature Suggestions

1. count:xxx or lang:xxx is repeated often, too busy visually?
2. Copy-paste ability for search syntax on page
   - feedback: "might be nice to have this text be accompanied by a copy button and/or have it prefilled in the search box :mag:"
![image (3)](https://user-images.githubusercontent.com/57463526/86499206-c17c6b00-bd3e-11ea-83c3-67df61f52d52.png)
3. Hide/Collapse suggestions on the /search homepage if it feels busy

**Comment by tsenart** [comment]
Even though the page loads correctly afterwards, I'm getting a 404 first which confuses the browser.

<img width="1428" alt="Screenshot 2020-07-03 at 10 20 20" src="https://user-images.githubusercontent.com/67471/86448379-f83e8b00-bd16-11ea-9127-00267aadb7d6.png">

**Comment by rvantonder** [comment]
https://github.com/sourcegraph/sourcegraph/pull/11939

**Comment by rvantonder** [comment]
Feedback: we should add references (i.e., links) to the patterns ('python print 2 statements should now look like this') or the android nested XML example. Just having a query there with the one-liner title makes this feel incomplete (I have more questions than answers when looking at the queries like, "why search for this?" or "why does this matter?" [example](https://github.com/sourcegraph/sourcegraph/pull/11939/files#r449704236) and I'm guessing if I don't really understand the context it's going to happen for many who haven't seen these pages before :P)

**Comment by rvantonder** [comment]
> might be nice to have this text be accompanied by a copy button and/or have it prefilled in the search box

Via @bobheadxi

**Comment by rvantonder** [comment]
> Which repos are these/what are they for?

Paraphrasing feedback from @asdine on the Go repo page. We should mention that these repos are the top 100 Go repos on GH.

**Comment by poojaj-tech** [comment]
@felixfbecker: Tracking this here to fix the bug on responsiveness you pointed out:
https://github.com/sourcegraph/sourcegraph/pull/11783#r449064515

**Comment by bobheadxi** [comment]
Not sure if this is the right issue for it, but re: the image in https://sourcegraph.slack.com/archives/C0EPTDE9L/p1594256613186200 will it be possible to collapse/hide the suggestions on the `/search` homepage? It seems like the first image in that message is going to be the default landing page and it seems very busy compared to the look currently on sourcegraph.com

**Comment by rvantonder** [comment]
@poojaj-tech this one is also a "must": https://github.com/sourcegraph/sourcegraph/issues/11956

This cosmetic one we can live with for now (I don't have time to look into it, but you or Rob might have an idea with the CSS): https://github.com/sourcegraph/sourcegraph/issues/11955

**Comment by poojaj-tech** [comment]
> Not sure if this is the right issue for the new homepage, but re: the image in https://sourcegraph.slack.com/archives/C0EPTDE9L/p1594256613186200 will it be possible to collapse/hide the suggestions on the `/search` homepage? The new one seems very busy compared to the look currently on sourcegraph.com

@bobheadxi thanks for the feedback, you are right --> it is busier with more content on the homepage (default landing) now. We don't have have a way to collapse/hide the suggestions yet. One thing to note: we will be adding more repo pages soon that will shift down the "example  searches", "search a language" and and "search syntax" section and help reduce the business. I also zoomed in to fit everything in the screenshot I posted in Slack, zooming to 100% on my 13 inch macbook looks
<img width="1436" alt="Screen Shot 2020-07-08 at 6 18 16 PM" src="https://user-images.githubusercontent.com/57463526/86986098-adbe7380-c147-11ea-99ef-0828429ac2b8.png">
 like this:

**Comment by poojaj-tech** [comment]
@rvantonder agree that fixing  #11956 is a must. Looking into it right now. I will also go over the 3.18 tracking issue to check any other bugs filed I may have missed -- thank you for linking these.

**Comment by christinaforney** [comment]
There are still open issues, this should not have been closed yet.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
These seem done, let's close the issue @poojaj-tech?

**Comment by poojaj-tech** [comment]
yep, closing. @attfarhan please re-open if you think otherwise.
