### ISSUE TITLE
Distribution: 3.19 Tracking issue

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#11954]
#### [Support new and existing deployments](https://github.com/orgs/sourcegraph/projects/74)

This is an ongoing expense, we anticipate this taking no more than 10d of work spread across the entire team.

#### [Reduce upgrade overhead](https://github.com/orgs/sourcegraph/projects/71)

Upgrading Kubernetes deployments requires customers spend a lot of engineering time to converge our released Kubernetes manifests with their fork as documented in [RFC-141](https://docs.google.com/document/d/1tsksAlqe77NmdPLw7oyy2u0-1rYDQeVpPeDo1T0Xt50).

We will finish the [Dhall](https://dhall-lang.org/) investigation and make a decision by the end of 3.19.

- @ggilmore
- @uwedeportivo

#### [Increase our e2e test frequency](https://github.com/orgs/sourcegraph/projects/72)

To increase our release cadence, we need to be able to run e2e tests more frequently. This is currently not possible as our CI infrastructure causes tests to be unreliable.

- @slimsag
- @davejrt
- @pecigonzalo 

#### [Support per-team alerts](https://github.com/orgs/sourcegraph/projects/73)

To allow teams to support and monitor the services and features they ship, we need to be able to route alerts to the relevant teams as described in [RFC-189](https://docs.google.com/document/d/1noZf86g2QwTbFNt3XSSbMg36D-_HCptP1thMzZsgt2Q).

- @bobheadxi
- @davejrt
- @slimsag

### Availability

Period is from **July 20th** to **August 19th (23 working days)**. Please write the days you won't be working and the number of working days for the period.

- **Dave**: 22d (off July20)
- **Robert**: 23d

### Workload

@bobheadxi: __2.50d__

- [x] Approved: Proposal: RFC-189: Support per-team alerts and on-call rotations [#12010](https://github.com/sourcegraph/sourcegraph/issues/12010) 
- [x] monitoring: migrate existing alert rules to generator [#12117](https://github.com/sourcegraph/sourcegraph/issues/12117) 
- [x] Dogfood the monitoring we ship with Sourcegraph [#5370](https://github.com/sourcegraph/sourcegraph/issues/5370) __2d__ 
- [x] ~cadvisor: investigate collecting IO metrics~ [#12163](https://github.com/sourcegraph/sourcegraph/issues/12163) 
- [x] Better account for peaks / max resource usage in monitoring [#12032](https://github.com/sourcegraph/sourcegraph/issues/12032) __0.5d__ 
- [x] Make license check not fail when our node version is upgraded [#12318](https://github.com/sourcegraph/sourcegraph/issues/12318) 
- [x] monitoring: generate alerts as native prometheus alerts, let alert_count depend on alert rules [#12336](https://github.com/sourcegraph/sourcegraph/issues/12336) 
- [x] sourcegraph/server:3.18 provisioning indicators panel missing [#12421](https://github.com/sourcegraph/sourcegraph/issues/12421) 🐛
- [x] deploy-sourcegraph: prometheus missing in `up` metric [#12482](https://github.com/sourcegraph/sourcegraph/issues/12482) 
- [x] monitoring: no easy way to trigger alerts for testing [#12423](https://github.com/sourcegraph/sourcegraph/issues/12423) 
- [x] monitoring: link back to grafana service dashboards in alert notifications [#12235](https://github.com/sourcegraph/sourcegraph/issues/12235) 
- [x] monitoring: better advice for alerts that do not have an entry in alert_solutions [#12236](https://github.com/sourcegraph/sourcegraph/issues/12236) 
- [x] frontend: hard errors alerts as ratio/percentage instead of absolute-value [#12158](https://github.com/sourcegraph/sourcegraph/issues/12158) 
- [x] monitoring: change relevant hard threshold alerts to ratio-based alerts [#12865](https://github.com/sourcegraph/sourcegraph/issues/12865) 
- [x] monitoring: index_queue_growth_rate firing without hitting threshold [#12868](https://github.com/sourcegraph/sourcegraph/issues/12868) 🐛
- [ ] ~monitoring: remove custom alertmanager from cloud~ [#12160](https://github.com/sourcegraph/sourcegraph/issues/12160) 
- [x] monitoring: difficult to understand 7d provisioning panel [#12692](https://github.com/sourcegraph/sourcegraph/issues/12692) 

@davejrt

- [ ] ~Bare-metal Buildkite agents capable of running Docker and VMs~ [#12101](https://github.com/sourcegraph/sourcegraph/issues/12101) 
- [ ] ~deploy-sourcegraph-dhall: Add CI job to generate diff between master and feature branch~ [#12716](https://github.com/sourcegraph/sourcegraph/issues/12716) 
- [ ] ~baremetal buildkite agent networking / instability issues~ [#12996](https://github.com/sourcegraph/sourcegraph/issues/12996) 

@daxmc99

- [x] Sourcegraph.com - add redis-store & precise-code-intel-bundle-manager snapshotting [#10450](https://github.com/sourcegraph/sourcegraph/issues/10450) 

@efritz

- [x] sourcegraph/customer [#72](https://github.com/sourcegraph/customer/issues/72) 🐛👩

@ggilmore

- [ ] ~deploy-sourcegraph-dhall: incrementally migrate sourcegraph.com services over to dhall~ [#12113](https://github.com/sourcegraph/sourcegraph/issues/12113) 
- [ ] ~[draft] deploy-sourcegraph-dhall: implement migrate-to-non-root overlay~ [#12283](https://github.com/sourcegraph/sourcegraph/issues/12283) 
- [ ] ~deploy-sourcegraph-dhall: grafana: implement new configuration logic for k8s.sgdev.org~ [#12109](https://github.com/sourcegraph/sourcegraph/issues/12109) 
- [ ] ~deploy-sourcegraph-dhall: frontend: implement new configuration logic for k8s.sgdev.org~ [#12105](https://github.com/sourcegraph/sourcegraph/issues/12105) 

@keegancsmith

- [x] sourcegraph/customer [#69](https://github.com/sourcegraph/customer/issues/69) 👩

@pecigonzalo

- [ ] ~Reduce the impact of unplanned work~ [#11904](https://github.com/sourcegraph/sourcegraph/issues/11904) 
- [x] Migrate terraform state to GCP [#12496](https://github.com/sourcegraph/sourcegraph/issues/12496) 

@slimsag: __7.50d__

- [x] sourcegraph/customer [#62](https://github.com/sourcegraph/customer/issues/62) __2d__ 👩
- [x] Formalize managed instances [#12495](https://github.com/sourcegraph/sourcegraph/issues/12495) __5d__ 
- [x] sourcegraph/customer [#73](https://github.com/sourcegraph/customer/issues/73) 👩
- [x] sourcegraph/customer [#53](https://github.com/sourcegraph/customer/issues/53) __0.5d__ 👩
- [x] sourcegraph/customer [#66](https://github.com/sourcegraph/customer/issues/66) 👩
- [ ] ~sourcegraph/customer~ [#74](https://github.com/sourcegraph/customer/issues/74) 👩
- [x] sourcegraph/customer [#85](https://github.com/sourcegraph/customer/issues/85) 👩
- [ ] ~sourcegraph/customer~ [#90](https://github.com/sourcegraph/customer/issues/90) 🐛👩
- [ ] ~Run e2e tests on bare-metal Buildkite agents on every commit to master (non-blocking)~ [#12339](https://github.com/sourcegraph/sourcegraph/issues/12339) 
- [ ] ~Run e2e "regression" tests on bare-metal Buildkite agents on every commit to master (non-blocking)~ [#12340](https://github.com/sourcegraph/sourcegraph/issues/12340) 
- [ ] distribution: add monitoring architecture page [#1221](https://github.com/sourcegraph/about/pull/1221) :shipit:
- [ ] distribution roadmap [#1104](https://github.com/sourcegraph/about/pull/1104) :shipit:
- [ ] Document when to introduce new services or not [#5487](https://github.com/sourcegraph/sourcegraph/pull/5487) :shipit:

@uwedeportivo: __8.00d__

- [x] sourcegraph/customer [#65](https://github.com/sourcegraph/customer/issues/65) 👩
- [x] deploy-sourcegraph-dhall: symbols: implement generate reading from config [#12076](https://github.com/sourcegraph/sourcegraph/issues/12076) __0.5d__ 
- [x] deploy-sourcegraph-dhall: searcher: implement generate reading from config [#12075](https://github.com/sourcegraph/sourcegraph/issues/12075) __0.5d__ 
- [x] deploy-sourcegraph-dhall: replacer: implement generate reading from config [#12074](https://github.com/sourcegraph/sourcegraph/issues/12074) __0.5d__ 
- [x] deploy-sourcegraph-dhall: repo-updater: implement generate reading from config [#12073](https://github.com/sourcegraph/sourcegraph/issues/12073) __0.5d__ 
- [x] deploy-sourcegraph-dhall: query-runner: implement generate reading from config [#12072](https://github.com/sourcegraph/sourcegraph/issues/12072) __0.5d__ 
- [x] deploy-sourcegraph-dhall: precise-code-intel: implement generate reading from config [#12071](https://github.com/sourcegraph/sourcegraph/issues/12071) __0.5d__ 
- [x] deploy-sourcegraph-dhall: postgres: implement generate reading from config [#12070](https://github.com/sourcegraph/sourcegraph/issues/12070) __0.5d__ 
- [x] deploy-sourcegraph-dhall: jaeger: implement generate reading from config [#12069](https://github.com/sourcegraph/sourcegraph/issues/12069) __0.5d__ 
- [x] deploy-sourcegraph-dhall: github-proxy: implement generate reading from config [#12066](https://github.com/sourcegraph/sourcegraph/issues/12066) __0.5d__ 
- [x] deploy-sourcegraph-dhall: cadvisor: implement generate reading from config [#12065](https://github.com/sourcegraph/sourcegraph/issues/12065) __0.5d__ 
- [x] ci-db-backcomp.sh is not branch-aware [#12302](https://github.com/sourcegraph/sourcegraph/issues/12302) 
- [x] sourcegraph/customer [#57](https://github.com/sourcegraph/customer/issues/57) __3d__ 👩

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by pecigonzalo** [comment]
cc/ @christinaforney @dadlerj

**Comment by bobheadxi** [comment]
## this week (week of jul 13)

Landed a range of improvements to alerting for 3.18 ([alert silencing](https://github.com/sourcegraph/sourcegraph/pull/12087), [notifications](https://github.com/sourcegraph/sourcegraph/pull/12046), [unifying some out-of-band alerts](https://github.com/sourcegraph/deploy-sourcegraph/pull/786). Worked on justifying and fleshing out some details for [supporting alert ownership for RFC189](https://github.com/sourcegraph/sourcegraph/issues/12010), planned tasks for 3.19, and am currently working on documenting the what, how, and why of our monitoring stack (https://github.com/sourcegraph/about/pull/1221). Also paired with @keegancsmith on [potential improvements to one of our alerts](https://github.com/sourcegraph/sourcegraph/issues/12158) and the generator as a whole.

## next week

Hopefully resolve https://github.com/sourcegraph/sourcegraph/issues/12158, since it is currently one of the more frequent critical alerts that isn't entirely actionable/valid on Cloud, and wrap up https://github.com/sourcegraph/sourcegraph/issues/5370 by setting up a time to take on-call and set up OpsGenie. Also finalize how we are [supporting alert ownership for RFC189](https://github.com/sourcegraph/sourcegraph/issues/12010) and and [finish documenting our monitoring stack](https://github.com/sourcegraph/about/pull/1221)

**Comment by davejrt** [comment]
**Week July 13**

Landing blackbox exporter into sourcegraph.com environment sourcegraph/deploy-sourcegraph-dot-com#2984 Lots of time spend on calls with capital one working through issues with their deployment related to indexed search starting. Also implemeted the fix suggested by @pecigonzalo regarding pv/pvc and their respecting claimref from namespaces.

**Week July 20**
Continuing to work through CapitalOne issues and beginning on #12101 in addition to fine tuning some of the blackbox alerts to ensure they reflect exactly what we need. These seemed to function well though in light of lasts weeks cloudflare outage. 
Continuing to work with CapitalOne to resolve any further issues

**Comment by pecigonzalo** [comment]
#### Week July 13
I worked on planning 3.19 which included starting this [experiment ](https://threads.com/34382596526) for tracking project progress. I have also started [RFC-202](https://docs.google.com/document/d/1s0gdKsCNegym6z1HGB53i3U_2HGwZwyvjiuv5HNWmH8/edit#) for standardizing configuration across our services.

#### Week July 20
My focus this week will be working with the team to set the our [goals](https://about.sourcegraph.com/company/goals) and planning the retrospective for 3.18

**Comment by uwedeportivo** [comment]
pretend this is last friday:

this week:

mainly release with dax and i finished all my dhall assignments from geoffrey (i used geoffrey's nicely done framework to capture in dhall the customizations we need to support dog-food k8s)

next week:

3.19 planning, some small remainders from release process, continue with geoffrey on dhall (we will probably start converting dog-food and start capturing all the kustomize customizations and twitter and apple customization)

**Comment by ggilmore** [comment]
This past week, I lost some time due medical issues and follow up. The rest of the week was spent catching up on rescheduled meetings, more medical follow up, following up with @uwe's good work on deploy-sourcegraph-dhall, and 3.19 planning

This week:
- meeting with uwe to catch up with progress
- meeting with dave to introduce him to https://github.com/sourcegraph/sourcegraph/issues/12113
- catch up with k8s.sgdev.org infrastructure changes for dhall, https://github.com/sourcegraph/sourcegraph/issues/12109 and https://github.com/sourcegraph/sourcegraph/issues/12105

**Comment by slimsag** [comment]
Copying my update over [from the 3.18 tracking issue](https://github.com/sourcegraph/sourcegraph/issues/11646#issuecomment-661272867) for posterity / visibility:

## Last week

I spent ~60% of my time on https://github.com/sourcegraph/customer/issues/62#issuecomment-661266320 and made great progress but with many context switches / interruptions throughout. I was sidetracked regularly by::

- team sync, seven 1:1s
- assisting with the release process (adding docker-compose release docs, debugging CI failures, etc)
- (~6h) debugging customer issues [1](https://sourcegraph.slack.com/archives/CTQ5LTF8D/p1595024750050300) [2](https://sourcegraph.slack.com/archives/C0B2RU51Q/p1595017746022600?thread_ts=1594949170.013000) [3](https://sourcegraph.slack.com/archives/CJX299FGE/p1595010997073000?thread_ts=1595010607.071900) [4](https://sourcegraph.slack.com/archives/CJX299FGE/p1594949631025100?thread_ts=1594949631.025100) [5](https://sourcegraph.slack.com/archives/CTGBWCKM0/p1594938548021600?thread_ts=1594924448.020600) [6](https://sourcegraph.slack.com/archives/CJX299FGE/p1594929560008800?thread_ts=1594929412.008000)
- helping devs here: [test their changes](https://sourcegraph.slack.com/archives/CJX299FGE/p1594951982030300?thread_ts=1594949711.026400), [debug dot-com issues](https://sourcegraph.slack.com/archives/CMBA8F926/p1594935782146100?thread_ts=1594934056.141800), [collecting some usage data](https://sourcegraph.slack.com/archives/CJX299FGE/p1594926820493600?thread_ts=1594926820.493600), [adding architecture diagrams](https://sourcegraph.slack.com/archives/CJX299FGE/p1594919940478700?thread_ts=1594919940.478700), and more.

## This week

I intend to:

- Finish and merge the distribution roadmap. 
- Finish and merge https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/1
- Assist several customers and devs.

**Comment by pecigonzalo** [comment]
## Priorities update
As discussed with CE https://github.com/sourcegraph/customer/issues/65 is now our top priority

**Comment by davejrt** [comment]
**Week July 20**

- Met with Geoffrey regarding Dhall and took small steps to familiarize myself more with this
- A lot of time spent on calls troubleshooting with $CUSTOMER indexed-search issues and assiting in the rollout of overlays related to https://github.com/sourcegraph/customer/issues/65
- Migrated data over from https://bigdata.sgdev.org to https://megakube.sgdev.org to assist with troubleshooting and debugging issues
- Assiting Indeed with rollout of new alertmanager https://sourcegraph.slack.com/archives/CSKMGUJ58/p1595433496171400

**Comment by ggilmore** [comment]
This week: 
- Meetings, donut, 1:1's
- Introduced @davejrt to Dhall
- More medical appointments
- Tasked switched from Dhall to investigating  https://github.com/sourcegraph/customer/issues/65

Next week:
I should have fewer medical appointments, and I'll continue dedicating my time to investigating https://github.com/sourcegraph/customer/issues/65 until that's solved

**Comment by uwedeportivo** [comment]
**Week July 20 - Last week**

- wrapped up e2e regression test remainder from 3.18 (https://github.com/sourcegraph/sourcegraph/pull/12439)
- 2 debug sessions with john at cap1 and follow-up work afterwards
- overlay for cap1 changes
- pretty quiet oncall week with one page that got fixed (https://github.com/sourcegraph/sourcegraph/pull/12407)
- many code reviews
- support slacks with nutanix, indeed and cap1

**Week July 27- Next week**

- do some dhall work (prepare more customizations)
- debug indexed search on megakube.sgdev and bigdata.sgdev

**Comment by bobheadxi** [comment]
### Week of July 20

Added the [first step towards supporting per-team alerts](https://github.com/sourcegraph/sourcegraph/pull/12358), worked on [migrating custom alerts into our generator](https://github.com/sourcegraph/sourcegraph/issues/12117), [investigated some provisioning issues on dot-com](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aopen+is%3Aissue+assignee%3Abobheadxi+label%3Asilenced-alert), [investigated collecting IO metrics](https://github.com/sourcegraph/sourcegraph/issues/12163) to support https://github.com/sourcegraph/customer/issues/65, and [added support for `for: duration` in our alerts](https://github.com/sourcegraph/sourcegraph/pull/12395)

### Next week

Wrap up outstanding PRs and [implement support for per-team alerts](https://github.com/sourcegraph/sourcegraph/issues/12010) + [dogfood it](https://github.com/sourcegraph/sourcegraph/issues/5370) alongside the [migrated custom alerts](https://github.com/sourcegraph/sourcegraph/issues/12117)

**Comment by slimsag** [comment]
### Last week

I spent the vast majority of my time helping with https://github.com/sourcegraph/customer/issues/65 and nearly completed https://github.com/sourcegraph/customer/issues/62 (literally only a few hours away).

### This week

I hope to finish https://github.com/sourcegraph/customer/issues/62 , the distribution roadmap, the monitoring architecture documentation, and catch up with Robert on monitoring.

**Comment by pecigonzalo** [comment]
#### Week July 20
Last week focus has been working with the team to set our team goals. The test around using GitHub projects for tracking progress seems to be working and ill continue with this during the rest of the iteration.
I have been also talking with Chayim about the secrets loading implementation.

#### Week July 27
Ill continue to focus on setting our team goals, we have settled on them but we are still working out the details. I will also try to finalize RFC-202 and the review of RFC 199.

#### Team update
Issue https://github.com/sourcegraph/customer/issues/65 has been resolved, but our focus remains on the sub-issues created by it https://github.com/sourcegraph/customer/issues/69 and https://github.com/sourcegraph/customer/issues/70.

**Comment by slimsag** [comment]
## This week

I helped $CUSTOMER with Uwe and Dave to ensure their demo went smoothly, completely finished work on managed instances and am ready to ship it to $MY_CUSTOMER_0, caught up with Robert on monitoring and next steps there, shipped Sourcegraph to $MY_CUSTOMER_1, began data collection for https://github.com/sourcegraph/customer/issues/71 - and started looking into release automation for deploy-sourcegraph-docker as well as brainstorming production readiness ideas.

I did not complete/merge the distribution roadmap or monitoring architecture documentation, but still intend to do so.

## Next week

Review https://github.com/sourcegraph/sourcegraph/pull/12581 - merge the distribution roadmap, architecture docs, get feedback on production readiness and move forward on that, continue looking into monitoring and release automation.

**Comment by bobheadxi** [comment]
## This week

I've been working on a range of improvements and polish to alerting ([formatting](https://github.com/sourcegraph/sourcegraph/pull/12510), [bug](https://github.com/sourcegraph/sourcegraph/pull/12510), [regression](https://github.com/sourcegraph/sourcegraph/pull/12489), [migration](https://github.com/sourcegraph/sourcegraph/pull/12391), [testing](https://github.com/sourcegraph/sourcegraph/pull/12532), etc).

I've also landed the core functionality for the RFC 189's per-team alerts (via [routing implementation](https://github.com/sourcegraph/sourcegraph/pull/12491)) and have prepared a pull request to configure team paging (https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/3073). The final pieces of this are also up for review: [migrate the rest of our out-of-band alerts](https://github.com/sourcegraph/sourcegraph/pull/12581) and [drop our custom alerting](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/3099).

## Next week

Land everything related to per-team alerts and work with each team to get rotations and alerts set up (per @nicksnyder's request). I imagine there will be problematic alerts / other issues, and will likely focus on follow-up work

**Comment by ggilmore** [comment]
This week:
- helped out with the $customer issue investigations
- more medical appointments and meetings
- synced with @uwedeportivo on his dhall work and talked about next steps
- discovered some dhall perf issues with @uwedeportivo and filed https://github.com/dhall-lang/dhall-haskell/issues/1960, hopefully we can find a good resolutionf or this
- task switched to back to infrastructure work for dhall dogfooding: added dhall plugins to our CI agents, preparing terraform code for catfood.sgdev.org (dogfood clone) - holding off on deploying it until next week to save on costs

**Comment by davejrt** [comment]
**THIS WEEK**

I'd say a fairly even portion of my time was spent between working on tasks for $customer and replicating their setup internally. I haven't gotten back around to do anything with Dhall which is unfortunate but I hope to make more progress on that next week. I made a decent start on #12101 and a working agent that aside from needing some fine tuning will be good to start using and iterate on.

I did take a tertiary glance at removing alertmanager but Robert kindly informed me that this was wrapped up with a bunch of other PRs he'll land next week so it's in his more than capable hands for now.  

**NEXT WEEK**

I'll have a PR ready to land for the baremetal CI agent which will be ready to start running jobs. I'm going to resync with geoffrey and/or uwe re dhall and make an effort to pick that back up again.

**Comment by uwedeportivo** [comment]
this week:

tinkered together with geoffrey on dhall (https://github.com/sourcegraph/deploy-sourcegraph-dhall/tree/the_rest_generate). we're in contact with the dhall core devs about some issues we hit and we also asked them for advice on how to set up the dhall interface for our customers (https://github.com/dhall-lang/dhall-haskell/issues/1960#issuecomment-667314221). we have tried a couple of things and we'll settle on something for the POC for the dogfood cluster.  we should be able to tie things up for the POC evaluation sometime next week.

did some debugging, overlay creation and general support for our bigdata $customer.

next week:

i want us to finish up the dhall POC and do some evaluation of suitability and if/how we proceed. i'm leaning towards proceeding. i think dhall advantages outweigh some of the difficulties. but i don't want to inject priors into the evaluation process so disregard my last sentence :-)

**Comment by pecigonzalo** [comment]
#### Last week
We finished our initial team [goals](https://about.sourcegraph.com/handbook/engineering/distribution/goals), I also finalized the review of RFC-199. We will make we test using microVMs with [ignite](https://github.com/weaveworks/ignite) for a v0 and will have to review the outcome of that testing before we can move to v1 and define how we deploy/support/HA/etc.

#### This week
We will kick-off our 360 review cycle and I will focus on that. Ill be working on the roadmap and a product readiness document with Stephen and will pair with Geoffrey to get more familiar with our Dhall implementation.
I have not been able to progress RFC-202 and if time allows I would like to finish that up.

#### Team update
The high priority items from last week seem to be resolved, and we will return to our tracking issue priorities.

_Ill update this again after I confirm those issues are resolved_

**Comment by ggilmore** [comment]
This week: 
- Many meetings, mostly syncing up with @uwedeportivo and onboarding @pecigonzalo and @davejrt to our Dhall configuration
- (mostly) deployed catfood.sgdev.org dhall POC. The remaining items are to add ingress-nginx resources to the dhall generator, fix a few small bugs, and lastly create the catfood.sgdev.org DNS entry 
   - see https://github.com/sourcegraph/deploy-sourcegraph-dhall/pull/18

**Comment by slimsag** [comment]
This week:

I spent most of my time, maybe 70% discussing things (distribution things, CE things, security things, code intel things, and more.) I spent 10% of my time helping customers, and 10% thinking about how to onboard CE folks. I made slight progress on release automation, but no progress on the other things I set out to do this week in my last update.

**Comment by bobheadxi** [comment]
### This week

I followed up on last week's update and have finalized most of the work for per-team alerts, and have been dogfooding it (to myself). I have pinged each team to set up on-call rotations so that we can switch over completely to the new alerting stack and [remove our old alerting](https://github.com/sourcegraph/sourcegraph/issues/12160) by end of 3.19 or early 3.20. I have also made a range of improvements to our alerting, including: making our provisioning alerts more informative, converting some of our hard-threshold alerts to be ratios, improve our alerts solutions documentation. I also looked into adjusting resources for some of our services that seem like they could use it.

### Next week

See if I can help others wrap up any outstanding tasks for this iteration, maybe work on [converting more of our noisy alerts to be ratio-based](https://github.com/sourcegraph/sourcegraph/issues/12865), and start looking at what I can do in 3.20

**Comment by uwedeportivo** [comment]
this week:

did some dhall work experimenting with unit tests and some more encompassing customizations that span more than one resource. did some initial bootstrap for marek for the 3.19 release. some customer work with cap1.

**Comment by pecigonzalo** [comment]
#### Last week
Kicked-off 360 review cycle and I was focused on that. I paired with Geoffrey to get more familiar with our Dhall implementation and architecture. I meet with Eric to talk about running code intel on firecracker VMs and how would we deploy those.

#### This week
Ill be working mainly on our 360 reviews and 3.20 planning. Ill also like to Dhall, I would like to do more testing now that I understand its structure better. Im also working on improving our incidents pipeline so its easier to track the status and number of active incidents.

#### Team update
Given the current number of customer issues, we are over our original estimates for support time, which might have an impact on the delivery of all listed items.
We started planning [3.20](https://github.com/sourcegraph/sourcegraph/issues/12836) last week and should by the end of the week.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
This week:

I was out Mon and half of Tue due to a family emergency. Tue was spent getting caught up. I discussed Dhall with the team and helped to determine next steps, interviewed two candidates (eng and CE), and helped customers ([#85](https://github.com/sourcegraph/customer/issues/85) (completed), [#62](https://github.com/sourcegraph/customer/issues/62) (completed), [#74](https://github.com/sourcegraph/customer/issues/74) (in progress), [#12999](https://github.com/sourcegraph/sourcegraph/issues/12999) (in progress), [#73](https://github.com/sourcegraph/customer/issues/73) (in progress)). I [reduced the reliance of myself](https://github.com/sourcegraph/customer/issues/73#issuecomment-674328804) in shipping Sourcegraph to some customers, and am running behind on other areas (support, distribution roadmap, monitoring arch docs, service arch docs, etc.) due to the life incident I had earlier in the week.

**Comment by ggilmore** [comment]
This week, I got catfood.sgdev.org in a demo-able state for the Dhall PoC (along with the accompanying https://github.com/sourcegraph/deploy-sourcegraph-dhall changes). Following the Wednesday demo, the @sourcegraph/distribution team has enough confidence to move forward with the dhall implementation. My next priorities are to sync with the Dhall maintainers and develop the Dhall roadmap/tracking issue

**Comment by pecigonzalo** [comment]
#### Last Week
I have mostly been working on the 3.20 plan and 360 reviews. I worked on a couple of incidents as well (`hostError ` on K8s nodes, https://github.com/sourcegraph/infrastructure/pull/2060, https://github.com/sourcegraph/customer/issues/75) and actively reviewing other Kubernetes notifications to identify fixes (eg. https://github.com/sourcegraph/deploy-sourcegraph/pull/816). 

#### This Week
My priority for this week is finalizing the plans for 3.20 and meeting with the team to close the reviews. Additionally, ill continue to work through our alerts and find action items from them.

**Comment by bobheadxi** [comment]
**last week**

A lot of misc. work and doing investigations around alerts discussions in Slack (often around alerts frequencies). Fiddled around with Dhall, and made other misc. improvements to tooling (docsite, license_finder). Brainstormed a potential idea for next iteration around improving release dogfooding / our deploy-sourcegraph forks

**next week**

Stay up to date on 3.20 plans and see how I can pitch in. Probably follow up on teams setting up their opsgenie alerts, and continue following up on issues with alerts that get raised

**Comment by davejrt** [comment]
**last week**
Landed [this](https://github.com/sourcegraph/infrastructure/pull/2054) PR which provides the code to build a buildkite-agent running on GCP, as well as the terraform code to deploy the autoscaling group. Also spent a number of sessions with Kimberly helping her sourcegraph running locally in her wsl2 environment. 

**this week**
Stephen pointed out the performance issues with the buildkite-agents, especially with relation to booting a vagrant box as well as pulling docker images. I suspect this is related to the nested virt and some virtual box networking that will need to be tuned. Captured in #12996

**Comment by bobheadxi** [comment]
**this week**

some debug sessions, follow-ups on per-team alerting and general improvements on that front. did some planning for k8s dogfooding in 3.20, and made a [proof-of-concept for what it might look like](https://sourcegraph.slack.com/archives/CJX299FGE/p1598024666020900)

**Comment by davejrt** [comment]
**Last week 17 July**

I'd estimate 90% of my time was spent debugging the GCP/vagrant/docker e2e testing issues #12996. PR is up for review [https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/141](here). Doesn't appear to be directly related to networking as first thought, and a high CPU count has an impact based on my testing

** This week 24 July **

Iron out any remaining issues with this portion of the e2e testing and sync with Uwe around improving the release process. I need to look more closely at our autoscaling capabilites in GCP to ensure we're getting maximum value and reliability out of the config.

**Comment by pecigonzalo** [comment]
#### Last Week
Last week was focused on closing 3.19, planning 3.20 and closing our 360 review packages. I was able to make some progress in the [Prometheus issue](https://github.com/sourcegraph/customer/issues/75) and sent a fix to the customer (thanks @bobheadxi and @uwe for the help here).
I also started to organize our GCP Projects, so its easier to set permissions by using groups instead of users and merging `deploy-sourcegraph` to `deploy-sourcegraph-dot-com`.

#### This Week
Ill work on adding our new on-call rotation to OpsGenia and sending a PR with the updated information to help finish [per-team alerts](https://github.com/sourcegraph/sourcegraph/issues/12899) and get some help to finalize the `deploy-sourcegraph-dot-com` merge.
 @bobheadxi and I will sync later this week so I can start helping on [Dogfood Kubernetes deployments](https://github.com/orgs/sourcegraph/projects/83).

**Comment by uwedeportivo** [comment]
last week
 
fighting really hard to get 3.19 out the door. we had several issues: it started with the segfault in redis-cache in single-server, DNS issues in single-server, regression tests not logging in, regression tests referencing wrong test repos, build issues, update-docker-image-tags issues. after we finished tagging the final release for 3.19, stephen discovered a race condition in DB migration, so we had to fix, redact 3.19.0 and release 3.19.1

this week

i started looking in the dhall migration/keep-up-to-date tool. will continue playing with that for a couple of days. also help geoffrey with planning and fleshing out the dhall project for real now
