### ISSUE TITLE
Search 3.19 Tracking issue

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#12276]
### Plan

**Goal: Deliver search functionality that is on par with [existing alternatives](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html), and pave the way for more powerful and exclusive search functionality.** Enable hierarchical search, optimize AND content queries, support NOT syntax for content searches. @rvantonder @stefanhengl 

**Goal: Help new users successfully onboard to and discover features of Sourcegraph Cloud.** Implement search tour. @attfarhan 

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@attfarhan: __2.50d__

- [x] Create web content stylesheet [#12303](https://github.com/sourcegraph/sourcegraph/issues/12303) __2d__ 🧶
- [x] Log 3 click events for new features on Search Homepage and Repo Page [#12356](https://github.com/sourcegraph/sourcegraph/issues/12356) __0.5d__ 

@rvantonder: __18.50d__

- [ ] Search feature request: Query syntax to search at a date (instead of revision) [#10820](https://github.com/sourcegraph/sourcegraph/issues/10820) 
- [x] Support unix-style globbing patterns for search field values [#10094](https://github.com/sourcegraph/sourcegraph/issues/10094) [👩](https://app.hubspot.com/contacts/2762526/company/464956351)
- [x] Query parser migration [#12477](https://github.com/sourcegraph/sourcegraph/issues/12477) __8d__ 
- [x] Duplicate results in or-operator merge operation [#12481](https://github.com/sourcegraph/sourcegraph/issues/12481) __1.5d__ 🐛
- [x] Treat trailing parentheses in new parser similar to old parser [#12733](https://github.com/sourcegraph/sourcegraph/issues/12733) __0.5d__ 🐛
- [x] Support or-expressions for repo: and file: parameters [#11009](https://github.com/sourcegraph/sourcegraph/issues/11009) __8d__ 
- [ ] Search recommendations to add quotes is misleading. [#12802](https://github.com/sourcegraph/sourcegraph/issues/12802) __0.5d__ 🐛
- [x] Unable to perform a literal search with a query that contains a `:` [#10171](https://github.com/sourcegraph/sourcegraph/issues/10171) 

@stefanhengl

- [x] add negation/NOT for file contents [#12232](https://github.com/sourcegraph/sourcegraph/issues/12232) 
- [x] Add NOT as syntactic sugar for negatable fields [#9976](https://github.com/sourcegraph/sourcegraph/issues/9976) 
- [x] panic in glob conversion function [#12456](https://github.com/sourcegraph/sourcegraph/issues/12456) 🐛
- [x] add syntax highlighting for NOT [#12639](https://github.com/sourcegraph/sourcegraph/issues/12639) 
- [x] search: reactivate dead code path in alertForOverRepoLimit [#12556](https://github.com/sourcegraph/sourcegraph/pull/12556) :shipit:

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by attfarhan** [comment]
### Last week
- Fix outstanding repogroup page issues:
  - Repogroup page responsiveness
  - Search page responsiveness
  - 404 flashing when visiting repogroup pages
  - Fixed flaky percy test
- Indexed repogroup repos using [ghdump](https://github.com/sourcegraph/ghdump)
- Private code call to actions
- Reviewed globbing RFC 


### This week 
- Web content stylesheet https://github.com/sourcegraph/sourcegraph/issues/12303
- Search homepage launch data (https://docs.google.com/document/d/1WJRst6C8JZcnlItvoRWs3baye_KJ0WDOrs9AIoHXI6k/edit#heading=h.trqab8y0kufp
- Search tour

**Comment by stefanhengl** [comment]
### Last Week
- added globbing support to backend [PR #12093](https://github.com/sourcegraph/sourcegraph/pull/12093).
- started working on globbing changes for web [#12287](https://github.com/sourcegraph/sourcegraph/pull/12287).
- started research on how to support "NOT" for patterns (#12232)[https://github.com/sourcegraph/sourcegraph/issues/12232].

### This Week
- finish globbing changes for web
- add "NOT" for patterns of indexed searches

**Comment by rvantonder** [comment]
**Last week**

Added option `search.migrateParser` to use the parser for all queries, and made that code 'feature complete' for the transition. Did some cleanup of implementation and range information exposed via GQL. Helped guide globbing support. 3.19 planning.

**This week**

Add hierarchical search under feature flag. If I have time, I'll tackle the more efficient AND-operator eval started in #11559.

**Comment by keegancsmith** [comment]
Posting here since I did lots of search work last week, and next week I intend on doing some search work:

**Last Week**: Shipped multi branch indexing. Lots of changes to the indexserver, testing and docs done for that. Debugged some issue in production. Main win was speeding up Sourcegraph.com since I noticed frontend was underprovisioned.

**This Week**: Larger idea is some src-expose work, main goal being making it feel first class.

**Next Week**: Current plan is to start investigating streaming searching.

**Comment by stefanhengl** [comment]
### Last Week
- finished the first iteration of globbing support (web + backend) https://github.com/sourcegraph/sourcegraph/pull/12287, https://github.com/sourcegraph/sourcegraph/pull/12365.
- fixed bug in globbing parser that Rijnard discovered while fuzzing the new parser https://github.com/sourcegraph/sourcegraph/pull/12365.
- created PR to support negation of field `content` https://github.com/sourcegraph/sourcegraph/pull/12412.

### This Week
-  merge PR to support negation of field `content`.
- work on list of bugs in https://github.com/sourcegraph/sourcegraph/issues/12476 before enabling globbing for all Sourcegraph org members.
- Update syntax highlighting and tooltips on web to support `-content:`
- add `NOT field:` as syntactic sugar for `-field:` for all negatable fields.

**Comment by keegancsmith** [comment]
#### Last Week

Main focus ended up being indexed search issues that the distribution team has been running into getting a very large instance to work. Lots of observability improvements, debugging and some bug fixes around shard rebalancing.

The other main focus of the week was src-expose. I ported it to src-cli and improved its performance and corner case bugs by switching to using git to serve repositories. I also did two customer calls somewhat related to src-expose.

As I went a long I did a few dev environment improvements: faster go CI, backcompat checks, alertmanager alerts, logdna, experimental minimal go dev environment.

### This Week

I expect more work from our Large Instance testing to surface. I am so close to the finish line for the src-expose work I want to spend a day on that. I originally planned to start work on streaming search this week. I am unsure if I'll have the time, so I'll likely save it for next week.

**Comment by rvantonder** [comment]
**Last week**

Added the query expansion code (DNF form) which is the crux for evaluating arbitrary nested queries. Had a chance to try some of this out and got some code changes to do but it's going to be ready real soon. Fuzzed the parser and fixed some new bugs. Helped push along the globbing/negatable content search functionality. Added instrumentation to collect queries for differential testing for parser migration.

**This week**

Add the evaluation logic for DNF-expanded queries => deliver nested search. I need to add some extra validation to make sure we evaluate only certain legal combinations, but it should be straightforward. Will also start doing the parser differential testing this week.

**Comment by attfarhan** [comment]
*Last week*

My focus last week was wrapping up outstanding debt from the search and repogroup pages. I merged the private code CTAs PR, worked on and opened a PR up for web content styles, and added additional logging on the repogroup and search pages. Also spent time in meetings (1:1s, retros) to improve future design->engineering process. I helped out with implementation of and reviewed the frontend updates for globbing in filters. Finally, I spent time looking into issues surfaced during 3.18 release testing (https://github.com/sourcegraph/sourcegraph/issues/12420, https://github.com/sourcegraph/sourcegraph/issues/12310).

*This week*

I will be focused on the search tour implementation this week.

**Comment by rvantonder** [comment]
** Last week **

I implemented and demo'd the end-to-end functionality for general search expressions (AKA "nested"/"hierarchical" search, better naming and description TBD). Other than that, QA testing and fixes of parser/search operations.

** This week **

I will continue to make search expressions robust and production ready, from a backend POV (validation, more testing). I'll be adding some syntax highlighting this week to operators. I'll document some needed changes/considerations to the UI and loop in Farhan, but I feel comfortable diving into the web side of things myself after doing the backend work (probably only next week). Mid-week this week, I plan to activate the new parser for Sourcegraph org, but want to test some inputs before that happens. That will also let us activate the globbing option, if/when ready.

**Comment by stefanhengl** [comment]
### Last week
I mainly worked on adding support for `-content:` and adding `NOT` as syntactic sugar. Both features have been merged. Apart from that, I worked through a list of open issues we have with globbing #12476.

### This week

I want to add syntax highlighting for `NOT` to polish the features we merged the previous week.  There are still some questions we have to answer when it comes to the UX of globbing:
- dependence on regex toggle?
- support `**` or just `*`
- how to handle substrings of globbing patterns for suggestions

**Comment by attfarhan** [comment]
*Last week* (4 day week -- public holiday)

I spent most of my time working on the search tour implementation, experimenting with different OSS libraries, primarily [Shepherd](https://github.com/shipshapecode/shepherd) and [React-joyride](https://github.com/gilbarbara/react-joyride). Also spent time early in the week addressing comments on the web content styles PR (https://github.com/sourcegraph/sourcegraph/pull/12387), will need to address whatever is remaining there to get it merged.

*This week*

Continuing on tour implementation. I am working on an implementation using Shepherd, and currently ironing out a few kinks but I believe this will be the implementation I go with.

**Comment by keegancsmith** [comment]
#### Last Week

Main focus was search indexing and performance at scale. I first focussed on a large customer, but then then morphed into search performance for sourcegraph.com. Ended up looking into it after hack sessions with Robert, Tomas, Stefan and Ryan. Biggest win was custom marshalling of the list of repo/branches to search we sent to Zoekt. Quoting my posts on #progress:

> Our large scale instance can now index every repo. This makes it possible to do an exhaustive search (eg find accidental commits of passwords) which was a signing hurdle. As an extra bonus the page which tells you which repos need indexing now works (a long time complaint at scale).
> 
> Searching all indexed repos on Sourcegraph.com is now ~0.4s faster (about 25% faster overall). When doing an indexed search we transfer a list of repos to search to Zoekt (our indexed searcher). This is a cost we pay every search no matter how many results it finds. We optimized how we create the list and it now takes about 75ms to transfer 100k repos instead of 500ms on sourcegraph.com. More details here [sourcegraph#12546](https://github.com/sourcegraph/sourcegraph/pull/12546#issuecomment-666226706). For the most eye melting benchmark results look here [zoekt#53](https://github.com/sourcegraph/zoekt/pull/53#issue-458018956).
> 
> Shaved off another 350ms with Ryan. Searching on sourcegraph.com across 100k repos now takes less than half a second on average.
> 
> See [sourcegraph#12557](https://github.com/sourcegraph/sourcegraph/pull/12557) for how we tackled that. We are nearly at the point where search time is dominated by actual source code searching instead of our infrastructure around zoekt. Stefan and I explored the final slowdown now and will likely try tackle it next week.

A lot of this work also ended required observability to find what to do. So there have been lots of improvements made to logs in zoekt and jaeger tracing around zoekt in the frontend.

Ended up not journaling daily last week, regrets. But was more transparent in \#progress so could use that to track high level work.

I ended up not doing my final work for src-expose. Will spend a day on it this week.

#### This Week

First half of the week is smaller tasks I've been meaning to get to + src-expose. Thursday I'll start work on streaming search. My focus will be purely experimental. I've been meaning to create an alternative graphql/JS free search UI. I'll likely create a dumb UI for this and use it as a playground for streaming work. So that will be my main goal this week.

Explicit non-goal: Over the weekend we doubled the number of indexed repos on Sourcegraph.com (100k -> 200k) leading to performance + OOM issues. I'm going to let other look into that, and instead focus on other work.

#### Next Week

Monday is a public holiday, so 4 days. Will hopefully have a very fast streaming search PoC that we can than look into integrating into the main product. Depending on where the code takes me I imagine two paths: streaming for searcher or integrating streaming into main search path.

**Comment by rvantonder** [comment]
**Last week**

Mostly spent on testing the work to migrate our query parser to the new implementation. This meant testing existing inputs that I'd collected and running differential testing (e.g., https://github.com/sourcegraph/sourcegraph/pull/12732). At the end of the week, I activated the new parser for Sourcegraph org members, and will activate it for all of Sourcegraph.com in the coming week. Other than that, various things: syntax highlighting for operators, removing the defunct replacer service, reviewed open (and now resolved) search query issues, lattice reviews.

**This week**

Activate and monitor new query parser up to branch cut, and will decide whether to enable by default. I'll add support for general search operators/expressions behind a feature flag for the 3.19 release, it won't be on by default yet because (a) the initial implementation will benefit from more usage Sourcegraph.com and (b) there are UI concerns we'll need to resolve for a consistent experience.

**Comment by stefanhengl** [comment]
#### Last week

Continued work on globbing, mainly added features that make it easier for new users to submit simple searches. Apart from that, I worked on documentation for `-content` and `NOT`, fixed a search alert that showed regex syntax if globbing was active, and finished the lattice reviews. 

#### This week

I will spend as much time as possible on improving the performance of queries containing `AND`. Depending on the rollout of the new parser, I would love to enable globbing for Sourcegraphers on .com for 1 week to evaluate whether we move forward. Last week Rijnard found a blocking issue for gobbling: Simple code intel delivered by plugins relies on regex syntax and breaks if globbing is active. I want to assess the extend of the problem and design a fix.

**Comment by attfarhan** [comment]
**Last week**
Continued to focus on the onboarding tour implementation, making decent progress there but ran into some difficulties towards the end of the week with a couple of details that I need to iron out this week. Otherwise, worked on fixing a bug in interactive mode which removed parentheses from queries, met with Rob about the enterprise homepage prototype, and discussed the repogroup pages implementation for Stanford.

**This week**
Continue on and wrap up tour implementation.

**Comment by keegancsmith** [comment]
#### Last week
First half of last week went to plan. Did lots of smaller tasks (observability, small bugs), quite a bit of pairing and src-expose work https://github.com/sourcegraph/sourcegraph/pull/12754. Streaming search didn't have as much progress, read a lot of code and wrote some simple server sent events code.

#### This week
Monday was a public holiday. In an effort to make progress on streaming search I did a no internet day on Tuesday. I have a [working prototype](https://github.com/sourcegraph/zoekt/tree/k/stream) I like of Zoekt streaming search. That was done since it was relatively clean to add. However, I'm going to instead focus the rest of the week validating the approach by getting a PoC in `sourcegraph-frontend` and possibly our webapp.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
**Last week**

Added `/.../` support to new parser so that its equal to our old functionality. I activated the new parser on Sourcegraph.com. So far everything is working well. I wanted to turn on the new parser by default in this release, but discovered some minor test cases that I need to fix but didn't get to. I decided to rather leave the new parser activated on Sourcegraph.com until the next release, and incorporate the fixes for default activation there--no need to risk or rush a big shift like this. Other than that, worked on a structural search use case for prospectives.

**This week**

Handle the remaining parser cases. I expect the majority of my time to into adding the general search expressions I prototyped earlier, under a feature flag. I'll be continuing prospective work on structural search and see what I can do to help us upgrade to 3.12 alpine images. And also planning for 3.20.

**Comment by stefanhengl** [comment]
#### Last week
Worked on improving performance for evaluation of AND-operands. I tried out several variations of the same idea we had to make the evaluation more efficient, however, the brute force approach we currently have was still as fast and much simpler. Hence I decided not to proceed with any of the approaches but instead, I slightly improved the current code. Regarding globbing, I merged a PR to improve performance for cases where users specify github.com explicitly as their code host.

#### This week
Based on the findings from last week I will optimize the performance of AND-queries just for indexed searches. I intend to implement a first POC where I translate our query-tree directly into a zoekt-query-tree. If the performance improves as expected we can move forward and refactor the rest of the code.

**Comment by attfarhan** [comment]
**Last week**
I was fully focused on the search tour implementation. Opened up a [PR](https://github.com/sourcegraph/sourcegraph/pull/12972), which I'm seeking feedback for now.

**This week**
My top priority is to get proudct + code review for the search tour, and get it merged. After that, planning for 3.20.

**Comment by keegancsmith** [comment]
#### Last week

PoC of streaming search in Zoekt. A very close real demo of streaming search in Sourcegraph. 4 day week, ended up spending half on streaming search and the other half on misc. Highlights of misc is more docs/testing of src-expose, [changelog entries for 3.19](https://github.com/sourcegraph/sourcegraph/pull/13008/) I forgot to document and a ~30% perf improvement for search queries with a `repo:` field (done with @stefanhengl in <https://github.com/sourcegraph/sourcegraph/pull/12976>)

#### This week

Single goal, streaming search on Sourcegraph.com behind a user configuration flag.
