### ISSUE TITLE
RFC 199: Implement user code executor for code intel indexer

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#12307]
Implement [RFC 199: User code execution in the auto-indexer](https://docs.google.com/document/d/1rCduWqaLAbMu2s43RwJTBbRlhL6qS3oqq4iawiGdoVE).

@efritz: __5.00d__

- [x] RFC 199: Deploy new indexer service [#12709](https://github.com/sourcegraph/sourcegraph/issues/12709) 
- [x] RFC 199: Replace docker commands with firecracker commands [#12708](https://github.com/sourcegraph/sourcegraph/issues/12708) __5d__ 
- [x] RFC 199: Deploy indexer service that uses firecracker [#13382](https://github.com/sourcegraph/sourcegraph/issues/13382) 
- [x] RFC 199: Gather metrics from indexer service [#13494](https://github.com/sourcegraph/sourcegraph/issues/13494) 
- [x] codeintel: Wrap index commands in a firecracker VM [#13421](https://github.com/sourcegraph/sourcegraph/pull/13421) :shipit:

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
