### ISSUE TITLE
Cloud: 3.19 Tracking issue

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#12327]
#### Goal 1: Allow users to add public code from github.com, gitlab.com and bitbucket.org

@unknwon, @ryanslade and @asdine are working on this together. Figuring out multi-tenancy is going to unlock a lot of the capabilities we want from the Cloud project. External services are at the center of this because they are our current mechanism for specifying which repos to sync. We want to think through the product changes (and consequences) necessary for users and organizations to create external services on any Sourcegraph instance and at least prototype what it would look like. We recognize that we're starting work on this goal in an uphill (i.e. discovery) phase so the amount of planned work will grow over time. We'll gather feedback on the end-user product experience we're thinking of from a larger group including @christinaforney, @sqs and @rrhyne as part of this discovery process.

#### Goal 2: Store and handle external service and external account secrets securely.

@chayim, and @daxmc99 are working on this together. As we already know, there's a lot of security ground-work to do before we can allow any user or organization to use sourcegraph.com with private code. This is one of the key changes that need to happen and aligns well with the first goal for this iteration.

#### Leftover

There's some work individual members of the team are doing this iteration that was left over from the previous, notably @unknwon is working on Enforcing Product Tiers  #11577.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

- @unknwon: July 27 to July 31 (5 days), on vacation.
- @ryanslade: Not working 10th August

### Tracked issues

@asdine: __3.00d__

- [ ] New external_service_repos table [#12711](https://github.com/sourcegraph/sourcegraph/issues/12711) __2d__ 
- [x] Remove cloneInProgress option from Repositories API [#12090](https://github.com/sourcegraph/sourcegraph/issues/12090) 
- [x] mail package deprecated [#10703](https://github.com/sourcegraph/sourcegraph/issues/10703) 🧶
- [x] Ability to disable SMTP TLS verification [#10702](https://github.com/sourcegraph/sourcegraph/issues/10702) __1d__ 👩

@daxmc99: __11.00d__

- [ ] Add operational playbook for updating external database versions [#1099](https://github.com/sourcegraph/about/issues/1099) 
- [ ] RFC 174: Terraform Cloud SQL [#11794](https://github.com/sourcegraph/sourcegraph/issues/11794) __1d__ 
- [ ] RFC 174: HA Postgres for Sourcegraph Cloud [#11496](https://github.com/sourcegraph/sourcegraph/issues/11496) __10d__ 
- [x] Sourcegraph.com - add redis-store & precise-code-intel-bundle-manager snapshotting [#10450](https://github.com/sourcegraph/sourcegraph/issues/10450) 

@keegancsmith

- [x] Rename default branch to `main` [#11464](https://github.com/sourcegraph/sourcegraph/issues/11464) 
- [x] Remove Gitolite blacklist configuration option [#11394](https://github.com/sourcegraph/sourcegraph/issues/11394) 

@ryanslade: __1.00d__

- [x] Add sync time columns to the external_services table [#12701](https://github.com/sourcegraph/sourcegraph/issues/12701) __1d__ 
- [ ] Frontend memory leak [#11790](https://github.com/sourcegraph/sourcegraph/issues/11790) 🐛
- [ ] Add tests for raw endpoint [#11259](https://github.com/sourcegraph/sourcegraph/issues/11259) 🧶

@tsenart

- [x] repo-updater: No private repos on sourcegraph.com [#12908](https://github.com/sourcegraph/sourcegraph/pull/12908) :shipit:

@unknwon: __8.50d__

- [ ] ~Enforcing product tiers~ [#11577](https://github.com/sourcegraph/sourcegraph/issues/11577) __5d__ 🛠️
- [x] Optimize reposourceCloneURLToRepoName [#12944](https://github.com/sourcegraph/sourcegraph/issues/12944) __0.5d__ 
- [x] Update ExternalServicesStore.List to support pagination [#12822](https://github.com/sourcegraph/sourcegraph/issues/12822) __2d__ 
- [x] Update call sites of ExternalServicesStore.List to avoid application-level aggregation [#12760](https://github.com/sourcegraph/sourcegraph/issues/12760) __1d__ 
- [x] Update ExternalServicesStore.List to allow filtering by user [#12704](https://github.com/sourcegraph/sourcegraph/issues/12704) __1d__ 
- [x] It is not called out clearly enough in docs that initial permission synching may take several hours [#12678](https://github.com/sourcegraph/sourcegraph/issues/12678) __0.5d__ 
- [x] auth: password reset page does not respect `auth.minPasswordLength` [#12331](https://github.com/sourcegraph/sourcegraph/issues/12331) __0.5d__ 🐛
- [x] Sourcegraph OSS user settings not accessible [#12191](https://github.com/sourcegraph/sourcegraph/issues/12191) __0.5d__ 🐛
- [ ] gqltest: migrate internal/cmd/search-integration-tester [#12143](https://github.com/sourcegraph/sourcegraph/issues/12143) __1.5d__ 🧶
- [x] Remove on-demand implementation of permissions [#10973](https://github.com/sourcegraph/sourcegraph/issues/10973) __1d__ 🧶

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by asdine** [comment]
### Last week

I finished the work on improving the performance of the site-admin repositories page, and removed the `Cloning` tab as well. This work has been deployed in 3.18.
I also replaced `gophermail`, the deprecated mail package we use by [jordan-wright/email](https://github.com/jordan-wright/email) and added support for sending email to self signed certificates.

### This week

I will work with @unknwon and @ryanslade on preparing a proof of concept for goal 1, and a proposal that will be submitted to the rest of the company.

**Comment by tsenart** [comment]
In my sync with @christinaforney today, we had the idea of using the new Product Document template to capture the context around Goal 1. The exact format and prompts aren't fixed in stone (and you should change them as you see fit) but I think they provide very good structure, aligned with what we were thinking of writing. What do you think @unknwon, @ryanslade, @asdine? Check it out here: https://docs.google.com/document/d/1MBZxnRlDG69Fyvzpai5rBqxizvX5zVeZiUe6z7VZrjk/edit#heading=h.g0gjwch98szj

**Comment by ryanslade** [comment]
> In my sync with @christinaforney today, we had the idea of using the new Product Document template to capture the context around Goal 1. The exact format and prompts aren't fixed in stone (and you should change them as you see fit) but I think they provide very good structure, aligned with what we were thinking of writing. What do you think @unknwon, @ryanslade, @asdine? Check it out here: https://docs.google.com/document/d/1MBZxnRlDG69Fyvzpai5rBqxizvX5zVeZiUe6z7VZrjk/edit#heading=h.g0gjwch98szj

I think that makes sense after we've done the prototype. Initially I was thinking of a simpler document that would describe the feature as user documentation as if it had already been implemented.

**Comment by unknwon** [comment]
> > In my sync with @christinaforney today, we had the idea of using the new Product Document template to capture the context around Goal 1. The exact format and prompts aren't fixed in stone (and you should change them as you see fit) but I think they provide very good structure, aligned with what we were thinking of writing. What do you think @unknwon, @ryanslade, @asdine? Check it out here: [docs.google.com/document/d/1MBZxnRlDG69Fyvzpai5rBqxizvX5zVeZiUe6z7VZrjk/edit#heading=h.g0gjwch98szj](https://docs.google.com/document/d/1MBZxnRlDG69Fyvzpai5rBqxizvX5zVeZiUe6z7VZrjk/edit#heading=h.g0gjwch98szj)
> 
> I think that makes sense after we've done the prototype. Initially I was thinking of a simpler document that would describe the feature as user documentation as if it had already been implemented.

Agree.

**Comment by keegancsmith** [comment]
Cross-posting since I intend to do some work on src-expose this week. This will be some iterative work to make src-expose feel first class.

https://github.com/sourcegraph/sourcegraph/issues/12276#issuecomment-661327625

**Comment by tsenart** [comment]
@sourcegraph/cloud: Can you please add your availability to the tracking issue in the "Availability" section?

**Comment by tsenart** [comment]
Ah well, I see we changed the tracking issue template to show unavailability, rather than availability. I think that makes sense.

**Comment by unknwon** [comment]
**Goal 1 Update (2020-07-21)**:

@ryanslade, @asdine and I paired and worked out the [prototype for _allowing users to add external services_](https://github.com/sourcegraph/sourcegraph/tree/cloud/3.19-prototype) end-to-end. Few more questions raised and added to our [sync notes](https://docs.google.com/document/d/10pw2aRfGu2MHfXauNHm1f6lnyOrhPys4U4n6xQoFIZ8/edit) (Q8-Q11).

Next step: @ryanslade will own writing the initial draft of product document and we will pair again on Thursday to finalize the product document for review.

**Comment by daxmc99** [comment]
**Goal 2 Update (2020-07-22)**

@chayim and I paired on [RFC 194](https://docs.google.com/document/d/1e10UPwmI16VAQleBK81EQMMGTRBgihI1vwL5I6kicrA/edit?usp=sharing) went over the first 3 issues. 
@chayim filed issues to scope out our work (https://github.com/sourcegraph/sourcegraph/labels/RFC-196). 
All of these issues can be tracked with under the Security tracking issue here: https://github.com/sourcegraph/sourcegraph/issues/12300

**Next steps**:
We plan to pair the rest of the week and knock out the numbered RFC issues [1](https://github.com/sourcegraph/sourcegraph/issues/12409),[2](https://github.com/sourcegraph/sourcegraph/pull/12207) and [3](https://github.com/sourcegraph/sourcegraph/issues/12268).

**Comment by unknwon** [comment]
**Goal 1 Update (2020-07-23)**:

@ryanslade, @asdine and I paired and worked on the [product document](https://docs.google.com/document/d/1BBI9poOapbKdjFyLEs9Ren5s5XEYjqcvzTZKpblfucc/edit#) (link might change because it's not the "Product docs" folder as other PDs) that @ryanslade drafted.

Next step:

- @ryanslade will publish the product document and get feedback from stakeholders.
- @asdine will start auditing [sync notes Q14](https://docs.google.com/document/d/10pw2aRfGu2MHfXauNHm1f6lnyOrhPys4U4n6xQoFIZ8/edit#bookmark=id.6w1hnnf6lxf2): _What places in our codebase assume a small number of external services in the database and would break or not scale when that assumption doesn’t hold anymore?_
- We will have another pair session on Friday (2020-07-24) to read code together and get us familiar with relevant codebase.

**Comment by chayim** [comment]
Trying something new.  For work on Goal #2, please see the @sourcegraph/security [tracking issue](https://github.com/sourcegraph/sourcegraph/issues/12300#issuecomment-663690291).  The short version involved @daxmc99 and I pairing together.

**Comment by ryanslade** [comment]
### Last Week

Worked with @unknwon and @asdine on the [product document](https://docs.google.com/document/d/14uorAh8vSWn7P2T42_v4t_jwHgvj7XopieJjIGNhA40/edit)

Looked into memory leaks on the frontend. Haven't found the culprit yet but I've been increasing my understanding of where we're currently producing the most garbage. Currently it's mostly coming from the our graphql layer due to the amount of json encoding and reflection involved there.

### This Week

I'll work with @asdine on preparing an RFC that proposes how we want to allow any user to create external services with the constraint that we only allow **public** code for now. 

I'll continue investigating memory leaks as a second priority.

**Comment by asdine** [comment]
### Last Week 

Worked with @ryanslade and @unknwon on the [product document](https://docs.google.com/document/d/14uorAh8vSWn7P2T42_v4t_jwHgvj7XopieJjIGNhA40/edit). I analysed the code for external services usage and potential scaling issues.
Worked on removing clone in progress option from the Repositories GraphQL API.

### This week

With @ryanslade, we'll pair on preparing an RFC for allowing users to create external services for public code.

**Comment by unknwon** [comment]
### Last week

On vacation 🌴 

### This week

- Catch up things
- I guess my main focus this week would be RFC 211 (haven't actually looked it yet but saw it is mentioned on daily updates)

**Comment by asdine** [comment]
### Last Week

I worked with @ryanslade on [RFC 211](https://docs.google.com/document/d/1K_VzB4RdtiecfH8EuVTwXBuMzUCW4X9e4_vdy0_VZDk/edit?usp=sharing).

### This week

With @ryanslade and @unknwon , we'll prepare tasks based on the RFC and start working on them.

**Comment by daxmc99** [comment]
**Last Week**
Paired with @chayim on RFC 196
Deployed Cloud SQL into the dogfood cluster as a service. 

**This week** 
Continue to pair with @chayim on RFC 196. 
Begin adding sidecars to `cloud` and `dogfood` deployments in preparation to migrate over.

**Comment by ryanslade** [comment]
**Goal 1 Progress**

Did a number of pairing sessions with @asdine on RFC 211 as we iterated based on feedback to the point where we think it's ready for implementation. We aimed to reduce the scope of the RFC to just what is required to support public code on public code hosts while keeping in mind that private code and organisation support is next. We wanted to focus on getting the groundwork right.

Looked into some memory and CPU profiles on Sourcegraph.com to see if there was any low hanging fruit there. Fixed one issue which was leading to a large number of pending timers (https://github.com/sourcegraph/sourcegraph/pull/12553)

**This week**

Extract engineering tasks from RFC 211 and work with @asdine  and @joe on implementation.

**Comment by ryanslade** [comment]
### Team update for Goal 1:

We finished up [RFC 211](https://docs.google.com/document/d/1K_VzB4RdtiecfH8EuVTwXBuMzUCW4X9e4_vdy0_VZDk/edit?ts=5f22adb5#) which is now approved.

We broke out the engineering tasks required to implement the RFC, #12699 . Our goal was to try and break it down to tasks that are all smaller than one day of effort. 

Currently:

* @asdine is working on migrating source information from the `sources` column on the `external_services` table to a new `external_service_repos` table as part of the "Database changes" section of the tracking issue
* @unknwon is working through the "Fetch external services section" of the tracking issue
* @ryanslade is working though the "Repo syncing section" of the tracking issue

We also synced with @daxmc99 and @chayim to ensure that we're not stepping on each other's toes regarding DB changes and have a clear path forward where the two sub teams can work independently.

**Comment by daxmc99** [comment]
** Goal 2 ** 

Preparing the RFC 196 branch for merging (https://github.com/sourcegraph/sourcegraph/tree/tracking-rfc196). 

The encryption store package is done. The focus this week is the data migration and key rotation work (#8 & #9 of the RFC 196). 

The security tracking issue contains the issue breakdown of the remaining work https://github.com/sourcegraph/sourcegraph/issues/12300 

This week:
Syncing closely with @ryanslade & @asdine to follow with encryption changes with their modifications to repo-updater.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by unknwon** [comment]
### Team update for Goal 1:

Continued our engineering work of [RFC 211](https://docs.google.com/document/d/1K_VzB4RdtiecfH8EuVTwXBuMzUCW4X9e4_vdy0_VZDk/edit?ts=5f22adb5#) as described in #12699.

Currently:

* @asdine continues working on migrating source information from the `repo.sources` column to a new `external_service_repos` table as part of the "Database changes" section. The PR #12789 is very close to be merged, fixing broken campaigns tests.
* @unknwon has finished off "Fetching external services" section (except two items that are delegated to @ryanslade), and started working on items in "Handling user deletion" section.
* @ryanslade was shortly blocked and helped out two items in "Fetching external services", now gets back to continue working though the "Repo syncing" section.

**Comment by daxmc99** [comment]
**Team Update for Goal 2 (Store and handle external service and external account secrets securely)**
Took review comments on https://github.com/sourcegraph/sourcegraph/pull/12933. This PR contains only the secret package. 

Upcoming week:
Make PRs for https://github.com/sourcegraph/sourcegraph/issues/12264 & https://github.com/sourcegraph/sourcegraph/issues/12263. 
This work has already been done on the RFC 196 tracking branch. https://github.com/sourcegraph/sourcegraph/compare/tracking-rfc196. It needs to be updated to account for Goal 1 team's changes to repo-updater.
