### ISSUE TITLE
src-cli: Implement new campaigns workflow

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#12333]
Docs/Schema in PR #10921

#### Tasks

- [ ] Implement `src campaigns apply` (see this comment https://github.com/sourcegraph/sourcegraph/pull/10921#issuecomment-648599857)
- [ ] Validate campaign spec YAML according to [schema](https://github.com/sourcegraph/sourcegraph/pull/11675/files#diff-487a75ab312f06a1128bfe31fdb22d8c)
  - I think duplicating that schema between here and `src-cli` is fine for now. If we can find a better solution that has `src-cli` fetch the schema from Sourcegraph: great.
- [ ] Create `changesetSpecs` with the `createChangesetSpec` mutation (see [schema here](https://github.com/sourcegraph/sourcegraph/pull/11675/files#diff-77b00099e496740aabe24323ad5a041e)), remembering their IDs
- [ ] Create `campaignSpec`, using the IDs as input
- [ ] Print preview URL if user doesn't want to apply
- [ ] Call `applyCampaign` if user wants to apply

Plus: clean up the code, possibly add tests, move code to smaller packages instead of the `./cmd` folder, etc.

#### First deliverable

A draft PR that implements the new command and flow for us to test to validate how the UX feels.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
