### ISSUE TITLE
Migrate terraform state to GCP

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#12496]
Currently the following terraform deployments rely on local state, and developers running a `terraform apply` then checking in there code + a state file into the repo. In doing so we assume the risk that developers could corrupt a state file or forget to check it in.

The following terraform deployments should be migrated to use remote state in GCP: 

- [ ] https://github.com/sourcegraph/infrastructure/tree/master/cloud
- [ ] https://github.com/sourcegraph/infrastructure/tree/master/dns
- [ ] https://github.com/sourcegraph/infrastructure/tree/master/site24x7

**TODO**

Determine naming scheme for each deployment
