### ISSUE TITLE
Tracking: Soft launch of indexed search over user added public code

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#12699]
### Database changes
  - [x] Create the external_service_repos table and migrate external_service sources column data to that table. Update stores to read sources data from that new table. #12789 
  - [x] Add namespace_user_id column to the external_services table and update stores to load and store data from that column. #12701 

### Security

- [x] User owned external services are only allowed for Github.com, Gitlab.com and Bitbucket.org. This should be enforced at the API layer as well as being limited by the UI #13430
- [x] Should we disable the `RepositoryPathPattern` config from user added repos? It could potentially allow users to override the name of existing repos
- [x] Ensure that:
  - [x] User added external services can **ONLY** sync public code https://github.com/sourcegraph/sourcegraph/pull/13626
  - [x] Site admin added external services can add public **and** private code https://github.com/sourcegraph/sourcegraph/pull/13626
- [x] secrets: use base64 and make interface private #13850
- [x] Transparent encryption and decryption for all tables that contain secrets or tokens #13851
	- [x] The sources json column returned by `listReposQueryFmtstr` should not include tokens https://github.com/sourcegraph/sourcegraph/issues/13614
- [x] Repository Settings > Mirroring should not display token in the UI #13852
- [ ] Encryption bootstrap #13853
- [x] Eyeball validate data being encrypted in the database #13854
- [ ] User documentation: data security policy #13855
- [ ] Detect and delete public repository added-on-visit when it become private #13978

### Repo syncing
  - [x] Add last_synced_at and next_sync_at to external services table #12701 
  - [x] On cloud, only fetch external services that were created by site admins here: https://github.com/sourcegraph/sourcegraph/blob/a95ac70cc52c8208233591cfbe896706620fa88c/cmd/repo-updater/shared/main.go#L127  
  - [x] Create worker function that syncs a single external service and updates next_sync https://github.com/sourcegraph/sourcegraph/pull/13483
    - [x] We should ignore repositoryPathPattern #13092 
  - [x] Use internal/workerutil to schedule concurrent syncing of external services based on next_sync time. Worker concurrency should be configurable. On Sourcegraph Cloud we need to enable the full syncer, but only for user owned external services. https://github.com/sourcegraph/sourcegraph/pull/13483
  - [ ] Add an alert if our external service job queue grows too large https://github.com/sourcegraph/sourcegraph/issues/14045
  - [x] Complete jobs should be cleaned up from the `external_service_sync_jobs` table
  - [x] Our Diff function always returns true for Modified, we need to improve this so that we can more efficiently backoff: https://github.com/sourcegraph/sourcegraph/blob/cc9ccc4d217bff1f2d94efab1a4bc5e625cc7d90/cmd/repo-updater/repos/types.go#L642
- [x] Investigate the impact of calling SyncSubset from within SyncExternalService. We currently do this via the streaming inserter: https://github.com/sourcegraph/sourcegraph/blob/main/cmd/repo-updater/repos/syncer.go#L178 
- [x] Syncer.SyncSubset is only ever used with one repo. Simplify the code.
- [ ] The repos.Store interface is very large. Can we reduce it by using the DBStore directly in the Syncer and only exposing methods on the store interface that are required outside of the package? https://github.com/sourcegraph/sourcegraph/issues/14092
- [x] The streaming inserter which is called on every sync [fetches all repos](https://github.com/sourcegraph/sourcegraph/blob/main/cmd/repo-updater/repos/syncer.go#L506), but only needs external ids. We should switch to a dedicated query #13671
- [ ] `SyncExternalService` now has some complicated name conflict resolution. Can we make this simpler be fetching repos from the currently syncing external service AND any possible conflicts before calculating the diff?
- [x] SyncExternalService is provided a Store that is already in a transaction as it is passed in by the worker handler. This means that the streaming inserter also uses a transaction which probably doesn't make sense as all repos will roll back on failure.
- [ ] Write some high level documentation describing how repo updater currently works while it is fresh
- [x] New syncer should use it's own logger: https://github.com/sourcegraph/sourcegraph/issues/13718
- [ ] Should `SyncRepo` include the external service as a parameter? Perhaps we should be passing in the default GitHub and GitLab repos as a param? This would ensure that there is no way for a repo to be added without a corresponding entry into `external_service_repos`

### Fetching external services
- [x] Update [ExternalServicesStore.List](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5d73f94a7ad9c8c5a5d30954f737e9dde5c2a8b5/-/blob/internal/db/external_services.go#L405) to allow filtering by user. #12704
- [x] Update call sites of [ExternalServicesStore.List](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5d73f94a7ad9c8c5a5d30954f737e9dde5c2a8b5/-/blob/internal/db/external_services.go#L405) to avoid application-level aggregation. #12760
- [x] Update [ExternalServicesStore.List](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5d73f94a7ad9c8c5a5d30954f737e9dde5c2a8b5/-/blob/internal/db/external_services.go#L405) to support pagination. #12822
- [x] Update repo-updater [SyncRateLimiter](https://github.com/sourcegraph/sourcegraph/blob/6523cb1e6e9f80d8240e0358940694c3ac7dcf49/cmd/repo-updater/repos/types.go#L949) to support pagination. https://github.com/sourcegraph/sourcegraph/pull/12911 https://github.com/sourcegraph/sourcegraph/pull/13002
- [x] Update API clients of [external services endpoints](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a587a76/-/blob/cmd/frontend/internal/httpapi/router/router.go#L112-113) to support pagination. https://github.com/sourcegraph/sourcegraph/pull/12975
- [x] Optimize [reposourceCloneURLToRepoName](https://github.com/sourcegraph/sourcegraph/blob/a547a87f9d3a447be90e2c53760f4792799e8e2c/cmd/frontend/graphqlbackend/git_tree_entry.go#L203) #12944

### Search
  - [ ] ~Amend search logic to fetch a list of repos configured by a user and include them by default when no repo filter is provided.~ Ensure that repos added by users are included in the search index.

### Handling deletion
  - [x] When a user is deleted (both soft and hard), update their external services deleted_at column. #12965
  - [x] ~~Ensure any entry in external_service_repos is deleted in cascade~~
  - [x] When an external service is (soft or hard?) deleted, determine which repos are orphaned by counting the number of references in the external_service_repos table and marked them as deleted. This must be done within the same transaction as the one deleting the external service. We need to be careful that if a repo is SOFT deleted it can be added later without causing this index to fail: `"repo_external_unique_idx" UNIQUE, btree (external_service_type, external_service_id, external_id)`   #13273

### Progressive rollout
  - [x] Add the external_service_user_mode feature flag as part of the configuration. By default, it will be disabled but if it contains public it will be considered enabled for public code. Anything other than public will disable the flag. Use the flag to protect the external service config page and related GraphQL api to users. #13052
  - [x] Add external_service_user_allow_list configuration option. It will contain a list of regex patterns that must be used to limit the users who will be able to create external services if the external_service_user_mode flag is enabled. https://github.com/sourcegraph/sourcegraph/pull/13099
  - [x] Add external_service_user_allow_percentage configuration option. It will contain a value from 0 to 100. If the external_service_user_mode flag is enabled, use that value to limit the number of users that can create external services, by hashing their user id and applying a modulo 100 on it. If the result is under that value, the user has access to that feature. https://github.com/sourcegraph/sourcegraph/pull/13099
  - [x] If a user is already allowed by external_service_user_allow_list, ignore this check https://github.com/sourcegraph/sourcegraph/pull/13099

**NOTE**: The above three items can all be solved by checking for tag existing on a user. For now, if a user has the `AllowUserExternalServicePublic` tag they will be allowed to add their own external services. 

- [x] Create the SQL script that opts in a certain percentage of users. It should be based on a hash of the user id so that running it again with an increased percentage has the desired effect.

This seems to do the trick:
```sql
-- Get a repeatable sample of 10%
WITH sample as (SELECT id FROM users TABLESAMPLE BERNOULLI(10) REPEATABLE(1))
-- Update users in the sample
UPDATE users SET tags = array_append(tags, 'AllowUserExternalServicePublic')
WHERE EXISTS (SELECT id from sample)
-- Unless they are already tagged
AND NOT(tags @> ARRAY['AllowUserExternalServicePublic']);
```

### Metrics
  - [x] Track number of code host connections added by users #13589
  - [x] Track total number of repositories added by users #13589
  - [x] Average repos per user can be derived from the above #13589
  - [ ] Track whether a user has added any external service (@ebrodymoore will help with this)
  	- [ ] Given the above, we can derive the visits per user with their own external services vs without
  - [ ] ~~Track when feature flag is enabled~~ (@unknwon: I think the metrics can be exposed regardless)
  - [x] Syncer metrics need to include external service id https://github.com/sourcegraph/sourcegraph/pull/13742
### Abuse mitigation
  - [ ] Update repo-updater to support user-added repo listing limits per user. https://github.com/sourcegraph/sourcegraph/issues/14043
  - [ ] Update repo-updater to support user-added repo listing limits in total. https://github.com/sourcegraph/sourcegraph/issues/14043
### Load testing
  - [ ] TODO
### UI Changes
  - [x] Replicate pages for “manage repositories”. #13095
  - [x] Backend changes to allow CRUD of external services by users. #13173
  - [x] Web app should respect feature flag in JSContext per user. #13095

**Comment by quinnkeast** [comment]
I've removed design recommendations from this tracking issue based on our decisions this week.

**Comment by ryanslade** [comment]
I'm closing this as all items are now either done or tracked in their own issue
