### ISSUE TITLE
Distribution 3.20 Tracking issue

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#12836]
#### [Support new and existing deployments](https://github.com/orgs/sourcegraph/projects/74)

This is an ongoing expense, we anticipate this taking no more than 10d of work spread across the entire team.

#### [Support teams migration to per-team alerts](https://github.com/orgs/sourcegraph/projects/73)

We have enabled per-team alerts and on-call rotations on [3.19](https://github.com/sourcegraph/sourcegraph/issues/11954), as teams onboard to this new workflow we will need to provide support and guide them through the transition.

#### [Reduce upgrade overhead](https://github.com/orgs/sourcegraph/projects/71)

We decided to move forward with the Dhall implementation and we will work on defining a roadmap for it **(spike)**. Additionally, we will work on a "`yaml-to-dhall`" and define a Dhall architecture that supports customizations **(spike)**.

- @ggilmore 
- @uwedeportivo 
- @davejrt 
- @bobheadxi 

#### [Enable failed e2e test notifications and blocking the pipeline](https://github.com/orgs/sourcegraph/projects/72)
Although we run the e2e tests daily, their failures are not visible to all which means at the end of the iteration we must ask teams to pitch in on short notice.
We will inline our e2e tests and notify engineers when a merge breaks our e2e tests to ensure our `main` branch is always in a working state.

- @slimsag 
- @davejrt 
- @pecigonzalo 

#### [Dogfood Kubernetes deployments](https://github.com/orgs/sourcegraph/projects/83)

Deployments to dogfood-k8s are automated from our latest images and reflect our customer’s workflow. [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) is kept up to date with our latest images. 

- @bobheadxi
- @pecigonzalo
- @ggilmore
- @slimsag

### Availability

Period is from **August 20th** to **September 19th (22 working days)**. Please write the days you won't be working and the number of working days for the period.

- **Gonza**: 22d

### Tracked issues

@bobheadxi

- [x] RFC-189: follow up with distribution, cloud, code-intel, search to set up opsgenie rotations [#12899](https://github.com/sourcegraph/sourcegraph/issues/12899) 
- [x] monitoring: remove custom alertmanager from cloud [#12160](https://github.com/sourcegraph/sourcegraph/issues/12160) 
- [x] monitoring: align ObservableOwners with current teams [#13075](https://github.com/sourcegraph/sourcegraph/issues/13075) 
- [x] k8s.sgdev.org: automate pull requests from deploy-sourcegraph [#13121](https://github.com/sourcegraph/sourcegraph/issues/13121) 
- [x] bundled alertmanager does not start up correctly in some environments with clustering enabled [#13079](https://github.com/sourcegraph/sourcegraph/issues/13079) 🐛
- [x] cadvisor: investigate collecting IO metrics [#12163](https://github.com/sourcegraph/sourcegraph/issues/12163) 
- [x] deploy-sourcegraph: have Renovate apply image updates as soon as they are built [#13122](https://github.com/sourcegraph/sourcegraph/issues/13122) 
- [ ] ~on-call: document actions to follow up on critical alerts~ [#1468](https://github.com/sourcegraph/about/issues/1468) 
- [ ] ~dogfood-k8s: finalize migration over to new cluster~ [#13792](https://github.com/sourcegraph/sourcegraph/issues/13792) 
- [x] k8s.sgdev.org: reset deploy-sourcegraph-dogfood-k8s using deploy-sourcegraph [#13120](https://github.com/sourcegraph/sourcegraph/issues/13120) 

@davejrt

- [x] baremetal buildkite agent networking / instability issues [#12996](https://github.com/sourcegraph/sourcegraph/issues/12996) 
- [x] Bare-metal Buildkite agents capable of running Docker and VMs [#12101](https://github.com/sourcegraph/sourcegraph/issues/12101) 
- [x] dhall: create "base" version of records and explicitly import into templating logic [#13336](https://github.com/sourcegraph/sourcegraph/issues/13336) 
- [x] dhall: customization architecture discussion [#13335](https://github.com/sourcegraph/sourcegraph/issues/13335) 

@daxmc99

- [x] sourcegraph/security-issues [#95](https://github.com/sourcegraph/security-issues/issues/95) 

@ggilmore

- [ ] ~ci: build and pin tool apks in CI for release~ [#13297](https://github.com/sourcegraph/sourcegraph/issues/13297) 🧶
- [x] dhall: create "base" version of records and explicitly import into templating logic [#13336](https://github.com/sourcegraph/sourcegraph/issues/13336) 
- [x] dhall: customization architecture discussion [#13335](https://github.com/sourcegraph/sourcegraph/issues/13335) 

@keegancsmith

- [x] sourcegraph/customer [#96](https://github.com/sourcegraph/customer/issues/96) 👩

@pecigonzalo

- [x] Document and pin Git version requirement [#13168](https://github.com/sourcegraph/sourcegraph/issues/13168) 🎩
- [x] Reduce the impact of unplanned work [#11904](https://github.com/sourcegraph/sourcegraph/issues/11904) 
- [x] k8s.sgdev.org: reset deploy-sourcegraph-dogfood-k8s using deploy-sourcegraph [#13120](https://github.com/sourcegraph/sourcegraph/issues/13120) 
- [x] Codecov coverage checks taking a long time [#13695](https://github.com/sourcegraph/sourcegraph/issues/13695) 
- [ ] ~dogfood-k8s: finalize migration over to new cluster~ [#13792](https://github.com/sourcegraph/sourcegraph/issues/13792) 

@slimsag

- [ ] ~sourcegraph/customer~ [#71](https://github.com/sourcegraph/customer/issues/71) 👩
- [x] Update all images to alpine:3.12 [#13035](https://github.com/sourcegraph/sourcegraph/issues/13035) 🧶
- [x] sourcegraph/customer [#94](https://github.com/sourcegraph/customer/issues/94) 👩
- [x] Prevent usages of `alpine` with a linter [#13247](https://github.com/sourcegraph/sourcegraph/issues/13247) 🎩
- [ ] ~sourcegraph/customer~ [#90](https://github.com/sourcegraph/customer/issues/90) 🐛👩
- [x] sourcegraph/customer [#74](https://github.com/sourcegraph/customer/issues/74) 👩
- [ ] ~Run e2e tests on bare-metal Buildkite agents on every commit to master (non-blocking)~ [#12339](https://github.com/sourcegraph/sourcegraph/issues/12339) 
- [ ] ~Run e2e "regression" tests on bare-metal Buildkite agents on every commit to master (non-blocking)~ [#12340](https://github.com/sourcegraph/sourcegraph/issues/12340) 
- [x] Put plan forward: Push site admins to use Docker Compose or Kubernetes for production deployments [#11828](https://github.com/sourcegraph/sourcegraph/issues/11828) 
- [ ] ~License report for syntect_server & its dependencies; remove syntaxes with questionable licenses~ [#11269](https://github.com/sourcegraph/sourcegraph/issues/11269) __1d__ 👩
- [ ] ~sourcegraph/customer~ [#97](https://github.com/sourcegraph/customer/issues/97) 👩
- [x] Stephen's Dhall PoC [#13798](https://github.com/sourcegraph/sourcegraph/issues/13798) 
- [x] sourcegraph/customer [#101](https://github.com/sourcegraph/customer/issues/101) 👩
- [x] sourcegraph/customer [#96](https://github.com/sourcegraph/customer/issues/96) 👩
- [x] sourcegraph/customer [#95](https://github.com/sourcegraph/customer/issues/95) 👩
- [x] managed instances: overhaul / clarify / update customer-facing docs [#13705](https://github.com/sourcegraph/sourcegraph/pull/13705) :shipit:
- [x] distribution: answer "Why is there not a stable or latest Docker image tag?" [#1435](https://github.com/sourcegraph/about/pull/1435) :shipit:

@uwedeportivo: __2.00d__

- [x] sourcegraph/customer [#95](https://github.com/sourcegraph/customer/issues/95) 👩
- [ ] ~Repo-updater component always outputs debug logs~ [#13191](https://github.com/sourcegraph/sourcegraph/issues/13191) __1d__ [👩](https://app.hubspot.com/contacts/2762526/company/1712883009)🎩
- [x] create deploy-sourcegraph to dhall record migration tool [#13306](https://github.com/sourcegraph/sourcegraph/issues/13306) __2d__ 
- [x] docker compose deployment ssh configuration docs [#13465](https://github.com/sourcegraph/sourcegraph/issues/13465) 
- [x] dhall: create "base" version of records and explicitly import into templating logic [#13336](https://github.com/sourcegraph/sourcegraph/issues/13336) 
- [x] dhall: customization architecture discussion [#13335](https://github.com/sourcegraph/sourcegraph/issues/13335) 
- [x] sourcegraph/customer [#82](https://github.com/sourcegraph/customer/issues/82) 👩
- [x] sourcegraph/customer [#96](https://github.com/sourcegraph/customer/issues/96) 👩

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by slimsag** [comment]
Update:

Overall not as productive a week as I would've liked, but I'm content. Addressed debt (Alpine 3.12 update in all images, unifying base docker images, adding linters to use it always), investigated baremetal buildkite agents with Dave and settled on final solution for running e2e and Docker tests, discussed next steps on Firecracker code intel, reviewed some RFCs, learned some Dhall to keep up to speed with it, and helped customers via https://github.com/sourcegraph/customer/issues/96 https://github.com/sourcegraph/customer/issues/99 https://github.com/sourcegraph/customer/issues/90 and had syncs/calls with https://sourcegraph.slack.com/archives/CMB6K7SMN/p1598639367073200 https://sourcegraph.slack.com/archives/CMB6K7SMN/p1598644460077400 as well as an interview and others.

**Comment by uwedeportivo** [comment]
update:

worked on dhall deploy-sourcegraph. have to admit, it's a lot of fun. geoffrey and i landed the migration tool. playing with the idea of ingesting a k8s dhall schema in golang and transforming it so that lists become records with keys extracted from some specific fields in the list elements. we need this to get to these specific elements. you can access list elements by index but finding out which element you are currently looking at is tricky because dhall intentionally limits you so you are forced to compose stronger schemas (lists are weak). so far i think this is the only substantial hurdle. we also want to decide if we want to be as detailed as the current k8s schemas or more simplified. both approaches have advantages and disadvantages.

**Comment by ggilmore** [comment]
Update:

- Planned Dhall roadmap with @uwedeportivo 
- Reviewed @uwedeportivo 's work on the dhall migrator, and setup a lot of tooling around it:
   - https://github.com/sourcegraph/ds-to-dhall
   - https://github.com/sourcegraph/homebrew-ds-to-dhall
   - https://github.com/sourcegraph/asdf-ds-to-dhall 
- Organized kickoff meeting to onboard @davejrt and @bobheadxi to the Dhall project. We will meet on Tuesday/Wednesday to check in, and then we'll kick off https://github.com/sourcegraph/sourcegraph/issues/13335

**Comment by bobheadxi** [comment]
**last week**

Worked on a GitHub Actions-based workflow for driving updates from deploy-sourcegraph to deploy-sourcegraph-k8s-dogfood-2 (including feedback on failure), which is pretty much complete. Worked with Gonza on identifying relevant changes for the original dogfooding environment. Attempted to update the k8s.sgdev.org, but was unable to get the deploy to work - will probably abandon the effort in favour of deploying the new dogfood config. Set up PRs for the remaining issues in the dogfooding project (https://github.com/sourcegraph/sourcegraph/pull/13449 , https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/3304 ) but this requires a bit more work / validation - spent a lot of time going over renovate docs and trying to figure out how to best set up deploy-sourcegraph being kept up to date. Looked into various alerts that have been coming through #opsgenie and tried to follow up on some of them. Looked at dhall stuff too as Geoffrey noted

**this week**

I've been waiting for an update to come in to deploy-sourcegraph to try out the test PR to mark it as done, but I'll figure out a good way to just go ahead and verify that this week and mark it as complete. Will also be trying to wrap up work on the new dogfood environment (including deploying it). I would like to write some docs for https://github.com/sourcegraph/about/issues/1468 as well, since following up on the new alerts has been a bit of a topic recently, and possibly treating this as my "debt" ticket.

I am also transitioning to a new [part-time schedule](https://sourcegraph.slack.com/archives/CJX299FGE/p1598629268150800)

**Comment by davejrt** [comment]
**Last week**

Worked on closing out #12101 and resolving the subsequent issues with virtualbox running on GCP. The decision to sue the vagrant-google plugin has been made as it's a lot more reliable, requires less resources than local testing and is a lot quicker. 

Met with Geoffrey and began proper on boarding to work on Dhall. Some addition work to upgrade the bigdata cluster and assist $CUSTOMER with an upgrade

**This week**

working on any last minute feedback for sourcegraph/deploy-docker#141 and beginning work on Dhall with the help of Uwe and Geoffrey. This will intially be a smaller project then onto more assigned issues as delegated by Geoffrey.

**Comment by pecigonzalo** [comment]
#### Last week
Last week was mostly a technical week, I worked through bugs, issues and alerts to try and reduce the number of events we receive daily. We identified a [problem](https://docs.google.com/document/d/1dtrOHs5STJYKvyjigL1kMm6u-W0mlyRSyVxPfKIOfEw/edit#bookmark=id.7bmlvlgpkt06) with some searches which were used in **saved searches** causing them scan all repositories.
I have also worked with @bobheadxi on the new dogfood instances and will continue that work this week.

#### This week
Ill continue to work on how to improve our API for support requests ass well as how we prioritize them to ensure we are working effectively. On a related task I would like to define how we prioritize the backlog, which relates to this as it affects how we revisit tasks/issues that were not set as high priority. 
I have also started to work on a draft of our long-term team objectives and how we scale the team as we grow.

#### Team update
We have closed the [per-team alerts](https://github.com/orgs/sourcegraph/projects/73) project :tada:!

**Comment by slimsag** [comment]
**This week**

Learned some more Dhall and discussed architecture plan with everyone, put forward RFCs [to deprecate single container deployments](https://github.com/sourcegraph/sourcegraph/issues/11828#issuecomment-685978554), sync'd with Bunny on proposal [to stop versioning our docs by branches](https://github.com/sourcegraph/sourcegraph/issues/13471), and had other regular meetings. Around Wed I had some personal / cat issues and had to take off Thur and Fri.

**Next week**

I am hoping to make forward progress on my assigned issues with the aim of completing everything assigned to me, I think it is still a reasonable workload currently and am optimistic things in my personal life will calm down soon, but will have to play it by ear a bit.

**Comment by davejrt** [comment]
**This week**

Closed out the first phase of e2e testing for deploy-sourcegraph-docker with the help of Gonza and Stephen. The rest of my time has been spent learning dhall and syncing with Geoffrey and Uwe who have been really helpful in helping me level up

**Next Week**

There are still some outstanding tasks related to e2e testing, which I will clarify with Stephen. I'm hoping to attack some of the tasks in the the Dhall POC. In addition to this I want to work with Gonza and Robert on our next steps related to monitoring (site24x7 and blackbox exporer) and how we get the best out of both.

**Comment by bobheadxi** [comment]
**this week**

Attempting my new part-time schedule. Verified dogfood PR automation is working (https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s-2/pull/20) and landed some work on improving Sourcegraph -> deploy-sourcegraph image updates, but this doesn't seem to be working as expected currently. Made various changes to docs ([updated release process](https://github.com/sourcegraph/about/pull/1517), fixing links, [reorganizing to add space for more deployment details](https://github.com/sourcegraph/about/pull/1518)). Did some Dhall learning ([task](https://github.com/sourcegraph/deploy-sourcegraph-dhall/pull/29), reading up about ideas for architecture)

**next week**

Wrap up work on dogfooding environment - finalize the image update changes, and have scheduled time with @pecigonzalo to run through deployment of the new environment. Did not get around to https://github.com/sourcegraph/about/issues/1468 this week, and still have my eyes on that, as well as exploring Dhall PoC tasks.

**Comment by ggilmore** [comment]
Last week: 
- Established the Dhall Roadmap
- Planned and kicked off https://github.com/sourcegraph/sourcegraph/issues/13120
- Created a number of tools / scripts / asdf-plugins to help with Dhall + boostrapping repositories. The final output is https://github.com/ggilmore/kickstart
- Met with the creator of Dhall and exchanged feedback

next week:
- schedule check-in meeting for https://github.com/sourcegraph/sourcegraph/issues/13120
- create longer time dhall roadmap
- start working on my implementation of https://github.com/sourcegraph/sourcegraph/issues/13120
- meet with @pecigonzalo and @uwedeportivo about Dhall meeting

**Comment by uwedeportivo** [comment]
last week:

- improvements to dhall migration tool (transformations, flexible input, ignore lists)
- pushed out 3.19.2
- participated in a lot of dhall discussions
- worked on my solution to https://github.com/sourcegraph/sourcegraph/issues/13335
- met with dhall creator

next week:

- finish up my solution to https://github.com/sourcegraph/sourcegraph/issues/13335 and pitch it
- do the repo-updater log work (quality of life task)

**Comment by pecigonzalo** [comment]
#### Last week
I started to work on our long-term objectives and scaling the team, but did not make the progress I wanted to. Ill continue to work on it this week. Dan opened an [initial draft](https://github.com/sourcegraph/about/pull/1521/files) of our escalation process and I intend to draft a PR to update our incident response and support "on-call/hero" rotation as discussed during our sync.

#### This week
As I was unable to make sufficient progress last week, this week's focus remain the same for the most part.

#### Team update
We will additionally kick-off planning 3.21.

**Comment by davejrt** [comment]
**Last week**

More or less fully on e2e testing. Setting up the e2e tests running on a vagrant box instead of the unreliable docker in docker solution. A little bit of dhall but to be honest, I feel as though I've dropped the ball on that and given my own desire in getting e2e running, I have been more of a passenger with Dhall. 

**This week**

Close out e2e testing and catch any low hanging fruit with Dhall. Also spoke with Gonza about our next steps with site24x7 vs blackbox exporter which may be pulled in for 3.20 more than likely pushed out to 3.21 as tech debt.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by pecigonzalo** [comment]
**Last week**
I have created a draft [update of our goals](https://github.com/sourcegraph/about/pull/1553/files) and started a document to update our incident management process as a follow-up to Dan's https://github.com/sourcegraph/about/pull/1521.
We also deployed a new dogfood cluster with @bobheadxi which will replace the old Pulumi based deployment.

**This week**
Ill continue to work on the goals adding some time estimates and other goals in our backlog as well as ad draft update to our incident management documents. I would also like to finish the new dogfood deployment by the end of the week.

**Team update**
We have bumped some items ([#1221](https://github.com/sourcegraph/about/pull/1221) and #5487) to 3.21 as we shift focus to some customer issues and reviewing the Dhall implementation architecture.

**Comment by slimsag** [comment]
**Last week**

Interviewed Cloud and CE candidates, overhauled customer-facing managed instance docs, brainstormed LSIF postgres move with Eric. Chatted with https://app.hubspot.com/contacts/2762526/companies/list/view/all/?query=apple about multi-region deployments and more. Figured out next steps of Dhall with Uwe and Geoffrey and swapped some of my planned work to help out further there, spending about ~6h total on my Dhall PoC.

**This week**

Close out my planned work for this iteration, 3.21 planning.

**Comment by bobheadxi** [comment]
**Last week**

Got really sucked up into [dogfooding](https://github.com/orgs/sourcegraph/projects/83) with various issues with GitHub Actions payloads and formatting, Renovate confusions and [bug](https://github.com/renovatebot/renovate/pull/7274), and actually deploying the whole thing with @pecigonzalo . The first two ended up being very time consuming due to the tedious nature of testing this kind of stuff ([act](https://github.com/nektos/act) not being a perfect simulation of Actions, Renovate needing to be set up in the target repository before things can be tested, bug was rather hard to trace down).

**This week**

Finalize dogfood deployment (https://github.com/sourcegraph/sourcegraph/issues/13792) and landing the Renovate bug fix (https://github.com/renovatebot/renovate/pull/7274) to close out the remaining issues for this iteration, and start looking at 3.21 tasks. Also merge https://github.com/sourcegraph/about/pull/1517

**Comment by ggilmore** [comment]
Last week:

- Decided with @uwedeportivo to onboard @slimsag to the dhall work
- Did some 3.21 planning
- Helped investigate bugs with ds-to-dhall and various tools 
- Started work on my dhall proof of concept 

This week: 
- More 3.21 planning
- Heads down on my dhall proof of concept. I'm worried that I'm kind of going in circles with this one, but I think I'll have something to show even if it's rough.

**Comment by bobheadxi** [comment]
**last week**

I spent most of the week finalizing the work on the new k8s.sgdev.org deployment with @pecigonzalo 's help, and have wrapped up most of that work and made the DNS switch to have the k8s.sgdev.org domain point to the new deployment ([announcement](https://sourcegraph.slack.com/archives/C0EPTDE9L/p1600531167006800)). I wrote up [documentation](https://github.com/sourcegraph/about/pull/1579) updating our information about our existing deployments as well as adding details about the new dogfood cluster.

**this week**

I took a look at some of the 3.21 tasks for single-day releases, and will start tackling some of them this week. I'll also figure out how to fix one last outstanding issue with the k8s.sgdev.org deployment ([thread](https://sourcegraph.slack.com/archives/C01AS4GCA90/p1600265077000800)) and given no complaints, spin down the old cluster to close out https://github.com/sourcegraph/sourcegraph/issues/13792 .

**Comment by ggilmore** [comment]
last week: 

- 3.21 Planning 
- prepared Dhall proof of concept for architecture meeting 

next week:

- pick services for sourcegraph.com dhall migration work
- identify substeps for each service (choose customizations, documentation, etc.)

**Comment by pecigonzalo** [comment]
**Last week**
We closed the plan for [3.21](https://github.com/sourcegraph/sourcegraph/issues/13675) and merged [updated team goals](https://github.com/sourcegraph/about/pull/1553]. I have also started a draft for and development tools team (final name TBD), its vision and an initial job description.

**Next week**
Start working on the GCP split project, by moving the e2e CI resources to a new project. I would also like to finish the draft for development tools team.
