### ISSUE TITLE
Cloud 3.20 Tracking issue

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#13144]
#### Soft launch of fast indexed search over user added public code from github.com, gitlab.com and bitbucket.org

Everyone on the team is working towards this goal this iteration. We want to progressively launch this feature to more and more users while monitoring performance impact and end user experience. There are components of UI/UX, security, load testing and more to be worked on. @ryanslade will be coordinating the scoping and refinement of this work in #12699.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

- @tsenart: Off from the 20th of August until the 7th of September 🌴 

### Tracked work

@ElizabethStirling

- [x] Auth: explicit session invalidation [#1126](https://github.com/sourcegraph/sourcegraph/issues/1126) 🔒

@Unassigned

- [x] Record and expose LOC metric in Zoekt [#13713](https://github.com/sourcegraph/sourcegraph/issues/13713) 

@asdine

- [x] New external_service_repos table [#12711](https://github.com/sourcegraph/sourcegraph/issues/12711) 

@daxmc99: __11.00d__

- [ ] RFC 174: Terraform Cloud SQL [#11794](https://github.com/sourcegraph/sourcegraph/issues/11794) __1d__ 
- [ ] RFC 174: HA Postgres for Sourcegraph Cloud [#11496](https://github.com/sourcegraph/sourcegraph/issues/11496) __10d__ 
- [x] sourcegraph/security-issues [#95](https://github.com/sourcegraph/security-issues/issues/95) 

@keegancsmith: __0.50d__

- [x] GitLab OAuth certificate signed by unknown authority [#4652](https://github.com/sourcegraph/sourcegraph/issues/4652) __0.5d__ 🐛👩

@ryanslade

- [x] repo-updater: Remove repos.FakeStore [#13403](https://github.com/sourcegraph/sourcegraph/pull/13403) :shipit:

@unknwon: __5.50d__

- [x] Bitbucket Server permissions only supports <2500 repositories [#12671](https://github.com/sourcegraph/sourcegraph/issues/12671) __0.5d__ 
- [x] authz: remove deprecated permissions site configs [#12357](https://github.com/sourcegraph/sourcegraph/issues/12357) __0.5d__ 🧶
- [x] gqltest: migrate internal/cmd/search-integration-tester [#12143](https://github.com/sourcegraph/sourcegraph/issues/12143) __1d__ 🧶
- [x] gqltest: enable in CI on `main` branch [#11579](https://github.com/sourcegraph/sourcegraph/issues/11579) __2d__ 
- [x] GitHub OAuth certificate signed by unknown authority [#13461](https://github.com/sourcegraph/sourcegraph/issues/13461) __0.5d__ 🐛
- [x] Migrate Grafana Permissions panel to the new format [#9923](https://github.com/sourcegraph/sourcegraph/issues/9923) __1d__ 
- [x] Site admins will not receive critical alerts if permission syncing is failing [#12673](https://github.com/sourcegraph/sourcegraph/issues/12673) 
- [x] No alerts fire if repository permissions add substantial performance issues [#12676](https://github.com/sourcegraph/sourcegraph/issues/12676) 
- [x] schema: remove deprecated authz fields [#13395](https://github.com/sourcegraph/sourcegraph/pull/13395) :shipit:
- [x] web: add pages to CRUD user-added external services [#13095](https://github.com/sourcegraph/sourcegraph/pull/13095) :shipit:

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by ryanslade** [comment]
### Goal Update for week ending 28th August

Progress on individual tasks can be seen here:
https://github.com/sourcegraph/sourcegraph/issues/12699

Main highlights were:
* A lot of pairing between @ryanslade and @asdine on repo updater. We're at the point now where external services can be synced individually and we've switched to using the `workerutil` package. All old tests are passing and manual testing shows things working as expected. The last step is to add some specific integration tests for the new work
* Initial version of UI changes merged: https://github.com/sourcegraph/sourcegraph/pull/13095
* Removed `repos.FakeStore` which was becoming a pain point.

**Comment by ryanslade** [comment]
### Goal Update for week ending 4th September

Progress on individual tasks can be seen here:
https://github.com/sourcegraph/sourcegraph/issues/12699

Main highlights were:
* Again a lot of pairing between @asdine and @ryanslade on #13483. It's been through PR review and there is only one outstanding issue which is how to deal with the same repo having different data when it belongs to more than one external service. The old syncer could see the whole picture and could deterministically merge them. The new syncer only has a view of one external service. A potential solution has been proposed, awaiting feedback: https://github.com/sourcegraph/sourcegraph/pull/13483#issuecomment-687225826
* Metrics added
* Work started on ensuring private code is never synced
* Work started on indexing code added by user services

**Comment by ryanslade** [comment]
### Goal Update for week ending 11th September

Progress on individual tasks can be seen here:
https://github.com/sourcegraph/sourcegraph/issues/12699

Main highlights were:
* Again a lot of pairing between @asdine and @ryanslade on #13483. We merged it near the end of the week and deployed to sourcegraph.com. Unfortunately we found an issue with one of our queries that meant it no longer used an index. This caused a large increase in latency so we decided to roll back. We have fixed that issue but will continue testing on k8s.sgdev.org and are unlikely to merge into main until after branch cut. We don't want it going out to customers until we are more confident.
* We are hoping to be able to merge soon after branch cut and trial there with sourcegraph employees

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
