### ISSUE TITLE
Allow exporting of campaign spec YAML

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#13210]
Right now, users can only edit/update a campaign if they have the matching campaign spec on their local machine.

That's especially important for customers who used campaigns before 3.19: their old campaigns have been migrated to the new workflow, but users don't have a way to update the campaigns.

But in our API the `CampaignSpec`s have these two fields:

https://github.com/sourcegraph/sourcegraph/blob/7c6b54b53e62cefba87142b100cfacdf0bce7aa6/cmd/frontend/graphqlbackend/schema.graphql#L648-L653

That should allow us to offer an export or download button on the campaigns page.

For new campaigns, we could simply download the original input, since that would contain comments etc.

For pre-3.19 campaigns we don't have the original input, but could convert the parsed input from JSON to YAML client-side and then download it.

cc @sourcegraph/campaigns 

**Work items**
- [x] Make src-cli provide the original input, rather than a json serialized version
- [x] Ask for design
- [x] Expose raw spec on campaign
- [x] Add initial implementation
- [x] Reconcile with figma, once designs are ready
