### ISSUE TITLE
Web: 3.20 Tracking issue

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#13290]
### Plan

For 3.20, the web team continues on their focus started last iteration to improve UI/UX, consistency and discoverability in the web app. We want to implement @quinnkeast's improvements of the sign-in/sign-out flow. In the theme of improving discoverability, we want to kick off the project to improve browser extension discoverability ([RFC 221](https://docs.google.com/document/d/19f4xleYBU1zZZdqMmXlLmFxeR-fwEpOwTOgViOFOnyo/edit#heading=h.trqab8y0kufp)) so we can implement it in 3.21. This needs to be designed first, but from our retrospective learnings we will involve ourselves in the design process from the start.

Leading to our medium term goal (2) of bringing the extensions platform into shape while connecting it with UI/UX improvements of the webapp, we will improve the UI/UX of the extensions registry, a project @AlicjaSuska has worked on and @tjkandala has done some work on as part of his onboarding. This is part of [RFC 209](https://docs.google.com/document/d/1I5BMEGp3QuB81AjSzLCQwq_XJV1sXevlU0lpB4O1pj8/edit#heading=h.trqab8y0kufp).

We also need to follow-up with a solution to test extensions with our new integration test suite, which is a prerequisite to have anything to test in the browser extension, important for our long-term goal around extensions and to allow other teams (code intel) to build on well-tested code.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

- Felix: 2 weeks vacation 2020-09-07 - 2020-09-18

### Tracked issues

@Unassigned

- [ ] RFC 221 Tracking issue: Improve discoverability/awareness of the browser extension ([#14165](https://github.com/sourcegraph/sourcegraph/issues/14165)) 

@felixfbecker: __1.00d__

Completed: __1.00d__
- [x] (🏁 28 days ago) 'About Sourcegraph' and 'Help' pages should be opened in the separate tab ([~#12286~](https://github.com/sourcegraph/sourcegraph/issues/12286)) __0.5d__ 
- [x] (🏁 26 days ago) Rendering of Directory Children With Single Folder Is Confusing ([~#13231~](https://github.com/sourcegraph/sourcegraph/issues/13231)) __0.5d__ 🐛👩

@marekweb: __1.00d__

- [ ] Investigate creation of Safari browser extension ([#13499](https://github.com/sourcegraph/sourcegraph/issues/13499)) __1d__ 🕵️

Completed
- [x] (🏁 20 days ago) Add opt-in option for Firefox browser extension telemetry ([~#13377~](https://github.com/sourcegraph/sourcegraph/issues/13377)) 
- [x] (🏁 10 days ago) Produce a source code zip of Firefox add-on to faciliate compliance review ([~#12918~](https://github.com/sourcegraph/sourcegraph/issues/12918); PRs: ~[#12099](https://github.com/sourcegraph/sourcegraph/pull/12099)~) 

@quinnkeast

- [ ] Adding a repository with improper credentials does not properly warn the user.  ([#13634](https://github.com/sourcegraph/sourcegraph/issues/13634)) 

@tjkandala: __15.00d__

- [ ] Some extensions need a dark mode variant ([#13666](https://github.com/sourcegraph/sourcegraph/issues/13666)) __1d__ 
- [ ] Implement UI changes on sign-in/sign-up form ([#13443](https://github.com/sourcegraph/sourcegraph/issues/13443)) __2d__ 
- [ ] Show error messages from third-party auth on sign-in page instead of on a plain text, white background plain HTML page ([#13442](https://github.com/sourcegraph/sourcegraph/issues/13442)) __2d__ 
- [ ] Remove sign out page ([#13440](https://github.com/sourcegraph/sourcegraph/issues/13440)) __0.5d__ 
- [ ] Create extensions for opening in additional editors - Atom, IntelliJ and Sublime Text ([#13270](https://github.com/sourcegraph/sourcegraph/issues/13270)) __0.5d__ 

Completed: __9.00d__
- [x] (🏁 20 days ago) Disable other extensions when sideloading (~[#13586](https://github.com/sourcegraph/sourcegraph/pull/13586)~) :shipit:
- [x] (🏁 16 days ago) Improve command palette (~[#13305](https://github.com/sourcegraph/sourcegraph/pull/13305)~) :shipit:
- [x] (🏁 16 days ago) Update toggle with new styling, add big toggle ([~#13272~](https://github.com/sourcegraph/sourcegraph/issues/13272)) __2.5d__ 
- [x] (🏁 14 days ago) Change language from "Sign in with $AUTH_PROVIDER" to "Continue with $AUTH_PROVIDER" ([~#13441~](https://github.com/sourcegraph/sourcegraph/issues/13441)) __0.5d__ 
- [x] (🏁 13 days ago) Improve the open-in-editor extension ([~#13474~](https://github.com/sourcegraph/sourcegraph/issues/13474)) 
- [x] (🏁 13 days ago) Last breadcrumb should not be a link on non-repo pages ([~#13651~](https://github.com/sourcegraph/sourcegraph/issues/13651)) __0.5d__ 
- [x] (🏁 today) Toggles on the extensions registry are higher on the z-axis than the command palette ([~#13781~](https://github.com/sourcegraph/sourcegraph/issues/13781)) __0.5d__ 🐛
- [x] (🏁 today) Add custom confirmation popup when enabling the extension ([~#13664~](https://github.com/sourcegraph/sourcegraph/issues/13664)) __1d__ 
- [x] (🏁 today) RFC 209: Extensions Discoverability ([~#13329~](https://github.com/sourcegraph/sourcegraph/issues/13329); PRs: ~[#12810](https://github.com/sourcegraph/sourcegraph/pull/12810)~, ~[#13699](https://github.com/sourcegraph/sourcegraph/pull/13699)~) __4d__ 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by tjkandala** [comment]
**Last week** I mostly worked to complete the changes proposed in RFC 209. I worked on the new toggle component, changes to the command palette, and updated styles for the extension registry. I also reviewed RFCs 213 and 221, and got started on some RFC 213 issues.

**Next week** I plan to implement the remaining RFC 209 changes once the toggle PR is merged. I also plan to help the team complete the sign in/out UX changes from RFC 213.

**Comment by marekweb** [comment]
**Last week** most of my coding work was on the browser extension and the refactor of feature flags, which is part of the work to update the Firefox add-on. That work went beyond my initial estimate but I also decided to include a bit more refactoring work that I initially planned. I also reviewed RFCs, and I had hiring interviews.

**This week** I'm wrapping up that add-on work and I'm moving on to the sign in/out UX tasks that are part of the milestone. I also intend to start investigating the Safari WebExtensions support.

**Comment by tjkandala** [comment]
**Last Week** I implemented the remaining changes from RFC 209 (extension registry), as well as further changes from Felix's review, and got approval from Felix in time for his vacation. I made further progress on RFC 213 (sign in/out) issues, but realized that I needed more context on auth, which I looked into. I also made small changes to extension code that I plan to merge this week. 

**This Week** I will merge the disparate RFC 209 branches before continuing work on the auth aspects of the sign in/out changes. I also plan to complete the open-in-editor extensions.

**Comment by tjkandala** [comment]
#### Last Week

I implemented some _new_ changes to the extension registry, made some changes to extensions, and worked on auth.

**Extension Registry**
- Implemented new animation for enabled extensions. Wrote React hook to abstract timeout management for this and future animations (#13749)
- Refactored `ExtensionToggle` to enable proper (non-blocking) modal when adding extensions, then implemented the modal.

**Extensions**

- Disable extension when sideloading (DX change)
- Add ability to specify dark-theme icon (#13703)

**Auth**

- Read auth + session-related code, then helped with the web portion of the explicit session invalidation PR.
- With the knowledge gained from working on the previously mentioned issue, finished an RFC213 issue and started working on others.

**This week**
I plan to wrap up work for this iteration by merging hanging PRs, then dedicating a few days to sign in/out UX issues.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment]
*Last week*

I debugged the request interception work-in-progress that will allow for extension testing, and which is being tracked in #12194. I started on the sign-in/sign-out UI changes. I started research on the potential development of the Safari extension. I made some changes to the browser extension build scripts, and also produced a new source code package for the FF add-on. I found an improved way to fetch the code-intel-extensions repository for bundling in Firefox.

**This week**

I'm focusing on the sign-in/sign-out UI work at the start of the week, and after branch cut I'll revisit the other priorities including the request interception for extension testing. Because of interest from the product team, I'll continue investigating the Safari extension.
