### ISSUE TITLE
Enterprise home: implementation tracking issue

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#13407]
See [RFC 224](https://docs.google.com/document/d/14VEsnxRKEkLmBvj_xy9r0enKL_Jr3GJjELh0qJA-vXg/edit?ts=5f458326#heading=h.trqab8y0kufp) and [Interaction Description Doc](https://docs.google.com/document/d/16LmD6IQ-lQUGf9mScX9JfGH11fsv_rE6PxdsdfAFpl8/edit#) for details

[Project Board](https://github.com/orgs/sourcegraph/projects/84)

## UI infrastructure
- [x] #13418 Create experimental feature flag for enterprise home panels
- [x] #13419 Create basic common lightweight panel component
- [x] #13486 Implement GraphQL query for filtering event log by event type

## Repositories panel
- [x] #13420 Implement Repositories panel functionality event log, with loading and empty state (no settings)

## Recent Searches panel
- [x] #13422 Implement Recent Searches panel functionality using the event log (including empty state and loading state, no settings)

## Recent Files panel
- [x] #13423 Implement Recent Files panel functionality using the event log (including empty state and loading state, no settings)

## Saved Searches panel
- [x] #13424 Implement Saved Searches panel functionality using the event log (including empty state and loading state, no settings), showing only my searches, and a button to add a saved search in the toolbar and the empty view
- [x] #13425 In Saved Searches panel, add query for all saved searches (using saved searches from all orgs the user belongs to) and add tabs in the toolbar to switch between user and all saved searches

## Polish
- [x] #13794 Update changelog
- [x] #13797  Stabilize visual tests due to timestamps

## Postponed future work - Modify Repositories panel to show repos recently modified by user
- [ ] #13236 Create server-side code to search repos by author using GraphQL 
- [ ] Replace Repositories data backend from event log to search of repos by author
- [ ] Implement settings button and state for lightweight panels
- [ ] Implement settings for Repositories panel with customizable git authors

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by lguychard** [comment]
@limitedmage given all that's remaining is "postponed future work", should this be backlogged?

**Comment by limitedmage** [comment]
@lguychard I'll close this and we can come back to considering the postponed future work once we collect feedback and decide how to proceed with this new experience.
