### ISSUE TITLE
RFC 227: Code monitoring

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#13413]
Tracking issue for [RFC 227: Code monitoring](https://docs.google.com/document/d/1_R5DgpUkxyZilsJ9vBQm5cvRPT2udc3tZIPg2q3cnZU/edit#), in response to [PD 12](https://docs.google.com/document/d/1D9Useap2CuPJmed7Htdoho4nyzM0MMT0LJL_MlhoMv4/edit#).

@quinnkeast

- [ ] Add link to user research signup to saved search notification emails ([#13673](https://github.com/sourcegraph/sourcegraph/issues/13673))

**Version 1**

- Private code monitors
    - Emails 
    - Web Hooks (focus: Test with Zapier, Slack)
With private code monitors individuals can create code monitors for themselves (no sharing or organization level code monitors). Version 1 improves the existing functionality ([saved searches with notifications](https://docs.sourcegraph.com/code_search/explanations/features#saved-searches)) significantly where the user experience is poor and the value of monitoring isn’t communicated in the product clearly. 

- [ ] Allow users to test the new email and webhook code monitor they've set up
- [ ] Throw error message if SMTP email support isn't enabled for a customer instance
- [ ] Documentation
    - Link from `Learn more` to core concepts 
    - When notifications are sent (frequency)
         - Query performance related time delays
    - Mention performance constraints that can improve ux like encouraging scoping to repos, etc.
    - Getting Started Examples
    - Link from `confidential information` to related issues
    - Webhook data format information (Simple, Zapier, Slack)

**Future Iterations**
- Event Log
    - See a code monitor's event history on sourcegraph (both successes and failures, particularly useful for webhooks)

- Starting points for code monitors
    - In future iterations, these can be a part of the actual creation flow and include additional starting points.
- More search result content in notification messages 
    - This will make notifications more valuable for users. There’s a few considerations to keep in mind.
        - For security and compliance use cases, it isn’t safe to include some content in plain text emails
        - Repository viewing permissions: Currently emails are sent via SMTP support on customers instances. 
            - We don’t and I believe we can’t check for repo viewing permissions easily because this happens on the customer instance. 
           - To solve this, perhaps it means supporting email sending on our systems?
            - Campaigns team is dealing with issues where we don’t always have user supplied auth tokens to check their repo permissions
              - Web Hooks notifications are shared into channels consumers by multiple users. This can be a security concern.

- Scale
    - Performance needs to be monitored to understand if this can break for customers with larger codebases.
    - We currently don't have 50 repository limit for code monitoring notifications (like commit and diff search). This is because notifications are sent very frequently, helping us avoid running into performance concerns that come up with batching a huge number of notifications together. 

- Organization
    - Notify multiple recipients for users in our system. How would individuals unsubscribe in this case? 
    - Alternatively notify the entire organizations.
