### ISSUE TITLE
Product team 3.20 Tracking issue

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#13698]
### Plan

List of work in progress:

- [Goals for search team](https://github.com/sourcegraph/about/pull/1462)
- [Wrap up roadmap PR](https://github.com/sourcegraph/about/pull/1164)
- Code monitoring
- Browser extension discoverability
- Campaigns UI support

### Availability

- Christina out 1 week vacation Aug 17-21, Labor Day

### Tracked issues

@kghopson

Completed
- [x] (🏁 772 days ago) https://github.com/sourcegraph/sourcegraph/issues/12945    🏳️ [3.20](https://github.com/sourcegraph/sourcegraph/milestone/45)
- [x] (🏁 751 days ago) https://github.com/sourcegraph/sourcegraph/issues/3298  [👩](https://app.hubspot.com/contacts/2762526/company/407948923)🐛   🏳️ [3.20](https://github.com/sourcegraph/sourcegraph/milestone/45)
- [x] (🏁 739 days ago) https://github.com/sourcegraph/sourcegraph/issues/4828    🏳️ [3.20](https://github.com/sourcegraph/sourcegraph/milestone/45)

@lorihey

Completed
- [x] (🏁 739 days ago) https://github.com/sourcegraph/sourcegraph/issues/4828    🏳️ [3.20](https://github.com/sourcegraph/sourcegraph/milestone/45)

@rrhyne: __1.00d__

Completed: __1.00d__
- [x] (🏁 713 days ago) ~https://github.com/sourcegraph/sourcegraph/issues/13117~  __1.00d__   🏳️ [Campaigns Sprint 2](https://github.com/sourcegraph/sourcegraph/milestone/49)

**Comment by AlicjaSuska** [comment]
**Last week** 
- #11777 (Browser extension discoverability issue) - I finished summarising usability test results and started building the design solutions. Re-running the usability tests the previous week caused a delay. I was supposed to be done with the solutions by the end of this week. Now, I'm planning to submit them for review early next week.
- #11872 (Extensions discoverability) - mostly focused on QA and correcting small elements, when necessary.
- Design system - I've restructured our Figma files so they mimic the Storybook structure, moved some components around.

**Next week**
- #11777 (Browser extension discoverability issue) - I'm planning to share the solutions, gather feedback and prepare issues for implementation in 3.21
- #11872 (Extensions discoverability) - continue with the QA
- Design system - add components necessary for the browser extension project, clean up the colors.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rrhyne** [comment]
**Last week**
* I had about a day worth of interviews and feedback
* Created and presented Figma for Sourcegraphers
* Looked into header and content alignment and wrote an RFC to address and breadcrumbs feedback

**This week**
* Sat in on the campaigns meeting with Indeed
* Created a component proposal for code display
* One full day of interviews and meetings
* I ran and processed unmoderated tests on usertesting.com for search tour
* Did QA on server home and put together video demo and prototype to solicit feedback

**Comment by AlicjaSuska** [comment]
**Last week**

- #11777 (Browser extension discoverability issue) - I finished designing the v.1 of solutions. Now, I'm gathering feedback from the team.
- #11872 (Extensions discoverability) - QA
- Published RFC 220 tackling the alerts inconsistencies

**Next week** 
- #11777 (Browser extension discoverability issue) - gather feedback, make the corrections and prepare the issues
- #11872 (Extensions discoverability) - action items bar ideas exploration
- Design system - add components necessary for the browser extension project, clean up the colors.
- Headers, breadcrums and branding work

**Comment by macraig** [comment]
**Last week**

- Worked on aggregating feedback for powering precise search using precise code intel data
- Worked on aggregating feedback for Sourcegraph discussions
- Took over NPS feedback
- Worked on aggregating information to identify code intel challenges and priorities for the next milestone
- Spent time meeting members from other teams


**Next week**

- Plan the next milestone with the code intel team
- Add milestone goals to new version of the roadmap
- Continue aggregating information to identify problem statements
- Follow up on code intel survey status
- Provide NPS feedback to users
- Spend time meeting members from other teams
