### ISSUE TITLE
authz: remove read/write path of binary format permissions

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#13740]
Follow up of #11457

### TODO

- [x] Remove read path of binary format
- [x] Remove `MigrateBinaryToIntarray` from #13706 

### Next steps

- [ ] Rename binary format column to `*_ids_bin`.
- [ ] Create an issue to transit to remove `_ints` suffix of columns.

**Comment by tsenart** [comment]
@unknwon: Also moved this to Backlog instead of current cycle.
