### ISSUE TITLE
Campaigns Sprint 1 Tracking issue

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#13828]
### Plan

Note: We have moved to 2-week sprints! This one is our first.

The main theme of this cycle is quality of life improvements for our users. Campaigns could be a lot easier to use! Many of these improvements will be around debugging a campaign, to shorten the cycle of “tweak the spec, apply the spec, see what went wrong, repeat”.

We also have several tickets that continue the theme of the previous cycle: bug fixing and polishing.

User feedback (from customers and internal folks) is driving our focus. We are also finishing up a round of formal user testing to further validate that we are focusing on the most urgent needs.

### Availability

Period is from Sep 21 to Oct 6, for 12 working day in total before branch cut.

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

@chrispine 3d (Sep 23-25)
@mrnugget 1d (Sep 25)
@eseliger 0d

### Tracked issues

@LawnGnome: __2.50d__

Completed: __2.50d__
- [x] (🏁 18 days ago) Add backlink to PR description again ([~#13459~](https://github.com/sourcegraph/sourcegraph/issues/13459)) __0.50d__
- [x] (🏁 18 days ago) Decorating changeset body fails with "Namespace not found" ([~#14159~](https://github.com/sourcegraph/sourcegraph/issues/14159))
- [x] (🏁 11 days ago) Allow users to publish only a subset of changesets ([~#13139~](https://github.com/sourcegraph/sourcegraph/issues/13139)) __2.00d__
- [x] (🏁 11 days ago) doc: fix published array ordering ([~#14354~](https://github.com/sourcegraph/sourcegraph/pull/14354)) :shipit:

@chrispine: __0.50d__

Completed: __0.50d__
- [x] (🏁 21 days ago) Remove old code in 3.21 release ([~#13018~](https://github.com/sourcegraph/sourcegraph/issues/13018)) __0.50d__ 🧶

@eseliger: __5.00d__

Completed: __5.00d__
- [x] (🏁 18 days ago) campaigns: cancelled GitLab pipelines don't take check state out of pending ([~#12667~](https://github.com/sourcegraph/sourcegraph/issues/12667); PRs: ~[#14129](https://github.com/sourcegraph/sourcegraph/pull/14129)~) __1.00d__ 🐛
- [x] (🏁 13 days ago) Refactor internal campaigns package ([~#13174~](https://github.com/sourcegraph/sourcegraph/issues/13174); PRs: ~[#14188](https://github.com/sourcegraph/sourcegraph/pull/14188)~) __2.00d__ 🧶
- [x] (🏁 13 days ago) Merge changesets.CreatedByCampaign and changesets.OwnedByCampaign fields ([~#12650~](https://github.com/sourcegraph/sourcegraph/issues/12650); PRs: ~[#14157](https://github.com/sourcegraph/sourcegraph/pull/14157)~) __1.00d__
- [x] (🏁 today) Expose author details on changeset spec description in GQL ([~#13645~](https://github.com/sourcegraph/sourcegraph/issues/13645); PRs: ~[#14181](https://github.com/sourcegraph/sourcegraph/pull/14181)~) __1.00d__

@mrnugget: __5.00d__

Completed: __5.00d__
- [x] (🏁 24 days ago) Documentation for configuring campaigns (scope for tokens) ([~#12888~](https://github.com/sourcegraph/sourcegraph/issues/12888); PRs: ~[#13948](https://github.com/sourcegraph/sourcegraph/pull/13948)~) __0.50d__
- [x] (🏁 14 days ago) Fix nil-pointer panic in go-diff  ([~#13976~](https://github.com/sourcegraph/sourcegraph/issues/13976)) 🐛
- [x] (🏁 13 days ago) Changesets are not re-opened and re-attached to a campaign if new apply adds them again ([~#13849~](https://github.com/sourcegraph/sourcegraph/issues/13849)) __2.50d__ 🐛
- [x] (🏁 13 days ago) Split up ChangesetCountsOverTime integration test ([~#12835~](https://github.com/sourcegraph/sourcegraph/issues/12835)) __1.00d__ 🧶
- [x] (🏁 11 days ago) Create integration test for src-cli ([~#13863~](https://github.com/sourcegraph/sourcegraph/issues/13863)) __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by mrnugget** [comment]
### Weekly update

Last week I focused on recording a new demo video for campaigns, which is [now live](https://sourcegraph.com/campaigns), and thus spent a lot of time running and re-running campaigns, which resulted not only in a few small bug fixes, but also one of my main goals for this sprint: improve the feedback loop and debugging experience when building campaigns with src-cli.

That's what I want to focus on this week, too: improve the error reporting in src-cli, make the feedback loop tighter, increase performance, add tests, etc.

My other goals for this sprint includes fixing [a nasty bug](https://github.com/sourcegraph/sourcegraph/issues/13849) in our reconciler/`applyCampaign` logic. I might do that once I reach my "eureka!"-moment with it. Oh, and I also found [a tasty bug in `go-diff`](https://github.com/sourcegraph/go-diff/issues/54) that I'm also marinating in the back of my head.

**Comment by eseliger** [comment]
### Weekly update

Last week I was out for vacation.

This week, I spent today on catching-up on mails, threads and discussions. Tomorrow, I will look deeper into the work to be done this iteration (or do we say sprint now?). Since my largest ticket, responsiveness, is dependent on design work, I'll be starting off with my other tickets first.

**Comment by LawnGnome** [comment]
#### Weekly update: 2020-09-14 to 2020-09-18

Last week was a bit of a struggle. I worked on implementing the changeset subset behaviour that we've been working on through the RFC process, and generally cleaning up RFCs, but got a bit less done than I'd hoped. I also pushed a few minor documentation updates for 3.20. In general, though, I was glad to have Friday off and reset.

This week, I'm going to be getting the subset behaviour landed come hell or high water (hopefully neither _actually_ happen), trying to figure out the worker util issue I've been intermittently banging my head against for a while, and, most importantly, ensuring that campaign-created changesets have a link back to the campaign.

**Comment by mrnugget** [comment]
### Weekly update

Last week I fixed multiple small things in src-cli and improved the error reporting. I also managed to fix the nasty bug that pops up when detaching/attaching changesets in `applyCampaign`, see https://github.com/sourcegraph/sourcegraph/pull/14099 for details, including a video walkthrough of the bugfix and how cool it demos the declarative model.

My goal for this week is to make progress on multiple smaller tickets, such as adding a src-cli integration test, splitting up a test in `sourcegraph/sourcegraph`, and fixing a bug in go-diff. Besides that I still want to make some progress improving error/debugging in src-cli.

**Comment by eseliger** [comment]
#### Weekly update: 2020-09-21 to 2020-09-25

Last week I first played catch-up from vacation the week before, then went onto tackling the non-design-related issues. Opened PRs for those, need to fix up some minor things and then they should be good to go.

This week, I'm planning to make all about responsiveness of the campaigns pages. The designs are ready for review and I'll be taking time today or tomorrow with design to go over it. Afterwards, fun implementation work. That should tick off most of my work items for this sprint, so currently seems to go according to plan.

**Comment by LawnGnome** [comment]
#### Weekly update: 2020-09-21 to 2020-09-25

Last week, I worked on a couple of key items in my sprint plan: [adding backlinks back into campaign created changesets](https://github.com/sourcegraph/sourcegraph/issues/13459) (which was a fun expansion pack project that came in way over its original time estimate, since I [ended up cleaning up `internal/db/namespaces.go` fairly significantly](https://github.com/sourcegraph/sourcegraph/pull/14033/files#diff-9f58b5c0218114a033675d33f94dc65b) as part of adding the functionality I needed specifically for this task), and updating [RFC 228](https://docs.google.com/document/d/1A-5cbYGz1p1UB1eAFsIgpK5XDkvS7ZNAVKMdtBm_WY0/edit?usp=sharing) to reflect what I really, _really_ hope is the final version of changeset template specialisation, along with its [associated](https://github.com/sourcegraph/sourcegraph/pull/13476) [PRs](https://github.com/sourcegraph/src-cli/pull/294) (which I think are more or less review ready, assuming we approve that RFC).

I also had a crack at [GitLab integration tests](https://github.com/sourcegraph/sourcegraph/issues/12219), but had trouble with `vcr`, which isn't designed to integrate with how we use HTTP clients in the GitLab package. More thought required here, but I wasn't happy with the approach I was looking at, so I want to come back to this afresh at a later date.

This week, I want to get RFC 228 really, truly, done, but expect to spend most of my time working on [support for using user tokens when interacting with code hosts](https://github.com/sourcegraph/sourcegraph/issues/13862). Around that, in my copious amounts of spare time, I may have another go at the GitLab integration tests, but I'll likely prioritise [validating the reconciler logic](https://github.com/sourcegraph/sourcegraph/issues/13648) above that as and when I have cycles.

**Comment by mrnugget** [comment]
### Weekly Update

Last week I reached the goals I set for myself that week: wrote an integration test for `src-cli`, split up a test in `sourcegraph/sourcegraph`, fixed the bug in `go-diff` and added some more tests to `go-diff`. The rest of my time I spent in `src-cli`, trying to make it easier to debug.

The first result of that was unintended but, at least in my opinion, a possibly great way to add more power to campaigns on the src-cli: add [templating support for campaign specs](https://github.com/sourcegraph/src-cli/pull/334) to allow `run` steps to access only the files yielded by search results and/or the files modified by a previous step. The design is not final and implementation wise it's still a prototype, but I'm looking for feedback on it and I want to spend more time on it this week.

The other result of my digging in `src-cli` was [support for "status bars" next to a progress bar.](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1601649315115400) Again, I think this is really handy and improves the feedback loop _a lot_, since you can see what's currently being executed in which repository. I also want to clean this up further this week.

Then we also have planning this week, which means I anticipate some backlog grooming or thinking about what we want to do.
