### ISSUE TITLE
Alan Harris On-boarding plan

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#13856]
### Week 1

Go through [General Onboarding](https://about.sourcegraph.com/handbook/people-ops/onboarding#for-all-new-teammates) and [Engineering Onboarding](https://about.sourcegraph.com/handbook/engineering/onboarding#engineering-onboarding).

- [x] Schedule an architecture deep dive session with @keegancsmith.

### Week 2 - 3

Get started with some smaller tasks that should help your learn a lot of our moving pieces.

- [x] Repository Settings > Mirroring should not display token in the UI #13852
- [x] Can't list branches of torvalds/linux repo on Github #5453
- [x] Show last ping data to admins on the Site-admin > Pings page #13956
- [x] Support efficient repository listing pagination in the GraphQL API #13715

### Week 4 - x

- [ ] Global abuse protection of all public endpoints #10629

**Comment by unknwon** [comment]
I often hear feedback from new teammates (at least three, during donut chats) that they're overwhelmed by how many things they need to do in the first week. 

Is it possible to control the pace in "Week 1 - 3" with a slow start (if possible)? For example, on week 1, only do X; on week 2, only Y and on week 3, only do Z?

**Comment by tsenart** [comment]
Good feedback @unknwon. What do you think of the changes I made?

**Comment by unknwon** [comment]
> Good feedback @unknwon. What do you think of the changes I made?

👍 That's better, LGTM.

**Comment by ryanslade** [comment]
This all LGTM 👍
