### ISSUE TITLE
RFC 235 Tracking issue: Move LSIF data to Postgres

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#13882]
Tracking issue for [RFC 235: Move LSIF data to Postgres](https://docs.google.com/document/d/1Y9p29hK8xrPUTvBdWqP9uAHDg3JLV-HCaxsbCo9-YHQ).

### Tracked issues

@efritz: __5.50d__

- [ ] Write announcement post for Postgres change ([#14009](https://github.com/sourcegraph/sourcegraph/issues/14009))

Completed: __5.50d__
- [x] (🏁 133 days ago) chore: Co-locate dev scripts to interact with postgres ([~#13942~](https://github.com/sourcegraph/sourcegraph/pull/13942)) :shipit:
- [x] (🏁 133 days ago) RFC 235: Add code intel postgres image ([~#13912~](https://github.com/sourcegraph/sourcegraph/issues/13912); PRs: ~[#13913](https://github.com/sourcegraph/sourcegraph/pull/13913)~) __0.50d__
- [x] (🏁 133 days ago) chore: Set exec bit on docker-images/codeintel-db/build.sh ([~#13955~](https://github.com/sourcegraph/sourcegraph/pull/13955)) :shipit:
- [x] (🏁 126 days ago) codeintel: RFC 235: Soft delete upload records ([~#13822~](https://github.com/sourcegraph/sourcegraph/pull/13822)) :shipit:
- [x] (🏁 119 days ago) RFC 235: Add migration infrastructure to codeintel database ([~#13885~](https://github.com/sourcegraph/sourcegraph/issues/13885); PRs: ~[#13903](https://github.com/sourcegraph/sourcegraph/pull/13903)~, ~[#13943](https://github.com/sourcegraph/sourcegraph/pull/13943)~) __1.00d__
- [x] (🏁 119 days ago) fix: Ensure frontend connects to frontend database ([~#14379~](https://github.com/sourcegraph/sourcegraph/pull/14379)) :shipit:
- [x] (🏁 118 days ago) RFC 235: Add code intel postgres container ([~#13883~](https://github.com/sourcegraph/sourcegraph/issues/13883); PRs: ~[#13864](https://github.com/sourcegraph/sourcegraph/pull/13864)~, ~[#13904](https://github.com/sourcegraph/sourcegraph/pull/13904)~, ~[#13924](https://github.com/sourcegraph/sourcegraph/pull/13924)~) __1.00d__
- [x] (🏁 118 days ago) RFC 235: Configure connection to codeintel database ([~#13884~](https://github.com/sourcegraph/sourcegraph/issues/13884); PRs: ~[#13864](https://github.com/sourcegraph/sourcegraph/pull/13864)~, ~[#13952](https://github.com/sourcegraph/sourcegraph/pull/13952)~) __0.50d__
- [x] (🏁 114 days ago) RFC 235: Update bundle manager to read from Postgres ([~#13886~](https://github.com/sourcegraph/sourcegraph/issues/13886); PRs: ~[#13923](https://github.com/sourcegraph/sourcegraph/pull/13923)~, ~[#13924](https://github.com/sourcegraph/sourcegraph/pull/13924)~) __0.50d__
- [x] (🏁 114 days ago) RFC 235: Update bundle manager janitor ([~#13887~](https://github.com/sourcegraph/sourcegraph/issues/13887); PRs: ~[#13923](https://github.com/sourcegraph/sourcegraph/pull/13923)~, ~[#14468](https://github.com/sourcegraph/sourcegraph/pull/14468)~)
- [x] (🏁 114 days ago) codeintel: Run migrations on startup for codeintel database ([~#14484~](https://github.com/sourcegraph/sourcegraph/pull/14484)) :shipit:
- [x] (🏁 114 days ago) RFC 235: Update worker to write to Postgres ([~#13889~](https://github.com/sourcegraph/sourcegraph/issues/13889); PRs: ~[#13923](https://github.com/sourcegraph/sourcegraph/pull/13923)~, ~[#13946](https://github.com/sourcegraph/sourcegraph/pull/13946)~) __0.50d__
- [x] (🏁 114 days ago) RFC 235: Migrate SQLite data to Postgres ([~#13888~](https://github.com/sourcegraph/sourcegraph/issues/13888); PRs: ~[#13923](https://github.com/sourcegraph/sourcegraph/pull/13923)~, ~[#13932](https://github.com/sourcegraph/sourcegraph/pull/13932)~) __0.50d__
- [x] (🏁 114 days ago) codeintel: Do not block bundle manager startup with migrations ([~#14493~](https://github.com/sourcegraph/sourcegraph/pull/14493)) :shipit:
- [x] (🏁 113 days ago) codeintel: Lower number of goroutines during SQLite -> Postgres migration ([~#14520~](https://github.com/sourcegraph/sourcegraph/pull/14520)) :shipit:
- [x] (🏁 113 days ago) codeintel: De-multiply writes during SQLite -> Postgres migration ([~#14536~](https://github.com/sourcegraph/sourcegraph/pull/14536)) :shipit:
- [x] (🏁 113 days ago) codeintel: Clean up bundle files after SQLite -> Postgres migration ([~#14537~](https://github.com/sourcegraph/sourcegraph/pull/14537)) :shipit:
- [x] (🏁 112 days ago) codeintel: Add indexes to codeintel database tables ([~#14538~](https://github.com/sourcegraph/sourcegraph/pull/14538)) :shipit:
- [x] (🏁 108 days ago) RFC 235: Do not mush data together in the server deployment ([~#14464~](https://github.com/sourcegraph/sourcegraph/issues/14464); PRs: ~[#14487](https://github.com/sourcegraph/sourcegraph/pull/14487)~)
- [x] (🏁 108 days ago) RFC 235: Update architecture diagram ([~#14605~](https://github.com/sourcegraph/sourcegraph/issues/14605))
- [x] (🏁 108 days ago) RFC 235: Update janitor ([~#14566~](https://github.com/sourcegraph/sourcegraph/issues/14566); PRs: ~[#14641](https://github.com/sourcegraph/sourcegraph/pull/14641)~)
- [x] (🏁 108 days ago) RFC 235: Document minimum time required to be spent in 3.21 ([~#14604~](https://github.com/sourcegraph/sourcegraph/issues/14604); PRs: ~[#14635](https://github.com/sourcegraph/sourcegraph/pull/14635)~)
- [x] (🏁 108 days ago) RFC 235: Find equivalent of the now useless "freeSpace" operation in the janitor ([~#14569~](https://github.com/sourcegraph/sourcegraph/issues/14569); PRs: ~[#14641](https://github.com/sourcegraph/sourcegraph/pull/14641)~)
- [x] (🏁 107 days ago) codeintel: Remove bundle manager hop from query path ([~#14507~](https://github.com/sourcegraph/sourcegraph/pull/14507)) :shipit:
- [x] (🏁 107 days ago) RFC 235: Update metrics ([~#14568~](https://github.com/sourcegraph/sourcegraph/issues/14568))
- [x] (🏁 14 days ago) RFC 235: Cleanup ([~#13890~](https://github.com/sourcegraph/sourcegraph/issues/13890)) __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
