### ISSUE TITLE
RFC 201: Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#13891]
Tracking issue for [RFC 201: Auto-indexer build configuration](https://docs.google.com/document/d/1NPQs1s814LZjNXjPuavqC1N7hZR192DNtmSBmAeH9UY).

### Tracked issues

@efritz: __1.50d__

Completed: __1.50d__
- [x] (🏁 56 days ago) codeintel: Refactor command runner in indexer ([~#14102~](https://github.com/sourcegraph/sourcegraph/pull/14102)) :shipit:
- [x] (🏁 56 days ago) codeintel: Lower indexer output to debug level ([~#14103~](https://github.com/sourcegraph/sourcegraph/pull/14103)) :shipit:
- [x] (🏁 56 days ago) codeintel: Refactor index command construction ([~#14105~](https://github.com/sourcegraph/sourcegraph/pull/14105)) :shipit:
- [x] (🏁 56 days ago) codeintel: Move away from hardcoding image names ([~#14114~](https://github.com/sourcegraph/sourcegraph/pull/14114)) :shipit:
- [x] (🏁 56 days ago) codeintel: Refactor construction of copyfiles flags ([~#14116~](https://github.com/sourcegraph/sourcegraph/pull/14116)) :shipit:
- [x] (🏁 56 days ago) codeintel: Add orderedKeys to indexer ([~#14117~](https://github.com/sourcegraph/sourcegraph/pull/14117)) :shipit:
- [x] (🏁 48 days ago) codeintel: Make docker/firecracker abstraction in indexer ([~#14121~](https://github.com/sourcegraph/sourcegraph/pull/14121)) :shipit:
- [x] (🏁 48 days ago) RFC 201: Write a JSONC index configuration format parser ([~#13892~](https://github.com/sourcegraph/sourcegraph/issues/13892); PRs: ~[#14356](https://github.com/sourcegraph/sourcegraph/pull/14356)~)
- [x] (🏁 47 days ago) migration: Update default indexer/indexer_args in lsif_indexes table ([~#14360~](https://github.com/sourcegraph/sourcegraph/pull/14360)) :shipit:
- [x] (🏁 47 days ago) codeintel: Update default indexer args in index scheduler ([~#14378~](https://github.com/sourcegraph/sourcegraph/pull/14378)) :shipit:
- [x] (🏁 47 days ago) RFC 201: Update auto indexer execution ([~#13894~](https://github.com/sourcegraph/sourcegraph/issues/13894); PRs: ~[#14359](https://github.com/sourcegraph/sourcegraph/pull/14359)~)
- [x] (🏁 47 days ago) migration: Fix bad default in indexer records ([~#14380~](https://github.com/sourcegraph/sourcegraph/pull/14380)) :shipit:
- [x] (🏁 47 days ago) codeintel: Fix bad default lsif-go arguments ([~#14386~](https://github.com/sourcegraph/sourcegraph/pull/14386)) :shipit:
- [x] (🏁 44 days ago) RFC 201: Update index scheduler to publish new payload ([~#13895~](https://github.com/sourcegraph/sourcegraph/issues/13895))
- [x] (🏁 44 days ago) codeintel: Remove temporary files from firecracker VMs on startup ([~#14411~](https://github.com/sourcegraph/sourcegraph/pull/14411)) :shipit:
- [x] (🏁 44 days ago) RFC 201: Add disk size to VM ([~#14390~](https://github.com/sourcegraph/sourcegraph/issues/14390); PRs: ~[#14412](https://github.com/sourcegraph/sourcegraph/pull/14412)~)
- [x] (🏁 44 days ago) RFC 201: Create index record based on database configuration ([~#14409~](https://github.com/sourcegraph/sourcegraph/issues/14409); PRs: ~[#14415](https://github.com/sourcegraph/sourcegraph/pull/14415)~)
- [x] (🏁 43 days ago) RFC 201: Create index record based on configuration file ([~#13896~](https://github.com/sourcegraph/sourcegraph/issues/13896); PRs: ~[#14416](https://github.com/sourcegraph/sourcegraph/pull/14416)~)
- [x] (🏁 43 days ago) RFC 201: Detect configuration from repo contents ([~#13897~](https://github.com/sourcegraph/sourcegraph/issues/13897); PRs: ~[#14418](https://github.com/sourcegraph/sourcegraph/pull/14418)~)
- [x] (🏁 43 days ago) codeintel: Add go mod download step to go index jobs ([~#14452~](https://github.com/sourcegraph/sourcegraph/pull/14452)) :shipit:
- [x] (🏁 40 days ago) codeintel: Store index job commands and output in the database ([~#14457~](https://github.com/sourcegraph/sourcegraph/pull/14457)) :shipit:
- [x] (🏁 9 days ago) RFC 201: Update metrics ([~#14567~](https://github.com/sourcegraph/sourcegraph/issues/14567); PRs: ~[#15545](https://github.com/sourcegraph/sourcegraph/pull/15545)~) __1.00d__
- [x] (🏁 today) RFC 201: Write architecture docs for precise code intel indexer ([~#14010~](https://github.com/sourcegraph/sourcegraph/issues/14010); PRs: ~[#15818](https://github.com/sourcegraph/sourcegraph/pull/15818)~) __0.50d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
