### ISSUE TITLE
Remove the `-tooling` cluster from the production project

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#13917]
The tooling k8s cluster is currently in the production project, we should move this cluster to a separate project.

We could reuse and existing cluster or create a new cluster and project for this.

#### Tasks
- [x] Discover connecting resources
- [x] Backups resources
- [x] Decide if share a k8s cluster ~~or utilize a new one~~
- [x] Migrate resources
- [x] Document these services
  - [x] https://about.sourcegraph.com/handbook/engineering/distribution/github_enterprise_testing_instance
- [x] Delete old resources

**Comment by pecigonzalo** [comment]
Tooling resources are used by the `dogfood` deployments as repository sources.

**Comment by pecigonzalo** [comment]
Volume claims:
```
{
  "accessModes": [
    "ReadWriteOnce"
  ],
  "capacity": {
    "storage": "1Gi"
  },
  "claimRef": {
    "apiVersion": "v1",
    "kind": "PersistentVolumeClaim",
    "name": "bitbucket-caddy",
    "namespace": "default",
    "resourceVersion": "135404162",
    "uid": "4b3fae88-5fb3-11ea-a199-42010a80003e"
  },
  "gcePersistentDisk": {
    "fsType": "ext4",
    "pdName": "gke-tooling-a9d52317-d-pvc-4b3fae88-5fb3-11ea-a199-42010a80003e"
  },
  "nodeAffinity": {
    "required": {
      "nodeSelectorTerms": [
        {
          "matchExpressions": [
            {
              "key": "failure-domain.beta.kubernetes.io/zone",
              "operator": "In",
              "values": [
                "us-central1-a"
              ]
            },
            {
              "key": "failure-domain.beta.kubernetes.io/region",
              "operator": "In",
              "values": [
                "us-central1"
              ]
            }
          ]
        }
      ]
    }
  },
  "persistentVolumeReclaimPolicy": "Delete",
  "storageClassName": "standard",
  "volumeMode": "Filesystem"
}
{
  "accessModes": [
    "ReadWriteOnce"
  ],
  "capacity": {
    "storage": "100Gi"
  },
  "claimRef": {
    "apiVersion": "v1",
    "kind": "PersistentVolumeClaim",
    "name": "bitbucket-home",
    "namespace": "default",
    "resourceVersion": "46257593",
    "uid": "56a0cb0a-921a-11e9-ac9b-42010a8000a9"
  },
  "gcePersistentDisk": {
    "fsType": "ext4",
    "pdName": "gke-tooling-a9d52317-d-pvc-56a0cb0a-921a-11e9-ac9b-42010a8000a9"
  },
  "persistentVolumeReclaimPolicy": "Delete",
  "storageClassName": "standard",
  "volumeMode": "Filesystem"
}
{
  "accessModes": [
    "ReadWriteOnce"
  ],
  "capacity": {
    "storage": "4000Gi"
  },
  "claimRef": {
    "apiVersion": "v1",
    "kind": "PersistentVolumeClaim",
    "name": "gitolite-repos",
    "namespace": "default",
    "resourceVersion": "2110256",
    "uid": "752ae39c-ffce-11e8-b3fc-42010a8001c8"
  },
  "gcePersistentDisk": {
    "fsType": "ext4",
    "pdName": "gke-tooling-a9d52317-d-pvc-752ae39c-ffce-11e8-b3fc-42010a8001c8"
  },
  "persistentVolumeReclaimPolicy": "Delete",
  "storageClassName": "standard",
  "volumeMode": "Filesystem"
}
{
  "accessModes": [
    "ReadWriteOnce"
  ],
  "capacity": {
    "storage": "20Gi"
  },
  "claimRef": {
    "apiVersion": "v1",
    "kind": "PersistentVolumeClaim",
    "name": "gitolite-ssh",
    "namespace": "default",
    "resourceVersion": "2110259",
    "uid": "7543fb9e-ffce-11e8-b3fc-42010a8001c8"
  },
  "gcePersistentDisk": {
    "fsType": "ext4",
    "pdName": "gke-tooling-a9d52317-d-pvc-7543fb9e-ffce-11e8-b3fc-42010a8001c8"
  },
  "persistentVolumeReclaimPolicy": "Delete",
  "storageClassName": "standard",
  "volumeMode": "Filesystem"
}
{
  "accessModes": [
    "ReadWriteOnce"
  ],
  "capacity": {
    "storage": "20Gi"
  },
  "claimRef": {
    "apiVersion": "v1",
    "kind": "PersistentVolumeClaim",
    "name": "mysql",
    "namespace": "default",
    "resourceVersion": "2099738",
    "uid": "870536ee-ffc4-11e8-b3fc-42010a8001c8"
  },
  "gcePersistentDisk": {
    "fsType": "ext4",
    "pdName": "gke-tooling-a9d52317-d-pvc-870536ee-ffc4-11e8-b3fc-42010a8001c8"
  },
  "persistentVolumeReclaimPolicy": "Delete",
  "storageClassName": "standard",
  "volumeMode": "Filesystem"
}
```

**Comment by pecigonzalo** [comment]
Creating disks with

```
gcloud compute disks create gke-dogfood-pvc-${NAME} --source-disk=https://www.googleapis.com/compute/v1/projects/sourcegraph-dev/zones/us-central1-a/disks/${PVC_NAME} --project=sourcegraph-dogfood --zone=us-central1-a --type pd-standard
```

**Comment by pecigonzalo** [comment]
Moved disks to the cluster zone with
```
gcloud compute disks move ${NAME} --async --zone=us-central1-a --destination-zone=us-central1-f --pro
ject=sourcegraph-dogfood
```

**Comment by pecigonzalo** [comment]
Created a `sourcegraph-github-enterprise` project for GHE.

**Comment by pecigonzalo** [comment]
When I copied the GHE disks using `gcloud compute disks create`, I was unable to attach a snapshot policy or change other parameters until I restored the disk from snapshot.
This process was automatically done for the other disks, but I had to do it manually here.

#### TODO
- [ ] Document playbook about moving disks between regions/projects
- [ ] Document playbook on restoring disks to PV/PVC

**Comment by pecigonzalo** [comment]
Exported DB using
```
gcloud --project=sourcegraph-dev sql export sql bitbucket-server 'gs://gp-export-bitbucket/Cloud_SQL_Export_2020-10-01 (13:02:11)' --database=bitbucket
```

Imported DB using
```
gcloud --project=sourcegraph-dogfood sql import sql bitbucket-8e76f102f9 'gs://gp-export-bitbucket/Cloud_SQL_Export_2020-10-01 (13:02:11)' --database=bitbucket
```

#### TODO
- [ ] Delete gp-export-bitbucket from `sourcegraph-dev`

**Comment by pecigonzalo** [comment]
I had to add the `dogfood` compute service account to the GCR bucket with read access, the account for GKE nodes is PROJECT_NUMBER-compute@developer.gserviceaccount.com.

#### TODO
- [ ] Add GCR bucket to Terraform
- [ ] Add GCR to Terraform
- [ ] Add service accounts and permissions to Terraform
