### ISSUE TITLE
Delete the big data clusters

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#13918]
The big data clusters are quite expensive and currently share space with our production clusters.
We want to separate these clusters to the shared dev project or a specific project for them.

There are 2 clusters:
- bigdata
- megakube

#### Tasks
- [x] Delete megakube
- [x] ~~Create a new cluster with Terraform~~
- [x] Backup bigdata cluster volumes
- [x] Migrate bigdata snapshot to the new cluster location
- [x] ~~Add documentation on how to bootstrap a bigdata cluster~~
- [x] ~~Test docs~~
- [x] Delete old cluster
- [x] Cleanup any lingering volumes, snapshots or images

**Comment by pecigonzalo** [comment]
Quick xargs to copy the bigdata disks
```
echo {0..14}"\n" | xargs -n1 -P5 -i gcloud compute disks create repos-gitserver-'{}' --source-disk=https://www.googleapis.com/compute/v1/projects/sourcegr
aph-dev/zones/us-central1-c/disks/repos-gitserver-'{}'-cap-one --project=sourcegraph-bigdata-test --zone=us-central1-c
```

**Comment by pecigonzalo** [comment]
Snapshot disks
```
echo repos-gitserver-{0..14}"\n" | xargs -n1 -P5 -i gcloud compute disks snapshot '{}' --project=sourcegraph-bigdata-test --zone=us-central1-c --snapshot-
names '{}'
```

**Comment by pecigonzalo** [comment]
Created a `sourcegraph-bigdata-test` to hold these snapshots cluster if we decide to bring it up.
