### ISSUE TITLE
Move the CI e2e runner to the CI project

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#13919]
The E2E CI agent is currently deployed to a different project than CI, we should move this agent to the CI project and consolidate all CI infrastructure.

#### Tasks
- [ ] ~~Deploy new agent~~
- [ ] ~~Shutdown the old agent~~
- [ ] ~~Verify it can run job and access all resources~~
- [ ] ~~Delete the old agent instance and volumes~~

**Comment by pecigonzalo** [comment]
The node `gke-ci-e2e-`  seems to be part of the CI GKE cluster, but it does not run any buildkite agents. I have to discover what runs on this node.
The other e2e test runner already exists in the `sourcegraph-ci` project and does not need to be moved.
