### ISSUE TITLE
Move the CI cluster to the CI project

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#13920]
We want to consolidate all CI resources in the CI project, and we need to move the Kubernetes CI cluster for this.

#### Tasks
- [x] Deploy new GKE cluster
- [x] Migrate all service accounts and secrets
- [x] Verify agents can correctly run tasks
- [x] Destroy old cluster

**Comment by pecigonzalo** [comment]
New cluster created in `sourcegraph-ci` using Terraform and old cluster destroyed.
