### ISSUE TITLE
Java code intelligence via Sourcegraph extension

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1400]
Milestones
- [ ] Single repository code intelligence (no dependency installation)
- [ ] Single repository code intelligence with dependency installation
- [ ] Cross repository code intelligence
