### ISSUE TITLE
Upgrade to PostgreSQL 11.1

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1404]
We are currently running a very old version of PostgreSQL (9.4). This is an opportunity to upgrade since 3.0 is a major release. Ideally we would have auto-upgrading.

Other context https://github.com/sourcegraph/enterprise/issues/11192

Status:
- [x] Switch deploy-sourcegraph to 11
- [x] Switch server to 11
- [x] Production upgraded
- [x] deploy-sourcegraph auto-upgrades
- [x] server auto-upgrades
- [x] test plans

**Comment by keegancsmith** [comment]
I actually mentioned this yesterday (and said pg 11.1) https://sourcegraph.slack.com/archives/CCLF4R6EM/p1544695576192700 So yes its something I can look into when I get back from vacation.

**Comment by beyang** [comment]
I looked into this over the holidays and concluded it would be more than a day's worth of work to get it done for 3.0 (as it would include writing up migration docs and some manual steps for existing customers). Discussed with @nicksnyder and decided to backlog.

**Comment by keegancsmith** [comment]
However, 3.0 is targeting new users and some large customers won't upgrade straight away. So shipping a new version (and including instructions on what to do to upgrade) makes a lot of sense since this will be an annoying change. To me it makes sense to get this out since its one of our oldest tech debt items.

**Comment by nicksnyder** [comment]
Good point, I forgot about the details of what we discussed on Monday (I should have written it down here!)

@beyang @dadler @sqs is it ok if we make 3.0 a hard “current users don’t upgrade” release so we can get stuff like this in and then make 3.1 the fast follow of “current users can upgrade”?

**Comment by nicksnyder** [comment]
@keegancsmith You are right and the conversation we had on Monday (which I forgot about) still stands. I am going to put this back in the milestone.

**Comment by tsenart** [comment]
> So shipping a new version (and including instructions on what to do to upgrade) makes a lot of sense since this will be an annoying change.

To pick this up, I need more complete context of what makes this annoying and what to look out for. Would you be able to brain-dump the details here @keegancsmith?

**Comment by tsenart** [comment]
Currently reading: https://www.postgresql.org/docs/9.4/pgupgrade.html

**Comment by tsenart** [comment]
There are three separate high level streams of work to this upgrade process that I can identify:

1. Ship Postgres 11.1 with Sourcegraph 3.0-beta and make sure everything works with it.
1. Write documentation AND/OR automation for existing customer deployments:
    - https://github.com/rtshome/pgrepup
    - https://severalnines.com/blog/upgrading-your-database-to-postgresql-version-10
    - https://www.slideshare.net/PostgreSQL-Consulting/ilya-kosmodemiansky-an-ultimate-guide-to-upgrading-your-postgresql-installation-pgconfeu
1. Migrate sourcegraph.com with minimal downtime from 9.4 to 11.1.
    - https://gitlab.com/gitlab-com/gl-infra/infrastructure/issues/3446
    - https://hunleyd.github.io/posts/Upgrading-PostgreSQL-from-9.4-to-10.3-with-pglogical/


I think the first item is the most pressing and should be done for *3.0-beta*, the second and third come next and ought to be ready in time for *3.0*.

Upgrading our own sourcegraph.com deployment should drive the documentation and automation we build for upgrading customer's deployment. With that in mind, whatever automation we use / build should be deployment setup (e.g. https://github.com/rtshome/pgrepup), so that it can be used in K8S, single Docker image, and others.

For all of that work to be reasonably safe, we should invest in better monitoring beforehand by deploying https://github.com/wrouesnel/postgres_exporter or something like it and setting up a [good Grafana dashboard](https://github.com/cybertec-postgresql/pgwatch2#screenshot-of-the-db-overview-dashboard).

**Comment by tsenart** [comment]
For the love of God, I can't find `sourcegraph/server` Dockerfile. Any pointers?

**Comment by dadler** [comment]
FYI @nicksnyder, you may have "at-ted" the wrong username; I haven't been involved with this repo.

**Comment by nicksnyder** [comment]
I agree about (1) being the most important for 3.0-beta

> For the love of God, I can't find sourcegraph/server Dockerfile. Any pointers?

https://github.com/sourcegraph/sourcegraph/issues/1129

> FYI @nicksnyder, you may have "at-ted" the wrong username; I haven't been involved with this repo.
Sorry! (I meant dadlerj but didn’t have autocomplete on mobile)

**Comment by nicksnyder** [comment]
This is merged in master and works for new deployments (tested on dogfood). The remaining work is documentation and migrating sourcegraph.com, which is for 3.0

**Comment by keegancsmith** [comment]
Updated the issue description. What is missing is auto-upgrades in server and test plans. I expect this to be ready by Thursday morning pacific time so we have time to test.

The current idea is to re-use our postgresql auto-upgrade we use in deploy-sourcegraph. However, it requires us to switch from alpine to debian/ubuntu. This should not be a big deal after some refactoring I did to our docker build process.

Note: The process of upgrading production made our auto-upgrade pretty battle hardened. So this should work well.

**Comment by keegancsmith** [comment]
The current status of this is I was blocked by our CI and docker versions. I spent most of the day fixing this (went down the wrong path multiple times). Finally our CI supports multi-stage builds. But this leaves little time for me to do the automatic upgrades + us testing. I am working on it now, but it will be a bit delayed. See https://github.com/sourcegraph/sourcegraph/issues/2083

To mitigate risk, we could detect outdated PGDATA, and tell users to run a specific command to upgrade for server? This would be much easier to implement quickly and we can test that (while still hoping to get into automatic upgrades). cc @nicksnyder.

**Comment by nicksnyder** [comment]
Any step that mitigates risk and allows us to release 3.0 on time is worth doing.

> tell users to run a specific command to upgrade for server

How would we communicate this to users? At the least we would document this in the [upgrade docs](https://github.com/sourcegraph/sourcegraph/issues/1426), but what happens if a user doesn't read that?

**Comment by nicksnyder** [comment]
@tsenart There are two paths forward, and you can choose whichever path you think is least risky for us cutting a tested 3.0 release:

Path 1:
- [ ] Finish [automated upgrade process](https://github.com/sourcegraph/sourcegraph/issues/1404#issuecomment-458979577)
- [ ] Write a test plan.
- [ ] Update [migration guide](https://github.com/sourcegraph/sourcegraph/pull/2101/files)

Path 2:
- [ ] Detect if there is old PGDATA. If so, don't startup and instead print a message for a manual command to run to perform migration
- [ ] Write a test plan.
- [ ] Update [migration guide](https://github.com/sourcegraph/sourcegraph/pull/2101/files)

[Keegan recommended path 2](https://github.com/sourcegraph/sourcegraph/issues/1404#issuecomment-459403538)

**Comment by tsenart** [comment]
There were a few things we couldn't finish in time for 3.0. Additionally, we figured out that upgrading to 11.1 was a blocker for certain customers, and hence, learned last minute that we'd need to upgrade to 10.6 instead.

Here's a TODO list for us to refer to afterwards.

1. Write documentation on how to upgrade for customers that run external Postgres databases.
1. Write [documentation](https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/sourcegraph-3.0.migrate.md#postgres-111) on how to upgrade for customers that run Kubernetes (env vars, etc) 
1. Write documentation for server image customers on how to upgrade.
1. Finish auto-upgrade code of server image to 10.6: https://github.com/sourcegraph/sourcegraph/pull/2121
1. Change deploy-sourcegraph Postgres deployment to 10.6
1. Downgrade sourcegraph.com to 10.6
1. Downgrade CI to 10.6
1. Update docs/dev documentation
1. CHANGELOG

**Comment by nicksnyder** [comment]
This is done
