### ISSUE TITLE
3.21 release tracking issue

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#14064]
# 3.21 Release (2020-10-21)

**Note:** All `yarn run release ...` commands should be run from folder `dev/release`.
**Note:** All `yarn run test ...` commands should be run from folder `web`.

## 2020-10-13 (5 work days before release): Prep for branch cut

- [x] Post a release status update to Slack:
  ```
  yarn run release release:status 3.21.0
  ``` 
  - [x] Review [all release-blocking issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Asourcegraph+label%3Arelease-blocker). Add them as checklist items here. Ensure someone is resolving each.

## 2020-10-14 (4 work days before release): Branch cut

- [x] Update the changelog and merge the generated pull request:
  ```
  yarn run release changelog:cut 3.21.0
  ```
- [x] Create the `3.21` branch off the CHANGELOG commit in the previous step: `git branch 3.21 && git push origin 3.21`.
- [x] Tag the first release candidate:
  ```
  yarn run release release:create-candidate 3.21.0-rc.1
  ```
- [x] Run regression tests:
  - [x] Follow [README.md](https://github.com/sourcegraph/sourcegraph/blob/main/web/src/regression/README.md) to set up your e2e environment. 
        Run the tests from the `web` directory. A more complete set of env vars can be found in this
        [1password](https://team-sourcegraph.1password.com/vaults/dnrhbauihkhjs5ag6vszsme45a/allitems/gm5dfflq6sfclmotneuayfdj5q) entry.
  - [x] New Sourcegraph Docker container:
    - Run the initializer: `E2E_INIT=true SOURCEGRAPH_BASE_URL=http://localhost:7080 yarn run test:regression -t 'Initialize new Sourcegraph instance'`
    - Run the regression test suite: `SOURCEGRAPH_BASE_URL=http://localhost:7080 yarn run test:regression`
  - [x] Upgrade from previous release:
    - Run the initializer on a Docker container running the last patch version of the previous major/minor release.
    - Upgrade and run the regression test suite.
  - [x] New Sourcegraph Kubernetes cluster:
    - Run the initializer on a new Sourcegraph Kubernetes cluster.
    - Run the regression test suite.

## 2020-10-14 to 2020-10-19: Cut new release candidates

As necessary, `git cherry-pick` bugfix (not feature!) commits from `main` into the release branch.
Aggressively revert or disable features that may cause delays.

- [x] Post a release status update to Slack:
  ```
  yarn run release release:status 3.21.0
  ``` 
  - [x] Review [all release-blocking issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+archived%3Afalse+org%3Asourcegraph+label%3Arelease-blocker). Add them as checklist items here. Ensure someone is resolving each.
  - [x] Review [all other open issues in the milestone](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Asourcegraph+-label%3Arelease-blocker+milestone%3A$MAJOR.$MINOR) and ask assignees to triage them to a different milestone (preferring Backlog).

Cut a new release candidate daily if necessary:

- [x] Cut and announce release candidate:
  ```
  N=<release-candidate-number> yarn run release release:create-candidate 3.21.0-rc.$N
  ```
- [x] Re-run the automated test suite against the new release candidate, file any regressions as
  `release-blocker` issues.
- [x] If necessary, manually test features or workflows affected by the cherry-pick.

## 2020-10-19 (1 work day before release) Tag final release

- [x] Tag the final release:
  ```
  yarn run release release-candidate:create 3.21.0
  ```
- [x] Verify the [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) on
  `main` is accurate (no items should have been added since branch cut, but some items may need to
  be removed).
- [x] Wait for the release Docker images to be available in [Docker Hub](https://hub.docker.com/r/sourcegraph/server/tags).
- [x] Release Docker Compose by following [these instructions](https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/RELEASING.md)
- [x] Open (but do not merge) PRs that publish the new release:
  ```
  # Run this in the main sourcegraph repository in the `dev/release` directory on `main` branch:
  yarn run release release:publish 3.21.0
  ```
- [x] Create (but do not merge) a PR to update https://docs.sourcegraph.com/admin/updates/kubernetes indicating the steps required to upgrade.
- [x] Review [all issues in the release milestone](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Asourcegraph+milestone%3A3.21). Backlog things that didn't make it into the release and ping issues that still need to be done for the release (e.g. Tweets, marketing).

## 2020-10-20 by 10am: Release

- [x] Merge the release-publishing PRs created previously.
  - For [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph), also:
    - [x] Merge the PR to update the [Kubernetes CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/main/doc/admin/updates/kubernetes.md)
    - [x] Tag the `v3.21.0` release at this commit.
        ```
        VERSION='v3.21.0' bash -c 'git tag -a "$VERSION" -m "$VERSION" && git push origin "$VERSION"'
        ```
  - For [sourcegraph](https://github.com/sourcegraph/sourcegraph), also:
    - [x] Cherry pick the release-publishing PR from `sourcegraph/sourcegraph@main` into the release branch.
- [x] Ask the product team to merge the blog post ([example](https://github.com/sourcegraph/about/pull/83)).

### Post-release

- [x] Notify the next release captain that they are on duty for the next release. They should complete the steps in this section.
- [x] Ensure you have the latest version github.com/sourcegraph/about checked out and it is located
      at `../about` (relative to this repository).
- [x] Update `dev/release/config.json` with the parameters for the current release.
- [x] Run `yarn build` to rebuild the release script (necessary, because `config.json` is compiled in).
- [x] Create release calendar events, tracking issue, and announcement for next release:
  ```
  # Add calendar events and reminders for key dates in the release cycle
  yarn run release tracking:release-timeline

  # Create the release tracking issue (i.e., this issue)
  yarn run release tracking:release-issue
  ```
- [x] Close this issue.
- [x] Close the milestone.

**Comment by bobheadxi** [comment]
I just manually sync'd the tracking issue with the state of the tracking issue in as of https://github.com/sourcegraph/about/commit/feebc6b825e3bafe1f6a28ea59395c11b741f546

If Stephen gets the chance to look at https://github.com/sourcegraph/about/pull/1750 and it gets merged, I'll update the issue again, but it's a small change so we should be good to go here

**Comment by bobheadxi** [comment]
It seems the dates were wrong, but I've changed them back to the correct dates by hand and filed https://github.com/sourcegraph/sourcegraph/issues/14626
