### ISSUE TITLE
Security 3.21 Tracking issue

### ISSUE THREAD

**Issue by ElizabethStirling** [sourcegraph/sourcegraph#14076]
### Plan

We plant to gain visibility into the attack surface of Sourcegraph components, in order to support hosting private code on sourcegraph.com. For this release our focus will be on container visibility.

**Goal:** Increase visibility into the threat surface of our product by running automated vulnerability scanning, both of our code and of our docker containers. This goal is our top priority, since it will allow us to more accurately prioritize future work.

**Goal:** Centralize logging in order to allow for analysis of events across the Sourcegraph platform, rather than events as they're contained within a single microservice.

### Availability

Period is from 2020-09-20 to 2020-10-20. Please write the days you won't be working and the number of working days for the period.

Elizabeth: 1d, (2020-09-25)
Chayim: 3d (2020-09-28, 2020-09-29, 2020-10-06)

### Tracked issues

@ElizabethStirling: __2.00d__

Completed: __2.00d__
- [x] (🏁 19 days ago) Send email notifications when important user account information is changed ([~#7517~](https://github.com/sourcegraph/sourcegraph/issues/7517)) 🔒
- [x] (🏁 9 days ago) Configure GitHub code scanning via CodeQL and OSSAR ([~#14187~](https://github.com/sourcegraph/sourcegraph/issues/14187)) __2.00d__

@chayim: __3.50d__

Completed: __3.50d__
- [x] (🏁 22 days ago) ./dev/ci/e2e.sh prints CI password into logs ([~#6973~](https://github.com/sourcegraph/sourcegraph/issues/6973)) __0.50d__ 🔒
- [x] (🏁 21 days ago) sourcegraph/security-issues ([~#97~](https://github.com/sourcegraph/security-issues/issues/97)) __1.00d__ 🔒
- [x] (🏁 11 days ago) User documentation: data security policy ([~#13855~](https://github.com/sourcegraph/sourcegraph/issues/13855)) __2.00d__

@daxmc99: __2.00d__

Completed: __2.00d__
- [x] (🏁 35 days ago) secrets: use base64 and make interface private ([~#13850~](https://github.com/sourcegraph/sourcegraph/issues/13850)) __2.00d__

@unknwon: __2.00d__

Completed: __2.00d__
- [x] (🏁 35 days ago) secrets: use base64 and make interface private ([~#13850~](https://github.com/sourcegraph/sourcegraph/issues/13850)) __2.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by ElizabethStirling** [comment]
**This week**
This week was mostly spent taking care of non-coding tasks. I hopped on an issue around key security, and updated [our Company Values](https://github.com/sourcegraph/about/pull/1603). Then, I spent the rest of the week looking at planning documents and our team goals.

**Next Week**
I hope to get this tracking document out of its WIP state, and hammer out #7517. Additionally, if I have time remaining, I'd like to take a look at #14011, but this is a stretch goal, and subject to change depending on how our planning sessions go.

**Comment by sushiwushi** [comment]
**This Week**

This week was mostly spent in learning and analyzing the impact from [issue 94](https://github.com/sourcegraph/security-issues/issues/94). I found that there are some mitigations in place however it's still viable to create a damaging exploit. All the procedures are planned and listed out, the remaining part will be constructing the exploit.

**Next Week**

As my upcoming exam is next week, I need to take a few days off to prepare for it. With that said, I will still be online to check daily emails and updates in Slack.

**Comment by chayim** [comment]
**This Week**

This was mostly a house keeping week. I added documentation on team-building, and got the goals PR into the security page.  Commented on some PRs as part of the cloud 3.20 release. I completed the initial run of the blog post on transparent security, and solicited feedback. At the end of the week, I began working on the data security policy - #13855.  I also completed the blog post and am awaiting feedback.

**Next week**

This week, I'm planning on fixing [security issue #97](https://github.com/sourcegraph/security-issues/issues/97).  Additionally, I'd like to complete the data policy (#13855), and release a reliable artifact that can be used as part of the sales process.  We're going to further break down the application scanning issue (#13557), and I'm planning on getting the blog post into the repository, pending comments.

**Comment by ElizabethStirling** [comment]
**This Week**
This week, I started by getting some work done on planning and goal definition. I then added a few things to the handbook around bounty payments and onboarding. I also got #7517 finished, [pending tests functioning again](https://sourcegraph.slack.com/archives/C07KZF47K/p1601670820126400). Additionally, I hopped on [a security incident](https://sourcegraph.slack.com/archives/C1JH2BEHZ/p1601575849032500) in order to ensure it got resolved quickly.

**Next Week**
I'd like to get some work done on #14011 in order to prevent secrets from leaking, and to ensure that we notice if they do leak. I'll be hopping on a sales call on Friday to get more insight into how the security team can help support the entire organization. Finally, I want to do some thinking on how I can help develop my career, and potentially make a blog post about it, if I can come up with anything interesting. I think it could be a helpful exercise for me to get comfortable with writing blogposts, even if we decide against publishing it. This thinking was spurred by [reading a blog post by @chrispine ](https://about.sourcegraph.com/blog/software-engineer-career-paths/) and wanting to do some thinking around ways to expand your influence in an organization.

**Comment by sushiwushi** [comment]
**This Week**

This week, I was out most of the time due to college exams. That being said, I was able to finalize the exploitation requirements and provide a working proof of concept for the [vulnerability](https://github.com/sourcegraph/security-issues/issues/94) I discovered. Oddly enough, I went down many unnecessary rabbit holes just to find that some token values are not required to make the exploit work.

**Next week**

I believe that there are more room to construct the exploit into achieving higher privilege state such as account takeover, so I'm gonna spend my time researching there. Additionally, I'll also try to verify [CSS injection](https://www.netsparker.com/blog/web-security/private-data-stolen-exploiting-css-injection/) as suggested by @chayim.

**Comment by chayim** [comment]
**Last Week**

Last week I get [security issue #97](https://github.com/sourcegraph/security-issues/issues/97) committed to main. I completed the work on the data policy (#13855) which you can [read here](https://docs.google.com/document/d/1sVBHaGLXojcq7zAxJo8D4Fonh4kxA3grtWgzbKoAn-0). At this point the specific policy can beocme a dedicated document as required for sales.  The team discussed breaking down the purpose of code and container scanning (#13557). Finally, all comments on the blog post (for the future) were merged into the document.  Time was also spent reviewing some lever candidates.  I also validated that our CI scripts no longer echo passwords into logs (#6973).

**Next week**

This week I'm planning on writing the [RFC](https://docs.google.com/document/d/1dBzP3VZWVNOZD7dIN4izgzl3wDa5Sjj8LtS9zQViri8/) for centralizing security events. I'm also going to close off the bounty for [security issue #97](https://github.com/sourcegraph/security-issues/issues/97). I want to spend time thinking about [point to point encryption](https://github.com/sourcegraph/security-issues/issues/57). nd possibly writing an RFC in order to kickstart the conversation.  Additionally, there's a coding excerise to grade.  Finally, I'd like to start on vulnerability scans of containers (#13557) now that we've broken it down, especially if @ElizabethStirling is going to start down the path of #14011.

**Comment by sushiwushi** [comment]
**This Week**

This week, I have verified a Cross-site request forgery (CSRF) vulnerability and XML external entity attack (XXE) during my penetration testing process in the application. Both of the reports can be found in [security issue #108](https://github.com/sourcegraph/security-issues/issues/108) and [security issue #110](https://github.com/sourcegraph/security-issues/issues/110).

**Next Week**

Next week, I will continue to penetrate the application and verify some vulnerabilities to make sure the application isn't vulnerable to them. One of the vulnerabilities I would like to try is HTTP request smuggling vulnerability that is emerging this year.

**Comment by chayim** [comment]
**This Week**

I finished up the [RFC](https://docs.google.com/document/d/1dBzP3VZWVNOZD7dIN4izgzl3wDa5Sjj8LtS9zQViri8/) for centralizing security events, and got it out for review.  I spent time thinking through hiring, and the vulnerability scans of containers (#13557) taking a direct look at Sysdig, and locally a few other vulnerability scanners.  I also started testing out vulnerability scanning of workloads with intruder. I also closed off the policy item (#13855).

**Next Week**
I'd like to wire up container scanning into the pipeline, probably using GitHub actions (#13557) which should move us towards fixing at lesat one item (#14089). I'd also like to get our RFC approved, and finalize the hiring process so that I can focus some attention there.

**Comment by ElizabethStirling** [comment]
**Last Week**
Throughout last week, I responded to and investigated some vulnerability reports. @chayim and I worked on milestones, and came to an agreement on when things would get done. Afterwards, I updated the `.gitignore` on some of our public repos as per a request from @nicksnyder. Finally, I got some work done on an RFC for [Security Issue 8](https://github.com/sourcegraph/security-issues/issues/8).


**This Week**
This week, I plan to start by finishing the [RFC](https://docs.google.com/document/d/1HzO7szEm-h4fqlQOnVbcJdpDmfQiM7Rb-Tz4CMEYl-Q/edit#) for [Security Issue 8](https://github.com/sourcegraph/security-issues/issues/8). I'd like to hammer out #14187 soon, so that we can have that additional logging infrastructure for our [security team goal](https://about.sourcegraph.com/handbook/engineering/security#visibility-into-sourcegraph-cloud-s-attack-surface) of visibility.

**Comment by ElizabethStirling** [comment]
**This Week**
I started this week responding to bug reports, then spent the majority of my remaining time writing and responding to comments on an [RFC](https://docs.google.com/document/d/1HzO7szEm-h4fqlQOnVbcJdpDmfQiM7Rb-Tz4CMEYl-Q/edit#) for [Security Issue 8](https://github.com/sourcegraph/security-issues/issues/8). I also resolved #14187 after determining that the only additional value OSSAR would give would be another ESlint scan, which we already have implemented. I finished by creating [the new tracking issue](https://github.com/sourcegraph/sourcegraph/issues/14813) for 3.22.


**Next Week**
Next week, I plan to finalize the decisions of the afforementioned RFC, but do not plan to implement them yet, since there are currently more pressing concerns at play. Then, I plan to context switch to tasks that will help wrap up the goals of 3.21 and start the goals of 3.22.

**Comment by sushiwushi** [comment]
**This Week**

This week, I have verified a HTTP request smuggling vulnerability and HTTP host header injection vulnerability during my penetration testing process in the application. Both of the reports can be found in [security issue #111](https://github.com/sourcegraph/security-issues/issues/111) and [security issue #112](https://github.com/sourcegraph/security-issues/issues/112).

**Next Week**

Next week, I will continue to penetrate the application and verify some vulnerabilities to make sure the application isn't vulnerable to them. One particular bug in my checklist is checking any possibility for a normal user to view site-admin directories and information.

**Comment by chayim** [comment]
**Last Week**

I created a PR to enable container scans with [anchore](https://github.com/sourcegraph/sourcegraph/pull/14767), and investigated a [reported issue](https://sourcegraph.slack.com/archives/CJX299FGE/p1602717596422900).  I answered questions for [RFC 245](https://docs.google.com/document/d/1dBzP3VZWVNOZD7dIN4izgzl3wDa5Sjj8LtS9zQViri8/), interviewed a promising candidate, and worked on our hiring process. I also answered a security questionnaire. Finally, I improved our [vulnerability reporting process](https://about.sourcegraph.com/handbook/engineering/security/reporting-vulnerabilities).

**This Week**

I'm going to merge the PR for container scans, and start fixing vulnerabilities. [RFC 245](https://docs.google.com/document/d/1dBzP3VZWVNOZD7dIN4izgzl3wDa5Sjj8LtS9zQViri8/) is going to be approved, and I'll start by setting things up. I'd like to get a PR up for the improved hiring process for security. Finally, I'm going to turn my attention back to intruder.io, and look at how it handles Google Cloud environments.

**Comment by ElizabethStirling** [comment]
Closing this out, since 3.21 is finished. Please use [the 3.22 tracking issue](https://github.com/sourcegraph/sourcegraph/issues/14813)
