### ISSUE TITLE
Product team 3.21 Tracking issue

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#14101]
### Plan

List of work in progress:

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@AlicjaSuska

- [ ] https://github.com/sourcegraph/sourcegraph/issues/13808    🏳️ [3.21](https://github.com/sourcegraph/sourcegraph/milestone/46)

@rrhyne: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/13928  __3.00d__   🏳️ [3.21](https://github.com/sourcegraph/sourcegraph/milestone/46)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/13808    🏳️ [3.21](https://github.com/sourcegraph/sourcegraph/milestone/46)

Completed
- [x] (🏁 821 days ago) https://github.com/sourcegraph/sourcegraph/issues/12192    🏳️ [3.21](https://github.com/sourcegraph/sourcegraph/milestone/46)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by rrhyne** [comment]
### Thursday 17th / Friday 18th
* Created a prototype of an alternative solution for advancing the search tour
* Explored design solutions for multi line query editor and collapsing queries

### Monday 21st / Wed 23rd
* Server home QA round 2
* Helped analytics process dodgy json files
* Responsive campaigns design work 
* Improved grid systems in the component library

**Comment by quinnkeast** [comment]
**Last week / 17-18**
- Design support for user-added cloud repositories
- Wrapped up content guidelines

**This week / 21–23**
- Launched content guidelines
- Supporting development of sign in / out UX
- Ramping up on Cloud team goals and planning design approach
