### ISSUE TITLE
RFC 211 Tracking issue

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#14163]
@asdine: __6.50d__

Completed: __6.50d__
- [x] (🏁 34 days ago) RFC 211: Repo updater should sync external services separately ([~#14041~](https://github.com/sourcegraph/sourcegraph/issues/14041)) __2.00d__
- [x] (🏁 34 days ago) RFC 211: Remove completed jobs from external_service_sync_jobs table ([~#14048~](https://github.com/sourcegraph/sourcegraph/issues/14048)) __0.50d__
- [x] (🏁 28 days ago) RFC 211: Repos added by user owned external services should be indexed ([~#14042~](https://github.com/sourcegraph/sourcegraph/issues/14042)) __1.00d__
- [x] (🏁 28 days ago) RFC 211: User added external services on Cloud should clone newly added repos on first sync ([~#14315~](https://github.com/sourcegraph/sourcegraph/issues/14315)) __2.00d__
- [x] (🏁 28 days ago) RFC 211: Add alert if repo sync jobs are not consumed ([~#14045~](https://github.com/sourcegraph/sourcegraph/issues/14045)) __1.00d__

@ryanslade: __14.00d__

- [ ] Cloud 2020-10-21 Tracking issue ([#14763](https://github.com/sourcegraph/sourcegraph/issues/14763)) __2.50d__
  - [x] (🏁 5 days ago) Implement repogroup:"my" workaround to allow us to better dogfood user added repos ([~#14919~](https://github.com/sourcegraph/sourcegraph/issues/14919)) __2.50d__

Completed: __14.00d__
- [x] (🏁 41 days ago) RFC 211: repo-updater new syncer doesn't use s.Logger ([~#13718~](https://github.com/sourcegraph/sourcegraph/issues/13718)) __0.50d__
- [x] (🏁 34 days ago) RFC 211: Repo updater should sync external services separately ([~#14041~](https://github.com/sourcegraph/sourcegraph/issues/14041)) __2.00d__
- [x] (🏁 33 days ago) RFC 211: Number of concurrent syncers should be configurable ([~#14268~](https://github.com/sourcegraph/sourcegraph/issues/14268)) __0.50d__
- [x] (🏁 28 days ago) RFC 211: We should apply a per user and total limit to user added repos ([~#14043~](https://github.com/sourcegraph/sourcegraph/issues/14043)) __1.50d__
- [x] (🏁 28 days ago) RFC 211: User added external services on Cloud should clone newly added repos on first sync ([~#14315~](https://github.com/sourcegraph/sourcegraph/issues/14315)) __2.00d__
- [x] (🏁 26 days ago) RFC 211: Write docs for user added repos ([~#14477~](https://github.com/sourcegraph/sourcegraph/issues/14477)) __0.50d__
- [x] (🏁 25 days ago) monitoring: add more panels to Grafana repo-updater dashboard ([~#14237~](https://github.com/sourcegraph/sourcegraph/issues/14237)) __1.00d__ 👩
- [x] (🏁 25 days ago) RFC-211: Devise and implement relevant alerts ([~#14442~](https://github.com/sourcegraph/sourcegraph/issues/14442)) __2.00d__
- [x] (🏁 22 days ago) Allow all Sourcegraph teammates to add their own public repos in the Cloud env ([~#14441~](https://github.com/sourcegraph/sourcegraph/issues/14441)) __0.50d__
- [x] (🏁 22 days ago) Create demo video for user added public repos in sourcegraph.com ([~#14438~](https://github.com/sourcegraph/sourcegraph/issues/14438)) __1.00d__
- [x] (🏁 5 days ago) Implement repogroup:"my" workaround to allow us to better dogfood user added repos ([~#14919~](https://github.com/sourcegraph/sourcegraph/issues/14919)) __2.50d__

**Comment by tsenart** [comment]
@ryanslade, @asdine: Is there other work we need to track that isn't here already?

**Comment by asdine** [comment]
@tsenart If we don't count the security work, everything seems there
