### ISSUE TITLE
RFC-214: Tracking issue

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#14166]
## Context

RFC-214: https://docs.google.com/document/d/1ajVQ11Vyi0Wz67DN15W3girJ5kyB5Zb7vk0LK6r7gbQ/edit

## Work

@unassigned

- [ ] Customers should be able to specify their own encryption token ([#14298](https://github.com/sourcegraph/sourcegraph/issues/14298))
- [ ] Customers should be able to specify their key rotation encryption token ([#14299](https://github.com/sourcegraph/sourcegraph/issues/14299))
- [ ] Sourcegraph should encrypt customer data with their customer specific token ([#14300](https://github.com/sourcegraph/sourcegraph/issues/14300))
- [ ] Sourcegraph should encrypt rotate customer token encrypted data ([#14302](https://github.com/sourcegraph/sourcegraph/issues/14302))
- [ ] Sourcegraph should log and email important encryption events ([#14303](https://github.com/sourcegraph/sourcegraph/issues/14303))

@daxmc99: __9.00d__

- [ ] RFC-214: Enable encryption on dogfood & cloud ([#14192](https://github.com/sourcegraph/sourcegraph/issues/14192)) __3.00d__

Completed: __6.00d__
- [x] (🏁 147 days ago) RFC-214: Transparent encryption and decryption for all tables that contain secrets or tokens ([~#13851~](https://github.com/sourcegraph/sourcegraph/issues/13851)) __1.00d__
- [x] (🏁 86 days ago) RFC-214: Encrypt secrets in user_external_accounts, external_services, saved_searches and external_service_repos ([~#13853~](https://github.com/sourcegraph/sourcegraph/issues/13853)) __5.00d__

@flying-robot: __1.00d__

Completed: __1.00d__
- [x] (🏁 152 days ago) RFC-214: Repository Settings > Mirroring should not display token in the UI ([~#13852~](https://github.com/sourcegraph/sourcegraph/issues/13852); PRs: ~[#14153](https://github.com/sourcegraph/sourcegraph/pull/14153)~) __1.00d__

@ryanslade: __1.00d__

Completed: __1.00d__
- [x] (🏁 152 days ago) RFC-214: Repository Settings > Mirroring should not display token in the UI ([~#13852~](https://github.com/sourcegraph/sourcegraph/issues/13852); PRs: ~[#14153](https://github.com/sourcegraph/sourcegraph/pull/14153)~) __1.00d__

@unknwon: __6.50d__

Completed: __6.50d__
- [x] (🏁 152 days ago) RFC-214: Eyeball validate data being encrypted in the database ([~#13854~](https://github.com/sourcegraph/sourcegraph/issues/13854)) __0.50d__
- [x] (🏁 147 days ago) RFC-214: Transparent encryption and decryption for all tables that contain secrets or tokens ([~#13851~](https://github.com/sourcegraph/sourcegraph/issues/13851)) __1.00d__
- [x] (🏁 86 days ago) RFC-214: Encrypt secrets in user_external_accounts, external_services, saved_searches and external_service_repos ([~#13853~](https://github.com/sourcegraph/sourcegraph/issues/13853)) __5.00d__

**Comment by ElizabethStirling** [comment]
Wanted to circle back on this to make sure it has a team assigned to it to prevent it from getting lost in the backlog, especially since this is post-GA work from the perspective of @sourcegraph/security. @sourcegraph/cloud seems like it would be the correct team, but I could see security being somewhat involved in pairing and reviewing code.

**Comment by unknwon** [comment]
I added "team/cloud" label since there are some half-baked PRs on some of these issues, and seems reasonable to currently have Cloud team as the engineering owner. However, defer to @tsenart and @chayim.

**Comment by chayim** [comment]
Confirmed. team/cloud definitely makes the most sense!

**Comment by unknwon** [comment]
Closing as we're no longer pursuing RFC 214
