### ISSUE TITLE
RFC 221 Tracking issue: Improve discoverability/awareness of the browser extension

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#14165]
Tracking issue for [RFC 221: Improve discoverability/awareness of the browser extension](https://docs.google.com/document/d/19f4xleYBU1zZZdqMmXlLmFxeR-fwEpOwTOgViOFOnyo/edit?usp=sharing)

### Tracked issues

@AlicjaSuska

- [ ] https://github.com/sourcegraph/sourcegraph/issues/14235 
- [x] https://github.com/sourcegraph/sourcegraph/issues/14234 

@felixfbecker

- [x] https://github.com/sourcegraph/sourcegraph/issues/14234

**Comment by Joelkw** [comment]
@AlicjaSuska I messed something up with our tracking issue bot/triggered it from dark mode tracking issue. Apologies for the noise and feel free to ignore.
