### ISSUE TITLE
Tracking issue to track Eric's tracking issue improvements in 3.21 

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#14264]
@efritz

- [ ] Tracking issue to track Eric's tracking issue improvements in 3.21  ([#14264](https://github.com/sourcegraph/sourcegraph/issues/14264)) 

Completed
- [x] (🏁 10 days ago) tracking-issue: Fix timeout (~[#13986](https://github.com/sourcegraph/sourcegraph/pull/13986)~) :shipit:
- [x] (🏁 10 days ago) tracking-issue: Fix long-form linked issues (~[#13989](https://github.com/sourcegraph/sourcegraph/pull/13989)~) :shipit:
- [x] (🏁 10 days ago) tracking-issue: Nested tracking issues (~[#13998](https://github.com/sourcegraph/sourcegraph/pull/13998)~) :shipit:
- [x] (🏁 9 days ago) tracking-issue: Parallelize writes (~[#14006](https://github.com/sourcegraph/sourcegraph/pull/14006)~) :shipit:
- [x] (🏁 9 days ago) tracking-issue: Break code up into files according to type/action (~[#14013](https://github.com/sourcegraph/sourcegraph/pull/14013)~) :shipit:
- [x] (🏁 9 days ago) tracking-issue: List PRs for an issue inline (~[#14018](https://github.com/sourcegraph/sourcegraph/pull/14018)~) :shipit:
- [x] (🏁 9 days ago) tracking-issue: Separate complete/incomplete work (~[#14034](https://github.com/sourcegraph/sourcegraph/pull/14034)~) :shipit:
- [x] (🏁 8 days ago) tracking-issue: Fix strikethrough on closed (un-merged) PRs (~[#14107](https://github.com/sourcegraph/sourcegraph/pull/14107)~) :shipit:
- [x] (🏁 7 days ago) tracking-issue: Nest unlinked PRs under the closest tracking issue (~[#14108](https://github.com/sourcegraph/sourcegraph/pull/14108)~) :shipit:
- [x] (🏁 7 days ago) tracking-issue: Fix tests (~[#14168](https://github.com/sourcegraph/sourcegraph/pull/14168)~) :shipit:
- [x] (🏁 7 days ago) tracking-issue: Do not show completed PRs if the owning image is also complete (~[#14169](https://github.com/sourcegraph/sourcegraph/pull/14169)~) :shipit:
- [x] (🏁 7 days ago) tracking-issue: Hide completed work nested in other completed work (~[#14175](https://github.com/sourcegraph/sourcegraph/pull/14175)~) :shipit:
- [x] (🏁 7 days ago) tracking-issue: Strikethrough complete PRs (for visual consistency) (~[#14176](https://github.com/sourcegraph/sourcegraph/pull/14176)~) :shipit:
- [x] (🏁 7 days ago) tracking-issue: Make sorting deterministic (~[#14184](https://github.com/sourcegraph/sourcegraph/pull/14184)~) :shipit:
- [x] (🏁 6 days ago) tracking-issue: Display partially nested items ([~#14177~](https://github.com/sourcegraph/sourcegraph/issues/14177); PRs: ~[#14185](https://github.com/sourcegraph/sourcegraph/pull/14185)~) 
- [x] (🏁 today) tracking-issue: Display intermediate tracking issues with disjoint labels ([~#14205~](https://github.com/sourcegraph/sourcegraph/issues/14205); PRs: ~[#14265](https://github.com/sourcegraph/sourcegraph/pull/14265)~) 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
