### ISSUE TITLE
Cloud 2020-10-07 Tracking issue

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#14340]
### Plan

1. RFC 167 - Enforcing product license tiers: @flying-robot and @unknwon will work on this with the aim to have it all done by the end of the cycle.
1. RFC 211 - User added public repos: @ryanslade and @asdine are wrapping up the last bits of this (monitoring and alerting, enabling it for all teammates, making a demo video).
1. Syncing repos is more scalable: We'll be paying down some technical debt we have introduced in repo-updater in the last few months, with the aim to make further changes down the line easier to implement.

Apart from these high level themes, we're going to work on a few customer issues and smaller improvements.

### Work

@unassigned: __3.50d__

- [ ] Deploy to a cluster link in search performance warning notice is relative, not absolute ([#13745](https://github.com/sourcegraph/sourcegraph/issues/13745)) __0.50d__ 🐛

Completed: __3.00d__
- [x] (🏁 8 days ago) RFC 167: Enforce private extension registry ([~#14026~](https://github.com/sourcegraph/sourcegraph/issues/14026)) __1.00d__
- [x] (🏁 7 days ago) RFC 167: Deal with old licenses ([~#14032~](https://github.com/sourcegraph/sourcegraph/issues/14032)) __2.00d__

@asdine: __7.00d__

Completed: __7.00d__
- [x] (🏁 11 days ago) observerSource.ListRepos doesn't record errors ([~#14337~](https://github.com/sourcegraph/sourcegraph/issues/14337); PRs: ~[#14518](https://github.com/sourcegraph/sourcegraph/pull/14518)~) __0.50d__ 🐛
- [x] (🏁 11 days ago) repo-updater crash with gitlab with projects with both id and name ([~#13737~](https://github.com/sourcegraph/sourcegraph/issues/13737); PRs: ~[#14519](https://github.com/sourcegraph/sourcegraph/pull/14519)~) __1.00d__ 🐛
- [x] (🏁 7 days ago) Missing external_service_repos rows ([~#14613~](https://github.com/sourcegraph/sourcegraph/issues/14613)) __0.50d__ 🐛
- [x] (🏁 7 days ago) repo-updater: Add an index on the external_service_sync_jobs ([~#14440~](https://github.com/sourcegraph/sourcegraph/issues/14440)) __0.50d__
- [x] (🏁 4 days ago) repo store: Return sources ([~#14707~](https://github.com/sourcegraph/sourcegraph/issues/14707); PRs: ~[#14772](https://github.com/sourcegraph/sourcegraph/pull/14772)~) __1.50d__ 🧶
- [x] (🏁 4 days ago) sourcegraph/customer ([~#48~](https://github.com/sourcegraph/customer/issues/48); PRs: ~[#14795](https://github.com/sourcegraph/sourcegraph/pull/14795)~) __1.00d__ 👩
- [x] (🏁 4 days ago) Detect and delete public repository added-on-visit when it become private ([~#13978~](https://github.com/sourcegraph/sourcegraph/issues/13978); PRs: ~[#14517](https://github.com/sourcegraph/sourcegraph/pull/14517)~) __1.00d__ 🔒
- [x] (🏁 today) repo-updater: SetClonedRepos fails with temporary file size exceeds temp_file_limit error ([~#14431~](https://github.com/sourcegraph/sourcegraph/issues/14431); PRs: ~[#14793](https://github.com/sourcegraph/sourcegraph/pull/14793)~) __1.00d__ 🐛

@flying-robot: __2.00d__

Completed: __2.00d__
- [x] (🏁 6 days ago) Support efficient repository listing pagination in the GraphQL API ([~#13715~](https://github.com/sourcegraph/sourcegraph/issues/13715); PRs: ~[#14690](https://github.com/sourcegraph/sourcegraph/pull/14690)~) __2.00d__ 👩🧶

@ryanslade: __6.50d__

- [ ] RFC 211 Tracking issue ([#14163](https://github.com/sourcegraph/sourcegraph/issues/14163)) __5.00d__
  - [x] (🏁 11 days ago) monitoring: add more panels to Grafana repo-updater dashboard ([~#14237~](https://github.com/sourcegraph/sourcegraph/issues/14237); PRs: ~[#14269](https://github.com/sourcegraph/sourcegraph/pull/14269)~) __1.00d__ 👩
  - [x] (🏁 8 days ago) Create demo video for user added public repos in sourcegraph.com ([~#14438~](https://github.com/sourcegraph/sourcegraph/issues/14438)) __1.00d__
  - [x] (🏁 8 days ago) Allow all Sourcegraph teammates to add their own public repos in the Cloud env ([~#14441~](https://github.com/sourcegraph/sourcegraph/issues/14441)) __0.50d__
  - [x] (🏁 11 days ago) RFC-211: Devise and implement relevant alerts ([~#14442~](https://github.com/sourcegraph/sourcegraph/issues/14442); PRs: ~[#14530](https://github.com/sourcegraph/sourcegraph/pull/14530)~) __2.00d__
  - [x] (🏁 12 days ago) RFC 211: Write docs for user added repos ([~#14477~](https://github.com/sourcegraph/sourcegraph/issues/14477); PRs: ~[#14516](https://github.com/sourcegraph/sourcegraph/pull/14516)~) __0.50d__

Completed: __6.50d__
- [x] (🏁 12 days ago) repo-updater: Clean up old sync jobs on startup ([~#14479~](https://github.com/sourcegraph/sourcegraph/pull/14479)) :shipit:
- [x] (🏁 12 days ago) RFC 211: Write docs for user added repos ([~#14477~](https://github.com/sourcegraph/sourcegraph/issues/14477); PRs: ~[#14516](https://github.com/sourcegraph/sourcegraph/pull/14516)~) __0.50d__
- [x] (🏁 11 days ago) monitoring: add more panels to Grafana repo-updater dashboard ([~#14237~](https://github.com/sourcegraph/sourcegraph/issues/14237); PRs: ~[#14269](https://github.com/sourcegraph/sourcegraph/pull/14269)~) __1.00d__ 👩
- [x] (🏁 11 days ago) RFC-211: Devise and implement relevant alerts ([~#14442~](https://github.com/sourcegraph/sourcegraph/issues/14442); PRs: ~[#14530](https://github.com/sourcegraph/sourcegraph/pull/14530)~) __2.00d__
- [x] (🏁 10 days ago) repo-updater: Handle null value returned from metric query ([~#14583~](https://github.com/sourcegraph/sourcegraph/pull/14583)) :shipit:
- [x] (🏁 10 days ago) repo-updater: Don't log when error is nil ([~#14584~](https://github.com/sourcegraph/sourcegraph/pull/14584)) :shipit:
- [x] (🏁 8 days ago) repo-updater: Remove NewChangesetSource ([~#14585~](https://github.com/sourcegraph/sourcegraph/pull/14585)) :shipit:
- [x] (🏁 8 days ago) Allow all Sourcegraph teammates to add their own public repos in the Cloud env ([~#14441~](https://github.com/sourcegraph/sourcegraph/issues/14441)) __0.50d__
- [x] (🏁 8 days ago) Create demo video for user added public repos in sourcegraph.com ([~#14438~](https://github.com/sourcegraph/sourcegraph/issues/14438)) __1.00d__
- [x] (🏁 7 days ago) monitoring: By default show instance name instead of "value" ([~#14662~](https://github.com/sourcegraph/sourcegraph/pull/14662)) :shipit:
- [x] (🏁 6 days ago) monitoring: Allow alerting on zero ([~#14658~](https://github.com/sourcegraph/sourcegraph/pull/14658)) :shipit:
- [x] (🏁 6 days ago) monitoring: Properly aggregate repo-updater metrics ([~#14704~](https://github.com/sourcegraph/sourcegraph/pull/14704)) :shipit:
- [x] (🏁 6 days ago) frontend: Remove deprecated language field ([~#14718~](https://github.com/sourcegraph/sourcegraph/pull/14718)) :shipit:
- [x] (🏁 5 days ago) monitoring: Amend repo-updater critical alerts ([~#14757~](https://github.com/sourcegraph/sourcegraph/pull/14757)) :shipit:
- [x] (🏁 5 days ago) repo-store: Add Delete method ([~#14709~](https://github.com/sourcegraph/sourcegraph/issues/14709); PRs: ~[#14768](https://github.com/sourcegraph/sourcegraph/pull/14768)~) __0.50d__ 🧶
- [x] (🏁 1 day ago) repo-updater: Remove deprecated Language field ([~#14801~](https://github.com/sourcegraph/sourcegraph/pull/14801)) :shipit:
- [x] (🏁 today) repo-updater: Convert the Store to use basestore ([~#14755~](https://github.com/sourcegraph/sourcegraph/issues/14755); PRs: ~[#14901](https://github.com/sourcegraph/sourcegraph/pull/14901)~) __1.00d__ 🧶

@tsenart

Completed
- [x] (🏁 5 days ago) db: Improve defaultRepos.List query ([~#14600~](https://github.com/sourcegraph/sourcegraph/pull/14600)) :shipit:

@unknwon: __3.00d__

Completed: __3.00d__
- [x] (🏁 11 days ago) monitoring: add more panels to Grafana repo-updater dashboard ([~#14269~](https://github.com/sourcegraph/sourcegraph/pull/14269)) :shipit:
- [x] (🏁 8 days ago) RFC 167: Generate new licenses with versioned tags ([~#14021~](https://github.com/sourcegraph/sourcegraph/issues/14021); PRs: ~[#14236](https://github.com/sourcegraph/sourcegraph/pull/14236)~) __1.00d__
- [x] (🏁 6 days ago) authz: remove read/write path of binary format permissions ([~#13740~](https://github.com/sourcegraph/sourcegraph/issues/13740)) __0.50d__
- [x] (🏁 today) RFC 167: Enforce allowlist extensions ([~#14027~](https://github.com/sourcegraph/sourcegraph/issues/14027)) __0.50d__
- [x] (🏁 today) RFC 167: Update documentation to reflect changes on license tags ([~#14022~](https://github.com/sourcegraph/sourcegraph/issues/14022)) __0.50d__
- [x] (🏁 today) Unable to log in via GitLab OAuth ([~#14144~](https://github.com/sourcegraph/sourcegraph/issues/14144)) __0.50d__ 🐛

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by ryanslade** [comment]
## Week ending 9th October

* Finished work on monitoring and alerting of `repo-updater`
* Added docs describing how to add public external services as a user

## Next week

* Demo video and opt in all current employees
* Start work on the tech debt items

**Comment by unknwon** [comment]
### Last week

Back from holiday, caught up Slack messages and emails.

### This week

Focus on RFC 167, sync with @flying-robot on Tuesday then split the workload.

**Comment by asdine** [comment]
### Last week

- Worked on deleting repositories when they become private https://github.com/sourcegraph/sourcegraph/pull/14517
- Worked on simplifying the repo.Store interface https://github.com/sourcegraph/sourcegraph/issues/14092
- Fix crash on Gitlab external service configuration https://github.com/sourcegraph/sourcegraph/pull/14519
- Fixed error recording or ListRepos errors https://github.com/sourcegraph/sourcegraph/pull/14518

### This week

- Finish the ongoing work on https://github.com/sourcegraph/sourcegraph/issues/14092 and https://github.com/sourcegraph/sourcegraph/pull/14517
- Work on repo-updater issues

**Comment by ryanslade** [comment]
## Week ending 16th October

* Tweaked the repo updater alerting and dashboards to handle deployments more gracefully and make some alerts less flaky
* Enabled Sourcegraph employees to add code to sourcegraph.com
* Recorded a demo video 
* Started moving db access code into `internal/db` so that `repos/store` only performs `repo-updater` specific tasks. Eventually we also want both stores to use the `basestore` package so that we can reuse transactions.

## Next tweek

* Planning and retrospective
* Work through db package debt items
* Decide on work for second half of week after planning

**Comment by asdine** [comment]
### Last week

- Finished the PR on deleting repositories when they become private https://github.com/sourcegraph/sourcegraph/pull/14517
- Created a plan for simplifying the repo.Store interface https://github.com/sourcegraph/sourcegraph/issues/14092
- Added missing `external_service_repos` rows by running queries on the production database https://github.com/sourcegraph/sourcegraph/issues/14613
- Added an index on `external_service_repos` state column https://github.com/sourcegraph/sourcegraph/issues/14440
- Modified `Get` and `List` methods of the internal/db/store methods to return sources https://github.com/sourcegraph/sourcegraph/issues/14707
- Fixed redis cache deletion https://github.com/sourcegraph/customer/issues/48

### This week

- Finish working on a scaling `SetClonedRepos`  https://github.com/sourcegraph/sourcegraph/issues/14431
- Spike to investigate a simpler architecture for repo-updater https://github.com/sourcegraph/sourcegraph/issues/14369
- Write an issue for simplifying our use of tokens on frontend, repo-udpater and gitserver
- Prepare next cycle with the team

**Comment by unknwon** [comment]
### Last week

- Was a bit chaos on my productivity later on the week
- Mostly focused on addressing the 3.21 release blocker.

### This week

- Finish up RFC 167
