### ISSUE TITLE
resolve pure docker admin update docs TODO (describe new env vars necessary for code intel DB)

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#14347]
https://github.com/sourcegraph/sourcegraph/pull/13904

**Comment by slimsag** [comment]
The tests do not need to be updated, but we need to release the prior versions before we can release this one.

Eric updated the tests and you can see they passed on CI here: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/153/files

What will need to be mentioned in the TODO section is that he added this line: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/153/files#diff-1421303c75ba132a8bdf81179add20eaR24

As is documented here: https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/58bcdf62eb47194c9706a381c385ee831547a963/test/pure-docker/volume-config.sh#L13-L16

**Comment by slimsag** [comment]
Basically the process to resolve this is:

1. [ ] Release pure-docker 3.18.0 -> 3.19.x upgrade, document it in https://docs.sourcegraph.com/admin/updates/pure_docker and inform customer and wait for them to upgrade:
    - Following https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/RELEASING.md#releasing-pure-docker
    - https://github.com/sourcegraph/customer/issues/103
2. [ ] Repeat the above for 3.19.x -> 3.20.x
3. [ ] Repeat the above for 3.20.x -> 3.21.x, including documenting the above note about the new codeintel-db and manual directory creation / `chown` commands needed.

**Comment by slimsag** [comment]
Looks like the last part here was done in https://github.com/sourcegraph/sourcegraph/pull/15412
