### ISSUE TITLE
Distribution - 2020.10.20 - Vibrant Beetle

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#14408]
#### [Support new and existing deployments](https://github.com/orgs/sourcegraph/projects/74)

This is an ongoing expense, we anticipate this taking no more than 5d of work spread across the entire team.

#### [Create a Dhall demo to gather customer feedback](https://github.com/orgs/sourcegraph/projects/71)

We would like to create a demo that we can share with customers and gather feedback about our proposed solution.

- @ggilmore 
- @uwedeportivo 

#### [Releases are created in a single day](https://github.com/orgs/sourcegraph/projects/90)

We have a goal of reducing the time it takes to create releases, and this current several-day system has encouraged us to view releases as “baked” rather than “snapshots of the main branch”, leading to situations where main is broken and we have to retrospectively fix it or adding last minute features.

- @davejrt 
- @bobheadxi 
- @pecigonzalo 

### Availability

Period is from **October 20th** to **November 2nd (10 working days)**. Please write the days you won't be working and the number of working days for the period.

- @uwedeportivo (5d, date TBD)

### Tracked issues

@bobheadxi: __7.00d__

- [ ] ~deploy-sourcegraph: mark automated PR failures as release-blockers~ ([#14622](https://github.com/sourcegraph/sourcegraph/issues/14622)) __0.50d__
- [ ] ~qa: automated sourcegraph/server upgrade test~ ([#13877](https://github.com/sourcegraph/sourcegraph/issues/13877)) __3.00d__
- [ ] ~set up automerge for third-party license updates~ ([#14766](https://github.com/sourcegraph/sourcegraph/issues/14766)) __0.50d__ 🎩

Completed: __3.00d__
- [x] (🏁 12 days ago) yarn release publish does not behave as expected ([~#14925~](https://github.com/sourcegraph/sourcegraph/issues/14925)) 🐛
- [x] (🏁 9 days ago) release: releases steps should happen as fast as possible ([~#14911~](https://github.com/sourcegraph/sourcegraph/issues/14911)) __0.50d__
- [x] (🏁 8 days ago) release: generated tracking issue has incorrect dates when run from non-PST time zone ([~#14626~](https://github.com/sourcegraph/sourcegraph/issues/14626)) __0.50d__ 🐛
- [x] (🏁 5 days ago) release: explore using campaigns to manage release PRs ([~#14971~](https://github.com/sourcegraph/sourcegraph/issues/14971)) __1.00d__ 🎩
- [x] (🏁 4 days ago) release: announce that a release is out ([~#14912~](https://github.com/sourcegraph/sourcegraph/issues/14912)) __0.50d__
- [x] (🏁 4 days ago) Walk Robert and Dax through managed instance upgrade process ([~#14998~](https://github.com/sourcegraph/sourcegraph/issues/14998))
- [x] (🏁 3 days ago) sourcegraph/customer ([~#97~](https://github.com/sourcegraph/customer/issues/97)) __0.50d__ 👩

@davejrt

- [ ] sourcegraph/customer ([#111](https://github.com/sourcegraph/customer/issues/111)) 👩

Completed
- [x] (🏁 130 days ago) Bigdata customer Tracking issue ([~#11717~](https://github.com/sourcegraph/sourcegraph/issues/11717))
- [x] (🏁 5 days ago) sourcegraph/customer ([~#122~](https://github.com/sourcegraph/customer/issues/122)) 👩
- [x] (🏁 5 days ago) sourcegraph/customer ([~#115~](https://github.com/sourcegraph/customer/issues/115)) 👩
- [x] (🏁 4 days ago) blackbox exporter & site 24/7 next steps ([~#13627~](https://github.com/sourcegraph/sourcegraph/issues/13627)) 🧶
- [x] (🏁 3 days ago) Run QA tests on bare-metal Buildkite agents on every commit to master (non-blocking) ([~#12340~](https://github.com/sourcegraph/sourcegraph/issues/12340))

@daxmc99: __4.00d__

- [ ] ~Automate Kubernetes cluster QA tests~ ([#13878](https://github.com/sourcegraph/sourcegraph/issues/13878)) __4.00d__

Completed
- [x] (🏁 13 days ago) Add PG_HERO for Cloud SQL ([~#14865~](https://github.com/sourcegraph/sourcegraph/issues/14865))
- [x] (🏁 7 days ago) RFC 174: HA Postgres for Sourcegraph Cloud ([~#11496~](https://github.com/sourcegraph/sourcegraph/issues/11496))
- [x] (🏁 4 days ago) Walk Robert and Dax through managed instance upgrade process ([~#14998~](https://github.com/sourcegraph/sourcegraph/issues/14998))

@efritz

- [ ] docs: Update pure-docker upgrading docs for 3.21 ([#14671](https://github.com/sourcegraph/sourcegraph/pull/14671)) :shipit:

@ggilmore: __5.00d__

- [ ] ~Create customer demo video for dhall direction~ ([#14646](https://github.com/sourcegraph/sourcegraph/issues/14646)) __5.00d__
- [ ] ~ci: build and pin tool apks in CI for release~ ([#13297](https://github.com/sourcegraph/sourcegraph/issues/13297)) 🧶

Completed
- [x] (🏁 4 days ago) sourcegraph/customer ([~#74~](https://github.com/sourcegraph/customer/issues/74)) 👩

@pecigonzalo: __1.00d__

Completed: __1.00d__
- [x] (🏁 5 days ago) Cancelled jobs in buildkite leave vagrant boxes running ([~#14582~](https://github.com/sourcegraph/sourcegraph/issues/14582)) __1.00d__
- [x] (🏁 4 days ago) blackbox exporter & site 24/7 next steps ([~#13627~](https://github.com/sourcegraph/sourcegraph/issues/13627)) 🧶

@slimsag: __0.50d__

- [ ] ~sourcegraph/customer~ ([#119](https://github.com/sourcegraph/customer/issues/119)) 👩

Completed: __0.50d__
- [x] (🏁 7 days ago) Solidify plan for Stephen ownership handoff ([~#14864~](https://github.com/sourcegraph/sourcegraph/issues/14864))
- [x] (🏁 6 days ago) sourcegraph/customer ([~#84~](https://github.com/sourcegraph/customer/issues/84)) 👩
- [x] (🏁 5 days ago) sourcegraph/customer ([~#122~](https://github.com/sourcegraph/customer/issues/122)) 👩
- [x] (🏁 5 days ago) sourcegraph/customer ([~#120~](https://github.com/sourcegraph/customer/issues/120)) 👩
- [x] (🏁 4 days ago) sourcegraph/customer ([~#103~](https://github.com/sourcegraph/customer/issues/103)) 👩
- [x] (🏁 4 days ago) Walk Robert and Dax through managed instance upgrade process ([~#14998~](https://github.com/sourcegraph/sourcegraph/issues/14998))
- [x] (🏁 4 days ago) sourcegraph/customer ([~#74~](https://github.com/sourcegraph/customer/issues/74)) 👩
- [x] (🏁 today) update 1password QA test env vars ([~#14875~](https://github.com/sourcegraph/sourcegraph/issues/14875)) __0.50d__

@uwedeportivo: __5.00d__

- [ ] ~Create customer demo video for dhall direction~ ([#14646](https://github.com/sourcegraph/sourcegraph/issues/14646)) __5.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ Roadmap
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by daxmc99** [comment]
**This week**:
- Finish up remaining Cloud SQL issues and sunset Postgres deployment. 
- Added Postgres users for every deployment
- Discussed [Deployment UX](https://docs.google.com/document/d/1WiY4fPNp28OqCQv21vb_khcqVMmo6wMSb_ZOOZjmc6M/edit)

**Next week**:
- Create RFC to faciliate input on each team using a seperate Postgres user for better observability
- Sync with Dave & Robert for design of e2e pipeline for automating cluster QA as part of releases for https://github.com/sourcegraph/sourcegraph/issues/13878 
- Continue Deployment UX pipeline discussion

**Comment by ggilmore** [comment]
This week: 

- Retrospective
- Deployment Discussion
- Prepared all prerequisite materials for recording the customer demo. 

Next week: 
- Monday: record the demo and share with distribution for feedback
- Get back to https://github.com/sourcegraph/sourcegraph/issues/13340

**Comment by bobheadxi** [comment]
**Last week**

Some handbook updates (deployments, prometheus), improvements to alert solutions documentation rendering. Made more improvements to releases: reduced timeline, date formatting, etc. Took a stab at continuous sourcegraph upgrade tests (https://github.com/sourcegraph/sourcegraph/pull/14974) and using campaigns in releases (https://github.com/sourcegraph/about/pull/1838)

**This week**

Continue working on https://github.com/sourcegraph/sourcegraph/pull/14974 and land https://github.com/sourcegraph/about/pull/1838 . Turns out the automerge for license updates isn't working out - gonna circle back to that and see if that's easy to fix: https://github.com/sourcegraph/sourcegraph/issues/14766#issuecomment-716486279

**Comment by pecigonzalo** [comment]
**Last week**

I have cleanup unused AWS resources and reviewed a couple of RFCs (RFC-249, RFC 245) and PRs. I have also been working with CE on the support pipeline.

**This week**

Im working on https://github.com/sourcegraph/sourcegraph/issues/13627 porting the checks to blackbox-exporter and merging the [improved deployment pipeline](https://github.com/sourcegraph/about/pull/1787) goal and planning the next sprint.

**Comment by davejrt** [comment]
**Last Week**

A lot of focus and firefighting with the release. Getting this into the hands of capital one and helping them with a small hiccup due to not following the upgrade path. 

Closing out sourcegraph/sourcegraph#12340 and breaking that down into smaller issues for each failing component, however the infrastructure in place can now be used more generically for other tests

**This week** 

Continue work on the failing regression/qa tests as well as help Robert and Dax with their efforts to test upgrades and k8s deployments.

**Comment by slimsag** [comment]
**This week**

Pushed through as much hand-off as I can, mostly spent time documenting things and walking others through various processes. Up-to-date project board with where I am at [here](https://github.com/orgs/sourcegraph/projects/105#card-47913318).

**Next week**

I expect to finish all hand-off tasks I have and close out that project before heading out to go on vacation for two weeks. Aiming to set myself up with as clean a slate as possible for when I return. I also hope to start work on my first [high-impact, low-cost win](https://github.com/orgs/sourcegraph/projects/106#card-48292576) by starting to investigate reducing the time it takes to loadd/display search results.

**Comment by ggilmore** [comment]
This week: 

I spent most of my time debugging https://github.com/sourcegraph/customer/issues/74. I also release a rough draft of the Dhall demo video (https://github.com/sourcegraph/sourcegraph/issues/14646) for @sourcegraph/distribution to review in https://sourcegraph.slack.com/archives/CJX299FGE/p1604110703335500. 

Next week: 

I will respond to feedback on the rough draft Dhall video that I shared, and I aim to restart work on https://github.com/sourcegraph/sourcegraph/issues/13340

**Comment by bobheadxi** [comment]
**This week**

Finalized and landed campaigns in releases and "closing" a release. Performed some instance upgrades for $CUSTOMER, made some progress on sourcegraph/server upgrade tests, made handbook updates for releases and managed instances. Opened a PR cleaning up how versions are configured in the release tooling (https://github.com/sourcegraph/about/pull/1880).

**Next week**

Plan issues for [11.03 work (release tooling + k8s.sgdev marketing)](https://github.com/sourcegraph/sourcegraph/issues/14630). Try to wrap up issues kicked from this sprint to 11.03 (sourcegraph/server upgrade tests, automerge).

**Comment by daxmc99** [comment]
**This week** 
Stephen guided Robert and me through a managed instance upgrade process. 
Performed some debugging of our services in production to determine the root-cause of our `repo-updater` service failing to start ([link](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1603922480483500). Investigated performing automated QA tests on our K8s cluster, similar to how we perform e2e & regression tests on our server and docker-compose deployments. 

**Next Week** 
Perform several managed instance upgrades. Begin running QA tests on `sourcegraph/sourcegraph` targetting K8s. Complete some small innovation tasks around using containerd images on our production clusters and evaluating ArgoCD & Flux as part of the Improve deployment pipeline UX distribution team [goal](https://about.sourcegraph.com/handbook/engineering/distribution/goals#medium-term-goals-3-6-months).

**Comment by pecigonzalo** [comment]
**Last week**
I merged the port of the site24x7 metrics to blackbox-exporter and was able to merge the Pipeline UX goal, but I forgot to add a problem statement. I have sent a new PR to add one. I have also had a meeting with CE to sync on how to handle CE <-> Eng workflow going forward and as we scale.
I also did a bit cleanup, removing the old `ops_team` OpsGenie group.

**This week**
The focus this week is to update our team goals and roadmap, referencing the items that are still relevant from https://github.com/sourcegraph/about/pull/1104. Similarly I will get started on a draft around team growth ideas, where we want to be in the future, what is working, what is not, and the steps we need to take to get there.
