### ISSUE TITLE
Campaigns Sprint 2 Tracking issue

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#14419]
### Plan

The main theme of this sprint is a continuation from our last sprint: quality of life improvements for our users. We need to make campaigns easier to use in everyday situations in order to get more people using campaigns. This includes easier debugging, better docs, and bug fixing.

We also have a couple of larger items: allowing users to use their own code host tokens, and enabling campaigns to create draft PRs.

### Availability

Period is from Oct 7 to Oct 20, for 10 working days in total.

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

@chrispine 0d
@mrnugget 0d
@eseliger 0d
@LawnGnome 1d (:canada: Thanksgiving October 12)

### Tracked issues

@unassigned

Completed
- [x] (🏁 1 day ago) Campaigns beta message box has a white background in dark mode ([~#14450~](https://github.com/sourcegraph/sourcegraph/issues/14450)) 🐛

@LawnGnome: __0.50d__

Completed: __0.50d__
- [x] (🏁 7 days ago) Campaigns preview icons improvements ([~#14426~](https://github.com/sourcegraph/sourcegraph/issues/14426))
- [x] (🏁 1 day ago) campaigns: move `unmarshalValidate`, with its yaml/json stuff, into `cschema` ([~#14249~](https://github.com/sourcegraph/sourcegraph/issues/14249)) __0.50d__
- [x] (🏁 today) campaigns: add new icon ([~#14740~](https://github.com/sourcegraph/sourcegraph/pull/14740)) :shipit:

@chrispine: __4.00d__

Completed: __4.00d__
- [x] (🏁 8 days ago) campaigns: large changesets can result in 413 errors ([~#12840~](https://github.com/sourcegraph/sourcegraph/issues/12840)) __1.00d__ 🐛
- [x] (🏁 7 days ago) CampaignSpecFields should include the importChangesets field ([~#13009~](https://github.com/sourcegraph/sourcegraph/issues/13009)) __1.00d__
- [x] (🏁 2 days ago) Changeset diff render can fail when gitserver hasn't synced yet ([~#12584~](https://github.com/sourcegraph/sourcegraph/issues/12584)) __2.00d__

@eseliger: __4.00d__

Completed: __4.00d__
- [x] (🏁 8 days ago) Burndown chart is off by one ([~#11744~](https://github.com/sourcegraph/sourcegraph/issues/11744); PRs: ~[#14525](https://github.com/sourcegraph/sourcegraph/pull/14525)~) __1.00d__ 🐛
- [x] (🏁 7 days ago) Add notice on how to publish remaining changesets ([~#14698~](https://github.com/sourcegraph/sourcegraph/pull/14698)) :shipit:
- [x] (🏁 7 days ago) Only take reconciled changesets into consideration when calculating events ([~#14521~](https://github.com/sourcegraph/sourcegraph/pull/14521)) :shipit:🐛
- [x] (🏁 7 days ago) Develop responsive campaign pages ([~#13118~](https://github.com/sourcegraph/sourcegraph/issues/13118)) __3.00d__
- [x] (🏁 5 days ago) Draft mode syntax support ([~#14699~](https://github.com/sourcegraph/sourcegraph/pull/14699)) :shipit:
- [x] (🏁 1 day ago) Implement UI display and burndown chart calculation for GitHub draft mode ([~#14742~](https://github.com/sourcegraph/sourcegraph/pull/14742)) :shipit:
- [x] (🏁 1 day ago) Add support for GitHub review webhooks ([~#14862~](https://github.com/sourcegraph/sourcegraph/pull/14862)) :shipit:
- [x] (🏁 today) Add support for draft changesets in reconciler ([~#14807~](https://github.com/sourcegraph/sourcegraph/pull/14807)) :shipit:

@mrnugget: __8.50d__

Completed: __8.50d__
- [x] (🏁 9 days ago) Create a `src campaign new` command that creates a campaign spec ([~#14449~](https://github.com/sourcegraph/sourcegraph/issues/14449)) __1.00d__
- [x] (🏁 9 days ago) Write a step-by-step guide on how to create a new campaign ([~#14448~](https://github.com/sourcegraph/sourcegraph/issues/14448)) __2.00d__
- [x] (🏁 9 days ago) Get rid of wall of text in campaign docs ([~#14529~](https://github.com/sourcegraph/sourcegraph/issues/14529)) __1.50d__
- [x] (🏁 9 days ago) src-cli should warn if a campaign results in zero changesets ([~#14531~](https://github.com/sourcegraph/sourcegraph/issues/14531)) __0.50d__
- [x] (🏁 9 days ago) src-cli progress bar prints empty status bars when repositories cannot be resolved ([~#14559~](https://github.com/sourcegraph/sourcegraph/issues/14559)) __0.50d__ 🐛
- [x] (🏁 2 days ago) Prototype accessing modified files/search results in campaign spec run commands ([~#14445~](https://github.com/sourcegraph/sourcegraph/issues/14445)) __2.00d__
- [x] (🏁 2 days ago) Improve the debugging experience when running campaigns with src-cli ([~#13861~](https://github.com/sourcegraph/sourcegraph/issues/13861)) __1.00d__

@rrhyne: __1.00d__

Completed: __1.00d__
- [x] (🏁 7 days ago) Campaigns preview icons improvements ([~#14426~](https://github.com/sourcegraph/sourcegraph/issues/14426))
- [x] (🏁 today) Design responsive screens for campaigns pages ([~#13117~](https://github.com/sourcegraph/sourcegraph/issues/13117)) __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by LawnGnome** [comment]
#### Weekly⁰ update: 2020-09-28 to 2020-10-05

Last week, [partial publishing support landed!](https://twitter.com/sqs/status/1311882431155195904) I also got started on [implementing user token support](https://github.com/sourcegraph/sourcegraph/issues/13862): the initial bits are in place, but there's lots more plumbing to do before that's done.

This week, I'll be working on (and hopefully finishing) user token support, and drafting an RFC for src-cli versioning.

⁰ For a slightly larger definition of "week" than normal, since we're transitioning to Tuesday updates.

**Comment by eseliger** [comment]
#### Weekly update: 2020-09-28 to 2020-10-05

Last week, I spent some time in hack sessions and interviews. In the time between those, I've spent most of my time focussing on responsive campaigns layouts. That was quite a task and I felt like making progress just very slowly. When something would work on all our 4 predefined viewports, the code usually ended up being quite nasty and I didn't feel very well about that, so I spent a lot of time finding good solutions that would not bloat the code unnecessarily just for layout purposes. I'm currently finishing off this effort.
This week, I'll be finishing the responsive designs. After that, I'll work on planning for my big ticket for this iteration: Publishing changesets as draft {PR,MR}s on GitHub and GitLab. 
I also have one bug ticket assigned that I might prioritize over the planning work, so it could end up in the release. I don't think it's necessary but when we have the luxurious situation of being able to choose execution order freely, I'd probably rather do that first, if a somewhat easy solution is feasible.

**Comment by eseliger** [comment]
#### Weekly update: 2020-10-05 to 2020-10-09

Last week, I finished up responsive designs for approval. Also hacked on the iconography for changeset spec actions. After that, I focussed on pagination for GitHub PR timeline events to fix a bug ticket, and wrote my implementation plan for draft PRs and executed the first step, making overridable take BoolOrString for the triple.
This week, I will continue work on the draft PR ticket, which will probably take most of the time this week, and have two smaller design things that we might want to squeeze into the release. Also a hack session on a short spike using Firecracker for src cli.

**Comment by LawnGnome** [comment]
#### Weekly update: 2020-10-06 to 2020-10-12

Last week, I focused on allowing users to use their own tokens when reconciling campaigns. This turned out to be quite the rabbit hole! The main challenge here is that this overlaps with other things we already have in the Sourcegraph codebase: users can use their code host as an authentication provider, which gives us one potential source of user tokens, and there was overlapping work to allow users to add their own code hosts that is also relevant for campaigns. Both of these have nascent (and experiemental) UIs to administer those connections, neither of which quite do what we actually need.

I've implemented a prototype that currently ignores all of that work and adds a new table for campaign user tokens and uses that to communicate with the code hosts. It works, but I'm concerned about the product direction here: adding a third potential source of tokens to the existing two (ish) feels icky, and there's a bunch of UI that has to be built to enable this, but it also feels difficult to reconcile what we have with what campaigns needs here.

Honestly, it wasn't a very fun week.

This week, I'll be soliciting more feedback on this issue and our user token direction, for real drafting the src-cli versioning RFC, and performing some tasks we need to have done before branch cut tomorrow (as I write this), such as updating our preview UI icons and styling to match Rob's excellent new mockups, and releasing src-cli.
