### ISSUE TITLE
Distribution: 2020.11.03 - Amazing Otter

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#14630]
#### [Support new and existing deployments](https://github.com/orgs/sourcegraph/projects/74)

This is an ongoing expense, we anticipate this taking no more than 5d of work spread across the entire team.

#### [Releases are created in a single day](https://github.com/orgs/sourcegraph/projects/90)

We have a goal of reducing the time it takes to create releases, and this current several-day system has encouraged us to view releases as “baked” rather than “snapshots of the main branch”, leading to situations where main is broken and we have to retrospectively fix it or adding last minute features.

- @davejrt 
- @bobheadxi 
- @daxmc99 

#### [Market k8s.sgdev.org internally](https://github.com/orgs/sourcegraph/projects/107)

Make k8s.sgdev.org a compelling destination for Sourcegraph engineers to encourage dogfood. Changes should mostly be surface-level improvements.

- @bobheadxi 
- @davejrt 
- @pecigonzalo 

#### [Implement 2+ sourcegraph.com services using dhall](https://github.com/orgs/sourcegraph/projects/71)

`sourcegraph.com` sees the highest amount of Kubernetes changes out of all of our deployments + `deploy-sourcegraph`. Scoping a single component limits the customizations that we need to implement and allows for easier onboarding other engineers.

- @ggilmore 
- @uwedeportivo

### Availability

Period is from **November 3rd** to **November 14th (9 working days)**. Please write the days you won't be working and the number of working days for the period. _This is a shorter iteration to align sprints with weeks_.

- **Dave (1d, Nov 1)**

### Tracked issues

@unassigned: __1.00d__

Completed: __1.00d__
- [x] (🏁 9 days ago) release(patch): investigate better process for tracking commits that must go in a patch ([~#15294~](https://github.com/sourcegraph/sourcegraph/issues/15294)) __1.00d__

@bobheadxi: __8.50d__

- [ ] set up automerge for third-party license updates ([#14766](https://github.com/sourcegraph/sourcegraph/issues/14766)) __0.50d__ 🎩
- [ ] upgrade devmanaged.sourcegraph.com to v3.20, v3.21 ([#15173](https://github.com/sourcegraph/sourcegraph/issues/15173)) __0.50d__
- [ ] ~k8s.sgdev: update handbook guidance for k8s.sgdev~ ([#15511](https://github.com/sourcegraph/sourcegraph/issues/15511)) __0.50d__

Completed: __7.00d__
- [x] (🏁 10 days ago) k8s.sgdev: add banners to internal instances indicating that Sourcegraphers should use k8s.sgdev.org ([~#15509~](https://github.com/sourcegraph/sourcegraph/issues/15509))
- [x] (🏁 10 days ago) release: create stub PRs for deploy-sourcegraph-docker, kubernetes upgrade ([~#15074~](https://github.com/sourcegraph/sourcegraph/issues/15074)) __1.00d__
- [x] (🏁 9 days ago) release: add deploy-sourcegraph-docker docs updates to release tool ([~#15325~](https://github.com/sourcegraph/sourcegraph/issues/15325)) __0.50d__
- [x] (🏁 6 days ago) release(patch): align patch steps with release tooling ([~#15293~](https://github.com/sourcegraph/sourcegraph/issues/15293)) __1.00d__
- [x] (🏁 5 days ago) monitoring: reduce threshold of low-utilization alerts ([~#14504~](https://github.com/sourcegraph/sourcegraph/issues/14504))
- [x] (🏁 5 days ago) qa: automated sourcegraph/server upgrade test ([~#13877~](https://github.com/sourcegraph/sourcegraph/issues/13877)) __3.00d__
- [x] (🏁 3 days ago) sourcegraph/customer ([~#135~](https://github.com/sourcegraph/customer/issues/135)) __0.50d__ 👩
- [x] (🏁 2 days ago) release: do not require a rebuild on configuration changes ([~#15562~](https://github.com/sourcegraph/sourcegraph/issues/15562)) __0.50d__ 🎩
- [x] (🏁 2 days ago) release: create tags in deploy-sourcegraph-* repositories ([~#15323~](https://github.com/sourcegraph/sourcegraph/issues/15323)) __0.50d__

@davejrt: __5.50d__

- [ ] qa: codeintel tests failing on first run ([#15165](https://github.com/sourcegraph/sourcegraph/issues/15165)) __0.50d__
- [ ] qa: onboarding tests require manual validation ([#15179](https://github.com/sourcegraph/sourcegraph/issues/15179)) __1.00d__
- [ ] qa: search qa tests failing in CI ([#15178](https://github.com/sourcegraph/sourcegraph/issues/15178)) __0.50d__
- [ ] qa: testing external-services fails in CI ([#15193](https://github.com/sourcegraph/sourcegraph/issues/15193)) __0.50d__
- [ ] qa: auth regression tests are failing ([#15180](https://github.com/sourcegraph/sourcegraph/issues/15180)) __1.50d__
- [ ] go binary to create sudo token should be more generic ([#15197](https://github.com/sourcegraph/sourcegraph/issues/15197)) __0.50d__ 🧶
- [ ] sourcegraph/customer ([#129](https://github.com/sourcegraph/customer/issues/129)) 👩

Completed: __1.00d__
- [x] (🏁 143 days ago) Bigdata customer Tracking issue ([~#11717~](https://github.com/sourcegraph/sourcegraph/issues/11717))
- [x] (🏁 11 days ago) sourcegraph/customer ([~#121~](https://github.com/sourcegraph/customer/issues/121)) 👩
- [x] (🏁 5 days ago) qa: core test failing ([~#15164~](https://github.com/sourcegraph/sourcegraph/issues/15164)) __0.50d__
- [x] (🏁 2 days ago) qa: configsettings hangs at end of test ([~#15167~](https://github.com/sourcegraph/sourcegraph/issues/15167)) __0.50d__

@daxmc99: __8.00d__

- [ ] Automate Kubernetes cluster QA tests ([#13878](https://github.com/sourcegraph/sourcegraph/issues/13878)) __4.00d__
- [ ] ~Evaluate ArgoCD or Flux for a Deployment UX~ ([#15198](https://github.com/sourcegraph/sourcegraph/issues/15198)) __2.00d__ 🕵️
- [ ] ~Use containerd images on clusters~ ([#15194](https://github.com/sourcegraph/sourcegraph/issues/15194)) __0.50d__ 🕵️
- [ ] ~Add Postgres dashboards with alerting~ ([#15029](https://github.com/sourcegraph/sourcegraph/issues/15029)) __1.00d__

Completed: __0.50d__
- [x] (🏁 11 days ago) sourcegraph/customer ([~#127~](https://github.com/sourcegraph/customer/issues/127)) __0.50d__ 👩
- [x] (🏁 4 days ago) Clarify steps needed for Cloud SQL ([~#1928~](https://github.com/sourcegraph/about/pull/1928)) :shipit:

@efritz

Completed
- [x] (🏁 2 days ago) ~docs: Update pure-docker upgrading docs for 3.21~ ([~#14671~](https://github.com/sourcegraph/sourcegraph/pull/14671)) :shipit:

@ggilmore: __5.00d__

Completed: __5.00d__
- [x] (🏁 3 days ago) Create customer demo video for dhall direction ([~#14646~](https://github.com/sourcegraph/sourcegraph/issues/14646)) __5.00d__

@pecigonzalo: __4.00d__

- [ ] ~k8s.sgdev: set up LSIF uploads for Sourcegraph repositories~ ([#15510](https://github.com/sourcegraph/sourcegraph/issues/15510)) __1.00d__
- [ ] ~Get approval on "RFC 263: Single-container deployments are for demos only"~ ([#15484](https://github.com/sourcegraph/sourcegraph/issues/15484))

Completed: __3.00d__
- [x] (🏁 9 days ago) Update Distribution team recurring processes ([~#1942~](https://github.com/sourcegraph/about/pull/1942)) :shipit:
- [x] (🏁 9 days ago) Add names to pipeline step labels ([~#15354~](https://github.com/sourcegraph/sourcegraph/pull/15354)) :shipit:🎩
- [x] (🏁 4 days ago) sourcegraph/customer ([~#136~](https://github.com/sourcegraph/customer/issues/136)) [👩](https://app.hubspot.com/contacts/2762526/company/887065580)
- [x] (🏁 3 days ago) CORS Proxy with allowlist support ([~#15582~](https://github.com/sourcegraph/sourcegraph/issues/15582)) __3.00d__

@slimsag

- [ ] ~Get approval on "RFC 263: Single-container deployments are for demos only"~ ([#15484](https://github.com/sourcegraph/sourcegraph/issues/15484))

Completed
- [x] (🏁 12 days ago) sourcegraph/customer ([~#83~](https://github.com/sourcegraph/customer/issues/83)) 👩
- [x] (🏁 11 days ago) Determine next steps on RFC 230 and 232 ([~#14997~](https://github.com/sourcegraph/sourcegraph/issues/14997))
- [x] (🏁 11 days ago) create upgrade schedule ([~#15174~](https://github.com/sourcegraph/sourcegraph/issues/15174))
- [x] (🏁 11 days ago) sourcegraph/customer ([~#123~](https://github.com/sourcegraph/customer/issues/123)) 👩
- [x] (🏁 11 days ago) sourcegraph/customer ([~#121~](https://github.com/sourcegraph/customer/issues/121)) 👩
- [x] (🏁 10 days ago) Experiment: Stephen becomes internal contributor, focusing on high-impact low-cost wins ([~#1754~](https://github.com/sourcegraph/about/pull/1754)) :shipit:
- [x] (🏁 10 days ago) link my “deployment - a crash course in Sourcegraph” slides in the handbook ([~#14999~](https://github.com/sourcegraph/sourcegraph/issues/14999))
- [x] (🏁 9 days ago) sourcegraph/customer ([~#71~](https://github.com/sourcegraph/customer/issues/71)) 👩
- [x] (🏁 9 days ago) Stephen: Re-review Distribution team goals / roadmap ([~#14996~](https://github.com/sourcegraph/sourcegraph/issues/14996))

@uwedeportivo: __9.00d__

- [ ] ~add gitserver to deploy-sourcegraph-dhall, with support for sourcegraph.com customizations~ ([#14131](https://github.com/sourcegraph/sourcegraph/issues/14131)) __4.00d__

Completed: __5.00d__
- [x] (🏁 11 days ago) sourcegraph/customer ([~#123~](https://github.com/sourcegraph/customer/issues/123)) 👩
- [x] (🏁 11 days ago) sourcegraph/customer ([~#121~](https://github.com/sourcegraph/customer/issues/121)) 👩
- [x] (🏁 3 days ago) Create customer demo video for dhall direction ([~#14646~](https://github.com/sourcegraph/sourcegraph/issues/14646)) __5.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by slimsag** [comment]
**This week**:

I have fully completed all of my planned handover tasks in https://github.com/orgs/sourcegraph/projects/105#card-47913307 and closed the project. There remains a few items, which I cannot make further progress on until a later date (e.g. until Customer Engineers onboard further, until people have had a chance to review PRs or RFCs I sent, etc.) and I am sure there will continue to be some hand-off tasks I need to perform well into the future. - however, I am calling it "done" here and..

**Next week**:

I am officially kicking off my new [high-impact, low-cost work](https://github.com/orgs/sourcegraph/projects/106) Mon and Tue, then going on vacation starting Wed and starting on that with a clean slate when I return!

**Comment by uwedeportivo** [comment]
this week:

caught up on things after vacation. finished gitserver component for the dhall project. finished the netflix 3.21 upgrade

next week:

continue the march, get on to the next components. should be quicker now that i sorted out what is shared. now it's more or less cookie-cutter

**Comment by bobheadxi** [comment]
**last week**

Landed more release tooling changes: unifying how versions are configured, including `deploy-sourcegraph-docker` in automated PR creation, automating the creation of stub upgrade entries. Currently ready for review: https://github.com/sourcegraph/sourcegraph/pull/15548 which brings better compatibility with patch releases so the tool can be used there as well, and improving the format of generated PRs. Also ready for review: sourcegraph server upgrade tests (https://github.com/sourcegraph/sourcegraph/pull/14974), which also includes improvements to QA tests in general (deterministic builds using specific candidate images, improving script reuse, etc)

**this week**

Land aforementioned PRs, and start working towards the remainder of my assigned issues this sprint. There are some unassigned issues that I should probably figure out if I have the bandwidth for (might, if the above PRs don't require too much extra work) or if someone else might be able to tackle them

**Comment by davejrt** [comment]
**last week**
Landed a number of PR's to get QA testing into `main` and working on `sourcegraph/sourcegraph` inc. #15191 #15535 and the largest would be #15493. The latter being the most significant because this is the first time another team has approached us to ask for something to be run on the vagrant based tests. I think this is a big win for us as it builds more confidence in our test infra and of course...more tests are good. 

**this week** 
Continuing to close out the rest of the [issues](https://github.com/issues?q=is%3Aopen+is%3Aissue+author%3Adavejrt+archived%3Afalse+label%3Adistribution-e2e-frequency) related to tests QA tests failing with the help of others teams in time for the next release. 

I'll also be attending gophercon sessions throughout the week. 

There is also an a customer support issue open here which if they get back to me after my email last week, may take up more time. https://github.com/sourcegraph/customer/issues/129

**Comment by pecigonzalo** [comment]
**Last week**
Last week was mostly meetings and chatting about different topics, I had a number of topics to follow up on (Cloudflare WAF, CORS Anywhere, Dhall demo videos, RFC-263).
I also merged the vagrant-buildkite-plugin "v0" to start testing it and as a buildkite-plugin example.

We also merged a number of changes and updates to our team recurrent meetings and workflows.

**This week**
This week I have GopherCon, so I believe ill be mostly busy with that. I would also like to provide an interim solution to the Web team restoring some of the CORS proxy functionality they had before, as this is currently blocking them.

**Comment by daxmc99** [comment]
**Last Week**

Opened https://github.com/sourcegraph/sourcegraph/pull/15486 to move to the official `k8s-client` for the cluster QA tests. 
Upgraded the sourcegraph demo instance 

Reviewed:
 https://github.com/sourcegraph/sourcegraph/pull/15512
 [RFC 263](https://docs.google.com/document/d/1GPypas4ZUZIw346EcNDM1up2OOQFyPpEzA3-0glPEMY/edit#)


**This Week**
Finish up the K8s buildkite pipeline. 
Begin innovation tasks
