### ISSUE TITLE
Cloud 2020-10-21 Tracking issue

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#14763]
### Plan

1. Cloud: @ryanslade and @quinnkeast will be working on an RFC to define information architecture and implementation plan to support private code owned by users and orgs. Additionally, we'll implement a work-around to allow us to dogfood user added repos easily (i.e. a dynamic "my" repos repogroup).

1. RFC 167 — Product license tiers: We didn't finish this last cycle, so @flying-robot and @unknwon will wrap this up first before focusing on auth work.

1. Auth: A lot of loose ends, chores, small bugs and quality of life improvements that have been stacking for a while. @unknwon and @flying-robot are working on this after RFC 167.

1. Tech debt: @asdine is concluding migrating the repo-updater `Store` to use the shared `basestore` package and other simplifications that were identified throughout the course of the recent work in that area.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

- @asdine: November 29 and 30 (2d)

### Tracked issues

@unassigned: __1.00d__

- [ ] sourcegraph/customer ([#117](https://github.com/sourcegraph/customer/issues/117); PRs: ~[#14983](https://github.com/sourcegraph/sourcegraph/pull/14983)~) 👩

Completed: __1.00d__
- [x] (🏁 8 days ago) Add an index to the repository creation timestamp ([~#14796~](https://github.com/sourcegraph/sourcegraph/issues/14796)) __0.50d__
- [x] (🏁 8 days ago) Be more graceful in handling a missing private key when generating licenses ([~#14908~](https://github.com/sourcegraph/sourcegraph/issues/14908)) __0.50d__

@artemruts: __1.50d__

- [ ] Impossible to copy errors out of code host status indicator ([#14643](https://github.com/sourcegraph/sourcegraph/issues/14643); PRs: [#15290](https://github.com/sourcegraph/sourcegraph/pull/15290)) 🐛
- [ ] ~Make password reset link duration configurable by site admins~ ([#13999](https://github.com/sourcegraph/sourcegraph/issues/13999)) __1.00d__ 🔒

Completed: __0.50d__
- [x] (🏁 today) Deploy to a cluster link in search performance warning notice is relative, not absolute ([~#13745~](https://github.com/sourcegraph/sourcegraph/issues/13745)) __0.50d__ 🐛

@arussellsaw: __1.00d__

Completed: __1.00d__
- [x] (🏁 today) Account update email should mention the instance URL ([~#14751~](https://github.com/sourcegraph/sourcegraph/issues/14751)) __1.00d__ 🐛

@asdine: __3.50d__

- [ ] Replace calls to repo-updater store ([#15082](https://github.com/sourcegraph/sourcegraph/pull/15082)) :shipit:

Completed: __3.50d__
- [x] (🏁 13 days ago) SetClonedRepos takes forever on Cloud ([~#14938~](https://github.com/sourcegraph/sourcegraph/issues/14938); PRs: ~[#14944](https://github.com/sourcegraph/sourcegraph/pull/14944)~) 🐛
- [x] (🏁 12 days ago) Simpler SetClonedRepos query ([~#14981~](https://github.com/sourcegraph/sourcegraph/pull/14981)) :shipit:
- [x] (🏁 6 days ago) repo-store: Convert the repos store to use basestore ([~#14754~](https://github.com/sourcegraph/sourcegraph/issues/14754); PRs: ~[#15051](https://github.com/sourcegraph/sourcegraph/pull/15051)~) __2.00d__ 🧶
- [x] (🏁 6 days ago) repo-store: Add Create method ([~#14708~](https://github.com/sourcegraph/sourcegraph/issues/14708); PRs: ~[#15081](https://github.com/sourcegraph/sourcegraph/pull/15081)~) __0.50d__ 🧶
- [x] (🏁 1 day ago) external service store:  Add an Upsert method ([~#14713~](https://github.com/sourcegraph/sourcegraph/issues/14713); PRs: ~[#15104](https://github.com/sourcegraph/sourcegraph/pull/15104)~) __1.00d__ 🧶

@flying-robot: __7.00d__

- [ ] RFC 167: Enforce campaigns ([#14029](https://github.com/sourcegraph/sourcegraph/issues/14029); PRs: [#15068](https://github.com/sourcegraph/sourcegraph/pull/15068)) __1.00d__
- [ ] Permissions Grafana alert should not include public repos ([#14894](https://github.com/sourcegraph/sourcegraph/issues/14894)) __1.00d__
- [ ] ~Make password reset link duration configurable by site admins~ ([#13999](https://github.com/sourcegraph/sourcegraph/issues/13999)) __1.00d__ 🔒

Completed: __4.00d__
- [x] (🏁 130 days ago) Bigdata customer Tracking issue ([~#11717~](https://github.com/sourcegraph/sourcegraph/issues/11717))
- [x] (🏁 12 days ago) Handle clone situations where HEAD is invalid ([~#14962~](https://github.com/sourcegraph/sourcegraph/pull/14962)) :shipit:🐛
- [x] (🏁 11 days ago) Don't use truncate in gitserver tests ([~#14986~](https://github.com/sourcegraph/sourcegraph/pull/14986)) :shipit:🐛
- [x] (🏁 5 days ago) RFC 167: Enforce monitoring ([~#14030~](https://github.com/sourcegraph/sourcegraph/issues/14030); PRs: ~[#15085](https://github.com/sourcegraph/sourcegraph/pull/15085)~) __2.00d__
- [x] (🏁 1 day ago) RFC 167: Enforce number of code host ([~#14024~](https://github.com/sourcegraph/sourcegraph/issues/14024); PRs: ~[#14916](https://github.com/sourcegraph/sourcegraph/pull/14916)~, ~[#15172](https://github.com/sourcegraph/sourcegraph/pull/15172)~) __1.00d__
- [x] (🏁 1 day ago) Provide a debug endpoint to list current authz providers ([~#14891~](https://github.com/sourcegraph/sourcegraph/issues/14891); PRs: ~[#15119](https://github.com/sourcegraph/sourcegraph/pull/15119)~) __1.00d__

@quinnkeast: __3.00d__

Completed: __3.00d__
- [x] (🏁 today) Cloud: Write RFC that clarifies cloud information architecture and implementation ([~#14918~](https://github.com/sourcegraph/sourcegraph/issues/14918)) __3.00d__

@ryanslade: __7.00d__

Completed: __7.00d__
- [x] (🏁 13 days ago) Drop language column on repo ([~#14760~](https://github.com/sourcegraph/sourcegraph/issues/14760); PRs: ~[#14942](https://github.com/sourcegraph/sourcegraph/pull/14942)~) __0.50d__ 🧶
- [x] (🏁 12 days ago) repo-updater: Use config value repoListUpdateInterval ([~#14983~](https://github.com/sourcegraph/sourcegraph/pull/14983)) :shipit:
- [x] (🏁 6 days ago) db: Use basestore.ScanStrings in repo store ([~#15096~](https://github.com/sourcegraph/sourcegraph/pull/15096)) :shipit:
- [x] (🏁 5 days ago) search: Create the "my" repo group  ([~#15093~](https://github.com/sourcegraph/sourcegraph/pull/15093)) :shipit:
- [x] (🏁 5 days ago) search: Only show "my" repogroup if user has added repos ([~#15143~](https://github.com/sourcegraph/sourcegraph/pull/15143)) :shipit:
- [x] (🏁 4 days ago) (Spike) Investigate exactly how code host connection works ([~#14853~](https://github.com/sourcegraph/sourcegraph/issues/14853)) __1.00d__ 🕵️
- [x] (🏁 today) schema: Fix typo ([~#15315~](https://github.com/sourcegraph/sourcegraph/pull/15315)) :shipit:
- [x] (🏁 today) Cloud: Write RFC that clarifies cloud information architecture and implementation ([~#14918~](https://github.com/sourcegraph/sourcegraph/issues/14918)) __3.00d__
- [x] (🏁 today) RFC 211 Tracking issue ([~#14163~](https://github.com/sourcegraph/sourcegraph/issues/14163)) __2.50d__

@tsenart

Completed
- [x] (🏁 today) repo-updater: Faster counting of user added repos ([~#15316~](https://github.com/sourcegraph/sourcegraph/pull/15316)) :shipit:

@unknwon: __7.00d__

- [ ] ~Pure-SQL authz approach~ ([#11767](https://github.com/sourcegraph/sourcegraph/issues/11767)) __1.50d__ 🎩🧶
- [ ] ~RFC 167: Not allowed to apply license with unknown plan~ ([#14031](https://github.com/sourcegraph/sourcegraph/issues/14031))

Completed: __5.50d__
- [x] (🏁 13 days ago) secret: remove abandoned secret key file on start ([~#14895~](https://github.com/sourcegraph/sourcegraph/issues/14895); PRs: ~[#14948](https://github.com/sourcegraph/sourcegraph/pull/14948)~) __0.50d__ 🔒
- [x] (🏁 13 days ago) secret: only turn on encryption when the env var is explicitly specified ([~#14898~](https://github.com/sourcegraph/sourcegraph/issues/14898); PRs: ~[#14947](https://github.com/sourcegraph/sourcegraph/pull/14947)~) __0.50d__ 🔒
- [x] (🏁 13 days ago) RFC 167: Enforce repository permissions ([~#14025~](https://github.com/sourcegraph/sourcegraph/issues/14025); PRs: ~[#14943](https://github.com/sourcegraph/sourcegraph/pull/14943)~) __0.50d__
- [x] (🏁 12 days ago) GitHub organization membership is not enforced when configured multiple auth providers ([~#14204~](https://github.com/sourcegraph/sourcegraph/issues/14204); PRs: ~[#14949](https://github.com/sourcegraph/sourcegraph/pull/14949)~) __1.00d__ 🐛
- [x] (🏁 12 days ago) Investigate why our dogfood instance stops syncing perms from Bitbucket Server ([~#14893~](https://github.com/sourcegraph/sourcegraph/issues/14893)) __1.00d__
- [x] (🏁 12 days ago) authz: add a test case to cover no updated user pending permissions ([~#14761~](https://github.com/sourcegraph/sourcegraph/issues/14761); PRs: ~[#14973](https://github.com/sourcegraph/sourcegraph/pull/14973)~) __0.50d__
- [x] (🏁 11 days ago) licensing: make product name recognize new plan tags ([~#14946~](https://github.com/sourcegraph/sourcegraph/pull/14946)) :shipit:
- [x] (🏁 8 days ago) authz: add `TouchRepoPermissions` API ([~#14701~](https://github.com/sourcegraph/sourcegraph/issues/14701); PRs: ~[#14972](https://github.com/sourcegraph/sourcegraph/pull/14972)~) __0.50d__
- [x] (🏁 8 days ago) RFC 167: Enforce branding ([~#14028~](https://github.com/sourcegraph/sourcegraph/issues/14028); PRs: ~[#14945](https://github.com/sourcegraph/sourcegraph/pull/14945)~) __0.50d__
- [x] (🏁 8 days ago) RFC 167: Enforce user limit ([~#14611~](https://github.com/sourcegraph/sourcegraph/issues/14611)) __0.50d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by ryanslade** [comment]
## Week ending 23rd October

* First half of the week was finishing off work from the previous cycle
* Second half was working together with @quinnkeast to understand how we're going to proceed with supporting private code and organisations on Cloud. Initially we'd like feedback on our overall ["Information Architecture" ideas]( https://docs.google.com/document/d/15vIqi4SHUKYM4MJ80GLwLxQpoMJRCJVXUVuSZoYmrug/edit)

## Next week

* Assuming no major changes required to information architecture, work on a RFC going into the details of how we're going to implement it.

**Comment by unknwon** [comment]
### Last week

Mainly Worked on RFC 167 items and finished prototyping pure-SQL authz.

### This week

Pair with @eseliger to validate pure-SQL authz design with campaigns and finish RFC 167 with @flying-robot.

**Comment by asdine** [comment]
### Last week

- First half of the week was finishing off work from the previous cycle
- Second half of the week, fixed `SetClonedRepos` behaviour with @tsenart 
- Worked on turning the repos store to use basestore

### This week

- Work on repo store and repo-updater store

**Comment by unknwon** [comment]
### Last week

- Paired with @eseliger on pure-SQL authz.
- Paired with @flying-robot on various items of RFC 167.

### This week

- Tidy up pure-SQL authz and RFC 167 PRs for review.
- Next cycle planning and kick off.

**Comment by asdine** [comment]
### Last week

- Worked on moving repo-updater store logic to the shared Repo Store and replacing all code to use the new store.
- Was off thursday and friday

### This week

- Keep working on repo-updater tech debt
- Review RFC 255

**Comment by artemruts** [comment]
### Last week

- Onboarding + teams sync meetings + dev setup.

### This week

- Wrap up #13745 and #14643
- Start working on #13999 @flying-robot 
- Work with the team to plan for RFC 261 related work
