### ISSUE TITLE
Security 3.22 Tracking issue

### ISSUE THREAD

**Issue by ElizabethStirling** [sourcegraph/sourcegraph#14813]
### Plan

This iteration, we want to resolve container scan vulnerabilities, initiate scanning of compute nodes, and host a dummy security repository on Sourcegraph Cloud as a proof of concept. This will ensure that our underlying infrastructure has no significant known flaws. Additionally, by having this proof of concept private repository, we can validate our design, and ensure that there are no obvious flaws in our access control.

**Goal:** Resolve container vulnerabilities with a score of at least 4.0, or have plans to resolve when resolutions are released.

**Goal:** All compute nodes are continuously scanned for known security vulnerabilities, and the security team is alerted when one is found.

**Goal:** We connect our [test security repository](https://github.com/sourcegraph/security-test/blob/main/README.md) to Sourcegraph Cloud and [only members who can access that repository on GitHub](https://github.com/sourcegraph/security-test/settings/access) can access that repository on Sourcegraph Cloud. These people are the organization owners, and members of the security team. Note that this depends on our [ability to host private code on Sourcegraph Cloud](https://about.sourcegraph.com/handbook/engineering/cloud#private-code-on-sourcegraph-cloud).

### Availability

Period is from 2020-10-20 to 2020-11-20. Please write the days you won't be working and the number of working days for the period.

Chayim: 1d (2020-11-03)

### Tracked issues

@unassigned: __2.00d__

- [ ] Team Security Tracking: Vulnerability scan and analysis ([#15477](https://github.com/sourcegraph/sourcegraph/issues/15477)) __2.00d__
  - [x] (🏁 1 day ago) One-time scan of external attack surface ports ([~#15478~](https://github.com/sourcegraph/sourcegraph/issues/15478)) __2.00d__

Completed: __2.00d__
- [x] (🏁 1 day ago) One-time scan of external attack surface ports ([~#15478~](https://github.com/sourcegraph/sourcegraph/issues/15478)) __2.00d__

@ElizabethStirling: __10.00d__

- [ ] Team Security Tracking: Vulnerability scan and analysis ([#15477](https://github.com/sourcegraph/sourcegraph/issues/15477)) __3.00d__
  - [x] (🏁 7 days ago) Triage issues in Google Security Command center, close easy wins ([~#15542~](https://github.com/sourcegraph/sourcegraph/issues/15542)) __3.00d__

Completed: __10.00d__
- [x] (🏁 14 days ago) Configure Cloudflare WAF ([~#15159~](https://github.com/sourcegraph/sourcegraph/issues/15159)) __5.00d__
- [x] (🏁 10 days ago) Enable rate limiter in dotcom ([~#15539~](https://github.com/sourcegraph/sourcegraph/issues/15539)) __1.00d__
- [x] (🏁 7 days ago) Triage issues in Google Security Command center, close easy wins ([~#15542~](https://github.com/sourcegraph/sourcegraph/issues/15542)) __3.00d__
- [x] (🏁 4 days ago) Re-permission, document, or deactivate public buckets ([~#15758~](https://github.com/sourcegraph/sourcegraph/issues/15758)) __1.00d__

@chayim: __7.00d__

- [ ] Team Security Tracking: Vulnerability scan and analysis ([#15477](https://github.com/sourcegraph/sourcegraph/issues/15477)) __2.00d__
  - [x] (🏁 12 days ago) Vulnerability scans of all insiders containers ([~#13551~](https://github.com/sourcegraph/sourcegraph/issues/13551)) __2.00d__

Completed: __7.00d__
- [x] (🏁 22 days ago) Review source code scan results and eliminate false positives ([~#15043~](https://github.com/sourcegraph/sourcegraph/issues/15043)) __2.00d__
- [x] (🏁 22 days ago) Set up centralized logging infrastructure ([~#13552~](https://github.com/sourcegraph/sourcegraph/issues/13552)) __1.00d__
- [x] (🏁 12 days ago) Vulnerability scans of all insiders containers ([~#13551~](https://github.com/sourcegraph/sourcegraph/issues/13551)) __2.00d__
- [x] (🏁 5 days ago) Analyze and fix a container vulnerability ([~#14089~](https://github.com/sourcegraph/sourcegraph/issues/14089)) __2.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by ElizabethStirling** [comment]
**This Week**
This week started with finalizing my RFC and responding to comments. I also did some thinking about how to share security with the rest of the team, and have scheduled a recurring security social event to promote team cohesion. I then updated the handbook's section on high agency to include insight from other colleagues. I took at look at [#13557](https://github.com/sourcegraph/sourcegraph/issues/13557), but need further GCP permissions to proceed on some of it. Finally, I chatted with team members as to what known security flaws they think we should investigate and triage. 


**Next Week**

Next week I expect to do some planning work with Chayim, both in relation to the chats I had with team members, and with regards to #13557. I hope I'll be able to get a good chunk of #13557 done as well. Finally, I'd like to start work on a slide to present in the company meeting to help communicate what security is working on to the rest of the team.

**Comment by sushiwushi** [comment]
**This Week**

This week, I have verified a clickjacking vulnerability and privilege escalation vulnerability during my penetration testing process in the application. Both of the reports can be found in [security issue #111](https://github.com/sourcegraph/security-issues/issues/113) and [security issue #114](https://github.com/sourcegraph/security-issues/issues/114).

**Next Week**

Next week, I will continue to penetrate the application and verify some vulnerabilities to make sure the application isn't vulnerable to them. In addition, I will also run some automated scans using scanners against the application.

**Comment by chayim** [comment]
**This Week**

I merged the PR for container cases, as well as the transparent security blog post. [RFC 245](https://docs.google.com/document/d/1dBzP3VZWVNOZD7dIN4izgzl3wDa5Sjj8LtS9zQViri8/) was approved, and some issues were created. I eliminated several false positives from our source code scanning, and ran an initial container scan with Anchore. Finally, I did some roadmap work for security.

**Next Week**

I will eliminate the remaining false positives (#15043) in our source code scanning. Next, I will set up centralized logging (#13552) infrastructure for security event logs. Finally, I'm refocusing on hiring - and working on the security hiring process we paused last week due to my migraine.

**Comment by ElizabethStirling** [comment]
**This week**
    This week had a lot of planning and context switching. I've learned from this, and hope to be able to avoid such outcomes in the future. However, I was still able to get plenty of work done. I started with communicating with Eric and Stephen about our known security holes, and how we want to update our priorities. I got some work done for #13557 by ~~bugging~~ collaborating with @Gonza to get the security command center turned on. I also have a plan of action for ingesting logs into Elasticsearch when it comes time to implement it in #14090 & 14091. Finally, I got most of the work done to enable the Cloudflare WAF (#15159) and rate limiting, though am somewhat blocked on a discussion about our Cloudflare plan. We may be able to get away without upgrading our plan for dotcom, but I need to do more investitgation. Finally, I got a chunk of handbook documentation done on how to use Grafana, Prometheus, and Cloudflare to observe what's happening with our clusters.

**Next Week**
    Next week I hope to finish out #15159, assuming that our discussions don't lead to us switching to using Google's WAF. If we do switch, I would hope I'd still be able to get things finished, but I'd need to work more closely with the distribution team to also update our DNS configuration and port us from Cloudflare to Google Cloud Armor. After this, I want to get back to work on #13557, and look into getting a trial of Veracode's DAST solution scanning our network.

**Comment by sushiwushi** [comment]
**This Week**
This week, I ran automated tests against Sourcegraph using [Nikto](https://cirt.net/Nikto2) and [Nessus](https://www.tenable.com/products/nessus) during my penetration testing process in the application. Both of the reports are exported and can be found in [security issue #116](https://github.com/sourcegraph/security-issues/issues/116) and [security issue #118](https://github.com/sourcegraph/security-issues/issues/118).

**Comment by chayim** [comment]
**This Week**

I eliminated false positives in code scanning (#15043), and committed a PR for a bug found by CodeQL. I configured centralized logging with Elastic, to accept out logs (#13552). Finally, I worked on our [roadmap](https://docs.google.com/document/d/1GRntQq8AVzFepDhDkAfAlj3lekZ3f2XJdrjoQPS93lY/) and created a first draft of our [incident management process](https://docs.google.com/document/d/1sVBHaGLXojcq7zAxJo8D4Fonh4kxA3grtWgzbKoAn-0/) which includes a [pull request](https://github.com/sourcegraph/about/pull/1874) to publicly share in our handbook.

**Next Week**

I will scan the external surface of Sourcegraph cloud, review outputs and plan accordingly. I will also ensure insiders containers are publishing vulnerability reports (#13551) so that we can start to fix them (#14089). I'm also hoping to spend more time thinking about [security issue 115](https://github.com/sourcegraph/security-issues/issues/115).

**Comment by ElizabethStirling** [comment]
**This Week**
    This week also had a good chunk of planning, but also a good chunk of doing. I was able to work with Chayim to get the existing items in the security roadmap estimated and added to GitHub (excluding the SOC/ISO compliance entry added today). We'll hopefully be able to refine these estimates and the goals of the security team over the course of the next week. I also enabled Cloudflare WAF on both dogfood and dotcom, as well as enabling a rate limiter for dogfood. I hope to enable the rate limiter for dotcom by end of day Friday, but it may slop over onto the weekend / Monday. Finally, I added handbook notes about observability, and how Cloudflare's WAF and rate limits are configured.
**Next Week**
    I hope to work with Chayim to finalize estimates on the goals and priorities of the security team. I want to get the rate limiter for dotcom switched on if it's not already enabled (#15539). I also want to triage the issues brought up in the Google Security Command center, so that we can clear those out (#15542). Note that I will be off Wednesday for a public holiday.

**Comment by sushiwushi** [comment]
**This Week**
This week, I ran automated tests against Sourcegraph using OWASP ZAP proxy during my penetration testing process in the application. After triaging the issues I discovered there are no direct security risk as investigated in [security issue 119](https://github.com/sourcegraph/security-issues/issues/119).

**Next Week**
I will run automated scanners against the application to eliminate low hanging fruits so it can be patched as soon as possible. I'll see if I'm able to get [Acunetix](https://www.acunetix.com/web-vulnerability-scanner/) and [Burp Suite Pro](https://portswigger.net/burp/pro) scanner to work.

**Comment by chayim** [comment]
> I will run automated scanners against the application to eliminate low hanging fruits so it can be patched as soon as possible. I'll see if I'm able to get [Acunetix](https://www.acunetix.com/web-vulnerability-scanner/) and [Burp Suite Pro](https://portswigger.net/burp/pro) scanner to work.

Big +1 for Acunetix. Burp Suite Pro is great, but I've liked the Acunetix outputs better over the last ~2 years.

**Comment by chayim** [comment]
This Week

I worked on changes to our [hiring process](https://github.com/sourcegraph/about/pull/1874), creating a [pairing project](https://github.com/sourcegraph/interviews/pull/160). I manually scanned all Sourcegraph dockers as part of #13551, and posted the reports to [security issue #120](https://github.com/sourcegraph/security-issues/issues/120). I some time thinking about [security issue #115](https://github.com/sourcegraph/security-issues/issues/115), which I don't yet know how to solve. Finally, I spent more time working on estimating the roadmap, and hiring.

Next Week

I have several interviews scheduled for the upcoming week. I'll update the handbook with the roadmap estimates. I want to get the hiring process PRs merged. Finally, given the container vulnerability reports [security issue #120](https://github.com/sourcegraph/security-issues/issues/120), I will rank by CVSS score, and start fixing (#14089).

**Comment by ElizabethStirling** [comment]
**This Week**
This week, Chayim and I finalized our work and our estimates for how long it would take. I switched the dotcom rate limiter on, as well as increasing the limit to avoid blocking legitimate users. I also reconfigured the WAF to not block extension uploads, and scheduled work for a more long term solution to that block. I also triaged the security issues repo and marked things as either Post-GA or Cloud-GA, depending on whether or not we need them done prior to GA being released. I then triaged and resolved outstanding google security command center issues, and made tracking issues for less important work. Finally, I've been working on getting Google Secret Manager(GSM) online for dogfood. In this vein, I've enabled audit logs, and have a PR out for a bash script to provide a simple API for developers to create, delete, list, and rotate secrets, with special attention paid to allowing for bulk creation and rotation of secrets.

**Next Week**
Next week, I want to get the secret management script merged in. Concurrently, I want to work on getting #15413 hammered out, which is loading dogfood secrets into dogfood's secret manager. I also want to finish #15455, which will update dogfood's k8s deployment scripts to fetch secrets from GSM. This will be a tight week, especially since scripting the secret management might slop over a tad bit, but I think that getting both of these hammered out is a potentially achievable goal.

**Comment by sushiwushi** [comment]
**This Week**

This week didn't went as planned. Demo requests were both denied for [Burp Suite Professional trial](https://portswigger.net/burp/pro) and [Acunetix web vulnerability scanner trial](https://www.acunetix.com/web-vulnerability-scanner/). I tried checking other vulnerability scanners in [OWASP](https://owasp.org/www-community/Vulnerability_Scanning_Tools) and some open-source scanners used by bug bounty hunters. However, after running it against sourcegraph.com it either reveals nothing or reveals there are too many vulnerabilities which most of them are false positive.

**Next Week**

I will run automated scanners against the web application to eliminate low hanging fruits so it can be patched as soon as possible. Additionally, I'll start running penetrating Sourcegraph cloud once the IP address are ready.

**Comment by chayim** [comment]
**This Week**

I focused on hiring, interviewing multiple candidates for [our open position](https://about.sourcegraph.com/handbook/engineering/hiring/software-engineer-security). I made small changes to the [pairing project](https://github.com/sourcegraph/interviews/pull/160). I was able to fix several container vulnerabilities [#14089], based on CVSS score. I also delved into SOC 3 research.

**Next Week**

The campaigns team reached out requesting a security review, which I'll start. I'm continuing to focus on hiring, in addition to merging the two PRs. In addition, roadmap planning and discussion around SOC. Finally, we'll plan the new iteration.

**Comment by ElizabethStirling** [comment]
**This Week**
This week, we ended up changing direction last minute to use Vault for secret management, rather than Google Secret Manager. This caused some roadblocks, since distribution was tied up with the release, but on the whole, I was still able to get significant chunks of work done. First, I was able to sync with Joe and socialize how we plan to manage AuthN/Z. Additionally, I re-reviewed our recent bug bounty emails and security command center results to ensure we didn't miss anything. Additionally, the staging vault cluster is almost entirely online, and is currently only awaiting re-review. I've also sourced and documented all buildkite secrets, so that we can start using the secret manager for our CI pipelines as soon as next week.

**Next Week**
I want to start by merging in the terraform to configure Vault, if I wasn't able to get it done before Monday. Then, I want to work in tandem on #15453 and #15454 to load the buildkite-relevant secrets into our staging vault, and begin consuming them in our CI pipelines. Once buildkite is fully configured, I want to see if I can finish out #15453 so that we have all of our dogfood & CI secrets loaded into vault. However, since I do have two days off for Thanksgiving, I may end up only finishing the buildkite work.

Closing this issue in favor of #15979, since this iteration has ended.

**Comment by chayim** [comment]
**This Week**

I started on the security review for campaigns (#15983). I merged the PR for the pairing project, and reached out to several candidates. I also spent time researching our SOC approach (#15985), and gathered my [notes](https://docs.google.com/document/d/1NgKJOaZJKWQLUDPkov3YCvvRzqbPi7ObUqBs9zeSSUk/). Finally, we planned the new iteration(#15979).

**Next Week**

I want to complete the security review for campaigns (#15983). I'm going to complete my SOC research, and start planning a roadmap for SOC (#15985). Then, I will start the work of centralizing logs for our dogfood WAF (#15980) or dogfood stackdriver (#15981).
