### ISSUE TITLE
Tracking issue: Remove the precise code intel bundle manager

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#14820]
### Plan

The precise-code-intelligence-bundle-manager is no longer a necessary core service after we've migrated data from SQLite to Postgres. Removing this service will simplify a lot of ops concerns from the code intel team (data retention, space clearing, monitoring, alerts, provisioning, etc). In broad strokes, our plan is to:

- Read/write from/to S3, GCS, or minio for upload data (falling back to the bundle manager)
- Remove fallbacks from the bundle manager client so that the service receives no ingress traffic
- Remove the bundle manager from all deployments. This requires that:
  - Ensure all bundle data has been migrated from the bundle manager persistent volume to Postgres
  - Ensure all upload data has been migrated to a volume which is managed independently (S3, GCS, or minio)

### Tracked issues

@efritz: __3.00d__

Completed: __3.00d__
- [x] (🏁 20 days ago) Write RFC to remove the bundle manager service ([~#14845~](https://github.com/sourcegraph/sourcegraph/issues/14845)) __0.50d__
- [x] (🏁 15 days ago) Write a S3, GCS, minio-compatible layer to replace bundle manager upload operations ([~#14823~](https://github.com/sourcegraph/sourcegraph/issues/14823); PRs: ~[#14933](https://github.com/sourcegraph/sourcegraph/pull/14933)~) __0.50d__
- [x] (🏁 15 days ago) Update development environment to include a minio container ([~#14824~](https://github.com/sourcegraph/sourcegraph/issues/14824)) __0.50d__
- [x] (🏁 14 days ago) Update production environments to include a minio service ([~#14825~](https://github.com/sourcegraph/sourcegraph/issues/14825)) __0.50d__
- [x] (🏁 10 days ago) server: Add default configuration to connect to the codeintel upload store ([~#15116~](https://github.com/sourcegraph/sourcegraph/pull/15116)) :shipit:
- [x] (🏁 7 days ago) Update bundle manager client to read from S3 or GCS ([~#14826~](https://github.com/sourcegraph/sourcegraph/issues/14826); PRs: ~[#15089](https://github.com/sourcegraph/sourcegraph/pull/15089)~, ~[#15106](https://github.com/sourcegraph/sourcegraph/pull/15106)~, ~[#15107](https://github.com/sourcegraph/sourcegraph/pull/15107)~, ~[#15114](https://github.com/sourcegraph/sourcegraph/pull/15114)~) __0.50d__
- [x] (🏁 7 days ago) codeintel: Remove all but remaining upload actions from bundle manager ([~#15163~](https://github.com/sourcegraph/sourcegraph/pull/15163)) :shipit:
- [x] (🏁 7 days ago) Tracking issue: Generic user code executor ([~#14822~](https://github.com/sourcegraph/sourcegraph/issues/14822))
- [x] (🏁 5 days ago) Update bundle manager client to remove all calls to the bundle manager ([~#14827~](https://github.com/sourcegraph/sourcegraph/issues/14827); PRs: ~[#15369](https://github.com/sourcegraph/sourcegraph/pull/15369)~, ~[#15374](https://github.com/sourcegraph/sourcegraph/pull/15374)~)
- [x] (🏁 1 day ago) Remove the bundle manager from deployments ([~#14828~](https://github.com/sourcegraph/sourcegraph/issues/14828); PRs: ~[#15490](https://github.com/sourcegraph/sourcegraph/pull/15490)~) __0.50d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
