### ISSUE TITLE
Tracking issue: Generic user code executor

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#14822]
### Plan

The precise-code-intel-indexer and precise-code-intel-indexer-vm is (as far as we have discussed) exactly the infrastructure that the @sourcegraph/campaigns team will need to safely and efficiently apply campaigns within Sourcegraph.

As a method to increase code quality, documentation, and testing, I am going to perform an experiment to make the current set of services completely generic (and free of any code-intelligence-specific behavior or mentions). This will leave future use cases open for adoption and will also give us a chance to remove some of the cruft that accumulated during rapid development and CNCF-specific efforts.

These services are deployed only in the cloud environment, so this should not affect any user deployments.

### Tracked issues

@efritz: __2.50d__

- [ ] Tracking issue: Remove the precise code intel bundle manager ([#14820](https://github.com/sourcegraph/sourcegraph/issues/14820))
  - [x] (🏁 today) codeintel: Refactor worker main ([~#15134~](https://github.com/sourcegraph/sourcegraph/pull/15134)) :shipit:

Completed: __2.50d__
- [x] (🏁 14 days ago) chore: Fix typo in usage documentation ([~#14841~](https://github.com/sourcegraph/sourcegraph/pull/14841)) :shipit:
- [x] (🏁 14 days ago) internal: Add base configuration object ([~#14836~](https://github.com/sourcegraph/sourcegraph/pull/14836)) :shipit:
- [x] (🏁 14 days ago) ~internal: Add base HTTP client~ ([~#14835~](https://github.com/sourcegraph/sourcegraph/pull/14835)) :shipit:
- [x] (🏁 14 days ago) Add SetLogContents to workerutil store ([~#14831~](https://github.com/sourcegraph/sourcegraph/issues/14831); PRs: ~[#14837](https://github.com/sourcegraph/sourcegraph/pull/14837)~)
- [x] (🏁 14 days ago) docker-images: Install src-cli in ignite-ubuntu base image ([~#14839~](https://github.com/sourcegraph/sourcegraph/pull/14839)) :shipit:
- [x] (🏁 14 days ago) Add QueuedCount to workerutil store ([~#14832~](https://github.com/sourcegraph/sourcegraph/issues/14832); PRs: ~[#14838](https://github.com/sourcegraph/sourcegraph/pull/14838)~)
- [x] (🏁 14 days ago) chore: Add additional utils for interacting with goroutines ([~#14840~](https://github.com/sourcegraph/sourcegraph/pull/14840)) :shipit:
- [x] (🏁 14 days ago) chore: Move handler out of workerutil options ([~#14861~](https://github.com/sourcegraph/sourcegraph/pull/14861)) :shipit:
- [x] (🏁 7 days ago) ~executor: Sample campaigns apply job queue~ ([~#14915~](https://github.com/sourcegraph/sourcegraph/pull/14915)) :shipit:
- [x] (🏁 7 days ago) Extract queue API from precise-code-intel-indexer into a new service ([~#14834~](https://github.com/sourcegraph/sourcegraph/issues/14834); PRs: ~[#14882](https://github.com/sourcegraph/sourcegraph/pull/14882)~) __0.50d__
- [x] (🏁 7 days ago) Make generic version of the precise-code-intel-indexer-vm service ([~#14833~](https://github.com/sourcegraph/sourcegraph/issues/14833); PRs: ~[#14883](https://github.com/sourcegraph/sourcegraph/pull/14883)~) __0.50d__
- [x] (🏁 7 days ago) Add executor-queue and executor to deployment environments ([~#15056~](https://github.com/sourcegraph/sourcegraph/issues/15056))
- [x] (🏁 6 days ago) Update the frontend proxy to target executor-queue ([~#14885~](https://github.com/sourcegraph/sourcegraph/issues/14885); PRs: ~[#15053](https://github.com/sourcegraph/sourcegraph/pull/15053)~) __0.50d__
- [x] (🏁 6 days ago) executor: Fix src-cli commands ([~#15080~](https://github.com/sourcegraph/sourcegraph/pull/15080)) :shipit:
- [x] (🏁 4 days ago) Remove precise-code-intel-indexer-vm service ([~#14844~](https://github.com/sourcegraph/sourcegraph/issues/14844); PRs: ~[#15123](https://github.com/sourcegraph/sourcegraph/pull/15123)~) __0.50d__
- [x] (🏁 today) Remove precise-code-intel-indexer service ([~#14843~](https://github.com/sourcegraph/sourcegraph/issues/14843); PRs: ~[#15135](https://github.com/sourcegraph/sourcegraph/pull/15135)~) __0.50d__
- [x] (🏁 today) codeintel: Refactor worker main ([~#15134~](https://github.com/sourcegraph/sourcegraph/pull/15134)) :shipit:

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
