### ISSUE TITLE
Campaigns Sprint 3 Tracking issue

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#14870]
### Plan

Our overarching goal is to _grow campaigns adoption_. The bulk of this sprint is focused on removing obstacles to companies using campaigns, such as the user token issue and the rate limiting issue. We will also work on improving our specs and will begin a big customer outreach push, which we will continue in our next sprint.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

- @eseliger **0d**
- @LawnGnome **0d**
- @mrnugget **1d unavailable: 27th October**
- @chrispine **0d**

### Tracked issues

@LawnGnome

Completed
- [x] (🏁 12 days ago) campaigns: fix icon display on navbars ([~#14967~](https://github.com/sourcegraph/sourcegraph/pull/14967)) :shipit:🐛
- [x] (🏁 4 days ago) extsvc: unify OAuth and username/password authentication methods in outbound requests ([~#15077~](https://github.com/sourcegraph/sourcegraph/pull/15077)) :shipit:

@eseliger: __3.00d__

Completed: __3.00d__
- [x] (🏁 12 days ago) Add error handling for not found changesets from GitHub ([~#14771~](https://github.com/sourcegraph/sourcegraph/pull/14771)) :shipit:🐛
- [x] (🏁 11 days ago) Fix timestamp usage on CampaignNode component ([~#15003~](https://github.com/sourcegraph/sourcegraph/pull/15003)) :shipit:
- [x] (🏁 11 days ago) a8n: Create GitHub PRs in draft status ([~#7998~](https://github.com/sourcegraph/sourcegraph/issues/7998); PRs: ~[#14527](https://github.com/sourcegraph/sourcegraph/pull/14527)~, ~[#15004](https://github.com/sourcegraph/sourcegraph/pull/15004)~, ~[#15005](https://github.com/sourcegraph/sourcegraph/pull/15005)~) __3.00d__ 👩
- [x] (🏁 11 days ago) Hide publish hint when at least one changeset has been published ([~#15016~](https://github.com/sourcegraph/sourcegraph/pull/15016)) :shipit:
- [x] (🏁 11 days ago) Fix history calculation when a reviewing user has been deleted ([~#15017~](https://github.com/sourcegraph/sourcegraph/pull/15017)) :shipit:🐛
- [x] (🏁 7 days ago) Cleanup rewirer code a bit ([~#15075~](https://github.com/sourcegraph/sourcegraph/pull/15075)) :shipit:
- [x] (🏁 6 days ago) Add error codes to campaign errors ([~#15059~](https://github.com/sourcegraph/sourcegraph/pull/15059)) :shipit:
- [x] (🏁 3 days ago) Refactor syncer ([~#15133~](https://github.com/sourcegraph/sourcegraph/pull/15133)) :shipit:
- [x] (🏁 1 day ago) Spawn one Syncer per external service ([~#15161~](https://github.com/sourcegraph/sourcegraph/pull/15161)) :shipit:

@mrnugget: __8.50d__

Completed: __8.50d__
- [x] (🏁 12 days ago) Handle not-found errors when importing changesets correctly ([~#14923~](https://github.com/sourcegraph/sourcegraph/issues/14923); PRs: ~[#14771](https://github.com/sourcegraph/sourcegraph/pull/14771)~) __1.00d__ 🐛
- [x] (🏁 5 days ago) Campaigns: `src actions` schema: add ability to reference config file from Docker Action ([~#10527~](https://github.com/sourcegraph/sourcegraph/issues/10527)) __1.00d__
- [x] (🏁 1 day ago) Create sample campaign specs and docs ([~#14957~](https://github.com/sourcegraph/sourcegraph/issues/14957)) __3.00d__
- [x] (🏁 1 day ago) Create templating/mount-files-in-container prototype for src-cli ([~#14922~](https://github.com/sourcegraph/sourcegraph/issues/14922)) __2.50d__
- [x] (🏁 1 day ago) campaigns: initial UI state after applying a campaign can be wonky ([~#14921~](https://github.com/sourcegraph/sourcegraph/issues/14921)) __1.00d__ 🐛

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by eseliger** [comment]
#### Weekly update: 2020-10-14 to 2020-10-20

Last week, I focused mainly on Draft mode PRs. While I uncovered I totally missed that we need the reconstruction of historic changeset events, and that I would need to add probably at least 4 new actions to the reconciler, I made some progress towards that and draft PRs for GitHub work now, I had to take on a refactor of the reconciler though, which made the ticket roll over to sprint three, where I still need to do GitLab support and docs work. I think it was worth it though, the changes to the reconciler make it a lot easier to understand for me, and I think Thorsten shares this thought. 
Besides that, I tried downloading the entirety of GitHub.com's database on our main repository into my local instance and uncovered a "bug" where we don't take a changeset as errored and can't fix itself, meaning that 404ing changesets will be retried loads of times and use up all our api rate limit tokens quickly. We've also had some chats on sharing work between the codeintel team and the campaigns team, where @efritz made some awesome PRs that make their whole infrastructure for running user code in a safe manner.

This week, I'll continue focussing on Draft _M_Rs, and possibly finish that effort. Afterwards, I'll head on to work on having some more useful rate limits applied in the reconciler and the syncer.

**Comment by mrnugget** [comment]
### Weekly Update

Spent the majority of last week working on src-cli improvements and bug fixes and will continue to do this week, after gathering feedback on the two prototypes (https://github.com/sourcegraph/src-cli/pull/334 and https://github.com/sourcegraph/src-cli/pull/357) I built. The goal is to combine both of them to make it really easy and performant to run a campaign that allows us to run @rvantonder's [go-staticcheck comby patterns](https://github.com/comby-tools/go-patterns/blob/main/go-staticcheck.toml) across repositories.

I also want to finish up my work with Erik on fixing not-found errors when importing changesets.

**Comment by LawnGnome** [comment]
#### Weekly update: 2020-10-13 to 2020-10-19

Last week was a grab bag: iterating on the new campaigns icon with the design team, updating the Sourcegraph backend as we approached the 3.21 release to ensure we had the right src-cli versions, releasing src-cli a couple of times, migrating some common spec validation code out into our new campaignutils repo, and writing up our challenges around user tokens to solicit feedback.

This week, I'll be focusing on user tokens — specifically, how can we leverage recent work on code host connections to support what we need to exit beta — and src-cli documentation.

**Comment by mrnugget** [comment]
#### Weekly Update

Writing this update today instead of tomorrow, because I'm out tomorrow.

Reached my goal of fixing the imported-changeset-not-found-errors properly, together with Erik. That, and his work on draft-publishing, lead us also to some refactoring in the reconciler. We also paired on building out the src-cli prototype that includes file-mounting and templating, which is now ready-to-review and should, in my opinion, be merged as an experimental feature.

My main focus this week is customers and helping @rrhyne reaching out to them with campaign specs that solve their problems. I started with that last week by writing a tutorial on how to update docker base images. Tutorial is done from my side and ready-for-review. I want to follow-up on that by creating another tutorial that search/replaces offensive language.

And I also hope to merge the mentioned src-cli prototype and document it so that we could use to make those campaigns easier and faster to run.

**Comment by rrhyne** [comment]
Removed https://github.com/sourcegraph/sourcegraph/issues/13655 as it wasn't discussed in planning.

**Comment by eseliger** [comment]
**Weekly update: 2020-10-20 to 2020-10-26**
Last week, I finished off the draft changesets ticket, by adding support for GitLab as well. Did some pairings on Authz, not found error handling for imported changesets, src-cli templating and reconciler work. The last two days I also spent some time on making the syncer respect rate limits, which is still ongoing.
This week I will finish the work on rate limiting in syncer and the GitHub client. Additionally, I'll look into adding a notice when looking at an outdated campaign spec.

---
Optional stuff
Might do some spikes on smaller refactors I started hacking on if time allows, like a planner for the rewirer or moving some heavy computations to the DB that aren't required anymore when we have DB-based authz.

**Comment by LawnGnome** [comment]
#### Weekly update: 2020-10-20 to 2020-10-26

Last week, I took my original plan for user tokens using a new table, changed it after feedback to use `user_external_accounts`, and then changed it back to using a new table so we have more flexibility in terms of how users can manage their credentials.

Plus ça change.

However, I ended the week with a strong handle on what needs to be done for user tokens, which [is now represented on this Kanban board](https://github.com/sourcegraph/sourcegraph/projects/7).

My next week is to start getting those tickets knocked off one by one: as I type, I'm in the middle of [a minor refactor to make it easier for us to support different credential types](https://github.com/sourcegraph/sourcegraph/pull/15077) (eg OAuth bearer tokens, or username and password via basic auth) consistently across code host types, and then that will feed into [the reconciler gaining support for user tokens](https://github.com/sourcegraph/sourcegraph/issues/14989). After that, I have to build the GraphQL resolvers and UI to allow management of those. Then, lots of testing. (And a security review to ensure we're encrypting credentials correctly at rest.)

(I also [merged the new campaigns logo](https://github.com/sourcegraph/sourcegraph/pull/14740) last week, which was _actually_ the highlight of my week.)

**Comment by mrnugget** [comment]
### Weekly update

Last week I managed to finish the big remaining tasks of the sprint: I wrote two tutorials for the campaign docs, added documentation for the new templated-campaign-specs after I merged the prototype, talked to customers, fixed a bug when importing changesets.

This week we're going to do planning and start a new sprint. I think the focus will be again: customers and preparing things for the launch.

**Comment by eseliger** [comment]
### Weekly update

Last week, I spent most of my time in the syncer code and in external service tables. We're now at a stage where we almost get rate limiting for both github and gitlab, but it needs another day or so of polishing. There's bunch of follow-up work that could be done, but I think until customers will have a couple thousand changesets, we should pivot to some other task. 

This week, I'm going to finish off the left-overs from last iteration, and then start looking into the burndown chart work, or, if Adam's PR will be merged by then, prioritize the user token UI.
