### ISSUE TITLE
authz: faster repository permissions syncing via GitHub webhook

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#14917]
Use webhook could detect changes to repository permissions faster and do not consume API rate limit quota.

For GitHub, we care about following events (the engineering owner will decide the final list):

- Collaborator add, remove, or changed
- Visibility changes
- Repositories
- Team adds

Our handler should work for both org- and repo-level webhooks.

IIRC, campaigns team is already using the webhook. If the spike turns out to be good, we probably can have a unified endpoint (if we haven't already) for receiving webhook and call different sub-handlers based on events (or let sub-handlers subscribe to desired events). The engineering owner will decide the approach.

Similar optimization could be done for GitLab and Bitbucket Server/Cloud if it turns out to be effective and reliable.

---

Pairing notes from @arussellsaw and @flying-robot:

## Tasks
- [x] grok campaigns-related webhook code as a starting point
  - [x] determine what can be reused / standardized
- [ ] document what authz-related events Git{Hub,Lab} send
  - [ ] document the contents of those events and how we use them
- [ ] handle authz events
  - [ ] support active users
  - [ ] support pending users
  - [ ] bump affected repos to head of priority queue
  - [ ] bump affected users to head of priority queue
  - [ ] implementing monitoring / observability (consistent logging, counters, graphs, etc.)

## General Events of Interest
- collaborator added, removed, or changed
- repository visibility changed (e.g. turned private, or made public again)
- repositories added to org
- users added to org

## Open Questions
- how can we best limit the feature to SG / Cloud folks up front? 
  - external service config, flag, etc.?

## Notes
- [presentation: State of Sourcegraph Authorization](https://docs.google.com/presentation/d/1QCCgRn7LDwW0OV0jaR3b5m-1r5Fl_DRagyoS_LteV5g)
- [docs: Permissions Syncing](https://docs.sourcegraph.com/admin/repo/permissions#background-permissions-syncing)
- [code: campaigns webhooks](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/campaigns/webhooks.go)
- [code: syncUserPerms](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/repo-updater/authz/perms_syncer.go#L162-235)
- [code: syncRepoPerms](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/repo-updater/authz/perms_syncer.go#L237-374)
- [code: runSchedule](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/repo-updater/authz/perms_syncer.go#L608-641)
- [code: schedule-perms-sync](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/repo-updater/repoupdater/server.go#L80)

**Comment by unknwon** [comment]
@flying-robot Really nice notes! Thanks for it 😁 

Just one minor addition to "Tasks", when `permissions.userMapping` is enabled, we should ignore those events even if admin has set them up.

https://github.com/sourcegraph/sourcegraph/blob/0a39ace3f54e5774e8f9375355e4f2165d4c6b75/enterprise/cmd/repo-updater/authz/perms_syncer.go#L626

**Comment by arussellsaw** [comment]
i have a PR with adding this to the documentation, just logging here whilst i work on it. These are the events related to auth on Github that we will subscribe to in order to enqueue authz updates:
#### Github:
* [member](https://developer.github.com/webhooks/event-payloads/#member)
* [public](https://developer.github.com/webhooks/event-payloads/#public)
* [membership](https://developer.github.com/webhooks/event-payloads/#membership)
* [organization](https://developer.github.com/webhooks/event-payloads/#organization)
* [repository](https://developer.github.com/webhooks/event-payloads/#repository)
* [team](https://developer.github.com/webhooks/event-payloads/#team)
* [team_add](https://developer.github.com/webhooks/event-payloads/#team_add)
