### ISSUE TITLE
3.21.1 PRs to be included

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#14955]
- [x] https://github.com/sourcegraph/sourcegraph/pull/14775

- [x] https://github.com/sourcegraph/sourcegraph/pull/14944

- [x] https://github.com/sourcegraph/sourcegraph/pull/14954

- [x] https://github.com/sourcegraph/sourcegraph/pull/14953

- [x] https://github.com/sourcegraph/sourcegraph/pull/14962

- [x] https://github.com/sourcegraph/sourcegraph/pull/14981

- [x] https://github.com/sourcegraph/sourcegraph/pull/14983
