### ISSUE TITLE
A. R. Onboarding plan

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#15011]
### Week 1

Go through [General Onboarding](https://about.sourcegraph.com/handbook/people-ops/onboarding#for-all-new-teammates) and [Engineering Onboarding](https://about.sourcegraph.com/handbook/engineering/onboarding#engineering-onboarding).

- [ ] Schedule an architecture deep dive session with @tsenart.
- [ ] Schedule a frontend development introduction session with @lguychard or @felixfbecker.
- [ ] Meet with @quinnkeast and @ryanslade (at once) to learn about the on-going work in the Cloud project and what upcoming UX changes you'll be working on.

### Week 2 - 3

Get started with some smaller tasks that should help your learn a lot of our moving pieces (frontend and backend).

- [ ] Impossible to copy errors out of code host status indicator #14643
- [ ] GraphQL ExternalLink should expose kind: ExternalServiceKind (enum) instead of serviceType: String #14979
- [ ] Deploy to a cluster link in search performance warning notice is relative, not absolute #13745

**Comment by tsenart** [comment]
@lguychard, @felixfbecker: While we'll have some more substantial frontend work soon in the Cloud team (like in 2/3 weeks), it'd be nice if you could identify a good medium size task for on-boarding a new full stack teammate to the frontend code. Any help appreciated!

**Comment by lguychard** [comment]
@tsenart suggestion for an introductory frontend (full-stack, actually) task that actually fits quite well within the scope of the Cloud team: https://github.com/sourcegraph/sourcegraph/issues/14357

**Comment by tsenart** [comment]
Thanks @lguychard!
