### ISSUE TITLE
3.22 release tracking issue

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#15023]
# 3.22 Release 

This release is scheduled for [Nov 20, 2020, 6:00 PM (UTC)](https://time.is/1800_20_Nov_2020_in_UTC?3.22%20release%20date).

---

**Note:** All `yarn run release ...` commands should be run from folder `dev/release`.

**Note:** All `yarn run test ...` commands should be run from folder `web`.

## Setup

- [x] Ensure release configuration in `dev/release/config.json` on `main` is up to date with the parameters for the current release.
- [x] Ensure the latest version of the release tooling has been built before each step using `yarn run build` in `dev/release`.

## [Nov 13, 2020, 6:00 PM (UTC)](https://time.is/1800_13_Nov_2020_in_UTC?Five%20working%20days%20before%203.22%20release) (5 work days before release): Prep for branch cut

- [x] Post a release status update to Slack - review all release-blocking issues, and ensure someone is resolving each.
  ```sh
  yarn run release release:status
  ``` 

## [Nov 16, 2020, 6:00 PM (UTC)](https://time.is/1800_16_Nov_2020_in_UTC?Four%20working%20days%20before%203.22%20release) (4 work days before release): Branch cut

- [x] Update the changelog and merge the generated pull request:
  ```sh
  yarn run release changelog:cut
  ```
- [x] Create the `3.22` branch off the CHANGELOG commit in the previous step: `git branch 3.22 && git push origin 3.22`.

Upon branch cut, create and test the first release candidate:

- [x] Tag the first release candidate:
  ```sh
  yarn run release release:create-candidate 1
  ```
- [x] Run regression tests:
  - [x] Follow the [Regression tests guide](https://github.com/sourcegraph/sourcegraph/blob/main/client/web/src/regression/README.md) to set up your e2e environment. 
        Run the tests from the `web` directory. A more complete set of env vars can be found in this
        [1password](https://team-sourcegraph.1password.com/vaults/dnrhbauihkhjs5ag6vszsme45a/allitems/gm5dfflq6sfclmotneuayfdj5q) entry.
  - [x] New Sourcegraph Docker container:
    - Run the initializer: `E2E_INIT=true SOURCEGRAPH_BASE_URL=http://localhost:7080 yarn run test:regression -t 'Initialize new Sourcegraph instance'`
    - Run the regression test suite: `SOURCEGRAPH_BASE_URL=http://localhost:7080 yarn run test:regression`
  - [x] Upgrade from previous release:
    - Run the initializer on a Docker container running the last patch version of the previous major/minor release.
    - Upgrade and run the regression test suite.
  - [x] New Sourcegraph Kubernetes cluster:
    - Run the initializer on a new Sourcegraph Kubernetes cluster.
    - Run the regression test suite.
- [x] File any regressions as `release-blocker` issues and assign the appropriate teams.

Revert or disable features that may cause delays. As necessary, `git cherry-pick` bugfix (not feature!) commits from `main` into the release branch. Continue to create new release candidates daily or as necessary, until no more `release-blocker` issues remain:

- [x] Cut the Nth release candidate:
  ```sh
  N=<release-candidate-number> yarn run release release:create-candidate $N
  ```
- [x] Re-run the automated test suite against the new release candidate, file any regressions as
  `release-blocker` issues.
  - [x] If necessary, manually test features or workflows affected by the cherry-pick.
- [x] Post a release status update by running the command below. Ensure someone is resolving each release-blocking issue. If there are no more release-blocking issues, proceed to tag the final release in the next section.
  ```
  yarn run release release:status
  ``` 

## Tag final release

Once there are no more release-blocking issues (as reported by the `release:status` command) proceed with creating the final release:

- [x] Verify the [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) on
  `main` is accurate (no items should have been added since branch cut, but some items may need to
  be removed).
- [x] Tag the final release:
  ```
  yarn run release release-candidate:create final
  ```
- [x] Wait for the release Docker images to be available in [Docker Hub](https://hub.docker.com/r/sourcegraph/server/tags).
- [x] Open PRs that publish the new release and address any action items required to finalize draft PRs (track PR status via the [generated release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns)):
  ```sh
  yarn run release release:stage
  ```

## [Nov 20, 2020, 6:00 PM (UTC)](https://time.is/1800_20_Nov_2020_in_UTC?3.22%20release%20date): Release

- [x] From the [release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns), merge the release-publishing PRs created previously.
  - For [sourcegraph](https://github.com/sourcegraph/sourcegraph), also:
    - [x] Cherry pick the release-publishing PR from `sourcegraph/sourcegraph@main` into the release branch.
- [x] Ask the product team to merge the blog post ([example](https://github.com/sourcegraph/about/pull/83)). Add the pull request to the release campaign:
  ```sh
  yarn run release release:add-to-campaign sourcegraph/about <pr-number>
  ```
- [x] Finalize and announce that the release is live:
  ```sh
  yarn run release release:close
  ```

### Post-release

- [x] Notify the next release captain that they are on duty for the next release. They should complete the steps in this section.
- [x] Open a PR to update `dev/release/config.json` with the parameters for the current release.
- [x] Run `yarn build` to rebuild the release script.
- [x] Create release calendar events, tracking issue, and announcement for next release:
  ```sh
  # Add calendar events and reminders for key dates in the release cycle
  yarn run release tracking:release-timeline

  # Create the release tracking issue (i.e., this issue)
  yarn run release tracking:release-issue
  ```
- [x] Close this issue.
- [ ] Close the milestone.

**Note:** If a patch release are requested after the release, ask that a [patch request issue](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=&labels=team%2Fdistribution&template=request_patch_release.md&title=3.22.1%3A+) be filled out and approved first.

**Comment by bobheadxi** [comment]
Just re-rendered the tracking issue, with `dryRun.trackingIssues: true` in the config:

```
yarn run release tracking:release-issue
```

**Comment by bobheadxi** [comment]
Updated the tracking issue by hand with the changes from https://github.com/sourcegraph/about/pull/1998/files

**Comment by pecigonzalo** [comment]
@bobheadxi just doing `yarn run build` right?

**Comment by bobheadxi** [comment]
> @bobheadxi just doing `yarn run build` right?

in `dev/release`, yep 👍

**Comment by pecigonzalo** [comment]
*3.22.0 has been published*

* Changelog: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#3-22.0
* Release campaign: https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.22.0

@pecigonzalo: Please complete the post-release steps before closing this issue.
