### ISSUE TITLE
Alex Russell-Saw Onboarding plan

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#15187]
### Week 1

Go through [General Onboarding](https://about.sourcegraph.com/handbook/people-ops/onboarding#for-all-new-teammates) and [Engineering Onboarding](https://about.sourcegraph.com/handbook/engineering/onboarding#engineering-onboarding).

- [x] Schedule an architecture deep dive session with @tsenart.
- [x] Schedule a backend development introduction session with @ryanslade (your on-boarding [buddy](https://about.sourcegraph.com/handbook/people-ops/onboarding/buddy-program)).
- [ ] Schedule pairing sessions with @asdine, @flying-robot and @unknwon, get to know each other and hack on whatever is on your plates.
- [x] Meet @efritz and learn about code intelligence.
- [x] Meet @keegancsmith and learn about search.

### Week 2 - 4

Get started with some smaller tasks that should help your learn a lot of our moving pieces. It's OK if some of these take a different time to complete than what you expect!

- [ ] Store indexed alongside cloned in repo #14764
- [x] Sharing of Sourcegraph searches breaks when using GitHub auth #15132
- [x] Include database versions in ping data #14405
- [x] Pair with @flying-robot on *authz: faster repository permissions syncing via GitHub webhook #14917*
- [x] Log Sourcegraph extensions events in BigQuery #15007
- [x] Account update email should mention the instance URL #14751 (added by @unknwon)
- [x] Email disableTLS site config property is misnamed #13043 (added by @unknwon)

**Comment by tsenart** [comment]
You are hereby officially on-boarded!
