### ISSUE TITLE
Campaigns Sprint 4 Tracking issue

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#15289]
### Plan

Our focus is on the highest-priority blockers/issues for our upcoming GA: user tokens, better burndown charts, and docs. We are also planning to create an RFC to help us design and scope our monorepo support: the ability for a single campaign to create multiple changesets in a single repo.
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

**Nov 4 - Nov 17**

- @mrnugget: Probably ~1d unavailable due to QCon
- @LawnGnome: 3d (PTO November 9 and 10; Remembrance Day November 11)
- @chrispine: 1d (RubyConf, Nov 17-19)
- @eseliger: 1-2d (Gophercon, Nov 09-13)

### Tracked issues

@LawnGnome: __3.00d__

Completed: __3.00d__
- [x] (🏁 12 days ago) campaigns: create files/directories that might be mounted into the container with global permissions ([~#365~](https://github.com/sourcegraph/src-cli/issues/365)) 🐛
- [x] (🏁 12 days ago) campaigns: close cidfile before removing it ([~#367~](https://github.com/sourcegraph/src-cli/issues/367)) 🐛
- [x] (🏁 12 days ago) campaigns: restore pre-3.20 instance compatibility ([~#370~](https://github.com/sourcegraph/src-cli/pull/370)) :shipit:
- [x] (🏁 8 days ago) campaigns: use tokens from user_external_accounts when reconciling campaigns ([~#14989~](https://github.com/sourcegraph/sourcegraph/issues/14989)) __1.00d__
- [x] (🏁 8 days ago) campaigns: use the user token for gitserver ([~#15345~](https://github.com/sourcegraph/sourcegraph/issues/15345)) __2.00d__
- [x] (🏁 1 day ago) Add free trial messaging to getting started page and index page ([~#15779~](https://github.com/sourcegraph/sourcegraph/issues/15779); PRs: ~[#15775](https://github.com/sourcegraph/sourcegraph/pull/15775)~)
- [x] (🏁 1 day ago) campaigns: add feature flag to disable regular user usage ([~#15780~](https://github.com/sourcegraph/sourcegraph/issues/15780))

@chrispine: __1.00d__

Completed: __1.00d__
- [x] (🏁 5 days ago) if no namespace is given, default to username ([~#15058~](https://github.com/sourcegraph/sourcegraph/issues/15058)) __1.00d__

@eseliger: __9.00d__

- [ ] Persisted changeset history ([#15891](https://github.com/sourcegraph/sourcegraph/pull/15891)) :shipit:

Completed: __9.00d__
- [x] (🏁 12 days ago) Fix closed draft PRs incorrectly being recognized as draft ([~#15397~](https://github.com/sourcegraph/sourcegraph/pull/15397)) :shipit:
- [x] (🏁 12 days ago) Don't request unused diffStat on campaign ([~#15406~](https://github.com/sourcegraph/sourcegraph/pull/15406)) :shipit:
- [x] (🏁 12 days ago) campaigns: #15101 caused repo-updater startup to block ([~#15128~](https://github.com/sourcegraph/sourcegraph/issues/15128); PRs: ~[#15423](https://github.com/sourcegraph/sourcegraph/pull/15423)~) __0.50d__
- [x] (🏁 12 days ago) GitHub GraphQL ratelimit is not respected ([~#14526~](https://github.com/sourcegraph/sourcegraph/issues/14526); PRs: ~[#15370](https://github.com/sourcegraph/sourcegraph/pull/15370)~) __1.50d__
- [x] (🏁 12 days ago) Query changeset stats from database ([~#15072~](https://github.com/sourcegraph/sourcegraph/pull/15072)) :shipit:
- [x] (🏁 8 days ago) campaigns: add user token settings interface ([~#14990~](https://github.com/sourcegraph/sourcegraph/issues/14990); PRs: ~[#15418](https://github.com/sourcegraph/sourcegraph/pull/15418)~, ~[#15506](https://github.com/sourcegraph/sourcegraph/pull/15506)~) __3.00d__
- [x] (🏁 8 days ago) Remove breadcrumbs from campaigns ([~#15588~](https://github.com/sourcegraph/sourcegraph/pull/15588)) :shipit:
- [x] (🏁 7 days ago) Refactor global areas into a single one ([~#15590~](https://github.com/sourcegraph/sourcegraph/pull/15590)) :shipit:
- [x] (🏁 7 days ago) Bitbucket Server support for user provided campaigns credentials ([~#15583~](https://github.com/sourcegraph/sourcegraph/pull/15583)) :shipit:
- [x] (🏁 7 days ago) Add support for BitbucketServer token credential ([~#15579~](https://github.com/sourcegraph/sourcegraph/issues/15579)) __1.00d__
- [x] (🏁 6 days ago) Local git config may break campaigns ([~#371~](https://github.com/sourcegraph/src-cli/issues/371)) 🐛
- [x] (🏁 6 days ago) Build campaigns empty page ([~#15540~](https://github.com/sourcegraph/sourcegraph/issues/15540); PRs: ~[#15597](https://github.com/sourcegraph/sourcegraph/pull/15597)~) __1.00d__
- [x] (🏁 6 days ago) Ensure ref prefix set for external_branch ([~#15601~](https://github.com/sourcegraph/sourcegraph/pull/15601)) :shipit:
- [x] (🏁 4 days ago) Fix user viewing admin profile fails with permission error ([~#15747~](https://github.com/sourcegraph/sourcegraph/pull/15747)) :shipit:🐛
- [x] (🏁 4 days ago) campaigns: display a banner when previewing a campaign that would require missing user tokens ([~#14991~](https://github.com/sourcegraph/sourcegraph/issues/14991); PRs: ~[#15599](https://github.com/sourcegraph/sourcegraph/pull/15599)~, ~[#15636](https://github.com/sourcegraph/sourcegraph/pull/15636)~) __1.00d__
- [x] (🏁 2 days ago) Faster compute of burndown charts ([~#15756~](https://github.com/sourcegraph/sourcegraph/pull/15756)) :shipit:
- [x] (🏁 2 days ago) Close campaign displays incorrect message ([~#15491~](https://github.com/sourcegraph/sourcegraph/issues/15491); PRs: ~[#15598](https://github.com/sourcegraph/sourcegraph/pull/15598)~) __0.50d__
- [x] (🏁 1 day ago) Pretty print and explain has no diff error ([~#15799~](https://github.com/sourcegraph/sourcegraph/pull/15799)) :shipit:
- [x] (🏁 1 day ago) Fix console warning about wrong language ([~#15801~](https://github.com/sourcegraph/sourcegraph/pull/15801)) :shipit:
- [x] (🏁 1 day ago) Change wording of "No action will be taken on apply" in preview ([~#14155~](https://github.com/sourcegraph/sourcegraph/issues/14155); PRs: ~[#15806](https://github.com/sourcegraph/sourcegraph/pull/15806)~) __0.50d__
- [x] (🏁 1 day ago) Add tabs to campaign list pages to reach getting started ([~#15805~](https://github.com/sourcegraph/sourcegraph/pull/15805)) :shipit:

@mrnugget: __7.50d__

Completed: __7.50d__
- [x] (🏁 12 days ago) Ctrl-c in `src campaign preview|apply` doesn't kill unresponsive containers ([~#15314~](https://github.com/sourcegraph/sourcegraph/issues/15314)) __1.00d__ 🐛
- [x] (🏁 11 days ago) ErrPublishSameBranch in reconciler should hard fail changesets ([~#15373~](https://github.com/sourcegraph/sourcegraph/issues/15373)) __0.50d__
- [x] (🏁 8 days ago) Allow non-site-admins to create campaigns, campaign specs and changeset specs ([~#15310~](https://github.com/sourcegraph/sourcegraph/issues/15310)) __1.00d__
- [x] (🏁 7 days ago) Add support for BitbucketServer token credential ([~#15579~](https://github.com/sourcegraph/sourcegraph/issues/15579)) __1.00d__
- [x] (🏁 7 days ago) Collect metrics for campaigns funnel  ([~#15482~](https://github.com/sourcegraph/sourcegraph/issues/15482); PRs: ~[#15617](https://github.com/sourcegraph/sourcegraph/pull/15617)~)
- [x] (🏁 6 days ago) Bump src-cli version and update docs to reflect new version ([~#15645~](https://github.com/sourcegraph/sourcegraph/pull/15645)) :shipit:
- [x] (🏁 4 days ago) Extend CampaignsUsageStatistics with count of specs and diff stats ([~#15278~](https://github.com/sourcegraph/sourcegraph/issues/15278)) __2.00d__
- [x] (🏁 4 days ago) src-cli out of bounds panic ([~#15719~](https://github.com/sourcegraph/sourcegraph/issues/15719))
- [x] (🏁 today) Clean up and extend the campaigns how-tos in the docs ([~#15311~](https://github.com/sourcegraph/sourcegraph/issues/15311)) __2.00d__

@rrhyne

Completed
- [x] (🏁 11 days ago) Determine location for campaign user tokens ([~#15347~](https://github.com/sourcegraph/sourcegraph/issues/15347))
- [x] (🏁 11 days ago) Campaigns home page empty state ([~#15341~](https://github.com/sourcegraph/sourcegraph/issues/15341))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by LawnGnome** [comment]
#### Weekly status: 2020-10-27 to 2020-11-02

Last week, I focused primarily on [plumbing user token support through the reconciler](https://github.com/sourcegraph/sourcegraph/issues/14989). As of the writing of this update, [a draft PR](https://github.com/sourcegraph/sourcegraph/pull/15301) is up, although I already know there are some changes required. I also wrote up [the higher level plan](https://docs.google.com/document/d/1AM37p6WoHh01R403BYnqguQQgeXEaBYEvd6s_ldTOAA/edit?usp=sharing) for this project, and created [a Kanban board for tracking purposes](https://github.com/sourcegraph/sourcegraph/projects/7).

This week, I'll be finishing the reconciler work, and then moving on to ensuring that we use user tokens when pushing commits to the code host.

**Comment by mrnugget** [comment]
### Weekly Update

I started my sprint by focusing on the add-campaigns-analytics tasks (https://github.com/sourcegraph/sourcegraph/pull/15279, https://github.com/sourcegraph/analytics/pull/71, https://github.com/sourcegraph/analytics/pull/67), because those need reviews from the analytics team and I wanted to have the PRs ready as soon as possible. I think I'll be able to merge them either later today or tomorrow. I also fixed an issue a customer discovered (https://github.com/sourcegraph/sourcegraph/pull/15536), a bug in src-cli (https://github.com/sourcegraph/src-cli/pull/369) and cleaned up error handling in the reconciler (https://github.com/sourcegraph/sourcegraph/pull/15528).

Yesterday I rebased & merged the user-tokens PRs that Adam got ready last Friday. After seeing the code and thinking that it shouldn't be too hard and would save us adding a bunch of "except..." to our docs, Erik and I, with Erik driving, added support for Bitbucket Server tokens to the implementations. That 
PR got merged today.

That means: user-token support on `main` is ready to go! The basic functionality works. Now we can document it, add a changelog entry (!), extend the UI etc.

Besides that I reviewed a lot of code and tried to help out customers trying to run campaigns, so I didn't get to the "deep work" tasks that I have for this sprint: writing an RFC for multiple-changesets-in-repositories and polishing our campaigns documentation.

I want to make that my focus this week (after merging the analytics PRs).

**Comment by eseliger** [comment]
Last week, I finally got the rate-limiting work in. Afterwards, I went on and started on the work for campaigns user credentials, and implemented the API and UI for that. Afterwards, Thorsten and I paired on expanding the implementation to also include bitbucket server. Today, I started working on most of the remaining tickets in short spikes to see which ones we can get in the fastest, so we can confidently say if time is pressing. Besides that, I made some small low-hanging fruit improvements to performance and added a migration that I wanted to get in before the release.

This week, I plan to finalize the campaigns empty page, add a banner to suggest token setup prior to applying the spec, and tinker around with the burndown chart to polish it a bit for the release.

**Comment by mrnugget** [comment]
### Weekly Update

I spent the last week writing [RFC 265 WIP: Multiple changesets per repository](https://docs.google.com/document/d/1cXEuUdYJeK-uwZpowhorPGSAUfE87QkaLbf9r_EVRfI/edit) and polishing our campaigns documentation. The documentation overhaul is complete with only one PR still waiting for a review.

The RFC is still in WIP and I want to continue working on it this week. I made progress in checking the technical feasibility and current limitations of having multiple changesets in one repository and wrote down the problem statement after untangling different ideas and concepts. The good news: our backend is already ready for multiple-changesets-per-repo, but our campaign specs and src-cli are not. The biggest question mark: how do we define in our campaign spec that multiple changesets should be created and how do we assign multiple branches to them? My goal is to answer that question in this next sprint.

Besides that there was a lot of customer support (responding to Slack messages, evaluating feedback, triaging bugs, etc.) and yesterday we got our first official campaigns customer!

We have sprint planning for Sprint 5 later today, but it looks like, besides working on the RFC, I'll spend my time on fixing a few smaller tickets and leaving enough Slack to help customers with campaigns and fix bugs.
