### ISSUE TITLE
Breaders: Tracking issue

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#15431]
### Plan

Tracks all the issues connected to headers and breadcrumbs updates

[Figma](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=624%3A229)

### Tracked issues

@felixfbecker: __2.50d__

Completed: __2.50d__
- [x] (🏁 75 days ago) Remove 'Home>Repositories' breadcrumbs from the code-oriented pages ([~#15433~](https://github.com/sourcegraph/sourcegraph/issues/15433); PRs: ~[#15920](https://github.com/sourcegraph/sourcegraph/pull/15920)~) __0.50d__
- [x] (🏁 75 days ago) Remove breadcrumbs from web-oriented pages ([~#15432~](https://github.com/sourcegraph/sourcegraph/issues/15432); PRs: ~[#15919](https://github.com/sourcegraph/sourcegraph/pull/15919)~) __0.50d__
- [x] (🏁 60 days ago) Add icon to the repository name breadcrumb ([~#15435~](https://github.com/sourcegraph/sourcegraph/issues/15435); PRs: ~[#16401](https://github.com/sourcegraph/sourcegraph/pull/16401)~) __0.50d__
- [x] (🏁 60 days ago) Make repo name and file name (the last breadcrumb) bold ([~#15437~](https://github.com/sourcegraph/sourcegraph/issues/15437); PRs: ~[#16401](https://github.com/sourcegraph/sourcegraph/pull/16401)~) __0.50d__
- [x] (🏁 60 days ago) Move repository settings to repository page ([~#15438~](https://github.com/sourcegraph/sourcegraph/issues/15438); PRs: ~[#16401](https://github.com/sourcegraph/sourcegraph/pull/16401)~) __0.50d__

@umpox: __0.50d__

Completed: __0.50d__
- [x] (🏁 3 days ago) Update the header component ([~#15563~](https://github.com/sourcegraph/sourcegraph/issues/15563))
- [x] (🏁 3 days ago) Make the new header responsive ([~#15564~](https://github.com/sourcegraph/sourcegraph/issues/15564))
- [x] (🏁 today) Move extension thumbnail to the details column on extension details page ([~#15567~](https://github.com/sourcegraph/sourcegraph/issues/15567)) __0.50d__
- [x] (🏁 today) Add updated header to the pages (list in the description) ([~#15565~](https://github.com/sourcegraph/sourcegraph/issues/15565))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by umpox** [comment]
Closing as all tracked issues are complete 🎉
