### ISSUE TITLE
Team Security Tracking: RFC249 Secret Management Tracking

### ISSUE THREAD

**Issue by chayim** [sourcegraph/sourcegraph#15452]
### Plan

Required work for RFC 249. Nice to have work that's relevant to this work tracked in #15475 
https://docs.google.com/document/d/1HzO7szEm-h4fqlQOnVbcJdpDmfQiM7Rb-Tz4CMEYl-Q/edit?usp=sharing

Main work sequence order of operations
#17793 -> #17797 -> #17801 -> #17802 -> #17803 -> #17804 -> [#17806, #17807] -> #17808 -> #17809 -> [#17810, #17811] -> #17812 -> #17813 -> #17814 -> #17815

[How to do secrets](https://docs.google.com/document/d/1WLxLEns1IrZvfGM66M_7Z7gDBjOSdAl-A6pQUIL6MVQ/edit#)
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/17814 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/17815 

Completed
- [x] (🏁 229 days ago) https://github.com/sourcegraph/sourcegraph/issues/16332 
- [x] (🏁 229 days ago) https://github.com/sourcegraph/sourcegraph/issues/15455 
- [x] (🏁 228 days ago) https://github.com/sourcegraph/sourcegraph/issues/17796 
- [x] (🏁 201 days ago) https://github.com/sourcegraph/sourcegraph/issues/17793 
- [x] (🏁 193 days ago) https://github.com/sourcegraph/sourcegraph/issues/17797 
- [x] (🏁 193 days ago) https://github.com/sourcegraph/sourcegraph/issues/17801 
- [x] (🏁 193 days ago) https://github.com/sourcegraph/sourcegraph/issues/17802 
- [x] (🏁 183 days ago) https://github.com/sourcegraph/sourcegraph/issues/17803 
- [x] (🏁 155 days ago) https://github.com/sourcegraph/sourcegraph/issues/17804 
- [x] (🏁 155 days ago) https://github.com/sourcegraph/sourcegraph/issues/17806 
- [x] (🏁 155 days ago) https://github.com/sourcegraph/sourcegraph/issues/17807 
- [x] (🏁 155 days ago) https://github.com/sourcegraph/sourcegraph/issues/17808 
- [x] (🏁 152 days ago) https://github.com/sourcegraph/sourcegraph/issues/17809 
- [x] (🏁 152 days ago) https://github.com/sourcegraph/sourcegraph/issues/17810 
- [x] (🏁 152 days ago) https://github.com/sourcegraph/sourcegraph/issues/17811 
- [x] (🏁 152 days ago) https://github.com/sourcegraph/sourcegraph/issues/17812 
- [x] (🏁 127 days ago) https://github.com/sourcegraph/sourcegraph/issues/17813 

@ElizabethStirling: __1.50d__

- [x] https://github.com/sourcegraph/sourcegraph/issues/17046 

Completed: __1.50d__
- [x] (🏁 287 days ago) https://github.com/sourcegraph/sourcegraph/issues/15453  __1.50d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
