### ISSUE TITLE
Team Security Tracking: RFC249 part 2 Secret Management Tracking

### ISSUE THREAD

**Issue by ElizabethStirling** [sourcegraph/sourcegraph#15475]
### Plan

Nice to have work on RFC 249. Required work tracked in #15452 

Additional work may be discovered in #17815

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@unassigned: __22.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/15464  __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/15465  __5.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/15466  __3.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/16496 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/17816 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/17817 

Completed: __12.00d__
- [x] (🏁 1008 days ago) https://github.com/sourcegraph/sourcegraph/issues/15462  __3.00d__
- [x] (🏁 1008 days ago) https://github.com/sourcegraph/sourcegraph/issues/15476 
- [x] (🏁 1008 days ago) https://github.com/sourcegraph/sourcegraph/issues/15459  __2.00d__
- [x] (🏁 1008 days ago) https://github.com/sourcegraph/sourcegraph/issues/15460  __5.00d__
- [x] (🏁 1008 days ago) https://github.com/sourcegraph/sourcegraph/issues/15463  __2.00d__

@ElizabethStirling

- [ ] https://github.com/sourcegraph/sourcegraph/issues/16487 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
