### ISSUE TITLE
Team Security Tracking: Vulnerability scan and analysis

### ISSUE THREAD

**Issue by ElizabethStirling** [sourcegraph/sourcegraph#15477]
### Plan

NOTE: this estimate does not include the triaging and fixing of issues, since that should be graduated to a tracking issue once the rest of the issues here are complete.

### Tracked issues

@unassigned: __4.00d__

Completed: __4.00d__
- [x] (🏁 47 days ago) One-time scan of external attack surface ports ([~#15478~](https://github.com/sourcegraph/sourcegraph/issues/15478)) __2.00d__
- [x] (🏁 today) One-time scan of compute nodes ([~#15479~](https://github.com/sourcegraph/sourcegraph/issues/15479)) __2.00d__

@ElizabethStirling: __3.00d__

Completed: __3.00d__
- [x] (🏁 53 days ago) Triage issues in Google Security Command center, close easy wins ([~#15542~](https://github.com/sourcegraph/sourcegraph/issues/15542)) __3.00d__

@chayim: __2.00d__

Completed: __2.00d__
- [x] (🏁 58 days ago) Vulnerability scans of all insiders containers ([~#13551~](https://github.com/sourcegraph/sourcegraph/issues/13551)) __2.00d__
- [x] (🏁 today) Triage and fix vulnerabilities, ensure important vulnerabilities fixed ([~#15480~](https://github.com/sourcegraph/sourcegraph/issues/15480))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by ElizabethStirling** [comment]
Closed as all items are complete
