### ISSUE TITLE
Python language support via extension

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1556]
This is part of the larger initiative of improving language support in 2019: https://github.com/sourcegraph/sourcegraph/issues/1551

- Language server: https://github.com/Microsoft/python-language-server
- WIP fork: https://github.com/sourcegraph/python-language-server/tree/wip2
- WIP extension
  - Extension https://sourcegraph.com/extensions/sourcegraph/python
  - Repository https://github.com/sourcegraph/sourcegraph-python

## Milestones

- [ ] Make a [test plan](https://github.com/sourcegraph/sourcegraph/blob/master/doc/dev/proposals/2018-12-20-improving-language-support-in-2019.md#test-plan)
- [x] (already implemented by @sqs) Add WebSocket support https://github.com/Microsoft/python-language-server/commit/79faae45a77e702d46af8068ff2724a39a8c28f1
- [x] (already implemented by @sqs) Add zip archive fetching support https://github.com/Microsoft/python-language-server/commit/79faae45a77e702d46af8068ff2724a39a8c28f1
- [ ] Deploy to Sourcegraph.com with TLS via ingress and add k8s config to the infrastructure repository
- [ ] Implement dependency fetching
- [ ] Cross repository support
- [ ] Upstream the changes to https://github.com/Microsoft/python-language-server

**Comment by chrismwendt** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/959
