### ISSUE TITLE
WIP: Cloud Milestone 3 Tracking issue

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#15610]
## Milestone 3: Any user can add public code from GitHub.com and GitLab.com

- [View on ProductBoard](https://sourcegraph.productboard.com/feature-board/2119755-cloud/)
- [GitHub Project](https://github.com/orgs/sourcegraph/projects/108)

### Tracked issues

@unassigned

Completed
- [x] (🏁 106 days ago) Search contexts for Cloud ([~#15623~](https://github.com/sourcegraph/sourcegraph/issues/15623))
- [x] (🏁 69 days ago) Update "not set" icon for code host connections ([~#17164~](https://github.com/sourcegraph/sourcegraph/issues/17164)) 🧶
- [x] (🏁 27 days ago) Update gitserver to stop passing the token in clone_url. ([~#18057~](https://github.com/sourcegraph/sourcegraph/issues/18057)) 🔒
- [x] (🏁 6 days ago) No entrypoint for managing repos if the user hasn't added a code host ([~#19161~](https://github.com/sourcegraph/sourcegraph/issues/19161); PRs: ~[#19175](https://github.com/sourcegraph/sourcegraph/pull/19175)~)

@artemruts: __5.00d__

Completed: __5.00d__
- [x] (🏁 111 days ago) Update email settings UI and handle account reunification ([~#15409~](https://github.com/sourcegraph/sourcegraph/issues/15409)) __2.00d__
- [x] (🏁 74 days ago) Code Hosts: update existing page and add modal for user tokens. ([~#16325~](https://github.com/sourcegraph/sourcegraph/issues/16325)) __3.00d__
- [x] (🏁 21 days ago) Users can create and manage code host connections ([~#15399~](https://github.com/sourcegraph/sourcegraph/issues/15399))
- [x] (🏁 today) Implement Pre-GA of public repositories for users ([~#17987~](https://github.com/sourcegraph/sourcegraph/issues/17987))

@arussellsaw

Completed
- [x] (🏁 111 days ago) Users can add their repositories from connected code hosts ([~#15401~](https://github.com/sourcegraph/sourcegraph/issues/15401))
- [x] (🏁 102 days ago) Fetch affiliated repos from code hosts for repo selection screen. ([~#16501~](https://github.com/sourcegraph/sourcegraph/issues/16501))
- [x] (🏁 71 days ago) Manage repositories/select repos to sync in user settings. ([~#16326~](https://github.com/sourcegraph/sourcegraph/issues/16326))
- [x] (🏁 62 days ago) Add async job indicator when saving changes in the 'Manage Repositories' page ([~#17240~](https://github.com/sourcegraph/sourcegraph/pull/17240)) :shipit:
- [x] (🏁 61 days ago) User <-> Public Repo mapping table ([~#17048~](https://github.com/sourcegraph/sourcegraph/issues/17048))
- [x] (🏁 41 days ago) Add a package for the Key interface ([~#18049~](https://github.com/sourcegraph/sourcegraph/issues/18049))
- [x] (🏁 36 days ago) Create a Key implementation for Cloud KMS ([~#18053~](https://github.com/sourcegraph/sourcegraph/issues/18053)) 🔒
- [x] (🏁 25 days ago) Encrypt ExternalService config before writing to the DB ([~#18059~](https://github.com/sourcegraph/sourcegraph/issues/18059))
- [x] (🏁 11 days ago) Update ExternalService.Configuration() to decrypt the config json blob if it's encrypted. ([~#18058~](https://github.com/sourcegraph/sourcegraph/issues/18058)) 🔒
- [x] (🏁 8 days ago) Add 'public repos by url' to manage repositories screen ([~#18600~](https://github.com/sourcegraph/sourcegraph/issues/18600))
- [x] (🏁 6 days ago) Public repos are not listed in UserSettingsRepositoryPage if the user doesn't also have repos added via a code host. ([~#19162~](https://github.com/sourcegraph/sourcegraph/issues/19162); PRs: ~[#19175](https://github.com/sourcegraph/sourcegraph/pull/19175)~)

@asdine: __1.00d__

- [ ] GraphQL DeleteExternalService query takes ~20 seconds or returns 5XX errors ([#18730](https://github.com/sourcegraph/sourcegraph/issues/18730))

Completed: __1.00d__
- [x] (🏁 112 days ago) Support filtering repos by owner in API ([~#15488~](https://github.com/sourcegraph/sourcegraph/issues/15488)) __1.00d__

@flying-robot: __1.00d__

Completed: __1.00d__
- [x] (🏁 68 days ago) Do not overwrite display name and avatar URL when not empty ([~#17086~](https://github.com/sourcegraph/sourcegraph/issues/17086); PRs: ~[#17257](https://github.com/sourcegraph/sourcegraph/pull/17257)~) __1.00d__

@quinnkeast

Completed
- [x] (🏁 62 days ago) Handling async repo list fetching ([~#16948~](https://github.com/sourcegraph/sourcegraph/issues/16948); PRs: ~[#17240](https://github.com/sourcegraph/sourcegraph/pull/17240)~)

@ryanslade: __5.00d__

Completed: __5.00d__
- [x] (🏁 130 days ago) All accounts always have a confirmed primary email address ([~#15274~](https://github.com/sourcegraph/sourcegraph/issues/15274)) __1.00d__
- [x] (🏁 130 days ago) User can set primary email ([~#15393~](https://github.com/sourcegraph/sourcegraph/issues/15393)) __1.00d__
- [x] (🏁 104 days ago) Handle revoked tokens during sync ([~#15739~](https://github.com/sourcegraph/sourcegraph/issues/15739)) __1.00d__
- [x] (🏁 74 days ago) Limit non-admin user to a single external service per code host ([~#16885~](https://github.com/sourcegraph/sourcegraph/issues/16885)) __1.00d__
- [x] (🏁 71 days ago) Add number of synced repos to externalServices GraphQL resolver  ([~#16729~](https://github.com/sourcegraph/sourcegraph/issues/16729)) __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by tsenart** [comment]
We're tracking this work in https://github.com/orgs/sourcegraph/projects/148 with the cloud/milestone-3 label.
