### ISSUE TITLE
Distribution: 2020.11.16 - Elegant Sardine

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#15710]
#### [Support new and existing deployments](https://github.com/orgs/sourcegraph/projects/74)

This is an ongoing expense, we anticipate this taking no more than 5d of work spread across the entire team.

#### [Releases are created in a single day](https://github.com/orgs/sourcegraph/projects/90)

We have include E2E, QA and multiple other manual tests in our automated tests pipelines, but we have found several tests need to be updated or fixed. We will be working with all teams to fix the tests and get a stable pipeline.

- @davejrt 
- @daxmc99 

#### [Market k8s.sgdev.org internally](https://github.com/orgs/sourcegraph/projects/107)

Make k8s.sgdev.org a compelling destination for Sourcegraph engineers to encourage dogfood. Changes should mostly be surface-level improvements.

- @bobheadxi 
- @pecigonzalo 

#### [Implement 2+ sourcegraph.com services using dhall](https://github.com/orgs/sourcegraph/projects/71)

`sourcegraph.com` sees the highest amount of Kubernetes changes out of all of our deployments + `deploy-sourcegraph`. Scoping a single component limits the customizations that we need to implement and allows for easier onboarding other engineers.

- @ggilmore 
- @uwedeportivo
- @daxmc99 

### Availability

Period is from **November 16rd** to **November 30th (10 working days)**. Please write the days you won't be working and the number of working days for the period.

- @daxmc99 (3d, 25th)
- @ggilmore (1d, 26th)

### Tracked issues

@bobheadxi: __4.00d__

- [ ] deploy-sourcegraph, deploy-sourcegraph-docker: generate update-docker-tags params from allDockerImages list ([#15896](https://github.com/sourcegraph/sourcegraph/issues/15896)) __1.00d__ 🧶

Completed: __3.00d__
- [x] (🏁 13 days ago) k8s.sgdev: update handbook guidance for k8s.sgdev ([~#15511~](https://github.com/sourcegraph/sourcegraph/issues/15511)) __0.50d__
- [x] (🏁 13 days ago) set up automerge for third-party license updates ([~#14766~](https://github.com/sourcegraph/sourcegraph/issues/14766)) __0.50d__ 🎩
- [x] (🏁 8 days ago) release: do not open PRs until all changesets have been created ([~#16015~](https://github.com/sourcegraph/sourcegraph/issues/16015))
- [x] (🏁 3 days ago) upgrade devmanaged.sourcegraph.com to v3.20, v3.21, v3.22 ([~#15173~](https://github.com/sourcegraph/sourcegraph/issues/15173)) __0.50d__
- [x] (🏁 2 days ago) release: update the version in about.sourcegraph.com GetStarted ([~#14111~](https://github.com/sourcegraph/sourcegraph/issues/14111)) __0.50d__
- [x] (🏁 2 days ago) generator: document monitoring generator (features, dev, etc) ([~#15787~](https://github.com/sourcegraph/sourcegraph/issues/15787); PRs: ~[#2000](https://github.com/sourcegraph/about/pull/2000)~) __1.00d__

@christinelovett

- [ ] ~sourcegraph/customer~ ([#145](https://github.com/sourcegraph/customer/issues/145)) 👩

@davejrt: __4.50d__

- [ ] go binary to create sudo token should be more generic ([#15197](https://github.com/sourcegraph/sourcegraph/issues/15197)) __0.50d__ 🧶
- [ ] sourcegraph/customer ([#129](https://github.com/sourcegraph/customer/issues/129)) 👩
- [ ] qa: onboarding tests require manual validation ([#15179](https://github.com/sourcegraph/sourcegraph/issues/15179)) __1.00d__
- [ ] ~sourcegraph/customer~ ([#145](https://github.com/sourcegraph/customer/issues/145)) 👩

Completed: __3.00d__
- [x] (🏁 13 days ago) qa: codeintel tests failing on first run ([~#15165~](https://github.com/sourcegraph/sourcegraph/issues/15165)) __0.50d__
- [x] (🏁 10 days ago) qa: testing external-services fails in CI ([~#15193~](https://github.com/sourcegraph/sourcegraph/issues/15193)) __0.50d__
- [x] (🏁 10 days ago) qa: search qa tests failing in CI ([~#15178~](https://github.com/sourcegraph/sourcegraph/issues/15178)) __0.50d__
- [x] (🏁 10 days ago) qa: auth regression tests are failing ([~#15180~](https://github.com/sourcegraph/sourcegraph/issues/15180)) __1.50d__
- [x] (🏁 4 days ago) ~sourcegraph/customer~ ([~#144~](https://github.com/sourcegraph/customer/issues/144)) 👩

@daxmc99: __7.50d__

- [ ] Use containerd images on clusters ([#15194](https://github.com/sourcegraph/sourcegraph/issues/15194)) __0.50d__ 🕵️
- [ ] Add Postgres dashboards with alerting ([#15029](https://github.com/sourcegraph/sourcegraph/issues/15029)) __1.00d__

Completed: __6.00d__
- [x] (🏁 11 days ago) Automate Kubernetes cluster QA tests ([~#13878~](https://github.com/sourcegraph/sourcegraph/issues/13878)) __1.00d__
- [x] (🏁 6 days ago) add "repo-updater" to service deploy-sourcegraph-dhall, with support for sourcegraph.com customizations ([~#15591~](https://github.com/sourcegraph/sourcegraph/issues/15591)) __5.00d__

@ggilmore

- [ ] Tracking issue: Use dhall on sourcegraph.com ([#13340](https://github.com/sourcegraph/sourcegraph/issues/13340))
  - [x] (🏁 2 days ago) add "symbols" to service deploy-sourcegraph-dhall, with support for sourcegraph.com customizations ([~#14130~](https://github.com/sourcegraph/sourcegraph/issues/14130))
- [ ] write developer friendly documentation for deploy-sourcegraph-dhall architecture ([#14135](https://github.com/sourcegraph/sourcegraph/issues/14135))

Completed
- [x] (🏁 2 days ago) add "symbols" to service deploy-sourcegraph-dhall, with support for sourcegraph.com customizations ([~#14130~](https://github.com/sourcegraph/sourcegraph/issues/14130))

@pecigonzalo: __3.50d__

- [ ] Get approval on "RFC 263: Single-container deployments are for demos only" ([#15484](https://github.com/sourcegraph/sourcegraph/issues/15484))

Completed: __3.50d__
- [x] (🏁 11 days ago) qa: testing core failing in CI ([~#15877~](https://github.com/sourcegraph/sourcegraph/issues/15877); PRs: ~[#15893](https://github.com/sourcegraph/sourcegraph/pull/15893)~) __0.50d__
- [x] (🏁 10 days ago) qa: testing external-services fails in CI ([~#15193~](https://github.com/sourcegraph/sourcegraph/issues/15193)) __0.50d__
- [x] (🏁 10 days ago) qa: auth regression tests are failing ([~#15180~](https://github.com/sourcegraph/sourcegraph/issues/15180)) __1.50d__
- [x] (🏁 6 days ago) k8s.sgdev: set up LSIF uploads for Sourcegraph repositories ([~#15510~](https://github.com/sourcegraph/sourcegraph/issues/15510)) __1.00d__
- [x] (🏁 2 days ago) sourcegraph/infrastructure ([~#2264~](https://github.com/sourcegraph/infrastructure/pull/2264)) :shipit:

@rvantonder: __0.50d__

Completed: __0.50d__
- [x] (🏁 10 days ago) qa: search qa tests failing in CI ([~#15178~](https://github.com/sourcegraph/sourcegraph/issues/15178)) __0.50d__

@slimsag

- [ ] Get approval on "RFC 263: Single-container deployments are for demos only" ([#15484](https://github.com/sourcegraph/sourcegraph/issues/15484))

@unknwon: __0.50d__

Completed: __0.50d__
- [x] (🏁 11 days ago) qa: testing core failing in CI ([~#15877~](https://github.com/sourcegraph/sourcegraph/issues/15877); PRs: ~[#15893](https://github.com/sourcegraph/sourcegraph/pull/15893)~) __0.50d__

@uwedeportivo: __7.00d__

- [ ] Tracking issue: Use dhall on sourcegraph.com ([#13340](https://github.com/sourcegraph/sourcegraph/issues/13340)) __4.00d__
  - [ ] add gitserver to deploy-sourcegraph-dhall, with support for sourcegraph.com customizations ([#14131](https://github.com/sourcegraph/sourcegraph/issues/14131)) __4.00d__
- [ ] gitserver dhall component: document customizations ([#16131](https://github.com/sourcegraph/sourcegraph/issues/16131)) __1.00d__
- [ ] gitserver dhall component: break out internal/generate into kind pieces (statefulset, service and pvs) ([#16132](https://github.com/sourcegraph/sourcegraph/issues/16132)) __1.00d__
- [ ] jaeger dhall sidecar: lift out shared parts and shared customizations ([#16133](https://github.com/sourcegraph/sourcegraph/issues/16133)) __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by pecigonzalo** [comment]
**Last week**
Last week was mostly meetings and catching up with conversations as I was in parallel attending GopherCon. I managed to land the new CORS proxy with some extra features and enable that to unblock the Web team.
We also had many conversations with @bobheadxi @tsenart and other engineers around our monitoring dashboards and how can we improve the development workflow for them while maintaining some of the features we currently have as well as ensuring we ship useful customer dashboards.

**This week**
Ill be working on releasing Sourcegraph so ill be mostly focused on that as well as enabling LSIF uploads for k8s.sgdev.org. I would also try to update our Goals with any relevant updates.

**Comment by davejrt** [comment]
**Last week**
Last week was mostly troubeshooting QA tests, with some success. I did some of the sessions for gophercon but found a lot of it a little to advanced for my current level, and probably didn't fully dedicate myself to only doing GO whilst it was on. 
There are a number of outstanding failures in the qa tests, one of which in search appears to be a small regression, but I have updated that issue with the notes to work with them to get this resolved. 
I helped out @daxmc99 with some of his k8s testing, mostly bouncing ideas around and working with him to get his tests running in CI. 
I was also on a number of calls trying to help out on a customer issue https://github.com/sourcegraph/customer/issues/129

**This week**

Helping out @pecigonzalo with his first release and working on the remaining tests with other teams. Also following up on https://github.com/sourcegraph/customer/issues/129 once i receive more info regarding their infrastructure.

**Comment by daxmc99** [comment]
**Last Week**
Getting our QA tests to work at the cluster level (thanks @davejrt). 
Began an innovation task of trying out containerd on our cluster nodes to see if there a decrease in our steady-state resource usage. 
Paired with Keegan to upgrade our k8s client. 
Attended Gophercon.

**This week**
Working with @uwedeportivo & @ggilmore to implement more services in Dhall.

**Comment by davejrt** [comment]
**Last week**
A lot of chipping away at the release process (so much better thanks to @bobheadxi ) with @pecigonzalo and helping out with tests and determining which errors are real vs flakey ci tests or timeouts. I spotted a few small bugs at fixed those is deploy-sourcegraph-docker and other places. Some time was spent helping on https://github.com/sourcegraph/customer/issues/129

**This week**
Working through the last of the issues with tests, I suspect some fine tuning is required for e2e but I expect fully functional e2e and qa testing in CI. I'll need to follow up on customer issues and then I'd really like to start my debt task of making the go init tool for clusters slightly more generic.

**Comment by uwedeportivo** [comment]
last week

paired up with geoffrey and dax on dhall component writing. have to say i enjoy the sessions and i'm learning a lot there. we're also making big progress and because it's a synchronous session, we make decisions quickly and put in place what's needed. 

helped installing a workaround for a cap1 issue (they couldn't delete the QA external service and switch over to prod).

worked a little on the license generator key rotation but we decided to give up and leave it leaked. the damage from introducing a bug there is greater than the damage from the leak.

worked a little on the deploy-sourcegraph to dhall tooling. there is opportunity there to make our tools more powerful but it's not high priority. more important is that we land all base components.

this week

pair up with geoffrey and dax again and land as much components as we can.

**Comment by pecigonzalo** [comment]
**Last week**
Mostly focused on releasing 3.22.0 and not much more as I was recovering 😷 I also drafted a initial port of a Gerrit deployment for the Web team as well as helping Security with an staging Vault deployment so they can start testing. We need to review these last two things in the Distribution meeting.

**This week**
This week ill mostly focus on catching up with PRs, next steps after release, closing the LSIF task and any other tasks pending before we leave for Thanksgiving.

**Team update**
🦃 Thanksgiving is later down this week and many of us will be offline.

**Comment by daxmc99** [comment]
**Last Week**
Paired with @uwedeportivo & @ggilmore to get up to speed on Dhall and write repo-updater (https://github.com/sourcegraph/deploy-sourcegraph-dhall/pull/13) 
Reviewed the @sourcegraph/security Vault implementation 
Minor fixups for Cluster-QA test which are currently running successfully

**This Week**
Closing out remaining tasks
- `containerd` deployments have rolled out on dogfood with any negative consequences. Container start times are down across the board. I think this is a safe change for our production instances.
- Postgres dashboard ( this has taken a bit longer since we now deploy 2 databases ) 
- Land dhall changes

🦃  I will be taking 11/25 - 11/28 off  (besides on-call responsibilities)

**Comment by ggilmore** [comment]
Last Week:

I've been laser focused on helping @daxmc99 onboard to deploy-sourcegraph-dhall via implementing repo-updater: https://github.com/sourcegraph/deploy-sourcegraph-dhall/pull/13 Pairing with both him and @uwedeportivo has been fantastic, and it's a great validation of our new initiative to pair more on the team.

This Week: 

We just merged https://github.com/sourcegraph/deploy-sourcegraph-dhall/pull/13, and we have some follow up tasks to prepare the repo for the rest of @sourcegraph/distribution to contribute:

- Write a markdown document for each service that documents both the available customizations along with copy-paste examples for the pipeline file. 
- Decouple the `Configuration/internal` type definitions and create separate `Configuration/Deployment/interal` defniitions that we can still bundle up in `Configuration/internal`. This also allows us to reference these smaller definitions in the `.../generate` functions - this allows us to use smaller interfaces and makes it easier to write tests 
- Refactor the jaeger sidecar logic 
- (stretch) Write tests for each customization

**Comment by pecigonzalo** [comment]
🚀 All tasks in **[Market k8s.sgdev.org internally](https://github.com/orgs/sourcegraph/projects/107)** are done!

**Comment by bobheadxi** [comment]
**last week**

Release debugging, release bug fixes, release changes. Live coding session for cluster QA tests and some other minor changes to the QA/E2E pipelines. Misc PRs: buildkite image publishing refactor, generator refactor, annotations experiment, etc.

**this week**

Try not to get sidetracked and focus on just finishing off my planned tasks.

**Comment by davejrt** [comment]
**Last week**

Debugging customer issues related to failed migrations and consequently a good bit of time refactoring some of deploy-sourcegraph-docker to pick log better error messages during failures. 

**This week**
Working on some debt/quality of life issues and look into the consistent migration failures in the deploy-sourcegraph-docker tests. This isn't the only place I've seen issues with migrations popping up recently so I think this is worth following up. Follow up on any remaining tasks for single day releases.

**Comment by ggilmore** [comment]
Last week: 

- I spent most of my time pairing with @daxmc99  and @uwedeportivo  to get repo-updater over the finish line. 
- I also paired with @pecigonzalo  and @davejrt  on Gerrit and the E2E tests respectively
- Finished up the documentation for the symbols service configuration  
- Sent customer email for @sourcegraph/customer-engineering review 
- Assisted with the sourcegraph.com downtime 

Next week:

- (Likely) will do individual pairing sessions onboard the rest of the team for the remaining services
- Monday - Do some cleanup with the configuration types
- Follow up with @sourcegraph/customer-engineering about messaging admins 
- I discovered a performance regression in dhall 1.36.0 with `with` statements. Rolling back to `1.35.0` fixes. I'm going to try to setup a reproduction test case so that I can submit a bug report

**Comment by bobheadxi** [comment]
**last week**

Landed dev/ci move, universal NOCLEANUP in `deploy-sourcegraph`, monitoring pillars, generator refactors (moving the generator itself, moving definitions) and documentation (generated API reference + intro to the generator: https://github.com/sourcegraph/sourcegraph/tree/main/monitoring), added about.sourcegraph.com updates to release tooling, 3x devmanaged upgrades. Opened a set of PRs for my last task in this sprint: https://github.com/sourcegraph/sourcegraph/issues/15896

**this week**

Take another look at the state of dhall work, since that seems to be an emphasis for the upcoming sprint. There are also two mini-tracking issues active with some low-hanging fruit for work on releases and monitoring (https://github.com/sourcegraph/sourcegraph/issues/16207, https://github.com/sourcegraph/sourcegraph/issues/16117 respectively) that I might take a look at.

I believe all our managed instances are due for an upgrade to 3.22 as well, will look into if we have issues for these. I mentioned in one of my daily updates possible improvements to the process - opened https://github.com/sourcegraph/sourcegraph/issues/16228 to track this

**Comment by daxmc99** [comment]
**Last Week**
Vacation for 🦃 
Merged dhall repo-updater component
Sourcegraph.com outage, created ops-incident here https://docs.google.com/document/d/1dtrOHs5STJYKvyjigL1kMm6u-W0mlyRSyVxPfKIOfEw/edit#bookmark=id.y7u0ufhvuzk

**This week**
Implement takeaway from outage to add an alert to the Postgres dashboard if the db schema is dirty
Continue dhall work
