### ISSUE TITLE
Cloud 2020-11-18 Tracking issue

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#15753]
### Period

From 2020-11-18 to 2020-12-01. Sourcegraph **3.22** and **3.23** release window.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

- @flying-robot 11/23 - 11/27 (Thanksgiving week)

### Tracked issues

@artemruts: __2.00d__

- [ ] Update email settings UI and handle account reunification ([#15409](https://github.com/sourcegraph/sourcegraph/issues/15409); PRs: [#15778](https://github.com/sourcegraph/sourcegraph/pull/15778)) __2.00d__

@arussellsaw: __4.00d__

- [ ] Unable to add a repository which has a plus sign (+) in the URL ([#15079](https://github.com/sourcegraph/sourcegraph/issues/15079))

Completed: __4.00d__
- [x] (🏁 13 days ago) authz: faster repository permissions syncing via GitHub webhook ([~#14917~](https://github.com/sourcegraph/sourcegraph/issues/14917)) __2.00d__ 🕵️
- [x] (🏁 13 days ago) Migrate campaigns webhooks to new scaffolding / infrastructure ([~#15337~](https://github.com/sourcegraph/sourcegraph/issues/15337)) __2.00d__
- [x] (🏁 today) Repositories view in settings ([~#15401~](https://github.com/sourcegraph/sourcegraph/issues/15401); PRs: ~[#16236](https://github.com/sourcegraph/sourcegraph/pull/16236)~)

@asdine: __0.50d__

Completed: __0.50d__
- [x] (🏁 7 days ago) Merge external service types ([~#16115~](https://github.com/sourcegraph/sourcegraph/pull/16115)) :shipit:
- [x] (🏁 6 days ago) Allow synchronization of private repos if owner has AllowUserExternalServicePrivate tag ([~#16023~](https://github.com/sourcegraph/sourcegraph/issues/16023); PRs: ~[#16123](https://github.com/sourcegraph/sourcegraph/pull/16123)~) __0.50d__ 🐛
- [x] (🏁 5 days ago) Move tag checking logic to User store ([~#16166~](https://github.com/sourcegraph/sourcegraph/pull/16166)) :shipit:

@flying-robot: __4.00d__

Completed: __4.00d__
- [x] (🏁 13 days ago) authz: faster repository permissions syncing via GitHub webhook ([~#14917~](https://github.com/sourcegraph/sourcegraph/issues/14917)) __2.00d__ 🕵️
- [x] (🏁 13 days ago) Migrate campaigns webhooks to new scaffolding / infrastructure ([~#15337~](https://github.com/sourcegraph/sourcegraph/issues/15337)) __2.00d__
- [x] (🏁 12 days ago) qa: remove tests covered by backend integration/unit tests ([~#15893~](https://github.com/sourcegraph/sourcegraph/pull/15893)) :shipit:🐛

@keegancsmith: __1.00d__

Completed: __1.00d__
- [x] (🏁 1 day ago) Research: Simplify access to repository tokens for gitserver ([~#14910~](https://github.com/sourcegraph/sourcegraph/issues/14910)) __1.00d__ 🔒🕵️🧶

@ryanslade: __4.50d__

- [ ] github-proxy: Instrument mutex contention ([#16312](https://github.com/sourcegraph/sourcegraph/pull/16312)) :shipit:

Completed: __4.50d__
- [x] (🏁 13 days ago) frontend: Log sync error after external service deletion ([~#15911~](https://github.com/sourcegraph/sourcegraph/pull/15911)) :shipit:
- [x] (🏁 12 days ago) db: User owned code host connections should not allow rate limits ([~#15923~](https://github.com/sourcegraph/sourcegraph/pull/15923)) :shipit:
- [x] (🏁 12 days ago) Disallow rate limits on user owned connections ([~#15744~](https://github.com/sourcegraph/sourcegraph/issues/15744)) __0.50d__
- [x] (🏁 8 days ago) sourcegraph/customer ([~#139~](https://github.com/sourcegraph/customer/issues/139)) 👩
- [x] (🏁 7 days ago) repo-updater: Enforce unique constraint on external_service_repos ([~#16022~](https://github.com/sourcegraph/sourcegraph/pull/16022)) :shipit:
- [x] (🏁 5 days ago) User-added repos do not stay indexed on Sourcegraph.com ([~#15820~](https://github.com/sourcegraph/sourcegraph/issues/15820); PRs: ~[#16176](https://github.com/sourcegraph/sourcegraph/pull/16176)~) __1.00d__ 🐛
- [x] (🏁 4 days ago) Deleting external services triggers too many queries ([~#16069~](https://github.com/sourcegraph/sourcegraph/issues/16069); PRs: ~[#16163](https://github.com/sourcegraph/sourcegraph/pull/16163)~) __1.00d__ 🐛
- [x] (🏁 today) Clean up external_service_repos  and external_services table on Sourcegraph.com ([~#15797~](https://github.com/sourcegraph/sourcegraph/issues/15797)) __2.00d__ 🐛
- [x] (🏁 today) db: Drop duplicate index. ([~#16286~](https://github.com/sourcegraph/sourcegraph/pull/16286)) :shipit:

@tsenart: __1.00d__

Completed: __1.00d__
- [x] (🏁 12 days ago) [Cloud] [CRITICAL] gitserver: 2s+ echo command duration test fires regularly ([~#15392~](https://github.com/sourcegraph/sourcegraph/issues/15392); PRs: ~[#15971](https://github.com/sourcegraph/sourcegraph/pull/15971)~)
- [x] (🏁 8 days ago) gitserver: Avoid double HTTP response header writing ([~#16072~](https://github.com/sourcegraph/sourcegraph/pull/16072)) :shipit:
- [x] (🏁 7 days ago) monitoring: Change syntect_server owner to Cloud team ([~#16083~](https://github.com/sourcegraph/sourcegraph/pull/16083)) :shipit:
- [x] (🏁 1 day ago) Research: Simplify access to repository tokens for gitserver ([~#14910~](https://github.com/sourcegraph/sourcegraph/issues/14910)) __1.00d__ 🔒🕵️🧶

@unknwon: __6.00d__

Completed: __6.00d__
- [x] (🏁 12 days ago) Stop truncating microsecond everywhere with a util package ([~#11246~](https://github.com/sourcegraph/sourcegraph/issues/11246); PRs: ~[#15968](https://github.com/sourcegraph/sourcegraph/pull/15968)~) __0.50d__ 🧶
- [x] (🏁 11 days ago) authz: remove authzFilter along with its metric and tests ([~#15731~](https://github.com/sourcegraph/sourcegraph/issues/15731); PRs: ~[#16006](https://github.com/sourcegraph/sourcegraph/pull/16006)~) __1.00d__ 🧶
- [x] (🏁 11 days ago) Remove database secret encryption ([~#15868~](https://github.com/sourcegraph/sourcegraph/issues/15868); PRs: ~[#16008](https://github.com/sourcegraph/sourcegraph/pull/16008)~) __0.50d__ 🔒🧶
- [x] (🏁 8 days ago) external_services: remove migration for unrestricted column in 3.23 ([~#15571~](https://github.com/sourcegraph/sourcegraph/issues/15571); PRs: ~[#16063](https://github.com/sourcegraph/sourcegraph/pull/16063)~) 🧶
- [x] (🏁 7 days ago) Simplify `PermsStore` logic with intarray extension ([~#11768~](https://github.com/sourcegraph/sourcegraph/issues/11768); PRs: ~[#16003](https://github.com/sourcegraph/sourcegraph/pull/16003)~) __1.00d__ 🧶
- [x] (🏁 7 days ago) authz: utilize expired_at and last_valid_at columns of user_external_accounts ([~#16067~](https://github.com/sourcegraph/sourcegraph/pull/16067)) :shipit:
- [x] (🏁 4 days ago) Move aggregated repository statistics to critical telemetry ([~#15883~](https://github.com/sourcegraph/sourcegraph/issues/15883); PRs: ~[#16188](https://github.com/sourcegraph/sourcegraph/pull/16188)~) __0.50d__
- [x] (🏁 4 days ago) Show lines of code in site-admin overview and on the manage repositories page ([~#15125~](https://github.com/sourcegraph/sourcegraph/issues/15125); PRs: ~[#16190](https://github.com/sourcegraph/sourcegraph/pull/16190)~) __1.00d__
- [x] (🏁 4 days ago) External services is not set as unrestricted when "authorization" presents in comment ([~#16068~](https://github.com/sourcegraph/sourcegraph/issues/16068); PRs: ~[#16211](https://github.com/sourcegraph/sourcegraph/pull/16211)~) __0.50d__ 🐛
- [x] (🏁 1 day ago) gqltest: add test for external code host links ([~#16206~](https://github.com/sourcegraph/sourcegraph/issues/16206); PRs: ~[#16231](https://github.com/sourcegraph/sourcegraph/pull/16231)~) __0.50d__
- [x] (🏁 1 day ago) Audit all requests to gitserver and make sure responses are authz checked before responding to users ([~#16191~](https://github.com/sourcegraph/sourcegraph/issues/16191)) __0.50d__ 🔒

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by unknwon** [comment]
> This cycle is going to be shorter for me, so I grabbed two login issues off the bat since they're related / straightforward.

@flying-robot Your workload (7.5d) doesn't look like so 😂

**Comment by arussellsaw** [comment]
This week was mostly getting to grips with the frontend codebase & graphql, but i've made good progress on the repositories settings page. Next week is where the larger uncertainty lies, as there are some elements of the design that will require pretty big changes to the implementation of FilteredConnection used by most list views in the app. I'll chat with @quinnkeast and @felixfbecker next week to see what we think the best approach is.

**Comment by unknwon** [comment]
### Last week

- No more application-level authz for repository permissions, `authzFilter` has been removed.
- Simplified PermsStore logic with intarray extension.

### This week

- Get last approval from `@gonza` for RFC 266: Production testing of all authorization models.
- Finish authz: clean up rows that have broken auth_data in user_external_accounts (#14899)
- Finish moving aggregated repository statistics to critical telemetry (#15883)
- Start work of showing lines of code in site-admin overview and on the manage repositories page (#15125)

**Comment by ryanslade** [comment]
### Last week

* Investigated issues around data stored in our `external_service_repos` table. Cleaned up a lot of the erroneous data and opened a PR to fix the root cause: https://github.com/sourcegraph/sourcegraph/pull/16022
* Investigated a customer issue: https://github.com/sourcegraph/customer/issues/139. Found a workaround and will work on a proper fix next week.

### This week

* Work on proper fix to customer issue above
* Focus on 🐛 issues
* Help with any work needed to unblock @artemruts' frontend changes

**Comment by asdine** [comment]
### Last week

- Investigated an external service sync issue with Github Enterprise https://github.com/sourcegraph/sourcegraph/issues/14907. I didn't manage to find the root cause and asked the author to share more logs. I worked on a PR to make the repo-updater store more solid and to add more logs.

### This week

- Start with bugs and customer issues
- Now that the release is out, finish the ongoing work on repo-updater's store tech debt
- Improve shared stores

**Comment by unknwon** [comment]
### Last week

- Moved git disk size and indexed LoC to pings critical metrics and display in site admin overview.
- Paired with @asdine on breaking up the huge tech debt PR.

### This week

- gqltest: add test for external code host links (#16206)
- Audit all requests to gitserver and make sure responses are authz checked before responding to users (#16191)
- Cycle grooming and planning

**Comment by asdine** [comment]
### Last week

- Paired with @unknwon on breaking up the big repo updater tech debt PR https://github.com/sourcegraph/sourcegraph/pull/15530
- Worked on a few customer issues that either need more context or don't appear to be issues https://github.com/sourcegraph/sourcegraph/issues/15876 https://github.com/sourcegraph/sourcegraph/issues/15763
- Use tag to allow syncing private repositories https://github.com/sourcegraph/sourcegraph/pull/16123

### This week

- Keep working on breaking up the tech debt PR and satellite issues
- National holidays most of the week
