### ISSUE TITLE
Campaigns Sprint 5 Tracking issue

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#15816]
### Availability

Nov 18 - Dec 1

- @mrnugget: 1-2d vacation, probably 26th or 27th Nov
- @LawnGnome: 0.5d vacation (Nov 19)
- @chrispine: 5d (RubyConf, Nov 18-19 & Thanksgiving, Nov 25-27)
- @eseliger: 0d vacation

### Tracked issues

@LawnGnome: __3.00d__

Completed: __3.00d__
- [x] (🏁 12 days ago) cli: better document login process and environment variables ([~#14528~](https://github.com/sourcegraph/sourcegraph/issues/14528)) __1.00d__
- [x] (🏁 12 days ago) doc: replicate src campaign apply -help as a reference page ([~#15882~](https://github.com/sourcegraph/sourcegraph/issues/15882))
- [x] (🏁 12 days ago) Document using tokens in campaigns ([~#15312~](https://github.com/sourcegraph/sourcegraph/issues/15312)) __1.00d__
- [x] (🏁 8 days ago) campaigns: allow environment variables to be passed through from the environment ([~#15822~](https://github.com/sourcegraph/sourcegraph/issues/15822)) __1.00d__

@eseliger: __6.00d__

Completed: __6.00d__
- [x] (🏁 8 days ago) Gitlab: Make SetWIP and UnsetWIP work for both Draft and WIP prefixes ([~#16101~](https://github.com/sourcegraph/sourcegraph/pull/16101)) :shipit:🐛
- [x] (🏁 8 days ago) Always refetch gitlab merge request data after mutation ([~#16100~](https://github.com/sourcegraph/sourcegraph/pull/16100)) :shipit:🐛
- [x] (🏁 8 days ago) Fix draft changeset appearing as OPEN after operationReopen ([~#16102~](https://github.com/sourcegraph/sourcegraph/pull/16102)) :shipit:🐛
- [x] (🏁 8 days ago) Restore backward compatibility with GitHub enterprise 2.20 ([~#16042~](https://github.com/sourcegraph/sourcegraph/pull/16042)) :shipit:
- [x] (🏁 8 days ago) Uploading changeset specs fails with "failed to normalize JSON: yaml: control characters are not allowed" ([~#16081~](https://github.com/sourcegraph/sourcegraph/issues/16081); PRs: ~[#16116](https://github.com/sourcegraph/sourcegraph/pull/16116)~, ~[#16116](https://github.com/sourcegraph/sourcegraph/pull/16116)~) 🐛
- [x] (🏁 7 days ago) Add changelog entry for #16100 ([~#16134~](https://github.com/sourcegraph/sourcegraph/pull/16134)) :shipit:
- [x] (🏁 7 days ago) Migrate changeset rewirer to DB based pattern ([~#16056~](https://github.com/sourcegraph/sourcegraph/issues/16056); PRs: ~[#15686](https://github.com/sourcegraph/sourcegraph/pull/15686)~) __2.50d__
- [x] (🏁 7 days ago) Don't try to update merged changesets on reapply ([~#16128~](https://github.com/sourcegraph/sourcegraph/pull/16128)) :shipit:🐛
- [x] (🏁 6 days ago) Move changesetRewirer into rewirer.go ([~#16151~](https://github.com/sourcegraph/sourcegraph/pull/16151)) :shipit:
- [x] (🏁 6 days ago) Design delta API ([~#16053~](https://github.com/sourcegraph/sourcegraph/issues/16053); PRs: ~[#16178](https://github.com/sourcegraph/sourcegraph/pull/16178)~) __0.50d__
- [x] (🏁 5 days ago) Reconciler not working after changeset errored ([~#16041~](https://github.com/sourcegraph/sourcegraph/issues/16041); PRs: ~[#16144](https://github.com/sourcegraph/sourcegraph/pull/16144)~) __1.00d__ 🐛
- [x] (🏁 5 days ago) Reconciler closes already closed changesets ([~#16148~](https://github.com/sourcegraph/sourcegraph/issues/16148); PRs: ~[#16150](https://github.com/sourcegraph/sourcegraph/pull/16150)~) 🐛
- [x] (🏁 5 days ago) Refactor changeset spec resolver to not require a context passed in for interface type resolution ([~#16182~](https://github.com/sourcegraph/sourcegraph/pull/16182)) :shipit:
- [x] (🏁 5 days ago) Add hydrate method to RewirerMappings ([~#16184~](https://github.com/sourcegraph/sourcegraph/pull/16184)) :shipit:
- [x] (🏁 5 days ago) Use new dbworker failed state for cancel method ([~#16201~](https://github.com/sourcegraph/sourcegraph/pull/16201)) :shipit:🧶
- [x] (🏁 5 days ago) ~Also fail rewiring when missing repo permissions on the close path~ ([~#16205~](https://github.com/sourcegraph/sourcegraph/pull/16205)) :shipit:🐛
- [x] (🏁 5 days ago) Remove campaigns => changeset mapping ([~#16203~](https://github.com/sourcegraph/sourcegraph/pull/16203)) :shipit:🧶
- [x] (🏁 today) Expose reconciler planner for use in resolver layer ([~#16055~](https://github.com/sourcegraph/sourcegraph/issues/16055); PRs: ~[#16185](https://github.com/sourcegraph/sourcegraph/pull/16185)~) __0.50d__
- [x] (🏁 today) Extend changeset spec resolvers by delta API fields ([~#16057~](https://github.com/sourcegraph/sourcegraph/issues/16057); PRs: ~[#16185](https://github.com/sourcegraph/sourcegraph/pull/16185)~) __1.50d__
- [x] (🏁 today) Implement basic first version of delta UI ([~#16240~](https://github.com/sourcegraph/sourcegraph/pull/16240)) :shipit:

@mrnugget: __9.50d__

Completed: __9.50d__
- [x] (🏁 13 days ago) src-cli: Clean up partially downloaded ZIP files if user aborts with Ctrl-C ([~#15865~](https://github.com/sourcegraph/sourcegraph/issues/15865)) __0.50d__
- [x] (🏁 8 days ago) Document how on.repository.branch in campaign spec is evaluated ([~#16077~](https://github.com/sourcegraph/sourcegraph/pull/16077)) :shipit:
- [x] (🏁 8 days ago) campaigns: allow the target branch to be customised ([~#15070~](https://github.com/sourcegraph/sourcegraph/issues/15070); PRs: ~[#393](https://github.com/sourcegraph/src-cli/pull/393)~) __1.00d__
- [x] (🏁 8 days ago) Uploading changeset specs fails with "failed to normalize JSON: yaml: control characters are not allowed" ([~#16081~](https://github.com/sourcegraph/sourcegraph/issues/16081); PRs: ~[#16116](https://github.com/sourcegraph/sourcegraph/pull/16116)~, ~[#16116](https://github.com/sourcegraph/sourcegraph/pull/16116)~) 🐛
- [x] (🏁 8 days ago) Introduced a "Failed" state to dbworker and reconciler ([~#15532~](https://github.com/sourcegraph/sourcegraph/issues/15532); PRs: ~[#15972](https://github.com/sourcegraph/sourcegraph/pull/15972)~) __1.00d__
- [x] (🏁 7 days ago) Allow users to create campaign spec even if execution failed in subset of repos ([~#15790~](https://github.com/sourcegraph/sourcegraph/issues/15790)) __1.00d__
- [x] (🏁 6 days ago) src-cli: Provide better stats/numbers while running a campaign ([~#15607~](https://github.com/sourcegraph/sourcegraph/issues/15607)) __1.00d__
- [x] (🏁 1 day ago) src-cli: race conditions in campaignProgressPrinter ([~#16195~](https://github.com/sourcegraph/sourcegraph/issues/16195)) __2.00d__ 🐛
- [x] (🏁 1 day ago) RFC: Allow to create multiple changeset specs in a single repository ([~#15349~](https://github.com/sourcegraph/sourcegraph/issues/15349)) __3.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by LawnGnome** [comment]
#### Weekly status: 2020-11-10 to 2020-11-16

Last week was abbreviated for me due to PTO and a public holiday, but when I was back I worked mostly on licensing issues: first implementing banners for unlicensed users, and then [backing out the licensing checks](https://github.com/sourcegraph/sourcegraph/pull/15775) and [updating the banners to cover the 3.22 release state of being unenforced](https://github.com/sourcegraph/sourcegraph/pull/15725) and adding a release changelog. I also added [a site setting to restrict campaign usage to admins](https://github.com/sourcegraph/sourcegraph/pull/15785).

This week, I'm focusing on user token documentation for 3.22, and then [adding search for changesets in campaigns](https://github.com/sourcegraph/sourcegraph/issues/15781).

**Comment by eseliger** [comment]
### Weekly update

Last week was lots of bug fixes, follow-up work for tokens and improvements for burndown chart performance. They all were smaller things and there was no general theme this week, more of an ad-hoc customer driven work loop.

This week, I'll wrap up two draft branches I have worked on for burndown charts and then pivot to designing the delta API and start dusting-off my PoC PRs for that.

**Comment by eseliger** [comment]
## Weekly update

Last week I've spent most time in debugging and fixing bugs and outlining the delta API in a spike. The DB based rewirer will be merged soon and I've validated that it will help us hit our goal. Quite a few customers are using campaigns now and so we found and fixed a lot of bugs in the system, but it actually feels good to get them all fixed, polishing and hardening the product. 

This week, I'll work on some more customer things and besides continue work on the delta API. The rewirer should be merged by tomorrow and then I'll start pushing out smaller pieces from the spike, slowly getting to implement the proposed API design. After that, we'll need to discuss how we communicate the reconciler plan and target changesets.

**Comment by mrnugget** [comment]
## Weekly update

Spent last week mostly working in `src-cli` (fixing little bugs, doing small tweaks) and responding to customer feedback/issues. So far, my sprint is going according to plan and I even caught a lucky break with one of my src-cli tickets (https://github.com/sourcegraph/sourcegraph/issues/15790) which turned out to be easier than I thought.

My goal for this week is to make more progress on RFC 265 (see updates in https://github.com/sourcegraph/sourcegraph/issues/15349). I want to get a prototype working that demonstrates how easy it would be to add the functionality on the client side and provides a better basis of discussion.

But I have a feeling that with all the customer feedback coming in and me not feeling so great this week, I won't make that much progress on it. Let's see.

**Comment by LawnGnome** [comment]
#### Weekly update: 2020-11-17 to 2020-11-23

Last week, I spent lots of time working on the src-cli and user token documentation in advance of the 3.22 release. This ended up being a bit more work than originally anticipated, since we decided to make the CLI documentation a top level thing, but we got it all reviewed and merged about an hour before the release (_without_ rushing), so the process worked! I was particularly happy with the autogenerated CLI reference documentation, although that still needs a lot of work to make it prettier.

After that, I added environment variable passthrough, which means that secrets no longer have to be encoded in campaign specs.

This week, I have two big items to work on: adding changeset text search, and indicating that a newer campaign spec is available when previewing. If I get through those, then adding more end-to-end testing to src-cli will be next on my agenda.

**Comment by mrnugget** [comment]
### Weekly update

Sprint done, all tasks checked off. Since the last update I finished off multiple smaller tasks: 

- Fixed a customer issue when uploading changeset specs that include YAML control characters #16081
- Fixed race conditions in src-cli #16195
- Added better stats to src-cli output #15607
- Added `-skip-errors` to src-cli https://github.com/sourcegraph/src-cli/pull/395

And then I focused on RFC 265 (see https://github.com/sourcegraph/sourcegraph/issues/15349 for updates) and closed this write-an-rfc-for-this ticket with the following message:

> I'm marking this ticket as done, because I think we've reached a "milestone" with this RFC:
> 
> - RFC is ready for review.
> - RFC contains a fleshed-out version of 1 of 2 possible solutions.
> - PR that implements this is ready to be reviewed.
> 
> We, as a team, still haven't made a decision as to which solution we should properly implement and ship, but I'd rather create a new ticket for this than to keep on moving this ticket from sprint to sprint.

The last sentence I'll take as input for today's sprint planning: I'm not 100% convinced that my proposed solution is the way to go, so I want more input from the rest of the team and from product. Because I do think we could, theoretically and practically, build both solutions and ship them to customers, but I wonder which one would provide more value.

---

As a meta note: I personally felt like there was not enough slack planned into this iteration _for me_. When we did our planning two weeks ago, Adam specifically pointed this out as a warning but I said "eh, it'll work out". And while it did work out, it didn't feel good. I felt like there was no room for exploration, taking a step back or cleaning up some thing. Again, emphasis on "for me": I have a personal issue with estimations and feeling "rushed" when I have lots of tasks with 1d estimations and no planned-in Slack. But just wanted to raise this here.
