### ISSUE TITLE
Security 3.23 Tracking issue Sprint 1

### ISSUE THREAD

**Issue by chayim** [sourcegraph/sourcegraph#15979]
### Plan

Goals:
1. Deploy Vault in dogfood and migrate several tokens [Team Goal #2](https://about.sourcegraph.com/handbook/engineering/security/goals#confidence-in-our-security-model)
1. Collect dogfood stackdriver, and Cloudflare logs [Team Goal #1](https://about.sourcegraph.com/handbook/engineering/security/goals#visibility-into-sourcegraph-cloud-s-attack-surface)

### Availability
Sprint is from 2020-11-21 to 2020-12-05
Duration is 10 days

Chayim: 8 days - Nov 24 (conference), Dec 1
Elizabeth: 7 days - Nov 26,27 + Dec 4

### Tracked issues

@unassigned

Completed
- [x] (🏁 34 days ago) sourcegraph/security-issues ([~#124~](https://github.com/sourcegraph/security-issues/issues/124)) 🔒

@ElizabethStirling: __12.00d__

- [ ] Team Security Tracking: RFC249 Secret Management Tracking ([#15452](https://github.com/sourcegraph/sourcegraph/issues/15452)) __12.00d__
  - [x] (🏁 21 days ago) Buildkite secrets are located and enumerated ([~#15453~](https://github.com/sourcegraph/sourcegraph/issues/15453)) __1.50d__
  - [x] (🏁 22 days ago) Create and configure Hashicorp Vault for testing purposes ([~#15885~](https://github.com/sourcegraph/sourcegraph/issues/15885)) __4.00d__
  - [x] (🏁 12 days ago) Document security requirements for production Vault ([~#16249~](https://github.com/sourcegraph/sourcegraph/issues/16249)) __3.00d__
  - [x] (🏁 21 days ago) K8s deployment secrets located and moved to Vault ([~#16251~](https://github.com/sourcegraph/sourcegraph/issues/16251)) __2.00d__
  - [x] (🏁 12 days ago) Infrastructure secrets located and enumerated ([~#16252~](https://github.com/sourcegraph/sourcegraph/issues/16252)) __1.50d__

Completed: __12.00d__
- [x] (🏁 22 days ago) Create and configure Hashicorp Vault for testing purposes ([~#15885~](https://github.com/sourcegraph/sourcegraph/issues/15885)) __4.00d__
- [x] (🏁 21 days ago) Buildkite secrets are located and enumerated ([~#15453~](https://github.com/sourcegraph/sourcegraph/issues/15453)) __1.50d__
- [x] (🏁 21 days ago) K8s deployment secrets located and moved to Vault ([~#16251~](https://github.com/sourcegraph/sourcegraph/issues/16251)) __2.00d__
- [x] (🏁 12 days ago) Infrastructure secrets located and enumerated ([~#16252~](https://github.com/sourcegraph/sourcegraph/issues/16252)) __1.50d__
- [x] (🏁 12 days ago) Document security requirements for production Vault ([~#16249~](https://github.com/sourcegraph/sourcegraph/issues/16249)) __3.00d__

@chayim: __8.00d__

- [ ] Centralize dogfood WAF logs into Elastic ([#15980](https://github.com/sourcegraph/sourcegraph/issues/15980)) __2.00d__

Completed: __6.00d__
- [x] (🏁 29 days ago) Campaigns security review ([~#15983~](https://github.com/sourcegraph/sourcegraph/issues/15983)) __1.00d__
- [x] (🏁 27 days ago) Complete SOC research ([~#15985~](https://github.com/sourcegraph/sourcegraph/issues/15985)) __1.00d__
- [x] (🏁 16 days ago) Determine how to centralize dogfood stackdriver logs into Elastic ([~#15981~](https://github.com/sourcegraph/sourcegraph/issues/15981)) __2.00d__
- [x] (🏁 16 days ago) Test logstash nodes for dogfood log gathering ([~#15982~](https://github.com/sourcegraph/sourcegraph/issues/15982)) __2.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by sushiwushi** [comment]
**This Week**

This week, I ran automated tests against Sourcegraph using Arachni during my penetration testing process in the application. After triaging the issues I discovered there are no direct security risk as investigated in [security issue 124](https://github.com/sourcegraph/security-issues/issues/124).

**Next Week**

I will run automated scanners against the application to eliminate low hanging fruits so it can be patched as soon as possible.

**Comment by ElizabethStirling** [comment]
**This Week**
I vindicated the validity of the venerable Vault by verifying its viability for vigilant storage of vital secrets, to the very great vexation of vile villains. This was vitalized by @pecigonzalo who volunteered to virtuously facilitate victory. In this vein, I am now vociferously verifying values for this venture. Verily, victory was obtained in the volatile venue of https://github.com/sourcegraph/security-issues/issues/, where my vigilance has vanquished vintage issues.

Tl;dr, I made sure vault was the correct choice, that it works for our needs. I'm creating a document that lists the requirements and considerations we will need when production-ifying Vault. I also followed up on and drove the closing of any uncategorized security issues in the security issues repo. This was a 3 day week for me.

**Next Week**
I plan to wear out the "V" key on my keyboard. Additionally, I want to have the relevant conversations with and provide the relevant requirements and guidance to distribution to prioritize the productionization of Vault. Once this is finalized, I want to spend some time verifying the locations of secrets in our repositories, and validating our plans for vanquishing them.

**Comment by sushiwushi** [comment]
**This Week**
This week, I ran automated tests against Sourcegraph docker instance using Burp Suite scanner proxy during my penetration testing process in the application which can be found in [security issue #125](https://github.com/sourcegraph/security-issues/issues/125).

**Next Week**
I will run automated scanners against the application to eliminate low hanging fruits so it can be patched as soon as possible.

**Comment by chayim** [comment]
**This Week**

I completed the [SOC research](https://docs.google.com/document/d/1NgKJOaZJKWQLUDPkov3YCvvRzqbPi7ObUqBs9zeSSUk/edit) (#15983) so that we could plan the SOC roadmap outside of my initial prioritization. I completed the security review of campaigns (#15983). I reached out to several candidates for our [open position](https://about.sourcegraph.com/handbook/engineering/hiring/software-engineer-security), spent time at a conference, and was sick.

**Next Week**

I'm going to continue reaching out to candidates and continue hiring. I  will work on planning, and the SOC roadmap. Finally, I'll either get our WAF logs (#15980) or stackdriver logs (#15981) into our Elastic cluster.

**Comment by ElizabethStirling** [comment]
**This Week**
This week, I re-divided and estimated Vault secret management issues #15452. I discovered that there are a few edge cases that will take a good chunk of time to properly test and verify in order to avoid causing issues with secret injection. I'm hopeful that my estimates are overestimates, but want to be conservative so that we have time to do this right. I was able to close out #15453 & #16251, which were locating buildkite and k8s deployment repo secrets. I then worked with @lguychard to build some fancy search queries that I will validate when enumerating terraform secrets in #16252. I also documented the security requirements for vault (#16249), and hope to get everything finalized and planned with distribution soon. 

**Next Week**
Next week, I plan to finalize #16252, and work with @lguychard to further refine search queries to detect secrets in our repositories. This will both serve a security purpose, as I'll have more confidence that I've enumerated all of our secrets, and it will serve a business purpose, since it'll help our clients see how to use Sourcegraph as a security product. I then plan to work with @chayim to get myself up to speed with the work he has done WRT centralized logging (#15444) so that we can work in tandem while I wait for Distribution to have capacity to productionify Vault.

**Comment by sushiwushi** [comment]
**This Week**
This week, I ran a fuzzing test against Sourcegraph docker instance using ffuf fuzzer during my penetration testing process in the application which can be found in security issue [#126](https://github.com/sourcegraph/security-issues/issues/126).

**Next Week**
I will run automated scanners against the application to eliminate low hanging fruits so it can be patched as soon as possible.

**Comment by chayim** [comment]
**This Week**

I continued my focus on hiring, and interviewed more candidates. I collected the [SOC roadmap](https://docs.google.com/document/d/1NgKJOaZJKWQLUDPkov3YCvvRzqbPi7ObUqBs9zeSSUk/edit) research and added it to ProductBoard. Similarly, I ingested the initial Stackdriver logs into our Elastic cluster (#15981, #15982), and worked out deployments with @pecigonzalo.

**Next Week**

This week I'm going to break down the logging work for Stackdriver log movement given the research completed in #15981 and #15982. I'll document our code review process, and continue the focus on hiring. Finally, I will help @sushiwushi move forward on [security issue #126](https://github.com/sourcegraph/security-issues/issues/126)/

**Comment by ElizabethStirling** [comment]
**This Week**
I finished enumerating secrets in our infrastructure repo (#16252), created a new security GCP project (#16491) to store security infrastructure, and began work on centralized logging. The Specifically, I did work to draft pubsub topics and subscriptions from dogfood to one of the newly created security projects (#16492). I should have a PR out for these early next week.

**Next Week**
I plan to finalize pubsub wiring for #16492. Then, I'll work to get an instance of pubsubbeats running in the security GCP project and connect it to elasticsearch. I hope to get this wired up by Wednesday so that I can spend the rest of the week validating the implementation, wiring it up to dotcom, and adding additional GCP logs #15444.

**Comment by sushiwushi** [comment]
**This Week**
This week, I ran a SQL injection fuzzing test against Sourcegraph docker instance using Burp Suite intruder during my penetration testing process in the application which can be found in [security issue #126](https://github.com/sourcegraph/security-issues/issues/126).

**Next Week**
I will continue run fuzzing tests against the application to discover hidden vulnerabilities so it can be patched as soon as possible.

**Comment by ElizabethStirling** [comment]
**This Week**
This week was mainly focused around getting pubsubbeats configured #16492 and helping onboard @andreeleuterio to the security team 🎉 🎉 🎉 🎉 🎉 . Unfortunately, things went a bit slower than expected, and I was only able to get partways through #16492. I started by getting pubsub wired up [infrastructure/#2289](https://github.com/sourcegraph/infrastructure/pull/2289). There were a few bugs in this, but @pecigonzalo helped resolve them. Afterwards, I got a GKE cluster configured to run our logging infrastructure [infrastructure/#2293](https://github.com/sourcegraph/infrastructure/pull/2293). Finally, I have a draft PR out for a helm chart that should deploy pubsubbeats to our cluster, though, I do have a bit more validation work to do before it's ready to merge [infrastructure/#2310](https://github.com/sourcegraph/infrastructure/pull/2310).

**Next Week**
Next Week, I have a short week, so I'll probably be doing some work to coordinate the handoff of #16492. I hope that I can get [infrastructure/#2310](https://github.com/sourcegraph/infrastructure/pull/2310) finished up, so that all that's left would be to wire up additional pubsub logging for dotcom and other relevant GCP projects. This should be as simple as creating relevant pubsub log sinks, similar to the ones created in dogfood.

**Comment by sushiwushi** [comment]
**This Week**
This week, I ran a command injection fuzzing test against Sourcegraph docker instance using Burp Suite intruder during my penetration testing process in the application which can be found in [security issue #129](https://github.com/sourcegraph/security-issues/issues/129).

**Next Week**
I will continue run fuzzing tests against the application to discover hidden vulnerabilities so it can be patched as soon as possible.

**Comment by andreeleuterio** [comment]
Bit late to this but
**Last week**
Got through with most of my onboarding tasks! 

**This week**
- Short week (I'm not around Thursday and Friday)
- Lots on meetings to meet folks on other teams
- https://github.com/sourcegraph/security-issues/issues/123

**Comment by ElizabethStirling** [comment]
Closing in favor of #16961
