### ISSUE TITLE
Code Intelligence Sprint 1 Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#16036]
### Plan

This sprint covers 2020/11/23 to 2020/12/04.

Owen, our team's new EM, will be starting 2020/11/23 :tada:. The team's priority will be to onboard Owen, discuss a hiring strategy, then get alignment on our goals and re-state them in the handbook.

Until we have a formalized plan, we have decided to concentrate on continuing work on auto-indexing (stability and observability) to ease adoption of precise code intelligence and build a massive open-source index, and on lsif-clang (making it more easily debuggable) so that the team can re-build expertise with the indexer.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

Owen: 8d (4x10 workweek)
Maria: 9d (out 2020/11/27)
Eric: 7d (out 2020/11/25-27)
Noah: 9d (out 2020/12/04)

### Tracked issues

@Strum355: __1.00d__

Completed: __1.00d__
- [x] (🏁 today) ~RFC 201: Add UI for configuration~ ([~#14571~](https://github.com/sourcegraph/sourcegraph/issues/14571); PRs: ~[#16408](https://github.com/sourcegraph/sourcegraph/pull/16408)~, ~[#16470](https://github.com/sourcegraph/sourcegraph/pull/16470)~) __1.00d__

@efritz: __6.50d__

- [ ] ~executor: Verify checksum of resources before execution~ ([#15937](https://github.com/sourcegraph/sourcegraph/issues/15937)) __0.50d__
- [ ] ~codeintel: git diffing fails graphql requests related to force-pushed commits~ ([#12588](https://github.com/sourcegraph/sourcegraph/issues/12588)) __0.50d__ 🐛
- [ ] ~executor: Add metrics dashboard~ ([#15938](https://github.com/sourcegraph/sourcegraph/issues/15938)) __2.00d__
- [ ] ~executor-queue: Update metrics dashboard~ ([#15939](https://github.com/sourcegraph/sourcegraph/issues/15939)) __0.50d__

Completed: __3.00d__
- [x] (🏁 7 days ago) executor-queue: Pass secrets along with job payload ([~#15940~](https://github.com/sourcegraph/sourcegraph/issues/15940); PRs: ~[#16260](https://github.com/sourcegraph/sourcegraph/pull/16260)~) __1.00d__
- [x] (🏁 6 days ago) executor: Break apart log contents ([~#15941~](https://github.com/sourcegraph/sourcegraph/issues/15941); PRs: ~[#15957](https://github.com/sourcegraph/sourcegraph/pull/15957)~, ~[#16245](https://github.com/sourcegraph/sourcegraph/pull/16245)~, ~[#16246](https://github.com/sourcegraph/sourcegraph/pull/16246)~, ~[#16247](https://github.com/sourcegraph/sourcegraph/pull/16247)~) __1.00d__
- [x] (🏁 5 days ago) executor-queue: Do not ignore errors from store methods ([~#16385~](https://github.com/sourcegraph/sourcegraph/pull/16385)) :shipit:
- [x] (🏁 5 days ago) codeintel: Convert FAILED state to ERRORED ([~#16384~](https://github.com/sourcegraph/sourcegraph/pull/16384)) :shipit:
- [x] (🏁 5 days ago) codeintel: Convert state columns to text ([~#16386~](https://github.com/sourcegraph/sourcegraph/pull/16386)) :shipit:
- [x] (🏁 1 day ago) codeintel: Fix integration tests ([~#16459~](https://github.com/sourcegraph/sourcegraph/pull/16459)) :shipit:
- [x] (🏁 today) ~RFC 201: Add UI for configuration~ ([~#14571~](https://github.com/sourcegraph/sourcegraph/issues/14571); PRs: ~[#16408](https://github.com/sourcegraph/sourcegraph/pull/16408)~, ~[#16470](https://github.com/sourcegraph/sourcegraph/pull/16470)~) __1.00d__
- [x] (🏁 today) LSIF Go Indexing fails after 3.17 > 3.21 upgrade ([~#16030~](https://github.com/sourcegraph/sourcegraph/issues/16030); PRs: ~[#16086](https://github.com/sourcegraph/sourcegraph/pull/16086)~, ~[#16140](https://github.com/sourcegraph/sourcegraph/pull/16140)~, ~[#16270](https://github.com/sourcegraph/sourcegraph/pull/16270)~, ~[#16368](https://github.com/sourcegraph/sourcegraph/pull/16368)~, ~[#16517](https://github.com/sourcegraph/sourcegraph/pull/16517)~) [👩](https://app.hubspot.com/contacts/2762526/company/464956351)

@scalabilitysolved: __0.50d__

- [ ] docs: Update code appendix links ([#16076](https://github.com/sourcegraph/sourcegraph/issues/16076)) __0.50d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by efritz** [comment]
**Completed 2020/11/23-11/24**

Triaged customer issue described by https://github.com/sourcegraph/sourcegraph/issues/16030. Possibly solved by https://github.com/sourcegraph/sourcegraph/pull/16140, but waiting for a confirmation in their environment.

**Planned 2020/11/30-12/04**

Will concentrate on https://github.com/sourcegraph/sourcegraph/issues/16030 until we are satisfied with the new commit graph update performance/resource usage in the customer's environment.

Once that is finished I'll switch to https://github.com/sourcegraph/sourcegraph/issues/15941 to improve the log contents UI for index jobs.

**Comment by macraig** [comment]
**Completed 2020/11/23-11/24**
- Refactor docs: the preferred term for "basic" code intel is now "search-based"
- Onboarding Owen :tada:
- Review goals and priorities

**Planned 2020/11/30-12/04**
- Get goals/priorities published and present to CE/Sales
- Start working on code intel terms user testing
- Work on code intel looker dashboard

**Comment by macraig** [comment]
Completed 2020/11/30-12/04
Goals/priorities published and presented to CE/Sales
Drafted code intel name conventions user testing
Added mockups for code intel dashboard

Planned 2020/12/07-12/11
Work on and present roadmap to CE/Sales
Continue work on user testing

**Comment by efritz** [comment]
**Completed 2020/11/30-12/04**

Made progress on https://github.com/sourcegraph/sourcegraph/issues/16030. Need to still get approval and merge https://github.com/sourcegraph/sourcegraph/pull/16459 and https://github.com/sourcegraph/sourcegraph/pull/16368.

**Planned 2020/12/07-12/11**

Remaining effort on https://github.com/sourcegraph/sourcegraph/issues/16030: I will branch off of 3.22 and cherry pick the following:

- https://github.com/sourcegraph/sourcegraph/commit/dc8beddf4066e30198c5ea368e6ee1092a6f4560
- https://github.com/sourcegraph/sourcegraph/commit/4e10e9f9a7a600d65dc9b24468073faad49e832d
- https://github.com/sourcegraph/sourcegraph/commit/6c9ea16c0f48a7bb7835580cb7f5db838102763e
- https://github.com/sourcegraph/sourcegraph/pull/16459
- https://github.com/sourcegraph/sourcegraph/pull/16368

Then, I will push a temporary enterprise frontend image for the customer to test. If this resolves their issues I will work on starting a 3.22 patch release with these same changes.

**Comment by efritz** [comment]
Sprint 2 at https://github.com/sourcegraph/sourcegraph/issues/16515.
