### ISSUE TITLE
internal contributor 3.23 Tracking issue

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#16080]
### Plan

Tracking issue for @slimsag working as an internal contributor on high-impact, low-cost wins.

Project board: https://github.com/orgs/sourcegraph/projects/106

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

Not working:

- Nov 26 & 27 (Thanksgiving)
- Dec 11th (Friday, Birthday)

Total time: **17d**

### Tracked issues

@unassigned

Completed
- [x] (🏁 12 days ago) Data: Sourcegraph.com search latencies ([~#17181~](https://github.com/sourcegraph/sourcegraph/issues/17181))

@felixfbecker

Completed
- [x] (🏁 15 days ago) Plan and begin Code Insights backend work ([~#16471~](https://github.com/sourcegraph/sourcegraph/issues/16471))

@slimsag: __5.00d__

- [ ] Webapp fetches entire file contents for each search result ([#6992](https://github.com/sourcegraph/sourcegraph/issues/6992); PRs: ~[#16254](https://github.com/sourcegraph/sourcegraph/pull/16254)~, ~[#16466](https://github.com/sourcegraph/sourcegraph/pull/16466)~, ~[#16570](https://github.com/sourcegraph/sourcegraph/pull/16570)~, ~[#16571](https://github.com/sourcegraph/sourcegraph/pull/16571)~) __5.00d__ 🐛
- [ ] search: time-to-first-result metric ([#16468](https://github.com/sourcegraph/sourcegraph/issues/16468); PRs: ~[#16571](https://github.com/sourcegraph/sourcegraph/pull/16571)~)
- [ ] Webapp should pre-fetch some search result highlights ([#16467](https://github.com/sourcegraph/sourcegraph/issues/16467); PRs: ~[#16466](https://github.com/sourcegraph/sourcegraph/pull/16466)~, ~[#16571](https://github.com/sourcegraph/sourcegraph/pull/16571)~)

Completed
- [x] (🏁 58 days ago) web: cleanup CodeExcerpt / CodeExcerpt2 code split ([~#16254~](https://github.com/sourcegraph/sourcegraph/pull/16254)) :shipit:
- [x] (🏁 50 days ago) web: search: major code excerpt refactor (better testing, code structure, etc.) ([~#16466~](https://github.com/sourcegraph/sourcegraph/pull/16466)) :shipit:
- [x] (🏁 47 days ago) graphql: add ability to syntax highlight specific line ranges ([~#16570~](https://github.com/sourcegraph/sourcegraph/pull/16570)) :shipit:
- [x] (🏁 47 days ago) search: reduce bytes transferred for loading each search result by ~50-70% ([~#16571~](https://github.com/sourcegraph/sourcegraph/pull/16571)) :shipit:
- [x] (🏁 15 days ago) Plan and begin Code Insights backend work ([~#16471~](https://github.com/sourcegraph/sourcegraph/issues/16471))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by slimsag** [comment]
**This week:**

Short week (Thanksgiving, taking two days off), spent most of Monday catching up on everything after being on vacation. Quickly fixed [a syntax highlighting bug](https://github.com/sourcegraph/sourcegraph/issues/13007) multiple users had complained about enough that one wanted to pay a bounty to have it fixed(❗). Discussed with Felix about Code Insights and how I might help there, and spent a majority of my time looking into https://github.com/sourcegraph/sourcegraph/issues/6992 - the code is very hairy/nasty here, but I anticipate completing this in 2-3 more work days. [I am discussing with the search team how to measure the impact this change has](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1606325812122100) and may add a new task time-boxed to 1-2d for putting something in place here to measure changes like this and streaming search.

**Next week:**

I expect to finish and merge a change for https://github.com/sourcegraph/sourcegraph/issues/6992 behind a feature flag, and begin looking at how to measure it.

**Comment by slimsag** [comment]
**This week**

I made slower progress towards #6992 than I wanted to, primarily because it became clear that I had to refactor a lot of spaghetti code in order to implement the fix cleanly. That said, I have:

- Sent a PR which does a major refactor of that spaghetti code https://github.com/sourcegraph/sourcegraph/pull/16466
- Have a PR ready (haven't sent yet) which fixes #6992 - preliminary testing shows a reduction of about 50-70% of compressed bytes transferred on both page load and overall when viewing all results. It feels a lot snappier even on a dev server where there is no latency.
- Finalized my 3.23 tracking issue #16080 and am actively planning code insights backend work with Felix and others.

**Next week**

I will finish up the search work here completely, and optimistically finish planning code insights backend work with Felix so that I can get started on that the week after next.

**Comment by slimsag** [comment]
**Last week**

Happy with the progress I made. I landed my major webapp refactor #16466 which was a per-requisite to fixing #6992. I then sent and merged both the frontend (#16571) and backend (#16570) fixes for #6992 behind a feature-flag which reduces bytes transferred for search result loading by ~50-70%.

I briefly helped resolve a Sourcegraph.com incident, and did a lot of work with Felix brainstorming how we will move forward on the Code Insights backend ([overview](https://github.com/sourcegraph/sourcegraph/issues/16471)). I put together [a "learn-as-we-go" draft RFC](https://docs.google.com/document/d/1LX6Msbxnz_DRf6OItZLaX-vELfnHGKgODkb1bVauolk/edit#).

**This week**

At the start of the week, I plan to add metrics for search-result-time-to-load (#16468) so I can determine how much we have won with my fix here #6992 and so that I can turn that feature flag on-by-default. If I have time, I will also try to implement #16467 which will further help with initial page loads.

I plan to polish up the [code insights "learn-as-we-go" RFC](https://docs.google.com/document/d/1LX6Msbxnz_DRf6OItZLaX-vELfnHGKgODkb1bVauolk/edit#), run it by a few others (I will have to wait until after holiday to get Felix's approval, I have Joel's approval), and begin executing on it late this week and begin taking in feedback and adapting as we go.

**Comment by slimsag** [comment]
**Last week**

Two-day week, as I just got back from holiday break. I spent the entire two days catching up on things, and mostly helping https://app.hubspot.com/contacts/2762526/company/407948923/ which has recently had a surge in activity (campaigns discussions, upgrade issues, account changes, etc.) that requires my time.

**This week**

Monday is lost to meetings, and I expect a day or two will go towards https://app.hubspot.com/contacts/2762526/company/407948923/ - specifically around campaigns discussions and https://github.com/sourcegraph/customer/issues/175

I aim to spend a majority of my time this week actually starting on code insights backend work.

**Comment by slimsag** [comment]
Picking up here: https://github.com/sourcegraph/sourcegraph/issues/17737
