### ISSUE TITLE
Distribution: 2020.11.30 - Gallant Jackal

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#16087]
#### [Support new and existing deployments](https://github.com/orgs/sourcegraph/projects/74)

This is an ongoing expense, we anticipate this taking no more than 5d of work spread across the entire team.

#### [Implement 5+ sourcegraph.com services using dhall](https://github.com/orgs/sourcegraph/projects/71?card_filter_query=milestone%3A%22dist%3A+2020.11.30%22)

Kick-start the Dhall migration of the `sourcegraph.com` deployment.

- @ggilmore 
- @uwedeportivo
- @daxmc99 
- @bobheadxi 
- @davejrt 
- @pecigonzalo 

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

**Dave:** Dec 7-8(2d)
**Gonza:** Dec 8(1d)

### Tracked issues

@bobheadxi: __6.00d__

- [ ] ~release: rough edges tracking issue~ ([#16207](https://github.com/sourcegraph/sourcegraph/issues/16207)) __1.00d__
- [ ] ~prom-wrapper: generated alert receiver ID is not sufficiently unique~ ([#16592](https://github.com/sourcegraph/sourcegraph/issues/16592)) __0.50d__ 🐛
- [ ] ~release: continue on errors~ ([#16549](https://github.com/sourcegraph/sourcegraph/issues/16549)) __0.50d__

Completed: __4.00d__
- [x] (🏁 13 days ago) deploy-sourcegraph, deploy-sourcegraph-docker: generate update-docker-tags params from allDockerImages list ([~#15896~](https://github.com/sourcegraph/sourcegraph/issues/15896)) __1.00d__ 🧶
- [x] (🏁 12 days ago) sourcegraph/customer ([~#140~](https://github.com/sourcegraph/customer/issues/140)) 👩
- [x] (🏁 5 days ago) dhall: implement grafana service in deploy-sourcegraph-dhall ([~#16263~](https://github.com/sourcegraph/sourcegraph/issues/16263)) __3.00d__

@davejrt: __3.00d__

- [ ] sourcegraph/customer ([#129](https://github.com/sourcegraph/customer/issues/129)) 👩

Completed: __3.00d__
- [x] (🏁 18 days ago) sourcegraph/customer ([~#143~](https://github.com/sourcegraph/customer/issues/143)) 👩
- [x] (🏁 2 days ago) dhall: implement github-proxy service in deploy-sourcegraph-dhall ([~#16259~](https://github.com/sourcegraph/sourcegraph/issues/16259)) __3.00d__

@daxmc99: __8.50d__

- [ ] ~Review frontend liveness and readiness probes on frontend~ ([#16250](https://github.com/sourcegraph/sourcegraph/issues/16250)) __1.00d__
- [ ] ~Use containerd images on clusters~ ([#15194](https://github.com/sourcegraph/sourcegraph/issues/15194)) __0.50d__ 🕵️
- [ ] ~Upgrade to Postgres 13 on dot-com~ ([#16611](https://github.com/sourcegraph/sourcegraph/issues/16611)) __5.00d__

Completed: __2.00d__
- [x] (🏁 11 days ago) Dhall: document repo-updater customizations ([~#16244~](https://github.com/sourcegraph/sourcegraph/issues/16244)) __1.00d__
- [x] (🏁 2 days ago) Add Postgres dashboards with alerting ([~#15029~](https://github.com/sourcegraph/sourcegraph/issues/15029)) __1.00d__

@efritz: __5.00d__

- [ ] ~sourcegraph/customer~ ([#156](https://github.com/sourcegraph/customer/issues/156); PRs: [#16636](https://github.com/sourcegraph/sourcegraph/pull/16636)) __5.00d__ 👩

@pecigonzalo: __4.00d__

- [ ] ~sourcegraph/customer~ ([#142](https://github.com/sourcegraph/customer/issues/142)) 👩
- [ ] Get approval on "RFC 263: Single-container deployments are for demos only" ([#15484](https://github.com/sourcegraph/sourcegraph/issues/15484))
- [ ] ~release: rough edges tracking issue~ ([#16207](https://github.com/sourcegraph/sourcegraph/issues/16207)) __1.00d__

Completed: __3.00d__
- [x] (🏁 4 days ago)  dhall: implement query-runner service in deploy-sourcegraph-dhall  ([~#16266~](https://github.com/sourcegraph/sourcegraph/issues/16266)) __3.00d__
- [x] (🏁 3 days ago) sourcegraph/customer ([~#141~](https://github.com/sourcegraph/customer/issues/141)) 👩

@uwedeportivo: __16.00d__

- [ ] Tracking issue: Use CI on sourcegraph.com with Dhall ([#13340](https://github.com/sourcegraph/sourcegraph/issues/13340)) __5.00d__
  - [ ] ~add deploy-sourcegraph-dhall pipeline to deploy-sourcegraph-dot-com~ ([#14132](https://github.com/sourcegraph/sourcegraph/issues/14132)) __1.00d__
  - [x] (🏁 2 days ago) add gitserver to deploy-sourcegraph-dhall, with support for sourcegraph.com customizations ([~#14131~](https://github.com/sourcegraph/sourcegraph/issues/14131)) __4.00d__
- [ ] ~dhall: implement searcher service in deploy-sourcegraph-dhall ~ ([#16267](https://github.com/sourcegraph/sourcegraph/issues/16267)) __3.00d__
- [ ] ~sourcegraph/customer~ ([#156](https://github.com/sourcegraph/customer/issues/156); PRs: [#16636](https://github.com/sourcegraph/sourcegraph/pull/16636)) __5.00d__ 👩

Completed: __7.00d__
- [x] (🏁 2 days ago) jaeger dhall sidecar: lift out shared parts and shared customizations ([~#16133~](https://github.com/sourcegraph/sourcegraph/issues/16133)) __1.00d__
- [x] (🏁 2 days ago) add gitserver to deploy-sourcegraph-dhall, with support for sourcegraph.com customizations ([~#14131~](https://github.com/sourcegraph/sourcegraph/issues/14131)) __4.00d__
- [x] (🏁 2 days ago) gitserver dhall component: break out internal/generate into kind pieces (statefulset, service and pvs) ([~#16132~](https://github.com/sourcegraph/sourcegraph/issues/16132)) __1.00d__
- [x] (🏁 2 days ago) gitserver dhall component: document customizations ([~#16131~](https://github.com/sourcegraph/sourcegraph/issues/16131)) __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by pecigonzalo** [comment]
**Last week**
It was a bit of an admin week, mostly catching up with emails, meetings, reviewing RFCs and PRs. Aside from those I deployed the Gerrit instance (thanks @ggilmore for the help) for our Dogfood environment as well a simple change to add LSIF to it. I also merged a PR to remove the low-utilization alerts as well as cleanup and address some of the Alertmanager silences we had in place.
I also had a couple of meeting with Security to sync on Vault and with CE to talk about the new communication process we discussed so its easier to route issues.

**This week**
This week will be focused around planning, organizing and cleaning some old projects/issues and updating documentation (Goals, CE workflow, Job description). I would also like to check the next steps for [Distribution: Releases are created in a single day](https://github.com/orgs/sourcegraph/projects/90) so we can close the project.

**Comment by ggilmore** [comment]
Last Week: 

@uwedeportivo and I spent the week extensively pairing with each member of @sourcegraph/distribution to work on deploy-sourcegraph-dhall. 

Next week: 

We will continue pairing with every member so that we can push each of 5 of the five components over the finish line.

**Comment by pecigonzalo** [comment]
**Last week**
Last week I focused on catching up with some topics like updating our docs on our support rotation and other threads. I did not manage to complete the Goals or JD update.
I managed to get `query-runner` port to Dhall 90% there but is not yet finished.

**This week**
I plan to finish `query-runner` and possible take another service if time allows. I have to catch-up to the Goals and JD updates, so once I finish `query-runner` those are the priority.

**Comment by bobheadxi** [comment]
(sorry about the assignment spam misclicked a bit there)

**last week**

Refactored the monitoring generator into multiple packages to better enable future feature work. Added feature and lightweight dev documentation for the generator (https://github.com/sourcegraph/sourcegraph/tree/main/monitoring), as well as new generated reference for the monitoring library (https://github.com/sourcegraph/sourcegraph/tree/main/monitoring/monitoring). Paired with Uwe and Geoffrey to catch up on the state of ds-dhall, and opened a PR adding a Grafana component to ds-dhall. Made our Docker images list a separate module and updated the usages of `update-docker-images` to use it (instead of hardcoding images).

**next week**

Work to finalize my Grafana PR when it gets a review. Start looking at addressing release tool pain points from last release, and maybe see if other dhall work needs to be done (and if not, start scheduling monitoring work)

**Comment by davejrt** [comment]
**last week**

Refactored a number of things in CI to make upgrades to node after an issue sprung up. Worked on Dhall with uwe and geoffrey which I think is most of the way there. I still need a fair bit more work here to really understand some of the finer points of the language but I am finding the more I work my way through this I am starting understand how things tie together. The e2e/qa pipelines are now running 

**This week**

I have a few days off for a national holiday here, and the goal is to finish `github-proxy` in Dhall.

**Comment by uwedeportivo** [comment]
last week

worked on deploy-sourcegraph-dhall, participating in pair sessions, doing some refactorings, writing a howto manual, improving ds-to-dhall tool. helped a customer (bigdata) overcome some repo-updater bug where it didn't push cloning progress forward. 

this week

finish my assignments for deploy-sourcegraph-dhall. finish the manual

**Comment by daxmc99** [comment]
**Last Week**
Paired with Uwe & Geoffrey to add the Postgres dhall implementation
I worked towards adding custom query support to `pg_exporter`. I plan to bake this into the image based on review comments.

**Next week**
Finish up dhall implementation of Postgres, rollout postgres 13 to cloud, and add docs on how to use `crictl` so that we can rollout contained on our cloud clusters

**Comment by bobheadxi** [comment]
**last week**

Helped Uwe a bit with patch release, and landed a range of release process and tool improvements based on feedback from the patch and from the previous release (with a few more open for review, and the rest having separate open issues - see an overview here: https://github.com/sourcegraph/sourcegraph/issues/16207). Implemented and merged Dhall Grafana component. Reviewed Dax's postgres dashboard work and Uwe's dhall docs. Planned for [monitoring redux project](https://github.com/orgs/sourcegraph/projects/112).

**next week**

Begin monitoring redux work and make sure that everything is clear, we're all aligned, and it's possible to assign the work to others. Anything else that comes up during planning.
