### ISSUE TITLE
generator: refactoring ideas tracking

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#16117]
This is a lightweight tracking issue for some ideas for potential monitoring generator refactoring. Some of these have potentially large scopes, those will be spun off into tickets if required and and checked off

* [x] Env defaults: https://github.com/sourcegraph/sourcegraph/pull/16062#discussion_r528746605 => fixed in https://github.com/sourcegraph/sourcegraph/pull/16724
* [ ] Permissions: https://github.com/sourcegraph/sourcegraph/pull/16062#discussion_r528751007
* [ ] Have each dashboard register itself: https://github.com/sourcegraph/sourcegraph/pull/16062#discussion_r528744558
* [x] ~Have monitoring definitions be distributed across packages: https://github.com/sourcegraph/sourcegraph/pull/16062#pullrequestreview-536346772~ I think this is too much additional complexity to the setup, and some awkward non determinsticness 
* [ ] Unify logging: https://github.com/sourcegraph/sourcegraph/pull/16062#discussion_r528606761
* [ ] moving shared.go to lib/ or shared/ and split into go.go, containers.go, etc
