### ISSUE TITLE
Tracking: release rough edges

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#16207]
Mini-tracking issue for some rough edges encountered by @pecigonzalo , most notably during the recent 3.22 release (#15023). Adapted from a Google doc he wrote up. We should split some of these into separate issues if they amount to a lot of work.

Check list indicates if an issue was created to track work, or if the problem itself was resolved directly

## Release tool

* [ ]  If you dont enter a version on `upcoming version` (_prompt_) it crashes, and you cant recover, you have to `git clean -fxd` => bug in confirmation prompt that ensures captains are aware of the configured version => fixed in https://github.com/sourcegraph/sourcegraph/pull/16689
* [x] Secrets configuration could be from something more universal (`.env`? `.envrc`?) => opened issue https://github.com/sourcegraph/sourcegraph/issues/16645
* [x] Would be nice to have a more "CLI-like" experience => fixed in https://github.com/sourcegraph/sourcegraph/pull/16519
* [x] Terrible things happen if release tool is interrupted (e.g. error on a repo) => opened issue https://github.com/sourcegraph/sourcegraph/issues/16549
* [x] Errors leave release in bad state => https://github.com/sourcegraph/sourcegraph/issues/16549

## Continuous integration

* [x] env vars in CI env are not good because they are displayed directly in the console and stored at Buildkite. => opened issue https://github.com/sourcegraph/sourcegraph/issues/16647

## Incorrect documentation

* [x] `git branch 3.22` incorrect => fixed in https://github.com/sourcegraph/about/pull/2128
* [x] ~"Upon branch cut, create and test the first release candidate:" should indicate to checkout 3.22~ this step is not required, candidates are cut from branches by the release tool
* [x] `yarn run release release-candidate:create final` should be `yarn run release release:create-candidate final` => fixed by https://github.com/sourcegraph/about/pull/2128
* [ ] Many steps on https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/RELEASING.md are already done by buildkite, should note and/or remove => fixed in https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/192
* [x] Testing instructions => covered by #15750 , instead of fixing this I believe we should just remove these steps
   * Regression tests docs point to wrong directory, should be `client/web`, tools missing
* [x] Releasing pure-docker are incorrect => opened issue https://github.com/sourcegraph/sourcegraph/issues/16646

### Tracked issues

@bobheadxi: __0.50d__

- [ ] release: continue on errors ([#16549](https://github.com/sourcegraph/sourcegraph/issues/16549)) __0.50d__

Completed
- [x] (🏁 1 day ago) release: remove manual regression testing from release process ([~#15750~](https://github.com/sourcegraph/sourcegraph/issues/15750))

**Comment by bobheadxi** [comment]
Put an 0.5d estimate on this for:

* Make PRs for the super-low-hanging fruit
* Create issues and prioritize everything else
