### ISSUE TITLE
Cloud 2020-12-02 Tracking issue

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#16237]
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

@asdine 12/01 - 12/03 (UAE National Holiday)
@ryanslade  12/09 - 12/11 PTO

### Tracked issues

@artemruts: __2.50d__

- [ ] GraphQL ExternalLink should expose kind: ExternalServiceKind (enum) instead of serviceType: String ([#14979](https://github.com/sourcegraph/sourcegraph/issues/14979)) __2.00d__

Completed: __0.50d__
- [x] (🏁 14 days ago) Remove Bitbucket cloud from list of code host when adding user added repos ([~#16315~](https://github.com/sourcegraph/sourcegraph/issues/16315)) __0.50d__
- [x] (🏁 6 days ago) Add resend email verification link to emails setting page ([~#16464~](https://github.com/sourcegraph/sourcegraph/pull/16464)) :shipit:

@arussellsaw: __1.00d__

Completed: __1.00d__
- [x] (🏁 13 days ago) Set read and write timeouts on gitserver http server ([~#16396~](https://github.com/sourcegraph/sourcegraph/pull/16396)) :shipit:
- [x] (🏁 13 days ago) Instrument when gitserver janitor is running ([~#16397~](https://github.com/sourcegraph/sourcegraph/pull/16397)) :shipit:
- [x] (🏁 12 days ago) Allow resending verification emails ([~#16310~](https://github.com/sourcegraph/sourcegraph/issues/16310)) __1.00d__
- [x] (🏁 6 days ago) Fetch affiliated repos from code hosts for repo selection screen. ([~#16501~](https://github.com/sourcegraph/sourcegraph/issues/16501))

@asdine: __4.00d__

Completed: __4.00d__
- [x] (🏁 15 days ago) Support filtering repos by owner in API ([~#15488~](https://github.com/sourcegraph/sourcegraph/issues/15488)) __1.00d__
- [x] (🏁 6 days ago) Add a dedicated method to fetch only a subset of repository columns ([~#16219~](https://github.com/sourcegraph/sourcegraph/issues/16219); PRs: ~[#16437](https://github.com/sourcegraph/sourcegraph/pull/16437)~, ~[#16590](https://github.com/sourcegraph/sourcegraph/pull/16590)~)
- [x] (🏁 6 days ago) Remove Repo store OnlyRepoIDs option ([~#16613~](https://github.com/sourcegraph/sourcegraph/pull/16613)) :shipit:
- [x] (🏁 6 days ago) Change global repo type structure ([~#16615~](https://github.com/sourcegraph/sourcegraph/pull/16615)) :shipit:
- [x] (🏁 6 days ago) Delete repo-updater Repo types ([~#16618~](https://github.com/sourcegraph/sourcegraph/pull/16618)) :shipit:
- [x] (🏁 4 days ago) repo-updater: Find root cause of memory spikes ([~#16679~](https://github.com/sourcegraph/sourcegraph/issues/16679); PRs: ~[#16688](https://github.com/sourcegraph/sourcegraph/pull/16688)~)
- [x] (🏁 2 days ago) repo store: Replace all calls to repo-updater's Insert with internal/db/repos#Create ([~#14711~](https://github.com/sourcegraph/sourcegraph/issues/14711); PRs: ~[#15530](https://github.com/sourcegraph/sourcegraph/pull/15530)~, ~[#16213](https://github.com/sourcegraph/sourcegraph/pull/16213)~) __1.00d__ 🧶
- [x] (🏁 2 days ago) repo store: Replace all calls to repo-updater's Delete with internal/db/repos#Delete ([~#14712~](https://github.com/sourcegraph/sourcegraph/issues/14712); PRs: ~[#15530](https://github.com/sourcegraph/sourcegraph/pull/15530)~, ~[#16215](https://github.com/sourcegraph/sourcegraph/pull/16215)~) __1.00d__ 🧶
- [x] (🏁 2 days ago) monitoring: Add container restart alerts for repo-updater ([~#16653~](https://github.com/sourcegraph/sourcegraph/issues/16653); PRs: ~[#16664](https://github.com/sourcegraph/sourcegraph/pull/16664)~)
- [x] (🏁 2 days ago) repo store: Replace all calls to repo-updater's ListRepos with internal/db/repos#List ([~#14710~](https://github.com/sourcegraph/sourcegraph/issues/14710); PRs: ~[#15530](https://github.com/sourcegraph/sourcegraph/pull/15530)~, ~[#16719](https://github.com/sourcegraph/sourcegraph/pull/16719)~) __1.00d__ 🧶
- [x] (🏁 2 days ago) repo store: Stop using the global dbconn ([~#15092~](https://github.com/sourcegraph/sourcegraph/issues/15092)) 🧶
- [x] (🏁 1 day ago) Decouple repo-updater store from the rest of the codebase ([~#16753~](https://github.com/sourcegraph/sourcegraph/pull/16753)) :shipit:
- [x] (🏁 1 day ago) Remove unused calls to repo updater store ([~#16759~](https://github.com/sourcegraph/sourcegraph/pull/16759)) :shipit:
- [x] (🏁 1 day ago) Ensure repo is always hydrated when needed ([~#16713~](https://github.com/sourcegraph/sourcegraph/pull/16713)) :shipit:

@flying-robot: __3.00d__

- [ ] Add ability to schedule janitor jobs for off-hours ([#10274](https://github.com/sourcegraph/sourcegraph/issues/10274)) [👩](https://app.hubspot.com/contacts/2762526/company/554338610)

Completed: __3.00d__
- [x] (🏁 7 days ago) gitserver: periodically run git gc  ([~#16241~](https://github.com/sourcegraph/sourcegraph/issues/16241); PRs: ~[#16359](https://github.com/sourcegraph/sourcegraph/pull/16359)~) __3.00d__

@quinnkeast

- [ ] Surface sync errors to users ([#16321](https://github.com/sourcegraph/sourcegraph/issues/16321))

@ryanslade: __2.50d__

Completed: __2.50d__
- [x] (🏁 13 days ago) Temporary file size error when upserting sources ([~#16318~](https://github.com/sourcegraph/sourcegraph/issues/16318); PRs: ~[#16352](https://github.com/sourcegraph/sourcegraph/pull/16352)~, ~[#16372](https://github.com/sourcegraph/sourcegraph/pull/16372)~) 🐛
- [x] (🏁 13 days ago) repo-updater: Lazily performs deletes in UpsertRepos ([~#16404~](https://github.com/sourcegraph/sourcegraph/pull/16404)) :shipit:
- [x] (🏁 12 days ago) User added private repos are visible to all ([~#16405~](https://github.com/sourcegraph/sourcegraph/issues/16405); PRs: ~[#16435](https://github.com/sourcegraph/sourcegraph/pull/16435)~, ~[#16444](https://github.com/sourcegraph/sourcegraph/pull/16444)~)
- [x] (🏁 9 days ago) Instrument syncer errors ([~#16319~](https://github.com/sourcegraph/sourcegraph/issues/16319); PRs: ~[#16505](https://github.com/sourcegraph/sourcegraph/pull/16505)~) __0.50d__
- [x] (🏁 9 days ago) Don’t delete repos when GitHub tokens are exhausted ([~#16393~](https://github.com/sourcegraph/sourcegraph/issues/16393); PRs: ~[#16453](https://github.com/sourcegraph/sourcegraph/pull/16453)~) __1.00d__
- [x] (🏁 9 days ago) errcode: Use anonymous interfaces ([~#16522~](https://github.com/sourcegraph/sourcegraph/pull/16522)) :shipit:
- [x] (🏁 9 days ago) Revert "errcode: Use anonymous interfaces (#16522)" ([~#16542~](https://github.com/sourcegraph/sourcegraph/pull/16542)) :shipit:
- [x] (🏁 7 days ago) Handle revoked tokens during sync ([~#15739~](https://github.com/sourcegraph/sourcegraph/issues/15739); PRs: ~[#16516](https://github.com/sourcegraph/sourcegraph/pull/16516)~) __1.00d__
- [x] (🏁 4 days ago) repo-updater: Find root cause of memory spikes ([~#16679~](https://github.com/sourcegraph/sourcegraph/issues/16679); PRs: ~[#16688](https://github.com/sourcegraph/sourcegraph/pull/16688)~)
- [x] (🏁 1 day ago) repo-updater: Allow custom git update interval ([~#16765~](https://github.com/sourcegraph/sourcegraph/pull/16765)) :shipit:
- [x] (🏁 1 day ago) Rethink monitoring of remaining code host rate limits ([~#16455~](https://github.com/sourcegraph/sourcegraph/issues/16455); PRs: ~[#16716](https://github.com/sourcegraph/sourcegraph/pull/16716)~, ~[#16750](https://github.com/sourcegraph/sourcegraph/pull/16750)~)

@tsenart

- [ ] Extension registry GraphQL API is slow ([#10554](https://github.com/sourcegraph/sourcegraph/issues/10554))
- [ ] Panic during db migration ([#16159](https://github.com/sourcegraph/sourcegraph/issues/16159))
- [ ] Timeout when accessing subdirectory with only one file ( Request to https://sourcegraph.com/.api/graphql?TreeEntries failed with 504) ([#10538](https://github.com/sourcegraph/sourcegraph/issues/10538))
- [ ] Add ability to schedule janitor jobs for off-hours ([#10274](https://github.com/sourcegraph/sourcegraph/issues/10274)) [👩](https://app.hubspot.com/contacts/2762526/company/554338610)
- [ ] [Cloud] [CRITICAL] gitserver: 2s+ echo command duration test fires regularly ([#15392](https://github.com/sourcegraph/sourcegraph/issues/15392))
- [ ] monitoring: Graph each of the different API rate limits separately (rest, graphql, search) ([#16391](https://github.com/sourcegraph/sourcegraph/issues/16391))
- [ ] monitoring: Change gitserver alerts and dashboard to monitor golden signals ([#16580](https://github.com/sourcegraph/sourcegraph/issues/16580); PRs: ~[#16591](https://github.com/sourcegraph/sourcegraph/pull/16591)~)

Completed
- [x] (🏁 13 days ago) vcs/git: Remove commandRetryer ([~#16360~](https://github.com/sourcegraph/sourcegraph/pull/16360)) :shipit:
- [x] (🏁 7 days ago) monitoring: Use lines for thresholds instead fill areas ([~#16547~](https://github.com/sourcegraph/sourcegraph/pull/16547)) :shipit:
- [x] (🏁 7 days ago) go.mod: Update gonduit dependency ([~#16581~](https://github.com/sourcegraph/sourcegraph/pull/16581)) :shipit:
- [x] (🏁 7 days ago) monitoring: Disable alerting for echo_command_duration ([~#16591~](https://github.com/sourcegraph/sourcegraph/pull/16591)) :shipit:
- [x] (🏁 6 days ago) grafana: Add internal Nginx dashboards ([~#16622~](https://github.com/sourcegraph/sourcegraph/pull/16622)) :shipit:
- [x] (🏁 5 days ago) Continuously capture memory profiles in repo-updater ([~#16655~](https://github.com/sourcegraph/sourcegraph/issues/16655); PRs: ~[#16656](https://github.com/sourcegraph/sourcegraph/pull/16656)~)
- [x] (🏁 5 days ago) gitserver: Enable continuous profiling ([~#16665~](https://github.com/sourcegraph/sourcegraph/pull/16665)) :shipit:
- [x] (🏁 4 days ago) monitoring: Critical alert for 90% memory utilisation on repo-updater ([~#16652~](https://github.com/sourcegraph/sourcegraph/issues/16652); PRs: ~[#16664](https://github.com/sourcegraph/sourcegraph/pull/16664)~)
- [x] (🏁 4 days ago) repo-updater: Skip listing conflicting repos when sourcing fails ([~#16688~](https://github.com/sourcegraph/sourcegraph/pull/16688)) :shipit:
- [x] (🏁 4 days ago) frontend: Enable continuous profiling ([~#16693~](https://github.com/sourcegraph/sourcegraph/pull/16693)) :shipit:
- [x] (🏁 4 days ago) pubsub: Use explicit credentials file ([~#16695~](https://github.com/sourcegraph/sourcegraph/pull/16695)) :shipit:
- [x] (🏁 2 days ago) Remove gitserver.Repo type ([~#16707~](https://github.com/sourcegraph/sourcegraph/pull/16707)) :shipit:
- [x] (🏁 1 day ago) Some commits not syncing with Gerrit-hosted git repository ([~#16387~](https://github.com/sourcegraph/sourcegraph/issues/16387))
- [x] (🏁 1 day ago) monitoring: Disable alerting for syntect_server ([~#16773~](https://github.com/sourcegraph/sourcegraph/pull/16773)) :shipit:

@unknwon: __4.50d__

- [ ] sourcegraph/customer ([#148](https://github.com/sourcegraph/customer/issues/148)) __2.00d__ 👩

Completed: __2.50d__
- [x] (🏁 14 days ago) graphqlbackend: add new scalar BigInt to fix int overflow ([~#16345~](https://github.com/sourcegraph/sourcegraph/pull/16345)) :shipit:
- [x] (🏁 13 days ago) gqltest: add a test to cover repository with space in its name ([~#15905~](https://github.com/sourcegraph/sourcegraph/issues/15905); PRs: ~[#16424](https://github.com/sourcegraph/sourcegraph/pull/16424)~) __0.50d__
- [x] (🏁 4 days ago) Write an RFC for First-class Perforce integration ([~#16508~](https://github.com/sourcegraph/sourcegraph/issues/16508)) __2.00d__ 👩

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by ryanslade** [comment]
### This week

* Worked on some of the issues that came out of an ops incident: https://docs.google.com/document/d/1dtrOHs5STJYKvyjigL1kMm6u-W0mlyRSyVxPfKIOfEw/edit#heading=h.r7tahw4ry14v
* Ironed out some issues around adding private code on .com as we test with dummy repos there
* Looked into reducing how often we trigger some slow queries, the deployment with the change appeared to reduce CPU usage in our SQL cluster quite significantly (see the drop at about 6:30):

<img width="1493" alt="Screenshot 2020-12-03 at 21 31 04" src="https://user-images.githubusercontent.com/25610/101177939-08a1bb80-3651-11eb-855e-60b91985a0a2.png">

### Next week

* Keep working on ticket that came our of ops incident as well as other bugs
* Work on handling revoked tokens during sync

**Comment by unknwon** [comment]
### Last week

- Added multiple test to our backend integration test suite
- Investigated on sourcegraph/customer (#148)

### This week

- Finish investigating sourcegraph/customer (#148)
- Start working on overhaul aggregated errors sent to Sentry (#16109)

**Comment by unknwon** [comment]
### Last week

* Finished Perforce technical PoC with permissions (#148)
* Drafted [RFC 277: First-class Perforce integration](https://docs.google.com/document/d/1r6ngZNOENVikcEzMU4v8b3TNT2TQydzILVDRqmJuzqY/edit?ts=5fd214ee#heading=h.trqab8y0kufp) and approved, created a [project](https://github.com/sourcegraph/sourcegraph/projects/13) for it.
* Worked on a hotfix for our user code host connections validation (#16614)

### This week

- Wrapping up on overhaul aggregated errors sent to Sentry (#16109)
- Expecting more polish work for the next cycle since it would be short for many of us.

**Comment by asdine** [comment]
### Last week

- Merged repository types and helpers and worked on decoupling repo-updater from the rest of the codebase

### This week

- Finish the decoupling and work on improving the store layer

**Comment by ryanslade** [comment]
Reopening this issue until since the cycle only ends tomorrow and it looks like the tracking tool doesn't update it when it's closed.
