### ISSUE TITLE
Campaigns Sprint 6 Tracking issue

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#16327]
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

* Adam: 1d (December 4)
* Thorsten: ~2d (one full day, probably December 4, and then toddler-daycare whenever that's required)
* Erik: ~1d (probably one day on the 10th)

### Tracked issues

@LawnGnome: __5.00d__

Completed: __5.00d__
- [x] (🏁 14 days ago) Add the ablity to download changeset diffs via the UI ([~#16098~](https://github.com/sourcegraph/sourcegraph/issues/16098); PRs: ~[#16337](https://github.com/sourcegraph/sourcegraph/pull/16337)~) __1.00d__
- [x] (🏁 8 days ago) Indicate newer campaign spec available when looking at outdated spec ([~#14532~](https://github.com/sourcegraph/sourcegraph/issues/14532); PRs: ~[#16146](https://github.com/sourcegraph/sourcegraph/pull/16146)~) __0.50d__
- [x] (🏁 8 days ago) Add migration to drop campaigns backup tables ([~#16223~](https://github.com/sourcegraph/sourcegraph/issues/16223); PRs: ~[#16532](https://github.com/sourcegraph/sourcegraph/pull/16532)~) __0.50d__ 🧶
- [x] (🏁 7 days ago) campaigns: reword download diff link ([~#16553~](https://github.com/sourcegraph/sourcegraph/pull/16553)) :shipit:
- [x] (🏁 6 days ago) campaigns: add a preparing step progress message ([~#401~](https://github.com/sourcegraph/src-cli/pull/401)) :shipit:
- [x] (🏁 6 days ago) Changeset text search ([~#15781~](https://github.com/sourcegraph/sourcegraph/issues/15781); PRs: ~[#16202](https://github.com/sourcegraph/sourcegraph/pull/16202)~) __1.00d__
- [x] (🏁 5 days ago) ~campaigns: add -vv to show executed commands~ ([~#402~](https://github.com/sourcegraph/src-cli/pull/402)) :shipit:
- [x] (🏁 3 days ago) Add views for tracked_mappings and branch_mappings ([~#16271~](https://github.com/sourcegraph/sourcegraph/issues/16271); PRs: ~[#16548](https://github.com/sourcegraph/sourcegraph/pull/16548)~) __0.50d__ 🧶
- [x] (🏁 today) campaigns: implement licensing ([~#15715~](https://github.com/sourcegraph/sourcegraph/issues/15715); PRs: ~[#16687](https://github.com/sourcegraph/sourcegraph/pull/16687)~, ~[#410](https://github.com/sourcegraph/src-cli/pull/410)~) __1.00d__
- [x] (🏁 today) campaigns: download diff button should not show on imported changesets ([~#16778~](https://github.com/sourcegraph/sourcegraph/issues/16778); PRs: ~[#16805](https://github.com/sourcegraph/sourcegraph/pull/16805)~) __0.50d__ 🐛

@eseliger: __7.00d__

Completed: __7.00d__
- [x] (🏁 6 days ago) Remove syncer prioritizing changesets that don't have a diffstat ([~#16604~](https://github.com/sourcegraph/sourcegraph/issues/16604); PRs: ~[#16605](https://github.com/sourcegraph/sourcegraph/pull/16605)~) 🧶
- [x] (🏁 4 days ago) Fix racy read on r.namespace ([~#16637~](https://github.com/sourcegraph/sourcegraph/pull/16637)) :shipit:
- [x] (🏁 4 days ago) Introduce store package ([~#16634~](https://github.com/sourcegraph/sourcegraph/pull/16634)) :shipit:🧶
- [x] (🏁 3 days ago) Add views for tracked_mappings and branch_mappings ([~#16271~](https://github.com/sourcegraph/sourcegraph/issues/16271); PRs: ~[#16548](https://github.com/sourcegraph/sourcegraph/pull/16548)~) __0.50d__ 🧶
- [x] (🏁 3 days ago) Changeset events for gitlab merge and close events not inferrable from notes ([~#15899~](https://github.com/sourcegraph/sourcegraph/issues/15899); PRs: ~[#16050](https://github.com/sourcegraph/sourcegraph/pull/16050)~) __1.00d__ 🐛
- [x] (🏁 3 days ago) Delta API design work input and validation ([~#16054~](https://github.com/sourcegraph/sourcegraph/issues/16054)) __2.00d__
- [x] (🏁 2 days ago) Refactor campaigns go tests ([~#16685~](https://github.com/sourcegraph/sourcegraph/pull/16685)) :shipit:🧶
- [x] (🏁 2 days ago) Refactor campaigns code into several packages ([~#16686~](https://github.com/sourcegraph/sourcegraph/pull/16686)) :shipit:🧶
- [x] (🏁 2 days ago) Remove httpcli from campaigns resolvers and service packages ([~#16690~](https://github.com/sourcegraph/sourcegraph/pull/16690)) :shipit:🧶
- [x] (🏁 2 days ago) Fix some golanglint warnings in campaigns packages ([~#16691~](https://github.com/sourcegraph/sourcegraph/pull/16691)) :shipit:🧶
- [x] (🏁 2 days ago) Make campaigns pkg the only entry-point for external usage of campaigns code ([~#16708~](https://github.com/sourcegraph/sourcegraph/pull/16708)) :shipit:🧶
- [x] (🏁 1 day ago) Find solution to preview changesets that are to be closed in the delta API ([~#16059~](https://github.com/sourcegraph/sourcegraph/issues/16059); PRs: ~[#16535](https://github.com/sourcegraph/sourcegraph/pull/16535)~) __3.00d__
- [x] (🏁 1 day ago) Add changelog entry for release 3.23 ([~#16766~](https://github.com/sourcegraph/sourcegraph/pull/16766)) :shipit:
- [x] (🏁 today) campaigns: update UI changelog for 3.23 ([~#16331~](https://github.com/sourcegraph/sourcegraph/issues/16331)) __0.50d__

@mrnugget: __8.00d__

Completed: __8.00d__
- [x] (🏁 14 days ago) Finish snapshot testing for TUI in src-cli ([~#16330~](https://github.com/sourcegraph/sourcegraph/issues/16330)) __0.50d__
- [x] (🏁 13 days ago) Mark worker records that exhausted retries as failed ([~#16046~](https://github.com/sourcegraph/sourcegraph/issues/16046)) __0.50d__
- [x] (🏁 13 days ago) Site admin, admin user campaigns tokens, remove user token actually removed own token ([~#16217~](https://github.com/sourcegraph/sourcegraph/issues/16217)) __1.00d__ 🐛
- [x] (🏁 11 days ago) Faster campaigns tests, part 2: determine plan without a database. ([~#16443~](https://github.com/sourcegraph/sourcegraph/pull/16443)) :shipit:
- [x] (🏁 7 days ago) campaigns: speed up tests by splitting up integration tests into smaller unit tests  ([~#16320~](https://github.com/sourcegraph/sourcegraph/issues/16320); PRs: ~[#16441](https://github.com/sourcegraph/sourcegraph/pull/16441)~, ~[#16507](https://github.com/sourcegraph/sourcegraph/pull/16507)~, ~[#16513](https://github.com/sourcegraph/sourcegraph/pull/16513)~) __2.00d__ 🧶
- [x] (🏁 7 days ago) src-cli: long-running containers are not killed when hitting Ctrl-C ([~#16026~](https://github.com/sourcegraph/sourcegraph/issues/16026)) __1.00d__ 🐛
- [x] (🏁 5 days ago) Add transformChanges to campaign spec and document it ([~#16235~](https://github.com/sourcegraph/sourcegraph/pull/16235)) :shipit:
- [x] (🏁 5 days ago) Allow to create multiple changeset specs in a single repository ([~#14970~](https://github.com/sourcegraph/sourcegraph/issues/14970)) __3.00d__

@rrhyne: __0.50d__

Completed: __0.50d__
- [x] (🏁 8 days ago) Indicate newer campaign spec available when looking at outdated spec ([~#14532~](https://github.com/sourcegraph/sourcegraph/issues/14532); PRs: ~[#16146](https://github.com/sourcegraph/sourcegraph/pull/16146)~) __0.50d__
- [x] (🏁 1 day ago) Add campaign requirements ([~#16676~](https://github.com/sourcegraph/sourcegraph/pull/16676)) :shipit:
- [x] (🏁 today) Design campaigns licensing flow and messaging  ([~#15351~](https://github.com/sourcegraph/sourcegraph/issues/15351))
- [x] (🏁 today) campaigns frontend: number of entries in changeset list doesn't match numbers at top of view ([~#16029~](https://github.com/sourcegraph/sourcegraph/issues/16029))

@tbodt

Completed
- [x] (🏁 6 days ago) ~Fix broken "Getting started with campaigns" link~ ([~#14592~](https://github.com/sourcegraph/sourcegraph/pull/14592)) :shipit:

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by eseliger** [comment]
### Weekly update

Last week, I worked mostly on getting everything related to changeset rewiring/reconciling into a shape that supports "dry-runs", which ultimately led into a rather lean PR that implemented the delta API resolvers, so backend is mostly done for now. Afterwards, I implemented a first take on the UI for that, so we have something to look at, other than just the API response. That should help us find issues with it early on. 

This week, I'll pair with design on the final appearance of the preview page. Also, I'll try to dig into getting closed changesets previewed in that UI as well, since that's the biggest unknown for this upcoming sprint. Besides, I might tackle one or two of the smaller issues.

**Comment by LawnGnome** [comment]
#### Weekly update: 2020-11-24 to 2020-11-30

Last week, I implemented support for changeset text search, and adding a banner to indicate that a newer campaign spec is available. Those are now complete, except for implementing any design tweaks required before release.

This week, I'll be working on end-to-end tests for src-cli, followed by our licensing changes for 3.23 and changeset spec text search, which is primarily adapting the changeset search to operate on specs.

**Comment by mrnugget** [comment]
### Weekly Update

I'm writing this update today, on a Monday, because I'm going to take tomorrow off (the gaming computer is finally here, put that in the email, Chris!).

After planning our new sprint last week, I started by checking off some small tickets, which all went well without any surprises. While working on the frontend I experienced some dev-environment pains that I've started to document and that I want to turn into something productive (a plan for keeping our developers happy and for ensuring that onboarding new engineers doesn't devolve into us saying "I'm sorry" a bunch of times). Adam and Erik already fixed some of these pain points on Friday (thank you!), but I still want to keep an eye on it.

I then focused on #1 of my two big tickets this iteration: speeding up our campaigns test suite. Today I opened the last PR for that, the fourth one, and with that I brought the runtime of the tests in the `campaigns` package down to ~7s from ~15s. I think that's better than expected, to be honest!

Once I'm back on Wednesday I'm going to focus on RFC265 for the remainder of the sprint.

**Comment by eseliger** [comment]
### Weekly update

Last week, I paired with design on the delta UI, worked on GitLab state change events and some webhooks fixes and got started on being able to display close operations in the preview UI. On the debt side, I got some dev environment QoL improvements in and cleaned up our frontend test suite, which we didn't need anymore since we migrated to using storybooks and testing in there.

This week, I want to finish up the close preview API changes, GitLab state change events and my ticket for pairing / giving feedback on the delta UI. Last bit for this sprint would then be to implement those designs. So far they are far more advanced/nuanced than I anticipated them to be (which is great), so let's see where the planned work amount gets us.

**Comment by rrhyne** [comment]
Last week I worked on the initial changeset text search, customer research for monorepos, participated in some sales calls  and created presentations for the CE and Sales teams.

This week, I am designing delta (update campaign) UI, doing more customer research and I hope to get a first rev of a CE pitch deck done.

**Comment by LawnGnome** [comment]
#### Weekly update: 2020-12-01 to 2020-12-07

Last week, I did essentially none of the things I thought I was going to do. I paired with Rob on the changeset text search design, and then addressed feedback on changeset text search and the newer spec banner, rebased them repeatedly to deal with shifting code underneath, and merged the latter. (The former is awaiting one more re-review, since we're still several days from branch cut, so I don't feel the need to rush it.)

Beyond that, I worked on allowing changeset diffs to be downloaded (wording tweak for that coming soon!), improved our developer experience around monitoring our TypeScript codebase for GraphQL operation changes, improved my own personal development environment by setting up a temporary cloud devbox, finished burning the ~boats~ pre-spec campaign tables, and took a day off. The day off was nice.

This week, I'll be doing the things I didn't do last week: changeset spec text search, end to end testing, and implementing the licensing checks for 3.23.

**Comment by mrnugget** [comment]
### Weekly Update

I'm going on vacation tomorrow and will be until Jan 4.

In the past week I shipped the experimental version of RFC 265: `transformChanges`. Including documentation and a how-to that explains how to use it to split up large diffs. I spent the remainder of my time in the sprint fixing two bugs in `src-cli` (https://github.com/sourcegraph/src-cli/pull/403, https://github.com/sourcegraph/src-cli/pull/407), writing documentation to help our CE team help our campaigns customers (https://github.com/sourcegraph/sourcegraph/pull/16748, https://github.com/sourcegraph/sourcegraph/pull/16770) and digging into a Docker bug that caused `src` to fail when running containers (https://github.com/sourcegraph/src-cli/issues/405#issuecomment-744504585).

**Comment by eseliger** [comment]
### Weekly Update

Last week, I worked on the delta api and shipped a new graphql endpoint to get a precise result that also supports close and detach operations to be displayed. In addition, I did a couple of QoL improvements to our codebase, like a restructuring and some improvements to test run times, and worked together with Rob on the designs for the final version of the delta UI.

This week is my last week before the holidays, so I'll only be available for the rest of this week. I will most likely pick up a couple of smaller issues that I'm certain I can finish by end of the week, so they aren't lying around for too long.
