### ISSUE TITLE
Tracking issue: Search contexts

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#16509]
### Tracked issues

@unassigned

Completed
- [x] (🏁 598 days ago) https://github.com/sourcegraph/sourcegraph/issues/24860 

@jdorfman

Completed
- [x] (🏁 567 days ago) https://github.com/sourcegraph/sourcegraph/pull/32869 

@limitedmage

Completed
- [x] (🏁 965 days ago) https://github.com/sourcegraph/sourcegraph/issues/16364 

@novoselrok

Completed
- [x] (🏁 993 days ago) https://github.com/sourcegraph/sourcegraph/issues/17398 
- [x] (🏁 986 days ago) https://github.com/sourcegraph/sourcegraph/issues/17676 
- [x] (🏁 980 days ago) https://github.com/sourcegraph/sourcegraph/issues/17679 
- [x] (🏁 978 days ago) https://github.com/sourcegraph/sourcegraph/issues/17762 
- [x] (🏁 978 days ago) https://github.com/sourcegraph/sourcegraph/issues/16362 
- [x] (🏁 972 days ago) https://github.com/sourcegraph/sourcegraph/issues/16363 
- [x] (🏁 971 days ago) https://github.com/sourcegraph/sourcegraph/issues/16365 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
