### ISSUE TITLE
Code Intelligence Sprint 2 Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#16515]
### Plan

This sprint covers 2020/12/07 to 2020/12/18.

### Availability

Owen: 8d (4x10 workweek)
Maria: 8d (off 12/07-08)
Eric: 10d
Noah: 10d

### Tracked issues

@Strum355: __5.00d__

- [ ] ~codeintel: Add index configuration for 5 C++ repositories on Cloud~ ([#16520](https://github.com/sourcegraph/sourcegraph/issues/16520)) __4.00d__

Completed: __1.00d__
- [x] (🏁 28 days ago) RFC 201: Add UI for configuration ([~#14571~](https://github.com/sourcegraph/sourcegraph/issues/14571)) __1.00d__
- [x] (🏁 26 days ago) code-intel: pass hex byte encoded commit hash to query ([~#16558~](https://github.com/sourcegraph/sourcegraph/pull/16558)) :shipit:
- [x] (🏁 18 days ago) autoindexer: Allow commands to be configured in the index container pre-indexing ([~#16726~](https://github.com/sourcegraph/sourcegraph/issues/16726))

@efritz: __9.00d__

- [ ] ~codeintel: Add index configuration for 5 C++ repositories on Cloud~ ([#16520](https://github.com/sourcegraph/sourcegraph/issues/16520)) __4.00d__
- [ ] ~codeintel: git diffing fails graphql requests related to force-pushed commits~ ([#12588](https://github.com/sourcegraph/sourcegraph/issues/12588)) __0.50d__ 🐛
- [ ] ~executor: Verify checksum of resources before execution~ ([#15937](https://github.com/sourcegraph/sourcegraph/issues/15937)) __0.50d__

Completed: __4.00d__
- [x] (🏁 28 days ago) RFC 201: Add UI for configuration ([~#14571~](https://github.com/sourcegraph/sourcegraph/issues/14571)) __1.00d__
- [x] (🏁 27 days ago) monitoring: Fix job name in frontend (for dev) ([~#16551~](https://github.com/sourcegraph/sourcegraph/pull/16551)) :shipit:
- [x] (🏁 25 days ago) executor: Fix too many open files ([~#16666~](https://github.com/sourcegraph/sourcegraph/pull/16666)) :shipit:
- [x] (🏁 22 days ago) ~codeintel: Optimize nearest upload operations~ ([~#16568~](https://github.com/sourcegraph/sourcegraph/pull/16568)) :shipit:
- [x] (🏁 21 days ago) codeintel: Update storybooks ([~#16639~](https://github.com/sourcegraph/sourcegraph/pull/16639)) :shipit:
- [x] (🏁 21 days ago) LSIF Indexing fails in 3.22.1 ([~#16667~](https://github.com/sourcegraph/sourcegraph/issues/16667); PRs: ~[#16636](https://github.com/sourcegraph/sourcegraph/pull/16636)~)
- [x] (🏁 21 days ago) codeintel: Refrain from using git log --all in directed path ([~#16733~](https://github.com/sourcegraph/sourcegraph/pull/16733)) :shipit:
- [x] (🏁 20 days ago) codeintel: Update commit graph updater metrics ([~#16527~](https://github.com/sourcegraph/sourcegraph/issues/16527); PRs: ~[#16739](https://github.com/sourcegraph/sourcegraph/pull/16739)~) __0.50d__
- [x] (🏁 20 days ago) workerutil: Initialize worker components with unique names ([~#16813~](https://github.com/sourcegraph/sourcegraph/pull/16813)) :shipit:
- [x] (🏁 20 days ago) codeintel: Remove duplicated store functions ([~#16815~](https://github.com/sourcegraph/sourcegraph/pull/16815)) :shipit:
- [x] (🏁 20 days ago) dbworker: Add tracing and metrics ([~#16817~](https://github.com/sourcegraph/sourcegraph/pull/16817)) :shipit:
- [x] (🏁 20 days ago) apiworker: Add tracing and metrics to client ([~#16818~](https://github.com/sourcegraph/sourcegraph/pull/16818)) :shipit:
- [x] (🏁 19 days ago) codeintel: Reduce gitserver errors for missing revisions ([~#16845~](https://github.com/sourcegraph/sourcegraph/pull/16845)) :shipit:
- [x] (🏁 19 days ago) codeintel: Reorganize background package ([~#16843~](https://github.com/sourcegraph/sourcegraph/pull/16843)) :shipit:
- [x] (🏁 19 days ago) codeintel: Handle unknown commits when recalculating commit graph for a repository ([~#16844~](https://github.com/sourcegraph/sourcegraph/pull/16844)) :shipit:
- [x] (🏁 19 days ago) workerutil: Standardize metrics ([~#16853~](https://github.com/sourcegraph/sourcegraph/pull/16853)) :shipit:
- [x] (🏁 19 days ago) codeintel: Emit additional metrics ([~#16856~](https://github.com/sourcegraph/sourcegraph/pull/16856)) :shipit:
- [x] (🏁 18 days ago) codeintel: Additional executor metrics ([~#16864~](https://github.com/sourcegraph/sourcegraph/pull/16864)) :shipit:
- [x] (🏁 18 days ago) codeintel: Emit metrics from auto-index scheduler routines ([~#16887~](https://github.com/sourcegraph/sourcegraph/pull/16887)) :shipit:
- [x] (🏁 17 days ago) executor: Add metrics dashboard ([~#15938~](https://github.com/sourcegraph/sourcegraph/issues/15938); PRs: ~[#16806](https://github.com/sourcegraph/sourcegraph/pull/16806)~) __2.00d__
- [x] (🏁 17 days ago) executor-queue: Update metrics dashboard ([~#15939~](https://github.com/sourcegraph/sourcegraph/issues/15939); PRs: ~[#16806](https://github.com/sourcegraph/sourcegraph/pull/16806)~) __0.50d__
- [x] (🏁 17 days ago) grafana: Do not sum by high-cardinality {{op}} on alarm-able data ([~#16932~](https://github.com/sourcegraph/sourcegraph/pull/16932)) :shipit:
- [x] (🏁 17 days ago) chore: Add missing readmes for enterprise/cmd services ([~#16923~](https://github.com/sourcegraph/sourcegraph/pull/16923)) :shipit:
- [x] (🏁 17 days ago) codeintel: Call ResolveRev to distinguish gitserver errors ([~#16934~](https://github.com/sourcegraph/sourcegraph/pull/16934)) :shipit:
- [x] (🏁 17 days ago) codeintel: Fix IsRevisionNotFound check ([~#16936~](https://github.com/sourcegraph/sourcegraph/pull/16936)) :shipit:

@scalabilitysolved

- [ ] ~Upload of large LSIF dump fails~ ([#16242](https://github.com/sourcegraph/sourcegraph/issues/16242))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by macraig** [comment]
**Completed 2020/12/07-12/11**
- Uber issue catch up and next steps
- Continued work on user study

**Planned 2020/12/14-12/18**
- Work on and present roadmap to CE/Sales
- Get user test on usertesting.com

**Comment by efritz** [comment]
**Completed 2020/12/07-12/11**

Fixed customer issue in https://github.com/sourcegraph/sourcegraph/issues/16667. Their instance appears stable with patch. Merged this to the main branch and will ensure that it has a similar benefit on dotcom.

**Planned 2020/12/14-12/18**

Work on increasing observability in the auto-indexer.

**Comment by efritz** [comment]
**Completed 2020/12/14-12/18**

- Paired with @Strum355 on https://github.com/sourcegraph/sourcegraph/issues/16726 to get configuration into the UI so we could more easily configure C++ index jobs
- @Strum355 managed to configure a job so that lsif-clang indexes itself on a local instance :tada:
- I worked additionally to clean up metrics and dashboards so that the cloud-alerts channel does not keep blowing up with code intel false alarms over the vacation.

**Remainder of the year**

![image](https://user-images.githubusercontent.com/103087/102665033-a6b17d80-4149-11eb-905f-731324b3782e.png)

**Comment by efritz** [comment]
Following up in https://github.com/sourcegraph/sourcegraph/issues/17028.
