### ISSUE TITLE
R.N onboarding plan

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#16521]
### Week 1

Go through [General Onboarding](https://about.sourcegraph.com/handbook/people-ops/onboarding#for-all-new-teammates) and [Engineering Onboarding](https://about.sourcegraph.com/handbook/engineering/onboarding#engineering-onboarding).

- [x] Set up an architecture deep dive session with @tsenart 

### Week 2 - 3

Get started with some smaller tasks:

- [x] Global filter values in quotes is not honored in URL parameters (case, patterntype)  https://github.com/sourcegraph/sourcegraph/issues/16186
- [x] settings page expects git ref, we return git rev https://github.com/sourcegraph/sourcegraph/issues/13787
- [x] syntax highlighting the wrong line https://github.com/sourcegraph/sourcegraph/issues/10468
