### ISSUE TITLE
3.22.1 patch release tracking issue

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#16531]
# 3.22.1 Patch Release

**Attention developers:** to get your commits in `main` included in this patch release, please file a [patch request](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=&labels=team%2Fdistribution&template=request_patch_release.md&title=3.22.1%3A+) for review. Only check off items if the commit have been cherry-picked into the `3.22` branch by the release captain.

- [x] request https://github.com/sourcegraph/sourcegraph/issues/16526, PR https://github.com/sourcegraph/sourcegraph/pull/16517
---

**Note:** All `yarn run release ...` commands should be run from folder `dev/release`.

**Note:** All `yarn run test ...` commands should be run from folder `web`.

## Setup

- [x] Ensure release configuration in [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) on `main` is up to date with the parameters for the current release.
- [x] Ensure the latest version of the release tooling has been built before each step using `yarn run build` in `dev/release`.

## Prepare release

Ensure all patch changes are included:

- [x] Ensure that all [patch request issues](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Apatch-release-request) are accounted for, and that the commits listed above has been cherry-picked to [`3.22` release branch](https://github.com/sourcegraph/sourcegraph/tree/3.22), and ensure CI passes on the release branch.
    ```
    git checkout 3.22
    git pull
    git cherry-pick <commit0> <commit1> ... # all relevant commits from the main branch
    git push 3.22
    ```
- [x] Cherry-pick relevant [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) configuration changes from `master` to the [`3.22` release branch](https://github.com/sourcegraph/deploy-sourcegraph/tree/3.22), and ensure CI passes on the release branch.
    ```
    git checkout 3.22
    git pull
    git cherry-pick <commit0> <commit1> ... # all relevant commits from the master branch
    git push 3.22
    ```
- [x] Cherry-pick relevant [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) configuration changes from `master` to the [`3.22` release branch](https://github.com/sourcegraph/deploy-sourcegraph-docker/tree/3.22), and ensure CI passes on the release branch.
    ```
    git checkout 3.22
    git pull
    git cherry-pick <commit0> <commit1> ... # all relevant commits from the master branch
    git push 3.22
    ```

Create and test release candidates:

- [x] Push a release candidate tag:
    ```
    yarn run release release-candidate:create 1
    ```
- [x] Wait for the release candidate Docker images to be available in [Docker Hub](https://hub.docker.com/r/sourcegraph/server/tags).
- [x] Ensure the release candidate starts for upgrades and new instances:
    ```
    # 1. Answer YES to delete /tmp/sourcegraph with the old image
    IMAGE=sourcegraph/server:3.22 ./dev/run-server-image.sh
    
    # 2. Answer NO to delete /tmp/sourcegraph with the new image
    IMAGE=sourcegraph/server:3.22.1-rc.1 ./dev/run-server-image.sh
    
    # 3. Answer YES to delete /tmp/sourcegraph with the new image
    IMAGE=sourcegraph/server:3.22.1-rc.1 ./dev/run-server-image.sh
    ```

## Stage release

- [x] Tag the final release:
    ```
    yarn run release release-candidate:create final
    ```
- [x] Wait for the release Docker images to be available in [Docker Hub](https://hub.docker.com/r/sourcegraph/server/tags).
- [x] Open PRs that publish the new release and address any action items required to finalize draft PRs (track PR status via the [generated release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns)):
  ```sh
  yarn run release release:stage
  ```

## Release

- [x] From the [release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns), merge the release-publishing PRs created previously.
  - For [sourcegraph](https://github.com/sourcegraph/sourcegraph), also:
    - [x] Cherry pick the release-publishing PR from `sourcegraph/sourcegraph@main` into the release branch.
- [x] Finalize and announce that the release is live:
  ```sh
  yarn run release release:close
  ```

## Post-release

- [ ] Open a PR to update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the parameters for the current release.
- [ ] Run `yarn build` to rebuild the release script.
- [ ] Close this issue.

**Note:** If another patch release is requested after the release, ask that a [patch request issue](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=&labels=team%2Fdistribution&template=request_patch_release.md) be filled out and approved first.

**Comment by bobheadxi** [comment]
I was able to confirm `sourcegraph/server:3.22.1-rc.1` starts up fine
