### ISSUE TITLE
Andre Eleuterio: On-boarding

### ISSUE THREAD

**Issue by chayim** [sourcegraph/sourcegraph#16582]
### Week 1

- [x] General [onboarding](https://about.sourcegraph.com/handbook/people-ops/onboarding).
  - [x] Add yourself to the [team page](../../../company/team/index.md).
  - [x] Watch the [new team member intro from the CEO](https://www.youtube.com/watch?v=EVHUGZe5uts)
  - [x] Set up a recurring weekly 25-minute [1-1 meeting](../../leadership/1-1.md) with your manager (e.g., `1-1 $YOURNAME-$MANAGERNAME`).
  - [x] If you are not familiar with Git, complete the [Git introduction](git_intro.md).
  - [x] Read the first page of [Sourcegraph's user documentation](https://docs.sourcegraph.com/user).
  - [ ] It might not be immediately necessary, but if you ever need to click a HubSpot link just ask for access in #sales.
  - [x] Go through the [analytics onboarding](https://sourcegraph.looker.com/projects/sourcegraph_events/files/1_home.md). This onboarding is within Looker, so if you don't have an account you can ask for access in #analytics. 
  - [x] [Add your working hours to Google Calendar](https://calendar.google.com/calendar/r/settings) so your teammates know when it is safe to add meetings to your calendar.
- [x] Engineering [onboarding](https://about.sourcegraph.com/handbook/engineering/onboarding)
- [x] Review https://docs.sourcegraph.com/dev/architecture
- [x] Chat with each team and understand what they own / do.
- [x] [Threat model security issue #115](https://github.com/sourcegraph/security-issues/issues/115)

### Week 2 - 8
- [x] [security issue #94](https://github.com/sourcegraph/security-issues/issues/94)
- [x] [security issue #123](https://github.com/sourcegraph/security-issues/issues/123)
- [x] [security issue #20](https://github.com/sourcegraph/security-issues/issues/20)
- [x] [automate security issue #120](https://github.com/sourcegraph/security-issues/issues/120)
- [x] [contribute to security issue #115](https://github.com/sourcegraph/security-issues/issues/115)

**Comment by andreeleuterio** [comment]
closing this as i've been with the company for almost three years
