### ISSUE TITLE
Distribution: 2020.12.14 - Kickass Fly

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#16669]
#### [Support new and existing deployments](https://github.com/orgs/sourcegraph/projects/74)

This is an ongoing expense, we anticipate this taking no more than 5d of work spread across the entire team.

#### [Seamless Upgrades](https://github.com/orgs/sourcegraph/projects/71?card_filter_query=milestone%3A%22dist%3A+2020.12.14%22)

Re-synchronize our base with [sourcegraph.com](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/) and add tests to components missing them.

- @ggilmore 
- @uwedeportivo 
- @daxmc99 

#### [Monitoring Redux](https://github.com/orgs/sourcegraph/projects/112)

Make our monitoring stack more compelling for engineers at Sourcegraph to interact with and build on top of. Support more use cases specific to the needs of engineers at Sourcegraph and Sourcegraph Cloud.

- @bobheadxi 
- @davejrt 
- @pecigonzalo 

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

- @bobheadxi: 15th, 16th (2d)
- @pecigonzalo: 21st->25th (5d)
- @davejrt: 24th->25th (2d)
- @daxmc99: 21st->25th (5d)
- @uwedeportivo: 24th, 25th (2d)
- @ggilmore: 24, 25th (2d)

### Tracked issues

@bobheadxi: __7.50d__

Completed: __7.50d__
- [x] (🏁 21 days ago) Tracking: release rough edges ([~#16207~](https://github.com/sourcegraph/sourcegraph/issues/16207)) __0.50d__
- [x] (🏁 17 days ago) prom-wrapper: generated alert receiver ID is not sufficiently unique ([~#16592~](https://github.com/sourcegraph/sourcegraph/issues/16592)) __0.50d__ 🐛
- [x] (🏁 14 days ago) monitoring: generate documentation for graphs without alerts ([~#15872~](https://github.com/sourcegraph/sourcegraph/issues/15872)) __3.00d__
- [x] (🏁 13 days ago) monitoring: development docs ([~#16938~](https://github.com/sourcegraph/sourcegraph/issues/16938)) __1.00d__
- [x] (🏁 10 days ago) sourcegraph/customer ([~#165~](https://github.com/sourcegraph/customer/issues/165)) __0.50d__ 👩
- [x] (🏁 10 days ago) sourcegraph/customer ([~#164~](https://github.com/sourcegraph/customer/issues/164)) __0.50d__ 👩
- [x] (🏁 10 days ago) sourcegraph/customer ([~#166~](https://github.com/sourcegraph/customer/issues/166)) __0.50d__ 👩
- [x] (🏁 today) ~monitoring: remove JSONNET, internal dashboards from Grafana image~ ([~#15875~](https://github.com/sourcegraph/sourcegraph/issues/15875)) __1.00d__

@davejrt: __1.00d__

Completed: __1.00d__
- [x] (🏁 19 days ago) go binary to create sudo token should be more generic ([~#15197~](https://github.com/sourcegraph/sourcegraph/issues/15197)) __0.50d__ 🧶
- [x] (🏁 15 days ago) ~sourcegraph/customer~ ([~#162~](https://github.com/sourcegraph/customer/issues/162)) 👩
- [x] (🏁 15 days ago) Document how to use vagrant for testing changing to CI ([~#16583~](https://github.com/sourcegraph/sourcegraph/issues/16583)) __0.50d__ 🧶

@daxmc99: __6.00d__

- [ ] ~Tracking issue: Dhall test components~ ([#16796](https://github.com/sourcegraph/sourcegraph/issues/16796)) __1.50d__
  - [ ] ~dhall: tests for grafana component~ ([#16802](https://github.com/sourcegraph/sourcegraph/issues/16802)) __0.50d__
  - [ ] ~dhall: tests for repo-updater component~ ([#16803](https://github.com/sourcegraph/sourcegraph/issues/16803)) __0.50d__
  - [ ] ~dhall: tests for postgres component~ ([#16804](https://github.com/sourcegraph/sourcegraph/issues/16804)) __0.50d__
- [ ] ~Tracking issue: Dhall stamp new commit to sync to for dot-com and k8s dhall~ ([#16785](https://github.com/sourcegraph/sourcegraph/issues/16785)) __1.50d__
  - [x] (🏁 today) ~dhall: re-sync grafana component~ ([~#16790~](https://github.com/sourcegraph/sourcegraph/issues/16790)) __0.50d__
  - [x] (🏁 today) ~dhall: re-sync repo-updater component~ ([~#16792~](https://github.com/sourcegraph/sourcegraph/issues/16792)) __0.50d__
  - [x] (🏁 today) ~dhall: re-sync postgres component~ ([~#16795~](https://github.com/sourcegraph/sourcegraph/issues/16795)) __0.50d__

Completed: __4.50d__
- [x] (🏁 7 days ago) dhall: implement postgres service in deploy-sourcegraph-dhall ([~#16262~](https://github.com/sourcegraph/sourcegraph/issues/16262)) __3.00d__
- [x] (🏁 today) ~dhall: re-sync grafana component~ ([~#16790~](https://github.com/sourcegraph/sourcegraph/issues/16790)) __0.50d__
- [x] (🏁 today) ~dhall: re-sync repo-updater component~ ([~#16792~](https://github.com/sourcegraph/sourcegraph/issues/16792)) __0.50d__
- [x] (🏁 today) ~dhall: re-sync postgres component~ ([~#16795~](https://github.com/sourcegraph/sourcegraph/issues/16795)) __0.50d__

@ggilmore: __2.00d__

- [ ] ~Tracking issue: Dhall test components~ ([#16796](https://github.com/sourcegraph/sourcegraph/issues/16796)) __1.00d__
  - [ ] ~dhall: tests for github-proxy component~ ([#16798](https://github.com/sourcegraph/sourcegraph/issues/16798)) __0.50d__
  - [ ] ~dhall: tests for symbols component~ ([#16799](https://github.com/sourcegraph/sourcegraph/issues/16799)) __0.50d__

Completed: __1.00d__
- [x] (🏁 today) dhall: re-sync github-proxy component ([~#16789~](https://github.com/sourcegraph/sourcegraph/issues/16789)) __0.50d__
- [x] (🏁 today) dhall: re-sync symbols component ([~#16793~](https://github.com/sourcegraph/sourcegraph/issues/16793)) __0.50d__

@pecigonzalo: __1.00d__

Completed: __1.00d__
- [x] (🏁 22 days ago) sourcegraph/deploy-sourcegraph-dot-com ([~#4025~](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/4025)) :shipit:
- [x] (🏁 22 days ago) sourcegraph/customer ([~#142~](https://github.com/sourcegraph/customer/issues/142)) 👩
- [x] (🏁 1 day ago) monitoring: implement workflow for config-mapping Grafana dashboards ([~#15873~](https://github.com/sourcegraph/sourcegraph/issues/15873)) __1.00d__
- [x] (🏁 today) Get approval on "RFC 263: Single-container deployments are for demos only" ([~#15484~](https://github.com/sourcegraph/sourcegraph/issues/15484))

@uwedeportivo: __3.00d__

- [ ] ~Tracking issue: Dhall test components~ ([#16796](https://github.com/sourcegraph/sourcegraph/issues/16796)) __1.50d__
  - [ ] ~dhall: tests for gitserver component~ ([#16797](https://github.com/sourcegraph/sourcegraph/issues/16797)) __0.50d__
  - [ ] ~dhall: tests for query-runner component~ ([#16800](https://github.com/sourcegraph/sourcegraph/issues/16800)) __0.50d__
  - [ ] ~dhall: tests for searcher component~ ([#16801](https://github.com/sourcegraph/sourcegraph/issues/16801)) __0.50d__

Completed: __1.50d__
- [x] (🏁 today) dhall: re-sync gitserver component ([~#16787~](https://github.com/sourcegraph/sourcegraph/issues/16787)) __0.50d__
- [x] (🏁 today) dhall: re-sync query-runner component ([~#16791~](https://github.com/sourcegraph/sourcegraph/issues/16791)) __0.50d__
- [x] (🏁 today) dhall: re-sync searcher component ([~#16794~](https://github.com/sourcegraph/sourcegraph/issues/16794)) __0.50d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by uwedeportivo** [comment]
last week

fair amount of work from oncall CE rotation, patch release, dot-com troubles. pairing sessions with teammates on Dhall components

next week

release captain, Dhall components polish and writing tests, Dhall catching up to dot-com + latest k8s Dhall code

**Comment by pecigonzalo** [comment]
**Last week**

Finished `query-runner` Dhall port and upgraded our demo.sourcegraph.com environment. I also worked on a number of outages we had last week (gerrit, sourcegraph.com, repo-updater, CI image missing).
I worked on the company meeting slide (thanks all for the help) and a draft to update our goals with the new timelines.

**This week**

This week I plan to focus on the Monitoring Redux tasks as well as merging the draft goals update.

**Team update**

As displayed in the body of this issue, we have the holidays coming up and most of the team is going to be out for the 2nd week of this iteration.

**Comment by daxmc99** [comment]
**Last week**
Addresses several on-call incidents
Paired with the team to implement Dhall features. 
Attempted Postgres 13 migration, encountered issues (see https://github.com/sourcegraph/sourcegraph/issues/16611 for info) 

**Next Week**
Get feedback on RFC 281 (https://docs.google.com/document/d/1_O5uxSVEHC6wjunizqZEsW3-Acsejo4eMt-G9X2z4cM/edit?usp=sharing)
Continue working on Dhall components
On-call rotations

**Comment by bobheadxi** [comment]
**Last week**

Generated dashboard docs (`Observable.Interpretation`), observability docs (how-to guides, background, cleanup). Worked on managed instance upgrades and automation.

**Next week**

A lot of minor QOL/debt items in https://github.com/sourcegraph/sourcegraph/issues/16673
