### ISSUE TITLE
Distribution: 2020.12.28 - Clever Frog

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#16673]
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@bobheadxi: __7.00d__

- [ ] ~monitoring: cadvisor recording rules seem broken~ ([#17069](https://github.com/sourcegraph/sourcegraph/issues/17069)) __3.00d__ 🐛
- [ ] ~monitoring: cadvisor panels don't work at all in docker-compose/pure-docker~ ([#17072](https://github.com/sourcegraph/sourcegraph/issues/17072)) 🐛

Completed: __4.00d__
- [x] (🏁 12 days ago) grafana: investigate upgrading to 7.3 ([~#15520~](https://github.com/sourcegraph/sourcegraph/issues/15520)) __0.50d__ 🧶
- [x] (🏁 12 days ago) release: automate bump of MINIMUM_UPGRADEABLE_VERSION ([~#16534~](https://github.com/sourcegraph/sourcegraph/issues/16534)) __0.50d__
- [x] (🏁 6 days ago) resources-report silently failing on sheet full ([~#17012~](https://github.com/sourcegraph/sourcegraph/issues/17012)) __0.50d__ 🐛
- [x] (🏁 6 days ago) monitoring: include a link to the exact panel that triggered an alert ([~#16073~](https://github.com/sourcegraph/sourcegraph/issues/16073)) __0.50d__ 🎩
- [x] (🏁 6 days ago) managed-instances: improve automation of upgrades ([~#16228~](https://github.com/sourcegraph/sourcegraph/issues/16228)) __1.00d__ 🎩
- [x] (🏁 2 days ago) monitoring: remove JSONNET, internal dashboards from Grafana image ([~#15875~](https://github.com/sourcegraph/sourcegraph/issues/15875)) __1.00d__

@davejrt

- [ ] ~create customer release tracking issues automatically~ ([#16216](https://github.com/sourcegraph/sourcegraph/issues/16216)) 🧶

@daxmc99: __3.00d__

- [ ] ~Upgrade to networking.k8s.io/v1 Ingress~ ([#16808](https://github.com/sourcegraph/sourcegraph/issues/16808)) 🧶
- [ ] Tracking issue: Dhall test components ([#16796](https://github.com/sourcegraph/sourcegraph/issues/16796)) __1.50d__
  - [ ] ~dhall: tests for grafana component~ ([#16802](https://github.com/sourcegraph/sourcegraph/issues/16802)) __0.50d__
  - [ ] ~dhall: tests for repo-updater component~ ([#16803](https://github.com/sourcegraph/sourcegraph/issues/16803)) __0.50d__
  - [ ] ~dhall: tests for postgres component~ ([#16804](https://github.com/sourcegraph/sourcegraph/issues/16804)) __0.50d__

Completed: __1.50d__
- [x] (🏁 2 days ago) Tracking issue: Dhall stamp new commit to sync to for dot-com and k8s dhall ([~#16785~](https://github.com/sourcegraph/sourcegraph/issues/16785)) __1.50d__

@ggilmore: __1.00d__

- [ ] Tracking issue: Dhall test components ([#16796](https://github.com/sourcegraph/sourcegraph/issues/16796)) __1.00d__
  - [ ] ~dhall: tests for github-proxy component~ ([#16798](https://github.com/sourcegraph/sourcegraph/issues/16798)) __0.50d__
  - [ ] dhall: tests for symbols component ([#16799](https://github.com/sourcegraph/sourcegraph/issues/16799)) __0.50d__

@pecigonzalo: __1.00d__

- [ ] ~Add handbook documentation for adding unplanned items to an iteration~ ([#16674](https://github.com/sourcegraph/sourcegraph/issues/16674))

Completed: __1.00d__
- [x] (🏁 2 days ago) monitoring: remove JSONNET, internal dashboards from Grafana image ([~#15875~](https://github.com/sourcegraph/sourcegraph/issues/15875)) __1.00d__

@uwedeportivo: __8.50d__

- [ ] Tracking issue: Dhall test components ([#16796](https://github.com/sourcegraph/sourcegraph/issues/16796)) __1.50d__
  - [ ] ~dhall: tests for gitserver component~ ([#16797](https://github.com/sourcegraph/sourcegraph/issues/16797)) __0.50d__
  - [ ] ~dhall: tests for query-runner component~ ([#16800](https://github.com/sourcegraph/sourcegraph/issues/16800)) __0.50d__
  - [ ] ~dhall: tests for searcher component~ ([#16801](https://github.com/sourcegraph/sourcegraph/issues/16801)) __0.50d__
- [ ] ~sourcegraph/customer~ ([#149](https://github.com/sourcegraph/customer/issues/149)) __2.00d__ 👩
- [ ] ~sourcegraph/customer~ ([#159](https://github.com/sourcegraph/customer/issues/159)) __1.00d__ 👩
- [ ] ~sourcegraph/customer~ ([#160](https://github.com/sourcegraph/customer/issues/160)) __1.00d__ 👩
- [ ] ~dhall: implement searcher service in deploy-sourcegraph-dhall~ ([#16267](https://github.com/sourcegraph/sourcegraph/issues/16267)) __3.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by uwedeportivo** [comment]
last week

fair amount of work from oncall CE rotation. pairing sessions with teammates on Dhall components

next week

release captain + Dhall components, Dhall catching up to dot-com + latest k8s Dhall code

**Comment by bobheadxi** [comment]
**last week**

I spent a good chunk of time investigating https://github.com/sourcegraph/sourcegraph/issues/17072 and https://github.com/sourcegraph/sourcegraph/issues/17069 and making PRs and changes to try and resolve them. Also wrapped up work on work on custom dashboards in Grafana (the configmapping stuff). I also took on a lot (too much 😢 ) unplanned work on things like resources-report, monitoring generator (reworked alert generation, strict greater/less than support, cleanup of unused multi-bound alerts support), postgres dashboard fixes (pending review https://github.com/sourcegraph/sourcegraph/pull/17131), general dashboards improvements (pending review https://github.com/sourcegraph/sourcegraph/pull/17034, disabling editing, alerts now link directly to relevant panels), some docs (tech stack overview, architecture overview, etc), and I paired with Dave to implement support for (almost) arbitrary dashboard panel customizations in the generator (pending review https://github.com/sourcegraph/sourcegraph/pull/17112)

**Comment by ggilmore** [comment]
Last week: 

I spent most of last week in planning meetings for the @sourcegraph/distribution team as a whole and a handful of Dhall ones. I spent some time with @daxmc99 pairing on Dhall testing tasks, while also working on https://github.com/sourcegraph/sourcegraph/issues/16799 + some shared testing utilities for the rest of the contributors to use. 

This week:

I will need to see how much time that I have available with our virtual offsite.
