### ISSUE TITLE
Move ops incident tracking to a `sourcegraph/incidents` repository

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#16675]
Moving ops incididents planning to a Github repository will make it easier to track the impact (both time and severity) of incidents + capture trends over time. We can leverage our existing project bots to surface the time impacts in our iteration planning issues. 

- [ ] Add template issue
- [ ] Private - so we can have sensitive info
- [ ] Add usage guides
- [ ] How do we map time for each team?
- [ ] How do we track effort?
- [ ] Options: Severity, Time, Px, all of those
- [ ] https://response.pagerduty.com/ 

To be discussed:

> for the ops incident doc, i remember we had the discussion of github issue vs google doc before. but i don’t remember pros/cons and i don’t know why we went with google docs. we had a similar discussion about where RFCs should live: google docs vs github issues. there the argument was that google docs has a much better commenting system with threads etc.

**Comment by ggilmore** [comment]
I have created a proof of concept here: https://github.com/sourcegraph/incidents, and have scheduled time to discuss this with a few good sounding boards on Thursday and Monday.

**Comment by ggilmore** [comment]
I created `sourcegraph/incidents` as proof of concept to try out filing our incidents in a GitHub issue tracker instead of our "Ops Incidents" Google Doc. I solicited feedback from some key engineers as they have relevant experience and have given me good feedback in the past. Here is a summary from my meetings:

- Vastly prefer using markdown to writing Google Docs
    - Heard anecdotes of people putting off writing ops incidents because they hate writing in Google Docs
    - Incident write-ups often include code of some kind (logs, bash commands, etc.). This is annoying to write directly in Google Docs.  Many people "work around" this by:
        1. Taking screenshots of code
        2. Writing in some other format and exporting to `.docx` (markdown + pandoc, org-mode, etc.)

        These are both horrifically kludgy. Writing directly in markdown is much better by comparison. 

- Like using separate Github issues for every incident
    - The current Google doc is just a "dumping ground" at the moment. Nobody reviews it after the initial write up. It's a lot easier to parse what happened with an incident if there is a **dedicated hub** (e.g. GitHub issue) for each incident.
    - Using GitHub issues allows you reference other issues / incidents in the incident writeup in a first-class manner
        - We can directly link to other related incidents by pasting a link to their corresponding GitHub issue
        - We can create companion issues in `sourcegraph/sourcegraph` that track the fixes for the incidents in `sourcegraph/incidents`
    - Using issues allows you to search/filter via the GitHub interface (examples: filter by date, use labels to "tag" issues, etc.)

- **They weren't too attached** to the proposed time-tracking / labeling mechanisms that I had in the proof of concept. We can introduce this tooling later on if we need it. Having a Github issue for each incident is already a win - and we can build on it if necessary.
    - Having a good template for people to follow is important

- Process changes are important too:
    - People aren't going to start reviewing incidents just because they're on Github. That process needs to made explicit.
    - **Suggestion:** Introduce a monthly incidents-review meeting. Interested engineers and engineering managers can attend. They'll review the incidents that occurred over the past month and do a retrospective on them. In this meeting:
        - Separate issues in sourcegraph/sourcegraph can be filed to track fixes for root causes
        - We can decide how we're going to prioritize work for those fixes
        - Any additional related incidents can be linked inside the issues
        - Any helpful categorization labels can be added to the issues

**Proposed next steps**

- Create issue template and detailed readme to outline the above process
    - Get sign-offs from the engineers that I talked to before on the above
- Create handbook entry to outline this new process
- Post to `#dev-announce` to start using `sourcegraph/incidents` and to stop using the google doc

**Comment by pecigonzalo** [comment]
This all sounds good. I gather we didnt get a reply from https://incident.io/, I would agree then to keep this simple and just move to the new tracker without investing too much in tooling until we get a chance to test that one out.

> Introduce a monthly incidents-review meeting. Interested engineers and engineering managers can attend. They'll review the incidents that occurred over the past month and do a retrospective on them

Its the responsibility of the engineer working on the incident to organize and have a post-mortem beyond just the document. This is already outlined in https://about.sourcegraph.com/handbook/engineering/incidents#post-mortem and it's our collective job to keep us all accountable for doing it.
Regardless, I like the idea of an additional general periodic review like the one you proposed.
