### ISSUE TITLE
monitoring: panel API redux tracking issue

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#16697]
### Plan

@pecigonzalo I believe this also covers a note you added:

> Enable the full grafana SDK functionality for panel configurations
>
> We would like to be able to fully customize panels to adapt to the type of information being display.

IMO we should instead enable better iteration on the useful defaults we provide in the generator (discussion: https://github.com/sourcegraph/about/pull/2000#discussion_r523027773) instead of _full_ customization of panels (we will have #15873 for that instead)

That said, we should:

* Enable some more options on the current API where appropriate
* For more drastic departures from our current panels:
   * Identify other types of data that aren't line-graph-time-series that we want to support panels for (the recent Cloud dashboards are probably a useful reference for what some teams might want)
   * Design & implement an API for opting in to different types of panels 

How panels are currently generated:

* API: https://github.com/sourcegraph/sourcegraph/tree/main/monitoring/monitoring#type-observablepaneloptions
* Code: https://k8s.sgdev.org/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Emonitoring+for+_%2C+row+:%3D+range+group.Rows+%7B+:%5B_%5D+%7D&patternType=structural

### Tracked issues

@bobheadxi: __1.00d__

Completed: __1.00d__
- [x] (🏁 26 days ago) monitoring: Define configuration types for new monitoring API ([~#17060~](https://github.com/sourcegraph/sourcegraph/issues/17060))
- [x] (🏁 21 days ago) monitoring: Implement existing functionality in the new API ([~#17061~](https://github.com/sourcegraph/sourcegraph/issues/17061)) __1.00d__

@davejrt: __1.00d__

Completed: __1.00d__
- [x] (🏁 26 days ago) monitoring: Define configuration types for new monitoring API ([~#17060~](https://github.com/sourcegraph/sourcegraph/issues/17060))
- [x] (🏁 21 days ago) monitoring: Implement existing functionality in the new API ([~#17061~](https://github.com/sourcegraph/sourcegraph/issues/17061)) __1.00d__
- [x] (🏁 today) monitoring: Demo new api features ([~#17062~](https://github.com/sourcegraph/sourcegraph/issues/17062))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by bobheadxi** [comment]
@davejrt assigning you for now since this is a bit more involved and will require some Go!

**Comment by bobheadxi** [comment]
Sketch:

```go
PanelOptions:      monitoring.PanelOptions(TimeSeries(), Unit(monitoring.Milliseconds), func(p *sdk.Panel) {	
							p.asdfasdf = "asdfasdf"
						}),
```

**Comment by davejrt** [comment]
I'm working through a lot of this in my head at the moment, without making a lot of genuine progress due to a lack of Go fundamentals I think. 

What might be helpful is to maybe break this down, to add one or a smaller group of features first. I feel as though perhaps my lack of understanding here is a bit like me opening pandora's box as I don't have all the context or the knowledge to know where to begin.

Ideally this is something I'd like to pair on with you at @bobheadxi because I feel you have the most vision into the future here from a distribution perspective. 

For example, with regard to the example above about constructing the panel...a good first step in my head would be to convert what we currently have to do this. Then go about adding in addition options but I'm afraid even that feels like a monumental task at this point.

**Comment by bobheadxi** [comment]
> a good first step in my head would be to convert what we currently have to do this

I think this would be a great start! Would be good to handle any potential migrations issues as well in that PR (e.g. if code needs to be changed to access the new API)

I think we can break this down in 3 steps:

* [ ] Identify new configurations we want to support by looking at the Cloud dashboards, such as ["Git Server - Cloud"](https://sourcegraph.com/-/debug/grafana/d/QvLV8J2Gk/git-server-cloud?orgId=1), or maybe check in with the Cloud team to see if there's anything else we should look at. This can be a simple list. Determine roughly what kind of changes we need to be able offer, these will be requirements of sorts.
   * For example, the [`*sdk.Panel` type](https://sourcegraph.com/github.com/grafana-tools/sdk/-/blob/panel.go#L44:2) offers everything, but at a glance it seems we _don't_ need to offer `CommonPanel` and even some of the other panel types like `DashlistPanel` and `PluginlistPanel` panel. Maybe the argument to our `Options` function type could offer a custom struct with just the panels we want to support (maybe _just_ `GraphPanel` to start with)
   * I think a good one from that GitServer dashboard is more options about positioning of tooltips, I think that can be accomplished with just `GraphPanel`
* [ ] Implement the _existing_ functionality in terms of a new API that would accommodate the requirements in the previous step (without actually implementing anything new), make migrations as required
* [ ] Implement some new options to demo the API and give a bit of a starting point for customizations that teams can leverage / build off of

If those steps sound good to you, we can break this out into a few issues and look at them one by one, and pair as needed!

**Comment by bobheadxi** [comment]
This is now a tracking issue (finally), closed https://github.com/sourcegraph/sourcegraph/issues/17059 in favour of this FYI @davejrt

**Comment by pecigonzalo** [comment]
@davejrt @bobheadxi remember to add the linked issues here to the project https://github.com/orgs/sourcegraph/projects/112
