### ISSUE TITLE
Campaigns Sprint 7 Tracking issue

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#16732]
### Availability

9 work days (over three weeks). If you have planned unavailability this iteration (e.g., vacation), you can note that here.

* @LawnGnome: 1d (probably December 28)
* @mrnugget: entire sprint :santa: :gift: 

### Tracked issues

@unassigned: __1.50d__

Completed: __1.50d__
- [x] (🏁 21 days ago) Document a compatibility matrix of campaigns ([~#16034~](https://github.com/sourcegraph/sourcegraph/issues/16034)) __1.50d__

@LawnGnome

Completed
- [x] (🏁 18 days ago) doc: add note about the interaction of SSH and credentials ([~#16889~](https://github.com/sourcegraph/sourcegraph/pull/16889)) :shipit:
- [x] (🏁 1 day ago) ci: migrate all CI to GitHub Actions ([~#415~](https://github.com/sourcegraph/src-cli/pull/415)) :shipit:

@eseliger: __1.00d__

Completed: __1.00d__
- [x] (🏁 20 days ago) Fix imported changesets being counted twice in metrics ([~#16848~](https://github.com/sourcegraph/sourcegraph/pull/16848)) :shipit:
- [x] (🏁 20 days ago) Merge unsynced and publication state together ([~#16860~](https://github.com/sourcegraph/sourcegraph/pull/16860)) :shipit:
- [x] (🏁 19 days ago) Display changesets in "failed" state differently than "errored" ([~#16009~](https://github.com/sourcegraph/sourcegraph/issues/16009); PRs: ~[#16863](https://github.com/sourcegraph/sourcegraph/pull/16863)~) __0.50d__
- [x] (🏁 18 days ago) campaigns: don't update diff stat until after changeset reconciliation is complete ([~#16196~](https://github.com/sourcegraph/sourcegraph/issues/16196); PRs: ~[#16914](https://github.com/sourcegraph/sourcegraph/pull/16914)~) __0.50d__ 🐛
- [x] (🏁 18 days ago) Don't enqueue unpublished changeset for closing ([~#16910~](https://github.com/sourcegraph/sourcegraph/pull/16910)) :shipit:🐛

@rrhyne: __2.00d__

Completed: __2.00d__
- [x] (🏁 21 days ago) Campaigns text search design  ([~#15889~](https://github.com/sourcegraph/sourcegraph/issues/15889)) __0.50d__
- [x] (🏁 19 days ago) Changeset spec text search design ([~#16782~](https://github.com/sourcegraph/sourcegraph/issues/16782)) __0.50d__
- [x] (🏁 8 days ago) Create campaigns demo content index ([~#16783~](https://github.com/sourcegraph/sourcegraph/issues/16783)) __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by LawnGnome** [comment]
#### Weekly update: 2020-12-08 to 2020-12-14

Last week, I finished up changeset text search, and then implemented the licensing checks for 3.23. The licensing checks ended up requiring more time than expected: we didn't have as good a handle on the behaviour for unlicensed deployments as we thought we did, and the actual requirements around licensing were also hard to pin down.

Beyond that, I spent a day or two in total pitching in on support, prototyped ideas for improving our progress reporting and command structure in `src`, and attended a couple of customer calls.

This week, I'm picking changeset spec text search and filtering back up — these were pushed out of the last sprint by a combination of the licensing work expanding and the update API blocking the changeset spec text search, and are my top priorities for sprint 8. In general, I'm unsure how my next two or three weeks will go: I have plenty of roadmap work planned and available, but with other engineers having increasingly limited availability as we run down towards Christmas, I may be more prone to interruptions than usual.

**Comment by LawnGnome** [comment]
#### Not so weekly update: 2021-01-05 edition

Next week, I intend to focus primarily on our changeset UI: adding text search and filtering to the update page, and finishing out the filtering design for the campaign page.
