### ISSUE TITLE
Tracking issue: Dhall stamp new commit to sync to for dot-com and k8s dhall

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#16785]
### Plan

agree on a fresh commit for both dot-com and k8s-dhall and stamp them into README: all issues related to this catchup will be tracked here

### Tracked issues

@daxmc99: __1.50d__

Completed: __1.50d__
- [x] (🏁 2 days ago) dhall: re-sync grafana component ([~#16790~](https://github.com/sourcegraph/sourcegraph/issues/16790)) __0.50d__
- [x] (🏁 2 days ago) dhall: re-sync repo-updater component ([~#16792~](https://github.com/sourcegraph/sourcegraph/issues/16792)) __0.50d__
- [x] (🏁 2 days ago) dhall: re-sync postgres component ([~#16795~](https://github.com/sourcegraph/sourcegraph/issues/16795)) __0.50d__

**Comment by ggilmore** [comment]
All subtasks are closed already
