### ISSUE TITLE
Tracking issue: Dhall test components

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#16796]
@daxmc99: __2.00d__

Completed: __2.00d__
- [x] (🏁 13 days ago) dhall: tests for postgres component ([~#16804~](https://github.com/sourcegraph/sourcegraph/issues/16804)) __0.50d__
- [x] (🏁 13 days ago) dhall: tests for grafana component ([~#16802~](https://github.com/sourcegraph/sourcegraph/issues/16802)) __0.50d__
- [x] (🏁 13 days ago) dhall: tests for repo-updater component ([~#16803~](https://github.com/sourcegraph/sourcegraph/issues/16803)) __0.50d__
- [x] (🏁 today) dhall: tests for gitserver component ([~#16797~](https://github.com/sourcegraph/sourcegraph/issues/16797)) __0.50d__

@ggilmore: __1.00d__

Completed: __1.00d__
- [x] (🏁 15 days ago) dhall: tests for github-proxy component ([~#16798~](https://github.com/sourcegraph/sourcegraph/issues/16798)) __0.50d__
- [x] (🏁 3 days ago) dhall: tests for symbols component ([~#16799~](https://github.com/sourcegraph/sourcegraph/issues/16799)) __0.50d__

@uwedeportivo: __1.00d__

Completed: __1.00d__
- [x] (🏁 3 days ago) dhall: tests for query-runner component ([~#16800~](https://github.com/sourcegraph/sourcegraph/issues/16800)) __0.50d__
- [x] (🏁 3 days ago) dhall: tests for searcher component ([~#16801~](https://github.com/sourcegraph/sourcegraph/issues/16801)) __0.50d__

**Comment by pecigonzalo** [comment]
All tasks in this tracking issue are done.
