### ISSUE TITLE
WIP: Security 3.24 Tracking issue Sprint 1

### ISSUE THREAD

**Issue by ElizabethStirling** [sourcegraph/sourcegraph#16961]
### Plan
Goals:
1. Continue to onboard André #16582 
1. Monitor our centralized logging infrastructure, and ensure its continued stability #15444, #16962, [Team Goal #1](https://about.sourcegraph.com/handbook/engineering/security/goals#visibility-into-sourcegraph-cloud-s-attack-surface)
1. Resolve known security issues [Team Goal #2](https://about.sourcegraph.com/handbook/engineering/security/goals#confidence-in-our-security-model)

@chayim please review these goals and update as relevant

### Availability
Sprint is from 2020-12-20 to 2021-01-02
Duration is 10 days

Chayim: 10 days - no vacation
Elizabeth: 2 days  - OOO starting 2020-12-23
André: 6 days - OOO 2020-12[24, 25, 31], 2020-01-01

### Tracked issues

@unassigned: __1.00d__

- [ ] Team Security Tracking: Security Event Logging ([#15444](https://github.com/sourcegraph/sourcegraph/issues/15444)) __1.00d__
  - [x] (🏁 12 days ago) Gather kube logs for centralized logging ([~#15449~](https://github.com/sourcegraph/sourcegraph/issues/15449)) __1.00d__

Completed: __1.00d__
- [x] (🏁 12 days ago) Gather kube logs for centralized logging ([~#15449~](https://github.com/sourcegraph/sourcegraph/issues/15449)) __1.00d__

@ElizabethStirling: __4.00d__

- [ ] Team Security Tracking: Security Event Logging ([#15444](https://github.com/sourcegraph/sourcegraph/issues/15444)) __4.00d__
  - [x] (🏁 12 days ago) Gather docker logs into centralized logging ([~#14090~](https://github.com/sourcegraph/sourcegraph/issues/14090)) __4.00d__
  - [x] (🏁 13 days ago) Create pubsub for dogfood stackdriver and connect to Security pubsubbeat instances ([~#16492~](https://github.com/sourcegraph/sourcegraph/issues/16492))

Completed: __4.00d__
- [x] (🏁 13 days ago) Create pubsub for dogfood stackdriver and connect to Security pubsubbeat instances ([~#16492~](https://github.com/sourcegraph/sourcegraph/issues/16492))
- [x] (🏁 12 days ago) Gather docker logs into centralized logging ([~#14090~](https://github.com/sourcegraph/sourcegraph/issues/14090)) __4.00d__

@chayim: __1.50d__

- [ ] Team Security Tracking: Security Event Logging ([#15444](https://github.com/sourcegraph/sourcegraph/issues/15444)) __1.00d__
  - [x] (🏁 5 days ago) Monitor disk allocation for elastic cloud, define retention policy ([~#16962~](https://github.com/sourcegraph/sourcegraph/issues/16962)) __1.00d__

Completed: __1.50d__
- [x] (🏁 12 days ago) Elastic Resize Causes 403s ([~#16964~](https://github.com/sourcegraph/sourcegraph/issues/16964)) __0.50d__
- [x] (🏁 5 days ago) Monitor disk allocation for elastic cloud, define retention policy ([~#16962~](https://github.com/sourcegraph/sourcegraph/issues/16962)) __1.00d__

### Security issues repo
@andreeleuterio
- [ ] Enforce SSL for dogfood bitbucket SSL connections ([security#123](https://github.com/sourcegraph/security-issues/issues/123))
- [ ] Stored XSS via javascript scheme through Quick links section ([security#94](https://github.com/sourcegraph/security-issues/issues/94))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by ElizabethStirling** [comment]
**This Week**
This was a super short week for me, but I was able to get pubsubbeats up and running on our security k8s logging cluster #16492! I made a few stability configuration changes, but otherwise everything has been running smoothly.

**Next Week**
I'm on vacation! But once I get back, I want to see the results of #16962, and whether or not it indicates we need to do #16963 prior to cloud GA. If not, I'll do additional work to tie up loose ends with regards to GCP centralized logging #15444, and clear up issues that are no longer relevant.

**Comment by andreeleuterio** [comment]
**This Week**
Short week for me; continued meeting folks and am now focused on https://github.com/sourcegraph/security-issues/issues/94. I was able to reproduce the issue and started looking into where to include validation.

**Next Week**
Also a short week for me. I'd like to wrap up https://github.com/sourcegraph/security-issues/issues/94 issue but having no one around might make it more difficult to advance on it.

**Comment by sushiwushi** [comment]
**This Week**
This week, I ran a path traversal fuzzing test against Sourcegraph docker instance using Burp Suite intruder during my penetration testing process in the application which can be found in [security issue #129](https://github.com/sourcegraph/security-issues/issues/130).

**Next Week**
I will continue run fuzzing tests against the application to discover hidden vulnerabilities so it can be patched as soon as possible.

**Comment by ElizabethStirling** [comment]
Closing in favor of #17031
