### ISSUE TITLE
Cloud 2021-01-06 Tracking issue

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#17027]
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@unassigned

Completed
- [x] (🏁 5 days ago) Loading/pending state for repository syncs after adding repos. ([~#17107~](https://github.com/sourcegraph/sourcegraph/issues/17107))

@ryanslade: __5.50d__

Completed: __5.50d__
- [x] (🏁 7 days ago) gitserver: Fix typo ([~#17041~](https://github.com/sourcegraph/sourcegraph/pull/17041)) :shipit:
- [x] (🏁 6 days ago) gitserver: Remove deprecated code ([~#17037~](https://github.com/sourcegraph/sourcegraph/pull/17037)) :shipit:
- [x] (🏁 5 days ago) External service syncing holds locks for too long ([~#16070~](https://github.com/sourcegraph/sourcegraph/issues/16070); PRs: ~[#17025](https://github.com/sourcegraph/sourcegraph/pull/17025)~) __1.00d__ 🐛
- [x] (🏁 4 days ago) Limit non-admin user to a single external service per code host ([~#16885~](https://github.com/sourcegraph/sourcegraph/issues/16885); PRs: ~[#17104](https://github.com/sourcegraph/sourcegraph/pull/17104)~) __1.00d__
- [x] (🏁 2 days ago) Add number of synced repos to externalServices GraphQL resolver  ([~#16729~](https://github.com/sourcegraph/sourcegraph/issues/16729); PRs: ~[#17127](https://github.com/sourcegraph/sourcegraph/pull/17127)~) __1.00d__
- [x] (🏁 1 day ago) basestore: Use Exec and add ExecResult ([~#17160~](https://github.com/sourcegraph/sourcegraph/pull/17160)) :shipit:
- [x] (🏁 1 day ago) Ensure that indexed repos on Sourcegraph.com are cloned ([~#16007~](https://github.com/sourcegraph/sourcegraph/issues/16007); PRs: ~[#17095](https://github.com/sourcegraph/sourcegraph/pull/17095)~) __1.00d__ 🐛
- [x] (🏁 today) Add pagination when listing default repos ([~#17161~](https://github.com/sourcegraph/sourcegraph/issues/17161); PRs: ~[#17193](https://github.com/sourcegraph/sourcegraph/pull/17193)~) __1.00d__ 🧶
- [x] (🏁 today) repo-updater: Fix nil connection panic ([~#17199~](https://github.com/sourcegraph/sourcegraph/pull/17199)) :shipit:
- [x] (🏁 today) repo-updater: Handle GitHub account suspension ([~#17159~](https://github.com/sourcegraph/sourcegraph/issues/17159); PRs: ~[#17195](https://github.com/sourcegraph/sourcegraph/pull/17195)~) __0.50d__

@unknwon: __2.00d__

Completed: __2.00d__
- [x] (🏁 6 days ago) Spike: Prototype account merging between GitLab and GitHub ([~#15332~](https://github.com/sourcegraph/sourcegraph/issues/15332)) __1.00d__ 🕵️
- [x] (🏁 6 days ago) Add critical alert when Permissions sync error rate is non-zero ([~#16698~](https://github.com/sourcegraph/sourcegraph/issues/16698); PRs: ~[#17075](https://github.com/sourcegraph/sourcegraph/pull/17075)~) __0.50d__
- [x] (🏁 3 days ago) repo-updater: always wrap context.Background with internal actor ([~#17149~](https://github.com/sourcegraph/sourcegraph/pull/17149)) :shipit:
- [x] (🏁 3 days ago) access_token: fix possible panic upon deletion ([~#17150~](https://github.com/sourcegraph/sourcegraph/pull/17150)) :shipit:
- [x] (🏁 1 day ago) authz: PermsSyncer should recognize account suspension ([~#16638~](https://github.com/sourcegraph/sourcegraph/issues/16638); PRs: ~[#17156](https://github.com/sourcegraph/sourcegraph/pull/17156)~) __0.50d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by unknwon** [comment]
My items are settled for this cycle, mostly clean up left-overs. Plan to fully tackle [RFC 277](https://docs.google.com/document/d/1r6ngZNOENVikcEzMU4v8b3TNT2TQydzILVDRqmJuzqY/edit?ts=5fd214ee#) in the next cycle.

**Comment by unknwon** [comment]
### Last week

- Wrapping up from the winter break and handle some left-over items.

### This week

I'm focusing on breaking up Overhaul aggregated errors sent to Sentry to smaller action items, including: use separate Sentry projects for web app and backend, go over each of reported issue see if they're really worth reporting.
