### ISSUE TITLE
C.C. Onboarding plan

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#17026]
### Week 1-2

Go through [General Onboarding](https://about.sourcegraph.com/handbook/people-ops/onboarding#for-all-new-teammates) and [Engineering Onboarding](https://about.sourcegraph.com/handbook/engineering/onboarding#engineering-onboarding).

- [x] Set up an architecture deep dive session with @tsenart 

### Week 2 - 3

Get started with some smaller tasks:

- [x] https://github.com/sourcegraph/sourcegraph/issues/15576 commit search on non-existent ref runs on HEAD and alerts
- [x] https://github.com/sourcegraph/sourcegraph/issues/16899 Support merging different commit data for type:diff and type:commit
- [x] https://github.com/sourcegraph/sourcegraph/issues/16723 Code monitors page info is wrong at end of list
- [ ] https://github.com/sourcegraph/sourcegraph/issues/13477 Symbol search returns results for 1 revision only

**Comment by lguychard** [comment]
I think this can be closed now :)
