### ISSUE TITLE
Code Intelligence Sprint 3 Tracking issue

### ISSUE THREAD

**Issue by scalabilitysolved** [sourcegraph/sourcegraph#17028]
### Plan

This sprint covers 2021/01/04 to 2021/01/15

### Availability

Owen: 8d (4x10 work week)
Maria: 8d (OOO Jan 14/15)
Eric: 10d
Noah: 10d
Garo: 5d 
Olaf: 5d

### Tracked issues

@Strum355: __4.00d__

Completed: __4.00d__
- [x] (🏁 13 days ago) apiworker: Set -e to trace docker command script execution ([~#17042~](https://github.com/sourcegraph/sourcegraph/pull/17042)) :shipit:
- [x] (🏁 6 days ago) autoindex: trigger autoindex job from UI ([~#17101~](https://github.com/sourcegraph/sourcegraph/pull/17101)) :shipit:
- [x] (🏁 3 days ago) codeintel: Add index configuration for 5 C++ repositories on Cloud ([~#16520~](https://github.com/sourcegraph/sourcegraph/issues/16520)) __4.00d__

@efritz: __5.00d__

- [ ] ~executor: Verify checksum of resources before execution~ ([#15937](https://github.com/sourcegraph/sourcegraph/issues/15937)) __0.50d__

Completed: __4.50d__
- [x] (🏁 12 days ago) executor: Return exit code and nil-error on command failure ([~#17049~](https://github.com/sourcegraph/sourcegraph/pull/17049)) :shipit:
- [x] (🏁 12 days ago) executor: Temporarily increase observability with log messages ([~#17052~](https://github.com/sourcegraph/sourcegraph/pull/17052)) :shipit:
- [x] (🏁 12 days ago) executor: Temporarily increase observability with log messages ([~#17056~](https://github.com/sourcegraph/sourcegraph/pull/17056)) :shipit:
- [x] (🏁 12 days ago) executor: Write scripts into workspace instead of another temporary directory ([~#17058~](https://github.com/sourcegraph/sourcegraph/pull/17058)) :shipit:
- [x] (🏁 6 days ago) Upload of large LSIF dump fails ([~#16242~](https://github.com/sourcegraph/sourcegraph/issues/16242); PRs: ~[#17175](https://github.com/sourcegraph/sourcegraph/pull/17175)~)
- [x] (🏁 6 days ago) autoindexing: Limit number of jobs automatically enqueued per commit ([~#17182~](https://github.com/sourcegraph/sourcegraph/pull/17182)) :shipit:
- [x] (🏁 4 days ago) codeintel: Add a feature flag for auto indexing ([~#17209~](https://github.com/sourcegraph/sourcegraph/pull/17209)) :shipit:
- [x] (🏁 4 days ago) Show auto-indexing in the UI based on feature flag ([~#17204~](https://github.com/sourcegraph/sourcegraph/issues/17204))
- [x] (🏁 3 days ago) debt: Improve schema.md generation ([~#17253~](https://github.com/sourcegraph/sourcegraph/pull/17253)) :shipit:
- [x] (🏁 3 days ago) codeintel: Add index configuration for 5 C++ repositories on Cloud ([~#16520~](https://github.com/sourcegraph/sourcegraph/issues/16520)) __4.00d__
- [x] (🏁 2 days ago) codeintel: Add source to all queries in db/lsif stores ([~#17334~](https://github.com/sourcegraph/sourcegraph/pull/17334)) :shipit:
- [x] (🏁 2 days ago) codeintel: git diffing fails graphql requests related to force-pushed commits ([~#12588~](https://github.com/sourcegraph/sourcegraph/issues/12588); PRs: ~[#17256](https://github.com/sourcegraph/sourcegraph/pull/17256)~) __0.50d__ 🐛
- [x] (🏁 2 days ago) codeintel: Remove upload files for orphaned commits ([~#12589~](https://github.com/sourcegraph/sourcegraph/issues/12589)) 🧶

@gbrik

Completed
- [x] (🏁 3 days ago) make the default value of codeIntel.lsif true ([~#554~](https://github.com/sourcegraph/code-intel-extensions/pull/554)) :shipit:
- [x] (🏁 3 days ago) remove references to setting 'codeIntel.lsif' to true from docs ([~#17292~](https://github.com/sourcegraph/sourcegraph/pull/17292)) :shipit:

@scalabilitysolved

Completed
- [x] (🏁 6 days ago) Upload of large LSIF dump fails ([~#16242~](https://github.com/sourcegraph/sourcegraph/issues/16242); PRs: ~[#17175](https://github.com/sourcegraph/sourcegraph/pull/17175)~)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by Strum355** [comment]
Completed/In Review:
- Trigger auto index job from UI
- Echo commands executed from the executor shell script
- Created autoindex configs for dolphin-emu/flatbuffers/linux kernel

Next Week:
- Olaf onboarding :tada: 
- Some docs work for Olaf
- <todo>

**Comment by macraig** [comment]
Last week:
- Post holiday catch up
- Code intel retro/planning
- Follow up on customers (Uber, Workiva and Dropbox)
- Looked into roslyn C++ indexer
- Code intel update slides for company meeting

Next Week:
- Code intel update presentation
- Call with customer indexing generated code
- Language landscape research

**Comment by efritz** [comment]
Last week:

- Occupied some space without a working brain
- Added executor infrastructure to dogfood instance to @andreeleuterio can do exploratory surgery on it.

Next week:

- Help onboard Olaf (architecture presentations)
- Working with Noah on the auto-indexer

**Comment by efritz** [comment]
Continuing the grind in https://github.com/sourcegraph/sourcegraph/issues/17371.
