### ISSUE TITLE
Campaigns Sprint 8 Tracking issue

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#17030]
### Tracked issues

@unassigned

Completed
- [x] (🏁 7 days ago) src-cli: Unix user ID mismatch can cause permission errors ([~#17172~](https://github.com/sourcegraph/sourcegraph/issues/17172))

@LawnGnome: __5.00d__

- [ ] campaigns: spike initial e2e cli testing ([#15884](https://github.com/sourcegraph/sourcegraph/issues/15884)) __1.00d__ 🕵️

Completed: __4.00d__
- [x] (🏁 12 days ago) cli: add a mode to avoid bind mounts ([~#16809~](https://github.com/sourcegraph/sourcegraph/issues/16809); PRs: ~[#412](https://github.com/sourcegraph/src-cli/pull/412)~, ~[#16979](https://github.com/sourcegraph/sourcegraph/pull/16979)~) __2.00d__
- [x] (🏁 4 days ago) Changeset spec text search ([~#15829~](https://github.com/sourcegraph/sourcegraph/issues/15829)) __2.00d__

@eseliger: __0.50d__

Completed: __0.50d__
- [x] (🏁 8 days ago) Don't display publish notice on empty campaigns ([~#17169~](https://github.com/sourcegraph/sourcegraph/pull/17169)) :shipit:🐛
- [x] (🏁 8 days ago) Introduce detach operation to reconciler ([~#17165~](https://github.com/sourcegraph/sourcegraph/pull/17165)) :shipit:
- [x] (🏁 7 days ago) Add stats resolver for preview API ([~#17168~](https://github.com/sourcegraph/sourcegraph/pull/17168)) :shipit:
- [x] (🏁 6 days ago) Test campaigns against GHE 2.22 instance ([~#17205~](https://github.com/sourcegraph/sourcegraph/issues/17205)) __0.50d__
- [x] (🏁 6 days ago) Introduce current state column ([~#17215~](https://github.com/sourcegraph/sourcegraph/pull/17215)) :shipit:
- [x] (🏁 5 days ago) Show all reconciler operations in actions column ([~#17248~](https://github.com/sourcegraph/sourcegraph/pull/17248)) :shipit:
- [x] (🏁 5 days ago) Implement base ref changed indicator in preview UI ([~#17287~](https://github.com/sourcegraph/sourcegraph/pull/17287)) :shipit:
- [x] (🏁 5 days ago) Recheck changeset syncer preconditions ([~#17280~](https://github.com/sourcegraph/sourcegraph/pull/17280)) :shipit:
- [x] (🏁 5 days ago) Adopt proper changeset backdrop highlight ([~#17285~](https://github.com/sourcegraph/sourcegraph/pull/17285)) :shipit:
- [x] (🏁 4 days ago) Campaign preview stats bar ([~#17213~](https://github.com/sourcegraph/sourcegraph/pull/17213)) :shipit:
- [x] (🏁 4 days ago) Respect search terms for totalCount computation in preview list ([~#17328~](https://github.com/sourcegraph/sourcegraph/pull/17328)) :shipit:🐛

@mrnugget: __5.50d__

Completed: __5.50d__
- [x] (🏁 7 days ago) ~Campaign Spec Sketches: monorepo & dynamic changesetTemplate~ ([~#17135~](https://github.com/sourcegraph/sourcegraph/pull/17135)) :shipit:🕵️
- [x] (🏁 2 days ago) Explore options to allow better customization of changesets in campaign spec ([~#17040~](https://github.com/sourcegraph/sourcegraph/issues/17040)) __5.00d__ 🕵️
- [x] (🏁 1 day ago) Detect whether gitserver would push to ssh:// URL and throw proper error message ([~#17050~](https://github.com/sourcegraph/sourcegraph/issues/17050)) __0.50d__ 🐛

@rrhyne: __1.00d__

Completed: __1.00d__
- [x] (🏁 today) Campaign update preview design ([~#15888~](https://github.com/sourcegraph/sourcegraph/issues/15888)) __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by mrnugget** [comment]
### Weekly update

Back from vacation on Monday, new sprint starting today and my big thing for this sprint and that I also want to actively tackle this week: explore options to change our campaign spec schema so it allows for better support of mono repos, per-repository customization of changeset templates, and further expansion to include support for tickets. [This](https://github.com/sourcegraph/sourcegraph/issues/17040) is a spike and my only goal is to come up with a draft for what such an extended campaign spec could look like.

Of note: I'm going to be out tomorrow, due to it being a Bavarian holiday.
