### ISSUE TITLE
monitoring: new monitoring API Tracking issue

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#17059]
### Plan

Add functionality to display more types of data in our Grafana dashboards.

### Tracked issues

@bobheadxi

- [ ] monitoring: Demo new api features ([#17062](https://github.com/sourcegraph/sourcegraph/issues/17062))
- [ ] monitoring: Implement existing functionality in the new API ([#17061](https://github.com/sourcegraph/sourcegraph/issues/17061))
- [ ] monitoring: Define configuration types for new monitoring API ([#17060](https://github.com/sourcegraph/sourcegraph/issues/17060))

@davejrt

- [ ] monitoring: Demo new api features ([#17062](https://github.com/sourcegraph/sourcegraph/issues/17062))
- [ ] monitoring: Implement existing functionality in the new API ([#17061](https://github.com/sourcegraph/sourcegraph/issues/17061))
- [ ] monitoring: Define configuration types for new monitoring API ([#17060](https://github.com/sourcegraph/sourcegraph/issues/17060))
- [ ] monitoring: new monitoring API Tracking issue ([#17059](https://github.com/sourcegraph/sourcegraph/issues/17059))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by bobheadxi** [comment]
Convenience link: this work stems from https://github.com/sourcegraph/sourcegraph/issues/16697

**Comment by bobheadxi** [comment]
Trying to convert https://github.com/sourcegraph/sourcegraph/issues/16697 into a tracking issue instead 😢 difficult
