### ISSUE TITLE
Distribution: 2021.01.11 - Blissful Dog

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#17137]
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@bobheadxi: __6.50d__

- [ ] monitoring: panel API redux tracking issue ([#16697](https://github.com/sourcegraph/sourcegraph/issues/16697)) __1.00d__
  - [x] (🏁 13 days ago) monitoring: Implement existing functionality in the new API ([~#17061~](https://github.com/sourcegraph/sourcegraph/issues/17061)) __1.00d__

Completed: __6.50d__
- [x] (🏁 14 days ago) monitoring(postgres): fix panels, adjust transaction alerts ([~#17131~](https://github.com/sourcegraph/sourcegraph/pull/17131)) :shipit:
- [x] (🏁 14 days ago) prometheus: alert dashboard links with fixed timestamps ([~#17034~](https://github.com/sourcegraph/sourcegraph/pull/17034)) :shipit:
- [x] (🏁 13 days ago) monitoring: export Sourcegraph version as metric, render annotation in Grafana on version changes ([~#17070~](https://github.com/sourcegraph/sourcegraph/issues/17070)) __1.00d__ 🎩
- [x] (🏁 13 days ago) monitoring: Implement existing functionality in the new API ([~#17061~](https://github.com/sourcegraph/sourcegraph/issues/17061)) __1.00d__
- [x] (🏁 12 days ago) monitoring: review changes in cadvisor metrics (if any) from migration to containerd ([~#17158~](https://github.com/sourcegraph/sourcegraph/issues/17158)) __0.50d__
- [x] (🏁 11 days ago) monitoring: cadvisor panels don't work at all in docker-compose/pure-docker ([~#17072~](https://github.com/sourcegraph/sourcegraph/issues/17072)) 🐛
- [x] (🏁 8 days ago) monitoring: cadvisor recording rules seem broken ([~#17069~](https://github.com/sourcegraph/sourcegraph/issues/17069)) __3.00d__ 🐛
- [x] (🏁 5 days ago) releases: adjust steps to have everything happen in 1 day ([~#17364~](https://github.com/sourcegraph/sourcegraph/issues/17364)) __1.00d__
- [x] (🏁 4 days ago) add release tool entry in distribution tools ([~#2212~](https://github.com/sourcegraph/about/issues/2212))

@davejrt: __1.00d__

- [ ] monitoring: panel API redux tracking issue ([#16697](https://github.com/sourcegraph/sourcegraph/issues/16697)) __1.00d__
  - [x] (🏁 13 days ago) monitoring: Implement existing functionality in the new API ([~#17061~](https://github.com/sourcegraph/sourcegraph/issues/17061)) __1.00d__

Completed: __1.00d__
- [x] (🏁 13 days ago) create customer release tracking issues automatically ([~#16216~](https://github.com/sourcegraph/sourcegraph/issues/16216)) 🧶
- [x] (🏁 13 days ago) monitoring: Implement existing functionality in the new API ([~#17061~](https://github.com/sourcegraph/sourcegraph/issues/17061)) __1.00d__
- [x] (🏁 11 days ago) redis-exporter image is 32-bit and not open-source ([~#11323~](https://github.com/sourcegraph/sourcegraph/issues/11323))
- [x] (🏁 10 days ago) sourcegraph/customer ([~#129~](https://github.com/sourcegraph/customer/issues/129)) 👩

@daxmc99: __1.50d__

- [ ] Tracking issue: Dhall test components ([#16796](https://github.com/sourcegraph/sourcegraph/issues/16796)) __1.50d__
  - [x] (🏁 10 days ago) dhall: tests for grafana component ([~#16802~](https://github.com/sourcegraph/sourcegraph/issues/16802)) __0.50d__
  - [x] (🏁 10 days ago) dhall: tests for repo-updater component ([~#16803~](https://github.com/sourcegraph/sourcegraph/issues/16803)) __0.50d__
  - [x] (🏁 10 days ago) dhall: tests for postgres component ([~#16804~](https://github.com/sourcegraph/sourcegraph/issues/16804)) __0.50d__

Completed: __1.50d__
- [x] (🏁 10 days ago) dhall: tests for postgres component ([~#16804~](https://github.com/sourcegraph/sourcegraph/issues/16804)) __0.50d__
- [x] (🏁 10 days ago) dhall: tests for grafana component ([~#16802~](https://github.com/sourcegraph/sourcegraph/issues/16802)) __0.50d__
- [x] (🏁 10 days ago) dhall: tests for repo-updater component ([~#16803~](https://github.com/sourcegraph/sourcegraph/issues/16803)) __0.50d__

@ggilmore: __1.00d__

- [ ] Tracking issue: Dhall test components ([#16796](https://github.com/sourcegraph/sourcegraph/issues/16796)) __1.00d__
  - [x] (🏁 12 days ago) dhall: tests for github-proxy component ([~#16798~](https://github.com/sourcegraph/sourcegraph/issues/16798)) __0.50d__
  - [x] (🏁 today) dhall: tests for symbols component ([~#16799~](https://github.com/sourcegraph/sourcegraph/issues/16799)) __0.50d__

Completed: __1.00d__
- [x] (🏁 12 days ago) dhall: tests for github-proxy component ([~#16798~](https://github.com/sourcegraph/sourcegraph/issues/16798)) __0.50d__
- [x] (🏁 today) dhall: tests for symbols component ([~#16799~](https://github.com/sourcegraph/sourcegraph/issues/16799)) __0.50d__

@pecigonzalo

- [ ] ~sourcegraph/customer~ ([#180](https://github.com/sourcegraph/customer/issues/180)) 👩

Completed
- [x] (🏁 13 days ago) Upgrade dogfood GHE to 2.22.6 ([~#17202~](https://github.com/sourcegraph/sourcegraph/issues/17202))
- [x] (🏁 11 days ago) Add cost-saving help for k8s resource estimator ([~#17274~](https://github.com/sourcegraph/sourcegraph/pull/17274)) :shipit:
- [x] (🏁 10 days ago) sourcegraph/customer ([~#176~](https://github.com/sourcegraph/customer/issues/176)) 👩

@uwedeportivo: __4.00d__

- [ ] Tracking issue: Dhall test components ([#16796](https://github.com/sourcegraph/sourcegraph/issues/16796)) __1.00d__
  - [x] (🏁 today) dhall: tests for query-runner component ([~#16800~](https://github.com/sourcegraph/sourcegraph/issues/16800)) __0.50d__
  - [x] (🏁 today) dhall: tests for searcher component ([~#16801~](https://github.com/sourcegraph/sourcegraph/issues/16801)) __0.50d__

Completed: __4.00d__
- [x] (🏁 6 days ago) dhall: implement searcher service in deploy-sourcegraph-dhall ([~#16267~](https://github.com/sourcegraph/sourcegraph/issues/16267)) __3.00d__
- [x] (🏁 today) dhall: tests for query-runner component ([~#16800~](https://github.com/sourcegraph/sourcegraph/issues/16800)) __0.50d__
- [x] (🏁 today) dhall: tests for searcher component ([~#16801~](https://github.com/sourcegraph/sourcegraph/issues/16801)) __0.50d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by pecigonzalo** [comment]
## Last week

Last week I came back from holidays and was mostly catching up with email, Slack, GitHub. I also went over and closed some old GitHub issues to try and cleanup our backlog.

## This week

This week ill be mostly planning for a Distribution virtual workshop/offsite and working on updating our hiring docs, process, profile, etc.

**Comment by davejrt** [comment]
**Last week**

Return from vacation, catching up on slack, meetings and quite a bit of admin work. Pushed the updates for the release tool, met with Robert to get some help and guidance on the monitoring redux.

**This week**

Continue on the the monitoring work with Robert, work through any tech debt in between to help support the learning(Go) I want/need to do.

**Comment by pecigonzalo** [comment]
### Last week

Worked mostly around some customer issues (misleading cost-estimator, problem after an upgrade) and some internal requests like upgrading GHE. I was also working on updating and testing our code challenges for interviews and the documentation around the process.

### This week

This week is going to be focused on the virtual workshop and continuing to work on the interview process and docs as well as reach out to potential candidates.

**Comment by bobheadxi** [comment]
## last week

Monitoring annotations, misc dashboard improvements (postgres, prometheus, container restarts), misc generator improves (strict comparators + alert refactor, etc), cAdvisor investigation (culminating in https://github.com/sourcegraph/sourcegraph/issues/17365). Also minor follow-ups to the above as needed.

## this week

Ensure tasks related to things I've been working on get wrapped up + documented. Virtual workshops and handoff prep
