### ISSUE TITLE
3.24 release tracking issue

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#17144]
# 3.24 Release

This release is scheduled for [Jan 20, 2021, 6:00 PM (UTC)](https://time.is/1800_20_Jan_2021_in_UTC?3.24%20release%20date).

---

**Note:** All `yarn run release ...` commands should be run from folder `dev/release`.

**Note:** All `yarn run test ...` commands should be run from folder `web`.

## Setup

- [x] Ensure release configuration in [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) on `main` is up to date with the parameters for the current release.
- [x] Ensure you have the latest version of the release tooling and configuration by checking out and updating `sourcegraph@main`.

## [Jan 14, 2021, 6:00 PM (UTC)](https://time.is/1800_14_Jan_2021_in_UTC?Five%20working%20days%20before%203.24%20release) (5 work days before release): Prep for branch cut

- [x] Post a release status update to Slack - review all release-blocking issues, and ensure someone is resolving each.
  ```sh
  yarn run release release:status
  ``` 

## [Jan 15, 2021, 6:00 PM (UTC)](https://time.is/1800_15_Jan_2021_in_UTC?Four%20working%20days%20before%203.24%20release) (4 work days before release): Branch cut

- [x] Update the changelog and merge the generated pull request:
  ```sh
  yarn run release changelog:cut
  ```
- [x] Create the `3.24` branch off the CHANGELOG commit in the previous step: `git branch 3.24 && git push origin 3.24`.

Upon branch cut, create and test the first release candidate:

- [x] Tag the first release candidate:
  ```sh
  yarn run release release:create-candidate 1
  ```
- [x] Wait for the [Sourcegraph pipeline](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=3.24), [QA pipeline](https://buildkite.com/sourcegraph/qa/builds?branch=3.24), and [E2E pipeline](https://buildkite.com/sourcegraph/e2e/builds?branch=3.24) in Buildkite to complete.
- [x] File any failures and regressions in the pipelines as `release-blocker` issues and assign the appropriate teams.

Revert or disable features that may cause delays. As necessary, `git cherry-pick` bugfix (not feature!) commits from `main` into the release branch. Continue to create new release candidates daily or as necessary, until no more `release-blocker` issues remain:

- [x] Cut the Nth release candidate:
  ```sh
  N=<release-candidate-number> yarn run release release:create-candidate $N
  ```
- [x] Re-run the automated test suite against the new release candidate, file any regressions as
  `release-blocker` issues.
  - [x] If necessary, manually test features or workflows affected by the cherry-pick.
- [x] Post a release status update by running the command below. Ensure someone is resolving each release-blocking issue. If there are no more release-blocking issues, proceed to tag the final release in the next section.
  ```
  yarn run release release:status
  ``` 

## Tag final release

Once there are no more release-blocking issues (as reported by the `release:status` command) proceed with creating the final release:

- [x] Verify the [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) on
  `main` is accurate (no items should have been added since branch cut, but some items may need to
  be removed).
- [x] Tag the final release:
  ```sh
  yarn run release release:create-candidate final
  ```
- [x] Wait for the release Docker images to be available in [Docker Hub](https://hub.docker.com/r/sourcegraph/server/tags).
- [x] Open PRs that publish the new release and address any action items required to finalize draft PRs (track PR status via the [generated release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns)):
  ```sh
  yarn run release release:stage
  ```

## [Jan 20, 2021, 6:00 PM (UTC)](https://time.is/1800_20_Jan_2021_in_UTC?3.24%20release%20date): Release

- [x] From the [release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns), merge the release-publishing PRs created previously.
  - For [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph), also:
    - [x] Tag the `v3.24.0` release at the most recent commit on the `v3.24` branch.
        ```sh
        VERSION='v3.24.0' bash -c 'git tag -a "$VERSION" -m "$VERSION" && git push origin "$VERSION"'
        ```
  - For [sourcegraph](https://github.com/sourcegraph/sourcegraph), also:
    - [x] Cherry pick the release-publishing PR from `sourcegraph/sourcegraph@main` into the release branch.
- [x] Ask the product team to merge the blog post ([example](https://github.com/sourcegraph/about/pull/83)). Add the pull request to the release campaign:
  ```sh
  yarn run release release:add-to-campaign sourcegraph/about <pr-number>
  ```
- [x] Finalize and announce that the release is live:
  ```sh
  yarn run release release:close
  ```

## Post-release

Notify the next release captain that they are on duty for the next release. They should complete the steps in this section.

- [x] Open a PR to update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the parameters for the current release.
- [x] Ensure you have the latest version of the release tooling and configuration by checking out and updating `sourcegraph@main`.
- [x] Create release calendar events, tracking issue, and announcement for next release:
  ```sh
  yarn run release tracking:issues
  yarn run release tracking:timeline
  ```
- [x] Close this issue.

**Note:** If a patch release is requested after the release, ask that a [patch request issue](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=&labels=team%2Fdistribution&template=request_patch_release.md&title=3.24.1%3A+) be filled out and approved first.

**Comment by bobheadxi** [comment]
@davejrt do you mind if we merge https://github.com/sourcegraph/sourcegraph/pull/17401 before doing the post-release steps here?

**Comment by davejrt** [comment]
> @davejrt do you mind if we merge #17401 before doing the post-release steps here?

For sure! Go ahead.

**Comment by davejrt** [comment]
*Sourcegraph 3.24.0 has been published*

* Changelog: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#3-24-0
* Release campaign: https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.24.0

@davejrt: Please complete the post-release steps before closing this issue.
