### ISSUE TITLE
3.24.0 upgrade managed instance tracking issue

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#17173]
# 3.24

## [Jan 21, 2021, 6:00 PM (UTC)](https://time.is/1800_21_Jan_2021_in_UTC?One%20working%20day%20before%203.24%20release) Upgrade managed instances

- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com)
- [x] Upgrade [devmanaged.sourcegraph.com](https://demo.sourcegraph.com)
- [x] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/1712860829](https://app.hubspot.com/contacts/2762526/company/1712860829/)
