### ISSUE TITLE
Cloud 2021-01-13 Tracking issue

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#17201]
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@artemruts

- [ ] Manage repositories view question ([#17354](https://github.com/sourcegraph/sourcegraph/issues/17354))

Completed
- [x] (🏁 27 days ago) Adds CircleDashedIcon to shared components ([~#17185~](https://github.com/sourcegraph/sourcegraph/pull/17185)) :shipit:
- [x] (🏁 27 days ago) Fixes links between repos and code hosts pages, minor routing cleanup. ([~#17179~](https://github.com/sourcegraph/sourcegraph/pull/17179)) :shipit:
- [x] (🏁 26 days ago) Add unique keys to repo page links ([~#17190~](https://github.com/sourcegraph/sourcegraph/pull/17190)) :shipit:🧶
- [x] (🏁 25 days ago) Don't check 'select all' with no query hits ([~#17291~](https://github.com/sourcegraph/sourcegraph/pull/17291)) :shipit:
- [x] (🏁 24 days ago) Fixes a link from repos to code hosts when no code hosts were active. ([~#17330~](https://github.com/sourcegraph/sourcegraph/pull/17330)) :shipit:
- [x] (🏁 4 days ago) Reuse sign-in OAuth workflow for code host connections ([~#17356~](https://github.com/sourcegraph/sourcegraph/issues/17356))
- [x] (🏁 today) One-click OAuth sign-in connection for security page ([~#17166~](https://github.com/sourcegraph/sourcegraph/issues/17166))

@arussellsaw: __3.00d__

- [ ] WIP: Cloud Milestone 3 Tracking issue ([#15610](https://github.com/sourcegraph/sourcegraph/issues/15610))
  - [x] (🏁 19 days ago) User <-> Public Repo mapping table ([~#17048~](https://github.com/sourcegraph/sourcegraph/issues/17048))

Completed: __3.00d__
- [x] (🏁 19 days ago) User <-> Public Repo mapping table ([~#17048~](https://github.com/sourcegraph/sourcegraph/issues/17048))
- [x] (🏁 12 days ago) Overhaul aggregated errors sent to Sentry ([~#16109~](https://github.com/sourcegraph/sourcegraph/issues/16109); PRs: ~[#17363](https://github.com/sourcegraph/sourcegraph/pull/17363)~) __3.00d__ 🎩

@asdine: __10.00d__

- [ ] monitoring: Disable auto deploy of latest main in deploy-sourcegraph-dot-com ([#16654](https://github.com/sourcegraph/sourcegraph/issues/16654))
- [ ] db: deprecate SetupGlobalConnection and SetupGlobalTestDB ([#17548](https://github.com/sourcegraph/sourcegraph/pull/17548)) :shipit:

Completed: __10.00d__
- [x] (🏁 25 days ago) Migrate to pgx library for Postgres access ([~#16575~](https://github.com/sourcegraph/sourcegraph/issues/16575); PRs: ~[#16901](https://github.com/sourcegraph/sourcegraph/pull/16901)~) __3.00d__
- [x] (🏁 21 days ago) Convert the accessTokens store to use the basestore package ([~#15844~](https://github.com/sourcegraph/sourcegraph/issues/15844); PRs: ~[#17405](https://github.com/sourcegraph/sourcegraph/pull/17405)~) __0.50d__ 🧶
- [x] (🏁 21 days ago) Convert the defaultRepos store to use the basestore package ([~#15845~](https://github.com/sourcegraph/sourcegraph/issues/15845); PRs: ~[#17406](https://github.com/sourcegraph/sourcegraph/pull/17406)~) __0.50d__ 🧶
- [x] (🏁 21 days ago) Convert the orgs store to use the basestore package ([~#15849~](https://github.com/sourcegraph/sourcegraph/issues/15849); PRs: ~[#17413](https://github.com/sourcegraph/sourcegraph/pull/17413)~) __0.50d__ 🧶
- [x] (🏁 21 days ago) Replace global database by local handle in AccessTokenStore ([~#17409~](https://github.com/sourcegraph/sourcegraph/pull/17409)) :shipit:
- [x] (🏁 21 days ago) Convert the queryRunnerState store to use the basestore package ([~#15847~](https://github.com/sourcegraph/sourcegraph/issues/15847); PRs: ~[#17410](https://github.com/sourcegraph/sourcegraph/pull/17410)~) __0.50d__ 🧶
- [x] (🏁 21 days ago) Convert the phabricator store to use the basestore package ([~#15846~](https://github.com/sourcegraph/sourcegraph/issues/15846); PRs: ~[#17407](https://github.com/sourcegraph/sourcegraph/pull/17407)~) __0.50d__ 🧶
- [x] (🏁 21 days ago) Convert the savedSearches store to use the basestore package ([~#15851~](https://github.com/sourcegraph/sourcegraph/issues/15851); PRs: ~[#17420](https://github.com/sourcegraph/sourcegraph/pull/17420)~) __0.50d__ 🧶
- [x] (🏁 20 days ago) Convert the namespaces store to use the basestore package ([~#15848~](https://github.com/sourcegraph/sourcegraph/issues/15848); PRs: ~[#17411](https://github.com/sourcegraph/sourcegraph/pull/17411)~) __0.50d__ 🧶
- [x] (🏁 20 days ago) Convert the orgMembers store to use the basestore package ([~#15850~](https://github.com/sourcegraph/sourcegraph/issues/15850); PRs: ~[#17417](https://github.com/sourcegraph/sourcegraph/pull/17417)~) __0.50d__ 🧶
- [x] (🏁 20 days ago) Delete saved searches when a user is hard deleted ([~#17461~](https://github.com/sourcegraph/sourcegraph/pull/17461)) :shipit:
- [x] (🏁 20 days ago) Convert the settings store to use the basestore package ([~#15853~](https://github.com/sourcegraph/sourcegraph/issues/15853); PRs: ~[#17455](https://github.com/sourcegraph/sourcegraph/pull/17455)~) __0.50d__ 🧶
- [x] (🏁 20 days ago) Convert the eventLogs store to use the basestore package ([~#15857~](https://github.com/sourcegraph/sourcegraph/issues/15857); PRs: ~[#17456](https://github.com/sourcegraph/sourcegraph/pull/17456)~) __0.50d__ 🧶
- [x] (🏁 20 days ago) Convert the orgInvitations store to use the basestore package ([~#15861~](https://github.com/sourcegraph/sourcegraph/issues/15861); PRs: ~[#17457](https://github.com/sourcegraph/sourcegraph/pull/17457)~) __0.50d__ 🧶
- [x] (🏁 20 days ago) Convert the surveyResponses store to use the basestore package ([~#15858~](https://github.com/sourcegraph/sourcegraph/issues/15858); PRs: ~[#17459](https://github.com/sourcegraph/sourcegraph/pull/17459)~) __0.50d__
- [x] (🏁 20 days ago) Convert the secrets store to use the basestore package ([~#15862~](https://github.com/sourcegraph/sourcegraph/issues/15862); PRs: ~[#17458](https://github.com/sourcegraph/sourcegraph/pull/17458)~) __0.50d__ 🧶
- [x] (🏁 20 days ago) Merge dbconn and dbutil packages ([~#16586~](https://github.com/sourcegraph/sourcegraph/issues/16586); PRs: ~[#17399](https://github.com/sourcegraph/sourcegraph/pull/17399)~) __0.50d__
- [x] (🏁 19 days ago) user-public-store: Remove dependency to global dbconn ([~#17500~](https://github.com/sourcegraph/sourcegraph/pull/17500)) :shipit:
- [x] (🏁 19 days ago) db: rename global variables ([~#17503~](https://github.com/sourcegraph/sourcegraph/pull/17503)) :shipit:
- [x] (🏁 19 days ago) db: rename store constructors ([~#17506~](https://github.com/sourcegraph/sourcegraph/pull/17506)) :shipit:
- [x] (🏁 19 days ago) db: remove references to dbconn in store tests ([~#17511~](https://github.com/sourcegraph/sourcegraph/pull/17511)) :shipit:
- [x] (🏁 19 days ago) chores: random cleanup of internal/db ([~#17518~](https://github.com/sourcegraph/sourcegraph/pull/17518)) :shipit:
- [x] (🏁 18 days ago) db: convert PermStore into a basestore ([~#17516~](https://github.com/sourcegraph/sourcegraph/pull/17516)) :shipit:
- [x] (🏁 18 days ago) frontend: inject db handle into schemaResolver ([~#17546~](https://github.com/sourcegraph/sourcegraph/pull/17546)) :shipit:
- [x] (🏁 14 days ago) db: rename internal/db package to internal/database ([~#17607~](https://github.com/sourcegraph/sourcegraph/pull/17607)) :shipit:
- [x] (🏁 14 days ago) db: rename enterprise/internal/db package to enterprise/internal/database ([~#17629~](https://github.com/sourcegraph/sourcegraph/pull/17629)) :shipit:

@flying-robot: __4.50d__

- [ ] WIP: Cloud Milestone 3 Tracking issue ([#15610](https://github.com/sourcegraph/sourcegraph/issues/15610)) __1.00d__
  - [x] (🏁 26 days ago) Do not overwrite display name and avatar URL when not empty ([~#17086~](https://github.com/sourcegraph/sourcegraph/issues/17086); PRs: ~[#17257](https://github.com/sourcegraph/sourcegraph/pull/17257)~) __1.00d__

Completed: __4.50d__
- [x] (🏁 27 days ago) Include additional unique user information in session ([~#16680~](https://github.com/sourcegraph/sourcegraph/issues/16680)) __1.50d__
- [x] (🏁 26 days ago) Do not overwrite display name and avatar URL when not empty ([~#17086~](https://github.com/sourcegraph/sourcegraph/issues/17086); PRs: ~[#17257](https://github.com/sourcegraph/sourcegraph/pull/17257)~) __1.00d__
- [x] (🏁 15 days ago) Self-service Teams subscription is appearing as "Enterprise" in customer's Sourcegraph instance ([~#17332~](https://github.com/sourcegraph/sourcegraph/issues/17332)) __2.00d__

@quinnkeast

- [ ] Manage repositories view question ([#17354](https://github.com/sourcegraph/sourcegraph/issues/17354))
- [ ] WIP: Cloud Milestone 3 Tracking issue ([#15610](https://github.com/sourcegraph/sourcegraph/issues/15610))
  - [x] (🏁 20 days ago) Handling async repo list fetching ([~#16948~](https://github.com/sourcegraph/sourcegraph/issues/16948); PRs: ~[#17240](https://github.com/sourcegraph/sourcegraph/pull/17240)~)

Completed
- [x] (🏁 20 days ago) Handling async repo list fetching ([~#16948~](https://github.com/sourcegraph/sourcegraph/issues/16948); PRs: ~[#17240](https://github.com/sourcegraph/sourcegraph/pull/17240)~)
- [x] (🏁 today) One-click OAuth sign-in connection for security page ([~#17166~](https://github.com/sourcegraph/sourcegraph/issues/17166))

@ryanslade: __5.50d__

Completed: __5.50d__
- [x] (🏁 26 days ago) repo-updater: Fix state page ([~#17272~](https://github.com/sourcegraph/sourcegraph/pull/17272)) :shipit:
- [x] (🏁 26 days ago) monitoring: Increase alert time range ([~#17269~](https://github.com/sourcegraph/sourcegraph/pull/17269)) :shipit:
- [x] (🏁 26 days ago) Convert the users store to use the basestore package ([~#15854~](https://github.com/sourcegraph/sourcegraph/issues/15854); PRs: ~[#17262](https://github.com/sourcegraph/sourcegraph/pull/17262)~) __0.50d__ 🧶
- [x] (🏁 26 days ago) db: Combine files that deal with db.UserStore ([~#17275~](https://github.com/sourcegraph/sourcegraph/pull/17275)) :shipit:
- [x] (🏁 25 days ago) repo-updater: Fix update queue length metric ([~#17308~](https://github.com/sourcegraph/sourcegraph/pull/17308)) :shipit:
- [x] (🏁 25 days ago) repo-updater: Small cleanup ([~#17302~](https://github.com/sourcegraph/sourcegraph/pull/17302)) :shipit:
- [x] (🏁 25 days ago) Revert "repo-updater: Small cleanup (#17302)" ([~#17316~](https://github.com/sourcegraph/sourcegraph/pull/17316)) :shipit:
- [x] (🏁 22 days ago) repo-updater: Don't schedule all repos for update on startup ([~#17318~](https://github.com/sourcegraph/sourcegraph/pull/17318)) :shipit:
- [x] (🏁 21 days ago) repo-updater: Fix update queue debug page ([~#17369~](https://github.com/sourcegraph/sourcegraph/pull/17369)) :shipit:
- [x] (🏁 21 days ago) repo-updater queue length alert firing ([~#17351~](https://github.com/sourcegraph/sourcegraph/issues/17351))
- [x] (🏁 21 days ago) Mirroring stats are inconsistent on Cloud ([~#17238~](https://github.com/sourcegraph/sourcegraph/issues/17238)) __1.00d__ 🐛
- [x] (🏁 21 days ago) ~doc: Include note on silencing sourgraph.com alerts~ ([~#17400~](https://github.com/sourcegraph/sourcegraph/pull/17400)) :shipit:
- [x] (🏁 21 days ago) db: Return tx.Done error ([~#17415~](https://github.com/sourcegraph/sourcegraph/pull/17415)) :shipit:
- [x] (🏁 20 days ago) Convert the userEmails store to use the basestore package ([~#15856~](https://github.com/sourcegraph/sourcegraph/issues/15856); PRs: ~[#17448](https://github.com/sourcegraph/sourcegraph/pull/17448)~) __0.50d__ 🧶
- [x] (🏁 20 days ago) Convert the userCredentials store to use the basestore package ([~#15855~](https://github.com/sourcegraph/sourcegraph/issues/15855); PRs: ~[#17469](https://github.com/sourcegraph/sourcegraph/pull/17469)~) __0.50d__
- [x] (🏁 19 days ago) Convert the userExternalAccounts store to use the basestore package ([~#15859~](https://github.com/sourcegraph/sourcegraph/issues/15859); PRs: ~[#17473](https://github.com/sourcegraph/sourcegraph/pull/17473)~) __0.50d__ 🧶
- [x] (🏁 19 days ago) db: external_services.cloud_default column should not be nullable ([~#17514~](https://github.com/sourcegraph/sourcegraph/pull/17514)) :shipit:
- [x] (🏁 15 days ago) Sync and index all non global external services on Cloud ([~#17472~](https://github.com/sourcegraph/sourcegraph/issues/17472); PRs: ~[#17501](https://github.com/sourcegraph/sourcegraph/pull/17501)~, ~[#17519](https://github.com/sourcegraph/sourcegraph/pull/17519)~, ~[#17550](https://github.com/sourcegraph/sourcegraph/pull/17550)~) __1.50d__
- [x] (🏁 14 days ago) Sourcegraph.com not indexing repos added by org ([~#17424~](https://github.com/sourcegraph/sourcegraph/issues/17424); PRs: ~[#17463](https://github.com/sourcegraph/sourcegraph/pull/17463)~) 🐛
- [x] (🏁 14 days ago) Improve rate limit instrumentation ([~#17200~](https://github.com/sourcegraph/sourcegraph/issues/17200); PRs: ~[#17567](https://github.com/sourcegraph/sourcegraph/pull/17567)~) __1.00d__

@unknwon: __5.00d__

Completed: __5.00d__
- [x] (🏁 21 days ago) RFC 277: Add new Perforce code host connection type ([~#16702~](https://github.com/sourcegraph/sourcegraph/issues/16702); PRs: ~[#17348](https://github.com/sourcegraph/sourcegraph/pull/17348)~) __2.00d__ 👩
- [x] (🏁 18 days ago) gitserver: abstract clone and fetch operations for different VCS ([~#17474~](https://github.com/sourcegraph/sourcegraph/pull/17474)) :shipit:
- [x] (🏁 14 days ago) gitserver: able to clone and fetch Perforce depots ([~#17551~](https://github.com/sourcegraph/sourcegraph/pull/17551)) :shipit:
- [x] (🏁 12 days ago) Overhaul aggregated errors sent to Sentry ([~#16109~](https://github.com/sourcegraph/sourcegraph/issues/16109); PRs: ~[#17363](https://github.com/sourcegraph/sourcegraph/pull/17363)~) __3.00d__ 🎩

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by artemruts** [comment]
### Last week

* Mostly working on closing little bugs/missed things for the [Milestone 3](https://github.com/orgs/sourcegraph/projects/108)
* Minor code reviews for Milestone 3
* [Worked on the new UI OAuth page](https://github.com/orgs/sourcegraph/projects/126) - code host connections

### This week

* Finish OAuth for code host connections and merge to `main`
* Start working on the OAuth UI for the signup pages
* Finish personal development plan & RFC on JS error dashboards

**Comment by unknwon** [comment]
### Last week

Kicked off the work for RFC 277

### This week

Continue tackling items of RFC 277

**Comment by ryanslade** [comment]
## Last Week

* Investigated a some customer issues, https://github.com/sourcegraph/customer/issues/173 and https://github.com/sourcegraph/customer/issues/172. Solutions proposed, waiting to hear back whether they were succesful.
* Worked on some db tech debt tasks
* Investigated some issues around `repo-updater` scheduling too many updates. Fix proposed: https://github.com/sourcegraph/sourcegraph/pull/17318

## This week

* Trigger zoekt indexing on demand when we know a repo has been updated
* Continue on tech debt to convert db packages to use basestore
* Possibly continue work on customer issues if the proposals didn't help

**Comment by asdine** [comment]
Last Week

- Migrated our PostgreSQL driver from https://github.com/lib/pq to https://github.com/jackc/pgx #16575 

This week

- Merge dbconn and dbutil packages
- Work on database stores
-

**Comment by unknwon** [comment]
### Last week

Basically finished syncing code from a Perforce Server.

### This week

Finish syncing permissions from a Perforce Server.

**Comment by ryanslade** [comment]
## Last Week

* Happy to say that that both customer issues were resolved with no code changes :) 
  * https://github.com/sourcegraph/customer/issues/173 - A combination of misconfiguration and `repo-updater` not running the correct version.
  * https://github.com/sourcegraph/customer/issues/172 - Confusion with the interplay between `repositoryPathPattern` and `nameTransformations` when combined with `exclude`
* Finished changes to the way we sync and index on cloud so that ONLY our default global external services are synced on demand, all other will be synced in the background on a schedule.

## This week

* Finish off rate limit instrumentation improvements and plan for the next cycle.

**Comment by asdine** [comment]
### Last week

- Migrated backend code to the basestore package
- Started removing calls to dbconn.Global

### This week

- Keep working on removing calls to dbconn.Global
- Migrate from `database/sql` to `jackc/sqlx`
