### ISSUE TITLE
code insights: backend MVP implementation

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#17218]
This is a tracking issue for implementing the MVP backend for Code Insights.

General strategy is documented in [RFC 273: Code Insights backend](https://docs.google.com/document/d/1LX6Msbxnz_DRf6OItZLaX-vELfnHGKgODkb1bVauolk/edit#heading=h.trqab8y0kufp).

**TL;DR**: We have a good amount of information that customers are interested in Code Insights. We have an experimental frontend demo we have been showing to prospective customers (viewable on k8s.sgdev.org) and multiple customers are interested in this. However, we are entirely blocked on having a scalable backend before customers can actually use it and we can get feedback on it to determine the product direction in general (there are still many open questions.) The team has not yet been able to hire a backend engineer, and Felix and Joel have chatted with me extensively about having me step in to contribute a solid foundation which customers can use at scale so we can determine what to do with the product next, and be able to make our first backend engineer hire for the team and make them be productive / have clear direction. The goal here is for @slimsag to work with the code insights team closely to add an MVP backend that can be used at scale and as a good foundation, and help with making the team generally successful in the future (once @slimsag steps back and goes onto other projects.)

### Tracked issues

@slimsag

- [ ] internal contributor 3.25 Tracking issue ([#17737](https://github.com/sourcegraph/sourcegraph/issues/17737))
  - [x] (🏁 19 days ago) add codeinsights-db (TimescaleDB) deployment ([~#1851~](https://github.com/sourcegraph/deploy-sourcegraph/pull/1851)) :shipit:
  - [x] (🏁 19 days ago) insights: set POSTGRES_PASSWORD ([~#1856~](https://github.com/sourcegraph/deploy-sourcegraph/pull/1856)) :shipit:
  - [x] (🏁 18 days ago) codeinsights-db: remove liveness/readiness probes ([~#1859~](https://github.com/sourcegraph/deploy-sourcegraph/pull/1859)) :shipit:
  - [x] (🏁 18 days ago) frontend: configure codeinsights DB env var ([~#1864~](https://github.com/sourcegraph/deploy-sourcegraph/pull/1864)) :shipit:
  - [x] (🏁 19 days ago) sourcegraph/deploy-sourcegraph-dot-com ([~#4599~](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/4599)) :shipit:
  - [x] (🏁 19 days ago) sourcegraph/deploy-sourcegraph-dot-com ([~#4600~](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/4600)) :shipit:
  - [x] (🏁 19 days ago) sourcegraph/deploy-sourcegraph-dot-com ([~#4601~](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/4601)) :shipit:
  - [x] (🏁 40 days ago) code insights: add Postgres migrations foundation ([~#17219~](https://github.com/sourcegraph/sourcegraph/issues/17219); PRs: ~[#17432](https://github.com/sourcegraph/sourcegraph/pull/17432)~, ~[#17586](https://github.com/sourcegraph/sourcegraph/pull/17586)~, ~[#17588](https://github.com/sourcegraph/sourcegraph/pull/17588)~)
  - [x] (🏁 27 days ago) code insights: add experimental GraphQL API ([~#17221~](https://github.com/sourcegraph/sourcegraph/issues/17221); PRs: ~[#17497](https://github.com/sourcegraph/sourcegraph/pull/17497)~, ~[#18075](https://github.com/sourcegraph/sourcegraph/pull/18075)~)
  - [x] (🏁 today) code insights: document that it is not supported in sourcegraph/server demo deployments ([~#17222~](https://github.com/sourcegraph/sourcegraph/issues/17222); PRs: ~[#17735](https://github.com/sourcegraph/sourcegraph/pull/17735)~)
  - [x] (🏁 18 days ago) code insights: deploy TimescaleDB in Kubernetes deployments ([~#17224~](https://github.com/sourcegraph/sourcegraph/issues/17224))
  - [x] (🏁 16 days ago) code insights: deploy TimescaleDB in docker-compose deployments ([~#17225~](https://github.com/sourcegraph/sourcegraph/issues/17225); PRs: ~[#259](https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/259)~)
  - [x] (🏁 39 days ago) code insights: deploy TimescaleDB in dev and CI environments ([~#17226~](https://github.com/sourcegraph/sourcegraph/issues/17226); PRs: ~[#17431](https://github.com/sourcegraph/sourcegraph/pull/17431)~, ~[#17733](https://github.com/sourcegraph/sourcegraph/pull/17733)~)
  - [x] (🏁 54 days ago) internal/db: generate separate schema.md files for codeintel and frontend DBs ([~#17228~](https://github.com/sourcegraph/sourcegraph/pull/17228)) :shipit:
  - [x] (🏁 47 days ago) docker-images: tag TimescaleDB as sourcegraph/codeinsights-db ([~#17427~](https://github.com/sourcegraph/sourcegraph/pull/17427)) :shipit:
  - [x] (🏁 40 days ago) internal/db: do not run TimescaleDB migrations against singleton database ([~#17585~](https://github.com/sourcegraph/sourcegraph/pull/17585)) :shipit:
  - [x] (🏁 40 days ago) Revert "insights: execute database migrations (#17586)" ([~#17701~](https://github.com/sourcegraph/sourcegraph/pull/17701)) :shipit:
  - [x] (🏁 39 days ago) dev/ci: do *not* run e2e sourcegraph/server tests with DEPLOY_TYPE=dev ([~#17731~](https://github.com/sourcegraph/sourcegraph/pull/17731)) :shipit:
  - [x] (🏁 39 days ago) Revert "Revert "insights: execute database migrations (#17586)" (#17701)" ([~#17732~](https://github.com/sourcegraph/sourcegraph/pull/17732)) :shipit:
  - [x] (🏁 39 days ago) code insights: add dev option to disable code insights backend entirely ([~#17738~](https://github.com/sourcegraph/sourcegraph/pull/17738)) :shipit:
  - [x] (🏁 39 days ago) code insights: fully qualify Postgres DSN to avoid conflicts ([~#17742~](https://github.com/sourcegraph/sourcegraph/pull/17742)) :shipit:
  - [x] (🏁 39 days ago) dev: give codeinsights-db more time to start ([~#17744~](https://github.com/sourcegraph/sourcegraph/pull/17744)) :shipit:
  - [x] (🏁 34 days ago) code insights: add new GraphQL schema ([~#17842~](https://github.com/sourcegraph/sourcegraph/pull/17842)) :shipit:
  - [x] (🏁 37 days ago) code insights: improve backend testing experience ([~#17843~](https://github.com/sourcegraph/sourcegraph/pull/17843)) :shipit:
  - [x] (🏁 34 days ago) code insights: add new user/org/global settings schema ([~#17844~](https://github.com/sourcegraph/sourcegraph/pull/17844)) :shipit:
  - [x] (🏁 37 days ago) insights: skip integration tests if DB unavailable in dev environments ([~#17861~](https://github.com/sourcegraph/sourcegraph/pull/17861)) :shipit:
  - [x] (🏁 30 days ago) insights: split out DB testing setup code into separate package ([~#18001~](https://github.com/sourcegraph/sourcegraph/pull/18001)) :shipit:
  - [x] (🏁 28 days ago) insights: add very basic GraphQL resolver integration test ([~#18035~](https://github.com/sourcegraph/sourcegraph/pull/18035)) :shipit:
  - [x] (🏁 4 days ago) dev: make drop-entire-db script also drop insights DB ([~#18081~](https://github.com/sourcegraph/sourcegraph/pull/18081)) :shipit:
  - [x] (🏁 26 days ago) insights: add initial DB schema ([~#18083~](https://github.com/sourcegraph/sourcegraph/pull/18083)) :shipit:
  - [x] (🏁 26 days ago) insights: add & prepare to use generated store mocks ([~#18118~](https://github.com/sourcegraph/sourcegraph/pull/18118)) :shipit:
  - [x] (🏁 26 days ago) insights: store: add support for querying series data points ([~#18129~](https://github.com/sourcegraph/sourcegraph/pull/18129)) :shipit:
  - [x] (🏁 26 days ago) insights: resolvers: implement point querying & add integration tests ([~#18130~](https://github.com/sourcegraph/sourcegraph/pull/18130)) :shipit:
  - [x] (🏁 23 days ago) insights: change series_id to string (hash); add index ([~#18230~](https://github.com/sourcegraph/sourcegraph/pull/18230)) :shipit:
  - [x] (🏁 20 days ago) insights: store: query metadata & other minor improvements ([~#18254~](https://github.com/sourcegraph/sourcegraph/pull/18254)) :shipit:
  - [x] (🏁 20 days ago) insights: store: add support for recording data points ([~#18255~](https://github.com/sourcegraph/sourcegraph/pull/18255)) :shipit:
  - [x] (🏁 20 days ago)  insights: add new discovery package for locating insights (and use it) ([~#18264~](https://github.com/sourcegraph/sourcegraph/pull/18264)) :shipit:
  - [x] (🏁 20 days ago) migrations: add insights_query_runner_jobs table ([~#18265~](https://github.com/sourcegraph/sourcegraph/pull/18265)) :shipit:
  - [x] (🏁 19 days ago) insights: actually enqueue/record insights from global settings ([~#18314~](https://github.com/sourcegraph/sourcegraph/pull/18314)) :shipit:
  - [x] (🏁 19 days ago) dev: allow codeinsights-db more time to startup ([~#18359~](https://github.com/sourcegraph/sourcegraph/pull/18359)) :shipit:
  - [x] (🏁 19 days ago) insights: turn on for Sourcegraph.com ([~#18360~](https://github.com/sourcegraph/sourcegraph/pull/18360)) :shipit:
  - [x] (🏁 18 days ago) insights: fix job dequeueing (columns mismatch) ([~#18390~](https://github.com/sourcegraph/sourcegraph/pull/18390)) :shipit:
  - [x] (🏁 3 days ago) insights: backfill data ([~#18398~](https://github.com/sourcegraph/sourcegraph/issues/18398))
  - [x] (🏁 18 days ago) insights: query correct series data ([~#18401~](https://github.com/sourcegraph/sourcegraph/pull/18401)) :shipit:
  - [x] (🏁 17 days ago) insights: turn on in dev environments by default ([~#18458~](https://github.com/sourcegraph/sourcegraph/pull/18458)) :shipit:
  - [x] (🏁 17 days ago) insights: correctly query data even if metadata is not present ([~#18459~](https://github.com/sourcegraph/sourcegraph/pull/18459)) :shipit:
  - [x] (🏁 17 days ago) insights: store: always store data in UTC format ([~#18460~](https://github.com/sourcegraph/sourcegraph/pull/18460)) :shipit:
  - [x] (🏁 17 days ago) insights: store: add fast data existence check ([~#18461~](https://github.com/sourcegraph/sourcegraph/pull/18461)) :shipit:
  - [x] (🏁 16 days ago) internal/vcs/git: add ability to get first ever commit in a repository ([~#18463~](https://github.com/sourcegraph/sourcegraph/pull/18463)) :shipit:
  - [x] (🏁 16 days ago) insights: disable TimescaleDB telemetry ([~#18464~](https://github.com/sourcegraph/sourcegraph/pull/18464)) :shipit:
  - [x] (🏁 today) insights: 3.25 release checklist ([~#18465~](https://github.com/sourcegraph/sourcegraph/issues/18465))
  - [x] (🏁 16 days ago) insights: query data aggregated over 12h ([~#18506~](https://github.com/sourcegraph/sourcegraph/pull/18506)) :shipit:
  - [x] (🏁 12 days ago) insights: backend: possible double-inserts (over-reporting) if container restarts happen frequently ([~#18510~](https://github.com/sourcegraph/sourcegraph/issues/18510))
  - [x] (🏁 16 days ago) insights: enable in all production deployments ([~#18515~](https://github.com/sourcegraph/sourcegraph/pull/18515)) :shipit:
  - [x] (🏁 16 days ago) insights: ensure search queries run with a large count: ([~#18518~](https://github.com/sourcegraph/sourcegraph/pull/18518)) :shipit:
  - [x] (🏁 16 days ago) insights: default to 90d display; improve handling of forked/archived repos ([~#18519~](https://github.com/sourcegraph/sourcegraph/pull/18519)) :shipit:

Completed
- [x] (🏁 54 days ago) internal/db: generate separate schema.md files for codeintel and frontend DBs ([~#17228~](https://github.com/sourcegraph/sourcegraph/pull/17228)) :shipit:
- [x] (🏁 47 days ago) docker-images: tag TimescaleDB as sourcegraph/codeinsights-db ([~#17427~](https://github.com/sourcegraph/sourcegraph/pull/17427)) :shipit:
- [x] (🏁 40 days ago) internal/db: do not run TimescaleDB migrations against singleton database ([~#17585~](https://github.com/sourcegraph/sourcegraph/pull/17585)) :shipit:
- [x] (🏁 40 days ago) code insights: add Postgres migrations foundation ([~#17219~](https://github.com/sourcegraph/sourcegraph/issues/17219); PRs: ~[#17432](https://github.com/sourcegraph/sourcegraph/pull/17432)~, ~[#17586](https://github.com/sourcegraph/sourcegraph/pull/17586)~, ~[#17588](https://github.com/sourcegraph/sourcegraph/pull/17588)~)
- [x] (🏁 40 days ago) Revert "insights: execute database migrations (#17586)" ([~#17701~](https://github.com/sourcegraph/sourcegraph/pull/17701)) :shipit:
- [x] (🏁 39 days ago) dev/ci: do *not* run e2e sourcegraph/server tests with DEPLOY_TYPE=dev ([~#17731~](https://github.com/sourcegraph/sourcegraph/pull/17731)) :shipit:
- [x] (🏁 39 days ago) Revert "Revert "insights: execute database migrations (#17586)" (#17701)" ([~#17732~](https://github.com/sourcegraph/sourcegraph/pull/17732)) :shipit:
- [x] (🏁 39 days ago) code insights: deploy TimescaleDB in dev and CI environments ([~#17226~](https://github.com/sourcegraph/sourcegraph/issues/17226); PRs: ~[#17431](https://github.com/sourcegraph/sourcegraph/pull/17431)~, ~[#17733](https://github.com/sourcegraph/sourcegraph/pull/17733)~)
- [x] (🏁 39 days ago) code insights: add dev option to disable code insights backend entirely ([~#17738~](https://github.com/sourcegraph/sourcegraph/pull/17738)) :shipit:
- [x] (🏁 39 days ago) code insights: fully qualify Postgres DSN to avoid conflicts ([~#17742~](https://github.com/sourcegraph/sourcegraph/pull/17742)) :shipit:
- [x] (🏁 39 days ago) dev: give codeinsights-db more time to start ([~#17744~](https://github.com/sourcegraph/sourcegraph/pull/17744)) :shipit:
- [x] (🏁 37 days ago) code insights: improve backend testing experience ([~#17843~](https://github.com/sourcegraph/sourcegraph/pull/17843)) :shipit:
- [x] (🏁 37 days ago) insights: skip integration tests if DB unavailable in dev environments ([~#17861~](https://github.com/sourcegraph/sourcegraph/pull/17861)) :shipit:
- [x] (🏁 34 days ago) code insights: add new GraphQL schema ([~#17842~](https://github.com/sourcegraph/sourcegraph/pull/17842)) :shipit:
- [x] (🏁 34 days ago) code insights: add new user/org/global settings schema ([~#17844~](https://github.com/sourcegraph/sourcegraph/pull/17844)) :shipit:
- [x] (🏁 30 days ago) insights: split out DB testing setup code into separate package ([~#18001~](https://github.com/sourcegraph/sourcegraph/pull/18001)) :shipit:
- [x] (🏁 28 days ago) insights: add very basic GraphQL resolver integration test ([~#18035~](https://github.com/sourcegraph/sourcegraph/pull/18035)) :shipit:
- [x] (🏁 27 days ago) code insights: add experimental GraphQL API ([~#17221~](https://github.com/sourcegraph/sourcegraph/issues/17221); PRs: ~[#17497](https://github.com/sourcegraph/sourcegraph/pull/17497)~, ~[#18075](https://github.com/sourcegraph/sourcegraph/pull/18075)~)
- [x] (🏁 26 days ago) insights: add initial DB schema ([~#18083~](https://github.com/sourcegraph/sourcegraph/pull/18083)) :shipit:
- [x] (🏁 26 days ago) insights: add & prepare to use generated store mocks ([~#18118~](https://github.com/sourcegraph/sourcegraph/pull/18118)) :shipit:
- [x] (🏁 26 days ago) insights: store: add support for querying series data points ([~#18129~](https://github.com/sourcegraph/sourcegraph/pull/18129)) :shipit:
- [x] (🏁 26 days ago) insights: resolvers: implement point querying & add integration tests ([~#18130~](https://github.com/sourcegraph/sourcegraph/pull/18130)) :shipit:
- [x] (🏁 23 days ago) insights: change series_id to string (hash); add index ([~#18230~](https://github.com/sourcegraph/sourcegraph/pull/18230)) :shipit:
- [x] (🏁 20 days ago) insights: store: query metadata & other minor improvements ([~#18254~](https://github.com/sourcegraph/sourcegraph/pull/18254)) :shipit:
- [x] (🏁 20 days ago) insights: store: add support for recording data points ([~#18255~](https://github.com/sourcegraph/sourcegraph/pull/18255)) :shipit:
- [x] (🏁 20 days ago)  insights: add new discovery package for locating insights (and use it) ([~#18264~](https://github.com/sourcegraph/sourcegraph/pull/18264)) :shipit:
- [x] (🏁 20 days ago) migrations: add insights_query_runner_jobs table ([~#18265~](https://github.com/sourcegraph/sourcegraph/pull/18265)) :shipit:
- [x] (🏁 19 days ago) add codeinsights-db (TimescaleDB) deployment ([~#1851~](https://github.com/sourcegraph/deploy-sourcegraph/pull/1851)) :shipit:
- [x] (🏁 19 days ago) sourcegraph/deploy-sourcegraph-dot-com ([~#4599~](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/4599)) :shipit:
- [x] (🏁 19 days ago) insights: set POSTGRES_PASSWORD ([~#1856~](https://github.com/sourcegraph/deploy-sourcegraph/pull/1856)) :shipit:
- [x] (🏁 19 days ago) sourcegraph/deploy-sourcegraph-dot-com ([~#4600~](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/4600)) :shipit:
- [x] (🏁 19 days ago) insights: actually enqueue/record insights from global settings ([~#18314~](https://github.com/sourcegraph/sourcegraph/pull/18314)) :shipit:
- [x] (🏁 19 days ago) dev: allow codeinsights-db more time to startup ([~#18359~](https://github.com/sourcegraph/sourcegraph/pull/18359)) :shipit:
- [x] (🏁 19 days ago) sourcegraph/deploy-sourcegraph-dot-com ([~#4601~](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/4601)) :shipit:
- [x] (🏁 19 days ago) insights: turn on for Sourcegraph.com ([~#18360~](https://github.com/sourcegraph/sourcegraph/pull/18360)) :shipit:
- [x] (🏁 18 days ago) frontend: configure codeinsights DB env var ([~#1864~](https://github.com/sourcegraph/deploy-sourcegraph/pull/1864)) :shipit:
- [x] (🏁 18 days ago) insights: fix job dequeueing (columns mismatch) ([~#18390~](https://github.com/sourcegraph/sourcegraph/pull/18390)) :shipit:
- [x] (🏁 18 days ago) codeinsights-db: remove liveness/readiness probes ([~#1859~](https://github.com/sourcegraph/deploy-sourcegraph/pull/1859)) :shipit:
- [x] (🏁 18 days ago) code insights: deploy TimescaleDB in Kubernetes deployments ([~#17224~](https://github.com/sourcegraph/sourcegraph/issues/17224))
- [x] (🏁 18 days ago) insights: query correct series data ([~#18401~](https://github.com/sourcegraph/sourcegraph/pull/18401)) :shipit:
- [x] (🏁 17 days ago) insights: turn on in dev environments by default ([~#18458~](https://github.com/sourcegraph/sourcegraph/pull/18458)) :shipit:
- [x] (🏁 17 days ago) insights: correctly query data even if metadata is not present ([~#18459~](https://github.com/sourcegraph/sourcegraph/pull/18459)) :shipit:
- [x] (🏁 17 days ago) insights: store: always store data in UTC format ([~#18460~](https://github.com/sourcegraph/sourcegraph/pull/18460)) :shipit:
- [x] (🏁 17 days ago) insights: store: add fast data existence check ([~#18461~](https://github.com/sourcegraph/sourcegraph/pull/18461)) :shipit:
- [x] (🏁 16 days ago) insights: disable TimescaleDB telemetry ([~#18464~](https://github.com/sourcegraph/sourcegraph/pull/18464)) :shipit:
- [x] (🏁 16 days ago) internal/vcs/git: add ability to get first ever commit in a repository ([~#18463~](https://github.com/sourcegraph/sourcegraph/pull/18463)) :shipit:
- [x] (🏁 16 days ago) insights: query data aggregated over 12h ([~#18506~](https://github.com/sourcegraph/sourcegraph/pull/18506)) :shipit:
- [x] (🏁 16 days ago) insights: enable in all production deployments ([~#18515~](https://github.com/sourcegraph/sourcegraph/pull/18515)) :shipit:
- [x] (🏁 16 days ago) code insights: deploy TimescaleDB in docker-compose deployments ([~#17225~](https://github.com/sourcegraph/sourcegraph/issues/17225); PRs: ~[#259](https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/259)~)
- [x] (🏁 16 days ago) insights: ensure search queries run with a large count: ([~#18518~](https://github.com/sourcegraph/sourcegraph/pull/18518)) :shipit:
- [x] (🏁 16 days ago) insights: default to 90d display; improve handling of forked/archived repos ([~#18519~](https://github.com/sourcegraph/sourcegraph/pull/18519)) :shipit:
- [x] (🏁 12 days ago) insights: backend: possible double-inserts (over-reporting) if container restarts happen frequently ([~#18510~](https://github.com/sourcegraph/sourcegraph/issues/18510))
- [x] (🏁 4 days ago) dev: make drop-entire-db script also drop insights DB ([~#18081~](https://github.com/sourcegraph/sourcegraph/pull/18081)) :shipit:
- [x] (🏁 3 days ago) insights: backfill data ([~#18398~](https://github.com/sourcegraph/sourcegraph/issues/18398))
- [x] (🏁 today) insights: 3.25 release checklist ([~#18465~](https://github.com/sourcegraph/sourcegraph/issues/18465))
- [x] (🏁 today) code insights: document that it is not supported in sourcegraph/server demo deployments ([~#17222~](https://github.com/sourcegraph/sourcegraph/issues/17222); PRs: ~[#17735](https://github.com/sourcegraph/sourcegraph/pull/17735)~)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
