### ISSUE TITLE
Campaigns Sprint 9 Tracking issue

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#17337]
### Tracked issues

@LawnGnome

- [ ] campaigns: dead link on the create campaign page ([#17931](https://github.com/sourcegraph/sourcegraph/issues/17931); PRs: [#17936](https://github.com/sourcegraph/sourcegraph/pull/17936), ~[#17937](https://github.com/sourcegraph/sourcegraph/pull/17937)~) 🐛

@eseliger: __6.00d__

Completed: __6.00d__
- [x] (🏁 15 days ago) Remove unneeded call to ensureStore ([~#17524~](https://github.com/sourcegraph/sourcegraph/pull/17524)) :shipit:
- [x] (🏁 14 days ago) Fix detach not correctly executed when changeset is in failed state ([~#17526~](https://github.com/sourcegraph/sourcegraph/pull/17526)) :shipit:🐛
- [x] (🏁 14 days ago) Change 'Create new campaign' button label to 'Create campaign' ([~#17481~](https://github.com/sourcegraph/sourcegraph/issues/17481); PRs: ~[#17527](https://github.com/sourcegraph/sourcegraph/pull/17527)~)
- [x] (🏁 14 days ago) Fix empty RewirerMappings.Hydrate being slow ([~#17525~](https://github.com/sourcegraph/sourcegraph/pull/17525)) :shipit:🐛
- [x] (🏁 14 days ago) campaigns: fix changeset count calculation ([~#16781~](https://github.com/sourcegraph/sourcegraph/issues/16781)) __2.00d__
- [x] (🏁 14 days ago) Implement extended expand section on preview nodes ([~#17327~](https://github.com/sourcegraph/sourcegraph/pull/17327)) :shipit:
- [x] (🏁 14 days ago) Implement faster resolver for global campaign diff stat ([~#17529~](https://github.com/sourcegraph/sourcegraph/pull/17529)) :shipit:
- [x] (🏁 11 days ago) Implement overhauled campaigns stats section ([~#17540~](https://github.com/sourcegraph/sourcegraph/pull/17540)) :shipit:
- [x] (🏁 11 days ago) Add commit changes column to campaigns preview UI ([~#17564~](https://github.com/sourcegraph/sourcegraph/pull/17564)) :shipit:
- [x] (🏁 11 days ago) campaigns: Cleanup some little things ([~#17608~](https://github.com/sourcegraph/sourcegraph/pull/17608)) :shipit:🧶
- [x] (🏁 9 days ago) Make superseding campaign spec dismissible ([~#17657~](https://github.com/sourcegraph/sourcegraph/pull/17657)) :shipit:
- [x] (🏁 9 days ago) Don't load all sync states when page slice is empty ([~#17707~](https://github.com/sourcegraph/sourcegraph/pull/17707)) :shipit:🐛
- [x] (🏁 9 days ago) Expose syncer errors in UI ([~#17610~](https://github.com/sourcegraph/sourcegraph/pull/17610)) :shipit:
- [x] (🏁 7 days ago) Fix loading all changeset events into memory when campaign is empty ([~#17710~](https://github.com/sourcegraph/sourcegraph/pull/17710)) :shipit:🐛
- [x] (🏁 7 days ago) Add tests for the changeset rewirer ([~#17719~](https://github.com/sourcegraph/sourcegraph/pull/17719)) :shipit:🧶
- [x] (🏁 7 days ago) Fix some golangci-lint errors in campaigns code ([~#17791~](https://github.com/sourcegraph/sourcegraph/pull/17791)) :shipit:🧶
- [x] (🏁 3 days ago) Add button to retry failed changeset ([~#17479~](https://github.com/sourcegraph/sourcegraph/issues/17479); PRs: ~[#17690](https://github.com/sourcegraph/sourcegraph/pull/17690)~, ~[#17834](https://github.com/sourcegraph/sourcegraph/pull/17834)~) __1.00d__
- [x] (🏁 2 days ago) Implement campaigns update UI design ([~#17110~](https://github.com/sourcegraph/sourcegraph/issues/17110); PRs: ~[#17894](https://github.com/sourcegraph/sourcegraph/pull/17894)~) __3.00d__

@mrnugget: __6.50d__

Completed: __6.50d__
- [x] (🏁 16 days ago) Create a "How to handle errored changesets” doc page ([~#17359~](https://github.com/sourcegraph/sourcegraph/issues/17359)) __0.50d__
- [x] (🏁 4 days ago) Link to troubleshooting docs when src-cli outputs an error that's not a step-failed-with-non-zero-exit-code error ([~#17259~](https://github.com/sourcegraph/sourcegraph/issues/17259)) __1.00d__
- [x] (🏁 3 days ago) Explore ways to run campaign spec steps in "workspaces" of a single repository ([~#17367~](https://github.com/sourcegraph/sourcegraph/issues/17367)) __5.00d__ 🕵️

@rrhyne: __1.50d__

Completed: __1.50d__
- [x] (🏁 2 days ago) Changeset filter design ([~#16780~](https://github.com/sourcegraph/sourcegraph/issues/16780)) __1.50d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
