### ISSUE TITLE
Distribution: 2021.01.25 - Sleepy Termite

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#17604]
#### [Seamless Upgrades](https://github.com/orgs/sourcegraph/projects/71?card_filter_query=milestone%3A%22dist%3A+2021.01.25%22)

We have two distinct objectives for this sprint:
- Build all remaining components.
- Migrate dotcom to the new deployment method.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@unassigned

- [ ] dhall: implement prometheus ([#17640](https://github.com/sourcegraph/sourcegraph/issues/17640))
- [ ] dhall: implement cadvisor ([#17633](https://github.com/sourcegraph/sourcegraph/issues/17633))

Completed
- [x] (🏁 9 days ago) dhall: implement searcher ([~#17642~](https://github.com/sourcegraph/sourcegraph/issues/17642))
- [x] (🏁 5 days ago) dhall: implement indexed-search ([~#17636~](https://github.com/sourcegraph/sourcegraph/issues/17636))
- [x] (🏁 5 days ago) dhall: implement jaeger ([~#17637~](https://github.com/sourcegraph/sourcegraph/issues/17637))
- [x] (🏁 4 days ago) dhall: implement syntect-server ([~#17643~](https://github.com/sourcegraph/sourcegraph/issues/17643))

@bobheadxi

- [ ] ~monitoring: alert solutions should link to versioned documentation~ ([#17598](https://github.com/sourcegraph/sourcegraph/issues/17598))

Completed
- [x] (🏁 13 days ago) document distribution forks ([~#17498~](https://github.com/sourcegraph/sourcegraph/issues/17498))
- [x] (🏁 12 days ago) monitoring: some observables end up with multiple metrics ([~#17599~](https://github.com/sourcegraph/sourcegraph/issues/17599)) 🐛
- [x] (🏁 10 days ago) prom-wrapper: introduce src-prometheus, migrate alerts history ([~#17602~](https://github.com/sourcegraph/sourcegraph/pull/17602)) :shipit:

@davejrt: __1.00d__

- [ ] sourcegraph/customer ([#177](https://github.com/sourcegraph/customer/issues/177)) 👩
- [ ] upgrade prevented with obscure errors due to null env lists in k8s YAML / indention errors ([#11754](https://github.com/sourcegraph/sourcegraph/issues/11754)) 🐛

Completed: __1.00d__
- [x] (🏁 11 days ago) 3.24.0 upgrade managed instance tracking issue ([~#17173~](https://github.com/sourcegraph/sourcegraph/issues/17173))
- [x] (🏁 5 days ago) monitoring: panel API redux tracking issue ([~#16697~](https://github.com/sourcegraph/sourcegraph/issues/16697))
- [x] (🏁 2 days ago) release: the release tooling for managed instances doesn't add the correct compose file ([~#17954~](https://github.com/sourcegraph/sourcegraph/issues/17954)) __1.00d__

@daxmc99: __0.50d__

- [ ] dhall: implement precise-code-intel ([#17639](https://github.com/sourcegraph/sourcegraph/issues/17639))
- [ ] ~Kubernetes database restoration docs missing?~ ([#17857](https://github.com/sourcegraph/sourcegraph/issues/17857)) 🐛

Completed: __0.50d__
- [x] (🏁 9 days ago) Tracking issue: Dhall test components ([~#16796~](https://github.com/sourcegraph/sourcegraph/issues/16796)) __0.50d__

@ggilmore

- [ ] dhall: implement codeintel-db ([#17634](https://github.com/sourcegraph/sourcegraph/issues/17634))

@pecigonzalo: __0.50d__

- [ ] ~monitoring: alert solutions should link to versioned documentation~ ([#17598](https://github.com/sourcegraph/sourcegraph/issues/17598))

Completed: __0.50d__
- [x] (🏁 12 days ago) sourcegraph/customer ([~#180~](https://github.com/sourcegraph/customer/issues/180)) 👩
- [x] (🏁 11 days ago) Add handbook documentation for adding unplanned items to an iteration ([~#16674~](https://github.com/sourcegraph/sourcegraph/issues/16674)) __0.50d__
- [x] (🏁 10 days ago) Patch release: Fix SAML validation error ([~#17772~](https://github.com/sourcegraph/sourcegraph/issues/17772))
- [x] (🏁 10 days ago) Multiple runs of automerge for each opened PR ([~#17756~](https://github.com/sourcegraph/sourcegraph/issues/17756)) 🐛
- [x] (🏁 8 days ago) Problem with Sourcegraph quickstart guide on Linux Elementary OS  ([~#17691~](https://github.com/sourcegraph/sourcegraph/issues/17691))
- [x] (🏁 2 days ago) dhall: implement minio  ([~#17638~](https://github.com/sourcegraph/sourcegraph/issues/17638))

@uwedeportivo: __6.50d__

- [ ] sourcegraph/customer ([#183](https://github.com/sourcegraph/customer/issues/183)) 👩
- [ ] sourcegraph/customer ([#149](https://github.com/sourcegraph/customer/issues/149)) __2.00d__ 👩
- [ ] sourcegraph/customer ([#159](https://github.com/sourcegraph/customer/issues/159)) __1.00d__ 👩
- [ ] sourcegraph/customer ([#160](https://github.com/sourcegraph/customer/issues/160)) __1.00d__ 👩
- [ ] prometheus: job label for frontend is different in different deployments ([#16552](https://github.com/sourcegraph/sourcegraph/issues/16552)) 🎩
- [ ] Tracking issue: Use CI on sourcegraph.com with Dhall ([#13340](https://github.com/sourcegraph/sourcegraph/issues/13340)) __1.00d__
  - [ ] ~add deploy-sourcegraph-dhall pipeline to deploy-sourcegraph-dot-com~ ([#14132](https://github.com/sourcegraph/sourcegraph/issues/14132)) __1.00d__
- [ ] dhall: implement frontend  ([#17635](https://github.com/sourcegraph/sourcegraph/issues/17635))

Completed: __1.50d__
- [x] (🏁 5 days ago) upgrade deploy-sourcegraph-dhall implementation to latest deploy-sourcegraph commits  ([~#17632~](https://github.com/sourcegraph/sourcegraph/issues/17632))
- [x] (🏁 4 days ago) dhall: implement redis ([~#17641~](https://github.com/sourcegraph/sourcegraph/issues/17641)) __1.50d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
