### ISSUE TITLE
Transition to new structural search path

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#17616]
### Plan

This is a tracking issue for refactoring structural search to be performant for large monorepos.

High level plan:
- [x] Move Zoekt querying to `searcher` behind a flag
- [x] Test current performance and stability for large for large monorepos
- [x] Make new code path default (#17846)
- [x] Remove old path https://github.com/sourcegraph/sourcegraph/pull/19434

### Tracked issues

- [x] Avoid building file list just for matching (#17569)
- [x] Support searching non-HEAD indexed branches (#17493)
- [ ] ~~Use cached zip when possible (#17694)~~

### Related
- [ ] Stream Zoekt results so the full result set isn't in memory  (#17494)
- [x] Unindexed structural search (#12348, also #8164)
- [x] Disentangle structural search from zoekt search (#11902)
- [ ] Make structural search independent of other search types (#17496, 7241c1e)

**Comment by camdencheek** [comment]
# Performance/stability test plan
​
Run test matrix for performance/stability, then do some exploratory testing comparing old and new results under different situations.
​
Matrix:
- Code paths:
  - old
  - new
- Platforms:
  - local
  - k8s
- Repo size:
  - small (sgtest/sourcegraph-typescript) 
  - large (torvalds/linux)
  - very large (TBD)
- Result set size:
  - small (~5 results)
  - large (~1000 results)
  - absurd (~20000 results)
- Query rate:
  - 1 query (hot)
  - 1 query (cold)
  - 1 query per second
  - 10 query per second
  - 100 query per second
​
Measure:
- Query latency
- Peak memory usage (pprof)
- Transferred bytes (prometheus metric?)
​
​
Exploratory testing focuses:
- Filters
- Interaction with streaming search
- Many results, few files
​
​
Notes:
- Can theoretically skip streaming file contents if the repo already exists locally. Maybe spin off background task to

**Comment by camdencheek** [comment]
Performance testing results here: https://github.com/camdencheek/query-performance-testing

**Comment by camdencheek** [comment]
Closing since the old structural search path no longer exists
