### ISSUE TITLE
RFC 215: Improving User Feedback Tracking issue

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#17650]
Tracks all the issues connected to [RFC 215](https://docs.google.com/document/d/1mn3AxOMLM_ivu-mfWa3VAXyJnmX4WFInREdB2kI_g6o/edit?usp=sharing) 'Improving user feedback channels'

### Tracked issues

@5h1rU

Completed
- [x] (🏁 6 days ago) Frontend: Add feedback trigger to nav bar ([~#17644~](https://github.com/sourcegraph/sourcegraph/issues/17644))
- [x] (🏁 4 days ago) Frontend: Implement omnipresent feedback widget ([~#17645~](https://github.com/sourcegraph/sourcegraph/issues/17645))

@ebrodymoore

Completed
- [x] (🏁 28 days ago) BizOps: Finalize where feedback widget data should be stored ([~#17652~](https://github.com/sourcegraph/sourcegraph/issues/17652))
- [x] (🏁 21 days ago) Frontend: Add "Product research and feedback" page to user settings ([~#17646~](https://github.com/sourcegraph/sourcegraph/issues/17646))
- [x] (🏁 15 days ago) BizOps: Handle data from feedback widget ([~#17651~](https://github.com/sourcegraph/sourcegraph/issues/17651))

@umpox

Completed
- [x] (🏁 27 days ago) Frontend: Create reusable text-based in-context feedback component ([~#17648~](https://github.com/sourcegraph/sourcegraph/issues/17648))
- [x] (🏁 21 days ago) Frontend: Add "Product research and feedback" page to user settings ([~#17646~](https://github.com/sourcegraph/sourcegraph/issues/17646))
- [x] (🏁 21 days ago) Allow admins to disable "Product research and feedback" for users on their instance ([~#17647~](https://github.com/sourcegraph/sourcegraph/issues/17647))
- [x] (🏁 4 days ago) Frontend: Implement omnipresent feedback widget ([~#17645~](https://github.com/sourcegraph/sourcegraph/issues/17645))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by umpox** [comment]
For this should be able to rework `<StatusBadge />` a little from https://github.com/sourcegraph/sourcegraph/pull/17521

**Comment by umpox** [comment]
@quinnkeast We're keen to get started on this. Do we have any mobile/tablet designs?

**Comment by umpox** [comment]
@5h1rU Note: We can probably feature flag this work so we can progress with merging PRs if we are blocked

**Comment by umpox** [comment]
Potential PRs:
- Feedback button in Nav
- Feedback widget in design system
- Product feedback settings page
- Update to Breaders share feedback work

**Comment by quinnkeast** [comment]
> @quinnkeast We're keen to get started on this. Do we have any mobile/tablet designs?

Smaller screens can be [seen on Figma now](https://www.figma.com/file/9FprSCL6roIZotcWMvJZuE/Improving-user-feedback-channels?node-id=792%3A0).

I would not show the button altogether at true mobile sizes: the overall UI is highly compromised at that viewport size, and I don't think the feedback button will be meaningful to us in that size.

**Comment by ebrodymoore** [comment]
@5h1rU and @umpox - for clarity, I'm responsible for everything once the form submissions hit HubSpot (such as getting the data into productboard, Slack and Looker). All you need to do is make sure the submissions get to HubSpot! cc @AlicjaSuska who had a question on this

**Comment by umpox** [comment]
@ebrodymoore @quinnkeast Where does this piece of work leave the [current feedback page](https://sourcegraph.com/survey)? We currently have functionality to only send data to that HubSpot form, if we want to support _both_ forms, we will need to update the backend logic

**Comment by quinnkeast** [comment]
> @ebrodymoore @quinnkeast Where does this piece of work leave the [current feedback page](https://sourcegraph.com/survey)? We currently have functionality to only send data to that HubSpot form, if we want to support _both_ forms, we will need to update the backend logic

I believe this should remain as-is, as it's tied to the NPS survey / feedback. The new feedback widget shouldn't affect or change the current NPS feedback.

**Comment by umpox** [comment]
We can close this now 🎉
