### ISSUE TITLE
3.25.0 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#17728]
# 3.25.25 managed instances upgrade

These [managaged instances](https://about.sourcegraph.com/handbook/engineering/distribution/managed) upgrades are scheduled for **[Feb 21, 2021, 6:00 PM (UTC)](https://time.is/1800_21_Feb_2021_in_UTC?One%20working%20day%20after%203.25%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](https://about.sourcegraph.com/handbook/engineering/distribution/managed/upgrade_process).

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com)

## Upgrade customer managed instances

- [x] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/1712860829](https://app.hubspot.com/contacts/2762526/company/1712860829/)

---

Also see [3.25 release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/17727)
