### ISSUE TITLE
3.25 release tracking issue

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#17727]
# 3.25 release

This release is scheduled for **[Feb 20, 2021, 6:00 PM (UTC)](https://time.is/1800_20_Feb_2021_in_UTC?3.25%20release%20date)**.

---

## Setup

- [x] Ensure release configuration in [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) on `main` is up to date with the parameters for the current release.
- [x] Ensure you have the latest version of the release tooling and configuration by checking out and updating `sourcegraph@main`.

## Prepare release

- [x] Post a release status update to Slack - review all release-blocking issues, and ensure someone is resolving each.
  ```sh
  yarn release release:status
  ```

Do the [branch cut](https://about.sourcegraph.com/handbook/engineering/releases#release-branches) for the release:

- [x] Update the changelog and merge the generated pull request:
  ```sh
  yarn release changelog:cut
  ```
- [x] Create the `3.25` branch off the CHANGELOG commit in the previous step:
  ```sh
  git branch 3.25 && git push origin 3.25
  ```

Upon branch cut, create and test release candidates:

- [x] Tag the first release candidate:
  ```sh
  N=1 yarn release release:create-candidate $N
  ```
- [x] Wait for the [Sourcegraph pipeline](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=3.25), [QA pipeline](https://buildkite.com/sourcegraph/qa/builds?branch=3.25), and [E2E pipeline](https://buildkite.com/sourcegraph/e2e/builds?branch=3.25) in Buildkite to complete.
- [x] File any failures and regressions in the pipelines as `release-blocker` issues and assign the appropriate teams.

Revert or disable features that may cause delays. As necessary, `git cherry-pick` bugfix (not feature!) commits from `main` into the release branch. Continue to create new release candidates as necessary, until no more `release-blocker` issues remain.

- [x] Post a release status update to Slack:
  ```sh
  yarn release release:status
  ``` 

## Stage release

Once there are no more release-blocking issues (as reported by the `release:status` command) proceed with creating the final release:

- [x] Verify the [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) on `main` and `3.25` are accurate.
- [x] Tag the final release:
  ```sh
  yarn release release:create-candidate final
  ```
- [x] Ensure the [Sourcegraph pipeline](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=3.25), [QA pipeline](https://buildkite.com/sourcegraph/qa/builds?branch=3.25), and [E2E pipeline](https://buildkite.com/sourcegraph/e2e/builds?branch=3.25) in Buildkite passes, and for the release Docker images to be available in [Docker Hub](https://hub.docker.com/r/sourcegraph/server/tags).
- [x] Open PRs that publish the new release and address any action items required to finalize draft PRs (track PR status via the [generated release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns)):
  ```sh
  yarn release release:stage
  ```

## Finalize release

- [x] From the [release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns), merge the release-publishing PRs created previously.
  - For [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph), also:
    - [x] Tag the `v3.25.0` release at the most recent commit on the `v3.25` branch.
        ```sh
        VERSION='v3.25.0' bash -c 'git tag -a "$VERSION" -m "$VERSION" && git push origin "$VERSION"'
        ```
  - For [sourcegraph](https://github.com/sourcegraph/sourcegraph), also:
    - [x] Cherry pick the release-publishing PR from `sourcegraph/sourcegraph@main` into the release branch.
- [x] Ask the product team (`#product`) to merge the blog post. Add the pull request to the release campaign:
  ```sh
  yarn release release:add-to-campaign sourcegraph/about <pr-number>
  ```
- [x] Finalize and announce that the release is live:
  ```sh
  yarn release release:close
  ```

## Post-release

Notify the next [release captain](https://about.sourcegraph.com/handbook/engineering/releases#release-captain) that they are on duty for the next release. They should complete the steps in this section.

- [x] Open a PR to update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the parameters for the current release.
- [x] Ensure you have the latest version of the release tooling and configuration by checking out and updating `sourcegraph@main`.
- [x] Create release calendar events, tracking issue, and announcement for next release:
  ```sh
  yarn run release tracking:issues
  yarn run release tracking:timeline
  ```
- [x] Close this issue.

**Note:** If a patch release is requested after the release, ask that a [patch request issue](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=&labels=team%2Fdistribution&template=request_patch_release.md&title=3.25.1%3A+) be filled out and approved first.

**Comment by davejrt** [comment]
*Sourcegraph 3.25.0 has been published*

* Changelog: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#3-25-0
* Release campaign: https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.25.0

@davejrt: Please complete the post-release steps before closing this issue.
