### ISSUE TITLE
3.24.1 patch release tracking issue

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#17770]
# 3.24.1 patch release

This release is scheduled for **[Jan 28, 2021, 6:00 PM (UTC)](https://time.is/1800_28_Jan_2021_in_UTC?3.24.1%20release%20date)**.

> **Attention developers:** to get your commits in `main` included in this patch release, please file a [patch request](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=&labels=team%2Fdistribution&template=request_patch_release.md&title=3.24.1%3A+) for review.
>
> Only check off items if relevant commits across the following repositories have been cherry-picked into the relevant `3.24` branch by the release captain:
>
> - `sourcegraph/sourcegraph`
> - `sourcegraph/deploy-sourcegraph`
> - `sourcegraph/deploy-sourcegraph-docker`

- https://github.com/sourcegraph/sourcegraph/issues/17772 - https://github.com/sourcegraph/sourcegraph/commit/6e0746c0f161b8a99d854a69a0727ad58e2c741b

## Setup

- [x] Ensure release configuration in [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) on `main` is up to date with the parameters for the current release.
- [x] Ensure you have the latest version of the release tooling and configuration by checking out and updating `sourcegraph@main`.

## Prepare release

Ensure that all [patch request issues](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Apatch-release-request) are accounted for, and have all relevant commits across relevant repositories listed above in the checklist.

For each of the following repositories, cherry-pick (see snippet below) and check off commits listed above.

- [x] `sourcegraph/sourcegraph` ([`3.24` release branch](https://github.com/sourcegraph/sourcegraph/tree/3.24))
- [x] `sourcegraph/deploy-sourcegraph` ([`3.24` release branch](https://github.com/sourcegraph/deploy-sourcegraph/tree/3.24))
- [x] `sourcegraph/deploy-sourcegraph-docker` ([`3.24` release branch](https://github.com/sourcegraph/deploy-sourcegraph-docker/tree/3.24))

```sh
git checkout 3.24
git pull
git cherry-pick <commit0> <commit1> ... # all relevant commits from the default branch
git push 3.24
```

- [x] Ensure CI passes on all release branches listed above.

Create and test the first release candidate:

- [x] Push a release candidate tag:
    ```sh
    N=1 yarn release release:create-candidate $N
    ```
- [x] Ensure the [Sourcegraph pipeline](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=3.24), [QA pipeline](https://buildkite.com/sourcegraph/qa/builds?branch=3.24), and [E2E pipeline](https://buildkite.com/sourcegraph/e2e/builds?branch=3.24) in Buildkite passes.
- [x] File any failures and regressions in the pipelines as `release-blocker` issues and assign the appropriate teams.

## Stage release

- [x] Verify the [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) on `main` and `3.24` are accurate.
- [x] Tag the final release:
    ```sh
    yarn release release:create-candidate final
    ```
- [x] Ensure the [Sourcegraph pipeline](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=3.24), [QA pipeline](https://buildkite.com/sourcegraph/qa/builds?branch=3.24), and [E2E pipeline](https://buildkite.com/sourcegraph/e2e/builds?branch=3.24) in Buildkite passes, and for the release Docker images to be available in [Docker Hub](https://hub.docker.com/r/sourcegraph/server/tags).
- [x] Open PRs that publish the new release and address any action items required to finalize draft PRs (track PR status via the [generated release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns)):
  ```sh
  yarn release release:stage
  ```

## Finalize release

- [x] From the [release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns), merge the release-publishing PRs created previously.
  - For [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph), also:
    - [x] Tag the `v3.24.0` release at the most recent commit on the `v3.24` branch.
        ```sh
        VERSION='v3.24.0' bash -c 'git tag -a "$VERSION" -m "$VERSION" && git push origin "$VERSION"'
        ```
  - For [sourcegraph](https://github.com/sourcegraph/sourcegraph), also:
    - [x] Cherry pick the release-publishing PR from `sourcegraph/sourcegraph@main` into the release branch.
- [x] Finalize and announce that the release is live:
  ```sh
  yarn release release:close
  ```

## Post-release

- [x] Open a PR to update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the parameters for the current release.
- [x] Ensure you have the latest version of the release tooling and configuration by checking out and updating `sourcegraph@main`.
- [x] Close this issue.

**Note:** If another patch release is requested after the release, ask that a [patch request issue](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=&labels=team%2Fdistribution&template=request_patch_release.md) be filled out and approved first.

**Comment by pecigonzalo** [comment]
*Sourcegraph 3.24.1 has been published*

* Changelog: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#3-24-1
* Release campaign: https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.24.1

@pecigonzalo: Please complete the post-release steps before closing this issue.
