### ISSUE TITLE
3.24.1 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#17771]
# 3.24.1 managed instances upgrade

These [managed instances](https://about.sourcegraph.com/handbook/engineering/distribution/managed) upgrades are scheduled for **[Jan 28, 2021, 6:00 PM (UTC)](https://time.is/1800_28_Jan_2021_in_UTC?One%20working%20day%20after%203.24.1%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](https://about.sourcegraph.com/handbook/engineering/distribution/managed/upgrade_process).

---

## Upgrade internal managed instances

- [ ] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [ ] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com)

## Upgrade customer managed instances

- [ ] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/1712860829](https://app.hubspot.com/contacts/2762526/company/1712860829/)

---

Also see [3.24.1 patch release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/17770)
