### ISSUE TITLE
Security: Vulnerability Scanning Tracking issue

### ISSUE THREAD

**Issue by andreeleuterio** [sourcegraph/sourcegraph#17838]
### Plan

Tracks all the issues related to [vulnerability scanning](https://sourcegraph.productboard.com/feature-board/2119755-cloud/features/5982381/detail) as part of the larger goal of enabling [private code on Sourcegraph Cloud](https://about.sourcegraph.com/company/goals#private-code-on-sourcegraph-cloud).

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/17851 

@andreeleuterio

- [ ] https://github.com/sourcegraph/sourcegraph/issues/17839  🛠️   🏳️ [Security: Vulnerability Scanning](https://github.com/sourcegraph/sourcegraph/milestone/92)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/17847 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/17848 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
