### ISSUE TITLE
Security: Infrastructure vulnerability scanning

### ISSUE THREAD

**Issue by andreeleuterio** [sourcegraph/sourcegraph#17839]
[Scanning our infrastructure for vulnerabilities](https://sourcegraph.productboard.com/feature-board/2119755-cloud/features/5989076/detail) is part of the larger goal of enabling private code on Sourcegraph Cloud. The goal is deploying a tool to scan our servers for vulnerabilities. [Tennable Nessus](https://www.tenable.com/products/nessus/nessus-professional) is likely the way to go here.

Acceptance criteria:

- [ ] We have a list of servers to scan and process in place to keep it updated.
- [ ] We have deployed the tool of choice to scan our servers periodically and store the results.
- [ ] We have a process and documentation for analyzing results and taking action on finds.
