### ISSUE TITLE
Code Intelligence Sprint 5 Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#17853]
### Plan

This sprint covers 2020-02-01 through 2020-01-12.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

Eric: 10d
Noah: 10d
Garo: 6d
Owen: 8d
Olaf: 10d
Maria: 10d
TJ: 10d

### Tracked issues

@Strum355

- [ ] Cross-language API/IDL support (GraphQL, Thrift, Protobuf) ([#981](https://github.com/sourcegraph/sourcegraph/issues/981))
- [ ] ~Failed LSIF uploads not reflected in uploads UI~ ([#18188](https://github.com/sourcegraph/sourcegraph/issues/18188)) 🐛

Completed
- [x] (🏁 18 days ago) Improve debuggability ([~#27~](https://github.com/sourcegraph/lsif-clang/issues/27))
- [x] (🏁 18 days ago) Emit stacktrace on segfault with instructions for core-dump only scenarios ([~#32~](https://github.com/sourcegraph/lsif-clang/pull/32)) :shipit:
- [x] (🏁 13 days ago) introduce documentation to aid users in the case of a segfault ([~#43~](https://github.com/sourcegraph/lsif-clang/pull/43)) :shipit:
- [x] (🏁 12 days ago) WIP: Documenting lsif-java ft. minor refactorings ([~#83~](https://github.com/sourcegraph/lsif-java/pull/83)) :shipit:
- [x] (🏁 12 days ago) cross-package type alias definitions have self-referencing semantic definition results ([~#130~](https://github.com/sourcegraph/lsif-go/issues/130); PRs: ~[#131](https://github.com/sourcegraph/lsif-go/pull/131)~) 🐛

@efritz

- [ ] Remove long-running transactions from dbworker ([#14920](https://github.com/sourcegraph/sourcegraph/issues/14920))
- [ ] blog: Write about the code intelligence commit graph optimization effort ([#17379](https://github.com/sourcegraph/sourcegraph/issues/17379))

Completed
- [x] (🏁 19 days ago) Search-based code intel hovers are broken when definition token and docstring are separated by multiple lines ([~#17925~](https://github.com/sourcegraph/sourcegraph/issues/17925); PRs: ~[#567](https://github.com/sourcegraph/code-intel-extensions/pull/567)~)
- [x] (🏁 18 days ago) Add clarity to MinIO credential settings ([~#16412~](https://github.com/sourcegraph/sourcegraph/issues/16412); PRs: ~[#17965](https://github.com/sourcegraph/sourcegraph/pull/17965)~)
- [x] (🏁 17 days ago) codeintel: Ensure txn is used for bulk inserts ([~#18020~](https://github.com/sourcegraph/sourcegraph/pull/18020)) :shipit:
- [x] (🏁 12 days ago) cross-package type alias definitions have self-referencing semantic definition results ([~#130~](https://github.com/sourcegraph/lsif-go/issues/130); PRs: ~[#131](https://github.com/sourcegraph/lsif-go/pull/131)~) 🐛
- [x] (🏁 10 days ago) UI: Fix cache key for document highlights ([~#17997~](https://github.com/sourcegraph/sourcegraph/pull/17997)) :shipit:
- [x] (🏁 10 days ago) Fix pings for lsif WAUs ([~#17923~](https://github.com/sourcegraph/sourcegraph/issues/17923); PRs: ~[#17959](https://github.com/sourcegraph/sourcegraph/pull/17959)~)
- [x] (🏁 10 days ago) chore: Add correct size hints when making slices ([~#18211~](https://github.com/sourcegraph/sourcegraph/pull/18211)) :shipit:
- [x] (🏁 10 days ago) chore: Fix order of driver.Value declarations in dbutil ([~#18212~](https://github.com/sourcegraph/sourcegraph/pull/18212)) :shipit:
- [x] (🏁 10 days ago) chore: Distinguish stores in error messages ([~#18213~](https://github.com/sourcegraph/sourcegraph/pull/18213)) :shipit:
- [x] (🏁 10 days ago) chore: Update bloom filter package interface ([~#18223~](https://github.com/sourcegraph/sourcegraph/pull/18223)) :shipit:
- [x] (🏁 10 days ago) codeintel: Add GetDumpsByIDs to dbstore ([~#18214~](https://github.com/sourcegraph/sourcegraph/pull/18214)) :shipit:
- [x] (🏁 10 days ago) codeintel: Add BulkMonikerResults to lsifstore ([~#18217~](https://github.com/sourcegraph/sourcegraph/pull/18217)) :shipit:
- [x] (🏁 10 days ago) codeintel: Standardize limit/offset parameters in lsifstore ([~#18218~](https://github.com/sourcegraph/sourcegraph/pull/18218)) :shipit:
- [x] (🏁 10 days ago) codeintel: Add DefinitionDumps and ReferenceIDsAndFilters to dbstore ([~#18221~](https://github.com/sourcegraph/sourcegraph/pull/18221)) :shipit:
- [x] (🏁 10 days ago) codeintel: Add PagedReferences to lsifstore ([~#18215~](https://github.com/sourcegraph/sourcegraph/pull/18215)) :shipit:
- [x] (🏁 10 days ago) codeintel: Do not return nil scanner ([~#18226~](https://github.com/sourcegraph/sourcegraph/pull/18226)) :shipit:
- [x] (🏁 3 days ago) codeintel: Remove dead code (api package, dbstore, lsifstore) ([~#18231~](https://github.com/sourcegraph/sourcegraph/pull/18231)) :shipit:
- [x] (🏁 today) codeintel: Add a request-level data cache ([~#15943~](https://github.com/sourcegraph/sourcegraph/issues/15943); PRs: ~[#17964](https://github.com/sourcegraph/sourcegraph/pull/17964)~)
- [x] (🏁 today) codeintel: Batch lsif store requests ([~#15945~](https://github.com/sourcegraph/sourcegraph/issues/15945); PRs: ~[#17964](https://github.com/sourcegraph/sourcegraph/pull/17964)~)

@gbrik

- [ ] Disconnect between hover for the same symbol ([#39](https://github.com/sourcegraph/lsif-clang/issues/39))

Completed
- [x] (🏁 21 days ago) make code intel alerts non dismissible ([~#566~](https://github.com/sourcegraph/code-intel-extensions/pull/566)) :shipit:
- [x] (🏁 21 days ago) RFC 201: Do not auto-index things being manually indexed ([~#14572~](https://github.com/sourcegraph/sourcegraph/issues/14572); PRs: ~[#17893](https://github.com/sourcegraph/sourcegraph/pull/17893)~)
- [x] (🏁 19 days ago) codeintel: prepopulate index configuration field with auto-configurator output ([~#17489~](https://github.com/sourcegraph/sourcegraph/issues/17489); PRs: ~[#17736](https://github.com/sourcegraph/sourcegraph/pull/17736)~)
- [x] (🏁 18 days ago) write script to combine multiple LSIF dumps of the same repo locally before upload ([~#17960~](https://github.com/sourcegraph/sourcegraph/issues/17960); PRs: ~[#24](https://github.com/sourcegraph/lsif-test/pull/24)~)
- [x] (🏁 14 days ago) escape the project root we compare paths against ([~#42~](https://github.com/sourcegraph/lsif-clang/pull/42)) :shipit:

@tjdevries

Completed
- [x] (🏁 18 days ago) ci: Use https:// rather than ssh for clone ([~#41~](https://github.com/sourcegraph/lsif-clang/pull/41)) :shipit:
- [x] (🏁 12 days ago) cross-package type alias definitions have self-referencing semantic definition results ([~#130~](https://github.com/sourcegraph/lsif-go/issues/130); PRs: ~[#131](https://github.com/sourcegraph/lsif-go/pull/131)~) 🐛

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by gbrik** [comment]
(going to start updating this as I go since it doesn't happen otherwise)

#### Week 1 Done
- Made all code intel hover alerts non-dismissible: sourcegraph/code-intel-extensions#566
- Opened PR for prepopulating autoindexer config field: #17736 
- Opened PR to skip auto-indexing for repos with manual indexes: #17893 
- Reviewed RFCs 293, 294, 307

#### Week 1 Planned
- Investigate a weird range mismatch in precise hovers for lsif-clang (and other langs?) sourcegraph/lsif-clang#39

**Comment by macraig** [comment]
**Last week:**
- RFC 293 
- Customer info aggregation: CE syncs, dashboard scraping, Sales/CE information surfacing project
- Customer reach out and follow-ups

**This week:**
- Planning prep
- RFCs 294 and 307 
- Fill in alignment doc
- Kick off design collab
- Customer follow ups

**Comment by olafurpg** [comment]
This week:

* Reviewed protoc brainstorm by @Strum355 
* Investigated lsif-java and the Kythe Java indexer
* Started working on a new Java compiler plugin based off lsif-java, but a clean rewrite in Java
* Addressed several comments on RFC 307

**Comment by macraig** [comment]
Last week:
- Code intel OKRs and strategy 
- Customers follow ups
- RFCs 294 and 307
- Alignment doc
- Dashboard get back WAUs
- Review cycle
- Design collab draft doc

This week:
- Q1 OKRs alignment and roadmap adjusting
- Continue customer reach out and delivery follow up
- Planning prep
- Chorus AI digging
- Draft mid-long term code intel roadmap

**Comment by efritz** [comment]
**Last week:**

- Looked in to database size issues at customer
- Looked in to performance issues at prospect customer (will continue investigating)

**This week:**

Going to continue working on backend performance optimizations.

**Comment by macraig** [comment]
Last week:

- PR on updated goals/milestones
- Iteration on roadmap: https://sourcegraph.productboard.com/roadmap/2288108-code-intel
- Continue customer reach out and delivery follow up
- Planning prep
- Some Chorus AI digging
- Hover re-design review

This week:
- Customer followup
- Merge updated goals/milestones
- More Chorus AI digging

**Comment by efritz** [comment]
**This week:**

Investigated a few customer performance issues. Refactored the code intelligence resolvers in https://github.com/sourcegraph/sourcegraph/pull/17964 to make it obvious where we need to optimize. Made a bunch of issues with the [code-intelligence-performance](https://github.com/sourcegraph/sourcegraph/labels/code-intelligence-performance) label.

**Next week:**

Will plan/prioritize the issues with the label above and start digging in to that for the next few iterations.

**Comment by olafurpg** [comment]
Last week:

* lsif-java reboot https://github.com/sourcegraph/lsif-java/pull/85

This week:

* Gradle integration for lsif-java

**Comment by efritz** [comment]
Continued in https://github.com/sourcegraph/sourcegraph/issues/18290.
