### ISSUE TITLE
Campaigns Sprint 10 Tracking issue

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#17890]
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

* @LawnGnome: 1d (BC Family Day, February 15)

### Tracked issues

@LawnGnome: __2.00d__

Completed: __2.00d__
- [x] (🏁 14 days ago) browser: quiet prettier warning ([~#17962~](https://github.com/sourcegraph/sourcegraph/pull/17962)) :shipit:
- [x] (🏁 14 days ago) Dockerfile: split release and dev recipes ([~#457~](https://github.com/sourcegraph/src-cli/pull/457)) :shipit:
- [x] (🏁 14 days ago) output: hide the cursor when updating ([~#456~](https://github.com/sourcegraph/src-cli/pull/456)) :shipit:
- [x] (🏁 13 days ago) campaigns: dead link on the create campaign page ([~#17931~](https://github.com/sourcegraph/sourcegraph/issues/17931); PRs: ~[#17936](https://github.com/sourcegraph/sourcegraph/pull/17936)~, ~[#17937](https://github.com/sourcegraph/sourcegraph/pull/17937)~) 🐛
- [x] (🏁 1 day ago) Changeset spec filtering ([~#16960~](https://github.com/sourcegraph/sourcegraph/issues/16960)) __2.00d__

@eseliger

Completed
- [x] (🏁 8 days ago) campaigns: Don't use global database anymore ([~#18113~](https://github.com/sourcegraph/sourcegraph/pull/18113)) :shipit:🧶
- [x] (🏁 5 days ago) Fix SIGSEGV in changeset spec validation for imported changesets ([~#465~](https://github.com/sourcegraph/src-cli/pull/465)) :shipit:🐛
- [x] (🏁 3 days ago) schemadoc: Render view query in schema documentation ([~#18280~](https://github.com/sourcegraph/sourcegraph/pull/18280)) :shipit:

@mrnugget: __7.00d__

Completed: __7.00d__
- [x] (🏁 3 days ago) Add syntax to publish changesets by branch name ([~#17921~](https://github.com/sourcegraph/sourcegraph/issues/17921)) __2.00d__
- [x] (🏁 3 days ago) Only download workspaces when executing campaign specs ([~#17920~](https://github.com/sourcegraph/sourcegraph/issues/17920)) __5.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
