### ISSUE TITLE
Implement select: (RFC 254)

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#18002]
Implementation plan for `select:` in the search query:

**Backend**

@camdencheek will start off on the backend work items. Feel free to create GH issues to track break down these tasks independently. Some guidance and thoughts:

- [x] #18073 define a data type ("schema") for selecting on a result set. I.e., a definition we can use as ground truth to validate against select values. If we see `select:repo` or `select:file.path`, we want to validate that this selected value is legal/valid. We use this value to drive the filtering on the data itself, which will make use of our internal data types like [`CommitSearchResolver`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search_commits.go#L29), `FileMatch`, and so on. We'll iterate on this together, since we need something similar in the frontend for checks/autocomplete suggestions. 

  It'd be great if we can reorganize and refactor around our result types as we go. If possible, we should look into factoring out result set types to `internal/search`, rather than use the `resolver` result types, but this might be more involved than it sounds, so let's see.

- [x] #18073 recognize `select` in queries

- [x] #18073 create  function(s) that take a result set and selection value, and filters results of that type. This is the code we'll invoke when we see `select`, as a post-processing step.

- [x] Investigate `select:repo` optimization and interaction with `show more` functionality. https://github.com/sourcegraph/sourcegraph/issues/18275

Related PRs: #18192

Additional, straightforward and sensible selectors beyond the basic ones we can support:

- [x] Support `select` on fields for  `symbol.kind` #18808 #18910

**Frontend**

@rvantonder will start off on frontend work items:

- [x] define and use the same data type ("schema") for validating user queries in the webapp above #18125
- [x] add basic `select` recognition and highlighting/hovers #18125, #18362
- [x] add autocomplete suggestions for queries #18125, #18196
- [ ] add metrics to track usage in pings
- [x] [document](https://docs.google.com/document/d/1_m63fsBMAtqaq3GA_aMzKUPxD3yxTy8d12lJE6qN6PU/edit#heading=h.haoy2pkn3skv) implementation details and decisions around result type selection

---

The above is expected to take 1.5 to 2 weeks while both @camdencheek and @rvantonder work on the above. This aligns with RFC 254 estimate of 3.5 weeks total for the  `select` implementation and +- 1 week for metrics data. We'll balance out work as we go along.

**Comment by camdencheek** [comment]
Some clarification about intended behavior of select:
- If the selected type doesn’t exist for a result, do we just drop that result? Ex. does type:repo sourcegraph select:commit return no results (repo does not belong to any commit), or return every commit associated with the resulting repos (repo has many commits that belong to it)? Maybe a better way to ask is does select operate on `has` relationships, or only `belongs to` relationships?
- If multiple `select` types are selected, do we map a single result to multiple results? Ex. does `type:file Sentinel (select:repo or select:path)` return two results (one path and one repo) for every file match?

**Comment by rvantonder** [comment]
Let's keep implementation details in this issue.

In general, answering "What is the behavior of `select`?" is always defined in terms of the result set definition and returns the data associated with the labels. Part of the result set definition is intuitively clear, and part of it is not yet, because there has never been a concentrated effort to define it (and this is part of what we need to pin down). E.g., a sketch of some relationships are clear:

```
repository
|
|- file
|  |
|  |- content
|  `- symbol
| 
`- commit
   |
   |- message
   |- diff-content
   |- author
   |- date-time
   ...
```


Once we think of adding a member to the above definition we need to also reconcile how this interacts with existing return values of queries (e.g., `type:repo`). This behavior is currently _undefined_ because we are introducing a new construct (new information) into the domain. So to walk through that specific example:

- `repo:sourcegraph select:commit` -- currently completely undefined. We decide whether to support returning `commit` data associated with a repo. If we do (it seems reasonable that we would define member `commit` under `repo`), then it would be included in our result set definition and a valid query, returning commits associated with repos matching `repo`. We do not have to rush and support `commit` on repos right away.

- `type:repo sourcegraph select:commit`--exactly the same as above, it is also undefined, but as I said, we need to also reconcile existing query behaviors with `select`. `type:repo` is a bit weird, in that it will only ever return repository names as results. `type:repo sourcegraph` is an alias for `repo:sourcegraph` but only when there are no other parameters for the second query. My intuition is to make this invalid/not supported, simply because `type:repo` has a current behavior and it's interaction with anything else is difficult for a user to predict (much like it is difficult to figure out what this should mean in the implementation). If we strictly wanted to support it, my best guess at what this behavior would do is to give precedence to `type:repo` (so find all repo names matching sourcegraph) and then pass it through `select:commit`, and since there's no commit data associated with the results of `type:repo`, this would mean no results.

---

For practical purposes: `select` with any `type:...` parameter is undefined, let's not deal with this. `repo` with `select:commit` is undefined, we decide when and how to support that, it doesn't have to happen all at once. Let's start by thinking about straightforward cases: `select:repo`, `select:file`.

For something like `Sentinel (select:repo or select:path)`, I it is better to just fall through to our existing `or` union behavior, because if we want to do something else here, like dedupe merging, it's going to be difficult to modify existing `or`. Practically, what this means is that as soon as we implement `select`, `or` will just work and mean `(Sentinel select:repo) or (Sentinel select:path)`. The default behavior is sensible to me, which is to merge different kinds of results for each result kind--you can take as a rough proxy a current query like where `type:` sort of acts like `select`:

[`repo:^github\.com/sourcegraph/sourcegraph$ (type:repo or type:path) sourcegraph count:2`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%28type:repo+or+type:path%29+sourcegraph+count:2&patternType=literal)

which will produce (note the `Repository name match` that the webapp highlights for a repo result):

<img width="1026" alt="Screen Shot 2021-02-08 at 12 06 47 PM" src="https://user-images.githubusercontent.com/888624/107268993-2bac6b00-6a06-11eb-8ac5-0182c7e6d191.png">

**Comment by camdencheek** [comment]
Nice, thanks for the detailed response. 

I'm a little concerned about supporting the "select commits from repo" scenario, simply because a repo result won't contain all the information needed to perform that select. It turns the select feature from a fairly simple filter into a much more complex feature that will need to make followup queries. Obviously not an immediate issue since that's not a critical use case for the first pass, but I'd still be curious to hear thoughts there.

**Comment by rvantonder** [comment]
We've iterated on the implementation details here and I'll update the RFC to reflect those this week.

**Comment by rvantonder** [comment]
`select` is implemented, including support for `symbol.kind`. It makes more sense to add metrics for `select` and `contains` at the same time to reduce the effort for changing the schema, so this work will be tracked in https://github.com/sourcegraph/sourcegraph/issues/18584 for both.
