### ISSUE TITLE
Campaigns Sprint 11 Tracking issue

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#18187]
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@LawnGnome

Completed
- [x] (🏁 9 days ago) campaigns: volume workspace still have issues with non-root execution ([~#478~](https://github.com/sourcegraph/src-cli/issues/478); PRs: ~[#479](https://github.com/sourcegraph/src-cli/pull/479)~) 🐛

@eseliger

Completed
- [x] (🏁 9 days ago) Add flag to insecurely skip certificate validation ([~#475~](https://github.com/sourcegraph/src-cli/pull/475)) :shipit:
- [x] (🏁 8 days ago) Implement new credential types holding SSH keys ([~#18539~](https://github.com/sourcegraph/sourcegraph/pull/18539)) :shipit:
- [x] (🏁 6 days ago) Add support for SSH credentials in reconciler and gitserver ([~#18590~](https://github.com/sourcegraph/sourcegraph/pull/18590)) :shipit:

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
