### ISSUE TITLE
RFC 311: Out of band migrations Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#18252]
### Plan

[RFC 311: Out of band migrations](https://docs.google.com/document/u/1/d/1q59lyj-tLEmEQBe3k9bTQj85NR4abfk2SLNS6UkmcdM)

### Tracked issues

@efritz

Completed
- [x] (🏁 326 days ago) https://github.com/sourcegraph/sourcegraph/issues/18237 (PRs: ~[#18392](https://github.com/sourcegraph/sourcegraph/pull/18392)~)   🏳️ [Code Intelligence Sprint 6](https://github.com/sourcegraph/sourcegraph/milestone/97)
- [x] (🏁 326 days ago) https://github.com/sourcegraph/sourcegraph/issues/18353 (PRs: ~[#18393](https://github.com/sourcegraph/sourcegraph/pull/18393)~, ~[#18405](https://github.com/sourcegraph/sourcegraph/pull/18405)~)   🏳️ [Code Intelligence Sprint 6](https://github.com/sourcegraph/sourcegraph/milestone/97)
- [x] (🏁 326 days ago) https://github.com/sourcegraph/sourcegraph/issues/18238 (PRs: ~[#18394](https://github.com/sourcegraph/sourcegraph/pull/18394)~)   🏳️ [Code Intelligence Sprint 6](https://github.com/sourcegraph/sourcegraph/milestone/97)
- [x] (🏁 325 days ago) https://github.com/sourcegraph/sourcegraph/issues/18248 (PRs: ~[#18395](https://github.com/sourcegraph/sourcegraph/pull/18395)~)   🏳️ [Code Intelligence Sprint 6](https://github.com/sourcegraph/sourcegraph/milestone/97)
- [x] (🏁 325 days ago) https://github.com/sourcegraph/sourcegraph/pull/18411 
- [x] (🏁 324 days ago) https://github.com/sourcegraph/sourcegraph/issues/18407 (PRs: ~[#18393](https://github.com/sourcegraph/sourcegraph/pull/18393)~, ~[#18467](https://github.com/sourcegraph/sourcegraph/pull/18467)~)   🏳️ [Code Intelligence Sprint 6](https://github.com/sourcegraph/sourcegraph/milestone/97)
- [x] (🏁 324 days ago) https://github.com/sourcegraph/sourcegraph/issues/18408 (PRs: ~[#18393](https://github.com/sourcegraph/sourcegraph/pull/18393)~, ~[#18467](https://github.com/sourcegraph/sourcegraph/pull/18467)~)   🏳️ [Code Intelligence Sprint 6](https://github.com/sourcegraph/sourcegraph/milestone/97)
- [x] (🏁 318 days ago) https://github.com/sourcegraph/sourcegraph/issues/18361 (PRs: ~[#18657](https://github.com/sourcegraph/sourcegraph/pull/18657)~)   🏳️ [Code Intelligence Sprint 6](https://github.com/sourcegraph/sourcegraph/milestone/97)
- [x] (🏁 284 days ago) https://github.com/sourcegraph/sourcegraph/issues/18239 (PRs: ~[#18344](https://github.com/sourcegraph/sourcegraph/pull/18344)~)
- [x] (🏁 263 days ago) https://github.com/sourcegraph/sourcegraph/issues/18406 (PRs: ~[#18393](https://github.com/sourcegraph/sourcegraph/pull/18393)~, ~[#20304](https://github.com/sourcegraph/sourcegraph/pull/20304)~)   🏳️ [Code Intelligence Iteration 10](https://github.com/sourcegraph/sourcegraph/milestone/106)
- [x] (🏁 221 days ago) https://github.com/sourcegraph/sourcegraph/issues/18240 (PRs: ~[#20967](https://github.com/sourcegraph/sourcegraph/pull/20967)~)
- [x] (🏁 221 days ago) https://github.com/sourcegraph/sourcegraph/issues/18241 (PRs: ~[#20967](https://github.com/sourcegraph/sourcegraph/pull/20967)~)
- [x] (🏁 221 days ago) https://github.com/sourcegraph/sourcegraph/issues/20906 (PRs: ~[#20967](https://github.com/sourcegraph/sourcegraph/pull/20967)~)
- [x] (🏁 221 days ago) https://github.com/sourcegraph/sourcegraph/pull/21670 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/29074 (PRs: ~[#29508](https://github.com/sourcegraph/sourcegraph/pull/29508)~)
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/18659 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
