### ISSUE TITLE
search: result limits and counts meta issue

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#18297]
This issue is a meta issue tracking our work around cleaning up result counts and limits for exhaustive search. We won't necessarily link all related issues to this, but will close this out once we have finished our work in this area.

See [RFC 319: Accuracy and UX of search result matches and counts](https://docs.google.com/document/d/1nxofp6pVQM8G3-W2HmUJv3zSPW9XWYx_tG2zCHoiUzw/edit)

-   [x] search: count strictly limits ResultCount [#18076](https://github.com/sourcegraph/sourcegraph/issues/18076)
-   [ ] search: count limit is enforced as number of matching fragments [#18298](https://github.com/sourcegraph/sourcegraph/issues/18298)
-   [ ] search: clearly state when limits are hit [#18300](https://github.com/sourcegraph/sourcegraph/issues/18300)
-   [x] streaming: count the number of highlights in diff and commit [#18301](https://github.com/sourcegraph/sourcegraph/issues/18301)
- [ ] streaming: highlight path, symbol and repository name matches https://github.com/sourcegraph/sourcegraph/issues/18374
-   [ ] streaming: detailed counts in response [#18302](https://github.com/sourcegraph/sourcegraph/issues/18302)
-   [ ] If we need to document changes to count for existing customers

**Comment by lguychard** [comment]
All issues tracked here are individually tracked in the GH project for exhaustive.
