### ISSUE TITLE
Code Intelligence Sprint 6 Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#18290]
### Plan

This sprint covers 2020-02-15 through 2020-02-26.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

Eric: 9d (out 02/26)
Noah: 8d (out 02/18-02/19)
Garo: 5d (out 02/15)
Owen: 8d
Olaf: 9d (will be out 02/26)
Maria: 8d (out 02/15-16)
TJ: 9d (out 02/15)

### Tracked issues

@Strum355

- [ ] Failed LSIF uploads not reflected in uploads UI ([#18188](https://github.com/sourcegraph/sourcegraph/issues/18188)) 🐛
- [ ] codeintel: surface errors in upload stage of LSIF dump uploading in the UI ([#18375](https://github.com/sourcegraph/sourcegraph/pull/18375)) :shipit:

Completed
- [x] (🏁 3 days ago) JDK 11+ support for javac plugin indexer ([~#90~](https://github.com/sourcegraph/lsif-java/issues/90); PRs: ~[#91](https://github.com/sourcegraph/lsif-java/pull/91)~)
- [x] (🏁 1 day ago) Gradle support ([~#87~](https://github.com/sourcegraph/lsif-java/issues/87))

@efritz

- [ ] RFC 311: Out of band migrations Tracking issue ([#18252](https://github.com/sourcegraph/sourcegraph/issues/18252))
  - [x] (🏁 14 days ago) RFC 311: Add migrations table ([~#18237~](https://github.com/sourcegraph/sourcegraph/issues/18237); PRs: ~[#18392](https://github.com/sourcegraph/sourcegraph/pull/18392)~)
  - [x] (🏁 14 days ago) RFC 311: Expose migration status via GraphQL ([~#18238~](https://github.com/sourcegraph/sourcegraph/issues/18238); PRs: ~[#18394](https://github.com/sourcegraph/sourcegraph/pull/18394)~)
  - [x] (🏁 13 days ago) codeintel: Add diagnostics count to lsif_data_documents ([~#18248~](https://github.com/sourcegraph/sourcegraph/issues/18248); PRs: ~[#18395](https://github.com/sourcegraph/sourcegraph/pull/18395)~)
  - [x] (🏁 14 days ago) RFC 311: Write migration machinery ([~#18353~](https://github.com/sourcegraph/sourcegraph/issues/18353); PRs: ~[#18393](https://github.com/sourcegraph/sourcegraph/pull/18393)~, ~[#18405](https://github.com/sourcegraph/sourcegraph/pull/18405)~)
  - [x] (🏁 6 days ago) RFC 311: Write usage docs ([~#18361~](https://github.com/sourcegraph/sourcegraph/issues/18361); PRs: ~[#18657](https://github.com/sourcegraph/sourcegraph/pull/18657)~)
  - [x] (🏁 12 days ago) RFC 311: Isolate migrators ([~#18407~](https://github.com/sourcegraph/sourcegraph/issues/18407); PRs: ~[#18393](https://github.com/sourcegraph/sourcegraph/pull/18393)~, ~[#18467](https://github.com/sourcegraph/sourcegraph/pull/18467)~)
  - [x] (🏁 12 days ago) RFC 311: Independently configure migrators ([~#18408~](https://github.com/sourcegraph/sourcegraph/issues/18408); PRs: ~[#18393](https://github.com/sourcegraph/sourcegraph/pull/18393)~, ~[#18467](https://github.com/sourcegraph/sourcegraph/pull/18467)~)
  - [x] (🏁 12 days ago) RFC 311: Register and run migrators ([~#18411~](https://github.com/sourcegraph/sourcegraph/pull/18411)) :shipit:
- [ ] ~docs: Write usage docs for internal/workerutil~ ([#18286](https://github.com/sourcegraph/sourcegraph/issues/18286))

Completed
- [x] (🏁 15 days ago) monitoring: Alert on massively bloated tables ([~#18284~](https://github.com/sourcegraph/sourcegraph/issues/18284); PRs: ~[#18343](https://github.com/sourcegraph/sourcegraph/pull/18343)~)
- [x] (🏁 14 days ago) codeintel: Research HOT for bulk inserts ([~#18285~](https://github.com/sourcegraph/sourcegraph/issues/18285); PRs: ~[#18345](https://github.com/sourcegraph/sourcegraph/pull/18345)~)
- [x] (🏁 14 days ago) RFC 311: Add migrations table ([~#18237~](https://github.com/sourcegraph/sourcegraph/issues/18237); PRs: ~[#18392](https://github.com/sourcegraph/sourcegraph/pull/18392)~)
- [x] (🏁 14 days ago) RFC 311: Write migration machinery ([~#18353~](https://github.com/sourcegraph/sourcegraph/issues/18353); PRs: ~[#18393](https://github.com/sourcegraph/sourcegraph/pull/18393)~, ~[#18405](https://github.com/sourcegraph/sourcegraph/pull/18405)~)
- [x] (🏁 14 days ago) RFC 311: Expose migration status via GraphQL ([~#18238~](https://github.com/sourcegraph/sourcegraph/issues/18238); PRs: ~[#18394](https://github.com/sourcegraph/sourcegraph/pull/18394)~)
- [x] (🏁 13 days ago) codeintel: Add diagnostics count to lsif_data_documents ([~#18248~](https://github.com/sourcegraph/sourcegraph/issues/18248); PRs: ~[#18395](https://github.com/sourcegraph/sourcegraph/pull/18395)~)
- [x] (🏁 12 days ago) RFC 311: Register and run migrators ([~#18411~](https://github.com/sourcegraph/sourcegraph/pull/18411)) :shipit:
- [x] (🏁 12 days ago) alert: Disable alert for Postgres table bloat ([~#18495~](https://github.com/sourcegraph/sourcegraph/pull/18495)) :shipit:
- [x] (🏁 12 days ago) codeintel: Fix div by zero in migration SQL query ([~#18504~](https://github.com/sourcegraph/sourcegraph/pull/18504)) :shipit:
- [x] (🏁 12 days ago) codeintel: Add additional opentracing logs to resolvers ([~#18244~](https://github.com/sourcegraph/sourcegraph/issues/18244); PRs: ~[#18451](https://github.com/sourcegraph/sourcegraph/pull/18451)~)
- [x] (🏁 12 days ago) codeintel: Paginate definitions lsifstore results ([~#18245~](https://github.com/sourcegraph/sourcegraph/issues/18245); PRs: ~[#18498](https://github.com/sourcegraph/sourcegraph/pull/18498)~)
- [x] (🏁 12 days ago) codeintel: Fix unbounded memory in lsifstore locations method ([~#18246~](https://github.com/sourcegraph/sourcegraph/issues/18246); PRs: ~[#18511](https://github.com/sourcegraph/sourcegraph/pull/18511)~)
- [x] (🏁 12 days ago) RFC 311: Isolate migrators ([~#18407~](https://github.com/sourcegraph/sourcegraph/issues/18407); PRs: ~[#18393](https://github.com/sourcegraph/sourcegraph/pull/18393)~, ~[#18467](https://github.com/sourcegraph/sourcegraph/pull/18467)~)
- [x] (🏁 12 days ago) RFC 311: Independently configure migrators ([~#18408~](https://github.com/sourcegraph/sourcegraph/issues/18408); PRs: ~[#18393](https://github.com/sourcegraph/sourcegraph/pull/18393)~, ~[#18467](https://github.com/sourcegraph/sourcegraph/pull/18467)~)
- [x] (🏁 12 days ago) codeintel: Add additional opentracing logs to lsifstore ([~#18243~](https://github.com/sourcegraph/sourcegraph/issues/18243); PRs: ~[#18451](https://github.com/sourcegraph/sourcegraph/pull/18451)~)
- [x] (🏁 9 days ago) codeintel: Avoid unbounded data retrieval from lsifstore ([~#18541~](https://github.com/sourcegraph/sourcegraph/pull/18541)) :shipit:
- [x] (🏁 9 days ago) codeintel: Fix bad value for trace log ([~#18550~](https://github.com/sourcegraph/sourcegraph/pull/18550)) :shipit:
- [x] (🏁 9 days ago) codeintel: Explode bundle.go into multiple files ([~#18553~](https://github.com/sourcegraph/sourcegraph/pull/18553)) :shipit:
- [x] (🏁 9 days ago) codeintel: Fix unbounded memory in lsifstore Ranges request ([~#18247~](https://github.com/sourcegraph/sourcegraph/issues/18247); PRs: ~[#18570](https://github.com/sourcegraph/sourcegraph/pull/18570)~)
- [x] (🏁 8 days ago) dev: Fix tempdir for codeintel-executor ([~#18616~](https://github.com/sourcegraph/sourcegraph/pull/18616)) :shipit:
- [x] (🏁 8 days ago) chore: Fix typo in comment ([~#18614~](https://github.com/sourcegraph/sourcegraph/pull/18614)) :shipit:
- [x] (🏁 7 days ago) codeintel: Fix bulk moniker query ordering to match index ([~#18615~](https://github.com/sourcegraph/sourcegraph/pull/18615)) :shipit:
- [x] (🏁 7 days ago) Fix assertion panic for type aliases to anonymous structs ([~#134~](https://github.com/sourcegraph/lsif-go/pull/134)) :shipit:
- [x] (🏁 7 days ago) codeintel: Deterministically order range lists during processing ([~#18613~](https://github.com/sourcegraph/sourcegraph/pull/18613)) :shipit:
- [x] (🏁 6 days ago) codeintel: More intelligently page/paginate lsifstore locations results ([~#18250~](https://github.com/sourcegraph/sourcegraph/issues/18250); PRs: ~[#18589](https://github.com/sourcegraph/sourcegraph/pull/18589)~)
- [x] (🏁 6 days ago) RFC 311: Write usage docs ([~#18361~](https://github.com/sourcegraph/sourcegraph/issues/18361); PRs: ~[#18657](https://github.com/sourcegraph/sourcegraph/pull/18657)~)
- [x] (🏁 6 days ago) docs: Write usage docs for db/basestore ([~#18287~](https://github.com/sourcegraph/sourcegraph/issues/18287); PRs: ~[#18658](https://github.com/sourcegraph/sourcegraph/pull/18658)~)

@olafurpg

Completed
- [x] (🏁 1 day ago) Gradle support ([~#87~](https://github.com/sourcegraph/lsif-java/issues/87))

@shrouxm

- [ ] no output produced for seemingly well-formed compile_commands.json ([#4](https://github.com/sourcegraph/lsif-clang/issues/4)) 🐛
- [ ] Merge upstream changes, and add instructions on how to do that ([#44](https://github.com/sourcegraph/lsif-clang/pull/44)) :shipit:
- [ ] codeintel: Write tool to compare LSIF dumps for semantic equality, and output semantic diffs ([#18183](https://github.com/sourcegraph/sourcegraph/issues/18183))

Completed
- [x] (🏁 14 days ago) codeintel: write RFC about organizing LSIF-related code + tooling ([~#18273~](https://github.com/sourcegraph/sourcegraph/issues/18273))
- [x] (🏁 2 days ago) add the lsif-protcol repo into the main sourcegraph repo ([~#18655~](https://github.com/sourcegraph/sourcegraph/pull/18655)) :shipit:
- [x] (🏁 2 days ago) add codeintelutils into sourcegraph/sourcegraph ([~#18665~](https://github.com/sourcegraph/sourcegraph/pull/18665)) :shipit:
- [x] (🏁 2 days ago) add lsif-test to main sourcegraph repo ([~#18672~](https://github.com/sourcegraph/sourcegraph/pull/18672)) :shipit:

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by gbrik** [comment]
#### Done Week 1
- Wrote & submitted [RFC 324](https://docs.google.com/document/d/1vXOSWTW_-oRJlOBUeh3efQvlhDw6eeKC6rfwDiwqFJw/edit)

#### Planned Week 1
- Wrap up sourcegraph/lsif-clang#4 (doc update) and sourcegraph/lsif-clang#44 (merging upstream)

#### Planned Week 2
- Once RFC 324 is approved, start working on #18183

**Comment by efritz** [comment]
Continued in https://github.com/sourcegraph/sourcegraph/issues/18860.
