### ISSUE TITLE
search: Tracking graphqlbackend refactor

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#18348]
This is a tracking issue for refactoring graphqlbackend into smaller, less monolithic packages. Currently, it's just a rough outline. Looking for feedback both on scope and on direction.

WIP goal statement: Disentangle graphqlbackend code and search code enough that we can move result types out of `graphqlbackend` and into `internal/search`.

Tasks to hit goal statement:
- [x] Disentangle GraphQL resolvers from result types
  - [x] Split `FileMatch` and `FileMatchResolver` (done previously)
  - [x] Split `lineMatch` and `lineMatchResolver` (#18349)
  - [x] Split `symbolSearchResult` and `symbolResolver` (done previously)
  - [x] Split `commitSearchResult` and `CommitSearchResultResolver` (#18497)
  - [x] Split `repositoryResult` and `RepositoryResolver` (effectively already done with `types.Repo`)\
- [x] Move repository and git commit resolution out of struct members
  - [x] Add repository/commit resolution at the result -> resolver level 
  - [x] Replace `GitCommitResolver` on `searchSymbolResult` with a git commit ID (#18596, #18637)
  - [x] Replace `GitCommitResolver` on `CommitSearchResultResolver` with a git commit ID (resolved later) (#18497)
- [x] Move result types from `graphqlbackend` into `internal/search(/result)?`
  - [x] `FileMatch` (#18794)
  - [x] `LineMatch` (#18794)
  - [x] `SearchSymbolResult` (#18794)
  - [x] `CommitSearchResult` (#19002)
  - [x] `HighlightedString` (#18995)

Related:
- Remove J prefix from FileMatch (#18564)
- Move some FileMatch methods from resolver to result type (#18563)

**Comment by camdencheek** [comment]
@sourcegraph/search I think this is finally to the point where the result types are all clear to be moved out of `graphqlbackend`. 

I'm looking for some opinions on next steps:

**Where would we like to move the result types?** 

Assuming we want to move the result types out of `graphqlbackend` now that they're independent of the resolvers, where to? A couple of options include `internal/search` or a new `internal/search/result` or something similar. I think their own sub-package might make sense to help keep them independent, there's also the readability of the import path (`search.FileMatch` vs `result.FileMatch`?) to take into account.

**What comes next?** 

Once the types are moved out of `graphqlbackend`, I think this is a good stopping point for this tracking issue. However, I think there is still a bit more followup work that can be done in response to splitting up results and resolvers. I'd love to keep the ball rolling on this, and would like to hear thoughts on what next steps should be. A few ideas:

- _Propagate result types further up the call chain._ Many of our search functions return resolvers when they could really be returning result types. This would also free them up to be moved out of `graphqlbackend` if we so choose. This might be more difficult than I'm imagining because of streaming search (a streamer takes resolvers, and is propagated all the way down the call chain in most cases). 
- _Minimize the result type interfaces (field and method)_. I started on this somewhat while splitting out the result types from resolvers, but there are many cases where are result types are much more complex than they need to be, which makes constructing them difficult for the consumer, and makes reasoning about them difficult when refactoring or adding new features. 
- _

**Comment by keegancsmith** [comment]
Moving them into a sub package sounds good to me. We have a bit of a sprawl right now under `./internal/search` but I think make it more sprawling :) Once we have the mess in there, its easier for us to move/combine/etc pkgs around. The big deal is finally having result types outside of graphqlbackend :D

**Comment by keegancsmith** [comment]
picking the suggested structure seems like a good north star and will certainly be better than the mess we have right now :D

**Comment by camdencheek** [comment]
Closing the issue because all changes within scope of this tracking issue are finished 🎉
