### ISSUE TITLE
insights: 3.25 release checklist

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#18465]
- [ ] Deploy TimescaleDB in docker-compose environments
- [ ] Turn on for all Kubernetes and Docker Compose deployments.
- [ ] Disable telemetry: https://github.com/sourcegraph/sourcegraph/pull/18464
