### ISSUE TITLE
I. G. onboarding plan

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#18611]
### Week 1

Go through [General Onboarding](https://about.sourcegraph.com/handbook/people-ops/onboarding#for-all-new-teammates) and [Engineering Onboarding](https://about.sourcegraph.com/handbook/engineering/onboarding#engineering-onboarding).

- [x] Once joined @sourcegraph organization, self-assign proposed issues to yourself.
- [x] Schedule an architecture deep dive session with @tsenart.
- [x] Schedule a backend development introduction session with @unknwon (your on-boarding [buddy](https://about.sourcegraph.com/handbook/people-ops/onboarding/buddy-program))
- [x] Meet with @arussellsaw and @ryanslade (at once) to learn about the on-going work in the Cloud project and what upcoming changes you'll be working on.

### Week 2 - 3

Get started with some smaller tasks that should help your learn a lot of our moving pieces.

- [x] debt: GraphQL backend ConnectionArgs can have a negative first value https://github.com/sourcegraph/sourcegraph/issues/3329
- [ ] Add docs for connecting to Azure DevOps as a code host https://github.com/sourcegraph/sourcegraph/issues/8647
- [x] Add tests for raw endpoint #11259
- [ ] Infinite redirect loop on sourcegraph.com when accessing submodule #10539

### Week 4 - X

Start working on more complex tasks that require deep diving into our codebase.

- [ ] External service list should indicate which services are user owned #14976
- [ ] gitserver: some exec prometheus metric improvements https://github.com/sourcegraph/sourcegraph/issues/9145
- [ ] Add admin flag to `org_members` table #15318
- [ ] Add graphql mutation to promote user to org admin #15319
- [ ] Indicate which members of an org are admins #15321
- [ ] 2FA https://github.com/orgs/sourcegraph/projects/135, #18185 (needs more context and refinement)

**Comment by tsenart** [comment]
@unknwon: I was thinking  that picking up the 2FA work from @flying-robot would also be a good Week 4 - X project. 

- https://github.com/orgs/sourcegraph/projects/135
- https://github.com/sourcegraph/sourcegraph/pull/18185

Alan had to drop everything to be a parent, so there might be some context that we'd need to discover then.

**Comment by tsenart** [comment]
![](https://media.giphy.com/media/jS27LWasgUIYrXtP83/giphy.gif)
