### ISSUE TITLE
3.26.0 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#18641]
# 3.26.0 managed instances upgrade

These [managed instances](https://about.sourcegraph.com/handbook/engineering/distribution/managed) upgrades are scheduled for **[Mar 22, 2021, 6:00 PM (UTC)](https://time.is/1800_22_Mar_2021_in_UTC?One%20working%20day%20after%203.26%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](https://about.sourcegraph.com/handbook/engineering/distribution/managed/upgrade_process).

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com)

## Upgrade customer managed instances

- [x] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/1712860829](https://app.hubspot.com/contacts/2762526/company/1712860829/)

---

Also see [3.26 release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/18640)
