### ISSUE TITLE
Things to fix before GA

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#18664]
### Description

Fix the following bugs and issues spotted during [hallway testing for pre-GA with public repos for users](https://docs.google.com/document/d/1VpI1aXxY3mtQ_RzEX9gTSLhzrNTM2iHQvd_u2kOqeEs/edit#):

**High priority**
- [ ] When removing code host connections, it hangs badly. On dotcom `DeleteExternalService` requests take ~20 seconds or `502`. #18730
- [ ] UserRepositories GraphQL queries take long time #19223 
- [x] In access token modal, disable auto completion and suggestions for access tokens.
- [x] In "Manage repos" view, immediate navigation to "Repositories" view occurs after the user clicks `Save`. Wait until ~repos are cloned~ **we have a list of all repos the user had selected**.
- [ ] In "Manage repos" view, searching while viewing paginated page other the the first is broken.
- [x] On "Repositories" view, `updating repos` banner is shown before user has added repos.
- [ ] Add GitLab Auth provider for dotcom #16745
- [x] In "Manage repos" view, "Sync selected public repositories" option should be disabled until a code host connection is present.

**Medium priority**
- [ ] In "Manage repos" view, replace pagination with better pagination component. #17136
- [ ] When removing repositories in the "Manage repos" view, it takes an extraordinarily long time to finish saving. (#19235 is a part of it)
- [ ] When adding invalid tokens (think `bla-bla-42`) for GitHub code host, backend doesn't report warnings/errors #18740

**Low priority**
- [x] In "Code host connections" view, "Edit" button shouldn't have focus after connection is made.
- [x] In "Code host connections" view, use LoaderButton for code host  `add`, `edit`, `remove` popups
- [ ] In "Manage repos" view, when filtering repos with the search input field, UI elements "jump" due to scrollbar visibility.

[Reference videos for these issues can be found on Airtable](https://airtable.com/shrLZwesaJBhgaBqF).

### Other action items

- [ ] Sort selected repositories at top of list in subsequent loads of "Manage repos" view #18780
- [x] Copy adjustments to "Manage repositories" view #18778
- [x] Improve usability around connecting code hosts with personal access tokens #18743
