### ISSUE TITLE
Tracking issue for enforced lint reconciliation

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#18720]
This issue will track the progress of reconciling `.golangci.yml` and `.golangci.enforced.yml`.

#18703 enables mandatory linting for the lint `ineffassign`, but added the file `.golangci.enforced.yml` so that it's not necessary to fix every lint warning before enabling a minimal set of enforced lints. Ideally, we will fix the existing lint warnings on `main` and unify `.golangci.enforced.yml` and `.golangci.yml`. 

We may decide some of these are too noisy to be worth enabling, but based on looking through issues, there's already been some good effort narrowing down to only useful lints. From that, I'm going to default to assuming that the currently-enabled lints are worth enforcing. 

Note that if a lint is generally useful, but doesn't make sense to apply in some situations, it can be ignored on a case-by-case basis with the `//nolint:lintname` directive (see more [here](https://golangci-lint.run/usage/false-positives/)). 

Candidates to add to `.golangci.enforced.yml` (current warning count in parens):
- [x] `bodyclose` (6) (fixed and enabled in #19036)
- [x] `gocritic` (50+) (fixed and enabled #19333 and #19335)
- [x] `goimports` (50+) (fixed and enabled in #18748)
- [x] `gosimple` (8) (fixed and enabled in #18998)
- [x] `govet` (7) (fixed and enabled in #19498)
- [x] `ineffassign` (2) (fixed in #18699, #18701; enabled in #18703)
- [x] `nolintlint` (0) (enabled in #18745)
- [x] `staticcheck` (8) (fixed and enabled in #19491)
- [x] `typecheck` (0) (enabled in #18745)
- [x] `unconvert` (37) (fixed and enabled in #18746)
- [x] `unused` (50+) (fixed and enabled in #19544)

Candidates for exclusion from `.golangci.yml`:
- [ ] `whitespace` (6) This will likely cause a large amount of noise, and is only a minor style lint. _However_, it can be fixed automatically with `golangci-lint run --fix`, so if we can enable auto-fixing with little friction, it's possible it could provide a small amount of value for readability. 
- [ ] `goprintffuncname` (1) This seems like a very specific style nit, and is not worth the CPU time to check it
- [ ] `dogsled` (3) Seems like a style nit that doesn't add value
- [ ] `interfacer` (15) The tool is deprecated, and the lints it provides are 1) not useful and 2) full of false positives
- [ ] `rowserrcheck` (3) This could be useful, but unfortunately suffers from many false positives due to [this issue](https://github.com/jingyugao/rowserrcheck/issues/16). Planning to exclude with a TODO to include once that that issue is fixed and upstreamed.
- [ ] `nakedret` (4) Opinionated style lint that's a good reminder, but likely not worth enforcing
- [ ] `dupl` (50+) I like the spirit of it, but in practice I've found it to be _very_ noisy
- [ ] `golint` (50+) These are generally good style lints, but not everyone cares about them. I don't feel strongly about this one, but I won't be championing it. 
- [ ] `errcheck` (20) Checking errors is good, but IMO, there are far too many cases we'd have to exclude for this to be useful. 
- [ ] `gosec` (34) These are sometimes good checks, but would very often need ignored. Since I'm going for high confidence on these enforced lints, this feels worth excluding at this point. 
- [ ] `stylecheck` (8) I'm trying not to annoy people, and this isn't configurable, so I'd rather not force all the capitalization nits.
- [ ] `unparam` (50+) I'm torn on this one, but ultimately, I expect the checks it runs to be unstable and noisy. It runs checks like "this parameter is always used with a specific value, so you can get rid of it", which, even if true, might not be the abstraction that makes sense. 
- [ ] `varcheck` (9) (fixed and enabled in #18997, then disabled in #19544) This is a subset of `unused`
- [ ] `deadcode` (25) (fixed and enabled in #19054, then disabled in #19544) This is a subset of `unused`
- [ ] `structcheck` (2) This check is a subset of `unused`

**Comment by tsenart** [comment]
@camdencheek: You shouldn't use the tracking label if an issue isn't meant to be used with the tracking-issue tool, so removing that label.

**Comment by tsenart** [comment]
Very excited for this! List LGTM, and rationale is :+1:
