### ISSUE TITLE
Cloud pre-GA hallway testing outcomes related to Search

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#18732]
During the hallway testing for [pre-GA with public repos on Cloud](https://docs.google.com/document/d/1VpI1aXxY3mtQ_RzEX9gTSLhzrNTM2iHQvd_u2kOqeEs/edit#), we found the following issues related to Search:

- [ ] Search context selector did not show up after adding repos / [View on LookBack](https://lookback.io/play/M8JZrGmYqytsGZacm#flow-hmJ9cHeuc6dCsRsL3)
- [x] #18750 Search toggles and copy button missing after contexts enabled with feature flag / [View on LookBack](https://lookback.io/play/M8JZrGmYqytsGZacm#flow-8KLgcmqLeZmLc6xMZ)
- [x] #18767 Clicked `-repo:` in autocomplete suggestions, `repo:` was inserted instead. User didn't realize this for a while / [View on LookBack](https://lookback.io/play/M8JZrGmYqytsGZacm#flow-t5u7nBqW9ajeuKWdi)
- [x] #18774 Repos listed in a user's personal context say that they're a "repository name match" instead of "Included in context" or similar, which causes confusion about why they're appearing. / [View on LookBack](https://lookback.io/play/ZEqzKQ6Sz3EvSXDBk#flow-LaN7N5yjvbzE2jMSx)

We have a separate tracking issue (#18664) for bugs related to the Cloud

**Comment by limitedmage** [comment]
> Search toggles and copy button missing after contexts enabled with feature flag

I've seen this issue locally and on Percy screenshots during integration/e2e tests, but I have not been able to get a consistent repro so it's very hard to debug. I suspect it's an issue where the MonacoQueryEditor is not resizing appropriately and thus spilling over to the toggles. Thanks to this I got a consistent repro so I'll investigate :) Filed #18750
