### ISSUE TITLE
Batchers Sprint 12 Tracking issue

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#18754]
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@unassigned

Completed
- [x] (🏁 1 day ago) Rename campaigns to batch changes ([~#18771~](https://github.com/sourcegraph/sourcegraph/issues/18771))

@LawnGnome: __7.00d__

- [ ] Extend GitHub token scope for campaigns by user:email ([#17555](https://github.com/sourcegraph/sourcegraph/issues/17555); PRs: [#18457](https://github.com/sourcegraph/sourcegraph/pull/18457)) __1.00d__
- [ ] Batch changes notice for UI ([#18894](https://github.com/sourcegraph/sourcegraph/issues/18894))

Completed: __6.00d__
- [x] (🏁 10 days ago) Changeset rate limiting / scheduling ([~#17370~](https://github.com/sourcegraph/sourcegraph/issues/17370)) __3.00d__
- [x] (🏁 7 days ago) batches: rename and update schemata ([~#18963~](https://github.com/sourcegraph/sourcegraph/pull/18963)) :shipit:
- [x] (🏁 6 days ago) cli: rename campaigns to batch changes ([~#18940~](https://github.com/sourcegraph/sourcegraph/issues/18940); PRs: ~[#489](https://github.com/sourcegraph/src-cli/pull/489)~)
- [x] (🏁 6 days ago) go.mod: rename campaignutils to batch-change-utils ([~#490~](https://github.com/sourcegraph/src-cli/pull/490)) :shipit:
- [x] (🏁 6 days ago) go.mod: handle the campaignutils rename ([~#19000~](https://github.com/sourcegraph/sourcegraph/pull/19000)) :shipit:
- [x] (🏁 5 days ago) cli: update minimum version ([~#19045~](https://github.com/sourcegraph/sourcegraph/pull/19045)) :shipit:
- [x] (🏁 1 day ago) batches: update doc image and video assets ([~#19117~](https://github.com/sourcegraph/sourcegraph/pull/19117)) :shipit:
- [x] (🏁 1 day ago) campaigns: migrate public docs and marketing materiel to the new name ([~#18799~](https://github.com/sourcegraph/sourcegraph/issues/18799)) __3.00d__

@eseliger: __5.50d__

- [ ] Enable SSH pushing of commits ([#17840](https://github.com/sourcegraph/sourcegraph/issues/17840); PRs: [#19177](https://github.com/sourcegraph/sourcegraph/pull/19177))
- [ ] RFC: campaigns: allow a single bot user to be used when reconciling ([#17919](https://github.com/sourcegraph/sourcegraph/issues/17919))
- [ ] campaigns: document SSH credential flow ([#16896](https://github.com/sourcegraph/sourcegraph/issues/16896); PRs: [#19177](https://github.com/sourcegraph/sourcegraph/pull/19177)) __1.00d__

Completed: __4.50d__
- [x] (🏁 13 days ago) Group campaigns graphql schema extension ([~#18809~](https://github.com/sourcegraph/sourcegraph/pull/18809)) :shipit:
- [x] (🏁 12 days ago) campaigns: update the GraphQL schema to support SSH keys ([~#16893~](https://github.com/sourcegraph/sourcegraph/issues/16893); PRs: ~[#18697](https://github.com/sourcegraph/sourcegraph/pull/18697)~) __1.00d__
- [x] (🏁 12 days ago) campaigns: extend settings UI to allow for SSH keys to be provisioned ([~#16894~](https://github.com/sourcegraph/sourcegraph/issues/16894); PRs: ~[#18697](https://github.com/sourcegraph/sourcegraph/pull/18697)~) __3.00d__
- [x] (🏁 11 days ago) Batch changes web client name refactor ([~#18856~](https://github.com/sourcegraph/sourcegraph/pull/18856)) :shipit:
- [x] (🏁 11 days ago) Rename campaigns package in web codebase to batches ([~#18871~](https://github.com/sourcegraph/sourcegraph/pull/18871)) :shipit:
- [x] (🏁 11 days ago) Finish overhaul of batch changes GraphQL API ([~#18878~](https://github.com/sourcegraph/sourcegraph/pull/18878)) :shipit:
- [x] (🏁 10 days ago) Remove import of repo-updater in batches code ([~#18906~](https://github.com/sourcegraph/sourcegraph/pull/18906)) :shipit:
- [x] (🏁 7 days ago) Repair ~campaigns~ batchers notify bot ([~#18944~](https://github.com/sourcegraph/sourcegraph/pull/18944)) :shipit:
- [x] (🏁 7 days ago) Close Batch Change and marking changesets to also be closed does not close changesets ([~#18955~](https://github.com/sourcegraph/sourcegraph/issues/18955); PRs: ~[#18957](https://github.com/sourcegraph/sourcegraph/pull/18957)~) __0.50d__ 🐛
- [x] (🏁 7 days ago) Rename all DB resources to new batch changes naming ([~#18941~](https://github.com/sourcegraph/sourcegraph/pull/18941)) :shipit:
- [x] (🏁 6 days ago) UpperFirst batch changes in webapp when product name is mentioned ([~#18986~](https://github.com/sourcegraph/sourcegraph/pull/18986)) :shipit:
- [x] (🏁 6 days ago) Fix license check in batches web UI ([~#18989~](https://github.com/sourcegraph/sourcegraph/pull/18989)) :shipit:
- [x] (🏁 5 days ago) Fix campaigns redirect ([~#19012~](https://github.com/sourcegraph/sourcegraph/pull/19012)) :shipit:
- [x] (🏁 5 days ago) Some more batch changes renaming cleanup ([~#19035~](https://github.com/sourcegraph/sourcegraph/pull/19035)) :shipit:
- [x] (🏁 5 days ago) Ensure we always use the newest external service ([~#19033~](https://github.com/sourcegraph/sourcegraph/pull/19033)) :shipit:
- [x] (🏁 4 days ago) Fix confusing changeset next sync date tooltip ([~#19083~](https://github.com/sourcegraph/sourcegraph/pull/19083)) :shipit:🐛
- [x] (🏁 4 days ago) Improve performance for batch changes with many changesets ([~#19053~](https://github.com/sourcegraph/sourcegraph/pull/19053)) :shipit:
- [x] (🏁 1 day ago) Fix alignment of diffstat in changesets list ([~#19119~](https://github.com/sourcegraph/sourcegraph/pull/19119)) :shipit:
- [x] (🏁 1 day ago) Some low hanging fruit improvements for burndown chart ([~#19052~](https://github.com/sourcegraph/sourcegraph/pull/19052)) :shipit:
- [x] (🏁 today) Faster changeset search ([~#19118~](https://github.com/sourcegraph/sourcegraph/pull/19118)) :shipit:

@malomarrec

- [ ] Public list of campaigns examples ([#18219](https://github.com/sourcegraph/sourcegraph/issues/18219))

@rrhyne

- [ ] Design changeset rate limiting / scheduling ([#18507](https://github.com/sourcegraph/sourcegraph/issues/18507))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
