### ISSUE TITLE
Code Intelligence Sprint 7 Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#18860]
### Plan

This sprint covers 2021-03-01 through 2021-03-12.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

Eric: 9d (out 2021-03-01)
Maria: 9d (out 2021-03-05)
Owen: 8d (4x10 schedule)
Noah: 10d
Roux: 6d (off Tuesdays/Thursdays)
Olaf: 10d
TJ: 10d

### Tracked issues

@AlicjaSuska

Completed
- [x] (🏁 today) Code intelligence result types in hovers shouldn't be dismissible  ([~#17582~](https://github.com/sourcegraph/sourcegraph/issues/17582); PRs: ~[#18843](https://github.com/sourcegraph/sourcegraph/pull/18843)~)

@Strum355

- [ ] Convert SemanticDB docstrings into LSIF hover messages ([#102](https://github.com/sourcegraph/lsif-java/issues/102); PRs: ~[#119](https://github.com/sourcegraph/lsif-java/pull/119)~)
- [ ] Symbols randomly missing  ([#115](https://github.com/sourcegraph/lsif-java/issues/115))
- [ ] bump Go version to 1.16.2 ([#137](https://github.com/sourcegraph/lsif-go/pull/137)) :shipit:

Completed
- [x] (🏁 13 days ago) adds support for denoting other languages ([~#10~](https://github.com/sourcegraph/lsif-semanticdb/pull/10)) :shipit:
- [x] (🏁 12 days ago) move from gogo/protobuf to google.golang.org/protobuf ([~#12~](https://github.com/sourcegraph/lsif-semanticdb/pull/12)) :shipit:
- [x] (🏁 11 days ago) derive symbol language from document language ([~#14~](https://github.com/sourcegraph/lsif-semanticdb/pull/14)) :shipit:
- [x] (🏁 7 days ago) ~DRAFT: Adds support for semanticdb documentation field~ ([~#11~](https://github.com/sourcegraph/lsif-semanticdb/pull/11)) :shipit:
- [x] (🏁 7 days ago) updates semanticdb.proto for updated Documentation field/message ([~#119~](https://github.com/sourcegraph/lsif-java/pull/119)) :shipit:
- [x] (🏁 7 days ago) fixes snapshot generator comment // insertion ([~#120~](https://github.com/sourcegraph/lsif-java/pull/120)) :shipit:
- [x] (🏁 4 days ago) fixes range deriving for constructs incl classes/interfaces ([~#121~](https://github.com/sourcegraph/lsif-java/pull/121)) :shipit:

@efritz

- [ ] ~codeintel: Do a better job distributing result chunk values~ ([#18242](https://github.com/sourcegraph/sourcegraph/issues/18242))
- [ ] ~codeintel: More intelligently page/paginate lsifstore diagnostic results~ ([#18249](https://github.com/sourcegraph/sourcegraph/issues/18249))
- [ ] codeintel: Standardize lsifstore out-of-band migrations ([#18667](https://github.com/sourcegraph/sourcegraph/pull/18667)) :shipit:
- [ ] ~codeintel: More intelligently page/paginate lsifstore bulk moniker results~ ([#18554](https://github.com/sourcegraph/sourcegraph/issues/18554); PRs: [#18549](https://github.com/sourcegraph/sourcegraph/pull/18549))

Completed
- [x] (🏁 12 days ago) dev: Add depgraph utility ([~#18883~](https://github.com/sourcegraph/sourcegraph/pull/18883)) :shipit:
- [x] (🏁 12 days ago) depgraph: List test imports as well ([~#18886~](https://github.com/sourcegraph/sourcegraph/pull/18886)) :shipit:
- [x] (🏁 11 days ago) chore: Fix depgraph test package gathering ([~#18892~](https://github.com/sourcegraph/sourcegraph/pull/18892)) :shipit:
- [x] (🏁 11 days ago) codenotify: Add codenotify for depgraph ([~#18891~](https://github.com/sourcegraph/sourcegraph/pull/18891)) :shipit:
- [x] (🏁 11 days ago) depgraph: Add NoBinarySpecificSharedCode lint pass ([~#18890~](https://github.com/sourcegraph/sourcegraph/pull/18890)) :shipit:
- [x] (🏁 11 days ago) chore: Fix typo in depgraph output ([~#18896~](https://github.com/sourcegraph/sourcegraph/pull/18896)) :shipit:
- [x] (🏁 11 days ago) chore: Remove dead packages ([~#18887~](https://github.com/sourcegraph/sourcegraph/pull/18887)) :shipit:
- [x] (🏁 11 days ago) ~chore: Move cmd/frontend/envvar to internal/envvar~ ([~#18895~](https://github.com/sourcegraph/sourcegraph/pull/18895)) :shipit:
- [x] (🏁 11 days ago) depgraph: ~Make it useful~ make it fast ([~#18915~](https://github.com/sourcegraph/sourcegraph/pull/18915)) :shipit:
- [x] (🏁 8 days ago) depgraph: Refactor ([~#18943~](https://github.com/sourcegraph/sourcegraph/pull/18943)) :shipit:
- [x] (🏁 8 days ago) chore: Remove cachefile ([~#18947~](https://github.com/sourcegraph/sourcegraph/pull/18947)) :shipit:
- [x] (🏁 8 days ago) docs: Write usage docs for internal/workerutil ([~#18286~](https://github.com/sourcegraph/sourcegraph/issues/18286); PRs: ~[#18802](https://github.com/sourcegraph/sourcegraph/pull/18802)~)
- [x] (🏁 8 days ago) chore: De-lint package imports ([~#18918~](https://github.com/sourcegraph/sourcegraph/pull/18918)) :shipit:
- [x] (🏁 8 days ago) depgraph: Add additional lints ([~#18952~](https://github.com/sourcegraph/sourcegraph/pull/18952)) :shipit:
- [x] (🏁 7 days ago) depgraph: Add additional lint passes ([~#18960~](https://github.com/sourcegraph/sourcegraph/pull/18960)) :shipit:
- [x] (🏁 7 days ago) depgraph: Update trace command to accept depth ([~#18988~](https://github.com/sourcegraph/sourcegraph/pull/18988)) :shipit:
- [x] (🏁 7 days ago) depgraph: Add trace-internal command ([~#18999~](https://github.com/sourcegraph/sourcegraph/pull/18999)) :shipit:
- [x] (🏁 7 days ago) depgraph: Adopt ffcli ([~#19005~](https://github.com/sourcegraph/sourcegraph/pull/19005)) :shipit:
- [x] (🏁 6 days ago) depgraph: Add summary subcommand ([~#19037~](https://github.com/sourcegraph/sourcegraph/pull/19037)) :shipit:
- [x] (🏁 6 days ago) chore: Package import lint pass ([~#19007~](https://github.com/sourcegraph/sourcegraph/pull/19007)) :shipit:
- [x] (🏁 5 days ago) lib: Introduce non-enterprise lib directory ([~#18992~](https://github.com/sourcegraph/sourcegraph/pull/18992)) :shipit:
- [x] (🏁 5 days ago) codeintel: More intelligently read from result chunks ([~#18620~](https://github.com/sourcegraph/sourcegraph/issues/18620); PRs: ~[#19010](https://github.com/sourcegraph/sourcegraph/pull/19010)~)
- [x] (🏁 today) Code intelligence result types in hovers shouldn't be dismissible  ([~#17582~](https://github.com/sourcegraph/sourcegraph/issues/17582); PRs: ~[#18843](https://github.com/sourcegraph/sourcegraph/pull/18843)~)
- [x] (🏁 today) Add result type label to the code intelligence tooltip ([~#18929~](https://github.com/sourcegraph/sourcegraph/issues/18929); PRs: ~[#18843](https://github.com/sourcegraph/sourcegraph/pull/18843)~)
- [x] (🏁 today) Add result type label to the references panel ([~#18930~](https://github.com/sourcegraph/sourcegraph/issues/18930); PRs: ~[#18843](https://github.com/sourcegraph/sourcegraph/pull/18843)~)
- [x] (🏁 today) Update the alert in code intelligence tooltips ([~#18931~](https://github.com/sourcegraph/sourcegraph/issues/18931); PRs: ~[#18843](https://github.com/sourcegraph/sourcegraph/pull/18843)~)
- [x] (🏁 today) codeIntel: Add pings for # repos ([~#18832~](https://github.com/sourcegraph/sourcegraph/issues/18832); PRs: ~[#18846](https://github.com/sourcegraph/sourcegraph/pull/18846)~)

@olafurpg

Completed
- [x] (🏁 11 days ago) Add documentation website ([~#112~](https://github.com/sourcegraph/lsif-java/pull/112)) :shipit:

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by Strum355** [comment]
All work around lsif-java and lsif-semanticdb:
- teaching da crew how 2 LSIF
- documentation field in semanticdb spec n co for javadoc/scaladoc in hovers
- added snapshot generating command to lsif-java for from semanticdb output
- some fixes and more to come in lsif-java :tada:

**Comment by efritz** [comment]
Continued in https://github.com/sourcegraph/sourcegraph/issues/19137.
