### ISSUE TITLE
batch: implement RFC 325 for global progressive rollout

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#18921]
High level plan:

* [x] Add new site configuration entries to the schema. (#19796)
* [x] Implement basic window handling functions based on that configuration: what's open, and when. (also #19796)
* [x] Prototype scheduler. (#19797)
* [x] Add the new "scheduled" state for changesets. (also #19797)
* [x] Wire up the scheduler to pull from this state and enqueue. (also also #19797)
* [x] Initial UI: "when will my changeset be processed?". (#19951)
* [ ] Documentation.

**Comment by malomarrec** [comment]
@LawnGnome is this going to be included in the 3.27 release (minus the missing UI work)?

**Comment by LawnGnome** [comment]
> @LawnGnome is this going to be included in the 3.27 release (minus the missing UI work)?

Just to close the loop on what actually happened: this is fully included in 3.27! Just working on the docs now.
