### ISSUE TITLE
RFC 345: Keyboard Navigation in Sourcegraph – Tracking issue

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#19023]
### Context

Tracking implementation for [RFC 345: Keyboard Navigation in Sourcegraph](https://docs.google.com/document/d/1_r8aikiE-zwn0ZkWmOilynNVA3HfmF9Mglgg6ZEkkls/edit#).

### Tracked issues

@AlicjaSuska

- [ ] https://github.com/sourcegraph/sourcegraph/issues/19018 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27771 
  - [x] (🏁 691 days ago) https://github.com/sourcegraph/sourcegraph/issues/19022 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

@quinnkeast

- [ ] https://github.com/sourcegraph/sourcegraph/issues/19020 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

@taras-yemets

- [ ] https://github.com/sourcegraph/sourcegraph/issues/19021 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
