### ISSUE TITLE
Public code on Cloud release (Milestone 3)

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#19139]
This issue tracks the soft release of public code on sourcegraph.com which we refer to as [milestone 3 in product board](https://sourcegraph.productboard.com/feature-board/2119755-core-application/features/5981869/detail)

### Blocking Issues

- [x] [repos: make GitLab repo syncing support OAuth token](https://github.com/sourcegraph/sourcegraph/issues/19136) 
- [ ] [SetExternalServiceRepos GraphQL query takes a long time](https://github.com/sourcegraph/sourcegraph/issues/19235)
- [x] [UserRepositories GraphQL query takes a long time](https://github.com/sourcegraph/sourcegraph/issues/19223) 
- [x] [No entrypoint for adding public code without first adding a code host](https://github.com/sourcegraph/sourcegraph/issues/19161)
- [ ]  Add GitLab Auth provider for dotcom #16745
- [ ] Sort selected repositories at top of list in subsequent loads of "Manage repos" view #18780
- [ ] When adding invalid tokens (think bla-bla-42) for GitHub code host, backend doesn't report warnings/errors #18740
- [ ] In "Manage repos" view, searching while viewing paginated page other the the first is broken.
- [x] [Public repos are not listed in UserSettingsRepositoryPage if the user doesn't also have repos added via a code host. ](https://github.com/sourcegraph/sourcegraph/issues/19162)
- [ ] [GraphQL DeleteExternalService is slow](https://github.com/sourcegraph/sourcegraph/issues/18730)

### Steps for release

- [ ] Enable for all current sourcegraph employees
- [ ] Announce in Slack
- [ ] Handle internal feedback (Add issues here once we have them)
- [ ] Enable for all users by removing code paths that check for the feature. This should be enabled for sourcegraph.com only
