### ISSUE TITLE
Code Intelligence Iteration 8 Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#19137]
### Plan

This sprint covers 2021-03-15 through 2021-03-26.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

Eric: 10d
Maria: TODO
Owen: 6D (Out 24th- 31st)
Noah: 8d (17th & 22nd)
Roux: 6d
Olaf: TODO
TJ: TODO

### Tracked issues

@Strum355

- [ ] 0-char reference, extraneous definition and duplicate reference ranges from anonymous classes ([#124](https://github.com/sourcegraph/lsif-java/issues/124))
- [ ] WIP: add signature pretty-printer to lsif-semanticdb conversion process ([#131](https://github.com/sourcegraph/lsif-java/pull/131)) :shipit:

Completed
- [x] (🏁 12 days ago) Emit definition occurences for type parameters ([~#125~](https://github.com/sourcegraph/lsif-java/pull/125)) :shipit:
- [x] (🏁 5 days ago) Type and Signatures are not emitted ([~#123~](https://github.com/sourcegraph/lsif-java/issues/123))
- [x] (🏁 5 days ago) Emit SemanticDB types and signatures ([~#126~](https://github.com/sourcegraph/lsif-java/pull/126)) :shipit:
- [x] (🏁 3 days ago) codeintel: fix range-contains off-by-one end character check ([~#19450~](https://github.com/sourcegraph/sourcegraph/pull/19450)) :shipit:
- [x] (🏁 3 days ago) Missing definition occurrence for method type parameters ([~#128~](https://github.com/sourcegraph/lsif-java/issues/128); PRs: ~[#129](https://github.com/sourcegraph/lsif-java/pull/129)~)
- [x] (🏁 today) Occurrences for class type parameters are not emitted ([~#122~](https://github.com/sourcegraph/lsif-java/issues/122))

@efritz

- [ ] Refresh lsif-node ([#19362](https://github.com/sourcegraph/sourcegraph/issues/19362))
- [ ] ~codeintel: More intelligently page/paginate lsifstore diagnostic results~ ([#18249](https://github.com/sourcegraph/sourcegraph/issues/18249))
- [ ] ~codeintel: Split diagnostics into separate column~ ([#18289](https://github.com/sourcegraph/sourcegraph/issues/18289))
- [ ] ~codeintel: Do a better job distributing result chunk values~ ([#18242](https://github.com/sourcegraph/sourcegraph/issues/18242))
- [ ] ~codeintel: Split hover text into separate column~ ([#18251](https://github.com/sourcegraph/sourcegraph/issues/18251))
- [ ] ~codeintel: More intelligently page/paginate lsifstore bulk moniker results~ ([#18554](https://github.com/sourcegraph/sourcegraph/issues/18554))

Completed
- [x] (🏁 13 days ago) Fix race condition in TestRunMigratorMigrationChangesDirection ([~#19127~](https://github.com/sourcegraph/sourcegraph/issues/19127); PRs: ~[#19153](https://github.com/sourcegraph/sourcegraph/pull/19153)~) 🐛
- [x] (🏁 4 days ago) extension host: Permanent HTTPStatusError after transient error ([~#19433~](https://github.com/sourcegraph/sourcegraph/issues/19433))
- [x] (🏁 2 days ago) Change misleading "no locations found" text ([~#19467~](https://github.com/sourcegraph/sourcegraph/pull/19467)) :shipit:
- [x] (🏁 2 days ago) docs: Write triage docs for code intelligence ([~#19361~](https://github.com/sourcegraph/sourcegraph/issues/19361); PRs: ~[#19490](https://github.com/sourcegraph/sourcegraph/pull/19490)~)

@olafurpg

Completed
- [x] (🏁 5 days ago) Implement LSIF emitter in Java. ([~#127~](https://github.com/sourcegraph/lsif-java/pull/127)) :shipit:

@shrouxm

- [ ] Write a cleaner/more general version of grailbio/bazel-compilation-database ([#18186](https://github.com/sourcegraph/sourcegraph/issues/18186))

Completed
- [x] (🏁 10 days ago) codeintel: add dev tool for diffing of semantic indexes ([~#19247~](https://github.com/sourcegraph/sourcegraph/pull/19247)) :shipit:
- [x] (🏁 today) codeintel: Write tool to compare LSIF dumps for semantic equality, and output semantic diffs ([~#18183~](https://github.com/sourcegraph/sourcegraph/issues/18183))

@tjdevries

- [ ] Write a cleaner/more general version of grailbio/bazel-compilation-database ([#18186](https://github.com/sourcegraph/sourcegraph/issues/18186))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by efritz** [comment]
Continued in https://github.com/sourcegraph/sourcegraph/issues/19533.
