### ISSUE TITLE
Sourcegraph for Public Code: API docs MVP Tracking issue

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#19281]
### Plan

In the next 2-3 months, implement something like godoc.org but for Go and TypeScript based on LSIF data. This should involve lots of iteration and internal testing, so that developers at Sourcegraph see obvious and immediate value in it.

The end result at 2-3 months should be on-par or better-than the state o the art for Go and TypeScript, but may still be rough around the edges and/or marked as experimental.

### Tracked issues

@slimsag

- [ ] API docs: MVP for Go (experimental/prototype state) Tracking issue ([#19389](https://github.com/sourcegraph/sourcegraph/issues/19389))
  - [ ] API docs: scope out initial project implementation ([#19385](https://github.com/sourcegraph/sourcegraph/issues/19385))
  - [ ] API docs: define rough user experience, workflows ([#19386](https://github.com/sourcegraph/sourcegraph/issues/19386))
  - [ ] API docs: figure out exact data requirements from LSIF ([#19387](https://github.com/sourcegraph/sourcegraph/issues/19387))
  - [ ] API docs: propose LSIF extensions ([#19388](https://github.com/sourcegraph/sourcegraph/issues/19388))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
