### ISSUE TITLE
Internal launch of Cloud milestone 3

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#19370]
- [x] Enable for all current sourcegraph employees
  - I added the tag for all users who are site admins or members of the 'sourcegraph' org
- [x] Announce in Slack
- [x] Handle internal feedback (Label them with bug and cloud/milestone-3)
- [x] Enable for all users by setting `"externalService.userMode": "public",`
