### ISSUE TITLE
API docs: public MVP for Go (in experimental status, but enabled for all users on Sourcegraph.com) Tracking issue

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#19389]
### Plan

Sourcegraph.com features API docs for Go, of equal or better caliber than existing solutions such as https://pkg.go.dev

See [API docs: product UX, LSIF investments, layout challenges, implementation roadmap](https://docs.google.com/document/d/1A7nMPv0DtO1M3S5IgHAhjUPlGXCnmxpQwIOs6cLbBDI/edit#heading=h.bea1pa8wttnv)

**Timeline:** TBD.

### Tracked issues

@unassigned

Completed
- [x] (🏁 42 days ago) make lsif-go support the new Sourcegraph documentation extension ([~#19591~](https://github.com/sourcegraph/sourcegraph/issues/19591))

@slimsag: __54.00d__

- [ ] API docs: MVP for TypeScript (experimental/prototype state) Tracking issue ([#19390](https://github.com/sourcegraph/sourcegraph/issues/19390)) __27.00d__
  - [x] (🏁 61 days ago) API docs: scope out initial project implementation ([~#19385~](https://github.com/sourcegraph/sourcegraph/issues/19385)) __1.00d__
  - [x] (🏁 61 days ago) API docs: define rough user experience, workflows ([~#19386~](https://github.com/sourcegraph/sourcegraph/issues/19386)) __1.00d__
  - [x] (🏁 61 days ago) API docs: figure out exact data requirements from LSIF ([~#19387~](https://github.com/sourcegraph/sourcegraph/issues/19387)) __10.00d__
  - [x] (🏁 61 days ago) API docs: propose and get approval on LSIF extensions ([~#19388~](https://github.com/sourcegraph/sourcegraph/issues/19388)) __10.00d__
  - [x] (🏁 21 days ago) API docs: make them visible to Google ([~#19391~](https://github.com/sourcegraph/sourcegraph/issues/19391)) __5.00d__
  - [x] (🏁 42 days ago) make LSIF backend store new Sourcegraph LSIF documentation extension ([~#19592~](https://github.com/sourcegraph/sourcegraph/issues/19592))
  - [x] (🏁 42 days ago) enable querying data from new Sourcegraph LSIF documentation extension via GraphQL ([~#19593~](https://github.com/sourcegraph/sourcegraph/issues/19593))
- [ ] API docs: ability to hover/definition/find-references on anything in signatures ([#21930](https://github.com/sourcegraph/sourcegraph/issues/21930))
- [ ] API docs: usage examples ([#21932](https://github.com/sourcegraph/sourcegraph/issues/21932))
- [ ] API docs: Google is indexing them in any form ([#21933](https://github.com/sourcegraph/sourcegraph/issues/21933))
- [ ] API docs: Go iota are not grouped logically ([#21937](https://github.com/sourcegraph/sourcegraph/issues/21937)) 🐛
- [ ] golang/go LSIF index needs updating ([#22439](https://github.com/sourcegraph/sourcegraph/issues/22439))

Completed: __54.00d__
- [x] (🏁 61 days ago) lsif/protocol: implement Sourcegraph documentation extension ([~#20108~](https://github.com/sourcegraph/sourcegraph/pull/20108)) :shipit:
- [x] (🏁 61 days ago) API docs: figure out exact data requirements from LSIF ([~#19387~](https://github.com/sourcegraph/sourcegraph/issues/19387)) __10.00d__
- [x] (🏁 61 days ago) API docs: define rough user experience, workflows ([~#19386~](https://github.com/sourcegraph/sourcegraph/issues/19386)) __1.00d__
- [x] (🏁 61 days ago) API docs: scope out initial project implementation ([~#19385~](https://github.com/sourcegraph/sourcegraph/issues/19385)) __1.00d__
- [x] (🏁 61 days ago) API docs: propose and get approval on LSIF extensions ([~#19388~](https://github.com/sourcegraph/sourcegraph/issues/19388)) __10.00d__
- [x] (🏁 61 days ago) API docs: implement LSIF extensions for Go LSIF indexer / langserver ([~#19395~](https://github.com/sourcegraph/sourcegraph/issues/19395)) __15.00d__
- [x] (🏁 51 days ago) lsif/protocol: add Sourcegraph documentation extension read/write support ([~#20568~](https://github.com/sourcegraph/sourcegraph/pull/20568)) :shipit:
- [x] (🏁 42 days ago) make LSIF backend store new Sourcegraph LSIF documentation extension ([~#19592~](https://github.com/sourcegraph/sourcegraph/issues/19592))
- [x] (🏁 42 days ago) enable querying data from new Sourcegraph LSIF documentation extension via GraphQL ([~#19593~](https://github.com/sourcegraph/sourcegraph/issues/19593))
- [x] (🏁 40 days ago) API docs: MVP/barebones webapp frontend for Go ([~#19397~](https://github.com/sourcegraph/sourcegraph/issues/19397); PRs: ~[#21224](https://github.com/sourcegraph/sourcegraph/pull/21224)~) __12.00d__
- [x] (🏁 21 days ago) API docs: make them visible to Google ([~#19391~](https://github.com/sourcegraph/sourcegraph/issues/19391)) __5.00d__
- [x] (🏁 21 days ago) API docs: make Go docs better than state-of-the-art ([~#19392~](https://github.com/sourcegraph/sourcegraph/issues/19392))
- [x] (🏁 16 days ago) API docs: make lsif-go emit data for documentation -> definition/references/hover ([~#21945~](https://github.com/sourcegraph/sourcegraph/issues/21945))
- [x] (🏁 14 days ago) API docs: "missing LSIF data" and "missing LSIF **documentation** data" states not handled separately ([~#22060~](https://github.com/sourcegraph/sourcegraph/issues/22060))
- [x] (🏁 14 days ago) API docs: Go: `var _ = ...` is included ([~#22029~](https://github.com/sourcegraph/sourcegraph/issues/22029)) 🐛
- [x] (🏁 14 days ago) API docs: non-top-level var/const are included ([~#22030~](https://github.com/sourcegraph/sourcegraph/issues/22030))
- [x] (🏁 7 days ago) API docs: symbols not sorted ([~#22306~](https://github.com/sourcegraph/sourcegraph/issues/22306))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
