### ISSUE TITLE
API docs: MVP for TypeScript (experimental/prototype state) Tracking issue

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#19390]
### Plan

Sourcegraph.com features API docs for TypeScript, of equal or better caliber than existing solutions (such as https://pkg.go.dev for Go)

See [API docs: product UX, LSIF investments, layout challenges, implementation roadmap](https://docs.google.com/document/d/1A7nMPv0DtO1M3S5IgHAhjUPlGXCnmxpQwIOs6cLbBDI/edit#heading=h.bea1pa8wttnv)

**Timeline:** TBD.

### Tracked issues

@slimsag: __54.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/19393 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/19396  __15.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/19398  __12.00d__

Completed: __27.00d__
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/issues/19389  __27.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
