### ISSUE TITLE
API docs: implement LSIF extensions for Go LSIF indexer / langserver

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#19395]
Depends on:

* [ ] API docs: scope out initial project implementation (#19385)
* [ ] API docs: define rough user experience, workflows (#19386)
* [ ] API docs: figure out exact data requirements from LSIF (#19387)
* [ ] API docs: propose LSIF extensions (#19388)

This will involve actually implementing and landing the extensions we propose in the lsif-go codebase https://github.com/sourcegraph/lsif-go

I have not looked at that codebase, but anticipate this will take ~3 weeks approx.

**Comment by slimsag** [comment]
Superseded by https://github.com/sourcegraph/sourcegraph/issues/19591
