### ISSUE TITLE
API docs: MVP/barebones webapp frontend for Go

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#19397]
Depends on:

* [ ] API docs: scope out initial project implementation (#19385)
* [ ] API docs: define rough user experience, workflows (#19386)
* [ ] API docs: figure out exact data requirements from LSIF (#19387)
* [ ] API docs: propose LSIF extensions (#19388)
* [ ] API docs: implement LSIF extensions for Go LSIF indexer / langserver (#19395)

At this point, we would have the data we need from LSIF but will need to put together an actual webapp frontend for Go API docs, i.e. "draw the rest of the owl".

This issue would be closed as soon as we have any basic version of functioning Go docs on sourcegraph.com, limited to just the Sourcegraph org if needed. Then, we will file follow-up issues and prioritize accordingly, which may be where the most substantial amount of time is spent before being able to say "we've done it" for Go.

For the general idea of how this would function from a product UX point of view, see: [API docs: product UX, LSIF investments, layout challenges, implementation roadmap](https://docs.google.com/document/d/1A7nMPv0DtO1M3S5IgHAhjUPlGXCnmxpQwIOs6cLbBDI/edit#heading=h.bea1pa8wttnv)

**Comment by slimsag** [comment]
**Last week**

I have a document detailing our data requirements from LSIF, exploring how LSIF/LSP meets that today, and discussing some LSIF/LSP extensions I plan to propose in the future: https://docs.google.com/document/d/1NcNYXOnprknfHkSTMOh1ST8een-NQUVuWCg5DbMmksM/edit?usp=sharing

I have a much clearer picture today about what we need to get to a usable Go MVP today (mostly Go indexer work, no new LSIF extensions) than I did e.g. even yesterday.

I have pushed various stakeholders to commit to specific high-level goals, and have gotten much clearer direction on that and general agreement on the implementation plan, etc.

**Comment by slimsag** [comment]
**This week**

I was out one day getting my vaccine. 20% of my time was spent handling customer incidents and helping others internally.

I discussed with Jean and Malo requirements from Nick, and got agreement on why focusing on search right off the bat (before hitting the MVP) would not make sense. In response to all of this, I have put together and initial "User problem" that we are solving, and worked with Jean and Malo to refine it. - you can find it in the [implementation plan](https://docs.google.com/document/d/1A7nMPv0DtO1M3S5IgHAhjUPlGXCnmxpQwIOs6cLbBDI/edit#heading=h.vl654olludq7)

2d was spent looking into lsif-go; I merged my first PR there and learned about how the codeintel test suite works. I continue to work on https://github.com/sourcegraph/sourcegraph/issues/19591 and am not blocked on anything.
