### ISSUE TITLE
Code Intelligence Iteration 9 Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#19533]
### Plan

This iteration covers through 2021-04-10.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

Eric: 10d
Owen: 6d
Maria: 8d
Olaf: TODO
TJ: TODO
Noah: 8d (2nd and 5th)
Roux: 5d (5th)

### Tracked issues

@Strum355

- [ ] codeintel: surface errors in upload stage of LSIF dump uploading in the UI ([#18375](https://github.com/sourcegraph/sourcegraph/pull/18375)) :shipit:
- [ ] Failed LSIF uploads not reflected in uploads UI ([#18188](https://github.com/sourcegraph/sourcegraph/issues/18188)) 🐛
- [ ] fix range building for tabs or mixed tabs/spaces files ([#171](https://github.com/sourcegraph/lsif-java/pull/171)) :shipit:

Completed
- [x] (🏁 17 days ago) Add signature pretty-printer to lsif-semanticdb conversion process ([~#131~](https://github.com/sourcegraph/lsif-java/pull/131)) :shipit:
- [x] (🏁 10 days ago) fix textDocument/reference -> textDocument/references ([~#149~](https://github.com/sourcegraph/lsif-java/pull/149)) :shipit:
- [x] (🏁 4 days ago) fix range building for all constructors ([~#151~](https://github.com/sourcegraph/lsif-java/pull/151)) :shipit:
- [x] (🏁 4 days ago) add pretty-printing of annotations on symbols ([~#148~](https://github.com/sourcegraph/lsif-java/pull/148)) :shipit:
- [x] (🏁 4 days ago) fix ctor range via textsearch & dont emit ref to class in ctro call ([~#156~](https://github.com/sourcegraph/lsif-java/pull/156)) :shipit:
- [x] (🏁 3 days ago) Pretty-print `throws` clause in method signatures ([~#160~](https://github.com/sourcegraph/lsif-java/pull/160)) :shipit:
- [x] (🏁 3 days ago) dont emit references for 'this' ([~#159~](https://github.com/sourcegraph/lsif-java/pull/159)) :shipit:
- [x] (🏁 3 days ago) Reduce emitted occurences noise from anonymous classes ([~#158~](https://github.com/sourcegraph/lsif-java/pull/158)) :shipit:

@davejrt

Completed
- [x] (🏁 10 days ago) large migrations fail due to liveness checks ([~#19757~](https://github.com/sourcegraph/sourcegraph/issues/19757))

@efritz

- [ ] codeintel: The lifecycle configuration is broken for MinIO ([#19729](https://github.com/sourcegraph/sourcegraph/issues/19729); PRs: ~[#19787](https://github.com/sourcegraph/sourcegraph/pull/19787)~, ~[#19788](https://github.com/sourcegraph/sourcegraph/pull/19788)~)
- [ ] codeintel: More intelligently page/paginate lsifstore bulk moniker results ([#18554](https://github.com/sourcegraph/sourcegraph/issues/18554); PRs: ~[#18549](https://github.com/sourcegraph/sourcegraph/pull/18549)~)
- [ ] codeintel: More intelligently page/paginate lsifstore diagnostic results ([#18249](https://github.com/sourcegraph/sourcegraph/issues/18249))
- [ ] blog: Write about the code intelligence commit graph optimization effort ([#17379](https://github.com/sourcegraph/sourcegraph/issues/17379))
- [ ] Refresh lsif-node ([#19362](https://github.com/sourcegraph/sourcegraph/issues/19362))
- [ ] dev-ex: Speed up database tests ([#19604](https://github.com/sourcegraph/sourcegraph/pull/19604)) :shipit:
- [ ] RFC 311: Out of band migrations Tracking issue ([#18252](https://github.com/sourcegraph/sourcegraph/issues/18252))
  - [x] (🏁 18 days ago) RFC 311: Add site-admin UI page to view migrations ([~#18344~](https://github.com/sourcegraph/sourcegraph/pull/18344)) :shipit:

Completed
- [x] (🏁 20 days ago) schemadoc: Use Postgres 12 ([~#19545~](https://github.com/sourcegraph/sourcegraph/pull/19545)) :shipit:
- [x] (🏁 20 days ago) server: Install Postgres 12 in Dockerfile ([~#19566~](https://github.com/sourcegraph/sourcegraph/pull/19566)) :shipit:
- [x] (🏁 20 days ago) dev: Update dev/start to put any installed postgres version on PATH ([~#19564~](https://github.com/sourcegraph/sourcegraph/pull/19564)) :shipit:
- [x] (🏁 20 days ago) dev: Update postgres container for squash_migrations.sh ([~#19563~](https://github.com/sourcegraph/sourcegraph/pull/19563)) :shipit:
- [x] (🏁 19 days ago) docker-image: Update codeintel-db to postgres 12 ([~#19574~](https://github.com/sourcegraph/sourcegraph/pull/19574)) :shipit:
- [x] (🏁 19 days ago) docs: Update references to Postgres 9.6 ([~#19565~](https://github.com/sourcegraph/sourcegraph/pull/19565)) :shipit:
- [x] (🏁 19 days ago) database: Require Postgres 12 ([~#19424~](https://github.com/sourcegraph/sourcegraph/pull/19424)) :shipit:
- [x] (🏁 19 days ago) blog: Write announcement on why we're upgrading to Postgres 12 ([~#19359~](https://github.com/sourcegraph/sourcegraph/issues/19359))
- [x] (🏁 18 days ago) codeintel: Add migration to add count of locations in lsif_data_{definitions,references} ([~#18549~](https://github.com/sourcegraph/sourcegraph/pull/18549)) :shipit:
- [x] (🏁 18 days ago) codeintel: Standardize lsifstore out-of-band migrations ([~#18667~](https://github.com/sourcegraph/sourcegraph/pull/18667)) :shipit:
- [x] (🏁 18 days ago) RFC 311: Add site-admin UI page to view migrations ([~#18344~](https://github.com/sourcegraph/sourcegraph/pull/18344)) :shipit:
- [x] (🏁 18 days ago) ~logo: Give a new face to this company~ ([~#19539~](https://github.com/sourcegraph/sourcegraph/pull/19539)) :shipit:
- [x] (🏁 13 days ago) monitoring: Alert on invalid indexes ([~#19694~](https://github.com/sourcegraph/sourcegraph/pull/19694)) :shipit:
- [x] (🏁 12 days ago) docs: Fix half-sentence in oob migration guide ([~#19722~](https://github.com/sourcegraph/sourcegraph/pull/19722)) :shipit:
- [x] (🏁 12 days ago) codeintel: Optimize out-of-band migration queries ([~#19695~](https://github.com/sourcegraph/sourcegraph/pull/19695)) :shipit:
- [x] (🏁 11 days ago) ~uploadstore: Manually expire objects when using MinIO~ ([~#19787~](https://github.com/sourcegraph/sourcegraph/pull/19787)) :shipit:
- [x] (🏁 11 days ago) codeintel: Standardize bulk upload technique ([~#19697~](https://github.com/sourcegraph/sourcegraph/pull/19697)) :shipit:
- [x] (🏁 11 days ago) codeintel: Split hover text into separate column ([~#18251~](https://github.com/sourcegraph/sourcegraph/issues/18251); PRs: ~[#19659](https://github.com/sourcegraph/sourcegraph/pull/19659)~)
- [x] (🏁 11 days ago) ~codeintel: Optimize offline data migrations~ ([~#19677~](https://github.com/sourcegraph/sourcegraph/pull/19677)) :shipit:
- [x] (🏁 11 days ago) codeintel: Do a better job distributing result chunk values ([~#18242~](https://github.com/sourcegraph/sourcegraph/issues/18242); PRs: ~[#19759](https://github.com/sourcegraph/sourcegraph/pull/19759)~)
- [x] (🏁 11 days ago) codeintel: Split diagnostics into separate column ([~#18289~](https://github.com/sourcegraph/sourcegraph/issues/18289); PRs: ~[#19659](https://github.com/sourcegraph/sourcegraph/pull/19659)~)
- [x] (🏁 11 days ago) postgres_exporter: Update build and queries ([~#19731~](https://github.com/sourcegraph/sourcegraph/pull/19731)) :shipit:
- [x] (🏁 10 days ago) large migrations fail due to liveness checks ([~#19757~](https://github.com/sourcegraph/sourcegraph/issues/19757))
- [x] (🏁 10 days ago) ~uploadstore: Omit multipart upload rule when backend is minio~ ([~#19788~](https://github.com/sourcegraph/sourcegraph/pull/19788)) :shipit:
- [x] (🏁 6 days ago) codeintel: Refactor data migrator ([~#19827~](https://github.com/sourcegraph/sourcegraph/pull/19827)) :shipit:

@macraig

- [ ] For milestone 5 list the build tools/project info for each customer we intend to deliver lsif-clang to. ([#17368](https://github.com/sourcegraph/sourcegraph/issues/17368))

Completed
- [x] (🏁 7 days ago) 🚚 LSIF-Java Delivery  ([~#13017~](https://github.com/sourcegraph/sourcegraph/issues/13017))

@olafurpg

Completed
- [x] (🏁 19 days ago) Update documentation ([~#132~](https://github.com/sourcegraph/lsif-java/pull/132)) :shipit:
- [x] (🏁 2 days ago) Add support for Gradle v7, fixes #164 ([~#168~](https://github.com/sourcegraph/lsif-java/pull/168)) :shipit:

@shrouxm

- [ ] Hover tooltip shows up seemingly randomly ([#18681](https://github.com/sourcegraph/sourcegraph/issues/18681)) 🐛
- [ ] Write a cleaner/more general version of grailbio/bazel-compilation-database ([#18186](https://github.com/sourcegraph/sourcegraph/issues/18186))

@tjdevries

- [ ] Hover tooltip shows up seemingly randomly ([#18681](https://github.com/sourcegraph/sourcegraph/issues/18681)) 🐛
- [ ] Write a cleaner/more general version of grailbio/bazel-compilation-database ([#18186](https://github.com/sourcegraph/sourcegraph/issues/18186))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by efritz** [comment]
Continuing in https://github.com/sourcegraph/sourcegraph/issues/20149.
