### ISSUE TITLE
Implement RFC312 Site credentials for Batch Changes

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#19571]
## Tasks involved

- [x] Get RFC approved
- [x] Implement site credentials table and store methods
- [x] Make enterprise site admin menu entries configurable
- [x] Implement site credentials UI in admin area
- [x] Use site credentials in reconciler and syncer
- [x] Document deprecation process
- [x] Add documentation on service accounts and where to configure them

RFC issue: https://github.com/sourcegraph/sourcegraph/issues/17919

**Comment by malomarrec** [comment]
@eseliger is this going to be included in this release (3.27)? Sounds like the only missing items are documentation.

**Comment by eseliger** [comment]
Yes it is, we talked about this quickly over zoom. It's part of the changelog and documentation is up for review
