### ISSUE TITLE
WIP: Frontend Platform Design Refresh Tracking issue

### ISSUE THREAD

**Issue by pdubroy** [sourcegraph/sourcegraph#19652]
### Plan

This issue tracks the work by the Frontend Platform team in executing the FY22 design refresh. See [RFC 357: Frontend Platform Refresh Plan](https://docs.google.com/document/d/1Zomc7cb2uWtp86Cvl6_W0r2aaF-vdGREVeCHVOZNMOU/edit#heading=h.trqab8y0kufp) for more discussion.

- [X] New themes defined in global styles, with the ability to turn them on in the web app and Storybook. ([#19653](https://github.com/sourcegraph/sourcegraph/issues/19653))
- [ ] 90% of affected components/pages covered by a visual regression test ([#19520](https://github.com/sourcegraph/sourcegraph/issues/19520))
    - [ ] File Tree. Currently partially supported through Percy. It would be useful to have in the Storybook but not essential. Ticket:  https://github.com/sourcegraph/sourcegraph/issues/19736
    - [X] NavBar. Covered in Storybook: https://5f0f381c0e50750022dc6bf7-kbvryslswx.chromatic.com/?path=/story/web-nav-globalnav--anonymous-viewer
    - [ ] Symbol tree/search. Not captured in either Percy or Storybook. It needs to be done. Ticket: https://github.com/sourcegraph/sourcegraph/issues/19736
    - [x] Code view. Not captured in either Percy or Storybook. I think it would be quickest to capture this through Percy, as we have some integration tests that cover this area. 
    - [x] Reference Panel - PR to add branded component to Storybook: https://github.com/sourcegraph/sourcegraph/pull/19647. It should also be tested through Percy as this component can become quite involved, as that's difficult to replicate through Storybook 
    - [X] Hover Overlay. Covered in Storybook https://5f0f381c0e50750022dc6bf7-kbvryslswx.chromatic.com/?path=/story/shared-hoveroverlay--loading
    - [ ] Branch/Tag/Commits selector. Not captured in either Percy or Storybook. It needs to be done. As this is more of a self container component than a typical page, it would make sense to add to Storybook if possible. Ticket: https://github.com/sourcegraph/sourcegraph/issues/19735 
    - [X] Search Results. Covered in Storybook https://5f0f381c0e50750022dc6bf7-kbvryslswx.chromatic.com/?path=/story/web-search-results-streaming-streamingsearchresults--standard-render
    - [X] Diff View. I believe this is also covered in Storybook: https://5f0f381c0e50750022dc6bf7-kbvryslswx.chromatic.com/?path=/story/web-diffs-filediffnode--all-file-node-states-overview
- [x] Enable screenshot tests in Storybook for dark-mode and redesign-theme to catch regressions. (#19955)
- [ ] Implement new theme in global styles
  - [x] Update color tokens (#19926)
  - [x] Update Bootstrap colors (https://github.com/sourcegraph/sourcegraph/issues/19970)
  - [ ] Better align files that are not using global color variables (https://github.com/sourcegraph/sourcegraph/issues/19970)
  - [x] Update typography (#19954)
- [x] Implement new design for new nav (#20023)
- [x] Introduce a feature flag for the redesign theme (#20444)
- [x] Implement new nav under feature flag (using old styles)
- [x] File tree
- [x] Code
- [x] Diff view

**Comment by valerybugakov** [comment]
@pdubroy, do we want to keep using this tracking issue for the outstanding work we need to accomplish after the redesign release?

It seems it wasn't up to date with all the work that we've been doing recently. Maybe it's better to fall back to just using issues + project board for the outstanding redesign work.
