### ISSUE TITLE
Distribution: Beatrix tasks for distro team rotation

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#19723]
### Plan

An issue to help track any tasks/issue whilst Beatrix is on rotation in the distribution team

### Tracked issues

@abeatrix: __5.50d__

Completed: __5.50d__
- [x] (🏁 11 days ago) Review and test the k8s installation documentation ([~#19727~](https://github.com/sourcegraph/sourcegraph/issues/19727)) __2.00d__
- [x] (🏁 11 days ago) provision GKE cluster for k8s testing ([~#19726~](https://github.com/sourcegraph/sourcegraph/issues/19726)) __0.50d__
- [x] (🏁 11 days ago) Complete k8s onboarding chapters ([~#19725~](https://github.com/sourcegraph/sourcegraph/issues/19725)) __2.00d__
- [x] (🏁 today) add any educational recommendations to CSE on boarding ([~#19728~](https://github.com/sourcegraph/sourcegraph/issues/19728)) __1.00d__

@davejrt: __6.50d__

- [ ] non-root overlays do not deploy successfully ([#19724](https://github.com/sourcegraph/sourcegraph/issues/19724)) __2.00d__

Completed: __4.50d__
- [x] (🏁 11 days ago) Review and test the k8s installation documentation ([~#19727~](https://github.com/sourcegraph/sourcegraph/issues/19727)) __2.00d__
- [x] (🏁 11 days ago) provision GKE cluster for k8s testing ([~#19726~](https://github.com/sourcegraph/sourcegraph/issues/19726)) __0.50d__
- [x] (🏁 11 days ago) Complete k8s onboarding chapters ([~#19725~](https://github.com/sourcegraph/sourcegraph/issues/19725)) __2.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by daxmc99** [comment]
Notes from upgrade walkthrough:

- [ ]  We do not tell users how to add a remote and assume "forking" is commonly understood 
- [ ] Inconsistency with the release tool and SOURCEGRAPH_VERSION
- [ ] Using shell variables without `export` directives
