### ISSUE TITLE
3.26.2 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#19776]
# 3.26.2 managed instances upgrade

These [managed instances](https://about.sourcegraph.com/handbook/engineering/distribution/managed) upgrades are scheduled for **[Apr 8, 2021, 6:00 PM (UTC)](https://time.is/1800_8_Apr_2021_in_UTC?One%20working%20day%20after%203.26.2%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](https://about.sourcegraph.com/handbook/engineering/distribution/managed/upgrade_process).

---

## Upgrade internal managed instances

- [ ] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [ ] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com)

## Upgrade customer managed instances

- [ ] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/1712860829](https://app.hubspot.com/contacts/2762526/company/1712860829/)
- [ ] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/974657309/](https://app.hubspot.com/contacts/2762526/company/974657309/)
- [ ] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/962613882/](https://app.hubspot.com/contacts/2762526/company/962613882/)

---

Also see [3.26.2 patch release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/19775)
