### ISSUE TITLE
Code Intelligence Iteration 10 Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#20149]
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@unassigned

- [ ] sbt support ([#110](https://github.com/sourcegraph/lsif-java/issues/110))
- [ ] Render Scala-specific signatures in hover messages ([#142](https://github.com/sourcegraph/lsif-java/issues/142))
- [ ] Add documentation for how to upload LSIF index to Sourcegraph ([#143](https://github.com/sourcegraph/lsif-java/issues/143))
- [ ] Add new Documentation.Format kind for Signatures, make repeated and upstream ([#145](https://github.com/sourcegraph/lsif-java/issues/145))
- [ ] Document how to setup lsif-java with GitHub Actions ([#146](https://github.com/sourcegraph/lsif-java/issues/146))
- [ ] `super` symbol in anonymous classes points to non-existent local symbol ([#157](https://github.com/sourcegraph/lsif-java/issues/157))
- [ ] Cross-repo navigation does not work for Gradle v2.2.1 ([#167](https://github.com/sourcegraph/lsif-java/issues/167))
- [ ] Render signatures for externally defined symbols ([#174](https://github.com/sourcegraph/lsif-java/issues/174))
- [ ] Bazel support ([#88](https://github.com/sourcegraph/lsif-java/issues/88))
- [ ] Buck support ([#99](https://github.com/sourcegraph/lsif-java/issues/99))

@Strum355

- [ ] emit overridden methods for method SymbolInformation ([#172](https://github.com/sourcegraph/lsif-java/pull/172)) :shipit:
- [ ] Implement SymbolInformation.overrides ([#113](https://github.com/sourcegraph/lsif-java/issues/113))
- [ ] Add additional SymbolInformation properties and upstream them ([#144](https://github.com/sourcegraph/lsif-java/issues/144))

Completed
- [x] (🏁 11 days ago) fix range building for all constructors ([~#151~](https://github.com/sourcegraph/lsif-java/pull/151)) :shipit:
- [x] (🏁 11 days ago) add pretty-printing of annotations on symbols ([~#148~](https://github.com/sourcegraph/lsif-java/pull/148)) :shipit:
- [x] (🏁 10 days ago) fix ctor range via textsearch & dont emit ref to class in ctro call ([~#156~](https://github.com/sourcegraph/lsif-java/pull/156)) :shipit:
- [x] (🏁 10 days ago) dont emit references for 'this' ([~#159~](https://github.com/sourcegraph/lsif-java/pull/159)) :shipit:
- [x] (🏁 9 days ago) Reduce emitted occurences noise from anonymous classes ([~#158~](https://github.com/sourcegraph/lsif-java/pull/158)) :shipit:
- [x] (🏁 6 days ago) fix range building for tabs or mixed tabs/spaces files ([~#171~](https://github.com/sourcegraph/lsif-java/pull/171)) :shipit:
- [x] (🏁 3 days ago) codeintel: add explicit support for MarkupContent in lsif/protocol & optimize hover ingestion ([~#20284~](https://github.com/sourcegraph/sourcegraph/pull/20284)) :shipit:
- [x] (🏁 2 days ago) Exception when building annotation tree in netflix/genie ([~#178~](https://github.com/sourcegraph/lsif-java/issues/178); PRs: ~[#182](https://github.com/sourcegraph/lsif-java/pull/182)~)
- [x] (🏁 2 days ago) Remove `abstract`/`static` from interface signature and pretty-print `default` modifier ([~#176~](https://github.com/sourcegraph/lsif-java/pull/176)) :shipit:
- [x] (🏁 today) Emit `MarkupContent` instead of `MarkedString[]` for hover messages ([~#162~](https://github.com/sourcegraph/lsif-java/issues/162); PRs: ~[#179](https://github.com/sourcegraph/lsif-java/pull/179)~)

@efritz

- [ ] RFC 311: Out of band migrations Tracking issue ([#18252](https://github.com/sourcegraph/sourcegraph/issues/18252))
  - [x] (🏁 3 days ago) RFC 311: Add observability to migration runner ([~#18406~](https://github.com/sourcegraph/sourcegraph/issues/18406); PRs: ~[#18393](https://github.com/sourcegraph/sourcegraph/pull/18393)~, ~[#20304](https://github.com/sourcegraph/sourcegraph/pull/20304)~)
- [ ] codeintel: Add janitor to clean up commits refs now unresolvable by gitserver ([#20357](https://github.com/sourcegraph/sourcegraph/pull/20357)) :shipit:
- [ ] codeintel: Update ctags ([#20381](https://github.com/sourcegraph/sourcegraph/pull/20381)) :shipit:

Completed
- [x] (🏁 13 days ago) codeintel: Auto index Go deps of sg/sg on Cloud ([~#19944~](https://github.com/sourcegraph/sourcegraph/pull/19944)) :shipit:
- [x] (🏁 13 days ago) codeintel: Add ensureUnambiguousResultSets to lsif-validate ([~#19946~](https://github.com/sourcegraph/sourcegraph/pull/19946)) :shipit:
- [x] (🏁 12 days ago) codeintel: Add additional logs to debug dependency indexing in Cloud ([~#19984~](https://github.com/sourcegraph/sourcegraph/pull/19984)) :shipit:
- [x] (🏁 6 days ago) codeintel: Improve logging around sg/sg dependency indexing ([~#20148~](https://github.com/sourcegraph/sourcegraph/pull/20148)) :shipit:
- [x] (🏁 6 days ago) codeintel: Respect edge direction for referenceResult item edges ([~#20160~](https://github.com/sourcegraph/sourcegraph/pull/20160)) :shipit:
- [x] (🏁 6 days ago) codeintel: Improve logging around sg/sg dependency indexing ([~#20165~](https://github.com/sourcegraph/sourcegraph/pull/20165)) :shipit:
- [x] (🏁 5 days ago) codeintel: Find correct oldest commit when calculating commit graph ([~#20230~](https://github.com/sourcegraph/sourcegraph/pull/20230)) :shipit:
- [x] (🏁 5 days ago) codeintel: Simplify committed at migrator batch selection query ([~#20243~](https://github.com/sourcegraph/sourcegraph/pull/20243)) :shipit:
- [x] (🏁 4 days ago) codeintel: Fix update deadlock in commit date migrator ([~#20264~](https://github.com/sourcegraph/sourcegraph/pull/20264)) :shipit:
- [x] (🏁 4 days ago) oobmigration: Re-check progress when we get a refreshed migration record ([~#20273~](https://github.com/sourcegraph/sourcegraph/pull/20273)) :shipit:
- [x] (🏁 4 days ago) codeintel: Only update committed_at on records that don't already have it set ([~#20276~](https://github.com/sourcegraph/sourcegraph/pull/20276)) :shipit:
- [x] (🏁 3 days ago) RFC 311: Add observability to migration runner ([~#18406~](https://github.com/sourcegraph/sourcegraph/issues/18406); PRs: ~[#18393](https://github.com/sourcegraph/sourcegraph/pull/18393)~, ~[#20304](https://github.com/sourcegraph/sourcegraph/pull/20304)~)
- [x] (🏁 3 days ago) codeintel: Stop infinitely processing the same batch of unknown commits ([~#20308~](https://github.com/sourcegraph/sourcegraph/pull/20308)) :shipit:
- [x] (🏁 3 days ago) codeintel: Ensure commit date migrator doesn't get suck on deleted repos ([~#20323~](https://github.com/sourcegraph/sourcegraph/pull/20323)) :shipit:
- [x] (🏁 3 days ago) codeintel: Unwrap vcs.IsRepoNotExist error when checking error ([~#20327~](https://github.com/sourcegraph/sourcegraph/pull/20327)) :shipit:

@olafurpg

- [ ] Implement inference for auto-indexing Java repositories ([#153](https://github.com/sourcegraph/lsif-java/issues/153))
- [ ] Unable to index gradle/gradle repository ([#175](https://github.com/sourcegraph/lsif-java/issues/175))
- [ ] Android gradle support ([#177](https://github.com/sourcegraph/lsif-java/issues/177))

Completed
- [x] (🏁 10 days ago) Enable cross-repo navigation. ([~#166~](https://github.com/sourcegraph/lsif-java/pull/166)) :shipit:
- [x] (🏁 9 days ago) Add support for Gradle v7, fixes #164 ([~#168~](https://github.com/sourcegraph/lsif-java/pull/168)) :shipit:
- [x] (🏁 6 days ago) Add support for the Gradle Playframework plugin. ([~#173~](https://github.com/sourcegraph/lsif-java/pull/173)) :shipit:

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by efritz** [comment]
Continued in https://github.com/sourcegraph/sourcegraph/issues/20149.
