### ISSUE TITLE
Turn on private code for the Sourcegraph Admin team

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#20220]
### Description

This cycle we plan to turn on private code for the Sourcegraph team to start testing this functionality ASAP.  
We need to pay special attention to security.

### Checklist

- [x] test in Dev that users can add see and sync private affiliated repositories using OAuth and personal token (👀  @artemruts. This appears to work for me, @ryanslade)
- [x] adjust UI copy for the "manage repo page" page (https://github.com/sourcegraph/sourcegraph/pull/20221)
- [ ] enable "Sync all repositories" radio option and update label to remove "(coming soon)".  (https://github.com/sourcegraph/sourcegraph/pull/20221)

**QUESTION →** Do we really want to do this? It opens us up to syncing ALL sourcegraph private code by accident before we've fully tested things.

**ANSWER →** Let's wait until all of the outstanding issues and questions raised in https://github.com/sourcegraph/sourcegraph/issues/20530 are answered

- [x] confirm that private repositories successfully sync
- [x] confirm that other user can't find code in the private repo
- [x] confirm that the repo is removed if the user removes it from their list
- [x] confirm that private repos can't be added via the "other public code" list
- [x] confirm existing repository features still work
- [x] enable private code for all Sourcegraph Admin team members
- [x] announce to the team, post a demo. We'll need to explain a couple of things: 
  1. They will need to delete their existing GitHub connection if they've already created one and recreate with a custom token that has the `repo` scope.
  2. GitLab connection should continue to work.
  2. They'll need to be a site admin for this to work at the moment. I don't think we should encourage more users to become site admins to try this out as we want to reduce access at some point.

### [Outstanding issues](#outstanding-issues) 

- [x] When adding code hosts via OAuth `private` scope is missing - private repos are not fetched  https://github.com/sourcegraph/sourcegraph/issues/20229
- [x] Search finds indexed private repo results, but does not display them #20254
- [x] Unauthenticated users can search through private code on Cloud #20253
- [ ] Private repos are not listed for non site admins #20262
- [ ] Site admins can view and search all private code on an instance. This feels like a big security risk given that we have a lot of site admins on Cloud
- [ ] Private affiliated repos don't include private Org repos https://github.com/sourcegraph/sourcegraph/issues/20477

### Acceptance Criteria

1. Users can see and sync affiliated repositories without regression in previously released functionality.
2. No code private code is leaked in any way.

### Notes

Add `AllowUserExternalServicePrivate` user tag to every Sourcegraph Admin teammate for the rollout.

**Comment by ryanslade** [comment]
In order to enable private code for a user you need to add a tag to their user like so:

Assuming you already know their username:

```sql
update users set tags = array_append(tags, 'AllowUserExternalServicePrivate') where username = 'XXX';
```

Unfortunately we don't actually have a consistent way of checking if someone is Sourcegraph employee so we need to run a couple of updates:

All users who are site admin:
```sql
update users set tags = array_append(tags, 'AllowUserExternalServicePrivate') where site_admin=true;
```

All users in the sourcegraph org:
```sql
update users set tags = array_append(tags, 'AllowUserExternalServicePrivate') 
where id in (select user_id from org_members where org_id = 1)
```

**Comment by RafLeszczynski** [comment]
@artemruts 

> enable "Sync all repositories" radio option and update label to remove "(coming soon)". QUESTION: Do we really want to do this? It opens us up to syncing ALL sourcegraph private code by accident before we've fully tested things.

Based on a conversation with @ryanslade I would recommend we do not add this feature now as there is a security risk of indexing private organizations' code. We could add this in the future. 

CC @christinaforney

**Comment by artemruts** [comment]
> @artemruts
> 
> > enable "Sync all repositories" radio option and update label to remove "(coming soon)". QUESTION: Do we really want to do this? It opens us up to syncing ALL sourcegraph private code by accident before we've fully tested things.
> 
> Based on a conversation with @ryanslade I would recommend we do not add this feature now as there is a security risk of indexing private organizations' code. We could add this in the future.
> 
> CC @christinaforney

We can still probably ship [updated UI](https://github.com/sourcegraph/sourcegraph/pull/20221) just disable the private code checks there. Almost nothing will change for the users but we'll be ready on the UI side.

**Comment by ryanslade** [comment]
I replied in the linked PR

**Comment by ryanslade** [comment]
@asdine Handing this over to you for next week

I've updated the tasks at the top with what we still need to do. 

I think since it'll only work for site admins at the moment anyway all we need to do for now is run the following SQL to enable it:

```sql
update users set tags = array_append(tags, 'AllowUserExternalServicePrivate') where site_admin=true;

```

**Comment by ryanslade** [comment]
@artemruts I think we can close this issue now right?

**Comment by artemruts** [comment]
@ryanslade I think so. I'll close it and add the `private-code-for-sg` label for all of the issues in the "outstanding section".
