### ISSUE TITLE
Documentation improvements for 3.2

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2023]
[**3.2 <kbd>docs-ux</kbd> issues**](https://github.com/sourcegraph/sourcegraph/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Adocs-ux)

More details in the private **Feb 2019 planning** Google doc.

## UX improvements

- [x] Simplify docs local testing/review and release process #2465
- [x] Update docs.sourcegraph.com to make 3.2 current #2242
- [x] Document how to update docs.sourcegraph.com as part of release process #2481
- [x] Remove in-product `/help` #2405 #1912 #1720 

## Content improvements

- [x] Link to Mermaid source for code architecture diagram #2355
- [x] Warn admins of potential issues with non-https #259
- [x] Improve NGINX SSL documentation #2466
- [x] make it clear that Sourcegraph owns the repo folder in "Add repositories already cloned to disk" #2479

**Comment by ryan-blunden** [comment]
#2060 has been created to track how and what will be done to improve cross-page navigation and overview. 

sourcegraph/docsite#7 has been created to decide how the page index will be managed. This needs to be decided upon before development can be begin.

**Comment by nicksnyder** [comment]
I have two more things to add to this tracking issue:
1. It is a pain that we have to make a [change to the docsite template to update version links](https://github.com/sourcegraph/docs.sourcegraph.com/commit/d445c460c2da54fba4f56f647d656ca3311decf5) separately from updating the documentation itself.
2. I am not convinced that it is worth the effort for us to maintain our own docsite generator in the long run compared to using an available alternative.

**Comment by francisschmaltz** [comment]
@nicksnyder I agree. We should take something prebuilt that we can iterate on.

**Comment by ryan-blunden** [comment]
@nicksnyder From 3.2 onwards, any docs change (styles, template or content) will be made in the sourcegraph repo and the docs site will be part of the local dev server.

These wins have made docsite worth the effort and I will gradually be taking ownership of the codebase but don't anticipate many more features.

**Comment by ryan-blunden** [comment]
Issues not closed in 3.2 can now be found in the [3.3 documentation improvements tracking issue](https://github.com/sourcegraph/sourcegraph/issues/2848).
