### ISSUE TITLE
Code Intelligence Iteration 10.5 Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#20398]
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

Eric: Out 4/28 (Wed), 4/30 (Fri), 5/7 (Fri), and will be absent for the next retro/planning

### Tracked issues

@Strum355

- [ ] code-intel: make table rows scroll on overflow ([#20556](https://github.com/sourcegraph/sourcegraph/pull/20556)) :shipit:

@efritz

- [ ] codeintel: Write code intelligence input index format specification ([#20401](https://github.com/sourcegraph/sourcegraph/issues/20401))
- [ ] codeintel: Auto-index (pre-module) direct dependencies of sg/sg ([#20404](https://github.com/sourcegraph/sourcegraph/issues/20404))

Completed
- [x] (🏁 8 days ago) codeintel: Update ctags ([~#20381~](https://github.com/sourcegraph/sourcegraph/pull/20381)) :shipit:
- [x] (🏁 7 days ago) codeintel: Bump version of universal-ctags ([~#20402~](https://github.com/sourcegraph/sourcegraph/issues/20402))
- [x] (🏁 7 days ago) codeintel: Rotate secrets ([~#20400~](https://github.com/sourcegraph/sourcegraph/issues/20400))
- [x] (🏁 7 days ago) database: Insert returning in batch inserter ([~#20436~](https://github.com/sourcegraph/sourcegraph/pull/20436)) :shipit:
- [x] (🏁 6 days ago) codeintel: Make upload and index search fields consistent ([~#20467~](https://github.com/sourcegraph/sourcegraph/pull/20467)) :shipit:
- [x] (🏁 4 days ago) codeintel: Re-enable TestCommittedAtMigratorUnknownCommits ([~#20517~](https://github.com/sourcegraph/sourcegraph/pull/20517)) :shipit:
- [x] (🏁 4 days ago) executor: Add execution time limit ([~#20465~](https://github.com/sourcegraph/sourcegraph/pull/20465)) :shipit:
- [x] (🏁 4 days ago) Document Postgres settings suggestions ([~#20403~](https://github.com/sourcegraph/sourcegraph/issues/20403); PRs: ~[#20431](https://github.com/sourcegraph/sourcegraph/pull/20431)~)
- [x] (🏁 4 days ago) codeintel: Add additional state filters to upload and index pages ([~#20468~](https://github.com/sourcegraph/sourcegraph/pull/20468)) :shipit:
- [x] (🏁 4 days ago) ci: Remove failing assertion in TestCommittedAtMigratorUnknownCommits ([~#20533~](https://github.com/sourcegraph/sourcegraph/pull/20533)) :shipit:

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
