### ISSUE TITLE
Improve cross-page navigation and overview to leaf page navigation

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#2060]
The Sourcegraph documentation would benefit from easier discoverability of pages and improved section overview hyperlinks.

## Easier Discovery

Most likely will be in the form of a page index in the left rail.

![screen shot 2019-01-29 at 11 18 24 am](https://user-images.githubusercontent.com/133014/51934437-6f505100-23b8-11e9-8f8e-1298fdbd7004.png)

## Improved section overview links

![screen shot 2019-01-29 at 11 25 12 am](https://user-images.githubusercontent.com/133014/51934491-91e26a00-23b8-11e9-8a16-5f97dd16e978.png)

## ToDo

 - [x] Decide if a config file, frontmatter or directory and file naming control the creation of the index https://github.com/sourcegraph/docsite/issues/7 
 - [ ] Design and functionality of the index
 - [ ] Design of the section overview
 - [ ] Documentation for adding a page and verifying the index entry works

**Comment by beyang** [comment]
Casting my vote for directory structure

**Comment by ryan-blunden** [comment]
For 3.2, the left nav will be hard-coded and in 3.3, it will be config file driven.
