### ISSUE TITLE
Site admin access to private code in Sourcegraph UI

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#20671]
Currently site admins have full access to any private code on an instance with no authorisation checks.

I've listed all the places (that we know of) that expose private code data or the existence of private code. Items that we plan to fix soon include the relevant issue. I've left notes on the other items explaining why they're not yet a high priority.

Viewing code:

* [x] Browsing repositories directly (https://github.com/sourcegraph/sourcegraph/issues/20622)
* [x] Searches that match private code (https://github.com/sourcegraph/sourcegraph/issues/20622)

Viewing the existence of a private repo:

* [x] Site Admin -> Repositories -> Repository status (https://github.com/sourcegraph/sourcegraph/issues/20622)
* [x] Site Admin -> Repositories -> Manage Code host. **NOTE** Code host tokens are redacted in this view. It's possible that the config may contain private repo names however. We could simply not display config for user added external services, would this be acceptable?
* [x] Site Admin -> Code intelligence -> uploads (https://github.com/sourcegraph/sourcegraph/issues/20626)
* [x] Site Admin -> Code intelligence -> autoindexing (https://github.com/sourcegraph/sourcegraph/issues/20626)
* [x] Site Admin -> Users -> Settings. **NOTE** I think the only risk here is exposing access token needed for our language servers. I don't think these are critical.
* [x] Site Admin -> Users -> Saved Searches **NOTE** Could potentially show the names of private repos? (https://github.com/sourcegraph/sourcegraph/issues/20800)
* [x] Site Admin -> Users -> organisations -> Saved searches **NOTE** Could potentially show the names of private repos? (https://github.com/sourcegraph/sourcegraph/issues/20800)
* [x] Show external service config for all users. We should hide this in case they've manually selected private repos. (https://github.com/sourcegraph/sourcegraph/issues/20814)

**Comment by ryanslade** [comment]
I've confirmed with @efritz that access tokens in user settings are not used anymore. 

We *could* remove them but this might feel strange to users. Perhaps we can display a deprecation notice. Either way, I don't think there's a risk if they're leaked.

**Comment by ryanslade** [comment]
@christinaforney @sourcegraph/security Tagging you for visibility

**Comment by unknwon** [comment]
The remaining work from the list are saved Searches of users and organizations.
