### ISSUE TITLE
Improve cloud provider deployment process

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2068]
## User story

> As a developer who wants to use Sourcegraph for my organization's code, I want to deploy Sourcegraph so that my whole organization can access it. This means [for many orgs] installing it on a public cloud provider such as AWS, Google Cloud, DigitalOcean, etc.

## Plan 

- [x] Close out "EC2 with Terraform milestone in" https://github.com/sourcegraph/deploy-sourcegraph-aws/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A%22EC2+with+Terraform%22
- [ ] Dogfood https://github.com/sourcegraph/deploy-sourcegraph-aws/ with some teammates
  - [x] @chrismwendt 
  - [ ] @ggilmore 
  - [ ] @KattMingMing or @attfarhan 
- [ ] Get feedback about https://github.com/sourcegraph/deploy-sourcegraph-aws/ from 1 customer
- [X] Figure out which cloud provider to tackle next: Digital Ocean or ~~Google Cloud~~
   - I will follow the same skeleton used in https://github.com/sourcegraph/deploy-sourcegraph-aws/, but there is some research involved in figuring out the minutae of each cloud provider's offering so that the terrform scripts can be properly ported. It is possible to de-risk this by trying to ask more knowledgeable teammates (e.g. @KattMingMing and DO) for help / and or to take point
- [ ] Publish one more terraform guide for ~~the cloud provider selected above~~ Digital Ocean: https://github.com/sourcegraph/deploy-sourcegraph-digitalocean/

**Comment by slimsag** [comment]
I know this is a tracking issue, but since I have no action items here I am unassigning myself to reflect that. Add me back if there is clear work I need to do here.

**Comment by ggilmore** [comment]
After discussion with @nicksnyder, I am prioritizing https://github.com/sourcegraph/sourcegraph/issues/2579 and https://github.com/sourcegraph/infrastructure/pull/1336 over this issue. The above checklist is still indicative of what needs to be done (most of which @ryan-blunden has already tackled).
