### ISSUE TITLE
Web server: Tracking issue

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#20734]
## Description

This issue tracks the work of improving the standalone web server added in [this PR](https://github.com/sourcegraph/sourcegraph/pull/20126).
Help is welcome ⛑. Let's move the web server to feature parity with the `frontend` server!

## Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/21811 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/21871 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/21904 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/21905 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/21906 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/40474 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 
- [x] (🏁 246 days ago) https://github.com/sourcegraph/sourcegraph/issues/21870 (PRs: ~[#32549](https://github.com/sourcegraph/sourcegraph/pull/32549)~, ~[#47413](https://github.com/sourcegraph/sourcegraph/pull/47413)~)

@5h1rU

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

@sqs

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

@umpox

Completed
- [x] (🏁 729 days ago) https://github.com/sourcegraph/sourcegraph/issues/21869 

@valerybugakov

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
