### ISSUE TITLE
RFC 305 - Extension Registry redesign - Tracking issue

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#20778]
### Description

This is a tracking issue for the [RFC 305](https://docs.google.com/document/d/1AMZkD8BKAX5veTEanWYpy2aD1RAjcWYlAkEfSZbtBgM/edit#heading=h.trqab8y0kufp) Next-Up Extensions Registry “Marketplace” Concepts

### Tracked issues

@tjkandala

- [ ] https://github.com/sourcegraph/sourcegraph/issues/20788 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/21149 

Completed
- [x] (🏁 521 days ago) https://github.com/sourcegraph/sourcegraph/issues/20789 
- [x] (🏁 521 days ago) https://github.com/sourcegraph/sourcegraph/issues/20790 
- [x] (🏁 521 days ago) https://github.com/sourcegraph/sourcegraph/issues/20779 
- [x] (🏁 521 days ago) https://github.com/sourcegraph/sourcegraph/issues/20781 
- [x] (🏁 521 days ago) https://github.com/sourcegraph/sourcegraph/issues/20782 
- [x] (🏁 521 days ago) https://github.com/sourcegraph/sourcegraph/issues/20784 
- [x] (🏁 521 days ago) https://github.com/sourcegraph/sourcegraph/issues/20786 
- [x] (🏁 521 days ago) https://github.com/sourcegraph/sourcegraph/issues/20956 
- [x] (🏁 521 days ago) https://github.com/sourcegraph/sourcegraph/issues/21007 
- [x] (🏁 521 days ago) https://github.com/sourcegraph/sourcegraph/issues/21011  🐛
- [x] (🏁 521 days ago) https://github.com/sourcegraph/sourcegraph/issues/20785 
- [x] (🏁 519 days ago) https://github.com/sourcegraph/sourcegraph/issues/21006 
- [x] (🏁 517 days ago) https://github.com/sourcegraph/sourcegraph/issues/21008 
- [x] (🏁 509 days ago) https://github.com/sourcegraph/sourcegraph/issues/21151 
- [x] (🏁 500 days ago) https://github.com/sourcegraph/sourcegraph/issues/21009 
- [x] (🏁 500 days ago) https://github.com/sourcegraph/sourcegraph/issues/20780 
- [x] (🏁 460 days ago) https://github.com/sourcegraph/sourcegraph/issues/21148 
- [x] (🏁 61 days ago) https://github.com/sourcegraph/sourcegraph/issues/21010

**Comment by sqs** [comment]
We removed the extension registry in 4.0. Closing issue.
