### ISSUE TITLE
[draft] Private code rollout plan

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#20793]
## Outstanding work

<details>
<summary>click for details</summary>
<br/>

**Groups are sorted by priority:**

* ### 🔐 Private code security (Ryan, Joe)
    - [ ] Tracking issue: [Site admin access to private code](https://github.com/sourcegraph/sourcegraph/issues/20671)
    - [ ] ["private repositories" OAuth scope for the users enrolled in the private code test](https://github.com/sourcegraph/sourcegraph/issues/20229)
    - [ ] [ private repos are not listed for non Admin users](https://github.com/sourcegraph/sourcegraph/issues/20262)

* ### 📊 analytics & DB (Indra, Asdine)
    - [ ] [Strip private data before logging events](https://github.com/sourcegraph/sourcegraph/issues/20628)
    - [ ] [<Redacted, see the issue>](https://github.com/sourcegraph/security-issues/issues/147)

* ### 🏁 Post sign-up flow (@artemruts, Asdine)
    - [ ] [post sign-up flow project board](https://github.com/orgs/sourcegraph/projects/125) (sync with @asdine to parallelize)

* ### 📟 User notifications UI (@artemruts, possibly Asdine)
    - [ ] [implement user notifications UI](https://github.com/sourcegraph/sourcegraph/issues/18066)
 
* ### 🤝 Improved sync status for affiliated repositories (Ryan, @artemruts)
    - [ ] [New endpoint to affiliated determine repo sync status](https://github.com/sourcegraph/sourcegraph/issues/20318)
    - [ ] [Improve "saving in progress" UX](https://github.com/sourcegraph/sourcegraph/issues/19826)
  
 * ### 🔑 OAuth code host connection flow (Joe, Indra)
    - [ ] [GitLab OAuth 401 errors](https://github.com/sourcegraph/sourcegraph/issues/19744)
    - [ ] [Revoking access to the Sourcegraph OAuth app doesn't trigger an error with code host connection](https://github.com/sourcegraph/sourcegraph/issues/20391)
    - [ ] [Canceling OAuth code host connection flow doesn't return the user to Sourcegraph](https://github.com/sourcegraph/sourcegraph/issues/20293)
   
* ### 🤗 UX improvements (@artemruts, possibly Asdine)
    - [ ] [Don't rely on ExternalServices -> config.repos](https://github.com/sourcegraph/sourcegraph/pull/20614)
    - [ ] [Improve repository view filtering](https://github.com/sourcegraph/sourcegraph/issues/20136)
    - [ ] [Reduce content jumping](https://github.com/sourcegraph/sourcegraph/issues/19371)
</details>

## Execution plan

I believe all of the above groups of tasks can be worked on in parallel, so my preliminary plan is:

**Sprint of May 4th**
1. Ryan and Joe take on tightening `private code security` + a round of security QA
2. Artem works on `post sign-up flow` to get us to the point where some tasks can be delegated to Asdine
3. Asdine and Indra are working on `analytics & DB`
4. Indra starts to work on `OAuth code host connection flow`

**Sprint of May 18th**
1. Ryan and Joe finish `private code security` tasks
2. Artem and Asdine are work on `post sign-up flow` and `user notifications UI` + a few round of QA with Quinn K
3. Joe and Indra work on `OAuth code host connection flow`
4. Ryan and Artem work `Improved sync status for affiliated repositories` + QA round with Quinn K

**Sprint of June 1st (3 days)**
1. all the toggles are correctly set and we can enable private code with a site-wide config + user tag
2. final rounds of QA

Also need to check when Tomas is back to see what work can be shared.

Downsides:
- _Very_ limited customer support availability, everything is on Alex
- Lots of changes with little QA
- June 4th is Friday
- Not everything labeled `june4th` can be delivered
- How do we know if anything goes wrong, what monitoring do we have?

## Rollout plan

- [ ] everything `private code` related is behind a feature user tag and a site-wide config boolean
- [ ] change log entry is added (@artemruts )
- [ ] team posts the announcement that we'll have 3rd party private code on .com (@artemruts)
- [ ] how will we enable only for specific accounts, we don't know the them?
