### ISSUE TITLE
3.2 code search UX tracking issue

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2081]
Code search, along with [code navigation](https://github.com/sourcegraph/sourcegraph/issues/2070), is one of the 2 main features of Sourcegraph. 

For this milestone (3.2), and the next few moving forward (~6 months or so), we are prioritizing: 
- @attfarhan and @ijsnow's familiarization and ownership over the search codebase 
- improving the current search feature set (stability, UX, etc.)
- improving code quality

We also have a growing backlog of issues and feature requests that should be addressed. We will solve relevant issues, and refactor the codebase as needed. Within ~6 months, we want to be able to build the bigger features of subquery search (#1005) and invoking search extensions on the backend, so we should keep these in mind while we tackle existing issues and improve the code.

For 3.2 specifically, the priorities are improving the search experience for new users and fixing bugs. Therefore, we have laid out the following plan.

## Plan

[**Issues labeled <kbd>search</kbd>**](https://github.com/sourcegraph/sourcegraph/issues?q=is:issue+is:open+sort:updated-desc+label:search+milestone:3.2)

- [ ] https://github.com/sourcegraph/sourcegraph/issues/2125
- [x] https://github.com/sourcegraph/sourcegraph/issues/652
- [ ] https://github.com/sourcegraph/sourcegraph/issues/1234
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/2368
- [ ] https://github.com/sourcegraph/sourcegraph/issues/1624

## Test/review plan

- Code reviewer: project team
- Tester: project team

**Comment by keegancsmith** [comment]
Cool, so the plan is to address some search issues / polish, then finish off sub-query search. A comprehensive list of changes will be useful for when planning finishing off sub-query search, in case a change/feature/fix should be "ported" to sub-query search.

**Comment by sqs** [comment]
> Cool, so the plan is to address some search issues / polish, then finish off sub-query search.

Yeah, except sub-query search (and invoking search extensions) definitely won't be worked on directly in this release cycle. (In case anyone reads your sentence above and thinks otherwise.)

**Comment by nicksnyder** [comment]
Most of these are still open so I am moving this to 3.2. We will discuss in the kickoff on Wednesday.

**Comment by nicksnyder** [comment]
Can you close out this 3.2 tracking issue, include and update about what did/didn't get done, and create a new tracking issue for 3.3?

**Comment by nicksnyder** [comment]
cc @ijt

**Comment by nicksnyder** [comment]
Closing this. 3.3 tracking issue is here: https://github.com/sourcegraph/sourcegraph/issues/2740
