### ISSUE TITLE
Design Refresh: Pre-release checklist

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#20846]
Before pushing the redesign out globally, we must ensure that we:

  - [x] Migrate Bootstrap required SCSS variables like `$primary` and `$indigo` to our redesign variants `$redesign-primary`, `$redesign-indigo`: remove the `@if` statement from the `variables-redesign.scss` file.
  - [x] Disable redesign toggle. We can append `theme-redesign` to the DOM for the initial release, and we don't want anyone using the old design whilst we haven't yet removed those styles
  - [x] Change the implementation of the `useRedesignToggle` to always return `[true, ()=>{}]`.
  - [x] Fix search tests to pass when streaming search is enabled permanently
  - [x] Fix GlobalNavBar.test.tsx failing when redesign is enabled
  - [x] Fix Percy theme changing to work on pages where the search bar is not displayed
  - [x] Remove Percy redesign variants.
  - [x] Remove Chromatic redesign variants in `Chromatic.story.tsx`.

**Comment by limitedmage** [comment]
We also have to make sure that `useRedesignToggle` returns (e.g.) `[true, ()=>{}]` so that components that use different logic depending on the redesign also continue to work. Otherwise we are relying on a localStorage value that may not be present.

**Comment by valerybugakov** [comment]
@limitedmage, added suggested changes to the checklist.
