### ISSUE TITLE
Design Refresh: Post-release checklist

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#20847]
After we have pushed the redesign out globally, we must ensure that we:

- [x] Replace `styles.scss` files with `styles-redesign.scss` where suitable.
- [x] https://github.com/sourcegraph/sourcegraph/issues/23718
- [x] Remove usage of `isThemeRedesign` local storage key.
- [x] Remove `theme-redesign` class, redesign styles should be applied without needing this. #23794
- [x] Remove `theme-classic` class and all styles associated with it.
- [x] Remove `redesign-d-none` class.
- [x] Investigate removing or re-configuring Bootstrap imports, as we may have less of a dependency on them.
- [x] Replace legacy semantic colors: https://github.com/sourcegraph/sourcegraph/issues/19973.
- [x] Remove `RedesignToggleDecorator` from Storybook. @umpox
- [x] Remove `RedesignToggleStorybook` from Storybook. @umpox
- [x] Remove legacy `border-radius-sm` and `border-radius-lg` from use https://github.com/sourcegraph/sourcegraph/issues/21106
- [x] Remove old `MonacoEditor` themes and make the redesign themes the standard ones #21988
- [x] Remove `StreamingSearchResultsFilterBars`, `SearchResultsFilterBars` and `SearchResultTypeTabs` components (requires #21529) #21898
- [x] Remove `web-content.scss` file and all usages of `.web-content` in code

**Comment by valerybugakov** [comment]
Closed [duplicated checklist](https://github.com/sourcegraph/sourcegraph/issues/20843) and added missing items from it.

**Comment by umpox** [comment]
Added https://github.com/sourcegraph/sourcegraph/issues/21106
