### ISSUE TITLE
Code monitors getting started page becomes unauthed landing page

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21161]
Currently, the code monitors page on cloud displays login page for unauthenticated users. We need to repurpose the code-monitors/getting started page to be a developer-friendly landing page for unauthed users. The page should provide a high level introduction to code monitors and ask the user to sign up to begin using them. 

This page could use a similar user flow and CTA style as [the batch changes getting started page](https://github.com/sourcegraph/sourcegraph/issues/21158) or a better design effort here should inform that page's design. 

![image](https://user-images.githubusercontent.com/539268/121756490-1ab45900-cacf-11eb-802e-7752fbab02ee.png)

https://www.figma.com/file/6WMfHdPt2ovTE1P527brwc/Code-monitor-getting-started-(%2321161)?node-id=4%3A754&viewport=368%2C396%2C0.25

Implementation plan:

- [x] Create `w1-signup-optimisation` typesafe feature flag in code #22271
- [x] Extract "Getting started" to its own component instead of making it part of code monitoring page #22271
- [x] Show "Getting started" tab in code monitoring page (right now there is no tab, user only sees the page if they have no monitors) #22274
- [x] Build new "Getting started" UI, replacing the old UI (regardless of feature flag) #22331
- [x] If feature flag is on, unauthenticated users should be redirected to "Getting started" page instead of redirecting to sign in #22356
  - [x] Hide "Create" button on top right of Code Monitoring page if user is not signed in #22356
  - [x] Show sign up CTAs instead of "Create" button in middle of page and feedback section on bottom right if user is not signed in #22356
- [x] Create empty view for code monitoring list and allow authenticated users users to see it
  - [x] Authenticated users should only be redirected to "Getting started" page if they don't have any code monitors **and** they haven't seen the "Getting started" page yet (using a localStorage flag)
 - [x] Add metrics logging (waiting on @rrhyne for what metrics will be logged)
 - [x] Create `w1-signup-optimisation` feature flag on Sourcegraph.com to start testing
 - [x] Remove `w1-signup-optimisation` flag

**Comment by malomarrec** [comment]
Only > 0.1% of users go to this page, so this has a minimal projected impact on retention. 
Tagging with retention-impact/low.
See [analytics](https://analytics.google.com/analytics/web/#/report/content-pages/a40540747w150533180p155508056/_u.date00=20210501&_u.date01=20210601&explorer-segmentExplorer.segmentId=analytics.pagePath&explorer-table.plotKeys=%5B%5D&explorer-table.filter=code-monitoring&explorer-graphOptions.selected=analytics.nthMonth).

**Comment by rrhyne** [comment]
Figma file:

https://www.figma.com/file/6WMfHdPt2ovTE1P527brwc/Code-monitor-getting-started-(%2321161)?node-id=4%3A754&viewport=368%2C396%2C0.25

**Comment by malomarrec** [comment]
I this lands, we'll A/B test under the `w0-signup-optimisation` flag

**Comment by novoselrok** [comment]
> @novoselrok the PR removing the feature flag has been merged. Should this issue be closed?

Correct, closed it now.
