### ISSUE TITLE
V1 Code Insights Docs: Tracking Issue

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#21172]
### Plan

For the first rapid-creation pass over code insights docs, to pair with our new creation flow. 

### Availability

(As necessary to get done.)

### Tracked issues

@Joelkw

Completed
- [x] (🏁 21 days ago) Placeholder code insights doc update, live for <1 week ([~#21171~](https://github.com/sourcegraph/sourcegraph/pull/21171)) :shipit:
- [x] (🏁 20 days ago) Two code insight quickstart guides ([~#21176~](https://github.com/sourcegraph/sourcegraph/pull/21176)) :shipit:
- [x] (🏁 19 days ago) Added administration and security explanation ([~#21218~](https://github.com/sourcegraph/sourcegraph/pull/21218)) :shipit:

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
