### ISSUE TITLE
Remove GraphQL search UI from webapp

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#21267]
GraphQL search UI has been deprecated since we made streaming search the default. With the redesign, GraphQL search UI will be completely disabled. We should remove the code.

This also requires migrating the experimental search console page to streaming search UI.

Note: This does NOT remove the GraphQL search API. That API will continue to exists. This just removes the UI that calls that API from the webapp in favor of streaming search.

This requires multiple steps:
- [x] Remove GraphQL search UI from search console page #21484
- [x] Deprecate `searchStreaming` feature flag and make streaming UI the permanent default [21522](https://github.com/sourcegraph/sourcegraph/pull/21522)
- [x] Remove `SearchResults` and `SearchResultsList` components [#21529](https://github.com/sourcegraph/sourcegraph/pull/21529)
- [x] Remove `StreamingSearchResultsFilterBars`, `SearchResultsFilterBars` and `SearchResultTypeTabs` components (once redesign has been permanently enabled) #21898
- [x] Move styles from `SearchResults.scss` and `SearchResultsList.scss` to CSS modules for `StreamingSearchResults` and `StreamingSearchResultsList` #21898
- [x] Remove GraphQL type conversions in `stream.ts`. Modify `FileMatch` and `SearchResult` components to use streaming search types instead of GraphQL types. #22024
- [ ] Move all contents of `client/web/src/search/results/streaming` up one level and delete the `streaming` folder #22070
