### ISSUE TITLE
Code Insights 3.29 release – Tracking issue

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#21322]
### Plan

All tasks that we want to release **before 3.29 cut** 
**Code freeze data**: 18 Jule

@unassigned: __3.00d__

- [ ] Code Insights Creation UI: Tracking issue ([#20212](https://github.com/sourcegraph/sourcegraph/issues/20212)) __3.00d__
  - [ ] Make the query input in the Code Insight creation UI a real search box, with autocompletion, syntax highlighting and toggles ([#21339](https://github.com/sourcegraph/sourcegraph/issues/21339)) __3.00d__

@coury-clark: __1.00d__

Completed: __1.00d__
- [x] (🏁 13 days ago) Include creation UI event logs in backend pings ([~#21527~](https://github.com/sourcegraph/sourcegraph/issues/21527)) __1.00d__

@vovakulikov: __13.00d__

- [ ] Code Insights Creation UI: Tracking issue ([#20212](https://github.com/sourcegraph/sourcegraph/issues/20212)) __7.00d__
  - [x] (🏁 17 days ago) Add autosuggestions to repository field in code insight create form ([~#20198~](https://github.com/sourcegraph/sourcegraph/issues/20198); PRs: ~[#21699](https://github.com/sourcegraph/sourcegraph/pull/21699)~, ~[#21814](https://github.com/sourcegraph/sourcegraph/pull/21814)~) __2.00d__
  - [x] (🏁 34 days ago) Align search query input of code insight creation form ([~#20201~](https://github.com/sourcegraph/sourcegraph/issues/20201)) __2.00d__
  - [x] (🏁 19 days ago) Code insights creation forms should save my progress if I navigate away from the page ([~#21098~](https://github.com/sourcegraph/sourcegraph/issues/21098); PRs: ~[#21744](https://github.com/sourcegraph/sourcegraph/pull/21744)~) __1.00d__
  - [x] (🏁 16 days ago) Add creating from search-query result functionality for code-insights ([~#21323~](https://github.com/sourcegraph/sourcegraph/issues/21323); PRs: ~[#21943](https://github.com/sourcegraph/sourcegraph/pull/21943)~) __2.00d__

Completed: __13.00d__
- [x] (🏁 34 days ago) Align search query input of code insight creation form ([~#20201~](https://github.com/sourcegraph/sourcegraph/issues/20201)) __2.00d__
- [x] (🏁 33 days ago) Add Codecov project for insights to track test coverage ([~#21241~](https://github.com/sourcegraph/sourcegraph/issues/21241); PRs: ~[#21348](https://github.com/sourcegraph/sourcegraph/pull/21348)~) __0.50d__ 🧶
- [x] (🏁 33 days ago) Code insights error handling breaks badly on FF relative to Chrome ([~#20336~](https://github.com/sourcegraph/sourcegraph/issues/20336)) 🐛
- [x] (🏁 26 days ago) Running a code insight over a timeframe when the repo didn't yet exist in Sourcegraph breaks the entire insight, but it should just not display data for that date(s) ([~#20772~](https://github.com/sourcegraph/sourcegraph/issues/20772); PRs: ~[#21288](https://github.com/sourcegraph/sourcegraph/pull/21288)~, ~[#5](https://github.com/sourcegraph/sourcegraph-search-insights/pull/5)~) 🐛
- [x] (🏁 19 days ago) Creation UI URL hierarchy ([~#21012~](https://github.com/sourcegraph/sourcegraph/issues/21012)) __0.50d__
- [x] (🏁 19 days ago) Code insights creation forms should save my progress if I navigate away from the page ([~#21098~](https://github.com/sourcegraph/sourcegraph/issues/21098); PRs: ~[#21744](https://github.com/sourcegraph/sourcegraph/pull/21744)~) __1.00d__
- [x] (🏁 18 days ago) Code Insights Setup testing — Tracking issue ([~#21240~](https://github.com/sourcegraph/sourcegraph/issues/21240)) __3.00d__
- [x] (🏁 17 days ago) Add autosuggestions to repository field in code insight create form ([~#20198~](https://github.com/sourcegraph/sourcegraph/issues/20198); PRs: ~[#21699](https://github.com/sourcegraph/sourcegraph/pull/21699)~, ~[#21814](https://github.com/sourcegraph/sourcegraph/pull/21814)~) __2.00d__
- [x] (🏁 16 days ago) Add creating from search-query result functionality for code-insights ([~#21323~](https://github.com/sourcegraph/sourcegraph/issues/21323); PRs: ~[#21943](https://github.com/sourcegraph/sourcegraph/pull/21943)~) __2.00d__
- [x] (🏁 13 days ago) Include creation UI event logs in backend pings ([~#21527~](https://github.com/sourcegraph/sourcegraph/issues/21527)) __1.00d__
- [x] (🏁 13 days ago) Code insight charts may have weird negative y-labels ([~#20046~](https://github.com/sourcegraph/sourcegraph/issues/20046)) __1.00d__ 🐛
- [x] (🏁 11 days ago) Add limit to number of repos resolved from search query for 1-click insight creation ([~#22159~](https://github.com/sourcegraph/sourcegraph/issues/22159))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
