### ISSUE TITLE
Worker tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#21756]
### Plan

This issue tracks progress of moving the background-tasks out from the frontend and repo-updater services. Because engineers knew how these services were deployed, it made it very easy for the answer to "where does this code go" to be "put it in the background of the frontend/repo-updater" more than it should have been.

Original POC can be found [in this old PR](https://github.com/sourcegraph/sourcegraph/pull/21537).

Similar discussions/goals:
- [Sunset repo-updater](https://github.com/sourcegraph/sourcegraph/issues/16197)
- [Isolate code intel background processes](https://github.com/sourcegraph/sourcegraph/issues/18253)

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/21766 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/21770 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/21771 

Completed
- [x] (🏁 644 days ago) https://github.com/sourcegraph/sourcegraph/issues/21781 
- [x] (🏁 440 days ago) https://github.com/sourcegraph/sourcegraph/issues/21767 

@Strum355

- [ ] https://github.com/sourcegraph/sourcegraph/issues/22175 

Completed
- [x] (🏁 694 days ago) https://github.com/sourcegraph/sourcegraph/pull/24008 

@efritz

- [ ] https://github.com/sourcegraph/sourcegraph/issues/21765 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/21993 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/22175 

Completed
- [x] (🏁 858 days ago) https://github.com/sourcegraph/sourcegraph/issues/21757 (PRs: ~[#21768](https://github.com/sourcegraph/sourcegraph/pull/21768)~)
- [x] (🏁 857 days ago) https://github.com/sourcegraph/sourcegraph/issues/21758 (PRs: ~[#21774](https://github.com/sourcegraph/sourcegraph/pull/21774)~)
- [x] (🏁 855 days ago) https://github.com/sourcegraph/sourcegraph/pull/21779 
- [x] (🏁 855 days ago) https://github.com/sourcegraph/sourcegraph/pull/21837 
- [x] (🏁 854 days ago) https://github.com/sourcegraph/sourcegraph/issues/21761 
- [x] (🏁 853 days ago) https://github.com/sourcegraph/sourcegraph/pull/21926 
- [x] (🏁 853 days ago) https://github.com/sourcegraph/sourcegraph/issues/21762 (PRs: ~[#21842](https://github.com/sourcegraph/sourcegraph/pull/21842)~)
- [x] (🏁 852 days ago) https://github.com/sourcegraph/sourcegraph/issues/21764 (PRs: ~[#21925](https://github.com/sourcegraph/sourcegraph/pull/21925)~)
- [x] (🏁 852 days ago) https://github.com/sourcegraph/sourcegraph/issues/21763 (PRs: ~[#21977](https://github.com/sourcegraph/sourcegraph/pull/21977)~)
- [x] (🏁 852 days ago) https://github.com/sourcegraph/sourcegraph/issues/21760 (PRs: ~[#21948](https://github.com/sourcegraph/sourcegraph/pull/21948)~)
- [x] (🏁 845 days ago) https://github.com/sourcegraph/sourcegraph/issues/21759 (PRs: ~[#21924](https://github.com/sourcegraph/sourcegraph/pull/21924)~)
- [x] (🏁 617 days ago) https://github.com/sourcegraph/sourcegraph/issues/30297 

@eseliger

Completed
- [x] (🏁 328 days ago) https://github.com/sourcegraph/sourcegraph/issues/21782 

@mrnugget

- [ ] https://github.com/sourcegraph/sourcegraph/issues/22175 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by daxmc99** [comment]
Will/is this service included in the single container deployment?

**Comment by efritz** [comment]
@daxmc99 It's already present in the enterprise build and was fixed by https://github.com/sourcegraph/sourcegraph/pull/22621 in the OSS build.
