### ISSUE TITLE
Code Insights Dashboards V1 Tracking issue

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#22215]
### Plan

Eventually, at the end of this issue, we want to have minimal working versions of the code insights dashboard. 

**Estimated to be complete by** _Friday, 2021-07-09_

### Related documents
- [Design proposal and tech thoughts](https://docs.google.com/document/d/1qHFFS53Ca3gmbi8jODUaPnkpu05CyqPi_VuAXKbmtsk/edit?usp=sharing) 
- [Low-fi designs sketches ](https://www.figma.com/file/g5lSlPBnHt00wCogjRFnt5/RFC-398%3A-Easily-Viewing-and-Sharing-Code-Insights-WIP?node-id=260%3A11)

### Info 
Our experimental feature flag for the dashboard functionality is:
```json
"experimentalFeatures": { "codeInsightsDashboards":  true }
```

### Tracked issues

@coury-clark: __2.00d__

Completed: __2.00d__
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/22533 (PRs: ~[#22695](https://github.com/sourcegraph/sourcegraph/pull/22695)~) __2.00d__

@vovakulikov: __14.00d__

Completed: __14.00d__
- [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/pull/22290 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/issues/22216 (PRs: ~[#22309](https://github.com/sourcegraph/sourcegraph/pull/22309)~) __1.50d__
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/22217 (PRs: ~[#22317](https://github.com/sourcegraph/sourcegraph/pull/22317)~) __2.00d__
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/22218 (PRs: ~[#22409](https://github.com/sourcegraph/sourcegraph/pull/22409)~) __1.50d__
- [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/issues/22225 (PRs: ~[#22409](https://github.com/sourcegraph/sourcegraph/pull/22409)~, ~[#22423](https://github.com/sourcegraph/sourcegraph/pull/22423)~, ~[#22474](https://github.com/sourcegraph/sourcegraph/pull/22474)~) __2.00d__
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/22462 (PRs: ~[#22565](https://github.com/sourcegraph/sourcegraph/pull/22565)~) 🧶
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/22228 (PRs: ~[#22564](https://github.com/sourcegraph/sourcegraph/pull/22564)~) __0.50d__
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/22231 (PRs: ~[#22620](https://github.com/sourcegraph/sourcegraph/pull/22620)~) __1.00d__
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/pull/22643 
- [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/22235  __1.00d__
- [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/22233 (PRs: ~[#22748](https://github.com/sourcegraph/sourcegraph/pull/22748)~) __2.00d__
- [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/22559 (PRs: ~[#22769](https://github.com/sourcegraph/sourcegraph/pull/22769)~) __1.50d__
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/22232 (PRs: ~[#22800](https://github.com/sourcegraph/sourcegraph/pull/22800)~) __1.00d__
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/22835 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/22851 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/22868 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/22886 
- [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/pull/22913 
- [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/pull/22967 
- [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/pull/22987 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/23017 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/22970 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/23022 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by vovakulikov** [comment]
All remaining tickets have been moved to this next tracking issue about dashboard v2 
https://github.com/sourcegraph/sourcegraph/issues/22920
