### ISSUE TITLE
GraphQL Client adoption: Tracking Issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#22496]
### Plan
We want to refactor more code to use [Apollo](https://docs.sourcegraph.com/dev/background-information/web/graphql#graphql-client).

Key actions:
- Migrating from `requestGraphQL | queryGraphQL | mutateGraphQL` usage to [useMutation and useQuery](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/graphql/graphql.ts?L127-157) hooks.
- Utilising the [Apollo cache](https://docs.sourcegraph.com/dev/background-information/web/graphql#how-do-i-use-the-apollo-cache) by adding the correct `id` fields to queries or providing alternative [keyFields](https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-identifier-generation-by-type) to use.

This tracking issue is to capture the work required to migrate much of the codebase to this new approach.

**Note**: While working on refactoring code, it would also be beneficial to clean up and simplify requests where we can. This [PR comment from Rok](https://github.com/sourcegraph/sourcegraph/pull/40263/files/06d001af01d76041472609e49f60c23b1f6dab64#r946393225) is just one example of the types of fetching functions we'd hope to clean up. The goal would be to improve readability and make these functions much easier to debug when there are issues.

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/22507 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/25035 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

@gitstart-sourcegraph

- [ ] https://github.com/sourcegraph/sourcegraph/issues/22507 
  - [x] (🏁 742 days ago) https://github.com/sourcegraph/sourcegraph/issues/24952 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

@valerybugakov

- [ ] https://github.com/sourcegraph/sourcegraph/issues/22507 
  - [x] (🏁 765 days ago) https://github.com/sourcegraph/sourcegraph/pull/24586 
  - [x] (🏁 757 days ago) https://github.com/sourcegraph/sourcegraph/pull/24639 
  - [x] (🏁 735 days ago) https://github.com/sourcegraph/sourcegraph/pull/24644 
  - [x] (🏁 757 days ago) https://github.com/sourcegraph/sourcegraph/pull/24866 
  - [x] (🏁 757 days ago) https://github.com/sourcegraph/sourcegraph/pull/24867 
  - [x] (🏁 756 days ago) https://github.com/sourcegraph/sourcegraph/pull/24868 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 690 days ago) https://github.com/sourcegraph/sourcegraph/issues/24869 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
