### ISSUE TITLE
insights: Insights setting persistence migration tracking issue

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#22524]
### Plan
Currently all code insights metadata is stored in Sourcegraph user / org / global settings. In the short term this is a useful tool for iteration. The long term storage location for all of this insight metadata should be in a persistent data storage and retrieved through an API.

### Release plan

We will release the new API in 3.34 with a feature flag default-on, which can be turned off by customers in case they run into issues.

This API will be released behind a feature flag in 3.34 that will be default enabled. If the flag is disabled, Code Insights will revert to using settings as the primary storage.

When the flag is enabled, all interactions with Code Insights will occur through the GraphQL API. Any changes or updates made during this time will not be synced back to settings, such that disabling the feature flag will revert the state prior to the flag being enabled. It is also possible to enter partially broken states, where backend insights were deleted that can no longer be resolved from the Database but is still referenced from settings files.

With the flag disabled, Code Insights will treat settings files as the source of truth for insight definitions, and continue to resolve backend insight data from the database.

Insights and dashboards that were previously created prior to the release of this API will be migrated in a job that runs regularly. 

Once the API is stable and we are ready to retire the settings based storage permanently, we will do the following:
1. Retire all settings related interactions for storing insights
2. Retire the feature flag
3. Ship an out of band migration to perform a final one time pass over all settings files and migrate insights and dashboards.

At this point, it will no longer be possible to revert to using settings files for insight definitions.

### Tracked issues

@unassigned: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/26794  🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26800  🐛
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26948 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27089  🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27148  🐛
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27149  🐛
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26905 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26679 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26666  🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27151  🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27288 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27460 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27463  🧶   🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26537    🏳️ [Insights iteration 9](https://github.com/sourcegraph/sourcegraph/milestone/149)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27923  🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/28512  🐛
- [ ] https://github.com/sourcegraph/sourcegraph/issues/25653 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26384 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26436 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26442    🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/29050 

Completed: __2.00d__
- [x] (🏁 176 days ago) https://github.com/sourcegraph/sourcegraph/issues/22812  __0.50d__ 🧶
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/issues/22811  __0.50d__ 🧶
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/issues/22820  __1.00d__ 🧶
- [x] (🏁 147 days ago) https://github.com/sourcegraph/sourcegraph/issues/22815  🎩
- [x] (🏁 142 days ago) https://github.com/sourcegraph/sourcegraph/issues/22819  🎩
- [x] (🏁 107 days ago) https://github.com/sourcegraph/sourcegraph/issues/22817  🧶
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/26789 
- [x] (🏁 72 days ago) https://github.com/sourcegraph/sourcegraph/issues/26903 
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/issues/27449  🧶   🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)

@AlicjaSuska

Completed
- [x] (🏁 75 days ago) https://github.com/sourcegraph/sourcegraph/issues/25697 

@CristinaBirkel

- [ ] https://github.com/sourcegraph/sourcegraph/issues/26757    🏳️ [Insights iteration 10](https://github.com/sourcegraph/sourcegraph/milestone/150)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27836    🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/28623  🐛   🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27214    🏳️ [Insights iteration 9](https://github.com/sourcegraph/sourcegraph/milestone/149)

Completed
- [x] (🏁 104 days ago) https://github.com/sourcegraph/sourcegraph/issues/25649    🏳️ [Insights iteration 3](https://github.com/sourcegraph/sourcegraph/milestone/130)
- [x] (🏁 99 days ago) https://github.com/sourcegraph/sourcegraph/issues/22818  🧶   🏳️ [Insights iteration 3](https://github.com/sourcegraph/sourcegraph/milestone/130)
- [x] (🏁 97 days ago) https://github.com/sourcegraph/sourcegraph/issues/25652    🏳️ [Insights iteration 3](https://github.com/sourcegraph/sourcegraph/milestone/130)
- [x] (🏁 97 days ago) https://github.com/sourcegraph/sourcegraph/issues/25924    🏳️ [Insights iteration 3](https://github.com/sourcegraph/sourcegraph/milestone/130)
- [x] (🏁 93 days ago) https://github.com/sourcegraph/sourcegraph/issues/25708    🏳️ [Insights iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/136)
- [x] (🏁 90 days ago) https://github.com/sourcegraph/sourcegraph/issues/26309    🏳️ [Insights iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/136)
- [x] (🏁 85 days ago) https://github.com/sourcegraph/sourcegraph/issues/22816  🧶   🏳️ [Insights iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/136)
- [x] (🏁 84 days ago) https://github.com/sourcegraph/sourcegraph/issues/26378    🏳️ [Insights iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/136)
- [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/issues/25979    🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 75 days ago) https://github.com/sourcegraph/sourcegraph/issues/26676    🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 69 days ago) https://github.com/sourcegraph/sourcegraph/issues/26675    🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 67 days ago) https://github.com/sourcegraph/sourcegraph/issues/27146  🕵️   🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/issues/26533    🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/issues/24481    🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 44 days ago) https://github.com/sourcegraph/sourcegraph/issues/27889  🐛   🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/issues/28700  🐛   🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/issues/28505  🐛   🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 37 days ago) https://github.com/sourcegraph/sourcegraph/issues/27983    🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/29487  🐛   🏳️ [Insights iteration 9](https://github.com/sourcegraph/sourcegraph/milestone/149)
- [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/issues/28504  🐛   🏳️ [Insights iteration 9](https://github.com/sourcegraph/sourcegraph/milestone/149)

@Joelkw

Completed
- [x] (🏁 75 days ago) https://github.com/sourcegraph/sourcegraph/issues/25697 

@coury-clark: __5.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27836    🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27928 

Completed: __5.00d__
- [x] (🏁 183 days ago) https://github.com/sourcegraph/sourcegraph/issues/22810  __2.00d__ 🧶
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/issues/22814  __1.00d__ 🧶
- [x] (🏁 169 days ago) https://github.com/sourcegraph/sourcegraph/issues/22821  __2.00d__ 🧶
- [x] (🏁 105 days ago) https://github.com/sourcegraph/sourcegraph/issues/25648 
- [x] (🏁 103 days ago) https://github.com/sourcegraph/sourcegraph/issues/25659 
- [x] (🏁 103 days ago) https://github.com/sourcegraph/sourcegraph/issues/22809  🧶
- [x] (🏁 99 days ago) https://github.com/sourcegraph/sourcegraph/issues/25654 
- [x] (🏁 99 days ago) https://github.com/sourcegraph/sourcegraph/issues/25650 
- [x] (🏁 89 days ago) https://github.com/sourcegraph/sourcegraph/issues/24441    🏳️ [Insights iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/136)
- [x] (🏁 89 days ago) https://github.com/sourcegraph/sourcegraph/issues/26525    🏳️ [Insights iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/136)
- [x] (🏁 85 days ago) https://github.com/sourcegraph/sourcegraph/issues/26377    🏳️ [Insights iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/136)
- [x] (🏁 85 days ago) https://github.com/sourcegraph/sourcegraph/issues/25719    🏳️ [Insights iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/136)
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/26451    🏳️ [Insights iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/136)
- [x] (🏁 77 days ago) https://github.com/sourcegraph/sourcegraph/issues/26660 
- [x] (🏁 77 days ago) https://github.com/sourcegraph/sourcegraph/issues/26807  🐛
- [x] (🏁 77 days ago) https://github.com/sourcegraph/sourcegraph/issues/27032  🐛
- [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/issues/26388    🏳️ [Insights iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/136)
- [x] (🏁 75 days ago) https://github.com/sourcegraph/sourcegraph/issues/26458  🐛   🏳️ [Insights iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/136)
- [x] (🏁 75 days ago) https://github.com/sourcegraph/sourcegraph/issues/26452    🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 72 days ago) https://github.com/sourcegraph/sourcegraph/issues/27208    🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 71 days ago) https://github.com/sourcegraph/sourcegraph/issues/25971    🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 71 days ago) https://github.com/sourcegraph/sourcegraph/issues/27245  🐛   🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 68 days ago) https://github.com/sourcegraph/sourcegraph/issues/27451  🐛   🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 68 days ago) https://github.com/sourcegraph/sourcegraph/issues/27452  🐛   🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/25196    🏳️ [Insights iteration 6](https://github.com/sourcegraph/sourcegraph/milestone/140)
- [x] (🏁 61 days ago) https://github.com/sourcegraph/sourcegraph/issues/27917  🐛   🏳️ [Insights iteration 6](https://github.com/sourcegraph/sourcegraph/milestone/140)
- [x] (🏁 58 days ago) https://github.com/sourcegraph/sourcegraph/issues/27837  🐛   🏳️ [Insights iteration 6](https://github.com/sourcegraph/sourcegraph/milestone/140)
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/issues/26533    🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 44 days ago) https://github.com/sourcegraph/sourcegraph/issues/27889  🐛   🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/issues/27306    🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/issues/29055  🐛   🏳️ [Insights iteration 8](https://github.com/sourcegraph/sourcegraph/milestone/148)
- [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/issues/28504  🐛   🏳️ [Insights iteration 9](https://github.com/sourcegraph/sourcegraph/milestone/149)

@unclejustin

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27221    🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27222    🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)

Completed
- [x] (🏁 86 days ago) https://github.com/sourcegraph/sourcegraph/issues/25878 (PRs: ~[#26481](https://github.com/sourcegraph/sourcegraph/pull/26481)~)   🏳️ [Insights iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/136)
- [x] (🏁 70 days ago) https://github.com/sourcegraph/sourcegraph/issues/25876    🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 70 days ago) https://github.com/sourcegraph/sourcegraph/issues/25877 (PRs: ~[#26422](https://github.com/sourcegraph/sourcegraph/pull/26422)~)   🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 70 days ago) https://github.com/sourcegraph/sourcegraph/issues/27220    🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 70 days ago) https://github.com/sourcegraph/sourcegraph/issues/27323    🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 68 days ago) https://github.com/sourcegraph/sourcegraph/issues/27218    🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/27769    🏳️ [Insights iteration 6](https://github.com/sourcegraph/sourcegraph/milestone/140)
- [x] (🏁 62 days ago) https://github.com/sourcegraph/sourcegraph/issues/27863  🐛   🏳️ [Insights iteration 6](https://github.com/sourcegraph/sourcegraph/milestone/140)

@vovakulikov

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27221    🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27222    🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27214    🏳️ [Insights iteration 9](https://github.com/sourcegraph/sourcegraph/milestone/149)

Completed
- [x] (🏁 91 days ago) https://github.com/sourcegraph/sourcegraph/pull/26151 
- [x] (🏁 91 days ago) https://github.com/sourcegraph/sourcegraph/pull/26235 
- [x] (🏁 86 days ago) https://github.com/sourcegraph/sourcegraph/pull/26382 
- [x] (🏁 72 days ago) https://github.com/sourcegraph/sourcegraph/pull/26422 
- [x] (🏁 71 days ago) https://github.com/sourcegraph/sourcegraph/issues/25874 (PRs: ~[#26149](https://github.com/sourcegraph/sourcegraph/pull/26149)~)   🏳️ [Insights iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/136)
- [x] (🏁 69 days ago) https://github.com/sourcegraph/sourcegraph/issues/27217    🏳️ [Insights iteration 5](https://github.com/sourcegraph/sourcegraph/milestone/137)
- [x] (🏁 65 days ago) https://github.com/sourcegraph/sourcegraph/issues/27219    🏳️ [Insights iteration 6](https://github.com/sourcegraph/sourcegraph/milestone/140)
- [x] (🏁 65 days ago) https://github.com/sourcegraph/sourcegraph/issues/27223    🏳️ [Insights iteration 6](https://github.com/sourcegraph/sourcegraph/milestone/140)
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/27769    🏳️ [Insights iteration 6](https://github.com/sourcegraph/sourcegraph/milestone/140)
- [x] (🏁 62 days ago) https://github.com/sourcegraph/sourcegraph/issues/27863  🐛   🏳️ [Insights iteration 6](https://github.com/sourcegraph/sourcegraph/milestone/140)
- [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/issues/27914    🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/issues/27911  🐛   🏳️ [Insights iteration 8](https://github.com/sourcegraph/sourcegraph/milestone/148)
- [x] (🏁 34 days ago) https://github.com/sourcegraph/sourcegraph/issues/28579  🐛   🏳️ [Insights iteration 8](https://github.com/sourcegraph/sourcegraph/milestone/148)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

### Test plans:

In https://github.com/sourcegraph/sourcegraph/issues/26593

**Comment by felixfbecker** [comment]
@coury-clark I think you need the `tracking` label, not `tracking-issue` (don't know what that other label is used for)

**Comment by felixfbecker** [comment]
Just to be clear, this is a plan for post-Beta, right? (thanks for creating this!)

**Comment by coury-clark** [comment]
> Just to be clear, this is a plan for post-Beta, right? (thanks for creating this!)

Likely a few of these will be done before so that we can fix some of the outstanding issues relevant to stateless processing.

**Comment by yinquanteo** [comment]
(from @Joelkw. pushing that update here for posterity. this issue shows up in the [Code Graph board](https://github.com/orgs/sourcegraph/projects/208/views/1))

Status: On track to move from "user settings files as a database" to an actual database (amazing!)

**Comment by coury-clark** [comment]
Closing this issue since we are now tracking this via project board https://github.com/orgs/sourcegraph/projects/200/views/7
