### ISSUE TITLE
insights: frontend / backend integration

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#22647]
### Plan
We want to integrate and unify the extensions code insights with the backend that is capable of running insights over many repositories.

**Estimated to be completed by**: Friday, 2021-07-16

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@coury-clark: __3.00d__

Completed: __3.00d__
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/18397  __1.00d__
- [x] (🏁 2 days ago) https://github.com/sourcegraph/sourcegraph/issues/22215  __2.00d__

@vovakulikov: __3.00d__

Completed: __3.00d__
- [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/22760  __1.00d__
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/22759  __2.00d__
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/22488 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
