### ISSUE TITLE
SSBC-EM: Overview of engineering milestones

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#22764]
The following engineering milestones are extracted from the first draft in our [scratch document](https://docs.google.com/document/d/1hXklrrAerQwpFcOQZELgZoqyxmFOxI7DVEDGJV7sxxg/edit?ts=60d4c942).

While progressing down the list of EMs they will be converted into separate tickets. Each EM might result in follow-up tickets that move into another EM.

- [x] Engineering milestone 0: get something running
- [ ] EM 1: Demo-able SSBC - Customers can see it, but not use it themselves yet
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/22550
  - [ ] EM 1.2: Better debuggable (for team members) execution of batch specs on k8s.sgdev.org:
    - [ ] Implement cancel in executor-queue
    - [ ] Add a namespace param to `createBatchSpecExecution`
    - [ ] Basic streaming of logs
    - [ ] Including UI that updates and possibly formats log output
    - [ ] Allow showing status per task in UI (repository, workspace, current command, stdout, etc.)
    - [ ] Any metrics
    - [ ] Status of executors (# of registered executors)
  - [ ] EM 1.3: We are able to record a GIF/video of SSBC and show it to customers without being embarrassed
    - [ ] Some sort of first round of UI polish
    - [ ] Link to executions on batch change page
    - [ ] Global batch spec executions list page
- [ ] _ROUGH DRAFT_ EM 2: Customers can use single-threaded alpha version of SSBC
  - [ ] 2.1 milestone:
    - [ ] Re-implement caching
      - [ ] Means: since we start src-cli on fresh machines up until this point, we don’t have a hot cache. This step means we need to implement functionality in src-cli that *uploads* the cached results per step and functionality in the backend that checks the cache and tells src-cli/executor-job which cached results to use
    - [ ] https://github.com/sourcegraph/sourcegraph/issues/22763
    - [ ] Retry with slightly adjusted spec input after error
    - [ ] Good “create batch spec” workflow, make it look good when no batch spec exists yet.
    - [ ] “Preview” repository resolving
    - [ ] Long-running batch specs also work reliably
- [ ] _ROUGH DRAFT_ EM 3: Better performance and granularity of steps in UI
  - [ ] Resolve workspaces becomes an execution step
  - [ ] One executor job per workspace (repository+path+commit) execution
  - [ ] src-cli able to execute a batch spec in a given workspace (not doing resolving of workspaces at all)
  - [ ] Asynchronous execution of these jobs using multiple executors
  - [ ] In UI users can selectively look at status/output of execution jobs
  - [ ] Batch spec is created server side
    - That probably means that batch_spec_executions will not be an executor table anymore but more a dbworker and has child batch_spec_workspace_executions executor records. => NO stable API yet
- [ ] _ROUGH DRAFT_ EM 4: Better iteration and debugging on batch specs
  - [ ] Overwrite single steps in repos
  - [ ] View diff after each step
  - [ ] Step wise retries
  - [ ] Visualize output variables

**Comment by chrispine** [comment]
Status: [We deployed our first end-to-end server-side batch change!](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1635288415083500) This is a huge milestone for us, and is the culmination of months of hard work and collaboration. Congrats, team!

[SSBC EM2.3 Cache1](https://github.com/sourcegraph/sourcegraph/issues/26929) tracks the SSBC work we intend to finish this sprint. We also want to finish our MVP of the Create (editor) page, which is found (along with future tasks) [here](https://github.com/sourcegraph/sourcegraph/issues/26142).

**Comment by malomarrec** [comment]
Status: we have a roster of 3 early adopter candidates, that we are meeting with during the next 2 weeks.
- https://github.com/sourcegraph/accounts/issues/537
- https://github.com/sourcegraph/accounts/issues/580
- https://github.com/sourcegraph/accounts/issues/565

The main risk that we are facing so far is timing: with Christmas coming up, our champions and dev tools teams are focusing on internal deadlines and don't have much time to allocate to this until January.

**Comment by malomarrec** [comment]
I don't think this issue is useful anymore, we can go back to using the `server-side` label.
May I close it? cc @eseliger
