### ISSUE TITLE
Better docs for setting up an instance ready for sharing

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#2277]
Ensure the content and process is clear for configuring Sourcegraph to be ready for sharing with a team. 

## Plan

- [ ] Review home page navigation links
- [ ] Update quickstart screencast with new repository syncing UI and flow.
- [x] Review nginx and SSL docs and add a video for running Sourcegraph with SSL.
  - [ ] Update Lets Encrypt docs.
  - [x] Update self-signed cert docs.
- [ ] How to configure Sourcegraph to send emails and why it's important (pass reset, notifications)
- [x] At least one use case video.

## Test/review plan

- Code reviewer: @sqs
- Tester: @sqs

**Comment by ryan-blunden** [comment]
Closing in favor of individual issues linked to from tracking issue.
