### ISSUE TITLE
Wildcard V.1: Tracking Issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#22850]
### Plan
We are moving and refining a set amount of small components to Wildcard as part of a 'v.1' release.

See [Wildcard Components Prioritization](https://docs.google.com/spreadsheets/d/1o_eHs6h7zEHxM75bUMMI6-v7st_-GwJqtSfOaVHlNdk/edit#gid=0) for more information.

### Tracked issues

@5h1rU

Completed
- [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/issues/22843 
- [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/issues/22845 

@umpox

Completed
- [x] (🏁 2 days ago) https://github.com/sourcegraph/sourcegraph/issues/22842 
- [x] (🏁 2 days ago) https://github.com/sourcegraph/sourcegraph/issues/22844 
- [x] (🏁 2 days ago) https://github.com/sourcegraph/sourcegraph/issues/22846 
- [x] (🏁 2 days ago) https://github.com/sourcegraph/sourcegraph/issues/22841 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by umpox** [comment]
Wildcard V1 components can be viewed [here](https://5f0f381c0e50750022dc6bf7-hculgczyce.chromatic.com/?path=/story/wildcard-container--overview) 🎉
