### ISSUE TITLE
Code Insights Dashboard V2 Tracking issue

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#22920]
### Plan
All tickets about code insights dashboards functionalities. Some tickets were moved from the dashboards V1 tracking issue https://github.com/sourcegraph/sourcegraph/issues/22215

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/30603 

@AlicjaSuska

- [ ] https://github.com/sourcegraph/sourcegraph/issues/23003  🙆   🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)

@unclejustin

- [ ] https://github.com/sourcegraph/sourcegraph/issues/22922    🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)

@vovakulikov

- [ ] https://github.com/sourcegraph/sourcegraph/issues/22675 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/22922    🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/23003  🙆   🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 349 days ago) https://github.com/sourcegraph/sourcegraph/issues/23070 

Completed
- [x] (🏁 810 days ago) https://github.com/sourcegraph/sourcegraph/issues/22793 (PRs: ~[#23079](https://github.com/sourcegraph/sourcegraph/pull/23079)~) 🐛
- [x] (🏁 770 days ago) https://github.com/sourcegraph/sourcegraph/issues/23201 
- [x] (🏁 580 days ago) https://github.com/sourcegraph/sourcegraph/issues/23065    🏳️ [Insights iteration 13](https://github.com/sourcegraph/sourcegraph/milestone/155)
- [x] (🏁 571 days ago) https://github.com/sourcegraph/sourcegraph/issues/22870    🏳️ [Insights iteration 14](https://github.com/sourcegraph/sourcegraph/milestone/156)
- [x] (🏁 349 days ago) https://github.com/sourcegraph/sourcegraph/issues/23070 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
