### ISSUE TITLE
CSS Modules migration: Tracking issue

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#23010]
## Description

It's important to completely migrate to CSS Modules to improve the front-end developer experience. This will give us important benefits such as:

1. Most of the CSS will be removed from the global scope — easier to maintain and update.
2. Stylesheets written for components will be consistent through the codebase. All components will use CSS modules.
3. CSS recompilation time will be significantly reduced because CSS modules can be rebuilt independently from each other.

Based on [the CSS isolation RFC](https://docs.google.com/document/d/1VedPoFy7WIuHeXPzwRGMmgjDPL4CBdTKmhy4OBmlmf8/edit#heading=h.trqab8y0kufp).

The Code Insight lives on the [Frontend Platform migrations dashboard](https://sourcegraph.com/insights/dashboards/frontendPlatformMigrations).

## Tracked issues

@gitstart-sourcegraph

Completed
- [x] (🏁 108 days ago) https://github.com/sourcegraph/sourcegraph/issues/25796 
- [x] (🏁 107 days ago) https://github.com/sourcegraph/sourcegraph/issues/25602 
- [x] (🏁 105 days ago) https://github.com/sourcegraph/sourcegraph/issues/25918 
- [x] (🏁 105 days ago) https://github.com/sourcegraph/sourcegraph/issues/25750 
- [x] (🏁 105 days ago) https://github.com/sourcegraph/sourcegraph/issues/25875 
- [x] (🏁 100 days ago) https://github.com/sourcegraph/sourcegraph/issues/25752 
- [x] (🏁 99 days ago) https://github.com/sourcegraph/sourcegraph/issues/26175 
- [x] (🏁 98 days ago) https://github.com/sourcegraph/sourcegraph/issues/26300 
- [x] (🏁 95 days ago) https://github.com/sourcegraph/sourcegraph/issues/26307 
- [x] (🏁 95 days ago) https://github.com/sourcegraph/sourcegraph/issues/26301 
- [x] (🏁 94 days ago) https://github.com/sourcegraph/sourcegraph/issues/26176 
- [x] (🏁 94 days ago) https://github.com/sourcegraph/sourcegraph/issues/26303 
- [x] (🏁 92 days ago) https://github.com/sourcegraph/sourcegraph/issues/26354 
- [x] (🏁 91 days ago) https://github.com/sourcegraph/sourcegraph/issues/26353 
- [x] (🏁 87 days ago) https://github.com/sourcegraph/sourcegraph/issues/25883 
- [x] (🏁 87 days ago) https://github.com/sourcegraph/sourcegraph/issues/26499 
- [x] (🏁 87 days ago) https://github.com/sourcegraph/sourcegraph/issues/26310 
- [x] (🏁 78 days ago) https://github.com/sourcegraph/sourcegraph/issues/26498 
- [x] (🏁 78 days ago) https://github.com/sourcegraph/sourcegraph/issues/27079 
- [x] (🏁 78 days ago) https://github.com/sourcegraph/sourcegraph/issues/26952 
- [x] (🏁 78 days ago) https://github.com/sourcegraph/sourcegraph/issues/25975 
- [x] (🏁 78 days ago) https://github.com/sourcegraph/sourcegraph/issues/26701 
- [x] (🏁 73 days ago) https://github.com/sourcegraph/sourcegraph/issues/26700 
- [x] (🏁 72 days ago) https://github.com/sourcegraph/sourcegraph/issues/26951 
- [x] (🏁 72 days ago) https://github.com/sourcegraph/sourcegraph/issues/26702 
- [x] (🏁 71 days ago) https://github.com/sourcegraph/sourcegraph/issues/27078 
- [x] (🏁 70 days ago) https://github.com/sourcegraph/sourcegraph/issues/26305 
- [x] (🏁 60 days ago) https://github.com/sourcegraph/sourcegraph/issues/27077 
- [x] (🏁 59 days ago) https://github.com/sourcegraph/sourcegraph/issues/28012 
- [x] (🏁 37 days ago) https://github.com/sourcegraph/sourcegraph/issues/28261 
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/issues/25751 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/23015 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/28010 

@valerybugakov

Completed
- [x] (🏁 192 days ago) https://github.com/sourcegraph/sourcegraph/issues/20004 
- [x] (🏁 154 days ago) https://github.com/sourcegraph/sourcegraph/issues/23011 
- [x] (🏁 144 days ago) https://github.com/sourcegraph/sourcegraph/pull/24629 
- [x] (🏁 144 days ago) https://github.com/sourcegraph/sourcegraph/pull/24631 
- [x] (🏁 144 days ago) https://github.com/sourcegraph/sourcegraph/pull/24630 
- [x] (🏁 142 days ago) https://github.com/sourcegraph/sourcegraph/pull/24660 
- [x] (🏁 142 days ago) https://github.com/sourcegraph/sourcegraph/pull/24661 
- [x] (🏁 142 days ago) https://github.com/sourcegraph/sourcegraph/pull/24664 
- [x] (🏁 140 days ago) https://github.com/sourcegraph/sourcegraph/pull/24759 
- [x] (🏁 140 days ago) https://github.com/sourcegraph/sourcegraph/pull/24781 
- [x] (🏁 140 days ago) https://github.com/sourcegraph/sourcegraph/pull/24784 
- [x] (🏁 140 days ago) https://github.com/sourcegraph/sourcegraph/pull/24786 
- [x] (🏁 140 days ago) https://github.com/sourcegraph/sourcegraph/pull/24791 
- [x] (🏁 140 days ago) https://github.com/sourcegraph/sourcegraph/pull/24782 
- [x] (🏁 140 days ago) https://github.com/sourcegraph/sourcegraph/pull/24783 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/23013 
- [x] (🏁 122 days ago) https://github.com/sourcegraph/sourcegraph/issues/23014 
- [x] (🏁 122 days ago) https://github.com/sourcegraph/sourcegraph/issues/23012 
- [x] (🏁 121 days ago) https://github.com/sourcegraph/sourcegraph/pull/25429 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/issues/23016 
- [x] (🏁 105 days ago) https://github.com/sourcegraph/sourcegraph/pull/25430 

### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by pdubroy** [comment]
Update from 2021-12-02:

<img width="508" alt="CleanShot 2021-12-02 at 10 28 06@2x" src="https://user-images.githubusercontent.com/17293/144394655-3c6c18d6-cc74-4747-aeb4-677877a3da22.png">

**Comment by valerybugakov** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/30354

**Comment by valerybugakov** [comment]
Update from 2022-01-28:

<img width="555" alt="Screen Shot 2022-01-28 at 17 31 01" src="https://user-images.githubusercontent.com/3846380/151573959-20d147bb-9592-4533-b9f1-994372a9ad2e.png">
