### ISSUE TITLE
3.31.0 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#23113]
# 3.31.0 managed instances upgrade

These [managed instances](https://about.sourcegraph.com/handbook/engineering/distribution/managed) upgrades are scheduled for **[Aug 21, 2021, 6:00 PM (UTC)](https://time.is/1800_21_Aug_2021_in_UTC?One%20working%20day%20after%203.31%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](https://about.sourcegraph.com/handbook/engineering/distribution/managed/upgrade_process).

---

## Upgrade internal managed instances

- [ ] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [ ] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com)

## Upgrade customer managed instances

- [ ] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/1712860829](https://app.hubspot.com/contacts/2762526/company/1712860829/)
- [ ] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/974657309/](https://app.hubspot.com/contacts/2762526/company/974657309/)
- [ ] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/962613882/](https://app.hubspot.com/contacts/2762526/company/962613882/)
- [ ] Upgrade instance for [https://app.hubspot.com/contacts/2762526/contact/37418051](https://app.hubspot.com/contacts/2762526/contact/37418051)
- [ ] Upgrade instance for [https://app.hubspot.com/contacts/2762526/contact/31240401](https://app.hubspot.com/contacts/2762526/contact/31240401)
- [ ] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/6301327782](https://app.hubspot.com/contacts/2762526/company/6301327782)

---

Also see [3.31 release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/23112)

**Comment by bobheadxi** [comment]
Superseded by https://github.com/sourcegraph/sourcegraph/issues/23144

**Comment by daxmc99** [comment]
This is the `3.31.0` tracking issue. It should be closed until after we release 3.31

**Comment by bobheadxi** [comment]
_actually_ superceded by https://github.com/sourcegraph/sourcegraph/issues/24516
