### ISSUE TITLE
`FilteredConnection` refactor: Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#23157]
### Plan
We want to break apart `<FilteredConnection />` into composable chunks and refactor existing parts of the app to a new approach.

This will make it much easier to make changes to individual components, specifically UI changes. It'll also mean it's a lot easier to gain understanding and write tests around the `FilteredConnection` logic that has been built over time.

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/23160 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/23161 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39130 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39131 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

@gitstart-sourcegraph

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

@plibither8

- [ ] https://github.com/sourcegraph/sourcegraph/issues/39128 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

@umpox

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

@valerybugakov

Completed
- [x] (🏁 131 days ago) https://github.com/sourcegraph/sourcegraph/pull/52823 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request
