### ISSUE TITLE
Code Insights Drilldown🔩  Tracking issue 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#23186]
### Plan

This project implies the implementation of code insights drill-down project. You can find designs for this project [here](https://www.figma.com/file/1zvF8Owrh1ndVH29lvyrXn/RFC-419%3A-Code-Insights-“Drilldown”?node-id=260%3A11)

### Tracked issues

@coury-clark: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/23201  __1.00d__
  - [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/23236  __1.00d__

Completed: __1.00d__
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/23236  __1.00d__

@vovakulikov: __11.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/23201  __9.50d__
  - [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/23187 (PRs: ~[#23244](https://github.com/sourcegraph/sourcegraph/pull/23244)~) __5.00d__
  - [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/23189 (PRs: ~[#23489](https://github.com/sourcegraph/sourcegraph/pull/23489)~, ~[#23559](https://github.com/sourcegraph/sourcegraph/pull/23559)~) __1.00d__
  - [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/issues/23190 (PRs: ~[#23559](https://github.com/sourcegraph/sourcegraph/pull/23559)~, ~[#23623](https://github.com/sourcegraph/sourcegraph/pull/23623)~) __2.00d__
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/23233 (PRs: ~[#23964](https://github.com/sourcegraph/sourcegraph/pull/23964)~) __1.50d__
  - [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/23678 (PRs: ~[#23707](https://github.com/sourcegraph/sourcegraph/pull/23707)~)
  - [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/23683 (PRs: ~[#23777](https://github.com/sourcegraph/sourcegraph/pull/23777)~)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/23441  __1.50d__

Completed: __9.50d__
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/23187 (PRs: ~[#23244](https://github.com/sourcegraph/sourcegraph/pull/23244)~) __5.00d__
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/23189 (PRs: ~[#23489](https://github.com/sourcegraph/sourcegraph/pull/23489)~, ~[#23559](https://github.com/sourcegraph/sourcegraph/pull/23559)~) __1.00d__
- [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/issues/23190 (PRs: ~[#23559](https://github.com/sourcegraph/sourcegraph/pull/23559)~, ~[#23623](https://github.com/sourcegraph/sourcegraph/pull/23623)~) __2.00d__
- [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/23678 (PRs: ~[#23707](https://github.com/sourcegraph/sourcegraph/pull/23707)~)
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/23683 (PRs: ~[#23777](https://github.com/sourcegraph/sourcegraph/pull/23777)~)
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/23233 (PRs: ~[#23964](https://github.com/sourcegraph/sourcegraph/pull/23964)~) __1.50d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by felixfbecker** [comment]
Closing as everything in scope for the V1 has been closed 🎉
