### ISSUE TITLE
Code Insights: Beta (3.31) Tracking issue

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#23201]
### Plan

The remaining items for us to be in beta: both from a [support perspective](https://docs.sourcegraph.com/admin/beta_and_prototype_features#beta-features) and [the conceptual requirements](https://about.sourcegraph.com/handbook/product/beta_and_experimental_feature_labels#beta-features). 

### Availability

Joel OOO July 29-30. 
Vova OOO July 30

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/24151  🐛
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/24226  🐛
  - [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/23952  🐛
  - [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/24003  🐛
  - [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/24117 (PRs: ~[#24129](https://github.com/sourcegraph/sourcegraph/pull/24129)~) 🐛
  - [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/24177 (PRs: ~[#24191](https://github.com/sourcegraph/sourcegraph/pull/24191)~) 🐛
  - [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/24178 (PRs: ~[#24191](https://github.com/sourcegraph/sourcegraph/pull/24191)~) 🐛
  - [x] (🏁 2 days ago) https://github.com/sourcegraph/sourcegraph/issues/24296  🐛

Completed
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/24003  🐛
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/24117 (PRs: ~[#24129](https://github.com/sourcegraph/sourcegraph/pull/24129)~) 🐛
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/23952  🐛
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/24177 (PRs: ~[#24191](https://github.com/sourcegraph/sourcegraph/pull/24191)~) 🐛
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/24178 (PRs: ~[#24191](https://github.com/sourcegraph/sourcegraph/pull/24191)~) 🐛
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/24070 
- [x] (🏁 2 days ago) https://github.com/sourcegraph/sourcegraph/issues/24296  🐛

@Joelkw

Completed
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/pull/24063 
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/pull/24334 

@coury-clark: __6.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/24151  __1.00d__ 🐛
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/24147  🐛
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/24149  🐛
  - [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/22401  🐛
  - [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/22799  __1.00d__ 🐛
  - [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/23268  🐛
  - [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/23863  🐛
  - [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/24146  🐛
  - [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/24148  🐛
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/24150  🐛
  - [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/24160  🐛
  - [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/24203  🐛
  - [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/24244  🐛🙆

Completed: __6.50d__
- [x] (🏁 40 days ago) https://github.com/sourcegraph/sourcegraph/pull/23101 
- [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/issues/23386  __0.50d__
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/23642  __0.50d__
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/23268  🐛
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/23690  __2.00d__
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/22799  __1.00d__ 🐛
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/22401  🐛
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/23766 (PRs: ~[#23786](https://github.com/sourcegraph/sourcegraph/pull/23786)~) __0.50d__
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/23767  __0.50d__
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/23798 
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/23785  __0.50d__
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/22931 
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/23863  🐛
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/23186  __1.00d__
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/24160  🐛
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/24148  🐛
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/pull/24210 
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/24146  🐛
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/24203  🐛
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/24244  🐛🙆
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/24150  🐛

@unclejustin: __0.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/24151  __0.50d__ 🐛
  - [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/issues/21958  __0.50d__ 🐛

Completed: __0.50d__
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/issues/21958  __0.50d__ 🐛
- [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/issues/23934  🙆
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/18708 

@vovakulikov: __12.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/22920 
  - [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/23067 (PRs: ~[#23847](https://github.com/sourcegraph/sourcegraph/pull/23847)~)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24151  🐛
  - [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/issues/23257 (PRs: ~[#23504](https://github.com/sourcegraph/sourcegraph/pull/23504)~) 🐛
  - [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/23586 (PRs: ~[#23846](https://github.com/sourcegraph/sourcegraph/pull/23846)~) 🐛
  - [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/23950 (PRs: ~[#24091](https://github.com/sourcegraph/sourcegraph/pull/24091)~) 🐛🙆
  - [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/23958 (PRs: ~[#24080](https://github.com/sourcegraph/sourcegraph/pull/24080)~) 🐛
  - [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/24036 (PRs: ~[#23988](https://github.com/sourcegraph/sourcegraph/pull/23988)~) 🐛
  - [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/24072 (PRs: ~[#24103](https://github.com/sourcegraph/sourcegraph/pull/24103)~) 🐛
  - [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/24174 (PRs: ~[#24188](https://github.com/sourcegraph/sourcegraph/pull/24188)~) 🐛
  - [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/24352 🐛

Completed: __12.50d__
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/issues/23203  __0.50d__
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/issues/23257 (PRs: ~[#23504](https://github.com/sourcegraph/sourcegraph/pull/23504)~) 🐛
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/23559 
- [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/pull/23623 
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/23067 (PRs: ~[#23847](https://github.com/sourcegraph/sourcegraph/pull/23847)~)
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/23586 (PRs: ~[#23846](https://github.com/sourcegraph/sourcegraph/pull/23846)~) 🐛
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/23205 (PRs: ~[#23853](https://github.com/sourcegraph/sourcegraph/pull/23853)~) __1.00d__
- [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/pull/23856 
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/pull/23964 
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/23260 (PRs: ~[#23969](https://github.com/sourcegraph/sourcegraph/pull/23969)~) __0.50d__
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/23655 (PRs: ~[#23969](https://github.com/sourcegraph/sourcegraph/pull/23969)~)
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/23202 (PRs: ~[#23988](https://github.com/sourcegraph/sourcegraph/pull/23988)~, ~[#23989](https://github.com/sourcegraph/sourcegraph/pull/23989)~) __0.50d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/24036 (PRs: ~[#23988](https://github.com/sourcegraph/sourcegraph/pull/23988)~) 🐛
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/23186  __9.50d__
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/23958 (PRs: ~[#24080](https://github.com/sourcegraph/sourcegraph/pull/24080)~) 🐛
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/24062 (PRs: ~[#24085](https://github.com/sourcegraph/sourcegraph/pull/24085)~)
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/23950 (PRs: ~[#24091](https://github.com/sourcegraph/sourcegraph/pull/24091)~) 🐛🙆
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/24072 (PRs: ~[#24103](https://github.com/sourcegraph/sourcegraph/pull/24103)~) 🐛
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/pull/24129 
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/24174 (PRs: ~[#24188](https://github.com/sourcegraph/sourcegraph/pull/24188)~) 🐛
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/pull/24191 
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/pull/24314 
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/23204 (PRs: ~[#23850](https://github.com/sourcegraph/sourcegraph/pull/23850)~) __0.50d__
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/24073 (PRs: ~[#24086](https://github.com/sourcegraph/sourcegraph/pull/24086)~)
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/24352 🐛
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/20212 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request
