### ISSUE TITLE
Improve CTA tracking

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#23243]
- [x] Track clicks on the homepage CTA: HomePageCTAImproveClicked
- [x] Track views on Contexts CTA: SearchResultContextsCTAShown
- [x] Track views on the search results CTA: SearchResultResultsCTAShown
- [x] Track views on the monitor CTA: SearchResultMonitorCTAShown
- [x] Track views on the save search CTA: SearchResultSavedSeachCTAShown

Figma file showing locations and names of tracked items:

https://www.figma.com/file/63HDLa3tDZDolLX6TFChmz/ImproveCTATracking?node-id=0%3A1&viewport=-242%2C435%2C0.25
