### ISSUE TITLE
Code Insights Beta Last Mile Tracking issue

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#24151]
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@unassigned

Completed
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/23201 

@coury-clark: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/24147  🐛
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24149  🐛

Completed: __1.00d__
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/23201  __1.00d__

@unclejustin: __0.50d__

Completed: __0.50d__
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/23201  __0.50d__

@vovakulikov

Completed
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/23201 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by felixfbecker** [comment]
Closing this tracking issue since we're in Beta now. @coury-clark could you move the open issues to our current tracking issue, if you plan to work on them this iteration?
