### ISSUE TITLE
Code Insights Post beta 3.32 release Tracking issue

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#24242]
### Plan

This issue describes all important things that we want to focus on after our beta release or in the near future after the code insights beta release.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@AlicjaSuska

- [ ] https://github.com/sourcegraph/sourcegraph/issues/24240 

@coury-clark: __11.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/24438  __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/23629  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24427  __7.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24512  __1.00d__

@unclejustin: __13.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/24239  __0.50d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24340  🐛
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24079 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24078 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24455 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24233  __2.50d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/21339  __3.00d__ 🙆
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24235  __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24238  __0.50d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/22920  __2.50d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/22922  __2.50d__

Completed: __2.00d__
- [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/20212  __3.00d__
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/24232  __2.00d__

@vovakulikov: __15.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/24236 (PRs: [#24559](https://github.com/sourcegraph/sourcegraph/pull/24559)) __5.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24201  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/22920  __4.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/22870  __1.50d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/22922  __2.50d__
- [x] https://github.com/sourcegraph/sourcegraph/issues/24262 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24235  __2.00d__

Completed: __3.00d__
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/24083 
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/24232  __2.00d__
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/24241  __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by vovakulikov** [comment]
@unclejustin If you work on something in this sprint/release consider adding these tickets or PRs to this tracking issue for transparency.
