### ISSUE TITLE
Transition repogroups to search contexts

### ISSUE THREAD

**Issue by novoselrok** [sourcegraph/sourcegraph#24269]
- [x] search contexts: use spec instead of ID in URL https://github.com/sourcegraph/sourcegraph/issues/24268
- [x] search contexts: iterate on single page design https://github.com/sourcegraph/sourcegraph/issues/24272
- [x] search contexts: add search box to single page view https://github.com/sourcegraph/sourcegraph/issues/24407
- [x] Convert Cloud repogroups to search contexts https://github.com/sourcegraph/sourcegraph/issues/24273
- [x] Replace repogroups with search contexts on the homepage https://github.com/sourcegraph/sourcegraph/issues/24274 
- [x] Remove repogroup community pages https://github.com/sourcegraph/sourcegraph/issues/24275
- [x] Remove `repogroup:` query filter https://github.com/sourcegraph/sourcegraph/issues/24277
