### ISSUE TITLE
sg: Create `sg setup` command that sets up local environment, including dependencies

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#24401]
The idea is that `sg setup` replaces the quickstart steps in our onboarding docs.

Goal: `sg setup` installs databases, it sets them up, it installs dependencies, it asks users how they want to run X or Y, helps user setup `/etc/hosts`, etc. After that the user can run `sg start` to get a working dev environment.

Inspiration: this [tweet](https://twitter.com/Nick_Craver/status/1375871107773956103) by a StackOverflow developer.

<a href="https://twitter.com/Nick_Craver/status/1375871107773956103"><img width="601" alt="screenshot_2021-08-30_09 46 15@2x" src="https://user-images.githubusercontent.com/1185253/131304514-ff9cd515-ba64-4e5d-bb80-e2f3867f0ed2.png"></a>

### TODOs

- [ ] Create a CI step for `sg` that uploads a binary so that new colleagues don't need to install Go before they can run `sg setup`
- [ ] Create infrastructure for `sg setup` command that can
  - [ ] ... ask users questions ("Option A, B, C?")
  - [ ] use answer to ask other question
- ... <fill in rest here>

**Comment by jeanduplessis** [comment]
Little bit off topic but thinking of sg as a local env setup tool I was wondering whether it should be in its own repo. Strategically I think it would be great if sg took care of managing the Souregraph repos for you as well (cloning them etc).

**Comment by coury-clark** [comment]
Right now `sg` has a dependency that it executes from the main `sourcegraph` repo. Is that something that would need to be changed to accomplish this?

One thing I've been thinking about is if we should explore an extension-based architecture for `sg` such that commands can be installed with their own dependencies. This might help in this case, for example a postgres extension could bundle the install without being too heavy in `sg`. Any thoughts on this? @mrnugget 

I agree with @jeanduplessis, managing our repos would be a big benefit.

**Comment by unknwon** [comment]
>One thing I've been thinking about is if we should explore an extension-based architecture for sg such that commands can be installed with their own dependencies. This might help in this case, for example a postgres extension could bundle the install without being too heavy in sg. Any thoughts on this? @mrnugget

GitHub CLI 2.0 [just announced support of extensions](https://github.blog/2021-08-24-github-cli-2-0-includes-extensions/), we may take some inspirations from it.

**Comment by mrnugget** [comment]
> Right now `sg` has a dependency that it executes from the main `sourcegraph` repo. Is that something that would need to be changed to accomplish this?

Not necessarily! The `sg rfc` command, for example, doesn't have that dependency. `sg setup`, too, could simply remove that dependency.

> One thing I've been thinking about is if we should explore an extension-based architecture for `sg` such that commands can be installed with their own dependencies. This might help in this case, for example a postgres extension could bundle the install without being too heavy in `sg`. Any thoughts on this? @mrnugget

That sounds potentially useful in the future, but I think we're still in the 0.x/MVP phase of `sg` and want to focus on adoption/stability/basics before digging into that topic.
