### ISSUE TITLE
sg tool is documented as the default way to run Sourcegraph for our devs

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#24466]
One of our team's KRs: "`sg` tool is documented as the default way to run Sourcegraph for our devs."

- [x] Poll devs to find out what is preventing them today from using `sg` by default, or when they don't use it, why not.
- [ ] Scope and prioritize tasks to address the above.
- [ ] Actually update the docs.

**Comment by malomarrec** [comment]
Doing in: https://github.com/sourcegraph/sourcegraph/issues/24964
