### ISSUE TITLE
esbuild issue tracker

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#24518]
After https://github.com/sourcegraph/sourcegraph/pull/24487 is merged, this issue tracks open issues in esbuild. See https://docs.sourcegraph.com/dev/background-information/web/build#esbuild for more information.

- [ ] @eseliger [reports](https://github.com/sourcegraph/sourcegraph/pull/24487#pullrequestreview-743821360) the navbar isn't responsive
- [ ] @valerybugakov [reports](https://github.com/sourcegraph/sourcegraph/pull/24487#pullrequestreview-743569955) autoprefixer isn't applied in some cases
- [ ] @valerybugakov [reports](https://github.com/sourcegraph/sourcegraph/pull/24487#pullrequestreview-743569955) `Find references` results in an uncaught exception
