### ISSUE TITLE
Improve code intelligence quality and reduce false positives

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2452]
Code intelligence has broken (I mean P0 broken) a few times in the past couple of weeks in ways that could have been prevented by E2E and unit tests. Also, basic-code-intel is rather slow on large repositories and often times reports false positives in definitions and references, which hampers adoption.

## Plan

- [x] Symbol search is too slow to provide jump-to-definition on torvalds/linux https://github.com/sourcegraph/sourcegraph/issues/2257
  - PR https://github.com/sourcegraph/sourcegraph/pull/2334
- [x] Set up E2E tests for code intelligence
  - Web app https://github.com/sourcegraph/sourcegraph/pull/2533)
  - Browser extension https://github.com/sourcegraph/sourcegraph/pull/2566
  - Code intel https://github.com/sourcegraph/sourcegraph/pull/2662
- [x] Fix and write more unit tests for basic-code-intel
  - https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/36
  - https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/38
  - https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/39
- [x] Publish all `sourcegraph/{go,python,...}` extensions in CI
  - Go https://github.com/sourcegraph/sourcegraph-go/pull/34
  - Python https://github.com/sourcegraph/sourcegraph-python/commit/4d858ae812ddfe983499525de68610185d864f04
- [x] Add docs for HTTP basic auth for language servers, and document this in extension READMEs https://github.com/sourcegraph/sourcegraph/issues/2595
  - Go https://github.com/sourcegraph/sourcegraph-go/pull/37
  - TypeScript https://github.com/sourcegraph/sourcegraph-typescript/pull/129
  - Python https://github.com/sourcegraph/sourcegraph-python/pull/10
- [x] Indicate that basic code intel hovers/defs/refs are fuzzy in the UI (could be a "Fuzzy" label in the tooltip, or other UI treatment in the defs/refs panel) https://github.com/sourcegraph/sourcegraph/issues/1174
  - basic-code-intel https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/41
  - Go https://github.com/sourcegraph/sourcegraph-go/pull/39
  - TypeScript https://github.com/sourcegraph/sourcegraph-typescript/pull/127
  - Python https://github.com/sourcegraph/sourcegraph-python/pull/4
- [x] Visual testing with Percy https://github.com/sourcegraph/sourcegraph/pull/2606
- [x] Index file-local definitions in the symbols service
  - Adding `fileLocal` to the Symbols DB https://github.com/sourcegraph/sourcegraph/pull/2788
  - Filtering by `fileLocal` https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/63
- [x] Index Go packages https://github.com/sourcegraph/sourcegraph/pull/2802
- [ ] Reduce false positives in basic-code-intel https://github.com/sourcegraph/sourcegraph/issues/2298
- [x] Perform symbol search on other repositories to find cross-repo definitions
  - https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/53
- [ ] Fall back to basic code intel when hovers take too long https://github.com/sourcegraph/sourcegraph/issues/2571
- [ ] Use `@sourcegraph/lsp-client` in sourcegraph-go https://github.com/sourcegraph/sourcegraph-go/issues/28
  - WIP PR https://github.com/sourcegraph/sourcegraph-go/issues/28
  - Blocked on issues in https://github.com/sourcegraph/sourcegraph-go/issues/28#issuecomment-469488194
- [ ] Incorporate `basic-code-intel` into `@sourcegraph/lsp-client`
- [ ] Eliminate dependency on Sourcegraph.com's basic-code-intel in e2e tests https://github.com/sourcegraph/sourcegraph/issues/2681
- [ ] Escape the `file:` filter in basic code intel https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/38#discussion_r262582085

## Test/review plan

- Symbols perf improvements have tests + benchmarks
- E2E/unit tests will be run in CI
- Reducing false positives will have unit tests

**Comment by chrismwendt** [comment]
> - [ ] Indicate that basic code intel hovers/defs/refs are fuzzy in the UI (could be a "Fuzzy" label in the tooltip, or other UI treatment in the defs/refs panel)

@sqs Do you have a link for this?

**Comment by nicksnyder** [comment]
Please close this tracking issue for 3.2 and create a new tracking issue for 3.3.

**Comment by chrismwendt** [comment]
3.3 tracking issue https://github.com/sourcegraph/sourcegraph/issues/2856
