### ISSUE TITLE
Tracking: Code Intelligence data retention

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#24602]
### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@Numbers88s

Completed
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/issues/26852 (PRs: ~[#27395](https://github.com/sourcegraph/sourcegraph/pull/27395)~)

@efritz

- [ ] https://github.com/sourcegraph/sourcegraph/issues/24961 
  - [x] (🏁 82 days ago) https://github.com/sourcegraph/sourcegraph/pull/26115 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26230 
  - [x] (🏁 107 days ago) https://github.com/sourcegraph/sourcegraph/issues/16413 (PRs: ~[#25007](https://github.com/sourcegraph/sourcegraph/pull/25007)~)
  - [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/issues/18027 

Completed
- [x] (🏁 119 days ago) https://github.com/sourcegraph/sourcegraph/pull/24522 
- [x] (🏁 119 days ago) https://github.com/sourcegraph/sourcegraph/pull/24603 
- [x] (🏁 119 days ago) https://github.com/sourcegraph/sourcegraph/pull/24613 
- [x] (🏁 119 days ago) https://github.com/sourcegraph/sourcegraph/pull/24612 
- [x] (🏁 119 days ago) https://github.com/sourcegraph/sourcegraph/pull/24611 
- [x] (🏁 119 days ago) https://github.com/sourcegraph/sourcegraph/pull/24604 
- [x] (🏁 119 days ago) https://github.com/sourcegraph/sourcegraph/pull/24608 
- [x] (🏁 119 days ago) https://github.com/sourcegraph/sourcegraph/pull/24606 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/pull/24769 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/pull/24770 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/pull/24778 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/pull/24794 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/pull/24777 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/pull/24772 
- [x] (🏁 117 days ago) https://github.com/sourcegraph/sourcegraph/pull/24807 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/24922 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/24827 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/24925 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/24294 
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/issues/18027 
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/pull/24793 
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/issues/24742 
- [x] (🏁 110 days ago) https://github.com/sourcegraph/sourcegraph/pull/25058 
- [x] (🏁 107 days ago) https://github.com/sourcegraph/sourcegraph/issues/16413 (PRs: ~[#25007](https://github.com/sourcegraph/sourcegraph/pull/25007)~)
- [x] (🏁 82 days ago) https://github.com/sourcegraph/sourcegraph/pull/26115 
- [x] (🏁 81 days ago) https://github.com/sourcegraph/sourcegraph/pull/26167 
- [x] (🏁 81 days ago) https://github.com/sourcegraph/sourcegraph/pull/26168 
- [x] (🏁 55 days ago) https://github.com/sourcegraph/sourcegraph/pull/26917 
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/issues/26852 (PRs: ~[#27395](https://github.com/sourcegraph/sourcegraph/pull/27395)~)

@macraig

- [ ] https://github.com/sourcegraph/sourcegraph/issues/26230 
  - [x] (🏁 107 days ago) https://github.com/sourcegraph/sourcegraph/issues/16413 (PRs: ~[#25007](https://github.com/sourcegraph/sourcegraph/pull/25007)~)

Completed
- [x] (🏁 107 days ago) https://github.com/sourcegraph/sourcegraph/issues/16413 (PRs: ~[#25007](https://github.com/sourcegraph/sourcegraph/pull/25007)~)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by olafurpg** [comment]
Is this epic ready to be closed?

**Comment by efritz** [comment]
@olafurpg I'll throw repository group configuration on here in a week or so before closing it out completely.
