### ISSUE TITLE
LHS navigation for Docs

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#2463]
## Tasks

- [x] @ryan-blunden Hard-coded nav HTML
- [x] @francisschmaltz Implement nav style and functionality
  - [x] Nav stays fixed so scrolling the content doesn’t scroll the nav.

---

Currently, users must rely on inter page links to navigate and discover different parts of our documentation. 

Adding a hierarchical representation of the site’s structure would let users browse to see if the info they're looking for matches a section or page.

Example from [readme.io](https://readme.readme.io/docs/internal-documentation) that has nice functionality.

![nav 1](https://user-images.githubusercontent.com/133014/53454846-69f91d00-39dd-11e9-95ea-298d4ba93386.gif)
