### ISSUE TITLE
UI performance: Tracking issue

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#24869]
### Plan

Provide improvements to the actual page rendering performance and perceived performance when the user interacts with the application UI.

Based on the [Frontend performance initiatives](https://docs.google.com/document/d/1ikrtT2ZGRih14ynNhP34MH-tN2F9AArAVQiwWCoFpFM/edit)

### Tracked issues

@unassigned: __5.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/24882  🕵️
- [ ] https://github.com/sourcegraph/sourcegraph/issues/25840  🕵️
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26347 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26348  🕵️
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26350  🕵️
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26351 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26573 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26841 (PRs: ~[#26843](https://github.com/sourcegraph/sourcegraph/pull/26843)~)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24878  __5.00d__

Completed
- [x] (🏁 30 days ago) https://github.com/sourcegraph/sourcegraph/issues/24881  🕵️
- [x] (🏁 16 days ago) https://github.com/sourcegraph/sourcegraph/issues/26840 (PRs: ~[#26843](https://github.com/sourcegraph/sourcegraph/pull/26843)~, ~[#26982](https://github.com/sourcegraph/sourcegraph/pull/26982)~)

@umpox: __10.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/26260 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24872  __1.00d__

Completed: __9.50d__
- [x] (🏁 65 days ago) https://github.com/sourcegraph/sourcegraph/pull/24845 
- [x] (🏁 64 days ago) https://github.com/sourcegraph/sourcegraph/issues/24877 (PRs: ~[#24836](https://github.com/sourcegraph/sourcegraph/pull/24836)~)
- [x] (🏁 64 days ago) https://github.com/sourcegraph/sourcegraph/issues/24879 
- [x] (🏁 45 days ago) https://github.com/sourcegraph/sourcegraph/pull/25635 
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/24870 (PRs: ~[#25455](https://github.com/sourcegraph/sourcegraph/pull/25455)~)
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/pull/25833 
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/24871 
- [x] (🏁 38 days ago) https://github.com/sourcegraph/sourcegraph/pull/25900 
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/pull/25952 
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/24873 
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/issues/26282 (PRs: ~[#26290](https://github.com/sourcegraph/sourcegraph/pull/26290)~) __2.00d__
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/24883 (PRs: ~[#26360](https://github.com/sourcegraph/sourcegraph/pull/26360)~) __2.00d__
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/24880 (PRs: ~[#26288](https://github.com/sourcegraph/sourcegraph/pull/26288)~) __0.50d__
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/26280 (PRs: ~[#26285](https://github.com/sourcegraph/sourcegraph/pull/26285)~) __1.00d__
- [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/pull/26711 
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/pull/26783 
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/pull/26594 
- [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/pull/26779 
- [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/issues/26270  __4.00d__

@valerybugakov

- [ ] https://github.com/sourcegraph/sourcegraph/issues/22496 
  - [x] (🏁 66 days ago) https://github.com/sourcegraph/sourcegraph/pull/24866 
  - [x] (🏁 65 days ago) https://github.com/sourcegraph/sourcegraph/pull/24868 

Completed
- [x] (🏁 66 days ago) https://github.com/sourcegraph/sourcegraph/issues/24876 (PRs: ~[#24866](https://github.com/sourcegraph/sourcegraph/pull/24866)~)
- [x] (🏁 65 days ago) https://github.com/sourcegraph/sourcegraph/pull/24868 
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/26433 (PRs: ~[#26843](https://github.com/sourcegraph/sourcegraph/pull/26843)~)
- [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/pull/26846 
- [x] (🏁 16 days ago) https://github.com/sourcegraph/sourcegraph/pull/26982 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by umpox** [comment]
Closing as we have completed all the intended work that was defined in the original [Frontend Performance Initiatives](https://docs.google.com/document/d/1ikrtT2ZGRih14ynNhP34MH-tN2F9AArAVQiwWCoFpFM/edit) doc.

Future work can still be tracked under the `UI Performance` label
