### ISSUE TITLE
sg: Create `sg setup` command that sets up local environment, including dependencies

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#24900]
The idea is that `sg setup` replaces the quickstart steps in our onboarding docs.

Goal: `sg setup` installs databases, it sets them up, it installs dependencies, it asks users how they want to run X or Y, helps user setup `/etc/hosts`, etc. After that the user can run `sg start` to get a working dev environment.

Inspiration: this [tweet](https://twitter.com/Nick_Craver/status/1375871107773956103) by a StackOverflow developer.

<a href="https://twitter.com/Nick_Craver/status/1375871107773956103"><img width="601" alt="screenshot_2021-08-30_09 46 15@2x" src="https://user-images.githubusercontent.com/1185253/131304514-ff9cd515-ba64-4e5d-bb80-e2f3867f0ed2.png"></a>

### TODOs

The goal is to add functionality to `sg setup` step by step and standardize on a
way to setup and run local dev env.

We start by adding an `sg setup` command that only prints the install
instructions, step by step, and end with `sg setup` that guides a user through
the setup process and installs dependencies for the user.

- [x] Create a CI step for `sg` that uploads a binary so that new colleagues don't need to install Go before they can run `sg setup`
- [x] Finish https://github.com/sourcegraph/sourcegraph/pull/25604
  - [x] Guide user through steps: show each step, ask for confirmation, ask whether they want to use Docker or not.
- [ ] Make `sg setup` clone repositories
  - [ ] Clone `sourcegraph/sourcegraph`, provide tips on what to do if it fails
  - [ ] Ask user whether they're an employee or not. If yes: clone `sourcegraph/dev-private`.
- [ ] Start with macOS: check which dependencies are installed
  - Instead of printing all dependencies that a user needs to install, check which one's are installed and **print instructions** for how to install them if not. **Only support Homebrew**.
- [ ] macOS: install dependencies automatically
  - Ask user whether we should install *missing* dependencies automatically. if yes, do so.

**Comment by fkling** [comment]
It would be great to either default to using the docker postgres/redis images or make this an opt-in feature. So maybe `sg setup` would only have to install docker and utility clis.

**Comment by mrnugget** [comment]
@jhchabran and I started work here: https://github.com/sourcegraph/sourcegraph/pull/25604

**Comment by mrnugget** [comment]
I updated the TODOs in the ticket description and will start by trying to get https://github.com/sourcegraph/sourcegraph/pull/25604 mergeable.

**Comment by jhchabran** [comment]
Useful checks: 

- [ ] Go version
- [ ] Docker Version
- [ ] kubectl version
- [ ] Postgresql Version (if not dockerized)
- [ ] Redis Version (if not dockerized) 
- `sg doctor` Diagnosis for quicker support:
  - [ ] OS name
  - [ ] OS version
  - [ ] current shell
  - [ ] `$PATH`
  - [ ] `go env`

**Comment by mrnugget** [comment]
More thoughts from Slack:

<img width="1091" alt="screenshot_2021-11-12_14 45 18@2x" src="https://user-images.githubusercontent.com/1185253/141476876-40c7a04a-d2b4-42f5-8f5f-26796a3647cb.png">

**Comment by unknwon** [comment]
nit: ["setup" is a noun, "set up" is a verb](https://handbook.sourcegraph.com/communication/content_guidelines/terminology_guidelines#:~:text=set%20up%20(v)/setup%20(n)) according to our handbook 😁

**Comment by mrnugget** [comment]
We also have `sg live`, `sg ci`, `sg migration`, … so I think having a noun in the command is fine!

**Comment by unknwon** [comment]
Oh sorry I totally missed the "sg setup" part... Yes for this 100% vote from me. Was referring to "Set up PostgreSQL" and "Set up Redis" 😁

**Comment by mrnugget** [comment]
I'm closing this now since #27563 is merged. We can create follow-up tickets for Linux support etc.
