### ISSUE TITLE
3 customers adopt on-prem auto-indexing

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#24961]
### Plan

This also benefits Batch Changes since it will make it easier for these customers to use SSBC

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/25097 

Completed
- [x] (🏁 114 days ago) https://github.com/sourcegraph/sourcegraph/issues/24421 
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/27441 (PRs: ~[#27445](https://github.com/sourcegraph/sourcegraph/pull/27445)~)

@Numbers88s

Completed
- [x] (🏁 114 days ago) https://github.com/sourcegraph/sourcegraph/issues/25787 (PRs: ~[#25851](https://github.com/sourcegraph/sourcegraph/pull/25851)~)
- [x] (🏁 110 days ago) https://github.com/sourcegraph/sourcegraph/issues/24744 (PRs: ~[#25716](https://github.com/sourcegraph/sourcegraph/pull/25716)~)
- [x] (🏁 108 days ago) https://github.com/sourcegraph/sourcegraph/issues/26054 
- [x] (🏁 107 days ago) https://github.com/sourcegraph/sourcegraph/issues/26216 
- [x] (🏁 93 days ago) https://github.com/sourcegraph/sourcegraph/issues/25788 (PRs: ~[#26289](https://github.com/sourcegraph/sourcegraph/pull/26289)~)
- [x] (🏁 82 days ago) https://github.com/sourcegraph/sourcegraph/issues/27446 (PRs: ~[#27472](https://github.com/sourcegraph/sourcegraph/pull/27472)~)

@Strum355: __1.00d__

Completed: __1.00d__
- [x] (🏁 114 days ago) https://github.com/sourcegraph/sourcegraph/issues/24421  __1.00d__
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/issues/26056 (PRs: ~[#26087](https://github.com/sourcegraph/sourcegraph/pull/26087)~)
- [x] (🏁 71 days ago) https://github.com/sourcegraph/sourcegraph/issues/27440 

@andreeleuterio

- [ ] https://github.com/sourcegraph/sourcegraph/issues/25098 

Completed
- [x] (🏁 114 days ago) https://github.com/sourcegraph/sourcegraph/issues/24421 

@chrismwendt

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27436 

Completed
- [x] (🏁 69 days ago) https://github.com/sourcegraph/sourcegraph/issues/27864 

@dcomas

- [ ] https://github.com/sourcegraph/sourcegraph/issues/25098 

Completed
- [x] (🏁 114 days ago) https://github.com/sourcegraph/sourcegraph/issues/24421 

@efritz: __0.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27436 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27444  __0.50d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27867 

Completed
- [x] (🏁 134 days ago) https://github.com/sourcegraph/sourcegraph/pull/25123 
- [x] (🏁 129 days ago) https://github.com/sourcegraph/sourcegraph/pull/25275 
- [x] (🏁 119 days ago) https://github.com/sourcegraph/sourcegraph/pull/25668 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/issues/25233 
- [x] (🏁 114 days ago) https://github.com/sourcegraph/sourcegraph/pull/25851 
- [x] (🏁 114 days ago) https://github.com/sourcegraph/sourcegraph/issues/24421 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/25990 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/25989 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/25988 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/25987 
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/issues/25931 (PRs: ~[#26024](https://github.com/sourcegraph/sourcegraph/pull/26024)~)
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/pull/26023 
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/pull/25991 
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/issues/26043 
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/issues/26060 (PRs: ~[#26067](https://github.com/sourcegraph/sourcegraph/pull/26067)~)
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/25986 
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/issues/26055 (PRs: ~[#26087](https://github.com/sourcegraph/sourcegraph/pull/26087)~)
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/issues/26056 (PRs: ~[#26087](https://github.com/sourcegraph/sourcegraph/pull/26087)~)
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/26107 
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/26109 
- [x] (🏁 110 days ago) https://github.com/sourcegraph/sourcegraph/issues/24744 (PRs: ~[#25716](https://github.com/sourcegraph/sourcegraph/pull/25716)~)
- [x] (🏁 108 days ago) https://github.com/sourcegraph/sourcegraph/issues/26054 
- [x] (🏁 107 days ago) https://github.com/sourcegraph/sourcegraph/issues/26216 
- [x] (🏁 107 days ago) https://github.com/sourcegraph/sourcegraph/issues/24743 (PRs: ~[#25817](https://github.com/sourcegraph/sourcegraph/pull/25817)~)
- [x] (🏁 93 days ago) https://github.com/sourcegraph/sourcegraph/issues/25788 (PRs: ~[#26289](https://github.com/sourcegraph/sourcegraph/pull/26289)~)
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/pull/27445 
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/24989 (PRs: ~[#25764](https://github.com/sourcegraph/sourcegraph/pull/25764)~)
- [x] (🏁 82 days ago) https://github.com/sourcegraph/sourcegraph/issues/27446 (PRs: ~[#27472](https://github.com/sourcegraph/sourcegraph/pull/27472)~)
- [x] (🏁 78 days ago) https://github.com/sourcegraph/sourcegraph/pull/27395 
- [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/issues/27437 (PRs: ~[#27457](https://github.com/sourcegraph/sourcegraph/pull/27457)~)
- [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/issues/27865 (PRs: ~[#27934](https://github.com/sourcegraph/sourcegraph/pull/27934)~)
- [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/issues/27866 
- [x] (🏁 72 days ago) https://github.com/sourcegraph/sourcegraph/pull/27949 
- [x] (🏁 69 days ago) https://github.com/sourcegraph/sourcegraph/issues/27864 
- [x] (🏁 64 days ago) https://github.com/sourcegraph/sourcegraph/issues/27439 (PRs: ~[#27455](https://github.com/sourcegraph/sourcegraph/pull/27455)~)
- [x] (🏁 64 days ago) https://github.com/sourcegraph/sourcegraph/issues/27438 (PRs: ~[#27456](https://github.com/sourcegraph/sourcegraph/pull/27456)~)
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/issues/24602 
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/25961 

@eseliger: __3.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/24907  __0.50d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24990 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27436 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27444  __0.50d__

Completed: __2.50d__
- [x] (🏁 114 days ago) https://github.com/sourcegraph/sourcegraph/issues/24421  __2.00d__
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/issues/26043 
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/issues/26055 (PRs: ~[#26087](https://github.com/sourcegraph/sourcegraph/pull/26087)~)
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/issues/26056 (PRs: ~[#26087](https://github.com/sourcegraph/sourcegraph/pull/26087)~)
- [x] (🏁 71 days ago) https://github.com/sourcegraph/sourcegraph/issues/27443  __0.50d__
- [x] (🏁 65 days ago) https://github.com/sourcegraph/sourcegraph/issues/27442  __0.50d__
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/25961 

@mohammadualam

- [ ] https://github.com/sourcegraph/sourcegraph/issues/25098 

Completed
- [x] (🏁 114 days ago) https://github.com/sourcegraph/sourcegraph/issues/24421 

@mrnugget

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27867 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by yinquanteo** [comment]
Leaving the below (that was flagged in the Code Graph dashboard) for posterity

Status: Some risk to flag – we don't have a specific point person that's able to advise from an ops perspective (due to bandwidth in those teams).

**Comment by yinquanteo** [comment]
@efritz, @scalabilitysolved: I renamed this issue and added it to [this dashboard](https://github.com/orgs/sourcegraph/projects/214/views/11). Let me know if you preferred if we took a different approach.

**Comment by macraig** [comment]
Moving to at risk. This KR issue is tightly paired with https://github.com/sourcegraph/sourcegraph/issues/27348, mirroring latest update for visibility:

> This key result is now at risk timeline-wise, although the fundamental goal is on track. My best guess is that it will slip by approximately a month due to the vacation period, and unrelated 3.34 upgrade issues.
> 
> https://github.com/sourcegraph/accounts/issues/565 will likely run an installation POC before Christmas, but actual deployment will be in January.
> https://github.com/sourcegraph/accounts/issues/537 encountered unrelated issues when upgrading to 3.34 and is postponing batch changes until resolved.
> other identified early adopters are similarly slowed down due to the vacation time and 3.34 upgrade issues.
> cc

**Comment by jyavorska** [comment]
@efritz @macraig what ended up being the final status of this OKR for Q4?

**Comment by macraig** [comment]
Off-track, extends to FY23 Q1
