### ISSUE TITLE
Tracking Issue: Consolidation of React testing libraries

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#24986]
## Plan

We currently have multiple React testing libraries in use across the application. This results in inconsistent tests and unnecessary dependencies.

Current testing libraries that we use:
- [React Test Renderer](https://reactjs.org/docs/test-renderer.html)
- [Enzyme](https://enzymejs.github.io/enzyme/)
- [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)

### Comparing approaches
React Test Renderer
- Limited in functionality
- [Usage in our application](https://sourcegraph.com/search?q=context:global+repo:sourcegraph/sourcegraph+from+%27react-test-renderer%27&patternType=literal) is also limited. We primarily use this library for snapshots and basic tests. Other libraries offer the same functionality.

Enzyme:
- Powerful functionality
- Can encourage bad practices. For example, shallow rendering, accessing a component instance directly. accessing component props. In particular, here's an [article](https://kentcdodds.com/blog/why-i-never-use-shallow-rendering) that states the dangers of shallow rendering

React Testing Library
- Powerful functionality
- Encourages better practices. Does not support shallow rendering, or other techniques that do not follow the libraries [guiding principles](https://testing-library.com/docs/guiding-principles). From my experience, following these principles makes tests much easier to write, and much more brittle to change.

Our preferred approach should be **React Testing Library** We should also consider moving snapshots to Storybook

![image](https://user-images.githubusercontent.com/9516420/140932429-263ad346-9ae7-4a0e-a571-21fb7a875d56.png)

### Goal

To complete this issue we should:
- Only use a single testing library across our frontend unit tests
- Have clear documentation that describes how we should write our frontend unit tests

### Tracked issues

@gitstart-sourcegraph

Completed
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/27280 
- [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/27281 

@umpox

Completed
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/27273 
- [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/issues/28459 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by umpox** [comment]
TODO: (Pending no major reasons against this approach)
- Link issue to refactor Enzyme usage to React Testing Library
- Link issue to refactor React Test Renderer usage to React Testing Library
- Link issue to improve testing documentation
- Add code insight to track imports of each lib

**Comment by felixfbecker** [comment]
I think we wanted to migrate everything to Enzyme because it was the only one that allowed easy customization of how specific types are rendered. E.g. passed `Observable`s or other deep object structures were causing huge blobs in snapshot outputs, making them hard to review.

**If** we want to maintain that and consider shallow rendering an anti pattern, that could probably also be solved with an eslint rule banning the shallow renderer.

**Comment by umpox** [comment]
That's interesting, when I've got chance I'll get an example branch up compare a few different patterns across libraries (like snapshot behavior).

I'd also say that pattern is what we should work towards move away from (following the same principles of testing library). Testing/snapshotting props passed between components is testing implementation more than functionality, meaning if those props change (through refactoring), the tests will fail again. Ideally the tests only fail when the functionality changes, so we can completely refactor parts of the codebase and use our tests as validation that nothing broke.

**Comment by pdubroy** [comment]
Update from 2021-12-02:

<img width="516" alt="CleanShot 2021-12-02 at 10 23 56@2x" src="https://user-images.githubusercontent.com/17293/144394199-0a4bd38d-54dd-4954-a7f2-5b2a72330a3c.png">

**Comment by umpox** [comment]
Closing as this migration has now been completed!

![image](https://user-images.githubusercontent.com/9516420/145605981-480791bc-89fd-4aad-a990-72a78cb3c374.png)
