### ISSUE TITLE
3.32.0 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#25003]
# 3.32.0 managed instances upgrade

These [managed instances](https://about.sourcegraph.com/handbook/engineering/distribution/managed) upgrades are scheduled for **[Sep 21, 2021, 6:00 PM (UTC)](https://time.is/1800_21_Sep_2021_in_UTC?One%20working%20day%20after%203.32%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](https://about.sourcegraph.com/handbook/engineering/distribution/managed/upgrade_process).

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com)

## Upgrade customer managed instances

- [x] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/1712860829](https://app.hubspot.com/contacts/2762526/company/1712860829/)
- [x] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/974657309/](https://app.hubspot.com/contacts/2762526/company/974657309/)
- [x] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/962613882/](https://app.hubspot.com/contacts/2762526/company/962613882/)
- [x] Upgrade instance for [https://app.hubspot.com/contacts/2762526/contact/37418051](https://app.hubspot.com/contacts/2762526/contact/37418051)
- [x] Upgrade instance for [https://app.hubspot.com/contacts/2762526/contact/31240401](https://app.hubspot.com/contacts/2762526/contact/31240401)
- [x] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/6301327782](https://app.hubspot.com/contacts/2762526/company/6301327782)
- [x] Upgrade instance for [https://app.hubspot.com/contacts/2762526/company/6284643600/](https://app.hubspot.com/contacts/2762526/company/6284643600/)

---

Also see [3.32.0 release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/25002)

**Comment by davejrt** [comment]
Superseded by #25167
