### ISSUE TITLE
Tracking issue: Decouple migrations from code deployments

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#25247]
### Plan

This issue tracks the progress of [RFC 469: Decouple migrations from code deployments](https://docs.google.com/document/d/1_wqvNbEGhMzu45CHZNrLQYys7gl0AtVpLluGp4cbQKk).

### Tracked issues

@unassigned

Completed
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/31435 
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/issues/31919 

@caugustus-sourcegraph

Completed
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/31256 
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/30362 

@danieldides

Completed
- [x] (🏁 81 days ago) https://github.com/sourcegraph/sourcegraph/issues/25258 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/issues/25256 (PRs: ~[#28437](https://github.com/sourcegraph/sourcegraph/pull/28437)~)
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/25257 
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/31434 
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/issues/31433 
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/issues/25255 (PRs: ~[#28437](https://github.com/sourcegraph/sourcegraph/pull/28437)~)

@efritz

Completed
- [x] (🏁 117 days ago) https://github.com/sourcegraph/sourcegraph/pull/28440 
- [x] (🏁 117 days ago) https://github.com/sourcegraph/sourcegraph/pull/28441 
- [x] (🏁 117 days ago) https://github.com/sourcegraph/sourcegraph/pull/28496 
- [x] (🏁 116 days ago) https://github.com/sourcegraph/sourcegraph/pull/28499 
- [x] (🏁 116 days ago) https://github.com/sourcegraph/sourcegraph/pull/28548 
- [x] (🏁 116 days ago) https://github.com/sourcegraph/sourcegraph/pull/28551 
- [x] (🏁 116 days ago) https://github.com/sourcegraph/sourcegraph/pull/28550 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/28596 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/28600 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/28599 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/28598 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/28615 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/28619 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/28618 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/28616 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/28617 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/28632 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/28636 
- [x] (🏁 113 days ago) https://github.com/sourcegraph/sourcegraph/pull/28642 
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/pull/28648 
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/pull/28649 
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/pull/28659 
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/pull/28688 
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/pull/28687 
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/pull/28686 
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/28712 
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/28710 
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/28713 
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/28714 
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/28715 
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/28718 
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/28740 
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/28739 
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/28746 
- [x] (🏁 110 days ago) https://github.com/sourcegraph/sourcegraph/pull/28751 
- [x] (🏁 110 days ago) https://github.com/sourcegraph/sourcegraph/pull/28650 
- [x] (🏁 110 days ago) https://github.com/sourcegraph/sourcegraph/pull/28150 
- [x] (🏁 110 days ago) https://github.com/sourcegraph/sourcegraph/pull/28693 
- [x] (🏁 110 days ago) https://github.com/sourcegraph/sourcegraph/pull/28767 
- [x] (🏁 110 days ago) https://github.com/sourcegraph/sourcegraph/pull/28768 
- [x] (🏁 110 days ago) https://github.com/sourcegraph/sourcegraph/pull/28772 
- [x] (🏁 109 days ago) https://github.com/sourcegraph/sourcegraph/pull/28818 
- [x] (🏁 109 days ago) https://github.com/sourcegraph/sourcegraph/pull/28820 
- [x] (🏁 109 days ago) https://github.com/sourcegraph/sourcegraph/pull/28824 
- [x] (🏁 109 days ago) https://github.com/sourcegraph/sourcegraph/pull/28850 
- [x] (🏁 109 days ago) https://github.com/sourcegraph/sourcegraph/issues/25259 
- [x] (🏁 109 days ago) https://github.com/sourcegraph/sourcegraph/issues/25253 (PRs: ~[#28437](https://github.com/sourcegraph/sourcegraph/pull/28437)~)
- [x] (🏁 109 days ago) https://github.com/sourcegraph/sourcegraph/issues/25254 
- [x] (🏁 105 days ago) https://github.com/sourcegraph/sourcegraph/pull/28952 
- [x] (🏁 105 days ago) https://github.com/sourcegraph/sourcegraph/pull/28959 
- [x] (🏁 105 days ago) https://github.com/sourcegraph/sourcegraph/pull/28955 
- [x] (🏁 105 days ago) https://github.com/sourcegraph/sourcegraph/pull/28953 
- [x] (🏁 105 days ago) https://github.com/sourcegraph/sourcegraph/pull/28929 
- [x] (🏁 103 days ago) https://github.com/sourcegraph/sourcegraph/issues/25261 (PRs: ~[#28804](https://github.com/sourcegraph/sourcegraph/pull/28804)~)
- [x] (🏁 102 days ago) https://github.com/sourcegraph/sourcegraph/pull/29123 
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/25250 
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/25251 
- [x] (🏁 78 days ago) https://github.com/sourcegraph/sourcegraph/issues/25249 (PRs: ~[#28872](https://github.com/sourcegraph/sourcegraph/pull/28872)~)
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/30013 
- [x] (🏁 61 days ago) https://github.com/sourcegraph/sourcegraph/pull/30248 
- [x] (🏁 61 days ago) https://github.com/sourcegraph/sourcegraph/pull/30249 
- [x] (🏁 61 days ago) https://github.com/sourcegraph/sourcegraph/pull/30250 
- [x] (🏁 61 days ago) https://github.com/sourcegraph/sourcegraph/pull/30251 
- [x] (🏁 61 days ago) https://github.com/sourcegraph/sourcegraph/pull/30262 
- [x] (🏁 61 days ago) https://github.com/sourcegraph/sourcegraph/pull/30269 
- [x] (🏁 61 days ago) https://github.com/sourcegraph/sourcegraph/pull/30270 
- [x] (🏁 61 days ago) https://github.com/sourcegraph/sourcegraph/pull/30271 
- [x] (🏁 61 days ago) https://github.com/sourcegraph/sourcegraph/pull/30273 
- [x] (🏁 61 days ago) https://github.com/sourcegraph/sourcegraph/pull/30265 
- [x] (🏁 61 days ago) https://github.com/sourcegraph/sourcegraph/pull/30268 
- [x] (🏁 60 days ago) https://github.com/sourcegraph/sourcegraph/pull/30314 
- [x] (🏁 60 days ago) https://github.com/sourcegraph/sourcegraph/pull/30309 
- [x] (🏁 60 days ago) https://github.com/sourcegraph/sourcegraph/pull/30319 
- [x] (🏁 60 days ago) https://github.com/sourcegraph/sourcegraph/pull/30318 
- [x] (🏁 59 days ago) https://github.com/sourcegraph/sourcegraph/pull/30321 
- [x] (🏁 59 days ago) https://github.com/sourcegraph/sourcegraph/pull/30276 
- [x] (🏁 58 days ago) https://github.com/sourcegraph/sourcegraph/pull/30386 
- [x] (🏁 58 days ago) https://github.com/sourcegraph/sourcegraph/pull/30388 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/pull/30403 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/pull/30405 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/pull/30406 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/pull/30407 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/pull/30411 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/pull/30418 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/pull/30409 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/pull/30408 
- [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/pull/30423 
- [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/pull/30428 
- [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/pull/30456 
- [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/pull/30458 
- [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/pull/30455 
- [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/pull/30457 
- [x] (🏁 55 days ago) https://github.com/sourcegraph/sourcegraph/pull/30526 
- [x] (🏁 55 days ago) https://github.com/sourcegraph/sourcegraph/pull/30512 
- [x] (🏁 55 days ago) https://github.com/sourcegraph/sourcegraph/pull/30509 
- [x] (🏁 55 days ago) https://github.com/sourcegraph/sourcegraph/pull/30542 
- [x] (🏁 55 days ago) https://github.com/sourcegraph/sourcegraph/pull/30501 
- [x] (🏁 55 days ago) https://github.com/sourcegraph/sourcegraph/pull/30544 
- [x] (🏁 55 days ago) https://github.com/sourcegraph/sourcegraph/pull/30549 
- [x] (🏁 54 days ago) https://github.com/sourcegraph/sourcegraph/pull/30602 
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/pull/30511 
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/pull/30514 
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/pull/30664 
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/pull/30693 
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/pull/30786 
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/pull/30773 
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/pull/30772 
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/pull/30855 
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/pull/29831 
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/pull/30846 
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/pull/30860 
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/pull/30863 
- [x] (🏁 46 days ago) https://github.com/sourcegraph/sourcegraph/pull/30936 
- [x] (🏁 46 days ago) https://github.com/sourcegraph/sourcegraph/pull/30774 
- [x] (🏁 46 days ago) https://github.com/sourcegraph/sourcegraph/pull/31086 
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/pull/30776 
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/pull/30760 
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/pull/31099 
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/31366 (PRs: ~[#31429](https://github.com/sourcegraph/sourcegraph/pull/31429)~)
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/31367 (PRs: ~[#31452](https://github.com/sourcegraph/sourcegraph/pull/31452)~)
- [x] (🏁 36 days ago) https://github.com/sourcegraph/sourcegraph/pull/31584 
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/pull/29144 
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/pull/31505 
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/pull/31603 
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/pull/31599 
- [x] (🏁 34 days ago) https://github.com/sourcegraph/sourcegraph/issues/25260 
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/31372 

@michaellzc

Completed
- [x] (🏁 32 days ago) https://github.com/sourcegraph/sourcegraph/issues/31257 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by efritz** [comment]
@scalabilitysolved If you add a label to this you have to add it to everything it tracks otherwise you have an empty issue description 😬

**Comment by scalabilitysolved** [comment]
Eeek, sorry about that @efritz , I didn't realize. Thanks for the catch!

**Comment by jyavorska** [comment]
In the product engineering project, this item has a delivery date of FY22 Q4 which is in the past. @macraig can you please take a look?
