### ISSUE TITLE
Search Contexts are the one way to specify a subset of code to search

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#25518]
This epic tracks our work towards making search contexts the only way one should specify a subset of code to search.

Entails:

- [ ] Deprecating version contexts https://github.com/sourcegraph/sourcegraph/issues/24505
- [ ] Transitioning repogroups to search contexts https://github.com/sourcegraph/sourcegraph/issues/24269
- [ ] Making search contexts GA https://github.com/sourcegraph/sourcegraph/issues/24503
- [ ] UI updates to support search context migration for community pages https://github.com/sourcegraph/sourcegraph/issues/25110
