### ISSUE TITLE
RFC 496: Continuous integration observability

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#25768]
This is a tracking issue for [RFC 496](https://docs.google.com/document/d/1fknr3NQGmwbKCfnF3Bcr-tYzV-TeuAGq-_Tm2-z_09M/edit#), a sub-RFC of #25348 

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37826  🛠️
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/26083 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/38346  🛠️
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/26073 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/26083 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/26101 
  - [x] (🏁 240 days ago) https://github.com/sourcegraph/sourcegraph/issues/26098 (PRs: ~[#26980](https://github.com/sourcegraph/sourcegraph/pull/26980)~)
  - [x] (🏁 161 days ago) https://github.com/sourcegraph/sourcegraph/issues/28283 

Completed
- [x] (🏁 240 days ago) https://github.com/sourcegraph/sourcegraph/issues/26098 (PRs: ~[#26980](https://github.com/sourcegraph/sourcegraph/pull/26980)~)
- [x] (🏁 161 days ago) https://github.com/sourcegraph/sourcegraph/issues/28283 

@bobheadxi

- [ ] https://github.com/sourcegraph/sourcegraph/issues/38346  🛠️
  - [x] (🏁 272 days ago) https://github.com/sourcegraph/sourcegraph/pull/25749 
  - [x] (🏁 271 days ago) https://github.com/sourcegraph/sourcegraph/pull/25810 
  - [x] (🏁 267 days ago) https://github.com/sourcegraph/sourcegraph/pull/25835 
  - [x] (🏁 145 days ago) https://github.com/sourcegraph/sourcegraph/issues/26071 
  - [x] (🏁 172 days ago) https://github.com/sourcegraph/sourcegraph/issues/26118 (PRs: ~[#28002](https://github.com/sourcegraph/sourcegraph/pull/28002)~)

Completed
- [x] (🏁 272 days ago) https://github.com/sourcegraph/sourcegraph/pull/25749 
- [x] (🏁 271 days ago) https://github.com/sourcegraph/sourcegraph/pull/25810 
- [x] (🏁 267 days ago) https://github.com/sourcegraph/sourcegraph/pull/25835 
- [x] (🏁 172 days ago) https://github.com/sourcegraph/sourcegraph/issues/26118 (PRs: ~[#28002](https://github.com/sourcegraph/sourcegraph/pull/28002)~)
- [x] (🏁 145 days ago) https://github.com/sourcegraph/sourcegraph/issues/26071 

@burmudar: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37826  __3.00d__ 🛠️
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/26072  __3.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/38346  __3.00d__ 🛠️
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/26072  __3.00d__

Completed
- [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/34608  __3.00d__

@jhchabran

- [ ] https://github.com/sourcegraph/sourcegraph/issues/38346  🛠️
  - [x] (🏁 252 days ago) https://github.com/sourcegraph/sourcegraph/issues/25562 (PRs: ~[#25835](https://github.com/sourcegraph/sourcegraph/pull/25835)~, ~[#26259](https://github.com/sourcegraph/sourcegraph/pull/26259)~)
  - [x] (🏁 268 days ago) https://github.com/sourcegraph/sourcegraph/pull/25892 
  - [x] (🏁 172 days ago) https://github.com/sourcegraph/sourcegraph/issues/26118 (PRs: ~[#28002](https://github.com/sourcegraph/sourcegraph/pull/28002)~)
  - [x] (🏁 173 days ago) https://github.com/sourcegraph/sourcegraph/issues/29411 

Completed
- [x] (🏁 268 days ago) https://github.com/sourcegraph/sourcegraph/pull/25892 
- [x] (🏁 252 days ago) https://github.com/sourcegraph/sourcegraph/issues/25562 (PRs: ~[#25835](https://github.com/sourcegraph/sourcegraph/pull/25835)~, ~[#26259](https://github.com/sourcegraph/sourcegraph/pull/26259)~)
- [x] (🏁 173 days ago) https://github.com/sourcegraph/sourcegraph/issues/29411 
- [x] (🏁 172 days ago) https://github.com/sourcegraph/sourcegraph/issues/26118 (PRs: ~[#28002](https://github.com/sourcegraph/sourcegraph/pull/28002)~)

**Comment by bobheadxi** [comment]
Closing this as done!
