### ISSUE TITLE
Code Insights Capture Groups Tracking issue

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#25972]
Track distinct values captured by regex capture groups in separate insights series.

![](https://pb-files.s3.amazonaws.com/production/attachments/125f18f756c6b87648b9f70d52ee12e79431937b09f93db2eb5f0c7137399e28/image.png)

For details, see the:

- [Productboard feature](https://sourcegraph.productboard.com/roadmap/3362047-code-insights-beta-to-ga/features/8057379/detail)
- [Product Brief RFC](https://docs.google.com/document/d/18yTOcOUmxOXka_UTZkkcCIsFY3dhA7r0eQukomt4rho/edit#heading=h.trqab8y0kufp)

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/28633  🐛
- [ ] https://github.com/sourcegraph/sourcegraph/issues/28802 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/29552 

Completed
- [x] (🏁 46 days ago) https://github.com/sourcegraph/sourcegraph/issues/28795 

@CristinaBirkel

Completed
- [x] (🏁 17 days ago) https://github.com/sourcegraph/sourcegraph/issues/29025  🐛   🏳️ [Insights iteration 9](https://github.com/sourcegraph/sourcegraph/milestone/149)

@Joelkw

Completed
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/pull/29218 

@coury-clark

Completed
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/issues/27435    🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/issues/28631    🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/28630    🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)

@unclejustin

Completed
- [x] (🏁 45 days ago) https://github.com/sourcegraph/sourcegraph/issues/28022    🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/28392    🏳️ [Insights iteration 8](https://github.com/sourcegraph/sourcegraph/milestone/148)
- [x] (🏁 40 days ago) https://github.com/sourcegraph/sourcegraph/issues/28622    🏳️ [Insights iteration 8](https://github.com/sourcegraph/sourcegraph/milestone/148)
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/issues/29551    🏳️ [Insights iteration 9](https://github.com/sourcegraph/sourcegraph/milestone/149)

@vovakulikov

Completed
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/issues/28627    🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 45 days ago) https://github.com/sourcegraph/sourcegraph/issues/28022    🏳️ [Insights iteration 7](https://github.com/sourcegraph/sourcegraph/milestone/143)
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/28026    🏳️ [Insights iteration 8](https://github.com/sourcegraph/sourcegraph/milestone/148)
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/28392    🏳️ [Insights iteration 8](https://github.com/sourcegraph/sourcegraph/milestone/148)
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/28628    🏳️ [Insights iteration 8](https://github.com/sourcegraph/sourcegraph/milestone/148)
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/28018    🏳️ [Insights iteration 8](https://github.com/sourcegraph/sourcegraph/milestone/148)
- [x] (🏁 40 days ago) https://github.com/sourcegraph/sourcegraph/issues/28622    🏳️ [Insights iteration 8](https://github.com/sourcegraph/sourcegraph/milestone/148)
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/28878    🏳️ [Insights iteration 9](https://github.com/sourcegraph/sourcegraph/milestone/149)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by felixfbecker** [comment]
Closing this as V1 has been implemented.
