### ISSUE TITLE
RFC 497: Restructuring CI experience

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#26182]
Tracking issue for [RFC 497: Restructuring CI Experience](https://docs.google.com/document/d/1QqOb0ZDuUDSB57RM_YLzqAPFaFnDGq-8AES5yppWiqg/edit)

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/28286 

Completed
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/28285 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/28288 

@bobheadxi

Completed
- [x] (🏁 34 days ago) https://github.com/sourcegraph/sourcegraph/issues/30203 

@jhchabran

- [ ] https://github.com/sourcegraph/sourcegraph/issues/28287 

Completed
- [x] (🏁 92 days ago) https://github.com/sourcegraph/sourcegraph/pull/28974 
- [x] (🏁 91 days ago) https://github.com/sourcegraph/sourcegraph/issues/28281 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by jhchabran** [comment]
We have decided to sunset this RFC for clarity, though parts of its proposed solution have been implemented already.
