### ISSUE TITLE
WIP: Code intel docs update Tracking issue

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#26230]
### Plan

Update and revamp Code Intelligence docs.

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/26999 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27576 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/45043 

Completed
- [x] (🏁 1293 days ago) https://github.com/sourcegraph/sourcegraph/issues/9362 
- [x] (🏁 865 days ago) https://github.com/sourcegraph/sourcegraph/issues/12501    🏳️ [3.21](https://github.com/sourcegraph/sourcegraph/milestone/46)
- [x] (🏁 861 days ago) https://github.com/sourcegraph/sourcegraph/issues/17988 
- [x] (🏁 788 days ago) https://github.com/sourcegraph/sourcegraph/issues/18443 
- [x] (🏁 788 days ago) https://github.com/sourcegraph/sourcegraph/issues/18442 (PRs: ~[#23916](https://github.com/sourcegraph/sourcegraph/pull/23916)~)
- [x] (🏁 788 days ago) https://github.com/sourcegraph/sourcegraph/issues/18444 (PRs: ~[#23916](https://github.com/sourcegraph/sourcegraph/pull/23916)~)
- [x] (🏁 788 days ago) https://github.com/sourcegraph/sourcegraph/issues/18446 (PRs: ~[#23916](https://github.com/sourcegraph/sourcegraph/pull/23916)~)
- [x] (🏁 469 days ago) https://github.com/sourcegraph/sourcegraph/issues/27095 

@Strum355

Completed
- [x] (🏁 1148 days ago) https://github.com/sourcegraph/sourcegraph/issues/13096  🐛
- [x] (🏁 539 days ago) https://github.com/sourcegraph/sourcegraph/pull/34095 
- [x] (🏁 330 days ago) https://github.com/sourcegraph/sourcegraph/pull/44359 

@aidaeology: __0.50d__

Completed: __0.50d__
- [x] (🏁 1152 days ago) https://github.com/sourcegraph/sourcegraph/issues/8351 
- [x] (🏁 1151 days ago) https://github.com/sourcegraph/sourcegraph/pull/13041 
- [x] (🏁 1149 days ago) https://github.com/sourcegraph/sourcegraph/pull/13078 
- [x] (🏁 1148 days ago) https://github.com/sourcegraph/sourcegraph/pull/13108 
- [x] (🏁 1148 days ago) https://github.com/sourcegraph/sourcegraph/issues/13096  🐛
- [x] (🏁 1147 days ago) https://github.com/sourcegraph/sourcegraph/issues/13049    🏳️ [3.19](https://github.com/sourcegraph/sourcegraph/milestone/44)
- [x] (🏁 1141 days ago) https://github.com/sourcegraph/sourcegraph/pull/13333 
- [x] (🏁 1108 days ago) https://github.com/sourcegraph/sourcegraph/issues/14224  __0.50d__   🏳️ [3.21](https://github.com/sourcegraph/sourcegraph/milestone/46)

@beyang

Completed
- [x] (🏁 1108 days ago) https://github.com/sourcegraph/sourcegraph/pull/14211 

@cesrjimenez

Completed
- [x] (🏁 155 days ago) https://github.com/sourcegraph/sourcegraph/issues/51533 

@christinaforney

Completed
- [x] (🏁 1422 days ago) https://github.com/sourcegraph/sourcegraph/pull/6657 

@efritz

Completed
- [x] (🏁 1266 days ago) https://github.com/sourcegraph/sourcegraph/issues/9987  🐛   🏳️ [3.16](https://github.com/sourcegraph/sourcegraph/milestone/41)
- [x] (🏁 1236 days ago) https://github.com/sourcegraph/sourcegraph/issues/9719    🏳️ [3.17](https://github.com/sourcegraph/sourcegraph/milestone/42)
- [x] (🏁 1180 days ago) https://github.com/sourcegraph/sourcegraph/issues/9609    🏳️ [3.18](https://github.com/sourcegraph/sourcegraph/milestone/43)
- [x] (🏁 1148 days ago) https://github.com/sourcegraph/sourcegraph/issues/13096  🐛
- [x] (🏁 1147 days ago) https://github.com/sourcegraph/sourcegraph/issues/13049    🏳️ [3.19](https://github.com/sourcegraph/sourcegraph/milestone/44)
- [x] (🏁 978 days ago) https://github.com/sourcegraph/sourcegraph/issues/16412    🏳️ [Code Intelligence Sprint 5](https://github.com/sourcegraph/sourcegraph/milestone/93)
- [x] (🏁 788 days ago) https://github.com/sourcegraph/sourcegraph/issues/23778 (PRs: ~[#23916](https://github.com/sourcegraph/sourcegraph/pull/23916)~)
- [x] (🏁 643 days ago) https://github.com/sourcegraph/sourcegraph/issues/24602 
- [x] (🏁 155 days ago) https://github.com/sourcegraph/sourcegraph/issues/51533 

@macraig

- [ ] https://github.com/sourcegraph/sourcegraph/issues/26229 

Completed
- [x] (🏁 862 days ago) https://github.com/sourcegraph/sourcegraph/issues/18123 
- [x] (🏁 791 days ago) https://github.com/sourcegraph/sourcegraph/issues/16473 
- [x] (🏁 791 days ago) https://github.com/sourcegraph/sourcegraph/issues/17621 
- [x] (🏁 643 days ago) https://github.com/sourcegraph/sourcegraph/issues/24602 
- [x] (🏁 601 days ago) https://github.com/sourcegraph/sourcegraph/issues/26225 
- [x] (🏁 469 days ago) https://github.com/sourcegraph/sourcegraph/issues/26226 
- [x] (🏁 469 days ago) https://github.com/sourcegraph/sourcegraph/issues/26227 
- [x] (🏁 469 days ago) https://github.com/sourcegraph/sourcegraph/issues/27094 

@ryan-blunden

Completed
- [x] (🏁 1670 days ago) https://github.com/sourcegraph/sourcegraph/issues/2559  👩   🏳️ [3.2](https://github.com/sourcegraph/sourcegraph/milestone/17)

@shrouxm

Completed
- [x] (🏁 1239 days ago) https://github.com/sourcegraph/sourcegraph/issues/10452    🏳️ [3.16](https://github.com/sourcegraph/sourcegraph/milestone/41)
- [x] (🏁 1239 days ago) https://github.com/sourcegraph/sourcegraph/issues/10576    🏳️ [3.16](https://github.com/sourcegraph/sourcegraph/milestone/41)
- [x] (🏁 1148 days ago) https://github.com/sourcegraph/sourcegraph/issues/13096  🐛
