### ISSUE TITLE
Architecture setup for VS Code extension 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#26429]
### Plan
Tracking issue for architecture work being done by @tjkandala . This issue covers: 
- Any exploratory work being done on how to expose Search
- Implementation work to switch from current notebook setup to webviews. You can read about that decision [here](https://docs.google.com/document/d/13fL-2lSqVzA7PajvmHRFZBYXYSrkCdsIPb2QsREdY9Q/edit#heading=h.2ovpjolqupyb).

### Tracked issues

@tjkandala

Completed
- [x] (🏁 663 days ago) https://github.com/sourcegraph/sourcegraph/issues/26445    🏳️ [Extensibility 3](https://github.com/sourcegraph/sourcegraph/milestone/138)
- [x] (🏁 538 days ago) https://github.com/sourcegraph/sourcegraph/issues/26448    🏳️ [Extensibility 3](https://github.com/sourcegraph/sourcegraph/milestone/138)
- [x] (🏁 538 days ago) https://github.com/sourcegraph/sourcegraph/issues/26440    🏳️ [Extensibility 3](https://github.com/sourcegraph/sourcegraph/milestone/138)
- [x] (🏁 538 days ago) https://github.com/sourcegraph/sourcegraph/issues/26438    🏳️ [Extensibility 3](https://github.com/sourcegraph/sourcegraph/milestone/138)
