### ISSUE TITLE
Expose Search on VS Code extension 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#26432]
### Plan
Tracking issue for any core-search related work being done on the VS Code extension.
- Any UI work related to exposing Search 
- Any performance work related to exposing Search

### Tracked issues

@jjinnii

- [ ] https://github.com/sourcegraph/sourcegraph/issues/26457    🏳️ [Extensibility 3](https://github.com/sourcegraph/sourcegraph/milestone/138)

@tjkandala

Completed
- [x] (🏁 538 days ago) https://github.com/sourcegraph/sourcegraph/issues/26441    🏳️ [Extensibility 3](https://github.com/sourcegraph/sourcegraph/milestone/138)
- [x] (🏁 538 days ago) https://github.com/sourcegraph/sourcegraph/issues/26455    🏳️ [Extensibility 3](https://github.com/sourcegraph/sourcegraph/milestone/138)
