### ISSUE TITLE
Improve client error tracking of the Sourcegraph application: Tracking issue

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#26570]
## Problem to solve

Today, we lack processes around client-side error monitoring, error reporting, and prioritizing and fixing runtime errors. Consequently, it can be difficult for Sourcegraph engineers to see, understand, and fix problems in the Sourcegraph application, which has a negative impact on engineering teams' effectiveness and, ultimately, on our customers. For the observability of on-prem instances, distributed traces, and other more advanced observability efforts, we'll follow the lead of the DevX team. 

## Measure of success

- [ ] We have a robust process for runtime error monitoring on the client, and it's documented in the handbook. 
- [ ] Relevant services and tools are configured to support the error monitoring process documented in the handbook. 
- [ ] An automated notification process lets the right people know there's an issue, and we have documentation that tells them how to address it. 

## Solution summary

- [x] Evaluate the relative advantages and disadvantages of Sentry vs Datadog and determine the best path forward
- [ ] Improve Sentry configuration to make production error debugging easier. 
- [ ] Collaborate with the DevX team on proxying client events through our backend.
- [ ] Introduce guidelines on error handling in client applications. 

What we're not doing right now:
- Explore ways to allow on-prem clients to share logs with the Sourcegraph team to speed up debugging.
- Extend Open Telemetry traces into the frontend, so that client teams can easily collect a sequence of events to debug client issues
- Explore what `src debug` can do today in regard to traces, and see if it can be used to export client log events as well

Artifacts:
- [RFC 501 REVIEW: Runtime error monitoring](https://docs.google.com/document/d/1d18e_YFJsw5cgDId8Iz1MT8A_GsHZTOGHMuem1JMzuM/edit#)

## What specific customers are we iterating on the problem and solution with?

Internal Sourcegraph developers

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/26580 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26583 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26585 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

@plibither8: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/26579  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26581  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26582  __1.00d__

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555  __3.00d__
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714  __3.00d__
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702  __3.00d__
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682  __3.00d__
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354  __3.00d__

@valerybugakov

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.

**Comment by daxmc99** [comment]
We are sunsetting all usage of Datadog https://github.com/sourcegraph/sourcegraph/issues/27386
