### ISSUE TITLE
Tracking issue: Global state management

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#26655]
### Motivation
We want to move forward with a global state management solution to address some of the problems in [RFC 391](https://docs.google.com/document/d/1-CBkQMO8Db3onfBF4onEn4I_3YljsfxIeJ6h64ZynGM/edit#heading=h.twdj57egor10).

The two proposed approaches here are either [useContextSelector](https://github.com/dai-shi/use-context-selector) or [Zustand](https://github.com/pmndrs/zustand).

Our view is that both approaches are actually quite similar. There is an important issue to be solved that is to avoid multiple stores creating non-directional dependencies. This is a potential problem in both libraries and we'll need extra work to make sure we avoid this!

### Plan

It's important we decide on a single approach so we can move forward with this, our proposed solution is:

**Adapt Zustand to use a single global store, add better linting and improve documentation**

How we will do this:
- Update existing Zustand code to use a global store. This means moving part of [this code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@tr/webpack-manifest-local/-/blob/client/web/src/search/navbarSearchQueryState.ts#L69:3) to be a generic store, [similar to how we create the Apollo cache.](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=tr%2Fwebpack-manifest-local&file=client%2Fshared%2Fsrc%2Fgraphql%2Fapollo%2Fcache.ts&editor=VSCode&version=1.4.0&start_row=0&start_col=0&end_row=0&end_col=0).
- Add an eslint rule to ban this kind of import: `import create from 'zustand'`. This is to enforce that we only allow creating a single global store. The one exception to this rule will be where we actually create the global store 😃 
- Add more documentation:
  - Managing different types of state:
    - Global state: shared across the application and should be stored in a single Zustand store. 
    - 'Localized' state: Will typically be used for things like reusable components, and may change depending on some configuration, should be stored in a normal React context. Example: Setting a `compact` state for all `FilteredConnection` UI components in a tree.
    - GraphQL state: Data fetched from our backend API, should be stored in the Apollo cache.
    - Local state: Normal React state that should be isolated in components, e.g. `useState`
  - FAQS
    - How to test
    - Common problems
    - ... etc

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/26658 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/28545 

@fkling

Completed
- [x] (🏁 698 days ago) https://github.com/sourcegraph/sourcegraph/issues/26656 
- [x] (🏁 672 days ago) https://github.com/sourcegraph/sourcegraph/pull/28491 

@umpox

Completed
- [x] (🏁 673 days ago) https://github.com/sourcegraph/sourcegraph/issues/26657 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request
