### ISSUE TITLE
3.34.0 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#26715]
# 3.34.0 managed instances upgrade

These [managed instances](../enablement/delivery/managed/index.md) upgrades are scheduled for **[Nov 23, 2021, 6:00 PM (UTC)](https://time.is/1800_23_Nov_2021_in_UTC?One%20working%20day%20after%203.34%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](https://handbook.sourcegraph.com/product-engineering/engineering/enablement/delivery/managed/upgrade_process).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [ ] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [ ] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.

## Upgrade customer managed instances

- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8195
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/1503

---

Also see [3.34.0 release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/26714)

**Comment by caugustus-sourcegraph** [comment]
Superseded by #27765

**Comment by bobheadxi** [comment]
Ah, weird bug in release tool - closing a later upgrade tracking issue 🤔

**Comment by caugustus-sourcegraph** [comment]
Superseded by #27856

**Comment by kevinwojo** [comment]
Superseded by #28043

**Comment by kevinwojo** [comment]
Superseded by #28105
