### ISSUE TITLE
Embrace Open Source contributions: Tracking issue

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#26991]
## What is it

The central place to track issues related to making the Sourcegraph repo more friendly to Open Source contributions. Based on our [experience](https://docs.google.com/document/d/11aD-ItGOw_s56cDkER71iMzFRkGe2MCPzESTKQ2rUGU/edit#) in participating in Hacktoberfest 2021 and [the Open Source leverage RFC](https://docs.google.com/document/d/1MkIL476kWiG5Y3HOYw1c0S1hbhs3FC496n9O2dewdUs/edit).

## Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/26993 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27001 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27002 

@bobheadxi

Completed
- [x] (🏁 496 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  🛠️

@mrnugget: __3.00d__

Completed: __3.00d__
- [x] (🏁 510 days ago) https://github.com/sourcegraph/sourcegraph/issues/28794  __3.00d__

### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by pdubroy** [comment]
@valerybugakov Is the intention here that this be an evergreen issue? Or is there a point where we can call this "done"?
