### ISSUE TITLE
Add tracking of inbound browser extension/code host integration traffic

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#27082]
The browser extension promotes users returning to the product frequently, thus it improves retention. As retention is a primary goal, we should more fully understand the amount of traffic the extension produces for both Cloud and self-hosted installations. 

Currently, there is no tracking of the browser extension to Sourcegraph installations. 

- [x] Add a method of tracking to link created by the extension to Sourcegraph instances
- [x] Add an event log to record an inbound link from the browser extension
- [x] Ensure this event is present in Amplitude
- [ ] #31059

**Comment by erzhtor** [comment]
@rrhyne, I've created draft [RFC 573](https://docs.google.com/document/d/1pgSZ1Lp6nG8UbRAuRJJZMjD4J343PbbeljBsK3_Z5Fk/edit#heading=h.trqab8y0kufp). Please, take a look when you will have time? Once we think it is good to enough, we can share w/ analytics team for their review.

**Comment by erzhtor** [comment]
@rrhyne, for better tracking across milestones/iterations I've separated it into two parts:
> - Add a method of tracking to link created by the extension to Sourcegraph instances
> - Add an event log to record an inbound link from the browser extension
> - Ensure this event is present in Amplitude

These are done and merged to the main branch, so will be closing this ticket.

> - Add pings to this event for self-hosted installations for

For the pings part, I've created a follow-up issue pings https://github.com/sourcegraph/sourcegraph/issues/31059 since it is taking longer for RFC to get the review/approval + preparing pings PR.

Please let me know if we think we should not separate into two tickets?
