### ISSUE TITLE
Improve browser extension acquisition

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#27100]
Sourcegraph browser extensions promote retention at a very high rate. Retention gives us additional time to prove value, and thus a longer timeframe in which to convert users to PQLs. If we then optimize the discoverability of the browser extensions we will improve the percentage of users who have installed the extension, and generate additional PQLs.

Currently, there are two prompts for installing a browser extension, one is a popover that occurs while the user is doing other tasks and a small button on file views. This popover is often closed by users instead of installing the extension. Another CTA from the repo homepage is too small to be seen frequently. 

We should improve this funnel by providing additional prompts to install the extension. Some ideas on where this can happen:

- [x] Add a link to install the extension in the getting started tour
- [ ] Add a browser extension CTA in search results for logged in users
- [ ] Adjust the browser extension CTA on file page to use the new style and placement
- [ ] Make the search results CTA dismissable

Steps to achieving this:

- [x] Add the ability to Sourcegraph to determine if the browser extension is not installed 
- [ ] Create design and copy for the CTA (we can repurpose the signup CTA – see below – but we should use a new illustration)
- [ ] Add CTA to file and search results page

**Sign up CTA**

![image](https://user-images.githubusercontent.com/539268/148401897-ad17a51d-80a6-4bff-9137-87c83333b32e.png)

## Metrics

We will know we are successful if:
* we can improve the number of browser extension installations 

## TODOs
- [ ] https://github.com/sourcegraph/sourcegraph/pull/30169
- [ ] [RFC 571](https://docs.google.com/document/d/1RNYu3ZDeT-JGE3rpxfdESUdEKO6ezUKFV5NBhvwd3z8/edit) cc @attfarhan, @rrhyne to Review
  - [ ] https://github.com/sourcegraph/analytics/pull/338 cc @attfarhan to Review
    - [ ] https://github.com/sourcegraph/sourcegraph/pull/29966 cc @attfarhan to Review

**Comment by rrhyne** [comment]
Landing pages are potentially slated for the week of 11/29 or the next.

**Comment by rrhyne** [comment]
@vdavid the browser extension CTAs should link to [this page](https://docs.sourcegraph.com/integration/browser_extension) until we get a better place in the product for them. 

Additionally, we should track these links with UTM parameters so we know where the installations are coming from:

* ?utm_campaign=inproduct-cta&utm_medium=direct_traffic&utm_source={INSERT-PAGE-HERE}-cta&utm_term=null&utm_content=install-browser-exten

INSERT-PAGE-HERE should be file-page or search-results

**Comment by rrhyne** [comment]
Search CTA cadence:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/results/StreamingSearchResults.tsx?L220

We'll need to replicate this on file pages and deal with other CTAs that might be shown there.

**Comment by rrhyne** [comment]
Current CTAs on this page look like an application event:

![image](https://user-images.githubusercontent.com/539268/148570993-7b4194ca-47b4-4635-b3ef-9499924a98bf.png)

Discussion about edits to the above:
https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1641248315005700

**Comment by rrhyne** [comment]
Rules for display as discussed in a 1-1

* This CTA should be shown on the search results page only for authenticated users
* On the file page, we should display the browser extension CTA on every 5th file page view to un-authenticated users to mirror the search results CTA logic
  * [Relevant code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d5bc16e86e2dd98319d3d9756de1258bff8ab50f/-/blob/client/web/src/repo/RepoContainer.tsx?L411:18)
  * [Relevant slack thread](https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1641248315005700)

**Comment by rrhyne** [comment]
As the current file page CTA is dismissable, the new CTA should be dismissable.

**Comment by vdavid** [comment]
I tend to forget much over a weekend, so I summed up the clues for myself from above and from our discussion with @rrhyne

[Figma link](https://www.figma.com/file/VlpvIoBXrG6GFWsEFmc6rB/Browser-extension-CTA-improvements?node-id=0%3A1)

The three tasks and all the clues I got:

1. Add a browser extension CTA in **search results** for logged in users
    * This CTA should be shown on the search results page only for authenticated users.
    * It should link to [this page](https://docs.sourcegraph.com/integration/browser_extension) for now.
    * With this UTM: `?utm_campaign=inproduct-cta&utm_medium=direct_traffic&utm_source={INSERT-PAGE-HERE}-cta&utm_term=null&utm_content=install-browser-exten` (I suppose it was clipped, check how it looks now and use the full UTM)
    * `{INSERT-PAGE-HERE}` should be either “file-page” or “search-results”
    * As the current file page CTA is dismissable, the new CTA should be dismissable.
1. Adjust the browser extension CTA on **file page** to use the new style and placement
    * Current CTAs on this page [look like](https://user-images.githubusercontent.com/539268/148570993-7b4194ca-47b4-4635-b3ef-9499924a98bf.png) an application event. [Here is a discussion](https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1641248315005700) about edits to this.
    * [Search CTA cadence](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/results/StreamingSearchResults.tsx?L220) – We'll need to replicate this on file pages and deal with other CTAs that might be shown there.
    * On the file page, we should display the browser extension CTA on every 5th file page view to un-authenticated users to mirror the search results CTA logic. [Relevant code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d5bc16e86e2dd98319d3d9756de1258bff8ab50f/-/blob/client/web/src/repo/RepoContainer.tsx?L411:18) and [Slack thread](https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1641248315005700)
1. Make the **search results sign up CTA** dismissable
    * This is pretty self-explanatory
    * Juliana Peña did the search results CTA and wrote the local storage library, she can help with the code as needed.

**Comment by vdavid** [comment]
We made good progress on this with @erzhtor today.

@rrhyne, some questions came up that need your input:

1. The **UTM** you provided ends with `install-browser-exten`.
Is that the correct utm_content, or is it clipped?
If it's clipped, am I right to assume it's  `install-browser-extension`?

2. When a user clicks the "sign up" button on the CTA, there's this **log call**: `telemetryService.log('SignUpPLGSearchCTA_1_Search')` ([(link to source code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/web/src/search/results/StreamingSearchResults.tsx?L215)).
I can also make a log call for the browser extension CTA, and I guess I should. Shall I?
If yes, I'll need some help with the naming. I could call it `BrowserExtensionPLGSearchCTA_1_Search` to follow the existing naming. But there will be another instance of the same CTA on the file page. I'll need a name for that too.

    The options that I see, to make responding easier on your end:
   - a.) You **don't care** about this data. I can do whatever I want.
   - b.) You'll **need** this telemetry logging, and I should call it `BrowserExtensionPLGSearchCTA_1_Search` on both pages
   - c.) You'll **need** this, and the names should be **different**, **I can call them** `BrowserExtensionPLGSearchCTA_1_Search` and `BrowserExtensionPLGSearchCTA_1_FilePage`
   - d.) You'll **need** this, the names should be **different**, and **you'll provide** the two names: ...
   - e.) Something else

    On my own, I'd go with **c.)**

3. In the current alert on the file page (the one that is in the wrong format, that looks like a system alert), there is quite a bit of **logic** ([see here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/web/src/repo/actions/InstallBrowserExtensionAlert.tsx)) to decide what link to use for both the copy and the URL to be linked.
4. This is some older, 2020ish code, and it looks like much thought went into this. I think it customizes the message for corporate installs vs. the cloud version, plus gives a direct link to the Chrome extension if the user is visiting from Chrome, and such things. Also, this alert is only used on the file page, so once I replace it with the new design, it'll be **dead code**, which I ought to remove.
The question is: should I go for a quick win by implementing it the **simpler way** you described above and throwing out the existing logic. **OR** I should **retain the logic**, but in that case, we'll need to review the copy a bit, and implementation and testing will take more time.

4. **Cadence** question: you said, "display the browser extension CTA on every 5th file page view [...] to mirror the search results CTA logic".
Actually, the logic for the search results CTA is to show it only if the search result count is divisible by 5. (so about 20% of the time)
I think it might be slightly confusing for users if the display of the CTA is non-deterministic. If I implement the suggested solution, the CTA will be hidden once they refresh the page.
So, I have an alternative suggestion that also displays the CTA 20% of the time: I could hash the page URL (or the file name, whichever is simpler), and based on that hash, I'll show the CTA with a 20% chance. With this solution, the logic would be more transparent to the user, and it'd be even more similar to the logic on the search results page.
What do you think? **Can I go ahead with this alternative solution?**

5. I still need the **icon** for the browser extension CTA that you started in [Figma here](https://www.figma.com/file/VlpvIoBXrG6GFWsEFmc6rB/Browser-extension-CTA-improvements?node-id=2%3A7140).

**Comment by rrhyne** [comment]
1. Yes, that was correct, but if you like the full name you can use your version
2. D! I defined the metrics with cards. You can see those [here](https://www.figma.com/file/VlpvIoBXrG6GFWsEFmc6rB/Browser-extension-CTA-improvements?node-id=26%3A5898). Note these should occur for the cloud AND be added to on-premise pings as well.  
3. I think we should respect the existing logic. Let's ask @muratsu 
4. same
5. I think that is incorrect. We don't want to show it every time. Number of results should have no bearing. Can we fix this?
6. Icon is done and is ready for export in the [Figma file](https://www.figma.com/file/VlpvIoBXrG6GFWsEFmc6rB/Browser-extension-CTA-improvements?node-id=26%3A5030)

**Comment by vdavid** [comment]
1. Thanks, I'll keep the specified utm_content then. Just wanted to double-check.
2. Great, thanks! In the Figma file, I'm seeing "InstallBrowserExtensionCTAShown" and "InstallBrowserExtensionCTAClicked". I assume I should use this pair on **both the search results page and the file page**. So we won't want to distinguish in the telemetry data based on which page the logging is coming from. If that's incorrect, let me know, otherwise, I'll go with this.
3. Sounds reasonable. If Murat agrees, then I'll try to retain the logic and will come back to you probably with a short video to demo how the new version looks like, to double-check the copy, etc.
4. (Actually, I mistakenly split #3 into two. Sorry about it.)
5. Sure, we can make it also "every 5th page view", no problem.
6. Thanks!

**Comment by muratsu** [comment]
Feel free to remove the logic as it's no longer relevant.


We've previously migrated from using self-hosted extensions to the marketplace and this logic & campaign is no longer needed.  

```
const FIREFOX_ALERT_START_DATE = new Date('July 16, 2021')
const FIREFOX_ALERT_FINAL_DATE = new Date('October 18, 2021')
```

Similarly we now have browser extensions for Chrome, Firefox & Safari and we should use a single landing page, rather than showing just a chrome link.

**Comment by vdavid** [comment]
Two questions to @rrhyne 

1. **Soft reloads**

When I'm on a file page (for example, [this one](https://sourcegraph.com/github.com/shadowsocks/shadowsocks-windows/-/blob/Shadowsocks/Models/Group.cs)), on the left side, there is a file list.
Should the browser extension CTA come up at every fifth click when I click around in this file list?
I'm asking because it will cause a little bit of flickering: each file content box on the right will start at the same top position, except for every fifth click, where it'll be below the CTA.
I'd go with **yes, it's no problem** by default, but I wanted to check with you.
The alternative is, of course, to only show/hide the CTA at hard reloads.
 
2. **Folder pages**

On the same level as the file pages, there are also folder ("tree view") pages (for example, [this one](https://sourcegraph.com/github.com/shadowsocks/shadowsocks-windows/-/tree/Shadowsocks/Models)).
Am I right to assume that we don't want to display the CTA on these pages, so we want to show them **only on the file pages**?

**Comment by rrhyne** [comment]
1. What experience fills better to you? I think I lean to hard reloads to avoid the jitter during a specific task.
2. Yes, file only for now please!

**Comment by vdavid** [comment]
@rrhyne questions about the metrics collected and sent in the on-prem pings:

The simplest way would be to send the bare aggregate metrics, which would be four numbers:
- 1\. number of CTAs shown on the file page
- 2\. number of CTAs clicked on the file page
- 3–4. same for the search results page.

But this probably would not be very helpful. So we could make some breakdowns. Our two ideas with Erzhan were time-based and user-based breakdowns. (This is also what we saw for other metrics being sent in pings.)
Time-based could help see trends, while user-based would help see whether 100 users saw 10 CTAs each vs 10 users 100 CTAs each.

1. What **intervals** do we want, if any? Is a **monthly** breakdown fine?
2. Do you want any **per-user** breakdown?

My suggestion is a simple **monthly breakdown** (aggregate per month per on-prem instance, so no user-based metrics).

**Comment by rrhyne** [comment]
Our goal with this project is to improve monthly and daily active users through the promotion of the browser and IDE extensions. Theoretically, if more users are aware of and install the browser extension and/or IDE extension, we should see a percentage of improvement in the installations MAU to DAU score. 

I believe this requires tracking by user. 

The process to generate pings requires an RFC. [You can read more about that here](https://docs.sourcegraph.com/dev/background-information/adding_ping_data).  I've created an RFC for this project that can be found here. Could you add sample data to it as required by the process? If you need help structuring this data properly, @attfarhan has completed this process many times.

**Comment by vdavid** [comment]
@rrhyne I've double-checked: we're already sending the MAU and DAU in the pings. So I believe adding the total number of CTA displays and clicks to the pings is enough for us to check for correlations. I'll go ahead with adding an example to the RFC.
