### ISSUE TITLE
Create code monitoring history/events pages

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#27168]
Designs: https://www.figma.com/file/FlsqgXqE2TPmrGDEw9uFtZ/Code-monitors-improvements?node-id=103%3A3 

- [x] Create basic UI and GraphQL queries (#31219)
- [x] Create UI inside the expanded row (#31682)
- [x] Show result count and link to search in logs (#32173)

**Comment by camdencheek** [comment]
Left a comment in the blocking issue, but the graphql endpoints should be good to go. I don't think there are any changes needed, but let me know if there is info you need that's not available.

**Comment by limitedmage** [comment]
Great find, @camdencheek, thank you for looking into this! I think we're good to go from a backend side for implementing code monitor events page for email actions.

**Comment by limitedmage** [comment]
I've decided that "Creating a search results page/view with the exact results for the event" is out of scope for this. I've moved it to a separate issue, #32174

**Comment by limitedmage** [comment]
This is now complete and #32220 is the follow-up to enable for everyone.
