### ISSUE TITLE
Make Code Monitors repo-aware

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#27304]
## Summary

Code Monitors currently suffer from an issue where, when searching multiple repositories or revisions, results may be missing or duplicated. 

## Multiple repo search

Currently, we run the provided search query, then if we get results, we save the timestamp of the latest result as a starting point for the next time the code monitor search query triggers by appending `after:` to the query. This is problematic with multiple repos because results may be returned for one repo before valid results from another repo have been pulled from the code host. 

Consider the following race:
1) 1:05 - repo A is fetched from the code host
2) 1:10 - repo B is fetched from the code host
3) 1:11 - repo A and repo B are searched, with filter `after:"1:01"`. One result is returned for repo B with timestamp 1:09
4) 1:12 - repo A is fetched. One commit is pulled with timestamp 1:06 that would match the monitor query
5) 1:13 - repo A and B are searched, with filter `after:"1:09"`. No results are returned because the matching commit in repo A is filtered out

## Multiple revision search

In addition to the repo fetch race condition, we have a similar race condition with searching multiple commit refs. A branch may be pushed to after a result is found in a different branch in the same repo.

Consider the following race:
1) create commit1 on branch1
2) create commit2 on main
3) push main to codehost
4) gitserver fetches commit2 on main
5) run `type:diff repo:myrepo rev:*refs/heads/* test`, get commit2 as a result
6) push branch1 to codehost
7) gitserver fetches commit1 on branch1
8) run `type:diff repo:myrepo rev:*refs/heads/* test after:<commit2 timestamp>`
9) get no results because commit2 is after commit1

## Proposed solution

In order to correctly start where we left off, I think we need to make code monitors repo-aware. That is, keep track of where we left off in each repo between searches.

Additionally, we will need to change the way we store the point we left off. We should move from saving a timestamp of the last result commit to saving a list of hashes that we previously searched from (more detail in the linked PR below).

In order to successfully make code monitors repo-aware, we will need to make the code monitors code call each commit/diff search itself so it can expand the refs into commit hashes and store the expanded refs for the next search. For this to be possible, I think we will need to complete some refactors up to the point where we have a "search plan", from which the code monitors backend can mutate the plan and kick off the commit/diff search jobs. 

## Tasks

- [x] Figure out a way to start exactly from where we previously left off (#27301)
- [ ] Complete refactoring up to the point that code monitors can create a search plan outside of the normal search path
- [ ] Rewrite code monitors to 1) generate a search plan, 2) expand revs for each repo, 3) save the expanded revs for each repo, 4) execute the search for each repo

**Comment by rvantonder** [comment]
I think the one thing I'm missing from the problem description, that's not explicitly said, is that we throw away repo info when we search over commits? Is the commit result set flattened over multiple repos/revs and that's why results don't appear? Is that accurate?

> For this to be possible, I think we will need to complete some refactors up to the point where we have a "search plan", from which the code monitors backend can mutate the plan and kick off the commit/diff search jobs.

I'm not sure I follow what the series of refactors are that's needed, I don't think there's a blocking issue here in any way as far as progress on code monitors specifically is concerned. Here's how I see it:

Code monitors is a tailored search application that runs search for a specific purpose. There's no principle or law that says it has to go through our traditional code search path right now. It _sounds_ like this problematic behavior affects general search, but that doesn't mean we have to solve it in general so that it's fixed for code monitors--after all, it sounds like the task here is "make code monitors repo-aware" rather than "make all commit search repo aware", so maybe picking out what we want here bears on the solution. That said, I would focus on the "make code monitors repo-aware" and solve first for that case. I would personally explore something like:

(1) Create a backend endpoint for code monitors and find some way for us to have an entry point from the client for code monitor functionality.
(2) Freely parse/build/execute your query (and by your query, I mean more the commit backend type than the general parse tree) in a way that solves this issue (whatever you would do for the "create a search plan outside of the normal search path" part), abstracting over the parts of our search code exists.

I don't really have a clear idea what this flow should/would look like or where it fits in, because it depends on this repo/ref expansion logic. The closest thing I can come up with that maybe fits into our existing flow is if you can create an internal "code monitor" search job, that keeps track of this state? For manipulating values like repos/refs when searching, this sounds much more like a runtime concern than a static generation of queries/planning, because the proposal talks about persisting/saving expanded revs for each repo. Ergo, If this were something like a "job", I would expect that job to have a handle on persisted values and generate internal representations (your commit query type) rather than the parse tree/query plan at some earlier point. Basically, "repo aware code monitor" concerns is for a particular backend, not the general query plan parsing and execution--therefore, this "repo-aware" logic should be particular to that backend, not some earlier manipulation of the query plan--and manipulate the internal representation for this particular backend (again, your commit query type). But I don't think that this is necessarily the right way to go about it-I'm not sure we _have_ to fit code monitors into the existing flow, as opposed to just building out a separate backend endpoint like a kind of "search app" and then do your manipulation, etc. before calling the more primitive `doResults` or commit search job or whatever.

Either way I don't think there's a magical set of refactors that we can definitively say "yes, this is what things should look like and the code monitor logic fits in nicely" (at least, I don't have a good idea of that). One part that would be nice maybe is to give "code monitor processing thing" a complete query plan without segmenting and executing atomic queries, e.g., in `toSearchInputs` of our main path but I'm pretty sure right now the scope for code monitors is atomic queries _anyway_ so this shouldn't be an actual concern--it should be safe to assume that the input query converts to a basic backend commit job. Either way, like I said, I'm not sure solving this for code monitors immediately means we have to use the standard search entry point-try exploring a way to carve out a backend place for just code monitor logic and then calling standard search with issues taken care of?

Summary: I'm just giving ideas because tackling this seems more open ended and entails a lot more than "code structure is in flux so where can we call code monitor backend logic, once that settles it's clear what we should do"--I think there are multiple valid ways to go about this and a solution is potentially quite independent from planned backend restructuring.

**Comment by camdencheek** [comment]
@rvantonder looking back at what I wrote, I realize I totally did not add enough detail for this issue for it to be useful to you. Sorry! Let's try this again 😄

The fundamental problem is that search doesn't return any information about what commits were searched, so we don't have any good starting point the next time we execute the search. Currently, our best estimate is using the time of the last commit result returned, since we know that we searched _at least_ that far if we're getting results. 

However, searches can run across multiple repositories, so a single timestamp can not accurately represent where we stopped searching in every repository. We may get a result for repository A with a timestamp that's after repository B's last fetch time, so commits that haven't been fetched from repository B's code host that have a timestamp before the result from repository A won't be searched the next time this code monitor triggers since they'll be filtered out by the `after` filter.

Now, you might reasonably ask "why don't we just partition the search results by repository, then store the last timestamp for each repository?" The answer is twofold. 

Fold 1: mutating the query so that we have a different `after:` value for each searched repository would be pretty difficult. We would have to take a query like `type:diff repo:github.com/sourcegraph/.* test` and change it to something like `type:diff (repo:github.com/sourcegraph/sourcegraph$ after:"october 27") or (repo:github.com/sourcegraph/go-diff$ after:"october 28") OR ... test`. This is complicated further by other repo predicates like `repo:contains.commit.after()`. This problem is solveable, but difficult.

Fold 2: even for a single repository, a timestamp is not good enough to accurately represent what has already been searched because we can search across multiple revs. Consider `type:diff repo:github.com/sourcegraph/sourcegraph$ rev:*refs/heads/* test`. If I have an in-progress branch that I've been working on for a month, then push it, my commits will have timestamps before the current `after:` filter that will never be searched. In order to fix this, we need to be more intelligent about telling git exactly what to search, and storing exactly what git searched.

My solution for solving issue 2 also solves issue 1, but it requires code monitors to become "repo-aware". I'm defining "repo-aware" as "code monitors handles running the search for each repo, storing where it left off on a per-repo basis". This is opposed to the current "non-repo-aware" situation where code monitors runs a single search over all the searched repos, and saves a single timestamp that tries its best to tell it where to start next time.

Now for some implementation details:

Code monitors runs outside the `frontend` process (in `worker`), so I think we have two options here. Either we can 1) add an endpoint to the frontend API that is code-monitors specific, and runs the code-monitors search path, or 2) we can have the code monitors process use the frontend code to parse the search query, build a search plan, and resolve repositories before calling the gitserver `/search` endpoint directly. I think these line up with your two suggestions above. More on this in a minute. 

To solve the "search over multiple revs" issue, my solution is to resolve all git references ahead of time (e.g. HEAD -> 815918d), so we have a list of stable hashes (references change meaning after a fetch) that we started our last search from. Then, next time we search, we do the same thing, but _exclude_ the previously searched hashes. Git semantics mean that `git log a18da81 --not b73195` means "search all commits reachable from `a18da81`, but exclude any commits reachable from `b73195`". This allows us to search exactly the commits that 1) match the rev filters, and 2) we didn't search before. (note that it's a bit more complicated than this, but `git rev-parse` handles all the heavy lifting). 

In order to use the above solution, code monitors needs to be able to 1) get a commit/diff search job, 2) for each repo to be searched, copy the search job and resolve the refs in the job to hashes for that repo,  3) mutate the search job for each repo to exclude the previously searched commits, and 4) execute the search job for each repo, and if the search succeeds, save the searched hashes so they can be excluded on the next run.

This makes option 1 (make a new code monitors API endpoint) look something like:
- Call the endpoint, passing in the code monitor ID so we can look up and save searched commits
- Execute the search up until we get a set of jobs and a list of repos to search
- Code specific to monitors hooks in and mutates the commit/diff search job accordingly
- Execute the mutated commit/diff search jobs

And option 2 is something like:
- In the `worker` process run the search code up until the point that we have our search jobs (what I'd been calling a "search plan") and the list of repos to be searched
- Code monitors mutates the search plan to resolve commits and add exclusions for each repository
- Code monitors executes the search plan, calling the gitserver `/search`

Option 1 is a little awkward because now we need a full extra endpoint just to hook in to mutating the search plan. Also, I don't like that it would mean code in the frontend owns accessing the code monitors db tables. 

Option 2 is a little awkward because we'd need to be able to call our search code up through generating the jobs from the `worker` process. This is the "I'm not sure if refactors have made it far enough to do this" thing I was talking about. Additionally, this breaks caching (which might be okay now that we will be streaming repos) and moves a lot more work to the worker process (which I think is okay). 

I hope this does a little better a job of clarifying my thoughts here.

**Comment by camdencheek** [comment]
After talking with @rvantonder, I think we've got a path forward. What I was hoping would be possible is not yet possible, but it's also not yet close enough to wait for it. So, instead, we identified a slightly hackier solution that should allow us to get the information we need in order to fix this issue. 

Short summary: I was hoping we'd be able to call something like `graphqlbackend.QueryToJobs(query)` and get a set of search jobs for a given query. This is currently very not possible, so instead, I'm going to add a lightweight callback so whenever we create a commit or diff job, it's passed back to the code monitor caller, where it can be mutated and executed. This will (hopefully) be replaced with the currently-not-possible option in the future, but I don't think code monitors can wait for that. It's difficult to describe the idea exactly, but I'll have some PRs for it in the near future, and I'll explain in more detail on those.

**Comment by jyavorska** [comment]
@benvenker can you please add a (conservative) estimate for when this will be delivered? Doesn't need to be exact, and it can change, but it's for the roadmap view at https://github.com/orgs/sourcegraph/projects/214/views/11.

**Comment by jyavorska** [comment]
In the product engineering project, this item has a delivery date of FY22 Q4 which is in the past. @benvenker can you please take a look?

**Comment by jyavorska** [comment]
@benvenker since this is continuing, can you please add use case labels, launch tier (set in project), and launch month (also set in project). Thank you!

**Comment by benvenker** [comment]
@jyavorska I'm going to swap this out for an issue relating to the actual end goal here, which is to enable code monitors to support at least a 10,000 repository limit. I'll be sure to add the relevant labels and add it to the roadmap.

**Comment by camdencheek** [comment]
This was enabled by default in https://github.com/sourcegraph/sourcegraph/pull/37028. Closing 🥳
