### ISSUE TITLE
Wildcard V2: Migration preparation tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27354]
### Plan
We want to use codemods and lint rules to help migrate our code to use Wildcard, and maintain it to ensure we continue to use Wildcard in the future.

We'll likely have to implement multiple codemods and lint rules to achieve this, but they will all ultimately be very similar. We should start with some initial focused issues here, so we can easily estimate future work and create a foundation to work from.

### Tracked issues

@umpox

Completed
- [x] (🏁 129 days ago) https://github.com/sourcegraph/sourcegraph/issues/27356 
- [x] (🏁 129 days ago) https://github.com/sourcegraph/sourcegraph/issues/27357 

@valerybugakov

Completed
- [x] (🏁 138 days ago) https://github.com/sourcegraph/sourcegraph/issues/27355 
- [x] (🏁 105 days ago) https://github.com/sourcegraph/sourcegraph/issues/27361 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request
