### ISSUE TITLE
Code search 3.3 tracking issue

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#2740]
## User story

@ijt, @ijsnow, @attfarhan : Could someone provide a paragraph on why these specific set of issues, the benefits and who this will help. This helps greatly with the writing of the blog post.

Examples at #2025 and #2848

---

- [x] Track down issue that https://app.hubspot.com/contacts/2762526/company/887065580 is seeing where they're not seeing any results with indexed search enabled #3294
- [x] Auto-fix queries with invalid regexes #2125
- [ ] ~Nested search @ijsnow @ijt~ (not going to be completed)
  - [x] Delete `!hier!` feature flag/code path
  - [ ] ~Nested query performance tracking~ (not going to be completed)
    - [x] Design document
    - [ ] ~Implementation #2879~ (not going to be completed)
       - [x] `recent_searches` table
       - [ ] ~report generating endpoint for nest querying enabled/disabled benchmark~(not going to be completed)
- [ ] ~If searcher zip archives are corrupted, we should gracefully handle it #1759 (stretch)~ (not going to be completed)
- [ ] ~Search keyword to enable searching of large file sizes #1624~(not going to be completed)
- [ ] Saved search improvements @attfarhan https://github.com/sourcegraph/sourcegraph/issues/2824
- [x] Search web app testability @attfarhan 
  - [x] Increase code coverage of `web/src/search/results/` directory from 0% to >80%
  - [ ] Increase code coverage of `web/src/search/saved-queries/` directory from 0% to >80% (stretch)
  - [x] For each of `shared/src/components/{CodeExcerpt.tsx, FileMatch.tsx, ResultContainer.tsx, FileMatchChildren.tsx}`, increase code coverage from 0% to >80%
- [ ] ~Add syntax highlighting to code blocks in markdown files~ https://github.com/sourcegraph/sourcegraph/issues/2144~ (not going to be completed) @attfarhan
- [ ] ~Ability for admins to see top 100 recent searches (*stretch*) #3256~ (not going to be completed)

**Comment by slimsag** [comment]
Also note https://github.com/sourcegraph/sourcegraph/issues/1005 and https://github.com/sourcegraph/sourcegraph/issues/35

**Comment by nicksnyder** [comment]
Those two issues should be considered when writing the design document, but neither of those are expected to ship in 3.3.

**Comment by slimsag** [comment]
Definitely 👍

**Comment by ijt** [comment]
I don't see the connection between #35 and hierarchical search. They seem like independent issues.

**Comment by nicksnyder** [comment]
#35 is just extra context about features that we might want to implement in the future. This context may or may not be relevant as you refactor/change code when you are directly working on hierarchical search.

**Comment by ijt** [comment]
Work on 3.3 is done. Closing this.
