### ISSUE TITLE
Code Insights: [Umbrella] FE setting migration problems

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#27415]
### Context
In this umbrella issue, we collect all known issues that are related to the setting migration story and the new GQL API. 

To activate the new gql API you should turn on the experimental flag in your setting cascade - ` "codeInsightsGqlApi": true`. If you see some strange behavior include this problem in the list below.

### Known issues

- [x] 1. Start Y-axis with 0 doesn't work for backend insights in new API https://github.com/sourcegraph/sourcegraph/pull/27613
- [x] 2. Edit page doesn't work properly for some insights (example on k8s - "New insight with new API 22") https://github.com/sourcegraph/sourcegraph/pull/27614
- [x] 3. After search insight creation the dashboard page fails with runtime error about the premature observable cancelation. [will be solved in this PR https://github.com/sourcegraph/sourcegraph/pull/27431]
- [x] 4. Creation UI live preview chart flashes Don't have data for this repositories error while a user types the first query of the first data series. Fixed in https://github.com/sourcegraph/sourcegraph/pull/27517

**Comment by felixfbecker** [comment]
@vovakulikov who owns fixing these issues? Are they frontend or backend issues?

**Comment by vovakulikov** [comment]
@felixfbecker so far they are all FE. Our plan split this issues between me and @unclejustin after our main tickets. In case if we found something BE related we will notify BE team.
