### ISSUE TITLE
Make SSBC available to non-site-admins

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#27543]
- [ ] Allow non-site-admins in resolvers https://github.com/sourcegraph/sourcegraph/pull/28671
- [ ] Don't allow access to cache entries from different users
- [ ] Non-site-admins should not be able to see shallow batch changes created by other users - https://github.com/sourcegraph/sourcegraph/pull/28726

**Comment by mrnugget** [comment]
As we anticipated, there are multiple ways to implement "Allow non-site-admins in resolvers". The main question each implementation has to answer: what can a non-admin see of another non-admin's batch spec?

The current non-SSBC answer is: a user can see another user's batch spec if they get sent the URL of the batch spec. They will then also only be able to see data depending on repository permissions (i.e. they can't see a changeset spec in the batch spec that is associated with a repo they don't have access to).

After a first spike, I think we implement the SSBC answer to that question in stages:

**Stage 0 (current status)**: non-admins can't create SSBC batch specs, but can view batch specs if they get sent the link
**Stage 1**: non-admins can't discover other non-admin's batch specs in a list. non-admins will only see the raw spec when looking at another non-admin's batch spec (if they get sent a link), and no other fields.
**Stage 2**: non-admins can discover other non-admin's batch specs in lists. non-admins will see fields of another user's batch specs, but workspaces only depending on repository permissions.
**Stage 3**: same as stage2, except that authors of batch specs can now decide whether others can see that batch spec in a list by toggling "private" on/off on a batch spec.

**Stage 2** doesn't necessarily have to build on **Stage 1** but could be built instead. The problem is that **Stage 2** is probably 2 weeks of effort and **Stage 1** is only a couple days.

The spike I did implemented large parts of **Stage 1** (without tests and without fixing the caching item as described in ticket here):

![admin_non_admin](https://user-images.githubusercontent.com/1185253/145035269-5bc25dbd-d5c6-4e33-a502-4abe40a73817.png)

**Comment by malomarrec** [comment]
Stage 2 is blocked by having the "draft runs" page (https://github.com/sourcegraph/sourcegraph/issues/26796 and some 3.1 work)

**Comment by mrnugget** [comment]
Outcome of Zoom meeting: implement Stage 1 now, Stage 2 later.

**Comment by mrnugget** [comment]
Another note: we also need to add checks for "CreateEmptyBatchChange" https://github.com/sourcegraph/sourcegraph/pull/28524/files#diff-525d4c66dcfff522a80de530657b4f82c987b465d537dc8eae66a76d1e615cbeR1449-R1452

**Comment by eseliger** [comment]
D O N E

**Comment by malomarrec** [comment]
<div style="width:100%;height:0;padding-bottom:69%;position:relative;"><iframe src="https://giphy.com/embed/3o7qDEq2bMbcbPRQ2c" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/mic-drop-peace-out-obama-3o7qDEq2bMbcbPRQ2c">via GIPHY</a></p>

**Comment by mrnugget** [comment]
I like how the still frame of the GIF matches your "I resign"

<img width="675" alt="screenshot_2021-12-09_16 51 06@2x" src="https://user-images.githubusercontent.com/1185253/145429390-f751c1de-1a61-4a72-9253-dcb54ec9652a.png">
