### ISSUE TITLE
Wildcard V2 - New Components

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#27606]
### Plan

Parent Tracking Issue for new Wildcard Library components. 

#### Links to relevant documents

[Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw).
[Issues](https://docs.google.com/document/d/1JU1SIZekkqCKHMfiLPpAT90Rf1XkATT-WQohFas4yMw/edit#) scoped for GitStart.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@unassigned: __40.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27720  __1.50d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/27721  __0.50d__
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/27722  __1.00d__

Completed: __40.00d__
- [x] (🏁 179 days ago) https://github.com/sourcegraph/sourcegraph/issues/27609  __2.00d__
- [x] (🏁 165 days ago) https://github.com/sourcegraph/sourcegraph/issues/27690  __1.00d__
- [x] (🏁 147 days ago) https://github.com/sourcegraph/sourcegraph/issues/27730  __1.50d__
- [x] (🏁 144 days ago) https://github.com/sourcegraph/sourcegraph/issues/27723  __1.50d__
- [x] (🏁 140 days ago) https://github.com/sourcegraph/sourcegraph/issues/27696  __2.00d__
- [x] (🏁 134 days ago) https://github.com/sourcegraph/sourcegraph/issues/27678  __4.50d__
- [x] (🏁 134 days ago) https://github.com/sourcegraph/sourcegraph/issues/27686  __2.00d__
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/27666  __1.00d__
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/27670  __3.00d__
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/27708  __4.00d__
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/27659  __3.00d__
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/27733  __3.00d__
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/27717  __0.50d__
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/27693  __3.00d__
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/27699  __1.00d__
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/27722  __1.00d__
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/27673  __6.00d__

@gitstart-sourcegraph: __17.50d__

Completed: __17.50d__
- [x] (🏁 165 days ago) https://github.com/sourcegraph/sourcegraph/issues/27690 
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/27666  __1.00d__
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/27708  __3.00d__
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/27659  __1.50d__
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/27711  __2.00d__
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/27726  __1.50d__
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/27717  __1.00d__
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/27693  __4.00d__
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/27699  __3.00d__
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/27673  __0.50d__

@umpox: __2.00d__

Completed: __2.00d__
- [x] (🏁 140 days ago) https://github.com/sourcegraph/sourcegraph/issues/27696  __2.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request
