### ISSUE TITLE
Wildcard V2: `<Badge />`Tracking issue

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#27609]
### Plan

Tracking Issue for individual `<Badge />` component

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@umpox: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __2.00d__
  - [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/27621  __1.00d__
  - [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/issues/27622  __1.00d__

Completed: __2.00d__
- [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/27621  __1.00d__
- [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/issues/27622  __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by umpox** [comment]
Closing as this component has now been added!

https://storybook.sgdev.org/?path=/story/wildcard-badge--badges
