### ISSUE TITLE
Wildcard V2: `<Link />` Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27659]
### Plan

Tracking Issue for individual `<Link />` component

### Tracked issues

@unassigned: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __3.00d__
  - [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/27660  __1.00d__
  - [x] (🏁 72 days ago) https://github.com/sourcegraph/sourcegraph/issues/27661  __2.00d__

Completed: __3.00d__
- [x] (🏁 72 days ago) https://github.com/sourcegraph/sourcegraph/issues/27661  __2.00d__
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/27660  __1.00d__

@gitstart-sourcegraph: __1.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __1.50d__
  - [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/27662  __0.50d__
  - [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/27663  __1.00d__

Completed: __1.50d__
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/27662  __0.50d__
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/27663  __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request
