### ISSUE TITLE
Wildcard V2: `<Link />` Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27654]
### Plan

Tracking Issue for individual `<Link />` component

### Tracked issues

@unassigned: __4.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27655  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27656  __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27657  __0.50d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27658  __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request
