### ISSUE TITLE
Wildcard V2: `<Typography />` Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27673]
### Plan

Tracking Issue for individual `<Typography />` component

### Tracked issues

@unassigned: __6.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __6.00d__
  - [x] (🏁 140 days ago) https://github.com/sourcegraph/sourcegraph/issues/27674  __2.00d__
  - [x] (🏁 146 days ago) https://github.com/sourcegraph/sourcegraph/issues/27675  __3.00d__
  - [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/27676  __1.00d__

Completed: __6.00d__
- [x] (🏁 146 days ago) https://github.com/sourcegraph/sourcegraph/issues/27675  __3.00d__
- [x] (🏁 140 days ago) https://github.com/sourcegraph/sourcegraph/issues/27674  __2.00d__
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/27676  __1.00d__

@gitstart-sourcegraph: __0.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __0.50d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/27677  __0.50d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request
