### ISSUE TITLE
Wildcard V2: `<Card />` Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27678]
### Plan

Tracking Issue for individual `<Card />` component

### Tracked issues

@unassigned: __2.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __2.50d__
  - [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/27679  __2.00d__
  - [x] (🏁 3 days ago) https://github.com/sourcegraph/sourcegraph/issues/27680  __0.50d__

Completed: __2.50d__
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/27679  __2.00d__
- [x] (🏁 3 days ago) https://github.com/sourcegraph/sourcegraph/issues/27680  __0.50d__

@umpox: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __2.00d__
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/27681  __2.00d__

Completed: __2.00d__
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/27681  __2.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by umpox** [comment]
Now complete!
