### ISSUE TITLE
Wildcard V2: `<Menu />, <MenuItem />` Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27699]
### Plan

Tracking Issue for individual `<Menu />, <MenuItem />` component

### Tracked issues

@unassigned: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __1.00d__
  - [x] (🏁 152 days ago) https://github.com/sourcegraph/sourcegraph/issues/27700  __1.00d__

Completed: __1.00d__
- [x] (🏁 152 days ago) https://github.com/sourcegraph/sourcegraph/issues/27700  __1.00d__

@gitstart-sourcegraph: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __3.00d__
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/27701  __3.00d__

Completed: __3.00d__
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/27701  __3.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by courier-new** [comment]
Hey there! The new implementation of the `<MenuList />` component appears to be producing a runtime warning. When you interact with the "Menu Example" story (sorry I can't provide a link at the moment, https://storybook.sgdev.org/ is down), this appears in the console:

```
index.js:136 Warning: React does not recognize the `popoverContentPosition` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `popovercontentposition` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by MenuItems)
    in MenuItems (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by MenuPopover)
    in MenuPopover (created by ForwardRef)
    in ForwardRef
    in Popover (created by DropdownProvider)
    in DescendantProvider (created by DropdownProvider)
    in DropdownProvider (created by Menu)
    in Menu (created by ForwardRef)
    in ForwardRef
    in div
    in Unknown (created by BrandedStory)
    in Router (created by MemoryRouter)
    in MemoryRouter (created by BrandedStory)
    in ApolloProvider (created by MockedProvider)
    in MockedProvider (created by MockedStoryProvider)
    in MockedStoryProvider (created by BrandedStory)
    in BrandedStory (created by unboundStoryFn)
    in ReactDecorator (created by unboundStoryFn)
    in unboundStoryFn
    in ErrorBoundary
```

This also occurs wherever a `MenuList` is used, regardless of whether or not a `position` prop is provided.

The menu still behaves completely as expected, so this is just about validating that the warning doesn't matter and then suppressing it. It seems like there's maybe a weird interaction between our `Popover` and Reach's `MenuItems` but I couldn't identify what from taking a 5 minute look.

Happy to file this as a separate ticket if that helps! Just wanted to raise it somewhere for now.

**Comment by courier-new** [comment]
One more thing, completely unrelated to my previous comment.

It looks like we're split across the codebase between using `▾`, the `.dropdown-toggle` Bootstrap class, and `ChevronDownIcon` for the dropdown arrow on a `MenuButton`:
- [Downward caret character](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%E2%96%BE&patternType=literal) - 3 results, including the `Menu` Storybook story
- [`.dropdown-toggle` class](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%5B%5E.-%5Ddropdown-toggle+lang:typescript+-file:test&patternType=regexp) - 4 results
- [`ChevronDownIcon`](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%3CMenuButton%28%5B%5Cn%5Cs%5D%2B.*%29%2B%3CChevron&patternType=regexp) - 2 results

The downward caret and `.dropdown-toggle` options seem less-than-ideal. The caret character visually looks too small, may render inconsistently across browsers, and needs to be wrapped in a `<span />` or something in order to be `aria-hidden`. On the other hand, the `.dropdown-toggle` class uses border hacks to produce the appearance of an arrow, and it's not vertically centered by default as a result. I also understand we're trying to phase out Bootstrap, so at the very least we'd need to re-implement that class if we decided to go that route.

Throughout the Wildcard design system files I exclusively see `ChevronDownIcon` used, for example in the [Actions stickers](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=908%3A2513) and the corresponding Actions in "Base." While still potentially needing to be `aria-hidden`, an Icon would at least be consistent and appropriately-sized/aligned, so I'm inclined to suggest we unify on `ChevronDownIcon`.
