### ISSUE TITLE
Wildcard V2: `<Tooltip />` Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27690]
### Plan

Tracking Issue for individual `<Tooltip />` component

### Tracked issues

@unassigned: __0.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __0.50d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/27692  __0.50d__

@gitstart-sourcegraph: __0.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __0.50d__
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/27691  __0.50d__

Completed: __0.50d__
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/27691  __0.50d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by valerybugakov** [comment]
Closed by [the implementation PR](https://github.com/sourcegraph/sourcegraph/pull/28887).
