### ISSUE TITLE
Wildcard V2: `<Modal />` Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27696]
### Plan

Tracking Issue for individual `<Modal />` component

### Tracked issues

@unassigned: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __2.00d__
  - [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/27697  __2.00d__

Completed: __2.00d__
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/27697  __2.00d__

@umpox: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __2.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/27698  __2.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request
