### ISSUE TITLE
Wildcard V2: `<Popover />` Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27693]
### Plan

Tracking Issue for individual `<Popover />` component

### Tracked issues

@unassigned: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __3.00d__
  - [x] (🏁 114 days ago) https://github.com/sourcegraph/sourcegraph/issues/27694  __3.00d__

Completed: __3.00d__
- [x] (🏁 114 days ago) https://github.com/sourcegraph/sourcegraph/issues/27694  __3.00d__

@gitstart-sourcegraph: __4.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __4.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/27695  __4.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request
