### ISSUE TITLE
Wildcard V2: `<Panel />` Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27708]
### Plan

Tracking Issue for individual `<Panel />` component

### Tracked issues

@unassigned: __4.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __4.00d__
  - [x] (🏁 77 days ago) https://github.com/sourcegraph/sourcegraph/issues/27709  __4.00d__

Completed: __4.00d__
- [x] (🏁 77 days ago) https://github.com/sourcegraph/sourcegraph/issues/27709  __4.00d__

@gitstart-sourcegraph: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __3.00d__
  - [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/issues/27710  __3.00d__

Completed: __3.00d__
- [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/issues/27710  __3.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request
