### ISSUE TITLE
Wildcard V2: `<Combobox />` Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27705]
### Plan

Tracking Issue for individual `<Combobox />` component. See also #22053.

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/32121 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/27706 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/27707 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

@vovakulikov

Completed
- [x] (🏁 354 days ago) https://github.com/sourcegraph/sourcegraph/issues/41630 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request
