### ISSUE TITLE
Wildcard V2: `<Checkbox />` Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27717]
### Plan

Tracking Issue for individual `<Checkbox />` component

### Tracked issues

@unassigned: __0.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __0.50d__
  - [x] (🏁 125 days ago) https://github.com/sourcegraph/sourcegraph/issues/27718  __0.50d__

Completed: __0.50d__
- [x] (🏁 125 days ago) https://github.com/sourcegraph/sourcegraph/issues/27718  __0.50d__

@gitstart-sourcegraph: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __1.00d__
  - [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/27719  __1.00d__

Completed: __1.00d__
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/27719  __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request
