### ISSUE TITLE
Wildcard V2: `<Tabs />` Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27733]
### Plan

Tracking Issue for individual `<Tabs />` component

### Tracked issues

@unassigned: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __3.00d__
  - [x] (🏁 45 days ago) https://github.com/sourcegraph/sourcegraph/issues/27734  __3.00d__

Completed: __3.00d__
- [x] (🏁 45 days ago) https://github.com/sourcegraph/sourcegraph/issues/27734  __3.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by taylorsperry** [comment]
It looks like we can close this tracking issue, right @oleggromov ?
