### ISSUE TITLE
3.32.1 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#27765]
# 3.32.1 managed instances upgrade

These [managed instances](../enablement/delivery/managed/index.md) upgrades are scheduled for **[Nov 17, 2021, 6:00 PM (UTC)](https://time.is/1800_17_Nov_2021_in_UTC?One%20working%20day%20after%203.32.1%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../enablement/delivery/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [ ] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [ ] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com)

## Upgrade customer managed instances

- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8195
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/1503

---

Also see [3.32.1 patch release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/27764)

**Comment by caugustus-sourcegraph** [comment]
Not relevant, all managed instances are already on 3.33.0
