### ISSUE TITLE
PD 503 sub-repository permissions tracking: complete implementation

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#27916]
This is a tracking issue for the **complete implementation of [PD 503: Sub-repository permissions model](https://docs.google.com/document/d/1d8j-6VC_nk8HXEDT6U2_s-_9uSzgzHWZzrJjII9pKEE/edit#)**, formerly RFC 503. This follows our work on [developing a proof-of-concept (milestone 139)](https://github.com/sourcegraph/sourcegraph/milestone/139?closed=1), and it primarily covered spikes on an implementation path and work that has carried forward on syncing permissions from Perforce (https://github.com/sourcegraph/sourcegraph/issues/26644) and the sub-repo perms smart client (https://github.com/sourcegraph/sourcegraph/issues/26645).

See the [November 15 update](https://docs.google.com/document/d/1d8j-6VC_nk8HXEDT6U2_s-_9uSzgzHWZzrJjII9pKEE/edit#bookmark=id.6brtu8eazde1) for more details on the outcome of the proof-of-concept, and the [complete implementation roadmap](https://docs.google.com/document/d/1d8j-6VC_nk8HXEDT6U2_s-_9uSzgzHWZzrJjII9pKEE/edit#bookmark=kix.xoo5gukib3q7) for an overview and discussion of the path forward.

### Background

Some code hosts support permissions being set against more granular items than repositories, which is currently all Sourcegraph supports. The high level aim of this project is to add support for permissions at a more granular level than repo.

See [PD 503](https://docs.google.com/document/d/1d8j-6VC_nk8HXEDT6U2_s-_9uSzgzHWZzrJjII9pKEE/edit) for a complete overview.

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/32968 

@bobheadxi: __6.00d__

Completed: __6.00d__
- [x] (🏁 236 days ago) https://github.com/sourcegraph/sourcegraph/pull/27762 
- [x] (🏁 222 days ago) https://github.com/sourcegraph/sourcegraph/issues/27918  __5.00d__
- [x] (🏁 221 days ago) https://github.com/sourcegraph/sourcegraph/issues/28412  __0.50d__
- [x] (🏁 206 days ago) https://github.com/sourcegraph/sourcegraph/issues/28451  __0.50d__

@mollylogue: __18.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/32618  __1.00d__ 🧶
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/28532 (PRs: ~[#30302](https://github.com/sourcegraph/sourcegraph/pull/30302)~, ~[#30508](https://github.com/sourcegraph/sourcegraph/pull/30508)~) __1.00d__ 🧶

Completed: __17.00d__
- [x] (🏁 203 days ago) https://github.com/sourcegraph/sourcegraph/issues/28918  __1.00d__
- [x] (🏁 182 days ago) https://github.com/sourcegraph/sourcegraph/issues/28916  __2.00d__
- [x] (🏁 181 days ago) https://github.com/sourcegraph/sourcegraph/issues/28264  __1.00d__
- [x] (🏁 181 days ago) https://github.com/sourcegraph/sourcegraph/issues/28912  __1.00d__
- [x] (🏁 181 days ago) https://github.com/sourcegraph/sourcegraph/issues/28266  __1.00d__
- [x] (🏁 173 days ago) https://github.com/sourcegraph/sourcegraph/issues/28243  __3.00d__
- [x] (🏁 167 days ago) https://github.com/sourcegraph/sourcegraph/issues/27498 (PRs: ~[#29771](https://github.com/sourcegraph/sourcegraph/pull/29771)~, ~[#29995](https://github.com/sourcegraph/sourcegraph/pull/29995)~) __2.00d__
- [x] (🏁 165 days ago) https://github.com/sourcegraph/sourcegraph/pull/30302 
- [x] (🏁 165 days ago) https://github.com/sourcegraph/sourcegraph/pull/30323 
- [x] (🏁 151 days ago) https://github.com/sourcegraph/sourcegraph/issues/30704  __2.00d__
- [x] (🏁 150 days ago) https://github.com/sourcegraph/sourcegraph/issues/30750 (PRs: ~[#30707](https://github.com/sourcegraph/sourcegraph/pull/30707)~) __2.00d__
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/issues/32124 
- [x] (🏁 109 days ago) https://github.com/sourcegraph/sourcegraph/issues/31982 
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/30475 (PRs: ~[#30508](https://github.com/sourcegraph/sourcegraph/pull/30508)~) __2.00d__

@ryanslade: __41.00d__

Completed: __41.00d__
- [x] (🏁 236 days ago) https://github.com/sourcegraph/sourcegraph/issues/26663  __1.00d__
- [x] (🏁 227 days ago) https://github.com/sourcegraph/sourcegraph/issues/28182  __1.00d__   🏳️ [Gitserver Hexagonal Refactor](https://github.com/sourcegraph/sourcegraph/milestone/147)
- [x] (🏁 227 days ago) https://github.com/sourcegraph/sourcegraph/issues/28181  __1.00d__   🏳️ [Gitserver Hexagonal Refactor](https://github.com/sourcegraph/sourcegraph/milestone/147)
- [x] (🏁 210 days ago) https://github.com/sourcegraph/sourcegraph/issues/27909  __3.00d__   🏳️ [Gitserver Hexagonal Refactor](https://github.com/sourcegraph/sourcegraph/milestone/147)
- [x] (🏁 209 days ago) https://github.com/sourcegraph/sourcegraph/issues/28263  __1.00d__
- [x] (🏁 206 days ago) https://github.com/sourcegraph/sourcegraph/issues/28273  __5.00d__
- [x] (🏁 171 days ago) https://github.com/sourcegraph/sourcegraph/issues/29913  __2.00d__
- [x] (🏁 164 days ago) https://github.com/sourcegraph/sourcegraph/issues/27496  __3.00d__
- [x] (🏁 161 days ago) https://github.com/sourcegraph/sourcegraph/pull/30109 
- [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/29988  __3.00d__
- [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/28242 (PRs: ~[#29308](https://github.com/sourcegraph/sourcegraph/pull/29308)~) __8.00d__
- [x] (🏁 152 days ago) https://github.com/sourcegraph/sourcegraph/issues/30829  __1.00d__
- [x] (🏁 147 days ago) https://github.com/sourcegraph/sourcegraph/issues/29994  __1.00d__
- [x] (🏁 147 days ago) https://github.com/sourcegraph/sourcegraph/issues/26972  __3.00d__
- [x] (🏁 145 days ago) https://github.com/sourcegraph/sourcegraph/issues/28280  __5.00d__
- [x] (🏁 119 days ago) https://github.com/sourcegraph/sourcegraph/issues/27448 (PRs: ~[#31316](https://github.com/sourcegraph/sourcegraph/pull/31316)~, ~[#31413](https://github.com/sourcegraph/sourcegraph/pull/31413)~, ~[#31559](https://github.com/sourcegraph/sourcegraph/pull/31559)~) __3.00d__

@sashaostrikov: __26.00d__

Completed: __26.00d__
- [x] (🏁 202 days ago) https://github.com/sourcegraph/sourcegraph/issues/28260  __2.00d__
- [x] (🏁 201 days ago) https://github.com/sourcegraph/sourcegraph/issues/26926  __2.00d__
- [x] (🏁 181 days ago) https://github.com/sourcegraph/sourcegraph/issues/28914 (PRs: ~[#29336](https://github.com/sourcegraph/sourcegraph/pull/29336)~) __1.00d__
- [x] (🏁 181 days ago) https://github.com/sourcegraph/sourcegraph/issues/29238 (PRs: ~[#29328](https://github.com/sourcegraph/sourcegraph/pull/29328)~) __2.00d__
- [x] (🏁 181 days ago) https://github.com/sourcegraph/sourcegraph/issues/29240 (PRs: ~[#29328](https://github.com/sourcegraph/sourcegraph/pull/29328)~, ~[#29335](https://github.com/sourcegraph/sourcegraph/pull/29335)~) __2.00d__
- [x] (🏁 181 days ago) https://github.com/sourcegraph/sourcegraph/issues/29239 (PRs: ~[#29328](https://github.com/sourcegraph/sourcegraph/pull/29328)~, ~[#29332](https://github.com/sourcegraph/sourcegraph/pull/29332)~) __2.00d__
- [x] (🏁 175 days ago) https://github.com/sourcegraph/sourcegraph/issues/29241 (PRs: ~[#29328](https://github.com/sourcegraph/sourcegraph/pull/29328)~, ~[#29334](https://github.com/sourcegraph/sourcegraph/pull/29334)~) __2.00d__
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/issues/28267 (PRs: ~[#29374](https://github.com/sourcegraph/sourcegraph/pull/29374)~) __2.00d__
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/issues/28265 (PRs: ~[#29374](https://github.com/sourcegraph/sourcegraph/pull/29374)~) __1.00d__
- [x] (🏁 147 days ago) https://github.com/sourcegraph/sourcegraph/issues/27490 (PRs: ~[#31049](https://github.com/sourcegraph/sourcegraph/pull/31049)~) __5.00d__
- [x] (🏁 146 days ago) https://github.com/sourcegraph/sourcegraph/issues/27332 (PRs: ~[#29919](https://github.com/sourcegraph/sourcegraph/pull/29919)~) __2.00d__
- [x] (🏁 119 days ago) https://github.com/sourcegraph/sourcegraph/issues/27448 (PRs: ~[#31316](https://github.com/sourcegraph/sourcegraph/pull/31316)~, ~[#31413](https://github.com/sourcegraph/sourcegraph/pull/31413)~, ~[#31559](https://github.com/sourcegraph/sourcegraph/pull/31559)~) __3.00d__

@varsanojidan: __1.00d__

Completed: __1.00d__
- [x] (🏁 133 days ago) https://github.com/sourcegraph/sourcegraph/issues/30751  __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by sashaostrikov** [comment]
@ryanslade 

After I finished working on codeintel tasks, I realised that probably we also want to apply sub-repo filters on [documentation references](https://github.com/sourcegraph/sourcegraph/blob/a37dcdfc3c50efbc5849c7785cec3c3efb106dc2/enterprise/cmd/frontend/internal/codeintel/resolvers/documentation_query_references.go#L20) and [documentation definitions](https://github.com/sourcegraph/sourcegraph/blob/a37dcdfc3c50efbc5849c7785cec3c3efb106dc2/enterprise/cmd/frontend/internal/codeintel/resolvers/documentation_query_definitions.go#L14) queries as well, as they can show users any files within a repo. 

I am not creating issues for now, because I'm not 100% sure about it (and don't want to pollute tracking issue with wrong tasks which will be deleted), so probably this can be done after I am back in January.

[Ranges](https://github.com/sourcegraph/sourcegraph/blob/a37dcdfc3c50efbc5849c7785cec3c3efb106dc2/enterprise/cmd/frontend/internal/codeintel/resolvers/query_ranges.go#L19) query should not be a problem because the documentation says that this query returns only results within a file.

**Comment by ryanslade** [comment]
@jplahn I'm going to close this as it's mostly noise at this point.

We're still doing some work on this related to Gerrit and improving permissions rules for Perforce but I don' think we need the overall tracking issue anymore.
