### ISSUE TITLE
Code Insights: [FE] Create creation UI page for capture group insight

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#28026]
## Context

Designs https://www.figma.com/file/qomcHxvHjrwfS3We6NVHGh/Automatically-generated-data-series-%5Breview%5D?node-id=246%3A11

This creation UI page should be almost the same compared to search-based insight creation UI except for data series input and maybe repositories field.  

Blockers:  
- https://github.com/sourcegraph/sourcegraph/issues/21339

## Todo
- [ ] Implement first layouts and basic components for creation page UI https://github.com/sourcegraph/sourcegraph/pull/28654
- [ ] Connect live preview chart to the creation form 
- [ ] Connect the page itself to the creation intro page
- [ ] Update Monaco query input (include preview button and regexp icon in query input field) 
- [ ] Include FE pings for creation/editing capture group insight
