### ISSUE TITLE
Distribution 3.3 tracking issue

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2809]
## User story

@ggilmore, @beyang, @slimsag : Could someone provide a paragraph on why these specific set of issues, the benefits and who this will help. This helps greatly with the writing of the blog post.

Examples at #2025 and #2848

---

Mark | Description
-- | --
:running_man: | work in progress
:hand: | blocked task
:muscle:   | stretch goal for this iteration
:red_circle:   | missing issue reference
:large_blue_circle:   | more investigation required to remove uncertainty
:black_circle:   | under discussion within the team

Activation (@beyang)
- [x] Tech debt: https://github.com/sourcegraph/sourcegraph/issues/2634
- [x] Tech debt: https://github.com/sourcegraph/sourcegraph/issues/2768
- [x] https://github.com/sourcegraph/sourcegraph/issues/2793
- [x] Quick configure button for all code hosts ([planning doc](https://docs.google.com/document/d/1bX5GkOdkKb19-Mg96G93WfyIghZILAvuMxcIbM-VOls/edit))
- [ ] :hand: :red_circle: Show repositories to be synced when adding a new external service (pending repo-updater updates)
- [ ] :running_man: Quick configure buttons for critical site config https://github.com/sourcegraph/sourcegraph/issues/2905
- [ ] :muscle: Network policies for k8s cluster https://github.com/sourcegraph/deploy-sourcegraph/issues/213

Auth (@beyang) Timeboxed to 2 days
- [x] Username immutable https://github.com/sourcegraph/sourcegraph/issues/2438
- [ ] :muscle: Confusing GitLab docs https://github.com/sourcegraph/sourcegraph/issues/2040
- [ ] :muscle: GitHub oauth bug https://github.com/sourcegraph/sourcegraph/issues/2398
- [ ] :muscle: GitLab oauth bug https://github.com/sourcegraph/sourcegraph/issues/2263
- [ ] :muscle: GitLab `identityProvider` bug https://github.com/sourcegraph/sourcegraph/issues/2476
- [ ] :muscle: Update config validation logic https://github.com/sourcegraph/sourcegraph/issues/2897
- [ ] :running_man: Confusion about Onelogin config: https://github.com/sourcegraph/sourcegraph/issues/3218

Auth (@beyang)
- [ ] :running_man: https://github.com/sourcegraph/sourcegraph/issues/3277

Deployment (@ggilmore)
- [ ] 🏃 redis-cache deployment upgrade from 2.x to 3.2 had incorrect perms on data dir https://github.com/sourcegraph/sourcegraph/issues/3254
- [ ] :muscle: Improve cloud provider deployment process https://github.com/sourcegraph/sourcegraph/issues/2068
- [ ] :muscle: HTTPS setup
   - Related issues:
      - https://github.com/sourcegraph/sourcegraph/issues/2285
      - https://github.com/sourcegraph/sourcegraph/issues/2475
      - https://github.com/sourcegraph/sourcegraph/issues/2478
      - > @KattMingMing Yea I’ll need to dig it up but it’s just that the documentation was incomplete and didn’t explain how to use it with Sourcegraph properly
i.e Let’s Encrypt auto renews and port 80 conflicts
- [ ] :muscle: :red_circle: Explore Pulumi as a deployment orchestration option. Try it out on dogfood / build cluster first.

Release (@slimsag)
- [ ] (stretch) Our services can create an unbounded number of processes https://github.com/sourcegraph/sourcegraph/issues/2743
- [ ] (stretch) Automated release testing https://github.com/sourcegraph/sourcegraph/issues/2392

Additional private issues: https://github.com/sourcegraph/infrastructure/issues/1409

**Comment by nicksnyder** [comment]
Link to this from the roadmap?

**Comment by sqs** [comment]
@nicksnyder 	Done https://docs.sourcegraph.com/dev/roadmap#3-3

**Comment by slimsag** [comment]
Closing since the 3.3 window has closed.
