### ISSUE TITLE
3.34.1 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by kevinwojo** [sourcegraph/sourcegraph#28105]
# 3.34.1 managed instances upgrade

These [managed instances](../enablement/delivery/managed/index.md) upgrades are scheduled for **[Nov 23, 2021, 6:00 PM (UTC)](https://time.is/1800_23_Nov_2021_in_UTC?One%20working%20day%20after%203.34.1%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../enablement/delivery/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.

## Upgrade customer managed instances

- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8195
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/1503
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/518
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282

---

Also see [3.34.1 patch release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/28104)
