### ISSUE TITLE
Repo Management Sub-repo Permissions Tracking issue

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#28180]
### Plan

This issue tracks all works required for implementing [sub-repo permissions](https://docs.google.com/document/d/1d8j-6VC_nk8HXEDT6U2_s-_9uSzgzHWZzrJjII9pKEE/edit#)

As a dependency on that project, we also need to implement phases 1 and 2 of our plan to move gitserver to a [hexagonal architecture](https://docs.google.com/document/d/1sxHpZIqKGi66evDQl6sN1FAJObbHAIkdl49EKOy7aUs/edit) and so we'll track those issues too.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27332    🏳️ [PD 503 sub-repo permissions](https://github.com/sourcegraph/sourcegraph/milestone/139)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27490    🏳️ [PD 503 sub-repo permissions](https://github.com/sourcegraph/sourcegraph/milestone/139)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27498    🏳️ [PD 503 sub-repo permissions](https://github.com/sourcegraph/sourcegraph/milestone/139)

@bobheadxi

- [ ] https://github.com/sourcegraph/sourcegraph/issues/26972    🏳️ [PD 503 sub-repo permissions](https://github.com/sourcegraph/sourcegraph/milestone/139)

@ryanslade

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27448    🏳️ [PD 503 sub-repo permissions](https://github.com/sourcegraph/sourcegraph/milestone/139)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27496    🏳️ [PD 503 sub-repo permissions](https://github.com/sourcegraph/sourcegraph/milestone/139)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by ryanslade** [comment]
Was just testing something out.. wanted to try and track issue from two different milestones
