### ISSUE TITLE
Saved search improvements

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2824]
Placeholder tracking issue for saved search improvements in 3.3
- [x] Saved searches not appearing on homepage
#1364
- [ ] ~Move saved searches from settings to a dedicated table in the database (stretch)~ (Not going to be completed, will be shipped in 3.4)
  - [ ] ~Can't delete or create multiple saved searches in one session. https://github.com/sourcegraph/sourcegraph/issues/3208 (stretch)~
  - [ ] ~Make saved searches available through our GraphQL API (stretch)~
- [ ] ~Re-implement `notifyOrganizations` and `notifyUsers` (removed in https://github.com/sourcegraph/enterprise/pull/9962, issue https://github.com/sourcegraph/enterprise/issues/9961) (stretch)~ (not going to be completed)
- [x] Configure Slack webhook URL link is broken #3102
- [ ] ~Add tests to react components (stretch)~

**Comment by nicksnyder** [comment]
Any update here?
