### ISSUE TITLE
3.3 Integrations quality tracking issue

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#2834]
**The source of truth for prioritization and what is being worked on are [the browser-extension issues on the "Code nav" project board](https://github.com/orgs/sourcegraph/projects/45?card_filter_query=label%3Abrowser-extension)**

**The source of truth for what is done in 3.3 are the [browser-extension issues on the 3.3 milestone](https://github.com/sourcegraph/sourcegraph/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Aupdated-desc+milestone%3A3.3+label%3Abrowser-extension+)**

## User story

@lguychard, @felixfbecker: Could someone provide a paragraph on why these specific set of issues, the benefits and who this will help. This helps greatly with the writing of the blog post.

Examples at #2025 and #2848

---

## Customer issues
- [x] Improve "Enable on this site" #2770, PR: https://github.com/sourcegraph/sourcegraph/pull/2835
- Bugs: https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Abrowser-extension+milestone%3A3.3+label%3Abug

## Technical Debt
- [x] Remove dead code in the browser extension
    - https://github.com/sourcegraph/sourcegraph/pull/2838
- [ ] Activate stylelint for the browser extension https://github.com/sourcegraph/sourcegraph/issues/2517
- [ ] Cleanup globals in [`context.tsx`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/shared/util/context.tsx), [`context.ts`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/context.ts), rely on `PlatformContext` when applicable, notably to differentiate in-page integration and browser extension. 
- [ ] Improve type safety of [chrome.runtime communication](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/extension/scripts/background.tsx#L218-284), remove deprecated messages
- [ ] Investigate removing global mutable [`repoUrlCache`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/shared/util/context.tsx#L19), or at the very least document its usage.
- [ ] Clean up Phabricator backend code (legacy Promise code, copy-pasta) [phabricator/backend.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/libs/phabricator/backend.tsx)
- [x] Clean up injected script entry point (remove useless checks & steps, improve clarity) [inject.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/extension/scripts/inject.tsx)
- [ ] Clean up `FileInfo` interface - `base`-prefixed properties should be in a nested property and not optional #3107 

## Stability & Polish
- [x] Investigate most frequent Sentry exceptions
    - [x] [`Unable to find command palette mount`](https://sentry.io/organizations/sourcegraph/issues/936671459/?project=1334031&query=is%3Aunresolved&statsPeriod=14d&utc=false)
    - [x] [`Cannot read property 'title' of null`](https://sentry.io/organizations/sourcegraph/issues/922440405/?project=1334031&query=is%3Aunresolved&statsPeriod=14d&utc=false) (related: #2515)
        - https://github.com/sourcegraph/sourcegraph/pull/2889
- [x] Improve reactive handling of DOM changes
    - [x] use a single `MutationObserver` and make inject functions reactive to DOM changes by taking `Observable<MutationRecord[]>`  https://github.com/sourcegraph/sourcegraph/pull/2909, #3191 
- [x] Make styling more native to code host
- [x] Add unit tests with code host HTML DOM fixtures
  - [x] Mount getters
  - [x] DOM functions
    - https://github.com/sourcegraph/sourcegraph/pull/3441

# Plan
Attack technical bugs and bugs by area:
- [ ] Common/entry point (single mutation observer, error handling, backend logic, interfaces etc) 🏃 
- [x] Bitbucket
- [ ] GitHub & GitHub Enterprise
- [ ] Phabricator
- [ ] Gitlab

**Comment by KattMingMing** [comment]
We have important customers using the Phabricator Extension so when making changes to Phabricator code you'll need to test running as the browser extension and also with https://github.com/sourcegraph/phabricator-extension.

**Comment by slimsag** [comment]
Closing since the 3.3 window has closed.
