### ISSUE TITLE
Humans of Sourcegraph: milestone 2 

### ISSUE THREAD

**Issue by adeola-ak** [sourcegraph/sourcegraph#28383]
[Scratch document](https://docs.google.com/document/d/1jLjTzsXGzQ5xfKTT_2Wxhu6OtF0wOzOYgfZmp04s0zk/edit)

- [x] **EM2: Design Planning**
  - [x] talk to people ops about accessing bamboo API
  - [x] create a design sketch
  - [x] DB planning 
  - [x] Create a skeleton of project in GitHub

**Comment by adeola-ak** [comment]
- got API access, my current key returns limited data but enough data for MVP to be complete (name, title, org, team, supervisor)
- will use bamboo as database
- project [here](https://github.com/adeola-ak/humans-of-sg) includes design sketch in readme
