### ISSUE TITLE
Devx Buildkite-Analytics Tracking issue

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#28470]
### Plan

Buildkite is releasing https://buildkite.com/test-analytics in beta this week. It supports out the box only Ruby RSpec and Junit test outputs. 

We need to convert the output of our tests into a format that Builkdite Analytics can parse, i.e JUnit xml reports. 

@jhchabran TODO update this ticket if needed when the beta is released.

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@bobheadxi

Completed
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/issues/28469 

@jhchabran

- [x] https://github.com/sourcegraph/sourcegraph/issues/28472 

@umpox

Completed
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/28471 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request
