### ISSUE TITLE
Docs 3.3 tracking issue

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#2848]
## User story

As a site admin or user, documentation should be aesthetically pleasing, version specific (when needed) and provide guides, e.g. how to get an SSL certificate trusted by your browser, and reference material, e.g. this is how repo syncing works in 3.3. This is so admins can be confident Sourcegraph is set up correctly, securely, and is ready for sharing.

This work provides new and/or updated documentation that is required when setting up a Sourcegraph instance for deploying and sharing.

## UX improvements

- [ ] New docs theme #2564
- [ ] Add LHS navigation for Docs #2463
- [x] Docs version selector #2464

## Content improvements

- [x] Better docs for setting up an instance ready for sharing #2277
- [ ] Markdown heading symbols are misaligned on Firefox #2246
- [ ] Improve NGINX Let's Encrypt documentation #2475
- [x] Docs improvements for GitHub external service #2902
- [x] Finish [Terraform AWS EC2 work](https://github.com/sourcegraph/deploy-sourcegraph-aws)
- [ ] Fix unclear and hard to discover indexed search documentation https://github.com/sourcegraph/sourcegraph/issues/2165
- [ ] Add documentation for cloning with ssh #2996

**Comment by slimsag** [comment]
Closing since the 3.3 window has closed.
