### ISSUE TITLE
Code intelligence 3.3 tracking issue

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2856]
## User story

The default code intelligence is not very precise and doesn't always find definitions for symbols that you're hovering over.

- [x] Support language-specific callbacks for filtering defs/refs https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/66
- [x] Poor quality Swift regexes https://github.com/sourcegraph/sourcegraph/issues/2903
  - https://github.com/sourcegraph/sourcegraph/pull/2912
  - https://github.com/sourcegraph/sourcegraph/pull/2945
- Fall back to basic code intel when hovers take over 500ms https://github.com/sourcegraph/sourcegraph/issues/2571
  - Implemented in https://github.com/sourcegraph/sourcegraph-go/pull/55
  - Disabled in https://github.com/sourcegraph/sourcegraph-go/pull/58 pending a different approach (see https://github.com/sourcegraph/sourcegraph-go/pull/57) and making sure it doesn't cause confusion
- [ ] Single-click j2d https://github.com/sourcegraph/enterprise/issues/11047
- [ ] Support j2d on parameters and local variables for various files (using tree-sitter)
- [ ] Use `@sourcegraph/lsp-client` https://github.com/sourcegraph/sourcegraph-go/issues/28
  - WIP PR https://github.com/sourcegraph/sourcegraph-go/issues/28
  - Go langserver needs updates described in  https://github.com/sourcegraph/sourcegraph-go/issues/28#issuecomment-469488194
- [x] Do not show "Find references" over comments or whitespace https://github.com/sourcegraph/sourcegraph/issues/2159
  - Attempt 1 (tie refs to the presence of a definition)  https://github.com/sourcegraph/sourcegraph/pull/3188
  - Attempt 2 (add a token type provider to the extension API) https://github.com/sourcegraph/sourcegraph/pull/3239
- [ ] Highlight variables https://github.com/sourcegraph/sourcegraph/issues/3037
- [ ] Dependency graph
- [ ] Filter definitions for all languages https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/67
- [ ] Implement document highlights using [tree-sitter](https://tree-sitter.github.io/tree-sitter/)
- [ ] Filter definitions by parent (from ctags)
- [x] Go code intel slow https://sourcegraph.slack.com/archives/C0C324C91/p1554154297030300
  - Recommend `-freeosmemory=false` https://github.com/sourcegraph/sourcegraph-go/pull/56
  - Set `-freeosmemory=false` on Sourcegraph.com https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/fe24ddf48cdb5195247ffbf5d03032d89e33ef98

**Comment by sqs** [comment]
@chrismwendt I don't see anything about Swift on here. Did you evaluate our current Swift support (and use @nicksnyder 	as an oracle) already?

**Comment by chrismwendt** [comment]
We looked briefly, but embarrassingly we both missed this glaring problem that I filed just now https://github.com/sourcegraph/sourcegraph/issues/2903

I'll fix that and do another assessment in ~3 hours. I expect filtering by imports to help a bit, too, which I plan to get to within a few days.

**Comment by chrismwendt** [comment]
Next tracking issue: 3.4 https://github.com/sourcegraph/sourcegraph/issues/3449
