### ISSUE TITLE
Tracking issue: Scalable explicit repository permissions

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#28590]
### Plan

This is the tracking issue about adding new APIs to allow large scale modifications of repository permissions.
The `setRepositoryPermissionsForUsers` GraphQL endpoint is not sufficient to manipulate repo permissions for a set of users, especially when the number of repositories is very large.
The goal here is to add a minimal set of APIs that allow more granular control over repository permissions.

Related to https://github.com/sourcegraph/customer/issues/546

### Tracked issues

@unassigned

- [x] https://github.com/sourcegraph/sourcegraph/issues/28594 

@asdine

- [ ] https://github.com/sourcegraph/sourcegraph/issues/28591 (PRs: ~[#28675](https://github.com/sourcegraph/sourcegraph/pull/28675)~)
- [x] https://github.com/sourcegraph/sourcegraph/issues/28592 

Completed
- [x] (🏁 93 days ago) https://github.com/sourcegraph/sourcegraph/pull/28675 

@mollylogue

- [ ] https://github.com/sourcegraph/sourcegraph/issues/28593 (PRs: ~[#28763](https://github.com/sourcegraph/sourcegraph/pull/28763)~)

Completed
- [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/pull/28763 

@ryanslade: __5.00d__

Completed: __5.00d__
- [x] (🏁 17 days ago) https://github.com/sourcegraph/sourcegraph/issues/34631  __5.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by mollylogue** [comment]
Doc with proposed new plan based on feedback from customer: https://docs.google.com/document/d/1oQ3KTErE6elRMbPwd7Ngdqi9iq1_MYOrnOimEGv7U3w/edit#heading=h.cgr6osyqgxh5 
Once we've finalized the plan we'll update this tracking issue to reflect any changes.

**Comment by asdine** [comment]
Closing this in favor of https://github.com/sourcegraph/sourcegraph/issues/36355
