### ISSUE TITLE
3.35.0 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#28614]
# 3.35.0 managed instances upgrade

These [managed instances](../enablement/delivery/managed/index.md) upgrades are scheduled for **[Dec 21, 2021, 6:00 PM (UTC)](https://time.is/1800_21_Dec_2021_in_UTC?One%20working%20day%20after%203.35%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../enablement/delivery/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade. **Warning**: This will require extra hand-holding due to changes made in https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/145. In particular, the TF state for the existing instance is not up to date.

## Upgrade customer managed instances

- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/1503
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/2512 (skipped, decomissioning)
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/6857

---

Also see [3.35.0 release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/28613)

**Comment by kevinwojo** [comment]
Superseded by #28641

**Comment by kevinwojo** [comment]
Superseded by #29291

**Comment by kevinwojo** [comment]
Superseded by #29404
