### ISSUE TITLE
Humans of Sourcegraph: milestone 3

### ISSUE THREAD

**Issue by adeola-ak** [sourcegraph/sourcegraph#29029]
[Scratch document](https://docs.google.com/document/d/1jLjTzsXGzQ5xfKTT_2Wxhu6OtF0wOzOYgfZmp04s0zk/edit)

- [x] **EM3: Build (run locally)**
  - [x] Able to access and display all available employee data from Bamboo data on the front end
  - [x] Modal pop up for employee cards
  - [x] Get more permissions from API - currently do not have hire date
  - [x] Customizing data displayed on the front end example: recent hires
  - [ ] Meet with People ops to get a better understanding of how the API permissions work

**Comment by adeola-ak** [comment]
Possible revisions to milestone to keep in mind from Chris: 
"I agree that there are a lot of tabs. I’d say for v0.1, just forget about tabs or filtering, and stick everyone there (ordered by start date, newest at the top).
If clicking someone takes you to their page, then that page could have things like their dept / org / team listed. Clicking on those could take you to a filtered view showing only people in that dept / org / team (and that could be a shareable url, too). But I think this paragraph is all v0.2 ideas :slightly_smiling_face:"

**Comment by adeola-ak** [comment]
possibly adding search bar while waiting for more API permissions
