### ISSUE TITLE
3.36.0 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by kevinwojo** [sourcegraph/sourcegraph#29291]
# 3.36.0 managed instances upgrade

These [managed instances](../../enablement/delivery/managed/index.md) upgrades are scheduled for **[Jan 21, 2022, 6:00 PM (UTC)](https://time.is/1800_21_Jan_2022_in_UTC?One%20working%20day%20after%203.36%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../enablement/delivery/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [ ] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [ ] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.
  - [ ] https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/196

## Upgrade customer managed instances

- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/2512
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/6857
- [ ]  Upgrade instance for sourcegraph/customer#605
- [ ]  Upgrade instance for sourcegraph/accounts#4029
- [ ]  Upgrade instance for sourcegraph/accounts#5057
- [ ]  Upgrade instance for sourcegraph/accounts#1338

---

Also see [3.36.0 release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/29290)

**Comment by kevinwojo** [comment]
Superseded by #29404

**Comment by caugustus-sourcegraph** [comment]
Superseded by #30042
