### ISSUE TITLE
Non-sequential migrations Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#29542]
### Plan

Let's get rid of that pesky migration conflict when two different teams merge around the same with database changes. We can get around this by reading migration definitions in a manner which don't impose a complete sequential order so that two unrelated migrations do not conflict.

See the attached issues for an implementation plan.

### Tracked issues

@efritz

Completed
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/issues/29547 (PRs: ~[#29555](https://github.com/sourcegraph/sourcegraph/pull/29555)~)
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/issues/29544 (PRs: ~[#29554](https://github.com/sourcegraph/sourcegraph/pull/29554)~)
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/issues/29543 (PRs: ~[#29553](https://github.com/sourcegraph/sourcegraph/pull/29553)~)
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/29545 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/29548 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by efritz** [comment]
Done!
