### ISSUE TITLE
SOC2: Cloud DevOps Tracking issue

### ISSUE THREAD

**Issue by JenRed777** [sourcegraph/sourcegraph#29589]
### Plan
Issue to track all on going SOC2 work for the Cloud DevOps team

### Tracked issues

@unassigned

Completed
- [x] (🏁 53 days ago) https://github.com/sourcegraph/sourcegraph/issues/29596 

@JenRed777

Completed
- [x] (🏁 53 days ago) https://github.com/sourcegraph/sourcegraph/issues/29579 
- [x] (🏁 46 days ago) https://github.com/sourcegraph/sourcegraph/issues/29578 
- [x] (🏁 46 days ago) https://github.com/sourcegraph/sourcegraph/issues/29601 
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/issues/29602 

@RafLeszczynski

Completed
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/issues/29602 

@caugustus-sourcegraph

Completed
- [x] (🏁 52 days ago) https://github.com/sourcegraph/sourcegraph/issues/29594 

@danieldides

Completed
- [x] (🏁 53 days ago) https://github.com/sourcegraph/sourcegraph/issues/29599 
- [x] (🏁 52 days ago) https://github.com/sourcegraph/sourcegraph/issues/29590 
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/issues/29595 

@daxmc99

- [ ] https://github.com/sourcegraph/sourcegraph/issues/29592 

Completed
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/issues/29591 
- [x] (🏁 46 days ago) https://github.com/sourcegraph/sourcegraph/issues/29601 
- [x] (🏁 32 days ago) https://github.com/sourcegraph/sourcegraph/issues/29593 

@filiphaftek

- [ ] https://github.com/sourcegraph/sourcegraph/issues/28082 
  - [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/33117 

Completed
- [x] (🏁 77 days ago) https://github.com/sourcegraph/sourcegraph/issues/29580 
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/issues/29591 
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/33117
