### ISSUE TITLE
Humans of Sourcegraph: milestone 4

### ISSUE THREAD

**Issue by adeola-ak** [sourcegraph/sourcegraph#29863]
[Scratch document](https://docs.google.com/document/d/1jLjTzsXGzQ5xfKTT_2Wxhu6OtF0wOzOYgfZmp04s0zk/edit)

- [ ] **EM4: Build (run locally)**
  - [x] Design
  - [x] Outline data needed - (preferred name, pronouns?)
  - [ ] Google auth login
  - [ ] Experimental use
  - [ ] Hosting
  - [x] Meet with People ops to get a better understanding of how the API permissions work

**Comment by adeola-ak** [comment]
- [ ] More features and filters?
