### ISSUE TITLE
Insights: Capture Groups v2 and Polish Tracking issue

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#29956]
### Plan

We shipped a terrific prototype v1 but we have some key UI features we need to complete to ensure capture group insights are widely usable. 

Examples: 

- [ ] What happens if there are more than 20 matches? The UI should indicate this
- [ ] Can we keep sorting of the "top 20" deterministic? 
- [ ] Should we let you select a wider range than 20? 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by Joelkw** [comment]
Notes from @coury-clark on the backend component of handling >20 – not low-hanging fruit for what it gets us right now. For the checkbox items.
