### ISSUE TITLE
3.36.1 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#30042]
# 3.36.1 managed instances upgrade

These [managed instances](../../cloud/delivery/managed/index.md) upgrades are scheduled for **[Jan 22, 2022, 6:00 PM (UTC)](https://time.is/1800_22_Jan_2022_in_UTC?One%20working%20day%20after%203.36.1%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../cloud/delivery/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.

## Upgrade customer managed instances

- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/2512 - Shut down in https://github.com/sourcegraph/customer/issues/603
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/6857
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/605
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/4029
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5057
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/1338

---

Also see [3.36.1 patch release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30041)

**Comment by caugustus-sourcegraph** [comment]
Superseded by #30052
