### ISSUE TITLE
Code Insights Smoke testing checklist

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#30043]
From our retro discussion: we want to build a "checklist" to confirm the happy paths are all covered after every release. This could be a manual actual checklist to start that we migrate to automated testing over time. Ideally, this list would mark what paths are covered by automated tests and what needs to be run manually.

We'd also like to list here any "scripts" that people are using currently to create testing insights, dashboards etc.

**Comment by unclejustin** [comment]
cc @Joelkw @AlicjaSuska @felixfbecker

**Comment by Joelkw** [comment]
Thanks! Here's [a script I use after manually creating insights to screenshot every 10 minutes as they run](https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1628928459272200?thread_ts=1628928236.272100&cid=C014ZCKMCAV). It may need to be updated with UI changes.  

Here [are the insights that I manually create](https://k8s.sgdev.org/insights/dashboards/ZGFzaGJvYXJkOnsiSWRUeXBlIjoiY3VzdG9tIiwiQXJnIjo3MjcxMzh9), generally, that we should automate via the API now, that provide a range of results sizes.

**Comment by Joelkw** [comment]
Here are some core paths we should test: 

- [ ] Create a new insight repo field auto-completes
   - [ ] The query field syntax highlights appropriately
   - [ ] The live preview loads if it's not an all-repos insight
- [ ] Create a new insight saves
  - [ ] The insight shows the correct loading state after creation 
  - [ ] The insight completes and stops showing the loading state
  - [ ] Adding it to a new dashboard saves
  - [ ] Creating a copy of it via filters saves
  - [ ] Removing it from a dashboard saves
  - [ ] Click-in-to-diff-search works 
  - [ ] Filtering works 
  - [ ] Click-in-to-diff-search on a filtered insight works 
- [ ] We should check the above on insights running over some repos, all repos, and some repos capture group, and all repos capture groups

**Separately, for priority, by far the most important testing we can do is the "correctness" testing to make sure the data itself is generated correctly.** See the prior comment for a good set of sample insights.

**Comment by unclejustin** [comment]
Quick notes from sync with the esteemed @coury-clark 

Long term we need access to GCP to enable copying an instance and running migrations.

Very generally:

- Copy instance and run migrations
- Check that all migrations ran successfully
- Check OOB migrations
- Perform basic CRUD for dashboards and insights with two different users
- Confirm users can see what they should, and not see what they shouldn't
- Confirm certain insights return data as expected. This implies creating the same insights from release to release, which also implies using creation scripts

The above plus @Joelkw 's notes is a pretty good starting point. I will get this written up into a handbook PR.

**Comment by unclejustin** [comment]
[Document here](https://docs.google.com/document/d/1VJb2G7uA1tWdtlklEvwtWhhsO3fl0Smd8rgA5myL74w/edit#heading=h.1xbxserpxj8x)
