### ISSUE TITLE
3.37.0 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#30052]
# 3.37.0 managed instances upgrade

These [managed instances](../../cloud/delivery/managed/index.md) upgrades are scheduled for **[Feb 22, 2022, 6:00 PM (UTC)](https://time.is/1800_22_Feb_2022_in_UTC?One%20working%20day%20after%203.37%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../cloud/delivery/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [x] Upgrade [insightstest.sourcegraph.com](https://insightstest.sourcegraph.com) 
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.
	- [x] Merge https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/302
	- [x] Upgrade executors (`sourcegraph/executors/google//module/*`) to `v3.37.1`
	- [x] Upgrade `google` providers to `4.8.0`

## Upgrade customer managed instances

- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/6857
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/605
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5057

---

Also see [3.37.0 release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30051)

**Comment by michaellzc** [comment]
Superseded by #30563

**Comment by michaellzc** [comment]
Superseded by #30638

**Comment by michaellzc** [comment]
@michaellzc Myfitnesspal Inc -> HashiCorp

**Comment by michaellzc** [comment]
Michael's to Upgrade List

From https://github.com/sourcegraph/accounts/issues/8288 to https://github.com/sourcegraph/accounts/issues/581

**Comment by mucles** [comment]
Manny's to upgrade list

From https://github.com/sourcegraph/accounts/issues/6857 to https://github.com/sourcegraph/accounts/issues/1338

**Comment by caugustus-sourcegraph** [comment]
@caugustus-sourcegraph - https://github.com/sourcegraph/accounts/issues/528 to https://github.com/sourcegraph/accounts/issues/547

**Comment by mucles** [comment]
removing Conversica from upgrade list - deleted managed instances - https://github.com/sourcegraph/customer/issues/603

**Comment by mucles** [comment]
removing from the upgrade list
-deleted managed instances - https://github.com/sourcegraph/customer/issues/603
-suspended managed instances - https://github.com/sourcegraph/accounts/issues/1338
-suspended managed instances - https://github.com/sourcegraph/accounts/issues/4029
