### ISSUE TITLE
Code Insights Marketing Landing Page Tracking issue

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#30106]
### Plan

The tracking issue for planning work for code insights marketing landing page. 

### Availability

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

### Tracked issues

@unassigned

Completed
- [x] (🏁 82 days ago) https://github.com/sourcegraph/sourcegraph/issues/30746    🏳️ [Insights iteration 11](https://github.com/sourcegraph/sourcegraph/milestone/153)

@unclejustin

Completed
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/30113    🏳️ [Insights iteration 11](https://github.com/sourcegraph/sourcegraph/milestone/153)
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/30745    🏳️ [Insights iteration 11](https://github.com/sourcegraph/sourcegraph/milestone/153)
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/30605    🏳️ [Insights iteration 11](https://github.com/sourcegraph/sourcegraph/milestone/153)
- [x] (🏁 59 days ago) https://github.com/sourcegraph/sourcegraph/issues/30165 

@vovakulikov

Completed
- [x] (🏁 93 days ago) https://github.com/sourcegraph/sourcegraph/issues/30107    🏳️ [Insights iteration 10](https://github.com/sourcegraph/sourcegraph/milestone/150)
- [x] (🏁 93 days ago) https://github.com/sourcegraph/sourcegraph/issues/30108    🏳️ [Insights iteration 10](https://github.com/sourcegraph/sourcegraph/milestone/150)
- [x] (🏁 93 days ago) https://github.com/sourcegraph/sourcegraph/issues/30156    🏳️ [Insights iteration 10](https://github.com/sourcegraph/sourcegraph/milestone/150)
- [x] (🏁 90 days ago) https://github.com/sourcegraph/sourcegraph/issues/30157    🏳️ [Insights iteration 10](https://github.com/sourcegraph/sourcegraph/milestone/150)
- [x] (🏁 89 days ago) https://github.com/sourcegraph/sourcegraph/issues/30158    🏳️ [Insights iteration 10](https://github.com/sourcegraph/sourcegraph/milestone/150)
- [x] (🏁 88 days ago) https://github.com/sourcegraph/sourcegraph/issues/30159    🏳️ [Insights iteration 10](https://github.com/sourcegraph/sourcegraph/milestone/150)
- [x] (🏁 87 days ago) https://github.com/sourcegraph/sourcegraph/issues/30160    🏳️ [Insights iteration 10](https://github.com/sourcegraph/sourcegraph/milestone/150)
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/30113    🏳️ [Insights iteration 11](https://github.com/sourcegraph/sourcegraph/milestone/153)
- [x] (🏁 80 days ago) https://github.com/sourcegraph/sourcegraph/issues/30167    🏳️ [Insights iteration 11](https://github.com/sourcegraph/sourcegraph/milestone/153)
- [x] (🏁 73 days ago) https://github.com/sourcegraph/sourcegraph/issues/30608    🏳️ [Insights iteration 11](https://github.com/sourcegraph/sourcegraph/milestone/153)
- [x] (🏁 59 days ago) https://github.com/sourcegraph/sourcegraph/issues/30165 
- [x] (🏁 58 days ago) https://github.com/sourcegraph/sourcegraph/issues/31686    🏳️ [Insights iteration 12](https://github.com/sourcegraph/sourcegraph/milestone/154)
- [x] (🏁 58 days ago) https://github.com/sourcegraph/sourcegraph/issues/31650    🏳️ [Insights iteration 12](https://github.com/sourcegraph/sourcegraph/milestone/154)
- [x] (🏁 58 days ago) https://github.com/sourcegraph/sourcegraph/issues/30166    🏳️ [Insights iteration 12](https://github.com/sourcegraph/sourcegraph/milestone/154)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
I think we can close it since everything here was implemented
