### ISSUE TITLE
lsif-python: umbrella issue

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#30178]
Progress tracker for Python indexer

Decisions:

(TODO)

Status Tracker:

- [x] Open new fork: https://github.com/sourcegraph/pyright
- [x] Start using lsif-typescript snapshot testing
- [x] Start emitting lsif-typed
- [x] #31035

(Will add more as I write them up)

Reported dev envs in https://github.com/sourcegraph/sourcegraph/issues/30179
