### ISSUE TITLE
☂️ Main issues with lsif-node/lsif-tsc

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#30172]
* [ ] https://github.com/sourcegraph/lsif-node/issues/47 - The two main pain points here are: (1) import/export monikers do not work correctly for packages in such a monorepo and (2) you need to manually iterate over the directories when you have multiple `tsconfig.json` files. We've run into this.
* [ ] [The dependency on the typescript tarball](https://github.com/sourcegraph/lsif-node/blob/b1d39f61eb8abdb9c3ef4a214b611eb0c2d2e98b/package.json#L38): https://github.com/sourcegraph/lsif-node/issues/32 ... This problem has been raised by multiple customers. [1](https://sourcegraph.slack.com/archives/C015JREMBTR/p1632258581013700), [2](https://sourcegraph.slack.com/archives/C02BJ8T258D/p1633711756266300)
* [ ] https://github.com/sourcegraph/lsif-node/issues/185 - This problem has been raised by [one customer](https://sourcegraph.slack.com/archives/C02BJ8T258D/p1632954510131400).
* [ ] https://github.com/sourcegraph/lsif-node/issues/186 - We've run into this.
* [ ] https://github.com/sourcegraph/lsif-node/issues/150 - We've run into this.
* [ ] Stack overflows: https://github.com/sourcegraph/lsif-node/issues/181 - We've run into this when doing bringup for NPM packages.

**Comment by olafurpg** [comment]
Closing this issue as wontfix given that we have released a new indexer scip-typescript
