### ISSUE TITLE
SSBC-EM3.3: Miscellaneous tweaks

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#30524]
## `8.5d` total, `0.5d` remaining

- [x] Create page: #31165 **`1d`** @eseliger
- [x] Docs: #29689 **`0.5d`** @eseliger 
- [x] Tech debt: #29164 **`0.5d`** @eseliger 
- [x] Editor page: #31172 **`0.5d`** @courier-new 
- [x] Editor page: #30465 @adeola-ak
- [x] Execution page: #30468 **`0.5d`**
- [x] List page: #31164 **`2d`** @courier-new 
- [x] List page: #31166 **`1d`** @courier-new 
- [x] List page: #30463 @adeola-ak
- [x] Infrastructure: #31094 **`0.5d`** @eseliger
