### ISSUE TITLE
DevX cross-team learning: improve support for application DX

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#30550]
Work towards accomplishing this roadmap item: https://github.com/sourcegraph/sourcegraph/issues/31006

Upon assigning an issue to a DevX team member, make sure to add the `team/devx` label!

### Tracked issues

@unassigned: __4.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/32070 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/31182  __4.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/32234  __3.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/32238  🐛
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/32929  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/31178 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/37982 

@bobheadxi: __4.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/31182  __4.00d__
  - [x] (🏁 173 days ago) https://github.com/sourcegraph/sourcegraph/issues/32231  __1.00d__
  - [x] (🏁 169 days ago) https://github.com/sourcegraph/sourcegraph/issues/32232  __3.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/37244 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/37626  🛠️
  - [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/31006  🛠️

Completed: __4.00d__
- [x] (🏁 199 days ago) https://github.com/sourcegraph/sourcegraph/issues/30555 
- [x] (🏁 188 days ago) https://github.com/sourcegraph/sourcegraph/pull/31466 
- [x] (🏁 185 days ago) https://github.com/sourcegraph/src-cli/pull/698 
- [x] (🏁 173 days ago) https://github.com/sourcegraph/sourcegraph/issues/32231  __1.00d__
- [x] (🏁 169 days ago) https://github.com/sourcegraph/sourcegraph/issues/32232  __3.00d__
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/31006  🛠️

@davejrt: __4.00d__

Completed: __4.00d__
- [x] (🏁 170 days ago) https://github.com/sourcegraph/sourcegraph/issues/31181  __2.00d__
- [x] (🏁 133 days ago) https://github.com/sourcegraph/sourcegraph/issues/30656  __1.00d__
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/issues/33839  __1.00d__

@jhchabran: __3.00d__

Completed: __3.00d__
- [x] (🏁 163 days ago) https://github.com/sourcegraph/sourcegraph/issues/29222 (PRs: ~[#32265](https://github.com/sourcegraph/sourcegraph/pull/32265)~) __3.00d__

@kstretch9

Completed
- [x] (🏁 199 days ago) https://github.com/sourcegraph/sourcegraph/issues/30555 

@mucles

- [ ] https://github.com/sourcegraph/sourcegraph/issues/31182 
  - [x] (🏁 16 days ago) https://github.com/sourcegraph/sourcegraph/issues/40006  🐛

Completed
- [x] (🏁 16 days ago) https://github.com/sourcegraph/sourcegraph/issues/40006  🐛

@vrto

- [ ] https://github.com/sourcegraph/sourcegraph/issues/31179 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by bobheadxi** [comment]
Closing this issue out as this is no longer a primary focus of the DevX team
