### ISSUE TITLE
3.36.3 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#30563]
# 3.36.3 managed instances upgrade

These [managed instances](../../cloud/delivery/managed/index.md) upgrades are scheduled for **[Feb 3, 2022, 6:00 PM (UTC)](https://time.is/1800_3_Feb_2022_in_UTC?One%20working%20day%20after%203.36.3%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../cloud/delivery/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [ ] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [ ] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.

## Upgrade customer managed instances

- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/6857
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/605
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/4029
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5057
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/1338

---

Also see [3.36.3 patch release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30562)

**Comment by michaellzc** [comment]
Superseded by #30638
