### ISSUE TITLE
New reference panel: mix precise/search-based data

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#30970]
The new reference panel currently only works with precise code intel. The `code-intel-extensions` reference panel falls back to search based code intel.

The following tasks are the result of the spike done in https://github.com/sourcegraph/sourcegraph/issues/31645 & https://github.com/sourcegraph/sourcegraph/pull/32823.

### TODOs

- Basic fallback to search-based code intel when no precise code intel is available https://github.com/sourcegraph/sourcegraph/pull/32823
  - [x] Determine which language spec to use for current document
  - [x] Find token in text document, using language spec to determine token boundaries
  - [x] Use language spec to determine file extensions
  - [x] Query definitions
    - [x] Filter definitions based on language spec's `filterDefinitions`
  - [x] Query references
  - [x] Tag results as search-based and display that in UI
  - [x] Handle clicks on definitions in mini code view correctly
- Replicate behaviour of search-based code intel in `code-intel-extensions`
  - [x] Complex query logic https://github.com/sourcegraph/sourcegraph/pull/33362
    - [x] First search in current repository, at *current commit*
    - [x] Then fallback to repositories that are not current repository, if not on Sourcegraph.com
    - [x] Race between indexed/unindexed search
      - [x] If `basicCodeIntel.indexOnly` is set, do not search unindexed
      - [x] Use `basicCodeIntel.unindexedSearchTimeout` when searching unindexed search
  - [x] Filter out [`isExternalPrivateSymbol`](https://github.com/sourcegraph/code-intel-extensions/blob/a26ad1243b3d376e85941946f71b8ca7a0f35e13/template/src/search/providers.ts#L486) (fix in symbols service layer)
  - [x] Handle forks/archived repos, see [this code comment](https://github.com/sourcegraph/code-intel-extensions/blob/a26ad1243b3d376e85941946f71b8ca7a0f35e13/template/src/search/providers.ts#L460-L463) https://github.com/sourcegraph/sourcegraph/pull/33277
    - [x] Respect `basicCodeIntel.includeForks`
    - [x] Respect `basicCodeIntel.includeArchives`
  - [x] Sort results by proximity https://github.com/sourcegraph/sourcegraph/pull/33223
  - [x] Handle `codeIntel.mixPreciseAndSearchBasedReferences` https://github.com/sourcegraph/sourcegraph/pull/33419
    - [ ] If there are no precise references: load search-based references
    - [ ] If there are precise references: only load search-based references if `codeIntel.mixPreciseAndSearchBasedReferences` is true. Filter out duplicates.

**Comment by mrnugget** [comment]
I updated the ticket description to include a (rough) list of tasks required to implement search-based code intel for the new reference panel. These are based on the spike done in https://github.com/sourcegraph/sourcegraph/issues/31645. And the spike contains some code/PoCs that we can reuse for the proper implementation.

**Comment by mrnugget** [comment]
Closing because all PRs related to this have been merged.
