### ISSUE TITLE
Humans of Sourcegraph: milestone 5

### ISSUE THREAD

**Issue by adeola-ak** [sourcegraph/sourcegraph#30981]
(Some carry over from milestone 4):

- [x] **EM5: Complete MVP**
  - [x] Finishing touches with design and styles
  - [x] Hosting (Vercel)
  - [x] Okta login
  - [x] Add development and features to be section to readme
