### ISSUE TITLE
Improve CI stability: stateless agents

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#31003]
## Problem to solve

The main pipeline is unstable and can be down for several hours per day, which can slow down developers, block releases, and make bugs difficult to uncover.

## Measure of success

- The main pipeline is consistently green for at least 23 hours/day. 
- Red builds on the pipeline, are caused by legitimate test failures, and not the lower level infrastructure they're running on. 
- Total build time on main is within ~5 minutes of previous deployment model.

## Solution summary

CI stability was our main focus in FY22Q4, but we're carrying into FY23Q1 an effort to make Buildkite agents stateless.  

By removing any previous [state](https://www.interviewbit.com/blog/stateful-vs-stateless/#:~:text=The%20most%20significant%20distinction%20between,to%20be%20done%20in%20stateful.) from buildkite agents, we can guarantee the environment in which a test is being run and reduce any failures to application code. 
 
- Ensure agents only ever run one job
- Implement caching outside of the agent to reduce build times
- Monitor build times and failure types to verify the hypothesis that state in our buildkite agents has been a significant source of failures and a red pipeline.

## What specific customers are we iterating on the problem and solution with?

Sourcegraph developers, and more broadly anyone who relies on tests in Buildkite.

## Impact on use cases

We want to ensure that our CI is not only fast, but reliable and isn't a bottleneck for developers releasing code.  

## Delivery plan

- [x] [Refactor test dependency](https://github.com/sourcegraph/sourcegraph/issues/29375) install process to reduce failures and conflict between package versions 
- [x] Implement caching for system packages, libraries and docker to speed up builds. 
- [x] Change kubernetes deployment model to ensure agents only run one job. 
- [x] Ensure autoscaling scales up and down, based on demand to save compute resources.
- [ ] Make Buildkite agents stateless by default.

For more details, see the [tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30233) for this body of work.

**Comment by taylorsperry** [comment]
@davejrt Will you please help me flesh this out?

**Comment by davejrt** [comment]
@taylorsperry Some updates in the various sections. Let me know how this reads to you

**Comment by bobheadxi** [comment]
Continuation: https://github.com/sourcegraph/sourcegraph/issues/33196
