### ISSUE TITLE
DevExp team to gain insight into other teams development pain points

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#31006]
## Problem to solve

DevX work today skew heavily towards continuous integration, infrastructure, and general tooling; we don't really see what, for example, an engineer on the Code Intel team might see every day. That limits the impact that we have on empowering Sourcegraph dev teams to do their best work. 

## Measure of success

1. Engineers in DevX feel comfortable navigating the tooling and processes used for developing the core Sourcegraph application.
2. DevX invests towards standardization of application DX tools and libraries, and contributes towards paying down the Sourcegraph application's tech debt.
3. It is easy for engineers on other teams to reach out to DevX with feedback and feature requests for application DX.

## Solution summary

Introduce a combination of proactive refactoring across the DX ecosystem and shadow sessions with other teams in order to: 
1. Observe processes and address pain points
2. Build relationships
3. Procure feedback and ideas for improvement

Artifacts:
- [Working group: DevX cross-team learning ](https://docs.google.com/document/d/1ZoO-zySXHs7E0p98j8byfz8TZFhKHWVP8s-2IL0fUCQ/edit)

## What specific customers are we iterating on the problem and solution with?

Sourcegraph developers, especially those working on the core Sourcegraph application.

## Impact on use cases

We want to contribute towards application DX that enables developers who work on features related to Sourcegraph's use cases.

## Delivery plan

- [x] February 7: Internal team review of [Working group: DevX cross-team learning](https://docs.google.com/document/d/1ZoO-zySXHs7E0p98j8byfz8TZFhKHWVP8s-2IL0fUCQ/edit).
- [x] February 9: Open [#wg-devx-cross-team](https://sourcegraph.slack.com/archives/C032SDS6QGZ) channel for async discussion with team contacts.
- [x] February 16: Kick off agreed-upon initiatives

For more details, see the [tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30550) for this body of work.

**Comment by taylorsperry** [comment]
@bobheadxi Will you please help me flesh this out?

**Comment by bobheadxi** [comment]
@taylorsperry I've updated the issue!
