### ISSUE TITLE
Improve engineering onboarding: tooling

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#31005]
## Problem to solve

`sg` has become an integral part of engineering at Sourcegraph. There are several categories of issues that need to be resolved due to its rapid growth and adoption.

- New Sourcegraph developers end up being guinea pigs for our `sg setup` tool because we don't have an automated testing process in place, and similarly for some other features of the `sg`
- Features have been haphazardly implemented, and we may need to start implementing a better architecture internally to keep up with new features. This most noticeably applies to features that have multiple internal job/task types (`sg lint`, `sg generate`, `sg test`, etc.)
    - [`sg.config.yaml` is also nearing 1000 lines of configuration](https://github.com/sourcegraph/sourcegraph/blob/main/sg.config.yaml), which may become problematic.
- We may have outgrown the capabilities of the current CLI framework of choice, and would benefit from a more feature-rich framework that enables (for example) better feature discovery
- We have no visibility into feature usage, adoption, and feedback for `sg`
- Lots of rough edges could be improved: `sg doctor`, update experience, intro guide to `sg`, half-migrated tools - many tasks can (and are) still invoked both directly and via `sg`.

Issues with `sg` are becoming increasingly prominent and disruptive (e.g. many engineers fixing ) so it is important we tackle improvements to smooth out the experience and lay the groundwork for future investments.

## Measure of success

- `sg` features better suggestions, completions, and convenience features for improved CLI UX
- `sg` has robust internal frameworks for implementing lints, tests, and generate tasks
- `sg` has more robust features for getting started on "inner development loop": 
   - Integration testing of core features
   - Checks and generate tasks are unified across CI and local dev
- Reduced size of `sg.config.yaml`
- Feedback and analytics on `sg` usage

## Solution summary

New teammates should be set up for success on day one of the job so that they can start contributing productively as soon as possible. 

Artifacts: none

## What specific customers are we iterating on the problem and solution with?

Sourcegraph developers

## Delivery plan

- [x] Identify roadmap of action items
- [x] Make `sg` approachable as it scales: completions, suggestions, unified documentation
- [x] Make development of tasks in `sg` easy to scale: framework migration, implementation of internal frameworks for testing, code generation, and scripting tasks
- [x] Migrate some shell scripts into Go-based implementations with `sg`: checks, code generation, misc. tooling
- [x] `sg setup` gets automated testing and also supports the use case of ensuring an environment stays up to date (automated fixes)
- [x] Unify linting tasks across CI and local dev using `sg`
- [ ] `sg` exports metrics indicating usage, timing, and error trends, and metrics are viewable in OkayHQ

### Tracked issues

 

@unassigned: __9.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/33848  __3.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/37327 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35133 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33913 

Completed: __6.00d__
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/28794  __1.00d__
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/36379  __5.00d__

@bobheadxi: __28.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/33447  __1.00d__ 🕵️
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35376 

Completed: __27.00d__
- [x] (🏁 77 days ago) https://github.com/sourcegraph/sourcegraph/issues/33383  __5.00d__
- [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/pull/33817 
- [x] (🏁 75 days ago) https://github.com/sourcegraph/sourcegraph/pull/33882 
- [x] (🏁 75 days ago) https://github.com/sourcegraph/sourcegraph/pull/33917 
- [x] (🏁 75 days ago) https://github.com/sourcegraph/sourcegraph/issues/33886  __1.00d__
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/issues/33363  __1.00d__
- [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/29052 (PRs: ~[#31879](https://github.com/sourcegraph/sourcegraph/pull/31879)~) __1.00d__
- [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/33871  🕵️
- [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/33884  __3.00d__
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/28794 
- [x] (🏁 32 days ago) https://github.com/sourcegraph/sourcegraph/issues/25441 (PRs: ~[#31879](https://github.com/sourcegraph/sourcegraph/pull/31879)~) __3.00d__
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/issues/33872  __1.00d__
- [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/issues/33846  __1.00d__ 🕵️
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/35805 
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/35396 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/issues/32562  __3.00d__
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/33245  __3.00d__
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/33885  __5.00d__

@burmudar: __2.50d__

Completed: __2.50d__
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/25839  __1.00d__
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/34608  __1.50d__

@jhchabran: __1.00d__

Completed: __1.00d__
- [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/33871  🕵️
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/28794  __1.00d__
- [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/pull/37412 

@marekweb: __1.00d__

Completed: __1.00d__
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/28794  __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by taylorsperry** [comment]
@jhchabran Would you please help me flesh this out?

**Comment by bobheadxi** [comment]
Idea: expand to welcome-to-sourcegraph functionality improvements. We could target:

- `sg test`
- `sg check/lint`

^ unify across ci and local

**Comment by bobheadxi** [comment]
Scratchpad for ideas: https://docs.google.com/document/d/1NS_C3te-59P149LD_rrL1zcflNqqZOoSHVJfv8oPcqY/edit

**Comment by jhchabran** [comment]
> Reduced size of sg.config.yaml

Could you elaborate on why this is a measure of success? If this translates in more ad-hoc code for example on the Go side, I'm not sure that's an actual win, as most people are comfortable editing the config but not that much the code itself. So I'm curious about the motivations behind this reasoning, to make sure I'm not missing something 😊

**Comment by bobheadxi** [comment]
> @bobheadxi Could you elaborate on why this is a measure of success? If this translates in more ad-hoc code for example on the Go side, I'm not sure that's an actual win, as most people are comfortable editing the config but not that much the code itself.

Ah, I forgot to open an issue about this - some other approaches are better utilities within the YAML, splitting it up by team/domain, etc, though it's quite open to interpretation 

@jhchabran  and even if folks are comfortable editing the config, I doubt that will stay that way for long as we reach over 1000 lines of YAML configuration (see "Problems to Solve" - it will soon (and IMO already has) become incredibly daunting to change.

**Comment by bobheadxi** [comment]
There are two core items left here:

> sg setup gets automated testing and also supports the use case of ensuring an environment stays up to date (automated fixes)

This is almost done - we just need to merge https://github.com/sourcegraph/sourcegraph/pull/37528, replace the old `sg setup`, and do the appropriate communication/guidance!

> sg exports metrics indicating usage, timing, and error trends, and metrics are viewable in OkayHQ

We are exporting some data here, but I think [we should revisit our OkayHQ investment](https://docs.google.com/document/d/1q0HPJY_BFDnOMbf_u_TODsi4fNgl9lQANi7J-SWLBjs/edit). That said, the core of the work - frameworks for collecting data and exporting it - is already done, so switching to a new backend will be trivial (though we will lose some data unfortunately)

The remaining issues in the list are a long tail of improvements, and do not need to be part of this project.

**Comment by bobheadxi** [comment]
I'm closing this now - with the `sg setup` cutover I think we are in a good spot, and we are revisiting analytics in the coming bet.
