### ISSUE TITLE
DevX SOC 2 compliance

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#31008]
## Problem to solve

Achieving SOC2 compliance is a company-wide priority; failure to do so could cost millions of dollars in missed deals. The DevX team is responsible for the following controls: 

- **GN-98**: Sourcegraph has a formal software development life cycle methodology and supporting procedures to help manage application and infrastructure changes.
- **GN-104**: Code changes are systematically required to be peer-reviewed and approved prior to merging code into the main branch.
- **GN-105**: Application and infrastructure changes are required to undergo functional, security, unit, integration, smoke, regression, and SAST testing prior to release to production.
- **GN-106**: Sourcegraph uses a continuous integration and delivery tool to help ensure a consistent build, test and deploy process. Software changes are systematically required to complete all steps within the continuous integration tool workflow prior to production deployment.

## Measure of success

- GN-98: We have documentation that describes the SLDC in its entirety.
- GN-104: Any PR that has been merged to main without a peer review is documented.
- GN-105 and GN-106: An auditor can point to how a given PR was tested and passed CI. In the case of an exception to the normal testing process, the auditor sees documentation of the exception.  

## Solution summary

Gather information about where our process are today, identify and find solutions for gaps, and update documentation accordingly. Leverage the [DevX SOC2 documentation Notebook](https://sourcegraph.com/notebooks/Tm90ZWJvb2s6NjA=) to make it easy to find information about how Sourcegraph addresses these controls. 

Artifacts:
- [SOC2 Overview and Plan](https://docs.google.com/document/d/1u17dmidt8AUBXMzZt96aEF89aGwTJTG463fKRyaq2Ws/edit#heading=h.9b4nabkodyzw)
- [GN-98: Sourcegraph SDLC](https://docs.google.com/document/d/1NqfuxSchCtGoecMLc3-HWt7ktSLSAu-ajYBTdJnsqeU/edit#heading=h.a6t8mk9kz0e5)
- [RFC: 568 Testing process to ensure SoC2 compliance (GN-105)](https://docs.google.com/document/d/1d0o1O1ReazXKoDB_MANo1MuWfqBlgeU-5VZAAZRGamc/edit#heading=h.atzqn1hp64ln)

## What specific customers are we iterating on the problem and solution with?

Sourcegraph security and infrastructure teams

## Impact on use cases

SOC2 compliance is aligned with the overarching goal to scale our business. 

## Delivery plan

- [x] GN-98 Add complete SDLC to the [handbook](https://handbook.sourcegraph.com/departments/product-engineering/process/sdlc)
- [x] GN-106 Add documentation to our [Continuous Integration page ](https://docs.sourcegraph.com/dev/background-information/continuous_integration)that describes soft failures as temporary exceptions that result from experimental or in-progress work.
- [x] GN-105 Solicit testing process information from infrastructure teams
- [x] GN-104 and GN-105 Require all PRs to include a "Test Plan"
- [x] GN-105 Communicate new requirements to engineering
- [x] [Roll out requirements to critical repos](https://github.com/sourcegraph/sourcegraph/issues/30427)

See the [tracking issue](https://github.com/sourcegraph/sourcegraph/issues/29724) for this body of work.

**Comment by taylorsperry** [comment]
@jhchabran Will you please help me flesh this out?

**Comment by jhchabran** [comment]
@taylorsperry I'm not sure to understand what we want to cover here, do you have some examples in mind? Or are we referring to the fleshed-out list of testing techniques that were referenced in https://docs.google.com/document/d/1lqd8pMrv2oc3XxC8QxT_4aU_o4Q7FEO8OU_tkT5AEMw/edit ?

**Comment by jhchabran** [comment]
Edit, all good, the plan is accurate 👍

**Comment by jhchabran** [comment]
Update: we're waiting for feedback from the auditors.

**Comment by taylorsperry** [comment]
We've received feedback from the auditors and are moving forward with [RFC 686](https://docs.google.com/document/d/1p5_FheDnShXJ1P3gt2LWUc4tqU4zRvECnG7SZhzB398/edit#heading=h.trqab8y0kufp), which addresses GN-98 (SLDC) documentation.

**Comment by jhchabran** [comment]
See https://github.com/sourcegraph/handbook/pull/3947 for a draft impl!

**Comment by jhchabran** [comment]
See https://github.com/sourcegraph/handbook/pull/3947 for a draft impl!
