### ISSUE TITLE
SSBC-EM3.6: Last lower-risk required features changes

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#31104]
## `14d`

- [ ] Erik's API overhaul **`5d`** @eseliger
  - [ ] #33397
- [ ] Infrastructure: #35981 **`4d`** @BolajiOlajide 
- [ ] Details page: https://github.com/sourcegraph/sourcegraph/issues/36020 **`1d`** @BolajiOlajide 
- [ ] #36364
- [x] Release prep: #26144 **`3d`** @BolajiOlajide 
- [ ] [Stretch] Docs: In-app banner describing and welcoming to SSBC **`1d`**
  - [ ] **Design**: #31425
---
### Non-engineering
- [ ] Docs: #21553
- [ ] Figure out customer support strategy

**Comment by eseliger** [comment]
Everything in here is tracked outside of this EM and properly prioritized in our board. Closing.

**Comment by malomarrec** [comment]
Just pinging @chrispine given there was a "Figure out customer support strategy" here, and we're closing this issue.
