### ISSUE TITLE
SSBC goes Beta with self-hosted executors

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#31105]
We name SSBC a beta feature. It will not be behind a feature-flag by default, it will not impair existing customers using the src-cli workflow. We want every customer to be aware of it.

Depending on the outcome of dogfooding from [EM3.6](https://github.com/sourcegraph/sourcegraph/issues/31104), we should decide as a team whether or not to spend an additional sprint polishing and bugfixing or publish what we have as beta.

- [ ] Implementing QA/bug fixes **`0.5d` - `1d`**
- [ ] https://github.com/sourcegraph/sourcegraph/issues/34251 **`1d`** @courier-new 
- [x] Release prep: [Enable feature flag by default](https://github.com/sourcegraph/sourcegraph/pull/37114) **`0.5d`** @eseliger 
- [ ] #36920 @courier-new 

This will ultimately close #27841.

**Comment by malomarrec** [comment]
It's very likely we won't have any managed instance pricing by that date, due to dependencies on our accounting systems/processes.

**Comment by eseliger** [comment]
Yes, that's totally fine! The line item merely means "we are ready for questions" and if the answer is "we don't know pricing yet, reach back in x months" that's totally fine!

**Comment by malomarrec** [comment]
Suggestion: remove the item, clearly state _today_ that managed instances are not supported outside of the experimental testing stage or on a case by case.

**Comment by eseliger** [comment]
Ok, makes sense to me. Engineering question: Will this impact the feature flag state on managed instances? Or do we allow managed instance owners to still deploy executors on their own and get started with SSBC with that? Or do we say it's also on by default on those instances and they need to be patient a bit longer?

**Comment by malomarrec** [comment]
OK goal:
https://github.com/sourcegraph/sourcegraph/issues/30817

**Comment by malomarrec** [comment]
@eseliger I added making sure we also have a gat on SSBC as part of the scope

**Comment by eseliger** [comment]
only remaining item is demo video and it's tracked separately, so closing this. BETA! (not a fraternity name)
