### ISSUE TITLE
devx: Feature flags UI/UX tracking issue

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#31182]
We have a feature flag system in place that would certainly see wider adoption if its UI/UX would be improved. Particularly, toggling a feature flag [currently requires a GraphQL API call](https://docs.sourcegraph.com/dev/how-to/use_feature_flags#create-the-feature-flag-through-the-graphql-api).

It would be great if we could have a site-admin page that lists feature flags and allows updating state as well. I could imagine us being able to quickly do that from `sg` as well.

### Tracked issues

@unassigned: __4.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/32234  __3.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/32238  🐛
- [ ] https://github.com/sourcegraph/sourcegraph/issues/32929  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33470 

Completed
- [x] (🏁 103 days ago) https://github.com/sourcegraph/sourcegraph/issues/30550  __4.00d__

@bobheadxi: __4.00d__

Completed: __4.00d__
- [x] (🏁 103 days ago) https://github.com/sourcegraph/sourcegraph/issues/30550  __4.00d__

@kopancek: __3.00d__

Completed: __3.00d__
- [x] (🏁 256 days ago) https://github.com/sourcegraph/sourcegraph/issues/32233  __3.00d__

@mucles

Completed
- [x] (🏁 103 days ago) https://github.com/sourcegraph/sourcegraph/issues/30550 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by camdencheek** [comment]
Ooh, great idea to put this in `sg`. I think that would be much lower lift than a site admin page, but would be a huge QOL improvement

**Comment by stefanhengl** [comment]
@sourcegraph/dev-experience Closing this because I believe this is done. Please reopen if needed.
