### ISSUE TITLE
Tracking issue - FY23 Q2 Resource Estimator Updates

### ISSUE THREAD

**Issue by JenRed777** [sourcegraph/sourcegraph#31201]
### Plan

Our current Resource Estimator is out of date and needs some attention. We need to go through and update our current metrics as well as add any new ones that we find are relevant 

[SDD](https://docs.google.com/document/d/1dQPkU4ajp6WlgIvfSo2iYk4xgzhT1BrZ65mSGklDIuw/edit#heading=h.q983jwvomu4c) 

### Product Requirements
* Define key metrics that impact Sourcegraph performance and how resource requirements change as a result of these indicators
* Make modifications to the Resource Estimator calculator to ensure we are including all services and that it is using the most up to date data retrieved via [Resource Estimator Data](https://docs.google.com/spreadsheets/u/0/d/1N7X_OXDwKk0QSR2Ghbj7ZhjVrQXcMNj-yC8mF1amBi4/edit)
* The improved tooling should aim to be able to provide recommendations/guidance for database selection.configuration and disk guidance.
* Help to define a process for storing a centralized source of truth for internally storing customer self-hosted resource allocation and any changes over time. This should be stored in a way that easily be fed to the calculator to ensure long term accuracy

### Measure of Success:
* Reduce the number of support questions and requests related to customer resource allocation for standing up and maintaining their Sourcegraph instances. Resource estimation will be self-serve and no longer require engagement from Delivery engineering team

### Tracked issues

@unassigned

Completed
- [x] (🏁 448 days ago) https://github.com/sourcegraph/sourcegraph/issues/38853 

@abeatrix

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37569 
  - [x] (🏁 455 days ago) https://github.com/sourcegraph/sourcegraph/issues/38320 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/37572 

Completed
- [x] (🏁 475 days ago) https://github.com/sourcegraph/sourcegraph/issues/30768 
- [x] (🏁 474 days ago) https://github.com/sourcegraph/sourcegraph/pull/37653 
- [x] (🏁 469 days ago) https://github.com/sourcegraph/sourcegraph/issues/37707 
- [x] (🏁 469 days ago) https://github.com/sourcegraph/sourcegraph/issues/37338 
- [x] (🏁 469 days ago) https://github.com/sourcegraph/sourcegraph/pull/37869 
- [x] (🏁 466 days ago) https://github.com/sourcegraph/sourcegraph/issues/38029 
- [x] (🏁 455 days ago) https://github.com/sourcegraph/sourcegraph/issues/38320 
- [x] (🏁 438 days ago) https://github.com/sourcegraph/sourcegraph/pull/39707 
- [x] (🏁 355 days ago) https://github.com/sourcegraph/sourcegraph/issues/30769 

@kevinwojo

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37572 

Completed
- [x] (🏁 475 days ago) https://github.com/sourcegraph/sourcegraph/issues/30765    🏳️ [FY23 Q2 Resource Estimator](https://github.com/sourcegraph/sourcegraph/milestone/196)
- [x] (🏁 475 days ago) https://github.com/sourcegraph/sourcegraph/issues/35961

**Comment by caugustus-sourcegraph** [comment]
Related: https://github.com/sourcegraph/sourcegraph/issues/11205, this work should be captured by the above issues.

**Comment by caugustus-sourcegraph** [comment]
Potentially incorporate findings from the root cause of https://github.com/sourcegraph/customer/issues/810
