### ISSUE TITLE
Code Insights: [FE] Remove old settings api code from webapp

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#31412]
We have a lot of old code to transform data between the settings and GraphQL APIs.

We need to remove this code and update all of the types. I think with will take a good amount of work because there is no way to break this up into smaller chunks (that I can see at this time).

## To-do
- [x] https://github.com/sourcegraph/sourcegraph/pull/31670
- [x] https://github.com/sourcegraph/sourcegraph/pull/31799 @vovakulikov
- [x] https://github.com/sourcegraph/sourcegraph/pull/31826
- [x] https://github.com/sourcegraph/sourcegraph/pull/32009  @vovakulikov 
- [x] Remove setting-based API insight fields (like insight visibility which doesn't exist anymore in the GQL API)
- [x] Remove setting-based API codebase (implementation class and all related helpers) https://github.com/sourcegraph/sourcegraph/pull/32057

**Comment by unclejustin** [comment]
Note: I think we can break this up into slightly smaller PRs by first updating the stories to not rely on the settings cascade.

[PR in progress here](https://github.com/sourcegraph/sourcegraph/pull/31670).

**Comment by felixfbecker** [comment]
@sourcegraph/code-insights-frontend this is in "Done" but not closed, can it be closed? I still see two unchecked checklist items so want to confirm

**Comment by unclejustin** [comment]
@felixfbecker should have been closed. Closing now.
