### ISSUE TITLE
Improve Growth Infrastructure to Better Support Experimentation

### ISSUE THREAD

**Issue by anna-mmikhova** [sourcegraph/sourcegraph#31462]
## Problem to solve

Currently our experimentation infra is limited. Custom tooling has limited functionality and no owner to maintain/improve it. We need more sophisticated tools to iterate, test & measure impact of Growth experiments.  Ideally we'd find a 3rd party tool that could suit our requirements to reduce needed maintenance, though investing in the custom tool is also an option,

Without the infra investment we'll depend on limited functionality and error prone methods. These methods have slow deployment and release speed.  

## Measure of success
Handbook has updated, more thorough framework for experimentation. Best practices are clear. Templates exist for guiding experiment process & documenting plans. Findings are also documented in standard template and appropriately stored/tagged for easy access sin the future.

All growth team feature flags (in both cloud & on-prem deployments) are able to run off the new infrastructure (3rd party or evolved custom system).

## Solution summary

Do market research and migrate to a promising service for AB testing. Collaborate with analytics to define best practices, build templates, and publish and socialize changes in RFC/Handbook.

## What specific customers are we iterating on the problem and solution with?

This is an internal systems and processes optimization that will allow us to experiment and activate users

## Impact on use cases
This will enable us to iterate faster and build more robust and conclusive product experiments.

## Delivery plan

- [x] Evaluate whether Launch Darkly meets minimum criteria [34604](https://github.com/sourcegraph/sourcegraph/issues/34604)
- [ ] Either migrate to LD or evaluate other vendors / custom solution upgrades. See [Feature Flag vendor discussion](https://docs.google.com/document/d/1j6NMCiVM_veN6UyDVHMoYwgakX1-UxUnSCh5R3kfINU/edit#) document
    - [x] https://github.com/sourcegraph/sourcegraph/issues/35223
    - [x] https://github.com/sourcegraph/sourcegraph/issues/35222
    - [x] https://github.com/sourcegraph/sourcegraph/issues/35221
    - [x] https://github.com/sourcegraph/sourcegraph/issues/35220
- [ ] Migrate to final solution decided after technical discovery, document, and share widely with other product teams
    - [x] https://github.com/sourcegraph/sourcegraph/issues/35308
    - [ ] ...
- [ ] Collaborate with analytics to: https://github.com/sourcegraph/analytics/issues/474
    -  [ ] Build templates for *planning* experiments (including hypothesis, sampling approach, feature flag name, measurement plan, defining success, etc.
    - [ ] Best practices for monitoring & when to end
    - [ ] Evaluation methods & reporting results - includes building templates & stating where results should be stored

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.

**Comment by malomarrec** [comment]
Outdated, closing
