### ISSUE TITLE
Tracking Issue: WCAG 2.1 AA Accessibility - Auditing user journeys

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#31475]
## Problem to solve
<!-- What is the problem and why is this an important problem to solve? -->

This tracking issue reflects the **Auditing** stage of the accessibility work that began in Q1. Today, the Sourcegraph web application does not comply with current WCAG guidelines. Our ultimate goal and measure of success is to reach (and maintain) compliance by the end of FY23 (January 2023).

## Measure of success
<!-- How will we validate/verify/know that we have solved the problem? -->
Each team's user journeys have been audited per the guidance in the artifacts below. 

## Solution summary
<!-- How are we going to solve this problem? What dependencies are there? This should be a concise summary followed by a list of concrete artifacts that contain more details (for example: PDs, RFCs) -->

- Accessibility champions begin auditing user journeys within their product areas. They use [this issue template](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=&labels=accessibility%2Cwcag%2F2.1%2Cwcag%2F2.1%2Ffixing%2Cestimate%2F3d&template=accessibility_issue.yaml&title=%5BAccessibility%5D%3A+) (found in [How to conduct an accessibility audit](https://docs.sourcegraph.com/dev/background-information/web/accessibility)) to raise issues that need to be addressed. 
- Frontend Platform Team improves automated scanning by adding new routes and journeys that can be scanned by TPGi. 
- Frontend Platform Team monitors automated scans for any regressions and raises issues accordingly. 

Artifacts:
- #31200 
- https://github.com/sourcegraph/sourcegraph/issues/31476
- [Sourcegraph Accessibility Remediation Plan](https://docs.google.com/document/d/1kVinUrMukEEFfqcHS1o36ASAezHKDkSjrBiILvGuDiE/edit)
- [RFC 557: WCAG 2.1 AA Compliance Plan](https://docs.google.com/document/d/1r9W3ZvSaT_CPzzLpp0cZgcFR47Qk8pbT76ATQPiIDRk/edit)
- [Accessibility Champions](https://docs.google.com/spreadsheets/d/1j0c77t5T9hlBno_htYj2Wd3RQzE02vq70l7gQvd4DHc/edit#gid=0)
- [WCAG 2.1 AA Accessibility Project Board](https://github.com/orgs/sourcegraph/projects/238/views/1)
- [How to conduct an accessibility audit](https://docs.sourcegraph.com/dev/background-information/web/accessibility)

## What specific customers are we iterating on the problem and solution with?
<!--
Reference customers by linking to their issue in our accounts repository. DON'T REFERENCE CUSTOMERS BY NAME!

Example:
- https://github.com/sourcegraph/accounts/issues/565
- https://github.com/sourcegraph/accounts/issues/537
- https://github.com/sourcegraph/accounts/issues/580
-->
- https://github.com/sourcegraph/accounts/issues/278

## Impact on use cases

<!--
Describe how this roadmap item contributes to improving the customer experience for one or more of the 5 use cases and apply the relevant use-case/* labels to this issue.

For enablement projects that don't target a specific use case, describe how you expect this work to enable teams/projects that are focused on use cases.
-->
This work contributes to the overall effort to scale our business. 

## Delivery plan
<!--
The overall plan for how we are going to achieve this roadmap item. This should be formulated as a checklist of concrete steps that are kept up-to-date so anyone can glance at the issue description to get a sense of what we have already delivered and what remains.

Each item on this list is ideally a concrete deliverable with an estimated delivery date and owner, but we don't want false precision, so just document the plan to the best of your ability, even if you don't have all the steps yet.
-->

**Step 2: Self auditing (May, June)**
Teams have committed to the following deadlines for completing their audits: 
- [ ] Frontend Platform - May 20
- [ ] Repo Management - May 27
- [ ] Growth and Integrations - May 20
- [ ] Cloud SaaS - June 1
- [ ] Search - May 20
- [ ] Code Insights
- [ ] Batch Changes - June 28 (interweaving audits and fixes)
- [ ] Conde Intel - May 18

### Tracked issues

<!-- BEGIN WORK -->
<!-- BEGIN ASSIGNEE:  -->
@unassigned

- [ ] https://github.com/sourcegraph/about/issues/5502 
- [ ] https://github.com/sourcegraph/about/issues/5515 
- [ ] https://github.com/sourcegraph/about/issues/5516 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/34056 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/34057 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/34059 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/34060 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/34061 
- [ ] https://github.com/sourcegraph/about/issues/5517 

Completed
- [x] (🏁 537 days ago) https://github.com/sourcegraph/sourcegraph/issues/34086 
- [x] (🏁 255 days ago) https://github.com/sourcegraph/about/issues/5464 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: BolajiOlajide -->
@BolajiOlajide: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27090  __2.00d__
  - [x] (🏁 518 days ago) https://github.com/sourcegraph/sourcegraph/issues/34068  __0.50d__
  - [x] (🏁 529 days ago) https://github.com/sourcegraph/sourcegraph/issues/34069  __0.50d__
  - [x] (🏁 516 days ago) https://github.com/sourcegraph/sourcegraph/issues/34079  __0.50d__
  - [x] (🏁 477 days ago) https://github.com/sourcegraph/sourcegraph/issues/34082  __0.50d__

Completed: __2.00d__
- [x] (🏁 756 days ago) https://github.com/sourcegraph/sourcegraph/issues/24466  __2.00d__
- [x] (🏁 615 days ago) https://github.com/sourcegraph/sourcegraph/issues/27348  __2.00d__
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: LawnGnome -->
@LawnGnome: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27090  __2.00d__
  - [x] (🏁 525 days ago) https://github.com/sourcegraph/sourcegraph/issues/34081  __0.50d__
  - [x] (🏁 469 days ago) https://github.com/sourcegraph/sourcegraph/issues/34083  __0.50d__
  - [x] (🏁 469 days ago) https://github.com/sourcegraph/sourcegraph/issues/34084  __0.50d__
  - [x] (🏁 496 days ago) https://github.com/sourcegraph/sourcegraph/issues/34090  __0.50d__

Completed: __2.00d__
- [x] (🏁 756 days ago) https://github.com/sourcegraph/sourcegraph/issues/24466  __2.00d__
- [x] (🏁 615 days ago) https://github.com/sourcegraph/sourcegraph/issues/27348  __2.00d__
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: Strum355 -->
@Strum355

- [ ] https://github.com/sourcegraph/sourcegraph/issues/33514 

Completed
- [x] (🏁 518 days ago) https://github.com/sourcegraph/sourcegraph/issues/33513 
- [x] (🏁 327 days ago) https://github.com/sourcegraph/sourcegraph/issues/33515 
- [x] (🏁 327 days ago) https://github.com/sourcegraph/sourcegraph/issues/33512 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: abeatrix -->
@abeatrix


Completed
- [x] (🏁 525 days ago) https://github.com/sourcegraph/sourcegraph/issues/34053    🏳️ [Integrations 8](https://github.com/sourcegraph/sourcegraph/milestone/188)
- [x] (🏁 525 days ago) https://github.com/sourcegraph/sourcegraph/issues/34052    🏳️ [Integrations 8](https://github.com/sourcegraph/sourcegraph/milestone/188)
- [x] (🏁 525 days ago) https://github.com/sourcegraph/sourcegraph/issues/34049    🏳️ [Integrations 8](https://github.com/sourcegraph/sourcegraph/milestone/188)
- [x] (🏁 525 days ago) https://github.com/sourcegraph/sourcegraph/issues/34051    🏳️ [Integrations 8](https://github.com/sourcegraph/sourcegraph/milestone/188)
- [x] (🏁 525 days ago) https://github.com/sourcegraph/sourcegraph/issues/34050    🏳️ [Integrations 8](https://github.com/sourcegraph/sourcegraph/milestone/188)
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: adeola-ak -->
@adeola-ak: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27090  __2.00d__
  - [x] (🏁 497 days ago) https://github.com/sourcegraph/sourcegraph/issues/34070  __0.50d__
  - [x] (🏁 525 days ago) https://github.com/sourcegraph/sourcegraph/issues/34078  __0.50d__
  - [x] (🏁 460 days ago) https://github.com/sourcegraph/sourcegraph/issues/34085  __0.50d__
  - [x] (🏁 460 days ago) https://github.com/sourcegraph/sourcegraph/issues/34094  __0.50d__

Completed: __2.00d__
- [x] (🏁 756 days ago) https://github.com/sourcegraph/sourcegraph/issues/24466  __2.00d__
- [x] (🏁 615 days ago) https://github.com/sourcegraph/sourcegraph/issues/27348  __2.00d__
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: almeidapaulooliveira -->
@almeidapaulooliveira


Completed
- [x] (🏁 509 days ago) https://github.com/sourcegraph/sourcegraph/issues/34193 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: camdencheek -->
@camdencheek


Completed
- [x] (🏁 518 days ago) https://github.com/sourcegraph/sourcegraph/issues/34192 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: cesrjimenez -->
@cesrjimenez


Completed
- [x] (🏁 519 days ago) https://github.com/sourcegraph/sourcegraph/issues/33507 
- [x] (🏁 519 days ago) https://github.com/sourcegraph/sourcegraph/issues/33508 
- [x] (🏁 518 days ago) https://github.com/sourcegraph/sourcegraph/issues/33506 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: courier-new -->
@courier-new: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27090  __2.50d__
  - [x] (🏁 484 days ago) https://github.com/sourcegraph/sourcegraph/issues/34071 
  - [x] (🏁 484 days ago) https://github.com/sourcegraph/sourcegraph/issues/34072 
  - [x] (🏁 453 days ago) https://github.com/sourcegraph/sourcegraph/issues/34074 (PRs: ~[#38788](https://github.com/sourcegraph/sourcegraph/pull/38788)~) __0.50d__
  - [x] (🏁 453 days ago) https://github.com/sourcegraph/sourcegraph/issues/34075 (PRs: ~[#38788](https://github.com/sourcegraph/sourcegraph/pull/38788)~) __0.50d__
  - [x] (🏁 453 days ago) https://github.com/sourcegraph/sourcegraph/issues/34076 (PRs: ~[#38788](https://github.com/sourcegraph/sourcegraph/pull/38788)~) __0.50d__
  - [x] (🏁 453 days ago) https://github.com/sourcegraph/sourcegraph/issues/34077 (PRs: ~[#38788](https://github.com/sourcegraph/sourcegraph/pull/38788)~) __0.50d__
  - [x] (🏁 453 days ago) https://github.com/sourcegraph/sourcegraph/issues/34087 (PRs: ~[#38788](https://github.com/sourcegraph/sourcegraph/pull/38788)~) __0.50d__
  - [x] (🏁 484 days ago) https://github.com/sourcegraph/sourcegraph/issues/34093 

Completed: __3.00d__
- [x] (🏁 756 days ago) https://github.com/sourcegraph/sourcegraph/issues/24466  __2.50d__
- [x] (🏁 615 days ago) https://github.com/sourcegraph/sourcegraph/issues/27348  __2.50d__
- [x] (🏁 532 days ago) https://github.com/sourcegraph/sourcegraph/issues/34073 (PRs: ~[#34488](https://github.com/sourcegraph/sourcegraph/pull/34488)~) __0.50d__
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: efritz -->
@efritz


Completed
- [x] (🏁 519 days ago) https://github.com/sourcegraph/sourcegraph/issues/33516 
- [x] (🏁 519 days ago) https://github.com/sourcegraph/sourcegraph/issues/33518 
- [x] (🏁 519 days ago) https://github.com/sourcegraph/sourcegraph/issues/33517 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: eseliger -->
@eseliger: __1.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27090  __1.50d__
  - [x] (🏁 532 days ago) https://github.com/sourcegraph/sourcegraph/issues/34080  __0.50d__
  - [x] (🏁 523 days ago) https://github.com/sourcegraph/sourcegraph/issues/34089  __0.50d__
  - [x] (🏁 456 days ago) https://github.com/sourcegraph/sourcegraph/issues/34092  __0.50d__

Completed: __1.50d__
- [x] (🏁 756 days ago) https://github.com/sourcegraph/sourcegraph/issues/24466  __1.50d__
- [x] (🏁 615 days ago) https://github.com/sourcegraph/sourcegraph/issues/27348  __1.50d__
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: fkling -->
@fkling


Completed
- [x] (🏁 495 days ago) https://github.com/sourcegraph/sourcegraph/issues/34198 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: jasongornall -->
@jasongornall


Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: jplahn -->
@jplahn


Completed
- [x] (🏁 496 days ago) https://github.com/sourcegraph/sourcegraph/issues/33519 
- [x] (🏁 496 days ago) https://github.com/sourcegraph/sourcegraph/issues/33520 
- [x] (🏁 489 days ago) https://github.com/sourcegraph/sourcegraph/issues/33521 
- [x] (🏁 489 days ago) https://github.com/sourcegraph/sourcegraph/issues/33522 
- [x] (🏁 489 days ago) https://github.com/sourcegraph/sourcegraph/issues/33523 
- [x] (🏁 455 days ago) https://github.com/sourcegraph/sourcegraph/issues/33525 
- [x] (🏁 455 days ago) https://github.com/sourcegraph/sourcegraph/issues/33524 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: kopancek -->
@kopancek


Completed
- [x] (🏁 510 days ago) https://github.com/sourcegraph/sourcegraph/issues/34117    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 510 days ago) https://github.com/sourcegraph/sourcegraph/issues/34119    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 510 days ago) https://github.com/sourcegraph/sourcegraph/issues/34128    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34122    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34123    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34124    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34125    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34126    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34127    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34121    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34120    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34118    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34116    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34115 (PRs: ~[#35708](https://github.com/sourcegraph/sourcegraph/pull/35708)~)   🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34114    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34113    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34111    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
- [x] (🏁 499 days ago) https://github.com/sourcegraph/sourcegraph/issues/34112    🏳️ [IAM & Admin Exp 22.05.17-22.05.31](https://github.com/sourcegraph/sourcegraph/milestone/194)
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: lguychard -->
@lguychard


Completed
- [x] (🏁 495 days ago) https://github.com/sourcegraph/sourcegraph/issues/34194 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: limitedmage -->
@limitedmage


Completed
- [x] (🏁 529 days ago) https://github.com/sourcegraph/sourcegraph/issues/34188 
- [x] (🏁 529 days ago) https://github.com/sourcegraph/sourcegraph/issues/34189 
- [x] (🏁 529 days ago) https://github.com/sourcegraph/sourcegraph/issues/34190 
- [x] (🏁 529 days ago) https://github.com/sourcegraph/sourcegraph/issues/34191 
- [x] (🏁 519 days ago) https://github.com/sourcegraph/sourcegraph/issues/34658 
- [x] (🏁 509 days ago) https://github.com/sourcegraph/sourcegraph/issues/34195 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: marisak -->
@marisak


Completed
- [x] (🏁 504 days ago) https://github.com/sourcegraph/sourcegraph/issues/35142 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: novoselrok -->
@novoselrok


Completed
- [x] (🏁 509 days ago) https://github.com/sourcegraph/sourcegraph/issues/34197 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: st0nebraker -->
@st0nebraker


Completed
- [x] (🏁 475 days ago) https://github.com/sourcegraph/about/issues/5466    🏳️ [A - Sprint 7](https://github.com/sourcegraph/about/milestone/21)
- [x] (🏁 468 days ago) https://github.com/sourcegraph/about/issues/5500    🏳️ [A - Sprint 7](https://github.com/sourcegraph/about/milestone/21)
- [x] (🏁 438 days ago) https://github.com/sourcegraph/about/issues/5467    🏳️ [A - Sprint 9](https://github.com/sourcegraph/about/milestone/23)
- [x] (🏁 425 days ago) https://github.com/sourcegraph/about/issues/5503    🏳️ [A - Sprint 10](https://github.com/sourcegraph/about/milestone/24)
- [x] (🏁 368 days ago) https://github.com/sourcegraph/about/issues/5519    🏳️ [A - Sprint 14](https://github.com/sourcegraph/about/milestone/28)
- [x] (🏁 368 days ago) https://github.com/sourcegraph/about/issues/5518    🏳️ [A - Sprint 14](https://github.com/sourcegraph/about/milestone/28)
- [x] (🏁 255 days ago) https://github.com/sourcegraph/about/issues/5501 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: tjkandala -->
@tjkandala


Completed
- [x] (🏁 490 days ago) https://github.com/sourcegraph/sourcegraph/issues/34055    🏳️ [Integrations 10](https://github.com/sourcegraph/sourcegraph/milestone/193)
- [x] (🏁 468 days ago) https://github.com/sourcegraph/sourcegraph/issues/34054    🏳️ [Integrations 10](https://github.com/sourcegraph/sourcegraph/milestone/193)
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: umpox -->
@umpox


Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: unclejustin -->
@unclejustin


Completed
- [x] (🏁 391 days ago) https://github.com/sourcegraph/sourcegraph/issues/33494    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 390 days ago) https://github.com/sourcegraph/sourcegraph/issues/33501    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 386 days ago) https://github.com/sourcegraph/sourcegraph/issues/33495    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
- [x] (🏁 385 days ago) https://github.com/sourcegraph/sourcegraph/issues/33499    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: varungandhi-src -->
@varungandhi-src


Completed
- [x] (🏁 494 days ago) https://github.com/sourcegraph/sourcegraph/issues/33509 
- [x] (🏁 492 days ago) https://github.com/sourcegraph/sourcegraph/issues/33511 
- [x] (🏁 492 days ago) https://github.com/sourcegraph/sourcegraph/issues/33510 
- [x] (🏁 492 days ago) https://github.com/sourcegraph/sourcegraph/issues/34448 
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: vovakulikov -->
@vovakulikov


Completed
- [x] (🏁 469 days ago) https://github.com/sourcegraph/sourcegraph/issues/33504    🏳️ [Insights iteration 21](https://github.com/sourcegraph/sourcegraph/milestone/163)
- [x] (🏁 469 days ago) https://github.com/sourcegraph/sourcegraph/issues/33503    🏳️ [Insights iteration 21](https://github.com/sourcegraph/sourcegraph/milestone/163)
- [x] (🏁 390 days ago) https://github.com/sourcegraph/sourcegraph/issues/33492 
- [x] (🏁 385 days ago) https://github.com/sourcegraph/sourcegraph/issues/33493    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
- [x] (🏁 384 days ago) https://github.com/sourcegraph/sourcegraph/issues/33497    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
- [x] (🏁 384 days ago) https://github.com/sourcegraph/sourcegraph/issues/33502    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
<!-- END ASSIGNEE -->

<!-- BEGIN ASSIGNEE: zlonko -->
@zlonko


Completed
- [x] (🏁 482 days ago) https://github.com/sourcegraph/about/issues/5465    🏳️ [A - Sprint 6](https://github.com/sourcegraph/about/milestone/20)
<!-- END ASSIGNEE -->
<!-- END WORK -->

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
