### ISSUE TITLE
Tracking Issue: Consolidation of frontend test frameworks

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#31707]
### Plan

Most of our tests (all of our unit tests) run through `jest`. All tests that use Puppeteer run through `mocha`.

We should migrate our `mocha` tests to `jest` because:
- Having a single test framework will improve DX and productivity
- It will help us avoid cross-framework bugs which are difficult to debug and track. Example: https://github.com/sourcegraph/sourcegraph/pull/31397
- `jest` is a library with greater usage and, generally, better support with different tooling
- The vast majority of our tests use `jest`, and we haven't had any major complaints about it in recent times.

**Note:** We previous had some complaints about `jest`. I investigated them in this issue: https://github.com/sourcegraph/sourcegraph/issues/31630. I found that there wasn't anything major that should block us in this migration.

### Tracked issues

@gitstart-sourcegraph: __8.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/31708  __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/31709  __3.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/31710  __3.00d__

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555  __8.00d__
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714  __8.00d__
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702  __8.00d__
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682  __8.00d__
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354  __8.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
