### ISSUE TITLE
3.38.0 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#31769]
# 3.38.0 managed instances upgrade

These [managed instances](../../cloud/delivery/managed/index.md) upgrades are scheduled for **[Mar 21, 2022, 6:00 PM (UTC)](https://time.is/1800_21_Mar_2022_in_UTC?One%20working%20day%20after%203.38%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../cloud/delivery/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.
- [x] Upgrade [insightstest.sourcegraph.com](https://insightstest.sourcegraph.com/)

## Upgrade customer managed instances

- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/6857
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/605
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5057
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/537

---

Also see [3.38.0 release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/31768)

**Comment by camdencheek** [comment]
Superseded by #32837
