### ISSUE TITLE
3.3 Plan for Sentry extension

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#3177]
The focus for the 3.3 release cycle will be getting the Sentry extension working 100% for Go and then adding support for the other primary languages.

Sentry repo: **WIP**: https://github.com/sourcegraph/sourcegraph-sentry

- [x] Add codecov to sourcegraph-sentry repo
- [ ] **Node.js (TypeScript/JavaScript):** Sentry extension renders line decorations with "View logs in Sentry >>" for lines that resemble log print statements that link to the matching live logs on Sentry.
    - [x] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [x] Link to Sourcegraph.com file/line where decoration should appear
        - [x] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [x] Implement log statement are detection using hard coded logic for this language.
        - [ ] 80% test coverage
        - [x] Merge the README PR from the first step. The links should now work.
- [ ] If user input is needed to configure the Sentry account (e.g., needing the project ID to construct the URLs), a progressive flow to complete setup:
    - [x] Line decorations are still shown with a dimmer color and read "Missing Sentry [missing config]"
    - [x] An editor/title action to "Set Sentry [missing config]" is shown that prompts the user for the value
    - [x] If the Sentry organization is missing in the user settings, a link to the user's setting `$SOURCEGRAPH_URL/users/$USER/settings` is rendered with the title action to "Set Sentry organization".
	- [ ] Also check for user errors e.g. if there is no json added to settings for the Sentry extension. Handle like missing configurations.
    - [ ] 80% test coverage
- [ ] "(Show/Hide) log links" action in command palette and a Sentry icon action item on the editor/title
    - [ ] Implementation done
    - [ ] 80% test coverage
    - [ ] Update the README to document this.
- [ ] **Go:** Sentry extension renders line decorations with "View logs in Sentry >>" for lines that resemble log print statements that link to the matching live logs on Sentry.
    - [x] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [x] Link to Sourcegraph.com file/line where decoration should appear
        - [x] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [x] Implement log statement are detection using hard coded logic for this language.
        - [ ] 80% test coverage
        - [x] Merge the README PR from the first step. The links should now work.
- [x] **Python:** Sentry extension renders line decorations with "View logs in Sentry >>" for lines that resemble log print statements that link to the matching live logs on Sentry.
    - [x] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [x] Link to Sourcegraph.com file/line where decoration should appear
        - [x] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement log statement are detection using hard coded logic for this language.
        - [ ] 80% test coverage
        - [x] Merge the README PR from the first step. The links should now work.
- [x] **Java:** Sentry extension renders line decorations with "View logs in Sentry >>" for lines that resemble log print statements that link to the matching live logs on Sentry.
    - [x] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [x] Link to Sourcegraph.com file/line where decoration should appear
        - [x] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement log statement are detection using hard coded logic for this language.
        - [ ] 80% test coverage
        - [x] Merge the README PR from the first step. The links should now work.
- [ ] The README.md file and other information shown on the extension's registry page (e.g., https://sourcegraph.com/extensions/sourcegraph/sentry) is informative and up to date with respect to:
	- [ ] Features
	- [x] Usage instructions
	- [ ] Compatibility (which versions of Sourcegraph, which code hosts, and which forms of the external service (e.g., Sentry cloud-hosted vs. Sentry self-hosted))
- [ ] If the extension is mentioned on the Sentry's website, that material is also kept up to date with what we have on our own site.

Customers (not exhaustive):

- https://app.hubspot.com/contacts/2762526/company/419771425 
- https://app.hubspot.com/contacts/2762526/company/693777200

**Comment by felixfbecker** [comment]
👍 for the 80% test coverage goal

**Comment by slimsag** [comment]
Closing since the 3.3 window has closed.

**Comment by nicksnyder** [comment]
@vanesa Can you create a new issue "3.4 Plan for Sentry extension" that includes remaining necessary work (i.e. unchecked boxes on this issue)?
