### ISSUE TITLE
Helm GA: Tracking issue

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#31821]
### Tracked issues

@unassigned

Completed
- [x] (🏁 66 days ago) https://github.com/sourcegraph/sourcegraph/issues/31888 
- [x] (🏁 66 days ago) https://github.com/sourcegraph/sourcegraph/issues/29546 
- [x] (🏁 65 days ago) https://github.com/sourcegraph/sourcegraph/issues/31835 
- [x] (🏁 64 days ago) https://github.com/sourcegraph/sourcegraph/issues/31874 
- [x] (🏁 64 days ago) https://github.com/sourcegraph/sourcegraph/issues/31875 
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/32016 
- [x] (🏁 59 days ago) https://github.com/sourcegraph/sourcegraph/issues/32181 
- [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/issues/32176 
- [x] (🏁 45 days ago) https://github.com/sourcegraph/sourcegraph/issues/32206 
- [x] (🏁 38 days ago) https://github.com/sourcegraph/sourcegraph/issues/32479 

@caugustus-sourcegraph

Completed
- [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/issues/32204 
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/issues/27759 
- [x] (🏁 36 days ago) https://github.com/sourcegraph/sourcegraph/issues/33156 
- [x] (🏁 36 days ago) https://github.com/sourcegraph/sourcegraph/issues/32748 
- [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/issues/32694 
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/32177 
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/33679 
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/32747 

@dan-mckean

Completed
- [x] (🏁 3 days ago) https://github.com/sourcegraph/sourcegraph/issues/33179 

@kevinwojo

Completed
- [x] (🏁 16 days ago) https://github.com/sourcegraph/sourcegraph/issues/33396 

@michaellzc

Completed
- [x] (🏁 64 days ago) https://github.com/sourcegraph/sourcegraph/issues/31016 
- [x] (🏁 64 days ago) https://github.com/sourcegraph/sourcegraph/issues/31889 
- [x] (🏁 58 days ago) https://github.com/sourcegraph/sourcegraph/issues/32175 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/issues/32095 
- [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/issues/32214 
- [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/issues/32178 
- [x] (🏁 52 days ago) https://github.com/sourcegraph/sourcegraph/issues/27760 
- [x] (🏁 51 days ago) https://github.com/sourcegraph/sourcegraph/issues/23088 
- [x] (🏁 49 days ago) https://github.com/sourcegraph/customer/issues/728  👩
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/issues/32700 
- [x] (🏁 45 days ago) https://github.com/sourcegraph/sourcegraph/issues/32777 
- [x] (🏁 43 days ago) https://github.com/sourcegraph/sourcegraph/issues/32791 
- [x] (🏁 37 days ago) https://github.com/sourcegraph/sourcegraph/issues/32179 
- [x] (🏁 36 days ago) https://github.com/sourcegraph/sourcegraph/issues/33188 
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/32180 

@mucles

Completed
- [x] (🏁 66 days ago) https://github.com/sourcegraph/sourcegraph/issues/31887

**Comment by michaellzc** [comment]
During the knowledge sharing call https://sourcegraph.slack.com/archives/C02E07JDBD3/p1647029471695489

Dax brought up a good point, we can potentially use Helm as an opportunity solve a lot of historical problems, tech debts, and bad practices from the `deploy-sourcegraph` deployment. Given it's beta and we have no official support, this is pretty much the only chance we get to do the right thing for good.

For example:

- https://github.com/sourcegraph/sourcegraph/issues/23088
- https://docs.google.com/document/d/1chs2YaI4pCg9meLnt6WFbdj2nxCY_r1U8TTSKOyPmDA/edit
