### ISSUE TITLE
WIP: code intel panel improvements tracking issue

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#31953]
### Goal

Be aligned on the design and implementation efforts following the better code intel experiment #30227. This tracking issue aims to: 

- Communicate status of design support and visual design prior to implementation 
- Communicate status of front-end implementation after designs are ready
- Create a high-level view of our phased plan

### Plan

[3 phase plan for an improved reference panel](https://docs.google.com/document/d/1E_6hgnFlRutelU4QI8PtFfOrxrq_wjw0UMbMMtAuQ4g/edit#). This tracking issue will track progress towards the first two phases. "Phase" 3 will be tracked in individual feature issues. 

#### Phase 1

- [ ] Support large list of references (👈  @jjinnii is working on this)
- [ ] Unified list for references and implementations (👈  @jjinnii is working on this)
- [ ] Ability to filter in reference panel 

#### Phase 2

- [ ] Keep 'References' panel open after clicking on one reference [#13722](https://github.com/sourcegraph/sourcegraph/issues/13722)
- [ ] Preview references/implementations in a side panel 
- [ ] User testing for new code intel panel behavior

**Comment by jjinnii** [comment]
@macraig @mrnugget I can't remember where the "unified" list of references/implementations came from. Is there a technical reason for needing to combine the ref/implementation tabs? Or (and please forgive my limited understanding of implementations here 😅 ), is there some benefit to the user/does it make more sense for it to be a combined list?

**Comment by mrnugget** [comment]
> I can't remember where the "unified" list of references/implementations came from. Is there a technical reason for needing to combine the ref/implementation tabs?

I think it's the other way around: we have separate tabs because of technical reasons, not because it makes the most sense from a user's perspective. The extension API doesn't allow us to have multiple lists (or any other content alongside a list) in a single tab, so the only way to implement "implementations" was to create a new tab.

But I think the experience on Google Code Search ([example link](https://cs.opensource.google/go/go/+/master:src/io/multi.go;bpv=1;bpt=1)) is far better:

<img width="971" alt="screenshot_2022-03-01_09 55 41@2x" src="https://user-images.githubusercontent.com/1185253/156137168-890be891-23aa-46e2-9e6a-f54c07022373.png">

You get a single view of all the relevant references/implementations ("Extended by")/definitions etc. You can filter them all at once. That often gets you closer to what you want than having to navigate (and filter and paginate and scroll) two lists. Especially if you're not really sure what you're looking for: "am I looking for an implementation or a reference?"

Sometimes it's clear cut and you know you only want a reference ("where is this interface used"), sometimes you know you only want implementations ("who implements this interface"), but sometimes (and I think this is more common) you want to get a lay of the land and see "how and where is this used" (meaning: implemented and referenced).

That's why I implemented it as a single list: I personally think it gets me closer to what I want faster, requires less clicks, less reloads, less pagination, etc.
