### ISSUE TITLE
Replace "SSBC" by "running batch changes server side" in docs and in-product messaging

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#32126]
After [syncing](https://docs.google.com/document/d/1AhuTd7NtzaBLu3CBpr-lr7JO_0Sc-yj6kTRW_9j8RYU/edit#) with PMM, it sounds like we have an agreement for how to name and introduce running batch changes server-side:

- Instead of talking about Server-Side Batch Changes, we talk about running a batch change server-side. There is no feature name. Instead, it is an implementation detail of batch changes provided as an option.
  - Example usage: “Run a batch change locally with src-cli, or setup executors to run a batch change using server-side execution”
- We use the run verb
- We don’t launch it as a feature, but we announce it as a capability: “Batch Changes can now scale to thousands of repositories, by running batch changes server-side”

**TODO**

- [ ] remove "server side batch changes" from the docs
- [ ] remove "server side batch changes" from roadmap
- [ ] check for "server side batch changes" in-product

**Comment by chrispine** [comment]
We will probably also want to change the src-cli command name
