### ISSUE TITLE
Tracking Issue: Wildcard V3

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#32121]
### Plan

Placeholder for new work required in Wildcard V3

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/29035 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/32127 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/32128 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35689 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35690 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36080 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27683 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27684 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27704 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27715 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27716 
- [x] https://github.com/sourcegraph/sourcegraph/issues/27705 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/27706 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/27707 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

@gitstart-sourcegraph

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
