### ISSUE TITLE
Growth and Integrations okr/2160-account-setups Tracking issue

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#32296]
### Plan

OKR: [>2160 individual account setups for self-hosted installs in Q1](https://github.com/sourcegraph/product-engineering-tracker/issues/68)

### Tracked issues

@philipp-spiess: __13.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/31214  __10.00d__   🏳️ [G&I Iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/178)

Completed: __3.50d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/31215  __1.00d__
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/31778  __0.50d__   🏳️ [G&I Iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/178)
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/31780  __2.00d__   🏳️ [G&I Iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/178)

@rrhyne: __13.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/31214  __10.00d__   🏳️ [G&I Iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/178)

Completed: __3.50d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/31215  __1.00d__
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/31778  __0.50d__   🏳️ [G&I Iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/178)
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/31780  __2.00d__   🏳️ [G&I Iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/178)

@slimsag: __24.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/31214  __10.00d__   🏳️ [G&I Iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/178)

Completed: __14.00d__
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/31446  __0.50d__   🏳️ [G&I Iteration 3](https://github.com/sourcegraph/sourcegraph/milestone/177)
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/31278  __2.00d__   🏳️ [G&I Iteration 3](https://github.com/sourcegraph/sourcegraph/milestone/177)
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/31279  __0.50d__   🏳️ [G&I Iteration 3](https://github.com/sourcegraph/sourcegraph/milestone/177)
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/31444  __0.50d__   🏳️ [G&I Iteration 3](https://github.com/sourcegraph/sourcegraph/milestone/177)
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/31445  __0.50d__   🏳️ [G&I Iteration 3](https://github.com/sourcegraph/sourcegraph/milestone/177)
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/31447  __0.50d__   🏳️ [G&I Iteration 3](https://github.com/sourcegraph/sourcegraph/milestone/177)
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/31277  __3.00d__   🏳️ [G&I Iteration 3](https://github.com/sourcegraph/sourcegraph/milestone/177)
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/31280  __0.50d__   🏳️ [G&I Iteration 3](https://github.com/sourcegraph/sourcegraph/milestone/177)
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/31215  __1.00d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/31216  __2.00d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/31744  __0.50d__
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/31778  __0.50d__   🏳️ [G&I Iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/178)
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/31780  __2.00d__   🏳️ [G&I Iteration 4](https://github.com/sourcegraph/sourcegraph/milestone/178)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
