### ISSUE TITLE
Repo Management: First-class Gerrit Support Tracking issue

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#32492]
### Tracked issues

@unassigned: __12.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/32494  __10.00d__
- [x] https://github.com/sourcegraph/sourcegraph/issues/35748 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35901  __2.00d__

@mollylogue: __7.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/35744  __4.00d__

Completed: __3.00d__
- [x] (🏁 412 days ago) https://github.com/sourcegraph/sourcegraph/issues/35743  __3.00d__

@varsanojidan: __23.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/32490  __3.00d__ 🕵️
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35746  __4.00d__

Completed: __16.00d__
- [x] (🏁 455 days ago) https://github.com/sourcegraph/sourcegraph/issues/32493  __10.00d__
- [x] (🏁 433 days ago) https://github.com/sourcegraph/sourcegraph/issues/32495  __3.00d__ 🕵️
- [x] (🏁 400 days ago) https://github.com/sourcegraph/sourcegraph/issues/35747  __3.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by mrnugget** [comment]
Implemented as part of https://github.com/sourcegraph/pr-faqs/issues/41
