### ISSUE TITLE
Repo Management Debt Tracking issue

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#32618]
### Tracked issues

@unassigned: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/23676  🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/45197  __3.00d__ 🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/45770  🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/28532 (PRs: ~[#44273](https://github.com/sourcegraph/sourcegraph/pull/44273)~, ~[#44274](https://github.com/sourcegraph/sourcegraph/pull/44274)~, ~[#45955](https://github.com/sourcegraph/sourcegraph/pull/45955)~, ~[#45956](https://github.com/sourcegraph/sourcegraph/pull/45956)~) 🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/49194  🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/49650  🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/49671  🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/44348  🐛🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/47735  🐛🧶

Completed
- [x] (🏁 571 days ago) https://github.com/sourcegraph/sourcegraph/issues/32380  🧶
- [x] (🏁 509 days ago) https://github.com/sourcegraph/sourcegraph/issues/33997  🧶
- [x] (🏁 454 days ago) https://github.com/sourcegraph/sourcegraph/issues/20127  🧶
- [x] (🏁 447 days ago) https://github.com/sourcegraph/sourcegraph/issues/27916 
- [x] (🏁 412 days ago) https://github.com/sourcegraph/sourcegraph/issues/15385  🧶
- [x] (🏁 412 days ago) https://github.com/sourcegraph/sourcegraph/issues/27803  🧶
- [x] (🏁 389 days ago) https://github.com/sourcegraph/sourcegraph/issues/17979  🧶
- [x] (🏁 350 days ago) https://github.com/sourcegraph/sourcegraph/issues/38089  🧶
- [x] (🏁 325 days ago) https://github.com/sourcegraph/sourcegraph/issues/44009  🧶
- [x] (🏁 290 days ago) https://github.com/sourcegraph/sourcegraph/issues/17911  🧶
- [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/issues/42468  🧶
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/19443  🧶
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/40431  🧶
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/9663  🧶

@DaivikDave: __0.50d__

Completed: __0.50d__
- [x] (🏁 412 days ago) https://github.com/sourcegraph/sourcegraph/issues/33099  __0.50d__ 🧶

@cbart

Completed
- [x] (🏁 321 days ago) https://github.com/sourcegraph/sourcegraph/issues/19096 (PRs: ~[#44311](https://github.com/sourcegraph/sourcegraph/pull/44311)~) 🧶

@indradhanush: __5.00d__

Completed: __5.00d__
- [x] (🏁 606 days ago) https://github.com/sourcegraph/sourcegraph/pull/30615 🧶
- [x] (🏁 342 days ago) https://github.com/sourcegraph/sourcegraph/issues/42229  🧶
- [x] (🏁 335 days ago) https://github.com/sourcegraph/sourcegraph/pull/43670 🧶
- [x] (🏁 335 days ago) https://github.com/sourcegraph/sourcegraph/pull/43737 🧶
- [x] (🏁 321 days ago) https://github.com/sourcegraph/sourcegraph/pull/44264 🧶
- [x] (🏁 301 days ago) https://github.com/sourcegraph/sourcegraph/pull/45163 🧶
- [x] (🏁 273 days ago) https://github.com/sourcegraph/sourcegraph/issues/44683  __5.00d__ 🧶

@mollylogue

Completed
- [x] (🏁 668 days ago) https://github.com/sourcegraph/sourcegraph/issues/27422  🧶
- [x] (🏁 462 days ago) https://github.com/sourcegraph/sourcegraph/issues/33280  🧶
- [x] (🏁 350 days ago) https://github.com/sourcegraph/sourcegraph/issues/42942  🧶

@mrnugget

Completed
- [x] (🏁 312 days ago) https://github.com/sourcegraph/sourcegraph/issues/44146  🧶

@ryanslade: __3.00d__

Completed: __3.00d__
- [x] (🏁 511 days ago) https://github.com/sourcegraph/sourcegraph/issues/35046  🧶
- [x] (🏁 462 days ago) https://github.com/sourcegraph/sourcegraph/issues/33280  🧶
- [x] (🏁 440 days ago) https://github.com/sourcegraph/sourcegraph/issues/38235  🧶
- [x] (🏁 413 days ago) https://github.com/sourcegraph/sourcegraph/issues/19878  __1.00d__ 🧶
- [x] (🏁 402 days ago) https://github.com/sourcegraph/sourcegraph/issues/33890  __1.00d__ 🧶
- [x] (🏁 378 days ago) https://github.com/sourcegraph/sourcegraph/issues/39494  __1.00d__ 🧶
- [x] (🏁 353 days ago) https://github.com/sourcegraph/sourcegraph/issues/42932  🧶
- [x] (🏁 325 days ago) https://github.com/sourcegraph/sourcegraph/pull/44273 🧶
- [x] (🏁 325 days ago) https://github.com/sourcegraph/sourcegraph/pull/44274 🧶
- [x] (🏁 325 days ago) https://github.com/sourcegraph/sourcegraph/pull/44289 🧶
- [x] (🏁 262 days ago) https://github.com/sourcegraph/sourcegraph/issues/46331  🧶
- [x] (🏁 252 days ago) https://github.com/sourcegraph/sourcegraph/issues/46562  🧶

@sashaostrikov

- [ ] https://github.com/sourcegraph/sourcegraph/issues/46468 
  - [x] (🏁 182 days ago) https://github.com/sourcegraph/sourcegraph/pull/50228 🧶

Completed
- [x] (🏁 479 days ago) https://github.com/sourcegraph/sourcegraph/issues/36774  🧶
- [x] (🏁 476 days ago) https://github.com/sourcegraph/sourcegraph/issues/19356  🧶
- [x] (🏁 462 days ago) https://github.com/sourcegraph/sourcegraph/issues/33280  🧶
- [x] (🏁 459 days ago) https://github.com/sourcegraph/sourcegraph/issues/33232  🧶
- [x] (🏁 353 days ago) https://github.com/sourcegraph/sourcegraph/issues/42943  🧶
- [x] (🏁 353 days ago) https://github.com/sourcegraph/sourcegraph/issues/42944  🧶
- [x] (🏁 350 days ago) https://github.com/sourcegraph/sourcegraph/issues/42941 (PRs: ~[#43025](https://github.com/sourcegraph/sourcegraph/pull/43025)~) 🧶
- [x] (🏁 325 days ago) https://github.com/sourcegraph/sourcegraph/issues/43221 (PRs: ~[#44283](https://github.com/sourcegraph/sourcegraph/pull/44283)~) 🧶
- [x] (🏁 325 days ago) https://github.com/sourcegraph/sourcegraph/issues/44291 (PRs: ~[#44293](https://github.com/sourcegraph/sourcegraph/pull/44293)~) 🧶
- [x] (🏁 290 days ago) https://github.com/sourcegraph/sourcegraph/issues/39593 (PRs: ~[#45767](https://github.com/sourcegraph/sourcegraph/pull/45767)~) 🧶
- [x] (🏁 284 days ago) https://github.com/sourcegraph/sourcegraph/issues/44782 (PRs: ~[#45905](https://github.com/sourcegraph/sourcegraph/pull/45905)~) 🧶
- [x] (🏁 283 days ago) https://github.com/sourcegraph/sourcegraph/pull/45955 🧶
- [x] (🏁 283 days ago) https://github.com/sourcegraph/sourcegraph/pull/45956 🧶
- [x] (🏁 187 days ago) https://github.com/sourcegraph/sourcegraph/pull/50051 🧶
- [x] (🏁 182 days ago) https://github.com/sourcegraph/sourcegraph/pull/50228 🧶

@varsanojidan

Completed
- [x] (🏁 539 days ago) https://github.com/sourcegraph/sourcegraph/issues/33172  🧶
- [x] (🏁 74 days ago) https://github.com/sourcegraph/sourcegraph/issues/33496  🧶

@vrto

Completed
- [x] (🏁 462 days ago) https://github.com/sourcegraph/sourcegraph/issues/33280  🧶

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
