### ISSUE TITLE
VSCE: Post-release cleanup

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#32674]
### Context

Due to time constraints, we did most v1 development for the VS Code extension on a large feature branch ([`tjk/vsce-search-ui`](https://github.com/sourcegraph/sourcegraph/tree/tjk/vsce-search-ui)). Subsequent bug fixes and the first few (manual) releases have been made on this branch.

Now that I've returned from a few weeks off/at low capacity, I'm working on cleaning up the mess so we can do iterative development with automated testing and releases. This is an umbrella issue to track this effort.

### Work

- [x] Rebase `tjk/vsce-search-ui` onto `main`
- [x] Add `client/vscode` directory to `codecov.yml` `ignore:` (PR #32676)
  - Note: remove after adding test infrastructure
- [x] Update developer documentation (PR #32678)
- [x] Create PRs for `tjk/vsce-search-ui` changes made in packages other than `client/vscode` for ease of review/testing (isolate effect of changes to web app).
  - [x] `SearchSidebar`: `forceButton` prop for search type links (PR: #32688)
  - [x] `SearchBox`: `setEditor` prop for focus (PR: #32693)
  - [x] Search results: `onSelect` prop to attach callback to file matches, etc.
    - [x] Should include fix for #30585 
    - Note: fixed in feature branch
   - [x] `StreamingSearchResultsList` props (PR: #33618)
- [x] Once dependent PRs are merged, rebase `tjk/vsce-search-ui` again. Thoroughly test VS Code extension build for regressions, then merge into `main`
- [ ] Implement automated testing (#26453)
  - [x] Add smoke test to ensure the extension compiles so that we have some protection while coming up with good infrastructure (good thinking @philipp-spiess!) 
  - [ ] Remove `client/vscode` directory from `codecov.yml` `ignore:`
- [x] Implement automated releases (#26437)
- [x] Delete prototype branches/PRs

**Comment by philipp-spiess** [comment]
Only the codecov issues is outstanding but that's not needed so we're closing this.
