### ISSUE TITLE
3.39.0 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#32837]
# 3.39.0 managed instances upgrade

These [managed instances](../../cloud/delivery/managed/index.md) upgrades are scheduled for **[Apr 21, 2022, 6:00 PM (UTC)](https://time.is/1800_21_Apr_2022_in_UTC?One%20working%20day%20after%203.39%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../cloud/delivery/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.

## Upgrade customer managed instances

- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/6857
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/605
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5057
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/537

---

Also see [3.39.0 release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/32836)

**Comment by keegancsmith** [comment]
@michaellzc you unassigned me. Does this mean someone on delivery will take care of this?

**Comment by camdencheek** [comment]
Superseded by #33458

**Comment by michaellzc** [comment]
> @michaellzc you unassigned me. Does this mean someone on delivery will take care of this?

@keegancsmith yes

this issue is intended for Delivery (or whoever owns MI in the future) to track MI upgrades.

**Comment by caugustus-sourcegraph** [comment]
Before this work can be done, we need to update all the existing MI's to reference the new database config files:

https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/399 for an example / the template updates, or https://github.com/sourcegraph/deploy-sourcegraph-managed/commit/a7fcd96b33f1685c917634ff2e917f84ec95bc88 for what was already done in dev.

**Comment by keegancsmith** [comment]
Superseded by #34256

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by michaellzc** [comment]
@michaellzc:
`dev`, https://github.com/sourcegraph/accounts/issues/528 - https://github.com/sourcegraph/accounts/issues/542 (rv)

@mucles 
https://github.com/sourcegraph/accounts/issues/542 (rv2) - https://github.com/sourcegraph/accounts/issues/547

@filiphaftek 
https://github.com/sourcegraph/accounts/issues/8288 - https://github.com/sourcegraph/accounts/issues/8285

@sanderginn 
https://github.com/sourcegraph/accounts/issues/581 - https://github.com/sourcegraph/accounts/issues/5057

anyone: https://github.com/sourcegraph/accounts/issues/537, demo

**Comment by Joelkw** [comment]
@michaellzc @mucles @filiphaftek [please see this slack message](https://sourcegraph.slack.com/archives/C02KX975BDG/p1650943380976359) – we may need a patch release and don't want you to have to upgrade these twice (or upgrade some of these to buggy versions, as noted in that post).

**Comment by coury-clark** [comment]
Superseded by #34546

**Comment by filiphaftek** [comment]
@michaellzc should we close this in favour of [3.39.1](https://github.com/sourcegraph/sourcegraph/issues/34546)?
