### ISSUE TITLE
3.6 plan for Datadog extension

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#3297]
The focus for the 3.5 release cycle is to get the Datadog extension working 100% for Python, Go, Node.js, Java.

WIP: https://github.com/sourcegraph/sourcegraph-datadog-metrics

- [ ] Update this checklist with any unfinished work from https://github.com/sourcegraph/sourcegraph/issues/3177
- [ ] Rename repo and extension from sourcegraph-datadog-metrics to sourcegraph-datadog
- [ ] Add codecov to sourcegraph-datadog repo
- [ ] **Python**
    - [x] Datadog extension renders line decorations with "View metric (Datadog) >>" for lines that resemble metrics calls that link to the most relevant page on Datadog.
        - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
            - [x] Link to Sourcegraph.com file/line where decoration should appear
            - [x] Link to GitHub.com file/line where decoration should appear
            - [ ] Link to GitHub.com PR diff file/line where decoration should appear
        - [ ] Implement line decorations that can be detected by looking at the single line; i.e., simply without needing to parse/analyze multiple lines or multiple files.
            - [ ] 80% test coverage
            - [ ] Merge the README PR from the first step. The links should now work.
    - [ ] Datadog extension renders line decorations with "Live traces (Datadog) >>" for lines that resemble traces (or are known to define a span) that link to the most relevant page on Datadog
        - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
            - [ ] Link to Sourcegraph.com file/line where decoration should appear
            - [ ] Link to GitHub.com file/line where decoration should appear
            - [ ] Link to GitHub.com PR diff file/line where decoration should appear
        - [ ] Implement line decorations that can be detected by looking at the single line; i.e., simply without needing to parse/analyze multiple lines or multiple files.
            - [ ] 80% test coverage
            - [ ] Merge the README PR from the first step. The links should now work.
            - [ ] Verify that the extension can detect all spans/traces defined in https://github.com/DataDog/trace-examples
- [ ] "(Show/Hide) metrics decorations" action in command palette
    - [ ] Implementation done
    - [ ] 80% test coverage
    - [ ] Update the README to document this.
- [ ] "(Show/Hide) trace decorations" action in command palette
    - [ ] Implementation done
    - [ ] 80% test coverage
    - [ ] Update the README to document this.
- [ ] "(Show/Hide) all decorations" action in command palette and a Datadog icon action item on the editor/title
    - [ ] Implementation done
    - [ ] 80% test coverage
    - [ ] Update the README to document this.
- [ ] If user input is needed to configure the Datadog account (e.g., needing the account ID to construct the URLs), a progressive flow to complete setup:
    - [ ] Line decorations are still shown with a dimmer color and read "Missing Datadog (whatever)" ([see LightStep example](https://sourcegraph.com/github.com/sourcegraph/sourcegraph-lightstep@779b2029df916f7f8eaa60b09819aea1938b8d08/-/blob/src/extension.ts#L51-56))
    - [ ] An editor/title action to "Set Datadog (whatever)" is shown that prompts the user for the value
- [ ] **Go**
    - [ ] Datadog extension renders line decorations with "View metric (Datadog) >>" for lines that resemble metrics calls that link to the most relevant page on Datadog.
        - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
            - [x] Link to Sourcegraph.com file/line where decoration should appear
            - [x] Link to GitHub.com file/line where decoration should appear
            - [ ] Link to GitHub.com PR diff file/line where decoration should appear
        - [ ] Implement line decorations that can be detected by looking at the single line; i.e., simply without needing to parse/analyze multiple lines or multiple files.
            - [ ] 80% test coverage
            - [ ] Merge the README PR from the first step. The links should now work.
    - [ ] Datadog extension renders line decorations with "Live traces (Datadog) >>" for lines that resemble traces (or are known to define a span) that link to the most relevant page on Datadog
        - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
            - [ ] Link to Sourcegraph.com file/line where decoration should appear
            - [ ] Link to GitHub.com file/line where decoration should appear
            - [ ] Link to GitHub.com PR diff file/line where decoration should appear
        - [ ] Implement line decorations that can be detected by looking at the single line; i.e., simply without needing to parse/analyze multiple lines or multiple files.
            - [ ] 80% test coverage
            - [ ] Merge the README PR from the first step. The links should now work.
            - [ ] Verify that the extension can detect all spans/traces defined in https://github.com/DataDog/trace-examples
- [ ] **Node.js (TypeScript/JavaScript)**
    - [ ] Datadog extension renders line decorations with "View metric (Datadog) >>" for lines that resemble metrics calls that link to the most relevant page on Datadog.
        - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
            - [x] Link to Sourcegraph.com file/line where decoration should appear
            - [x] Link to GitHub.com file/line where decoration should appear
            - [ ] Link to GitHub.com PR diff file/line where decoration should appear
        - [ ] Implement line decorations that can be detected by looking at the single line; i.e., simply without needing to parse/analyze multiple lines or multiple files.
            - [ ] 80% test coverage
            - [ ] Merge the README PR from the first step. The links should now work.
    - [ ] Datadog extension renders line decorations with "Live traces (Datadog) >>" for lines that resemble traces (or are known to define a span) that link to the most relevant page on Datadog
        - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
            - [ ] Link to Sourcegraph.com file/line where decoration should appear
            - [ ] Link to GitHub.com file/line where decoration should appear
            - [ ] Link to GitHub.com PR diff file/line where decoration should appear
        - [ ] Implement line decorations that can be detected by looking at the single line; i.e., simply without needing to parse/analyze multiple lines or multiple files.
            - [ ] 80% test coverage
            - [ ] Merge the README PR from the first step. The links should now work.
            - [ ] Verify that the extension can detect all spans/traces defined in https://github.com/DataDog/trace-examples
- [ ] **Java**
    - [ ] Datadog extension renders line decorations with "View metric (Datadog) >>" for lines that resemble metrics calls that link to the most relevant page on Datadog.
        - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
            - [x] Link to Sourcegraph.com file/line where decoration should appear
            - [x] Link to GitHub.com file/line where decoration should appear
            - [ ] Link to GitHub.com PR diff file/line where decoration should appear
        - [ ] Implement line decorations that can be detected by looking at the single line; i.e., simply without needing to parse/analyze multiple lines or multiple files.
            - [ ] 80% test coverage
            - [ ] Merge the README PR from the first step. The links should now work.
    - [ ] Datadog extension renders line decorations with "Live traces (Datadog) >>" for lines that resemble traces (or are known to define a span) that link to the most relevant page on Datadog
        - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
            - [ ] Link to Sourcegraph.com file/line where decoration should appear
            - [ ] Link to GitHub.com file/line where decoration should appear
            - [ ] Link to GitHub.com PR diff file/line where decoration should appear
        - [ ] Implement line decorations that can be detected by looking at the single line; i.e., simply without needing to parse/analyze multiple lines or multiple files.
            - [ ] 80% test coverage
            - [ ] Merge the README PR from the first step. The links should now work.
            - [ ] Verify that the extension can detect all spans/traces defined in https://github.com/DataDog/trace-examples
                - [ ] Open a PR to add a Java example to https://github.com/DataDog/trace-examples and mark it as closing https://github.com/DataDog/trace-examples/issues/46
- [ ] The README.md file and other information shown on the extension's registry page (e.g., https://sourcegraph.com/extensions/sourcegraph/sentry) is informative and up to date with respect to:
    - [ ] Features
    - [ ] Usage instructions
    - [ ] Compatibility (which versions of Sourcegraph, which code hosts, and which forms of the external service (e.g., Datadog's US endpoint vs. Datadog's EU endpoint))
- [ ] If the extension is mentioned on the Datadog's website, that material is also kept up to date with what we have on our own site.

Customers (not exhaustive):

- http://app.hubspot.com/contacts/2762526/company/561806411

**Comment by nicksnyder** [comment]
Going to close this issue until @christinaforney verifies the product plan. https://github.com/sourcegraph/sourcegraph/issues/655 is the overall tracking issue.
