### ISSUE TITLE
RFC 629: Cold-storing older worker execution logs - Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#33024]
### Plan

Implements [RFC 629: Cold-storing older worker execution logs](https://docs.google.com/document/d/1ZQ1PYXHXsGQA59VDsZKlXfSScW_8pL4DBAb7CUBzEEY).

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/33025 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33026 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33027 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33028 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33030 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33031 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33032 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33033 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33034 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33036 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33084 
- [x] https://github.com/sourcegraph/sourcegraph/issues/27090 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/33037 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/33038 

Completed
- [x] (🏁 756 days ago) https://github.com/sourcegraph/sourcegraph/issues/24466 
- [x] (🏁 615 days ago) https://github.com/sourcegraph/sourcegraph/issues/27348 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by varungandhi-src** [comment]
Was accidentally closed
