### ISSUE TITLE
RFC 624: Configurable auto-indexing recognizers - Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#33039]
### Plan

Implements [RFC 624: Configurable auto-indexing recognizers](https://docs.google.com/document/d/1LOVI6xogkt4Iifl1F_8Gb_H9pXQ_MrynW8vmr6D05A0).

### Tracked issues

@Strum355

Completed
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/33046 

@efritz

- [x] https://github.com/sourcegraph/sourcegraph/issues/33040 

Completed
- [x] (🏁 213 days ago) https://github.com/sourcegraph/sourcegraph/issues/33042 
- [x] (🏁 202 days ago) https://github.com/sourcegraph/sourcegraph/issues/33041 
- [x] (🏁 192 days ago) https://github.com/sourcegraph/sourcegraph/issues/33044 (PRs: ~[#34712](https://github.com/sourcegraph/sourcegraph/pull/34712)~)
- [x] (🏁 190 days ago) https://github.com/sourcegraph/sourcegraph/issues/33045 (PRs: ~[#34807](https://github.com/sourcegraph/sourcegraph/pull/34807)~, ~[#34864](https://github.com/sourcegraph/sourcegraph/pull/34864)~)
- [x] (🏁 178 days ago) https://github.com/sourcegraph/sourcegraph/issues/35451 
- [x] (🏁 51 days ago) https://github.com/sourcegraph/sourcegraph/issues/34295 (PRs: ~[#36122](https://github.com/sourcegraph/sourcegraph/pull/36122)~, ~[#41463](https://github.com/sourcegraph/sourcegraph/pull/41463)~)
- [x] (🏁 51 days ago) https://github.com/sourcegraph/sourcegraph/issues/34297 (PRs: ~[#36122](https://github.com/sourcegraph/sourcegraph/pull/36122)~, ~[#41466](https://github.com/sourcegraph/sourcegraph/pull/41466)~)
- [x] (🏁 51 days ago) https://github.com/sourcegraph/sourcegraph/issues/34296 (PRs: ~[#36122](https://github.com/sourcegraph/sourcegraph/pull/36122)~, ~[#41471](https://github.com/sourcegraph/sourcegraph/pull/41471)~)

@macraig

- [x] https://github.com/sourcegraph/sourcegraph/issues/33047 

@tjdevries

Completed
- [x] (🏁 51 days ago) https://github.com/sourcegraph/sourcegraph/issues/34295 (PRs: ~[#36122](https://github.com/sourcegraph/sourcegraph/pull/36122)~, ~[#41463](https://github.com/sourcegraph/sourcegraph/pull/41463)~)
- [x] (🏁 51 days ago) https://github.com/sourcegraph/sourcegraph/issues/34297 (PRs: ~[#36122](https://github.com/sourcegraph/sourcegraph/pull/36122)~, ~[#41466](https://github.com/sourcegraph/sourcegraph/pull/41466)~)
- [x] (🏁 51 days ago) https://github.com/sourcegraph/sourcegraph/issues/34296 (PRs: ~[#36122](https://github.com/sourcegraph/sourcegraph/pull/36122)~, ~[#41471](https://github.com/sourcegraph/sourcegraph/pull/41471)~)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.
