### ISSUE TITLE
3.5 plan for LightStep extension

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#3304]
The focus for the 3.5 release cycle is to get the LightStep extension working 100% for Go, Node.js, Python, Java.

WIP: https://github.com/sourcegraph/sourcegraph-lightstep

- [ ] Update this checklist with any unfinished work from https://github.com/sourcegraph/sourcegraph/issues/3297
- [ ] Add codecov to sourcegraph-lightstep repo
- [ ] **Go**: LightStep extension renders line decorations with "Live traces (LightStep) >>" for lines that resemble traces (or are known to define a span) that link to the most relevant page on LightStep
    - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [ ] Link to Sourcegraph.com file/line where decoration should appear
        - [ ] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement line decorations that can be detected by looking at the single line; i.e., simply without needing to parse/analyze multiple lines or multiple files.
        - [ ] 80% test coverage
        - [ ] Merge the README PR from the first step. The links should now work.
- [ ] "(Show/Hide) trace decorations" action in command palette
    - [ ] Implementation done
    - [ ] 80% test coverage
    - [ ] Update the README to document this.
- [ ] If user input is needed to configure the LightStep account (e.g., needing the account ID to construct the URLs), a progressive flow to complete setup:
    - [ ] Line decorations are still shown with a dimmer color and read "Missing LightStep (whatever)" ([see LightStep example](https://sourcegraph.com/github.com/sourcegraph/sourcegraph-lightstep@779b2029df916f7f8eaa60b09819aea1938b8d08/-/blob/src/extension.ts#L51-56))
    - [ ] An editor/title action to "Set LightStep (whatever)" is shown that prompts the user for the value
- [ ] **Node.js (TypeScript/JavaScript)**: LightStep extension renders line decorations with "Live traces (LightStep) >>" for lines that resemble traces (or are known to define a span) that link to the most relevant page on LightStep
    - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [ ] Link to Sourcegraph.com file/line where decoration should appear
        - [ ] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement line decorations that can be detected by looking at the single line; i.e., simply without needing to parse/analyze multiple lines or multiple files.
        - [ ] 80% test coverage
        - [ ] Merge the README PR from the first step. The links should now work.
- [ ] **Python**: LightStep extension renders line decorations with "Live traces (LightStep) >>" for lines that resemble traces (or are known to define a span) that link to the most relevant page on LightStep
    - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [ ] Link to Sourcegraph.com file/line where decoration should appear
        - [ ] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement line decorations that can be detected by looking at the single line; i.e., simply without needing to parse/analyze multiple lines or multiple files.
        - [ ] 80% test coverage
        - [ ] Merge the README PR from the first step. The links should now work.
- [ ] **Java**: LightStep extension renders line decorations with "Live traces (LightStep) >>" for lines that resemble traces (or are known to define a span) that link to the most relevant page on LightStep
    - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [ ] Link to Sourcegraph.com file/line where decoration should appear
        - [ ] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement line decorations that can be detected by looking at the single line; i.e., simply without needing to parse/analyze multiple lines or multiple files.
        - [ ] 80% test coverage
        - [ ] Merge the README PR from the first step. The links should now work.
- [ ] The README.md file and other information shown on the extension's registry page (e.g., https://sourcegraph.com/extensions/sourcegraph/sentry) is informative and up to date with respect to:
    - [ ] Features
    - [ ] Usage instructions
    - [ ] Compatibility (which versions of Sourcegraph, which code hosts, and which forms of the external service)
- [ ] If the extension is mentioned on the LightStep's website, that material is also kept up to date with what we have on our own site.

**Comment by nicksnyder** [comment]
This plan is obsolete.
