### ISSUE TITLE
3.6 plan for Sentry/DataDog/LightStep extensions

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#3305]
The focus for the 3.6 release is to add support for more use cases and languages.

- [ ] Update this checklist with any unfinished work from https://github.com/sourcegraph/sourcegraph/issues/3304
- [ ] **Datadog Node.js**, enhance detection by also parsing/analyzing the package.json and express.js entrypoint to see if Datadog metrics/APM/tracing is being used (and, e.g., using that to decorate express.js `app.get` and other lines that define HTTP endpoints in web frameworks).
- [ ] **Datadog Ruby**
    - [ ] Datadog extension renders line decorations with "View metric (Datadog) >>" for lines that resemble metrics calls that link to the most relevant page on Datadog.
        - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
            - [ ] Link to Sourcegraph.com file/line where decoration should appear
            - [ ] Link to GitHub.com file/line where decoration should appear
            - [ ] Link to GitHub.com PR diff file/line where decoration should appear
        - [ ] Implement line decorations
            - [ ] 80% test coverage
            - [ ] Merge the README PR from the first step. The links should now work.
    - [ ] Datadog extension renders line decorations with "Live traces (Datadog) >>" for lines that resemble traces (or are known to define a span) that link to the most relevant page on Datadog
        - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
            - [ ] Link to Sourcegraph.com file/line where decoration should appear
            - [ ] Link to GitHub.com file/line where decoration should appear
            - [ ] Link to GitHub.com PR diff file/line where decoration should appear
        - [ ] Implement line decorations
            - [ ] 80% test coverage
            - [ ] Merge the README PR from the first step. The links should now work.
            - [ ] Verify that the extension can detect all spans/traces defined in https://github.com/DataDog/trace-examples (open PR to add example for this language to that repo if necessary).
- [ ] **Datadog PHP**
    - [ ] Datadog extension renders line decorations with "View metric (Datadog) >>" for lines that resemble metrics calls that link to the most relevant page on Datadog.
        - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
            - [ ] Link to Sourcegraph.com file/line where decoration should appear
            - [ ] Link to GitHub.com file/line where decoration should appear
            - [ ] Link to GitHub.com PR diff file/line where decoration should appear
        - [ ] Implement line decorations
            - [ ] 80% test coverage
            - [ ] Merge the README PR from the first step. The links should now work.
    - [ ] Datadog extension renders line decorations with "Live traces (Datadog) >>" for lines that resemble traces (or are known to define a span) that link to the most relevant page on Datadog
        - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
            - [ ] Link to Sourcegraph.com file/line where decoration should appear
            - [ ] Link to GitHub.com file/line where decoration should appear
            - [ ] Link to GitHub.com PR diff file/line where decoration should appear
        - [ ] Implement line decorations
            - [ ] 80% test coverage
            - [ ] Merge the README PR from the first step. The links should now work.
            - [ ] Verify that the extension can detect all spans/traces defined in https://github.com/DataDog/trace-examples (open PR to add example for this language to that repo if necessary).
- [ ] **Datadog C++**
    - [ ] Datadog extension renders line decorations with "View metric (Datadog) >>" for lines that resemble metrics calls that link to the most relevant page on Datadog.
        - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
            - [ ] Link to Sourcegraph.com file/line where decoration should appear
            - [ ] Link to GitHub.com file/line where decoration should appear
            - [ ] Link to GitHub.com PR diff file/line where decoration should appear
        - [ ] Implement line decorations
            - [ ] 80% test coverage
            - [ ] Merge the README PR from the first step. The links should now work.
    - [ ] Datadog extension renders line decorations with "Live traces (Datadog) >>" for lines that resemble traces (or are known to define a span) that link to the most relevant page on Datadog
        - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
            - [ ] Link to Sourcegraph.com file/line where decoration should appear
            - [ ] Link to GitHub.com file/line where decoration should appear
            - [ ] Link to GitHub.com PR diff file/line where decoration should appear
        - [ ] Implement line decorations
            - [ ] 80% test coverage
            - [ ] Merge the README PR from the first step. The links should now work.
            - [ ] Verify that the extension can detect all spans/traces defined in https://github.com/DataDog/trace-examples (open PR to add example for this language to that repo if necessary).
- [ ] **LightStep** Enhance detection by also parsing/analyzing other files or multiple lines to see if LightStep traces are being used (and, e.g., using that to decorate express.js `app.get` and other lines that define HTTP endpoints in web frameworks).
    - [ ] Update all languages.
    - [ ] 80% test coverage
    - [ ] Update README with examples
        - [ ] Link to Sourcegraph.com file/line where decoration should appear
        - [ ] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
- [ ] **LightStep Ruby**: LightStep extension renders line decorations with "Live traces (LightStep) >>" for lines that resemble traces (or are known to define a span) that link to the most relevant page on LightStep
    - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [ ] Link to Sourcegraph.com file/line where decoration should appear
        - [ ] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement line decorations
        - [ ] 80% test coverage
        - [ ] Merge the README PR from the first step. The links should now work.
- [ ] **LightStep PHP**: LightStep extension renders line decorations with "Live traces (LightStep) >>" for lines that resemble traces (or are known to define a span) that link to the most relevant page on LightStep
    - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [ ] Link to Sourcegraph.com file/line where decoration should appear
        - [ ] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement line decorations
        - [ ] 80% test coverage
        - [ ] Merge the README PR from the first step. The links should now work.
- [ ] **LightStep C++**: LightStep extension renders line decorations with "Live traces (LightStep) >>" for lines that resemble traces (or are known to define a span) that link to the most relevant page on LightStep
    - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [ ] Link to Sourcegraph.com file/line where decoration should appear
        - [ ] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement line decorations
        - [ ] 80% test coverage
        - [ ] Merge the README PR from the first step. The links should now work.
- [ ] **Sentry (all languages)** support format specifiers (eg if you have `log.Printf("enqueueing %s update", foo)`, it should construct a log query for "enqueueing" and "update", not the literal "%s")
    - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language and how to configure the match pattern.
        - [ ] Link to Sourcegraph.com file/line where decoration should appear
        - [ ] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement log statement are detection using patterns from the user's extension settings (if set).
        - [ ] 80% test coverage
        - [ ] Merge the README PR from the first step. The links should now work.
- [ ] **Sentry (all languages):** support user-defined heuristics for log line matching (eg if you are using a custom log library whose calls look like `log(INFO, "my message")`
    - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language and how to configure the match pattern.
        - [ ] Link to Sourcegraph.com file/line where decoration should appear
        - [ ] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement log statement are detection using patterns from the user's extension settings (if set).
        - [ ] 80% test coverage
        - [ ] Merge the README PR from the first step. The links should now work.
- [ ] **Sentry Swift:** Sentry extension renders line decorations with "View logs in Sentry >>" for lines that resemble log print statements that link to the matching live logs on Sentry.
    - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [ ] Link to Sourcegraph.com file/line where decoration should appear
        - [ ] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement log statement are detection using hard coded logic for this language.
        - [ ] 80% test coverage
        - [ ] Merge the README PR from the first step. The links should now work.
- [ ] **Sentry Ruby:** Sentry extension renders line decorations with "View logs in Sentry >>" for lines that resemble log print statements that link to the matching live logs on Sentry.
    - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [ ] Link to Sourcegraph.com file/line where decoration should appear
        - [ ] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement log statement are detection using hard coded logic for this language.
        - [ ] 80% test coverage
        - [ ] Merge the README PR from the first step. The links should now work.
- [ ] **Sentry PHP:** Sentry extension renders line decorations with "View logs in Sentry >>" for lines that resemble log print statements that link to the matching live logs on Sentry.
    - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [ ] Link to Sourcegraph.com file/line where decoration should appear
        - [ ] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement log statement are detection using hard coded logic for this language.
        - [ ] 80% test coverage
        - [ ] Merge the README PR from the first step. The links should now work.
- [ ] **Sentry C++:** Sentry extension renders line decorations with "View logs in Sentry >>" for lines that resemble log print statements that link to the matching live logs on Sentry.
    - [ ] Create (but don't merge) a PR to update the README to include example links where this extension will work for this language.
        - [ ] Link to Sourcegraph.com file/line where decoration should appear
        - [ ] Link to GitHub.com file/line where decoration should appear
        - [ ] Link to GitHub.com PR diff file/line where decoration should appear
    - [ ] Implement log statement are detection using hard coded logic for this language.
        - [ ] 80% test coverage
        - [ ] Merge the README PR from the first step. The links should now work.
- [ ] Ensure all READMEs are up to date
- [ ] If you haven't already done so, create a shared library for detecting open tracing space so this logic can be shared between LightStep and Datadog extensions.

Customers affected (TODO incomplete):

- Sentry
  - https://app.hubspot.com/contacts/2762526/company/419771425
  - https://app.hubspot.com/contacts/2762526/company/693777200 
- Datadog
  - https://app.hubspot.com/contacts/2762526/company/1100581370/

**Comment by nicksnyder** [comment]
This plan is obsolete.
