### ISSUE TITLE
Tracking issue: Run tests to help decide about search technology (JCEF vs native)

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#33187]
Things to test, in rough order of decreasing priority:

[Google Doc Notes](https://docs.google.com/document/d/1ZiqsuiBJ-YKUl2jBdnj82lXf0kmC7eC6wZCbpB1Pu2U/edit)

- [x] Can we add a JCEF component anywhere on the UI?
- [x] Can we put a JCEF component to a modal?
- [x] How long does it take to load the modal with content (does the JCEF component flicker?)
- [x] Can we customize the colors of the web view to match the JetBrains layout?
    - How does the bridge between native and browser look like? Look for custom UI settings and see how we can forward them to the browser environment.
- [x] Can we avoid page refreshes and loading indicators to a large extent?
- [x] How can we measure and compare the startup speed of the web view in comparison to a native widget?
- [x] Debugging Tools: Can we connect chrome debugger (for UI tests)?
- [x] Keyboard handling: Does tabbing inside and outside the JCEF component work as intended?
- [x] Keyboard handling: There are default shortcuts for interacting with a search box. Do these work?
- [x] Keyboard handling: Do custom keyboard shortcuts work as well?
- [x] Can we register events in Analytics? (are we sandboxed?)
- [x] What browser APIs are supported
    - And what about older JetBrains versions?
- [x] Can we support VIM Mode? (Does VIM mode apply to modals at all, or is that editor-only?
- [x] How can we bundle the JavaScript?

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @rrhyne @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.

**Comment by vdavid** [comment]
@philipp-spiess I've created this issue based on our [meeting notes from yesterday](https://docs.google.com/document/d/188QewWUxtU8X-kpJxtSySZCO3xYE7rggWRCEXsPyPJQ/edit#), to track our progress and make space for the discussion related to these tests.

**Comment by jjinnii** [comment]
@vdavid @philipp-spiess Hey both! Quick clarification question:

My understanding of this issue is that it's a technical spike to understand whether we can utilize webviews and to what extent we can control/modify webviews. On bullets 4/5:

> Does it feel native?
 Can we make it feel native by using a few theme colors?

Is this more a question of "to what extent can we control the UI with webviews", referring to modification of fonts/colors to make a webview component "look" native? If so, could we potentially re-phrase it to reflect this? The questions "does it feel native", "does changing the colors make it feel native" are questions are users should be answering for us. 😄

**Comment by philipp-spiess** [comment]
@vdavid I started a Google document yesterday with the same intention. The document is probably better since we have more room for more notes so let's use that instead: https://docs.google.com/document/d/1ZiqsuiBJ-YKUl2jBdnj82lXf0kmC7eC6wZCbpB1Pu2U/edit 

@jjinnii 

> Is this more a question of "to what extent can we control the UI with webviews", referring to modification of fonts/colors to make a webview component "look" native? If so, could we potentially re-phrase it to reflect this? The questions "does it feel native", "does changing the colors make it feel native" are questions are users should be answering for us. 😄

Yes! That makes sense. What about:

- Can we customize the colors of the webview to match the jetbrains layout?
- Can we avoid page refreshes and loading indicators to a large extend?
- How can we measure and compare the startup speed of the web view in comparison to a native widget?

**Comment by philipp-spiess** [comment]
I wrote down everything we've learned last week in [this doc](https://docs.google.com/document/d/1Lkj_2MjayAqlvOTLjaLFGHYJnobV1ieRxXhH_jJDBgQ/edit#). We're now waiting for feedback before making a final decision.

**Comment by vdavid** [comment]
I think these are all done and we've got feedback for the doc, so I'd close this issue. @philipp-spiess, what do you think?

**Comment by philipp-spiess** [comment]
Agreed. 🎉
