### ISSUE TITLE
Reduce percentage of builds flaked to < 10% per day

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#33196]
## Solution summary

Artifacts:
- TO DO

## What specific customers are we iterating on the problem and solution with?

- TO DO

## Delivery plan

- [ ] TO DO

## Tracked issues

 

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/26257 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/29624 

@bobheadxi

- [ ] https://github.com/sourcegraph/sourcegraph/issues/30237  🕵️

Completed
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/30233 

@davejrt

- [ ] https://github.com/sourcegraph/sourcegraph/issues/30237  🕵️

Completed
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/30233

**Comment by bobheadxi** [comment]
@davejrt assigning you for now as a continuation of https://github.com/sourcegraph/sourcegraph/issues/30233 !

**Comment by taylorsperry** [comment]
Folding this goal into our initiative to aggregate CI metrics https://github.com/sourcegraph/sourcegraph/issues/33242.

**Comment by jhchabran** [comment]
@davejrt relevant bit of context: https://github.com/sourcegraph/devx-scratch/blob/main/2022/support/log.md?plain=1#L11
