### ISSUE TITLE
All Sourcegraph components can export uniform, structured logs

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#33192]
## Problem to solve

Today, `log15` is used throughout the Sourcegraph codebase for logging. It is mostly sufficient, but has some issues:

- Strange conventions: log levels are `dbug`, `eror`, etc. which is a common source of confusion, and causes interop issues with external tools
- Unmaintained: [most of `log15`'s commit activity is from over 5 years ago](https://sourcegraph.com/github.com/inconshreveable/log15@master/-/commits), and the repository has a number of abandoned open PRs. We are unlikely to run into `log4j`-style security risk, but this is still a potential risk.
- Performance: logging libraries like https://github.com/uber-go/zap are ~1000% to ~5000% faster than `log15` ([reference](https://github.com/uber-go/zap#performance)) - at Sourcegraph's logging volume this is a likely a non-negligible difference

We also have issues such as extensive use of global logging, which does not include any structured metadata, and extensive use of unstructured logs in general. This leads to a low signal to noise ratio, and a lack of ability to filter logs in a useful manner.

We can take this opportunity to improve tie-in with [OpenTracing standards](https://opentelemetry.io/docs/reference/specification/logs/data-model/#trace-context-fields), and improve our sensitive data redaction in logging.

## Measure of success

- A standardized logging package is introduced that exports a logger with standardized fields (~[`lib/log`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/tree/lib/log)~ now https://github.com/sourcegraph/log)
- A document is created that describes logging best practices: ["How to add and use logging"](https://docs.sourcegraph.com/dev/how-to/add_and_use_logging)
- Migration is in progress for all Sourcegraph services to switch to the new logging package ([dashboard](https://k8s.sgdev.org/sign-in?returnTo=%2Finsights%2Fdashboards%2FZGFzaGJvYXJkOnsiSWRUeXBlIjoiY3VzdG9tIiwiQXJnIjo3MjcyNTN9))

## Solution summary

We will propose a complete migration to [zap](https://github.com/uber-go/zap) (which would work for Cloud as well as on-prem) and encourage use of passing loggers instances around to enable better structured logging by attaching metadata to logger instances and log entries that can be propagated. Part of this will likely include banning the use of other printing/logging packages other than the chosen logging library.

Artifacts:
- Brainstorming and feedback discussion: https://github.com/sourcegraph/sourcegraph/discussions/33248

## What specific customers are we iterating on the problem and solution with?

Internal Sourcegraph developers.

## Impact on use cases

This effort contributes to the company-wide effort to improve Observability. 

## Delivery plan

- [x] Investigate existing proposals, issues, and problem space [details](https://github.com/sourcegraph/sourcegraph/discussions/33248)
- [x] MVP implementation and proposal is prepared [details](https://github.com/sourcegraph/sourcegraph/pull/33953)
- [x] Initial rounds of implementation and migration are handled by DevX
- [x] Roll out JSON logs in Cloud: https://github.com/sourcegraph/sourcegraph/issues/34599 and ensure the format works ([update](https://sourcegraph.slack.com/archives/C033PDEV740/p1651597329911709?thread_ts=1651514676.645109&cid=C033PDEV740))
- [x] Set up tooling to avoid migration regressions and communicate new recommendations to #dev-backend
- [x] Allocate some migrations to GitStart and ramp them up to perform migrations effectively
- [x] Support teams in performing their own migrations, and address feedback/documentation issues continuously

### Tracked issues

 

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/33475  🕵️
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33476 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35257 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35837 

Completed
- [x] (🏁 62 days ago) https://github.com/sourcegraph/sourcegraph/issues/33477 

@bobheadxi: __8.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/33240  __3.00d__ 🛠️
  - [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/issues/34217  __3.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33241  __3.00d__ 🛠️
  - [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/issues/34217  __3.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33473 

Completed: __8.00d__
- [x] (🏁 62 days ago) https://github.com/sourcegraph/sourcegraph/issues/33953 
- [x] (🏁 62 days ago) https://github.com/sourcegraph/sourcegraph/issues/33474 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/pull/34479 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/issues/34321  __1.00d__
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/pull/34529 
- [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/issues/34217  __3.00d__
- [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/pull/34596 
- [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/issues/34599 
- [x] (🏁 55 days ago) https://github.com/sourcegraph/sourcegraph/pull/34594 
- [x] (🏁 55 days ago) https://github.com/sourcegraph/sourcegraph/pull/34674 
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/issues/34584 
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/issues/34482  __1.00d__
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/issues/34319  __3.00d__
- [x] (🏁 36 days ago) https://github.com/sourcegraph/sourcegraph/pull/35516 
- [x] (🏁 36 days ago) https://github.com/sourcegraph/sourcegraph/pull/35430 
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/pull/36687 
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/pull/36834 
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/36734 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/issues/33954  🕵️

@burmudar: __6.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/36923  __1.00d__ 🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/34608  __5.00d__
  - [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/34607  __5.00d__

Completed: __5.00d__
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/34607  __5.00d__

@davejrt: __3.00d__

Completed: __3.00d__
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/issues/34319  __3.00d__

@gitstart-sourcegraph: __8.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/36384  __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36382  __1.50d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/37398  __1.00d__
  - [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/issues/37399  __0.50d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/37461  __1.00d__

Completed: __4.50d__
- [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/issues/35514 (PRs: ~[#35516](https://github.com/sourcegraph/sourcegraph/pull/35516)~) __2.00d__
- [x] (🏁 2 days ago) https://github.com/sourcegraph/sourcegraph/issues/36387  __2.00d__
- [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/issues/37399  __0.50d__

@jhchabran

- [ ] https://github.com/sourcegraph/sourcegraph/issues/33240  🛠️
  - [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/pull/35879 

Completed
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/pull/35879 

@marekweb: __1.00d__

Completed: __1.00d__
- [x] (🏁 49 days ago) https://github.com/sourcegraph/sourcegraph/issues/34482  __1.00d__

@varungandhi-src

- [ ] https://github.com/sourcegraph/sourcegraph/issues/33473 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by bobheadxi** [comment]
Brainstorming and feedback discussion: https://github.com/sourcegraph/sourcegraph/discussions/33248

**Comment by bobheadxi** [comment]
Migration dashboard: https://k8s.sgdev.org/insights/dashboards/ZGFzaGJvYXJkOnsiSWRUeXBlIjoiY3VzdG9tIiwiQXJnIjo3MjcyNTN9

**Comment by vrto** [comment]
FYI

I have been looking into [OpenTelemetry](https://opentelemetry.io) as we can potentially leverage an existing standard for log data. The summary of my findings is available in [this document](https://docs.google.com/document/d/1-bpXGkE7LWqrZiWv0HCkBSJBdb7PdJA5eNS4GLUxQ6Q/edit#heading=h.vq2fonsg7iqp).

From my findings, I think that our work in the logging improvements seems well-aligned with OpenTelemetry’s log models, and we’ve been mindful about committing to this format early on. I recommend we proceed as planned.

**Comment by taylorsperry** [comment]
Progress: We have a new logging library that encodes some best practices:
- Safe, strongly-typed ways to add fields to logs
- Easy-to-use ways to build contextful loggers by attaching metadata to all logs emitted by a logger (e.g. for tracing events and actions taken by subsytems)
- Restricting the ability to emit context-less logs (no global loggers)

[How to add logging](https://docs.sourcegraph.com/dev/how-to/add_logging) and [Add observability](https://docs.sourcegraph.com/dev/how-to/add_observability) have been added to the docs. 

We are working on migrating logs to this new library. See
[Code Insights for Migration progress (approximate)](https://k8s.sgdev.org/insights/dashboards/ZGFzaGJvYXJkOnsiSWRUeXBlIjoiY3VzdG9tIiwiQXJnIjo3MjcyNTN9).

The next step is to investigate which migrations we can delegate to Gitstart.

**Comment by bobheadxi** [comment]
Note that the code for this has moved to https://github.com/sourcegraph/log. There are currently no plans to move the docs, etc and we will probably continue to refer to it as `lib/log` for some time.
