### ISSUE TITLE
All Sourcegraph components can export standardized sets of metrics

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#33241]
## Problem to solve

Today, our services do not export uniform metrics. With various implementations and custom metrics, this makes it difficult to interpret what a user is actually experiencing when the metrics are being viewed by an individual, or take any meaningful action if it isn't clear what the metric represents. It's also been [noted](https://sourcegraph.slack.com/archives/C02VDNKBWDU/p1651063380116879?thread_ts=1651043351.515279&cid=C02VDNKBWDU) that custom metrics can be very expensive, which we'd like to avoid. 

In order to accurately display what users are experiencing when using Sourcegraph and provide a way to determine service issues more easily, we should export metrics using the [RED method](https://www.infoworld.com/article/3638693/the-red-method-a-new-strategy-for-monitoring-microservices.html#jump). 

## Measure of success

- Services adhere to and export a standardized set of Rate, Error and Duration based metrics, which are consumable via more meaningful dashboards. 
- The handbook documents this implementation and how to use it effectively
- Migration to use the new metrics is in progress for any service not currently using it. 

## Solution summary

We will propose a migration of any services not currently using the [RED metrics package](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/metrics/operation.go?subtree=true) to provide better information for our users. 

Artefacts:
- Current [RED metrics implementation](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/metrics/operation.go?subtree=true)

## What specific customers are we iterating on the problem and solution with?

Internal Sourcegraph developers, and those teams who consume these metrics most often (Customer Engineering, Delivery, Cloud DevOps). 

## Impact on use cases

This effort contributes to the company-wide effort to improve Observability.

## Delivery plan

- [ ] Investigate existing proposals, issues, and problem space
- [ ] Prepare a draft docs page with standardized proposal
- [ ] Partner with team to implement and refine the implementation approach
- [ ] Start performing migration of services to new metrics

### Tracked issues

 

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/48801 

Completed
- [x] (🏁 496 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  🛠️

@bobheadxi: __3.00d__

Completed: __3.00d__
- [x] (🏁 496 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  __3.00d__ 🛠️
- [x] (🏁 475 days ago) https://github.com/sourcegraph/sourcegraph/issues/33192  __3.00d__ 🛠️
- [x] (🏁 474 days ago) https://github.com/sourcegraph/sourcegraph/issues/33240  __3.00d__ 🛠️

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by vrto** [comment]
FYI

I have been looking into [OpenTelemetry](https://opentelemetry.io) as we can potentially leverage an existing standard for log data. The summary of my findings is available in [this document](https://docs.google.com/document/d/1-bpXGkE7LWqrZiWv0HCkBSJBdb7PdJA5eNS4GLUxQ6Q/edit#heading=h.vq2fonsg7iqp).

From my findings, I think should re-shuffle here a bit. The push towards RED metrics is a useful initiative but is aligned with OpenTelemetry’s Tracing functional component. For Metrics, we should consider whether adopting the OpenTelemetry instruments ([counter, measure, observer](https://opentelemetry.io/docs/concepts/data-sources/#traces)) is worth adopting.

**Comment by vrto** [comment]
Did a little more digging around this; I acknowledge that the [North Star](https://docs.google.com/document/d/19bPH4Zxb8zl4DwDyOMfdSx5o4PI3UkshGsAh89QBdlM/edit#heading=h.8moaux461mlv) is _way_ more focused on logs+traces than metrics.

It appears that while OTel Metrics work is WIP, they're going to be treating as an important collaborator and will provide quality [first-class integration](https://opentelemetry.io/docs/reference/specification/metrics/datamodel/#prometheus-compatibility). It's something I plan (we should) be keeping an eye on.
