### ISSUE TITLE
CI key result metrics are centralized and aggregated in reports

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#33242]
## Problem to solve

Today, there's not an easy way for stakeholders to get at-a-glance observability into the health of our CI pipeline. We're capturing daily metrics for "time main is red" in the #dev-experience channel, but this data is insufficient because it conflates incidents (which are mostly in the hands of PR authors themselves) with flakes (which can be improved with more stable tests and more resilient infrastructure). These are different problems with different solutions, and they have different implications for pipeline health. 

## Measure of success

The most important CI metrics are captured and easily observable. Our hope is that by the end of the quarter, as a result of our other efforts, these metrics will reflect that less than 10% of builds are flaking per day and build time is under 30 minutes. 

## Solution summary

We will export the identified metrics to a single service, making it easily consumable for stakeholders and allow for better decision making based on said metrics. 

Artefacts:
- [Scratch pad - CI pipeline metrics](https://docs.google.com/document/d/1QvyMnMJIAEMmVcmHAkj472Fhx7bbSEBjF9DPXafqvTc/edit#)

## What specific customers are we iterating on the problem and solution with?

Internal Sourcegraph stakeholders

## Impact on use cases

This work contributes to our overall effort to increase operational maturity. 

## Delivery plan

- [x] [Identify the metrics we want to capture](https://docs.google.com/document/d/1QvyMnMJIAEMmVcmHAkj472Fhx7bbSEBjF9DPXafqvTc/edit)
- [x] Make sure we are capturing desired metrics ([`buildchecker history`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/buildchecker/README.md#history))
- [x] Slack notification to report weekly incident and flake numbers
- [x] Push relevant metrics to Okay

### Tracked issues

 

@bobheadxi

Completed
- [x] (🏁 135 days ago) https://github.com/sourcegraph/sourcegraph/pull/29734 
- [x] (🏁 96 days ago) https://github.com/sourcegraph/sourcegraph/pull/31360 
- [x] (🏁 96 days ago) https://github.com/sourcegraph/sourcegraph/pull/31823 
- [x] (🏁 86 days ago) https://github.com/sourcegraph/sourcegraph/pull/32224 

@davejrt

Completed
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/pull/35666 
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/pull/35671 
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/pull/36087 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/36173 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
