### ISSUE TITLE
RFC 619: Code Intelligence Platform - Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#33371]
### Plan

Implements [RFC 619: Code Intelligence Data Platform](https://docs.google.com/document/d/1AjZ_d0nJVHbV75IH3jZRkrGXhsv_AXp2kS4nrw2SAQ8).

### Tracked issues

@Numbers88s

Completed
- [x] (🏁 53 days ago) https://github.com/sourcegraph/sourcegraph/issues/38171 
- [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/33374 
- [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/38166 
- [x] (🏁 40 days ago) https://github.com/sourcegraph/sourcegraph/issues/33376 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/issues/38160 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/issues/41060 
- [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/38167 
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/41129 
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/41130 
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/41131 
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/41132 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/38165 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/38163 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/38164 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/38162 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/38161 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/33373 

@efritz

Completed
- [x] (🏁 40 days ago) https://github.com/sourcegraph/sourcegraph/issues/33376 
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/41134 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/42197 
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/pull/42211 
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/pull/42316 
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/pull/42329 
- [x] (🏁 2 days ago) https://github.com/sourcegraph/sourcegraph/pull/42400 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/42405 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/42319 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
