### ISSUE TITLE
3.38.1 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#33458]
# 3.38.1 managed instances upgrade

These [managed instances](../../cloud/delivery/managed/index.md) upgrades are scheduled for **[Apr 6, 2022, 6:00 PM (UTC)](https://time.is/1800_6_Apr_2022_in_UTC?One%20working%20day%20after%203.38.1%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../cloud/delivery/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.

## Upgrade customer managed instances

- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/537

---

Also see [3.38.1 patch release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/33457)

**Comment by michaellzc** [comment]
@michaellzc @danieldides:
from https://github.com/sourcegraph/accounts/issues/528 to https://github.com/sourcegraph/accounts/issues/547

**Comment by mucles** [comment]
@mucles 
from https://github.com/sourcegraph/accounts/issues/8282 to https://github.com/sourcegraph/accounts/issues/537

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by michaellzc** [comment]
it's done
