### ISSUE TITLE
Proto: Rename symbol with batch changes

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#33703]
## Problem to solve

Users that start using Batch Changes often struggle in writing batch changes steps (code rewrite steps) required to get to their first batch change. This increases time to value and limits the number of MAUs.
Making batch changes code rewerite steps easy to develop in general is a massive problem. However, we can identify valuable subproblems to address. Symbol renaming is a frequent, valuable, well-defined sub-problem.

More in https://github.com/sourcegraph/sourcegraph/issues/32834

## Measure of success

This is a spike to understand the feasibility and engineering effort required to deliver https://github.com/sourcegraph/sourcegraph/issues/32834

It is successful if we have:
- a releasable feature, feature-flagged, with clearly defined limitations
- using this feature allows to perform a 99% accurate symbol-rename, given target repositories match prerequisites
- a scope of work and list of dependencies on other product areas
- a preview video that generates significant engagement/excitement

## Solution

Create a simple way for users to rename a symbol across their entire codebase, using code intelligence data.

<img width="2128" alt="image" src="https://user-images.githubusercontent.com/25070988/159269792-117a62bc-e853-4638-aa4f-b0237cfa5546.png">

This would give users an IDE-like experience of renaming symboles, but apply to all your codebase. In the long term it would create a very easy to use entrypoint into Bath Changes, increasing MAUs and our key metric `# of changesets merged`.

Note that this feature will be conditioned on precise code-intelligence data being available for all repositories targeted by the change.

The initial user experience will be:
- from a popover, when hovering or clicking a symbol
- you can navigate to a pre-filled batch change template
- that operates the symbol rename across the repositories targeted by the `on.repositoriesMatchingQuery`, provided that precise code intelligence data is available

## Impact on use cases

This creates an end-to-end Code health workflow, starting on the search results page, and ending with a batch change. 

## Delivery plan
- [ ] Take this [hackathon work](https://www.loom.com/share/6285137481c641b18fa0c9dc92d4addd) and scope out work required to release it as `experimental`
- [ ] RFC: pings for "rename symbol" clicks
- [ ] Do a minimal iteration required to release it as `experimental` behind a feature flag
- [ ] Record a public-facing demo video
- [ ] Create instructions for CEs to use this in a demo flow

**Comment by malomarrec** [comment]
Some notes:
- this button should only appear when precise code intel is available on the repo
- difficult case: how do we detect symbols you cannot rename? So for example, renaming a symbol that is defined in a repo you don't name
- if `foo` to `bar` in repo `A`, and in repo `B` that imports `foo` from `A`. We would also need to bump the version of `A` that is imported, and that is language-specific and maybe build-tool specific. Go is probably simpler than Java.

**Comment by scalabilitysolved** [comment]
@malomarrec Is this something that Batch Changes will be spikingin Q2?

**Comment by malomarrec** [comment]
Yes, it is on our roadmap to _spike_ this

**Comment by malomarrec** [comment]
Sounds like this will be greatly facilitated by [#33757](https://github.com/sourcegraph/sourcegraph/issues/33757)

**Comment by LawnGnome** [comment]
With #45316 and the posting of [the progress video](https://sourcegraph.slack.com/archives/C89KCDK5J/p1670397496352319), I think this is officially done.

Obvious next steps, should we decide to continue this work:

1. Fix the UI integration so it's not weirdly hooked into the extension API action code.
2. Have the UI use a styled modal, rather than `window.prompt`. (And generally get some design input on all of this.)
3. Limit renames only to Go files, and symbol types that can actually be renamed.
4. Fix the backend code to not use GraphQL to call back into code intel resolvers.
5. Add tests to, like, everything. Probably starting with Lingua Franker.
6. Implement `execute` on the relevant batch spec creation resolver(s) so we don't have a literal sleep-wait in the action code to wait for workspaces to be resolved.

Doing those _should_ be sufficient to ship this as a beta feature.
