### ISSUE TITLE
Go code checker: Insights -> Batch Changes MVP

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#33801]
Move https://github.com/sourcegraph/sourcegraph/pull/33289 to releasable iteration. See context and product story here: https://github.com/sourcegraph/sourcegraph/issues/31693

#### TODO

All those items are TODO for the Batch Changes team:

- [x] feature flag this feature (add it as an experimental feature) `goCodeCheckerTemplates`
- [x] code review 
- [ ] implement updated banner on the create and editor page (see this [figma](https://www.figma.com/file/3EeWSGVWr5AapidUe31b79/Insights-integration?node-id=51%3A2435))
- [x] add ping for when a user click on the `go code checker` tab (no RFC needed), this already exists for the other tabs
- [x] @malomarrec add "fixed" insights series to graphs 
- [x] @malomarrec  [quickfix] instead of [gofix]
- [x] add experimental banner

Those items are TODO for the Code Insights team:
- [x] add prototype badge to go code checker tab (Code Insights team will do it)
<img width="1151" alt="Screenshot 2022-04-12 at 18 29 51" src="https://user-images.githubusercontent.com/25070988/163010272-6d6b554d-e0ad-4b48-b7f1-280bd2ef43ae.png">

**Comment by malomarrec** [comment]
@eseliger volunteered to take a look at scope this week, to make sure this can be worked on next sprint. Thank you Erik!
