### ISSUE TITLE
Refactor search result components

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#34237]
Our search result components have some [technical debt](https://github.com/sourcegraph/sourcegraph/pull/31146#discussion_r807212130) that needs to be fixed.

- [x] Split `SearchResult` into `RepoSearchResult` and `CommitSearchResult` components - #34804
- [x] Rename `FileMatch` to `FileSearchResult` - #34805
- [x] Refactor `CommitSearchResultMatch` to a function component - #34935
- [x] Refactor `CodeExcerpt` to a function component - #35881
- [x] Rename `RepoIcon` to `CodeHostIcon` - #35891
- [x] Move `FileSearchResult` and all the components only it depends on from `shared` to `search-ui` package - #35903
- [x] Factor out any common UI between `RepoSearchResult`, `CommitSearchResult`, and `FileSearchResult` into a new `SearchResult` component. Or put more stuff into the existing `ResultContainer`. - #35982

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by limitedmage** [comment]
@novoselrok I know you had more thoughts on this, let me know if anything major is missing from this issue.
