### ISSUE TITLE
3.40.0 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#34256]
# 3.40.0 managed instances upgrade

These [managed instances](../../cloud/devops/managed/index.md) upgrades are scheduled for **[May 23, 2022, 6:00 PM (UTC)](https://time.is/1800_23_May_2022_in_UTC?One%20working%20day%20after%203.40%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../cloud/devops/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [ ] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [ ] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.

## Upgrade customer managed instances

- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/537
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/820
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/814
- [ ] Upgrade second instance for https://github.com/sourcegraph/customer/issues/820

---

Also see [3.40.0 release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/34255)

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by coury-clark** [comment]
Superseded by #34546

**Comment by unknwon** [comment]
Superseded by #36219
