### ISSUE TITLE
Notebooks: Cleanup for getting started page

### ISSUE THREAD

**Issue by marisak** [sourcegraph/sourcegraph#34480]
#### Details 
After the launch of search notebooks (yay 🎉 ) I solicited some feedback from the design team on how the getting started page could be visually improved and made more consistent with our other getting started experiences. All the items can be found in [Figma](https://www.figma.com/file/32wyz09t6u2bSBvsJwmDEA/Search-Notebooks-GA?node-id=2497%3A16618). I've pulled out the most urgent items here: 
- Change capitalization of tabs to title case 
> "It should be capital when you are referring to the feature name: "You can use Notebooks (the feature) to do XYZ at your company...." "We do not charge for using the Notebooks feature"
> But lowercase when referring to the actual notebooks themselves: "I created a notebook to do..." "I've made a few notebooks to help with..."
- Add "Create Notebook" CTA to main card, similar to Code Insights getting started 
- Change bottom CTAs to 1 column wide with empty column between them (or find a third CTA) 
- Edit some of the copy (e.g. tagline in top card) 

#### Type of debt

- Visual: All of these items are centered around improving the look and feel of this feature. 
- Bigger experience changes like an interactive demo are in the backlog. There's an issue ([link](https://github.com/sourcegraph/sourcegraph/issues/34384)) for tracking those bigger items. 

#### Estimated amount of work

- S - up to 1 week across product, design, and engineering 

#### Areas affected 
- "Getting started" page in search notebooks 

#### Impact 
- Consistency across product areas, therefore affects perception of our product 
- Notebooks just formally launched, so hopefully lots of people are seeing this page! 
- I made a pretty big mistake in defining the conditions under which people see this page, so I'd like to fix it while Notebooks is still fresh 

#### Urgency 
- Not critical, but not fixing it would cause us to incur more design debt 

#### Action plan
Specific items to fix can be found above under "Details." 

- [x] **April 25:** Marisa creates this issue and sends it to search product team for prioritization and estimation 
- [x] **April 26:** Marisa updates this issue with proposed design changes that correspond to the list in "Details" 
- [ ] (will continue to update following discussion with search product team!) 
- [ ] **May 6:** Marisa will publish documentation on the getting started pattern ([draft](https://docs.google.com/document/d/1E2Cb4f4v1d7q1EkY8BaVMjQjCFr6YZbui7iavKirkfc/edit#heading=h.trqab8y0kufp))

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by marisak** [comment]
Proposed design changes: [Figma](https://www.figma.com/file/32wyz09t6u2bSBvsJwmDEA/Search-Notebooks-GA?node-id=2567%3A16640)
