### ISSUE TITLE
Code intelligence 3.4 tracking issue

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#3449]
## User story

- As a user, code intel sometimes feels slow and buggy and I want it to feel fast and smooth. Hover tooltips don't show up and I can't click "Find references" consistently.

- As a user, I want the option to stay in my code host when clicking "Go to definition" or "Find references".

## Issues

- [x] Add "Submit code intel feedback" button to the toolbar
  - Go https://github.com/sourcegraph/sourcegraph-go/pull/70
  - TypeScript https://github.com/sourcegraph/sourcegraph-typescript/pull/175
  - Basic code intel https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/100
- [x] Upload basic-code-intel coverage https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/113
- [ ] Use `@sourcegraph/lsp-client` https://github.com/sourcegraph/sourcegraph-go/issues/28
  - Use `@sourcegraph/lsp-client` in the Go extension https://github.com/sourcegraph/sourcegraph-go/pull/36
  - Add support for custom `initializationOptions` in lsp-client https://github.com/sourcegraph/lsp-client/pull/36
  - ~~Move `originalRootUri` to `initializationOptions` https://github.com/sourcegraph/go-langserver/pull/369~~ subsumed by the next item
  - Support `"rootUri": "git://..."` in go-langserver https://github.com/sourcegraph/go-langserver/pull/373
  - Derive `zipURL` from `zipURLTemplate` https://github.com/sourcegraph/go-langserver/pull/370
- [ ] Single-click j2d https://github.com/sourcegraph/enterprise/issues/11047
  - Expose API in codeintellify https://github.com/sourcegraph/codeintellify/pull/106
  - Use in web app https://github.com/sourcegraph/sourcegraph/pull/3444
  - Split it into 2 pieces:
    - [ ] Replace click-based pinning with pin icon
    - [ ] Use single-click for j2d
  - [ ] Gather evidence from users or the team that this is better
- [ ] Investigate LSIF (discussion and doc at https://sourcegraph.slack.com/archives/CHXHX7XAS/p1556571369004700)
- [ ] Make `identCharPattern` configurable per language https://github.com/sourcegraph/sourcegraph/issues/3614
- [ ] Add a delay to the disappearance of the hover tooltip https://github.com/sourcegraph/codeintellify/issues/48
- [ ] Show loading indicator somewhere other than the tooltip
- [ ] Highlight other occurrences of variables https://github.com/sourcegraph/sourcegraph/issues/1283
- [ ] Dependency graph (insofar as it makes basic code intel more precise)
- [ ] References panel in code hosts
- [ ] Radical thought: pre-compute hovers in the background (like Kythe, Haskell Code Explorer)
- [ ] Support j2d on parameters and local variables (using tree-sitter)
  - Proof of concept https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/110
- [ ] Filter definitions for all languages https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/67
- [ ] Filter definitions by parent (from ctags)

**Comment by chrismwendt** [comment]
@sqs I ordered the list of tasks based on our [code intel sync today](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1555539024000300). Does this reflect your expectation of the order of priorities, too?

**Comment by felixfbecker** [comment]
`lsp-client` has been pushed through 2 iterations now, so I would like to see it prioritised higher. There are now two features added since the creation of lsp-client that should be shared across all languages (code intel toggle and connection troubleshooting notifications), but keep getting implemented per-language, causing inconsistent feature support and more work for us.

This issue claims that depends on changes/a specific PR in lsp-client, but the PR description says "this is a total hack" and I don't know why it is needed and can't be expressed through standard LSP (at least there is no explanation in https://github.com/sourcegraph/sourcegraph-go/issues/28)

**Comment by felixfbecker** [comment]
I would also like to point out that our codeintel extensions (both basic code intel and precise) still have 0% test coverage.

**Comment by chrismwendt** [comment]
The time is indeed ripe for switching to lsp-client! Yet another item to add to the growing list is the [LSIF prototype](https://sourcegraph.slack.com/archives/C89KCDK5J/p1556940616047700)

Since switching to lsp-client is an extension-level change, every customer will get the improvements without upgrading their deployments :sparkles:

Now, for largely historical reasons, go-langserver is not quite 100% LSP-compliant.

Given this, how do we integrate lsp-client?

Could we patch go-langserver and use lsp-client immediately? This would break code intel for customers with existing go-langserver deployments. Could we support both simultaneously? How would the extension know which version of go-langserver it's communicating with?

We could patch go-langserver immediately and push lsp-client through 2 more iterations to fulfill our 2 minor version support policy, but how can we get it integrated sooner?

**Comment by chrismwendt** [comment]
Next iteration's tracking issue: https://github.com/sourcegraph/sourcegraph/issues/4066
