### ISSUE TITLE
3.39.1 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#34546]
# 3.39.1 managed instances upgrade

These [managed instances](../../cloud/devops/managed/index.md) upgrades are scheduled for **[Apr 27, 2022, 6:00 PM (UTC)](https://time.is/1800_27_Apr_2022_in_UTC?One%20working%20day%20after%203.39.1%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../cloud/devops/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.

## Upgrade customer managed instances

- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/537
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/820
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/814
- [x] Upgrade second instance for https://github.com/sourcegraph/customer/issues/820

---

Also see [3.39.1 patch release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/34545)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sanderginn** [comment]
@michaellzc just to confirm, you assigned sourcegraph/accounts/issues/5057 to me, but this customer currently has no active MI

**Comment by michaellzc** [comment]
> @michaellzc just to confirm, you assigned [sourcegraph/accounts/issues/5057](https://github.com/sourcegraph/accounts/issues/5057) to me, but this customer currently has no active MI

my bad. let's ignore it

**Comment by daxmc99** [comment]
All instances have been upgraded 
comfirmed via `fd "VERSION" -x cat`
