### ISSUE TITLE
VSCE: Add VSCE nightly build and automated release to buildkite

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#34592]
Task list for implementing nightly build and automated release to our CI.

- [x] Merge https://github.com/sourcegraph/sourcegraph/pull/34537 for #26437 to Nightly Build branch
- [x] Merge https://github.com/sourcegraph/sourcegraph/pull/34522 for #34205 to main
- [x] Create branch for VSCE release: [vsce/release](https://github.com/sourcegraph/sourcegraph/tree/vsce/release)
- [x] Get a Personal Access Token for publishing extensions to VS Code Marketplace 
- [x] Add Token to onepassword under `VS Code Marketplace Token`
- [x] Add VS Code Marketplace Personal Access Token to GCP Secret Manager (need devX's help: [thread](https://sourcegraph.slack.com/archives/C01N83PS4TU/p1651085055704769)) https://github.com/sourcegraph/infrastructure/pull/3276
- [x] Create a new build for the automated release #34205 on buildkite
- [x] Create a new scheduled build for #26437 on buildkite

Scheduled build created in pipeline:
![image](https://user-images.githubusercontent.com/68532117/166330225-293a4efa-b870-46fb-89e0-cdbfb356438a.png)

Resources:
- [Current release workflow for main app](https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases)
- [Sourcegraph Release Issue Template](https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases/release_issue_template/)
- [VS Code Docs on automating release](https://code.visualstudio.com/api/working-with-extensions/continuous-integration#automated-publishing)
- [Workflow example](https://github.com/microsoft/vscode-platform-specific-sample/blob/main/.github/workflows/ci.yml)
-
