### ISSUE TITLE
Saved searches 3.4 tracking issue

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#3469]
- [ ] Migrate saved searches from site settings to a dedicated PostgreSQL table. 
   - [x] Write migration logic.
   - [x] Update query-runner to read from and notify users based on saved searches table.
   - [x] Update web app and write GraphQL mutations to read and write saved searches from and to the DB table.
   - [x] Write tests for new saved searches GQL mutations.
   - [x] Write tests for migration.
   - [ ] Fix https://github.com/sourcegraph/sourcegraph/issues/3208
- [x] Write script to query our current GQL API for organizations that have created saved searches so we can gather feedback from https://app.hubspot.com/contacts/2762526/company/419771425.
- [ ] Implement updated designs https://app.zeplin.io/project/5ca3ab5ba1b13978edb206e1/screen/5ca3ab79e249f005dc97fa7d
- [ ] Implement a way to send notifications (stretch): 
  - to a webhook URL (more important)
  - to a list of emails 
  - (existing) to the owner (org/user) of the saved search via email
  - (existing) to the owner (org/user) of the saved search via the Slack webhook URL defined in their settings

Customers: https://app.hubspot.com/contacts/2762526/company/419771425 https://app.hubspot.com/contacts/2762526/company/864034457
