### ISSUE TITLE
Code modification 3.6 Tracking Issue

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#3483]
**Goals**
- MVP search-and-replace functionality (backend and client PR integration)

**Work items**
- [x] Add backend Replacer service (analog to Searcher) #3580
- [x] Stream back results (diff content) for change previews #3580
- [x] Add diff generation support for external replacer tool(s)
- [x] A Sourcegraph CodeMod extension
  - Issue PRs: https://github.com/sourcegraph/pull-request-extension-exp/pull/1
  - Run a CodeMod Query and patch on PR: https://github.com/sourcegraph/pull-request-extension-exp/pull/4
  - PR window to fill out commits and PR metadata. https://github.com/sourcegraph/pull-request-extension-exp/pull/4
- [x] Frontend previews w/ `replace:` qualifier (GQL) #4464

Proposal Document: https://docs.google.com/document/d/14A0bfQ9Nef2JBmovlCrIRalTEc_U14K2roQjHKnOvzo

[**Figma mocks**](https://www.figma.com/file/hAZG4YTH7OmJKob8cxoOcNlh/Large-scale-code-modification?node-id=0%3A1)
