### ISSUE TITLE
Integrations quality 3.4 tracking issue

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#3485]
- **The core features of browser extension are stable on GitHub**
    - Code intelligence works reliably and quickly
        - [ ] GitHub code intelligence always works after a soft page load https://github.com/sourcegraph/sourcegraph/issues/750
        - [x] The browser extension works reliably on GitHub PRs https://github.com/sourcegraph/sourcegraph/issues/3480, https://github.com/sourcegraph/sourcegraph/issues/3491 🏃 
        - [ ] Code intelligence works on snippets https://github.com/sourcegraph/sourcegraph/issues/3105, https://github.com/sourcegraph/sourcegraph/issues/771
        - [ ] Code intelligence works on GitHub blame views https://github.com/sourcegraph/sourcegraph/issues/3295
        - [ ] Comments are not detected as code views https://github.com/sourcegraph/sourcegraph/issues/3110
    - Injected UI elements are styled appropriately and behave correctly
        - [ ] There is a "View file" button on rendered markdown files https://github.com/sourcegraph/sourcegraph/issues/753
        - [ ] Command palette is correctly injected and styled even when unauthed https://github.com/sourcegraph/sourcegraph/issues/1584
    - Core extension features work reliably and quickly
        - [x] Extension context evaluation is efficient https://github.com/sourcegraph/sourcegraph/issues/3192
        - [ ] Decorations implementation is efficient
            - [x] DOM functions are well tested https://github.com/sourcegraph/sourcegraph/issues/3321
            - [ ] `applyDecorations()` is well tested
            - [ ] Refactor decorations implementation https://github.com/sourcegraph/sourcegraph/issues/3285
        - [ ] Text field completion is efficient #3433, #3461
- **The browser extension can be set up and used easily by enterprise customers**
    - The browser extension gracefully handles auth proxy timeout  https://github.com/sourcegraph/sourcegraph/issues/3440
        - [x] Improve error handling of requests to the GraphQL backend https://github.com/sourcegraph/sourcegraph/pull/3292 🏃
- **The core browser extension codebase is sane and well-tested**
    - [x] Selections are specific to a code view https://github.com/sourcegraph/sourcegraph/pull/2937
    - [ ] `FileInfo` does not allow invalid states https://github.com/sourcegraph/sourcegraph/issues/3107
    - [x] There is only one way to specify a code view resolver https://github.com/sourcegraph/sourcegraph/issues/3271
    - [x] The abstraction layer `client/browser/src/browser` is removed in favour of the web extension polyfill https://github.com/sourcegraph/sourcegraph/issues/3005, https://github.com/sourcegraph/sourcegraph/issues/3200 🏃 
    - [ ] Errors are not intentionally swallowed https://github.com/sourcegraph/sourcegraph/issues/3085
    - [x] Stylelint is enabled https://github.com/sourcegraph/sourcegraph/issues/2517
    - [x] Build does not emit Typescript errors https://github.com/sourcegraph/sourcegraph/issues/2765

**Comment by felixfbecker** [comment]
@ryan-blunden Summarized improvements of 3.4 iteration:
- Fixed bugs around code intelligence not working in some cases on GitHub
- Fixed performance issues (page becoming unresponsive on large PRs)
- Overhauled error handling of talking to Sourcegraph instances, issues like wrong Sourcegraph instance or unknown repositories should be better handled now
  - Browser extension does no longer fallback to sourcegraph.com (this didn't fully work anyway and only caused confusing errors)
- Added a lot of tests for DOM interactions
- Refactored to use more modern browser extension APIs (this allows us to add more features faster in the future)
