### ISSUE TITLE
Implement usage statistics and audit logging

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#3583]
**Background**
We currently provide high-level, aggregate usage statistics to site admins and users (such as a count of daily, weekly, and monthly active users) as well as some individual aggregate metrics (such as a flag for a user's latest activity).

Going forward, we'd like to be able to provide more context to admins around historical usage, both for tracking product usage (e.g. how many times a user logged in in a given week, rather than just capturing the "latest" time) and for audit logging (e.g. who most recently made updates to the site config, etc.).

**Approach**
We won't be able to enumerate every possible metric a priori, implying that an instance would need to be able to record arbitrary event logs. Redis Streams would be an ideal way to accomplish this (per discussions with @tsenart ). 

**Implementation**

(HIGHLY WIP)

- [ ] Update to Redis 5.0+
  - [ ] Update all relevant Go libraries
- [ ] Write migrations (as needed for upgrades from previous Sourcegraph versions)
- [ ] Refactor `usagestats` package 
  - [ ] Remove most user-level metrics (such as the new stage metrics)
  - [ ] Begin logging whitelisted user actions via Redis Streams (authenticated users only?)
  - [ ] Replace event handlers and usage stats lookups to aggregate Stream data (versus incrementing/accessing user-level data)
  - [ ] If necessary on 25,000 user test instance, implement caching
- [ ] Add audit logging
  - [ ] Add new audit log site-admin page that aggregates account, authentication, and security-related events (specific list TBD)
  - [ ] Add GraphQL layer
  - [ ] Only store 7 days of history on free and OSS instances, 30 days on Enterprise, and unlimited on Unlimited
- [ ] [stretch] Provide option to use external database for Unlimited instances

**Comment by dadlerj** [comment]
@tsenart you've clearly done some thinking on this, and mentioned it would be valuable for core services use as well. If you can give any advice on how you'd get started, let me know. If I recall correctly, step 1 was updating to the latest version of Redis (and the various Redis libraries)?

**Comment by tsenart** [comment]
> If you can give any advice on how you'd get started, let me know. If I recall correctly, step 1 was updating to the latest version of Redis (and the various Redis libraries)?

Yep, that's what I suggest we do. The Implementation plan looks good to me.

**Comment by nicksnyder** [comment]
@unknwon is interested and available to work on this as part of 3.8 so it would be nice to finalize requirements and implementation plan here. He is going to be not working for 2 days and then will be in CST+8 for two weeks.

@dadlerj can you more clearly define the requirements and desired outcome?

@tsenart since it seems like you thought about this somewhat already (and it does seem to be within the realm of concern for @sourcegraph/core-services, it would be ideal if you could help finalize the design before your vacation (is there any context missing from the issue?) and review the code this iteration (after you are back from vacation).

**Comment by keegancsmith** [comment]
My only concern about redis is we have run into durability issues with it since in the past we mixed cache data with persistent data. I think whatever design we come up with it should contrast it with storing the date in postgres. In particular an audit log is likely not that high write, so may be more appropriate for postgres.

**Comment by tsenart** [comment]
>  In particular an audit log is likely not that high write,

Interesting. In my mind an audit log is very write heavy as it needs to capture almost every event happening in Sourcegraph (i.e. event logging / streams). The analytics use case is requires us capturing a super set of the events an audit log would require, so, with the right design, one could extend things easily.

With that said, I think we should take a step back from this particular solution. I think Redis Streams could definitely be useful, but we should not commit to this before more thoroughly discovering the requirements and problem space.

Additionally, I share @keegancsmith's concerns about Redis durability and after getting more clear product requirements, I propose that we first invalidate Postgres as a viable option (i.e. determine with reasonable confidence that it won't be fit for duty at scale). Here are some resources I'd look into to get started:

- https://docs.google.com/presentation/d/1294AeJ1EZXN6Ae1URD4DqW-ekHIc977atQoMDQnJc_M/edit#slide=id.p6
- https://www.citusdata.com/blog/2018/01/24/citus-and-pg-partman-creating-a-scalable-time-series-database-on-PostgreSQL/

> it would be ideal if you could help finalize the design before your vacation (is there any context missing from the issue?) 

What is the intended scope of this work from a product perspective? The following comes to mind as separate (but possibly inter-related) pieces:

1. Audit logging feature
1. New analytics features / dashboard
1 Infrastructure to support the previous features

We need to spec things out a little more before proceeding. Who owns all of this, what's the desired timeline and what customers / deals are behind it?

**Comment by nicksnyder** [comment]
@dadlerj @christinaforney which one of you owns speccing out the needs here? My working assumption is that @dadlerj should define what metrics we want to collect in the future (to help us make a tech decision) and the we target adding one or two concrete metrics this iteration. As for audit logging, is this our need or a customer need? This kind of feels like two separate problems/solutions that should not be conflated. My intuition is to prioritize the metrics and defer audit logging.

**Comment by keegancsmith** [comment]
> > In particular an audit log is likely not that high write,

> Interesting. In my mind an audit log is very write heavy as it needs to capture almost every event happening in Sourcegraph (i.e. event logging / streams). The analytics use case requires us capturing a super set of the events an audit log would require, so, with the right design, one could extend things easily.

I was thinking of an audit log which captured write actions by users, not write actions by background processes. So this would mostly be around admin actions. If it was an audit log on what our system is doing, then yes this is very high write.

> This kind of feels like two separate problems/solutions that should not be conflated.

Agreed.

> My intuition is to prioritize the metrics and defer audit logging.

:+1:

**Comment by dadlerj** [comment]
Thanks for all of the feedback, everyone!

This is not going to be as pretty as the project scoping docs that Product usually puts together, so please let me know where more info would be helpful!

**Background/problems**

From my point of view, this project is about building a common backend that supports multiple frontend products/use cases, not all of which are needed today.

The problems:

* The current site usage statistics page is built on an extremely brittle and un-extensible redis-based backend. Adding a new metric almost always requires modifying/migrating the redis data structure (and all of the stored data), or adding an entirely new one.

* As a result, capturing any new metrics, or adding any features based on user action aggregation (such as https://github.com/sourcegraph/sourcegraph/issues/3333 which I added a couple iterations ago, https://github.com/sourcegraph/sourcegraph/issues/2069 which Beyang added a few iterations ago, @vanesa's work on https://github.com/sourcegraph/sourcegraph/issues/2348, soon https://github.com/sourcegraph/sourcegraph/issues/5088, and any future work on audit logs) requires:
  1. Adding a new storage backend, new backend event handlers, and new data aggregators (see the churn in the `usagestats` package).
  2. Deciding on a data structure, writing new tests, testing for performance at massive scale.
  3. Adding the new frontend code to custom handle the new event(s).

**Definition of success/Scope**

The concrete outcome I'd like to reach is:

- "All" frontend user actions are logged inside of the Sourcegraph instance. This includes everything from "user viewed a page", to "user clicked a button", to "user hovered over a symbol" — along the lines of a Google Analytics, or what we use BigQuery/Looker for for Sourcegraph.com metrics. These user actions (or "events") that are logged can accept an arbitrary text (or json?) argument.
- "All" is quoted above to indicate that it's not really all events :) — rather, only the things we care about would actually be logged. See [all calls to `eventLogger.log` ](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+eventlogger.log%28) in the frontend code to get a sense for the scale here
- All of these events would pass through a common GraphQL endpoint and event handler on the backend that would add them into the new database.
- All of these events are stored in a backend database containing:
  - `name`: the name of the event
  - `argument` (or whatever): the string argument
  - `url`: the URL on the page when the event was logged
  - `userID`: the user that did the action
  - `anonymousUserID`: a UUID stored in a cookie that we use as a way to aggregate actions by anonymous users (when the instance has `"auth.public": true` set). This is already generated and used in the existing usagestats package.
   - `timestamp`: the timestamp of the action
- From this raw database we could easily aggregate data as needed to generate each of the features/products described above, including:
  - Site usage statistics — e.g. a count of monthly active users would be as simple as: `SELECT COUNT(DISTINCT user_id) FROM events WHERE timestamp > $start_of_month AND timestamp < $end_of_month`
  - Extension usage (@vanesa's project) — a count of unique users by extension would be as simple as `SELECT user_id, argument FROM events WHERE name='ExtensionActivated'` to get the list, then loop over each record to build the list.
  - Audit logs — e.g., a list of actions that match some list of "audit loggable" events, such as `SELECT name, user_id, timestamp FROM events WHERE name IN ('SettingsChanged', 'ConfigChanged', 'RepoViewed',  ...)`

**Out of scope**

Note that actually creating the features/products listed aboved is NOT part of the definition of success — rather, once the data store is available we would begin to add/migrate these. 

Any thoughts?

**Comment by dadlerj** [comment]
To be clear, using redis-streams (or redis at all) is not at all important. I do expect a high write volume, though.

**Comment by nicksnyder** [comment]
Thanks @dadlerj that is really helpful context. What retention policy do you want this kind of data to have? For example, do we only need to keep last X months of data, or do we need to keep a history of all data over all time?

**Comment by dadlerj** [comment]
Great question — I was thinking about this as well:

* We currently only store 93 days of history (to ensure we have at least 3 calendar months of usage metrics).
* Beyond that, it'd be nice to expand a bit for a longer-term view (e.g. 6 months?), but not critical.
* It would be great (but also not critical) if we could allow customers to use an external DB for this data, and if so, to configure their own retention policy.

**Comment by keegancsmith** [comment]
yeah this is high write rate, and traditionally sounds like a "click log" or "access log". So a traditional batch processing system sounds like the correct approach. There are likely quite a few off the shelf open source / paid products for this. I would imagine if we stuck with user generated actions, this would still be small enough for a "dumb" log processing approach to generate the rolled up stats.

**Comment by dadlerj** [comment]
Yep, sounds great — I agree there are a lot of open source projects that could help here (e.g. https://sourcegraph.slack.com/archives/C02FSM7DW/p1563812786001000 and your old thread at https://sourcegraph.slack.com/archives/C0C324C91/p1549627499061000?thread_ts=1549609065.059000&cid=C0C324C91). 

I am not opinionated on what the best solution would be as long as it allows the workflow above. Only key things for me: (1) self-hosted, running inside our docker image, (2) allows custom events.

**Comment by tsenart** [comment]
So, the next steps, I think, would be similar to what the Code Navigation team is doing with LSIF backends: To prototype and evaluate a few options with clear performance and functional requirements at hand.

I would run a set of benchmarks / load tests against these different backends with the event schema that @dadlerj described above, filled with a synthetic (but realistic) data set.

Options I'd consider worth trying first:
- Postgres using [table partitioning](https://www.citusdata.com/blog/2018/01/24/citus-and-pg-partman-creating-a-scalable-time-series-database-on-PostgreSQL/)
- [Clickhouse](https://clickhouse.yandex/)

Note the absence of Redis Streams in this list: That is because that component was always meant to be used as a data-hub (i.e. unified log abstraction, like Kafka) between different potential data producers and consumers in our architecture (i.e. frontend, repo-updater, git-server, etc), never as an ready to use analytics backend by itself. Instead, an analytics service would consume said events produced by other services in the architecture (via Redis Streams) and generate rolled-up analytics using whatever backing store it chooses.

But we don't have to introduce said unified log to reap the benefits of more versatile analytics. The write-path to this analytics service can still be done via RPC, proxied via the frontend API.

In order to accelerate learning with the different backend options, I think we'd benefit from working on such an analytics-service, with a small API, in isolation (i.e. like lsif-server).

Some questions to answer in this exploration phase:
- Does the backend perform at our expected scale and usage patterns?
  - At 80k repos with 500(?) daily active users. What's an upper bound of sustained and peak write rate we'd like to support (events per second)?
  - How much data should/can we retain?
  - What's the time range of queries we'd like to support (i.e. different time buckets)?
  - What's the maximum time we can wait for a query?
- Is it simple enough for our users to operate and maintain?
  - What are the data storage requirements?
  - What are the CPU and memory requirements?
  - Does it need a lot of hand holding?

**Comment by dadlerj** [comment]
Awesome, thanks @tsenart! 

In general, though, I don't want us to over-invest in this project — we have low write volume requirements today, short retention requirements, and it's used for an infrequently used (and honestly, probably nice-to-have) feature. If this isn't going to be the backbone for audit logs, then maybe we just make some incremental improvements instead.

I hear you on planning for the right solution for the future, but timeline and prioritization are the questions. What's the workplan for the approach above? It looks to me like a full iteration?

**Comment by tsenart** [comment]
> In general, though, I don't want us to over-invest in this project — we have low write volume requirements today, short retention requirements, and it's used for an infrequently used (and honestly, probably nice-to-have) feature. If this isn't going to be the backbone for audit logs, then maybe we just make some incremental improvements instead.

That sounds reasonable to me!

> What's the workplan for the approach above? It looks to me like a full iteration?

Perhaps less than a full iteration. I think one of us (@unknwon?) could finish this exploration phase in 1.5 - 2 weeks and then devise a work plan for the implementation phase, which I’d expect to take about as long as the exploration phase, so yes, the whole project I think is likely taking 1 iteration.

**Comment by nicksnyder** [comment]
@tsenart Given the desire not to over invest, do you think it would be fine to just choose an approach and go with it? My personal bias would be PostgreSQL (to avoid adding new tech to our stack). Is the frontend the right service to add this to, or should we have a completely separate "metrics" service?

**Comment by tsenart** [comment]
> Given the desire not to over invest, do you think it would be fine to just choose an approach and go with it?

I feel reticent to do this without some short period of testing with a large scale data-set. It should not take long to verify the performance characteristics of each approach. We can do it without writing much code at all: Just create a schema, load data (e.g. a dump of our BigQuery data set) and run a bunch of queries at a given rate.

> My personal bias would be PostgreSQL (to avoid adding new tech to our stack).

Mine too, with the scale caveat. Clickhouse, on the other hand, could unlock capabilities we don't currently have, since it's just so much faster for the analytics use case. To be considered.

> Is the frontend the right service to add this to, or should we have a completely separate "metrics" service?

I think an analytics / metrics service is best. The frontend would just relay RPCs to it.

**Comment by nicksnyder** [comment]
Sounds good. To be clear, I didn't mean to imply that we would skip testing/validation for PostgreSQL, just that we might be able to decide to skip testing other approaches like Clickhouse if we can validate that PostgreSQL will meet our needs.

**Comment by nicksnyder** [comment]
I chatted with @unknwon yesterday and he is going to share his plan for testing scale of PostgreSQL. Here are our rough notes from our convo:

Goal: test perf of PostgreSQL at $CUSTOMER scale
- Create test schema
- Describe how you are going to generate test data
- Describe how much test data and how you arrived at that amount
- Describe what you are going to measure
  - Latency inserting new row in large table
    - What is acceptable? <<100ms(?)
  - Latency dropping oldest day of rows
    - What is acceptable? <<1s(?)
  - Latency of example query (what is a representative example?)
    - What is acceptable? Ask @dadlerj.

**Comment by dadlerj** [comment]
Perf is actually not a huge issue/concern on my end. There's no scale issue currently, and I don't think there would be that big of an increase in the volume of events logged in the new world. 

My personal definition of success is all around reducing the system's brittleness and complexity of adding new metrics. Latency on inserting/dropping (and to a lesser degree, querying) shouldn't be seen as a big user priority, but feel free to investigate if it's an eng priority!

**Comment by dadlerj** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/5486
