### ISSUE TITLE
Tracking: Blank Page whitescreen issue

### ISSUE THREAD

**Issue by jasongornall** [sourcegraph/sourcegraph#35874]
### Plan

Summary tracking ticket for remaining work with white-screens during deployment

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/35636 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35634 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35637 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
