### ISSUE TITLE
3.40.1 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#36219]
# 3.40.1 managed instances upgrade

These [managed instances](../../cloud/devops/managed/index.md) upgrades are scheduled for **[Jun 2, 2022, 6:00 PM (UTC)](https://time.is/1800_2_Jun_2022_in_UTC?One%20working%20day%20after%203.40.1%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../cloud/devops/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com) @mucles
- [x] Upgrade [rctest.sourcegraph.com](https://rctest.sourcegraph.com) @filiphaftek 
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no  demos scheduled for the hour of the upgrade. 

## Upgrade customer managed instances

- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528 @filiphaftek 
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532 @filiphaftek 
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542 @filiphaftek 
- [x] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542 @filiphaftek 
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041 @filiphaftek 
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547 @filiphaftek 
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282 @filiphaftek 
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285 @filiphaftek 
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581 @kalanchan 
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/537 @mucles
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/820 @mucles
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/814 @mucles 
- [x] Upgrade second instance for https://github.com/sourcegraph/customer/issues/820 @mucles
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/774 @filiphaftek 
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/956 @daxmc99 
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/769 @filiphaftek 

---

Also see [3.40.1 patch release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/36218)``

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sanderginn** [comment]
Blocked until we have a tag `3.40.1` in https://github.com/sourcegraph/deploy-sourcegraph-docker

**Comment by unknwon** [comment]
Sourcegraph 3.40.1 has been published

**Comment by filiphaftek** [comment]
All instances ready.
