### ISSUE TITLE
logging(gitstart) tracking issue: migrate graphqlbackend to use sourcegraph/log

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#36382]
## Problem statement

The `graphqlbackend` layer in Sourcegraph's `frontend` service has a lot of log15 usage. As a core entrypoint to many parts of Sourcegraph, having this layer migrated could help speed adoption of the new logging library.

## Success criteria

All 85 usages of log15 in `cmd/frontend/graphqlbackend` are replaced with usages of appropriately scoped loggers.

https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Ecmd/frontend/graphqlbackend+log15&patternType=literal

## Implementation details

Most usages here fall in one of two places:

1. a `resolver` struct function
2. a helper function

In case 1, the resolver struct should hold a reference to a `log.Logger`. In case 2, the helper should accept a logger parameter.

## Tracked issues

@gitstart-sourcegraph: __1.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37586  __1.50d__
  - [x] (🏁 40 days ago) https://github.com/sourcegraph/sourcegraph/issues/37398  __1.00d__
  - [x] (🏁 65 days ago) https://github.com/sourcegraph/sourcegraph/issues/37399  __0.50d__

Completed: __1.50d__
- [x] (🏁 64 days ago) https://github.com/sourcegraph/sourcegraph/issues/33192  __1.50d__ 🛠️

**Comment by bobheadxi** [comment]
Closing this - I am going to rewrite this as a smaller set of tasks
