### ISSUE TITLE
3.40.2 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#36791]
# 3.40.2 managed instances upgrade

These [managed instances](../../admin-exp/devops/managed/index.md) upgrades are scheduled for **[Jun 10, 2022, 6:00 PM (UTC)](https://time.is/1800_10_Jun_2022_in_UTC?One%20working%20day%20after%203.40.2%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../admin-exp/devops/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [ ] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [ ] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.

## Upgrade customer managed instances

- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/537
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/820
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/814
- [ ] Upgrade second instance for https://github.com/sourcegraph/customer/issues/820
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/774
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/956

---

Also see [3.40.2 patch release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/36790)

**Comment by unknwon** [comment]
Superseded by #37184
