### ISSUE TITLE
Reduced isolation deployments for executor

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#36837]
Implements [RFC 696: Reduced isolation deployments for executor](https://docs.google.com/document/d/16SVTBbuqAc2RizJBZgBRCfv5fsMVhR_a2QrIHnEh5T0).

### Plan

See tracked issues as well as the timeline section within the RFC, which we will continue to update for expected deliverables.

### Tracked issues

@efritz

- [ ] https://github.com/sourcegraph/sourcegraph/issues/36838    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36839    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36840    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36844    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36845    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36846    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36847    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36848    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)

@eseliger

- [ ] https://github.com/sourcegraph/sourcegraph/issues/36838    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36839    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36840    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36844    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36845    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36846    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36847    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36848    🏳️ [Executors 1 - easy to deploy self-hosted](https://github.com/sourcegraph/sourcegraph/milestone/203)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
