### ISSUE TITLE
Code Security Team 🐅 Tracking Issue: lockfile-indexing-based dependency search

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#36979]
### TODO

- [ ] Policy support for lockfile indexing (i.e. "index these repos at HEAD every 15min")
- [ ] Build out lockfile indexing for Yarn
  - First Yarn (because we can everything from `yarn.lock`,)
  - Build parser for `yarn.lock` that creates a full tree
  - Persist _tree_ to database (not a flat list)
  - Save metadata about indexing operation ("indexed at commit f00 at 12:45, wth
    full graph")
- [ ] Ensure correct data is saved for other languages
  - For Python/Go: if we can't reconstruct full tree, only persist and return direct dependencies
- [ ] Allow querying of dependency tree on service layer (i.e. not via search interface yet)
  - direct only
  - level 1/2/3
- [ ] Add lockfile indexing for Javen with Maven/`pom.xml`
  - See Olaf's idea for creating full tree by shelling out to maven.
- [ ] Retention policy support for lockfile indexing (i.e. "delete these lockfile graphs after 3 weeks")

- [ ] Create an admin page/repo page that gives overview of lockfile indexing status
- [ ] Write docs on how to start lockfile indexing
- [ ] Turn off lazy dependency search and only use previously-persisted results from lockfile indexing (alert user?)

- [ ] Clean up `dependenciesSource` duplication between `internal/repos/depdencies.go` and `cmd/gitserver/server/vcs_dependencies_syncer.go`

### What's missing from this list

These things still need to be done (list above is mostly concerned with "backend service" level of things):

- Define how exactly we will query dependencies via search (`repo:deps(foo level=1)` or `dependencies:(foo level=1)`?)
- Define what search results look like
- Implement new search result type (involve search product)
- Implement new search query syntax (involve search product)
- Communicate to user when no indexing has happened yet

### Notes

[Olaf's idea for creating full tree/graph for Maven/`pom.xml`](https://sourcegraph.slack.com/archives/C032G1CLM7X/p1654005016448169):

> Idea for Java dependencies search: support only pom.xml files and implement a
> lockfile parser that shells out to mvn dependency:tree to get the full
> dependency graph. There are options to emit structured XML files or graphviz dot
> files. Maven is a declarative build tool so it should be safe to invoke this
> command unlike the equivalent functionality for Gradle, which requires arbitrary
> code execution
> https://gist.github.com/olafurpg/d434a4cdefd7e92e30d2d1876cd48efb
