### ISSUE TITLE
Tracking: MVP - Lockfile-indexing-based dependency search

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#37012]
### Context

We're iterating ton a dependency graph workflow to help security engineering and development teams triage and remediate vulnerabilities faster. See the problem we want to solve in ([PD 35 WIP - Dependency Graph for code security](https://docs.google.com/document/d/1Bq2SAx-FXxzW0YFbkIYoPS6bvy-LvlvZMyOTNUI1NV0/edit#heading=h.z5ozjpfzh2yl)).

### MVP

In the MVP, we want to let users navigate the dependency graph of their code in an iterative manner. Instead of just showing a flat list of dependencies/dependents for `repo A`, you can:
- see the list of direct dependencies/dependents of `repo A`
- see the list of transitive dependencies/dependents of `repo A` at depth `n`. Exact syntax TBD, eg.`dependencies:(sourcegraph depth=3)`.
- easily navigate along the `repo A` -> `repo B` -> `repo C` dependency/dependents path
- search for code predicates inside any of those scopes

This partially answer: "how is my code affected by dependency on `repo A`? What are optimal resolution steps?". It's a first step towards our goal to answer questions such as:

> Does my repo depend directly on X? If not, what dependencies of my repo bring X into scope?

In the MVP, we will focus on javascript, golang, python (in order), and Java/Maven because we can use lockfiles and already have a lot of building blocks ready. We want to move to Java/Gradle next, using precise code intel data, because that's what's most valuable to customers.

_UI is ultimate TBD, for illustration:_

![Image](https://user-images.githubusercontent.com/25070988/173081457-2d0a1fa9-461f-4577-8150-634faf791fba.png)

Design discussions are happening in this [RFC](https://docs.google.com/document/d/1nRs20p_-ImyRXt9nZa5WjwJIaRfiXTyOYHOL6i1DFUA/edit#).

### Plan

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37010    🏳️ [Code security MVP](https://github.com/sourcegraph/sourcegraph/milestone/201)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/37011    🏳️ [Code security MVP](https://github.com/sourcegraph/sourcegraph/milestone/201)

@malomarrec

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37007    🏳️ [Code security MVP](https://github.com/sourcegraph/sourcegraph/milestone/201)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/37009    🏳️ [Code security MVP](https://github.com/sourcegraph/sourcegraph/milestone/201)

@mrnugget

Completed
- [x] (🏁 330 days ago) https://github.com/sourcegraph/sourcegraph/issues/36979    🏳️ [Code security MVP](https://github.com/sourcegraph/sourcegraph/milestone/201)

@quinnkeast

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37007    🏳️ [Code security MVP](https://github.com/sourcegraph/sourcegraph/milestone/201)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/37009    🏳️ [Code security MVP](https://github.com/sourcegraph/sourcegraph/milestone/201)
