### ISSUE TITLE
3.41.0 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#37184]
# 3.41.0 managed instances upgrade

These [managed instances](../../admin-exp/devops/managed/index.md) upgrades are scheduled for **[Jun 21, 2022, 6:00 PM (UTC)](https://time.is/1800_21_Jun_2022_in_UTC?One%20working%20day%20after%203.41%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../admin-exp/devops/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [x] Upgrade [rctest.sourcegraph.com](https://rctest.sourcegraph.com)
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.

## Upgrade customer managed instances

- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/537
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/820
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/814
- [x] Upgrade second instance for https://github.com/sourcegraph/customer/issues/820
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/774
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/956
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/769
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/1038
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/1046
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/1044
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/1056

---

Also see [3.41.0 release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/37183)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by michaellzc** [comment]
it's done
