### ISSUE TITLE
DevX Q2B2 release tool papercuts  tracking issue

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#37355]
### Problem

There is a lengthy backlog of papercut issues with the release process - https://github.com/orgs/sourcegraph/projects/240/views/2 - many of which are quick(ish) fixes, and make the process unnecessarily frustrating.

### Scope

Boundaries:

- Only the issues tracked here.

Out of scope:

- Major rewrites and significant new features (e.g. https://github.com/sourcegraph/sourcegraph/issues/38346)

### Definition of done

All issues on this tracking issue are resolved.

### Tracked issues

@bobheadxi

Completed
- [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/issues/37460 

@davejrt: __8.50d__

Completed: __8.50d__
- [x] (🏁 16 days ago) https://github.com/sourcegraph/sourcegraph/issues/30586  __1.00d__
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/30588  __1.00d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/31737  __1.00d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/32448  __1.00d__
- [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/issues/31745  __0.50d__
- [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/issues/31772  __1.00d__
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/31755  __1.00d__
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/31742  __1.00d__
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/31740  __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by bobheadxi** [comment]
Current participants: @davejrt @bobheadxi
