### ISSUE TITLE
Server-side Beta - post-release go-to-market tracking issue

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#37422]
Tracking the work items that need to happen in support of the release:
- [x] update availability and compatibility in handbook
- [x] add enablement page
- [x] update FAQ
- [ ] add video to pages https://github.com/sourcegraph/sourcegraph/issues/34251
- [x] remind CEs to share blog post announcement with Batch Changes customers
- [x] when demo is update, remind CEs to show SSBC in demos
- [x] post in #sales
- [x] share release tweet in batch changes channel to re-tweet
- [ ] @malomarrec directly contact
  - [x] https://github.com/sourcegraph/accounts/issues/565
  - [ ] https://github.com/sourcegraph/accounts/issues/580
  - [x] https://github.com/sourcegraph/accounts/issues/8263
  - [x] https://github.com/sourcegraph/accounts/issues/537
  - [x] https://github.com/sourcegraph/accounts/issues/542
  - [x] https://github.com/sourcegraph/accounts/issues/532
  - [x] https://github.com/sourcegraph/accounts/issues/6859
  - [x] https://github.com/sourcegraph/accounts/issues/3439 via Owen
  - [ ] https://github.com/sourcegraph/accounts/issues/570 via  David R
  - [ ] https://github.com/sourcegraph/accounts/issues/287 via Dan R
  - [x] https://github.com/sourcegraph/accounts/issues/547

**Comment by malomarrec** [comment]
Hello from bot
