### ISSUE TITLE
DevX: `sourcegraph/log` migration tracking issue

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#37586]
### Plan

We want to migrate _all_ logging in `sourcegraph/sourcegraph` to the new logging library introduced in https://github.com/sourcegraph/sourcegraph/issues/33192, [`sourcegraph/log`](https://github.com/sourcegraph/log) ([docs](https://docs.sourcegraph.com/dev/how-to/add_logging)).

This will mostly be done with the assistance of GitStart.

- [Logging migration dashboard](https://k8s.sgdev.org/insights/dashboards/ZGFzaGJvYXJkOnsiSWRUeXBlIjoiY3VzdG9tIiwiQXJnIjo3MjcyNTN9)
- [Gitstart](https://app.gitstart.com/clients/sourcegraph/tickets?project=SourceGraph%20DevX)

### Tracked issues

@gitstart-sourcegraph: __9.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37778  __1.00d__ 🛠️
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/37899  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/40896  __1.00d__
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/37899  __1.00d__

Completed: __9.50d__
- [x] (🏁 64 days ago) https://github.com/sourcegraph/sourcegraph/issues/33192  __9.50d__ 🛠️

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by jhchabran** [comment]
Closing this in favour of https://github.com/sourcegraph/sourcegraph/issues/40896
