### ISSUE TITLE
WIP: FP/DevX Client Flakes Spike

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#37616]
Tracking issue for the joint effort in addressing the client flakes situation covered over https://docs.google.com/document/d/1CHa6kMVpJF6Si75zyU9MV7xHf1VZ6nViLiOZFr8PkyQ/edit# 

This is a joint effort in between the DevX and FrontendPlatform team. 

### Tracked issues

@bobheadxi

Completed
- [x] (🏁 62 days ago) https://github.com/sourcegraph/sourcegraph/issues/37617 

@burmudar

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37826  🛠️
  - [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/37613 

Completed
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/37613 

@jhchabran

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37615 

Completed
- [x] (🏁 59 days ago) https://github.com/sourcegraph/sourcegraph/issues/37618 
- [x] (🏁 44 days ago) https://github.com/sourcegraph/sourcegraph/pull/38718 

@kalanchan

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37615 

@umpox

Completed
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/37662 

@valerybugakov

Completed
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/37661 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/issues/37665 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/issues/37660 
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/issues/37663 
- [x] (🏁 46 days ago) https://github.com/sourcegraph/sourcegraph/issues/37666 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by jhchabran** [comment]
cc @quinnhare

**Comment by valerybugakov** [comment]
Linking another fixed issue here for visibility https://github.com/sourcegraph/sourcegraph/issues/37548

**Comment by valerybugakov** [comment]
@quinnhare, I removed your team label because it breaks the tracking issue links to sub-tasks

**Comment by jhchabran** [comment]
#37615 is nearly complete, closing this to clean things up.
