### ISSUE TITLE
DevX: Q2B2 Codeintel OpenTelemetry and s2 observability

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#37778]
### Problem

Cloud instances are lacking observability tooling (_make Cloud the preferred deployed method_), and inconsistent tracing export is a long-standing problem on self-hosted instances (_provide a world-class admin experience_).

### Scope

- **Boundaries**
  - We target [sourcegraph.sourcegraph.com](https://github.com/sourcegraph/customer/issues/1046) (not all Cloud instances), and explore feasibility for sourcegraph.com
  - We will not touch anything that isn't related to CodeIntel, _unless_ absolutely necessary/tangential (e.g. API change)
  - We will not add vendor-specific integrations within the code (e.g. vendor-specific push)
- **Definition of done**
  - OTel Collector is deployed and collecting OTel data
    - Data is then pushed into a service provider HoneyComb ~and Grafana~
    - Prove that we can send data to other provider, in this case ~Grafana~ Jaeger
  - Codeintel error logs are reported to Sentry, and Cloud + codeintel makes an assessment on its usefulness in operating   Cloud instances
  - ~Codeintel shares an experience report of having such observability in place, and we publicize in relevant channels and newsletter~

### Tracked issues

 

@bobheadxi

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37901 

Completed
- [x] (🏁 82 days ago) https://github.com/sourcegraph/sourcegraph/issues/27386 
- [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/pull/38499 
- [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/issues/38232  🐛
- [x] (🏁 67 days ago) https://github.com/sourcegraph/sourcegraph/pull/39002 
- [x] (🏁 66 days ago) https://github.com/sourcegraph/sourcegraph/issues/38819 
- [x] (🏁 34 days ago) https://github.com/sourcegraph/sourcegraph/issues/37902 
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/39174 
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/37900 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/41024 
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/38198 
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/37903 
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/37907 

@davejrt

Completed
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/38198 

@gitstart-sourcegraph: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/40896  __1.00d__ 🛠️
  - [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/37899  __1.00d__

Completed: __1.00d__
- [x] (🏁 95 days ago) https://github.com/sourcegraph/sourcegraph/issues/33192  __1.00d__ 🛠️
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/37586  __1.00d__

@jhchabran

Completed
- [x] (🏁 94 days ago) https://github.com/sourcegraph/sourcegraph/issues/33240  🛠️
- [x] (🏁 73 days ago) https://github.com/sourcegraph/sourcegraph/issues/26981 (PRs: ~[#38411](https://github.com/sourcegraph/sourcegraph/pull/38411)~)
- [x] (🏁 30 days ago) https://github.com/sourcegraph/sourcegraph/issues/37905 (PRs: ~[#38499](https://github.com/sourcegraph/sourcegraph/pull/38499)~)
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/37958 

@plibither8

Completed
- [x] (🏁 73 days ago) https://github.com/sourcegraph/sourcegraph/issues/26981 (PRs: ~[#38411](https://github.com/sourcegraph/sourcegraph/pull/38411)~)

@sanderginn

Completed
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/38198 

@valerybugakov

Completed
- [x] (🏁 73 days ago) https://github.com/sourcegraph/sourcegraph/issues/26981 (PRs: ~[#38411](https://github.com/sourcegraph/sourcegraph/pull/38411)~)
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/37907 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by bobheadxi** [comment]
cc @vrto

**Comment by jhchabran** [comment]
cc @vrto, we did another pass with @bobheadxi and trimmed down our first draft into this ticket

**Comment by bobheadxi** [comment]
Helpful links:

- Initial tracing implementation exploration: https://github.com/sourcegraph/devx-scratch/blob/main/2022/observability/log.snb.md#2022-06-23-opentelemetry-trace-export-exploration
- Scratch docs: https://docs.google.com/document/d/1B3jE5nbAngt_c7NYynmDXWmHPoNCv_4cFG9ttc4ZXPI/edit#

**Comment by vrto** [comment]
@jhchabran @bobheadxi I commented on the [original bet scratch doc](https://docs.google.com/document/d/1B3jE5nbAngt_c7NYynmDXWmHPoNCv_4cFG9ttc4ZXPI/edit#), I'm mainly concerned with the items in "definition of done".

**Comment by jhchabran** [comment]
@bobheadxi we're invited you to a quick sync call later on today, quick heads up!

**Comment by bobheadxi** [comment]
Current participants: @bobheadxi @jhchabran @davejrt

**Comment by bobheadxi** [comment]
Current participants: @bobheadxi @jhchabran @davejrt

**Comment by bobheadxi** [comment]
@jhchabran you're most familiar with the work here, I'm reassigning this issue to you as I prepare to transition to Cloud :)
