### ISSUE TITLE
Compute Insights v1 Tracking issue

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#37857]
### Plan

- Roadmap issue: https://github.com/sourcegraph/sourcegraph/issues/33632
- [RFC](https://docs.google.com/document/d/1Vktm_9CtSoF8zjye5YwCrfaLm8srktf0fccbM-3bcOA/edit)
- [Figma](https://www.figma.com/file/DqZHetdfqHSVzzWtyfjOmr/?node-id=246%3A11)

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/39075 
- [x] https://github.com/sourcegraph/sourcegraph/issues/39162 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39915 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39916  🐛
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39912 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/40095 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/41192  🧶

Completed
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/issues/39913  🐛

@AlicjaSuska

Completed
- [x] (🏁 77 days ago) https://github.com/sourcegraph/sourcegraph/issues/37923    🏳️ [Insights iteration 21](https://github.com/sourcegraph/sourcegraph/milestone/163)
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/38836    🏳️ [Insights iteration 22](https://github.com/sourcegraph/sourcegraph/milestone/164)

@CristinaBirkel

Completed
- [x] (🏁 82 days ago) https://github.com/sourcegraph/sourcegraph/issues/37864    🏳️ [Insights iteration 21](https://github.com/sourcegraph/sourcegraph/milestone/163)
- [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/issues/37867    🏳️ [Insights iteration 21](https://github.com/sourcegraph/sourcegraph/milestone/163)
- [x] (🏁 67 days ago) https://github.com/sourcegraph/sourcegraph/issues/38872  🐛   🏳️ [Insights iteration 22](https://github.com/sourcegraph/sourcegraph/milestone/164)
- [x] (🏁 64 days ago) https://github.com/sourcegraph/sourcegraph/issues/37866    🏳️ [Insights iteration 22](https://github.com/sourcegraph/sourcegraph/milestone/164)
- [x] (🏁 64 days ago) https://github.com/sourcegraph/sourcegraph/issues/38352    🏳️ [Insights iteration 21](https://github.com/sourcegraph/sourcegraph/milestone/163)

@coury-clark

Completed
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/37949    🏳️ [Insights iteration 21](https://github.com/sourcegraph/sourcegraph/milestone/163)
- [x] (🏁 75 days ago) https://github.com/sourcegraph/sourcegraph/issues/37173    🏳️ [Insights iteration 21](https://github.com/sourcegraph/sourcegraph/milestone/163)
- [x] (🏁 75 days ago) https://github.com/sourcegraph/sourcegraph/issues/37175    🏳️ [Insights iteration 21](https://github.com/sourcegraph/sourcegraph/milestone/163)
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/issues/38433    🏳️ [Insights iteration 23](https://github.com/sourcegraph/sourcegraph/milestone/165)

@leonore

Completed
- [x] (🏁 77 days ago) https://github.com/sourcegraph/sourcegraph/issues/37868    🏳️ [Insights iteration 21](https://github.com/sourcegraph/sourcegraph/milestone/163)

@unclejustin

Completed
- [x] (🏁 69 days ago) https://github.com/sourcegraph/sourcegraph/issues/37966    🏳️ [Insights iteration 21](https://github.com/sourcegraph/sourcegraph/milestone/163)
- [x] (🏁 65 days ago) https://github.com/sourcegraph/sourcegraph/issues/38896    🏳️ [Insights iteration 22](https://github.com/sourcegraph/sourcegraph/milestone/164)
- [x] (🏁 65 days ago) https://github.com/sourcegraph/sourcegraph/issues/37220    🏳️ [Insights iteration 22](https://github.com/sourcegraph/sourcegraph/milestone/164)

@vovakulikov

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37218    🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/37259 
  - [x] (🏁 44 days ago) https://github.com/sourcegraph/sourcegraph/issues/39032  🐛   🏳️ [Insights iteration 23](https://github.com/sourcegraph/sourcegraph/milestone/165)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39643 
  - [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/issues/38832    🏳️ [Insights iteration 23](https://github.com/sourcegraph/sourcegraph/milestone/165)
  - [x] (🏁 44 days ago) https://github.com/sourcegraph/sourcegraph/issues/39032  🐛   🏳️ [Insights iteration 23](https://github.com/sourcegraph/sourcegraph/milestone/165)
  - [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/issues/39917  🐛   🏳️ [Insights iteration 23](https://github.com/sourcegraph/sourcegraph/milestone/165)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27771 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/39064  🧶   🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)

Completed
- [x] (🏁 81 days ago) https://github.com/sourcegraph/sourcegraph/issues/38049    🏳️ [Insights iteration 21](https://github.com/sourcegraph/sourcegraph/milestone/163)
- [x] (🏁 70 days ago) https://github.com/sourcegraph/sourcegraph/issues/37961    🏳️ [Insights iteration 21](https://github.com/sourcegraph/sourcegraph/milestone/163)
- [x] (🏁 68 days ago) https://github.com/sourcegraph/sourcegraph/issues/37965    🏳️ [Insights iteration 22](https://github.com/sourcegraph/sourcegraph/milestone/164)
- [x] (🏁 68 days ago) https://github.com/sourcegraph/sourcegraph/issues/37970    🏳️ [Insights iteration 22](https://github.com/sourcegraph/sourcegraph/milestone/164)
- [x] (🏁 65 days ago) https://github.com/sourcegraph/sourcegraph/issues/37969    🏳️ [Insights iteration 22](https://github.com/sourcegraph/sourcegraph/milestone/164)
- [x] (🏁 65 days ago) https://github.com/sourcegraph/sourcegraph/issues/38344    🏳️ [Insights iteration 22](https://github.com/sourcegraph/sourcegraph/milestone/164)
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/38836    🏳️ [Insights iteration 22](https://github.com/sourcegraph/sourcegraph/milestone/164)
- [x] (🏁 44 days ago) https://github.com/sourcegraph/sourcegraph/issues/39032  🐛   🏳️ [Insights iteration 23](https://github.com/sourcegraph/sourcegraph/milestone/165)
- [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/issues/38832    🏳️ [Insights iteration 23](https://github.com/sourcegraph/sourcegraph/milestone/165)
- [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/issues/39917  🐛   🏳️ [Insights iteration 23](https://github.com/sourcegraph/sourcegraph/milestone/165)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
