### ISSUE TITLE
DevX: Q2B2 DevX product analytics tracking issue

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#37931]
### Problem

We're improving how we collect and aggregate analytics and metrics that are relevant to DevX work.

We need these analytics to better inform DevX team work, and also to be able to better inform external stakeholders about the outcomes of DevX work.

[Scratch doc link.](https://docs.google.com/document/d/1EUQuyBHT6TfmpIWX1Av-nNM4OxGKWcIp_K-rixCjWqQ/edit?usp=sharing)

### Scope

- **Boundaries**
  - Confirm our preferred choice of tooling for analytics (decisions about OkayHQ, Honeycomb)
  - Identify the metrics that we're tracking
  - Transfer metrics from deprecated tooling to our new preferred tooling
  - Idenfity new metrics that we're not yet tracking but we'd like to track
- **Definition of done**
  - We have a clear idea of which metrics we're collecting and which tool to access them
  -  We make metrics available in an accessible location to stakeholders outside of the team
  - **Rollout Plan**
    -  Communicate our preferred tooling for analytics, with explanation for why we're choosing it, and which tools we will be dropping.
    - Communicate which DevX metrics we're tracking and how they might be useful outside of the team
    - Communicate which DevX metrics are informing our decisions internally to the team

### Tracked issues

 

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37808 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/37809 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/40807 

@bobheadxi

Completed
- [x] (🏁 32 days ago) https://github.com/sourcegraph/sourcegraph/issues/37810 

@burmudar

- [ ] https://github.com/sourcegraph/sourcegraph/issues/40806 

@marekweb

- [ ] https://github.com/sourcegraph/sourcegraph/issues/39505 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39512 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by jhchabran** [comment]
thought: we probably should add owners to CI jobs, so we can report who is owning what (please challenge this)

**Comment by bobheadxi** [comment]
Current participants: @marekweb @bobheadxi @kalanchan

**Comment by bobheadxi** [comment]
Current participants: @marekweb @bobheadxi @kalanchan

**Comment by jhchabran** [comment]
Was chatting with @mrnugget this morning and this came up. @marekweb I don't know where you're putting your wip work, but I think that if it's not already in there (though I think we mentioned it quite a few times in our previous runs on this topic) it should be :D 

> “time from commit pushed to github to all checks done”

**Comment by bobheadxi** [comment]
@marekweb has there been any update on this?

**Comment by marekweb** [comment]
We basically paused these for now due to low priority but I could it back up in a later bet or in a cooldown period.
