### ISSUE TITLE
RFC 697: Multiple version upgrades - Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#38038]
### Plan

This issue tracks progress against the proposal [RFC 697: Multiple version upgrades](https://docs.google.com/document/d/1eNiwzWZmfpvzFhs9IDcM7Sbchv_Hm8Uj-6bI-3TDlvg).

### Tracked issues

@Brielle-C

- [x] https://github.com/sourcegraph/sourcegraph/issues/40638 
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/41287 

Completed
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/41287 

@Cyberwhiz5000

- [x] https://github.com/sourcegraph/sourcegraph/issues/40638 
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/41287 

Completed
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/41287 

@Joelkw

- [x] https://github.com/sourcegraph/sourcegraph/issues/40638 
  - [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/40700    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)

Completed
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/40700    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)

@beyang

- [x] https://github.com/sourcegraph/sourcegraph/issues/40638 
  - [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/40705 

Completed
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/40705 

@chrismwendt

- [x] https://github.com/sourcegraph/sourcegraph/issues/40638 
  - [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/40702 

Completed
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/40702 

@coury-clark

- [x] https://github.com/sourcegraph/sourcegraph/issues/40638 
  - [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/40700    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)

Completed
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/40700    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)

@efritz

- [x] https://github.com/sourcegraph/sourcegraph/issues/40638 
  - [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/38054 
  - [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/issues/40642 (PRs: ~[#40395](https://github.com/sourcegraph/sourcegraph/pull/40395)~)
  - [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/40644 
  - [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/40645 
  - [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/40646 
  - [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/40647 
  - [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/40648 
  - [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/40649 
  - [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/40665 
  - [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/40666 
  - [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/pull/40668 
  - [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/pull/40669 
  - [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/pull/40672 
  - [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/issues/40738 (PRs: ~[#40758](https://github.com/sourcegraph/sourcegraph/pull/40758)~, ~[#40759](https://github.com/sourcegraph/sourcegraph/pull/40759)~)
  - [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/issues/40740 (PRs: ~[#40767](https://github.com/sourcegraph/sourcegraph/pull/40767)~)
  - [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/40741 (PRs: ~[#40955](https://github.com/sourcegraph/sourcegraph/pull/40955)~)
  - [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/40753 
  - [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/40754 
  - [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/issues/40760 
  - [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/40761 (PRs: ~[#41067](https://github.com/sourcegraph/sourcegraph/pull/41067)~)
  - [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/40762 (PRs: ~[#41067](https://github.com/sourcegraph/sourcegraph/pull/41067)~)
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/40768 (PRs: ~[#41391](https://github.com/sourcegraph/sourcegraph/pull/41391)~)
  - [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/40819 
  - [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/40820 
  - [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/40821 
  - [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/40822 
  - [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/40823 
  - [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/pull/40934 
  - [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/pull/40953 
  - [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/40954 
  - [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/40956 
  - [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/pull/40957 
  - [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/pull/41159 
  - [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/pull/41225 
  - [x] (🏁 17 days ago) https://github.com/sourcegraph/sourcegraph/pull/41238 
  - [x] (🏁 17 days ago) https://github.com/sourcegraph/sourcegraph/pull/41259 
  - [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/pull/41373 
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/41587 
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/41610 
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/41611 
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/41697 

Completed
- [x] (🏁 30 days ago) https://github.com/sourcegraph/sourcegraph/issues/38101 
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/40646 
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/40649 
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/40644 
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/40647 
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/40648 
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/40665 
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/40666 
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/pull/40668 
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/pull/40669 
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/pull/40672 
- [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/issues/40642 (PRs: ~[#40395](https://github.com/sourcegraph/sourcegraph/pull/40395)~)
- [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/issues/38094 
- [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/issues/40740 (PRs: ~[#40767](https://github.com/sourcegraph/sourcegraph/pull/40767)~)
- [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/issues/40738 (PRs: ~[#40758](https://github.com/sourcegraph/sourcegraph/pull/40758)~, ~[#40759](https://github.com/sourcegraph/sourcegraph/pull/40759)~)
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/40819 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/40820 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/40645 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/40823 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/40821 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/40822 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/issues/40760 
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/40754 
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/40753 
- [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/pull/40957 
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/40956 
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/40954 
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/pull/40934 
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/pull/40953 
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/38099 
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/pull/41022 
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/pull/41026 
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/40741 (PRs: ~[#40955](https://github.com/sourcegraph/sourcegraph/pull/40955)~)
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/pull/41070 
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/pull/41072 
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/pull/41073 
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/pull/41071 
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/pull/41074 
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/pull/41075 
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/pull/41076 
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/pull/41081 
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/pull/41080 
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/pull/40958 
- [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/pull/41159 
- [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/pull/41225 
- [x] (🏁 17 days ago) https://github.com/sourcegraph/sourcegraph/pull/41238 
- [x] (🏁 17 days ago) https://github.com/sourcegraph/sourcegraph/pull/41259 
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/38054 
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/40761 (PRs: ~[#41067](https://github.com/sourcegraph/sourcegraph/pull/41067)~)
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/40762 (PRs: ~[#41067](https://github.com/sourcegraph/sourcegraph/pull/41067)~)
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/pull/41373 
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/pull/41390 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/41697 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/40768 (PRs: ~[#41391](https://github.com/sourcegraph/sourcegraph/pull/41391)~)
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/41610 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/41611 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/41587 

@jac

- [x] https://github.com/sourcegraph/sourcegraph/issues/40638 
  - [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/40705 

Completed
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/40705 

@macraig

- [x] https://github.com/sourcegraph/sourcegraph/issues/40638 
  - [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/40702 

Completed
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/40702 

@malomarrec

- [x] https://github.com/sourcegraph/sourcegraph/issues/40638 
  - [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/40703 

Completed
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/40703 

@ryphil

- [x] https://github.com/sourcegraph/sourcegraph/issues/40638 
  - [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/40704 

Completed
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/40704 

@tbliu98

- [x] https://github.com/sourcegraph/sourcegraph/issues/40638 
  - [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/40701 

Completed
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/40701 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
