### ISSUE TITLE
RFC 697: Isolate out-of-band migrations - Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#38094]
### Plan

See [RFC 697: Multiple version upgrades](https://docs.google.com/document/d/1eNiwzWZmfpvzFhs9IDcM7Sbchv_Hm8Uj-6bI-3TDlvg).

Update out of band migrations so that they do not require code outside of a specific allow-list (which excludes things like the gitserver client, and things that transitively include `internal/conf`).

### Tracked issues

@efritz

- [ ] https://github.com/sourcegraph/sourcegraph/issues/38038 
  - [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/38050 (PRs: ~[#39984](https://github.com/sourcegraph/sourcegraph/pull/39984)~, ~[#40113](https://github.com/sourcegraph/sourcegraph/pull/40113)~)
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/38051 (PRs: ~[#40395](https://github.com/sourcegraph/sourcegraph/pull/40395)~)
  - [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/38052 (PRs: ~[#39984](https://github.com/sourcegraph/sourcegraph/pull/39984)~, ~[#40145](https://github.com/sourcegraph/sourcegraph/pull/40145)~)
  - [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/38053 (PRs: ~[#40387](https://github.com/sourcegraph/sourcegraph/pull/40387)~)
  - [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/38555 
  - [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/39508 (PRs: ~[#40168](https://github.com/sourcegraph/sourcegraph/pull/40168)~)
  - [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/pull/39778 
  - [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/pull/39783 
  - [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/pull/39787 
  - [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/pull/40050 
  - [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/pull/40062 
  - [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/pull/40065 
  - [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/40392 (PRs: ~[#40527](https://github.com/sourcegraph/sourcegraph/pull/40527)~)
  - [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/pull/40394 
  - [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/40528 
  - [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/40531 
  - [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/40569 
  - [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/40580 
  - [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/pull/40603 

Completed
- [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/pull/39778 
- [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/pull/39783 
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/pull/39787 
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/pull/40065 
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/pull/40062 
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/pull/40050 
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/39508 (PRs: ~[#40168](https://github.com/sourcegraph/sourcegraph/pull/40168)~)
- [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/38053 (PRs: ~[#40387](https://github.com/sourcegraph/sourcegraph/pull/40387)~)
- [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/pull/40394 
- [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/38555 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/40528 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/40531 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/40569 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/40580 
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/pull/40603 
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/40392 (PRs: ~[#40527](https://github.com/sourcegraph/sourcegraph/pull/40527)~)
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/38050 (PRs: ~[#39984](https://github.com/sourcegraph/sourcegraph/pull/39984)~, ~[#40113](https://github.com/sourcegraph/sourcegraph/pull/40113)~)
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/38052 (PRs: ~[#39984](https://github.com/sourcegraph/sourcegraph/pull/39984)~, ~[#40145](https://github.com/sourcegraph/sourcegraph/pull/40145)~)
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/38051 (PRs: ~[#40395](https://github.com/sourcegraph/sourcegraph/pull/40395)~)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
