### ISSUE TITLE
RFC 697: Migration quality of life improvements - Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#38099]
### Plan

See [RFC 697: Multiple version upgrades](https://docs.google.com/document/d/1eNiwzWZmfpvzFhs9IDcM7Sbchv_Hm8Uj-6bI-3TDlvg).

This issue tracks miscellaneous quality of life improvements of the migrator related to the multiple version upgrade effort.

### Tracked issues

@efritz

- [ ] https://github.com/sourcegraph/sourcegraph/issues/38038 
  - [x] (🏁 54 days ago) https://github.com/sourcegraph/sourcegraph/issues/37794 (PRs: ~[#38110](https://github.com/sourcegraph/sourcegraph/pull/38110)~)
  - [x] (🏁 46 days ago) https://github.com/sourcegraph/sourcegraph/issues/38046 (PRs: ~[#38687](https://github.com/sourcegraph/sourcegraph/pull/38687)~)
  - [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/38217 (PRs: ~[#38917](https://github.com/sourcegraph/sourcegraph/pull/38917)~, ~[#38958](https://github.com/sourcegraph/sourcegraph/pull/38958)~)
  - [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/issues/38740 (PRs: ~[#38777](https://github.com/sourcegraph/sourcegraph/pull/38777)~)
  - [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/38741 (PRs: ~[#38777](https://github.com/sourcegraph/sourcegraph/pull/38777)~)
  - [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/38742 (PRs: ~[#38777](https://github.com/sourcegraph/sourcegraph/pull/38777)~)
  - [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/pull/38959 
  - [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/pull/38984 
  - [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/pull/39768 
  - [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/39839 
  - [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/39863 (PRs: ~[#39851](https://github.com/sourcegraph/sourcegraph/pull/39851)~, ~[#39852](https://github.com/sourcegraph/sourcegraph/pull/39852)~, ~[#39864](https://github.com/sourcegraph/sourcegraph/pull/39864)~, ~[#39865](https://github.com/sourcegraph/sourcegraph/pull/39865)~, ~[#39868](https://github.com/sourcegraph/sourcegraph/pull/39868)~, ~[#39870](https://github.com/sourcegraph/sourcegraph/pull/39870)~)
  - [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/pull/39891 
  - [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/pull/39892 
  - [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/pull/39938 
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/39961 (PRs: ~[#40988](https://github.com/sourcegraph/sourcegraph/pull/40988)~)

Completed
- [x] (🏁 54 days ago) https://github.com/sourcegraph/sourcegraph/issues/37794 (PRs: ~[#38110](https://github.com/sourcegraph/sourcegraph/pull/38110)~)
- [x] (🏁 46 days ago) https://github.com/sourcegraph/sourcegraph/issues/38046 (PRs: ~[#38687](https://github.com/sourcegraph/sourcegraph/pull/38687)~)
- [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/pull/38959 
- [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/pull/38984 
- [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/issues/38740 (PRs: ~[#38777](https://github.com/sourcegraph/sourcegraph/pull/38777)~)
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/38742 (PRs: ~[#38777](https://github.com/sourcegraph/sourcegraph/pull/38777)~)
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/38741 (PRs: ~[#38777](https://github.com/sourcegraph/sourcegraph/pull/38777)~)
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/38217 (PRs: ~[#38917](https://github.com/sourcegraph/sourcegraph/pull/38917)~, ~[#38958](https://github.com/sourcegraph/sourcegraph/pull/38958)~)
- [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/pull/39768 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/39839 
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/pull/39892 
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/pull/39891 
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/39863 (PRs: ~[#39851](https://github.com/sourcegraph/sourcegraph/pull/39851)~, ~[#39852](https://github.com/sourcegraph/sourcegraph/pull/39852)~, ~[#39864](https://github.com/sourcegraph/sourcegraph/pull/39864)~, ~[#39865](https://github.com/sourcegraph/sourcegraph/pull/39865)~, ~[#39868](https://github.com/sourcegraph/sourcegraph/pull/39868)~, ~[#39870](https://github.com/sourcegraph/sourcegraph/pull/39870)~)
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/pull/39938 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/39961 (PRs: ~[#40988](https://github.com/sourcegraph/sourcegraph/pull/40988)~)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
