### ISSUE TITLE
RFC 697: Migrator Mk.2 - Tracking issue

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#38101]
### Plan

See [RFC 697: Multiple version upgrades](https://docs.google.com/document/d/1eNiwzWZmfpvzFhs9IDcM7Sbchv_Hm8Uj-6bI-3TDlvg).

This issue tracks the development of the updated `migrator` service, which will also handle upgrades over multiple versions. Related work will include ensuring schema migrations over multiple versions are possible, and ensuring we also run data migrations in this tool.

### Tracked issues

@efritz

- [ ] https://github.com/sourcegraph/sourcegraph/issues/38038 
  - [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/38044 (PRs: ~[#38111](https://github.com/sourcegraph/sourcegraph/pull/38111)~)
  - [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/38045 (PRs: ~[#36319](https://github.com/sourcegraph/sourcegraph/pull/36319)~)
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/38047 (PRs: ~[#39791](https://github.com/sourcegraph/sourcegraph/pull/39791)~)
  - [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/issues/38048 (PRs: ~[#39265](https://github.com/sourcegraph/sourcegraph/pull/39265)~)
  - [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/pull/39154 
  - [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/pull/39155 
  - [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/pull/39182 
  - [x] (🏁 30 days ago) https://github.com/sourcegraph/sourcegraph/pull/39196 
  - [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/pull/39457 
  - [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/pull/39458 
  - [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/pull/39459 
  - [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/pull/39473 
  - [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/pull/39474 
  - [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39540 
  - [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39541 
  - [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39542 
  - [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39543 
  - [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39545 
  - [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39546 
  - [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39547 
  - [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39548 
  - [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39549 
  - [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39553 
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/39578 (PRs: ~[#39265](https://github.com/sourcegraph/sourcegraph/pull/39265)~, ~[#40628](https://github.com/sourcegraph/sourcegraph/pull/40628)~, ~[#40633](https://github.com/sourcegraph/sourcegraph/pull/40633)~, ~[#40634](https://github.com/sourcegraph/sourcegraph/pull/40634)~, ~[#40636](https://github.com/sourcegraph/sourcegraph/pull/40636)~, ~[#40637](https://github.com/sourcegraph/sourcegraph/pull/40637)~, ~[#40639](https://github.com/sourcegraph/sourcegraph/pull/40639)~, ~[#40640](https://github.com/sourcegraph/sourcegraph/pull/40640)~, ~[#40641](https://github.com/sourcegraph/sourcegraph/pull/40641)~)
  - [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/39579 (PRs: ~[#39629](https://github.com/sourcegraph/sourcegraph/pull/39629)~)
  - [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/39581 (PRs: ~[#39628](https://github.com/sourcegraph/sourcegraph/pull/39628)~)
  - [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/pull/39641 
  - [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/pull/39665 
  - [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/pull/40623 
  - [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/pull/40624 
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/40635 

Completed
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/38044 (PRs: ~[#38111](https://github.com/sourcegraph/sourcegraph/pull/38111)~)
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/pull/39155 
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/pull/39154 
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/pull/39182 
- [x] (🏁 30 days ago) https://github.com/sourcegraph/sourcegraph/pull/39196 
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/38045 (PRs: ~[#36319](https://github.com/sourcegraph/sourcegraph/pull/36319)~)
- [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/pull/39458 
- [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/pull/39457 
- [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/pull/39459 
- [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/pull/39473 
- [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/pull/39474 
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39540 
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39541 
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39542 
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39543 
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39545 
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39549 
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39548 
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39547 
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39546 
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/pull/39553 
- [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/pull/39641 
- [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/issues/38048 (PRs: ~[#39265](https://github.com/sourcegraph/sourcegraph/pull/39265)~)
- [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/pull/39665 
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/39579 (PRs: ~[#39629](https://github.com/sourcegraph/sourcegraph/pull/39629)~)
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/issues/39581 (PRs: ~[#39628](https://github.com/sourcegraph/sourcegraph/pull/39628)~)
- [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/pull/40624 
- [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/pull/40623 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/38047 (PRs: ~[#39791](https://github.com/sourcegraph/sourcegraph/pull/39791)~)
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/pull/40635 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/39578 (PRs: ~[#39265](https://github.com/sourcegraph/sourcegraph/pull/39265)~, ~[#40628](https://github.com/sourcegraph/sourcegraph/pull/40628)~, ~[#40633](https://github.com/sourcegraph/sourcegraph/pull/40633)~, ~[#40634](https://github.com/sourcegraph/sourcegraph/pull/40634)~, ~[#40636](https://github.com/sourcegraph/sourcegraph/pull/40636)~, ~[#40637](https://github.com/sourcegraph/sourcegraph/pull/40637)~, ~[#40639](https://github.com/sourcegraph/sourcegraph/pull/40639)~, ~[#40640](https://github.com/sourcegraph/sourcegraph/pull/40640)~, ~[#40641](https://github.com/sourcegraph/sourcegraph/pull/40641)~)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
