### ISSUE TITLE
3.42.0 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#38120]
# 3.42.0 managed instances upgrade

These [managed instances](../../admin-exp/devops/managed/index.md) upgrades are scheduled for **[Jul 25, 2022, 6:00 PM (UTC)](https://time.is/1800_25_Jul_2022_in_UTC?One%20working%20day%20after%203.42%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../admin-exp/devops/managed/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [ ] Upgrade [rctest.sourcegraph.com](https://rctest.sourcegraph.com)
- [ ] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.
- [ ] Upgrade [tpgi.sourcegraph.com](https://tpgi.sourcegraph.com) - this is the accessibility audit managed instance, please contact #frontend-platform before upgrading.

## Upgrade customer managed instances

- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/537
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/820
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/814
- [ ] Upgrade second instance for https://github.com/sourcegraph/customer/issues/820
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/774
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/956
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/769
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/1046
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/1044
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/1057
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/1058
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/1101
- [ ] Upgrade instance for https://github.com/sourcegraph/customer/issues/1106
- [ ] https://github.com/sourcegraph/accounts/issues/8483

---

Also see [3.42.0 release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/38119)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud - the "team/cloud" label was applied to this issue.

**Comment by ryanslade** [comment]
Superseded by #38645

**Comment by michaellzc** [comment]
close in favor of https://github.com/sourcegraph/sourcegraph/issues/39597
