### ISSUE TITLE
Move “open in editor” extension to core workflow

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#38378]
Useful links:

- [Figma](https://www.figma.com/file/7bVINrmqfDpxmLx3gv1uVa/Sunsetting-extensions?node-id=2117%3A22821)
- [Old repo](https://github.com/sourcegraph/open-in-editor-extension)
- [Doc](https://docs.google.com/document/d/1b-0Me_JPxUnnEmgcJp1s5C3Hk7g38c0jULMVvQrHyWI/edit#)

Tasks:

- [x] Figure out settings structure
- [x] Assemble supported IDE list
- [x] Create branch
- [x] Create URL getter
- [x] Create action items container for the migrated extensions (git-extras, open-in-editor + view on the code host) – Copy styles from “ActionsContainer”
- [x] Create a component for “open in editor” action
- [x] Add settings to user settings
- [x] Collect icons for the different supported IDEs
- [x] Make the icon change to the IDE icon once settings are set correctly
- [x] Create a custom `useIde` hook exposing an `openInIDE` callback
- [x] Create a popover based on Sara’s designs
  - Dropdown clues: We don’t currently have a base dropdown component, but [SearchContextDropdown](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/search-ui/src/input/SearchContextDropdown.tsx) (used to select a context from the search page) and [DashboardSelect](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-select/DashboardSelect.tsx) (used to find dashboards from the Code Insights page) should give an example of how to start putting this together. They use slightly different technologies under the hood (SearchContextDropdown uses reactstrap, and DashboardSelect uses reach) but we don’t have this standardized at all, use whichever option from those best suits our needs.
- [x] Hook up popover to open
- [x] Make sure keyboard navigation/interaction support is great! Our accessibility audit is upcoming!
- [x] Create docs page to explain how to change settings
- [x] Unit test build-url.ts
- [x] Implement editor and base path saving in settings
- [x] Migrate previous settings
- [ ] Add deprecation notices to the four repos

Test:
- [ ] Test it with all supported IDEs
- [ ] Test it on Windows with IntelliJ
- [ ] Test it with GoLand or some other JetBrains IDE that’s not IntelliJ
- [ ] Test it with an older IntelliJ version

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
