### ISSUE TITLE
Errors Classification: Tracking issue

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#38612]
### Plan

This [doc](https://docs.google.com/document/d/10n6j2empkCzr6yL873p8WuL6R0U8Erm0awIwOp9hRl8/edit#heading=h.ai41ynoo7bjc) captures the inspiration, proposal and plan for actionable and classifiable errors in Sourcegraph's code.

<WIP>

### Tracked issues

@unassigned: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/38618  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/38620  __1.00d__ 🕵️

@indradhanush: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/38616  __1.00d__

Completed: __1.00d__
- [x] (🏁 350 days ago) https://github.com/sourcegraph/sourcegraph/issues/38615 (PRs: ~[#38671](https://github.com/sourcegraph/sourcegraph/pull/38671)~, ~[#38885](https://github.com/sourcegraph/sourcegraph/pull/38885)~) __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
