### ISSUE TITLE
3.41.1 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#38645]
# 3.41.1 managed instances upgrade

These [managed instances](../../../../cloud/index.md) upgrades are scheduled for **[Jul 14, 2022, 6:00 PM (UTC)](https://time.is/1800_14_Jul_2022_in_UTC?One%20working%20day%20after%203.41.1%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../../../cloud/technical-docs/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [ ] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [ ] Upgrade [rctest.sourcegraph.com](https://rctest.sourcegraph.com)
- [ ] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.
- [ ] Upgrade [tpgi.sourcegraph.com](https://tpgi.sourcegraph.com) - this is the accessibility audit managed instance, please contact #frontend-platform before upgrading.

## Upgrade customer managed instances

- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/537
- [ ] Upgrade instance for [customer #820](https://github.com/sourcegraph/customer/issues/820)
- [ ] Upgrade instance for [customer #814](https://github.com/sourcegraph/customer/issues/814)
- [ ] Upgrade second instance for [customer #820](https://github.com/sourcegraph/customer/issues/820)
- [ ] Upgrade instance for [customer #774](https://github.com/sourcegraph/customer/issues/774)
- [ ] Upgrade instance for [customer #956](https://github.com/sourcegraph/customer/issues/956)
- [ ] Upgrade instance for [customer #769](https://github.com/sourcegraph/customer/issues/769)
- [ ] Upgrade instance for [customer #1046](https://github.com/sourcegraph/customer/issues/1046)
- [ ] Upgrade instance for [customer #1044](https://github.com/sourcegraph/customer/issues/1044)
- [ ] Upgrade instance for [customer #1057](https://github.com/sourcegraph/customer/issues/1057)
- [ ] Upgrade instance for [customer #1058](https://github.com/sourcegraph/customer/issues/1058)
- [ ] Upgrade instance for [customer #1101](https://github.com/sourcegraph/customer/issues/1101)
- [ ] Upgrade instance for [customer #1106](https://github.com/sourcegraph/customer/issues/1106)
- [ ] Upgrade instance for [customer #1108](https://github.com/sourcegraph/customer/issues/1108)
- [ ] Upgrade instance for [customer #1107](https://github.com/sourcegraph/customer/issues/1107)
- [ ] Upgrade instance for [customer #1109](https://github.com/sourcegraph/customer/issues/1109)

---

Also see [3.41.1 patch release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/38644)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.
