### ISSUE TITLE
DevX Q2B2: s2 continuous deployment

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#38911]
### Plan

s2 needs an interim continuous deployment mechanism for dogfooding purposes while Cloud works on a long-term CD system for the Cloud product. The DevX team will drive these efforts with the assistance of the Cloud team.

@michaellzc has prepared the following for us:

- [x] `mg update-golden` - will fetch the latest docker-compose and update tags to latest (https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/788)
- [x] `mg upgrade` - use the updated golden files to upgrade the instance (https://github.com/sourcegraph/customer/issues/1141)
- [x] GCP authentication in GitHub Actions: https://github.com/sourcegraph/deploy-sourcegraph-managed/blob/main/.github/workflows/reload_frontend.yml
- [x] Automate: https://github.com/sourcegraph/customer/issues/1174

The above tools can be used to create an action that runs the golden update, upgrade to it, and then commit the changes back to repo.

Related: https://github.com/sourcegraph/customer/issues/1153

### Tracked issues

 

@davejrt

- [ ] https://github.com/sourcegraph/sourcegraph/issues/39202 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by kalanchan** [comment]
i think we should be good after @davejrt's fixes
