### ISSUE TITLE
3.3.8 Release

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#3897]
# 3.3.8 Release

- [x] Create a checklist of the changes that you want to release (i.e. open or merged PRs).
  - [x] repo-updater: Support external_id migrations (#3848)
  - [x] repo-updater: Drop repo trigger set_repo_name and unused repo columns (#3776)
  - [x] repo-updater: Reset Bitbucket Server external ids (#3850)
  - [x] repo-updater: Use original metadata object in Exclude (#3879)
- [x] Communicate your intentions by sending a message to #dev-announce that includes a link to this issue.
- [x] Cherry pick changes into the existing release branch (this exists already as `MAJOR.MINOR`, do not create a new branch) and check them off the list above.
    - [x] Ensure that the cherry-picked commits don't depend on any commits that aren't already in the release branch.
- [x] Push the release branch with your cherry-picked commit(s) and make sure CI passes.

## Release sourcegraph/server

- [ ] Create an annotated git tag and push it (this triggers CI to build the Docker images for the new version). For example:
    ```
    VERSION='v3.3.8' bash -c 'git tag -a "$VERSION" -m "$VERSION" && git push origin "$VERSION"'
    ```

- [ ] Wait for the final Docker images to be available at https://hub.docker.com/r/sourcegraph/server/tags.

## Release Kubernetes deployment

In [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph):

- [ ] Wait for Renovate to open a PR to update the image tags and merge that PR ([example](https://github.com/sourcegraph/deploy-sourcegraph/pull/199)).
- [ ] Follow the ["Cutting a new patch version" instructions in https://github.com/sourcegraph/deploy-sourcegraph/blob/master/README.dev.md](https://github.com/sourcegraph/deploy-sourcegraph/blob/master/README.dev.md#cutting-a-new-patch-version-eg-v2121)

## Update the docs

- [x] Update the version (major.minor.patch) of Sourcegraph in the docs ([example](https://github.com/sourcegraph/sourcegraph/pull/2841)) by running the following
  ```
  find . -type f -name '*.md' -exec sed -i '' -E 's/sourcegraph\/server:[0-9\.]+/sourcegraph\/server:$NEW_VERSION/g' {} +
  ```
- [x] Update versions in docs.sourcegraph.com template ([example](https://github.com/sourcegraph/sourcegraph/pull/2841/files#diff-3d0e70da24a04f44a1fdc404b7242b89))
- [x] Update `latestReleaseKubernetesBuild` and `latestReleaseDockerServerImageBuild` ([example](https://github.com/sourcegraph/sourcegraph/pull/2370/commits/15925f2769564225e37013acb52d9d0b30e1336c)).
- [x] [Update deploy-aws version](https://github.com/sourcegraph/deploy-sourcegraph-aws/edit/master/ec2/resources/user-data.sh#L3)
- [x] [Update deploy-digitalocean version ](https://github.com/sourcegraph/deploy-sourcegraph-digitalocean/edit/master/resources/user-data.sh#L3)
- [ ] Message @slimsag on Slack: `MAJOR.MINOR.PATCH has been released, update deploy-sourcegraph-docker as needed`
- [x] Create a new section for the patch version in the changelog. Verify that all changes that have been cherry picked onto the release branch have been moved to this section of the [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/master/CHANGELOG.md) on `master`.
- [ ] Post a reply in the #dev-announce thread to say that the release is complete.

**Comment by dadlerj** [comment]
The largest orgs using Sourcegraph on Bitbucket Server that I can think of have already migrated to 3.3.7 (including https://app.hubspot.com/contacts/2762526/company/407948923 of course,  https://app.hubspot.com/contacts/2762526/company/557889642, and https://app.hubspot.com/contacts/2762526/company/557692615). 

I believe this bug is what we saw during the upgrade that I shared at https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/f515ed11af54b736725104d59556052d321ddf77?first=50

**Comment by slimsag** [comment]
Thank you for sending these up! I'll take over this and ship later today or tomorrow morning

**Comment by slimsag** [comment]
Sorry for not providing an update on this yesterday. My plan is to cut this release after I have a patch for a few perf issues in for https://app.hubspot.com/contacts/2762526/company/407948923  Aim was to do it yesterday but some other work for them popped up, so it's looking like today/tomorrow.

My understanding based on what Dan said above is that this isn't critical for any customer, so waiting isn't harmful at all. If I hear otherwise, though, I'll ship earlier without the perf patches!

**Comment by slimsag** [comment]
So I ended up being delayed on this further, and 3.4 is cut on Tues.. if this isn't important for https://app.hubspot.com/contacts/2762526/company/407948923 should I still cut this?

**Comment by keegancsmith** [comment]
Yeah lets just abandon ship.

**Comment by slimsag** [comment]
Cool, abandoning ship then. If anyone chooses to do another 3.3 patch release, these changes will then make it in / such a person can reuse this work.

**Comment by slimsag** [comment]
(Continuing in https://github.com/sourcegraph/sourcegraph/issues/4137)
