### ISSUE TITLE
Introduce client performance observability to the Sourcegraph application: Tracking issue

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#39272]
## Problem to solve

The client's observability is lacking. We use Sentry for error tracking but do not have client [RUM](https://en.wikipedia.org/wiki/Real_user_monitoring) and performance monitoring instrumentations. It means that we have no understanding of how real users are using our client application in terms of performance/interactions. It limits our ability to assess and prioritize areas for improvement. We are forced to do it based on limited customer development sessions, anecdotal evidence, or one-time testing without the ability to monitor trends and proactively jump on the most impactful issues. Instrumenting our client application can reveal user issues that couldn’t be observed or diagnosed any other way.

## Measure of success

- [ ] We have a robust process for client performance observability on the client, and it's documented in the handbook. 
- [ ] Relevant services and tools are configured to enable the client performance observability. 
- [ ] Auto instrumentations for client performance monitoring are configured. 
- [ ] The collected amount of app telemetry data is sufficient for running queries, visualizing traces, and asking questions about specific user interactions.

## Solution summary

- [x] Evaluate the relative advantages and disadvantages of available performance monitoring tooling and determine the best path forward
- [ ] Basic OpenTelemetry integration to enable gathering performance metrics immediately so that we can identify bottlenecks across the application and make targeted improvements that improve core workflow. 
    - [ ] Install and configure OpenTelemetry packages required for client tracing.
    - [ ] Move installed OpenTelemetry packages into their chunk with long-term caching rules to mitigate bundle size increase.
- [ ] [Integrate with backend tracing to enable distributed tracing for a more complete picture](https://github.com/sourcegraph/sourcegraph/issues/37907).
- [ ] Configure client auto-instrumentations
    - [ ] RUM
    - [ ] Web vitals
    - [ ] Navigation
    - [ ] Network calls
    - [ ] React components
- [ ] Make targeted performance improvements to core workflow based on OpenTelementy metrics.
- [ ] Documentation guidelines
    - [ ] Recommended tags and context for traces
    - [ ] Best practices for instrumenting features
    - [ ] Docs on inspecting and interpreting results in Honeycomb
- [ ] Configure event sampling
- [ ] Configure event batching to limit API calls

Artifacts:
- [RFC 722: client performance observability](https://docs.google.com/document/d/1aGsPEjC8TcWG-V6WT5oOV7AJq71nvu0_KVSmJDloiME/edit#)

## What specific customers are we iterating on the problem and solution with?

Internal Sourcegraph developers

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
