### ISSUE TITLE
3.43.0 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by mohammadualam** [sourcegraph/sourcegraph#39334]
# 3.43.0 managed instances upgrade

These [managed instances](../../../../cloud/index.md) upgrades are scheduled for **[Aug 23, 2022, 6:00 PM (UTC)](https://time.is/1800_23_Aug_2022_in_UTC?One%20working%20day%20after%203.43%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../../../cloud/technical-docs/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.

---

## Upgrade internal managed instances

- [x] Upgrade [rctest.sourcegraph.com](https://rctest.sourcegraph.com)
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.
- [x] Upgrade [tpgi.sourcegraph.com](https://tpgi.sourcegraph.com) - this is the accessibility audit managed instance, please contact #frontend-platform before upgrading.
- [x] ~Upgrading [research.sourcegraph.com]~ This is a test instance shared by engineering org
- [x] ~Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)~ This is a test instance shared by engineering org
- [x] ~Upgrade [sourcegraph.sourcegraph.com](https://sourcegraph.sourcegraph.com)~ This instance receives unreleased version upgrade reguarly by #dev-experience

## Upgrade customer managed instances

- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/537
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8494
- [x] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/8494
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8247
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/3078
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8495
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/1246
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/2007
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/981
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8383
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/1084
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8377
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8278
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/4189
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8483
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8287
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8389
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8340
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8306
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/3922
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/4345
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/589
- [x] Upgrdae instance for https://github.com/sourcegraph/accounts/issues/8496
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/7890
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8497

---

Also see [3.43.0 release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/39333)

/cc @sourcegraph/cloud-devops

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by filiphaftek** [comment]
@coury-clark can you please confirm that we can start upgrading Managed Instances to `3.43.0`? I see that [docker-compose](https://raw.githubusercontent.com/sourcegraph/deploy-sourcegraph-docker/v3.43.0/docker-compose/docker-compose.yaml) is created.
