### ISSUE TITLE
DevX OpenTelemetry default tracking issue

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#39397]
### Plan

Work required to make OpenTelemetry the default - and _only_ - observability export format in Sourcegraph 4.0, with backwards-analagous behaviour enabled by making Jaeger an optional component that can be deployed with an appropriately configured OpenTelemetry collector.

Also see [the proposal](https://docs.google.com/document/d/1Gcs0lBPGg3vbRvHwt8G1IJBFVO5_1MGeR-PbaW2J888/edit#).

### Tracked issues

@bobheadxi

Completed
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/pull/40441 
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/40589 
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/40455 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/41244 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/41243 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/39399 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/40680 

@jhchabran

Completed
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/40813 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/40680 

@sanderginn

Completed
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/40456 
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/issues/40813 
- [x] (🏁 1 day ago) https://github.com/sourcegraph/sourcegraph/issues/40457 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/40680 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by bobheadxi** [comment]
Marking this as completed! All engineering work has landed been deployed to S2 where it's been tested, and we also have admin docs available for the deployment changes: https://docs.sourcegraph.com/admin/observability/opentelemetry
