### ISSUE TITLE
Code Insights Tracking issue - Search result page insight live preview

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#39421]
### Plan

In this project we want to bring code insights data and UI to the search result page. 
The first implementation of this is a prototype and should be shipped with turned off by default feature flag.

- [Figma Designs](https://www.figma.com/file/zJHFMF1RYta92C3Trp9y4b/Insights-on-the-search-screen-%2338443-Final-review?node-id=260%3A11) 
- Roadmap issue https://github.com/sourcegraph/sourcegraph/issues/38440

### Tracked issues

@chwarwick

- [ ] https://github.com/sourcegraph/sourcegraph/issues/39222 

Completed
- [x] (🏁 71 days ago) https://github.com/sourcegraph/sourcegraph/issues/39241    🏳️ [Insights iteration 23](https://github.com/sourcegraph/sourcegraph/milestone/165)

@vovakulikov

- [ ] https://github.com/sourcegraph/sourcegraph/issues/38430 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39216 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39228 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39229 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39230 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
@Joelkw, do you think we still need this? Or can we close this tracking issue and all sub-items?

**Comment by Joelkw** [comment]
We can close this!
