### ISSUE TITLE
1-click export MVP Tracking issue

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#39588]
### Plan

This is a tracking issue for 1-click export project MVP. Related discussion can be found here: https://github.com/sourcegraph/sourcegraph/discussions/37930

This issue can be considered closed when the MVP version of the project is implemented and 1-click export can be successfully used in production.

Due to its nature, 1-click export feature is easy to extend (by adding new processors which fetch additional data about SG instance), that's why this tracking issue is not intended to be open until 100% of 1-click export functionality is developed and on the contrary tracks the progress of an MVP version implementation. Every future extension (GH issue) can be linked to this issue and implemented separately, out of the scope of this tracking issue.

### Tracked issues

@unassigned

Completed
- [x] (🏁 427 days ago) https://github.com/sourcegraph/sourcegraph/issues/40096 (PRs: ~[#40190](https://github.com/sourcegraph/sourcegraph/pull/40190)~)
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/39999 
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/39998 
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/39997 
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/39589 
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/40000 
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/39869 
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/39751 

@jhchabran

Completed
- [x] (🏁 496 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  🛠️

@sashaostrikov

Completed
- [x] (🏁 433 days ago) https://github.com/sourcegraph/sourcegraph/issues/39616 (PRs: ~[#39813](https://github.com/sourcegraph/sourcegraph/pull/39813)~)
- [x] (🏁 433 days ago) https://github.com/sourcegraph/sourcegraph/issues/39618 (PRs: ~[#39855](https://github.com/sourcegraph/sourcegraph/pull/39855)~)
- [x] (🏁 433 days ago) https://github.com/sourcegraph/sourcegraph/issues/39619 (PRs: ~[#39813](https://github.com/sourcegraph/sourcegraph/pull/39813)~)
- [x] (🏁 433 days ago) https://github.com/sourcegraph/sourcegraph/issues/39620 (PRs: ~[#39880](https://github.com/sourcegraph/sourcegraph/pull/39880)~)
- [x] (🏁 431 days ago) https://github.com/sourcegraph/sourcegraph/pull/39931 
- [x] (🏁 431 days ago) https://github.com/sourcegraph/sourcegraph/issues/39947 (PRs: ~[#39962](https://github.com/sourcegraph/sourcegraph/pull/39962)~)
- [x] (🏁 429 days ago) https://github.com/sourcegraph/sourcegraph/issues/39960 (PRs: ~[#39962](https://github.com/sourcegraph/sourcegraph/pull/39962)~)
- [x] (🏁 428 days ago) https://github.com/sourcegraph/sourcegraph/issues/39590 (PRs: ~[#40078](https://github.com/sourcegraph/sourcegraph/pull/40078)~)
- [x] (🏁 427 days ago) https://github.com/sourcegraph/sourcegraph/pull/40190 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by sqs** [comment]
(cc @kstretch9 because this might relate to the OpenTelemetry export stuff, either actually or just from a customer's POV)

**Comment by ryphil** [comment]
@sashaostrikov - I just cleaned up our GitHub and these tracking issues may not be needed any longer! I tagged each ticket with the 1-click export Epic and created [this view](https://github.com/orgs/sourcegraph/projects/209/views/7) to show progress. Thoughts?

**Comment by sashaostrikov** [comment]
@ryphil that's nice, thank you!

I think I want to keep this issue just to have a single place of project updates, so it will also be easier for me to track the progress after I am back from PTO (instead of jumping across Slack channels searching for updates).

But as soon as it is finished, we should close this ticket and continue working on post-MVP 1-click project in scope of your Epic :)

**Comment by sashaostrikov** [comment]
@sourcegraph/delivery (which may be a legacy handle, but still)
Is this an active project?
If not, I want to close this issue.
