### ISSUE TITLE
Frontend Platform core workflow performance: Tracking Issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#39595]
Goal: **Noticeably improve performance across the core workflow for Sourcegraph 4.0** This is also a placeholder issue for ongoing, post-4.0 performance improvements that we expect to be identified through https://github.com/sourcegraph/sourcegraph/issues/39272

### Plan

Original drafts and discussion [in this Google doc](https://docs.google.com/document/d/1ic2bt29YKRfcNe6b5jiU0lB9ajzcoUhJcOFCvcQmIX8/edit)

This tracking issue is a collection of work that we think will be valuable and worth doing for the 4.0 release. 

**Note**: This tracking issue comes with the caveat that, as of writing, it has been created from ~3 days of sporadic performance investigations, and that we are slightly limited by some uncertainty with the search/file UX changes for 4.0. _It is still subject to changes as we discover new possible performance wins_.

### Tracked issues

@unassigned: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/39600  __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39601 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39604 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39610 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39611  🕵️
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39612  🕵️
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39617 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555  __2.00d__
- [x] (🏁 690 days ago) https://github.com/sourcegraph/sourcegraph/issues/24869  __2.00d__
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714  __2.00d__
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702  __2.00d__
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682  __2.00d__
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354  __2.00d__

@umpox

- [ ] https://github.com/sourcegraph/sourcegraph/issues/39598 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39739 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 690 days ago) https://github.com/sourcegraph/sourcegraph/issues/24869 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
