### ISSUE TITLE
3.42.1 upgrade managed instances tracking issue

### ISSUE THREAD

**Issue by varsanojidan** [sourcegraph/sourcegraph#39597]
# 3.42.1 managed instances upgrade

These [managed instances](../../../../cloud/index.md) upgrades are scheduled for **[Jul 29, 2022, 6:00 PM (UTC)](https://time.is/1800_29_Jul_2022_in_UTC?One%20working%20day%20after%203.42.1%20release)**.

To perform these upgrades, follow the [managed instances upgrade process](../../../../cloud/technical-docs/upgrade_process.md).
Make sure to upgrade internal instances before customer instances.
For compliance, ensure that you link the upgrade pull requests to this issue.

---

## Upgrade internal managed instances

- [x] Upgrade [devmanaged.sourcegraph.com](https://devmanaged.sourcegraph.com)
- [x] Upgrade [rctest.sourcegraph.com](https://rctest.sourcegraph.com)
- [x] Upgrade [demo.sourcegraph.com](https://demo.sourcegraph.com) - contact #ce beforehand and make sure there are no demos scheduled for the hour of the upgrade.
- [x] Upgrade [tpgi.sourcegraph.com](https://tpgi.sourcegraph.com) - this is the accessibility audit managed instance, please contact #frontend-platform before upgrading.
- [x] Upgrade [sourcegraph.sourcegraph.com](https://sourcegraph.sourcegraph.com) (Not needed, this instance runs insiders build)

## Upgrade customer managed instances

- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/528
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/532
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade second instance for https://github.com/sourcegraph/accounts/issues/542
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/5041
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/547
- ~[ ] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8288~ pending for teardown
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8282
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8285
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/581
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/537
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/820
- [x] Upgrade second instance for https://github.com/sourcegraph/customer/issues/820
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/774
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/956
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/769
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/1044
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/1057
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/1058
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/1101
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/1106
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/1108
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/1107
- [x] Upgrade instance for https://github.com/sourcegraph/customer/issues/1109
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8483
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8389
- [x] Upgrade instance for https://github.com/sourcegraph/accounts/issues/8340

---

Also see [3.42.1 patch release tracking issue](https://github.com/sourcegraph/sourcegraph/issues/39596)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by daxmc99** [comment]
This has been completed
