### ISSUE TITLE
UI Papercuts for Sourcegraph 4.0: Tracking issue

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#39640]
### Plan

In advance of the Sourcegraph 4.0 release at the end of September, we're swarming on minor UI pain points (surfaced by customers and dogfooding) that collectively add friction to the core workflow. 

### Delivery plan

Spike and deliver as many quick wins as possible by Friday, August 12, before shifting focus to an emerging theme around improved compare functionality. 

### Tracked issues

@unassigned: __5.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/32088  __1.00d__ 🕵️
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33065  __1.00d__ 🕵️
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39625  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/18903  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/19871  __0.50d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24125  [👩](https://app.hubspot.com/contacts/2762526/company/6286373436)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/2546    🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)
- [x] https://github.com/sourcegraph/sourcegraph/issues/27771 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/17064 

Completed: __1.00d__
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555  __5.50d__
- [x] (🏁 841 days ago) https://github.com/sourcegraph/sourcegraph/issues/19652 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714  __5.50d__
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702  __5.50d__
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682  __5.50d__
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354  __5.50d__

@lrhacker: __3.00d__

Completed: __3.00d__
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555  __3.00d__
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714  __3.00d__
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702  __3.00d__
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682  __3.00d__
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354  __3.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
