### ISSUE TITLE
Aggregation insights on search results page Tracking issue

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#39643]
### Plan

Refer to the [scope RFC](https://docs.google.com/document/d/1yLV7MGOEXYT3yPvBxHHm8y2-p737KIrju_QPqlhBYz4/edit#) as the source of truth.

### Tracked issues

@unassigned

Completed
- [x] (🏁 30 days ago) https://github.com/sourcegraph/sourcegraph/issues/41206 
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/issues/41283  🐛   🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)

@AlicjaSuska

Completed
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/issues/40306    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)

@CristinaBirkel

Completed
- [x] (🏁 52 days ago) https://github.com/sourcegraph/sourcegraph/issues/39929    🏳️ [Insights iteration 24](https://github.com/sourcegraph/sourcegraph/milestone/166)
- [x] (🏁 44 days ago) https://github.com/sourcegraph/sourcegraph/issues/40216    🏳️ [Insights iteration 24](https://github.com/sourcegraph/sourcegraph/milestone/166)
- [x] (🏁 36 days ago) https://github.com/sourcegraph/sourcegraph/issues/40211    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/issues/40756    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 32 days ago) https://github.com/sourcegraph/sourcegraph/issues/40844    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/issues/41216    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/issues/39922    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)

@Joelkw

Completed
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/pull/41776 

@chwarwick

Completed
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/39626  🕵️   🏳️ [Insights iteration 23](https://github.com/sourcegraph/sourcegraph/milestone/165)
- [x] (🏁 60 days ago) https://github.com/sourcegraph/sourcegraph/issues/39624    🏳️ [Insights iteration 23](https://github.com/sourcegraph/sourcegraph/milestone/165)
- [x] (🏁 52 days ago) https://github.com/sourcegraph/sourcegraph/issues/39776    🏳️ [Insights iteration 24](https://github.com/sourcegraph/sourcegraph/milestone/166)
- [x] (🏁 45 days ago) https://github.com/sourcegraph/sourcegraph/issues/40212    🏳️ [Insights iteration 24](https://github.com/sourcegraph/sourcegraph/milestone/166)
- [x] (🏁 44 days ago) https://github.com/sourcegraph/sourcegraph/issues/40207    🏳️ [Insights iteration 24](https://github.com/sourcegraph/sourcegraph/milestone/166)
- [x] (🏁 43 days ago) https://github.com/sourcegraph/sourcegraph/issues/40540    🏳️ [Insights iteration 24](https://github.com/sourcegraph/sourcegraph/milestone/166)
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/40576    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 32 days ago) https://github.com/sourcegraph/sourcegraph/issues/40682    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 32 days ago) https://github.com/sourcegraph/sourcegraph/issues/40844    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/41016  🐛   🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/41010    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/40794    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/41447    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/40500    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)

@coury-clark

Completed
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/40045    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/issues/40370    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 37 days ago) https://github.com/sourcegraph/sourcegraph/issues/40707    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/41274  🐛   🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/41018    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/41442    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/41547  🐛   🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)

@leonore

Completed
- [x] (🏁 52 days ago) https://github.com/sourcegraph/sourcegraph/issues/39924    🏳️ [Insights iteration 24](https://github.com/sourcegraph/sourcegraph/milestone/166)
- [x] (🏁 45 days ago) https://github.com/sourcegraph/sourcegraph/issues/40205    🏳️ [Insights iteration 24](https://github.com/sourcegraph/sourcegraph/milestone/166)
- [x] (🏁 38 days ago) https://github.com/sourcegraph/sourcegraph/issues/40418    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 37 days ago) https://github.com/sourcegraph/sourcegraph/issues/40425    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 36 days ago) https://github.com/sourcegraph/sourcegraph/issues/40693    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/40368    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/41015  🐛   🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/41269    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/40805    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/issues/41318    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/issues/41423  🐛   🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/41018    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/40971  🧶   🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/40500    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/40684  🕵️   🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/41701    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)

@unclejustin

Completed
- [x] (🏁 30 days ago) https://github.com/sourcegraph/sourcegraph/issues/40427    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 30 days ago) https://github.com/sourcegraph/sourcegraph/issues/40683    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/41120  🐛   🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/issues/40871    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 24 days ago) https://github.com/sourcegraph/sourcegraph/issues/40861    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/issues/41256  🐛   🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)

@vovakulikov

- [ ] https://github.com/sourcegraph/sourcegraph/issues/37259 
  - [x] (🏁 54 days ago) https://github.com/sourcegraph/sourcegraph/issues/39032  🐛   🏳️ [Insights iteration 23](https://github.com/sourcegraph/sourcegraph/milestone/165)

Completed
- [x] (🏁 50 days ago) https://github.com/sourcegraph/sourcegraph/issues/40136    🏳️ [Insights iteration 24](https://github.com/sourcegraph/sourcegraph/milestone/166)
- [x] (🏁 45 days ago) https://github.com/sourcegraph/sourcegraph/issues/39955    🏳️ [Insights iteration 24](https://github.com/sourcegraph/sourcegraph/milestone/166)
- [x] (🏁 44 days ago) https://github.com/sourcegraph/sourcegraph/issues/39954    🏳️ [Insights iteration 24](https://github.com/sourcegraph/sourcegraph/milestone/166)
- [x] (🏁 44 days ago) https://github.com/sourcegraph/sourcegraph/issues/40088    🏳️ [Insights iteration 24](https://github.com/sourcegraph/sourcegraph/milestone/166)
- [x] (🏁 43 days ago) https://github.com/sourcegraph/sourcegraph/issues/40360    🏳️ [Insights iteration 24](https://github.com/sourcegraph/sourcegraph/milestone/166)
- [x] (🏁 37 days ago) https://github.com/sourcegraph/sourcegraph/issues/39956    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 36 days ago) https://github.com/sourcegraph/sourcegraph/issues/40856  🐛   🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 33 days ago) https://github.com/sourcegraph/sourcegraph/issues/40902  🐛   🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 33 days ago) https://github.com/sourcegraph/sourcegraph/issues/40940  🐛   🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/issues/40868    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/issues/40766    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/issues/40306    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/issues/41053    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/issues/41011    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/issues/39922    🏳️ [Insights iteration 25](https://github.com/sourcegraph/sourcegraph/milestone/167)
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/41191  🐛   🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/41158  🐛   🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/41346  🐛   🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/40719 
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/41428  🐛   🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/41291  🐛   🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 23 days ago) https://github.com/sourcegraph/sourcegraph/issues/41469  🐛   🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/41133    🏳️ [Insights iteration 26](https://github.com/sourcegraph/sourcegraph/milestone/168)
- [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/issues/37857 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
I'm closing this one since the 4.0 release has already happened and we shipped search aggregation v1. See https://github.com/sourcegraph/sourcegraph/issues/42401 for the follow-up work
