### ISSUE TITLE
Code Nav: 3.5 Tracking Issue

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#4066]
**Source of truth:** [is:open is:issue org:sourcegraph project:sourcegraph/45 milestone:3.5](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Asourcegraph+project%3Asourcegraph%2F45+milestone%3A3.5+)

- [x] Make decorations performant #3285, requirement for ⬇️  @felixfbecker 
- [x] Support decorations on diffs #911, PR: #3288  @felixfbecker 
- [ ] Introduce first-class support for diff views #4062 @felixfbecker 	
- [ ] e2e test script for Phabricator integration #3667 🏃 @lguychard / @chrismwendt 
- [ ] Properly clean up code views #4064 🏃 
- [ ] Fix Bitbucket text selection #4051 🏃 @chrismwendt 
- [ ] Refactor `FileInfo` and clean up error swallowing due to always assuming base and head file exist #4377  #3107 #3085 
- [ ] `repositoryPathPattern` support and extension API for code host source #4370 
- [ ] See if there are other manual test plans that can be replaced with e2e test
- [ ] Investigate using puppeteer-firefox for Firefox e2e tests #4378 
- [ ] Investigate filling `TextDocument.content` again #4065

**Comment by chrismwendt** [comment]
:+1: to puppeteer-firefox, which would have caught https://github.com/sourcegraph/sourcegraph/issues/4114
