### ISSUE TITLE
Integrations: Sunsetting extensions tracking issue

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#40981]
### Plan

We will be sunsetting Sourcegraph extensions and incorporating top extensions into the main functionally of our platform with the upcoming Sourcegraph 4.0 release in September 2022. 

Though we are sunsetting Sourcegraph extensions, the functionality from top used extensions will soon be part of the core workflow and be easier to use, have better performance, and will be enhanced over time. 

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/38461  🛠️   🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)

@fkling

Completed
- [x] (🏁 51 days ago) https://github.com/sourcegraph/sourcegraph/issues/39499    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)

@jjinnii

Completed
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/38316  🛠️   🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/38378  🛠️   🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/38377  🛠️   🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)

@macraig

Completed
- [x] (🏁 195 days ago) https://github.com/sourcegraph/sourcegraph/issues/31953 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/issues/31071 

@olafurpg

Completed
- [x] (🏁 195 days ago) https://github.com/sourcegraph/sourcegraph/issues/31953 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/issues/31071 

@philipp-spiess

Completed
- [x] (🏁 195 days ago) https://github.com/sourcegraph/sourcegraph/issues/31953 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/issues/31071 
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/issues/40085    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/39041    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/38316  🛠️   🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/40556    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/pull/41111 
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/pull/41300 
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/41314    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/40991    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/41329    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/38529    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/40257    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/pull/41504 
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/41327    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/41039    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/40460    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/41528  🐛   🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/issues/39804    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)

@ryankscott

Completed
- [x] (🏁 195 days ago) https://github.com/sourcegraph/sourcegraph/issues/31953 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/issues/31071 
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/38316  🛠️   🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/41262    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/40214    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/38377  🛠️   🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)

@taras-yemets

Completed
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/issues/40085    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/38532    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/issues/39437    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/38377  🛠️   🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/41327    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/40433    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/40974    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)

@vdavid

Completed
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/38378  🛠️   🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/40991    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/41039    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)
- [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/40974    🏳️ [Integrations 17](https://github.com/sourcegraph/sourcegraph/milestone/214)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

/cc @muratsu @jjinnii @ryankscott
