### ISSUE TITLE
[Webapp Refactor]: Tracking issue

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#41145]
This is a placeholder for a general readiness discussion.

[The main RFC/overview doc on the Code Insight FE types problem](https://docs.google.com/document/d/1GYLfV6VCB42YyoqWCoM9ACFaEnPQz1n5_veArEVCus4/edit#heading=h.gt6sdv90qn1)

Notes: This is referring to the frontend only. This also assumes that _something_ will be asked of us in the current codebase (i.e. dashboards). None of this is necessary if we never touch `/insights` again.

- We must get rid of the context-based API class since this approach is no longer needed and it makes our codebase more complicated. This class-based approach isn't something that other parts of the product adopted, and therefore it's difficult to reuse outside of code insights, and it makes it harder to bring some UI into code insights from other parts of the product.

- We must assess what code needs to be moved out of the enterprise and into shared. Right now, it is impossible to reuse some CI code that will slow down or even prohibit development later. **Example:** For the aggregation feature, we had to extract some components so they would be available. It took a decent amount of time before we could start working on the feature. It makes sense that this will happen again, so we should do our best to prepare for it.

- We must remove most custom frontend types and consume the GraphQL types directly. Adding, updating and testing are still harder than they could be because of all this debt we carry.

Strategic customers have a much higher expectation of resiliency, plus many more eyes on our product. We need to tighten things up before it's a problem.

### Tracked issues

@vovakulikov

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43864 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43192 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43867 

Completed
- [x] (🏁 320 days ago) https://github.com/sourcegraph/sourcegraph/issues/31085    🏳️ [Insights iteration 29](https://github.com/sourcegraph/sourcegraph/milestone/171)
- [x] (🏁 98 days ago) https://github.com/sourcegraph/sourcegraph/issues/43862 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by Joelkw** [comment]
Notes from sync
- justin has ideas to scope this down he'll share/add.
