### ISSUE TITLE
⭐ DevX Support Tracking issue (Q3B1)

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#41179]
### Plan

 

This issues is merely a way to tag all the work related to support, so we can give visibility to our team on all support tasks that were accomplished during a bet cycle and its following cool down period. 

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42258 

@bobheadxi

Completed
- [x] (🏁 34 days ago) https://github.com/sourcegraph/sourcegraph/pull/42129 
- [x] (🏁 34 days ago) https://github.com/sourcegraph/sourcegraph/pull/42118 
- [x] (🏁 33 days ago) https://github.com/sourcegraph/sourcegraph/pull/42264 
- [x] (🏁 32 days ago) https://github.com/sourcegraph/sourcegraph/pull/42320 

@burmudar

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42552 

Completed
- [x] (🏁 28 days ago) https://github.com/sourcegraph/sourcegraph/issues/42484 (PRs: ~[#42494](https://github.com/sourcegraph/sourcegraph/pull/42494)~)
- [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/pull/42520 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/42580 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/42623 
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/pull/42549 
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/pull/42689 
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/pull/42760 
- [x] (🏁 today) https://github.com/sourcegraph/run/issues/44 

@davejrt

- [ ] https://github.com/sourcegraph/sourcegraph/issues/41728 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42934 

Completed
- [x] (🏁 59 days ago) https://github.com/sourcegraph/sourcegraph/issues/38911  🛠️

@efritz

Completed
- [x] (🏁 32 days ago) https://github.com/sourcegraph/sourcegraph/pull/42311 

@jhchabran

Completed
- [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/pull/41842 
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/42257 
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/pull/42816 
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/pull/42830 
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/pull/42444 
- [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/pull/43288 

@keegancsmith

Completed
- [x] (🏁 39 days ago) https://github.com/sourcegraph/sourcegraph/pull/42003 
- [x] (🏁 34 days ago) https://github.com/sourcegraph/sourcegraph/pull/42233 
- [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/pull/42557 

@marekweb

Completed
- [x] (🏁 34 days ago) https://github.com/sourcegraph/sourcegraph/pull/42017 
- [x] (🏁 32 days ago) https://github.com/sourcegraph/sourcegraph/pull/42021 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/42607 
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/42566 

@mrnugget

Completed
- [x] (🏁 19 days ago) https://github.com/sourcegraph/sourcegraph/pull/42366 

@sanderginn

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43404 

Completed
- [x] (🏁 33 days ago) https://github.com/sourcegraph/sourcegraph/pull/42252 
- [x] (🏁 20 days ago) https://github.com/sourcegraph/sourcegraph/issues/42638 
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42869

**Comment by jhchabran** [comment]
https://github.com/sourcegraph/infrastructure/pull/3899

**Comment by jhchabran** [comment]
- https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/17317

**Comment by jhchabran** [comment]
- https://github.com/sourcegraph/sourcegraph/pull/42311

**Comment by jhchabran** [comment]
- https://github.com/sourcegraph/deploy-sourcegraph/pull/4187

**Comment by jhchabran** [comment]
- https://github.com/sourcegraph/infrastructure/commit/4608d049100283c7aa09a23ce241d3a6d8ff3d5e

**Comment by jhchabran** [comment]
- https://github.com/sourcegraph/infrastructure/pull/4097

**Comment by jhchabran** [comment]
Bet cycle finished, closing this issue.
