### ISSUE TITLE
v3.3.8 patch release

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4137]
- [x] Create a checklist of the changes that you want to release (i.e. open or merged PRs).
    - Search performance:
        - [x] 3e65372c9b2f871a359feb1e24a1a3abd45f1661
        - [x] c893ed3d378c7dcb8332c5ccded3ef315bf56e1f
    - Syntax highlighting:
        - [x] 47323fe29105ff49f3e986a72dd7131c60ff2787
        - [x] 1b92ce1a851dd5a988d4039fb4b1b6dac26178f2
        - [x] a29e6559d4f516696aae233f9968964b9b17a783 
  - [x] repo-updater: Support external_id migrations (#3848)
  - [x] repo-updater: Drop repo trigger set_repo_name and unused repo columns (#3776)
  - [x] repo-updater: Reset Bitbucket Server external ids (#3850)
  - [x] repo-updater: Use original metadata object in Exclude (#3879)
- [x] ~Communicate your intentions by sending a message to #dev-announce that includes a link to this issue.~
- [x] Cherry pick changes into the existing release branch (this exists already as `MAJOR.MINOR`, do not create a new branch) and check them off the list above.
    - [x] Ensure that the cherry-picked commits don't depend on any commits that aren't already in the release branch.
- [x] Push the release branch with your cherry-picked commit(s) and make sure CI passes.

## Release sourcegraph/server

- [x] Create an annotated git tag and push it (this triggers CI to build the Docker images for the new version). For example:
    ```
    VERSION='v3.2.1-rc.1' bash -c 'git tag -a "$VERSION" -m "$VERSION" && git push origin "$VERSION"'
    ```

- [x] Wait for the final Docker images to be available at https://hub.docker.com/r/sourcegraph/server/tags.

## Release Kubernetes deployment

In [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph):

- [x] Wait for Renovate to open a PR to update the image tags and merge that PR ([example](https://github.com/sourcegraph/deploy-sourcegraph/pull/199)).
- [x] Follow the ["Cutting a new patch version" instructions in https://github.com/sourcegraph/deploy-sourcegraph/blob/master/README.dev.md](https://github.com/sourcegraph/deploy-sourcegraph/blob/master/README.dev.md#cutting-a-new-patch-version-eg-v2121)

## Update the docs

- [x] ~Update the version (major.minor.patch) of Sourcegraph in the docs ([example](https://github.com/sourcegraph/sourcegraph/pull/2841)) by running the following~
  ```
  find . -type f -name '*.md' -exec sed -i '' -E 's/sourcegraph\/server:[0-9\.]+/sourcegraph\/server:$NEW_VERSION/g' {} +
  ```
- [x] Update versions in docs.sourcegraph.com template ([example](https://github.com/sourcegraph/sourcegraph/pull/2841/files#diff-3d0e70da24a04f44a1fdc404b7242b89))
- [x] ~Update `latestReleaseKubernetesBuild` and `latestReleaseDockerServerImageBuild` ([example](https://github.com/sourcegraph/sourcegraph/pull/2370/commits/15925f2769564225e37013acb52d9d0b30e1336c)).~
- [x] ~[Update deploy-aws version](https://github.com/sourcegraph/deploy-sourcegraph-aws/edit/master/ec2/resources/user-data.sh#L3)~
- [x] ~[Update deploy-digitalocean version ](https://github.com/sourcegraph/deploy-sourcegraph-digitalocean/edit/master/resources/user-data.sh#L3)~
- [x] ~Message @slimsag on Slack: `MAJOR.MINOR.PATCH has been released, update deploy-sourcegraph-docker as needed`~
- [x] Create a new section for the patch version in the changelog. Verify that all changes that have been cherry picked onto the release branch have been moved to this section of the [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/master/CHANGELOG.md) on `master`.
- [x] Post a reply in the #dev-announce thread to say that the release is complete.
