### ISSUE TITLE
Delivery tracking issue 9.28-10.12

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#41771]
### To prioritize

- [ ] Update Upgrade instructions @abeatrix 
- [x] #42256
      AMIs for all AWS regions
- [ ] One-click AWS CloudFormation launch template @jac 
- [ ] Move Sourcegraph AMIs under separate AWS account @slimsag 
- [ ] Foundational Technical Review for AWS Marketplace ([chat](https://sourcegraph.slack.com/archives/C042DHN76HE/p1663302496231619?thread_ts=1662702169.213699&cid=C042DHN76HE)) @beyang 

### Questions

* What's our current process for updating the Docker Compose docs? -  A: there's automation around this.

### Punt

- [ ] One-click Azure launch #42661 
- [ ] One-click GCP launch #42660 
- [ ] Migration path from (and deprecation of) Docker Compose to k3s
- [ ] One-click config export ([chat](https://sourcegraph.slack.com/archives/C02E4HE42BX/p1663698348898329), https://github.com/sourcegraph/sourcegraph/discussions/37930, https://github.com/sourcegraph/sourcegraph/issues/39588)
- [ ] Health Status Checker ([chat](https://sourcegraph.slack.com/archives/C02E4HE42BX/p1663698348898329), [doc](https://docs.google.com/document/d/1shS8DZkZXMB-T4rKwLMogU70N4mSyOpDG1G7ElkjHD4/edit#heading=h.5owhf6uyyp03))

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by felixfbecker** [comment]
@abeatrix did you mean to close the entire tracking issue with https://github.com/sourcegraph/sourcegraph/pull/42453, or only tick off the first item?

**Comment by abeatrix** [comment]
> @abeatrix did you mean to close the entire tracking issue with https://github.com/sourcegraph/sourcegraph/pull/42453, or only tick off the first item?

Woops I only meant to close the first item, I think it was closed automatically when one of my PR was closed, thanks for catching this 😓

**Comment by beyang** [comment]
Closing in favor of: https://github.com/orgs/sourcegraph/projects/290/views/1
