### ISSUE TITLE
FE Integration Testing Tracking issue

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#41799]
### Plan

Add and refine integration tests for Code Insights

[Notes from sync](https://docs.google.com/document/d/1KVyBY77SC-JyXXNBNGw5K0QAlLLNNImiiTEHF1Mp6qA/edit#heading=h.jmv9prci6066)

### Issue ideas

This is just a quick dump of more test ideas. We can move these into issues if we agree they are needed as we have time.

- Test the integration between the options menu and insight
- Test the integration between the filter popover and insight

### Tracked issues

@unclejustin

Completed
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/41800    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/issues/41804    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/issues/41802    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/41807    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
- [x] (🏁 3 days ago) https://github.com/sourcegraph/sourcegraph/issues/41810    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
- [x] (🏁 3 days ago) https://github.com/sourcegraph/sourcegraph/issues/41812    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)

@vovakulikov

- [x] https://github.com/sourcegraph/sourcegraph/issues/42312    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)

Completed
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/issues/41803    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/41811    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
- [x] (🏁 4 days ago) https://github.com/sourcegraph/sourcegraph/issues/41813    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

/cc @joelkw @felixfbecker @vovakulikov

**Comment by vovakulikov** [comment]
Reopened because there is one more issue about chart focus management testing.
