### ISSUE TITLE
gitserver: Remove passing in URL to Exec

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#4182]
Gitserver.Exec currently supports passing in an URL (the clone URL) whenever you run a command. This was used when we would lazily (re)clone repositories. The only place we do that now is sourcegraph.com. For customer instances we should have all repos cloned all the time.

Removing our support for URL in gitserver.Exec has two major benefits:

1. We never need to ask repo-updater for the clone URL in the request path of
   a user.
2. The code around lazily setting URL is complicated and error prone. We can
   greatly simplify.

### TODO

- [ ] Prod: Work out a plan for Sourcegraph.com.
- [ ] Customers: Ensure repo-updater always clones repositories.
- [ ] Customers: Remove gitserver repo deletion janitor jobs.
- [ ] Remove the URL field from gitserver.Exec.

**Comment by keegancsmith** [comment]
I am putting this into the 3.5 milestone since this is some work which would benefit large customers. cc @slimsag @christinaforney @sourcegraph/core-services

**Comment by slimsag** [comment]
Could you clarify in which way this would benefit large customers? I assume it is hidden in this point:

> We never need to ask repo-updater for the clone URL in the request path of
a user.

My guess is that asking repo-updater for the clone URL is expensive/costly, or consumes an API request against the code host?

**Comment by keegancsmith** [comment]
Two ways:

1. Perf, avoid speaking to repo-updater.
2. Stability. We have retryCommand, fallback logic, etc all in place to deal with adding in the URL. I'm sure there are bugs lurking in this that we are unaware of since they rarely trigger.

**Comment by keegancsmith** [comment]
I realised we still rely on this behaviour for EnsureRevision. This is tricky, since EnsureRevision is useful behaviour to keep. We probably need to whiteboard a new design to properly fix how gitserver knows a origin URL and how it keeps it up to date.

Fixing this thorny bit of code makes sense, but I think we need to put more thought into it than I originally expected.

**Comment by tsenart** [comment]
@keegancsmith: I'd love to tackle this. Would like to chat about it tomorrow in our hack session.

**Comment by unknwon** [comment]
@tsenart @keegancsmith given the recent spike you did on stop storing tokens on gitserver's disk, does this issue no longer make sense?

**Comment by tsenart** [comment]
Yep, this was fixed by #16707.
