### ISSUE TITLE
Code Insights: Compute Insights V2 Tracking issue

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#41871]
### Plan

- [RFC](https://docs.google.com/document/d/1Vktm_9CtSoF8zjye5YwCrfaLm8srktf0fccbM-3bcOA/edit)
- [Designs](https://www.figma.com/file/DqZHetdfqHSVzzWtyfjOmr/?node-id=246%3A11)
- [Roadmap Issue](https://github.com/sourcegraph/sourcegraph/issues/33632)

Follow-up issues from [compute insight V1](https://github.com/sourcegraph/sourcegraph/issues/37857) work.

Start date: TBD
Due date: TBD

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/39075 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39912 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39916  🐛
- [ ] https://github.com/sourcegraph/sourcegraph/issues/40095 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/41192  🧶
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39915 

Completed
- [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/32618  🧶

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

/cc @joelkw @felixfbecker @vovakulikov
