### ISSUE TITLE
Chart API primitives Tracking issue

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#42008]
### Plan

This project came up during this issue spike about chart API https://github.com/sourcegraph/sourcegraph/issues/40009#issuecomment-1251023014

**Start date**: TBD
**Due date**: TBD

## Quick recap of spike results
In the past 1-2 months, we introduced a lot props in the high-level charts. This stands against the high-level chart principle - "High-level chart doesn't support all possible cases but provides a simple good first data visualization".

This project's goal is making chart API more customisable and composable. For example 
```tsx
function ConsumerChart() {
  const xScale =  scaleBand<string>({ domain: ['category1', 'category2', 'category3'] }),
  const yScale = scaleLinear<number>({ domain: [0, 100] })

  return (
     <Chart xScale={xScale} yScale={yScale}>
        <ChartAxisLeft {/* Any consumer specific props */}/>
        <ChartAxisBottom {/* Any consumer specific props */} /> 

        <ChartContent>
              { content => <AnyConsumerSpecificContent {/* Any consumer specific props */}/> }
        </ChartContent>

        <ChartTooltip {/* Any consumer specific props */} />
     </Chart>
  )
}
```

### Tracked issues

@unassigned

- [x] https://github.com/sourcegraph/sourcegraph/issues/37259 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42005 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42006 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42007  🧶

Completed
- [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/32618  🧶

@vovakulikov

- [x] https://github.com/sourcegraph/sourcegraph/issues/37259 
  - [x] (🏁 335 days ago) https://github.com/sourcegraph/sourcegraph/issues/42004 

Completed
- [x] (🏁 335 days ago) https://github.com/sourcegraph/sourcegraph/issues/42004 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
