### ISSUE TITLE
Code navigation: Code Mirror design support tracking issue

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#42059]

**Comment by jjinnii** [comment]
## Design process

  - Estimate: Two weeks to one month
  - Weighting factors: High risk, medium certainty (High risk because the file view is one of the most viewed pages on Sourcegraph) 

  ### Discover
  - [ ] Existing customer feedback - Link
    - [ ] NPS scores
    - [ ] Feedback submissions
    - [ ] Customer support requests
  - [ ] Internal users - Link
  - [ ] External users - Link, Link

  ### Define
  - [x] Github issue
  - [x] Design challenge

  ### Design
  - [ ] Wireframes - Link
  - [ ] High fidelity design using design system - Figma
  - [ ] Prototype - Link
  - [ ] Designer review

  ### Testing
  - [ ] Hallway testing - Link
  - [ ] Usertesting.com task based evaluation - Link

  ### Deliver
  - [ ] Announce in #progress
  - [ ] Loom - Link
  - [ ] Team review
  - [ ] Design team review
  - [ ] QA - Link

  ### Measure
  - [ ] Metrics defined in the Figma file ([i](https://handbook.sourcegraph.com/departments/product-engineering/product/design/metrics/defining-metrics/)) - Link
  - [ ] Followup task will analyze metrics to ensure successful completion - Link

**Comment by jjinnii** [comment]
Closing this tracking issue as #41187 was not prioritized as a must have for first release.
