### ISSUE TITLE
⭐ Q3B1: Scale Testing – Manually reproducing customer issues 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#42068]
➡️ **Bet conclusion** https://docs.google.com/document/d/1EikVa90v_itxaN5bKSfx59_Dn2q0ElEDhZA6Zp1aiCI/edit#bookmark=id.4thqlb3dusam 

There is a critical need to have a way of providing large-instances of various code hosts for internal testing purposes. These tools should be sourcegraph-wide services and all new features should be going through scale testing to ensure they work for all customers, especially strategic customers. 

See [Codehost Scale Testing](https://docs.google.com/document/d/1f9GcEpqJ5KA3YvfsOy48mdhILkvJZrqD9SfpZoNlQTg/edit#heading=h.1dosuqn3s1bf) for more. 

This is an essential pillar to reach strategic readiness. See [Toward a confidently Strategic-ready code intelligence platform (post-4.0) 2022-08](https://docs.google.com/document/d/1qQTbEytX5VENOsoaMIaZV8lsFBEsa4n_XU5Aod-dGrw/edit) for more.

[Scratch Log](https://github.com/sourcegraph/devx-scratch/blob/main/2022/scaletesting/log.snb.md) 

## Problem

The context mentioned above is quite clear, but how to get there is very blurry. 

For example, there are no defined use cases yet. What each team wants to test at scale is purely based on previous observations, with varying confidence levels. What kind of data is relevant enough is totally unclear. What kind of synthetic data represents accurately enough a customer instance so we can be confident that testing against it will tell us that it'll work with the customer? 

➡️ So we're navigating uncharted waters, and we need to provide tooling to make this happen, as early as possible so each team can use their findings to reshape their roadmap toward strategic readiness. 

- Repo management & IAM
  - Have a L/XL instance to play with, connected to GitHub, Gitlab, BitBucket, Perforce (sorted by priority)
- CodeNav
  - Need to understand how scaling affects performances: have an instance you can scale up to whichever size you want and connect to any codehost
- Search Core
  - Find out how many concurrent searches we can support
  - What can 2,000 engineers do? What do they do to an instance?

See [Strategic customer support, state of the world ](https://docs.google.com/spreadsheets/d/1n-KfGc8m1w09rIzNKm5tRxAYmP4-w11CVOCplMvVazk/edit#gid=1172385107) for L / XL definitions.

## Scope

At this stage, there is no need for any kind of automation because teams can simply take turns in using the scale testing environment. 

- We are to actively support teammates using the instance and document as we go. 
- We push for its use. If it's not being used, we seek to understand why.  
- We build tools that are useful to observe the instance if needed. 
- We are to pair with them to build tooling to feed data into the instances. 
- And we maintain the instance, of course.

### Boundaries

- Single instance only. Or if really needed, we manually duplicate it. 
- Limited automation for provisioning the instance: populate, snapshot and restore. 
- Non-goal: replicating customer traffic on the instance. 
- Non-goal: cost optimization; this is an investment, just don't overspend for no reason. 
- We maintain, but do not monitor the scale testing instance, that's up to the teams using the instance (but if you see something, tell them eh). 

### Definition of Done

- An engineer familiar with infrastructure and observability can operate and monitor the instance while conducting some tests. 
- At least two teams got data relevant to strategic readiness out of the scale testing instance. 
- Instance can be fed with synthetic data
- Users can be populated up to 10k < X < 20k 
  - Repositories up to 100k < X < 250k and with the largest one being 16 GB < X < 30 GB 
  - Code hosts: GitHub, GitLab at minimum. Perforce.
- We know what the limits of our scale testing instance are. How big can we go? 
- How much does this cost? 

### Payout

Each participating team has collected feedback on how their domain operates at scale and knows how to create meaningful data. We can reproduce hypothetical use cases that approximate our customer use case (repos count and size, users count). 

The best case scenario is that each team has uncovered potential blockers and has mapped out how to reproduce customers' scenarios. The worst-case scenario is they have simply uncovered bugs that would or have affected customers in the past. 

We'll have enough data (cost, usage, reliability) to accurately decide if we want to keep focusing on improving the testing capabilities and/or if we want to focus on automating the tooling itself. 

### Approach 

We previously implemented an MVP, see [Scale testing](https://handbook.sourcegraph.com/departments/engineering/dev/tools/scaletesting/) that is currently being tested by Eric Friz and Stephan Hengl. This is our starting point.

- Assist @efritz, @stefanhengl and @ryanslade in their usage of the scale testing instance. 
  - 🔥 This is the most important thing here. Nobody using the scale testing instance means having zero impact. 
- Being able to populate >10k+ users on CodeHost
  - In particular GitHub which is a problem @quinnhare and @jhchabran  are in touch with their support) 
- Creating synthetic data
  - What do we have so far? What do we need? How can we plug this in easily? 

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43033 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43745 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42072 (PRs: [#43649](https://github.com/sourcegraph/sourcegraph/pull/43649))
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42084 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42085 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43042 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43045 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43047 

Completed
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42094 
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42069 
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42086 

@Piszmog

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43745 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43043 

Completed
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42086 

@burmudar

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43745 
  - [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/issues/42095 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43746 
  - [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/43035 

Completed
- [x] (🏁 29 days ago) https://github.com/sourcegraph/sourcegraph/pull/43035 
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42094 
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42069 

@davejrt

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42100 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43745 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42083 

Completed
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42094 
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42069 

@jhchabran

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42088 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42090 (PRs: ~[#43349](https://github.com/sourcegraph/sourcegraph/pull/43349)~)
- [ ] https://github.com/sourcegraph/sourcegraph/pull/43744 

Completed
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42094 
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42101 
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42069 
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42086 

@kalanchan

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43745 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42096 

Completed
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42094 

@kopancek: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43745 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 

Completed: __1.00d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42094  __1.00d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42069  __1.00d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42086 

@miveronese: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43745 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 

Completed: __1.00d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42094  __1.00d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42069  __1.00d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42086 

@mucles

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43745 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42093 

Completed
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42094 
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42069 

@quinnhare

Completed
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42101 

@sanderginn: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43745 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42559 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 
  - [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/42071 (PRs: [#43649](https://github.com/sourcegraph/sourcegraph/pull/43649))

Completed: __1.00d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42094  __1.00d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42069  __1.00d__
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42086 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by jhchabran** [comment]
Closing, see recap here https://docs.google.com/document/d/1EikVa90v_itxaN5bKSfx59_Dn2q0ElEDhZA6Zp1aiCI/edit#bookmark=id.4thqlb3dusam
