### ISSUE TITLE
⭐  Q3B1: Scaletesting – Creating testing data

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#42069]
### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42072 (PRs: [#43649](https://github.com/sourcegraph/sourcegraph/pull/43649))
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42084 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42085 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43033 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43045 
- [x] https://github.com/sourcegraph/sourcegraph/issues/42094 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43045 

@burmudar

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/issues/42091 
  - [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/42870 
  - [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/issues/43342 

Completed
- [x] (🏁 22 days ago) https://github.com/sourcegraph/sourcegraph/issues/42091 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/issues/43342 
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/42870 

@davejrt

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42083 
  - [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/42082 

Completed
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/42082 

@jhchabran

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43047 
  - [ ] https://github.com/sourcegraph/sourcegraph/pull/43739 
  - [ ] https://github.com/sourcegraph/sourcegraph/pull/43744 
  - [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/issues/42092 
  - [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/42275 
  - [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/42503 
  - [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/issues/42565 
  - [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/pull/42622 
  - [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/pull/42651 
  - [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/43051 (PRs: ~[#43082](https://github.com/sourcegraph/sourcegraph/pull/43082)~, ~[#43523](https://github.com/sourcegraph/sourcegraph/pull/43523)~)
  - [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/pull/43349 
  - [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/43357 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42086 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43047 
  - [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/pull/43082 

Completed
- [x] (🏁 27 days ago) https://github.com/sourcegraph/sourcegraph/issues/42092 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/42503 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/issues/42565 
- [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/pull/42651 
- [x] (🏁 18 days ago) https://github.com/sourcegraph/sourcegraph/pull/42622 
- [x] (🏁 15 days ago) https://github.com/sourcegraph/sourcegraph/issues/42275 
- [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/43051 (PRs: ~[#43082](https://github.com/sourcegraph/sourcegraph/pull/43082)~, ~[#43523](https://github.com/sourcegraph/sourcegraph/pull/43523)~)
- [x] (🏁 7 days ago) https://github.com/sourcegraph/sourcegraph/pull/43349 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/43357 

@kopancek: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068  __1.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 
  - [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__
- [x] https://github.com/sourcegraph/sourcegraph/issues/42094  __1.00d__
  - [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42086 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 

Completed: __1.00d__
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__

@miveronese: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068  __1.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 
  - [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__
- [x] https://github.com/sourcegraph/sourcegraph/issues/42094  __1.00d__
  - [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42086 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 

Completed: __1.00d__
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__

@mucles

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42093 
  - [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/42082 

Completed
- [x] (🏁 11 days ago) https://github.com/sourcegraph/sourcegraph/issues/42082 

@sanderginn: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068  __1.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42071 (PRs: [#43649](https://github.com/sourcegraph/sourcegraph/pull/43649))
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 
  - [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__
- [x] https://github.com/sourcegraph/sourcegraph/issues/42094  __1.00d__
  - [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42086 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43052 (PRs: [#43649](https://github.com/sourcegraph/sourcegraph/pull/43649), [#43649](https://github.com/sourcegraph/sourcegraph/pull/43649))

Completed: __1.00d__
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by jhchabran** [comment]
- https://github.com/sourcegraph/handbook/pull/5131

**Comment by jhchabran** [comment]
Bet closed, see tracking issue for the context.
