### ISSUE TITLE
⭐ Q3B1: ScaleTesting – Accompanying teams to conduct test at scale

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#42086]
### Plan

For each team who reached us to perform testing at scale, we want to make sure they can perform at least an experiment on their own. Our role is to support them by removing roadblocks and adjusting their goals toward what we can provide at this stage. 

We are to provide support and gather feedback from their attempts. 

- What do they want to test 
- What went well 
- What went bad 
- What they'll need next

### Tracked issues

@Piszmog

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43043 

@jhchabran

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42087 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42088 
  - [x] https://github.com/sourcegraph/sourcegraph/issues/42089 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42090 (PRs: ~[#43349](https://github.com/sourcegraph/sourcegraph/pull/43349)~)
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43043 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43047 
  - [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/pull/43082 
- [x] https://github.com/sourcegraph/sourcegraph/issues/42069 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43047 

Completed
- [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/pull/43082 

@kopancek

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 
- [x] https://github.com/sourcegraph/sourcegraph/issues/42069 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 

@miveronese

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 
- [x] https://github.com/sourcegraph/sourcegraph/issues/42069 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 

@sanderginn

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 
- [x] https://github.com/sourcegraph/sourcegraph/issues/42069 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43049 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by jhchabran** [comment]
Bet closed, see tracking issue for the context.
