### ISSUE TITLE
⭐ Q3B1: ScaleTesting – DevOps

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#42094]
### Plan

This tracking issue captures DevOps related issues for the ScaleTesting Bet. 

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43042 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43045 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42069 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43045 

@burmudar

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42095 
  - [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/42097 
  - [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/42102 

Completed
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/42097 
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/issues/42102 

@davejrt

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42100 
  - [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/42099 

Completed
- [x] (🏁 25 days ago) https://github.com/sourcegraph/sourcegraph/issues/42099 

@jhchabran

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/42503 

Completed
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/42503 

@kalanchan

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42096 
  - [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/43032 

Completed
- [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/43032 

@kopancek: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068  __1.00d__
  - [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42069  __1.00d__
  - [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__

Completed: __1.00d__
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__

@miveronese: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068  __1.00d__
  - [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42069  __1.00d__
  - [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__

Completed: __1.00d__
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__

@mucles

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068 
  - [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/43032 

Completed
- [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/43032 

@sanderginn: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42068  __1.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/42559 
  - [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42069  __1.00d__
  - [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__

Completed: __1.00d__
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/issues/43044  __1.00d__

**Comment by jhchabran** [comment]
https://github.com/sourcegraph/deploy-sourcegraph-scaletesting/pull/11

**Comment by jhchabran** [comment]
- https://github.com/sourcegraph/infrastructure/pull/4013

**Comment by jhchabran** [comment]
Bet closed, see tracking issue for the context.
