### ISSUE TITLE
4.0.1 patch release tracking issue

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#42112]
# 4.0.1 patch release

This release is scheduled for **[Sep 26, 2022, 6:00 PM (UTC)](https://time.is/1800_26_Sep_2022_in_UTC?4.0.1%20release%20date)**.

> **Attention developers:** to get your commits in `main` included in this patch release, please file a [patch request](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=&labels=team%2Fdistribution&template=request_patch_release.md&title=4.0.1%3A+) for review.
>
> Only check off items if relevant commits across the following repositories have been cherry-picked into the relevant `4.0` branch by the release captain:
>
> - `sourcegraph/sourcegraph`
> - `sourcegraph/deploy-sourcegraph`
> - `sourcegraph/deploy-sourcegraph-docker`

- [x] https://github.com/sourcegraph/sourcegraph/issues/41989
- [x] https://github.com/sourcegraph/sourcegraph/commit/e2df224db1727d9b25e91001fc762e2b22ded136
- [x] https://github.com/sourcegraph/sourcegraph/commit/367b874419cc498bcdd4f323f997d475be647b6f
- [x] https://github.com/sourcegraph/sourcegraph/commit/a750af2dea1b910025664d1ebf3208648f32364e
- [x] https://github.com/sourcegraph/sourcegraph/commit/4ab710dc0025ec0fc4a6293141ee044f30ad6f96
- [x] https://github.com/sourcegraph/sourcegraph/commit/13694ea69eba28ca8b14d225eae92e39575480ea
- [x] https://github.com/sourcegraph/sourcegraph/commit/fa42ad2e4e22b94a1d7b69c59e4536b8db5b18b6
- [x] https://github.com/sourcegraph/sourcegraph/commit/75c42316a2270623c058458bf31492785530aa14

## Setup

- [x] Ensure release configuration in [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) on `main` is up-to-date with the parameters for the current release.
- [x] Ensure you have the latest version of the release tooling and configuration by checking out and updating `sourcegraph@main`.
- [x] Create a `Security release approval issue` and post a message in the [#security](https://sourcegraph.slack.com/archives/C1JH2BEHZ) channel tagging @security-support.

## Prepare release

Ensure that all [patch request issues](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Apatch-release-request) are accounted for, and have all relevant commits across relevant repositories listed above in the checklist.

For each of the following repositories you have made changes to, cherry-pick (see snippet below) and check off commits listed above.

- [x] `sourcegraph/sourcegraph` ([`4.0` release branch](https://github.com/sourcegraph/sourcegraph/tree/4.0) [CI](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=4.0))
- [x] `sourcegraph/deploy-sourcegraph` ([`4.0` release branch](https://github.com/sourcegraph/deploy-sourcegraph/tree/4.0) [CI](https://buildkite.com/sourcegraph/deploy-sourcegraph/builds?branch=4.0))
- [x] `sourcegraph/deploy-sourcegraph-docker` ([`4.0` release branch](https://github.com/sourcegraph/deploy-sourcegraph-docker/tree/4.0) [CI](https://buildkite.com/sourcegraph/deploy-sourcegraph-docker/builds?branch=4.0))
- [x] `sourcegraph/deploy-sourcegraph-helm` ([`4.0` release branch](https://github.com/sourcegraph/deploy-sourcegraph-helm/tree/release/4.0) [CI](https://buildkite.com/sourcegraph/deploy-sourcegraph-helm/builds?branch=4.0))

```sh
git checkout 4.0
git pull
git cherry-pick <commit0> <commit1> ... # all relevant commits from the default branch
git push origin 4.0
```

- [x] Ensure CI passes on all release branches listed above.

Create and test the first release candidate:

- [x] Push a release candidate tag:
  ```sh
  N=1; yarn release release:create-candidate $N
  ```

**Note**: Ensure that you've pulled both main and release branches before running this command.

- [x] Ensure that the following Buildkite pipelines all pass for the `v4.0.1-rc.1` tag:

  - [x] [Sourcegraph pipeline](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=v4.0.1-rc.1)

- [x] File any failures and regressions in the pipelines as `release-blocker` issues and assign the appropriate teams.

**Note**: You will need to re-check the above pipelines for any subsequent release candidates. You can see the Buildkite logs by tweaking the "branch" query parameter in the URLs to point to the desired release candidate. In general, the URL scheme looks like the following (replacing `N` in the URL):

- Sourcegraph: `https://buildkite.com/sourcegraph/sourcegraph/builds?branch=v4.0.1-rc.N`
- QA: `https://buildkite.com/sourcegraph/qa/builds?branch=v4.0.1-rc.N`
- E2E: `https://buildkite.com/sourcegraph/qa/builds?branch=v4.0.1-rc.N`

## Stage release

- [x] Verify the [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) on `main` and `4.0` are accurate.
- [x] Tag the final release:
  ```sh
  yarn release release:create-candidate final
  ```
- [x] Ensure that the following pipelines all pass for the `v4.0.1` tag:

  - [x] [Sourcegraph pipeline](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=v4.0.1)

- [x] Wait for the `v4.0.1` release Docker images to be available in [Docker Hub](https://hub.docker.com/r/sourcegraph/server/tags)
- [x] Open PRs that publish the new release and address any action items required to finalize draft PRs (track PR status via the [generated release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes)):
  ```sh
  yarn release release:stage
  ```

## Finalize release

- [x] From the [release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes), merge the release-publishing PRs created previously. Note: some PRs require certain actions performed before merging.
- [x] **After all the PRs are merged**, perform following checks/actions
  - For [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph)
    - [x] Ensure the [release tag](https://github.com/sourcegraph/deploy-sourcegraph/tags) has been created
  - For [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker)
    - [x] Ensure the [release tag](https://github.com/sourcegraph/deploy-sourcegraph-docker/tags) has been created
  - For [sourcegraph](https://github.com/sourcegraph/sourcegraph), also:
    - [x] Cherry-pick the release-publishing PR from `sourcegraph/sourcegraph@main` into the release branch.
  - For [deploy-sourcegraph-helm](https://github.com/sourcegraph/deploy-sourcegraph-helm), also:
    - [x] Update the [changelog](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/CHANGELOG.md) to include changes from the patch
    - [x] Cherry-pick the release-publishing PR from the release branch into `main`
- [x] Finalize and announce that the release is live:
  ```sh
  yarn release release:announce
  yarn release release:close
  ```

## Post-release

- [x] Open a PR to update [`dev/release/release-config.jsonc`](https://github.com/sourcegraph/sourcegraph/edit/main/dev/release/release-config.jsonc) with the parameters for the current release.
- [x] Ensure you have the latest version of the release tooling and configuration by checking out and updating `sourcegraph@main`.
- [x] Let the #cloud team know about the managed instances upgrade issue.
- [x] Close this issue.

**Note:** If another patch release is requested after the release, ask that a [patch request issue](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=&labels=team%2Fdistribution&template=request_patch_release.md) be filled out and approved first.

**Comment by camdencheek** [comment]
*Sourcegraph 4.0.1 has been published*

* Changelog: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#4-0-1
* GitHub release: https://github.com/sourcegraph/sourcegraph/releases/tag/v4.0.1
* Release batch change: https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.0.1

@camdencheek: Please complete the post-release steps before closing this issue.
Please also update outstanding patch requests, if relevant:

* #41989
