### ISSUE TITLE
⭐ Q3B1 Bazel: Build our frontend code

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#42144]
See [Bazel @ Sourcegraph](https://docs.google.com/document/d/1HYbaYz9GAhjfHKCMgxi8O3Zi6n3uDkezR3pETxjtO8g/edit) for the document introducing the idea. 

## Problem

Introducing Bazel in our codebase is challenging, as it will require us to adapt our codebase to the constraints that Bazel requires to be able to provide the guarantees we are after: hermetic builds, better caching, reliably test only what changed, etc … (see the original doc). 

One of the most significant sources of slowness on the CI is the frontend client, which takes a long time to build and has some flaky tests due to browser based nature. Integrating frontend code and Bazel while retaining a good enough developer experience is also challenging, as the ecosystem is moving very fast and our codebase has some debts when it comes to tooling (running behind major versions on significant dependencies, such as test runners, etc …) 

Therefore this makes the frontend the best candidate to get started with Bazel. If we can't make it work, there is very little point in porting the other parts of the codebase, but at least we'll have identified what are the areas that need to be updated on the frontend side to make it work. 
### Boundaries 

- Focus purely on the frontend code
- Web client first. 
- Audience: people familiar with Bazel
- CI + local
- Unit Tests > Integration Tests > (E2E tests, stretch goal)

### Definition of Done

- Can run client tests, if and only if necessary. 
- Can build a client bundle, if and only if necessary. 
- Can do the above both in CI and local
- Behind a feature flag in CI, unless we're 100% sure it's working well. 
- CI runs its own Bazel cache.

## Payout

We know that one of the trickiest parts of our codebase can work with Bazel or we have established what needs to be changed to make it work, were we to fail this bet. 

Faster (>10% avg per day) builds on CI. 

Less build failures on main due to flakes (from [10%,15%] to [8%, 12%]) 

## Approach 

Use aspect.build rules for the frontend. 
Get direct help from the FrontEnd Platform team.

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42148 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42151 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42152 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42153 

@davejrt

Completed
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/42149 

@jhchabran

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42147 

@marekweb

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42150 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42908 

Completed
- [x] (🏁 14 days ago) https://github.com/sourcegraph/sourcegraph/issues/42532 

@valerybugakov

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42147

**Comment by sluongng** [comment]
What I would recommend is in addition to remote-cache, setting up a stateful, self-hosted BuildKite Agent (or github action runner, not sure what's your main CI platform) for Bazel job. The level of isolation of the BuildKite Agent should be a shell session (not a docker container) so that Bazel's JVM could be re-used between different CI jobs.

This should enable you to leverage [Bazel's in-memory caching](https://sluongng.hashnode.dev/bazel-caching-explained-pt-2-bazel-in-memory-cache) to speed up CI job execution.

You should be able to get away with a very small number of stateful BuildKite Agents as we expect CI jobs to be relatively faster to execute.

**Comment by jhchabran** [comment]
## Status Update 

➡️ Our bet cycle is now complete and we have decided to work with https://aspect.dev to get things up and running. They are going to focus on the front-end, for the same reasons mentioned in the issue description. 

---

## Closing summary 

We learned a lot about Bazel and the various rules themselves while working on this bet. As it was ranked low priority, we didn't invest too much time. 

- **Result**: Failed. We didn't reach the payout in any way. 
- **Impact**: while we didn't reach anything from the original _payout_, we learned a lot from the experience. This also validated that Bazel is a good solution and some experiments, notably by @michaellzc and @danieldides on Cloud's side were sucessful. 
- **Frictions**: 
  - Priorization toward Scale Testing really took the majority of our time. In the end, we didn't allocate enough time for this to succeed. Also, while @valerybugakov helped us, I think that for this to succeed we would have needed a FE engineer working full-time on this with us. 
  - We came across various issues, mostly inherent to trying to port FE code that wasn't designed with Bazel in mind and having a long history resulting in various scripts not being the easiest to handle. 

We won't be opening a new bet for this, as we'll simply support our external contractor with everything they need to port our FE codebase to Bazel.
