### ISSUE TITLE
📕 [Tracking issue] GitHub App

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#42145]
We need to build our GitHub App integration from the ground up, as our code is a leftover from Cloud V1 and assumes that there will only be a single GitHub App per Sourcegraph instance. This does not hold true in a non-Cloud V1 environment, as customers can interface with many GitHub instances, and if they want to use GitHub App connections to interface with all of them, we need to support multiple GitHub Apps.

## Requirements

- We need to support multiple GitHub Apps
  - Customers might want to interface with github.com, as well as a self-hosted customer.ghe.com.
- We want to focus on building GitHub App from a customer-experience-first perspective. This means figuring out how customers will set up GitHub App integrations first, and only then figuring out how we will build the integration to fit that flow.
  - This does not mean we can discard any technical limitations. GitHub App has a few caveats, and are still limited by what GitHub allows us to do.
- We need to keep the option of a central GitHub App for Sourcegraph Cloud open
  - A central GitHub App for Sourcegraph Cloud would have to work with a redirect proxy to redirect logins to the correct customer instance, as GitHub Apps have a limited number of redirect URLs
  - We cannot rely on automatically configuring webhooks to the GitHub App webhook URL, since that would mean that ALL Cloud customer webhooks would pass through that endpoint (probably sourcegraph.com)
- We need to be aware of the multiple installation flows
  - Customers can start the App installation process either on Sourcegraph, or directly on the App page on GitHub, which can lead to differences in the installation experience
- Preferably the setup flow should guide the customer through the entire process, if possible

## Task list

- [x] #50703
  - [x] Lay out the steps required for a successful GitHub App connection
  - [x] Work with a designer to lay out a customer flow that will enable customers to complete the steps
  - [x] Design pages for each step of the flow

- [x] Frontend
  - [x] Documentation for GitHub App creation and setup #52189
  - [x] Implement pages from the design section
  - [x] #51696
  - [x] Add a way to view GitHub Apps from somewhere in the Site Admin

- [x] Backend
  - [x] #50853
  - [x] #50708
  - [x] #50709
  - [x] #51028
  - [x] #50852
    - At this point, a GitHub App installation should function similar to a GitHub code host connection
  - [x] #51027
    - [x] #51694
  - [x] #51026
  - [x] #51025

- [x] Monitoring
  - [x] What would customers want to keep track of when it comes to GitHub App installations?

### Won't do
- ~~Cloud~~
  - ~~Create a GitHub App for Cloud (or repurpose the existing Sourcegraph GitHub App)~~
  - ~~Create a redirect proxy, i.e. sourcegraph.com/cloud/customer, that redirects to the correct customer instance~~
  - ~~Set up managed instances with the Sourcegraph Cloud GitHub App~~

## Relevant docs
[Understanding GitHub App](https://docs.google.com/document/d/1t0vhiSuqgVBmOaqym8eG88Ny31fJaF2d3htgOQOQB2M/edit#)

[GitHub App/Fine-grained Access Tokens PRFAQ](https://docs.google.com/document/d/1OeXCG77cCXYE85gKMZEw1tKjjecIPlQHfdKc1A22yzU/edit#)

## QA Tasks

These are tasks that should preferably be done ASAP so that it can be backported to go out with 5.1

None of these are breaking issues, but they can be a bit annoying and hard to debug when they do come up
None of these are specific to GitHub Apps either, they're a consequence of some of our auth code, but they might become more relevant when people try to switch to GitHub Apps

- [ ] External account cleanup
  - We can end up with "zombie" external accounts when the auth provider for an external account is removed. We should consider cleaning up those external accounts by matching the `clientID` or something similar. It can cause confusion in a variety of cases. For example, the Account Security page will show that you have a GitHub account connected, but the account is from an old GitHub connection that is no longer relevant.
- [ ] Additional information when deleting GitHub Apps
  - When a GitHub App is deleted, the code host connections for that GitHub App will still exist, but will no longer be functional. We should see if we can delete all associated code host connections in the process as well (and alert users that this is what will happen)
  - Similarly, the Auth provider will still be configured in the site config. Might be worth mentioning this to the user so that they don't forget
  - The webhooks endpoint will also still exist. Also worth pointing out (won't have any impact if it stays there)
- [x] Add a "users" option for GitHub code host connections
  - Our GitHub code host connections has an option to specify "orgs". However, if a GitHub App is installed on a user account, this "orgs" option won't work by specifying the user's name in the "orgs" section, because of the GitHub API. We should instead have an option to clone all repositories that a GitHub App was installed on for a given installation.
- [ ] (stretch) Allow multiple auth providers with the same URL
  - This seems to be a common ask anyways. This was a problem in the past because of how permissions syncing worked. But with the new permissions table where permissions are associated with a specific external account, this limitation should be gone. There might be some areas in the code where we still do URL comparisons, but in theory the hard blocker for allowing multiple external accounts to the same code host connection should be gone. This will help alleviate some annoyances when it comes to transitioning from a traditional GitHub code host connection to a GitHub App as well.
