### ISSUE TITLE
⭐ Q3B1: GCP Cost Saving Phase 2

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#42154]
Previous work: 

- https://github.com/sourcegraph/sourcegraph/issues/38347 
- [WIP GCP Cost Savings Bet](https://docs.google.com/document/d/1eLpTgsIgxUhb9AN67vkWdhDvbYayTB8--V7EMdUb-_0/edit#)

## Problem

Dotcom and preprod were largely over provisioned as at the time multi-tenancy was the prioritized strategy for Sourcegraph. 

Now that Cloud (Single tenancy) is the new strategy, there is a huge opportunity to tune our infrastructure for cost and performance. We made pretty good progress on the previous one, see https://github.com/sourcegraph/sourcegraph/issues/38347#issuecomment-1252601209 but there are still many things left to do. 

Now that we have S2, DogFood is also a good candidate for cost reduction. 

## Scope

We have used cookie cutter templates in the past that over provisioned our infrastructure; to reduce cloud cost and properly tune infrastructure we can work on the following:

- Identify services and deployments that are over provisioned using metrics to backup our reasoning
- Remove redundant or legacy infrastructure added in the past that creates overhead
- Work with other internal teams to understand how their services work and what is the proper deployment baseline
- Implement new tooling to help us control environments and reduce workloads

### Boundaries 

Sourcegraph dotcom and preprod 
Dogfood
Sourcegraph-CI 

### Definition of Done

- GitServer & Indexed-search are operating on dotcom at their minimal provisioning while still operating properly. 
- Dogfood environment is operating at their minimal provisioning while still operating properly
- Removal of environments that are not being used anymore (Preprod or Dogfood)
- Exhibit how much cost saving this brings on a monthly basis. 
- Create platform for teams to easily monitor their cost

## Payout 

We have an opportunity here to save over $100k/month on dotcom, dogfood and preprod. Our goal is to not just cut costs, but to correctly tune our infrastructure so that we aren’t wasteful while still performant. These extra resources can be allocated to other parts of the company to help grow and sustain our business. 

## Approach
We have the following areas to work on

- Dotcom
  - Work with search-core and reduce indexed-search disk allocation
  - Deep dive on dotcom’s backup tooling (velero) and see how we can optimize backup schedules and snapshot creation
  - Work with frontend platform to reduce CPU/Mem allocation for their frontend services
  - Determine if moving over to managed SQL is worth it
- Preprod
  - Remove cluster or spin down to low costing environment for infrastructure testing
- Dogfood
  - Remove cluster or spin down to low costing environment for infrastructure testing

### Tracked issues

@unassigned

Completed
- [x] (🏁 410 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  🛠️

@kalanchan

Completed
- [x] (🏁 410 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  🛠️

@mucles

Completed
- [x] (🏁 410 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  🛠️

**Comment by jhchabran** [comment]
@kalanchan, everything is now set up for you to map the tickets as you see fit. 

For that you need to: 

- Create tickets with the prefix `GCP Cost Saving: `, that's optional but it's clearer this way. 
  - Give the following labels to those tickets: `team/devx` `devx/q3b1/gcpcost` 
  - Assign them to the Devx GitHub project
  - Click on "more" and select "GCP Cloud Saving" as a bet in the dropdown

<img width="337" alt="image" src="https://user-images.githubusercontent.com/10151/192488155-16608d16-7c9c-4fb3-af7d-b936608d61ec.png">

cc @davejrt
