### ISSUE TITLE
sg maintenance improvement tracking issue

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#42207]
### Plan

`sg maintenance` has been identified as the root cause for corrupting repos. This has caused us to effectively have it disabled in all MIs and also for some customers. Along with that, some customers continue to see repo corruption.

While we know that running `sg maintenance` causes repo corruption, we have not yet identified the root cause. This tracking issue will focus on identifying the root causes and subsequently fixing them.

### Tracked issues

@unassigned: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42710 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36974 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39028  __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42214  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/37029  🐛

Completed
- [x] (🏁 121 days ago) https://github.com/sourcegraph/sourcegraph/issues/39025 

@burmudar: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42213  __2.00d__

@indradhanush: __6.50d__

Completed: __6.50d__
- [x] (🏁 121 days ago) https://github.com/sourcegraph/sourcegraph/issues/42208  __2.00d__
- [x] (🏁 121 days ago) https://github.com/sourcegraph/sourcegraph/issues/42212 (PRs: ~[#42270](https://github.com/sourcegraph/sourcegraph/pull/42270)~) __0.50d__
- [x] (🏁 110 days ago) https://github.com/sourcegraph/sourcegraph/issues/42394  __1.00d__
- [x] (🏁 60 days ago) https://github.com/sourcegraph/sourcegraph/issues/42210  __2.00d__
- [x] (🏁 60 days ago) https://github.com/sourcegraph/sourcegraph/issues/42852  __1.00d__

@varsanojidan: __2.00d__

Completed: __2.00d__
- [x] (🏁 121 days ago) https://github.com/sourcegraph/sourcegraph/issues/42208  __2.00d__

#### Artifacts from other repos

- [ ] Potentially resolves: [customer#1237](https://github.com/sourcegraph/customer/issues/1237)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

/cc @jplahn @ryphil

**Comment by keegancsmith** [comment]
> sg maintenance has been identified as the root cause for corrupting repos. This has caused us to effectively have it disabled in all MIs and also for some customers. Along with that, some customers continue to see repo corruption.

Is this still happening on instances after we introduced gc.lock support? If so, damn...

**Comment by mrnugget** [comment]
Out of curiosity: which `sg maintenance` are we talking about? There's [this version](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1659717280669359) floating around Slack and then there's [this one](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/sg_maintenance.sh) in our repository.

The one in Slack does create a `.git/gc.pid` lockfile, but I don't see where it checks whether a `.git/gc.pid` already exists.

**Comment by DaedalusG** [comment]
Folks I haven't yet gathered enough info to open an issue on this, but _a customer_ is reporting an issue that prompted me bringing this up again in a [related issue](https://github.com/sourcegraph/sourcegraph/issues/25264). I'm thinking about advising turning off `sg maintenance`. Feel free to DM me if you want a link to that thread, or more info.

**Comment by indradhanush** [comment]
@DaedalusG If you're seeing a related problem, then I'd suggest to go ahead with turning off `sg maintenance` and see if that resolves the issue for them for now. And if it does then that's another useful data point and any information that could be useful would be helpful towards this effort.

**Comment by ggilmore** [comment]
> Out of curiosity: which `sg maintenance` are we talking about? There's [this version](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1659717280669359) floating around Slack ...
> 
> The one in Slack does create a `.git/gc.pid` lockfile, but I don't see where it checks whether a `.git/gc.pid` already exists.

@mrnugget 

Apologies for the drive-by comment, but the `set -o noclobber` setting takes care of that edge case. See the info about "noclobber" in the [bash manual](https://www.gnu.org/software/bash/manual/bash.html).

**Comment by keegancsmith** [comment]
> keegancsmith yeah unfortunately we were still seeing repo corruption issues on an MI that would've had the fix: [sourcegraph/customer#1229](https://github.com/sourcegraph/customer/issues/1229)

I don't see a smoking gun that this is `sg maintenance`, but if you consistently had corruption issues, then didn't after disabling it then nevermind :P

**Comment by varsanojidan** [comment]
> don't see a smoking gun that this is sg maintenance, but if you consistently had corruption issues, then didn't after disabling it then nevermind :P

Yeah I agree we don't have hard evidence that it's sgm that's causing this but we do have some cause for suspicion:
1) the errors we have been seeing have been consistent with sgm errors we've seen in the past, i.e. : ```bad object refs```
2) the corruption have also been on monorepos
3) we haven't had complaints of any corruption after turning sgm off as far as we are aware.

The plan is to try to recreate an environment where we see the type of corruption the customers are seeing and then dive into the root cause and discern if its sgm (or something else entirely)

**Comment by keegancsmith** [comment]
FYI sg maintenance will default to off now. https://github.com/sourcegraph/sourcegraph/pull/42856

**Comment by mrnugget** [comment]
Closing this, because `sg maintenance` is not enabled by default anymore. We can reopen once we get back to it.

**Comment by DaedalusG** [comment]
@keegancsmith @mrnugget just wanted to comment here that for some users this routine _seems_ to still be useful: https://github.com/sourcegraph/customer/issues/586#issuecomment-1401451101

**Comment by mrnugget** [comment]
Yeah, left a comment in that other issue. That `sg maintenance` can be useful we know. The problem is: we don't know why and when and how it breaks things.

**Comment by keegancsmith** [comment]
Here is some historical context on what sg maintenance gave us https://github.com/sourcegraph/search-scratch/blob/master/2021/monorepo/sg_maintenance.org

Just to comment on why sg maintenance is useful. It optimizes gits storage to have less packfiles as well as adding extra indexes. The less packfile stuff makes git more efficient to do things like git archive / git fetch --shallow / etc. The extra indexes make operations involving git history more efficient. So the indexes do things like git log or blame on a file/dir much faster. Much faster is only really needed on repos with lots of history.
