### ISSUE TITLE
Address the unstable CSS order in the web application production bundle: Tracking issue

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#42217]
## Problem to solve

The CSS rules order in the production environment is different from what we have in the development env. We can choose only one thing with the current build configuration:
1. Consistent CSS rules order in production.
2. Tree shaking powered by `sideEffects: false`.

[See this comment](https://github.com/webpack/webpack/issues/7094#issuecomment-945663737) on the unresolved issue:
> In addition to that, `mini-css-plugin` makes no strong guarantee about the order of independent CSS files. It tries its best to keep the importing order, but there are some cases where this is not followed, e. g. because modules are split into multiple css bundles.
I would recommend to not rely on CSS order between multiple files in general.

See [the Slack thread](https://sourcegraph.slack.com/archives/C03JMRKLJHZ/p1663661972699879) and [the initial issue](https://github.com/sourcegraph/sourcegraph/pull/41736) that triggered this investigation. 

## Measure of success

- [ ] We have a consistent order of CSS rules in the production and development of web application bundles.
- [ ] We use the production bundle for visual regression testing to ensure such issues are captured early.
- [ ] The CSS tree-shaking works without changes.

## Solution Summary

- [ ] Restructure exports in packages with CSS modules to enable tree-shaking without relying on the `sideEffects` property.
    - [ ] #42218
    - [ ] #42219
- [ ] #42220
- [x] #22831
- [ ] #42221
- [ ] #42222

## What specific customers are we iterating on the problem and solution with?

Internal Sourcegraph developers

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42218 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42219 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42220 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42221 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/42222 

Completed
- [x] (🏁 905 days ago) https://github.com/sourcegraph/sourcegraph/issues/19555 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27714 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27702 
- [x] (🏁 587 days ago) https://github.com/sourcegraph/sourcegraph/issues/27682 
- [x] (🏁 561 days ago) https://github.com/sourcegraph/sourcegraph/issues/27354 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

/cc @taylorsperry @muratsu
