### ISSUE TITLE
codeintel: improve code intel backend performance and stability

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/sourcegraph#42235]
Tracking issue for strategic work on improving performance stability etc of the code intel backend

- [ ] https://github.com/sourcegraph/sourcegraph/issues/41202
- [ ] https://github.com/sourcegraph/sourcegraph/issues/41200
- [x] https://github.com/sourcegraph/sourcegraph/issues/41201
- [x] https://github.com/sourcegraph/sourcegraph/issues/30998

More to be added as areas for improvement arise
