### ISSUE TITLE
insights: strategic scoped insights: Tracking issue

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#42328]
[RFC](https://docs.google.com/document/d/1vWxSDSbslZQFEK24rhlo8-K2sCiaaCX5PQoCqEdpI_8/edit#heading=h.4zxjk7qxn6f3)

We currently have 2 ways to scope series by repository. Either a small, (think ~10 or less from a UX perspective,) explicitly defined list of repositories, or "all repositories." At strategic sized customers, having the ability to easily scope it to a group of repositories (by using some sort of repo filter, whether that's a context or something else,) is essential. Until we understand what the functionality will be, we will use the term "strategic scoped insight" for this project.

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44478  🐛
  - [x] (🏁 334 days ago) https://github.com/sourcegraph/sourcegraph/issues/43497  🕵️
  - [x] (🏁 348 days ago) https://github.com/sourcegraph/sourcegraph/issues/43512 

Completed
- [x] (🏁 348 days ago) https://github.com/sourcegraph/sourcegraph/issues/43512 
- [x] (🏁 334 days ago) https://github.com/sourcegraph/sourcegraph/issues/43497  🕵️

@AlicjaSuska

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 239 days ago) https://github.com/sourcegraph/sourcegraph/issues/42333    🏳️ [Insights iteration 29](https://github.com/sourcegraph/sourcegraph/milestone/171)

Completed
- [x] (🏁 239 days ago) https://github.com/sourcegraph/sourcegraph/issues/42333    🏳️ [Insights iteration 29](https://github.com/sourcegraph/sourcegraph/milestone/171)

@CristinaBirkel

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 361 days ago) https://github.com/sourcegraph/sourcegraph/issues/42761    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)

Completed
- [x] (🏁 361 days ago) https://github.com/sourcegraph/sourcegraph/issues/42761    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)

@chwarwick

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 291 days ago) https://github.com/sourcegraph/sourcegraph/issues/38104 
  - [x] (🏁 364 days ago) https://github.com/sourcegraph/sourcegraph/issues/42426    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
  - [x] (🏁 298 days ago) https://github.com/sourcegraph/sourcegraph/issues/42455 
  - [x] (🏁 363 days ago) https://github.com/sourcegraph/sourcegraph/issues/42462    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
  - [x] (🏁 362 days ago) https://github.com/sourcegraph/sourcegraph/issues/42463    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
  - [x] (🏁 292 days ago) https://github.com/sourcegraph/sourcegraph/issues/45219 

Completed
- [x] (🏁 364 days ago) https://github.com/sourcegraph/sourcegraph/issues/42426    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
- [x] (🏁 363 days ago) https://github.com/sourcegraph/sourcegraph/issues/42462    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
- [x] (🏁 362 days ago) https://github.com/sourcegraph/sourcegraph/issues/42463    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
- [x] (🏁 298 days ago) https://github.com/sourcegraph/sourcegraph/issues/42455 
- [x] (🏁 292 days ago) https://github.com/sourcegraph/sourcegraph/issues/45219 
- [x] (🏁 291 days ago) https://github.com/sourcegraph/sourcegraph/issues/38104 

@coury-clark

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 357 days ago) https://github.com/sourcegraph/sourcegraph/issues/42429    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)

Completed
- [x] (🏁 260 days ago) https://github.com/sourcegraph/sourcegraph/issues/43065 

@leonore

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 296 days ago) https://github.com/sourcegraph/sourcegraph/issues/42479 
  - [x] (🏁 298 days ago) https://github.com/sourcegraph/sourcegraph/issues/45215 
  - [x] (🏁 294 days ago) https://github.com/sourcegraph/sourcegraph/issues/45217 
  - [x] (🏁 236 days ago) https://github.com/sourcegraph/sourcegraph/issues/45351 

Completed
- [x] (🏁 298 days ago) https://github.com/sourcegraph/sourcegraph/issues/45215 
- [x] (🏁 296 days ago) https://github.com/sourcegraph/sourcegraph/issues/42479 
- [x] (🏁 294 days ago) https://github.com/sourcegraph/sourcegraph/issues/45217 
- [x] (🏁 236 days ago) https://github.com/sourcegraph/sourcegraph/issues/45351 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by leonore** [comment]
[Link to the notes for the scoped insight sync ](https://docs.google.com/document/d/1GJe-hc4GrAd8NzEVnXX4u_RRMoJeSbH5W9JXfNHgvvg/edit)
