### ISSUE TITLE
Distribution: 3.5 Tracking Issue

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4233]
Private companion issue: https://github.com/sourcegraph/infrastructure/issues/1502

# High-level goals

- Update critical customers to 3.4
- Address customer P1s
- Improve ops and monitoring, both for site admins and our own visibility into customer environments
- Make it easier to test at scale, automate release testing.

# Proposed work

- @slimsag
    - [x] Search sometimes links to incorrect revisions from other repositories #3992
    - [x] GraphQL requests are ambiguous in Prometheus, making it impossible to monitor HTTP metrics #4246
    - [x] Unexpected HTTP error: 520 Origin Error on index:no search #4211
    - [ ] Monitoring
        - [ ] Prometheus metrics for when inter-service communication is failing #4240
        - [ ] Prometheus metrics for monitoring high-level error rates of internal requests #4241
        - [ ] Defined thresholds for per-service Prometheus metrics that are truly bad #4242
        - [ ] Better way to monitor deploy-sourcegraph-docker containers #4243
        - [ ] Prometheus metrics breakdown for site admins #4244
    - [ ] investigate alternative avenues to "symbol search slow on very large repositories #3534"
    - [ ] 💪Upstream standard Prometheus+Grafana+Jaeger work to deploy-sourcegraph (all customers) 
#3410
    - [ ] 💪https://github.com/sourcegraph/sourcegraph/issues/4005
    - [ ] 💪https://github.com/sourcegraph/sourcegraph/issues/4004
    - [ ] 💪https://github.com/sourcegraph/sourcegraph/issues/4003
    - [ ] 💪https://github.com/sourcegraph/sourcegraph/issues/3406
    - [ ] 💪https://github.com/sourcegraph/sourcegraph/issues/2408
- @ggilmore
    - [ ] [Create gitlab.sgdev.org](https://github.com/sourcegraph/sourcegraph/issues/4252) 
    - [ ] [Re-create bitbucket.sgdev.org](https://github.com/sourcegraph/sourcegraph/issues/4253)
    - [ ] 💪 [faster deploys to sourcegraph.com and k8s.sgdev.org](https://github.com/sourcegraph/sourcegraph/issues/4254) (stretch, although I think that renovate-pro is doable)
   - [ ] 💪[Dashboard for monitoring deploys to sourcegraph.com and k8s.sgdev.org](https://github.com/sourcegraph/sourcegraph/issues/4257)
   - [ ] 💪 [Mechanism to query or view the current deployment state of clusters](https://github.com/sourcegraph/sourcegraph/issues/4258)
    - [ ] 💪https://github.com/sourcegraph/sourcegraph/issues/4235
- @beyang 
    - [ ] Release test automation (https://github.com/sourcegraph/sourcegraph/issues/4238, https://github.com/sourcegraph/sourcegraph/issues/4176)
    - [x] GSuite OIDC auth bug (https://github.com/sourcegraph/sourcegraph/issues/4056)
    - [ ] Update Gitolite docs (https://github.com/sourcegraph/sourcegraph/issues/4250)
    - [ ] GitLab auth issue (https://github.com/sourcegraph/sourcegraph/issues/3917)
    - [ ] Access token issue (https://github.com/sourcegraph/sourcegraph/issues/4209)
    - [ ] Language servers behind same domain (https://github.com/sourcegraph/sourcegraph/issues/4437)
    - [ ] Fix up langserver docs, update with workaround in #4437  (https://github.com/sourcegraph/sourcegraph/issues/3561)
- @kzh 
    - [ ] https://github.com/sourcegraph/sourcegraph/issues/4036
    - [ ] 💪https://github.com/sourcegraph/sourcegraph/issues/4235

💪 == stretch goal
