### ISSUE TITLE
Bitbucket Server native integration

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#4236]
## Outcome

- There exists a Sourcegraph for Bitbucket Server plugin
- The level of integration it provides is similar to that of the Phabricator integration:
    - It allows the Bitbucket admin to point the plugin to a self-hosted Sourcegraph instance.
    - All of its functionality is provided by a JS bundle fetched from the Sourcegraph instance.
    - It does not integrate any deeper with Bitbucket Server than the Phabricator integration (eg. UI elements are still injected, vs. contributed through Bitbucket APIs).
    - It requires users to be logged into the Sourcegraph instance to get code intelligence / extensions functionality.

## Task breakdown

- [x] Create scaffolding for a Bitbucket Server plugin
- [x] Use this plugin to inject on every Bitbucket page a snippet of JS that fetches the JS bundle from a Sourcegraph instance
- [x] sourcegraph/sourcegraph: create a separate Webpack entrypoint for a code-host agnostic bundle that's similar to phabricator.bundle.js
    - [x] Make sure that bundle is served by the Sourcegraph instance
    - [x] Make sure that bundle is correctly cached
- [x] Give a way for site admins to configure the URL of the Sourcegraph instance
    - [x] Make sure only site admins can set the Sourcegraph URL, but all users can retrieve it (from the included JS)
- [ ] Prepare submission to Atlassian Marketplace
    - [x] Documentation: verify that the documentation is good enough that the integration can be configured easily upon installation
- [x] Verify tracking works
- [ ] UX
    - [ ] Explore adding a toggle on all pages, configurable by the site admin, to enable an opt-in experience https://sourcegraph.slack.com/archives/CHXHX7XAS/p1562346908018900?thread_ts=1562344998.016200&cid=CHXHX7XAS
- [x] Docs: update main Sourcegraph docs to mention the existence of the plugin
- [x] **Testing**
    - [x] Manual testing on k8s.sgdev.org
    - [x] Manual testing on a fresh Bitbucket Server + Sourcegraph instance
    - [ ] Automated testing: an e2e test that verifies the setup process + usage

**Comment by lguychard** [comment]
Closing this for the 3.6 milestone.

Follow-up issues:
- https://github.com/sourcegraph/sourcegraph/issues/4884
- https://github.com/sourcegraph/sourcegraph/issues/4882
- https://github.com/sourcegraph/sourcegraph/issues/4883
