### ISSUE TITLE
Improved Perforce Support Tracking issue

### ISSUE THREAD

**Issue by jplahn** [sourcegraph/sourcegraph#42390]
### Plan
This issue tracks a number of improvements we can make to our Perforce support. This particular tracking issue is limited to Repo Management and IAM (e.g. it doesn't consider Perforce improvements for Code Insights). Issues below are a combination of customer identified pain points, technical improvements we have identified, and anything else that will make the lives of admins easier when working with Perforce and Sourcegraph. 

### Tracked issues

@unassigned: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/35828 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50247  __3.00d__
  - [x] (🏁 132 days ago) https://github.com/sourcegraph/sourcegraph/issues/43855  __3.00d__   🏳️ [First-class Perforce QoL and Bugfixes](https://github.com/sourcegraph/sourcegraph/milestone/220)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52260  🐛👩

Completed: __3.00d__
- [x] (🏁 132 days ago) https://github.com/sourcegraph/sourcegraph/issues/43855  __3.00d__   🏳️ [First-class Perforce QoL and Bugfixes](https://github.com/sourcegraph/sourcegraph/milestone/220)

@indradhanush: __12.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/50247  __12.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/40330 (PRs: ~[#52937](https://github.com/sourcegraph/sourcegraph/pull/52937)~, ~[#53253](https://github.com/sourcegraph/sourcegraph/pull/53253)~, ~[#53468](https://github.com/sourcegraph/sourcegraph/pull/53468)~, ~[#53505](https://github.com/sourcegraph/sourcegraph/pull/53505)~, ~[#53605](https://github.com/sourcegraph/sourcegraph/pull/53605)~, ~[#53608](https://github.com/sourcegraph/sourcegraph/pull/53608)~, ~[#53668](https://github.com/sourcegraph/sourcegraph/pull/53668)~) __12.00d__   🏳️ [First-class Perforce QoL and Bugfixes](https://github.com/sourcegraph/sourcegraph/milestone/220)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/51537  __12.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/40330 (PRs: ~[#52937](https://github.com/sourcegraph/sourcegraph/pull/52937)~, ~[#53253](https://github.com/sourcegraph/sourcegraph/pull/53253)~, ~[#53468](https://github.com/sourcegraph/sourcegraph/pull/53468)~, ~[#53505](https://github.com/sourcegraph/sourcegraph/pull/53505)~, ~[#53605](https://github.com/sourcegraph/sourcegraph/pull/53605)~, ~[#53608](https://github.com/sourcegraph/sourcegraph/pull/53608)~, ~[#53668](https://github.com/sourcegraph/sourcegraph/pull/53668)~) __12.00d__   🏳️ [First-class Perforce QoL and Bugfixes](https://github.com/sourcegraph/sourcegraph/milestone/220)

@peterguy: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/50247  __2.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/36135  __1.00d__   🏳️ [First-class Perforce QoL and Bugfixes](https://github.com/sourcegraph/sourcegraph/milestone/220)
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44096  __1.00d__ 🐛   🏳️ [First-class Perforce QoL and Bugfixes](https://github.com/sourcegraph/sourcegraph/milestone/220)
  - [x] (🏁 64 days ago) https://github.com/sourcegraph/sourcegraph/issues/52099    🏳️ [First-class Perforce Documentation](https://github.com/sourcegraph/sourcegraph/milestone/224)

Completed
- [x] (🏁 64 days ago) https://github.com/sourcegraph/sourcegraph/issues/52099    🏳️ [First-class Perforce Documentation](https://github.com/sourcegraph/sourcegraph/milestone/224)

@pjlast

Completed
- [x] (🏁 290 days ago) https://github.com/sourcegraph/sourcegraph/issues/41444 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

/cc @sourcegraph/iam

**Comment by mrnugget** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/50247
