### ISSUE TITLE
Search Aggregation v2 Tracking issue

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#42401]
### Plan
Follow up work for the original Search Aggregation project  https://github.com/sourcegraph/sourcegraph/issues/39643

Refer to the [scope RFC](https://docs.google.com/document/d/1yLV7MGOEXYT3yPvBxHHm8y2-p737KIrju_QPqlhBYz4/edit#) as the source of truth.

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/41214 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/41275  🙆

@AlicjaSuska

- [ ] https://github.com/sourcegraph/sourcegraph/issues/39126    🏳️ [Insights iteration 24](https://github.com/sourcegraph/sourcegraph/milestone/166)
- [x] https://github.com/sourcegraph/sourcegraph/issues/37259 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/39935 

@leonore

- [ ] https://github.com/sourcegraph/sourcegraph/issues/41138 

Completed
- [x] (🏁 342 days ago) https://github.com/sourcegraph/sourcegraph/issues/41033    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)

@unclejustin

- [ ] https://github.com/sourcegraph/sourcegraph/issues/39957    🏳️ [Backlog](https://github.com/sourcegraph/sourcegraph/milestone/5)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/40536 

@vovakulikov

- [ ] https://github.com/sourcegraph/sourcegraph/issues/41153 
- [x] https://github.com/sourcegraph/sourcegraph/issues/37259 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/39935 

Completed
- [x] (🏁 342 days ago) https://github.com/sourcegraph/sourcegraph/issues/41033    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

/cc @joelkw @felixfbecker @vovakulikov
