### ISSUE TITLE
Code Insights Strategic Scale Tracking issue

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#43068]
### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/40266  🕵️
- [ ] https://github.com/sourcegraph/sourcegraph/issues/41143 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/41144 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/41155 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/41156 
- [x] https://github.com/sourcegraph/sourcegraph/issues/42328 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44478  🐛
  - [x] (🏁 334 days ago) https://github.com/sourcegraph/sourcegraph/issues/43497  🕵️
  - [x] (🏁 348 days ago) https://github.com/sourcegraph/sourcegraph/issues/43512 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27469 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/34659 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35368  🕵️
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36495 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/37136 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/38951  🐛   🏳️ [Insights iteration 29](https://github.com/sourcegraph/sourcegraph/milestone/171)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/39900 
- [x] https://github.com/sourcegraph/sourcegraph/issues/22920 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/30603 

Completed
- [x] (🏁 375 days ago) https://github.com/sourcegraph/sourcegraph/issues/28858 
- [x] (🏁 375 days ago) https://github.com/sourcegraph/sourcegraph/issues/40265  🕵️
- [x] (🏁 372 days ago) https://github.com/sourcegraph/sourcegraph/issues/42295 
- [x] (🏁 348 days ago) https://github.com/sourcegraph/sourcegraph/issues/43512 
- [x] (🏁 348 days ago) https://github.com/sourcegraph/sourcegraph/issues/42880 
- [x] (🏁 334 days ago) https://github.com/sourcegraph/sourcegraph/issues/43497  🕵️
- [x] (🏁 298 days ago) https://github.com/sourcegraph/sourcegraph/issues/42872  🕵️   🏳️ [Insights iteration 29](https://github.com/sourcegraph/sourcegraph/milestone/171)
- [x] (🏁 264 days ago) https://github.com/sourcegraph/sourcegraph/issues/41146 

@AlicjaSuska

- [x] https://github.com/sourcegraph/sourcegraph/issues/42328 
  - [x] (🏁 239 days ago) https://github.com/sourcegraph/sourcegraph/issues/42333    🏳️ [Insights iteration 29](https://github.com/sourcegraph/sourcegraph/milestone/171)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43392 
  - [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43671 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 

Completed
- [x] (🏁 305 days ago) https://github.com/sourcegraph/sourcegraph/issues/39969    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
- [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 
- [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 
- [x] (🏁 239 days ago) https://github.com/sourcegraph/sourcegraph/issues/42333    🏳️ [Insights iteration 29](https://github.com/sourcegraph/sourcegraph/milestone/171)

@CristinaBirkel

- [ ] https://github.com/sourcegraph/sourcegraph/issues/41938  🕵️
- [x] https://github.com/sourcegraph/sourcegraph/issues/42328 
  - [x] (🏁 361 days ago) https://github.com/sourcegraph/sourcegraph/issues/42761    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)

Completed
- [x] (🏁 382 days ago) https://github.com/sourcegraph/sourcegraph/issues/38329    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
- [x] (🏁 368 days ago) https://github.com/sourcegraph/sourcegraph/issues/41157    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
- [x] (🏁 368 days ago) https://github.com/sourcegraph/sourcegraph/issues/38330    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
- [x] (🏁 361 days ago) https://github.com/sourcegraph/sourcegraph/issues/42761    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)

@chwarwick

- [x] https://github.com/sourcegraph/sourcegraph/issues/42328 
  - [x] (🏁 291 days ago) https://github.com/sourcegraph/sourcegraph/issues/38104 
  - [x] (🏁 364 days ago) https://github.com/sourcegraph/sourcegraph/issues/42426    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
  - [x] (🏁 298 days ago) https://github.com/sourcegraph/sourcegraph/issues/42455 
  - [x] (🏁 363 days ago) https://github.com/sourcegraph/sourcegraph/issues/42462    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
  - [x] (🏁 362 days ago) https://github.com/sourcegraph/sourcegraph/issues/42463    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
  - [x] (🏁 292 days ago) https://github.com/sourcegraph/sourcegraph/issues/45219 

Completed
- [x] (🏁 364 days ago) https://github.com/sourcegraph/sourcegraph/issues/42426    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
- [x] (🏁 363 days ago) https://github.com/sourcegraph/sourcegraph/issues/42462    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
- [x] (🏁 362 days ago) https://github.com/sourcegraph/sourcegraph/issues/42463    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
- [x] (🏁 333 days ago) https://github.com/sourcegraph/sourcegraph/issues/34707  🕵️
- [x] (🏁 298 days ago) https://github.com/sourcegraph/sourcegraph/issues/42455 
- [x] (🏁 292 days ago) https://github.com/sourcegraph/sourcegraph/issues/45219 
- [x] (🏁 291 days ago) https://github.com/sourcegraph/sourcegraph/issues/38104 
- [x] (🏁 260 days ago) https://github.com/sourcegraph/sourcegraph/issues/43065 

@coury-clark: __7.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42107  🕵️
- [x] https://github.com/sourcegraph/sourcegraph/issues/42328 
  - [x] (🏁 357 days ago) https://github.com/sourcegraph/sourcegraph/issues/42429    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24427  __7.00d__

Completed
- [x] (🏁 349 days ago) https://github.com/sourcegraph/sourcegraph/issues/42296  🕵️   🏳️ [Insights iteration 29](https://github.com/sourcegraph/sourcegraph/milestone/171)
- [x] (🏁 260 days ago) https://github.com/sourcegraph/sourcegraph/issues/43065 

@leonore

- [ ] https://github.com/sourcegraph/sourcegraph/issues/41939  🕵️
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43671 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 
- [x] https://github.com/sourcegraph/sourcegraph/issues/42328 
  - [x] (🏁 296 days ago) https://github.com/sourcegraph/sourcegraph/issues/42479 
  - [x] (🏁 298 days ago) https://github.com/sourcegraph/sourcegraph/issues/45215 
  - [x] (🏁 294 days ago) https://github.com/sourcegraph/sourcegraph/issues/45217 
  - [x] (🏁 236 days ago) https://github.com/sourcegraph/sourcegraph/issues/45351 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/45775 
  - [x] (🏁 272 days ago) https://github.com/sourcegraph/sourcegraph/issues/45745 
  - [x] (🏁 261 days ago) https://github.com/sourcegraph/sourcegraph/issues/45746 
  - [x] (🏁 271 days ago) https://github.com/sourcegraph/sourcegraph/issues/45750 
  - [x] (🏁 279 days ago) https://github.com/sourcegraph/sourcegraph/issues/46073 
  - [x] (🏁 271 days ago) https://github.com/sourcegraph/sourcegraph/issues/46074 
  - [x] (🏁 259 days ago) https://github.com/sourcegraph/sourcegraph/issues/46243 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36091 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36414  🧶

Completed
- [x] (🏁 362 days ago) https://github.com/sourcegraph/sourcegraph/issues/42605    🏳️ [Insights iteration 28](https://github.com/sourcegraph/sourcegraph/milestone/170)
- [x] (🏁 306 days ago) https://github.com/sourcegraph/sourcegraph/issues/42128  🕵️
- [x] (🏁 298 days ago) https://github.com/sourcegraph/sourcegraph/issues/45215 
- [x] (🏁 296 days ago) https://github.com/sourcegraph/sourcegraph/issues/42479 
- [x] (🏁 294 days ago) https://github.com/sourcegraph/sourcegraph/issues/45217 
- [x] (🏁 279 days ago) https://github.com/sourcegraph/sourcegraph/issues/46073 
- [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 
- [x] (🏁 272 days ago) https://github.com/sourcegraph/sourcegraph/issues/45745 
- [x] (🏁 271 days ago) https://github.com/sourcegraph/sourcegraph/issues/46074 
- [x] (🏁 271 days ago) https://github.com/sourcegraph/sourcegraph/issues/45750 
- [x] (🏁 264 days ago) https://github.com/sourcegraph/sourcegraph/issues/41146 
- [x] (🏁 261 days ago) https://github.com/sourcegraph/sourcegraph/issues/45746 
- [x] (🏁 259 days ago) https://github.com/sourcegraph/sourcegraph/issues/46243 
- [x] (🏁 236 days ago) https://github.com/sourcegraph/sourcegraph/issues/45351 
- [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/32618  🧶

@unclejustin

Completed
- [x] (🏁 385 days ago) https://github.com/sourcegraph/sourcegraph/issues/32782    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
- [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/32618  🧶

@vovakulikov

- [ ] https://github.com/sourcegraph/sourcegraph/issues/42330  🧶   🏳️ [Insights iteration 29](https://github.com/sourcegraph/sourcegraph/milestone/171)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44846 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44847 
  - [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43392 
  - [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43671 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43477 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44846 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44847 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/45775 
  - [x] (🏁 263 days ago) https://github.com/sourcegraph/sourcegraph/issues/45823 
  - [x] (🏁 260 days ago) https://github.com/sourcegraph/sourcegraph/issues/46493 
- [x] https://github.com/sourcegraph/sourcegraph/issues/22920 
  - [x] (🏁 349 days ago) https://github.com/sourcegraph/sourcegraph/issues/23070 

Completed
- [x] (🏁 385 days ago) https://github.com/sourcegraph/sourcegraph/issues/32782    🏳️ [Insights iteration 27](https://github.com/sourcegraph/sourcegraph/milestone/169)
- [x] (🏁 349 days ago) https://github.com/sourcegraph/sourcegraph/issues/23070 
- [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 
- [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/45701 
- [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 
- [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 
- [x] (🏁 263 days ago) https://github.com/sourcegraph/sourcegraph/issues/45823 
- [x] (🏁 260 days ago) https://github.com/sourcegraph/sourcegraph/issues/45427 
- [x] (🏁 260 days ago) https://github.com/sourcegraph/sourcegraph/issues/46493 
- [x] (🏁 8 days ago) https://github.com/sourcegraph/sourcegraph/issues/32618  🧶

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

/cc @joelkw @felixfbecker @vovakulikov
