### ISSUE TITLE
Implement Role-Based Access Control (Tracking)

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#43276]
### Problem statement

Customers expect us to have the authorization on the API implemented (product gap “Interservice authentication” from one of the customers). This is standard across the industry but we are not enforcing it. 
Not being able to define fine-grained access to several resources limits customers from enabling some features on Sourcegraph like [Batch Changes, because they don’t want just anyone to be able to make bulk code changes across multiple repositories](https://github.com/sourcegraph/sourcegraph/issues/34491).

### Problem validation / why

Some customers are blocked from enabling features like Batch Changes because we don't have an access control system.
Examples of customers that are currently **blocked**:

- https://github.com/sourcegraph/accounts/issues/579
- https://github.com/sourcegraph/accounts/issues/1
- https://github.com/sourcegraph/accounts/issues/3
>There's no way we're going to give x,000 engineers the ability to deploy changes across all our repositories

- https://github.com/sourcegraph/accounts/issues/8243
Also, see [product gap](https://sourcegraph2020.lightning.force.com/lightning/r/Product_Gap__c/a1B5b00000MwQNZEA3/view).

See [RFC 747 Role-Based Access Control](https://docs.google.com/document/d/1mCg5-GiqRuBx2Hrls8lrYEfPMlzuZHmUQ4rCJd0JLeg/edit?pli=1#) for current candidate

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43252 
  - [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/issues/45439 (PRs: ~[#46159](https://github.com/sourcegraph/sourcegraph/pull/46159)~)
  - [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/45451 
  - [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/45452 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/49885 

Completed
- [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/issues/45439 (PRs: ~[#46159](https://github.com/sourcegraph/sourcegraph/pull/46159)~)
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/45451 
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/45452 

@BolajiOlajide

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43252 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/46817 (PRs: ~[#49472](https://github.com/sourcegraph/sourcegraph/pull/49472)~, ~[#49719](https://github.com/sourcegraph/sourcegraph/pull/49719)~)
  - [x] (🏁 104 days ago) https://github.com/sourcegraph/sourcegraph/issues/41940 
  - [x] (🏁 103 days ago) https://github.com/sourcegraph/sourcegraph/issues/45436 (PRs: ~[#45462](https://github.com/sourcegraph/sourcegraph/pull/45462)~)
  - [x] (🏁 103 days ago) https://github.com/sourcegraph/sourcegraph/issues/45437 (PRs: ~[#45463](https://github.com/sourcegraph/sourcegraph/pull/45463)~)
  - [x] (🏁 103 days ago) https://github.com/sourcegraph/sourcegraph/issues/45438 (PRs: ~[#45463](https://github.com/sourcegraph/sourcegraph/pull/45463)~)
  - [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/45440 (PRs: ~[#46190](https://github.com/sourcegraph/sourcegraph/pull/46190)~)
  - [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/45441 (PRs: ~[#46190](https://github.com/sourcegraph/sourcegraph/pull/46190)~)
  - [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/45442 (PRs: ~[#46190](https://github.com/sourcegraph/sourcegraph/pull/46190)~)
  - [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/45443 (PRs: ~[#46190](https://github.com/sourcegraph/sourcegraph/pull/46190)~)
  - [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/45444 (PRs: ~[#47704](https://github.com/sourcegraph/sourcegraph/pull/47704)~)
  - [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/45445 (PRs: ~[#47717](https://github.com/sourcegraph/sourcegraph/pull/47717)~)
  - [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/issues/45446 
  - [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/issues/45447 (PRs: ~[#49177](https://github.com/sourcegraph/sourcegraph/pull/49177)~)
  - [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/issues/45448 (PRs: ~[#48317](https://github.com/sourcegraph/sourcegraph/pull/48317)~, ~[#49177](https://github.com/sourcegraph/sourcegraph/pull/49177)~)
  - [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/45449 (PRs: ~[#47410](https://github.com/sourcegraph/sourcegraph/pull/47410)~)
  - [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/45450 (PRs: ~[#47409](https://github.com/sourcegraph/sourcegraph/pull/47409)~)
  - [x] (🏁 62 days ago) https://github.com/sourcegraph/sourcegraph/issues/45453 (PRs: ~[#45854](https://github.com/sourcegraph/sourcegraph/pull/45854)~)
  - [x] (🏁 62 days ago) https://github.com/sourcegraph/sourcegraph/issues/45454 (PRs: ~[#45854](https://github.com/sourcegraph/sourcegraph/pull/45854)~)
  - [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/issues/45455 (PRs: ~[#46053](https://github.com/sourcegraph/sourcegraph/pull/46053)~, ~[#46053](https://github.com/sourcegraph/sourcegraph/pull/46053)~)
  - [x] (🏁 93 days ago) https://github.com/sourcegraph/sourcegraph/issues/45456 (PRs: ~[#45658](https://github.com/sourcegraph/sourcegraph/pull/45658)~, ~[#45680](https://github.com/sourcegraph/sourcegraph/pull/45680)~, ~[#45680](https://github.com/sourcegraph/sourcegraph/pull/45680)~, ~[#45752](https://github.com/sourcegraph/sourcegraph/pull/45752)~, ~[#45752](https://github.com/sourcegraph/sourcegraph/pull/45752)~, ~[#45791](https://github.com/sourcegraph/sourcegraph/pull/45791)~, ~[#45791](https://github.com/sourcegraph/sourcegraph/pull/45791)~)
  - [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/issues/45457 (PRs: ~[#47130](https://github.com/sourcegraph/sourcegraph/pull/47130)~)

Completed
- [x] (🏁 104 days ago) https://github.com/sourcegraph/sourcegraph/issues/41940 
- [x] (🏁 103 days ago) https://github.com/sourcegraph/sourcegraph/issues/45436 (PRs: ~[#45462](https://github.com/sourcegraph/sourcegraph/pull/45462)~)
- [x] (🏁 103 days ago) https://github.com/sourcegraph/sourcegraph/issues/45437 (PRs: ~[#45463](https://github.com/sourcegraph/sourcegraph/pull/45463)~)
- [x] (🏁 103 days ago) https://github.com/sourcegraph/sourcegraph/issues/45438 (PRs: ~[#45463](https://github.com/sourcegraph/sourcegraph/pull/45463)~)
- [x] (🏁 99 days ago) https://github.com/sourcegraph/sourcegraph/pull/45577 
- [x] (🏁 93 days ago) https://github.com/sourcegraph/sourcegraph/issues/45456 (PRs: ~[#45658](https://github.com/sourcegraph/sourcegraph/pull/45658)~, ~[#45680](https://github.com/sourcegraph/sourcegraph/pull/45680)~, ~[#45680](https://github.com/sourcegraph/sourcegraph/pull/45680)~, ~[#45752](https://github.com/sourcegraph/sourcegraph/pull/45752)~, ~[#45752](https://github.com/sourcegraph/sourcegraph/pull/45752)~, ~[#45791](https://github.com/sourcegraph/sourcegraph/pull/45791)~, ~[#45791](https://github.com/sourcegraph/sourcegraph/pull/45791)~)
- [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/issues/45455 (PRs: ~[#46053](https://github.com/sourcegraph/sourcegraph/pull/46053)~, ~[#46053](https://github.com/sourcegraph/sourcegraph/pull/46053)~)
- [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/pull/46159 
- [x] (🏁 62 days ago) https://github.com/sourcegraph/sourcegraph/pull/46635 
- [x] (🏁 62 days ago) https://github.com/sourcegraph/sourcegraph/issues/45454 (PRs: ~[#45854](https://github.com/sourcegraph/sourcegraph/pull/45854)~)
- [x] (🏁 62 days ago) https://github.com/sourcegraph/sourcegraph/issues/45453 (PRs: ~[#45854](https://github.com/sourcegraph/sourcegraph/pull/45854)~)
- [x] (🏁 51 days ago) https://github.com/sourcegraph/sourcegraph/pull/47114 
- [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/45441 (PRs: ~[#46190](https://github.com/sourcegraph/sourcegraph/pull/46190)~)
- [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/45442 (PRs: ~[#46190](https://github.com/sourcegraph/sourcegraph/pull/46190)~)
- [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/45443 (PRs: ~[#46190](https://github.com/sourcegraph/sourcegraph/pull/46190)~)
- [x] (🏁 47 days ago) https://github.com/sourcegraph/sourcegraph/issues/45440 (PRs: ~[#46190](https://github.com/sourcegraph/sourcegraph/pull/46190)~)
- [x] (🏁 43 days ago) https://github.com/sourcegraph/sourcegraph/issues/47231 (PRs: ~[#47401](https://github.com/sourcegraph/sourcegraph/pull/47401)~)
- [x] (🏁 43 days ago) https://github.com/sourcegraph/sourcegraph/issues/47402 
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/45450 (PRs: ~[#47409](https://github.com/sourcegraph/sourcegraph/pull/47409)~)
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/pull/47403 
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/45449 (PRs: ~[#47410](https://github.com/sourcegraph/sourcegraph/pull/47410)~)
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/pull/47411 
- [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/issues/45457 (PRs: ~[#47130](https://github.com/sourcegraph/sourcegraph/pull/47130)~)
- [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/pull/47499 
- [x] (🏁 41 days ago) https://github.com/sourcegraph/sourcegraph/issues/45446 
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/issues/47131 (PRs: ~[#47406](https://github.com/sourcegraph/sourcegraph/pull/47406)~)
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/issues/47468 (PRs: ~[#47504](https://github.com/sourcegraph/sourcegraph/pull/47504)~)
- [x] (🏁 35 days ago) https://github.com/sourcegraph/sourcegraph/pull/47500 
- [x] (🏁 33 days ago) https://github.com/sourcegraph/sourcegraph/pull/47780 
- [x] (🏁 26 days ago) https://github.com/sourcegraph/sourcegraph/pull/48118 
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/pull/48464 
- [x] (🏁 21 days ago) https://github.com/sourcegraph/sourcegraph/issues/45444 (PRs: ~[#47704](https://github.com/sourcegraph/sourcegraph/pull/47704)~)
- [x] (🏁 13 days ago) https://github.com/sourcegraph/sourcegraph/issues/45445 (PRs: ~[#47717](https://github.com/sourcegraph/sourcegraph/pull/47717)~)
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/pull/49046 
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/pull/48960 
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/pull/49109 
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/pull/49049 
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/pull/49146 
- [x] (🏁 12 days ago) https://github.com/sourcegraph/sourcegraph/pull/48664 
- [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/pull/49189 
- [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/issues/45447 (PRs: ~[#49177](https://github.com/sourcegraph/sourcegraph/pull/49177)~)
- [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/issues/45448 (PRs: ~[#48317](https://github.com/sourcegraph/sourcegraph/pull/48317)~, ~[#49177](https://github.com/sourcegraph/sourcegraph/pull/49177)~)
- [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/pull/49181 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/49515 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/49607 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/49594 

@courier-new

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43252 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/46817 (PRs: ~[#49472](https://github.com/sourcegraph/sourcegraph/pull/49472)~, ~[#49719](https://github.com/sourcegraph/sourcegraph/pull/49719)~)

Completed
- [x] (🏁 10 days ago) https://github.com/sourcegraph/sourcegraph/pull/49180 
- [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/pull/49235 
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/pull/49479 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/49625 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/49635 
- [x] (🏁 2 days ago) https://github.com/sourcegraph/sourcegraph/pull/49472 
- [x] (🏁 2 days ago) https://github.com/sourcegraph/sourcegraph/pull/49719 

@github-actions

Completed
- [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/pull/49245 
- [x] (🏁 9 days ago) https://github.com/sourcegraph/sourcegraph/pull/49260 
- [x] (🏁 6 days ago) https://github.com/sourcegraph/sourcegraph/pull/49549 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/49593 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/49619 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/49616 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/49629 
- [x] (🏁 5 days ago) https://github.com/sourcegraph/sourcegraph/pull/49647 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

/cc @sourcegraph/iam

**Comment by BolajiOlajide** [comment]
Met with 
[@David Veszelovszki](https://sourcegraph.slack.com/team/U02RM5BJ7NU)
 today to discuss potential overlap between RBAC and SCIM.
We discussed possible overlaps between the two project and potential collaborations for the future.
SCIM deals with cross domain identity management and helps consolidate users from external systems with what they should look like on Sourcegraph. At this point, there’s no overlap and both projects are solving different problems but there’s high possibility of a collaboration in the future.
