### ISSUE TITLE
Pagination - must have - FE scale audit - strategic readiness: Tracking issue

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43392]
### Plan

This issue tracks all the pagination-related issues that are must have's for strategic readiness and came from the FE scale audit.

Resources:
- [Product Experience at Scale: Great vs. Good vs. Bad](https://docs.google.com/document/d/1KPsPfZqZ2AAIJ5Ybe7QrWKuaafYF5vUcaB1IfiF82Po/edit#heading=h.4jfhf6ai2t49)
- [Raw scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0)

### Tracked issues

@unassigned: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43391  __2.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43418 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43621  __2.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43857 

@AlicjaSuska

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 312 days ago) https://github.com/sourcegraph/sourcegraph/issues/43535 
  - [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 

Completed
- [x] (🏁 312 days ago) https://github.com/sourcegraph/sourcegraph/issues/43535 
- [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 

@courier-new: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43391  __2.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43393 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43549 
  - [x] (🏁 337 days ago) https://github.com/sourcegraph/sourcegraph/issues/43593 
  - [x] (🏁 337 days ago) https://github.com/sourcegraph/sourcegraph/issues/43624 
  - [x] (🏁 204 days ago) https://github.com/sourcegraph/sourcegraph/issues/44706  __2.00d__
- [x] https://github.com/sourcegraph/sourcegraph/issues/27090 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43393 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43549 

Completed: __2.00d__
- [x] (🏁 756 days ago) https://github.com/sourcegraph/sourcegraph/issues/24466 
- [x] (🏁 615 days ago) https://github.com/sourcegraph/sourcegraph/issues/27348 
- [x] (🏁 337 days ago) https://github.com/sourcegraph/sourcegraph/issues/43624 
- [x] (🏁 337 days ago) https://github.com/sourcegraph/sourcegraph/issues/43593 
- [x] (🏁 98 days ago) https://github.com/sourcegraph/sourcegraph/issues/52507  __2.00d__

@danielmarquespt

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 312 days ago) https://github.com/sourcegraph/sourcegraph/issues/43535 

Completed
- [x] (🏁 312 days ago) https://github.com/sourcegraph/sourcegraph/issues/43535 

@novoselrok

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43589 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43665 
  - [x] (🏁 302 days ago) https://github.com/sourcegraph/sourcegraph/issues/43590 
  - [x] (🏁 302 days ago) https://github.com/sourcegraph/sourcegraph/issues/43667 

Completed
- [x] (🏁 302 days ago) https://github.com/sourcegraph/sourcegraph/issues/43590 
- [x] (🏁 302 days ago) https://github.com/sourcegraph/sourcegraph/issues/43667 

@philipp-spiess: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43391  __2.00d__
  - [x] (🏁 342 days ago) https://github.com/sourcegraph/sourcegraph/issues/43417 
  - [x] (🏁 299 days ago) https://github.com/sourcegraph/sourcegraph/issues/43658 
  - [x] (🏁 295 days ago) https://github.com/sourcegraph/sourcegraph/issues/43659 
  - [x] (🏁 204 days ago) https://github.com/sourcegraph/sourcegraph/issues/44706  __2.00d__

Completed: __2.00d__
- [x] (🏁 342 days ago) https://github.com/sourcegraph/sourcegraph/issues/43417 
- [x] (🏁 299 days ago) https://github.com/sourcegraph/sourcegraph/issues/43658 
- [x] (🏁 295 days ago) https://github.com/sourcegraph/sourcegraph/issues/43659 
- [x] (🏁 98 days ago) https://github.com/sourcegraph/sourcegraph/issues/52507  __2.00d__

@thenamankumar: __10.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43391  __10.00d__
  - [x] (🏁 264 days ago) https://github.com/sourcegraph/sourcegraph/issues/43620  __3.00d__
  - [x] (🏁 267 days ago) https://github.com/sourcegraph/sourcegraph/issues/43622  __2.00d__
  - [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43623  __3.00d__
  - [x] (🏁 204 days ago) https://github.com/sourcegraph/sourcegraph/issues/44706  __2.00d__

Completed: __10.00d__
- [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43623  __3.00d__
- [x] (🏁 267 days ago) https://github.com/sourcegraph/sourcegraph/issues/43622  __2.00d__
- [x] (🏁 264 days ago) https://github.com/sourcegraph/sourcegraph/issues/43620  __3.00d__
- [x] (🏁 98 days ago) https://github.com/sourcegraph/sourcegraph/issues/52507  __2.00d__

@vovakulikov

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 

Completed
- [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
