### ISSUE TITLE
FE Scale Audit - must have's - strategic readiness: Tracking issue

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43391]
### Description

This issue tracks all the must-have's that came out of the [FE scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0).

### Tracked issues

@unassigned: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43392  __2.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43418 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43621  __2.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43857 

Completed
- [x] (🏁 350 days ago) https://github.com/sourcegraph/sourcegraph/issues/43449  🐛
- [x] (🏁 342 days ago) https://github.com/sourcegraph/sourcegraph/issues/43448  🐛

@AlicjaSuska

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43392 
  - [x] (🏁 312 days ago) https://github.com/sourcegraph/sourcegraph/issues/43535 
  - [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43671 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/44357 
  - [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/44358 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43688 
  - [x] (🏁 295 days ago) https://github.com/sourcegraph/sourcegraph/issues/43689 
  - [x] (🏁 294 days ago) https://github.com/sourcegraph/sourcegraph/issues/43691 

Completed
- [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/44358 
- [x] (🏁 312 days ago) https://github.com/sourcegraph/sourcegraph/issues/43535 
- [x] (🏁 302 days ago) https://github.com/sourcegraph/sourcegraph/issues/43910 
- [x] (🏁 295 days ago) https://github.com/sourcegraph/sourcegraph/issues/43689 
- [x] (🏁 294 days ago) https://github.com/sourcegraph/sourcegraph/issues/43691 
- [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 
- [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 

@courier-new: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43392  __2.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43393 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43549 
  - [x] (🏁 337 days ago) https://github.com/sourcegraph/sourcegraph/issues/43593 
  - [x] (🏁 337 days ago) https://github.com/sourcegraph/sourcegraph/issues/43624 
  - [x] (🏁 204 days ago) https://github.com/sourcegraph/sourcegraph/issues/44706  __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43688 
  - [x] (🏁 258 days ago) https://github.com/sourcegraph/sourcegraph/issues/43692 
- [x] https://github.com/sourcegraph/sourcegraph/issues/27090 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43393 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43549 
  - [x] (🏁 258 days ago) https://github.com/sourcegraph/sourcegraph/issues/43692 

Completed: __2.00d__
- [x] (🏁 756 days ago) https://github.com/sourcegraph/sourcegraph/issues/24466 
- [x] (🏁 728 days ago) https://github.com/sourcegraph/sourcegraph/issues/24421 
- [x] (🏁 615 days ago) https://github.com/sourcegraph/sourcegraph/issues/27348 
- [x] (🏁 337 days ago) https://github.com/sourcegraph/sourcegraph/issues/43624 
- [x] (🏁 337 days ago) https://github.com/sourcegraph/sourcegraph/issues/43593 
- [x] (🏁 98 days ago) https://github.com/sourcegraph/sourcegraph/issues/52507  __2.00d__

@danielmarquespt

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43392 
  - [x] (🏁 312 days ago) https://github.com/sourcegraph/sourcegraph/issues/43535 

Completed
- [x] (🏁 312 days ago) https://github.com/sourcegraph/sourcegraph/issues/43535 

@jjinnii

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43676 
  - [x] (🏁 341 days ago) https://github.com/sourcegraph/sourcegraph/issues/43677 
  - [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/43678 
  - [x] (🏁 316 days ago) https://github.com/sourcegraph/sourcegraph/issues/43679 

Completed
- [x] (🏁 341 days ago) https://github.com/sourcegraph/sourcegraph/issues/43677 
- [x] (🏁 316 days ago) https://github.com/sourcegraph/sourcegraph/issues/43679 
- [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/43678 

@leonore

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43671 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 

Completed
- [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 

@novoselrok

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43676 
  - [x] (🏁 341 days ago) https://github.com/sourcegraph/sourcegraph/issues/43677 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43392 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43589 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43665 
  - [x] (🏁 302 days ago) https://github.com/sourcegraph/sourcegraph/issues/43590 
  - [x] (🏁 302 days ago) https://github.com/sourcegraph/sourcegraph/issues/43667 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43477 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43478 

Completed
- [x] (🏁 341 days ago) https://github.com/sourcegraph/sourcegraph/issues/43677 
- [x] (🏁 302 days ago) https://github.com/sourcegraph/sourcegraph/issues/43590 
- [x] (🏁 302 days ago) https://github.com/sourcegraph/sourcegraph/issues/43667 

@philipp-spiess: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43392  __2.00d__
  - [x] (🏁 342 days ago) https://github.com/sourcegraph/sourcegraph/issues/43417 
  - [x] (🏁 299 days ago) https://github.com/sourcegraph/sourcegraph/issues/43658 
  - [x] (🏁 295 days ago) https://github.com/sourcegraph/sourcegraph/issues/43659 
  - [x] (🏁 204 days ago) https://github.com/sourcegraph/sourcegraph/issues/44706  __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43477 
  - [x] (🏁 323 days ago) https://github.com/sourcegraph/sourcegraph/issues/43685 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43688 
  - [x] (🏁 295 days ago) https://github.com/sourcegraph/sourcegraph/issues/43689 
  - [x] (🏁 294 days ago) https://github.com/sourcegraph/sourcegraph/issues/43691 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/44357 
  - [x] (🏁 333 days ago) https://github.com/sourcegraph/sourcegraph/issues/43669 
  - [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/44358 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43676 
  - [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/43678 

Completed: __2.00d__
- [x] (🏁 342 days ago) https://github.com/sourcegraph/sourcegraph/issues/43417 
- [x] (🏁 333 days ago) https://github.com/sourcegraph/sourcegraph/issues/43669 
- [x] (🏁 323 days ago) https://github.com/sourcegraph/sourcegraph/issues/43685 
- [x] (🏁 317 days ago) https://github.com/sourcegraph/sourcegraph/issues/44296 
- [x] (🏁 317 days ago) https://github.com/sourcegraph/sourcegraph/issues/43687  🐛
- [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/44358 
- [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/43678 
- [x] (🏁 308 days ago) https://github.com/sourcegraph/sourcegraph/issues/44666 
- [x] (🏁 302 days ago) https://github.com/sourcegraph/sourcegraph/issues/43910 
- [x] (🏁 299 days ago) https://github.com/sourcegraph/sourcegraph/issues/43658 
- [x] (🏁 295 days ago) https://github.com/sourcegraph/sourcegraph/issues/43659 
- [x] (🏁 295 days ago) https://github.com/sourcegraph/sourcegraph/issues/43689 
- [x] (🏁 294 days ago) https://github.com/sourcegraph/sourcegraph/issues/43691 
- [x] (🏁 98 days ago) https://github.com/sourcegraph/sourcegraph/issues/52507  __2.00d__

@thenamankumar: __10.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43392  __10.00d__
  - [x] (🏁 264 days ago) https://github.com/sourcegraph/sourcegraph/issues/43620  __3.00d__
  - [x] (🏁 267 days ago) https://github.com/sourcegraph/sourcegraph/issues/43622  __2.00d__
  - [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43623  __3.00d__
  - [x] (🏁 204 days ago) https://github.com/sourcegraph/sourcegraph/issues/44706  __2.00d__

Completed: __10.00d__
- [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43623  __3.00d__
- [x] (🏁 267 days ago) https://github.com/sourcegraph/sourcegraph/issues/43622  __2.00d__
- [x] (🏁 264 days ago) https://github.com/sourcegraph/sourcegraph/issues/43620  __3.00d__
- [x] (🏁 98 days ago) https://github.com/sourcegraph/sourcegraph/issues/52507  __2.00d__

@vovakulikov

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44846 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44847 
  - [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43392 
  - [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43671 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43477 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44846 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44847 

Completed
- [x] (🏁 278 days ago) https://github.com/sourcegraph/sourcegraph/issues/43561 
- [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 
- [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
