### ISSUE TITLE
Ranking: migrate to dedicated project

### ISSUE THREAD

**Issue by sanderginn** [sourcegraph/sourcegraph#43404]
The bucket `lsif-pagerank-experiments` in the project `olafurpg-experiments` needs to be migrated to a dedicated `ranking-experiments` project.

### Todo
- [x] Add project definition to [TF](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/infrastructure/-/blob/gcp/projects/terraform.tfvars?L1-35)
- [x] Move bucket to new project ([docs](https://cloud.google.com/storage/docs/moving-buckets))
- [ ] Add bucket definition to TF
- [ ] Ensure IAM bindings are configured properly in order to view billing details
- [ ] Tear down `olafurpg-experiments`

### Unknowns
* Is `lsif-pagerank-experiments` constantly/actively written to? When can it be safely moved?
* Further technical requirements for this project?

**Comment by olafurpg** [comment]
We'll are still writing to the bucket. I'll post an update once we stop writing.

**Comment by jhchabran** [comment]
update: just need to wrap up

**Comment by sanderginn** [comment]
All resources have been deleted as they are no longer in use.
