### ISSUE TITLE
Other UI improvements - must have - FE scale audit - strategic readiness: Tracking issue

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43479]
### Description

This issue tracks all the must-have that came out of the [FE scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0) that all into 'other UI improvements' category.

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44358 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/44357 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44358 

@philipp-spiess

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 3 days ago) https://github.com/sourcegraph/sourcegraph/issues/43669 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/44357 
  - [x] (🏁 3 days ago) https://github.com/sourcegraph/sourcegraph/issues/43669 

Completed
- [x] (🏁 3 days ago) https://github.com/sourcegraph/sourcegraph/issues/43669 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by AlicjaSuska** [comment]
Closing: duplicated by mistake (#44357)
