### ISSUE TITLE
Lists (except for pagination) - must have - FE scale audit - strategic readiness: Tracking issue

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43477]
### Plan

This issue tracks all the must-have's that came out of the [FE scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0) that are related to lists (except for [pagination](https://github.com/sourcegraph/sourcegraph/issues/43392)).

### Tracked issues

@novoselrok

- [x] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/43478 

@philipp-spiess

- [x] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 323 days ago) https://github.com/sourcegraph/sourcegraph/issues/43685 

Completed
- [x] (🏁 323 days ago) https://github.com/sourcegraph/sourcegraph/issues/43685 

@vovakulikov

- [x] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44846 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44847 
- [x] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44846 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/44847 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
