### ISSUE TITLE
Display non-oob migrations in Site Admin UI [Tracking issue]

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#43536]
### Plan

We display only Out-of-band migrations in the Site Admin, it'll be great for customers and CEs to be able to have an overview of the actual migrations that have been run on their sourcegraph instance. 
Considering the `frontend` service won't start if `migrations` fail, it'll be worth it to look into decoupling this page or making the site admin accessible when migrations fail so customers can have an overview of what's failing and what's not.

<img width="1334" alt="CleanShot 2022-10-27 at 13 00 28@2x" src="https://user-images.githubusercontent.com/25608335/198267486-ae5a989c-e269-4924-addb-8759429cfce6.png">

[Context](https://sourcegraph.slack.com/archives/C07KZF47K/p1666772473060899)

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43537 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43539 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43540 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43541 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
