### ISSUE TITLE
Sorting - must have - FE scale audit - strategic readiness: Tracking issue

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43676]
### Plan

This issue tracks all the must-have's that came out of the [FE scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0) that are related to sorting.

### Tracked issues

@jjinnii

- [x] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 341 days ago) https://github.com/sourcegraph/sourcegraph/issues/43677 
  - [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/43678 
  - [x] (🏁 316 days ago) https://github.com/sourcegraph/sourcegraph/issues/43679 

Completed
- [x] (🏁 341 days ago) https://github.com/sourcegraph/sourcegraph/issues/43677 
- [x] (🏁 316 days ago) https://github.com/sourcegraph/sourcegraph/issues/43679 
- [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/43678 

@novoselrok

- [x] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 341 days ago) https://github.com/sourcegraph/sourcegraph/issues/43677 

Completed
- [x] (🏁 341 days ago) https://github.com/sourcegraph/sourcegraph/issues/43677 

@philipp-spiess

- [x] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/43678 

Completed
- [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/43678 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
