### ISSUE TITLE
Charts - must have - FE scale audit - strategic readiness: Tracking issue

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43671]
### Plan

This issue tracks all the must-have's that came out of the [FE scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0) that are related to charts.

### Tracked issues

@AlicjaSuska

- [x] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 
- [x] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 

Completed
- [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 

@leonore

- [x] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 
- [x] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 

Completed
- [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 

@vovakulikov

- [x] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 
- [x] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 
  - [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 

Completed
- [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43673 
- [x] (🏁 274 days ago) https://github.com/sourcegraph/sourcegraph/issues/43674 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
