### ISSUE TITLE
Alerts and warnings - must have - FE scale audit - strategic readiness: Tracking issue

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43688]
### Plan

This issue tracks all the must-have's that came out of the [FE scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0) that are related to warnings and alerts - communicating that the experience may not be optimal or cannot be served well because of the volume.

### Tracked issues

@AlicjaSuska

- [x] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 295 days ago) https://github.com/sourcegraph/sourcegraph/issues/43689 
  - [x] (🏁 294 days ago) https://github.com/sourcegraph/sourcegraph/issues/43691 

Completed
- [x] (🏁 295 days ago) https://github.com/sourcegraph/sourcegraph/issues/43689 
- [x] (🏁 294 days ago) https://github.com/sourcegraph/sourcegraph/issues/43691 

@courier-new

- [x] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 258 days ago) https://github.com/sourcegraph/sourcegraph/issues/43692 
- [x] https://github.com/sourcegraph/sourcegraph/issues/27090 
  - [x] (🏁 258 days ago) https://github.com/sourcegraph/sourcegraph/issues/43692 

Completed
- [x] (🏁 756 days ago) https://github.com/sourcegraph/sourcegraph/issues/24466 
- [x] (🏁 728 days ago) https://github.com/sourcegraph/sourcegraph/issues/24421 
- [x] (🏁 615 days ago) https://github.com/sourcegraph/sourcegraph/issues/27348 

@philipp-spiess

- [x] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 295 days ago) https://github.com/sourcegraph/sourcegraph/issues/43689 
  - [x] (🏁 294 days ago) https://github.com/sourcegraph/sourcegraph/issues/43691 

Completed
- [x] (🏁 295 days ago) https://github.com/sourcegraph/sourcegraph/issues/43689 
- [x] (🏁 294 days ago) https://github.com/sourcegraph/sourcegraph/issues/43691 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
