### ISSUE TITLE
⭐ Q4B1: Observability 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#43748]
# Observability Bet Q4

## Problem

Since the introduction of OpenTelemetry in 4.0 we still do not have a good grasp on our tracing observability. We still send a large amount of traces, so much so that Honeycomb and Grafana Cloud have:

* Rate limited us (Grafana cloud)
* Dropped our large spans (Grafana cloud)
* Notified us of large spans (Honeycomb)
* Notified us of breaking our quota (Honeycomb)

In terms of being rate limited and busting our quota, we addressed this by adding a Tail Sampler to the otel-collector. Even with the tail sampler we’re still sending a large amount. Which means we still haven’t addressed the source.

We also need to reduce the amount of providers we use for observability. Today, across all environments we send metrics, logs and traces to:

<table>
  <tr>
   <td>Provider
   </td>
   <td>What
   </td>
   <td>Environment
   </td>
  </tr>
  <tr>
   <td>GCloud
   </td>
   <td>Metrics, Logs, Traces 
   </td>
   <td>Managed instances (cloud), dotCom, Scaletesting
   </td>
  </tr>
  <tr>
   <td>Grafana Cloud
   </td>
   <td>Traces, Logs
   </td>
   <td>CI, dotCom, Dogfood
   </td>
  </tr>
  <tr>
   <td>HoneyComb
   </td>
   <td>Traces, Metrics
   </td>
   <td>CI, dotCom
   </td>
  </tr>
  <tr>
   <td>Jaeger (Bundled)
   </td>
   <td>Traces
   </td>
   <td>Dogfood*, S2
   </td>
  </tr>
  <tr>
   <td>Grafana (Bundled)
   </td>
   <td>Metrics
   </td>
   <td>Dogfood*
   </td>
  </tr>
</table>

As per above table, we can see there is a big overlap with the providers that we use for dotCom, which is also our largest spender. **Recently Grafana cloud has been “deprecated” and we need to move from it ASAP**. With the move, we should also consolidate on one preferred provider, at least for dotCom. 

_As a side note: A few engineers have mentioned that they quite enjoy using Honeycomb._

## Scope

For this bet we are removing the use of Grafana Cloud. We also want more control over our tracing. With more control we want to be able to enable and disable tracing easily and have a good idea about our size and rate of traces that we send.

## Boundaries

* No additional overall spend for observability
* Same version of otel-collector
* No additional tracing
* Update configuration regarding tracing
* For the CI pipeline, we only want to handle the pipeline case of uploading logs
* CI pipeline is not significantly interrupted with the move away from Grafana Cloud
* We can add metrics regarding our tracing and spend

## Definition of Done

* We have a single provider (outside of cloud) for all our observability and have made everyone aware of the single provider
* We have an answer for our send rates regarding our traces
* We know why we produced big traces/spans
* We are able to identify the source environment of a trace
* We have a dashboard with alerts set indicating our spend and quotas
* The handbook is updated with our preferred observability provider
* We are able to control our tracing through configuration
* Any configuration changes are documented

## Payout

* We have a preferred observability provider which we use in all our environments
* We don’t encounter warnings, alerts regarding the rate and size of our traces and spans
* We are alerted if our trace rate has increased and we will hit our budget/quota
* We are still able to troubleshoot and provide metrics of our CI
* Our Grafana Cloud usage and spend is 0.

## Approach

* We consolidate on one provider for all of our environments outside of cloud
* We introduce more tracing configuration to allow us more control
* Add metrics to our tracing to better observe how the feature is behaving
* Update the CI pipeline to stop using Grafana Cloud and switch to Honeycomb/Gcloud

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43947 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/44246 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/43978 

Completed
- [x] (🏁 300 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  🛠️

@burmudar

- [ ] https://github.com/sourcegraph/sourcegraph/issues/44016 

Completed
- [x] (🏁 300 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  🛠️
- [x] (🏁 125 days ago) https://github.com/sourcegraph/sourcegraph/pull/44772 

@marekweb

Completed
- [x] (🏁 300 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  🛠️

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by burmudar** [comment]
Some related work being done on frontend is being done by @valerybugakov in:
- #39272

We should make sure that whatever we do in this bet aligns with what is being done in the frontend
