### ISSUE TITLE
⭐ Q4B1: GCP Cost Saving Phase 3

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/sourcegraph#44099]
Previous work: 

- https://github.com/sourcegraph/sourcegraph/issues/42154
- [GCP Cost Savings Bet phase 3](https://docs.google.com/document/d/1HA1p-5EbqZvacRTQN5003C1nEDopUP6h2Jd96bFn5Pk/edit#)

## Problem

Continuation of previous [GCP Cost savings bet](https://docs.google.com/document/d/1iQwvnQBl_NzFB39xCarIpk-GQH6Q-EjDzWyVK7SroSw/edit#), there are still a couple key areas we can reduce spend on.

## Scope

We have used cookie cutter templates in the past that over provisioned our infrastructure; to reduce cloud cost and properly tune infrastructure we can work on the following:

- Identify services and deployments that are over provisioned using metrics to backup our reasoning
- Remove redundant or legacy infrastructure added in the past that creates overhead
- Work with other internal teams to understand how their services work and what is the proper deployment baseline
- Implement new tooling to help us control environments and reduce workloads

### Boundaries 

Sourcegraph dotcom and preprod 
Dogfood
Sourcegraph-CI 

### Definition of Done

- Reduce rest of dotcom’s deployments
- Optimize buildkite to have less pods hanging around and efficiently spin up the right # of nodes
- Dogfood environment is operating at their minimal provisioning while still operating properly
- Assist finance in creating FY2023 and 2024 cost models

## Payout 

We have an opportunity here to save another $20k-$30k/month on dotcom, dogfood and CI. Our goal is to not just cut costs, but to correctly tune our infrastructure so that we aren’t wasteful while still performant. These extra resources can be allocated to other parts of the company to help grow and sustain our business.

## Approach
We have the following areas to work on

Dotcom
- Work with search core and frontend teams to reduce CPU/Mem allocation for their services
- Integrate GKE backups and replace Velero
- Add node affinity for heavy workloads

Dogfood
- Continue cutting down resources until minimal environment is available
 
CI
- Understand and identify how the buildkite agent queue algo works
- Pack more jobs onto a node, and have less node hang time
- Reduce job agents in queue on weekends / low priority hours
- Research whether current custom VM is most cost effective

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/44871 

Completed
- [x] (🏁 228 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  🛠️

@jhchabran

- [ ] https://github.com/sourcegraph/sourcegraph/issues/44618 

Completed
- [x] (🏁 228 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  🛠️

@kalanchan

Completed
- [x] (🏁 228 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  🛠️

**Comment by jhchabran** [comment]
Closing this.
