### ISSUE TITLE
Other UI improvements - must have - FE scale audit - strategic readiness: Tracking issue

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#44357]
### Plan

This issue tracks all the 'other' UI issues that are must have's that came out of the strategic readiness audit but are not directly related to scale readiness.

Resources:

[Product Experience at Scale: Great vs. Good vs. Bad](https://docs.google.com/document/d/1KPsPfZqZ2AAIJ5Ybe7QrWKuaafYF5vUcaB1IfiF82Po/edit#heading=h.4jfhf6ai2t49)
[Raw scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0)

### Tracked issues

@AlicjaSuska

- [x] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/44358 

Completed
- [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/44358 

@philipp-spiess

- [x] https://github.com/sourcegraph/sourcegraph/issues/43391 
  - [x] (🏁 333 days ago) https://github.com/sourcegraph/sourcegraph/issues/43669 
  - [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/44358 

Completed
- [x] (🏁 333 days ago) https://github.com/sourcegraph/sourcegraph/issues/43669 
- [x] (🏁 313 days ago) https://github.com/sourcegraph/sourcegraph/issues/44358 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
