### ISSUE TITLE
Discovery of updates to free-licensing tier (final step of 4.0 P&P updates)

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#44657]
This ticket outlines the work to update the final changes to the 4.0 pricing and packaging: Introducing a new free tier of licensing. 

Full context on pricing and packaging changes [here](https://docs.google.com/document/d/1q1AiigPbzX1bwpSfQblGJfWTpGlwpRfxlW5GIL6ZnjY/edit#bookmark=id.tf1cgyb53jqw).

Specific context on the requirements of the free tier [here](https://docs.google.com/document/d/1eY06VXvjpIc_582soi5Zvw6KIwuma82pTgelWk4iHxw/edit). Note: There are some outstanding questions here we need to answer. I(Ryan) will pair with whichever developer begins to work on this.  

Deadline: Marketing plans to announce the first week of December to go into effect with the January release. 

/cc @sourcegraph/source/iam

### Spike

We're timeboxing this to `2d` as a spike to find out *how to implement this* and the goal should be that after 2 days the subtasks below are filled out.

### Subtasks
- [x] Introduce a new free plan so that existing users are not auto-migrated
- [x] Increase batch changes limit to 10
- [x] Limit private repositories to 1
- [x] Disable SAML auth provider

**Comment by kopancek** [comment]
I was researching on how we could achieving distinguishing old free plan customers from those using the new plan and here are my thoughts on that:
1. There is currently a table `versions` in the database that contains data in the following format:
![Image](https://user-images.githubusercontent.com/9974711/206685669-0e91fe88-79d1-4307-80bd-055badf1f156.png)
Or in the case of non-release build, the following format:
![Image](https://user-images.githubusercontent.com/9974711/206685797-e9ff55eb-e4ef-410a-97ab-cbd02894fb93.png)
2. When the service is started, [the following code is executed on sg side](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/cli/serve_cmd.go?L89)
```go
// InitDB initializes and returns the global database connection and sets the
// version of the frontend in our versions table.
func InitDB(logger sglog.Logger) (*sql.DB, error) {
	sqlDB, err := connections.EnsureNewFrontendDB(observation.ContextWithLogger(logger, &observation.TestContext), "", "frontend")
	if err != nil {
		return nil, errors.Errorf("failed to connect to frontend database: %s", err)
	}

	if err := upgradestore.New(database.NewDB(logger, sqlDB)).UpdateServiceVersion(context.Background(), "frontend", version.Version()); err != nil {
		return nil, err
	}

	return sqlDB, nil
}
```
3. We can hook into the function and add something **before** the `UpdateServiceVersion` call. We can then check if there is a record in the `versions` table for `free-plan`. 
  a. YES -> we use whatever version that points to. 
  b. NO -> We need to check if there is already a record for `frontend` service in the table
    I. YES -> this instance was already spinned up before, so we use `free-0` plan version (the old one)
    II. NO -> We use the new `free-1` plan version
    In any case, we store the plan version in the database, so that next time we ask, we can just read the plan version from the DB
All of the above needs to be behind a gate, which will probably need to be time based, e.g. is this happening after `2023-01-20` or whatever the date of free-1 plan release is. If we are not behind that date, `free-0` plan is applied
4. On the next service restart, we just read the value from the database, no need to check anything else anymore.

The drawback of this plan is, that customers can easily change the value in the database.

**Comment by kopancek** [comment]
Depending on the number of current free plan users, we may instead opt for a different solution if their number is sufficiently low.

## Create a free license for all the current customers
This would involve us creating a license for all the current free-0 plan customers and them applying the license if they want to stick to the old version of licensing. We can also just generate 1 free-0 license on sourcegraph.com and give the same license key to all of these customers.

## Create an API endpoint on sourcegraph.com to check the license
This would involve the most amount of work, hence why I mention it as last. But in general, this would add a central authority, which can determine the free plan version. It would mean, that existing free plan customers need to register their instance with us, if they want to continue using the old plan. Everyone else uses the new plan. If the API call fails, they are on the new plan as well (to protect the code from network outage).

**Comment by mrnugget** [comment]
> Create a free license for all the current customers

This seems like the simplest option, implementation wise, since it's mostly non-coding work.

Question: we still wouldn't be able to determine whether a user was a true "free-0" user, right?

If we would want to tell the user in the product "hey, you're being auto-upgraded to the new free plan, if you want to keep your old plan: send us a mail" we're back to square one, because we can't determine whether they're free-0, right?

**Comment by kopancek** [comment]
This is the latest update:
1. We are postponing implementation on this until February release
1. Creating a free license for all the free customers is not feasible, since there's too many
2. API endpoint would be too much effort, so not feasible
3. We should implement the solution suggested [in the previous comment](https://github.com/sourcegraph/sourcegraph/issues/44657#issuecomment-1344153113), but instead of throwing the license information in the `versions` table, we should create a new table instead with just the licensing information. This way we do not mix concerns in a single table and since we should have more time to implement the solution in January/February, let's do it without introducing too much tech debt.

**Comment by mrnugget** [comment]
I'm closing this, because it seems not relevant to current licensing/pricing discussions. Happy to reopen if that's not the case.
