### ISSUE TITLE
[Meta] FE scale audit: Reusable patterns for proper cursor-based pagination

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#44706]
We’re working on a [replacement for](https://github.com/sourcegraph/sourcegraph/pull/44664) `useConnection` with better defaults and support for bi-directional pagination. The existing `useConnection` hook was added as a replacement for <FilteredConnection/> a bit [over a year ago](https://github.com/sourcegraph/sourcegraph/pull/22722) and is a drop-in replacement for the older pattern on the frontend (without having to change anything in the backend). It does this very well: It’s currently simple to move from <FilteredConnection/> to the new hook implementation.

As part of the strategic scale-testing, I’m currently working with Naman and Kelli take this one step further: We’re rethinking how we’re doing pagination across the stack. This means that we now recommend a fully cursor-based implementation in the backend that supports traversal in both directions and we’re also changing the UI default from being an append-only list to showing individual pages. This will need new front-end components: a hook similar to `useConnection` and a [new pagination UI component](https://www.figma.com/file/LZoW17Fy6eqOfnxjxIRB7d/%F0%9F%93%91-Pagination-Experiments?t=0QPBSel9sN03v8us-1) and new back-end components.

## Plan

This issue tracks the high-level completion of this effort and is broken down into the following tasks:

- [x] #45247
- [x] [Rename](https://sourcegraph.slack.com/archives/C04931KQVRC/p1669050551421889) the existing `useConnection` hook to make it clear what it is still being used for. (#44703)
- [x] Add a new hook to consume the backend API and allows for easy traversal of the data. (#44664)
- [x] Implement the [new UI component](https://www.figma.com/file/LZoW17Fy6eqOfnxjxIRB7d/%F0%9F%93%91-Pagination-Experiments?t=0QPBSel9sN03v8us-1) as a first-class Wildcard component. (#44737)
- [x] Add explanation and examples to the docs (#45612)
- [ ] Migrate a few routes to the new pattern to learn about shortcomings and refine the API
- [ ] Extend backend support for custom cursors (other than `ID`) and custom `ORDER BY` columns (perhaps by using [composite types](https://www.postgresql.org/docs/current/rowtypes.html)?)

## Read more

Learn more on why cursor-based navigation is the new preferred way or why we following the Relay spec for cursor based navigation:

- https://use-the-index-luke.com/no-offset
- https://relay.dev/docs/guided-tour/list-data/advanced-pagination/
- https://shopify.dev/api/usage/pagination-graphql
- https://relay.dev/graphql/connections.htm

/cc @felixfbecker
