### ISSUE TITLE
Bazel Aspect-dev: building the frontend 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#44909]
## Aspect Migration Plan

- PNPM pre-factor
- Convert gulp generation steps to Bazel build targets 
  - schema
  - graphQlSchema
  - graphQlOperations
  - cssModulesTypings
- Build & bundle @sourcegraph/web with Bazel 
- Jest test examples (including jest snapshots) 
- Demonstrate fast development round-trip with webpack devserver
- Demonstrate optimized fast CI
- Demonstrate BUILD file generation

More detail is in their  notes doc:
https://hackmd.io/@aspect/By-gEU4Ni

 
 

## Process

@ Aspect: creating any issue and tagging it with `aspect-dev` will bring it to this issue automatically. Our usual workflow is to only tag issues, and have PRs to close the issues. 

See this page for more info: https://handbook.sourcegraph.com/departments/engineering/dev/process/tracking_issues/

For the reviewers, you can tag @jhchabran, @valerybugakov 

## Resources

- [Bazel @ Sourcegraph](https://docs.google.com/document/d/1HYbaYz9GAhjfHKCMgxi8O3Zi6n3uDkezR3pETxjtO8g/edit)
- [Sourcegraph / Aspect.dev](https://docs.google.com/document/u/2/d/16CcBg9dEK1SwmdXHAzKqQmhcIH3jpB_bwAB7KJC_ETc/edit)

### Sourcegraph

- [ ] Eliminate circular dependencies to unblock the Bazel integration.
    - [x] https://github.com/sourcegraph/sourcegraph/issues/45978
    - [x] https://github.com/sourcegraph/sourcegraph/issues/45979
    - [x] https://github.com/sourcegraph/sourcegraph/issues/46115
- [ ] Migrate from `yarn` to `pnpm`.
    - [x] https://github.com/sourcegraph/sourcegraph/issues/45970
    - [x] https://github.com/sourcegraph/sourcegraph/issues/45990
    - [ ] https://github.com/sourcegraph/sourcegraph/issues/45991

### Aspect

_TODO Aspect (plan as you see fit)_ 

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/43746 
  - [x] (🏁 224 days ago) https://github.com/sourcegraph/sourcegraph/issues/44910 

Completed
- [x] (🏁 410 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  🛠️

@gitstart-sourcegraph

- [ ] https://github.com/sourcegraph/sourcegraph/issues/45991 

Completed
- [x] (🏁 186 days ago) https://github.com/sourcegraph/sourcegraph/issues/45990 (PRs: ~[#46143](https://github.com/sourcegraph/sourcegraph/pull/46143)~)

@jbedard

- [ ] https://github.com/sourcegraph/sourcegraph/issues/46486 
  - [x] (🏁 138 days ago) https://github.com/sourcegraph/sourcegraph/pull/46193 

Completed
- [x] (🏁 227 days ago) https://github.com/sourcegraph/sourcegraph/pull/45016 
- [x] (🏁 214 days ago) https://github.com/sourcegraph/sourcegraph/pull/45689 
- [x] (🏁 213 days ago) https://github.com/sourcegraph/sourcegraph/pull/45682 
- [x] (🏁 213 days ago) https://github.com/sourcegraph/sourcegraph/pull/45697 
- [x] (🏁 210 days ago) https://github.com/sourcegraph/sourcegraph/pull/45792 
- [x] (🏁 210 days ago) https://github.com/sourcegraph/sourcegraph/pull/45789 
- [x] (🏁 209 days ago) https://github.com/sourcegraph/sourcegraph/pull/45793 
- [x] (🏁 209 days ago) https://github.com/sourcegraph/sourcegraph/pull/45826 
- [x] (🏁 209 days ago) https://github.com/sourcegraph/sourcegraph/pull/45831 
- [x] (🏁 208 days ago) https://github.com/sourcegraph/sourcegraph/pull/45756 
- [x] (🏁 208 days ago) https://github.com/sourcegraph/sourcegraph/pull/45866 
- [x] (🏁 207 days ago) https://github.com/sourcegraph/sourcegraph/pull/45922 
- [x] (🏁 206 days ago) https://github.com/sourcegraph/sourcegraph/pull/45946 
- [x] (🏁 205 days ago) https://github.com/sourcegraph/sourcegraph/pull/45954 
- [x] (🏁 189 days ago) https://github.com/sourcegraph/sourcegraph/pull/46188 
- [x] (🏁 189 days ago) https://github.com/sourcegraph/sourcegraph/pull/46189 
- [x] (🏁 187 days ago) https://github.com/sourcegraph/sourcegraph/pull/46258 
- [x] (🏁 181 days ago) https://github.com/sourcegraph/sourcegraph/pull/46536 
- [x] (🏁 175 days ago) https://github.com/sourcegraph/sourcegraph/pull/46740 
- [x] (🏁 175 days ago) https://github.com/sourcegraph/sourcegraph/pull/46613 
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/pull/46815 
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/pull/46872 
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/pull/46828 
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/pull/46873 
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/pull/46874 
- [x] (🏁 173 days ago) https://github.com/sourcegraph/sourcegraph/pull/46906 
- [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/pull/47049 
- [x] (🏁 167 days ago) https://github.com/sourcegraph/sourcegraph/pull/47060 
- [x] (🏁 164 days ago) https://github.com/sourcegraph/sourcegraph/pull/47139 
- [x] (🏁 164 days ago) https://github.com/sourcegraph/sourcegraph/pull/47222 
- [x] (🏁 138 days ago) https://github.com/sourcegraph/sourcegraph/pull/46193 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/pull/48520 
- [x] (🏁 133 days ago) https://github.com/sourcegraph/sourcegraph/pull/48670 
- [x] (🏁 133 days ago) https://github.com/sourcegraph/sourcegraph/pull/48671 
- [x] (🏁 132 days ago) https://github.com/sourcegraph/sourcegraph/pull/48779 

@jhchabran

Completed
- [x] (🏁 227 days ago) https://github.com/sourcegraph/sourcegraph/pull/45052 

@kormide

Completed
- [x] (🏁 227 days ago) https://github.com/sourcegraph/sourcegraph/pull/44755 
- [x] (🏁 226 days ago) https://github.com/sourcegraph/sourcegraph/pull/45089 
- [x] (🏁 224 days ago) https://github.com/sourcegraph/sourcegraph/pull/45090 

@valerybugakov

Completed
- [x] (🏁 221 days ago) https://github.com/sourcegraph/sourcegraph/pull/45398 
- [x] (🏁 210 days ago) https://github.com/sourcegraph/sourcegraph/pull/45760 
- [x] (🏁 210 days ago) https://github.com/sourcegraph/sourcegraph/pull/45761 
- [x] (🏁 209 days ago) https://github.com/sourcegraph/sourcegraph/pull/45763 
- [x] (🏁 209 days ago) https://github.com/sourcegraph/sourcegraph/pull/45839 
- [x] (🏁 209 days ago) https://github.com/sourcegraph/sourcegraph/pull/45838 
- [x] (🏁 209 days ago) https://github.com/sourcegraph/sourcegraph/pull/45807 
- [x] (🏁 208 days ago) https://github.com/sourcegraph/sourcegraph/pull/45889 
- [x] (🏁 206 days ago) https://github.com/sourcegraph/sourcegraph/pull/45812 
- [x] (🏁 206 days ago) https://github.com/sourcegraph/sourcegraph/pull/45899 
- [x] (🏁 203 days ago) https://github.com/sourcegraph/sourcegraph/pull/45945 
- [x] (🏁 203 days ago) https://github.com/sourcegraph/sourcegraph/pull/45948 
- [x] (🏁 203 days ago) https://github.com/sourcegraph/sourcegraph/pull/45949 
- [x] (🏁 203 days ago) https://github.com/sourcegraph/sourcegraph/pull/45967 
- [x] (🏁 202 days ago) https://github.com/sourcegraph/sourcegraph/pull/45953 
- [x] (🏁 193 days ago) https://github.com/sourcegraph/sourcegraph/pull/45976 
- [x] (🏁 193 days ago) https://github.com/sourcegraph/sourcegraph/pull/45977 
- [x] (🏁 189 days ago) https://github.com/sourcegraph/sourcegraph/pull/46192 
- [x] (🏁 188 days ago) https://github.com/sourcegraph/sourcegraph/pull/46194 
- [x] (🏁 187 days ago) https://github.com/sourcegraph/sourcegraph/pull/46145 
- [x] (🏁 186 days ago) https://github.com/sourcegraph/sourcegraph/pull/46143 
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/pull/45649 

--- 

Sourcegraph DRI: @jhchabran (+ @quinnhare)
