### ISSUE TITLE
Search contexts usability improvements implementation [tracking issue]

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#44903]
This is a tracking issue for the implementation of #44542

- [x] DB backend and GraphQL API for setting starred and default context (#44624)
- [x] Remove auto-defined contexts from the frontend, add `global` context to the existing `search_contexts` database table (#44875)
- [x] Modify GraphQL API query for `SearchContexts` to return in new order: first default, then starred, then any other contexts (#44876)
- [x] Implement new design for search context management page with table and menu
  - [x] Update page header (#44966)
  - [x] Use table view for desktop mode (#45001)
  - [x] Use cards for mobile/tablet mode (#45040)
- [x] Enable search context management page for everyone (#45302)
- [x] Implement stars
  - [x] Implement adding/removing stars in search context management page (#45230)
  - [x] Implement adding/removing stars in individual search context page (#45281)
  - [x] Show stars in search context dropdown (#45289)
- [x] Implement default context
  - [x] Implement setting default context in search context management page (#45387)
  - [x] Implement settings default context in individual search context page (#45391)
  - [x] Show default context in search context dropdown and remove the Reset button (#45430)
  - [x] Add backend to query default context (#45483)
  - [x] Modify search context behavior so default context is always selected first when the page is loaded. Remove the use of `LAST_SEARCH_CONTEXT_KEY` item in `localStorage`. (#45489)
  - [x] If no default context is available, a notice is shown in the dropdown to prompt users to select a new default. (#45500)
- [x] Add docs (#45569)

Post-implementation cleanup and polish (not necessary to complete this issue, can be spun off later):
- Implement page-based pagination in search context management page (depends on #44664)
- Completely remove auto-defined contexts from GraphQL API and backend
- Add action to duplicate a context (#44670) 

/cc @sourcegraph/search-product
