### ISSUE TITLE
Remove outdated feature flags

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#45048]
From a conversation with @ryphil on August 28: this is a list of feature flags (in Go, in TS, ...) that were part of the old Cloud v1 and that can now be removed.

- `experimentalFeatures.enablePostSignupFlow`
- feature flags:
  - `open-beta-enabled`
  - `org-code`
  - `org-email-invites`
  - `org-deletion`
  - `github-app-cloud`
- `props.authenticatedUser?.tags?.includes('CreateOrg')`
- site config `externalServiceUserMode` can be `disabled`, `unknown`, `public`, `all`

Then there’s also other tags:
- `AllowUserExternalServicePrivate`
- `AllowUserExternalServicePublic`

### Tasks

- [x] Audit which of these feature flags is still in use. 1 sentence per feature flag describing what it does and why.
- [x] Talk to Ryan again to confirm that the feature flag can be removed and, if necessary, define what the new default behaviour should be
- [ ] Remove feature flags
