### ISSUE TITLE
Onboarding tasks for Julie

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#45208]
- [x] Read or browse [Effective Go](https://go.dev/doc/effective_go). Goal: get to know some common Go idioms
- [x] https://github.com/sourcegraph/sourcegraph/issues/45220. Goal: dip your toes into Go
- [x] https://github.com/sourcegraph/sourcegraph/issues/45632. Goal: Familiarity with our query parsing and its quirks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/45466. Goal: Bigger task that gets you into jobs and search observability
- [x] Dogfooding: convert [Life of a search query docs](https://docs.sourcegraph.com/dev/background-information/architecture/life-of-a-search-query) to a [Sourcegraph Notebook](https://sourcegraph.com/notebooks/Tm90ZWJvb2s6MTk2Nw==).

**Comment by camdencheek** [comment]
@jtibshirani just added a [new one](https://github.com/sourcegraph/sourcegraph/issues/45466). This one is a little bit larger and more ambiguous, but does not have any deadlines on it 🙂

**Comment by jtibshirani** [comment]
Closing this out since I'm done onboarding, I'll still tackle https://github.com/sourcegraph/sourcegraph/issues/45466 separately.
