### ISSUE TITLE
insights: data retention: Tracking issue

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#45775]
**context**: code insights save data at pre-defined periodic times (hourly/daily/weekly/monthly/yearly). each data point corresponds to up to X * N rows in the database, where X is the number of repos the insight is defined to run over, and N is the number of query matches (1 for regular search, 1+ for capture group matching). we currently have no system in place to prune this data, even though we know 1) insights get slower to load the more data there is, 2) insights are not very legible the more samples are loaded.

**success criteria**
* Each insight is limited to some N samples.
* Samples older than samples[len(samples)-N:N] are moved to a separate table
* N is configurable (to some upper bound?)
* We allow users to view only a subset of samples, where the subset is of size L <= N 
* Older samples that have been moved to a separate table can be exported by a user (with their user context)

[original sync notes](https://docs.google.com/document/d/1H9jik0g5h_ZsDUTNTTAOXuW4rgnTk4wzp0HCJg5oUFs/edit)

### Tracked issues

@leonore

- [x] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 272 days ago) https://github.com/sourcegraph/sourcegraph/issues/45745 
  - [x] (🏁 261 days ago) https://github.com/sourcegraph/sourcegraph/issues/45746 
  - [x] (🏁 271 days ago) https://github.com/sourcegraph/sourcegraph/issues/45750 
  - [x] (🏁 279 days ago) https://github.com/sourcegraph/sourcegraph/issues/46073 
  - [x] (🏁 271 days ago) https://github.com/sourcegraph/sourcegraph/issues/46074 
  - [x] (🏁 259 days ago) https://github.com/sourcegraph/sourcegraph/issues/46243 

Completed
- [x] (🏁 279 days ago) https://github.com/sourcegraph/sourcegraph/issues/46073 
- [x] (🏁 272 days ago) https://github.com/sourcegraph/sourcegraph/issues/45745 
- [x] (🏁 271 days ago) https://github.com/sourcegraph/sourcegraph/issues/46074 
- [x] (🏁 271 days ago) https://github.com/sourcegraph/sourcegraph/issues/45750 
- [x] (🏁 261 days ago) https://github.com/sourcegraph/sourcegraph/issues/45746 
- [x] (🏁 259 days ago) https://github.com/sourcegraph/sourcegraph/issues/46243 

@vovakulikov

- [x] https://github.com/sourcegraph/sourcegraph/issues/43068 
  - [x] (🏁 263 days ago) https://github.com/sourcegraph/sourcegraph/issues/45823 
  - [x] (🏁 260 days ago) https://github.com/sourcegraph/sourcegraph/issues/46493 

Completed
- [x] (🏁 263 days ago) https://github.com/sourcegraph/sourcegraph/issues/45823 
- [x] (🏁 260 days ago) https://github.com/sourcegraph/sourcegraph/issues/46493 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](<https://en.wikipedia.org/wiki/Spike_(software_development)>)
- 🔒 Security issue
- 🙆 Stretch goal
