### ISSUE TITLE
Search 3.6 tracking issue

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#4582]
## Themes
low-latency, scalability, consistent results

## Completed
- [x] Code mod MVP #4464 @rvantonder

## Moved to 3.7
- [ ] p99 latency of the search query “print” at 42req/s with 20k repos is under 2s -- Core Services (3.6 issue: #4598, 3.7 issue: #4924)
- [ ] Scalable symbol search #3534 @kzh  
- [ ] Multiline non-indexed search #4518 @attfarhan

## Moved to 3.8 
- [ ] Repository-level pagination #2865 @slimsag

**Comment by keegancsmith** [comment]
@ijt The 3.6 milestone will be closed very soon. Please close this out and ensure you are tracking the work in a new tracking issue.
