### ISSUE TITLE
Add separate "edit" page for code hosts

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#46033]
We need to change the current page into being a purely "details" page. We need to add `/edit` page to edit the configuration. Just like with webhooks.

### Tasks

- [x] Create separate `/edit` page
- [x] Update all links to old page to `/edit` if they were about config changes
- [x] Move connection check to new "details" page
- [x] Show config on details page, but uneditable (no quick actions, no "Update configuration" button)
- [x] Link to "/edit" from new details page
- [x] Add "Delete" button to details page
- [x] Show number of repositories
- [x] Link to repositories page with filter-by-code-host-enabled

**Comment by sashaostrikov** [comment]
Maybe details page will spare us from making this extra check during ext svc sync:
https://github.com/sourcegraph/sourcegraph/blob/72f9ebf997ad6865e7f335314ee4b5f5b47f57f1/cmd/repo-updater/repoupdater/server.go#L177-L215

**Comment by sashaostrikov** [comment]
### TODOs after details page is created

#### Update URL from `/site-admin/external-services/${status.externalService.id}/edit` to `/site-admin/external-services/${status.externalService.id}`
- [ ] [StatusMessagesNavItem](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/nav/StatusMessagesNavItem.tsx?L284&subtree=true) page
- [ ] [ExternalServiceEntry](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/repo/settings/components/ExternalServiceEntry.tsx?L66&subtree=true) and [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/repo/settings/components/ExternalServiceEntry.tsx?L74&subtree=true) and [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/repo/settings/components/ExternalServiceEntry.tsx?L82&subtree=true)
- [ ] [`/cmd/repo-updater/shared/main.go`](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/repo-updater/shared/main.go?L400:25&subtree=true)
- [ ] [AddExternalServicePage](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/components/externalServices/AddExternalServicePage.tsx?L111&subtree=true)
- [ ] [and ExternalServiceNode](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/components/externalServices/ExternalServiceNode.tsx?L172&subtree=true)

Changes to `.../edit` are made in https://github.com/sourcegraph/sourcegraph/pull/46238.
