### ISSUE TITLE
Persist edit history for site configuration including author and expose via GraphQL

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#46031]
Part of https://github.com/sourcegraph/sourcegraph/issues/40377 but only about site-configuration.

## Tasks

- [x] Persist author for site config changes (we already persist the history in `critical_and_site_config` but don't record the author) #46150
- [x] ~~Maybe, depending on whether it's encrypted: re-encrypt history when encryption key changes?~~
    - We do not encrypt site config at the moment in the application layer
- [x] Define API to expose the site config history via GraphQL #46205, 
  - API would need to expose `history` with date/time, who, diff to previous edit.
  - Needs to support pagination
  - Draft:
    ```graphql
    siteConfiguration {
      // ...
      editHistory(last: 10) {
      nodes {
        id
        author { firstname, lastname } // <-- this is a User node
        date
        diff // <-- this is a diff
        // lines changed? removed? we already have a "diff" node in our GraphQL API, maybe we can reuse?
      }
      pageInfo {
        totalCount
        // ...
      }
      }
    }
    ```
- [ ] Implement API (Partly implemented (except diff) in: https://github.com/sourcegraph/sourcegraph/pull/46475)
  - [x] Handle changes to "redacted" values 
  - [ ] Compute diffs on the backend after loading requested number of edits

**Comment by indradhanush** [comment]
Had a chat with @mrnugget today and here's the plan going forward for generating diffs which is yet to be implemented:

#### Database changes
1. Add a new column to the `critical_and_site_config` table called `redacted_contents`
1. On write, store the redacted version of the config to this column but:
  i. Before redacting, replace each secret in the site config with its sha256 hash modulo 1000 and prefix it with `REDACTED-`, such that the access token would now look like: `REDACTED-999` for example
  
#### Diff implementation
1. When generating the diff, look at `redacted_contents` which will now pick up the diff on access tokens since underlying hash will have changed if the access token was updated 

#### API changes
1. Add a new boolean field to `SiteConfigurationChange` named `reproducableDiff` which indicates if the diff can be generated or not
  - For site config entries prior to introduction of this feature, it is not possible to generate the diffs safely without leaking the access token themselves
1. Make `Diff` nullable so that for changes with no diff it returns null instead of an empty string
