### ISSUE TITLE
Database Backed Permissions Syncing: Tracking issue

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#46078]
## Goal

Replace the `PermissionSyncer` with a [database-backed worker](https://docs.sourcegraph.com/dev/background-information/workers).

The customer impact is that we'll be able to show the current and previous state of permission syncing in the site-admin and user settings UI, making it easier to debug and predict permission syncing.

It'll also help us -- engineers on the IAM team -- debug permission syncer better and develop new features faster (example feature: provider-based sync jobs). Once permission syncing state is kept in the database (and not in memory, as it is right now), we can also move it to the `workers` service and scale horizontally if needed.

In the long term this is also a crucial step towards [sunsetting repo-updater](https://github.com/sourcegraph/sourcegraph/issues/16197) since `PermissionSyncer` is one of the big in-memory, singleton objects we are currently running in `repo-updater`.

## How?

The [`PermSyncer`, as it is right now](https://github.com/sourcegraph/sourcegraph/blob/187c92dc8c1648e2f24c08df4880c7bd5eda3452/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go#L42-L46) can be roughly divided into 3 parts:

1. The [scheduler](https://github.com/sourcegraph/sourcegraph/blob/187c92dc8c1648e2f24c08df4880c7bd5eda3452/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go#L1084-L1089) that queries the database for **users** and **repositories** for which we need to sync permissions and then enqueues in-memory sync jobs for them
2. The API that allows other parts of Sourcegraph to schedule permission sync jobs for users and repositories on demand
  - [`ScheduleUsers`](https://github.com/sourcegraph/sourcegraph/blob/187c92dc8c1648e2f24c08df4880c7bd5eda3452/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go#L105)
  - [`ScheduleRepos`](https://github.com/sourcegraph/sourcegraph/blob/187c92dc8c1648e2f24c08df4880c7bd5eda3452/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go#L155)
3. The [sync loop](https://github.com/sourcegraph/sourcegraph/blob/187c92dc8c1648e2f24c08df4880c7bd5eda3452/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go#L920) that works off the permission sync jobs from the in-memory queue and syncs user/repo permissions accordingly

All of that can be modeled as a database-backed worker:

1. Create a `permission_sync_jobs` table that represents requests to sync permissions for a given user/repo
2. Create a worker that works off permission sync jobs from that table
3. Create a scheduler that runs in the background and every X seconds enqueues `permission_sync_jobs` for users/repos that need to be synced
4. Create an API to enqueue jobs on the demand

I tried to do exactly that in my prototype: https://github.com/sourcegraph/sourcegraph/pull/44796

## Milestones

- [x] Milestone 1: [put prototype behind a feature flag and merge it](https://github.com/sourcegraph/sourcegraph/issues/45617) **WIP** `3d`
- [ ] Milestone 2: [turn prototype into proper solution](https://github.com/sourcegraph/sourcegraph/issues/46318) (`8d`)
- [ ] Milestone 3: [remove `PermsSyncer`, make database-backed syncer the default ](https://github.com/sourcegraph/sourcegraph/issues/46325)(`8d`)

Bonus:

- [ ] Record number of synced permissions on job (`2d`)
- [ ] Record execution_logs on job (`3d`)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by mrnugget** [comment]
Closing since it's done
