### ISSUE TITLE
Sourcegraph Own milestone planning

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#46306]
**WIP, this is just me exploring options! Don't read on, this will drastically change :)**

https://github.com/sourcegraph/sourcegraph/issues/46306#tasklist-block-196afea7-9151-4ed4-8cb3-5298b2005feb

https://github.com/sourcegraph/sourcegraph/issues/46306#tasklist-block-b0016c4b-0fba-4e7f-b01a-a665301cd152

### Questions to answer with Own MVP

- [ ] What is unowned (via search, want dashboard later)
- [ ] What is Owned by person X
- [ ] How did ownership coverage change over time (insights)
- [ ] How is the amount of stuff I/my team owns changing over time (insights)
- [ ] Search contexts competitor: Scope search to files owned by my team
- [ ] Who can I ask about the original piece of code that's changed in a PR for review
- [ ] Who can I ask for general guidance in language X?
- [ ] Who could know about this stuff?
- [ ] Who should own this code?
- [ ] What does our _actual_ org chart look like? Suggested team structures
