### ISSUE TITLE
Permissions Center: Tracking issue

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#46317]
[PR-FAQ](https://github.com/sourcegraph/pr-faqs/issues/23) | [Slack](https://sourcegraph.slack.com/archives/C04J31SQQNN) | [Figma mockups](https://www.figma.com/file/wmP7mAQds8DsrqQMuU2VSq/Permission-Center?node-id=78%3A2179&t=wuGZI0Uxv7sJBWT4-0)

### Plan
Currently, site admins need more visibility around who has access to what part of the code and why. Admins can not monitor the permissions syncing model, which runs in the background and struggle with debugging permissions issues for their users. 

With the Permissions Center MVP project, we aim to resolve all these pain points for our customers and make the system more “inspectable, debuggable, predictable" by having:
- Database-backed permissions syncing
- Permissions Sync Dashboard to monitor permission sync jobs
- Permissions Info Dashboard to view who has access to which repositories

*The [SCIM Project](https://github.com/sourcegraph/pr-faqs/issues/66), under the Permissions Center umbrella, works separately on adding new automation capabilities to our users management system and making it more intelligent.*

[DB backed perms syncing queue migration plan](https://github.com/sourcegraph/sourcegraph/issues/46078).

### Tracked issues

@unassigned: __8.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/46325  __2.00d__
  - [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/46772  __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/46324  __1.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/47874  __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/48336 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/49907  __2.00d__

Completed: __3.00d__
- [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/46772  __2.00d__
- [x] (🏁 88 days ago) https://github.com/sourcegraph/sourcegraph/issues/46329  __3.00d__

@danielmarquespt

Completed
- [x] (🏁 88 days ago) https://github.com/sourcegraph/sourcegraph/issues/46329 

@github-actions

Completed
- [x] (🏁 125 days ago) https://github.com/sourcegraph/sourcegraph/pull/49314 
- [x] (🏁 124 days ago) https://github.com/sourcegraph/sourcegraph/pull/49406 
- [x] (🏁 123 days ago) https://github.com/sourcegraph/sourcegraph/pull/49505 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/pull/49768 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/pull/49796 🐛
- [x] (🏁 88 days ago) https://github.com/sourcegraph/sourcegraph/issues/46329 

@kopancek

Completed
- [x] (🏁 124 days ago) https://github.com/sourcegraph/sourcegraph/issues/49327  🐛

@mrnugget: __3.00d__

Completed: __3.00d__
- [x] (🏁 186 days ago) https://github.com/sourcegraph/sourcegraph/issues/45617  __3.00d__

@sashaostrikov: __43.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/46318  __9.00d__
  - [x] (🏁 181 days ago) https://github.com/sourcegraph/sourcegraph/issues/46319 (PRs: ~[#46500](https://github.com/sourcegraph/sourcegraph/pull/46500)~, ~[#46568](https://github.com/sourcegraph/sourcegraph/pull/46568)~, ~[#46601](https://github.com/sourcegraph/sourcegraph/pull/46601)~) __3.00d__
  - [x] (🏁 179 days ago) https://github.com/sourcegraph/sourcegraph/issues/46321 (PRs: ~[#46656](https://github.com/sourcegraph/sourcegraph/pull/46656)~) __2.00d__
  - [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/issues/46322  __2.00d__
  - [x] (🏁 179 days ago) https://github.com/sourcegraph/sourcegraph/issues/46323 (PRs: ~[#46666](https://github.com/sourcegraph/sourcegraph/pull/46666)~) __1.00d__
  - [x] (🏁 178 days ago) https://github.com/sourcegraph/sourcegraph/issues/46697 (PRs: ~[#46699](https://github.com/sourcegraph/sourcegraph/pull/46699)~) __1.00d__
  - [x] (🏁 176 days ago) https://github.com/sourcegraph/sourcegraph/issues/46760 (PRs: ~[#46762](https://github.com/sourcegraph/sourcegraph/pull/46762)~)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/46325  __3.00d__
  - [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/46558  __2.00d__
  - [x] (🏁 171 days ago) https://github.com/sourcegraph/sourcegraph/issues/46975 (PRs: ~[#47009](https://github.com/sourcegraph/sourcegraph/pull/47009)~)
  - [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/issues/47023 (PRs: ~[#47106](https://github.com/sourcegraph/sourcegraph/pull/47106)~, ~[#47113](https://github.com/sourcegraph/sourcegraph/pull/47113)~) __1.00d__
  - [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/issues/47151 (PRs: ~[#47164](https://github.com/sourcegraph/sourcegraph/pull/47164)~, ~[#47271](https://github.com/sourcegraph/sourcegraph/pull/47271)~)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/47302 (PRs: ~[#48178](https://github.com/sourcegraph/sourcegraph/pull/48178)~) __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/48601  🐛

Completed: __41.50d__
- [x] (🏁 182 days ago) https://github.com/sourcegraph/sourcegraph/pull/46557 
- [x] (🏁 181 days ago) https://github.com/sourcegraph/sourcegraph/issues/46319 (PRs: ~[#46500](https://github.com/sourcegraph/sourcegraph/pull/46500)~, ~[#46568](https://github.com/sourcegraph/sourcegraph/pull/46568)~, ~[#46601](https://github.com/sourcegraph/sourcegraph/pull/46601)~) __3.00d__
- [x] (🏁 179 days ago) https://github.com/sourcegraph/sourcegraph/issues/46323 (PRs: ~[#46666](https://github.com/sourcegraph/sourcegraph/pull/46666)~) __1.00d__
- [x] (🏁 179 days ago) https://github.com/sourcegraph/sourcegraph/issues/46321 (PRs: ~[#46656](https://github.com/sourcegraph/sourcegraph/pull/46656)~) __2.00d__
- [x] (🏁 178 days ago) https://github.com/sourcegraph/sourcegraph/issues/46697 (PRs: ~[#46699](https://github.com/sourcegraph/sourcegraph/pull/46699)~) __1.00d__
- [x] (🏁 178 days ago) https://github.com/sourcegraph/sourcegraph/pull/46698 
- [x] (🏁 176 days ago) https://github.com/sourcegraph/sourcegraph/issues/46760 (PRs: ~[#46762](https://github.com/sourcegraph/sourcegraph/pull/46762)~)
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/issues/46322  __2.00d__
- [x] (🏁 173 days ago) https://github.com/sourcegraph/sourcegraph/pull/46938 
- [x] (🏁 173 days ago) https://github.com/sourcegraph/sourcegraph/pull/46977 
- [x] (🏁 171 days ago) https://github.com/sourcegraph/sourcegraph/issues/46975 (PRs: ~[#47009](https://github.com/sourcegraph/sourcegraph/pull/47009)~)
- [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/issues/47088  __1.00d__
- [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/issues/47023 (PRs: ~[#47106](https://github.com/sourcegraph/sourcegraph/pull/47106)~, ~[#47113](https://github.com/sourcegraph/sourcegraph/pull/47113)~) __1.00d__
- [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/pull/47172 
- [x] (🏁 167 days ago) https://github.com/sourcegraph/sourcegraph/pull/47247 
- [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/issues/47151 (PRs: ~[#47164](https://github.com/sourcegraph/sourcegraph/pull/47164)~, ~[#47271](https://github.com/sourcegraph/sourcegraph/pull/47271)~)
- [x] (🏁 165 days ago) https://github.com/sourcegraph/sourcegraph/pull/47350 
- [x] (🏁 165 days ago) https://github.com/sourcegraph/sourcegraph/pull/47367 
- [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/46558  __2.00d__
- [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/pull/47369 
- [x] (🏁 155 days ago) https://github.com/sourcegraph/sourcegraph/pull/47461 
- [x] (🏁 154 days ago) https://github.com/sourcegraph/sourcegraph/pull/47543 
- [x] (🏁 147 days ago) https://github.com/sourcegraph/sourcegraph/pull/47901 
- [x] (🏁 146 days ago) https://github.com/sourcegraph/sourcegraph/pull/47933 
- [x] (🏁 146 days ago) https://github.com/sourcegraph/sourcegraph/pull/47990 
- [x] (🏁 144 days ago) https://github.com/sourcegraph/sourcegraph/issues/48121 (PRs: ~[#48123](https://github.com/sourcegraph/sourcegraph/pull/48123)~)
- [x] (🏁 144 days ago) https://github.com/sourcegraph/sourcegraph/pull/48124 
- [x] (🏁 144 days ago) https://github.com/sourcegraph/sourcegraph/pull/48119 
- [x] (🏁 143 days ago) https://github.com/sourcegraph/sourcegraph/pull/48178 
- [x] (🏁 143 days ago) https://github.com/sourcegraph/sourcegraph/pull/48200 
- [x] (🏁 141 days ago) https://github.com/sourcegraph/sourcegraph/pull/48206 
- [x] (🏁 140 days ago) https://github.com/sourcegraph/sourcegraph/pull/48265 
- [x] (🏁 139 days ago) https://github.com/sourcegraph/sourcegraph/pull/48345 
- [x] (🏁 139 days ago) https://github.com/sourcegraph/sourcegraph/pull/48352 
- [x] (🏁 139 days ago) https://github.com/sourcegraph/sourcegraph/issues/48246  __2.00d__
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/pull/48548 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/pull/48462 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/pull/48600 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/pull/48604 
- [x] (🏁 136 days ago) https://github.com/sourcegraph/sourcegraph/pull/48607 
- [x] (🏁 136 days ago) https://github.com/sourcegraph/sourcegraph/pull/48624 
- [x] (🏁 134 days ago) https://github.com/sourcegraph/sourcegraph/pull/48633 
- [x] (🏁 134 days ago) https://github.com/sourcegraph/sourcegraph/issues/48707 (PRs: ~[#48708](https://github.com/sourcegraph/sourcegraph/pull/48708)~) __0.50d__
- [x] (🏁 133 days ago) https://github.com/sourcegraph/sourcegraph/issues/48416 (PRs: ~[#48735](https://github.com/sourcegraph/sourcegraph/pull/48735)~) __1.00d__
- [x] (🏁 132 days ago) https://github.com/sourcegraph/sourcegraph/pull/48820 
- [x] (🏁 132 days ago) https://github.com/sourcegraph/sourcegraph/pull/48811 
- [x] (🏁 131 days ago) https://github.com/sourcegraph/sourcegraph/pull/48900 
- [x] (🏁 130 days ago) https://github.com/sourcegraph/sourcegraph/pull/48999 
- [x] (🏁 130 days ago) https://github.com/sourcegraph/sourcegraph/pull/49011 
- [x] (🏁 130 days ago) https://github.com/sourcegraph/sourcegraph/pull/49076 
- [x] (🏁 125 days ago) https://github.com/sourcegraph/sourcegraph/issues/49183 (PRs: ~[#49286](https://github.com/sourcegraph/sourcegraph/pull/49286)~, ~[#49314](https://github.com/sourcegraph/sourcegraph/pull/49314)~) 🐛
- [x] (🏁 124 days ago) https://github.com/sourcegraph/sourcegraph/pull/49403 
- [x] (🏁 124 days ago) https://github.com/sourcegraph/sourcegraph/issues/49386 
- [x] (🏁 120 days ago) https://github.com/sourcegraph/sourcegraph/issues/47867 
- [x] (🏁 120 days ago) https://github.com/sourcegraph/sourcegraph/issues/46333  __1.00d__
- [x] (🏁 119 days ago) https://github.com/sourcegraph/sourcegraph/pull/49752 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/pull/49755 
- [x] (🏁 117 days ago) https://github.com/sourcegraph/sourcegraph/pull/49834 
- [x] (🏁 116 days ago) https://github.com/sourcegraph/sourcegraph/issues/46560 (PRs: ~[#49833](https://github.com/sourcegraph/sourcegraph/pull/49833)~, ~[#49908](https://github.com/sourcegraph/sourcegraph/pull/49908)~) __3.00d__
- [x] (🏁 116 days ago) https://github.com/sourcegraph/sourcegraph/pull/49903 
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/issues/49909 (PRs: ~[#49964](https://github.com/sourcegraph/sourcegraph/pull/49964)~) __1.00d__
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/50092 
- [x] (🏁 109 days ago) https://github.com/sourcegraph/sourcegraph/pull/50176 
- [x] (🏁 109 days ago) https://github.com/sourcegraph/sourcegraph/issues/50089 (PRs: ~[#50114](https://github.com/sourcegraph/sourcegraph/pull/50114)~)
- [x] (🏁 109 days ago) https://github.com/sourcegraph/sourcegraph/pull/50184 
- [x] (🏁 108 days ago) https://github.com/sourcegraph/sourcegraph/pull/50229 
- [x] (🏁 105 days ago) https://github.com/sourcegraph/sourcegraph/pull/50292 
- [x] (🏁 105 days ago) https://github.com/sourcegraph/sourcegraph/issues/50256  🐛
- [x] (🏁 95 days ago) https://github.com/sourcegraph/sourcegraph/pull/50535 
- [x] (🏁 88 days ago) https://github.com/sourcegraph/sourcegraph/issues/46329  __22.00d__
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/pull/52600 

@thenamankumar: __25.50d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/46318  __2.00d__
  - [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/issues/46320  __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/46325  __6.00d__
  - [x] (🏁 182 days ago) https://github.com/sourcegraph/sourcegraph/issues/46332 
  - [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/46558  __2.00d__
  - [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/issues/46559  __2.00d__
  - [x] (🏁 173 days ago) https://github.com/sourcegraph/sourcegraph/issues/46911  __1.00d__
  - [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/issues/47123  __0.50d__
  - [x] (🏁 151 days ago) https://github.com/sourcegraph/sourcegraph/issues/47160  __0.50d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/47077  __2.00d__
- [ ] https://github.com/sourcegraph/sourcegraph/issues/47873  __3.00d__

Completed: __20.50d__
- [x] (🏁 182 days ago) https://github.com/sourcegraph/sourcegraph/issues/46332 
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/issues/46320  __2.00d__
- [x] (🏁 173 days ago) https://github.com/sourcegraph/sourcegraph/issues/46911  __1.00d__
- [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/issues/46559  __2.00d__
- [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/issues/47123  __0.50d__
- [x] (🏁 165 days ago) https://github.com/sourcegraph/sourcegraph/issues/47084  __0.50d__
- [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/46558  __2.00d__
- [x] (🏁 151 days ago) https://github.com/sourcegraph/sourcegraph/issues/47160  __0.50d__
- [x] (🏁 151 days ago) https://github.com/sourcegraph/sourcegraph/issues/47732 
- [x] (🏁 145 days ago) https://github.com/sourcegraph/sourcegraph/issues/47734 
- [x] (🏁 140 days ago) https://github.com/sourcegraph/sourcegraph/issues/47869  __3.00d__
- [x] (🏁 138 days ago) https://github.com/sourcegraph/sourcegraph/issues/48349 
- [x] (🏁 138 days ago) https://github.com/sourcegraph/sourcegraph/issues/47871  __1.00d__
- [x] (🏁 138 days ago) https://github.com/sourcegraph/sourcegraph/issues/47870  __1.00d__
- [x] (🏁 138 days ago) https://github.com/sourcegraph/sourcegraph/issues/47878  __1.00d__
- [x] (🏁 131 days ago) https://github.com/sourcegraph/sourcegraph/issues/48332  __1.00d__
- [x] (🏁 131 days ago) https://github.com/sourcegraph/sourcegraph/issues/48331  __2.00d__
- [x] (🏁 127 days ago) https://github.com/sourcegraph/sourcegraph/issues/47877  __2.00d__
- [x] (🏁 126 days ago) https://github.com/sourcegraph/sourcegraph/issues/49168  🐛
- [x] (🏁 126 days ago) https://github.com/sourcegraph/sourcegraph/issues/49285  🐛
- [x] (🏁 124 days ago) https://github.com/sourcegraph/sourcegraph/pull/49495 
- [x] (🏁 120 days ago) https://github.com/sourcegraph/sourcegraph/issues/47867 
- [x] (🏁 118 days ago) https://github.com/sourcegraph/sourcegraph/pull/49777 🐛
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/issues/50025  🐛
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/50078 
- [x] (🏁 105 days ago) https://github.com/sourcegraph/sourcegraph/issues/50256  🐛
- [x] (🏁 88 days ago) https://github.com/sourcegraph/sourcegraph/issues/46329  __6.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
