### ISSUE TITLE
[DB Backed Perms Syncing] Milestone 2 Proper Solution: Tracking Issue

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#46318]
### Tracked issues

@sashaostrikov: __9.00d__

- [x] https://github.com/sourcegraph/sourcegraph/issues/46317  __9.00d__
  - [x] (🏁 181 days ago) https://github.com/sourcegraph/sourcegraph/issues/46319 (PRs: ~[#46500](https://github.com/sourcegraph/sourcegraph/pull/46500)~, ~[#46568](https://github.com/sourcegraph/sourcegraph/pull/46568)~, ~[#46601](https://github.com/sourcegraph/sourcegraph/pull/46601)~) __3.00d__
  - [x] (🏁 179 days ago) https://github.com/sourcegraph/sourcegraph/issues/46321 (PRs: ~[#46656](https://github.com/sourcegraph/sourcegraph/pull/46656)~) __2.00d__
  - [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/issues/46322  __2.00d__
  - [x] (🏁 179 days ago) https://github.com/sourcegraph/sourcegraph/issues/46323 (PRs: ~[#46666](https://github.com/sourcegraph/sourcegraph/pull/46666)~) __1.00d__
  - [x] (🏁 178 days ago) https://github.com/sourcegraph/sourcegraph/issues/46697 (PRs: ~[#46699](https://github.com/sourcegraph/sourcegraph/pull/46699)~) __1.00d__
  - [x] (🏁 176 days ago) https://github.com/sourcegraph/sourcegraph/issues/46760 (PRs: ~[#46762](https://github.com/sourcegraph/sourcegraph/pull/46762)~)

Completed: __9.00d__
- [x] (🏁 181 days ago) https://github.com/sourcegraph/sourcegraph/issues/46319 (PRs: ~[#46500](https://github.com/sourcegraph/sourcegraph/pull/46500)~, ~[#46568](https://github.com/sourcegraph/sourcegraph/pull/46568)~, ~[#46601](https://github.com/sourcegraph/sourcegraph/pull/46601)~) __3.00d__
- [x] (🏁 179 days ago) https://github.com/sourcegraph/sourcegraph/issues/46323 (PRs: ~[#46666](https://github.com/sourcegraph/sourcegraph/pull/46666)~) __1.00d__
- [x] (🏁 179 days ago) https://github.com/sourcegraph/sourcegraph/issues/46321 (PRs: ~[#46656](https://github.com/sourcegraph/sourcegraph/pull/46656)~) __2.00d__
- [x] (🏁 178 days ago) https://github.com/sourcegraph/sourcegraph/issues/46697 (PRs: ~[#46699](https://github.com/sourcegraph/sourcegraph/pull/46699)~) __1.00d__
- [x] (🏁 176 days ago) https://github.com/sourcegraph/sourcegraph/issues/46760 (PRs: ~[#46762](https://github.com/sourcegraph/sourcegraph/pull/46762)~)
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/issues/46322  __2.00d__

@thenamankumar: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/46317  __2.00d__
  - [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/issues/46320  __2.00d__

Completed: __2.00d__
- [x] (🏁 174 days ago) https://github.com/sourcegraph/sourcegraph/issues/46320  __2.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
