### ISSUE TITLE
[DB Backed Perms Syncing] Milestone 3 Remove old PermSyncer: Tracking Issue

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#46325]
### Plan

Milestone 3: remove `PermsSyncer`, make database-backed syncer the default

**Testing!!** At this point we need to be _super confident_ that it works like it should 
### Tracked issues

@unassigned: __2.00d__

- [x] https://github.com/sourcegraph/sourcegraph/issues/46317  __2.00d__
  - [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/46772  __2.00d__

Completed: __2.00d__
- [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/46772  __2.00d__

@sashaostrikov: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/46317  __3.00d__
  - [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/46558  __2.00d__
  - [x] (🏁 171 days ago) https://github.com/sourcegraph/sourcegraph/issues/46975 (PRs: ~[#47009](https://github.com/sourcegraph/sourcegraph/pull/47009)~)
  - [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/issues/47023 (PRs: ~[#47106](https://github.com/sourcegraph/sourcegraph/pull/47106)~, ~[#47113](https://github.com/sourcegraph/sourcegraph/pull/47113)~) __1.00d__
  - [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/issues/47151 (PRs: ~[#47164](https://github.com/sourcegraph/sourcegraph/pull/47164)~, ~[#47271](https://github.com/sourcegraph/sourcegraph/pull/47271)~)

Completed: __3.00d__
- [x] (🏁 171 days ago) https://github.com/sourcegraph/sourcegraph/issues/46975 (PRs: ~[#47009](https://github.com/sourcegraph/sourcegraph/pull/47009)~)
- [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/issues/47023 (PRs: ~[#47106](https://github.com/sourcegraph/sourcegraph/pull/47106)~, ~[#47113](https://github.com/sourcegraph/sourcegraph/pull/47113)~) __1.00d__
- [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/issues/47151 (PRs: ~[#47164](https://github.com/sourcegraph/sourcegraph/pull/47164)~, ~[#47271](https://github.com/sourcegraph/sourcegraph/pull/47271)~)
- [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/46558  __2.00d__

@thenamankumar: __6.00d__

- [x] https://github.com/sourcegraph/sourcegraph/issues/46317  __6.00d__
  - [x] (🏁 182 days ago) https://github.com/sourcegraph/sourcegraph/issues/46332 
  - [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/46558  __2.00d__
  - [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/issues/46559  __2.00d__
  - [x] (🏁 173 days ago) https://github.com/sourcegraph/sourcegraph/issues/46911  __1.00d__
  - [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/issues/47123  __0.50d__
  - [x] (🏁 151 days ago) https://github.com/sourcegraph/sourcegraph/issues/47160  __0.50d__

Completed: __6.00d__
- [x] (🏁 182 days ago) https://github.com/sourcegraph/sourcegraph/issues/46332 
- [x] (🏁 173 days ago) https://github.com/sourcegraph/sourcegraph/issues/46911  __1.00d__
- [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/issues/46559  __2.00d__
- [x] (🏁 168 days ago) https://github.com/sourcegraph/sourcegraph/issues/47123  __0.50d__
- [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/46558  __2.00d__
- [x] (🏁 151 days ago) https://github.com/sourcegraph/sourcegraph/issues/47160  __0.50d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
