### ISSUE TITLE
Permission Syncs Dashboard: Tracking issue

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#46329]
### Plan

Currently, there is no way for site admins to monitor the permissions syncing, which works in the background. Debugging failed permission syncs is also not easy. We get our inspiration from the "Manage Code Host", "Repositories", and "Executor Instances" pages to build a similar dashboard for permission syncing. 

The initial version of the dashboard will include the following:

- [ ] Sync bobs listing (real-time via polling)
    - [ ] User/Repo details + link to their permissions info page
    - [ ] Status of job (success, in progress, failed)
    - [ ] queuedAt, successAt, failedAt, execution time
    - [ ] Reason type: manual, scheduled-*, webhook-*event
    - [ ] Count of new permissions added/removed and total number of permissions
    - [ ] Execution logs
- [ ] Stats
    - [ ] Queue Size
    - [ ] Total no of failures, success, etc TBD
- [ ] Filters
    - [ ] By user
    - [ ] By repo
    - [ ] By status
    - [ ] By trigger reason
- [ ] Actions
    - [ ] Clear Queue -> cancel all jobs in the queue
- [ ] Bonus TBD

### Tracked issues

@unassigned: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/46317  __3.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/47874  __2.00d__
  - [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/47085 
  - [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/47307 
  - [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/47881  __1.00d__

Completed: __1.00d__
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/47881  __1.00d__
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/47085 
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/47307 

@danielmarquespt

- [ ] https://github.com/sourcegraph/sourcegraph/issues/46317 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/46489 

@github-actions

- [ ] https://github.com/sourcegraph/sourcegraph/issues/46317 
  - [x] (🏁 34 days ago) https://github.com/sourcegraph/sourcegraph/pull/49580 

Completed
- [x] (🏁 34 days ago) https://github.com/sourcegraph/sourcegraph/pull/49580 

@sashaostrikov: __22.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/46317  __22.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/47302 (PRs: ~[#48178](https://github.com/sourcegraph/sourcegraph/pull/48178)~) __2.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/48601  🐛
  - [x] (🏁 66 days ago) https://github.com/sourcegraph/sourcegraph/issues/47082 (PRs: ~[#47543](https://github.com/sourcegraph/sourcegraph/pull/47543)~, ~[#47730](https://github.com/sourcegraph/sourcegraph/pull/47730)~) __1.00d__
  - [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/47301 (PRs: ~[#47350](https://github.com/sourcegraph/sourcegraph/pull/47350)~, ~[#47367](https://github.com/sourcegraph/sourcegraph/pull/47367)~) __1.00d__
  - [x] (🏁 51 days ago) https://github.com/sourcegraph/sourcegraph/issues/47303 (PRs: ~[#48345](https://github.com/sourcegraph/sourcegraph/pull/48345)~, ~[#48352](https://github.com/sourcegraph/sourcegraph/pull/48352)~) __2.00d__
  - [x] (🏁 72 days ago) https://github.com/sourcegraph/sourcegraph/issues/47306  __1.00d__
  - [x] (🏁 58 days ago) https://github.com/sourcegraph/sourcegraph/issues/47308 (PRs: ~[#47933](https://github.com/sourcegraph/sourcegraph/pull/47933)~) __1.00d__
  - [x] (🏁 58 days ago) https://github.com/sourcegraph/sourcegraph/issues/47731 (PRs: ~[#47901](https://github.com/sourcegraph/sourcegraph/pull/47901)~, ~[#47933](https://github.com/sourcegraph/sourcegraph/pull/47933)~) __2.00d__
  - [x] (🏁 52 days ago) https://github.com/sourcegraph/sourcegraph/issues/47868 (PRs: ~[#48119](https://github.com/sourcegraph/sourcegraph/pull/48119)~, ~[#48206](https://github.com/sourcegraph/sourcegraph/pull/48206)~) __2.00d__
  - [x] (🏁 46 days ago) https://github.com/sourcegraph/sourcegraph/issues/47872 (PRs: ~[#48462](https://github.com/sourcegraph/sourcegraph/pull/48462)~) __2.00d__
  - [x] (🏁 44 days ago) https://github.com/sourcegraph/sourcegraph/issues/47879 (PRs: ~[#48811](https://github.com/sourcegraph/sourcegraph/pull/48811)~) __1.00d__
  - [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/47880  __2.00d__
  - [x] (🏁 52 days ago) https://github.com/sourcegraph/sourcegraph/issues/48245 (PRs: ~[#48265](https://github.com/sourcegraph/sourcegraph/pull/48265)~) __2.00d__
  - [x] (🏁 43 days ago) https://github.com/sourcegraph/sourcegraph/issues/48894 (PRs: ~[#48900](https://github.com/sourcegraph/sourcegraph/pull/48900)~) __1.00d__
  - [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/48895 (PRs: ~[#48999](https://github.com/sourcegraph/sourcegraph/pull/48999)~) __1.00d__
  - [x] (🏁 38 days ago) https://github.com/sourcegraph/sourcegraph/issues/49073 (PRs: ~[#49121](https://github.com/sourcegraph/sourcegraph/pull/49121)~) __1.00d__
  - [x] (🏁 34 days ago) https://github.com/sourcegraph/sourcegraph/pull/49529 

Completed: __20.00d__
- [x] (🏁 72 days ago) https://github.com/sourcegraph/sourcegraph/issues/47306  __1.00d__
- [x] (🏁 66 days ago) https://github.com/sourcegraph/sourcegraph/issues/47082 (PRs: ~[#47543](https://github.com/sourcegraph/sourcegraph/pull/47543)~, ~[#47730](https://github.com/sourcegraph/sourcegraph/pull/47730)~) __1.00d__
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/47301 (PRs: ~[#47350](https://github.com/sourcegraph/sourcegraph/pull/47350)~, ~[#47367](https://github.com/sourcegraph/sourcegraph/pull/47367)~) __1.00d__
- [x] (🏁 58 days ago) https://github.com/sourcegraph/sourcegraph/issues/47731 (PRs: ~[#47901](https://github.com/sourcegraph/sourcegraph/pull/47901)~, ~[#47933](https://github.com/sourcegraph/sourcegraph/pull/47933)~) __2.00d__
- [x] (🏁 58 days ago) https://github.com/sourcegraph/sourcegraph/issues/47308 (PRs: ~[#47933](https://github.com/sourcegraph/sourcegraph/pull/47933)~) __1.00d__
- [x] (🏁 52 days ago) https://github.com/sourcegraph/sourcegraph/issues/47868 (PRs: ~[#48119](https://github.com/sourcegraph/sourcegraph/pull/48119)~, ~[#48206](https://github.com/sourcegraph/sourcegraph/pull/48206)~) __2.00d__
- [x] (🏁 52 days ago) https://github.com/sourcegraph/sourcegraph/issues/48245 (PRs: ~[#48265](https://github.com/sourcegraph/sourcegraph/pull/48265)~) __2.00d__
- [x] (🏁 51 days ago) https://github.com/sourcegraph/sourcegraph/issues/47303 (PRs: ~[#48345](https://github.com/sourcegraph/sourcegraph/pull/48345)~, ~[#48352](https://github.com/sourcegraph/sourcegraph/pull/48352)~) __2.00d__
- [x] (🏁 46 days ago) https://github.com/sourcegraph/sourcegraph/issues/47872 (PRs: ~[#48462](https://github.com/sourcegraph/sourcegraph/pull/48462)~) __2.00d__
- [x] (🏁 44 days ago) https://github.com/sourcegraph/sourcegraph/issues/47879 (PRs: ~[#48811](https://github.com/sourcegraph/sourcegraph/pull/48811)~) __1.00d__
- [x] (🏁 43 days ago) https://github.com/sourcegraph/sourcegraph/issues/48894 (PRs: ~[#48900](https://github.com/sourcegraph/sourcegraph/pull/48900)~) __1.00d__
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/48895 (PRs: ~[#48999](https://github.com/sourcegraph/sourcegraph/pull/48999)~) __1.00d__
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/issues/47880  __2.00d__
- [x] (🏁 38 days ago) https://github.com/sourcegraph/sourcegraph/issues/49073 (PRs: ~[#49121](https://github.com/sourcegraph/sourcegraph/pull/49121)~) __1.00d__
- [x] (🏁 34 days ago) https://github.com/sourcegraph/sourcegraph/pull/49529 

@thenamankumar: __6.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/46317  __6.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/47077  __2.00d__
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/47873  __3.00d__
  - [x] (🏁 77 days ago) https://github.com/sourcegraph/sourcegraph/issues/47076 
  - [x] (🏁 66 days ago) https://github.com/sourcegraph/sourcegraph/issues/47082 (PRs: ~[#47543](https://github.com/sourcegraph/sourcegraph/pull/47543)~, ~[#47730](https://github.com/sourcegraph/sourcegraph/pull/47730)~) __1.00d__

Completed: __1.00d__
- [x] (🏁 77 days ago) https://github.com/sourcegraph/sourcegraph/issues/47076 
- [x] (🏁 66 days ago) https://github.com/sourcegraph/sourcegraph/issues/47082 (PRs: ~[#47543](https://github.com/sourcegraph/sourcegraph/pull/47543)~, ~[#47730](https://github.com/sourcegraph/sourcegraph/pull/47730)~) __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
