### ISSUE TITLE
Code Nav: 3.6 Tracking Issue

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#4639]
## Goals

- Enterprise customers using Bitbucket Server, Gitlab can deploy Sourcegraph features on the code host easily using native integrations.
- Extensions: keep polishing the Sentry extension experience.
- Code intelligence: keep investigating LSIF.

## Work

- [x] Bitbucket Server native integration #4236 
- [x] Gitlab native integration #1000
- [ ] Sentry integration #4756 (V2), #2985 
- [ ] Add LSIF support to Sourcegraph https://github.com/sourcegraph/sourcegraph/issues/4692

**Comment by lguychard** [comment]
- Bitbucket server native integration was completed. See #4236 for full scope & task breakdown. Follow-up issues: https://github.com/sourcegraph/sourcegraph/issues/4236#issuecomment-511342615

**Comment by felixfbecker** [comment]
- MR for GitLab integration is open and in review by GitLab: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/30574

**Comment by vanesa** [comment]
- Sentry extension is currently blocked due to a CORS issue with the Sentry API, will be taking to 3.7.

**Comment by chrismwendt** [comment]
- LSIF support was added in https://github.com/sourcegraph/sourcegraph/pull/4799 Follow-up issues:
  - Write a Go LSIF exporter (Joe)
  - Add a new token type: LSIF upload tokens
  - Convert repository names to IDs
