### ISSUE TITLE
JobFair: Bazel Tracking Issue

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#46486]
Board: https://github.com/orgs/sourcegraph/projects/311
Doc: https://docs.google.com/document/d/1qTA1_O4JagpK8GH5ypW47-E_Y6JL0ZTnLz-GlooxIwc/edit#heading=h.1tqe9otelmby

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/48991 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/47900 

@burmudar

Completed
- [x] (🏁 135 days ago) https://github.com/sourcegraph/sourcegraph/pull/48568 
- [x] (🏁 132 days ago) https://github.com/sourcegraph/sourcegraph/pull/48711 
- [x] (🏁 132 days ago) https://github.com/sourcegraph/sourcegraph/pull/48717 
- [x] (🏁 132 days ago) https://github.com/sourcegraph/sourcegraph/pull/48632 
- [x] (🏁 131 days ago) https://github.com/sourcegraph/sourcegraph/pull/48813 
- [x] (🏁 129 days ago) https://github.com/sourcegraph/sourcegraph/pull/48448 
- [x] (🏁 123 days ago) https://github.com/sourcegraph/sourcegraph/pull/49103 
- [x] (🏁 117 days ago) https://github.com/sourcegraph/sourcegraph/pull/49005 
- [x] (🏁 116 days ago) https://github.com/sourcegraph/sourcegraph/pull/49910 
- [x] (🏁 111 days ago) https://github.com/sourcegraph/sourcegraph/pull/50066 
- [x] (🏁 48 days ago) https://github.com/sourcegraph/sourcegraph/pull/52539 

@davejrt

Completed
- [x] (🏁 143 days ago) https://github.com/sourcegraph/sourcegraph/issues/47807 

@jbedard

- [x] https://github.com/sourcegraph/sourcegraph/issues/44909 
  - [x] (🏁 138 days ago) https://github.com/sourcegraph/sourcegraph/pull/46193 

Completed
- [x] (🏁 138 days ago) https://github.com/sourcegraph/sourcegraph/pull/46193 
- [x] (🏁 119 days ago) https://github.com/sourcegraph/sourcegraph/pull/48978 

@jhchabran

- [ ] https://github.com/sourcegraph/sourcegraph/issues/50032 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52914 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/46850 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/46870 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/46871 
- [ ] https://github.com/sourcegraph/sourcegraph/pull/47902 

Completed
- [x] (🏁 410 days ago) https://github.com/sourcegraph/sourcegraph/issues/33242  🛠️
- [x] (🏁 179 days ago) https://github.com/sourcegraph/sourcegraph/pull/46660 
- [x] (🏁 178 days ago) https://github.com/sourcegraph/sourcegraph/issues/46667 
- [x] (🏁 175 days ago) https://github.com/sourcegraph/sourcegraph/pull/46720 
- [x] (🏁 171 days ago) https://github.com/sourcegraph/sourcegraph/issues/46832 
- [x] (🏁 171 days ago) https://github.com/sourcegraph/sourcegraph/issues/46841 
- [x] (🏁 167 days ago) https://github.com/sourcegraph/sourcegraph/issues/46840 
- [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/issues/46834 
- [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/issues/46842 
- [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/issues/46844 
- [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/issues/46846 
- [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/issues/46848 
- [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/issues/46852 
- [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/issues/46854 
- [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/issues/46860 
- [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/issues/46866 
- [x] (🏁 143 days ago) https://github.com/sourcegraph/sourcegraph/issues/47807 
- [x] (🏁 143 days ago) https://github.com/sourcegraph/sourcegraph/issues/46683 
- [x] (🏁 143 days ago) https://github.com/sourcegraph/sourcegraph/issues/46516 
- [x] (🏁 138 days ago) https://github.com/sourcegraph/sourcegraph/pull/48451 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46837 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46856 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46862 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46864 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46833 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46835 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46836 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46838 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46843 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46845 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46849 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46851 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46855 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46857 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46858 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46859 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46861 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46863 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46865 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46867 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/issues/46853 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/pull/48460 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/pull/48534 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/pull/48547 
- [x] (🏁 136 days ago) https://github.com/sourcegraph/sourcegraph/pull/48620 
- [x] (🏁 133 days ago) https://github.com/sourcegraph/sourcegraph/issues/46839 
- [x] (🏁 132 days ago) https://github.com/sourcegraph/sourcegraph/pull/48545 
- [x] (🏁 131 days ago) https://github.com/sourcegraph/sourcegraph/pull/48906 
- [x] (🏁 126 days ago) https://github.com/sourcegraph/sourcegraph/pull/49169 
- [x] (🏁 117 days ago) https://github.com/sourcegraph/sourcegraph/pull/49228 
- [x] (🏁 116 days ago) https://github.com/sourcegraph/sourcegraph/pull/49898 
- [x] (🏁 112 days ago) https://github.com/sourcegraph/sourcegraph/pull/49966 
- [x] (🏁 82 days ago) https://github.com/sourcegraph/sourcegraph/pull/49217 
- [x] (🏁 59 days ago) https://github.com/sourcegraph/sourcegraph/pull/52186 
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/pull/52916 
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/pull/52923 

@valerybugakov

Completed
- [x] (🏁 166 days ago) https://github.com/sourcegraph/sourcegraph/issues/46844 
- [x] (🏁 160 days ago) https://github.com/sourcegraph/sourcegraph/issues/46973 
- [x] (🏁 137 days ago) https://github.com/sourcegraph/sourcegraph/pull/48418 
- [x] (🏁 132 days ago) https://github.com/sourcegraph/sourcegraph/pull/48805 
- [x] (🏁 132 days ago) https://github.com/sourcegraph/sourcegraph/pull/48809 
- [x] (🏁 131 days ago) https://github.com/sourcegraph/sourcegraph/pull/48888 
- [x] (🏁 130 days ago) https://github.com/sourcegraph/sourcegraph/pull/48976 
- [x] (🏁 130 days ago) https://github.com/sourcegraph/sourcegraph/pull/48982 
- [x] (🏁 130 days ago) https://github.com/sourcegraph/sourcegraph/pull/48981 
- [x] (🏁 130 days ago) https://github.com/sourcegraph/sourcegraph/pull/48527 
- [x] (🏁 127 days ago) https://github.com/sourcegraph/sourcegraph/pull/49175 
- [x] (🏁 125 days ago) https://github.com/sourcegraph/sourcegraph/pull/49278 
- [x] (🏁 109 days ago) https://github.com/sourcegraph/sourcegraph/pull/50111 
- [x] (🏁 89 days ago) https://github.com/sourcegraph/sourcegraph/issues/50343 
- [x] (🏁 83 days ago) https://github.com/sourcegraph/sourcegraph/issues/50809 
- [x] (🏁 80 days ago) https://github.com/sourcegraph/sourcegraph/pull/50847 
- [x] (🏁 76 days ago) https://github.com/sourcegraph/sourcegraph/pull/51135 
- [x] (🏁 75 days ago) https://github.com/sourcegraph/sourcegraph/pull/51393 
- [x] (🏁 75 days ago) https://github.com/sourcegraph/sourcegraph/pull/51395 
- [x] (🏁 73 days ago) https://github.com/sourcegraph/sourcegraph/pull/51508 
- [x] (🏁 70 days ago) https://github.com/sourcegraph/sourcegraph/pull/51562 
- [x] (🏁 68 days ago) https://github.com/sourcegraph/sourcegraph/pull/51498 
- [x] (🏁 68 days ago) https://github.com/sourcegraph/sourcegraph/pull/51560 
- [x] (🏁 68 days ago) https://github.com/sourcegraph/sourcegraph/pull/51695 
- [x] (🏁 67 days ago) https://github.com/sourcegraph/sourcegraph/pull/51758 
- [x] (🏁 67 days ago) https://github.com/sourcegraph/sourcegraph/pull/51763 
- [x] (🏁 67 days ago) https://github.com/sourcegraph/sourcegraph/pull/51693 
- [x] (🏁 60 days ago) https://github.com/sourcegraph/sourcegraph/pull/51611 
- [x] (🏁 56 days ago) https://github.com/sourcegraph/sourcegraph/pull/52062 
- [x] (🏁 53 days ago) https://github.com/sourcegraph/sourcegraph/pull/52429 
- [x] (🏁 52 days ago) https://github.com/sourcegraph/sourcegraph/pull/52489 
- [x] (🏁 51 days ago) https://github.com/sourcegraph/sourcegraph/pull/52534 
- [x] (🏁 51 days ago) https://github.com/sourcegraph/sourcegraph/pull/50907 
- [x] (🏁 45 days ago) https://github.com/sourcegraph/sourcegraph/pull/52667 
- [x] (🏁 45 days ago) https://github.com/sourcegraph/sourcegraph/pull/52853 
- [x] (🏁 42 days ago) https://github.com/sourcegraph/sourcegraph/pull/52906
