### ISSUE TITLE
insights: admin UI: Tracking issue

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#46491]
part of strategic ready code insights

/cc @felixfbecker @vovakulikov

### Tracked issues

@unassigned

Completed
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/issues/46490 

@chwarwick

Completed
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/46878 
- [x] (🏁 58 days ago) https://github.com/sourcegraph/sourcegraph/issues/46668 
- [x] (🏁 43 days ago) https://github.com/sourcegraph/sourcegraph/issues/46669 

@leonore

Completed
- [x] (🏁 63 days ago) https://github.com/sourcegraph/sourcegraph/issues/46878 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](<https://en.wikipedia.org/wiki/Spike_(software_development)>)
- 🔒 Security issue
- 🙆 Stretch goal
