### ISSUE TITLE
Teams tracking issue

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#46597]
- [ ] Meet with David V
  - [ ] Write RFC, maybe joint effort
  - [ ] Extend organizations or introduce teams?
  - [ ] SCIM will be great for getting these teams in, for customers that use it
- [ ] Finalize Teams API schema https://github.com/sourcegraph/sourcegraph/pull/45817
- [ ] Design teams database schema
- [ ] Add teams database layer and API implementation
- [ ] Implement CLI interface to manage teams
- [ ] UIs for managing teams
  - [ ] Step 1: Site-admin only
  - [ ] Step 2: Introduce manager role for a team and a role that allows to create new teams
- [ ] Prove data model and ingestion with example scripts
  - [ ] Start with GitHub teams, as we use that ourselves
  - [ ] Next up GitLab teams seems useful
- [ ] Start thinking about writing syncers for team structures
  - [ ] GitHub?
  - [ ] GitLab?
  - [ ] LDAP? Maybe not if using SCIM!
  - [ ] SCIM!
  - [ ] Executor-based hook?

ADO permissions are based on AD - overlap?

**Comment by eseliger** [comment]
Next step:

- Meet with David tomorrow
- Start writing RFC for Teams vs Organizations and how they're going to work
