### ISSUE TITLE
Ingesting CODEOWNERS data into Sourcegraph

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#46600]
What we want:

- [ ] Ingesting ownership data from external systems
  - [ ] The Own service should opaquely consult both data sources
  - [ ] Ingestion works like that: You specify a codeowners flavored document per repository, and can attach it to either all commits or commit beyond a certain point (TBD)
- [ ] Expose ingested CODEOWNERS data as well, similar interface as the CODEOWNERS git file
- [ ] CLI interface to add CODEOWNERS entries to files

Items to work on:
- [x] API schema
   - https://github.com/sourcegraph/sourcegraph/issues/47821
- [x] Database schema
    - https://github.com/sourcegraph/sourcegraph/issues/47820
- [x] Integration into Own service
    - https://github.com/sourcegraph/sourcegraph/issues/47822 
- [x] Ingestion CLI interface
     - https://github.com/sourcegraph/sourcegraph/issues/47823
- [x] UI for ingested ownership information
     - https://github.com/sourcegraph/sourcegraph/issues/47824
     - https://github.com/sourcegraph/sourcegraph/issues/47825

**Comment by eseliger** [comment]
Question: Who can see ingested ownership data? Who can create ownership data?

**Comment by leonore** [comment]
[Excalidraw discovery sketching](https://app.excalidraw.com/s/4Dr1S6qmmY7/4STIidoJODW)

_Overall assumptions_
- _ingesting ownership data will override any committed ownership data_
- _UI for ingestion is site-admin access only (happy to discuss this but it makes UI implementation easier; because it's an easy place for it to live)_

**Database schema**
- add ownership database table which holds codeowners file_contents and repo_id
     - do we want to store in proto format? my thinking was that the gql endpoint would need to validate the codeowners format anyway. would there be a high unmarshalling cost on every read?

**API schema**
- add graphql endpoints for ingesting codeownership data, listing ingested data, and deleting ingested data
- the ingestion endpoint should validate the input is in a valid format

**Integration into own service**
- update the logic for `OwnersFile()` such that we check the database for a manually ingested ownership file, and if it exists, use that

**Ingestion CLI interface**
- update src-cli to connect to the ingestion API schema. 
       - question: do we allow non-site admins to use this then, even if UI is limited?

**UI for ingested ownership information**
- add a site admin management page that allows to upload a codeowners file for a specific repo and also lists existing codeowners file in the database. 
- might need some consultative design
- upload button that takes a text file and reads it into a string
- stretch- could we have an inline code editor for the files?

**Comment by eseliger** [comment]
> do we want to store in proto format? my thinking was that the gql endpoint would need to validate the codeowners format anyway. would there be a high unmarshalling cost on every read?

since we also want to display the original, we might just store both, the proto bytes and the original content? 

> - question: do we allow non-site admins to use this then, even if UI is limited?

I think not for now, wdyt? Just to keep it simple and consistent. 

> add a site admin management page that allows to upload a codeowners file for a specific repo and also lists existing codeowners file in the database.

in the site-admin area, but also under repo settings, I would think is helpful

> upload button that takes a text file and reads it into a string

alternatively textarea also feels worthwhile to me, also maybe for an "editing" function 

One more thing for the UI I think we need to consider:
We want to display on the repo to everyone when there is codeowners data ingested, and probably let everyone read it's contents, too. (read access open to all). Must be easy to tell for the user that the codeowners file in git is not used, and that there is data, and what it looks like. 
Agree some design help would be good here.


-------------

All sounds very sane to me :)

**Comment by leonore** [comment]
> since we also want to display the original, we might just store both, the proto bytes and the original content?

good point, I forgot we don't store the raw string in the protobuf either, it would be costly to reproduce but also having both is good indication that it would have been validated 👍 

> > question: do we allow non-site admins to use this then, even if UI is limited?
> I think not for now, wdyt? Just to keep it simple and consistent.

fully agree with keeping it site-admin only, wanted to gauge if there was opposition to it.

> in the site-admin area, but also under repo settings, I would think is helpful

that makes sense, adding the same upload/edit component for pages here: https://sourcegraph.sourcegraph.com/bitbucket.org/batch-change-buddy/jtest/-/settings? I'll make sure to add an issue for it.

> alternatively textarea also feels worthwhile to me, also maybe for an "editing" function

yep, that's what I meant as "inline code editor". I think it would be nice, just have to think of the page design.

> One more thing for the UI I think we need to consider:
> We want to display on the repo to everyone when there is codeowners data ingested, and probably let everyone read it's contents, too. (read access open to all). Must be easy to tell for the user that the codeowners file in git is not used, and that there is data, and what it looks like.
> Agree some design help would be good here.

yes. I'll add an issue for needing design here and tag rob on it, can also discuss in the sync on tuesday. 

ty! (no reply needed, can just 👍 if nothing to add)

**Comment by leonore** [comment]
@eseliger I think we can close this issue and reopen a new one for future improvements.
