### ISSUE TITLE
Distribution 3.6 Tracking Issue

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#4677]
Private companion issue: https://github.com/sourcegraph/infrastructure/issues/1550

# High-level goals

- Update critical customers to 3.5
- Spin up new customers
- Address customer P1s
- Improve ops and monitoring
  - for site admins
  - for our own technical ops visibility into customer environments
  - for understanding product usage
- Make it easier to test at scale, automate release testing.

# Proposed work

- @slimsag
    - [x] 3.3.8 regression: corsOrigin * no longer allowed #4424
    - [x] ~(assist) symbol search slow at scale~ #3534
    - [x] 💪~Search pagination / incremental search~ #2865 -> some progress was made here but not released in 3.6. See #2865
    - [x] 💪~(low-hanging large count, not what Core is working on) investigate and improve text search performance~ #4482
    - [ ] 💪https://github.com/sourcegraph/sourcegraph/issues/4435
- @ggilmore
    - [ ] It is not clear that externalURL must be configured https://github.com/sourcegraph/sourcegraph/issues/3899
    - [ ] High memory usage in 3.3 https://github.com/sourcegraph/sourcegraph/issues/4643
    - [ ] unable to upgrade buildkite-agent: Composer ... "SHA384 is not supported by your openssl extension https://github.com/sourcegraph/sourcegraph/issues/4500
    - [ ]  "Extensions: unable to publish to sourcegraph.sgdev.org because nginx POST body size is too small" https://github.com/sourcegraph/sourcegraph/issues/3555
- @beyang
    - [ ] Release test automation (https://github.com/sourcegraph/sourcegraph/issues/4238, https://github.com/sourcegraph/sourcegraph/issues/4176)
    - [ ] Update Gitolite docs (https://github.com/sourcegraph/sourcegraph/issues/4250)
    - [ ] GitLab auth issue (https://github.com/sourcegraph/sourcegraph/issues/3917)
    - [ ] Access token issue (https://github.com/sourcegraph/sourcegraph/issues/4209)
    - [ ] Language servers behind same domain (https://github.com/sourcegraph/sourcegraph/issues/4437)
    - [ ] Fix up langserver docs, update with workaround in #4437  (https://github.com/sourcegraph/sourcegraph/issues/3561)

💪 == stretch goal

**Comment by keegancsmith** [comment]
@beyang The 3.6 milestone will be closed very soon. Please create a new tracking issue and close this out.
