### ISSUE TITLE
Fixing rate limiting for permission syncing

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#47011]
**ATTENTION**: this is scratch pad issue that can later maybe be turned into something else, but I'm using it to record loose thoughts right now

## Context

Permission 2XL Scale: https://docs.google.com/document/u/1/d/1TpdAS1sj_5FMZfxOvk9PnDeBD3_J9wpcIO-6MeSPALw/edit#heading=h.n9z0x3rxmzdf
Indra's investigation: https://docs.google.com/document/d/1_QuVbaDo2nTU4qmcqbWaWfdO92fZHjWlHAm04V8kWCY/edit#heading=h.ibml3cw57y40

## Goals

- Clarity - for users and engineers - on which rate limit is used when
- Defaults that fit our usecases: syncing repositories, syncing changestes, syncing permissions, ... When syncing permissions rate limits should be per token.
- Ability to talk to code hosts from any service. Right now we can only talk to code hosts from `repo-updater`.

## Current problems

The biggest problems we have for permission syncing at 2XL and the rate limiter
are these I think:

1. Rate limiter state is not distributed (i.e. we can't talk to code host from `worker`)
2. Rate limiter state is not visible to admins (admins can't see how many requests to a code host have been made, which operations are currently blocked by rate limit, ...)
3. Global, internal rate limit overrides per-token rate limit returned by GitHub (i.e. when doing permission sync), *but* its default value is based on what GitHub allows per token.

Example to illustrate (3):

- GitHub's API allows 5000 req/hr, *per token*
- [Here we use these `5000 req/hr` as a default per code host connection](https://github.com/sourcegraph/sourcegraph/blob/5e931ba35768278285112c9d01c037999963d439/internal/extsvc/types.go#L615-L619) if rate limiting hasn't been disabled or set to another value
- When we [`fetchUserPermsByToken`](https://github.com/sourcegraph/sourcegraph/blob/5e931ba35768278285112c9d01c037999963d439/enterprise/internal/authz/github/github.go#L165)
  - in the case of GitHub we call [`ListAffiliatedRepositories`](https://github.com/sourcegraph/sourcegraph/blob/5e931ba35768278285112c9d01c037999963d439/internal/extsvc/github/v3.go#L568)
  - we wait if we ran out of rate limit: [here](https://github.com/sourcegraph/sourcegraph/blob/5e931ba35768278285112c9d01c037999963d439/internal/extsvc/github/v3.go#L195)
  - if we still have requests left, we record that request, in the internal rate limiter
- **PROBLEM:** We *never* check the actual rate limit returned by the API for this token
  - The `RateLimitMonitor` that records the rate limit status returned by GitHub is only used in the `Source`: https://github.com/sourcegraph/sourcegraph/blob/5e931ba35768278285112c9d01c037999963d439/internal/repos/github.go#L418-L452
  - **It's not used in the code path for permission syncing at all**

OKAY, UPDATE 1 DAY LATER:

* We do use separate rate limiter for authentication providers: https://github.com/sourcegraph/sourcegraph/blob/8f7ebbee2f58338cf7d541eee7c63c986cc8796f/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go#L387-L389
* But that seems to have the same URN as the external service/code host connection rate limiter
* And then we call `WaitN` here: https://github.com/sourcegraph/sourcegraph/blob/8f7ebbee2f58338cf7d541eee7c63c986cc8796f/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go#L859
* But further down, in the client, we call it again: https://github.com/sourcegraph/sourcegraph/blob/8f7ebbee2f58338cf7d541eee7c63c986cc8796f/internal/extsvc/github/v3.go#L195-L196
* -> we consume 2 rate-limiter tokens for every request

## Possible solution?

Do we need an internal, _per token_ rate limit? Customers could say:
- I want `5000req/hr` per token
- I want `20000req/hr` global

But... that's also super dumb, no?

Shouldn't we "simply" say that we treat the global limit as per-token?

But... that would break backwards compatibility, because suddendly customers get `len(tokens)*5000 req/hr`.

So, we probably do need a "global" and "local" limit, except that by default the
global one is off and the per-token one is set to `5000req/hr`

We also need to incorporate the `RateLimitMonitor` into the permission sync code.

We should probably abstract all of the rate limiting away so that the client code is only:

`ratelimiter.wait(1)` under the hood checks api-returned rate limit, then token-based rate limit, then global rate limit.

Token-based rate limiters and global rate limiters need to be updated at same time and both need to allow request.

**We need to fix the fact that we consume twice the tokens we need when doing permision syncing, because we're calling `Wait` in the permission syncer and down in the client**

## Tasks

- [x] #47186
  - [ ] Ensure that every authz-provider client uses a rate limiter under the hood
  - [ ] Then: remove manual `rateLimiter.Wait` calls in `PermsSyncer` and let authz provider handle that 
- [x] Ensure that authz-providers respect external rate limits
  - [x] GitHub #48423
  - [x] GitLab #48616
  - [x] Azure DevOps #49004
  - [x] Bitbucket Cloud #49001
- [ ] Provide a way to configure internal rate limits for permissions syncing
  - [ ] Ensure that permission sync internal rate limits aren't entangled with code host connections
  - [ ] Allow specifying rate limits in auth provider config to use in permissions syncs
- [ ] Provide a way to configure internal rate limits per URL
  - [ ] Permission syncs/repo discovery should adhere to this limit
- [x] #47187
- [ ] ...

## Notes

- Do we even need pagination here? https://github.com/sourcegraph/sourcegraph/blob/5e931ba35768278285112c9d01c037999963d439/internal/repos/types.go#L29-L31
- Is this still a valid assumption? https://github.com/sourcegraph/sourcegraph/blob/5e931ba35768278285112c9d01c037999963d439/internal/repos/types.go#L32-L39
- `backoff` here is unused: https://github.com/sourcegraph/sourcegraph/blob/5e931ba35768278285112c9d01c037999963d439/cmd/gitserver/shared/shared.go#L548
- Why do we not use a `RateLimitSyncer.limiter` in repo-updater (https://github.com/sourcegraph/sourcegraph/blob/5e931ba35768278285112c9d01c037999963d439/cmd/repo-updater/shared/main.go#L133) but use it in `gitserver`?
  - Seems like that's because in `repo-updater` we sync the rate limits whenever an external service is updated/created: https://github.com/sourcegraph/sourcegraph/blob/5e931ba35768278285112c9d01c037999963d439/cmd/repo-updater/shared/main.go#L141-L142
- We already have a debugserver endpoint that returns rate limit info: https://github.com/sourcegraph/sourcegraph/blob/5e931ba35768278285112c9d01c037999963d439/cmd/repo-updater/shared/main.go#L216
- We [also use `ratelimit.InstrumentedLimiter` to throttle git operations from `gitserver`](https://github.com/sourcegraph/sourcegraph/blob/8f7ebbee2f58338cf7d541eee7c63c986cc8796f/cmd/gitserver/server/server.go#L458-L475)
- There's also [`mutablelimiter.Limiter`](https://github.com/sourcegraph/sourcegraph/blob/8f7ebbee2f58338cf7d541eee7c63c986cc8796f/cmd/gitserver/server/server.go#L334-L338)
- We also have a [`defaultRateLimit`](https://github.com/sourcegraph/sourcegraph/blob/8f7ebbee2f58338cf7d541eee7c63c986cc8796f/schema/site.schema.json#L36-L40) in the site-config
  - Added in [#33551](https://github.com/sourcegraph/sourcegraph/issues/33551)
- [`(*ratelimit.Registry).getOrSet(string, *InstrumentedLimiter)`](https://github.com/sourcegraph/sourcegraph/blob/8f7ebbee2f58338cf7d541eee7c63c986cc8796f/internal/ratelimit/rate_limit.go#L49-L54) is _never_ called with a 2nd parameter that's not `nil`.

---

- Here's where we define the default rate limits per code host: https://github.com/sourcegraph/sourcegraph/blob/5e931ba35768278285112c9d01c037999963d439/internal/extsvc/types.go#L599-L600

/cc @sourcegraph/source/iam

**Comment by mrnugget** [comment]
Let's close th is because we fixed a lot of things here, but we still need the distributed rate limiter.
