### ISSUE TITLE
Teams: GraphQL resolvers

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#47043]
```[tasklist]
### Remaining tasks
- [x] Test for `members(search)` and implement relevant fakes #47440
- [ ] Make `members()` query user fetching more efficient - currently it is a for loop. https://github.com/sourcegraph/sourcegraph/issues/49425
- [x] Extract `fakeTeamsDb` and `fakeUsersDB` to a testing package #47521
- [ ] Consider incorporating `ConnectionResolver` to remove some connection code.
- [ ] Or at least merge `compute` and `applyArgs` across connections.
- [ ] Split tests? (the file is over a 1000 lines already)
- [x] Team member modifiers - add #47512, set, delete
- [ ] Unify the use of `fakeUsersDB` with `fakeUser` method in that package. Perhaps after extracting `fakeUsersDB`
- [x] Set/Remove members ops
- [x] Add support for counting deeply nested teams and team members
```

**Comment by cbart** [comment]
I've filed tasks in the backlog for the remaining line items that made sense.
