### ISSUE TITLE
(Amplitude) metrics for Own

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#47062]
### TODO event logging

- [x] `searchResults:ownershipMailto:clicked` https://github.com/sourcegraph/sourcegraph/pull/48932
    - also included `searchResults:ownershipUsers:clicked`
    - and `searchResults:ownershipTeams:clicked` 
- [x] Ingested CODEOWNERS files events https://github.com/sourcegraph/sourcegraph/pull/48938
  - `own:owner:added`
  - `own:owner:removed`
  - `own:owner:updated`
- [x] **new** `filePage:ownershipPanel:viewOwnerDetail:clicked` https://github.com/sourcegraph/sourcegraph/pull/48928
- [x] `searchResults:ownershipCsv:exported` https://github.com/sourcegraph/sourcegraph/pull/48868
- [x] `repoPage:ownerTab:viewed` https://github.com/sourcegraph/sourcegraph/pull/48870
- [x] `repoPage:ownerTab:clicked`https://github.com/sourcegraph/sourcegraph/pull/48871
- [x] `search:selectOwner:searched` https://github.com/sourcegraph/sourcegraph/pull/48740 using `SelectFileOwnersSearch`
- [x] `search:hasOwner:searched` https://github.com/sourcegraph/sourcegraph/pull/48740 using `FileHasOwnersSearch`
- [x] `filePage:openOwnershipPannel:clicked` https://github.com/sourcegraph/sourcegraph/pull/48651 - using `OwnershipPanelOpened`, unless we want to distinguish click and panel opening?

Not available:

- `ownershipPannel:addOwner:clicked` - add owner is not implemented for starship
- `searchResultPage:emailAllOwner:clicked` - we do not have an email-all for starship
- `repoPage:viewMoreOwner:clicked` - we don't have that on repo page, but for file page we have `filePage:openOwnershipPannel:clicked`
- `repoPageOwnerTab:viewOwnerDetail:clicked` - we do not have this on repo page, but let's do `filePage:ownershipPanel:viewOwnerDetail:clicked`
- `repoPageOwnerTab:addOwner:clicked` - we do not have this yet
- Owner changes are not supported, instead we added `own:ingestedCodeownersFile:*`
  - `own:owner:added`
  - `own:owner:removed`
  - `own:owner:updated`

### Description

We want to track Own usage in Amplitude (through `eventLogs`) and in looker through pinsg.

The main questions we want to answer are:
- did this customer setup Own?
- what repository coverage do they have?
- how and how frequently are users using ownership data

#### (ping) Did this customer set up own

TODO
- define a ping that is true if the customer has turned on the feature flag
- define a ping that is true if the customer has ingested (any) ownership data

#### (ping) What repository does this customer have

- Own coverage: `# repos with ownership` / `total number of repos`

#### (ping) D/W/MAUS

In pings, define a Own DAU, WAU, MAU the following way:

D/W/MAU(Own) is a user that has performed at least one of those actions in a Day/Week/Month:
- performed a `select:file.owners` search
- performed a `repo:has.owner` or any other `has.owner` search
- opened the ownership panel

#### (amplitude) how and how frequently are users using ownership data

- file page
	- `filePage:openOwnershipPannel:clicked`
	- `ownershipPannel:addOwner:clicked`

- repo page
	- `repoPage:viewMoreOwner:clicked`
	- `repoPage:ownerTab:viewed`
	- `repoPage:ownerTab:clicked`

- repo page / owner tab
	- `repoPageOwnerTab:addOwner:clicked`
	- `repoPageOwnerTab:viewOwnerDetail:clicked`

- search
	- `search:selectOwner:searched`
	- `search:hasOwner:searched`
	- `searchResultPage:emailAllOwner:clicked`

- common
	- `own:owner:added`
	- `own:owner:removed`
	- `own:owner:updated`

#### Key use case candidate

- `searchResults:ownershipCsv:exported` when a CSV list of emails is exported
- `searchResults:ownershipMailto:clicked` when someone uses `select:owner` search and uses the mailto function

**Comment by malomarrec** [comment]
Next step: @ebrodymoore to approve the pings

**Comment by andersonlauren** [comment]
For pings: can we put DAU, WAU, and MAU into critical telemetry

**Comment by malomarrec** [comment]
@andersonlauren I don't understand your question, can you explain? (Maybe it was not for me, in which case, ignore)

**Comment by andersonlauren** [comment]
sorry @malomarrec that was for @nathan-downs as were discussing this ticket.

**Comment by nathan-downs** [comment]
@malomarrec how do we plan on identifying repo names? To my knowledge, we've redacted these in the past to protect user privacy.

**Comment by malomarrec** [comment]
@nathan-downs we won't!
On the instance: we count # repos with coverage cs those without. We only exfiltrate the number, nothing identifiable about the repo.
Does that answer the question, or did I misunderstand?

**Comment by nathan-downs** [comment]
@malomarrec sounds good, approved!

**Comment by eseliger** [comment]
docs for adding pings: https://docs.sourcegraph.com/dev/background-information/adding_ping_data

**Comment by cbart** [comment]
@nathan-downs at this point I think we have (almost?) all the elements mentioned in points 1-4 of [pings adding docs](https://docs.sourcegraph.com/dev/background-information/adding_ping_data):

- schema in sourcegraph/analytics#810
- event log query in #48493
- export of own pings in #48300

We're missing changes where events are actually logged, but if I understand correctly, we can do these independently.

Are we good to review these?

**Comment by cbart** [comment]
(also sorry for tagging you directly, I'm not yet fully aware of the process, please correct me if there's another way to push this forward)

**Comment by malomarrec** [comment]
@nathan-downs can you ping me here when those are available in Amplitude? I'd like to look at the dogfood results

**Comment by eseliger** [comment]
this was in done but not closed, can we close it @cbart or is there something left?
