### ISSUE TITLE
Implement user permissions sync for Azure code host

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#47165]
**Blocked by**

- [ ] #47163.

**Tasks**

- [x] ~~Use the list organization API to list all organizations~~
- [x] Use the list repositories API to list all repos under an organizations #48209 
- [x] Populate permissions in the user permissions table #48209 
- [x] Implement ValidationCheck #48465 

/cc @ryphil
