### ISSUE TITLE
Add support for Azure as an auth provider

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#47163]
**This is a pre-requisite for permissions syncing on ADO.**

- [x] New users should be able to sign up on Sourcegraph with Azure https://github.com/sourcegraph/sourcegraph/pull/47763
- [x] Existing users should be able to connect their Azure account to Sourcegraph https://github.com/sourcegraph/sourcegraph/pull/47763/

**Functionality tasks**

- [ ] Handle username conflict if present by adding a suffix `-1`, `-2` and so on until a non-conflicting username is found (Tracked in https://github.com/sourcegraph/sourcegraph/issues/47894)
- [x] ~~Handle value for default URL~~ This is not needed as we do not expose URL as a config
- [ ] Implement a behaviour similar to `allowOrgs` or `allowGroups` - Standalone issue created: https://github.com/sourcegraph/sourcegraph/issues/48555
- [x] Show Azure connection in account security page #48184 
- [x] Show pretty icon in sign in page https://github.com/sourcegraph/sourcegraph/pull/47865
- [ ] If `allowSignup` is false, disable new signups to sourcegraph - Standalone issue created: https://github.com/sourcegraph/sourcegraph/issues/48557
- [x] Check email verification behaviour (`email != ""` in code)
  - I've checked with the security team on Slack and they are okay with this assumption. Also we have the same behavior in Gitlab auth provider when we invoke `GetAndSaveUser` and similarly for GitHub we always mark email as verified.

**Good to haves**
- [ ] Tweak custom query params injection in OAuthContext (https://github.com/sourcegraph/sourcegraph/pull/48209#discussion_r1121613113)

/cc @ryphil

**Comment by indradhanush** [comment]
All the functionality tasks have been completed or have a standalone issue. This issue is now completed.
