### ISSUE TITLE
Display instance upgrade readiness in Site admin > Updates

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#47259]
- https://storybook.sgdev.org/?path=/story/web-site-admin-webhooks-webhooklognode--collapsed
- https://storybook.sgdev.org/?path=/story/web-batches-batch-spec-execute-workspacedetails--visible-workspace-queued
- https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/code-graph/indexes/UHJlY2lzZUluZGV4OiJJOjEzOTkyOCI=
	<img width="913" alt="CleanShot 2023-02-06 at 17 54 21@2x" src="https://user-images.githubusercontent.com/2946214/216940933-6b74ad5e-c49b-49a4-bea5-346ceb7b3de5.png">

## TODO

- [x] Query the GraphQL endpoint implemented in https://github.com/sourcegraph/sourcegraph/issues/47258 to get schema drift and OOB migration information.
- [x] If there is any schema drift detected, display the context, and inform the site admin to contact support.
- [x] If there is no schema drift and no unfinished-and-deprecated OOB migration detected, provide links to the upgrade documentation depending on the deployment model (if possible).
- [x] Update docs in https://docs.sourcegraph.com/admin/updates#multi-version-upgrades

## Expected outcome

When the site admin looks at the **Site admin > Updates** page, it should be clear what the next steps are when seeking an instance upgrade.
