### ISSUE TITLE
Site admin quality of life improvements tracking issue

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#47545]
### Plan

Improvements and fixes we can make with low to medium investment that will have a highly positive impact on the Sourcegraph Site Admin experience.

### Tracked issues

- [x] https://github.com/sourcegraph/sourcegraph/issues/47546
- [ ] https://github.com/sourcegraph/sourcegraph/issues/40377
- [ ] https://github.com/sourcegraph/sourcegraph/issues/47548
- [ ] https://github.com/sourcegraph/sourcegraph/pull/47589
- [ ] https://github.com/sourcegraph/sourcegraph/pull/47766

/cc @ryphil

**Comment by mrnugget** [comment]
(Leaving my name here so I get pinged on stuff)
