### ISSUE TITLE
Sentinel Step 0 - Tracking issue

### ISSUE THREAD

**Issue by willdollman** [sourcegraph/sourcegraph#47830]
### Plan

We want to complete Step 0 in the [PRFAQ roadmap](https://docs.google.com/document/d/10Hs6SfUsJ_WN3ZNOJxT3oFu3LXGGRm0QuhQeexv7Ggk/edit#heading=h.euzt9t4zg1fr), which involves:

- In-product landing page, linking to the .com demo ([link](https://www.figma.com/file/IRtUDCo39aXXXwuxxHBUFk/Sentinel-landing-page?node-id=1%3A186&t=0szu83GoAr8TvAHe-0))
- Prototype on .com
  - Scan direct and transitive dependencies
  - Filter for reachability at the dependency level (Snyk and semgrep do this function-call level, Snyk by building a callgraph and semgrep using comby)
  - CVEs come from GitHub
  - Java only
  - On Sourcegraph.com only
- Capturing interest
  - Schedule a call
  - One click thingy for capturing lang interest
  - Link to github discussion

### Tracked issues

```[tasklist]
### Landing Page
- [ ] Create Sentinel landing page on customer instances
```

```[tasklist]
### Marketing
- [ ] Create Sentinel marketing page
- [ ] Create call to action to gather customer feedback
```

```[tasklist]
### sourcegraph.com demo
- [ ] Define vulnerability data format
- [ ] Background job for fetching and storing vulnerability data
- [ ] Background job for matching dependency data with vulnerability data
- [ ] Update frontend prototype
```
