### ISSUE TITLE
Tracking Issue: Perms Center March Startship 

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#47867]
The tracking issue for the remaining work, which shall be completed by 13th March for the Starship release. 

### P0
- [ ] [BE [Syncs]: Expose & replace old perms sync API](https://github.com/sourcegraph/sourcegraph/issues/47731)
- [ ] FE [Syncs]: Basic perms sync table UI and integrate with the paginated API.
- [ ] BE [Info]: Build API for users & repos permissions info supporting both old & new data models
- [ ] FE [Info]: UI for perms info tables 

### P1
- [ ] FE [Info]: Add manually trigger sync button on perms info page
- [ ] [BE [Syncs]: Add filters for reasonGroup and state in perms sync api](https://github.com/sourcegraph/sourcegraph/issues/47302)
- [ ] [BE [Syncs]: Add text search for repo/user perms sync api](https://github.com/sourcegraph/sourcegraph/issues/47303)
- [ ] FE [Syncs]: UI for perms syncs filters and integrate with API & URL params.
- [ ] BE [Syncs]: API for perms sync stats including queued items, last failining for users & repos, users/repos with outdated perms
- [ ] FE [Syncs]: Show live perms sync stats

### P2
- [ ] FE BE [Info]: Add search filters for perms info
- [ ] FE [Syncs]: Add re-trigger sync action button for sync job item
- [ ] FE BE [Syncs]: Add cancel queued job(s) action buttons

### P3
- [ ] BE [Syncs]: Record execution logs
- [ ] FE [Syncs]: Show perms info modal with timestamps, provider stats and execution logs
- [ ] BE [Syncs]: Cleanup old perms syncer, syncjobs & feature flag
