### ISSUE TITLE
Own Starship go-to-market tracking issue

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#48051]
Tracking for the go-to-market side of the Starship release.

- [x] Update PMM brief "what we're launching in Startship" @malomarrec 
- [x] - [ ] Vision blog post @malomarrec 
  - [x] Write blog post @malomarrec 
  - [x] Review and feedback @sourcegraph/own @iskyOS 
- [x] Marketing landing page @iskyOS 
  - [x] Initial design and content @iskyOS 
  - [x] copy review @malomarrec 
  - [x] 1 min demo video from @eseliger
- [x] Sales team enablement @malomarrec 
  - [x] training session is scheduled on March 15 and 16th, @iskyOS and @jamielndsy are organising
  - [x] handbook page or deck @malomarrec 
- [x] Release blog post 

Own is gonna be feature-flagged off by default at Starship and tagged as experimental. It will be free during the experimental and (closed) Beta phase, but may be paying afterwards.

**Comment by malomarrec** [comment]
This is now complete, and the release post draft is here https://docs.google.com/document/d/15k2IdBPJUyYVThedF_0Urv8LTmiAhfx1dFdtaj41nOg/edit
