### ISSUE TITLE
Code modification 3.7 Tracking Issue

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#4864]
**Goals**
- MVP search-and-replace functionality (CI and deployment to test clusters)

**Work items**
- [x] Add replacer to CI pipeline; add `Dockerfiles` #3928
- [x] Add external tool integration and test to Replacer service that performs a simple replace operation (e.g., string substitution) #3928
- [x] Update YAML files for `sgdev` deployments [#294](https://github.com/sourcegraph/deploy-sourcegraph/pull/294/files)

Improvements:
- [ ] Use `language` query argument to force structural matcher
- [ ] Test structure (see [comment](https://github.com/sourcegraph/sourcegraph/pull/3928#discussion_r300800211))
- [ ] Share zip cache with searcher
- [ ] Use/explore zoekt indexing for replacer
- [ ] Test richer search-and-replace request operations

Proposal Document: https://docs.google.com/document/d/14A0bfQ9Nef2JBmovlCrIRalTEc_U14K2roQjHKnOvzo

[**Figma mocks**](https://www.figma.com/file/hAZG4YTH7OmJKob8cxoOcNlh/Large-scale-code-modification?node-id=0%3A1)
