### ISSUE TITLE
Core Services: 3.7 Tracking Issue

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#4924]
## Goal

99th percentile latency of indexed search at 42req/s with 20k repos is under 2s.

## Availability

Team:
- Hackweek(s) **July 22nd - Aug 2nd** ([see details here](https://docs.google.com/document/d/1Ljs7C3uB7Di6tfyUsKOHMuFHflrGQFC6quQR_SoOQ34/edit#heading=h.yahdutol4v38))
- @tsenart & @mrnugget in San Diego for GopherCon from **July 22th-27th**
- @tsenart, @mrnugget & @keegancsmith in Berlin for Core Meetup **August 5th-10th**

Invidividuals:

- @mrnugget: Not working **August 12th-16th**
- @tsenart Available
- @keegancsmith Available

## Background

A requirement for future work on Zoekt performance is to define a performance model of Zoekt's current architecture that allows us to predict Zoekt's performance to a certain extent.

After doing back-of-the-napkin math, we came up with the following formula:

"With N cores and M shards it can take up to X to search a single shard when aiming to do 42req/s (T)"

![IMG_4654](https://user-images.githubusercontent.com/1185253/61435859-cb446d00-a939-11e9-9997-7087955b54fa.jpeg)

With variables plugged in, that gives us:
- "With 384 cores and 30000 shards and 42 req/s it can take a maximum of 300us to search a single shard"
- "With 1 core and 30000 shards and 42 req/s it can take a maximum of 0.79us to search a single shard"

## Planned work

- [ ] Global repository permissions caching (#4812)
- [ ] Determine resource allocation "equation" and update docs for admins to provision them accordingly for their Sourcegraph installation (e.g. https://confluence.atlassian.com/bitbucketserver/scaling-bitbucket-server-776640073.html)
- [ ] Experiment with more efficient posting lists in Zoekt https://github.com/sourcegraph/zoekt/pull/10
- [ ] Scale Zoekt horizontally
    - [ ] Write proposal, derive implementation plan from it.

### Moar Ideas 
- [ ] Reduce contention in Zoekt
- [ ] Improve `indexData.simplify` in Zoekt
- [ ] Improve parsing of newlines in Zoekt
- [ ] Shard compaction
- [ ] Shard compression (are we I/O bound?)

**Comment by tsenart** [comment]
Added `Shard compression (are we I/O bound?)` to the list of ideas.

**Comment by tsenart** [comment]
@christinaforney, @nicksnyder: How about we have our planning meeting to go over this proposed work plan while we're in San Diego? We don't have a lot of time available in this iteration (Gophercon + Hackweek + Vacations + Core Services offsite), so have that in mind when glancing over this issue.
