### ISSUE TITLE
Search: 3.7 Tracking Issue

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#4947]
## Planned work
- [ ] Scalable symbol search #3534 @kzh  
- [x] Multiline non-indexed search #4518 @attfarhan
- [x] Codemod progress #4864 @rvantonder

## Stretch goals
- [ ] Beginner-friendly search @ijt, @attfarhan
