### ISSUE TITLE
CSV Search Result Export Meta Issue

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#49645]
- [ ] We do not allow cancellation on CSV export
- [ ] Ranges are not in a standard format (`[line [start end]]`), and need to be manually parsed
- [ ] Full file is aggregated in memory, not streamed
- [ ] Should consider moving to backend so this can be consumed and tested programatically
- [x] A search is rerun to get data for export even if the current results are under the display limit of 1500 (fixed in #50316)
- [x] There is no loading indication (fixed in #50316)
- [x] Failures are not shown to the user (fixed in #50316)
- [x] We only export results of the first type we see (#50316 will warn users)
- [x] Results are not in the same order as in the UI when the search needs to be re-run (#50316 will warn users)
- [x] The maximum number of exported results is 100,000 (#50316 will warn users)

/cc @sourcegraph/search-product

**Comment by gl-srgr** [comment]
Enhancement request related to export: https://github.com/sourcegraph/sourcegraph/issues/54201

**Comment by camdencheek** [comment]
Closing since the search jobs solve this problem better
