### ISSUE TITLE
Cody tracking issue 2023-04-03–2023-04-17

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#50343]
## Plan
Early user feedback has indicated the following are important:

* improved context quality (context quality almost always dictates the accuracy of the Cody response).
* some also prefer a less chat-y, more code-search-y interface
* would like an easy way to insert a generated snippet of code into the right place
* fast autocomplete, triggers automatically
* VS Code is shipping new native plugin endpoints for an upcoming version of GitHub Copilot. We are investigating whether they are willing to open these up.

We also think it would help drive awareness if Cody lived in a separate repository that was completely open source.

```[tasklist]
### Features
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50448
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50281
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50344
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50507
```
```[tasklist]
### Bugs and other stuff
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50446
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50462
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50445
```

```[tasklist]
## Next cycle wishlist
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50459
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50273
- [ ] Abuse detection + blocking mechanism
- [ ] Factor out stuff in Go binary
- [ ] Toggle LLM backend endpoint, need to support both OpenAI and Anthropic, $CUSTOMER wants it
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50713
- [ ] Self-hosted embeddings
```

**Comment by jdorfman** [comment]
@beyang done and more coming daily

**Comment by malomarrec** [comment]
@beyang who's working on the VS Code extension issue? Looks unassigned?
I'd like to bump https://github.com/sourcegraph/sourcegraph/issues/50180

**Comment by beyang** [comment]
@malomarrec no one AFAIK, want to bring it up on Monday's sync?

**Comment by malomarrec** [comment]
@sourcegraph/cody shall we have a recorded Cody demo at the end of this sprint, to share progress with others?

**Comment by malomarrec** [comment]
@sourcegraph/cody shall we close this?
