### ISSUE TITLE
Cody Magical Web Search Experiment Launch

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#50512]
Engineering tasks tracker for: https://github.com/sourcegraph/sourcegraph/issues/50215

The scope of this issue is to get the Cody Magical Web Search prototype ready to launch on dot com for experimentation purposes. 

The Magical Web Search powered by Cody aims at generating search queries in Sourcegraph-specific syntax from natural language queries by the user.

**TODOs**
- [x] Add Powered by Cody text below the search input box.
- [x] Add Experimental tag.
- [ ] Implement rate limiting per user.
- [ ] Move cody prompt template to backend.
- [x] Record user input, transformed query and feedback in the database.
- [x] Show feedback component on the search results page.
- [ ] Make Cody Search stateful & sync with local storage?
- [ ] UX finalisation & implementation.
- [x] Improve prompt quality v1.
- [ ] Prepare a list of prompts for testing.
- [ ] Improve prompt quality v2 based on the new list.
- [ ] Launch experiment on dotcom.
