### ISSUE TITLE
[done] Ownership inference

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#50571]
Spike https://github.com/sourcegraph/sourcegraph/issues/50801

**File level**

At this point the goal is to use online fetching of signals on the file level.

- [x] Display recent contributor signals https://github.com/sourcegraph/sourcegraph/issues/50565
  - We compute recent contributions for file with a gitserver call - something we can demo quickly
- [x] Display recent viewer signals https://github.com/sourcegraph/sourcegraph/issues/50564
- [x] Enabling/disabling ownership signals in the UI

**Aggregation**

Aggregation can piggyback of the existing code intel indexing and also reuse the Admin UI.

- [x] Stub graphQL API for displaying ownership https://github.com/sourcegraph/sourcegraph/issues/50800
- [x] Repo and directory page UI for displaying ownership [figma](https://groups.google.com/a/sourcegraph.com/g/own-team)
- [x] Implement a recent contributor aggregate signal
  - [x] Database and stores https://github.com/sourcegraph/sourcegraph/issues/50946
  - [x] #51382
  - [x] **TBD** Knobs and monitoring
- [x] Implement a viewer indexer **NEEDS EXPANDING**

Notes:

- For the recent viewer signal, it is enough that we [keep the last timestamp](https://github.com/sourcegraph/sourcegraph/issues/50571#issuecomment-1507528266) a repo was reindexed for viewership.

Notes:

- all ownership signalling work should be hidden behind `own-signals` feature flag

**Comment by coury-clark** [comment]
@cbart fyi - the figma link in OP goes to the wrong place
