### ISSUE TITLE
Ownership Search tracking issue

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#50653]
- [x] https://github.com/sourcegraph/sourcegraph/issues/46585
- [x] https://github.com/sourcegraph/sourcegraph/issues/46586
- [ ] Investigate performance of this search type
- [ ] Should we allow `file:has.owner(@me)` to reference "owned by myself"?
- [ ] Auto completion for owner by available Sourcegraph users
  - [ ] This username should then be resolved in the backend so that also email rules and external_accounts handle rules match

Question: How do we go about additional types/levels of ownership in search?
What this can initially answer:
- What code is strictly unowned
- What code is strictly owned by my team/myself
- Only search code owned by myself

Not so much about "weak" ownership. What code do I _effectively_ own?
Should we extend the syntax later? `file:has.owner(@eseliger type:expertise)`, `file:has.owner(@eseliger type:committer)`, `file:has.owner(@eseliger type:XXX)`?  What would the allowed types be?
