### ISSUE TITLE
LLM proxy tracking issue

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#50726]
## Goal

To get better control over API keys, we want to host a public LLM proxy. At a very high level, this proxy ought to simplify the key management of upstream LLM providers, provide proper rate limiting so we don't get gigantic bills, and should help collecting usage numbers. This service will make sure customers are governed by the terms negotiated by Sourcegraph that allow zero retention.

## Design ideas

- LLM proxy will be a global one-off service, likely decoupled from the sourcegraph.com deployment, living at some subdomain like completions.sourcegraph.com or so.
- The service will be one of the supported backends for completions, and is the default one used when nothing else is set.
- Using completions should be opt-in, so some setting to enable it should still be required (for now). This includes reading Cody terms, probably. 
- The LLM proxy should be a _public_ service. This puts us at certain risk, so we need to handle rate limiting well, need to stay on top of our spending, and need to have a kill switch. 
- The LLM proxy can live in the Sourcegraph monorepo, to benefit from all the tools we have already built, including CI pipelines, sg and so on, but will not ship to customer deployments as it's a one-shot service.
- Since this service is potentially long-lived and global, proper versioning is important. 
- We want this proxy to be able to handle outages of LLMs.
- If upstream LLMs won't be able to support our scale (reqs/s) on single accounts, we need to keep a path forward open for managing multiple keys per LLM, to balance the load across accounts.

```[tasklist]
### Tasks
- [ ] Create scaffolding for a new enterprise service (the llm-proxy)
- [ ] Create deployment resources for the service, under some domain (can be a testing domain for now). Rafal suggests this is a separate GCP project that we can lock down more. Deployment specifics TBD, if the service remains stateless, it might be feasible to give Cloud Run a try, otherwise we will use GKE likely. The important parts to this deployment are that it supports bursts and high connection counts. We might want to allow CORS requests.
- [ ] Implement a RESTful API interface for a completions endpoint. It should be versioned. Upstream API keys are part of the proxy configuration, not the request. The request could contain a plain copy of what we'll send to Anthropic, or slightly different if it would be easier to support multiple backends by that. Client code for this already exists: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/tree/enterprise/cmd/frontend/internal/completions/streaming
- [ ] Implement a new client so that Sourcegraph can speak to the new proxy. This should be backported. 
- [ ] Implement authentication. Auth should be optional (we allow anonymous, public users to use it, too, like App users or Cody standalone uses). Authentication would be used by paid instances to get much higher rate limits. For authentication, it would be great if we wouldn't have to manage another set of API keys for this, so perhaps some authentication mechanism that uses the license key could be useful? Otherwise, we will implement API key management for customer instances as well. Access to the database of license keys to see what tags they have would be massively useful, though.
- [ ] Implement rate limiting. Rate limiting should apply to both anonymous users and authenticated users, with different limits. Ideally, we can eventually support overwrites per IP/user. Rate limiting for unauthenticated users should be IP based initially. Rate limiting should track the requests and ideally also the number of tokens used.
- [ ] Site config allows to configure the new Sourcegraph backend. 
- [ ] Add observability and alerting to the system. This is critical as we need to ensure a certain SLA eventually and want to be informed about cost and usage. 
- [ ] Implement usage tracking. We want to know which user/instance uses the proxy how much. Ideally, these events can be visualized somewhere. The dotcom license tracker UI would be a great place to expose this data.
```

**Comment by bobheadxi** [comment]
Note about my pricing estimates - I'm pretty sure I'm guesstimating horribly wrong here, it's rather complicated and I'm not actually sure the calculator handles the concurrent requests right (it seems more expensive than it should be). Updated my comment with some other findings

> How about we do a ~1d spike to see how easy it is to get up and running there?

Yep!

> Also, can we do something to be able to still run llm proxy locally for dev or would that not work anymore when we start tailoring the binary for use in cloud run? (Warning: I know next to nothing about it :))

I'm pretty sure it will just run our Docker images OOTB! It's not one of those serverless platforms that require you to write in their thingamajig from what I can tell. Will spike it out though, but if we can just throw it a container (which we do already in https://github.com/sourcegraph/controller - we use Cloud Run _Jobs_, which presumably runs on the same thing) this will keep local dev happy

> How can we get observability to work there, given we won't be able to just scrape the cloud run machine every 30s like other prom targets I'm assuming?

We get GCP Monitoring OOTB, and we can query it with PromQL (almost - Monarch has some limitations in the query language, `{__name__}` queries), and even throw a Grafana in front (what we do in https://monitoring.sgdev.org)

> Once we start doing auth and rate limiting, we will need some sort of state management, how would that work best in cloud run? A managed redis instance for sharing context? Some other best practices there?

I believe managed redis will be the way to go here (we probably would have gone with redis anyway in a K8s solution I think), google has an offering for this that seems to speak redis ([Memorystore](https://cloud.google.com/memorystore))

**Comment by eseliger** [comment]
sounds all great, excited to see if this can work for us :)

**Comment by krrishdholakia** [comment]
Hey @eseliger @bobheadxi 

We faced similar issues and ended up using a key-manager for this. Curious why that's insufficient in this context? 

Context: working on a way to simplify LLM API calls - https://github.com/BerriAI/litellm, and would love to be helpful if possible

**Comment by unknwon** [comment]
> Hey @eseliger @bobheadxi
> 
> We faced similar issues and ended up using a key-manager for this. Curious why that's insufficient in this context?
> 
> Context: working on a way to simplify LLM API calls - https://github.com/BerriAI/litellm, and would love to be helpful if possible

Hey @krrishdholakia - For the LLM proxy (now Cody Gateway), the primary focus is the API key (from upstream LLM providers) and token (from Sourcegraph itself) management, thus it is actually not about providing a unified interface/adapter for different LLM providers.
