### ISSUE TITLE
Cody tracking issue 2023-04-17–2023-05-01

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#50809]
## Plan

```[tasklist]
### Features
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50344
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50273
     - [ ] Toggle LLM backend endpoint, need to support both OpenAI and Anthropic, $CUSTOMER wants it
- [ ] Abuse detection + blocking mechanism @eseliger 
- [ ] #50726 @eseliger 
- [ ] CLI spike + factor out stuff + LSP wrapper? @mrnugget 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50180
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50559
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50448
- [ ] https://github.com/sourcegraph/pr-faqs/issues/152
- [ ] cody web app: https://github.com/sourcegraph/sourcegraph/issues/50784 - @philipp-spiess & @thenamankumar 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50399 @dominiccooney 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50876
```

```[tasklist]
### Bugs and other stuff
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50771
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50955
```

```[tasklist]
## Next cycle wishlist
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50459
```

**Comment by malomarrec** [comment]
Heads up @philipp-spiess @beyang @mrnugget I replaced the autocomplete item by a link to this PR-FAQ tracker https://github.com/sourcegraph/pr-faqs/issues/152.
Please use it to post updates.
I'd like to come together and come up with a strawman roadmap for autocomplete, with the ultimate goal being [idiomatic autocomplete](https://docs.google.com/document/d/12eO60kiaGwhjZr1Z3Ny-4GBfHXZJUWHhgu9op0QDOUY/edit#) a.k.a. autocomplete that knows about all your private codebase.
@philipp-spiess @beyang if you want to jot down a bunch of tentative steps in the PR-FAQ doc, in the roadmap session, we can go from there. I don't want to set yet another meeting before some async prep work :)
