### ISSUE TITLE
WIP: Gerrit Batch Changes Tracking issue

### ISSUE THREAD

**Issue by varsanojidan** [sourcegraph/sourcegraph#50820]
Milestone 1: Batch Changes
- [x] https://github.com/sourcegraph/sourcegraph/issues/46731
- [x] https://github.com/sourcegraph/sourcegraph/issues/46732
- [x] https://github.com/sourcegraph/sourcegraph/issues/46733
- [x]  https://github.com/sourcegraph/sourcegraph/issues/46735
