### ISSUE TITLE
The Big Cody Tracking Issue

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#50934]
Legend:
- 🧱  working on deliverable
- 🔍  research
- ⛏️  hacking on it
- 🆕  not started
- 📖  scoping
- 💄  refinement
- 🧪 experiment (something there, but needs work)
- 🪧 currently no one working on it
- 📦 shipped

---

#### Context fetching

@jtibshirani @stefanhengl @camdencheek 

- [ ] 🔍 Multi-repo context fetching
- [ ] 🧱 Scalable embeddings (work with big monorepos)
- [ ] 🧪 Intent Detection for better context fetching
- [ ] 🆕 Ranking when context fetching
- [ ] 🔍 [Supply code intelligence context to Cody](https://docs.google.com/document/d/1b4nLWa8pc74xC3MmtZjVQhE1nXe_xWyWmwF-aoumeVw/edit)

#### Dependency on 3rd parties

- [ ] 🆕 Self-hostable embeddings (no data sent to 3rd party provider)
- [ ] 🆕 Sourcegraph hosted embeddings GA
- [ ] 🪧 Bring your own LLM

#### Guardrails

@keegancsmith

- [ ] 🧱 Enterprise adoption: Filters/policies/attribution

#### Misc

- [ ] 🧪 Hallucination detection 

### Infrastructure

@eseliger @bobheadxi @unknwon 

- [x] 📦 Infrastructure: Rate limiting
- [ ] 🧱 Infrastructure: LLM Proxy
- [ ] 🆕 Infrastructure: Embeddings API

### VS Code

@abeatrix @philipp-spiess @danielmarquespt 

- [ ] 💄 VS Code: General frontend work
- [ ]  🔍 VS Code: "non-stop cody" (batch multiple changes, ...)
  - @dominiccooney 
- [ ] 🆕 VS Code: Voice Chat
- [ ] 🧪 Autocomplete
  -  @beyang @philipp-spiess

### Cody in Web

@thenamankumar @almeidapaulooliveira

- [ ] ⛏️ [Cody in the Web UI](https://docs.google.com/document/d/11FLUc-B19mZJVR3tb5GsINPVd8V_Pd3KXhd0IrvJ7O8/edit#heading=h.ifs8884gwpyg)
- [ ] 🧱 [Magical search](https://docs.google.com/document/d/10RZCwcKz-I0NbdEW9finkvpo2vDGSqZRaOVPMtDmseg/edit#) 

### Other Clients

- [ ] 🆕 Emacs
- [ ] 🧪 Vim
  -  @mrnugget 
- [ ] 🆕 IntelliJ
  - @davidv
- [ ] 🧪 CLI
  -  @mrnugget

### Plugins/Misc

- [ ] 🔍 User-defined recipes
- [ ] 🪧 Plugin system
- [ ] 🆕 Make Cody use different types of data
    - [ ] 🆕 Indexing documentation
    - [ ] 🆕 GitHub issues/code reviews
    - [ ] 🧪 Honeycomb traces, spans (@dominiccooney was looking into this)
    - [ ] 🆕 Git
    - [ ] 🆕 Compiler error output + runtime errors
- [ ] 🔍 Make Cody use tools
- [ ] 🆕 GraphViz in Cody
- [ ] 🪧 ChatGPT plugin
- [ ] 🆕 Prompt testing
- [ ] 🧱 Cody can use App as a backend
  -  @slimsag

**Comment by mrnugget** [comment]
Clsoing this, since it's outdated
