### ISSUE TITLE
gRPC June 2023 milestone

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#51069]
# Plan

#### delivery enablement

In general, start the conversations with our delivery and support teams to identify customers that we can work with for trying out grpc with the 5.1.X release, and get the ball rolling with our Cloud team to start enabling gRPC on managed instances. 

- [ ] https://github.com/sourcegraph/sourcegraph/issues/51067
- [x] https://github.com/sourcegraph/sourcegraph/issues/51547
 	- [x] https://github.com/sourcegraph/sourcegraph/issues/51595
- [x] https://github.com/sourcegraph/sourcegraph/pull/53350
- [x] https://github.com/sourcegraph/sourcegraph/pull/52208 - This PR adds additional monitoring for non-utf-8 string issue described in #52181. 

####  feature parity with REST rpc implementations:

- [x] https://github.com/sourcegraph/sourcegraph/issues/51056
- [x] https://github.com/sourcegraph/sourcegraph/issues/51055 
- [x] https://github.com/sourcegraph/sourcegraph/issues/51501

#### prepare for making gRPC the **default implementation** for internal API calls:

- [x] https://github.com/sourcegraph/sourcegraph/issues/51066

### after branch cut

- [ ] https://github.com/sourcegraph/sourcegraph/issues/51054: This is related to our own CI pipeline, not Sourcegraph itself. So, this PR doesn't _need_ to go in before code freeze. 

- [ ] https://github.com/sourcegraph/sourcegraph/issues/51060: This makes Zoekt-indexserver robust against certain transient network errors when requesting configuration from sourcegraph-frontend. Our http implementation already handles this, so it'd be nice for the gRPC implementation to support this as well. However adding [monitoring](https://github.com/sourcegraph/sourcegraph/pull/52208) for the [utf-8 issue](https://github.com/sourcegraph/sourcegraph/issues/52181) took precedence over this. 

- [ ] https://github.com/sourcegraph/sourcegraph/issues/53356 - Unfortunately, an issue with the sourcegraph-frontend -> zoekt-webserver PR was discovered just shortly after this was merged. Given then impending branch cut, a decision was made to put this specific gRPC implementation behind an additional feature flag. (see the issues for more details). @ggilmore made the decision that adding [additional monitoring support for the utf-8 issue](https://github.com/sourcegraph/sourcegraph/pull/52208)) was more important than trying to figure exactly what went wrong with this implementation. 

- [ ] https://github.com/sourcegraph/sourcegraph/pull/52181 - The monitoring component for this (https://github.com/sourcegraph/sourcegraph/pull/52208) will be added _before_ branch cut. However, the analysis of the breadth impact of this issue and any possible mitigations will be need to be done after branch cut. This is not an issue for the release since gRPC is off by default, we will have monitoring for this in place, and I strongly suspect that our managed instance customers will be much less exposed to non-utf8 strings.

#### migrate services 

- [ ] https://github.com/sourcegraph/sourcegraph/issues/46525
- [x] https://github.com/sourcegraph/sourcegraph/issues/46522

### Reason: Not reasonable to tackle in this milestone, but can be explored in a future one

- Convert the following services / endpoints to use gRPC:
	-  `syntax-highlighter`: This service is written in rust, and neither @mucles @ggilmore have experience writing this language. 

### Reason: Wait until related projects are approved 

- https://github.com/sourcegraph/sourcegraph/issues/51059
 	- Opening additional ports for gRPC can require us to coordinate a lot with our customers before we're able to roll this out. Since the likely-to-be-prioritized mTLS project could also require port changes, it makes sense to defer this work so only ask customers to change their ports once (instead of twice over back-to-back releases). 

### Reason: Out of Scope for the gRPC effort as a whole 

- Convert the following services / endpoints to use gRPC:
	- `postgres`: Postgres uses a [custom wire protocol](https://www.postgresql.org/docs/current/protocol.html) by default. There is no officially support Protobuf-based implementation, nor can we expect most hosted postgres solutions to support a custom protocol. 
	- `redis`: see postgres

- Convert any public facing APIs to use gRPC. This is not in scope[ for the original PRFAQ](https://docs.google.com/document/d/1lf7REi_4t03tIxSPccDG4VHtNo-6SLI1-3zDcrspi6k/edit#heading=h.5lz8pui1twmh). Many clients such as web-browsers use our public facing APIs, and there isn't a great story for [these types of clients](https://buf.build/blog/connect-web-protobuf-grpc-in-the-browser).

**Comment by camdencheek** [comment]
@ggilmore can we close this one out?
