### ISSUE TITLE
Cody tracking issue - 

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#51094]
## Plan

```[tasklist]
### Features
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50273
- [ ] https://github.com/sourcegraph/sourcegraph/issues/51090
- [ ] #50726 @eseliger 
- [ ] https://github.com/sourcegraph/pr-faqs/issues/152
- [ ] cody web app: https://github.com/sourcegraph/sourcegraph/issues/50784 - @philipp-spiess & @thenamankumar 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50399 @dominiccooney 
```

```[tasklist]
### Bugs and other stuff
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50771
```

```[tasklist]
## Next cycle wishlist
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50459
```
