### ISSUE TITLE
Setup: Improve local repositories picker/step screen UI/UX

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#51251]
## Design

- [Design issue](https://github.com/sourcegraph/sourcegraph/issues/50729)
- [Low-fidelity wireframes](https://app.excalidraw.com/s/4Dr1S6qmmY7/8npVXwfKEHS)
- [High-fidelity Figma design](https://www.figma.com/file/8UUuaIUPVJDzp8U9ImNvA7/Connect-Cody-and-polish-setup-experience?type=design&node-id=210-513&t=j3cJJmHmUooKaUkl-0)

## Work items

- [x] Frontend: Create routing and chrome for new "setup" settings page (https://github.com/sourcegraph/sourcegraph/pull/51589)
- [ ] Backend: Modify filepicker API to selectively detect that a folder is either itself a Git repo, or parent folder of multiple Git repos, and return the right response or error if that is not the case
- [ ] Backend: Modify the way local code hosts are stored to know if it's either a single Git repo folder, or a parent folder of multiple Git repos
- [ ] Frontend: Implement new local repository picking/management UI for picking single repo folders
- [ ] Frontend: Implement new local repository picking/management UI for picking parent folder of multiple repos
- [ ] Frontend: Implement "Connect sourcegraph.com" page based on existing menu item action

## Feedback from user testing research
Users clicked the text to edit the file path for local repos instead of clicking the "Pick Path" button. 
- [One user was vocally frustrated about the experience of using "Pick path."](https://sourcegraph.dovetailapp.com/data/3ulhqqBRSRSB3iOegrm5uT#:v:h=3f6wmhPPQXLkfuu4eTQ9af)
- [4/8 users said that the setup experience wasn't transparent.](https://docs.google.com/forms/d/1I-vY0K9P0BiD5cmQujCNEoipSEL_N-iBP95dskeKYJU/edit#responses)

Notes: Redesign the "Pick Path" UI to represent better what users can do with it (currently, it appears to be a field, so users want to type in it; however, it is working more like a button than a form field, leading to confusion). Redesign the "Pick Path" UI for better user freedom and transparency.

## Considerations 
- We do have a picker field for MacOS but for Linux and Windows, we fallback on a simple text field where you suppose to fill out an absolute path for a directory with git repositories
- from @limitedmage  rethink input itself maybe we should use a static list with add/remove controls. Also suggests creating groups of repos by folder in blocks.

- from @almeidapaulooliveira we also need to think about the issue of people wanting to edit which repos they’ve added in individual folders

- from @fkling  I think we’ll definitely need a fallback input method. Depending on what kind of application we want to be we could actually store the local repository syncing settings in a settings file. We could then simply read from and write to the file in the fallback input method.

**Comment by vovakulikov** [comment]
@limitedmage This might be implemented on the client only if we don't have enough time to make BE changes/improvements. We could scan a fetched list of repositories and aggregate them by their paths. 

>Backend: Modify the way local code hosts are stored to know if it's either a single Git repo folder, or a parent folder of multiple Git repos

**Comment by limitedmage** [comment]
> @limitedmage This might be implemented on the client only if we don't have enough time to make BE changes/improvements. We could scan a fetched list of repositories and aggregate them by their paths.
> 
> > Backend: Modify the way local code hosts are stored to know if it's either a single Git repo folder, or a parent folder of multiple Git repos

@vovakulikov  I think having this in the backend would be the best way to easily know what UI to render for this design: 

![image](https://github.com/sourcegraph/sourcegraph/assets/206864/f0b3afac-1f6f-413f-a299-b07fa94bf6ea)

We can start with a simplified version of this UI that still has you pick a single folder/folders and we render all the repos in a list without grouping.

**Comment by slimsag** [comment]
> Backend: Modify the way local code hosts are stored to know if it's either a single Git repo folder, or a parent folder of multiple Git repos

I think it would be very easy to return a boolean indicating if the selected repo contained a `.git` directory. Otherwise, we can assume it's a folder of multiple Git repos (figuring out if this is actually true would probably be costly if the user picks a big folder.)

**Comment by slimsag** [comment]
I'm starting to look at / think about the backend issues here, and will really begin to dive in on Monday.

> Backend: Modify filepicker API to selectively detect that a folder is either itself a Git repo, or parent folder of multiple Git repos, and return the right response or error if that is not the case

I think that this one should be pretty simple if I modify the current GraphQL file picker API to return a boolean indicating if the folder the user picked has a `.git` folder inside of it. Not perfect, but a decent signal that it is an individual repo. The downside of this is it would inch us further away from switching to the Tauri file-picker API? The alternative would be for me to expose a new API which takes a filepath and tells if it contains a `.git` folder, so we can use the Tauri file picker API and then answer the same question in the frontend code ourselves. Thoughts?

> Backend: Modify the way local code hosts are stored to know if it's either a single Git repo folder, or a parent folder of multiple Git repos

I think this will probably be affected greatly by the work @fkling is doing in #51805 - after looking at his PR there I see we have some reconciliation of ideas to sort through here. From what I am seeing, we can still basically do the same thing we planned before:

1. If the user clicks add-single-repository, we can add a new `LOCAL` external service whose config points to just that one repo (as was the plan before)
2. If the user clicks add-folder-of-repositories, we can add a new `LOCAL` external service whose config points to `/glob/pattern/*` (as was the plan before)

We could then differentiate in the UI which type it is by looking at the glob pattern (if it ends with `*` we know it's a folder of repos, not an individual repo)?

**Comment by slimsag** [comment]
https://github.com/sourcegraph/sourcegraph/pull/51841

**Comment by limitedmage** [comment]
Thanks @slimsag! Agree that we should reconcile the work being done in #51805 and #51841 with the design that's being worked on, to make sure the new changes enable us to implement the design successfully. 

I also agree it's better to switchto  the Tauri dialog rather than keep using the GraphQL API to open a file picker, so let's prioritize that (#51841).

**Comment by slimsag** [comment]
I think this is all done, so going to close this. Let's reopen more specific issues for any individual items that we need to follow up on.
