### ISSUE TITLE
☂️ Cody completions engineering umbrella

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#51344]
[Project Board](https://github.com/orgs/sourcegraph/projects/331/views/6)

A list of engineering tasks to complete for https://github.com/sourcegraph/pr-faqs/issues/152

```[tasklist]
## Known Issues and bugs
- [ ] #52529
- [ ] #52587
```

```[tasklist]
## Next up
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52592
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52593
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52594
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52591
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52589
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52590
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52595
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52596
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52598
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52687
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52942
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52945
- [ ] https://github.com/sourcegraph/sourcegraph/issues/53315
- [ ] https://github.com/sourcegraph/sourcegraph/issues/53317
- [ ] https://github.com/sourcegraph/sourcegraph/issues/53316
- [ ] https://github.com/sourcegraph/sourcegraph/issues/53633
- [ ] https://github.com/sourcegraph/sourcegraph/issues/53634
- [ ] https://github.com/sourcegraph/sourcegraph/issues/53635
- [ ] https://github.com/sourcegraph/sourcegraph/issues/53636
- [ ] https://github.com/sourcegraph/sourcegraph/issues/53642
- [ ] https://github.com/sourcegraph/sourcegraph/issues/53643
- [ ] https://github.com/sourcegraph/sourcegraph/issues/53644
```

**Comment by philipp-spiess** [comment]
I'll be retiring this issue in favor of the project board: https://github.com/orgs/sourcegraph/projects/331/views/6
