### ISSUE TITLE
Change Cody release readiness from "Experimental" to "Beta" in all repositories, both as a text label and in images

### ISSUE THREAD

**Issue by gwestersf** [sourcegraph/sourcegraph#51445]
Cody is currently in public beta. The current feature set has been validated by early customers. New features releasing in June may be experimental or beta, but the overall product has beta readiness.

**Task List**

- [ ] Change experimental label on about.sourcegraph.com
- [ ] Change experimental label on Sourcegraph App
- [ ] Change experimental label in Visual Studio Code plugin
- [ ] Change experimental label on docs.sourcegraph.com
- [ ] Code search for other mentions of "experimental"
- [ ] Product to work with marketing (product marketing) to update recorded materials and artwork to beta

**Comment by philipp-spiess** [comment]
@gwestersf From an engineering side this is all done. I’m not sure what your plans are on the marketing side though so I’m assigning this to you for now.
