### ISSUE TITLE
Cody 0.1 bug bash umbrella

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#51773]
Since there were quite a few bug reports, I’m summarizing them into an issue so we don't forget about any:

```[tasklist]
## Bugs
- [ ] https://github.com/sourcegraph/sourcegraph/issues/51768
- [ ] https://github.com/sourcegraph/sourcegraph/issues/51759
- [ ] https://github.com/sourcegraph/sourcegraph/issues/51760
- [x] Change Cody name to "Cody AI by Sourcegraph" and update READMEs (https://sourcegraph.slack.com/archives/C052G9Y5Y8H/p1683755505861949?thread_ts=1683718154.408839&cid=C052G9Y5Y8H)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/51776
- [x] Make it so that reset opens the chat tab
```

**Comment by philipp-spiess** [comment]
Removing Cody Bug: Edit field behaves different #51740 from the list. This is not a recent regression and doesn't seem super urgent to fix (compared to the rest).

**Comment by philipp-spiess** [comment]
All of these are fixed now 🎉
