### ISSUE TITLE
[dri] Detailed ownership page for directory and repo.

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#51792]
- [x] UI presenting ownership details https://github.com/sourcegraph/sourcegraph/issues/50799
- [x] Show more in Ownership panel links to drilldown page on repo/dir view
- [x] Can promote signals to owners from drilldown page
- [x] Can assign arbitrary owners from the drilldown page
