### ISSUE TITLE
llmproxy: Productionize service

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#51830]
On our last mile towards a hosted service, we need to productionize it further. This includes (and please help to extend this list, as it's just some initial thoughts and you guys have more experience productionizing deployments here):
- [x] Playbook for operations: https://handbook.sourcegraph.com/departments/engineering/teams/cody/llm-proxy/
- [x] Alerting and observability to know when things break
  - [x] Alerts go to Slack
  - [ ] Alerts go to on-call: TBD => https://github.com/sourcegraph/sourcegraph/issues/52409
  - [x] Dashboards (Grafana like, for Cloud Run): Only the OOTB for now https://handbook.sourcegraph.com/departments/engineering/teams/cody/llm-proxy/#observability
- [x] Perhaps investigate tracing to see timing issues, but unclear if this can work (can we propagate spans over HTTP?): https://handbook.sourcegraph.com/departments/engineering/teams/cody/llm-proxy/#tracing 
- [ ] Connect to dotcom and see if that causes any significant load => #52327 
- [ ] Start defining SLAs for the prod deployment, multi-region? => https://github.com/sourcegraph/sourcegraph/issues/52409
- @unknwon 
	- [x] How does Cloud Run actually perform and scale under pressure? (probably due to my lack of hands-on experience with Cloud Run)?
	  - Scale-up happens aggressively based primarily on concurrent requests. See https://github.com/sourcegraph/infrastructure/pull/4979 for initial observations
	- [x] What happens when upgrades/deployments occurs during heave traffic?
	  - Request do not route to new revisions until they are healthy based on `/-/healthz`
	- [x] How long would a Cloud Run connection survive for streaming requests? (e.g. if the streaming response takes 2 minutes, would it be killed)? => https://github.com/sourcegraph/infrastructure/pull/4992
- Rafal
	- [x] Proxying overhead, how much time we spent on non-upstream requests, e.g. contacting dotcom, checking rate limiting, etc.
	   - We have always-on tracing for everything going through LLM-proxy, including request to Sourcegraph.com, upstream providers, event logging, background jobs, etc. https://handbook.sourcegraph.com/departments/engineering/teams/cody/llm-proxy/#tracing

**Comment by bobheadxi** [comment]
Initial ops docs: http://go/llm-proxy
