### ISSUE TITLE
[aso] Assigning ownership

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#51922]
Brainstorm doc: https://docs.google.com/document/d/11bgay02tTT_ZICM8L4GbWe-C1WFzd39gJ8lBwdFZCB0/edit#

Filed work items:

- [x] DB & repos #51914 
- [x] RBAC wired up with ownership assigning #51915 
- [x] `own.Service` extended with a method returning assigned owners per repo #51916 

Next work items:

- [x] Integrate assigned owners into search https://github.com/sourcegraph/sourcegraph/issues/52133
- [x] integrate assigned owners into graphQL resolvers (blob, repo, directory view) https://github.com/sourcegraph/sourcegraph/issues/52134
- [x] implement graphQL API for changing assigned ownership (with RBAC) https://github.com/sourcegraph/sourcegraph/issues/52135
- [x] UI for changing assigned ownership
  - [x] Button to promote an owner [#52891](https://github.com/sourcegraph/sourcegraph/issues/52891)
  - [x] UI for assigning arbitrary owner
