### ISSUE TITLE
[uni] Resolution and unification of owners

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#52139]
Following from the spike: https://github.com/sourcegraph/sourcegraph/pull/52070

- [x] Merge in `Bag` for search filtering use case (this ticket)
- [x] Merge in `Clusters` for graphQL API and search select use cases (this ticket) https://github.com/sourcegraph/sourcegraph/pull/52501
- [x] Allow searching by verified email https://github.com/sourcegraph/sourcegraph/issues/52140
- [ ] Allow searching by code host handle https://github.com/sourcegraph/sourcegraph/issues/52141
- [x] Match linked code host handles https://github.com/sourcegraph/sourcegraph/issues/52142
- [x] Match all verified emails https://github.com/sourcegraph/sourcegraph/issues/52143
- [x] Teams matching https://github.com/sourcegraph/sourcegraph/issues/52503
- Extracting github identity from email 
- [x] Replacing own.Service/ResolveOwners use in search filtering with Bag 
- [x] Replace own.Service/ResolveOwners use in search `select:file.owners` https://github.com/sourcegraph/sourcegraph/pull/52501
- [x] Replace own.Service/ResolveOnwers use in graphQL resolvers. https://github.com/sourcegraph/sourcegraph/issues/52504
