### ISSUE TITLE
Seamless embeddings tracking issue

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#52253]
### Plan

**Problem**: 
Admins have to schedule embedding jobs manually, which is intractable for customers that want to embed a lot of repos.

**Why should we solve this Problem?**
Solving the problem will enable customers to embed a large number of repos which will improve the user experience of Cody.

**How:**
- Support delta updates to avoid exploding costs of auto-scheduled embedding jobs
- Leverage codeintel's policy framework for UI and backend.

### Tasks

```[tasklist]
### must
- [ ] #52158
- [ ] #52326
- [x] https://github.com/sourcegraph/sourcegraph/pull/52374
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52455
- [ ] https://github.com/sourcegraph/sourcegraph/pull/52505
- [ ] https://github.com/sourcegraph/sourcegraph/pull/52799
- [ ] #52066
- [ ] https://github.com/sourcegraph/sourcegraph/pull/52822
- [ ] https://github.com/sourcegraph/sourcegraph/issues/50172
- [ ] https://github.com/sourcegraph/sourcegraph/pull/52888
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52983
- [ ] https://github.com/sourcegraph/sourcegraph/pull/53226
- [ ] Enable "incremental" per default
```

```[tasklist]
### nice-to-have
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52358
- [ ] https://github.com/sourcegraph/sourcegraph/issues/52668
- [ ] Invariant: never schedule 2 jobs for the same repo
```
