### ISSUE TITLE
Self Hosted Embeddings on AWS

### ISSUE THREAD

**Issue by jac** [sourcegraph/sourcegraph#52272]
## Background
It is not possible on AWS to provision less than eight A100 40GB GPUs at a time (p4d.24xlarge). This makes self hosting an embeddings model prohibitively expensive (~25k/month).

AWS has a number of [Accelerated Computing](https://aws.amazon.com/ec2/instance-types/#Accelerated_Computing) offerings with other GPU models. Evaluation of these offerings to determine an optimal performance/cost choice is critical in order to offer self hosted embeddings generation on AWS.

The following [blog post](https://towardsdatascience.com/choosing-the-right-gpu-for-deep-learning-on-aws-d69c157d8c86) provides a general overview of the offerings including recommendations based on key metrics (performance, cost). This provides a starting point from which we can do our own evaluation.

## Testing
Embeddings performance will be evaluated using the [all-mpnet-base2](https://huggingface.co/sentence-transformers/all-mpnet-base-v2) model to generate embeddings for the [sourcegraph/sourcegraph](https://github.com/sourcegraph/sourcegraph) repository.

```[tasklist]
### GPU Evaluation
- [x] A100 40G baseline measurement
- [x] A10G measurement
- [x] T4 measurement
- [x] V100 measurement
```

## Deployment

```[tasklist]
### Tasks
- [ ] Make [sourcegraph/embeddings-api](https://github.com/sourcegraph/embeddings-api/) public
- [ ] Make `sourcegraph/embeddings-api` Docker image public
- [ ] Build AMI which has Docker deployment pre-configured and/or document manual deployment process
```

**Comment by jac** [comment]
# Prepping the host machine
NVIDIA drivers must be installed to utilise the GPU. AWS outlines a few [methods](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-nvidia-driver.html) for doing so.

The following details the steps for `Option 2: Public NVIDIA drivers`:
```bash
# Pre-req
## !!! Must be using Amazon Linux 2 (HVM) and not Amazon Linux 2023
$ sudo yum update
$ sudo yum install kernel-devel

# Install nvidia driver
## !!! Ensure `uname -r` output matches `ls /usr/src/kernels`
## !!! The `yum update` above likely updated the kernel - reboot to switch to it
$ sudo ln -s /bin/gcc10-cc /usr/bin/cc
$ export BASE_URL=https://us.download.nvidia.com/tesla
$ export DRIVER_VERSION=470.182.03
$ curl -fSsl -O $BASE_URL/$DRIVER_VERSION/NVIDIA-Linux-x86_64-$DRIVER_VERSION.run
$ sudo sh NVIDIA-Linux-x86_64-$DRIVER_VERSION.run
#> nvidia-installer was forced to guess...
#> > Ok
#> Install 32-bit compatibility...
#> > No
#> > Ok

# Install docker + nvidia-container-runtime
$ sudo yum install docker
$ sudo systemctl enable --now docker
$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.repo | sudo tee /etc/yum.repos.d/nvidia-container-toolkit.repo
$ sudo yum install nvidia-container-toolkit
$ sudo nvidia-ctk runtime configure --runtime=docker
$ sudo usermod -a -G docker ec2-user
$ newgrp docker
$ sudo systemctl restart docker

# Verify docker can use GPU
$ sudo docker run --rm --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi
```

AWS also offer prebuilt AMIs which have the Tesla drives preinstalled which I have not verified yet.

**Comment by jac** [comment]
# Testing Details
As previously noted testing involves embedding the `sourcegraph/sourcegraph` repo using [all-mpnet-base-v2](https://huggingface.co/sentence-transformers/all-mpnet-base-v2). Here I'll dig a little deeper into the testing infra and process.

## Infra
There are two main components of the testing infra, a Sourcegraph deployment, and the embeddings-api.
The components are deployed on separate instances within the same region in `ec2` ensuring minimal latency reducing the influence of RTT on the embedding duration.

### Sourcegraph Deployment
- m6a.2xlarge
- Docker Compose deployment
- Embeddings stored in blobstore
- 50GB gp3 drive

1. Spin up Sourcegraph with Embeddings service enabled
```bash
docker compose -f docker-compose.yaml -f embeddings/embeddings.docker-compose.yaml up -d
```
2. Add GitHub code host, `sourcegraph/sourcegraph` repo
3. Wait for clone + Zoekt index to finish


### Embeddings API
- Amazon Linux 2

1. Deploy GPU instance for testing
2. Follow above [instructions](https://github.com/sourcegraph/sourcegraph/issues/52272#issuecomment-1559624564) to configure the machine as necessary to run the `embeddings-api` container.
3.  Deploy the container[^1]
```
docker run --gpus all -p 80:8000 --name embeddings-api -d embeddings-api
```
4. Verify the model is working
```
curl http://127.0.0.1/v1/embeddings \
  -H "Content-Type: application/json" \
  -d '{
    "input": "Your text string goes here",
    "model": "embeddings-v1"
  }'
```

[^1]: As the prebuilt image is private I used `scp` to copy the [embeddings-api](https://github.com/sourcegraph/embeddings-api/) repo to the instance and build the image there

## Testing Process
1. Configure the Sourcegraph repo for Embeddings
```
"embeddings": {
    "enabled": true,
    "url": "http://ip-<ip>.us-west-2.compute.internal/v1/embeddings",
    "accessToken": "dummy value",
    "model": "embeddings-v1",
    "dimensions": 768,
    "excludedFilePathPatterns": []
  }
```
As the `embeddings-api` is not behind any auth the `accessToken` value doesn't matter.
2. Schedule the embeddings of `sourcegraph/sourcegraph`
3. Wait for the embeddings to finish generating
4. Retrieve the `start` and `end` times from the `repo_embedding_jobs` table
```
$docker exec -it pgsql psql -U sg
> select * from repo_embedding_jobs;
```
5. Tear down the Sourcegraph instance
```
docker compose -f docker-compose.yaml -f embeddings/embeddings.docker-compose.yaml down -v
```
6. Repeat for the next GPU

**Comment by jac** [comment]
# Findings

| Instance Type | GPU  | GPU Amount | Max Observed GPU Mem (MiB) | Start Time      | Finish Time     | Duration (minutes) |
| ------------- | ---- | ---------- | -------------------------- | --------------- | --------------- | ------------------ |
| g5.xlarge     | A10G | 1          | 5350                       | 13:34:00.10115  | 13:42:05.245624 | 8.09               |
| g4dn.xlarge   | T4   | 1          | 5150                       | 14:59:37.039573 | 15:21:48.810683 | 22.2               |

### Notes
- From my observation Sourcegraph does a good job of keeping the GPU at 100% utilisation for the entire time

**Comment by rafax** [comment]
@jac if I understand this correctly, Sourcegraph embedding worker job is responsible for scheduling calls to Embedding API here - did you make any configuration tweaks to make sure it can use all of API capacity? Are there any available?

**Comment by jac** [comment]
@rafax I used a default Docker Compose deployment with Embeddings enabled.

I was doing some more reading on the stats reported by `nvidia-smi`, particularly the `Utilisation` metric.

>  the percentage of time one or more GPU kernels are running over the last second

As such there could have been idle GPU kernels despite showing 100% utilisation. Profiling would be necessary to determine how many kernels were actually in use at any point in time.

If I'm not mistaken worker has a default concurrency of 1. So it processes sequential chunks of a single repo.
With higher concurrency embedding two repos in parallel the results could be significantly different depending on the number of GPU kernels a particular GPU model has.


This could be what you are seeing? There very much could be unused API capacity as a result of the way Sourcegraph currently interacts with the API.
