### ISSUE TITLE
📕 [Tracking issue] Licensing and Gating

### ISSUE THREAD

**Issue by kopancek** [sourcegraph/sourcegraph#52507]
# Description

Tracking issue for licensing and gating PRFAQ:
- https://github.com/sourcegraph/pr-faqs/issues/123

All the milestones are defined in the [PRFAQ google doc](https://docs.google.com/document/d/1g46TWsxMgtjSE6yNyNtWdUU8XpB35JamL0YFa7Gwb0o/edit#heading=h.qqzw2fy1e7cb)

Below is a list of milestones and sub-jobs that need to be completed for each milestone.

# Milestones

## M1: Fix admin analytics MAU reporting

- [x] 🐛 The Monthly Active User calculation shows a different number of active users since it is calculated in multiple places

## M2: Automated billing changes

These are things needed to support the [2023-04-17 Automated billing Q2 proposal](https://docs.google.com/document/u/0/d/1aJniLvsyAuomsnBrdT0_kpVa9P2tbSYZEwS8bmfGJRg/edit))

- [x] #52508
- [x] #52836
- [x] API endpoint for checking license validity and mapping license to a specific sourcegraph instance https://github.com/sourcegraph/sourcegraph/pull/52928
- [x] Call the licensing API from instances on a periodic basis https://github.com/sourcegraph/sourcegraph/pull/52948
  - [x] https://github.com/sourcegraph/sourcegraph/pull/53297
- [x] #52921
  - [x] Add catch-all alert for revoked/expired license
- [x] #53144
  - this might be risky and we need to be very careful what we plan on doing here
- [x] #53075
- [x] Only allow not sending pings to us if the license is air-gapped
- [x] #53145
- [x] https://github.com/sourcegraph/sourcegraph/pull/53474

## Won't do
~M3: Eliminating abuse of the soft-deletion API~

- ~[ ] Figure out with other business stakeholders what can be done here~
- ~[ ] Make the necessary changes (TBD)~

# Risks
- ~M3 is risky, because we are very close to the deadline and it is not clear how we want to solve the problem~

**Comment by kopancek** [comment]
Closing as this was done
