### ISSUE TITLE
VS Cody <> App onboarding experience

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/sourcegraph#52659]
This is a parent issue for tracking how we can optimise the Minimum Time to Aha for Cody in VS Code, and in particular to how it integrates with the Cody App.

## Tasks

```tasklist
### In progress
- [ ] Add App download button in https://github.com/sourcegraph/sourcegraph/pull/52560
- [ ] Add Embedding setup notices w/ "Add to Cody" buttons in https://github.com/sourcegraph/sourcegraph/issues/52614

### TODO
- [ ] Improve login page design and copy
- [ ] Review the scenarios
```

## Design Principles

- Optimise the minimum steps to aha moment at all costs
- The experience should be delightfully simple
- All setup should be as automatic as possible
- After the first aha, help them to explore and go deeper

## Ideal Scenarios

The end-to-end workflows we're aiming for…

### Scenario 1: Starting with VS Code

1. Developer installs Cody from VS Code Marketplace
1. VS Code shows a link to download the App
1. Developer downloads, installs and runs the App
1. Logs into Sourcegraph (? should it also detect creds from VS Code if they exist?)
1. App auto-detects the VS Code extension
1. App auto-adds the repos and starts generating embeddings
1. App gives a link/button to return to VS Code w/ login credentials
1. VS Code shows the embeddings are being generated
1. VS Code and/or Cody app notifies user that Cody is ready to go
1. Developer has first "aha" moment interacting with Cody

### Scenario 2: Starting with Cody App

TODO

## Open questions

- What happens if an excited developer from an Enterprise customer wants to try out Cody with some of their own private code. VS Code can only talk to an SG instance or the Cody app… but should it be able to talk to both?

**Comment by malomarrec** [comment]
Just linking the Cody onboarding [tracking doc here](https://docs.google.com/document/d/12es0B419R7eP76-M29RHxMW6dOdF4y2Kjc6ReSh5nPs/edit#)

**Comment by toolmantim** [comment]
Put together some flows for how a much more streamlined onboarding could work between Cody App and Cody for VS Code:
https://app.excalidraw.com/s/4Dr1S6qmmY7/7Hbgb8FoGtZ

Will be discussing with @danielmarquespt tomorrow for how it maps to the work he's already started on the App.

**Comment by toolmantim** [comment]
Given the work that's happening on other IDE extensions, we should consider which parts of this would be universal too.

**Comment by toolmantim** [comment]
Design work is happening in https://github.com/sourcegraph/sourcegraph/issues/53238

**Comment by toolmantim** [comment]
I've updated https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?type=design&node-id=3250-136841&mode=design to cover all the items here that need doing

cc @abeatrix @dominiccooney

**Comment by toolmantim** [comment]
@umpox fyi I added an item related to the welcome guide
