### ISSUE TITLE
5.0.5 patch release tracking issue

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#52745]
# 5.0.5 patch release

This release is scheduled for **[May 31, 2023, 5:00 PM (UTC)](https://time.is/1700_31_May_2023_in_UTC?5.0.5%20release%20date)**.

> **Attention developers:** to get your commits in `main` included in this patch release, please file a [patch request](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=&labels=team%2Fdistribution&template=request_patch_release.md&title=5.0.5%3A+) for review.
>
> Only check off items if relevant commits across the following repositories have been cherry-picked into the relevant `5.0` branch by the release captain:
>
> - `sourcegraph/sourcegraph`
> - `sourcegraph/deploy-sourcegraph`
> - `sourcegraph/deploy-sourcegraph-docker`

- [x] TODO: Add [patch request issues](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Apatch-release-request) and their associated commits here

## Setup

- [x] Ensure release configuration in [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) on `main` has version 5.0.5 selected by using the command:

```shell
pnpm run release release:activate-release
```

- [x] Ensure you have the latest version of the release tooling and configuration by checking out and updating `sourcegraph@main`.
- [x] Create a `Security release approval issue` and post a message in the [#security](https://sourcegraph.slack.com/archives/C1JH2BEHZ) channel tagging @security-support.

## Prepare release

Ensure that all [patch request issues](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Apatch-release-request) are accounted for, and have all relevant commits across relevant repositories listed above in the checklist.

For each of the following repositories you have made changes to, cherry-pick (see snippet below) and check off commits listed above.

- [x] `sourcegraph/sourcegraph` ([`5.0` release branch](https://github.com/sourcegraph/sourcegraph/tree/5.0) [CI](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=5.0))
- [x] `sourcegraph/deploy-sourcegraph` ([`5.0` release branch](https://github.com/sourcegraph/deploy-sourcegraph/tree/5.0) [CI](https://buildkite.com/sourcegraph/deploy-sourcegraph/builds?branch=5.0))
- [x] `sourcegraph/deploy-sourcegraph-docker` ([`5.0` release branch](https://github.com/sourcegraph/deploy-sourcegraph-docker/tree/5.0) [CI](https://buildkite.com/sourcegraph/deploy-sourcegraph-docker/builds?branch=5.0))
- [x] `sourcegraph/deploy-sourcegraph-helm` ([`5.0` release branch](https://github.com/sourcegraph/deploy-sourcegraph-helm/tree/release/5.0) [CI](https://buildkite.com/sourcegraph/deploy-sourcegraph-helm/builds?branch=5.0))

```sh
git checkout 5.0
git pull
git cherry-pick <commit0> <commit1> ... # all relevant commits from the default branch
git push origin 5.0
```

- [x] Ensure CI passes on all release branches listed above.

Create and test the first release candidate:

- [x] Push a new release candidate tag. This command will automatically detect the appropriate release candidate number. This command can be executed as many times as required, and will increment the release candidate number for each subsequent build: :
  ```sh
  pnpm run release release:create-candidate
  ```

**Note**: Ensure that you've pulled both main and release branches before running this command.

- [x] Ensure that the following Buildkite pipelines all pass for the `v5.0.5-rc.1` tag:
- [x] [Sourcegraph pipeline](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=v5.0.5-rc.1)
- [x] File any failures and regressions in the pipelines as `release-blocker` issues and assign the appropriate teams.

**Note**: You will need to re-check the above pipelines for any subsequent release candidates. You can see the Buildkite logs by tweaking the "branch" query parameter in the URLs to point to the desired release candidate. In general, the URL scheme looks like the following (replacing `N` in the URL):

- Sourcegraph: `https://buildkite.com/sourcegraph/sourcegraph/builds?branch=v5.0.5-rc.N`
- QA: `https://buildkite.com/sourcegraph/qa/builds?branch=v5.0.5-rc.N`
- E2E: `https://buildkite.com/sourcegraph/qa/builds?branch=v5.0.5-rc.N`

## Stage release

- [x] Verify the [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) on `main` and `5.0` are accurate.
- [x] Promote a release candidate to the final release build. You will need to provide the tag of the release candidate which you would like to promote as an argument. To get a list of available release candidates, you can use:
  ```shell
  pnpm run release release:check-candidate
  ```
  To promote the candidate, use the command:
  ```sh
  pnpm run release release:promote-candidate tag
  ```
- [x] Ensure that the following pipelines all pass for the `v5.0.5` tag:
- [x] [Sourcegraph pipeline](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=v5.0.5)
- [x] Wait for the `v5.0.5` release Docker images to be available in [Docker Hub](https://hub.docker.com/r/sourcegraph/server/tags)
- [x] Open PRs that publish the new release and address any action items required to finalize draft PRs (track PR status via the [generated release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes)):
  ```sh
  pnpm run release release:stage
  ```

## Finalize release

- [x] From the [release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes), merge the release-publishing PRs created previously. Note: some PRs require certain actions performed before merging.
- [x] **After all the PRs are merged**, perform following checks/actions
  - For [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph)
    - [x] Ensure the [release tag](https://github.com/sourcegraph/deploy-sourcegraph/tags) has been created
  - For [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker)
    - [x] Ensure the [release tag](https://github.com/sourcegraph/deploy-sourcegraph-docker/tags) has been created
  - For [deploy-sourcegraph-helm](https://github.com/sourcegraph/deploy-sourcegraph-helm), also:
    - [x] Update the [changelog](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/CHANGELOG.md) to include changes from the patch
    - [x] Cherry-pick the release-publishing PR from the release branch into `main`
- [x] Finalize and announce that the release is live:
  ```sh
  pnpm run release release:announce
  ```

## Post-release

- [x] Close the release:

```shell
  pnpm run release release:close
```

- [x] Open a PR to update [`dev/release/release-config.jsonc`](https://github.com/sourcegraph/sourcegraph/edit/main/dev/release/release-config.jsonc) after the auto-generated changes above if any.

**Note:** If another patch release is requested after the release, ask that a [patch request issue](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=&labels=team%2Fdistribution&template=request_patch_release.md) be filled out and approved first.

**Comment by keegancsmith** [comment]
The deploy-sourcegraph* repos have no commits since 5.0.4 except for helm which had 3cce4d261ca8201e8491d7ecdea949a660dafe04 which was already included in a hotfix only for helm (`5.0.4-rev.1`)

**Comment by keegancsmith** [comment]
Here are the commits in the sourcegraph repo since 5.0.4:

```
$ git log --oneline v5.0.4..origin/5.0
8efe59f1c4 (origin/5.0) [Backport 5.0] Remove debug print statement (#52727)
a1f6e1f88d [Backport 5.0] Bump syntax-highlighter docker container for single-docker deployment (#52712)
86b00e996c [Backport 5.0] gitserver: use cat-file for reading blobs containing .. (#52688)
a74f104a1a [Backport 5.0] Make endpoint configurable for OpenAI completions client (#52601)
76ab4b8bd3 batches: add docs for new org admin setting (#52676) (#52679)
7da051fc56 [Backport 5.0] batches: add organization setting to enable all members of org to become batch changes admins (#52655)
f64adefa58 remove 'unreleased' text from 5.0.4 changelog entry (#52678)
8ae3a9887f [Backport 5.0] batches: add settings for org level batch changes admin (#52656)
00d83fe795 [Backport-5.0] [fix] fixes for mau calculations in product analytics (#52581) (#52682)
636872c1e6 [Backport 5.0] [fix] makeDateTrunc calculating rolling_month wrong (#52579) (#52607)
15c63593e0 [Backport 5.0] [fix] use same where condition in user analytics as in pings for mau (#52608)
4d3099bfe2 [Backport 5.0] bext: ignore non-code diff content hovers on Bitbucket (#52613)
d7bb5a1aea Backport Implement features in LLM Proxy layer to 5.0 (#52531)
bbd7837886 Backport 52299 to 5.0 (#52302)
d2eac1e79d [Backport 5.0] (feat) add ability to allow anonymous usage mode based on "auth.publi… (#52506)
```

The all have titles except the one which just says 52299, that PR was had this title:
```
[fix] switch id column of user_repo_permissions table to bigint (#52299)
```

**Comment by keegancsmith** [comment]
I'm pretty much ready to promote the tag to final. It isn't clear in the instructions, but I assume I need security to be happy first so will do it once https://github.com/sourcegraph/sourcegraph/issues/52746 is closed.

**Comment by keegancsmith** [comment]
*Sourcegraph 5.0.5 has been published*

* Changelog: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#5-0-5
* GitHub release: https://github.com/sourcegraph/sourcegraph/releases/tag/v5.0.5
* Release batch change: https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.5

@keegancsmith: Please complete the post-release steps before closing this issue.
