### ISSUE TITLE
[rel] Bag is bulletproof

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#52911]
The [Bag](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/own/ownref.go?L115) that is used for unification of various ownership signals needs to be bulletproof. In particular:

- `Resolve` should not error, it should just do best-effort resolution and leave it be.
- No other methods used for interaction should panic.

Tasks:

- [x] Stop the bleeding for prod panics #52870
- [x] Remove root cause #52877
- [x] Do not return errors from the bag #52913
- [x] Guarantee of no panics from the bag
