### ISSUE TITLE
Code Nav: 3.8 tracking issue

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#5293]
**LSIF**
- [x] Decide on a backend implementation for LSIF: **we decided to use SQLite**
- [x] Load/perf testing global find references
- [x] Review SQLite PR https://github.com/sourcegraph/sourcegraph/pull/5332
- [x] C++ LSIF support https://github.com/sourcegraph/lsif-cpp
- [x] Think about how to merge LSIF data from separate compilation units: https://docs.google.com/document/d/1ocoxE_Jnee70_RjQEFSz58jxRE3VZuNg9OGHvu68O6o/edit

**Customer Issues**
- [x] Phabricator issue https://github.com/sourcegraph/sourcegraph/issues/5051
- [ ] Performance on large pull requests: investigate what can be done to remove the 50 code views limit workaround https://github.com/sourcegraph/sourcegraph/issues/5172
    - [x] Improve core inefficiencies in editorService/modelService https://github.com/sourcegraph/sourcegraph/pull/5464
    - [ ] Look into using `IntersectionObserver` to lazily load code views https://github.com/sourcegraph/sourcegraph/pull/5541

**Quality**
- [ ] 100% of browser extension & integrations regression testing is automated  https://github.com/sourcegraph/sourcegraph/issues/5294

**Comment by lguychard** [comment]
- LSIF alpha support was shipped in 3.8.
- Improvements to the Phabricator code were made: https://github.com/sourcegraph/sourcegraph/pull/5320
- Performance:
    - The core inefficiencies were solved by https://github.com/sourcegraph/sourcegraph/pull/5464
    - https://github.com/sourcegraph/sourcegraph/pull/5541 will allow to remove the 50-file limit, but it was not merged in time for branch cut. It should get merged/deployed in the first week of the 3.9 iteration.
- Browser extension tests are automated for all code hosts. The only scenario that is not automated is Phabricator revisions using staging areas. The setup for this scenario is very complex to automate.
