### ISSUE TITLE
cody: ensure cody is correctly enabled/disabled by default for 5.1 release

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#52980]
See: https://docs.google.com/document/d/1syg64zhUapagA1c8YVO7v4_EUI_m583C39UeRNcCJ3k/edit

## Tasks

(These are taken from the Google Doc above)

* [x] Use single site-config value to turn Cody on/off: `cody.enabled: true/false` → https://github.com/sourcegraph/sourcegraph/pull/52919
  - If `cody.enabled == true`, it still needs `completions` to be set for Cody to be on
* [x] Change this ping value to reflect that value: [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@b0b9e06e7f02da16a3837b0c04261dbcc9fb6e17/-/blob/cmd/frontend/internal/app/updatecheck/handler.go?L478) → https://github.com/sourcegraph/sourcegraph/pull/52919
* [x] Keep ability to restrict Cody to certain users, but rename config names → https://github.com/sourcegraph/sourcegraph/pull/52919
    * Keep but rename `experimentalFeatures.CodyRestrictUsersFeatureFlag` to `cody.restrictUsersFeatureFlag`
    * Rename `cody-experimental` feature flag to `cody` (only has effect if `cody.restrictUsersFeatureFlag` is true)
* [x] Show Cody main navigation element and `/cody` page: https://github.com/sourcegraph/sourcegraph/pull/53360
    * This button is visible independent of whether cody is on/off.
    * If `cody.enabled == false`, then we show a "ask your site-admin to enable it" page
        * Design is [here](https://www.figma.com/file/ZpFPw0zZhVkCjrp68hPmA6/Enterprise-Cody-web-onboarding?type=design&node-id=1-1364&t=yuAM9Ol6Yn8S7254-4), development of the .com version is almost complete by GitStart. Only small tweaks required for enterprise.
    * If `cody.enabled == true`, then show Cody
        * Designs for these flows [here](https://www.figma.com/file/ZpFPw0zZhVkCjrp68hPmA6/Enterprise-Cody-web-onboarding?type=design&node-id=0-1&t=yuAM9Ol6Yn8S7254-0).
* [x] Create a documentation page for site-admin that explains https://docs.sourcegraph.com/cody/explanations/enabling_cody_enterprise
    * How to configure `completions`
    * How to configure `embeddings`
        * How to setup blob store
    * How to turn cody on with `cody.enabled`
    * How to restrict turned-on Cody to selective users with `cody.restrictUsersFeatureFlag` and feature flag `cody`
    * Link to this page from `/cody` if user is site-admin https://github.com/sourcegraph/sourcegraph/pull/53626
* [x] Add GraphQL query with which to query whether Cody is enabled on instance or not (for current user) → https://github.com/sourcegraph/sourcegraph/pull/52941
    * `site.codyEnabled`
* [x] Change VS Code extension (and other editor extensions) to check for that value and show friendly error message if Cody is disabled → https://github.com/sourcegraph/sourcegraph/pull/52739
    * (This needs to essentially do two checks: check if `site.CodyEnabled` exists & then possible value)
* [x] Change feature-flags for Cody-in-web so that it's enabled by default according to Product https://github.com/sourcegraph/sourcegraph/pull/53360
* [x] zero-conf of `completions` / `embeddings` in site-config https://github.com/sourcegraph/sourcegraph/pull/53471
    * requirement:
        * on-prem: Sourcegraph license key
        * cloud: Sourcegraph license key
        * app: --
    * requirement 2:
        * on-prem: [CE/AE has to enable Cody Gateway access for license key](https://handbook.sourcegraph.com/departments/engineering/teams/cody/cody-gateway/using/)
        * cloud: cloud has to turn config on to enable Cody Gateway access per instance
        * app: --
    * if `cody.enabled == true` and `completions` and `embeddings` are **not** set:
        * instance talks via **Cody Gateway with Anthropic/OpenAI**, using Sourcegraph’s contract
    * if `cody.enabled == true` and `completions` and `embeddings` are set:
        * instance talks directly to configured completions/embeddings provider
* [x] Add enterprise-gating for Cody: [see ticket](https://github.com/sourcegraph/sourcegraph/issues/52903) https://github.com/sourcegraph/sourcegraph/pull/52933
* [x] update `dev-private` to have up-to-date site-config https://github.com/sourcegraph/dev-private/pull/67
* [ ] stretch goal: create `/site-admin/cody` page that shows **not implemented**
    * whether `cody.enabled` in site-config is on/off
    * whether `cody.restrictUsersFeatureFlag` in site-config is on/off
    * configured completions provider
    * configured embeddings provider
    * usage overview (how many embeddings created, …)
* [x] Implement onboarding and flagged of designs [#53023](https://github.com/sourcegraph/sourcegraph/issues/53023) [Figma](https://github.com/sourcegraph/sourcegraph/issues/53023) https://github.com/sourcegraph/sourcegraph/pull/53360

## Related PRs

- https://github.com/sourcegraph/sourcegraph/pull/52739
- https://github.com/sourcegraph/sourcegraph/pull/52919
- https://github.com/sourcegraph/sourcegraph/pull/52933
- https://github.com/sourcegraph/sourcegraph/pull/52941

**Comment by eseliger** [comment]
Critical items completed.

There are two small follow-ups that we can merge if we want, but the main goal of this ticket is complete, so closing before I head out:
- https://github.com/sourcegraph/sourcegraph/pull/53626 (Please backport)
- https://github.com/sourcegraph/sourcegraph/pull/53628 (already a backport PR, just needs to be merged)
