### ISSUE TITLE
Cody context: keyword search follow-ups

### ISSUE THREAD

**Issue by jtibshirani** [sourcegraph/sourcegraph#53274]
In https://github.com/sourcegraph/sourcegraph/pull/52233 and https://github.com/sourcegraph/sourcegraph/pull/52019 we added support for a keyword search fallback when embeddings aren't available for a repo. This issue tracks remaining bugs + improvements.

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/pull/53279
- [ ] https://github.com/sourcegraph/zoekt/pull/592
- [ ] https://github.com/sourcegraph/sourcegraph/pull/53430
- [x] Debug why are we seeing different scores on S2 vs. dot com? **Answer:** The BM25 score takes into account the average document length in a repo, and how much the current doc differs from that. We use Zoekt shard merging on dot com and S2, which groups multiple repos into the same index and therefore changes the 'average file length' value. This can swap the result order but shouldn't have a huge affect on ranking/ recall.
```
