### ISSUE TITLE
Distribution: 3.8 tracking issue

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#5367]
**Metrics**
- [ ]  built-in prometheus/grafana in all deploy contexts
- [ ] shared dashboards across all deploy contexts
- [ ] custom prometheus/grafana docker images

**High-touch customer upgrades**
- [ ] ....

**High priority customer bugs and issues**
- [ ] ...

**Comment by unknwon** [comment]
Should this be closed?
