### ISSUE TITLE
Search: 3.8 tracking issue

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#5368]
- [ ] Zoekt symbol search follow up work
- [x] Search UI enhancements
    - [x] [Selected result type tabs](https://github.com/sourcegraph/sourcegraph/issues/5378)
- [ ] Literal search as the default: https://github.com/sourcegraph/sourcegraph/issues/5374
