### ISSUE TITLE
cody: add ability to configure context window in site config, expose to client, use it

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#53745]
### Background

After Anthropic [announced the 100K context window](https://www.anthropic.com/index/100k-context-windows) for Claude, we were all eager to try it, but couldn't, because we have a hardcoded context window size on the client side.

In ["Evaluating Cody + gpt-3.5-turbo"](https://docs.google.com/document/d/18v70vqAfCc-6sDMFidxnQflBbrIazZY8Sj3lkRdSEYA/edit) @dominiccooney described how switching models immediately brings up context window problems, because gpt-3.5-turbo is smaller than what Cody was built for (the "old" Anthropic Claude window size).

### Goal

The goal is to be able to not only adjust the `completions.model` in the site-config, but also which context size the client should make use of.

So instead of `completions.model: "claude-1-100k"`, we also want something like (not exactly, probably!) `completions.contextWindow: 100000` in the site-config.

The clients will then fetch this configuration from the instance and adjust amount of context sent to the model accordingly.

### Tasks

- [ ] Add `contextWindow` to site config with good format (is integer the best choice? not sure)
- [ ] Extend GraphQL schema to expose model and context window. Maybe something like this:
    ```graphql
    type Site {
        # [...]
        completionsConfiguration: CompletionsConfiguration!
    }

    type CompletionsConfiguration {
        model: String!
        contextWindow: Int!
    }
    ```
- [ ] VS Code: in backwards-compatible way (like [this](https://github.com/sourcegraph/sourcegraph/blob/1ac0db469d9a6dddb1b6ce2d04b5360e31d0c272/client/cody-shared/src/sourcegraph-api/graphql/client.ts#L229-L266)), read the configuration when connecting to an instance
- [ ] VS Code: build up context to make sure it respects context window size
  - @dominiccooney has some ideas on how we could do this relatively well without just guesstimating: https://docs.google.com/document/d/18v70vqAfCc-6sDMFidxnQflBbrIazZY8Sj3lkRdSEYA/edit?disco=AAAAzGkLshI
- ... possibly more?

**Comment by philipp-spiess** [comment]
Has anyone looked into how complex the tokenizer for these models are? E.g. could we even add the full tokenizer to our clients so we don't have do always approximate the character length somehow?

**Comment by philipp-spiess** [comment]
@philipp-spiess I found this: https://bundlephobia.com/package/gpt-3-encoder@1.1.4

**Comment by mrnugget** [comment]
@philipp-spiess that's what I linked to further above:

> @dominiccooney has some ideas on how we could do this relatively well without just guesstimating: https://docs.google.com/document/d/18v70vqAfCc-6sDMFidxnQflBbrIazZY8Sj3lkRdSEYA/edit?disco=AAAAzGkLshI

**Comment by philipp-spiess** [comment]
@mrnugget 🤦  sorry yeah I see that now
