### ISSUE TITLE
DevInfra: Migrate go:generate directives to Bazel Tracking issue

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#54516]
Using `go:generate` directives doesn't play well with Bazel because the outputs are not deterministic and there is no way they can be integrated that way directly. 

We could argue that we're fine with that and that we'll keep running `sg generate go` and rely on the linter to catch cases where we didn't update the generated files. But it comes with a price: 

- it's moderately slow, it takes about 32s on my machine to complete. 
- it's can be surprising: we're generating src-cli ref docs with the latest released version, but we're using a pinned version when shipping it in the container images.
- it's also fragile, the above example makes a network call; if GitHub is down, it fails. 

So the best approach here is to extract the `go:generate` statement into Bazel. We get the following benefits: 

- it's fast most of the time, because it's cached. 
- it's deterministic, because bazel. 
- it's one step closer to not having to run `sg lint go` in CI.

While it might look complicated on the first look, such statements are merely about calling a shell command. So to bazelify them, we can turn them into a `genrule` and deal with the outputs so they're now deterministic. 

### Plan

- Go through them one by one
- Turn it into a `genrule` 
- If it's a repeated use case, write a macro 
- If files are written back to the source tree, 

### Tracked issues

@unassigned

Completed
- [x] (🏁 2023-10-16) https://github.com/sourcegraph/sourcegraph/issues/54835 

@Strum355

- [ ] https://github.com/sourcegraph/sourcegraph/issues/58882 
  - [x] (🏁 2024-01-02) https://github.com/sourcegraph/sourcegraph/issues/54833 (PRs: ~[#59215](https://github.com/sourcegraph/sourcegraph/pull/59215)~)

Completed
- [x] (🏁 2024-01-02) https://github.com/sourcegraph/sourcegraph/issues/54833 (PRs: ~[#59215](https://github.com/sourcegraph/sourcegraph/pull/59215)~)

@burmudar

Completed
- [x] (🏁 2023-07-25) https://github.com/sourcegraph/sourcegraph/issues/54824 
- [x] (🏁 2023-07-25) https://github.com/sourcegraph/sourcegraph/issues/54834 
- [x] (🏁 2023-07-26) https://github.com/sourcegraph/sourcegraph/issues/54825 
- [x] (🏁 2023-07-31) https://github.com/sourcegraph/sourcegraph/issues/54826 
- [x] (🏁 2023-08-21) https://github.com/sourcegraph/sourcegraph/issues/54832 
- [x] (🏁 2023-09-11) https://github.com/sourcegraph/sourcegraph/issues/54820 

@davejrt

Completed
- [x] (🏁 2023-08-21) https://github.com/sourcegraph/sourcegraph/issues/54832 

@jhchabran

- [ ] https://github.com/sourcegraph/sourcegraph/issues/55122 
  - [x] https://github.com/sourcegraph/sourcegraph/issues/54821 

Completed
- [x] (🏁 2023-07-03) https://github.com/sourcegraph/sourcegraph/pull/54517 
- [x] (🏁 2023-07-03) https://github.com/sourcegraph/sourcegraph/pull/54538 
- [x] (🏁 2023-07-07) https://github.com/sourcegraph/sourcegraph/pull/54619 
- [x] (🏁 2023-07-10) https://github.com/sourcegraph/sourcegraph/pull/54685 
- [x] (🏁 2024-01-02) https://github.com/sourcegraph/sourcegraph/issues/54827

**Comment by jhchabran** [comment]
Done!
