### ISSUE TITLE
Upload archive to Sourcegraph

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#54659]
This represents the parent ticket that encompass all the steps needed to build an interface that allows users upload data from different sources into Sourcegraph.

For the initial work, we'll be focusing on `.zip` or `.tar` files.
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/54677
- [ ] https://github.com/sourcegraph/sourcegraph/issues/54678
- [ ] https://github.com/sourcegraph/sourcegraph/issues/54679
```
