### ISSUE TITLE
graphql: Add `user.hasCompletedPostSignup` & mutation to set it

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#54672]
Requirement for https://github.com/sourcegraph/sourcegraph/issues/54465 is that we keep track of whether a user has completed the post-signup flow.

First idea we discussed with @gitstart-sourcegraph is to use cookies, but they don't persist across browsers and to Cody app, so we came to conclusion to persist this backend-side. That's what this ticket is about.

(Until this ticket is implemented, @gitstart-sourcegraph will use cookies in #54465 and then switch to the GraphQL solution once it's ready).

### Tasks

- [ ] Add `completed_post_signup` to `users` table, `DEFAULT false`
- [ ] Set it to `true` for existing users that have a verified email
- [ ] Add field to the Go model `User`
- [ ] Load it in `database/users`
- [ ] Add `users.hasCompletedPostSignUp` to GraphQL schema
- [ ] Add resolver method to `UserResolver` to return the value
- [ ] Add GraphQL mutation `markUserAsCompletedPostSignup(user: ID!)` 
- [ ] Implement database layer method to set field to true
- [ ] Implement GraphQL resolver for mutation
