### ISSUE TITLE
Finalize 'External data sources in Cody' PRFAQ

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#54807]
Tracking issue for writing missing sections and finalizing the [PRFAQ](https://docs.google.com/document/d/15K-BV-xMHv_7Sw2SNq-tbzSHrKb54EUgsmtWqxhEbYc/edit#task=OhDb40PWG5lwOrAG), encompassing the sections outlined below, to provide a comprehensive and informative document. The goal is to have 80% done until **Friday**. 

---

```[tasklist]
### Tasks
- [x] Write the 'North Star' section of the PRFAQ, outlining the goals and objectives for implementing external data sources in Cody.
- [x] Draft an end-to-end visionary scope, including components for publishers, consumers, and onboarding.
- [x] Write the 'Scope' section of the PRFAQ. Defining the MVP (v0) outlined by the team.
- [x] ~Write sub-metrics to support each RFC.~ [Deprecated]
- [ ] Add milestones to the 'Scope' section
- [ ] Team review
- [ ] Designers review
- [ ] Remove 'TO-DOs' from the document
```

- [Figma board with illustrations.](https://www.figma.com/file/l19kryf7QGURKUzsH2yrO4/End-to-end-draft-of-Cody-plugins?type=design&node-id=0%3A1&mode=design&t=4pWfLa0djeYexo7d-1)

**Comment by almeidapaulooliveira** [comment]
The PRFAQ was canceled.  So, we're closing this issue for now.
