### ISSUE TITLE
DevInfra: Local Env Improvements Tracking issue

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#55019]
### Plan

  - `sg start` also fires up a structured log browser (loki?) 
    - Look into `logcli` https://grafana.com/docs/loki/latest/tools/logcli/
  - (stretch) `sg start` also always fire up the tracing?  
  - `sg start` shows panic very explictly
  - `sg start/run` uses Bazel for almost everything 
    - frontend being runnable this way depends on the work with ESBuild 
    - no target should depend on Bazel 
  - Install Comby through statically built release 
    - We may have to ship this one on our own (check the nix folks work)
  - Install universal-ctags through statically built release 
    - We may have to ship this one on our own (check the nix folks work)
  - Replace dev-private with a devx-service API call to download the latest config
  - Make asdf optional in `sg setup` 
  - Create a packaging mechanism so it's easy to just bump a tool version for the stateless agents
  - No CI job should require asdf 
  - `sg setup report` prints out all the local config, path, versions, of everything it depends on.
  - Install pre-commit (ask in `sg setup`) 
    - shellcheck
    - shfmt 
    - prettier

### Tracked issues

@unassigned

Completed
- [x] (🏁 2023-11-24) https://github.com/sourcegraph/sourcegraph/issues/56020 
- [x] (🏁 2024-03-13) https://github.com/sourcegraph/sourcegraph/issues/59157 
- [x] (🏁 2024-03-13) https://github.com/sourcegraph/sourcegraph/issues/59154 

@Strum355

- [ ] https://github.com/sourcegraph/sourcegraph/issues/59155 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59156 

Completed
- [x] (🏁 2023-12-11) https://github.com/sourcegraph/sourcegraph/issues/57307 
- [x] (🏁 2024-01-10) https://github.com/sourcegraph/sourcegraph/issues/59150 
- [x] (🏁 2024-02-05) https://github.com/sourcegraph/sourcegraph/issues/59153 

@burmudar

Completed
- [x] (🏁 2024-02-12) https://github.com/sourcegraph/sourcegraph/issues/59151 

@jamesmcnamara

- [ ] https://github.com/sourcegraph/sourcegraph/issues/59155 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59156

**Comment by jhchabran** [comment]
@mucles's plan

- run some discovery alone for another day, don't get blocked on anything, aiming for the mental model 
- plan a meeting to cover all the questions 
- next week, work on a plan.

**Comment by mucles** [comment]
Plan: [Local Env Improvements](https://docs.google.com/document/d/1cIS6HIWwAUsC9bj7xbrmt-2XFoj0jXG9yEFebTzNaUE/edit?usp=sharing)

**Comment by burmudar** [comment]
Good candidate for this tracking issue
- https://github.com/sourcegraph/devx-support/issues/413
