### ISSUE TITLE
DevInfra: Test Quarantining Tracking issue

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#55018]
### Plan

  - Introduce a mechanism to distinguish quarantined tests from the normal ones (tags?)
    - It must be easy to quarantine a test: `sg test quarantine [--remove] //my/target` perhaps? 
    - Create a GitHub issue on the fly?
  - Exclude quarantined tests from the main test jobs and run them in a separate job (soft-failing?)
  - Weekly report about the quarantined tests
    - Newly added tests 
    - Warning about upcoming disabled tests
    - Ping EM of tests target owners

### Tracked issues

@unassigned

Completed
- [x] (🏁 2023-12-06) https://github.com/sourcegraph/sourcegraph/issues/55728 
- [x] (🏁 2023-12-06) https://github.com/sourcegraph/sourcegraph/issues/55729 
- [x] (🏁 2023-12-06) https://github.com/sourcegraph/sourcegraph/issues/55730 

@burmudar

Completed
- [x] (🏁 2023-08-14) https://github.com/sourcegraph/sourcegraph/issues/55731 
- [x] (🏁 2023-08-15) https://github.com/sourcegraph/sourcegraph/issues/55727 

@jhchabran

Completed
- [x] (🏁 2023-08-14) https://github.com/sourcegraph/sourcegraph/issues/55731

**Comment by jhchabran** [comment]
@burmudar let's chat about this when you come back tomorrow !
