### ISSUE TITLE
DevInfra: CI Observability Tracking issue

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#55017]
### Plan

  = use gcp for everything 
  - Infra related metrics and alerts
    = Use opsgenie to trigger incidents
    - Agents: resource usage across time + alerts (disk, memory, cpu) 
    - Agents: queuing time + alerts
    - Agents: cost reporting
  - Build related alerts 
    - Agent / Bazel Crashes 
  - Flakiness reports
    - Test targets metrics on `main` 
    - Test targets metrics on everything else
    - Test targets metrics per team
      - Find a mechanism to assign test targets to a given team
  - Usage metrics 
    - Builds across time, on both main and other branches 
    - Speed ...
  - Logs are uploaded to GCP cloud logging 
  - Logs are easily searchable 
    - We want to be able to easily find out if a given error has been happening a lot or not
  - Detect if failure is caused by code or infra related
    - don't use cody yet, just hardcode the few various cases where it's known to be infra (like OOM) 
  - Automated Weekly report 
    - How many builds, flakes per team, quarantined tests, etc ...
  - Track (code insights?) usage of GithubAction across the entire org

### Tracked issues

@unassigned

- [x] https://github.com/sourcegraph/sourcegraph/issues/55750 
- [x] https://github.com/sourcegraph/sourcegraph/issues/55753 
- [x] https://github.com/sourcegraph/sourcegraph/issues/55754 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55755  🕵️
- [x] https://github.com/sourcegraph/sourcegraph/issues/55758 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55751
