### ISSUE TITLE
DevInfra: RFC 795 Tracking issue

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#55122]
### Plan

https://docs.google.com/document/d/11cw-7dAp93JmasITNSNCtx31xrQsNB1L2OoxVE6zrTc/edit

### Tracked issues

@unassigned

- [x] https://github.com/sourcegraph/sourcegraph/issues/59075 
- [x] https://github.com/sourcegraph/sourcegraph/issues/59417 

@burmudar

- [x] https://github.com/sourcegraph/sourcegraph/issues/59056 
- [x] https://github.com/sourcegraph/sourcegraph/issues/59069 
- [x] https://github.com/sourcegraph/sourcegraph/issues/59070 
- [x] https://github.com/sourcegraph/sourcegraph/issues/59071 
- [x] https://github.com/sourcegraph/sourcegraph/issues/59072 

Completed
- [x] (🏁 2023-12-29) https://github.com/sourcegraph/sourcegraph/issues/59067 
- [x] (🏁 2024-02-06) https://github.com/sourcegraph/sourcegraph/issues/59062 
- [x] (🏁 2024-02-06) https://github.com/sourcegraph/sourcegraph/issues/59065 
- [x] (🏁 2024-02-06) https://github.com/sourcegraph/sourcegraph/issues/59066 
- [x] (🏁 2024-02-06) https://github.com/sourcegraph/sourcegraph/issues/59061 
- [x] (🏁 2024-02-06) https://github.com/sourcegraph/sourcegraph/issues/59064 
- [x] (🏁 2024-02-12) https://github.com/sourcegraph/sourcegraph/issues/59063 

@jhchabran

- [x] https://github.com/sourcegraph/sourcegraph/issues/59056 
- [x] https://github.com/sourcegraph/sourcegraph/issues/59068 
- [x] https://github.com/sourcegraph/sourcegraph/issues/59069 
- [x] https://github.com/sourcegraph/sourcegraph/issues/59070 
- [x] https://github.com/sourcegraph/sourcegraph/issues/59071 
- [x] https://github.com/sourcegraph/sourcegraph/issues/59073 
- [x] https://github.com/sourcegraph/sourcegraph/issues/59076 
- [x] https://github.com/sourcegraph/sourcegraph/issues/59632 

Completed
- [x] (🏁 2023-08-09) https://github.com/sourcegraph/sourcegraph/pull/55645 
- [x] (🏁 2023-10-23) https://github.com/sourcegraph/sourcegraph/issues/56101 
- [x] (🏁 2023-12-06) https://github.com/sourcegraph/sourcegraph/issues/56107 
- [x] (🏁 2024-01-09) https://github.com/sourcegraph/sourcegraph/issues/54821 
- [x] (🏁 2024-02-06) https://github.com/sourcegraph/sourcegraph/issues/59062 
- [x] (🏁 2024-02-06) https://github.com/sourcegraph/sourcegraph/issues/59061 
- [x] (🏁 2024-02-06) https://github.com/sourcegraph/sourcegraph/issues/59064 
- [x] (🏁 2024-02-06) https://github.com/sourcegraph/sourcegraph/issues/56102 
- [x] (🏁 2024-02-06) https://github.com/sourcegraph/sourcegraph/issues/59077 
- [x] (🏁 2024-02-12) https://github.com/sourcegraph/sourcegraph/issues/59063 
- [x] (🏁 2024-03-11) https://github.com/sourcegraph/sourcegraph/issues/59074
