### ISSUE TITLE
Distributed Rate Limiters Tracking issue

### ISSUE THREAD

**Issue by varsanojidan** [sourcegraph/sourcegraph#55272]
## Plan

[PRFAQ](https://docs.google.com/document/d/13JFBvQmy5jmThgebH6GpuYa6IyOF90Ha-B6U4W9A-Mw/edit#heading=h.hm7u1pi4lv6t)
[RFC](https://docs.google.com/document/d/1UWqNJsQoTmqreNqQw8X0Rqe1_FbDhidqcWy0UPHfN_I/edit)

### Milestone 1: DB backed rate-limiters
- [x] https://github.com/sourcegraph/sourcegraph/issues/55273
- [x] https://github.com/sourcegraph/sourcegraph/issues/55274
- [x] https://github.com/sourcegraph/sourcegraph/issues/55373
- [x] https://github.com/sourcegraph/sourcegraph/issues/55276
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55277
- [x] https://github.com/sourcegraph/sourcegraph/issues/55435
- [x] https://github.com/sourcegraph/sourcegraph/issues/56026
- [x] https://github.com/sourcegraph/sourcegraph/issues/55436
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55278

### Milestone 2: API DB backed rate-limiters
- [x] https://github.com/sourcegraph/sourcegraph/issues/55280
- [x] https://github.com/sourcegraph/sourcegraph/issues/55281
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55282
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55279

### Milestone 3: Git DB backed rate-limiters
- [x] https://github.com/sourcegraph/sourcegraph/issues/55284
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55285
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55279
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55286

### Milestone 4: Code host UI
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55287
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55288

### (optional) Milestone 5: Remove github-proxy
- [x] https://github.com/sourcegraph/sourcegraph/issues/55289
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55290

/cc @sourcegraph/source
