### ISSUE TITLE
S: Tracking issue

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#55355]
#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](<https://en.wikipedia.org/wiki/Spike_(software_development)>)
- 🔒 Security issue
- 🙆 Stretch goal
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55374
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55515
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55539
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55540
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55541
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55575
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55576
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55577
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55578
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55579
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55615
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55736
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56254
```
