### ISSUE TITLE
Exhaustive Search Frontend Tracking

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#55382]
Tracks work for the UX part of exhaustive search.

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55804
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55805
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55707
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55708
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55709
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55711
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55712
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55713
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55706
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55807
```

**Comment by Piszmog** [comment]
Cancelling since these are tracked elsewhere
