### ISSUE TITLE
Exhaustive Search Backend Tracking

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#55383]
Tracks work related to the backend work for exhaustive search.

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55384
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55767
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55768
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55769
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55387
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55386
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55810
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55809
```

**Comment by Piszmog** [comment]
Cancelling since these are tracked elsewhere
