### ISSUE TITLE
git debuggability spikes

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#55514]
This is a tracking doc for fleshing out issues/RFC for features to be delivered in the scope of Git Debuggability project.

Git recording
- [x] #55599
	- [ ] [XS -- issue] “why did git command run?”
	- [ ] [XS -- issue] storing the output of commands + status (success/fail)
	- [ ] [M — issue] rerunning the command

Git visibility
- [ ] [M — issue/RFC?] “initiator” of a gitserver request (both HTTP/GRPC)
- [x] #55582
- [x] #55601
- [ ] [S — issue] on-demand repo purging
- [ ] [S — issue] Soft-deleted repo tracking
- [ ] [M — issue] UI Badge when repo cleanup is happening (caveat: making a gitserver janitor subprocess visible)

/cc @sourcegraph/source
