### ISSUE TITLE
Git Debuggability: Metadata recording (Tracking)

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#55599]
With the first MVP of Git Debuggability, we were able to achieve the following:

* Allow site admins to configure repositories they'll like to record commands for.
* Allow site admins to configure the max amount of records they'll like to store in Redis
* Allow site admins to configure commands they'll like to ignore from being recorded
* Implement a [UI](https://sourcegraph.sourcegraph.com/bitbucket.org/batch-change-buddy/jtest/-/settings/logs?activeTab=0) that allows site admins to view recorded commands

The above features gave us a starting point for understanding issues that'll help site admins and the technical support team investigate Gitserver-related issues. After scraping and scouring several slack threads and channels (e.g. #escalation-engineering, #discuss-customer-support, #discuss-source, etc.), we've been able to scope out the focus for the next couple of weeks: #55514.

This issue was created to tackle the common trend between the four questions below:

* Why did the command run?
* Did the command run successfully or did it fail?
* What's the output of the command?
* Can I rerun the command?

The answer can be found in the metadata for recorded commands. Currently when recording a command, [we do not save any information asides from the following](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/wrexec/recording_cmd.go?L20):

```go
type RecordedCommand struct {
	Start    time.Time `json:"start"`
	Duration float64   `json:"duration_seconds"`
	Args     []string  `json:"args"`
	Dir      string    `json:"dir"`
	Path     string    `json:"path"`
}
```

To be able to answer the questions asked above, we'll need to store more information (read **metadata**) about the recorded command. I'll break down my proposal to answer each of the questions below:

### Why did the command run?

There are several reasons we run a command in Gitserver, we could be performing janitor operations, performing a batch change, executing a search query etc. I'm proposing we extend the `RecordedCommand` struct to include the reason a recorded command is being executed. That way the caller of the recorder can specify what the reason is.

That way, we can modify methods like `WrapWithRepoName` to include the reason why a command is run.

```go
type WrapWithRepoNameArgs struct {
	repoName api.RepoName
	cmd *exec.Cmd
	reason string
}

// WrapWithRepoName constructs a new RecordingCommand based of an existing
// os/exec.Cmd, while also setting up the ShouldRecordFunc currently set in the
// factory. It uses repoName to create a new Redis list using it.
func (rf *RecordingCommandFactory) WrapWithRepoName(ctx context.Context, logger log.Logger, args WrapWithRepoNameArgs) *RecordingCmd {
	store := rcache.NewFIFOList(GetFIFOListKey(string(args.repoName)), rf.maxSize)
	return RecordingWrap(ctx, logger, rf.shouldRecord, store, args.cmd, args.reason)
}
```

##### Suggestion from Thorsten

We can utilize `context.Context` to figure out why a command ran. We can allow the caller to save the reason in context and we just access it via `ctx`.

### What's the output of the command?

We already have access to the `Cmd` when recording a command, we can access the `Cmd.Output` field to get the output of the command.

<img width="1029" alt="CleanShot 2023-08-07 at 04 15 45@2x" src="https://github.com/sourcegraph/sourcegraph/assets/25608335/287c8997-00d5-47ad-9d9c-65a818b1721b">

### Did the command run successfully or did it fail?

We can answer that using the `Success()` method available on `Cmd.ProcessState`. This method returns true if the command was executed successfully.

![CleanShot 2023-08-07 at 04 13 29@2x](https://github.com/sourcegraph/sourcegraph/assets/25608335/1480a714-99e8-4ede-a86d-4c0869beccfd)

```go
cmd.ProcessState.Success()
```

### Can I rerun the command?

A quick and dirty way to achieve this is by allowing the caller of the `RecordingWrap` method to specify if a command is re-runnable. 

##### What does being a command being re-runnable mean?

It means the `UI` (or frontend if you will) must know the exact endpoint to call, so as to initiate the command execution.

**TBD** after the spike for moving repo cloning and queuing to a db-backed worker.

Questions:
1. Should commands that have been executed successfully be re-runnable?

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56043
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56044
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56045
```

/cc @sourcegraph/source

**Comment by sashaostrikov** [comment]
> Questions:
>
> Should commands that have been executed successfully be re-runnable?

We basically have 2 types of commands: "read-only" and "writing". 

By read-only, I mean the commands which don't change the repo per se, commands like "rev-parse", "ls-files", "config --get", etc.
By "writing," I mean the commands which have an effect on the repo state, like "fetch", "gc", "clone", etc.

My initial thought was that we may want to rerun only "writing" commands because they have an effect. But after seconds thoughts, I think that sometimes rerunning "read-only" commands can also be useful when there are some search issues and some files aren't present. In such cases listing files one more time may help verify that the issue is fixed and necessary files are present (at the same time, we might as well rerun the search...).

This is not the answer to your question but some thoughts. I gravitate towards rerunning only "writing" commands in the beginning and then getting some feedback on that. It could be extended by one more setting, which will add a list of commands that shouldn't be rerunnable. This way we can protect ourselves from some more or less unique cases which customers can face.
