### ISSUE TITLE
git debuggability: move repo update queue to the database

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#55757]
Project [RFC](https://docs.google.com/document/d/18uhMwPIHRzxFiArMgpAED-VSYPquH2A5JjTm9b-OSmU/edit#heading=h.o7cq3ahlf8ka)

## Implementation plan
This project requires making changes to the critical gitserver and repo-updater infrastructure which is widely distributed across files and packages. 

This makes feature flagging difficult. 

Because of that, it is decided that Milestones will be opened as separate PRs but will be merged once the main changes are all in place (all except the last milestone).

## Milestones (marked as "done" when PR is opened)
- [ ] [DONE] #55761
- [ ] [DONE] #55762
- [ ] [DONE] #55763
- [ ] [DONE] #55966
- [x] #55764
- [x] #55765
- [x] #55766

## Additional work
- [ ] SHOULD BE DONE BEFORE TESTING AND MERGING: make id of `repo_update_jobs` BIGINT
- [ ] Log clone progress to the jobs table
- [ ] Think about keeping the `rpsLimiter` and using it as a budget in the worker. Also: maybe make the site config setting for it int->float (or interval)

## List of PRs in a chronological order
- M1: [database schema](https://github.com/sourcegraph/sourcegraph/pull/55817)
- M1: [using worker instead of RPC](https://github.com/sourcegraph/sourcegraph/pull/55886)
- M2: [remove gitserver in-memory clone queue](https://github.com/sourcegraph/sourcegraph/pull/55936)
- M3: [remove gitserver repoUpdateLocks / all fetches/clones go thru DB now](https://github.com/sourcegraph/sourcegraph/pull/56006)

/cc @sourcegraph/source

**Comment by mrnugget** [comment]
Closing this because we don't have the capacity to continue work on it at the moment. I closed all open PRs and related tickets.
