### ISSUE TITLE
release tool: Update patch release tracking issue to reflect current workflow

### ISSUE THREAD

**Issue by sanderginn** [sourcegraph/sourcegraph#55784]
The [patch release tracking issue template](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/dev/release/templates/patch_release_issue_template.md) contains steps that relate to the release process predating the release tool. Furthermore, there are some broken links and duplicate instructions.

The following changes need to be made:
- [x] [This block](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/dev/release/templates/patch_release_issue_template.md?L31-38) needs to be changed to a task item "Ensure that all backport PRs have been merged."
- [x] [This line](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/dev/release/templates/patch_release_issue_template.md?L40) can be removed entirely, as this build doesn't run until later in the process and the release captain is informed to verify that the build has passed at that step.
- [x] [This note](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/dev/release/templates/patch_release_issue_template.md?L49) can move up ahead of the release candidate step for added clarity.
- [x] [This line](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/dev/release/templates/patch_release_issue_template.md?L59) needs to
  - Update #ask-security to #discuss-security
  - Update the URL to create the Security  release approval issue to the [correct format](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=andreeleuterio%2C+evict%2C+willdollman%2C+mohammadualam&labels=release-blocker&projects=&template=security-release-approval.md&title=%24RELEASE_VERSION+Security+approval). If the `RELEASE_VERSION` URL parameter can be set to the right version automatically, that would be nice.
- [x] [This command](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/dev/release/templates/patch_release_issue_template.md?L97) needs to be removed entirely. This step is already performed as part of the checklist for the PR on the main repository, as it is required to get the final build to pass ([example PR](https://github.com/sourcegraph/sourcegraph/pull/55737)).
- [x] [This line](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/dev/release/templates/patch_release_issue_template.md?L86) contains a broken link in the batch change URL: the trailing `s` should be removed.
- [ ] The cherry-picking for https://github.com/sourcegraph/deploy-sourcegraph-helm can be automated (tracked in https://github.com/sourcegraph/sourcegraph/issues/55786). Once this is done, the step in the tracking issue can be updated to verify that the tag has been created like the other steps.
- [x] Add a step at the end of the process to open a PR that updates the changelog on `main`:
  - Moves the released changes into the version section
  - Adds a new section for the upcoming patch release, if this isn't the last planned patch release for this minor version

**Comment by sanderginn** [comment]
Added an item for cherry-picking of https://github.com/sourcegraph/deploy-sourcegraph-helm/.

**Comment by sanderginn** [comment]
Added an item for updating the changelog.
