### ISSUE TITLE
Webapp and Integrations: 3.9 tracking issue

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#5605]
**Search**
- [ ] [RFC 31: Literal search by default](https://docs.google.com/document/d/11avb0ixXHGmHrpUM1-1ijSxogWiYMXXH1SCM8ozvX-s/edit#heading=h.mwfvbon6sh88) @attfarhan 
- [ ] [RFC 14: Improve autocomplete suggestions](https://docs.google.com/document/d/1vSzZayA6p-znJ-7y8XrdlzluvZhboYytEuQ465_TTM4/edit#heading=h.17849ke90xv4) @hadrian-git @unknwon 

**Customer issues**
- [ ] Test browser extension GSuite deployment: https://github.com/sourcegraph/sourcegraph/issues/5604

**Integrations**
- [ ] Wrap up the Gitlab integration

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
Closing this tracking issue.

**Comment by tsenart** [comment]
Please update accordingly.
