### ISSUE TITLE
Q4 - Cody quality: Tracking issue

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#56163]
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56182
- [ ] https://github.com/sourcegraph/cody/issues/1041
- [ ] https://github.com/sourcegraph/cody/issues/1042
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56582
- [ ] https://github.com/sourcegraph/cody/issues/1038
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57670
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57790
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57842
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57841
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57843
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57845
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57844
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57850
```

**Comment by slimsag** [comment]
There are tracking issues (drafts) for all of this, but I'm not going to go through the pain of turning them into issues, linking them here, etc. They're in the `Customer: L` column

**Comment by cbart** [comment]
@slimsag I'd be happy to go ahead and turn the cody quality work items into issues and link them here. You mentioned `Customer: L` column. Where is that?

**Comment by slimsag** [comment]
Largely finished, so closing this out.
