### ISSUE TITLE
Q3 - LLM dispatch: Tracking issue

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#56161]
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56167
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56183
- [ ] https://github.com/sourcegraph/cody/issues/931
- [ ] https://github.com/sourcegraph/cody/issues/987
```

**Comment by cbart** [comment]
I'm going to close this for now since LLM dispatch is going for Q4 scope is pending leadership guidance as well as quality experiment results.
