### ISSUE TITLE
Q4 - Embeddings juggling: Tracking issue

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#56176]
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56179
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56180
- [ ] https://github.com/sourcegraph/cody/issues/1462
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58403
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58457
- [ ] https://github.com/sourcegraph/cody/pull/1856
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58609
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58431
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57726
```

**Comment by cbart** [comment]
I'm going to close this epic and all the related issues.
