### ISSUE TITLE
5.1.7 patch release tracking issue

### ISSUE THREAD

**Issue by jdpleiness** [sourcegraph/sourcegraph#56213]
# 5.1.7 patch release

This release is scheduled for **[Aug 24, 2023, 5:07 PM (UTC)](https://time.is/1707_24_Aug_2023_in_UTC?5.1.7%20release%20date)**.

> [!WARNING]
> To get your commits in `main` included in this patch release, add the `backport-5.1` to the PR to `main`.

## Setup

- [x] Ensure you have the latest version of the release tooling and configuration by checking out and updating `sourcegraph@main`.
- [x] Ensure release configuration in [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) on `main` has version 5.1.7 selected by using the command:

```shell
pnpm run release release:activate-release
```

## Prepare release

- [x] Ensure that all [backported PRs](https://github.com/sourcegraph/sourcegraph/pulls?q=is%3Apr+is%3Aopen+base%3A5.MINOR) have been merged.

Create and test the first release candidate:

> [!NOTE]
> Ensure that you've pulled both main and release branches before running this command.

- [x] Push a new release candidate tag. This command will automatically detect the appropriate release candidate number. This command can be executed as many times as required, and will increment the release candidate number for each subsequent build: :

  ```sh
  pnpm run release release:create-candidate
  ```

- [x] Ensure that the following Buildkite pipelines all pass for the `v5.1.7-rc.2` tag:
  - [x] [Sourcegraph pipeline](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=v5.1.7-rc.2)
- [x] File any failures and regressions in the pipelines as `release-blocker` issues and assign the appropriate teams.

> [!NOTE]
> You will need to re-check the above pipelines for any subsequent release candidates. You can see the Buildkite logs by tweaking the "branch" query parameter in the URLs to point to the desired release candidate. In general, the URL scheme looks like the following (replacing `N` in the URL): `https://buildkite.com/sourcegraph/sourcegraph/builds?branch=v5.1.7-rc.N`

Once there is a release candidate available:

- [x] Create a [Security release approval](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=andreeleuterio%2C+evict%2C+willdollman%2C+mohammadualam&labels=release-blocker&projects=&template=security-release-approval.md&title=5.1.7+Security+approval) issue and post a message in the [#discuss-security](https://sourcegraph.slack.com/archives/C1JH2BEHZ) channel tagging `@security-support`.

## Stage release

- [x] Verify the **5.1.7** section of [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) on the `main` is accurate.
- [x] Ensure security has approved the [Security release approval](https://github.com/sourcegraph/sourcegraph/issues?q=label%3Arelease-blocker+Security+approval+is%3Aopen) issue you created.
- [x] Promote a release candidate to the final release build. You will need to provide the tag of the release candidate which you would like to promote as an argument. To get a list of available release candidates, you can use:
  ```shell
  pnpm run release release:check-candidate
  ```
  To promote the candidate, use the command:
  ```sh
  pnpm run release release:promote-candidate <tag>
  ```
- [x] Ensure that the pipeline for the `v5.1.7` tag has passed: [Sourcegraph pipeline](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=v5.1.7)
- [x] Wait for the `v5.1.7` release Docker images to be available in [Docker Hub](https://hub.docker.com/r/sourcegraph/server/tags)
- [x] Open PRs that publish the new release and address any action items required to finalize draft PRs (track PR status via the [generated release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.7)):
  ```sh
  pnpm run release release:stage
  ```

## Finalize release

- [x] From the [release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.7), merge the release-publishing PRs created previously. Note: some PRs require certain actions performed before merging.
- [x] **After all the PRs are merged**, perform following checks/actions
  - For [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph)
    - [x] Ensure the [release tag](https://github.com/sourcegraph/deploy-sourcegraph/tags) has been created
  - For [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker)
    - [x] Ensure the [release tag](https://github.com/sourcegraph/deploy-sourcegraph-docker/tags) has been created
  - For [deploy-sourcegraph-helm](https://github.com/sourcegraph/deploy-sourcegraph-helm), also:
    - [x] Update the [changelog](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/CHANGELOG.md) to include changes from the patch
    - [x] Cherry-pick the release-publishing PR from the release branch into `main`
- [x] Announce that the release is live:
  ```sh
  pnpm run release release:announce
  ```

## Post-release

- [x] Close the release:

```shell
  pnpm run release release:close
```

- [x] Open a PR to update [`dev/release/release-config.jsonc`](https://github.com/sourcegraph/sourcegraph/edit/main/dev/release/release-config.jsonc) after the auto-generated changes above if any.
- [x] Update the [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) by opening and merging a PR into `main` (**not** the release branch), making the following changes:
  - [x] Move the released changes into the 5.1.7 version section
  - [x] Add a new section for the [upcoming patch release](https://handbook.sourcegraph.com/departments/engineering/dev/process/releases/#current-patch-schedule) if this is not the last planned patch release for version 5.1

> [!NOTE]
> If another patch release is requested after the release, ask that a [patch request issue](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=&labels=team%2Fdistribution&template=request_patch_release.md) be filled out and approved first.

**Comment by jdpleiness** [comment]
*Sourcegraph 5.1.7 has been published*

* Changelog: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#5-1-7
* GitHub release: https://github.com/sourcegraph/sourcegraph/releases/tag/v5.1.7
* Release batch change: https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.7

@jdpleiness: Please complete the post-release steps before closing this issue.

**Comment by jdpleiness** [comment]
All steps completed 🚀
