### ISSUE TITLE
JetBrains: support deep linking to avoid copy-pasting access token

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#56384]
Currently, users need to copy-paste an access token to authenticate. This is problematic because requires multiple manual steps to create and copy the access token increasing the risk that users don't manage to go through the onboarding steps. We should solve this problem by using a deep-linking approach similar to the VS Code extension. The new flow should be: open URL to authenticate with instance, open browser to click authorize, get redirected to IntelliJ and you are now authenticated.

* To implement this, we use `org.jetbrains.ide.RestService`. We should *not* use `OAuthCallbackHandlerBase` since we don't implement OAuth.
* It's not possible to provide an arbitrary callback URL. To support deep-linking into JetBrains, we need to add support for a dynamic port number in the redirect URL. I've consulted with #discuss-security (https://sourcegraph.slack.com/archives/C1JH2BEHZ/p1694005452464939) and we agreed to add a `LOCALHOST` redirect that should have custom design to highlight the risk of allowing a local redirect. The design can say it's OK to click authorize if you opened the page from the JetBrains plugin. 
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56498
```

**Comment by vdavid** [comment]
I've identified these subtasks:
- [ ] Hook up the "Sign in free with Sourcegraph.com" [button](https://github.com/sourcegraph/sourcegraph/pull/56633) to open a URL
  - [ ] Figure out what the URL should be. Something like `http://sourcegraph.com/user/settings/tokens/new/callback` but with an argument
  - [ ] Figure out how to find the correct local port in the IDE
  - [ ] Test if the button opens the correct URL
- [ ] Adjust back-end to accept requests from JetBrains
  - [ ] Find the back-end code that handles this
  - [ ] Update back-end code to accept the port argument
  - [ ] Make sure it only accepts numbers. If a non-number arrives, just return 400 Bad Request
  - [ ] Test that it responds to valid and invalid requests correctly
- [ ] Update our ["Authorize" page](https://github.com/sourcegraph/sourcegraph/issues/56388) and add support for localhost redirect
  - [ ] Find the back-end code that accepts/generates redirect URLs: `http://localhost:$JETBRAINS_PORT_NUMBER/api/sourcegraph/$TOKEN`
  - [ ] Update backend code to generate `localhost:port` URLs
  - [ ] Update copy on this page to something like "You are authorizing for a JetBrains IDE" and "we are redirecting to localhost"
  - [ ] Test if the page renders and redirects correctly
- [ ] Create `org.jetbrains.ide.RestService` to handle deep links
  - [ ] Create service
  - [ ] Save token received through deep link
  - [ ] Handle errors: if invalid deep link arrives, just silently ignore and log it.
  - [ ] Test if it correctly receives and handles valid requests, and throws away invalid ones
