### ISSUE TITLE
JetBrains: followup for autocomplete language setting

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#56466]
```[tasklist]
### Tasks
- [x] JetBrains: Allow manual triggering (alt-backslash) even for disabled languages
- [x] JetBrains: Increase height of languages table in settings UI
- [x] JetBrains: Hide languages table when "Automatically trigger completions" is disabled
- [x] JetBrains: add button to status bar to enable/disable autocomplete for language
```
