### ISSUE TITLE
Distribution 3.9 tracking issue

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5737]
- Stephen: 100% focused on critical customer issues
    - [ ] syntax highlighter needs better HA implementation sourcegraph/sourcegraph#5406
    - [ ] Services: Add a generic form of network throttling (part 1) #5736
    - [ ] Some repositories stuck in "Empty repository" state sourcegraph/sourcegraph#5684
    - [ ] Better logging around GraphQL API usage sourcegraph/sourcegraph#5706
- Uwe
    - [ ] alert system and issues related to alerts #5369 
    - [ ] dashboard for cluster-internal network activity with alerting
    - [ ] generate dashboards with jsonnet integrated into build system
    - [ ] continue implementing roadmap from #4260
    - [ ] track down which of the legacy dashboards still make sense
- Beyang
    - TODO
- Geoffrey
    - TODO

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
Closing this 3.9 tracking issue. Please update accordingly.
