### ISSUE TITLE
Source tracking issue: Licensing

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#57456]
## Work

Define and implement license expiration behavior, Ensure success of telemetry-export project

#### License expiration
**Goal**: When a license expires the system should continue functioning, but users should be signed out and only one admin should be able to sign in
- [x] Sourcegraph features shouldn't get disabled when a license expires. Sourcegraph should continue functioning **2d**
  - Looking for references of [this function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/license/license.go?L51) is a good start
- [x] Sign out all user sessions when a license is expired **3d**
  - License expiration isn't quite a trigger we can react to, so the check should probably happen on user session validation, with the session being deleted if the license is expired
- [x] Prevent user sign-in when a license is expired **1d**
  - Similar to above, the sign-out and prevent-sign-in checks will probably be in the same place and happen together
- [x] Only allow admins to sign in **1d**
- [x] Clearly document license expiration behaviour, as well as the events leading up to license expiration **2d**
  - See [this doc](https://docs.google.com/document/d/12kW66xukqbZ1w6s8E2SpYYcYExzKiCLXJjzQhmS8D1w/edit#heading=h.9hwf3thj13oe) as well 
- [x] Communicate upcoming changes with technical support and make sure that everyone knows where to find answers

#### Telemetry-export project
- [x] Review duplicate site-ID + license key behaviour **1d**
  - Action items here might be a tiny bit unclear. Do we think the existing system is reliable? Can we make it more robust?
- [x] Routinely check if we're receiving duplicate pings for the same license key **3d**
- [x] Establish clear communication channels when duplicate license keys are detected

#### Open questions
- What happens to user access tokens? Can we prevent their use while a license is expired? Would it have any unintended consequences?

/cc @sourcegraph/source

**Comment by kalanchan** [comment]
hello testing

**Comment by pjlast** [comment]
@kalanchan here's the last few things to do for licensing in [this](https://sourcegraph.slack.com/archives/C03K05FCRFH/p1706863222750199) slack message from @eseliger , which includes some test plans.

- Get [the PR](https://github.com/sourcegraph/sourcegraph/pull/60046) merged and backported that introduces new plans, and deprecates old ones
- Get the the [license management UI changes](https://github.com/sourcegraph/sourcegraph/pull/60051) reviewed and tested
- Get the PR that does the scary thing merged: [Remove Cody from old enterprise plans](https://github.com/sourcegraph/sourcegraph/pull/60052)
- Roll the above two out to S2, dotcom, make sure Cody still works (those have licenses already that should make this smooth, worst case, the new license management will be in place now)
- Finish [document about licensing changes](https://docs.google.com/document/d/1hty_2k6SIW_b1tN_YtTCH-UXg0fGX233ZnzBm_6RltM/edit#heading=h.st56ccy4t6yl), post it broadly and make sure people are aware of it
- Request the sg03 cloud instance, generate a Code Search Only, Cody Only, and Code AI Enterprise plan license for use on that instance, hand off to Taiyab and Bolaji for verifying their changes
- Wait for any feedback on the new license management UI, or any last-minute miscommunications

Things like license expiration behaviour has already been tested (and demoed in demo day), and license anomalies and expiration notifications are already live and running for a while now (in #licenses and #license-anomalies respectively).

**Comment by pjlast** [comment]
# QA Test Plan

## Summary

Reworked various aspects of Sourcegraph licensing:
- License expiration behaviour
  - Sourcegraph continues to function but all non-admin users are signed out of Sourcegraph
- License notifications are sent to #licenses and #license-anomalies
- New license plans are implemented for 5.3

## Test Plan

- [ ]  We can create new licenses with the new license creation page
- [ ]  When a license expires, regular users are signed out of Sourcegraph and only admins can sign in
- [ ]  Notifications are being sent to #licenses and #license-anomalies respectively


## QA Checklist

1. **Have you made any infra related changes to environment variables, new services, or deployment methods that could affect customers?**
   - [ ] Yes - I've informed [#team-cloud](https://sourcegraph.slack.com/archives/C03LCPCT3SP) and [#team-delivery](https://sourcegraph.slack.com/archives/C02VDNKBWDU) of the changes.
   - [ ] Yes - Changelog or documentation has been updated, this includes changes to defaults and site config flags.
   - [ ] No

    If your change is non-trivial, please review the [Cloud Launch](https://handbook.sourcegraph.com/departments/cloud/launch-process/#questionnaire) process. 

    If you've made changes to documentation, please link them in the comments below.  
    
    Comments:

2. **Which environments have the changes been tested on?**
   - [ ] rctest.sourcegraph.com
   - [ ] sourcegraph.sourcegraph.com
   - [ ] sourcegraph.com
   - [ ] cody-dev.sgdev.dev (running based off 5.2 release branch)
   - [ ] scaletesting.sgdev.org
   - [ ] other
  
    If other, please specify:

3. **Experimental features have been marked and behind a feature flag?**
   - [ ] Yes
   - [ ] No
   - [ ] N/A

    If no, please specify why:

4. **Has telemetry been added as part of the product requirements?**
   - [ ] Yes
   - [ ] No
   - [ ] N/A

5. **Completed entry to release post.**
   - [ ] Yes
   - [ ] No
   - [ ] N/A

6. **Is a feature flagged in a way when turns the feature off, it behaves as-if the feature does not exist?**
   - [ ] Yes
   - [ ] No
   - [ ] N/A

    If no, please specify why:

7. **A [CHANGELOG entry](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) has been added for the feature/change?**
   - [ ] Yes
   - [ ] No
   - [ ] N/A

8. **Please provide any additional testing you've done that has not been covered above:**


---- 

Tech Lead/DRI sign off: @eseliger / @pjlast
