### ISSUE TITLE
Source tracking issue: Perforce stability & bugfixing

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#57458]
## Goal

Fix bugs that make the existing Perforce support better, and also help with #57457 (stop the bleeding) to reduce support load and customer friction.
Also, reduce the bus factor for Perforce where only Peter knows about it.

**NON goal** is to add new functionality to Perforce: Streams, better changelist support, making Perforce feel more native. In this iteration, Perforce will remain a git repository that gitserver manages and is created using p4-fusion.

## Impact

The team does not see Perforce as a major risk anymore, is proficient with it and the tools we use around it, and customers no longer see frequent issues while exporting their depot into the Sourcegraph git repo.

## Milestones/Tasks

Note: There is no definitive set of individual tasks yet, I want to propose that as we work on the clear issues from the list, we will most likely discover other things and should just keep working on these until we feel better about the state of perforce in general, applying some timeboxing to it to make sure other topics besides Perforce get attention as well.

**Our general planned timebox for this is 5 weeks** stop the bleeding work that _also_ benefits Perforce is not counted here.

### We trust the p4-fusion Perforce to Git export **24d + 5d**
_We become ~experts in the p4-fusion codebase and have deep understanding of how it works_

- Import a bunch of repositories into a helix server and make sure they all clone without issues **3d**
- Fix the segfault issue in p4-fusion 1.13 **2d**
- Fix the p4-fusion hanging issue **2d**
- #36135 **1d**
- ~#50403 **4d**~
- #57475 **2d**
- E2E test suite that clones depots, checks syncing works, retrieves files, syncs permissions **10d**
- ~Stretch goal: The p4 changelist mapper works and doesn't cause issues with the DB at scale **5d**~
  - Try: Import the linux kernel repo into perforce, that's 1M changelists. Not clear if that scale will work though.

### Perforce permission syncing generally works and doesn't feel weird **5d**

- Perforce accounts should show under external accounts **3d**
- #57585 **2d** (timebox)

### Perforce setup is not confusing **11d**

  - Make p4-fusion the default and the only supported export method #46501 **2d**
    - This might require us to migrate existing git-p4 repos **Xd**
  - We understand the resource requirements of p4-fusion **3d**
  - #54189 **1d**
  - #48636 **1d**
  - #57625 **2d**
  - #57638 **1d**
  - #57628 **1d**

### We address Perforce customer-reported bugs **9d**

  - #52260 **3d** (timebox)
  - #56901 **3d** (timebox)
  - ~#56978 **3d** (timebox)~

### We have expertise in Perforce terminology, operation, and debugging **10d**

  - Write down internal knowledge base on Perforce models around depots, permissions, and so forth **5d**
  - We regularly pair on Perforce issues and write down findings and debugging guides
  - p4-fusion is part of the dev env #57307 **1.5d**
  - We use SSL in our test infra **2d**

/cc @sourcegraph/source

**Comment by eseliger** [comment]
Planned work done, timebox of 5 weeks has been exceeded by about 2 weeks, approximately. But we really needed to dig into the p4-fusion, or abandon it.

QA plan to follow.

**Comment by eseliger** [comment]
# QA Test Plan

## Summary

Perforce support has gotten significantly more stable, by fixing the most common bugs, resource hog problems, and by uplevelling the team on their understanding of Perforce, so we can provide some level of support.

## Test Plan

**Functional testing:** Verify that the application functions as expected and meets the requirements. This will include testing of user interfaces, inputs, outputs, and all other functionalities.

We run a perforce code host connection on S2 to verify that no issues occur while keeping our depots in sync.

**Integration testing:** Verify that all the components of the application integrate and work together seamlessly.

We wrote a ton of tests to verify that p4-fusion behaves correctly against a perforce server. The test suites test for various common issues with C++ programs, including memory leaks, and we verify the structure of the emitted git data to be 100% correct.

**Performance testing:** Verify that the application performs efficiently and effectively under different loads and stress levels.

We ran various comparison tests against the old version, and see improvement somewhere between 5 and 10x at least, with memory reduction of up to inf, depending on how large your depot is (ie. we no longer keep it all in memory).

## Cody Checklist (If applicable)

1. **Does your feature respect the global [Cody feature flag](https://docs.google.com/document/d/1syg64zhUapagA1c8YVO7v4_EUI_m583C39UeRNcCJ3k/edit#heading=h.tpnhxt0fhs3)? Default experience is OFF for Self Hosted**
   - [ ] Yes
   - [ ] No
   - [x] N/A
 
2. **Have you backtested prompts and questions that have worked before? IE - Can you summarize the following file?**
   - [ ] Yes
   - [ ] No
   - [x] N/A

   If yes, please specify your test prompts and the response:

3. **Have you made any client-side changes to Cody? To prevent breakages, please ensure your changes have been tested on other Cody platforms (Web, App, etc)**
   - [ ] Yes, I've tested my changes across the different applicable Cody platforms
   - [ ] No
   - [x] N/A
   
4. **Which clients have your changes been tested on?**
   - [ ] VS Code
   - [ ] Cody App
   - [ ] Sourcegraph Web
   - [ ] IntelliJ
   - [ ] Other
 
   If other, please specify: 
   
 5.  **Please provide any additional testing you've done that has not been covered above:**


 **If you notice any bugs related to the setup experience or Cody in general please raise them in [#team-cody](https://sourcegraph.slack.com/archives/C04NPH6SZMW) and tag `@teamcody` & `@design-team`.**



## QA Checklist

1. **Have you made any infra related changes to environment variables, new services, or deployment methods that could affect customers?**
   - [ ] Yes - I've informed [#team-cloud](https://sourcegraph.slack.com/archives/C03LCPCT3SP) and [#team-delivery](https://sourcegraph.slack.com/archives/C02VDNKBWDU) of the changes.
   - [ ] Yes - Changelog or documentation has been updated, this includes changes to defaults and site config flags.
   - [x] No

    If your change is non-trivial, please review the [Cloud Launch](https://handbook.sourcegraph.com/departments/cloud/launch-process/#questionnaire) process. 

    If you've made changes to documentation, please link them in the comments below.  
    
    Comments:

2. **Which environments have the changes been tested on?**
   - [ ] rctest.sourcegraph.com
   - [x] sourcegraph.sourcegraph.com
   - [ ] sourcegraph.com
   - [ ] cody-dev.sgdev.dev (running based off 5.2 release branch)
   - [ ] scaletesting.sgdev.org
   - [ ] other
  
    If other, please specify:

3. **Experimental features have been marked and behind a feature flag?**
   - [ ] Yes
   - [ ] No
   - [x] N/A

    If no, please specify why:

4. **Has telemetry been added as part of the product requirements?**
   - [ ] Yes
   - [ ] No
   - [x] N/A

5. **Completed entry to release post.**
   - [ ] Yes
   - [ ] No
   - [x] N/A

6. **Is a feature flagged in a way when turns the feature off, it behaves as-if the feature does not exist?**
   - [ ] Yes
   - [ ] No
   - [x] N/A

    If no, please specify why:

7. **A [CHANGELOG entry](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) has been added for the feature/change?**
   - [ ] Yes
   - [ ] No
   - [x] N/A

8. **Please provide any additional testing you've done that has not been covered above:**


---- 

Tech Lead/DRI sign off: @eseliger
