### ISSUE TITLE
Q4 - Self-hosted embeddings: Tracking issue

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#57470]
Working on a self-hosted embeddings service delivered for a customer. The work is scoped to a release pipeline and setting up a development/testing environment.
```[tasklist]
### Tasks
- [ ] Release step that publishes embeddings in artifact repository.
- [ ] Embeddings smoke test in release pipeline.
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57618
- [ ] Customer size load on development environment
- [ ] Tracking issue: robust embeddings compute and search
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57796
```

**Comment by cbart** [comment]
Got AWS access ([here](https://sourcegraph.slack.com/archives/C01CSS3TC75/p1696853190695469?thread_ts=1696852833.501569&cid=C01CSS3TC75)) and figuring out how to use Terraform :/

**Comment by rafax** [comment]
We have 3.5/5 items outlined above @cbart  - we have:
- publishing [images](https://console.cloud.google.com/gcr/images/sourcegraph-dev/US/embeddings-api)
- (basic) smoke [test](https://github.com/sourcegraph/embeddings-api/blob/main/api_test.py#L24)
- [test environment in GCP](https://sourcegraph.slack.com/archives/C05AQFZGBB5/p1694099117033469?thread_ts=1693956307.401439&cid=C05AQFZGBB5) (missing AWS so 0.5)
- a [perf-client ](https://github.com/sourcegraph/embeddings-api/blob/main/perf-client/README.md)that can generate load mirroring embedding requests sent by a Sourcegraph instance (largest chunk data I have is for a 2GB repo)

**Comment by cbart** [comment]
Thank you!

My goal here was slightly different (and I did not frame it well).

- Publishing images that customer can fetch (sourcegraph-dev is private as far as I am aware)
- Smoke test including Cody end-to-end (similar what the aim for quality testing is)
- test environment in AWS (should have specified that)
