### ISSUE TITLE
Source gRPC 6.0 Plan

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#57554]
# Educate our team & tell them how to use gRPC **10d**

> Develop training guides (documentation / videos) that cover the following:
> 
> - [x] Basics of gRPC / protobuf
> - [x] A tutorial that creates an example service in Go that covers all RPC types (see [https://grpc.io/docs/what-is-grpc/core-concepts/#overview](https://grpc.io/docs/what-is-grpc/core-concepts/#overview))
> - [x] gRPC best practices
>     - [https://grpc.io/docs/guides/performance/](https://grpc.io/docs/guides/performance/)
>     - [https://cloud.google.com/apis/design](https://cloud.google.com/apis/design)
>     - [https://protobuf.dev/programming-guides/](https://protobuf.dev/programming-guides/)
> - [x] Educate about known (recurring) classes of issues
>     - [non-UTF-8](https://github.com/sourcegraph/sourcegraph/issues/52181) strings
>         - in Protobuf, all `string` type fields must be utf-8 encoded, but the Go `string` type doesn’t enforce this
>         - You have to be aware that you need to validate the encoding of your strings if they’re derived from user input
>             - Teach people how to sanitize strings
>                 - Ex: [https://github.com/sourcegraph/sourcegraph/pull/55369](https://github.com/sourcegraph/sourcegraph/pull/55369)
>         - If your string can’t be forced to use uft-8 encoding (sanitization isn’t possible for whatever reason), teach people to use the `bytes` type instead
>         - Teach people about the existence of the internal error reporter that surfaces this issue: [https://handbook.sourcegraph.com/departments/engineering/dev/tools/grpc/#grpc-internal-errors-metrics](https://handbook.sourcegraph.com/departments/engineering/dev/tools/grpc/#grpc-internal-errors-metrics)
>     - message size:
>         - gRPC has a notion of a maxmium message size to protect clients / servers against unexpectedly large payloads.
>             - [https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0#grpc-services-and-large-binary-payloads](https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0#grpc-services-and-large-binary-payloads)
>             - Consider your endpoints, and the payloads they’re capable of sending (ex. `symbols` service responses sending ~1 gigabyte worth of code intel data, zoekt sending hundreds of megabytes of search results) and consider:
>                 - restructuring your endpoints in such a way that the response size is cut down
>                 - switching to a [streaming-style RPC](https://grpc.io/docs/what-is-grpc/core-concepts/#server-streaming-rpc) to send i
>                     - consider changing
>     - [x] Write documentation about helpful utilities that we’ve written for gRPC
>         - Standardized gRPC monitoring for new services
>         - Connection pooling: [https://github.com/sourcegraph/sourcegraph/blob/main/internal/grpc/defaults/cache.go#L30](https://github.com/sourcegraph/sourcegraph/blob/main/internal/grpc/defaults/cache.go#L30)
>         - Utilities to convert gRPC streams with binary payloads to io.Reader/Writers: [https://github.com/sourcegraph/sourcegraph/blob/main/internal/grpc/streamio/streamio.go](https://github.com/sourcegraph/sourcegraph/blob/main/internal/grpc/streamio/streamio.go)
>         - Utilities to help with splitting larger messages into a stream of smaller ones: [https://github.com/sourcegraph/sourcegraph/blob/main/internal/grpc/chunk/chunker.go](https://github.com/sourcegraph/sourcegraph/blob/main/internal/grpc/chunk/chunker.go)

- [x] This (^)  is solved with this existence of https://github.com/sourcegraph/sourcegraph/blob/main/internal/grpc/example/doc.go. 

- [ ] How to debug GRPC (~2d)  (stretch)
    - Teach people how to use Wireshark (and import the protobuf schemas so that Wireshark understands how to debug)

# Rollout gRPC-powered site configuration **5d**

- [x] create a new alert type for the conf package that can let us know if the service hasn’t been able to fetch the site configuration for a few minutes
    - Should we make the service panic and crash instead? Many people might not configure notifications from the alerts in our built in monitoring.
        - On startup, many of our services will already get killed by Kubernetes if they can’t fetch the site configuration (since they’ll fail the readiness check).
        
- [x] roll out deploy gRPC powered site configuration to all managed instances over the course of a month: see [https://docs.google.com/document/d/1rZaH10vJbk5z-8XyIuH9ib3zy5QTJTwire68wXA4Zyg/edit](https://docs.google.com/document/d/1rZaH10vJbk5z-8XyIuH9ib3zy5QTJTwire68wXA4Zyg/edit)
	- Done. https://sourcegraph.slack.com/archives/C03JR7S7KRP/p1706729521724139?thread_ts=1703287403.782489&cid=C03JR7S7KRP

# Cleanup old REST code for the 6.0 release **15d**

> - [x] On `main` , enforce that gRPC is used at all times by making [conf.IsGRPCEnabled()](https://github.com/sourcegraph/sourcegraph/blob/40b3b333c809ef8f1a9923ca9c2f6630c1ea7eb0/internal/conf/grpc.go#L11-L19) *always* return `true` .
>     - This means that the “REST” branches of all the “use GRPC or REST” checks in our clients are now dead code - leaving only GRPC remaining for the upcoming `6.0` release.
>     - This change must ******not****** be back-ported to the `5.2.X` release branch. We still need to be able to toggle between REST / GRPC in Sourcebraph `5.2`
> - [x] On `main`, note all usages of REST code that we need to delete after the last patch release . As a starting point:
>     - [x] Client code:
>         - Look at [all usages of conf.IsGRPCEnabled()](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/conf/grpc.go?L11:6-11:19#tab=references)
>             - Go through, and recursively delete all code in the “use REST” branch. This includes
>                 - All functions that now don’t have more references
>                 - all referenced interfaces that only existed for the purpose of supporting the REST fallback
>     - [x] Server code:
>         - Delete all the corresponding REST code from all of the server structs / interfaces that implement the REST implementations of all the gRPC RPC methods
>             - recursively delete dead functions, interfaces, etc.
>             - Can find all GRPC servers with this sourcegraph search: [https://sourcegraph.com/search?q=context:global+repo:^github\.com/sourcegraph/sourcegraph%24+mustEmbedUnimplemented&patternType=standard&sm=1&groupBy=path](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+mustEmbedUnimplemented&patternType=standard&sm=1&groupBy=path)
>     - [x] Clean up tests: now that the REST implementation is entirely gone, a fair number of test cases that relied on the REST case won’t compile / fail entirely now.
>         - Example: [https://github.com/sourcegraph/sourcegraph/blob/f17dd8bd03cb53cd4142a1012e1ae7c544e31f46/internal/gitserver/client_test.go#L849-L898](https://github.com/sourcegraph/sourcegraph/blob/f17dd8bd03cb53cd4142a1012e1ae7c544e31f46/internal/gitserver/client_test.go#L849-L898)

   - [x] Done: https://github.com/sourcegraph/sourcegraph/pull/59093

- [x] In progress after above is completed. Write educational materials so that our engineering team follows the REST API deprecation policy.
   - done in https://sourcegraph.slack.com/archives/C0EPTDE9L/p1706039695856019
  

# Extra implement gRPC retry support

- [x] In response to a [customer issue](https://github.com/sourcegraph/customer/issues/2598#issuecomment-1904913677), we've added support for automatically retrying certain RPC calls if we suspect that there are connection issues. The HTTP client that we were using has automatic retry support, so this change brings our gRPC implementation to parity. 
   - Done. See the following PRs:
      - Implementing the core retry logic:
        - https://github.com/sourcegraph/sourcegraph/pull/59095
        - https://github.com/sourcegraph/sourcegraph/pull/59140
        - https://github.com/sourcegraph/sourcegraph/pull/59145
        - https://github.com/sourcegraph/sourcegraph/pull/59146
        - https://github.com/sourcegraph/sourcegraph/pull/59191
      
      - Service-specific PRs enabling retries for certain methods (with caveats):
        - https://github.com/sourcegraph/sourcegraph/pull/59107
        - https://github.com/sourcegraph/sourcegraph/pull/59110
        - https://github.com/sourcegraph/sourcegraph/pull/59111
        - https://github.com/sourcegraph/sourcegraph/pull/59130
        - https://github.com/sourcegraph/sourcegraph/pull/59133
        - https://github.com/sourcegraph/sourcegraph/pull/59136

**Comment by ggilmore** [comment]
All tasks above have been completed.
