### ISSUE TITLE
Q4 - Guardrails: Tracking issue

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#57727]
[PRD: Guardrails](https://docs.google.com/document/u/0/d/1c3CLC7ICDaG63NOWjO6zWm-UElwuXkFrKbCKTw-7H6Q/edit)

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57728
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58149
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57922
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59244
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59262
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59427
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58993
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59261
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59694
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59277
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59860
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59335
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59294
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59576
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59701
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59720
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59336
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59337
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59996
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59824
```

```[tasklist]
### P1-Feb-release, non-blocking, up for grabs
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59776
```

Remaining tasks moved to follow-up May-iteration epic: [#60513](https://github.com/sourcegraph/sourcegraph/issues/60513)

**Comment by cbart** [comment]
Tentatively assigning the work for after Stephen is back from OOO

**Comment by cbart** [comment]
Note: Relevant comparison of guardrail features https://sourcegraph.slack.com/archives/C0C324C91/p1698258585704789

**Comment by cbart** [comment]
Some notes from 1:1 with @philipp-spiess who took the time to explain to me how we can go about implementing guardrails UI in VS Code:

    Implement a guardrails provider somewhere around [main](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fcody.git&branch=HEAD&file=vscode%2Fsrc%2Fmain.ts&editor=VSCode&version=2.2.16&start_row=207&start_col=9&end_row=207&end_col=9),
    the provider manages search queries for guardrails with a cache
    extend the [messages api](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fcody.git&branch=HEAD&file=vscode%2Fsrc%2Fchat%2Fprotocol.ts&editor=VSCode&version=2.2.16&start_row=103&start_col=34&end_row=103&end_col=34)
    extend App to [act on guardrails messages](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fcody.git&branch=HEAD&file=vscode%2Fwebviews%2FApp.tsx&editor=VSCode&version=2.2.16&start_row=74&start_col=17&end_row=74&end_col=17) from extension

**Comment by cbart** [comment]
One task to be finished this week, the rest moved to a May epic: https://github.com/sourcegraph/sourcegraph/issues/60513
