### ISSUE TITLE
Search Suite — Search results Tracking issue

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#57803]
[Main RFC](https://docs.google.com/document/d/1RZUDa7heWuVHgUj_G9xXuWxzyA43pp3MJWSYz1vyCr4/edit)

### Plan
The plan is basically to improve search result page and increase our DAU, the search result page is main entry point for most of our search flows so this is very important to have the best UI/UX there. Some issues require design and product effort. 

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/pull/59178
- [ ] https://github.com/sourcegraph/sourcegraph/pull/59084
- [ ] https://github.com/sourcegraph/sourcegraph/pull/59015
- [ ] https://github.com/sourcegraph/sourcegraph/pull/58966
- [ ] https://github.com/sourcegraph/sourcegraph/pull/58612
- [ ] https://github.com/sourcegraph/sourcegraph/pull/58311
- [ ] https://github.com/sourcegraph/sourcegraph/pull/58164
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59446
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59385
- [ ] https://github.com/sourcegraph/sourcegraph/pull/58979
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59449
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59450
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59451
- [x] Design issue https://github.com/sourcegraph/sourcegraph/issues/58371
```

**Comment by vovakulikov** [comment]
# QA Test Plan

## Summary
The new search page got a lot of changes, most noticeable and important one
- New Search results filters
- New Search result look (slim search results, better integration with new search navigation)
- New Search result file preview panel 
- Performance improvements (includes cache over filters, show unhighlighted code while we fetch highlighted chunks)

## Test Plan





**Functional testing:** Verify that the application functions as expected and meets the requirements. This will include testing of user interfaces, inputs, outputs, and all other functionalities.

- **Filters**
   - [ ] Check that filters panel shows right set of filters (for instance query with type:repository doesn't produce any repo or lang filters in the panel)
   - [ ] Check that as you add/remove filters you see relevant results in the search results blocks, this one is very important to check since we had an issue about but we couldn't reproduce this problem since we got a report about this (issue https://github.com/sourcegraph/sourcegraph/issues/59594)
   - [ ] Check that whenever you go from filters to filters you can always go back in browser history and see your previously set of filters
   - [ ] Check that as you go through different filter types (like Code, Repositories, File, ...etc) you always see only relevant to this type filters (for example when you select lang filter in the File type when you go to the Repository you should see no lang type since this filter doesn't match with Repository type)
   - [ ] Check that `count:all` filter shows up only when search result limit hit
   - [ ] Check that you can see skeleton loading state disappears when filters are loaded
   - [ ] Check that you we don't trigger filters loading if you go back to the filters set when you had before at some point of your session on the search result page
   - [ ] Check that filters persist as you change they query (if you change `type:` filter some filters may disappear if they don't match with new value of the type: filter (see points above about it)
   - [ ] Check that "Move filters to the query" button works properly if you have some filters selected
   
- **File preview panel**   
   - [ ] Check that you can open file preview panel by clicking Preview button in the header of the search result match 
   - [ ] Check that file preview loads correct file and has all matches for this file
   - [ ] Check that file preview scrolls to the first search match automatically as you open it
   - [ ] Check that file preview panel works properly when you click next/prev button in the header
   - [ ] Check that you can close file preview
   

**Integration testing:** Verify that all the components of the application integrate and work together seamlessly.

- [ ] Check that you can share the link with filters and filters will be restored in the new browser windows by URL query param 
- [ ] Check that you can see that aggregation feature respects filters in the URL 
- [ ] Check that you can create an insight/batch change/monitoring and query will have filters in it
- [ ] Check that new integration has a proper toggle UI in the user menu and changes looks of the global navigation as it should 
- [ ] Check that new navigation UI has all recently added licenses updates (it doesn't show anything that it shouldn't if user doesn't have proper set of license rights)

**Performance testing:** Verify that the application performs efficiently and effectively under different loads and stress levels.

- [ ] Check that you can see unhighlighted search matches result first and highlighted after as they load

**Security testing:** Verify that the application is secure by default - customer data, repo permissions, IAM, and database security has not been compromised. 

  See [secure coding training](https://handbook.sourcegraph.com/departments/security/secure-code-training/) and [secure coding practices](https://sourcegraph.sourcegraph.com/notebooks/Tm90ZWJvb2s6Njc=) for examples.

**Usability testing:** Verify that the application has met design guidelines and meets the needs of our users. If you did not work with a designer, or you have visual or UX changes that have not been QAed by a designer, please reach out at [#ask-design](https://sourcegraph.slack.com/archives/C0HMGV90V) as soon as possible!

- [ ] Check mobile layout of the filters panel 
- [ ] Check different UI states on the search result page with new search result page look (aggregation UI window, no matches state, search error state), make sure that spacings are correct there
- [ ] Check that file preview looks good on tablet screens (mobile optional)

**Compatibility testing:** Verify that the application works on all supported distribution environments (Compose, K8s, Helm, Dotcom, Cloud, etc).



## QA Checklist

1. **Have you made any infra related changes to environment variables, new services, or deployment methods that could affect customers?**
   - [ ] Yes - I've informed [#team-cloud](https://sourcegraph.slack.com/archives/C03LCPCT3SP) and [#team-delivery](https://sourcegraph.slack.com/archives/C02VDNKBWDU) of the changes.
   - [ ] Yes - Changelog or documentation has been updated, this includes changes to defaults and site config flags.
   - [x] No

    If your change is non-trivial, please review the [Cloud Launch](https://handbook.sourcegraph.com/departments/cloud/launch-process/#questionnaire) process. 

    If you've made changes to documentation, please link them in the comments below.  
    
    Comments:

2. **Which environments have the changes been tested on?**
   - [ ] rctest.sourcegraph.com
   - [x] sourcegraph.sourcegraph.com
   - [x] sourcegraph.com
   - [ ] cody-dev.sgdev.dev (running based off 5.2 release branch)
   - [ ] scaletesting.sgdev.org
   - [ ] other
  
    If other, please specify:

3. **Experimental features have been marked and behind a feature flag?**
   - [x] Yes
   - [ ] No
   - [ ] N/A

    If no, please specify why:

4. **Has telemetry been added as part of the product requirements?**
   - [x] Yes
   - [ ] No
   - [ ] N/A

5. **Completed entry to release post.**
   - [ ] Yes
   - [x] No
   - [ ] N/A

6. **Is a feature flagged in a way when turns the feature off, it behaves as-if the feature does not exist?**
   - [ ] Yes
   - [x] No
   - [ ] N/A

    If no, please specify why: Partially, since we changed search results look this change doesn't have a feature flag, same about file preview panel, but it's possible to turn off new filter panel with feature flag, then old filter panel will show up. 

7. **A [CHANGELOG entry](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) has been added for the feature/change?**
   - [ ] Yes
   - [ ] No
   - [ ] N/A

8. **Please provide any additional testing you've done that has not been covered above:**

**Comment by camdencheek** [comment]
Closing as done
