### ISSUE TITLE
[Tracking Issue] Cody Self-Serve Dec GA

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#58018]
The tracking issue for Cody Self Serve Dec GA.

### Community Users
Time period: per month
- 500 autocomplete suggestions
- 20 chat/command invocations
### Pro users
- Unlimited usage limits
- Abuse prevention rate limiting? @chenkc805 @rafax 

## Tasks
- [x] **Core Flow**
  - [ ] Users should be able to sign up from IDEs and marketing website
  - [ ] Users should be able to see what plan they are on
  - [ ] User onboarding flow changes
- [x] **Usage Limits**
  - [ ] Community users should be unable to use Cody when they hit their usage limits.
  - [ ] Community users who hit the usage limit should see an upsell to drive the user to Cody Pro.
  - [ ] Community users who hit the usage limit should get a date notifying them when their usage limit rests.
  - [ ] Pro users should be able to use Cody without any limits. 
  - [ ] Pro users should still have some safeguard limits set.
- [x] **Upgrade**
  - [ ] User should be able to Upgrade from Community to Pro tier and get Pro for free until February
  - [ ] User should be able to evaluate the Enterprise plan and reach out to sales to inquire more about this plan
  - [ ] Pricing Page
- [x] **Usage Tracking**
  - [ ] Users should be able to see how many autocomplete suggestions and chats they've used within the month.

**Comment by chenkc805** [comment]
re: rate limiting - can we build in some sort of rate limiting _before_ the requests get made to the LLM to save on costs? Something like:

- After X suggestions have been made in 1 month, add a Y ms delay to each suggestion
- After X chats have been made in 1 month, add a Y s delay to each chat response back

**Comment by chenkc805** [comment]
**Update on usage limits:** We're introducing daily usage limits to Community (in addition to Community's monthly usage limit) and Pro tier to protect against abuse. These limits are:

- Community daily limits = 50/ day for chat/commands and 1000/day for autocomplete (ie. what we're doing today on dotcom)
- Pro daily limits = 100/ day for chat/commands and 2000/day for autocomplete (ie. what we're doing today on dotcom * 2)

**For embeddings limit, let's limit at 5 MB of code** (about 56% of app users, who are already super users cause they've gone through the hard work of embedding their repos). We can always expand later if we believe users aren't hitting their "Aha" moment.

**Comment by thenamankumar** [comment]
@chenkc805 For community users daily limit is not required as the monthly limit is low and just to note 50 & 1000 / day limits don't make sense when the monthly limit is 20 & 500.

100 & 2000 /day for pro looks good.

**Comment by chenkc805** [comment]
Update here, let's make the embeddings limit:

- Cody Community - Embed up to 200 MB of your own code (based on sg/sg being ~200MB)
- Cody Pro - Embed up to 2 GB of code with your team
  - re: embedding 2GB of code with your team, I'm imagining that there's a shared UI that people on the Team level so teammates can look at what repos are embedded and can manage that together. If this is not feasible by December GA, we can just make the embeddings limit 2 GB of code for you as an individual. CC: @danielmarquespt What do you think?

**Comment by chenkc805** [comment]
Update: for Cody Pro for December GA, we'll simplify to :

- Cody Community - Embed up to 200 MB of your own code (based on sg/sg being ~200MB)
- Cody Pro - Embed up to 2 GB of your own code

For Cody Feb GA, I'd like us to explore having a "team managed" embeddings that all team members can tap and use. CC: @danielmarquespt could I get your help wireframing this, and @thenamankumar @vdavid @chrsmith What do you think?

**Comment by thenamankumar** [comment]
@chenkc805 AFAIK, there is no cloud storage of your own code embeddings, so other than sharing a common limit, I don't think team members can share the embeddings itself.
