### ISSUE TITLE
Q4 - Analytics: Tracking issue

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#58232]
[RFC 870](https://docs.google.com/document/u/0/d/1bwOuxnMd-a7i6gyAvxF2vdB942iFkUc_O_soIuo1Nn0/edit) 

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58233
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58432
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58798
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59276
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59270
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59275
- [ ] https://github.com/sourcegraph/sourcegraph/issues/60080
- [ ] https://github.com/sourcegraph/sourcegraph/issues/60098
- [ ] https://github.com/sourcegraph/sourcegraph/issues/60170
- [ ] https://github.com/sourcegraph/sourcegraph/issues/60329
```

**Comment by cbart** [comment]
Follow-up in May epic: https://github.com/sourcegraph/sourcegraph/issues/60516
