### ISSUE TITLE
tracking: demonstrate keyword search prototype on s2

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#58235]
We want to bring code search closer to the "keyword search" style that users are used to, where queries are broken up into individual terms that can match broadly across the file name, contents, and symbols.

This issue tracks us demonstrating the value of this approach. A successful outcome is buy in to further invest in making this a broad change across our product.

```[tasklist]
### Tasks
- [ ] lookup smart search telemetry
- [ ] sqs style loom for "make search better"
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58125
- [ ] enable on s2
```

[RFC: Search Platform Q4 Plan - Google Docs](https://docs.google.com/document/d/1gk4G1l_8H3uvNGbmvYEnUfE7s7_5cMWibbTwNwHQVRI/edit#heading=h.ume1wuwp7ygz)

/cc @sourcegraph/search-platform

**Comment by keegancsmith** [comment]
Smart search telemetry for dotcom is at https://sourcegraph.looker.com/dashboards/532?Timestamp+Date=14+day
Can explore deeply using redash as well at https://redash.sgdev.org \o/

I haven't dived into the data yet, but will do soon.

**Comment by keegancsmith** [comment]
FYI the feature flag is on s2 and based on the telemetry data for dotcom smart search rarely triggers.
