### ISSUE TITLE
tracking: improved indexed search ranking

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#58234]
We want to bring code search closer to the "keyword search" style that users are used to, where queries are broken up into individual terms that can match broadly across the file name, contents, and symbols.

This issue tracks improvements we are making to ranking. The work done here benefits all customers even if we don't ship a change to our syntax. This is were the majority of our work has been concentrated so far.

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57666
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57950
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58195
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58196
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58197
- [x] ranking: add recall to zoekt test
- [ ] better file match limits as part of display limit
- [ ] integration test on zoekt in sourcegraph repo
```

### Lower priority tasks
- [x] https://github.com/sourcegraph/sourcegraph/issues/58057
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58059

[RFC: Search Platform Q4 Plan - Google Docs](https://docs.google.com/document/d/1gk4G1l_8H3uvNGbmvYEnUfE7s7_5cMWibbTwNwHQVRI/edit#heading=h.ume1wuwp7ygz)

/cc @sourcegraph/search-platform

**Comment by keegancsmith** [comment]
There is a PR out for integration/e2e testing on ranking. This should make it much easier to see quickly the effect of ranking changes on the corpus of queries we are tracking (and extending that corpus).

Next up I am keen on tackling our ideas around boosting atoms matches better (currently have 3 issues around that). Keen on this since it seems tracktable and I often see results where I wish we had done that.

**Comment by keegancsmith** [comment]
We are focussing on other work to ensure we can ship something end to end for users. All the items here are important, but are not on the critical path given our previous work on ranking.

Also here is a photo from the whiteboard when we met up about our discussion around atom ranking
![IMG_1442](https://github.com/sourcegraph/sourcegraph/assets/187831/6a02d3f7-39aa-4136-8d34-f3fc79b8f30e)

**Comment by stefanhengl** [comment]
@keegancsmith do we still need this tracking issue given that this was targeted for the last release?
