### ISSUE TITLE
Q4 - Admin experience: Tracking issue

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#58375]
[PRD: Cody for Enterprise](https://docs.google.com/document/d/1csaMR09ed_zLoLTQ4JcArHmQVHeORKbh4y_jEOFIai8/edit#heading=h.ske6bffnwzwz)

[Work Plan](https://docs.google.com/document/d/1tWo_Iu8BtAqsh8yHGxpBEWf0JKH858QnWtMFNHDGVXs/edit#heading=h.xyn66mph5uw1)

## Landing hotlist

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59681
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59682
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59976
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59977
- [ ] https://github.com/sourcegraph/cody/issues/2976
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59980
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59981
- [ ] https://github.com/sourcegraph/cody/issues/2925
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59683
- [ ] https://github.com/sourcegraph/sourcegraph/issues/60306
```

## Milestone 1 (Dec)

```[tasklist]
### Tasks
- [x] https://github.com/sourcegraph/sourcegraph/issues/58463
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58624
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58623
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58625
- [ ] Clearly document what can go wrong with cody admin limits being violated
```

## Milestone 2 (Jan-Feb)

```[tasklist]
### Tasks
- [x] https://github.com/sourcegraph/sourcegraph/issues/58463
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58626
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58629
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58627
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58634
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58631
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58630
```

## Milestone 3 (Feb)

```[tasklist]
### Tasks
- [x] https://github.com/sourcegraph/sourcegraph/issues/58463
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58628
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58632
- [ ] https://github.com/sourcegraph/sourcegraph/issues/58633
- [ ] https://github.com/sourcegraph/cody/issues/2999
```
