### ISSUE TITLE
Craft some embeddings test cases based on interactions

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#58431]
Goal: craft quality test cases for chat based on samples representative of usage.

How do we do it?

- Cluster interactions or transcripts, and see what we get
- Iterate with various ways of clustering to arrive at a reasonable sample set
- Craft test cases based off the samples.

Focus: embeddings sensitivity.

Next steps: extract the pattern of obtaining test cases for automating.

--Waiting on https://github.com/sourcegraph/sourcegraph/issues/58457--

```[tasklist]
### Tasks
- [x] Figure out how to query BigQuery
- [x] Prototype a clustering mechanism for starters https://github.com/sourcegraph/sourcegraph/pull/58498
- [ ] Evaluate single clustering solution on the transcripts dataset.
```

**Comment by cbart** [comment]
BigQuery: https://sourcegraph.slack.com/archives/CN4FC7XT4/p1700569146888819?thread_ts=1698869988.579849&cid=CN4FC7XT4

**Comment by cbart** [comment]
- We found that we have just a handful of data points, so could have clustered them by hand.
- Clustering prototype PR: https://github.com/sourcegraph/sourcegraph/pull/58498/files
- Waiting on https://github.com/sourcegraph/cody/pull/1856 to gert more data

**Comment by cbart** [comment]
Unassigning myself - we can pick this up once we have more data points
