### ISSUE TITLE
Access token expiration (P0 complete)

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#58652]
Slack: https://sourcegraph.slack.com/archives/C05405NC49H/p1701257573590089?thread_ts=1701196587.077239&cid=C05405NC49H

Team discussion 11/30: https://docs.google.com/document/d/1U78ry234hdI-9L55WplblOGYF-GXqm9Z-easuwQ3yxE/edit#bookmark=id.llci0n1q8qk0
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59545
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59544
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59543
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59774
- [ ] https://github.com/sourcegraph/cody/issues/2788
- [ ] https://github.com/sourcegraph/jetbrains/issues/311
```

**Comment by cbart** [comment]
@slimsag please take a look whether this makes sense as part of admin experience scope.
