### ISSUE TITLE
Q4 - Chat evaluation

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#59117]
```[tasklist]
### Tasks
- [ ] Run-a-file checker
- [ ] Syntactic closeness metric - language agnostic
- [ ] https://github.com/sourcegraph/sourcegraph/issues/59205
```
