### ISSUE TITLE
Search jobs: Switch from CSV to JSON

### ISSUE THREAD

**Issue by jtibshirani** [sourcegraph/sourcegraph#59329]
### Requirements:
  - [x] Add individual matches
  - [ ] Add checksum to header
  - [ ] Add tags (metadata, topics) as new column

### Design
- Switch from CSV to JSON
- Serve JSON in the format of the Steam API IE ChunkMatches with byte offsets

```[tasklist]
### Tasks
- [x] Update SearchQuery interface to take a (more generic) Writer interface
- [x] Implement a JSON Writer
- [x] Switch storage layer and download format to JSON
- [x] Serve JSON
```

Context:
https://sourcegraph.slack.com/archives/C05KARB1F33/p1702502762016359
