### ISSUE TITLE
Implement new Plans from Pricing and Packaging

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#59413]
```[tasklist]
### tasks:
- [x] Remove FeatureCody from old plans + comms
- [x] For the above: Need to issue dotcom a new license for one of the new tiers, otherwise it will lose Cody
- [x] Introduce new plans to subscription management
- [x] Deprecate old plans, comms required
- [x] Update handbook page for how to generate licenses
- [x] Write announcement post that manual tags are discouraged
- [x] Implement enforcement for code monitoring
- [x] Implement enforcement for notebooks
- [x] Implement enforcement for code search
- [x] Backport cody drop PR
```

## Moved to later

- [ ] Implement max cody user count
- [ ] Roll out new RBAC access to license management

**Comment by eseliger** [comment]
Comms are out, all PRs merged.
