### ISSUE TITLE
P1 Hardening of context sources in the extension against codyignore (find out if we need to do this separately for extensions)

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#59683]
Start by exploring context sources that do not respect codyignore and add them to the tasklist:

- [x] For each context source document how is it using cody ignore. Are there any issues or possiblities of leaking context?
- [x] For cases where possible send a PR to harden the context - so respect codyignore where context was leaking.
- [x] Document the other cases
  - Preferably in the docs.sourcegraph.com -> ask VS Code team where the best place to document that is so we have source of truth

Please see [the doc](https://docs.google.com/document/d/1LUNSOuwwhgycfCvqoI3AETS-sDIjCpZknFv2ueQ8Ctw/edit#heading=h.9ej9zzvhqq58).

```[tasklist]
### Tasks
```

**Comment by arafatkatze** [comment]
I would not say this issue is fully finished in the sense that there are many edge cases that haven't been considered 
<img width="757" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/11155207/a71bfc7e-ab01-47ef-ab44-6919a46f94ae">

But this handle the current state of Vscode for single git repo uses so for that reason I am closing this issue(Because I interpreted this issue to be limited to VScode alone).

**Comment by arafatkatze** [comment]
New Issue https://github.com/sourcegraph/sourcegraph/issues/60289 

Current Context hardening status is defined in this document(for Vscode) [Document](https://docs.google.com/document/d/1LUNSOuwwhgycfCvqoI3AETS-sDIjCpZknFv2ueQ8Ctw/edit#heading=h.9i9alxn1la52)
