### ISSUE TITLE
Strict Gitserver API surface

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#59738]
To improve debuggability and implement meaningful performance improvements, we're going to provide a strictly-typed git interface from gitserver that doesn't split the responsibilities of dealing with git output and data between the server and client packages.
The outcome will be that we can switch simple commands over to methods like libgit2 or go-git as a follow-up because we don't rely on the log output format anymore on the client side, without introducing further breaking changes to the API.
This will also help increase the security of gitserver, as we will be able to move subrepo perm checks into the server, so we never even return data that shouldn't be read by the given actor.

List of gitserver.Client methods that we likely want to migrate:

- [x] `ArchiveReader(ctx context.Context, repo api.RepoName, options ArchiveOptions) (io.ReadCloser, error)` @pjlast 
  - Consolidate error handling on server-side so that notfound errors are returned before any messages are streamed
- [x] `BatchLog(ctx context.Context, opts BatchLogOptions, callback BatchLogCallback) error` @eseliger 
  - Already a separate endpoint, although the data is very low-level, might consider rolling this into other requests.
- [x] `StreamBlameFile(ctx context.Context, repo api.RepoName, path string, opt *BlameOptions) (HunkReader, error)` @eseliger 
- [x] `GetDefaultBranch(ctx context.Context, repo api.RepoName, short bool) (refName string, commit api.CommitID, err error)` @eseliger 
- [x] `GetObject(ctx context.Context, repo api.RepoName, objectName string) (*gitdomain.GitObject, error)` @ggilmore 
- [x] `HasCommitAfter(ctx context.Context, repo api.RepoName, date string, revspec string) (bool, error)` @eseliger 
  - Could this be implemented by getting the latest commit on branch X, and compare the date then? If so, let's not create a separate endpoint here. There's only a single user of this method, that could encapsulate this logic.
- [x] `ListRefs(ctx context.Context, repo api.RepoName) ([]gitdomain.Ref, error)` @eseliger 
- [x] `ListBranches(ctx context.Context, repo api.RepoName, opt BranchesOptions) ([]*gitdomain.Branch, error)` @eseliger 
- [x] `MergeBase(ctx context.Context, repo api.RepoName, base, head string) (api.CommitID, error)` @eseliger 
- [x] `ResolveRevision(ctx context.Context, repo api.RepoName, spec string, opt ResolveRevisionOptions) (api.CommitID, error)` @eseliger 
- [x] `ResolveRevisions(_ context.Context, repo api.RepoName, _ []protocol.RevisionSpecifier) ([]string, error)` @eseliger 
  - Remove. Use the above method instead at callsite.
- [x] `Stat(ctx context.Context, repo api.RepoName, commit api.CommitID, path string) (fs.FileInfo, error)`
- [x] `DiffPath(ctx context.Context, repo api.RepoName, sourceCommit, targetCommit, path string) ([]*diff.Hunk, error)`
  - Merged with `Diff` @eseliger 
- [x] `ReadDir(ctx context.Context, repo api.RepoName, commit api.CommitID, path string, recurse bool) ([]fs.FileInfo, error)`
- [x] `NewFileReader(ctx context.Context, repo api.RepoName, commit api.CommitID, name string) (io.ReadCloser, error)` @eseliger 
- [x] `DiffSymbols(ctx context.Context, repo api.RepoName, commitA, commitB api.CommitID) ([]byte, error)` @ggilmore 
- [x] `Commits(ctx context.Context, repo api.RepoName, opt CommitsOptions) ([]*gitdomain.Commit, error)` @eseliger 
- [x] `FirstEverCommit(ctx context.Context, repo api.RepoName) (*gitdomain.Commit, error)` @ggilmore 
  - Maybe: Remove. It's slow and we might be able to move away from the current use-case.
- [x] `ListTags(ctx context.Context, repo api.RepoName, commitObjs ...string) ([]*gitdomain.Tag, error)` @eseliger 
- [x] `ListDirectoryChildren(ctx context.Context, repo api.RepoName, commit api.CommitID, dirnames []string) (map[string][]string, error)`
  - Remove, use ReadDir instead.
- [x] `Diff(ctx context.Context, opts DiffOptions) (*DiffFileIterator, error)` @eseliger 
- [x] `ReadFile(ctx context.Context, repo api.RepoName, commit api.CommitID, name string) ([]byte, error)` @eseliger 
  - Combine with NewFileReader to encourage streaming processing over memory-intensive io.ReadAlls. Functionally equivalent. 
- [x] `BranchesContaining(ctx context.Context, repo api.RepoName, commit api.CommitID) ([]string, error)` @eseliger 
- [x] `RefDescriptions(ctx context.Context, repo api.RepoName, gitObjs ...string) (map[string][]gitdomain.RefDescription, error)`
- [x] `CommitExists(ctx context.Context, repo api.RepoName, id api.CommitID) (bool, error)` @eseliger 
  - Remove. Use GetCommit instead and do an error check. 
- [x] `CommitsExist(ctx context.Context, repoCommits []api.RepoCommit) ([]bool, error)` @eseliger 
  - Remove. Use GetCommit(s) instead and do an error check.
- [x] `Head(ctx context.Context, repo api.RepoName) (string, bool, error)` @eseliger 
  - Merge with GetDefaultBranch.
- [x] `CommitDate(ctx context.Context, repo api.RepoName, commit api.CommitID) (string, time.Time, bool, error)` @eseliger 
  - Remove. Use GetCommit instead.
- [x] `CommitGraph(ctx context.Context, repo api.RepoName, opts CommitGraphOptions) (_ *gitdomain.CommitGraph, err error)` @eseliger 
- [x] `CommitLog(ctx context.Context, repo api.RepoName, after time.Time) ([]CommitLog, error)` @eseliger 
- [x] `CommitsUniqueToBranch(ctx context.Context, repo api.RepoName, branchName string, isDefaultBranch bool, maxAge *time.Time) (map[string]time.Time, error)` @eseliger 
- [x] `LsFiles(ctx context.Context, repo api.RepoName, commit api.CommitID, pathspecs ...gitdomain.Pathspec) ([]string, error)`
  - Can this be combined with ls-tree from ReadDir?
- [x] `GetCommits(ctx context.Context, repoCommits []api.RepoCommit, ignoreErrors bool) ([]*gitdomain.Commit, error)` @eseliger 
  - Don't convert. Only exposed for the integration test suite. Should unexport once the integration test can live purely server-side for GetCommits, and removed from client interface.
- [x] `GetCommit(ctx context.Context, repo api.RepoName, id api.CommitID, opt ResolveRevisionOptions) (*gitdomain.Commit, error)`
- [x] `GetBehindAhead(ctx context.Context, repo api.RepoName, left, right string) (*gitdomain.BehindAhead, error)` @ggilmore 
- [x] `ContributorCount(ctx context.Context, repo api.RepoName, opt ContributorOptions) ([]*gitdomain.ContributorCount, error)` @eseliger 
- [x] `LogReverseEach(ctx context.Context, repo string, commit string, n int, onLogEntry func(entry gitdomain.LogEntry) error) error` @eseliger 
- [x] `RevList(ctx context.Context, repo string, commit string, onCommit func(commit string) (bool, error)) error` @eseliger 

## Finalizing

- [ ] Sunset exec endpoint
