### ISSUE TITLE
3.10 Release blog post tasks

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#5974]
# 3.10 Release: DevRel tasks

- [x] [Release blog post](https://docs.google.com/document/d/1124LhEejKb4fTunQtk1EsKhqkydpPpeCd5B5mHojFI4/edit#heading=h.vws1psj6dp0i)
- [x] [Release email](https://github.com/sourcegraph/sourcegraph/issues/5976)
- [x] [Release tweet](https://github.com/sourcegraph/sourcegraph/issues/5975)

## At the start of the month (2019-11-01)

- [x] Create draft blog post Google doc in [Sourcegraph shared](https://drive.google.com/drive/u/0/folders/0B3lEU2lM-l9gUk5sNmRSMVFHVFU)
  - [x] View each [team's release deliverables](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.10+label%3Aroadmap) to generate the outline of the blog post
  - [ ] Share link to blog post doc in #progress Slack channel, asking Team leads to review

- [x] Create draft tweet
- [x] Create draft email
- [x] Link to the blog post, email and tweet

### Create calendar events

Add events to the shared Release Schedule calendar in Google and invite team@sourcegraph.com:

- [ ] Blog post draft ready for review (5 days before release)
- [ ] Final blog post changes/suggestions must be submitted (3 days before the release)
- [ ] Blog post / tweets go live (the specific date we plan to do this, often not the 20th when it is a Friday).

## In the first week

- [x] Confirm with each team that the planned deliverables are still on track to be announced in the blog post.
- [x] Fill out each section based on the deliverables to first draft quality
- [x] Think about what media (e.g. screenshot, screencast) will accompany the section content

## In the second week

- [x] Remove `motd` previous release promotion from [Sourcegraph.com global settings](https://sourcegraph.com/site-admin/global-settings)
- [x] Post the blog post draft to #dev-announce: `The blog post draft for <VERSION> is ready, please review your parts are accurate and provide feedback by <DATE>: <link>
- [x] Tweet written
- [x] Email written
- [x] Write a warning at the top of the Google doc: `The blog post has been finalized and moved to Markdown, further changes here will not be reflected. Contact @ryan-blunden for suggestions.`
- [x] Export blog post from Google docs to Markdown and create a new branch and draft pull request in [sourcegraph/about](https://github.com/sourcegraph/about/), using the [release blog post template](https://github.com/sourcegraph/about/blob/master/RELEASE_BLOG_POST_TEMPLATE.md)
- [x] Send blog post, and email to [copy editor](https://docs.google.com/spreadsheets/d/1UUSSWrS8aKsLEg7M3Qdzw9s0GLJCI1eCrSJI06Qofb0/edit#gid=0_)

## 5 working days before release

- [x] Start producing screenshots, diagrams, and screencasts for each blog post section

## 3 working days before release

- [x] Check for any last minute release changes that affect the blog post, e.g. last minute feature removal
- [x] Finalize screenshots, diagrams, and screencasts
- [x] Blog post approved
- [x] Email approved
- [x] Tweet approved

## Day of release

- [x] Publish blog post once the final release is cut, and docs version change is deployed
- [x] Publish tweet:
  - [ ] Pin new release tweet
  - [ ] Confirm with Product if tweet will be promoted
- [x] Send email in HubSpot
- [ ] Create new `notice` in [Sourcegraph.com global settings](https://sourcegraph.com/site-admin/global-settings)
   ```
   "notices": [
     {
       "message": "Sourcegraph {VERSION} is now available! Check out the [{VERSION} release blog post](https://about.sourcegraph.com/blog/sourcegraph-{VERSION}) for more details.",
       "location": "top",
       "dismissible": true
     }
   ]
   ```
- [ ] Use tweet or email content for post on the [LinkedIn Sourcegraph company page](https://www.linkedin.com/company/sourcegraph/)
- [ ] Put notification in #dev-rel Slack channel with links to blog post and tweet

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by christinaforney** [comment]
Tweet: https://twitter.com/srcgraph/status/1197222073203953664
Email: https://app.hubspot.com/email/2762526/details/21550822162/performance
Blogpost: https://about.sourcegraph.com/blog/sourcegraph-3.10
