### ISSUE TITLE
5.3.0 release tracking issue

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#60032]
# 5.3 release

This release is scheduled for **[Feb 13, 2024, 8:00 AM (UTC)](https://time.is/0800_13_Feb_2024_in_UTC?5.3%20release%20date)**.

---

## Setup

- [x] Ensure you have the latest version of the release tooling and configuration by checking out and updating `sourcegraph@main`.
- [x] Ensure release configuration in [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) on `main` has version 5.3.0 selected by using the command:

```shell
pnpm run release release:activate-release
```

## Security review ([Feb 13, 2024, 8:00 AM (UTC)](https://time.is/0800_13_Feb_2024_in_UTC?One%20working%20week%20before%205.3%20release))

- [x] Create a [Security release approval](https://github.com/sourcegraph/sourcegraph/issues/new/choose#:~:text=Security%20release%20approval) issue and post a message in the [#discuss-security](https://sourcegraph.slack.com/archives/C1JH2BEHZ) channel tagging `@security-support`.

## Cut release ([Feb 9, 2024, 8:00 AM (UTC)](https://time.is/0800_9_Feb_2024_in_UTC?Three%20working%20days%20before%205.3%20release))

Perform these steps three days before the release date to generate a stable release candidate.

### Prepare release

- [x] Post a release status update to Slack - [review all release-blocking issues](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aopen+is%3Aissue+label%3Arelease-blocker), and ensure someone is resolving each.

  ```sh
  pnpm run release release:status
  ```

Do the [branch cut](https://handbook.sourcegraph.com/departments/engineering/dev/process/releases/#release-branches) for the release:

- [x] Update the changelog and create pull requests:

  ```sh
  pnpm run release changelog:cut
  ```

- [x] Manually review the pull requests created in the previous step and merge.
- [x] Wait for CI of the commit on `main` to pass.
- [x] Request Admin permissions of `sourcegraph/sourcegraph` repository through [Entitle](https://app.entitle.io/request?targetType=resource&duration=1800&justification=Temporarily%20disable%20the%20%22Require%20linear%20history%22%20rule%20for%20release%20branches%20to%20create%20a%20new%20release%20branch.&integrationId=032680b6-f13d-42aa-9837-38097b45f0fe&resourceId=cd16ad0f-0e7e-4f20-8a8c-b3c57751dafd&roleId=5151f2f3-40a3-4697-99a2-b5e756e43f5b&grantMethodId=5151f2f3-40a3-4697-99a2-b5e756e43f5b) in order to disable the [**Require linear history** protection rule for release branches](https://github.com/sourcegraph/sourcegraph/settings/branch_protection_rules/34536616#:~:text=Require%20linear%20history).

- ~[ ] Enable the [`release-protector` GitHub Action](https://github.com/sourcegraph/sourcegraph/blob/main/.github/workflows/release-protector.yml) in the `sourcegraph/sourcegraph` repository.~

- [x] Create the `5.3` branch off the CHANGELOG commit in the previous step:

  ```sh
  pnpm run release release:branch-cut
  ```

- [x] Re-enable the [**Require linear history** protection rule for release branches](https://github.com/sourcegraph/sourcegraph/settings/branch_protection_rules/34536616#:~:text=Require%20linear%20history).

- [x] Push a new release candidate tag. This command will automatically detect the appropriate release candidate number. This command can be executed as many times as required, and will increment the release candidate number for each subsequent build: :

  ```sh
  pnpm run release release:create-candidate
  ```

- [x] Ensure that the following Buildkite pipelines all pass for the `v5.3.0-rc.N` tag:
- [x] [Sourcegraph pipeline](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=v5.3.0-rc.1)
- [x] Cross check all reported CVEs are in the accepted list (`https://handbook.sourcegraph.com/departments/security/tooling/trivy/5-3-0`). You can use the utility command `sg release cve-check` to help with this step. Otherwise, alert `@security-support` in the [#release-guild](https://sourcegraph.slack.com/archives/C032Z79NZQC) channel ASAP.
- [x] File any failures and regressions in the pipelines as `release-blocker` issues and assign the appropriate teams.

Revert or disable features that may cause delays. As necessary, `git cherry-pick` bugfix (not feature!) commits from `main` into the release branch. Continue to create new release candidates as necessary, until no more `release-blocker` issues remain.

- [x] Update the [target branch of the RC test instance](https://github.com/sourcegraph/cloud/blob/main/.github/workflows/mi_upgrade_rctest.yml#L51) to the new release branch `5.3`.
- [x] Trigger a [manual run of the GitHub Action](https://github.com/sourcegraph/cloud/actions/workflows/mi_upgrade_rctest.yml) to upgrade the RC test instance. It should complete without an error, otherwise there might be a database migration problem that warrants a `release-blocker` issue.

> [!important]
> You will need to re-check the above pipelines for any subsequent release candidates. You can see the Buildkite logs by tweaking the "branch" query parameter in the URLs to point to the desired release candidate. In general, the URL scheme looks like the following (replacing `N` in the URL):

- Sourcegraph: `https://buildkite.com/sourcegraph/sourcegraph/builds?branch=v5.3.0-rc.N`

- [x] Post a release status update to Slack:

  ```sh
  pnpm run release release:status
  ```

## Code Freeze

Create candidates as necessary

```shell
pnpm run release release:create-candidate
```

Monitor the release branch, and backports. Ensure the branch remains healthy.

### Stage release

On the day of the release, confirm there are no more release-blocking issues (as reported by the `release:status` command), then proceed with creating the final release:

- [x] Bake constants and other static values into the release branch (and also update main) This requires the release branch exists (should be automated above).
  ```shell
  pnpm run release release:bake-content
  ```
- [x] Merge the resulting pull requests for the content bake generated by the command above
- [x] Release a new version of src-cli, terraform-google-executors, aws-executors
  ```shell
  pnpm run release release:create-tags
  ```
- [ ] Ensure the latest version of src-cli is available in all sources. You may need to run this command a few times in the background.
  ```shell
    pnpm run release release:verify-releases
  ```
- [x] Make another release candidate with the baked content
- [x] Make sure [CHANGELOG entries](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) have been moved from **Unreleased** to **5.3.0**, but exluding the ones that merged to `main` after the branch cut (whose changes are not in the `5.3` branch).
- [x] Ensure security has approved the [Security release approval](https://github.com/sourcegraph/sourcegraph/issues?q=label%3Arelease-blocker+Security+approval+is%3Aopen) issue you created.
- [x] Make sure [deploy-sourcegraph-helm CHANGELOG entries](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/CHANGELOG.md) have been moved from **Unreleased** to **5.3.0**, but exluding the ones that merged to `main` after the branch cut (whose changes are not in the `5.3` branch).
- [x] Promote a release candidate to the final release build. You will need to provide the tag of the release candidate which you would like to promote as an argument. To get a list of available release candidates, you can use:

  ```shell
  pnpm run release release:check-candidate
  ```

  To promote the candidate, use the command:

  ```sh
  pnpm run release release:promote-candidate <tag>
  ```

- [x] Ensure that the following pipelines all pass for the `v5.3.0` tag:
  - [x] [Sourcegraph pipeline](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=v5.3.0)
- [x] Wait for the `v5.3.0` release Docker images to be available in [Docker Hub](https://hub.docker.com/r/sourcegraph/server/tags)
- [x] Open PRs that publish the new release and address any action items required to finalize draft PRs (track PR status via the [generated release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes)):

  ```sh
  pnpm run release release:stage
  ```

### Finalize release

- [x] From the [release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes), merge the release-publishing PRs created previously.
  - For [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph)
    - [x] Ensure the [release tag `v5.3.0`](https://github.com/sourcegraph/deploy-sourcegraph/tags) has been created
  - For [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker)
    - [x] Ensure the [release tag `v5.3.0`](https://github.com/sourcegraph/deploy-sourcegraph-docker/tags) has been created
  - For [deploy-sourcegraph-helm](https://github.com/sourcegraph/deploy-sourcegraph-helm)
    - [x] Cherry pick the release-publishing PR from the release branch into main
- [x] Alert the marketing team in [#release-post](https://sourcegraph.slack.com/archives/C022Y5VUSBU) that they can merge the release post.
- [x] Announce that the release is live:
  ```sh
  pnpm run release release:announce
  ```
- ~[ ] Disable the `release-protector` github action in sourcegraph/sourcegraph. This may require you to request admin permissions using Entitle.~

### Post-release

- [ ] Create release calendar events, tracking issue, and announcement for next release (note: these commands will prompt for user input to generate the definition for the next release):
  ```sh
  pnpm run release release:prepare
  pnpm run release tracking:issues
  pnpm run release tracking:timeline
  ```
- [ ] Close the release.
  ```sh
  pnpm run release release:close
  ```
- [ ] Open a PR to update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the auto-generated changes from above.

**Note:** If a patch release is requested after the release, ask that a [patch request issue](https://github.com/sourcegraph/sourcegraph/issues/new?assignees=&labels=team%2Fdistribution&template=request_patch_release.md&title=5.3.1%3A+) be filled out and approved first.

**Comment by keegancsmith** [comment]
@BolajiOlajide @unknwon I was reviewing these commands and realised I should probably run some of them now even  though the next step in here says Feb 9th. IE should I already be running the changelog creation command? Additionally I manually created the 5.3 branch via git, not via the release tooling. Is it possible I messed something up here?

Also

> The release template should say where to update the automation for CD of the release branch, iirc it’s just one line of change. No rc needed

I don't see the relevant information here. Can ya help point out what I need to do?

**Comment by unknwon** [comment]
>...realised I should probably run some of them now even though the next step in here says Feb 9th.

Yes the dates are confusing, more like "deadline" than the "start date" of doing things.

>Additionally I manually created the 5.3 branch via git, not via the release tooling. Is it possible I messed something up here?

I think that's what I did too, should be no problem.


> > The release template should say where to update the automation for CD of the release branch, iirc it’s just one line of change. No rc needed
> 
> I don't see the relevant information here. Can ya help point out what I need to do?

It's here:

![CleanShot 2024-02-02 at 15 52 11@2x](https://github.com/sourcegraph/sourcegraph/assets/2946214/95c0556a-63b3-4e99-80b6-a74a6cc06818)

**Comment by keegancsmith** [comment]
> Enable the [release-protector GitHub Action](https://github.com/sourcegraph/sourcegraph/blob/main/.github/workflows/release-protector.yml) in the sourcegraph/sourcegraph repository

@unknwon @BolajiOlajide I am striking out this step since from what I can tell we are not using that workflow this time? If I am not mistaken we will continue with backports at code freeze, but they will require Erica's approval.

FYI my plan is to cut an rc once code freeze is in effect.

**Comment by BolajiOlajide** [comment]
> > Enable the [release-protector GitHub Action](https://github.com/sourcegraph/sourcegraph/blob/main/.github/workflows/release-protector.yml?rgh-link-date=2024-02-07T11%3A04%3A21Z) in the sourcegraph/sourcegraph repository
> 
> @unknwon @BolajiOlajide I am striking out this step since from what I can tell we are not using that workflow this time? If I am not mistaken we will continue with backports at code freeze, but they will require Erica's approval.
> 
> FYI my plan is to cut an rc once code freeze is in effect.

Yeah, that's an old artifact. I'll send a PR to remove that, we've discontinued the release protector.

**Comment by keegancsmith** [comment]
@jhchabran just double checking, but I still need to do all the steps listed under release day? In particular this step I am double checking:

>  Bake constants and other static values into the release branch (and also update main) This requires the release branch exists (should be automated above).

Just wondering if there is any overlap with these PRs: https://github.com/sourcegraph/sourcegraph/pull/60366 and https://github.com/sourcegraph/sourcegraph/pull/60087

**Comment by jhchabran** [comment]
@keegancsmith yes, those are merely touching the deps for the migrator to be able to MVU, not all of the baking content part the release tooling does are merged on main.

**Comment by keegancsmith** [comment]
Security release approval issue at https://github.com/sourcegraph/sourcegraph/issues/60449

**Comment by keegancsmith** [comment]
It literally took me all day to do the first step of the release (bake contents). Here is my lab journal so far

Had to sort out some backports and CI was goofing. So ended up starting the release process an hour later.

Created the security issue before those PRs landed. Given earlier work I did I am just gonna go ahead and do the release since I know our CVEs are in a good place.

    pnpm run release release:bake-content

Our release tooling embeds shell scripts in other repos&#x2026; which do things like run sed differently on mac vs linux. This failed since I have gnu coreutils installed on my mac. So had to run scripts with the prefix

    PATH=/usr/bin:"$PATH"

Then it failed with the error `sed: first RE may not be empty`. This turned out to be since when the release tool clones repos it doesn't fetch tags. I am guessing this has never actaully been tested :/

I hacked in fetching tags and it was still broken. Then I realised its because we do shallow cloning. I'd love to know how this worked in `5.2`. To finally get this to work, I added `'git fetch --unshallow'` to the edits we do. But then it still failed since for some reason at the release tooling doing the push.

So I manually created the PR and just did this again for AWS by commenting out the google step. This also failed in a way so badly I am convinced this has never been tested. The code blames to march last year, but the code mixes up the repo name and owner name.

So the reason the steps fail after the prepare-release.sh script has run is that script pushes and commits. But things run from the release tooling shouldn't do that.

All in all it would of been faster to do this manually by a significant margin. Here is the PR to halffix it <https://github.com/sourcegraph/sourcegraph/pull/60470>.

So I had to comment out the two terraform bake steps since they where so broken, then I could continue with the likely better tested paths.

Nope, not better tested:

```
+ go run ./data/cmd/generator --write-frozen=false
go: downloading github.com/sourcegraph/zoekt v0.0.0-20240212021124-1c158f9b8661
panic: error: missing -archive flag
```

JH quickly fixed this by replacing it with the new bazel based generator. However, when actually running in the release tooling it breaks. I assume it has never been tested on a version which is going to be released, but hasn't released yet. Turns out the issue is bazel not finding postgres.

In the meantime there are also some high-prio bug fixes landing for guardrails, so its a blessing that it is 3pm and I still haven't been able to finish the first step&#x2026; Here is a PR I contributed to help resolve the guardrails issue <https://github.com/sourcegraph/sourcegraph/pull/60471>

Ok sent out a PR to fix bazel not finding postgres. <https://github.com/sourcegraph/sourcegraph/pull/60479> Now I hit my next issue. We basically deleted the doc directory, and the tool is trying to update the src-cli reference. I sent out another PR to just skip this part of the release process. Will follow up. <https://github.com/sourcegraph/sourcegraph/pull/60480>

Finally I managed to finish the very first step of baking content! I started this journey at 10am, it is now 4:30pm. I will take this until the point I cut a new RC, but then I am gonna ask for someone to take over or maybe I pick it up again tomorrow morning.

**Comment by keegancsmith** [comment]
@BolajiOlajide `pnpm run release release:verify-releases` is reporting that both brew and npm do not have the new version of src-cli. However, when I look at the CI for src-cli, it says it skips the npm step. I don't know this part of our release, do I need to kick something? Can I just forge ahead on the steps and do the npm and brew by the 15th?

![image](https://github.com/sourcegraph/sourcegraph/assets/187831/85435d1e-a70c-4bfa-8082-372066acd5dd)

**Comment by BolajiOlajide** [comment]
> @BolajiOlajide `pnpm run release release:verify-releases` is reporting that both brew and npm do not have the new version of src-cli. However, when I look at the CI for src-cli, it says it skips the npm step. I don't know this part of our release, do I need to kick something? Can I just forge ahead on the steps and do the npm and brew by the 15th?
> 
> ![image](https://private-user-images.githubusercontent.com/187831/304476037-85435d1e-a70c-4bfa-8082-372066acd5dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NDE3NzQsIm5iZiI6MTcwNzg0MTQ3NCwicGF0aCI6Ii8xODc4MzEvMzA0NDc2MDM3LTg1NDM1ZDFlLWE3MGMtNGJmYS04MDgyLTM3MjA2NmFjZDVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxNjI0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzhjMzBmYzYxZjQ2OTk0OTgzNzMyNzRlOGMzN2VlMGE5ZmRkMTFkYmZlMTc4YjYwZTEwNmY5YmYwZDQyOGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QeuHAP-DXpQtPfaN9kuWQUVpXAGZBHfhvK_xDTLTNdM)

[Homebrew](https://github.com/sourcegraph/homebrew-src-cli/commit/a45dc90adc542d9a349786220d70273bb46e7e5b) is updated to 5.3.0. I'm looking into what's up with NPM.

**Comment by keegancsmith** [comment]
> Make sure [deploy-sourcegraph-helm CHANGELOG entries](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/CHANGELOG.md) have been moved from Unreleased to 5.3.0, but exluding the ones that merged to main after the branch cut (whose changes are not in the 5.3 branch).

The automation did the changelog stuff. However, no step created the release branch. I am manually doing that now since I see in the code some steps depend on it existing. Additionally there have been two commits to main, so I will ask about that with the authors.

**Comment by keegancsmith** [comment]
*Sourcegraph 5.3.0 has been published*

* Changelog: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#5-3-0
* GitHub release: https://github.com/sourcegraph/sourcegraph/releases/tag/v5.3.0
* Release batch change: https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.0

@keegancsmith: Please complete the post-release steps before closing this issue.

**Comment by keegancsmith** [comment]
> pnpm run release release:prepare

@BolajiOlajide I think we need to setup the timeline and captains for patch releases before I can run the post release tasks?

**Comment by BolajiOlajide** [comment]
Issue closed by release tool. #60032
