### ISSUE TITLE
[Cody PLG] Add integration test for `CodyManagementPage.tsx`

### ISSUE THREAD

**Issue by chrsmith** [sourcegraph/sourcegraph#60132]
The Cody Management page is surprisingly complex, with various types of banners displayed based on the user's subscription status and feature flags. (e.g. the logic added in https://github.com/sourcegraph/sourcegraph/pull/59989.)

This page will become even more onerous to maintain as we shift the source of truth for Cody data between backends. (e.g. deriving subscription limits from the SSC backend, and/or Cody Gateway.) See the `// BUG:` comments called out in https://github.com/sourcegraph/sourcegraph/pull/60075.

So to avoid regressions on this page, and ensure the behavior matches our expectations, it's paramount we have a good integration test for this component.

**Comment by chrsmith** [comment]
We probably would want to do the same thing for `CodySubscriptionPage.tsx`, since that too will go through several waves of changes as we progressively roll out the PLG experience.

**Comment by vdavid** [comment]
I agree it'd be great to have automated testing for these components, but let's not take that on before the release. We can easily go this far with manual QA. Reprioritized this as a P2 for post-Feb.

**Comment by chrsmith** [comment]
Here are a couple of issues that came up _today_ as we take a closer look at this particular page.

- https://github.com/sourcegraph/accounts.sourcegraph.com/issues/442
- https://github.com/sourcegraph/accounts.sourcegraph.com/issues/444

**Comment by vdavid** [comment]
We want to see a test for:
- [ ] Each "banner" that we show.
  - For example, what are the required inputs to make the "Be Limitless with Cody Pro" banner appear.
- The differences in text/behavior based on the feature flags. `arePaymentsEnabled`/`freeTrialEnded` values:
  - [ ] for now: `false/false`,
  - [ ] starting Feb 8th: `true/false`
  - [ ] starting Feb 15th: `true/true`
  - [ ] (`false/true` shouldn't ever be the case, so maybe just add a comment to not worry about adding any tests for that.)

**Comment by vdavid** [comment]
To prevent issues like https://sourcegraph.slack.com/archives/C05SZB829D0/p1708613278533909 (PR: https://github.com/sourcegraph/sourcegraph/pull/60701)
