### ISSUE TITLE
tracking issue: standardize on Jaeger in all deployment contexts

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6014]
Previously, we [decided to standardize on Jaeger](https://github.com/sourcegraph/sourcegraph/issues/3175) in all deployment contexts. This issue is to track progress towards that.

- [ ] Upstream standard Prometheus+Grafana+Jaeger work to deploy-sourcegraph #3410
- [ ] Jaeger integration substantially harms search performance #5363
- [ ] Port Jaeger from deploy-sourcegraph-docker -> sourcegraph/server deployments #6012

Related high-level vision for monitoring in Sourcegraph: https://github.com/sourcegraph/sourcegraph/issues/4260

**Comment by beyang** [comment]
Replaced by https://github.com/sourcegraph/sourcegraph/issues/9300
