### ISSUE TITLE
[ReOps] Research roadmap 2024 Q1

### ISSUE THREAD

**Issue by meglynst** [sourcegraph/sourcegraph#60184]
- [x] Feb 5 - 9 : Prep async research roadmap work
- [x] Feb 12: Send async work to teams to complete (doc: https://docs.google.com/document/d/1AlCqxar8prKRBkhoCMl94E4IqxkIyNquhO1YHSyKg7w/edit?usp=sharing)
- [x] Feb 19: All async work returned to UXR (me)
- [ ] Feb 19: Discuss at UXR Sync (doc: https://docs.google.com/spreadsheets/d/1rOXkIK-9mbzQZ726SRQybfg5kwn4W0zvqSi4y5tVouQ/edit#gid=2015318861)
- [ ] Feb 20 - 26: Create V1 roadmap
- [ ] Feb 22 - Feb 29: Get feedback, update as necessary
- [ ] Mar 4: Start research
