### ISSUE TITLE
Distribution 3.10 tracking issue

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6038]
For reference, the work we set out to do in 3.9 was: https://github.com/sourcegraph/sourcegraph/issues/5737

For 3.10, we intend to do the following:

- Stephen: 100% focused on critical customer issues
    - [ ] ~(carried over from 3.9) Services: Add a generic form of network throttling (part 1) #5736~ Superseded
    - [ ] (carried over from 3.9) Some repositories stuck in "Empty repository" state sourcegraph/sourcegraph#5684
    - [ ] (carried over from 3.9) Better logging around GraphQL API usage sourcegraph/sourcegraph#5706
    - [ ] Continue improving search pagination API: [issues](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+is%3Aopen+label%3Asearch-pagination)
- Uwe
    - [ ] ~(carried over from 3.9) Resolve Grafana reverse proxy CSRF issue https://github.com/sourcegraph/sourcegraph/issues/6075~
    - [ ] (carried over from 3.9) Finalize Dashboards/Panels and document them
    - [ ] ~move alerts from alertmanager to Grafana~
    - [ ] Disk space alerts https://github.com/sourcegraph/sourcegraph/issues/5994
    - [x] GRAFANA_SERVER _URL default https://github.com/sourcegraph/sourcegraph/issues/5900
    - [x] Prometheus behind reverse proxy https://github.com/sourcegraph/issues-uber/issues/212
    - [ ] Eliminate ephemeral alert [RFC 35](https://docs.google.com/document/d/1GXYTBktfRjr3I5vyl-TwCixITtKG0snVXcehRU1dfok/edit#heading=h.9gknqva39m5l)
- Beyang
    - [x] Finish automation of regression tests ([RFC](https://docs.google.com/document/d/16MiKluindPCH6tCg_yqWOfBXubvuNK0Phg57U0_uovU/edit))
    - [x] :vulcan_salute: Release captain: revise and improve release captain docs, automating mechanical tasks.
    - [ ] Identify and break ground on security initiatives.
    - [ ] Omni config ([RFC](https://docs.google.com/document/d/1_HNAEaJBRR5dN1ti-ypDRAlZ4HJMsyYTfDj5Kk_jLWU/edit)) OR fix https://github.com/sourcegraph/sourcegraph/issues/5014
    - [ ] Re-enable LogDNA (https://github.com/sourcegraph/infrastructure/issues/1661)
    - Beyang's customer issues
      - [ ] Docs, regression test for using Sourcegraph with Atlassian Identity Manager (https://github.com/sourcegraph/sourcegraph/issues/5873)
      - [ ] Add org membership restriction option to GitHub auth (https://github.com/sourcegraph/sourcegraph/issues/4195)
      - [ ] Saved searches send email notifications not working (issues/1)
      - [ ] Get lines of code via API
- Geoffrey
    - Continue with hermetic Docker builds: https://github.com/sourcegraph/sourcegraph/pull/5745, [RFC 37](https://docs.google.com/document/d/1CXDUqE6qUKrduT8TFgWxWC58IUrrK4eiL08c3fKzHyc/edit#)

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Unchecked items here were not completed, some may be carried over. New tracking issue for 3.11 here: https://github.com/sourcegraph/sourcegraph/issues/6695
