### ISSUE TITLE
🎯 Decouple Release Ownership

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#60453]
[Slack channel](https://sourcegraph.slack.com/archives/C06JENN2QBF) 

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/61057 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61062 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61063 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61064 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61065 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61066 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61067 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61068 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61069 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61070 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61071 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61072 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61073 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61074 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61075 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61076 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61077 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61078 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61079 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61080 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61081 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61082 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61083 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61084 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61085 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61086 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61088 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61089 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61090 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61091 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61094 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61095 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61096 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61097 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61098 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61099 

@BolajiOlajide

- [ ] https://github.com/sourcegraph/sourcegraph/issues/61057 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61060 

@Chickensoupwithrice

- [ ] https://github.com/sourcegraph/sourcegraph/issues/61057 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61060 

@DaedalusG

- [ ] https://github.com/sourcegraph/sourcegraph/issues/61057 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61060 

@jdpleiness

- [ ] https://github.com/sourcegraph/sourcegraph/issues/61057 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61060 

@jhchabran

- [ ] https://github.com/sourcegraph/sourcegraph/issues/61057 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61061 

@kalanchan

- [ ] https://github.com/sourcegraph/sourcegraph/issues/61057 
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/61060

**Comment by jhchabran** [comment]
Closing in favour of https://github.com/sourcegraph/sourcegraph/issues/61057
