### ISSUE TITLE
🎯 Conventions for new repos to prevent compliance deviations

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#60456]
Related ticket on sec-team side: https://github.com/sourcegraph/security/issues/1150 

# Repo Conventions

Ensure new and existing repositories have sane defaults set for default actions, branch protection and teams.

## Problem
New repositories get created everyday for various reasons. A new product, a new direction or just a POC. 

Currently we're reactive into making a repository conform to settings which we consider default , which often requires someone manually going through repositories to check that they have the right settings.

We should be proactive and ensure repositories have the right workflows, branch protection rules and teams at all times.
## Success criteria

- N% of the repos impacting customers are indentified and instrumented
- Mission critical conventions are monitored. See [this](https://docs.google.com/document/d/1P1t8wflyefESTgkZfLbl0UNCj8APQn24uKoAukZwdGI/edit#heading=h.trqab8y0kufp) RFC for security identified as mission critical conventions

## Proposal

Create a service that continuously tracks the configuration and status of repositories in our GitHub organization. We can also leverage some builtin functionality from GitHub by creating a `.github` repository in our organization which allows us to ensure new repositories will have required workflows like PR-Auditor and CLA Bot. The service will also ensure repositories have default teams, branch protection and workflows enabled.

By default a repository will be subject to SOC2 controls. Naturally not all repositories _should_ fall under the SOC2 controls, therefore the service should support opting out certain controls.

To ensure continued compliance the service should:
* Generate a report of repositories that are and are not compliant, and whether there is a defined reason for there non-compliance ie. The repo is private and not shipping something to customers.
* Create issues when a repository is found to be not compliant upon which the repository owner should explain why it is not compliant.

![Repo Conventions Core(1)](https://github.com/sourcegraph/devx-support/assets/1001709/8e4e7f35-8d25-4403-b181-fe0d74fd8ea9)

### Milestones

| Description | Estimate |
| --- | --- |
| Conventions are documented in the handbook | 1 day
| Creating any repo has default workflows setup like CLA Bot, PR-Auditor | 2 day
| When a new repo is created default teams are added and branch protection rules are set. | 2 day
| Default teams and branch protection rules are added to existing repositories | 2 days
| Labelling a repository with an label like `exempt/soc2` makes the service not apply SOC2 conventions | 3 days
| Issues are created for repositories that are not compliant with SOC2 controls | 3 days
| Service can generate a report on repositories that are SOC2 compliant and which are exempt. | 2 days
|  Create dashboard for repos being actively monitored | 2 days
| _STRETCH_ - Scan issues on repositories for issues that should not be public | 3 days

#### Risks
* GitHub token limits, which we may hit while scan and update repositories.
* GitHub webhook granularity and limits. Due to the amount of events that all repositories might send via the webhook we might hit a GitHub limit.
* GitHub permissions, certain actions that we would want perform on repositories might not be supported by the GitHub API
* Repo might not have a clear defined owner

### Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/61146 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61147 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61155 

@burmudar

- [ ] https://github.com/sourcegraph/sourcegraph/issues/61154 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/62465 

Completed
- [x] (🏁 2024-04-22) https://github.com/sourcegraph/sourcegraph/issues/61149 
- [x] (🏁 2024-04-30) https://github.com/sourcegraph/sourcegraph/issues/61152 
- [x] (🏁 2024-04-30) https://github.com/sourcegraph/sourcegraph/issues/61148 
- [x] (🏁 2024-04-30) https://github.com/sourcegraph/sourcegraph/issues/61150 
- [x] (🏁 2024-05-13) https://github.com/sourcegraph/sourcegraph/issues/61153 
- [x] (🏁 2024-05-15) https://github.com/sourcegraph/sourcegraph/issues/62464
