### ISSUE TITLE
Add support for Structural Search

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#6073]
Goals

- Add support for Structural Search. See [RFC 48](https://docs.google.com/document/d/16WwZA8zf-soI0HgCXGrRL5IrmyZnGYrB5VTXsqguUzo/edit#heading=h.9b09j3rvvpcj).

Work items

- [x] Add codepath for structural search #6147 #6156 #6223 #6551 
- [x] Parse structural search patterns to queries that we can run against the search index, similar to [RegexpToQuery](https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/query/regexp.go#L48) #6156 #6412 
- [x] Run the queries against Zoekt (possibly incrementally), returning a list of files to run structural search on #6197 #6262
- [x] Add a package for calling out to comby #6244 #6424
- [x] Add a codepath that passes the list of files to comby for structural search #6309
- [x] Add structural search component to searcher #6449 
- [x] Update Docker dependencies for deployments #6494 
- [x] Add e2e integration test #6551

Triaged
- Upgrade the comby dependency to use the new parser engine  [RFC 48, Part 2](https://docs.google.com/document/d/16WwZA8zf-soI0HgCXGrRL5IrmyZnGYrB5VTXsqguUzo/edit#heading=h.9b09j3rvvpcj).

Next release
- Optimization: refine Zoekt query to return [only file matches](https://github.com/sourcegraph/sourcegraph/pull/6309#issuecomment-548691096), and use RepoList from Zoekt
- Add dedicated metrics

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
