### ISSUE TITLE
Automation Tracking Issue 3.10

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6085]
### RFC 42: Find and replace code across multiple repositories using Comby

[Link to RFC 42](https://docs.google.com/document/d/1j85PoL6NOzLX_PHFzBQogZcnttYK0BXj9XnrxF3DYmA/edit#)

#### Frontend & Backend

- [x] GraphQL API @felixfbecker (https://github.com/sourcegraph/sourcegraph/pull/6135/files)

#### Backend

- [x] Implement skeleton GraphQL layer & CRUD operations https://github.com/sourcegraph/sourcegraph/pull/6121
- [x] Persist/marshal/unmarshal `CampaignPlan.Arguments` in a way that keeps JSONC https://github.com/sourcegraph/sourcegraph/pull/6263
- [x] Implement `previewCampaignPlan` #6265 
  - [x] Search for repositories with the specified `searchScope`
  - [x] Create and nun `CampaignJob`s that send requests to replacer service to get back a diff for the specified `matchTemplate` and `rewriteTemplate`
  - [x] Support `Wait` argument to make this mutation synchronous/asynchronous
- [x] Implement returning `ChangesetPlans` for a running/finished `CampaignPlan` https://github.com/sourcegraph/sourcegraph/pull/6430
  - [x] Implement `campaignPlanResolver.Changesets`
  - [x] Implement `campaignPlanResolver.RepositoryDiffs`
- [x] Implement diffs for existing changesets
  - [x] Implement `campaignResolver.RepositoryDiffs` https://github.com/sourcegraph/sourcegraph/pull/6270
  - [x] Implement `changesetResolver.Diff`  https://github.com/sourcegraph/sourcegraph/issues/6164
- [x] Clean up `CampaignPlans` that have not been attached to a campaign in `TTL` https://github.com/sourcegraph/sourcegraph/pull/6513
- [x] Implement `campaignPlanResolver.BackgroundProcessStatus`
- [x] Implement `createCampaign` for `Campaign`s with `CampaignPlan` https://github.com/sourcegraph/sourcegraph/issues/6403 @tsenart 
- [x] Add `CreatePullRequest` method to `github.Client` and use it in `createCampaign`
- [x] Add `CreatePullRequest` methods to `bitbucketserver.Client` and use it in `createCampaign` https://github.com/sourcegraph/sourcegraph/pull/6573 & https://github.com/sourcegraph/sourcegraph/pull/6575 
- [x] Return an error in `addChangesetsToCampaign` if `Campaign` has a `CampaignPlan`
- [ ] Implement `retryCampaign` that retries the subprocesses of `createCampaign`
  - [ ] Make `ChangesetJob` execution idempotent: check that new commits are not added to same branch, check for `ErrAlreadyExists` response from code hosts
- [ ] Implement `cancelCampaignPlan` so that all jobs are cancelled
- [ ] Set an upper time limit on `CampaignJob` execution
- [ ] Create changesets for a repositories default branch (right now we open the PR for `master`, [see here](https://github.com/sourcegraph/sourcegraph/blob/5ade8c1edc52688387673eebe0fcd2db033720bc/enterprise/pkg/a8n/service.go#L210))
- [ ] Add metrics/tracing to `previewCampaignPlan` and `createCampaign`

#### Frontend

- [x] Add snapshot tests
- [x] Render campaign description as markdown (in client) @eseliger
- [x] Add dropdown and Monaco editor to `CampaignDetails` form for the `CampaignPlanSpecification`
- [x] Add "Preview" button that triggers a preview, show the planned changesets
  - [x] `ChangesetList` made to work for `ExternalChangeset | ChangesetPreview`
- [ ] Cancel the previous preview with `switchMap`
- [x] Show preview progress with a loading spinner
- [x] Show errors
- [x] Add diff preview using diff components as a tab next to "Changesets"

#### Internal User Testing

- [ ] Test the user flow with a colleague at Sourcegraph

### Leftover from 3.9

- [ ] Only "update" a changeset when it actually changed.
- [x] Support Bitbucket Server changeset events
  - [x] Add `ChangesetEvents` for Bitbucket Server (requires fetching `/activities` for Bitbucket Server changesets) @tsenart 
  - [x] Update CHANGELOG to mention additional requests done by repo-updater to sync A8N data and to warn about its current limits of scalability / potential impact on code host when used beyond a certain scale.
  - [x] Incorporate Bitbucket Server `ChangesetEvents` into burndown chart API 
- [ ] Bitbucket Server webhooks ([RFC](https://docs.google.com/document/d/18RStJNmD9BswkjDwDVDDe792j2UavgqHB_hHE9i3npc/edit))
- [x] Making "adding changesets" work if changesets have been created before. See [comment](https://github.com/sourcegraph/sourcegraph/pull/6041#issuecomment-542568259) and [this issue](https://github.com/sourcegraph/src-cli/issues/52)

### Stretch-Goals

- [ ] Rename `campaign.{name,description}` to `campaign.{title,body}`
- [ ] Shows status of all changesets in the campaign and allow querying/filtering by the following fields
  - [x] Show "open/merged/closed"
  - [x] Show "review status"
  - [ ] Show "commit statuses"
  - [ ] Show "labels"
  - [ ] Filtering fields via GraphQL API
    - [ ] Filter by "open/merged/closed"
    - [ ] Filter by "commit statuses"
    - [ ] Filter by "review status"
    - [ ] Filter by "labels"
- [ ] Show the combined event timeline from all changesets
  - [ ] GraphQL schema
  - [ ] Show comments
  - [ ] Show approvals
- [ ] Show the set of participants involved in the campaign
  - [ ] GraphQL schema

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
