### ISSUE TITLE
Support explicit repository permissions model

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#6086]
This issue is for tracking support of explicit repository permissions model, please see [RFC 40: Explicit Repository Permissions Model](https://docs.google.com/document/d/167WV_rhBg3oj0yw9fHwUMlB-8BR3ktk2FSsKiUQo55Y/edit) for background and design details.

### Implementation Plan

PR: #6427
- [x] Configuration
	- [x] `site.schema.json`
	- [x] Site alert for blocking all accesses when both permission models are configured
- [x] Database migration
	- [x] Migration scripts
	- [x] Update Bitbucket Server Authz Provider to recognize `provider` column
- [x] Package `permsstore`
	- [x] `(*store).LoadUserPermissions`
	- [x] `(*store).LoadRepoPermissions`
	- [x] `(*store).LoadPendingPermissions`
	- [x] `(*store).UpsertRepoPermissions`
	- [x] `(*store).UpsertPendingPermissions`
	- [x] `(*store).RemoveRepoPermissions`
	- [x] `(*store).RemovePendingPermissions`
	- [x] `(*store).SetRepoPermissions`
	- [x] `(*store).SetPendingPermissions`
	- [x] `(*store).GrantPendingPermissions`
	- [x] Verify the design can be reused by Bitbucket Server Provider #6500
	- [x] Verify the design is good for GraphQL APIs
    - [x] Abstract some blocks to functions
	- [x] Think about locking
	- [x] Tests

---

- [ ] GraphQL APIs
	- [ ] Update `schema.graphql`
	- [ ] `setRepositoryPermissionsForUsers`
	- [ ] `addRepositoryPermissionsForUsers`
	- [ ] `removeRepositoryPermissionsFromUsers`
	- [ ] `authorizedUserRepositories`
	- [ ] `usersWithPendingPermissions`
	- [ ] `Repository.authorizedUsers`
	- [ ] Tests https://github.com/sourcegraph/sourcegraph/pull/6427#issuecomment-557392099
- [ ] Inject into [`authzFilter`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@88392bca41bedd7eb90f3a714b2ea020f6a492fd/-/blob/cmd/frontend/db/repos_perm.go#L42:6) https://github.com/sourcegraph/sourcegraph/pull/6427#discussion_r349900524
	- [ ] Block all access when both permission models are configured (`hooks.PreAuthMiddleware`)
- [ ] Handle change of `bind_id` in site config
- [ ] Handle user deletion, also clean up pending permission for the user just in case
- [ ] Clean up `TODO:`s

---

Follow up:
- [ ] https://github.com/sourcegraph/sourcegraph/issues/6859
- [ ] https://github.com/sourcegraph/sourcegraph/issues/6845

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by unknwon** [comment]
Moved to 3.12 since it'd a roadmap item.

**Comment by tsenart** [comment]
@unknwon: Please create individual issues that we can put in the tracking issue unless you plan to finish all of this in 3.12.

What would your estimate be for the remainder of the work? Be conservative :)

**Comment by unknwon** [comment]
Created #7298, #7300, #7301, #7302 and closing this one. Added each of them with estimates to the 3.12 tracking issue.
