### ISSUE TITLE
Claude 3 ready for enterprises: Tracking issue

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#61020]
This is to make claude 3 offering enterprise ready. It involves working prompting, sourcegraph instance configuration to use claude 3, but does not involve quality work.

Slack: https://sourcegraph.slack.com/archives/C068NE5KL8Y/p1710189195259379?thread_ts=1710182295.264049&cid=C068NE5KL8Y
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61166
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61167
- [ ] https://github.com/sourcegraph/cody/issues/3413
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61170
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61325
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61291
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61340
- [x] https://github.com/sourcegraph/sourcegraph/issues/61341
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61339
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61342
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61351
- [ ] https://github.com/sourcegraph/cody/issues/3529
- [ ] https://github.com/sourcegraph/cody/pull/3650
```

**Comment by chwarwick** [comment]
All issues completed
