### ISSUE TITLE
JetBrains stability with regards to self-signed certificates

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#61021]
```[tasklist]
### Tasks
- [x] macOS local certs
- [ ] window local certs
- [ ] linux local certs
```

**Comment by chwarwick** [comment]
@cbart  @aramaraju  I lowered this to a P1 since we completed macOs and windows/linux are not a current priority.

**Comment by cbart** [comment]
I'll close it to declutter the dashboard since this is scoped to a specific customer and seems like our work there is done. @aramaraju correct me if I'm wrong.

**Comment by taylorsperry** [comment]
I'm reopening this and assigning @pkukielka, who's picking up the Windows/Linux portion of this work. Some context in this [thread](https://sourcegraph.slack.com/archives/C01U497GASZ/p1711047171200559).

**Comment by aramaraju** [comment]
Will need to still be done for Win and Linux platforms, so let's have this open

**Comment by chwarwick** [comment]
> Will need to still be done for Win and Linux platforms, so let's have this open

Opened a draft PR with the fixes for Windows and Linux however I do not have the ability to fully test. 
https://github.com/sourcegraph/cody/pull/3752

**Comment by taylorsperry** [comment]
Thank you, @chwarwick! @kalanchan can you help us find an eng with Windows/Linux to test, please?

**Comment by cbart** [comment]
@arafatkatze / @slimsag in your discussions for planning testing of enterprise environments, did you think about parameterizing the box on which the test would run so that we could at least have a manual, but reproducible and automated way of running the full test suite on a specific OS with proxy config?

**Comment by arafatkatze** [comment]
> did you think about parameterizing the box on which the test would run so that we could at least have a manual, but reproducible and automated way of running the full test suite on a specific OS with proxy config?

Great catch Cezary and no that didn't cross my mind at the time. For now Stephen helped me narrow down the scope of this problem to 
<img width="174" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/11155207/5cef429e-15cc-403d-9ad1-a1c2ba64d3ef">
<img width="97" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/11155207/38d9ffea-a90c-4c69-b067-17e60327dfa2">


From [this document
](https://docs.google.com/spreadsheets/d/1He8ECpzJftbBVMqRbQ_jzEOMeT9XcfvXtjycFRtxbVg/edit#gid=0) the idea is to solve for the two cases first fully and then work on things incrementally but yes Ideally it would be very nice to have a reproducible automated way of running things.
