### ISSUE TITLE
🎯 New Release Process Tracking issue

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#61057]
See http://go/releases for the WIP documentation. 

## Problem

During the previous quarter, we built a new process for the release tooling, that ended up being [QA'ed against the 5.3.0 release](https://docs.google.com/document/d/1tkAjgDeglzow9uSoWJlnBKhuSzhf1K0BI5FslzltPjs/edit#bookmark=id.w7o08qqdw14a) to ensure we're producing similar artifacts. 

It has landed on main in #60962 and it's working as intended. The most critical parts of the new release process are now behind us and we can focus on polishing the tooling and assembling all the individual components to form a slick experience for everyone. 

This coincide with [RFC864](https://docs.google.com/document/d/1vZmRx6k-OUpSgrAJ9ovu4qfzrExQDXzWiBYv9XbGEZM/edit) which introduces monthly releases. 

➡️ On this Friday, we'll have a meeting with @kalanchan to make the final decision on what exactly we intend to release on April 5th, which will be the first time we do a monthly release (as opposed to previous approach where we were only releasing patches). 

This tracking issue captures all the remaining work to wrap up the release process entirely and to pass ownership to the Releases team, while the Dev-Infra team will retain ownership on how to build the Sourcegraph server itself. 

RFC for handling minor/major stuff https://docs.google.com/document/d/19nhqFisHi9Y9KeCZuShxuVKyZKJNRj9Udxr3tJIzeb8/edit

## Success criteria

- N% of customer facing porducts that uses the new process
- N teams have written release tests
- N internal builds have been shipped to an external customer 

### ✅ Setup  

- [x] Land the new release process on `main` 
- [x] Ensure the new process works when build on Aspect Workflows. 
- [x] Perform an internal release straigh from `main` 

### ➡️ April 5th (Deadline 2024/04/02)  

The April 6th release should use the new release process. In the eventuality of an absolute blocker we'd discover at the last minute, we should still be able to use the old release process. 

- Must do (we can't release without those):
  - #61060
  - #61061
  - #61063
  - #61064
  - #61159
  - #61067
  - #61062
    - Hard part was done, release manifest have been refined for clarity and reliability. 
    - It's just about reporting the changes on the rest, which is mechanical and running the process with a `QA-` prefixed public tag.
    - Remember to compare the final result against a previous release. 
  - #61071
  - #61072
  - #61589
- Ok to delay (we can work around it if we can't get the done on time) 
  - #61065
    - If the internal AMIs are still public, as long as you can't pull them by accident, we're fine. It's a perfecly legit solution, we could close this ticket. 
  - #61066
  - #61068 
    - Can be QA'ed manually (just inspect the final container and check that the schemas are there)
  - #61069
    - Can be run manually. 
  - #61070
  - #61073
  - #61074
  - #61075
  - #61323

### 📆 Automation (Deadline 2024/04/31) 

At this point, this is just about polishing and reaping the benefits of the new process. 

Please don't take anything from here until we've fixed everything in the previous milestone (w/ the exception of event based issues or time based ones or if you strongly believe doing it earlier will help). 

- [x] Deploy release registry on MSP
- [x] Add persistant storage to the release registry
- #61076
- [x] Release registry can compute version numbers on its own 
- #61077
- #61078
- #61079
- #61080
- #61081
- #61082
- #61083
- #61084
- #61085
- #61086
- #61088
- #61089
- #61090
- #61091
- [ ] #62081
- [x] [Version the release registry API](https://github.com/sourcegraph/releaseregistry/issues/22)
- [ ] sg release should check that current branch isn't behind its remote
- [ ] automate changelog clone to `sg/docs`
- [x] automate release creation

### 📆 Normalizing all products (Deadline 2024/05/15) 

- [ ] #61094
- [ ] #61095
- [ ] #61096
- [x] #61114

### 📆 Shipping internal builds to external customers (ETA 2024/05/15)

In some cases, we want to ship an internal build to customers, usually to demonstrate that we fixed a bug. The best approach there is to publish images to a custom registry that the customer can pull from. 

- #61097
- #61098

### 📆 Wrap-up (Deadline 2024/05/01) 

- #61099

---

## Tracked issues

@unassigned

- [ ] https://github.com/sourcegraph/sourcegraph/issues/61410
