### ISSUE TITLE
🎯 New docsite wrap ups

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#61227]
See [this doc](https://docs.google.com/document/d/1vRmu5VA-zKJRSV4ilTRQOE4eJ7_jbsZ8MUbKlcA9TYw/edit) for context. 

### Plan

- [ ] Update all templates for generated documentation to match their counterpart on github.com/sourcegraph/docs 
- [ ] Add a delivery job on `main` that pushes updates to generated docs as a PR on github.com/sourcegraph/docs. 
- [ ] Docsite serves HEAD docs from a specific commit if unversioned (for everything but dev docs) 
- [ ] Remove all legacy documentation (dev docs excepted) as everything is in the new docsite
- [ ] Remove safety check that prevents to merge doc changes 
- https://github.com/sourcegraph/sourcegraph/issues/61085
- [ ] Docsite serves all version <5.3.0 with a banner indicating this is the legacy documentation. 
- [ ] Docsite redirects straight to sourcegraph.com/docs if asked for a version >5.3.0 
- [ ] Docsite is now hosted at docs-legacy.sourcegraph.com 
- [ ] Docsite redirects from docs.sourcegraph.com to docs-legacy.sourcegraph.com
