### ISSUE TITLE
Web: 3.10 tracking issue

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#6122]
### [RFC 10](https://docs.google.com/document/d/1Vo7HlwO_HgrK8O-VEIZ9wHuSyHdEA0zk9qucNCoF0jg/edit)

RFC 10 is about making search filters discoverable and easy for everyone.

**OKR: 2.b.iv - Make the power of search accessible to more users**

**Planned work for 3.10:**
- [ ] 🏃Finish [RFC 14](https://docs.google.com/document/d/1vSzZayA6p-znJ-7y8XrdlzluvZhboYytEuQ465_TTM4/edit): Showing users suggestions of filters & filter values as they type into the search bar, and highlighting valid filters in search queries. @hadrian-git 
    - [x] 🏃 Show suggested filters & filter values from https://github.com/sourcegraph/sourcegraph/pull/5859 when the user types: https://github.com/sourcegraph/sourcegraph/pull/6105
    - [ ] Keep the suggestions close to what is being typed by pinning the suggestions dropdown to the first character of the filter being typed.
    - [ ] Highlight valid filters in the query.
    - [ ] Redirect the user to the appropriate repo/file page when he types an exact repo/file filter.
- [ ] 🏃 Start work on [RFC 15](https://docs.google.com/document/d/1_rIshE3pBG4FKrytl4PbyqI_EEX8dL1dgmOwMbDrszo/edit#heading=h.uwk7ypaomhxf): split the search UX into two modes, omni and interactive.  @attfarhan 
    - [ ] ~🏃 Reach a consensus on [RFC 65](https://docs.google.com/document/d/15VPfvnPC9xi7VUj6crrZAujRokZX_wWdVZrWuMNBtqM/): frontend query parser implementation.~
    - [ ] ~Implement [RFC 65](https://docs.google.com/document/d/15VPfvnPC9xi7VUj6crrZAujRokZX_wWdVZrWuMNBtqM/edit#)~
    - [ ] 🏃Start implementing interactive mode: implement the repository filter in interactive mode. We'll keep this behind a feature flag.

### [RFC 61](https://docs.google.com/document/d/1ayxlx5AqX8senGkxYc4Gcy4c5Irpm_5gR8JHMsnu5D8/edit)

RFC 61 is about integrating Sourcegraph natively into GitLab, for gitlab.com and self-hosted GitLab instances.

**OKR: 1.e - Increase engagement with the product**

**Planned work for 3.10:**
- [x] 🏃 Merge [GitLab MR #16556: Add Sourcegraph integration](https://gitlab.com/gitlab-org/gitlab/merge_requests/16556) @felixfbecker 
    - [x] Fix outstanding GitLab bugs:
        - [x] Gitlab: unable to determine revision or file path #6009
        - [x] Gitlab: unable to file information (no-commit-sha) #6010
        - [x] Command palette overflows on Gitlab #6150
        - [x]  Browser extension CSS modifies Gitlab alert style #6151
    - [ ] Plan progressive rollout of GitLab.com <-> Sourcegraph.com integration

## Customer issues

- [ ] Survey page fails to load properly https://github.com/sourcegraph/issues-uber/issues/211 @lguychard

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
