### ISSUE TITLE
Epic: search syntax highlighting

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#62164]
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/60235
- [ ] https://github.com/sourcegraph/sourcegraph/issues/19469
- [ ] https://github.com/sourcegraph/sourcegraph/issues/16141
```
