### ISSUE TITLE
Fuzzy finder

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#62426]
... or something that resembles it.

My suggestion would be to try to use the same fetcher/caching logic as the search input, because that should be relatively reusable. If that doesn't work or doesn't provide the same results as the current fuzzy finder we can try to refactor the existing one to decouple it more from React.

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/pull/62494
- [ ] Add support for toggle between repo and global (?)
- [ ] Add result count
- [ ] Add empty state
```

**Comment by taiyab** [comment]
Follow up to this: https://github.com/sourcegraph/sourcegraph/issues/62673
