### ISSUE TITLE
Svelte: Milestone 3 Umbrella form small UI/UX improvements

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#62492]
For milestone 3 (June release) we want to address the following list of 
UI/UX problems

- [ ] Add a hover state for the search result block's header to solve the problem of aiming the action buttons at the end of the row on big screens ([Slack message with feedback](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1715087088061529))
- [ ] Add custom platform identical scrollbars for scrollable blocks
- [ ] Add highlighting search matches for the revision picker suggestions
