### ISSUE TITLE
Rockskip: improve test coverage 

### ISSUE THREAD

**Issue by jtibshirani** [sourcegraph/sourcegraph#62550]
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/pull/62510
- [ ] https://github.com/sourcegraph/sourcegraph/pull/62549
- [ ] https://github.com/sourcegraph/sourcegraph/pull/62557
- [ ] https://github.com/sourcegraph/sourcegraph/pull/62581
- [ ] https://github.com/sourcegraph/sourcegraph/pull/62686
```

/cc @sourcegraph/search-platform

**Comment by jtibshirani** [comment]
Closing this out. I'm tracking the final item "Enable Rockskip in integration tests" separately.
