### ISSUE TITLE
chore: fix playwright tests in web-sveltekit

### ISSUE THREAD

**Issue by bahrmichael** [sourcegraph/sourcegraph#62821]
In [https://github.com/sourcegraph/sourcegraph/pull/62820](https://github.com/sourcegraph/sourcegraph/pull/62820) I disabled tests that were failing in `client/web-sveltekit`.

You can run them with `pnpm t` after navigating to `client/web-sveltekit`.

```
### Tasks
- [ ] load file
- [ ] default editor link
- [ ] editor link
- [ ] code host link
- [ ] dropdown menu
- [ ] view modes
- [ ] meta data
- [ ] initial page load
- [ ] initial page load with selected line
- [ ] go to another file
- [ ] select a line
- [ ] [back] preserve scroll position
- [ ] [forward] preserve scroll position
- [ ] [back] preserve scroll position with selected line
- [ ] non-existent file
- [ ] error loading file data
- [ ] error loading highlights data
- [ ] basic functionality
- [ ] error handling root
- [ ] error handling children
- [ ] error handling non-existing directory -> root
- [ ] list branches
- [ ] list tags
- [ ] has search button
- [ ] main navbar menus are visible above search input
- [ ] can be opened and closed
- [ ] can iterate over matches
 
```
