### ISSUE TITLE
Automation Tracking Issue 3.11

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6663]
### Goals

* Improve stability & performance
* Improve developer speed & UX by refactoring and paying off tech debt
* [RFC 73 REVIEW: Campaigns to find and remove credentials](https://docs.google.com/document/d/143FIe1Tak4_YPPuOuEzuobTQW09ZU85WfOCdZkNwIVQ/edit#heading=h.b5eblutsndzz)

### Availability

* @mrnugget not working 21. November
* @mrnugget, @tsenart, @eseliger & @felixfbecker in Berlin from 25.-29. November
* @eseliger & @felixfbecker in San Francisco from 3.-10. December

### Backend

While working on the tasks below, we continuously refactor existing code, pay off tech debt and continuously improve developer UX: #6572

##### Enabling Frontend

- [x] Extend graphql schema by head/base for codeintel https://github.com/sourcegraph/sourcegraph/pull/6750
- [x] a8n: Align API for previews and external changesets https://github.com/sourcegraph/sourcegraph/issues/6752

##### Bugs & Housekeeping

- [x] Create changesets for a repository's default branch #6682
- [x] Replacer service is never started by server in the docker image https://github.com/sourcegraph/sourcegraph/issues/6711
- [x] For some repositories `gitserver` cannot apply the diff #6625 
- [x] Non-manual Campaigns cannot be deleted due to foreign-key constraint https://github.com/sourcegraph/sourcegraph/issues/6659
- [x] Improve error responses in gitserver when applying diff fails https://github.com/sourcegraph/sourcegraph/issues/6717 
- [x] Set an upper time limit on `CampaignJob` execution https://github.com/sourcegraph/sourcegraph/issues/6720
- [x]  replacer service responds with 503 with cold cache https://github.com/sourcegraph/sourcegraph/issues/6766 
- [x] Syncing 24 GitHub pull requests fails due to GraphQL node limit reached #6658
- [x] Handle the deletion of external services and repos https://github.com/sourcegraph/sourcegraph/issues/6727 
- [x] Add tracing to `previewCampaignPlan` and `createCampaign` https://github.com/sourcegraph/sourcegraph/issues/6721
- [x] a8n: Generated diff has not a deterministic order https://github.com/sourcegraph/sourcegraph/issues/6910#event-2841037775

##### Features

- [x] Campaign type to remove NPM credentials https://github.com/sourcegraph/sourcegraph/issues/6852 (First part of [RFC 73](https://docs.google.com/document/d/143FIe1Tak4_YPPuOuEzuobTQW09ZU85WfOCdZkNwIVQ/edit#heading=h.b5eblutsndzz)) 
- [x] Implement `retryCampaign` that retries the subprocesses of `createCampaign` https://github.com/sourcegraph/sourcegraph/issues/6718
  - [x] a8n: External branch names should be more unique https://github.com/sourcegraph/sourcegraph/issues/7088 @ryanslade 
- [x] Implement `cancelCampaignPlan` so that all jobs are cancelled https://github.com/sourcegraph/sourcegraph/issues/6719
- [x] Allow closing and deleting of Campaigns https://github.com/sourcegraph/sourcegraph/issues/7082 @mrnugget 
- [ ] Execute `ChangesetJob`s in parallel https://github.com/sourcegraph/sourcegraph/issues/6722
- [ ] Upsert ChangesetEvents from Bitbucket Server webhooks https://github.com/sourcegraph/sourcegraph/issues/6726
- [ ] Gracefully handle changeset deletion in code hosts #6396

### Frontend

- [x] Add more snapshot tests (CampaignDetails)
- [ ] Cancel the previous preview using `switchMap`
- [x] Write E2E or regression tests, evaluate runtime
- [ ] Implement code intelligence for external changeset diffs #6749 #6752
- [ ] Split `CampaignDetails` component into more manageable components
- [ ] General UI polish + incorporate changes requested by christina
- [ ] Prototype for json-schema2form-generator @felixfbecker 
- [ ] Proposal/RFC for campaigns through extension API
- [ ] Hide burndown chart if data is empty
- [x] Don't show editor for manual
- [x] Make campaign type dropdown a label in read-only mode
- [x] Add `retryCampaign` button @eseliger
- [ ] UI for closing a campaign and showing that a campaign is closed
- [ ] UI for closing a campaigns changesets when closing/deleting the campaign

### Internal User Testing

- [ ] Test the user flow with colleagues at Sourcegraph

**Comment by tsenart** [comment]
Looking great!

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
