### ISSUE TITLE
Web: 3.11 tracking issue

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#6664]
## Roadmap

**OKR: 2.b.iv - Make the power of search accessible to more users**

**Planned work for 3.11:**
- [ ] ⚠️ Finish [RFC 14](https://docs.google.com/document/d/1vSzZayA6p-znJ-7y8XrdlzluvZhboYytEuQ465_TTM4/edit): Showing users suggestions of filters & filter values as they type into the search bar, and highlighting valid filters in search queries. @hadrian-git 
    - [ ] ⚠️ Highlight valid filters in the query.
- [x] ✅[RFC 15](https://docs.google.com/document/d/1_rIshE3pBG4FKrytl4PbyqI_EEX8dL1dgmOwMbDrszo/edit#heading=h.uwk7ypaomhxf): split the search UX into two modes, omni and interactive.  @attfarhan 
    - [x] ✅Implement interactive mode. We'll keep this behind a feature flag.

**OKR: 1.e - Increase engagement with the product**

**Planned work for 3.11:**
- [x] ✅GitLab post-merge [follow-ups](https://gitlab.com/groups/gitlab-org/-/epics/2201)
    - [x] ✅Fix hover overlay z-index issues: #6520, [RFC 76](https://docs.google.com/document/d/1albi6HaAU9JAqdQXjsE-50NidxG4icE-36XqxxKgfM4/edit#heading=h.7f7hbn3miqi9), https://gitlab.com/gitlab-org/gitlab/issues/36415 => https://github.com/sourcegraph/codeintellify/pull/196, https://github.com/sourcegraph/sourcegraph/pull/7023
- [ ] Python imports search extension: remove see all usages links by default. https://github.com/sourcegraph/issues-uber/issues/218 @attfarhan

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
