### ISSUE TITLE
Structural search improvements and documentation

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#6679]
These are work items improve the quality of structural search in 3.11:

- [ ] Get match patterns to hit the index where spaces in structural search patterns can match newlines
  - [x] PR #6851 
  - [ ] e2e integration test
- [x] Address zip issues (`Assert_failure zip.ml:212:4`) #7134 
- [x] Address worker management
  - [x] Orphaned process management (partial solutions: #7177 #7162)
  - [x] Gracefully handle worker OOM #7187
- [x] Honor `lang` parameter scope #7179
- [x] Multiline highlighting #6899, #7018
- [x] Add experimental flag (default ON, with possibility to disable) #7194
- [x] `where` rule filter #7180 
- [ ] Documentation

Triaged items for 3.12 are tracked in #7234.

**Comment by rvantonder** [comment]
Stability and usability issues so far:

1. OOM related: fetching archives

<img width="1432" alt="Screen Shot 2019-11-22 at 1 29 00 AM" src="https://user-images.githubusercontent.com/888624/69410572-90c45580-0cc8-11ea-9d6e-55b1aaf71e77.png">

The tars can be quite big (5+ GB, probably stuff like linux):

<img width="279" alt="Screen Shot 2019-11-22 at 1 39 51 AM" src="https://user-images.githubusercontent.com/888624/69410870-1ea04080-0cc9-11ea-8d08-1fc032d8b0fe.png">

Worker OOM, probably because git archive is loaded into memory:

<img width="1000" alt="Screen Shot 2019-11-15 at 12 31 34 AM" src="https://user-images.githubusercontent.com/888624/69410666-bbaea980-0cc8-11ea-844e-7e69dd4d294e.png">

Investigate why doesn't `rg` doesn't run into this. Perhaps streams, but structural search should also be using streams?

Worker exits abnormally, probably OOM related:

<img width="1107" alt="Screen Shot 2019-11-15 at 12 09 57 AM" src="https://user-images.githubusercontent.com/888624/69410736-daad3b80-0cc8-11ea-9aa2-33b798c382dd.png">

2. Corrupt zip. Probably not archive related, since (a) there is enough space and (b) I've seen this specific repo/zip cause recurring crashes

<img width="797" alt="Screen Shot 2019-11-22 at 1 23 38 AM" src="https://user-images.githubusercontent.com/888624/69410620-a89bd980-0cc8-11ea-9a84-dec32937345f.png">

3. No idea. How is this possible.
<img width="965" alt="Screen Shot 2019-11-22 at 1 28 14 AM" src="https://user-images.githubusercontent.com/888624/69410603-a0dc3500-0cc8-11ea-8d53-df11e6371853.png">

4. In general, running search requests (orphaned processes?) probably due to (1) or to a lesser extent (2). Confirm locally. 

<img width="291" alt="Screen Shot 2019-11-22 at 1 46 06 AM" src="https://user-images.githubusercontent.com/888624/69411353-067cf100-0cca-11ea-8174-7edcb8401e71.png">

5. Wishlist: pattern without quotes issue
<img width="1243" alt="Screen Shot 2019-11-15 at 12 17 32 AM" src="https://user-images.githubusercontent.com/888624/69410697-c9fcc580-0cc8-11ea-892e-be1db465a784.png">

**Comment by chrismwendt** [comment]
I see a "Searching literally" message when using `patterntype:structural` (more context in https://github.com/sourcegraph/sourcegraph/issues/6994)

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Closing, but will update items that will happen by 3.11 release.
