### ISSUE TITLE
Index multiple (non-master) branches

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#6728]
Requested by https://app.hubspot.com/contacts/2762526/company/554338610

From the customer:

* Yes we see performance issues and timeouts
* some core repos are big. Like 4Gb/repo
* Can we keep it on end user how many they want to index ? (I understand its resource heavy). But still i would say 5 branches should be allowed. And yes it can change depending on release cycles.

Related to https://github.com/sourcegraph/sourcegraph/issues/89

Not 100% sure who to tag, so I guessed here. Still needs prioritization from @christinaforney.

**Comment by keegancsmith** [comment]
This requires a bit more work than you may expect, since in multiple places we assume we are dealing with master branch only. Additionally zoekt has some great stuff around reducing the size of the index across multiple branches which we would want to integrate. So I think this is a great feature to add, but for context when prioritising it will require an iteration worth of work from someone.

**Comment by keegancsmith** [comment]
Leaving unassigned until someone works on it, the team/core-services label is enough for us to find it :)

**Comment by keegancsmith** [comment]
The spike for 3.13 is to get zoekt's indexserver indexing multiple branches without any other regressions/feature added to our product. IE we still just search over HEAD. Once we have done that spike, we will be in a better position to estimate the rest of the work. See below an outdated comment I wrote up:

> My estimate of 4 days is to achieve the following:
> - Index multiple branches in zoekt (via simple setting, don't know how yet)
> - Don't regress on any place we inspect zoekt indexes (lots of different searches rely on it)
> - Make normal text search use it.

**Comment by keegancsmith** [comment]
@sourcegraph/core-services this is actually quite tricky to implement with our current tarball interface. So please comment with ideas / responses to the information below.

### Current implementation

Indexing is done by `zoekt-archive-index`, a command we implemented which can index tarballs. It's based on streaming in the file and creating the zoekt index, hence tarball being ideal (and git can efficiently create tarballs via `git archive`). We don't actually store the intermediate tarball on disk, since it can be processed directly from the stream.

Zoekt's branch support is done via annotating each indexed document with the list of branches it is part of. This allows for much smaller indexes since it can be assumed most files are identical across tracked branches. IE if `foo.go` is the same on both branches, there is one document for `foo.go` with both branches in its annotations. If different there are two documents for `foo.go` each with the different content and branch list. The crux is we pass documents to the indexer, so we need to know this information up front. Here-in lies the conundrum, since we can't efficiently join 2 (or more) tarball streams.

The way zoekt does it in its upstream setup is to directly index git repos. It directly inspects the git objects involved, so it can walk over and decide if two files are the same very efficiently.

### Ideas

- Store intermediate tarballs. Process them to produce a mini index of which paths are unique/etc. Probably just use a simple hash based approach, or investigate relying on git including metadata for the OID. This index can then be used when constructing the indexes.
- Instead of constructing an index, rely on `git ls-tree` outputs. This seems reasonable.
- Expose a "remote git" interface so we can rely on what upstream zoekt does. This seems slow to me.
- Produce a custom archive format from the gitserver with this information. This isn't as crazy as it sounds, since once we have this piece it allows us to do lots of different things.

**Comment by mrnugget** [comment]
> The crux is we pass documents to the indexer, so we need to know this information up front. Here-in lies the conundrum, since we can't efficiently join 2 (or more) tarball streams.

Can you explain this a bit more? I think I understood everything up to this point, but I got lost here. What is meant with "indexer" and "documents" here? I thought we pass tarballs to the indexer (and naively assumed that we can tell zoekt "this tarball belongs to repo X's branch Y").

**Comment by tsenart** [comment]
@keegancsmith: What if we actually cloned the git repo (temporarily) locally for zoekt to index it? Would it be that much slower that the tarball?

**Comment by keegancsmith** [comment]
> > The crux is we pass documents to the indexer, so we need to know this information up front. Here-in lies the conundrum, since we can't efficiently join 2 (or more) tarball streams.
> 
> Can you explain this a bit more? I think I understood everything up to this point, but I got lost here. What is meant with "indexer" and "documents" here? I thought we pass tarballs to the indexer (and naively assumed that we can tell zoekt "this tarball belongs to repo X's branch Y").

Zoekt creates a combined index for a repo across multiple branches. IE it natively understands the concept of a branch. The way the archive indexer works is by iterating over the archive and creating a zoekt.Document per archive file and passing that to the indexer. Part of a zoekt.Document is which branches a Document is for. In particular see this line in the current implementation https://github.com/sourcegraph/zoekt/blob/2f3fa2c3ee1919d37a452c221ffb2a209a0fdfcd/cmd/zoekt-archive-index/main.go#L192

We need to update zoekt-archive-index to support multiple branches if we want to use zoekt branch support. That line will change to the branches for that document. Say you have two branches you are indexing and `README.md` is the same on both. Then you should create one `zoekt.Document` with Branches set to both branches. If they differ, then we need to create a `zoekt.Document` per branch.

> @keegancsmith: What if we actually cloned the git repo (temporarily) locally for zoekt to index it? Would it be that much slower that the tarball?

This would be much slower. The working copy of a repository is _much_ smaller. We could look into sparse clones / etc, but they still involve fetching a lot of extra information.

### Todays investigation

- [metadata in archives](#org20ef2b3)
    - [zoekt-archive-index detects content type](#orgec85232)
    - [zoekt-archive-index supports zips](#org385eebb)

<span class="timestamp-wrapper"><span class="timestamp">[2020-01-20 Mon 17:07]</span></span>


<a id="org20ef2b3"></a>

# metadata in archives

```go
package main

import (
    "archive/tar"
    "archive/zip"
    "bytes"
    "fmt"
    "io"
    "log"
    "net/http"
    "os"
    "os/exec"
)

func archive(format string) []byte {
    cmd := exec.Command("git", "archive", "--format", format, "HEAD")
    if len(os.Args) > 1 {
        cmd.Dir = os.Args[1]
    }
    var out bytes.Buffer
    cmd.Stdout = &out
    if err := cmd.Run(); err != nil {
        log.Fatal(format, err)
    }
    return out.Bytes()
}

func doZip() {
    b := archive("zip")
    zr, err := zip.NewReader(bytes.NewReader(b), int64(len(b)))
    if err != nil {
        log.Fatal(err)
    }

    fmt.Println("Content-Type:", http.DetectContentType(b))
    fmt.Println("Comment:", zr.Comment)
    for i, f := range zr.File {
        if i == 5 {
            break
        }
        fmt.Printf("%q {Comment: %q, CRC32: %d, Extra: %q}\n", f.Name, f.Comment, f.CRC32, string(f.Extra))
    }
}

func doTar() {
    b := archive("tar")
    fmt.Println("Content-Type:", http.DetectContentType(b))
    r := tar.NewReader(bytes.NewReader(b))
    for i := 0; i < 5; i++ {
        h, err := r.Next()
        if err == io.EOF {
            return
        }
        if err != nil {
            log.Fatal(err)
        }
        fmt.Printf("%q %q %q\n", h.Name, h.Xattrs, h.PAXRecords)
    }
}

func main() {
    fmt.Println("ZIP")
    doZip()
    fmt.Println("\nTAR")
    doTar()
}
```

    ZIP
    Content-Type: application/zip
    Comment: b097d736b23d4b52572ffe476c198349083b22d8
    ".bash_darwin" {Comment: "", CRC32: 1509042833, Extra: "UT\x05\x00\x01֘\x13^"}
    ".bash_logout" {Comment: "", CRC32: 4179832495, Extra: "UT\x05\x00\x01֘\x13^"}
    ".bash_profile" {Comment: "", CRC32: 4028417853, Extra: "UT\x05\x00\x01֘\x13^"}
    ".bashrc" {Comment: "", CRC32: 2998635290, Extra: "UT\x05\x00\x01֘\x13^"}
    ".beetsconfig" {Comment: "", CRC32: 2842374341, Extra: "UT\x05\x00\x01֘\x13^"}
    
    TAR
    Content-Type: application/octet-stream
    "pax_global_header" map[] map["comment":"b097d736b23d4b52572ffe476c198349083b22d8"]
    ".bash_darwin" map[] map[]
    ".bash_logout" map[] map[]
    ".bash_profile" map[] map[]
    ".bashrc" map[] map[]

Both ZIP and Tar don't seem to encode useful metadata, other than global metadata indicating the commit SHA an archive was exported from. Zip has the benefit of random access and a CRC32 to help quickly establish files that are different (still need to check same though since crc32 collisions are not that rare). If we had the git OID of each file I'd feel more comfortable just relying on that to determine sameness.

So the "simple" path forward is to download the zip file(s) and merge them.


<a id="orgec85232"></a>

# DONE zoekt-archive-index detects content type

```go
func detectContentType(r io.Reader) (string, io.Reader, error) {
    var buf [512]byte
    n, err := io.ReadFull(r, buf[:])
    if err != nil && err != io.ErrUnexpectedEOF {
        return "", nil, err
    }

    ct := http.DetectContentType(buf[:n])

    // If we are a seeker, we can just undo our read
    if s, ok := r.(io.Seeker); ok {
        _, err := s.Seek(int64(-n), io.SeekCurrent)
        return ct, r, err
    }

    // Otherwise we need to return a new reader which merges in the read bytes
    return ct, io.MultiReader(bytes.NewReader(buf[:n]), r), nil
}
```

zoekt-archive-index: support gzip via content detection (I5579da64) https://gerrit-review.googlesource.com/c/zoekt/+/251278


<a id="org385eebb"></a>

# TODO zoekt-archive-index supports zips

Implementing this upstream. I have a working implementation for files on disk, need to implement it for files fetched from the network.

```shell
rm ~/.zoekt/zoekt_v15.00000.zoekt; go build ./cmd/zoekt-archive-index && ./zoekt-archive-index -name zoekt -branch master zoekt.tar
```

**Comment by keegancsmith** [comment]
I have filed a more specific issue about what we want to achieve in 3.13 and have removed this from the milestone: https://github.com/sourcegraph/sourcegraph/issues/7930

I think in 3.14 we should be able to integrate that change into sourcegraph and close this out.

**Comment by keegancsmith** [comment]
I'm being lazy and adding the 10d estimate, rather than breaking this task down further. Treat this like a placeholder while we do planning. Expect this estimate to disappear and subtasks to appear next week.

**Comment by keegancsmith** [comment]
I've specced out the work needed for this. I have spent today heads down getting the first item done (internal endpoint for git clone). Ran into quite a few problems with getting shallow clones to work, but have a prototype which support git protocol v2 and shallow clones. I wanted protocol v2 for less chatty cloning, but from debugging it seems for shallow clones/fetches it still is quite chatty. But won't spend too much time on that now, and rather just validate perf/etc.

- Validation
  1. TODO internal endpoint for git clone
  2. TODO validate performance of shallow git clone vs archive in prod
- Use zoekt-git-index
  1. TODO indexserver deciding to incremental index seperate to indexing
  2. TODO indexserver does shallow git clone
  3. TODO indexserver uses zoekt-git-index, but uses name HEAD
- Index multipe branches
  1. TODO sourcegraph-frontend supports branches not named HEAD, ignores others
  2. TODO indexserver get config including branches to index
  3. TODO indexserver resolves all branches and passes them to indexing stage
- Use all indexed branches
  1. TODO sourcegraph-frontend uses indexed search for all indexed branches

See details for the hacky PoC which I used as a test bed.

<details>

Needs to act like a normal HTTP git clone endpoint. We used to support this, revert in all: Remove git upload-pack support [#3255](https://github.com/sourcegraph/sourcegraph/pull/3255). I would like to avoid frontend proxying like we used to do. Rather we should redirect to the gitserver.

1.  zoekt: `git clone --bare --depth 1 http://sourcegraph-frontend-internal/.internal/git/my/repo`
2.  frontend: redirect to correct gitserver shard
3.  gitserver: has a handler for upload-pack. Might be able to get away with just the exec handler?

4.  [ ] Validate we are using protocol v2
5.  [ ] We redirect instead of proxy
6.  [ ] Optional? use repo ID

```shell
# Shallow clone wasn't working, debugged with
GIT_CURL_VERBOSE=1 git clone --bare --depth 1 http://localhost:3090/.internal/git/fake.local/matcher-refactor

# Now trying a better impl of info-refs.
# Not sure what to do. So gonna investigate v2 instead
curl -H 'Git-Protocol: version=2' 'https://github.com/sourcegraph/go-langserver.git/info/refs?service=git-upload-pack'
curl -H 'Git-Protocol: version=2' 'http://localhost:3090/.internal/git/github.com/sourcegraph/go-langserver/info/refs?service=git-upload-pack'

# Other commands I used
GIT_CURL_VERBOSE=1 git -c protocol.version=2 fetch --no-tags http://127.0.0.1:10810 +e1c0b05f5b9d25459eba30cfb0007cb78ff796bd:refs/heads/go-mod
```


```go
package main

import (
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path"
	"strconv"
	"strings"
)

var uploadPackArgs = []string{
	// Partial clones/fetches
	"-c", "uploadpack.allowFilter=true",

	// Can fetch any object. Used in case of race between a resolve ref and a
	// fetch of a commit. Safe to do, since this is only used internally.
	"-c", "uploadpack.allowAnySHA1InWant=true",

	"upload-pack",
}

func handleUploadPack(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(os.Stderr, "\n\n#######################\n%s %s\n", r.Method, r.URL)

	args := append([]string{}, uploadPackArgs...)
	switch r.Header.Get("Content-Type") {
	case "application/x-git-upload-pack-request":
		w.Header().Set("Content-Type", "application/x-git-upload-pack-result")
		args = append(args, "--stateless-rpc", "--strict", ".")
	case "":
		w.Header().Set("Content-Type", "application/x-git-upload-pack-advertisement")
		w.WriteHeader(http.StatusOK)
		w.Write(packetWrite("# service=git-upload-pack\n"))
		w.Write([]byte("0000"))
		args = append(args, "--advertise-refs", "--stateless-rpc", "--strict", ".")
	default:
		http.Error(w, "Unexpected Content-Type", http.StatusBadRequest)
		return
	}

	body := r.Body
	defer body.Close()

	env := os.Environ()
	if protocol := r.Header.Get("Git-Protocol"); protocol != "" {
		env = append(env, "GIT_PROTOCOL="+protocol)
	}

	cmd := exec.CommandContext(r.Context(), "git", args...)
	cmd.Env = env
	cmd.Stdout = w
	cmd.Stdin = body
	if err := cmd.Run(); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func packetWrite(str string) []byte {
	s := strconv.FormatInt(int64(len(str)+4), 16)
	if len(s)%4 != 0 {
		s = strings.Repeat("0", 4-len(s)%4) + s
	}
	return []byte(s + str)
}

func main() {
	go http.ListenAndServe("127.0.0.1:10811", http.HandlerFunc(handleUploadPack))
	http.ListenAndServe("127.0.0.1:10810", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		u := *r.URL
		u.Host = "127.0.0.1:10811"
		u.Path = path.Join("/repos/foo/bar", u.Path)
		http.Redirect(w, r, u.String(), http.StatusTemporaryRedirect)
	}))
}
```
</details>

**Comment by keegancsmith** [comment]
@asdine to help out after the graphql work you are doing, you can pick up some of the tasks here. In particular the code around zoekt + multiple branches in the sourcegraph frontend. This would be code that lives in `zoekt.go` in the graphql backend. There is a function `zoektIndexedRepos` which takes a list of `RepositoryRevisions` and splits them into two lists: indexed search and non-indexed. What is missing when we move to multiple branches is knowing which one is the default branch ("HEAD"). We can either change the zoekt API to indicate that, or have a documented convention that the first branch is always HEAD. The latter seems like bad coupling/design, but I think it is acceptable (and avoids diverging from upstream).

**Comment by keegancsmith** [comment]
### Index multiple branches

Here is an update on the work I want to tackle this week, hopefully before branch cut. Others can help pick up.

#### sourcegraph-frontend ignores branches not named HEAD

Need to introduce a field to indicate which branch is HEAD, or a convention (such as first branch is HEAD). Doing the convention since that is what is currently does. Just auditing places we read the list of branches:

-   Admin display of a repos indexes just seems to work.
-   Searching breaks in subtle ways because we don't limit searches in the search query we generate. Will have to add some syntax like "branch:HEAD"? Might even justify tracking which branch is HEAD, but I think its safe for us to make the assumption the first branch is always HEAD.
-   symbol search has `indexedSymbols` that just returns true. Will need to return the branch to search. will also need to update symbols search to specify the branch to search. Initially I can just make it check the first branch.

After reading a bit more code I think it will be less hacky to make the idea of the default branch a first class citizen in zoekt.

This work might be interesting to @rvantonder.

#### indexserver get config including branches to index

This can be a simple experimental field. Sent out wip search config endpoint for multiple branches [#10545](https://github.com/sourcegraph/sourcegraph/pull/10545) for others to pick up.

This work might be interesting to @asdine 

#### indexserver resolves all branches and passes them to indexing stage

Performance of resolving non-HEAD branches? Currently resolving HEAD avoids git subprocess so is fast.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
Not much progress was made this week. I ended up only working on this task two days this week. I focussed on smaller tasks around branch cut that would of had a bigger impact if they made it in (since this wouldn't of been ready for branch cut). The current state of this work is still a week out.  The main difficulty at the moment is performance when querying Zoekt. Right now we don't have a way to limit which branches to search against zoekt without creating a very bad query.

Approaches I am considering:
1. Support in Zoekt for our RepositoryRevisions structure. Then we could just naively pass this list down. I am thinking this is ideal.
2. Assuming non-HEAD list of repos to search is small, and creating a zoekt query using the existing infra. I think this is likely quite complicated.
3. Taking the opportunity to redesign how we talk to zoekt, and use sourcegraph repo ID's instead for a more efficient list. I think this is likely not worth it for the delays it would cause.

Now that I have written it down, I'm fairly certain (1) is the correct direction. I'll start exploring that next week.

We also don't have indexing of multiple branches working end to end, but have bits and pieces existing. There is a non-functional PR for the change in sourcegraph's end here https://github.com/sourcegraph/sourcegraph/pull/10545. There is also this change to use the response from sourcegraph in zoekt here https://github.com/sourcegraph/zoekt/pull/45. @asdine maybe you can pick up https://github.com/sourcegraph/sourcegraph/pull/10545 and integrate and test the two to ensure we have this working end to end?

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
This is going out in 3.18. Quoting the changelog entry:

> Revisions listed in `experimentalFeatures.versionContext` or `experimentalFeatures.search.index.branches` will be indexed for faster searching. This is the first support towards indexing non-default branches.

**Comment by dadlerj** [comment]
🎉 @keegancsmith just to confirm, if a company is already using version contexts, and they update Sourcegraph, then all of the branches in those version contexts will have indexes added automatically, correct?

If the version context specifies `"rev": "HEAD"`, will it add a new index, or will that use the existing one for the default branch? Does https://github.com/sourcegraph/sourcegraph/pull/12154 need to be merged first? I only ask because this is already in use, and it could significantly increase memory usage if not (so I want to be ready to warn the existing users).

**Comment by keegancsmith** [comment]
> 🎉 @keegancsmith just to confirm, if a company is already using version contexts, and they update Sourcegraph, then all of the branches in those version contexts will have indexes added automatically, correct?

Yes. You will need to wait until the indexing has happened, but that shouldn't take too long.

> If the version context specifies `"rev": "HEAD"`, will it add a new index, or will that use the existing one for the default branch?

We always will index `HEAD`. The revs found in the version context are added to that list and we deduplicate. So yes, it will use the existing one rather than duplicating an index.

> Does #12154 need to be merged first? I only ask because this is already in use, and it could significantly increase memory usage if not (so I want to be ready to warn the existing users).

I see, so you expect some users may reduce use of version contexts due to increased indexing requirements? If that is so, then I have two follow up actions:

- Merge #12154 and cherry-pick into release branch
- Add configuration to exclude version contexts from indexing. Cherry-pick into release branch.

If you think this is needed, I'll work on that tomorrow.
