### ISSUE TITLE
3.11 release tracking issue

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#6792]
# 3.11 Release (2019-11-20)

**Note:** All `yarn run release ...` commands should be run from `dev/release` in the [sourcegraph repository](https://github.com/sourcegraph/sourcegraph).

## 2019-11-13 (5 working days before release): Prepare for branch cut

- [ ] In the [Retrospectives folder](https://drive.google.com/drive/u/0/folders/1UiNZujRgsThPFkHoWJvymlsNDsBRtn6O), copy the previous retrospective   doc into the current one (which should contain placeholder text).
- [ ] Post to #dev-announce that all CHANGELOG updates should be in `master` ASAP (before tomorrow).
  Otherwise, they won't be included in the release.
- [ ] Use `./dev/release-ping.sh` to ping teammates who have open issues / PRs in the milestone to
  ask them to triage those that won't make it into the release.
- [ ] Verify there is a draft of the release blog post.

## 2019-11-16 (4 working days before release): Branch cut

- [ ] Verify for each CHANGELOG item the following (if any item does not have these, disable it,
  notify the owner, and remove it from the CHANGELOG):
  - It has an owner attached to it
  - It has undergone manual QA (and the QA was done on k8s.sgdev.org or at scale if the feature requires it).
  - It is covered by the regression test suite
- [ ] Add a new section `## 3.MINOR` to [CHANGELOG.md](https://github.com/sourcegraph/sourcegraph/blob/master/CHANGELOG.md#unreleased) immediately under `## Unreleased changes`. Add new empty sections under `## Unreleased changes` ([example](https://github.com/sourcegraph/sourcegraph/pull/2323)).
- [ ] Create the `3.11` branch off the CHANGELOG commit in the previous step: `git branch 3.11 && git push origin 3.11`.
- [ ] Tag and announce the first release candidate:
  ```
  yarn run release release-candidate:create 3.11.0-rc.1
  yarn run release release-candidate:announce 3.11.0-rc.1
  ```
- [ ] Run regression tests:
  - [ ] New Sourcegraph Docker container:
    - Run the initializer: `E2E_INIT=true SOURCEGRAPH_BASE_URL=http://localhost:7080 yarn run test-regression -t 'Initialize new Sourcegraph instance'`
    - Run the regression test suite: `SOURCEGRAPH_BASE_URL=http://localhost:7080 yarn run test-regression`
  - [ ] Upgrade from previous release:
    - Run the initializer on a Docker container running the last patch version of the previous major/minor release.
    - Upgrade and run the regression test suite.
  - [ ] New Sourcegraph Kubernetes cluster:
    - Run the initializer on a new Sourcegraph Kubernetes cluster.
    - Run the regression test suite.

## 2019-11-16 - ONE_WORKING_DAY_BEFORE_RELEASE Daily: Cut new release candidates

As necessary, `git cherry-pick` bugfix (not feature!) commits from `master` into the release branch.
Aggressively revert or disable features that may cause delays.

- [ ] Review [all release-blocking issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Asourcegraph+label%3Arelease-blocker). Add them as checklist items here. Ensure someone is resolving each.
- [ ] Review [all other open issues in the milestone](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Asourcegraph+-label%3Arelease-blocker+milestone%3A3.11) and ask assignees to triage them to a different milestone (preferring Backlog).

Daily, cut a new release candidate if necessary:

- [ ] Cut and announce release candidate:
  ```
  N=<release-candidate-number> yarn run release release-candidate:create 3.11.0-rc.$N
  N=<release-candidate-number> yarn run release release-candidate:announce 3.11.0-rc.$N
  ```
- [ ] Re-run the automated test suite against the new release candidate, file any regressions as
  `release-blocker` issues.
- [ ] If necessary, manually test features or workflows affected by the cherry-pick.

## 2019-11-19 (1 working day before release) Tag final release

- [ ] Tag and announce on Slack the final release:
  ```
  yarn run release release-candidate:create 3.11.0`
  yarn run release release-candidate:announce 3.11.0
  ```
- [ ] Verify the [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/master/CHANGELOG.md) on
  `master` is accurate (no items should have been added since branch cut, but some items may need to
  be removed).
- [ ] Wait for the release Docker images to be available at https://hub.docker.com/r/sourcegraph/server/tags.
- [ ] Cut the Kubernetes cluster release in [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph):
    - [ ] Wait for Renovate to open a PR to update the image tags and merge that PR into `master` ([example](https://github.com/sourcegraph/deploy-sourcegraph/pull/199)).
    - [ ] Create the `3.11` release branch from this commit.
      ```
      VERSION=`3.11` bash -c 'git fetch origin && git checkout origin/master && git branch $VERSION && git checkout $VERSION && git push -u origin $VERSION'
      ```
    - [ ] Tag the `v3.11.0` release at this commit.
        ```
        VERSION='v3.11.0' bash -c 'git tag -a "$VERSION" -m "$VERSION" && git push origin "$VERSION"'
        ```
- [ ] Open (but do not merge) PRs that do the following:
    - [ ] Update the documented version of Sourcegraph ([example](https://github.com/sourcegraph/sourcegraph/pull/2370/commits/701780fefa5809abb16669c9fb29738ec3bb2039)).
    ```
    # With find on macOS:
    find . -type f -name '*.md' -exec sed -i '' -E 's/sourcegraph\/server:[0-9\.]+/sourcegraph\/server:3.11.0/g' {} +
    # With find on Linux:
    find . -type f -name '*.md' -exec sed -i -E 's/sourcegraph\/server:[0-9\.]+/sourcegraph\/server:3.11.0/g' {} +
    # With ruplacer:
    ruplacer --go -t md 'sourcegraph/server:[0-9\.]+' 'sourcegraph/server:3.11.0'
    ```
    - [ ] Update `latestReleaseKubernetesBuild` and `latestReleaseDockerServerImageBuild` ([example](https://github.com/sourcegraph/sourcegraph/pull/2370/commits/15925f2769564225e37013acb52d9d0b30e1336c)).
    - [ ] Update versions in docs.sourcegraph.com header ([example](https://github.com/sourcegraph/sourcegraph/pull/2701/commits/386e5ecb5225ab9c8ccc9791b489160ed7c984a2))
    - [ ] [Update deploy-aws version](https://github.com/sourcegraph/deploy-sourcegraph-aws/edit/master/ec2/resources/user-data.sh#L3)
    - [ ] [Update deploy-digitalocean version ](https://github.com/sourcegraph/deploy-sourcegraph-digitalocean/edit/master/resources/user-data.sh#L3)
    - [ ] Message @slimsag on Slack: `3.11.0 has been released, update deploy-sourcegraph-docker as needed`
- [ ] Review [all issues in the release milestone](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Asourcegraph+milestone%3A3.11). Backlog things that didn't make it into the release and ping issues that still need to be done for the release (e.g. Tweets, marketing).
- [ ] Verify the blog post is ready to be merged.

## 2019-11-20 by 10am: Release

- [ ] Merge the docs PRs created in the previous step.
- [ ] Merge the blog post ([example](https://github.com/sourcegraph/about/pull/83)).

### Post-release

- [ ] Create a placeholder doc in the [Retrospectives folder](https://drive.google.com/drive/u/0/folders/1UiNZujRgsThPFkHoWJvymlsNDsBRtn6O)
  for the 3.11 Retrospective. Add the following text to the document:
  ```
  Placeholder (copy actual contents from previous retrospective after that is completed)
  ```
- [ ] Update `dev/release/config.json` with the parameters for the current release.
- [ ] Create release calendar events, tracking issue, and announcement for next release:
  ```
  # Add calendar events and reminders for key dates in the release cycle
  yarn run release add-timeline-to-calendar

  # Create the release tracking issue (i.e., this issue)
  yarn run release tracking-issue:create

  # Post link to tracking to #dev-announce
  yarn run release tracking-issue:announce
  ```
- [ ] Notify the next release captain that they are on duty for the next release. Include a link to this release issue template.

## $RETROSPECTIVE_DATE: 3.11 retrospective

- [ ] Complete the retrospective
- [ ] Copy over the retrospective to the new retrospective document (which should have a placeholder)
- [ ] Close this issue.
- [ ] Close the milestone.
