### ISSUE TITLE
a8n/core: Expose CI status on changesets

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#7093]
A customer asked for mirroring the CI status on the changeset list. This will probably require a webhook of some sort on the supported codehosts.

---
Proposed schema change
```graphql
enum CIState {
	PENDING # this can probably be mapped to the "awaiting" as well as "running" state of github as well
	PASSED
	FAILED
}

type ExternalChangeset {
	ciState: CIState!
}
```

# Current Status:

This issue has ended up being a lot bigger than originally estimated as it consists of the following parts:

- [X] Fetch GitHub commit / context status
- [x] Fetch GitHub CheckSuite status
- [x] Fetch GitHub CheckRun status
- [X] Handle GitHub webhooks for commit status
- [x] Handle GitHub webhooks for CheckSuite
- [x] Handle GitHub webhooks for CheckRun
- [x] Fetch BitBucket build status
  - [x] ~Set up CI somewhere to test~ Add status using API
- [ ] Handle BitBucket build status webhook

**Comment by ryanslade** [comment]
@eseliger What would you like the backend to return if the repo doesn't have CI configured? Should we make it nullable?

For now I'll just make it return `PASSED`

Also, shall we try integrating on the same branch? It's unlikely that we'll conflict and that way I can add a dummy handler very quickly that just returns a random status so that you can begin work on the UI.

**Comment by eseliger** [comment]
Ah yes nullable seems good!

Sure let’s do that :)

**Comment by ryanslade** [comment]
How do you feel about calling it `ChangesetCheckState` instead?

**Comment by eseliger** [comment]
Absolutely, that was just a rough draft feel free to shape it the way you like :)

**Comment by ryanslade** [comment]
@eseliger We can work off this branch: https://github.com/sourcegraph/sourcegraph/pull/8020

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by ryanslade** [comment]
Closing this and pulling out the last remaining task into its own issue:
https://github.com/sourcegraph/sourcegraph/issues/8480
