### ISSUE TITLE
Code intelligence tracking issue 3.12

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#7150]
**Theme** Increase user confidence in code intelligence provided by LSIF and make setup easier.

[Sourcegraph project roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)

- [x] Fall back to basic code intel because LSIF might be sparse https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/179
- [x] Drop basic code intel results from files that have LSIF results https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/180
- [x] Recognize more variable names in various languages https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/186
- [x] [RFC 89: Indicating precision levels of code intel in UI](https://docs.google.com/document/d/1aVbkz-yIBHNdrubkYq9vUrVa7_yUUVSPMmwvy52hRXc/edit#) (Eric)
- [ ] Dart LSIF indexer https://github.com/sourcegraph/lsif-dart / https://github.com/sourcegraph/crossdart (Chris, Rijnard)

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by nicksnyder** [comment]
3.12 is done
