### ISSUE TITLE
Core Services: 3.12 Tracking Issue

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#7190]
### Context

**Status**: This tracking issue is finalized.

### Availability (__59d__)

Period is the Dec 16th -> Jan 15th. Please put in the days you won't be working and the number of working days for the period. Merry Christmas and a happy New Year! :santa: :christmas_tree:

Total availability, excluding @mrnugget, @ryanslade ([a8n](https://github.com/sourcegraph/sourcegraph/issues/7129)) and @tsenart (management): 16 + 15 + 15 + 13 = __59d__

- @keegancsmith 12/24 - 1/1 OOO. 16 days available.
- @kzh Dec 23th - Jan 1st. 15 days available.
- @mrnugget OOO Dec 23th - Jan 3rd. Available Dec 16th to 20th (**5d**) and Jan 6th to 15th (**8d**). 13 days available.
- @rvantonder 12/24 Dec to  1/2. 15 days available.
- @ryanslade 30th Dec - 15th Jan (__13d__).
- @tsenart 16th Dec - 20th Dec (__5d__), 6th Jan - 15th Jan (__8d__). 13 days available.
- @unknwon (CST +8) 12/18 - 12/23 Part-time (= 2 working days), 1/3 - 1/15. 13 days available.

### Planned work

All planned customer issues, technical debt and roadmap items are meant to be finished in the iteration. If we don't finish all planned work, it is either due to unknown unkowns or our estimating accuracy. While we cannot work on the former, we can on the latter — over time, we aim to estimate better.

Roadmap items may take more than an iteration to implement. As such please link to an issue which is scoped to this iteration. IE the issue should be closed at the end of the iteration.

All issues listed need to have a number of days estimate attached. When setting days, try and overestimate the time needed. Do not use a granularity less than half a day. The total amount of work assigned to you needs to be about 75% of your available days.

#### Items

- [x] Ability to filter out archived Bitbucket Server repositories [#5494](https://github.com/sourcegraph/sourcegraph/issues/5494) __1d__ [👩](https://app.hubspot.com/contacts/2762526/company/407948923)
- [x] String literal search "*foo/bar" causes an error despite "*" not being a regex special character [#4194](https://github.com/sourcegraph/sourcegraph/issues/4194) __1d__ [👩](https://app.hubspot.com/contacts/2762526/company/407948923)
- [x] Default symbol sidebar to using Zoekt for indexed branches [#6078](https://github.com/sourcegraph/sourcegraph/issues/6078) __2d__ [👩](https://app.hubspot.com/contacts/2762526/company/464956351)
- [x] External service _.schema.json files failing with "...is outside repository" error [#6034](https://github.com/sourcegraph/sourcegraph/issues/6034) __0.5d__ 👩
- [x] Add mechanism for downloading code file [#5478](https://github.com/sourcegraph/sourcegraph/issues/5478) __1d__ [👩](https://app.hubspot.com/contacts/2762526/company/554338610)
- [x] repository settings page does not display errors properly [#3593](https://github.com/sourcegraph/sourcegraph/issues/3593) __0.5d__ [👩](https://app.hubspot.com/contacts/2762526/company/407948923)
- [x] Add org membership restriction option to GitHub auth [#4195](https://github.com/sourcegraph/sourcegraph/issues/4195) __1d__ [👩](https://app.hubspot.com/contacts/2762526/company/561806411)
- [x] Error after saving external service [#7176](https://github.com/sourcegraph/sourcegraph/issues/7176) __0.5d__ [👩](https://app.hubspot.com/contacts/2762526/company/1749284052)
- [x] Perform controlled clean up of child processes for structural search #7295 __2d__ @rvantonder 
- [x] negated repohasfile is ineffective #7380 __1d__ 👩 @keegancsmith 
- [x] Make progress on developing and documenting a richer search expression language, and collecting feedback (RFC, no tracking issue) __2d__ @rvantonder [RFC 94 WIP](https://docs.google.com/document/d/1nYv_p1138eHsN7WOw0s3x69Y0HK2L8x7VP-nFKQGal8/edit)
- [x] Pending product sync, @rvantonder reserves a chunk of time to work on Dart LSIF (parent tracking issue #7150) and code-intel search/automation integration __5d+__ @rvantonder 
- [x] repo-updater: Soft delete rows in the repo table [#6859](https://github.com/sourcegraph/sourcegraph/issues/6859) __1d__  @keegancsmith [🛠️](https://github.com/sourcegraph/sourcegraph/issues/6086)
- [x] Integrate Bitbucket Server Plugin's permissions endpoints [#7282](https://github.com/sourcegraph/sourcegraph/issues/7282) __3d__ 🛠️@kzh
- [x] Diff/commit search should still show how many repositories timed out when a single repo error occurred [#5520](https://github.com/sourcegraph/sourcegraph/issues/5520) __1d__ [👩](https://app.hubspot.com/contacts/2762526/company/407948923)
- [x] Unable to clone GitLab repositories with self signed certificate [#2990](https://github.com/sourcegraph/sourcegraph/issues/2990) __1d__ 👩@keegancsmith
- [ ] Sourcegraph.com scales to support native integration into gitlab.com [#6738](https://github.com/sourcegraph/sourcegraph/issues/6738) __1d__ 🕵️ @keegancsmith
- [x] GitHub external service: repository sync service fails if org name contains _ or - [#3983](https://github.com/sourcegraph/sourcegraph/issues/3983) __0.5d__ 👩 @ryanslade 
- [ ] Enforce warnings for unsupported parameters and filters in structural search #7293 __1d__ @rvantonder 
- [x] RFC 40: GraphQL APIs #7298 __4d__ 🛠️ @unknwon
- [x] RFC 40: Grant permissions on user creation and email verification #7679 __0.5d__ 🛠️ @unknwon
- [x] RFC 40: Integrate explicit permissions model into authz workflow #7300 __2d__ 🛠️ @unknwon
- [x] a8n: Upsert ChangesetEvents from Bitbucket Server webhooks [#6726](https://github.com/sourcegraph/sourcegraph/issues/6726) __3d__ 🛠️ @kzh 
- [ ] a8n: Use a persistent queue for CampaignJobs and ChangesetJobs (https://github.com/sourcegraph/sourcegraph/issues/6723) __TBC__ 🧶@ryanslade

#### Legend

- 👩 Customer issue
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))

**Comment by tsenart** [comment]
@sourcegraph/core-services: This is a first pass at our 3.12 tracking issue. It's **not final**. @keegancsmith and I have triaged customer issues today. Next week we'll do roadmap items and technical debt. If you have ideas for those, or for any customer issues we have missed, please comment in this issue.

Additionally, write up your availability in the appropriate section.

PS: We haven't pursued https://github.com/sourcegraph/sourcegraph/pull/7142 for preparing the tracking issue because the our Sourcegraph extension that expands customer Hubspot links doesn't work in PR views.

**Comment by rvantonder** [comment]
Possible item to add (don't know if we plan to hit it this iteration, I will probably tackle parts of the language, if not the implementation): 

- [ ] Select repos filter __3d+__ #7003 👩

**Comment by tsenart** [comment]
@sourcegraph/core-services: I previously included weekends in my availability. That was a mistake. If you have done the same, please change.

**Comment by tsenart** [comment]
@ryanslade: Hope everything is going well with the newly extended family :-) I'm updating your availability above as per the Not Working calendar. I know you've been busy so I'm not sure it's entirely up-to-date. If so, let us know when you find a few moments.

**Comment by tsenart** [comment]
@rvantonder: Added your suggestion to the items. Are there other things you want to be doing in 3.12 that are not in there yet? If so, please add.

**Comment by tsenart** [comment]
We have reviewed the open `debt` core services issues and have deemed none of them a high priority relative to customer issues and the still to be determined roadmap items.

Without the roadmap items that we're still going to add on Thursday, the current list of customer issues accounts for __25d__ of work which fits well within the __59d__ availability we have.

**Comment by tsenart** [comment]
@kzh: Added  "Integrate Bitbucket Server Plugin's permissions endpoints #7282 3d 🛠️@kzh" to the tracking issue.

**Comment by rvantonder** [comment]
I have roughly blocked out the time that I'd like to allocate to tasks this iteration with time estimates, but it is not finalized. See PR description.

**Comment by tsenart** [comment]
@rvantonder, @unknwon: Added each of your issues to the 3.12 milestone and to the Core Services 3.12 project.

**Comment by tsenart** [comment]
@sourcegraph/core-services: The total estimated work accounts for __75d__ which goes beyond our availability. I propose we take these customer issues out of this iteration (and tackle them next one):

- [ ] Index multiple (non-master) branches [#6728](https://github.com/sourcegraph/sourcegraph/issues/6728) __5d__ [👩](https://app.hubspot.com/contacts/2762526/company/554338610)
- [ ] postgresql: (Auto)tune DB pool sizes based on max connections [#3473](https://github.com/sourcegraph/sourcegraph/issues/3473) __3d__ [👩](https://app.hubspot.com/contacts/2762526/company/419771425)
- [ ] search filter `archived`/`fork` "yes/no/only" values are confusing [#7003](https://github.com/sourcegraph/sourcegraph/issues/7003) __5d__  [👩](https://app.hubspot.com/contacts/2762526/company/1749284052)

This would bring the remaining estimated work to __53d__ which leaves us some slack. In any case, it'd be good to assess in the next retrospective how or if having slack has had a positive impact.

Please :+1: or :-1: the proposed changes.

**Comment by keegancsmith** [comment]
>  repo-updater: Soft delete rows in the repo table #6859 1d 🛠️

Spent some time hacking on this with @unknwon today. I fear this is more like 2 days work, we ran into a few issues making it non-trivial. IE 2 days due to needed research and experimentation.

**Comment by tsenart** [comment]
I removed the three customer issues mentioned in https://github.com/sourcegraph/sourcegraph/issues/7190#issuecomment-567598405 from the list of work.

**Comment by unknwon** [comment]
While everyone is on holiday this week...

I'm going to continue working on "RFC 40: GraphQL APIs #7298", and try to experiment more on repo soft-delete from where @keegancsmith and I left on last pair session.

**Comment by keegancsmith** [comment]
### W00 Plan [2020-01-06]

Still need to catch up and sync with everyone, but this is my plan for this week as it stands. My main goal is to experiment with code host fingerprinting. This is to get an idea of what is possible w.r.t. minimizing the number of steps an admin needs to do to setup codehosts on Sourcegraph. See [#7464](https://github.com/sourcegraph/sourcegraph/issues/7464) for a scoped issue for this work for this week.

Other issues I plan on tackling this week:
-   repo-updater: Soft delete rows in the repo table [#6859](https://github.com/sourcegraph/sourcegraph/issues/6859)
-   GitLab Sourcegraph.com production readiness [#6738](https://github.com/sourcegraph/sourcegraph/issues/6738)

**Comment by mrnugget** [comment]
### Last week on "Thorsten works on Automation"...

Before the winter break, I finished implementing the GraphQL API for Campaigns in draft-mode. See https://github.com/sourcegraph/sourcegraph/pull/7278

Since that went a lot faster than I estimated, I have time left in this iteration for other things. So I started working on "updating Campaigns", which is the the next highest prio item on our roadmap.

If you want some to get some more context and my thoughts on that item, read these two slack threads:

- https://sourcegraph.slack.com/archives/CMMTWQQ49/p1576656059049000
- https://sourcegraph.slack.com/archives/CMMTWQQ49/p1576828957003100

I started to work on this in this PR: https://github.com/sourcegraph/sourcegraph/pull/7328 

### Week 2020-01-06 to 2020-01-10

My plan for this week is to

* Keep working on "updating campaigns". With the current state of #7328 my next step will be to add the actual "updating" of branches on a codehost.
* Assist @ryanslade onboarding again after his paternity leave
* Fix Automation bugs
* _Maybe_: Help out the code intel team with a task after they reached out to me

**Comment by unknwon** [comment]
### W00 Plan [2020-01-06 to 2010-01-10]

- Must deliver: RFC 40: GraphQL APIs #7298
- Best to deliver: RFC 40: Handle change of bind_id in site config #7301
- Others: pair coding with @keegancsmith again to work on repository soft delete

**Comment by rvantonder** [comment]
**Last week, 1 working day**

I worked on

- [ ] Perform controlled clean up of child processes for structural search #7295 2d

**Week 2020-01-06 to 2020-01-10**

I will work on (and probably finish) these items this week:

- [ ] Perform controlled clean up of child processes for structural search #7295 1d 
- [ ] Enforce warnings for unsupported parameters and filters in structural search #7293 1d
- [ ] Make progress on developing and documenting a richer search expression language, and collecting feedback (RFC, no tracking issue) 2d
- [ ] Dart LSIF (parent tracking issue #7150) (partially, day 2/5)

**Comment by kzh** [comment]
### W00 Plan [2020-01-06]
* Work on delivering `a8n: Upsert ChangesetEvents from Bitbucket Server webhooks` #6726 this iteration.
* Testing for `Integrate Bitbucket Server Plugin's permissions endpoints` #7282 on customer instances.

**Comment by ryanslade** [comment]
**Last week, 4 working days**

I worked on

- [ ] cmd/frontend: Stop relying on FileInfo.Size() (#7391 )
- [ ] enterprise/a8n: Don't replace NPM environment variables (#7440)
- [ ] enterprise/a8n: Fix panic in store (#7392)
- [ ] enterprise/a8n: Add global locking around RunChangesetJob (#7453)

**Week 2020-01-06 to 2020-01-10**

I will work on:

- [ ] Sync service fails for unknown org (https://github.com/sourcegraph/sourcegraph/issues/3983)
- [ ] Maybe persistent queues, to discuss in sync

**Comment by rvantonder** [comment]
My update for Week 1

Last week **2020-01-06 to 2020-01-10**

- Improve quality of structural search
  - removed repo/zip limitation (can now search over Linux or larger repos that wasn't possible before. #7133
  - Cleaner process management when forking comby procs #7295
- Structural search blog post WIP https://github.com/sourcegraph/about/pull/489
- Query language RFC, (AND/OR/NOT) [RFC 94 WIP](https://docs.google.com/document/d/1nYv_p1138eHsN7WOw0s3x69Y0HK2L8x7VP-nFKQGal8/edit)
- Added e2e regression tests for diff/commit search https://github.com/sourcegraph/sourcegraph/pull/7640

This week **2020-01-13 to 2020-01-17**

- [ ] Better control over displayed results and `count` parameter for structural search (rework a PR in progress https://github.com/sourcegraph/sourcegraph/pull/7491)
- [ ] Enforce warnings for unsupported parameters and filters in structural search (I deprioritized this and will push to get it in before branch cut #7293)
- Continue RFC 94 and put it up for review this week
- Put up structural search blog post for review and publish
- Rest of the time after branch cut will be split helping Dart LSIF efforts

**Comment by tsenart** [comment]
@ryanslade: Are you doing this in time for branch cut?

- [ ] GitHub external service: repository sync service fails if org name contains _ or - #3983 0.5d woman @ryanslade

**Comment by mrnugget** [comment]
### Week 2020-01-13 to 2020-01-17

My plan for this week is to

* After merging #7328 and follow-ups last week, this week I want to finish the backend portion of "updating campaigns" by adding support for Bitbucket Server and then, possibly, assist the Web team when adding the frontend.
* Before planning 3.13: take a look at next highest priority items under "Stretch Goals in https://github.com/sourcegraph/sourcegraph/issues/7129 to see how they could roughly be implemented in order to allow others to take on some of the Automation work in 3.13
* Plan 3.13.
* Prototype some ideas for [RFC 92 - Stacking Diffs](https://docs.google.com/document/d/1m6WH47vl-DFynfEdjpGez2pj7bTO3MRFAPpDgEDlvFI/edit#heading=h.kfdzelmr4v06) which is the next highest priority Automation roadmap item
* Investigate and hopefully implement some minor UX improvements for Automation (speed up initial Campaign creation time, https://github.com/sourcegraph/sourcegraph/issues/7646)
* Maybe: depending on how they're planning their week, I might assist @efritz and @chrismwendt by trying to write an LSIF indexer for C#

**Comment by ryanslade** [comment]
### Week 2020-01-13 to 2020-01-17

My plan for this week is to

* Get https://github.com/sourcegraph/sourcegraph/issues/6723 finished off
* Have a stab at #3983 before branch cut
* Taking one of the stretch goals from here: https://github.com/sourcegraph/sourcegraph/issues/7129

**Comment by kzh** [comment]
Last week, there was a lot progress towards #6726. The core functionality is complete.
* [a8n: accept incoming BBS plugin webhook payloads](https://github.com/sourcegraph/sourcegraph/pull/7554)
* [webhook: switch from raw events to activities](https://github.com/sourcegraph/bitbucket-server-plugin/pull/16)
* [a8n: create ChangesetEvents from incoming BBS webhook payloads](https://github.com/sourcegraph/sourcegraph/pull/7655)
Today, I'll do some housekeeping: releasing `v1.2` of Bitbucket Server Sourcegraph plugin.

**Comment by unknwon** [comment]
Last week, I finished up RFC 40: GraphQL APIs #7298 except regression test suite.

### W01 Plan [2020-01-13]

- Before branch cut (theme: make RFC 40 in preview state):
	1. Finish regression test suite for #7298 
	2. Finish other planned items (in order): #7300, #7679, #7302
- After branch cut (theme: make RFC 40 robust):
	- Any items unable to be finished before the branch cut
	- Others (no actual items yet): performance test, admin e2e usability test

---

I removed item "RFC 40: Handle change of bind_id in site config #7301 0.5d" because (as I commented on the issue) it might not be the ideal solution the prospective customer wants, thus not worth working on it at this point.

I added "RFC 40: Grant permissions on user creation and email verification #7679" because it is a necessary step (missed back when I added iteration items) for the preview version of RFC 40.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
3.12 done. Continue on with 3.13 https://github.com/sourcegraph/sourcegraph/issues/7719
