### ISSUE TITLE
Web: 3.12 tracking issue

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#7229]
### OKR: 2.b.iv - Make the power of search accessible to more users

**Planned work for 3.12**:

 - Finish RFC 14: Showing users suggestions of filters & filter values as they type into the search bar, and highlighting valid filters in search queries.
    - [ ] Implement Monaco-editor backed search query input, providing syntax highlighting, hover tooltips and diagnostics for search queries: https://github.com/sourcegraph/sourcegraph/pull/7669
 
- RFC 15: split the search UX into two modes, omni and interactive.
    - [ ] Add filter negation to text-based filter inputs (repo, file)
    - [x] Add buttons for remaining filters 
    - [x] Add unit tests

**Comment by lguychard** [comment]
@attfarhan can you spell out the next steps on RFC15 in the issue description?

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
