### ISSUE TITLE
Structural search feature improvements

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#7234]
The following issues are planned work items and will improve the quality of structural search:

- [x] Pattern parsing without quotes and multiline input (consider UI and `src-cli` solutions). Update as of March 2020: this will happen with the new parser implementation #9971
- [x] The line match/result count issue #9426
- [ ] Follow up of match counts #9426: #9564 
- [x] UX of `show more` results #9079
- [ ] promote comby warnings (pattern starts with `:[x]`) #7294
- [ ] Upgrade the comby dependency to use the new parser engine RFC 48, Part 2 when ready
- [ ] Saved search #7316
- [x] Documentation in combination with `src-cli` https://github.com/sourcegraph/src-cli/pull/67
- [x] Evaluate further solutions for orphaned processes #7295 (3.12)
- [x] Disable/warn on unsupported scopes like `case` #7293 
- [x] Add additional metrics #7630 (3.12)
- [x] ~Optimization: refine Zoekt query to return only file matches, and use RepoList from Zoekt~ Add Zoekt optimizations #8365 #8371 
- [ ] Pull out structural search execution path from search_results.go. Too much locking/repo filter logic in one place.

Wishlist:

- [x] Lift zip file restriction #7133 (3.12)
- [ ] Enable unindexed structural search #8164 
- [ ] Perfect [unicode highlighting](https://github.com/sourcegraph/sourcegraph/pull/7018#issuecomment-561474768)

**Comment by tsenart** [comment]
@rvantonder: Taking this out of the 3.12 milestone since it's not going to be complete by then. Please create separate issues for each of the items and triage for 3.13.

**Comment by rvantonder** [comment]
Yeah, this issue should not have been in the milestone, it's not specific to 3.12 since it was restructured a month ago.

**Comment by tsenart** [comment]
Any next steps here in the context of 3.14 planning?

**Comment by rvantonder** [comment]
@tsenart nope. I've updated this issue to be current. There are a handful of things in here that are still personally useful for me to track. Feel free to remove the core-services label if you don't want this on your radar.

**Comment by tsenart** [comment]
> Feel free to remove the core-services label if you don't want this on your radar.

It's fine to review this every month :)

**Comment by rvantonder** [comment]
I'm going to close this issue--there are not so many dangling tasks any more and this issue doesn't really contribute priority/importance than the issues do themselves.
