### ISSUE TITLE
Distribution 3.12 tracking issue

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#7240]
| Mark | Description                                       |
|------|---------------------------------------------------|
| 🏃   | Work in progress                                  |
| ✋   | Blocked task                                      |
| 💪   | Stretch goal for this iteration                   |
| ⏱️💪   | Status changed to stretch mid-iteration             | 
| ⌛   | Waiting for information from user          |
| 🎁   | Unexpected addition to milestone         |
| 🔴   | Missing issue reference                           |
| 🔵   | More investigation required to remove uncertainty |
| ⚫️   | Under discussion within the team                  |
| ~crossed out~ | No longer expect to achieve in iteration. |

The work we set out to do in 3.10 was: https://github.com/sourcegraph/sourcegraph/issues/6038

### OKR 1: Critical customer features

- **General**
  - [ ] Enforce pod security policies https://github.com/sourcegraph/deploy-sourcegraph/issues/482 @beyang
  - [ ] 💪 GraphQL timeout on very large repositories https://github.com/sourcegraph/sourcegraph/issues/6878 @beyang
  - [ ] Version number is wrong for 3.11.0, causing update checker to not work #7442 @ggilmore @beyang 
  - [ ] 🏃⌛(anticipated) Forbidden - CSRF token invalid #7368 @slimsag (identify workaround at least) @slimsag
- **Monitor recently reported search issues** @slimsag
  - [ ] Search indexing monitoring: https://github.com/sourcegraph/deploy-sourcegraph-docker/issues/55
  - [ ] search: add prometheus metric(s) about how many repos are indexed/nonindexed #4197
  - [ ] metrics/alerts for gitserver slow execs and fetches/clones #6675
  - [ ] 🏃Searcher dashboard incorrectly reports on query-runner #7531
  - [ ] 🏃Frontend dashboard: "Search responses by status" query is not aggregated #7627
- **(anticipated) Make it clear to admins how to configure alerting** @slimsag
  - [ ] Add documentation for setting up Grafana alerting #7523
- **(anticipated?) Monitor GitLab integration** @uwedeportivo
  - [ ] alerts for code intelligence latency
  - [ ] alert gitserver latency spikes https://github.com/sourcegraph/sourcegraph/issues/6651
  - [ ] metric labeling https://github.com/sourcegraph/sourcegraph/issues/6650
  - [ ] disk space alerts https://github.com/sourcegraph/sourcegraph/issues/5994 @uwedeportivo @slimsag

### OKR 2: Features and docs that accelerate customer journey

- [ ] Document scaling recommendations https://github.com/sourcegraph/sourcegraph/issues/6274 @beyang
- **Monitoring: insight into instance over/under-provisioned-ness** @slimsag
  - [ ] Add unified set of container / pod Prometheus metrics #5547
  - [ ] Add monitoring/alerts to signal whether instance is underprovisioned or not #7529
- [ ] catch-all: Improve onboarding / initial setup documentation, auth documentation, etc @slimsag
  - ✅18 issues identified from running a user onboarding test: https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+is%3Aopen+label%3Aonboarding-test-1

### OKR 3: Improve developer productivity

- [ ] Move e2e tests into regression test suite https://github.com/sourcegraph/sourcegraph/issues/5721 @beyang
- [ ] Add regression tests that ensure diff, commit, and repo search work properly https://github.com/sourcegraph/sourcegraph/issues/7102 @beyang
- [ ] Eliminate ephemeral alerts [RFC 35](https://docs.google.com/document/d/1GXYTBktfRjr3I5vyl-TwCixITtKG0snVXcehRU1dfok/edit#heading=h.9gknqva39m5l) @uwedeportivo

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by nicksnyder** [comment]
3.12 is released. It looks like we didn't get to much (any?) of the planned work in 3.12. As discussed in the team meeting today, let's figure out how to do better moving forward.
