### ISSUE TITLE
e2e test pains (tracking issue)

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#7510]
Overall the e2e tests are **AWESOME**, but sometimes they add friction to the dev process. I am listing these out and encourage other people to edit this issue (or +1 issues they've seen too) so we can prioritize fixing the biggest e2e pain points.

- [ ] After calling `setConfig` in `beforeAll`, your test needs custom logic to wait for the site config change to be applied. Causes confusing build failures like https://buildkite.com/sourcegraph/sourcegraph-e2e/builds/2730#65bc539e-33ef-4c2e-bad7-22af7cef0cda that are less likely to happen locally (because local is often faster), and requires either more tricky polling logic (examples: [1](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@db2fc2055d41238ec7baedcabc3ce99a0db63273/-/blob/web/src/e2e/e2e.test.ts#L1561:16) [2](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@db2fc2055d41238ec7baedcabc3ce99a0db63273/-/blob/web/src/e2e/e2e.test.ts#L1436:16)) or a sleep. 
- [ ] A helper to assert the content of a search results page would be helpful. There is a fair bit of duplication of [tricky code like this](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@db2fc2055d41238ec7baedcabc3ce99a0db63273/-/blob/web/src/e2e/e2e.test.ts#L1180-1192).
- [ ] `cmd/server/pre-build.sh` disk out of space: https://buildkite.com/sourcegraph/sourcegraph-e2e/builds/2734#6759d10d-8af8-40ce-8d71-4550f5285bc8 (retrying build usually works)
- [ ] The initial external service setup step is slow. It could be made a lot faster by not typing in each character into the Monaco editor 1-by-1 and by parallelizing the repo checks.
  - Workaround: https://github.com/sourcegraph/sourcegraph/pull/7508 (`SKIP_EXTERNAL_SERVICE_SETUP`)
- [ ] Who is monitoring skipped tests to ensure they are either removed (if irrelevant) or prioritized to be unskipped? I worry that we might assume things are tested that are actually skipped, such as [this test](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@db2fc2055d41238ec7baedcabc3ce99a0db63273/-/blob/web/src/e2e/e2e.test.ts#L1263).

**Comment by lguychard** [comment]
> not typing in each character into the Monaco editor 1-by-1 and by parallelizing the repo checks

[`ensureTestExternalService()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@db2fc2055d41238ec7baedcabc3ce99a0db63273/-/blob/web/src/regression/util/api.ts#L269-308) from the regression test utils creates the external service through the API (not the UI) and performs repo checks in parallel. We should use it in e2e tests, and possibly keep a simple e2e test (not in the `beforeAll` hook) checking that the UI flow to add an external service performs as expected.

**Comment by felixfbecker** [comment]
Referencing https://github.com/sourcegraph/sourcegraph/issues/5259
Even better that we already have the function in the regression test suite. Going forward though, I think we need to be more conscious about not making the regression test suite a silo that doesn't share improvements with the e2e test suite...

**Comment by bobheadxi** [comment]
Closing for the more recent https://github.com/sourcegraph/sourcegraph/issues/21249
