### ISSUE TITLE
Distribution 3.13 tracking issue

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7537]
| Mark | Description                                       |
|------|---------------------------------------------------|
| 🏃   | Work in progress                                  |
| ✋   | Blocked task                                      |
| 💪   | Stretch goal for this iteration                   |
| ⏱️💪   | Status changed to stretch mid-iteration             | 
| ⌛   | Waiting for information from user          |
| 🎁   | Unexpected addition to milestone         |
| 🔴   | Missing issue reference                           |
| 🔵   | More investigation required to remove uncertainty |
| ⚫️   | Under discussion within the team                  |
| ~crossed out~ | No longer expect to achieve in iteration. |

The work we set out to do in 3.11 was: https://github.com/sourcegraph/sourcegraph/issues/7240

### OKR 1: Critical customer features

- **💪 (anticipated) Dogfood the monitoring we ship to customers** @slimsag
  - [ ] Setup new Grafana alerting on k8s.sgdev.org and sourcegraph.com to go to Slack #7527
  - [ ] Determine missing alerts between alertmanager and grafana #7528
- **💪 (anticipated) Further assess the comprehensiveness of monitoring** @slimsag
  - [ ] Assess missing prometheus metrics #6428
  - [ ] Identify further service-specific metrics missing from new Grafana dashboards + alerts #7524
  - [ ] Identify further inter-service communication metrics missing from new Grafana dashboards + alerts #7525
- [ ]  🏃attribute SameSite for cookies https://github.com/sourcegraph/sourcegraph/issues/6167 @uwedeportivo
- [ ] @ggilmore figure out permission issue with docker-compose: https://github.com/sourcegraph/sourcegraph/issues/7829

### OKR 2: Features and docs that accelerate customer journey

- **Make us aware of problems on customer instances proactively through aggregate information, so we can proactively reach out and provide support.**
  - [ ] @slimsag @uwedeportivo to identify next steps or write RFC
- **When a customer reports a problem, make it easy for them to send us extensive metrics & logs for debugging.**
  - [ ] @uwedeportivo @slimsag to identify next steps or write RFC
- [ ] @slimsag @ggilmore Add docker-compose documentation to about.sourcegraph.com
   - Related: write full documentation for how to deploy on AWS, GCP, Digital Ocean
   - Write docs for how to migrate from sourcegraph/server to docker-compose

- [ ] 💪 @ggilmore @slimsag docker-compose: figure out a solution for how to scale services 
  - https://dhall-lang.org/?
  - https://github.com/mikefarah/yq ?

 
### OKR 3: Improve developer productivity

- 💪 Figure out a solution for how to communicate and propagate deployment changes to all 4 deployment types

**Comment by beyang** [comment]
Closing this out in favor of our [planning/tracking document](https://docs.google.com/document/d/1ScXeBcFXAeUeWIgcSjB8Qy8c1E8JJkA8BZOtEffkvoU/edit#)
