### ISSUE TITLE
Web: 3.13 tracking issue

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#7726]
#### Search

- [ ] [Monaco-backed search field](https://github.com/sourcegraph/sourcegraph/pull/7669) follow-ups @lguychard :
    - [ ] #7692 Search field does not shrink when the window is resized
    - [x] #7693 Improve syntax highlighting themes 
    - [x] #7694 Improve completion items icons 🏃 
    - [x] #7695 Some dynamic suggestion types are missing 🏃 
    - [x] #7696 Improper warnings for lang: filter
    - [ ] #7697 Isolate theming from other Monaco editors on the page 
    - [x] #7698 Diagnostics should take pattern type into account  #8238
    - [x] #7774 Display plain input box while lazy-loading  #8237 
- [x] Improve discoverability of structural search? ([Slack thread](https://sourcegraph.slack.com/archives/CMT39K56Z/p1578592913014600)) @attfarhan #8233
- [x] https://github.com/sourcegraph/sourcegraph/issues/7885 Add interactive search regression tests @attfarhan https://github.com/sourcegraph/sourcegraph/pull/8294
- [x] Interactive search improvements with new query parser @attfarhan :  
  - [x] Switching between modes preserves filters #7974 
  - [x] Make both types of URLs compatible with all modes 
  - [x] Improve parsing logic (`case`, `patternType`, colons (https://github.com/sourcegraph/sourcegraph/issues/6490)) 

#### Automation

- [x] Make delete text clickable #7560 @eseliger
- [x] Campaign plan updates and UI clarification #7683 @eseliger 
- [x] CI Status (depends on API) #7680 @eseliger
- [x] Labels on campaigns #7686 @eseliger
- [x] Specify branch name #7646 @eseliger 

#### Customer issues & debt

- [x] https://github.com/sourcegraph/sourcegraph/issues/6533 Notifications on code hosts are now missing alert styles @felixfbecker 
- [x] [GitLab #193433](https://gitlab.com/gitlab-org/gitlab/issues/193433) Sourcegraph popover stays visible when switching MR tabs @lguychard https://github.com/sourcegraph/sourcegraph/pull/8340
- [ ] Search debt @attfarhan   🏃: 
  - [x] https://github.com/sourcegraph/sourcegraph/issues/6900 Highlighting cuts off before the last line in the preview https://github.com/sourcegraph/sourcegraph/pull/8375
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/6218 Incorrect highlighting for 'authless' search
  - [x] https://github.com/sourcegraph/sourcegraph/issues/8253 Search header improvements https://github.com/sourcegraph/sourcegraph/pull/8345
  - [x] https://github.com/sourcegraph/sourcegraph/issues/7379 H-padding commit search lacks H-padding https://github.com/sourcegraph/sourcegraph/pull/8359
  - [x] https://github.com/sourcegraph/sourcegraph/issues/8161 Confusing behavior for URLs without patternType parameter
  - [ ] https://github.com/sourcegraph/sourcegraph/issues/7167 Code tab is toggled when typing input
## Stretch goals

- [ ] https://github.com/sourcegraph/sourcegraph/issues/5259 e2e test setup should use API @lguychard  
- [ ] https://github.com/sourcegraph/sourcegraph/issues/3765: Nicer display of sign-in errors
- [ ] https://github.com/sourcegraph/sourcegraph/issues/7004: Exclude archived and forks from search results by default
- [x] Extended campaign list view #7684
- [ ] Tracking
    - [ ] https://github.com/sourcegraph/sourcegraph/issues/7833 Track time to first search in pings
    - [ ] https://github.com/sourcegraph/sourcegraph/issues/7832 Track usage of search filters in pings
    - [ ] https://github.com/sourcegraph/sourcegraph/issues/7831 Track usage of search modes in pings

**Comment by lguychard** [comment]
## W01 Recap

Merged https://github.com/sourcegraph/sourcegraph/pull/7669/files behind the `smartSearchField` feature flag and filed follow-up issues (see in issue description above). Off by default for everyone (inc. team) until I fix some of the most glaring follow-up issues.

## W02 Plan

- Main goal: #7693, #7695 then enable feature-flag by default for the team (dev environment, k8s & sgdev, Sourcegraph org on sourcegraph.com).
- Tackle one TBD item from **Customer issues & debt**
- Keep working my way through the rest of the follow-up issues.

**Comment by eseliger** [comment]
## W01 Recap

- Got lots of last minute work on Draft mode for campaigns done #7659 

## W02 Plan

- Tackle campaign plan updates #7683
- Tackle some leftovers like #7560

**Comment by attfarhan** [comment]
## W01 Recap
- Merged interactive search: https://github.com/sourcegraph/sourcegraph/pull/7672, and a bunch of follow-ups

## W02 Plan
- Plan and start work on onboarding improvements
- Discuss structural search UI improvements

**Comment by felixfbecker** [comment]
## W01 Recap
* Planned Automation 3.13 iteration
* Improvements to e2e tests:
  - Switch back from Jest to Mocha
    - Console log lines are now correlated again to their tests
    - Screenshots are now correlated again to their tests
    - Tests don’t run if setup failed
    - Debugger works again
  - Improve console log printing
    - Mirrors the style of Chrome dev tools logs as close as possible

## W02 Plan
- [x] Make timestamps in Buildkite UI toggleable
- [x] Fix logspam from worst offenders
- [ ] Campaign details form
- [ ] Read into stacked diffs RFC

**Comment by sqs** [comment]
I am deprioritizing (backlogging) these 2 items and their related backend work because none of the private beta customers has told us they are necessary:

- Show set of participant users involved in the campaign #7685
- Show comments of all changesets in campaign #7688

**Comment by lguychard** [comment]
## W02 Recap

- Improved styling of Monaco query input. Working on improvements to completions (#7694, #7695) in #7949. I'm a bit late on where I wanted to be on this. I want to get this review-ready and get a UX 👌 from @christinaforney ASAP.
- Fixed regression in GitHub DOM: https://github.com/sourcegraph/sourcegraph/pull/7967. This notably impacted Codecov users who use the browser extension on private repos without a private Sourcegraph instance, because private repo detection was broken. Filed https://github.com/sourcegraph/sourcegraph/issues/7980 to improve browser extension 

## W03 Plan

- Get #7949 review-ready, get the UX reviewed, merge & activate internally. 
- Chatting with Rijnard this week about keeping frontend & backend search parsers in sync.
- Tackle GitLab issue [#193433](https://gitlab.com/gitlab-org/gitlab/issues/193433)

**Comment by eseliger** [comment]
## W02 Recap

- CI status web part (waiting for possible follow-up work once API is final) #7680
- Fixed some nits on automation #8023, #8030
- Addressed last-minute changes for testing of automation #8033 
- Started spikes on "Campaign plan updates and UI clarification" #7683 - revisiting after reprioritization of automation goals

## W03 Plan

- Frontend and API stub for labels on campaigns #7686
- Campaign updates UI with `src` CLI - override of #7683 
- Make delete text clickable #7560
- Might tackle documentation for `src` based campaign ("Create new" button works different now)

**Comment by felixfbecker** [comment]
# W02 Recap

- Make timestamps in Buildkite UI toggleable
- Fix logspam from worst offenders
- Implemented last-minute read-only feature frontend for https://app.hubspot.com/contacts/2762526/company/608245740  and `viewerCanAdminister` GraphQL API for campaigns
- 2 interviews

# W03 Plan

- Make notification styles customizable and customize per code-host https://github.com/sourcegraph/sourcegraph/issues/6533
- Automation: TBD, need to discuss at sync later - priorities shifted.
- 1 interview

**Comment by attfarhan** [comment]
## W02 Recap

- Improve interactive mode styling https://github.com/sourcegraph/sourcegraph/commit/5f100af72c126139f83f85cdbda05e2cae4e7c9f
- Moved frontend query parser from web to shared https://github.com/sourcegraph/sourcegraph/commit/7fb4f163720508bdb3716ade9b6c854c15b80a5b
- Make frontend query parser case insensitive https://github.com/sourcegraph/sourcegraph/commit/2d24b71be5784ca6dc98f2f3e1d8f09783a17066 
- Use frontend query parser to detect `case` filters https://github.com/sourcegraph/sourcegraph/commit/0cf9a689d78084a5b30ad7347720f107e6abbbc0
- Use frontend query parser to detect `patternType` filters https://github.com/sourcegraph/sourcegraph/commit/9688f669fb5558854adacff57cdfa0071b175b1e
- Fix search result border missing https://github.com/sourcegraph/sourcegraph/commit/e0c676c4a90e762ec324b2da933da738b901db5e
- Add hide suggestions setting https://github.com/sourcegraph/sourcegraph/commit/9cd2360275fb4f5f64dce21786c070e018ae63b9
- Remove split search modes option from site config https://github.com/sourcegraph/sourcegraph/commit/e22f412335a63773fe5e87d201b52e87a40a5834
- Discussed structural search toggle 
- Opened PR for preserving filters between interactive and text mode https://github.com/sourcegraph/sourcegraph/pull/7974

## W03 Plan

- Merge PR for preserving filters between interactive and text mode https://github.com/sourcegraph/sourcegraph/pull/7974
- Structural search toggle
- Interactive search regression tests

**Comment by sqs** [comment]
Removed item:

- Stacked diffs research (depends on API) #7682 **2d**

because https://github.com/sourcegraph/sourcegraph/issues/7682#issuecomment-578854758

**Comment by attfarhan** [comment]
## W03 Recap
- Add hide suggestions setting https://github.com/sourcegraph/sourcegraph/commit/9cd2360275fb4f5f64dce21786c070e018ae63b9
- Remove split search modes option from site config https://github.com/sourcegraph/sourcegraph/commit/e22f412335a63773fe5e87d201b52e87a40a5834
- Merged PR for preserving filters between interactive and text mode https://github.com/sourcegraph/sourcegraph/pull/7974
- Fixed not all filters being handled in interactive mode https://github.com/sourcegraph/sourcegraph/commit/c4bf7ad071aab33beacdaa0f6cbe68f8d6e02eb7
- Fixed selected filters row padding in interactive mode https://github.com/sourcegraph/sourcegraph/commit/d08173cd49de1eed2beb00c7970701f9e3887103
- PR open for structural search toggle  https://github.com/sourcegraph/sourcegraph/pull/8233
- Conduct 1 architecture interview 
- Grade 1 coding assigment

## W04 Plan

- Merge structural search toggle https://github.com/sourcegraph/sourcegraph/pull/8233
- Interactive search regression tests
- Highlighting cuts off before the last line in the preview https://github.com/sourcegraph/sourcegraph/issues/6900
- Lattice reviews

**Comment by eseliger** [comment]
## W03 Recap
- Improved campaign close popover UX #8117 (review on non-reacty part appreciated here: https://github.com/sourcegraph/sourcegraph/pull/8117#discussion_r372586576)
- Fixed a nasty bug with history blocking https://github.com/sourcegraph/sourcegraph/pull/8125
- Implemented labels on changesets (explored some Go here) https://github.com/sourcegraph/sourcegraph/pull/8115
- Began work on `src` cli documentation in the web-app, working on content

## W04 Plan

- Finally complete campaign updates (was awaiting changes on `src` cli) #7683 
- Complete content for `src` cli documentation in the web-app (out of band, added due to reprioritization) 
- Specify branch name #7646
- Lattice reviews

**Comment by lguychard** [comment]
## W03 Recap
- Worked on web coding screen exercise
- Fixed issue with the GitLab native integration (reported internally, not by GitLab) https://github.com/sourcegraph/sourcegraph/pull/8135
- Display plain input box while lazy-loading MonacoQueryInput https://github.com/sourcegraph/sourcegraph/pull/8237
- Take patternType into account for MonacoQueryInput diagnostics https://github.com/sourcegraph/sourcegraph/pull/8238

## W04 Plan
- Get #7949 wrapped up.
- Tackle GitLab issue [#193433](https://gitlab.com/gitlab-org/gitlab/issues/193433)

**Comment by felixfbecker** [comment]
# W03 Recap

- 1 Interview
- Make notification styles customizable and customize per code-host #6533
- Help with code intel extension changes
- PR reviews

# W04 Plan
- PR reviews

**Comment by lguychard** [comment]
## W04 Recap
- Fixed issues with code intelligence on GitLab.com - twice 🙄 (#8280, #8323). This makes the discussion we had at last week's sync about nightly test runs all the more relevant. I pinged Paul from GitLab to fast-track review of my fixes, and they should be deployed to .com today (GitLab.com is only deployed twice weekly).
- Quick Phabricator browser extension fix for a prospect (#8286).
- Helped out with UX designer interviews (portfolio reviews).
- Worked on the the GitLab native integration issue that was planned for 3.13 (#8340).

## W05 Plan

I'm quite late on my smart search field / MonacoQueryInput work, so this will be my main focus for the week to wrap up planned work for 3.13, along with Lattice reviews.

**Comment by eseliger** [comment]
### W04 Recap
- Lattice reviews
- Continued on campaign updates #7683
- Fixed CLA bot once for all
- Fixed web style regression https://github.com/sourcegraph/sourcegraph/pull/8258

### W05 Plan

My main target this week is finally getting campaign updates in for the 3.13 release, alongside lattice review finish-ups. Below is the current state, I'm planning on getting a first PR up by latest tomorrow, so there is some more time for reviews and change requests.

![image](https://user-images.githubusercontent.com/19534377/74164998-c53f1200-4c24-11ea-8b30-22e26baf149f.png)

**Comment by felixfbecker** [comment]
# W04 Recap

- PR reviews
- Prevent `.only()`s on master: https://github.com/sourcegraph/sourcegraph/pull/8320
- Helped on sourcegraph-typescript

# W05

- Lattice reviews

**Comment by attfarhan** [comment]
## W04 Recap
- Lattice reviews
- Regression tests for interactive search
- Fix query input in navbar didn't update when searching from tree pages in interactive mode
- Merge structural search toggle
- Opened PR for tracking search modes

## W05 Plan
- Merge tracking search modes
- Search debt issues

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by lguychard** [comment]
## W05 Recap
- Added a git-extras setting for a customer: https://github.com/sourcegraph/sourcegraph-git-extras/pull/103
- Finally got https://github.com/sourcegraph/sourcegraph/pull/8452 ready for review, which will close #7694, #7695, #7696. This will miss the branch cut, though.
- Designer & web interviews.
- Lattice peer reviews

## W06 Plan
- 3.14 planning
- Lattice direct reports reviews
- Customer issue: https://github.com/sourcegraph/customer/issues/23

**Comment by attfarhan** [comment]
## W05 Recap

- Fixed race condition in interactive search for URLs with undefined patternTypes https://github.com/sourcegraph/sourcegraph/commit/d4614ce47388ec544551de0c15921c3f9aaab7be
- Clarified patternType logic for URLs with no patternType https://github.com/sourcegraph/sourcegraph/commit/fc98e5eb4624b2b05ad7cd6fc76477511a09ff08
- Add horizontal padding to markdown-based search results https://github.com/sourcegraph/sourcegraph/commit/ee7bcf608aaeb9847801fd66aafb7d0eac876fdc
- Search header improvements: clear query and remove interactive search UI elements on non-search- or repo-related pages https://github.com/sourcegraph/sourcegraph/commit/0f9f8d2a3b48688fc6b13a92bf38619d32f78908
- Fixes for `type` filter in interactive mode https://github.com/sourcegraph/sourcegraph/commit/20e0b1d774283f3c0745397af00ba1387f9ef56d
- Improve filter validation in interactive mode https://github.com/sourcegraph/sourcegraph/commit/44a529f8f923bce2a181644650dd5fe261ddc286
- Fix matches in context lines not getting highlighted https://github.com/sourcegraph/sourcegraph/commit/58b6d2769db53fa99aa2745ac19d3d5ad02f2eb8
- Add new `content` filter as a valid filter https://github.com/sourcegraph/sourcegraph/commit/88aa4903f0bdd186ead419e48a473cfcbe9dfc4a
- Add commit message filter https://github.com/sourcegraph/sourcegraph/commit/55b1f110585ab10a337811b6dbb7a90a57f278d7

## W06 plan
- 3.14 planning 
- Search unit tests https://github.com/sourcegraph/sourcegraph/issues
- Add FieldTypes map to query parserhttps://github.com/sourcegraph/sourcegraph/issues/8440
- Flying to Tokyo on Friday for TSConfJP
