### ISSUE TITLE
search: Support AND / OR / NOT predicate language in search queries

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#7823]
This the umbrella issue for reaching feature parity with OpenGrok. This is an OKR of the Core Services team in Q1 2020.

Progress:

- [x] Design for and/or queries is tracked in #8346 
- [x] Implement predicates support for searching file content #8567
  - [x] Parser additions #8633 #8802 #8784  #8809 
  - [x] Refactors for existing search #8566 #8565 #8564
  - [x] Heuristics to make search usable and robust #9762 #9816 
  - [x] Basic query validation #9817 #9172 #9754 

---

Q2:
- [x] Refine query validation #9971 
- [x] Add `NOT` as syntactic sugar #9976
- [x] Explore search support to non-content searches (i.e., repo, filepath, commit, ... searches) #9974, #11009 

---

- [ ] TODO: Checking and/or query usage to pings #9177

Related documents: [RFC 94](https://docs.google.com/document/d/1nYv_p1138eHsN7WOw0s3x69Y0HK2L8x7VP-nFKQGal8/edit?ts=5e2845ae#heading=h.trqab8y0kufp)
Related issues: #7154,  #4774, #1005,#8397, #636

**Comment by rvantonder** [comment]
Since this is the umbrella issue and crosses multiple iterations, I'm removing the day estimate and spike labels. I'm tracking a subtask that communicates progress for 3.13 in #8346.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Closing this--the tasks for Q2 scope are done. We'll introduce and/or expressions for general queries tracked in #11009 and prototyped in https://github.com/sourcegraph/sourcegraph/tree/rvt/nested-search-7777
