### ISSUE TITLE
a8n: Create GitHub PRs in draft status

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#7998]
Requested by https://app.hubspot.com/contacts/2762526/contact/17877751: 

> Being able to have github PRs created in draft status would be a nice QoL improvement for our testing use cases.

**Comment by chrispine** [comment]
we could have `published-draft: true/false` as well as `published: true/false`, but we will consider this after we have publishing-a-subset implemented.

**Comment by eseliger** [comment]
## Implementation plan

- [ ] Write Readme entry for usage of draft/bool triple for the publish field
- [ ] Extend the `overridable` package in `campaignutils` by support for the triple
  - [ ] Make a generic version of the bool rule parser / matcher
  - [ ] Use the generic version to create a [`Publish` overridable type that has three methods `True`, `False`, `Draft`](https://play.golang.org/p/9WXAhvMIroP)
- [ ] Extend the changeset_spec schema publish property by `'draft'`
- [ ] Extend the campaign_spec schema by the draft mode string in the published type
- [ ] Add code in src cli using the overridable package to determine the draft property of changeset specs before uploading them
- [ ] Add a draft field in the GraphQL API on changeset specs and changesets (can also be on hidden ones, I think)
- [ ] Add an indicator in the UI for `ChangesetSpecNode` and `ChangesetNode`
- [ ] Extend GitHub and GitLab clients by logic that takes `changeset.Draft()` into account in `CreateChangeset`
- [ ] Extend GitHub and GitLab client `UpdateChangeset` by a logic that determines if the changeset should be taken out of draft mode and "undraft" the changeset accordingly. (No way back for now, though)
- [ ] Update the action logic in the reconciler to handle `Draft` like `True` (should be OK, because the client later on will do the right action on the code host, based on the Draft flag on the spec)
- [ ] Make sure the changeset spec title is not dirty when in draft mode on GitLab, where we need to alter the title.

> NOTE: For the GitLab related things, i'll only tackle them once the simpler to implement GitHub works. They're next to each other in the list though to make it a little less overwhelming.

### Questions
- [ ] Do changeset specs also reflect the changed title for GitLab? Or just changesets once synced?
- [ ] I think we don't need a draft field on the changeset, given we can just take it from the associated spec. Also, it's only required for the Draft flag in the GraphQL API and for the changeset spec upload endpoint to update the title in the spec if draft is true. Depending on the number of cases where I end up needing it, I'll revisit and might be adding a `draft bool NOT NULL` column to `changesets`
