### ISSUE TITLE
Web: 3.14 tracking issue

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#8445]
## Planned Work

@attfarhan: __0.00d__

- [ ] Improve onboarding experience [#8584](https://github.com/sourcegraph/sourcegraph/issues/8584) __?d__ 
- [x] Unify definition of filters/suggestions in webapp [#8151](https://github.com/sourcegraph/sourcegraph/issues/8151) __?d__ 🧶
- [x] Track daily, weekly, monthly active users of search in pings [#7833](https://github.com/sourcegraph/sourcegraph/issues/7833) __?d__ 
- [x] Track usage of search modes in pings [#7831](https://github.com/sourcegraph/sourcegraph/issues/7831) __?d__ 

@eseliger: __0.50d__

- [ ] a8n/web: Campaign detail view scrolls to top when diff/changesets tab is changed [#7714](https://github.com/sourcegraph/sourcegraph/issues/7714) __0.5d__ 🐛

@felixfbecker: __0.50d__

- [x] Weird search results borders [#8760](https://github.com/sourcegraph/sourcegraph/issues/8760) __?d__ 🐛
- [x] Horizontal scrolling of search results doesn't work in Firefox [#8757](https://github.com/sourcegraph/sourcegraph/issues/8757) __?d__ 🐛
- [x] Site init page shows in dark theme if OS dark theme is enabled [#6420](https://github.com/sourcegraph/sourcegraph/issues/6420) __0.5d__ 🐛👩

@lguychard: __8.00d__

- [x] new search autocompletion gets in my way [#8904](https://github.com/sourcegraph/sourcegraph/issues/8904) __?d__ 
- [x] smartSearch doesn't recognize index field [#8860](https://github.com/sourcegraph/sourcegraph/issues/8860) __0.5d__ 🐛
- [ ] Search bar no longer updating to show current repo with smartSearchField turned on [#8839](https://github.com/sourcegraph/sourcegraph/issues/8839) __0.5d__ 🐛
- [x] Triple quotes cause a query to become invisible [#8801](https://github.com/sourcegraph/sourcegraph/issues/8801) __0.5d__ 🐛
- [ ] Suggestion icons hard to see in light theme [#8764](https://github.com/sourcegraph/sourcegraph/issues/8764) __0.5d__ 🐛
- [ ] Search bar and directory page have different search bars [#8752](https://github.com/sourcegraph/sourcegraph/issues/8752) __0.5d__ 🐛
- [ ] New search autocomplete yields no results in this particular case [#8749](https://github.com/sourcegraph/sourcegraph/issues/8749) __?d__ 
- [x] type:code doesn't work in smartSearchField [#8742](https://github.com/sourcegraph/sourcegraph/issues/8742) __0.5d__ 🐛
- [x] type:file missing in smartSearchField [#8741](https://github.com/sourcegraph/sourcegraph/issues/8741) __0.5d__ 🐛
- [ ] Missing space when inserting new filter [#8740](https://github.com/sourcegraph/sourcegraph/issues/8740) __0.5d__ 🐛
- [x] Newline possible in new search UI [#8738](https://github.com/sourcegraph/sourcegraph/issues/8738) __0.5d__ 🐛
- [x] search bar: Ctrl-f on website cut off [#8736](https://github.com/sourcegraph/sourcegraph/issues/8736) __0.5d__ 🐛
- [ ] Cursor is put at the beginning of search field after submitting (instead of staying at end) [#8731](https://github.com/sourcegraph/sourcegraph/issues/8731) __0.5d__ 🐛
- [ ] Branch/commit/tag selector dropdown is slow on giant monorepo (100K+ branches) [#8594](https://github.com/sourcegraph/sourcegraph/issues/8594) __?d__ 
- [x] onboarding confetti hidden by other layers in web UI [#8527](https://github.com/sourcegraph/sourcegraph/issues/8527) __0.5d__ 🐛
- [ ] Web: 3.14 tracking issue [#8445](https://github.com/sourcegraph/sourcegraph/issues/8445) __?d__ 
- [ ] MonacoQueryInput theme is broken on pages that have another Monaco editor [#7697](https://github.com/sourcegraph/sourcegraph/issues/7697) __1d__ 🐛
- [ ] MonacoQueryInput does not shrink when the window is resized. [#7692](https://github.com/sourcegraph/sourcegraph/issues/7692) __1d__ 🐛
- [ ] Clicking "Show more" at end of a result set does not jump you back to the top of the page [#7024](https://github.com/sourcegraph/sourcegraph/issues/7024) __?d__ 🐛

@ryanslade: __3.00d__

- [x] campaigns: Allow filtering/sorting of campaigns and changesets in campaigns [#8462](https://github.com/sourcegraph/sourcegraph/issues/8462) __3d__ 

Unassigned: __0.00d__

- [ ] Track usage of search filters in pings [#7832](https://github.com/sourcegraph/sourcegraph/issues/7832) __?d__ 

## Legend

👩 Customer issue
🐛 Bug
🧶 Technical debt
🛠️ Roadmap
🕵️ Spike
🔒 Security issue

**Comment by lguychard** [comment]
@attfarhan could you create a placeholder issue in 3.14 with the `team/web` label for work on the onboarding experience?

**Comment by lguychard** [comment]
## W06 Summary
- Merged https://github.com/sourcegraph/sourcegraph/pull/8452
- Worked on customer issues: https://github.com/sourcegraph/sourcegraph/pull/8515, https://github.com/sourcegraph/sourcegraph/pull/8520, https://github.com/sourcegraph/sourcegraph/pull/8528, https://github.com/sourcegraph/sourcegraph/pull/8530
- Hiring
- Lattice direct report reviews

## W07 Plan
- Finalize web 3.14 tracking issue
- Triage web backlog
- Hiring

**Comment by eseliger** [comment]
## W06 Summary
- Worked through feedback on campaigns UI, still need to transform notes into an issue
- Planning for 3.14, especially prioritize and triage remote code execution
- Small fix for the flickering loader https://github.com/sourcegraph/sourcegraph/pull/8464
- Architecture interview
- Built a spike prototype for the discussed ideas of remote code execution

## W07 Plan
- Finalize campaigns 3.14 tracking issue
- Possibly proceed work on spike
- Otherwise focus on campaigns UI feedback (or both if time allows)

**Comment by attfarhan** [comment]
## W06 summary
- Merged fix for code tab getting toggled when query changed https://github.com/sourcegraph/sourcegraph/commit/1f791aa1e566494419646a50ffbba62e24c3f516
- FilterInput unit tests https://github.com/sourcegraph/sourcegraph/commit/a94bd3029b2adace5984e1c9de014ad114189c47
- Merged tracking search modes PR https://github.com/sourcegraph/sourcegraph/commit/e5eb213088c409feeabccb1065f213a4fe3d4e1c
- Worked on unifying SuggestionTypes and FilterTypes enums (https://github.com/sourcegraph/sourcegraph/compare/master...fa/unify-filters)

## W07 plan
- Finish unifying SuggestionTypes and FilterTypes 
- Start work on including search modes tracking in pings
- Start work on onboarding RFC

**Comment by lguychard** [comment]
## W07 Summary

- Did a UX review of the smart search field with Christina and fixed some issues so that we can enable it on sourcegraph.com:
    - https://github.com/sourcegraph/sourcegraph/pull/8605
    - https://github.com/sourcegraph/sourcegraph/pull/8613
    - https://github.com/sourcegraph/sourcegraph/pull/8615
    - https://github.com/sourcegraph/sourcegraph/pull/8616
    - https://github.com/sourcegraph/sourcegraph/pull/8639
- Helped out with some [code intel](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1582800114052600) [issues](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1582849832066200)
- Wrapped up Lattice
- Hiring

## W08 Plan

- Backlog triage: closing stale issues, cleaning up labels, identifying & prioritizing high-impact existing issues in our backlog.
- Bug: #8527
- Add a unit test asserting desired behaviour for #7024
- Investigate quick win for #8594
- Hiring

**Comment by attfarhan** [comment]
## W07 Summary
- Researched, compiled, and triaged issues with our onboarding flow, and wrote [RFC 121: Onboarding improvements](https://docs.google.com/document/u/1/d/1BlJcrn_nCnzSw7_2M2QG9hLABTvqLPvmhz4XCQkglhw/edit#) 
- Merged [Unify SuggestionTypes and FilterTypes enums](https://github.com/sourcegraph/sourcegraph/pull/8577)
- [Remove literal search toast](https://github.com/sourcegraph/sourcegraph/commit/a94b5232e8a78be635cb1479892647f9e8782e68) 

## W08 plan
- Start work on including search modes tracking in pings
- Start work on tracking daily, weekly, monthly active users of search in pings
- Fix interactive mode filters have trouble with double quotes #8418

**Comment by attfarhan** [comment]
## W08 summary
- Technical experience interview 
- Fix case:yes queries not working https://github.com/sourcegraph/sourcegraph/commit/3cb9d1182a31c88710e4075446eb7392a46303e4
- Started working on pings
- Responded to feedback on RFC 121
- Diagnose customer issue: accidental LastPass accidental entry https://github.com/sourcegraph/sourcegraph/issues/8834

## W09 plan
- Wrap up pings
- Fix interactive mode filters have trouble with double quotes

**Comment by eseliger** [comment]
## W08 summary
- Architecture interview, debrief Simon and 6 coding assignments graded
- Put way more effort than expected in https://github.com/sourcegraph/customer/issues/13 but found many bugs and had debug sessions with @mrnugget half the week
	- this is awaiting some PRs to be finished up, then i'll revisit for final testing and cleanup
- Extended the BBS plugin and fixed a bug that would slowly tear down the BBS instance 
- Sat down with @tsenart and @mrnugget to debug other parts of the BBS plugin
- Improved dev startup speed https://github.com/sourcegraph/sourcegraph/pull/8840
- Completed https://github.com/sourcegraph/sourcegraph/pull/8464
- Started work on browser extension nightly e2e builds, not finished yet though
- Finished up work on campaigns UI feedback https://github.com/sourcegraph/sourcegraph/pull/8663

## W09 plan
- First technical experience interview
- Finish up delivery plan for campaign updates
- Finish draft of remote code execution prototype
- Room for debugging and doc improvements for campaigns + updates and webhooks

**Comment by felixfbecker** [comment]
## W08 summary

- Architecture interview & debrief
- ✨ dependency upgrade week
- Added new ESLint rule to catch a common class of bugs (`undefined` in template strings)
- Fixed P1 extension API/code intel bug https://github.com/sourcegraph/sourcegraph/pull/8877 https://github.com/sourcegraph/code-intel-extensions/pull/303
- Some build improvements over at https://github.com/sourcegraph/code-intel-extensions

## W09
- Finish https://github.com/sourcegraph/sourcegraph/pull/6546
- Start on [RFC 67: Authentication UI in native integrations/browser extension](https://docs.google.com/document/d/14hpJWb_K81r0A8ciFGbR2FrdYvU6M4SaLJNYyWTAfu4/edit)

**Comment by lguychard** [comment]
## W09 Summary

- Smart search fixes. A fix from last week caused an annoying bug: https://github.com/sourcegraph/sourcegraph/pull/8980
- Hiring (busy pipeline last week)

## W10

- Smart search fixes (haven't been able to do everything I wanted on that front).
- Hiring.

**Comment by felixfbecker** [comment]
## W09 Summary

- Interview
- Fixing browser extension release and e2e tests, incl. Firefox
  - Didn't get to make progress on the auth stuff yet, this is a prerequisite

## W10

- Native integration auth hints
- Interview

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by eseliger** [comment]
## W09 Summary

- Many code screens and interviews
- Improvements and bug fixes for discovered problems in campaigns
	- #8957 
	- #8992 
	- #8955 
	- #8956 
	- #8991 
	- #8952 
	- #9026 
	- #9028 
	- #9035 
	- #9030 
	- #8948 
	- #9031 

## W10

- Some more low hanging fruit improvements on the campaigns UI and debt 
- Campaigns iteration planning
- Finishing off the campaign updates delivery plan
- Interviews
