### ISSUE TITLE
campaigns: Improve UX of using the src CLI with Automation

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#8479]
This is a meta-issue to collect the issues in the `src-cli` repository that I plan to be working on in the next iteration:

- [x] a8n: Node package upgrade campaign not failing when yarn-error.log file produced https://github.com/sourcegraph/src-cli/issues/131
- [x] search and scopeQuery return different number of results https://github.com/sourcegraph/src-cli/issues/125
- [x] a8n: Need command to either run automation ignoring the cache and/or deleting the cache https://github.com/sourcegraph/src-cli/issues/115
- [x] a8n: Cannot use `count` in `scopeQuery` https://github.com/sourcegraph/src-cli/issues/114
- [x] a8n: Doesn't support namespaced Docker image names e.g, sourcegraph/rxjs-upgrade https://github.com/sourcegraph/src-cli/issues/113
- [x] a8n: Steps should not be cached if the Docker image has been rebuilt. SHA needs to be checked, not just the tag https://github.com/sourcegraph/src-cli/issues/112
- [x] Diff produced by src actions exec doesn't respect gitignore https://github.com/sourcegraph/src-cli/issues/137
- [x] Don't fail actions exec if only a subset of repositories failed https://github.com/sourcegraph/src-cli/issues/129
- [x] a8n: Output shows duplicate lines when verbose flag is given https://github.com/sourcegraph/src-cli/issues/119
- [x] Unzip failed with interactive message https://github.com/sourcegraph/src-cli/issues/109
- [x] a8n: Hitting `Ctrl-C` when running `src action exec` doesn't kill spawned containers https://github.com/sourcegraph/src-cli/issues/117
- [x] Add `src actions create` command to create actions.json boilerplate https://github.com/sourcegraph/src-cli/issues/153
- [x] Use JSON schema to validate that a given action definition is valid https://github.com/sourcegraph/src-cli/issues/155

**Comment by tsenart** [comment]
@mrnugget: This didn't have the campaigns label so we didn't look at it. Please triage.

**Comment by mrnugget** [comment]
I'll continue work on this in 3.15, since it grew in 3.14.
