### ISSUE TITLE
Core Services: 3.14 Tracking Issue

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#8552]
### Status

This tracking issue is active.

### Availability

Period is the February 21st until March 17th. Please put in the days you won't be working and the number of working days for the period.

- @keegancsmith: 17d. Not working 24th February.
- @mrnugget: 18d
- @rvantonder: 18d
- @ryanslade: 18d
- @tsenart: 5d
- @unknwon: 18d

### Planned work

@keegancsmith: __0.50d__

- [ ] indexed-search: more prometheus metrics for search [#9111](https://github.com/sourcegraph/sourcegraph/issues/9111) __?d__ 
- [ ] allow cloning a specific branch only [#8875](https://github.com/sourcegraph/sourcegraph/issues/8875) __?d__ 👩
- [x] sourcegraph/customer [#32](https://github.com/sourcegraph/customer/issues/32) __?d__ 👩
- [x] Search became slower [#8589](https://github.com/sourcegraph/sourcegraph/issues/8589) __?d__ 
- [x] repohascommitafter:'1 week ago' type:repo .+ returns empty result set [#8568](https://github.com/sourcegraph/sourcegraph/issues/8568) __?d__ 👩
- [x] sourcegraph/customer [#19](https://github.com/sourcegraph/customer/issues/19) __?d__ [👩](https://app.hubspot.com/contacts/2762526/company/554275594)
- [x] db: drop repos.enabled column in 3.15 [#7815](https://github.com/sourcegraph/sourcegraph/issues/7815) __0.5d__ 🧶
- [x] CLA bot broken [#5839](https://github.com/sourcegraph/sourcegraph/issues/5839) __?d__ 🐛
- [ ] ~simple traces for search~ [#8655](https://github.com/sourcegraph/sourcegraph/issues/8655) __?d__ 
- [ ] ~Update docs for "Adding repositories already cloned to disk"~ [#8412](https://github.com/sourcegraph/sourcegraph/issues/8412) __2d__ [👩](https://app.hubspot.com/contacts/2762526/company/554275594)🐛
- [ ] ~Docs page for "using Sourcegraph with a monorepo"~ [#8411](https://github.com/sourcegraph/sourcegraph/issues/8411) __1d__ [👩](https://app.hubspot.com/contacts/2762526/company/554275594)
- [ ] ~docs: Ensure new arch for repo-updater is reflected in dev docs~ [#3911](https://github.com/sourcegraph/sourcegraph/issues/3911) __0.5d__ 🧶
- [ ] ~docs: Document using an alternate clone URL for repos~ [#658](https://github.com/sourcegraph/sourcegraph/issues/658) __0.5d__ 🧶

@mrnugget: __3.00d__

- [x] Updating a Campaign with same diff/base-branch for already-merged changeset fails [#8846](https://github.com/sourcegraph/sourcegraph/issues/8846) __2d__ 🐛
- [x] Webhook always initialized with example.com [#8827](https://github.com/sourcegraph/sourcegraph/issues/8827) __0.5d__ 🐛
- [x] Handle Campaigns with description = NULL in database [#8772](https://github.com/sourcegraph/sourcegraph/issues/8772) __0.5d__ 🐛
- [x] sourcegraph/customer [#24](https://github.com/sourcegraph/customer/issues/24) __?d__ 👩
- [ ] sourcegraph/customer [#18](https://github.com/sourcegraph/customer/issues/18) __?d__ 👩
- [ ] ~a8n: Support Bitbucket build status webhooks~ [#8480](https://github.com/sourcegraph/sourcegraph/issues/8480) __1d__ 
- [ ] ~campaigns: Improve UX of using the src CLI with Automation~ [#8479](https://github.com/sourcegraph/sourcegraph/issues/8479) __3d__ 🛠️
- [ ] ~campaigns Spike: Executing src actions on a server~ [#7723](https://github.com/sourcegraph/sourcegraph/issues/7723) __4d__ 🛠️

@rvantonder: __7.00d__

- [x] Use search index when @commit is specified and matches HEAD [#9022](https://github.com/sourcegraph/sourcegraph/issues/9022) __1d__ 👩
- [x] Add search metrics for time-to-first-result [#8306](https://github.com/sourcegraph/sourcegraph/issues/8306) __3d__ 
- [x] Should archives and forks be excluded by default? [#7004](https://github.com/sourcegraph/sourcegraph/issues/7004) __3d__ 👩
- [ ] ~search: Implement AND / OR for file contents~ [#8567](https://github.com/sourcegraph/sourcegraph/issues/8567) __12d__ 👩🛠️
- [ ] ~Address repohascommitafter search filter performance bottleneck~ [#6745](https://github.com/sourcegraph/sourcegraph/issues/6745) __1d__ 👩🕵️

@ryanslade: __10.50d__

- [x] Newly created changesets are not synced for hours [#8909](https://github.com/sourcegraph/sourcegraph/issues/8909) __?d__ 🐛
- [x] GitHub changeset CI status not consistently correct [#8787](https://github.com/sourcegraph/sourcegraph/issues/8787) __0.5d__ 🐛
- [x] Changeset syncing should not occur on the frontend [#8587](https://github.com/sourcegraph/sourcegraph/issues/8587) __1.5d__ 🧶
- [x] Redactor can be too aggressive [#8586](https://github.com/sourcegraph/sourcegraph/issues/8586) __0.5d__ 🐛
- [x] campaigns: Allow filtering/sorting of campaigns and changesets in campaigns [#8462](https://github.com/sourcegraph/sourcegraph/issues/8462) __3d__ 
- [x] Diagnose and fix slow /.api/registry/extensions endpoint [#7544](https://github.com/sourcegraph/sourcegraph/issues/7544) __1d__ 🧶
- [x] campaigns: Heuristic syncing of Changesets and ChangesetEvents [#6388](https://github.com/sourcegraph/sourcegraph/issues/6388) __4d__ 🧶
- [ ] ~Instrument changeset syncing~ [#8588](https://github.com/sourcegraph/sourcegraph/issues/8588) __1.5d__ 
- [ ] ~Use shared and configurable rate limiter~ [#8546](https://github.com/sourcegraph/sourcegraph/issues/8546) __1d__ 

@tsenart: __0.00d__

- [x] RFC 113: Implement `PermsFetcher` interface for Bitbucket Server authz provider [#8891](https://github.com/sourcegraph/sourcegraph/issues/8891) __?d__ 
- [ ] Core Services: 3.14 Tracking Issue [#8552](https://github.com/sourcegraph/sourcegraph/issues/8552) __?d__ 
- [ ] ~Reject invalid externalURL with non-/ path~ [#7884](https://github.com/sourcegraph/sourcegraph/issues/7884) __0.5d__ 🐛

@unknwon: __9.50d__

- [x] Filter out soft-deleted repositories when syncing permissions [#9076](https://github.com/sourcegraph/sourcegraph/issues/9076) __0.5d__ 
- [ ] ~RFC 113: Implement `PermsFetcher` interface for GitHub authz provider~ [#8890](https://github.com/sourcegraph/sourcegraph/issues/8890) __?d__ 
- [x] RFC 113: Implement `authz.PermsScheduler` [#8708](https://github.com/sourcegraph/sourcegraph/issues/8708) __1d__ 🛠️
- [x] RFC 113: Change `authzFilter` to adopt new ways to check permissions [#8630](https://github.com/sourcegraph/sourcegraph/issues/8630) __1d__ 🛠️
- [x] "head>" string shows up in long-line search results [#8619](https://github.com/sourcegraph/sourcegraph/issues/8619) __?d__ 🐛
- [ ] RFC 113: Instrumenting `PermsSyncer` [#8612](https://github.com/sourcegraph/sourcegraph/issues/8612) __0.5d__ 🛠️
- [x] RFC 113: Schedule permissions syncing for new repositories added [#8609](https://github.com/sourcegraph/sourcegraph/issues/8609) __0.5d__ 🛠️
- [x] RFC 113: Make `provider` column nullable for perms table [#8608](https://github.com/sourcegraph/sourcegraph/issues/8608) __0.5d__ 🛠️
- [x] RFC 113: Implement `authz.PermsStore.SetUserPermissions` method [#8607](https://github.com/sourcegraph/sourcegraph/issues/8607) __0.5d__ 🛠️
- [x] Ambiguous association between permissions and authz provider [#8597](https://github.com/sourcegraph/sourcegraph/issues/8597) __0.5d__ 
- [x] repo-updater: Updates every repository on every syncer sync [#8501](https://github.com/sourcegraph/sourcegraph/issues/8501) __1d__ 🐛👩
- [x] RFC 113: Implement `PermsFetcher` interface for GitLab authz provider [#8492](https://github.com/sourcegraph/sourcegraph/issues/8492) __1d__ 🛠️
- [x] RFC 113: Implement `authz.PermsSyncer` [#8376](https://github.com/sourcegraph/sourcegraph/issues/8376) __2d__ 🛠️
- [x] Issue using SAML auth provider with Jumpcloud [#2143](https://github.com/sourcegraph/sourcegraph/issues/2143) __0.5d__ 
- [x] ~RFC 113: Change default user mapping bind type to username~ [#8611](https://github.com/sourcegraph/sourcegraph/issues/8611) __0.5d__ 🛠️
- [ ] ~RFC 113: Schedule permissions syncing upon user log in~ [#8610](https://github.com/sourcegraph/sourcegraph/issues/8610) __0.5d__ 🛠️
- [ ] ~Use serializable transactions for updating permissions~ [#7877](https://github.com/sourcegraph/sourcegraph/issues/7877) __2d__ 🕵️
- [ ] ~Forbidden - CSRF token invalid~ [#7368](https://github.com/sourcegraph/sourcegraph/issues/7368) __2d__ 🐛

@uwedeportivo: __4.00d__

- [x] kubernetes: admin service debug page discovers endpoints [#8654](https://github.com/sourcegraph/sourcegraph/issues/8654) __4d__ 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue

**Comment by tsenart** [comment]
@sourcegraph/core-services: Please propose additional work for the iteration if it hasn't yet been milestoned and labeled accordingly.

**Comment by rvantonder** [comment]
**W06 Summary**

- Made progress on adding search latency metrics to sourcegraph.com #8432. Been waiting on #8423 to stabilize to finish this up.
- Updated RFC 94 with summary from feedback and the plan for implementing AND/OR expressions
- Started refactoring search code to prepare for changes to query for the above
- Fixed small issues for better structural search usability 
- Did some e2e testing and updated docs for running them

**W07 Plan**

- Implement parser for AND/OR expressions
- Add search functionality on files for above (probably not going to happen this week, but maybe towards the end)
- Continue organizing/refactoring search code as needed for the above

**Comment by unknwon** [comment]
### W06 Summary
* [x] Reviewed one code exercise, participated one followup call
* [x] Revised and got approval for  [RFC 113: Move GitLab permissions syncing to background in repo-updater](https://docs.google.com/document/d/1x3Y9jZzjJlJqmJ2czJ4A1NXKbY4hMa9K9pn1501r5IY/edit) 
* [x] [repo: normalize `private` column from the `metadata`](https://github.com/sourcegraph/sourcegraph/pull/8495)
* [ ] Support customer issue  [Can not add new user to Sourcegraph by JumpCloud SAML problem](https://sourcegraph.atlassian.net/browse/SG-68) 
	* Waiting for customer response
* [ ] repo-updater: Updates every repository on every syncer sync [#8501](https://github.com/sourcegraph/sourcegraph/issues/8501)
	* Missing tests and CHANGELOG entry
* MISC: 
	* #8483
	* sourcegraph/about#589
	* sourcegraph/customer#29

### W07 Plan [2020-02-24]
- One video interview call
- repo-updater: Updates every repository on every syncer sync [#8501](https://github.com/sourcegraph/sourcegraph/issues/8501) **0.5d**
- RFC 113: Implement PermsSyncer scheduler #8376 **2d**
- Spike: add cross-repo hover tips to lsif-go **0.5d**

**Comment by mrnugget** [comment]
### Previous week

- Fixed a bug in the campaign update logic https://github.com/sourcegraph/sourcegraph/pull/8437
- Did some TypeScript! https://github.com/sourcegraph/sourcegraph/pull/8482
- Started prototyping a "remote version" of `src action exec` https://github.com/sourcegraph/src-cli/pull/128
- Multiple small fixes and improvements in `src-cli` (https://github.com/sourcegraph/src-cli/pull/132, https://github.com/sourcegraph/src-cli/pull/133, https://github.com/sourcegraph/src-cli/pull/135, https://github.com/sourcegraph/src-cli/pull/136, https://github.com/sourcegraph/src-cli/pull/138)
- Renamed `a8n` to `campaigns` in the codebase!
- Planning, interviews, sync with product on next steps for `src-cli` 
- Took over a customer issue and reached out to them https://github.com/sourcegraph/customer/issues/24

### W07 Plan [2020-02-24]

After talking with @christinaforney and @eseliger on Friday about the future of `src-cli`, I will start to
- (a) implement some more UX fixes and suggestions to improve the local-only workflow
- (b) start prototyping & writing an RFC for a proper multi-agent mode for `src actions`

Point (b) is the result of learning from the prototype in https://github.com/sourcegraph/src-cli/pull/128. We realized that it does not provide enough value (compared to `ssh & tmux & src action exec` on a big machine) to warrant the effort to build it out proper.

A multi-agent model, where agents pull work from and report progress to Sourcegraph, does provide more value and also moves us in the direction we want to head in anyway (where we can add a web UI to start/watch actions). More details going to be discussed in today's Campaigns sync.

Besides that I'm going to:
- Following up on customer issue
- Multiple interviews

**Comment by kzh** [comment]
**W06 Summary**

- Fixed a bug with BBS plugin permissions endpoint https://github.com/sourcegraph/sourcegraph/pull/8549
- Added a release script for BBS plugin https://github.com/sourcegraph/bitbucket-server-plugin/pull/19
- Added webhook support for build status events in BBS plugin https://github.com/sourcegraph/bitbucket-server-plugin/pull/18
- Did some testing (validation for permissions + webhook, instance setup, minor stress test) around BBS Sourcegraph plugin setup for https://github.com/sourcegraph/customer/issues/18, worked on docs.

**W07 Plan**
- Open PR for https://github.com/sourcegraph/customer/issues/18 docs.
- Open PR for https://github.com/sourcegraph/sourcegraph/issues/6745

**Comment by ryanslade** [comment]
## W06 Summary

* Enable CheckRun syncing for changesets
* Addressed a couple of issues around redacting sensitive urls
* Started work related to heuristic syncing

## W07 Plan

* Prototype heuristic syncing + Create RFC from prototype
* I imagine the above will lead me creating smaller tickets such as https://github.com/sourcegraph/sourcegraph/issues/8546
* Multiple interviews

**Comment by rvantonder** [comment]
@tsenart my current work items is stable and what I've settled on for this iteration.

**Comment by tsenart** [comment]
Thanks @rvantonder. @keegancsmith, @mrnugget, @ryanslade, @unknwon: Is your planned work ready? Please let me know as I want to finalise the tracking issue today.

**Comment by unknwon** [comment]
@tsenart I've finished arranging work items for this iteration.

**Comment by mrnugget** [comment]
@tsenart Yes, mine is stable, even though it's hard to put concrete estimates on it, since I suspect that some things will change in the course of the iteration (since we're trying out and prototyping a lot of things with `src` CLI)

**Comment by keegancsmith** [comment]
My work will be in flux all iteration, as I triage/investigate the current and incoming customer issues. The things that are not customer related are minor documentation/debt that I will tackle and can be regarded as stable.

**Comment by ryanslade** [comment]
@tsenart My work is stable unless I need to take over anything from Kevin

**Comment by tsenart** [comment]
@nicksnyder, @christinaforney: The tracking issue is ready for your review.

**Comment by nicksnyder** [comment]
LGTM

nit: there are some references to a8n :)

question: This week is week 7? Should reset for new release cycle right?

**Comment by tsenart** [comment]
> question: This week is week 7? Should reset to 0 for new release cycle right?

Are you referring to the weekly status updates? We haven't reset before, it's always been the week of the year (starting at 0), like we use in Company Meeting.

**Comment by rvantonder** [comment]
**W07 Summary**

Focused almost singularly on the AND/OR query parser. This is, in some ways, the most important part to get right and I feel good about the direction and implementation for building things out.

- Implemented query parser in #8633. Partial progress on migrating the scanner logic in https://github.com/sourcegraph/sourcegraph/commit/7aeab1fde7a01fe0cb33038634d9c59d02ae7a0a
- Investigated fuzz testing on parser code and ran it for a couple of hours (no bugs)
- Minor: get rid of flaky lint #8582
- Interview

**W08 Plan**

- Integrate AND/OR parser with what we currently use for our parser scanner, then migrate our existing tests. I made partial progress on this last week.
- Mid-week, I expect to have prototype support/translate AND/OR queries for content search. After that, I expect to polish and thoroughly test for the rest of the week
- Set aside 0.5d to 1d to investigate #6745
- (Re)-prioritize search latency PR. Dependent on #8423 which isn't landed yet, but I can still make progress without it.

**Comment by unknwon** [comment]
### W07 Summary
- [x] Did two video interview calls
- [x] repo-updater: Updates every repository on every syncer sync  [#8501](https://github.com/sourcegraph/sourcegraph/issues/8501) 
- [x] “head>” string shows up in long-line search results  [#8619](https://github.com/sourcegraph/sourcegraph/issues/8619) 
- [x] Issue using SAML auth provider with Jumpcloud [#2143](https://github.com/sourcegraph/sourcegraph/issues/2143)
- RFC 113: Implement `authz.PermsSyncer`  [#8376](https://github.com/sourcegraph/sourcegraph/issues/8376) 
	* PR #8571, addressed feedback first round of review
- Can not add new user to Sourcegraph by JumpCloud SAML problem [SG-68](https://sourcegraph.atlassian.net/browse/SG-68)
	* Waiting for customer
- Ambiguous association between permissions and authz provider  [#8597](https://github.com/sourcegraph/sourcegraph/issues/8597) 
	* 	Wait to be solved by migrating all authz providers to use permissions tables
- MISC: 
	* #8570, #8625, #8648

### W08 Plan [2020-03-02]

- One video interview call
- RFC 113: Implement `authz.PermsSyncer` [#8376] (https://github.com/sourcegraph/sourcegraph/issues/8376) **0.5d**
- RFC 113: Implement `authz.PermsStore.SetUserPermissions` method #8607 **0.5d**
- RFC 113: Remove provider columns in repo and user permissions table #8608 **0.5d**
- RFC 113: Implement PermsFetcher interface for GitLab authz provider #8492 **1d**
- RFC 113: Implement authz.PermsScheduler #8708 **1d**
- Can not add new user to Sourcegraph by JumpCloud SAML problem [SG-68](https://sourcegraph.atlassian.net/browse/SG-68)
	* Waiting for customer

**Comment by mrnugget** [comment]
### Previous week

- Following up on and ultimately fixing customer issue https://github.com/sourcegraph/customer/issues/24
- Various fixes in `src` CLI:
  - [Change wording of 'cached result found' log message](https://github.com/sourcegraph/src-cli/pull/146)
  - [Use git diff in temp repository instead of diff over directories](https://github.com/sourcegraph/src-cli/pull/144)
  - [Log cache hits when running 'src action exec](https://github.com/sourcegraph/src-cli/pull/143)
  - [Add -create-plan flag to 'src action exec](https://github.com/sourcegraph/src-cli/pull/142)
  - [Improve verbose output of src action exe](https://github.com/sourcegraph/src-cli/pull/141)
  - [Replace terminal UI with a more readable logger when src actions exec is run in verbose mode](https://github.com/sourcegraph/src-cli/pull/140)
- Multiple interviews

### W08 Plan [2020-03-02]

- Stand by for customer issues
- Continue thinking about and improving `src` CLI UX, probably moving more to Sourcegraph itself
- Writing down some thoughts I have regarding a concrete engineering/product vision for Campaigns 
- Decide how to continue with the prototype created by @eseliger in https://github.com/sourcegraph/sourcegraph/pull/8574

**Comment by ryanslade** [comment]
## W07 Summary

* Initial version of heuristic syncing ready for review
* Multiple interviews

## W08 Plan

* Add instrumentation to heuristic syncer
* Shared rate limiter for heuristic and auth syncing
* Maybe going to conference on Thurs / Friday with @keegancsmith. Tickets sold out but might still be able to get in

**Comment by keegancsmith** [comment]
### W07 Summary

First week of customer support. Ended up fixing a few issues, while filing a few others. It has been great to be directly interacting with customers to get a feeling for common issues customers run into. More importantly it improves my intuitions around projects we can do to improve our customer experience.

I've been focussed on filing issues rather than fixing them. Additionally been thinking of projects we can do. This will continue, and I will continue to resist the urge to jump into code :)

### W08 Plan

More of the same. It feels like the load will be less this week, so I will tackle one of the projects I think will help with customers / already planned work.

**Comment by ryanslade** [comment]
Change of plans, I won't be attending ScaleConf so I've got an extra two days of availability.

**Comment by unknwon** [comment]
### W08 Summary
* [x] Did one code exercise review and one followup call
* [x] Did one video interview call
* [x] RFC 113: Implement `authz.PermsStore.SetUserPermissions` method  [#8607](https://github.com/sourcegraph/sourcegraph/issues/8607)
* [x] Can not add new user to Sourcegraph by JumpCloud SAML problem  [SG-68](https://sourcegraph.atlassian.net/browse/SG-68) 	
* [x] RFC 113: Make `provider` column nullable for perms table  [#8608](https://github.com/sourcegraph/sourcegraph/issues/8608)
* [x] RFC 113: Implement PermsFetcher interface for GitLab authz provider  [#8492](https://github.com/sourcegraph/sourcegraph/issues/8492)
* RFC 113: Implement `authz.PermsSyncer ` [#8376](https://github.com/sourcegraph/sourcegraph/issues/8376)
	* #8571, #8792 merged, working on remaining tests and followups
* RFC 113: Implement `authz.PermsScheduler`  [#8708](https://github.com/sourcegraph/sourcegraph/issues/8708)
	* #8844 reviewed, addressing feedback
* Proposal: Use ExternalAccountSpec to identify user for pending permissions #8795
* MISC: 
	* #8718, #8793, #8813

### W09 Plan [2020-03-09]

_My theme this week is to ship RFC 113_

- One followup call
- Finishing up `authz.PermsSyncer` **2d**
- Webhook always initialized with example.com #8827 **0.5d**
- Test the background permission syncing end-to-end with GitLab **1.5d**
- Create delivery plan for RFC 113 **0.5d**

**Comment by ryanslade** [comment]
## W08 Summary

* A few iterations on the heap based changeset scheduler
* Initial PR for filtering changesets by state, review state and check state

## W09 Plan

* Get the above two items merged
* Add sorting and pagination for changesets
* Make code host rate limiter configurable and shared between at least the changeset and permissions syncer

**Comment by mrnugget** [comment]
### Previous week

I spent the majority of the week helping @eseliger testing and debugging the campaign he created for https://github.com/sourcegraph/customer/issues/13 That resulted in a lot of fixes and issues:

- Upper-case GitHub webhook event's state before conversion campaigns #8824
- Check error after failing to create a commit on gitserver campaigns #8823
- Compute Bitbucket Server changeset review state based on events campaigns #8821
- Ensure that Sourcegraph instances don't overwrite BBS webhook campaigns #8820
- Fix nil panics in webhook event conversion and fix log statement #8819
- Log when accepting/dropping webhook events from Bitbucket Server campaigns #8815
- Handle double-delivery of Bitbucket Server webhooks campaigns #8799
- Add a not-null constraint to {campaigns,campaign_jobs}.description campaigns #8788
- Fix unmarshaling and displaying of gitserver CreateCommitFromPatchError #8717

That combined nicely with documenting the `bitbucket-server-plugin` for https://github.com/sourcegraph/customer/issues/18 and improving the Campaigns documentation in general:

- Revise BBS documentation to mention webhooks and give clearer instructions #8791
- Document how to get started with Campaigns and add note about webhooks #8767

The rest of the week was spent on interviews, hacking on our docs, trying to get IntelliJ to run `bitbucket-server-plugin`, adding a mission/vision statement for Campaigns (https://github.com/sourcegraph/about/pull/623 and https://github.com/sourcegraph/about/pull/628)

### W08 Plan [2020-03-09]

- Finish writing documentation for the Bitbucket Server plugin and then check off: https://github.com/sourcegraph/customer/issues/18 There is one PR open for this that I want to get merged: https://github.com/sourcegraph/sourcegraph/pull/8845
- Keep assisting @eseliger with his testing efforts and fixing the bugs and rough edges that he (or I) discover. I still have these open draft PRs that I want to get in in one form or another:
  - Do not mark CampaignJob as "publication enqueued" if ChangesetJob failed #8825
  - WIP: Compute a changeset's state based on events #8822
  - Test updating unchanged ChangsetEvent doesn't modify database row #8771
- Then I also want to fix this issue that is blocking @eseliger: https://github.com/sourcegraph/sourcegraph/issues/8846

Besides that: I want to try to get some improvements to our docs merged, interviews, getting back into `src` CLI improvements, hopefully start to pick up remote-code execution prototype.

**Comment by rvantonder** [comment]
**W08 Summary**

- Spent the majority of my time rough prototyping for executing `and`/`or` queries so I have a clear idea how for breaking down the implementation/testing into subtasks. [Example clip on slack](https://sourcegraph.slack.com/files/UHKEYMS75/FUJM4QHUK/and-or-poc2.mp4).
- PRs for excluding forks and archived repos by default #8874 #8739 #8737
- Search latency tracking: Merged #8432. The last part is merging the PR to log timings, up at #8868 
- Didn't get time for to investigate #6745, will get to it this week.

**W09 Plan**

- Continue `and`/`or` query work. I will broadly be tackling tasks around any of:
  - extending the parser for various purposes (concatenation / literal vs regexp parsing)
  - query validation
  - merging existing query logic and tests with the new parser
  - search implementation and optimization
  - refactoring for the above
- Merge the work to make archive/forked repos excluded by default
- Investigate #6745
- Side task: structural search use cases for customers

**Comment by keegancsmith** [comment]
### W08 Summary
More customer support. Attended bits of a conference on Thursday and Friday and chatted to a few people about Sourcegraph. Was otherwise a bit of a low productivity week for me (sleep :/), should pick the pace back up this week.

### W09 Plan
My main priority is still customer support. But any time not spent doing customer support/code reviews will be spent on helping out on permissions background syncer. We want to ensure it is ready by branch cut, and its at a point where we can start sharing the remaining work.

**Comment by unknwon** [comment]
### W09 Summary
* [x] Did one followup call
* [x] Webhook always initialized with example.com  [#8827](https://github.com/sourcegraph/sourcegraph/issues/8827)
* [x] Update pending permissions tables to use fields of ExternalAccount #8795
	* #8973, #8979
* [x] Finished implementation of `authz.PermsSyncer`
	* #8844, #8927, #8931, #8932, #8967
* [x] RFC 113: Implement PermsFetcher interface for GitLab authz provider  [#8492](https://github.com/sourcegraph/sourcegraph/issues/8492) 
	* #8812, #8965
* RFC 113: Change authzFilter to adopt new ways to check permissions  [#8630](https://github.com/sourcegraph/sourcegraph/issues/8630) 
	* #8984
* MISC: 
	* #8884, #8906, #8966

### W10 Plan [2020-03-16]


* RFC 113: Change authzFilter to adopt new ways to check permissions  [#8630](https://github.com/sourcegraph/sourcegraph/issues/8630) 
	* #8984
* Add tests for `authz.PermsSyncer` **0.5d**
* Make `PermsStore.AuthzroizeRepos` return a third argument to indicate if the result is complete **0.5d**
* RFC 113: Instrumenting PermsSyncer #8612 **0.5d**
* GitLab e2e testing and fix critical issues revealed **1d**
* Bitbucket Server e2e testing and fix critical issues revealed **1d**

**Comment by rvantonder** [comment]
**W09 Summary**

I spent 80% of this week on customer-related search functionality. The highlight is that turning off search for forks by default caused unexpected and poor UX when searching an existing repo. I spent time on a solution for that (thanks @keegancsmith for suggesting a much easier approach than fiddling with the webapp). That needed careful testing, and I also discovered a discrepancy in how this is dealt with in sourcegraph.com versus other deploys due inconsistency in handling `type:repo` in queries. Basically: a lot of tricky cases and unexpected UX things to consider in search, and expensive to fix, test, and change comprehensively. In addition, the following happened:
- Backend search latency PR was merged and confirmed to successfully log to DB
- Put up a PR where we use the Zoekt index if the `@commit` part matches HEAD (likely to be an improvement for monorepo customers when we autofill queries with `@commit`)
- Added a `concat` operator to the new `and`/`or` parser.
- Silently fixed a ZIP64 issue in structural search for repos/zips that have a lot of central directory entries. Basically, you would get an ugly error message for certain repos with structural search.
- I _still_ didn't get time to look at `repohascommitafter` perf in #6745. This is important, but de-prioritized due to the other search issues needing more time.

**W10 Plan**

- Will look at #6745 first thing this week and get an idea of how much time is needed to help that effort.
- I expect my time will be less dominated by search functionality changes, so hope to spend most of my time making significant progress on `and`/`or` queries.
- We would like to log end-to-end search latency, including webapp. I plan to look into how we can do that on the webapp side.

**Comment by ryanslade** [comment]
W09 Summary

* Added support for filtering changesets by state, review state and check state
* Part of the above changes the code to precompute those values on sync or webhook so we now use the computed fields in resolvers
* Reuse bitbucket rate limiter between syncs

W10 Plan

* Help @mrnugget and @eseliger in ironing out rough campaign edges before branch cut
* Create an RFC for global code host rate limiting per external service

**Comment by mrnugget** [comment]
### Last week

I added documentation for the Bitbucket Server plugin and tweaked our docs a tiny bit while working on them (added global breadcrumbs, made headers consistent, etc.)

Also took some time to try to improve our local dev workflow and ended up improving our watch-recompile scripts in a way that stops _all_ Go services being restarted, even though they didn't change.

After @eseliger uncovered more bugs in our webhooks/events-based-changeset-state implementations I spent the latter part of the week focused on fixing those and improving them.

### This week

This week is going to be bumpy. Germany is in nearly full-on Corona mode: borders are closed, events are cancelled and, relevant to this thread, daycare is closed for the next 5 weeks. That means my wife and I will alternate watching our daughter throughout the day. I hope I can make it to all meetings on time and get some stuff done, but at this point I'd rather offer a disclaimer than make promises.

Well, at least the weather is nice.

Now, if I do manage to get things done, I want to:

* decide on how to get this to work: https://github.com/sourcegraph/sourcegraph/pull/8985 The crucial bit here is that this would introduce the possibility of a campaign being related to more than one campaign plan. The feature request behind this makes a lot of sense (you want to keep updating a campaign with new campaign plans because you keep executing your `src action exec` but not have merged/close changesets disappear), I just need to think through the ramifications.
* come up with a plan and actionable steps that will help us prevent this many bugs creeping into a feature or popping up as regressions. What I'm thinking: more integration-y tests in Go, e2e tests that actually test our workflow (by now I don't care whether we create a real pull request with every test run or not, in fact, I think we _should_), refactor our code so that we find better abstractions across multiple code hosts (those are leaky so far and it's easy to miss details specific to a single codehost)

The last point is also what I think we should focus on in the next iteration regarding campaigns.

**Comment by keegancsmith** [comment]
### W09 Summary

Usual focus on customer issues. Several minor src-expose changes after feedback from a customer. Lots of time spent on Zoekt slowness. Ongoing. https://github.com/sourcegraph/sourcegraph/issues/9001

### W10 Plan

Zoekt slowness https://github.com/sourcegraph/sourcegraph/issues/9001 and start planning for 3.15. Schools are closing down here so will be juggling childcare with my wife (who isn't always remote yet). As such I am in a similar boat as others with respect to focus time.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
