### ISSUE TITLE
search: Implement AND / OR for file contents

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#8567]
Parent issue: #7823. Breakdown of tasks:

- [x] Refactor / organize current query code (partially done) #8566 #8565 #8564
- [x] Implement the parser for the language (mostly done) #8633 #8802 #8784 #8809
- [x] Add search behavior for expressions. Breakdown:
  - [x] Critical: New query parser scaffolding (make a code path that uses the new query parser) #9167
  - [x] Critical: Feature flag the above #9168
  - [x] Critical: Query evaluation. Evaluate `and`/`or` queries. #9169
  - [x] Critical: Disambiguate parentheses part of search pattern (regex) versus expression grouping. #9170
  - [x] Critical: Query semantics for patterns (what are the semantics of concat). Separate implementation for each of literal, regexp, structural. #9171
  - [x] Important: Query validation. Separate implementation required for each of literal, regexp, and structural search patterns. #9172
  - [ ] Important: Remove the feature flag. Initially use a heuristic to only use the new parser if it contains `and`, `or` keywords. This will help ease a full transition away from the current parsing. #9176
  - [ ] Important: migrate current query parsing to use new parser, including tests. Separate implementation for each of literal, regexp, structural. (NOT NECESSARILY FOR 3.15)
---

Related documents: [RFC 94](https://docs.google.com/document/d/1nYv_p1138eHsN7WOw0s3x69Y0HK2L8x7VP-nFKQGal8/edit?ts=5e2845ae#heading=h.trqab8y0kufp)

**Comment by nicksnyder** [comment]
Is this RFC 94? If so, can you link to the RFC from the issue?

**Comment by rvantonder** [comment]
Sure thing. Note the umbrella issue for this lives in #7823

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Closing--follow up tasks can be tracked in a separate issue, the core functionality is implemented.
