### ISSUE TITLE
Search inputs that don't work but should

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#8780]
This is an umbrella tracking issue for all kinds of corner cases in search that are not handled properly. I'm tracking these because some will disappear when we switch to the new query parser.

- [x] - fixed by `migrateParser` - [`(" ")`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%28%22+%22%29&patternType=regexp) in regex mode https://github.com/sourcegraph/sourcegraph/issues/4562
- [x] - fixed by `migrateParser - Colons and field validation, `:` can't be searched, etc. https://github.com/sourcegraph/sourcegraph/issues/10171

- [x] - fixed by `migrateParser` - Quoted strings for field values do not interpret escape sequences properly for special character `\`. https://github.com/sourcegraph/sourcegraph/issues/10442#issuecomment-629460664

- [x] - The `/.../` syntax is more strict in a good way. File path-like patterns like `/foo/bar` will not be considered a regex delimiter, in the old parser it was. Solution: https://github.com/sourcegraph/sourcegraph/pull/12964 Previous issues: https://github.com/sourcegraph/sourcegraph/issues/9147 https://github.com/sourcegraph/sourcegraph/issues/6314

- [ ] - partially fixed by `migrateParser`, needs to validate non-empty `file:` - Broken single quotes in literal search: https://github.com/sourcegraph/sourcegraph/issues/8363
- [ ] - not fixed by `migrateParser` (out of scope for parsing) - [Impossible](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%5Cn*&patternType=regexp) to search for repeating `\n*` in regex mode 
- [ ] - not fixed by `migrateParser` (out of scope for parsing) - [Messed up](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%5C%5Cn*&patternType=regexp) results for `\\n*`, not even sure what's going on here.
  - Possibly related: `\n` only works on unindexed search path. https://github.com/sourcegraph/sourcegraph/issues/11364
- [ ] - `file:` as empty is accepted, but should probably be validated. partly resolved by content (give a suggestion) - [Can't search for file:](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+language:typescript+file:&patternType=literal) when the value is blank `repo:^github\.com/sourcegraph/sourcegraph$ language:typescript file:`. In regex mode, putting quotes around it [finds result](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+language:typescript+%22file:%22&patternType=regexp).

- [ ] - Need to better alert character class patterns that contain a space, out of scope for parser migration. Example: `repo:^github\.com/sourcegraph/sourcegraph$ \{[^ ]+` raises an alert `Error parsing regexp: missing closing ]: [^`, because we don't recognize the space in our language (it becomes concat). This is true of new and old parser, but it means we should alert why this doesn't compile.

- [ ] `file:"vendor/github.com/emicklei/go-restful/cors_filter.go|caddyhttp/push/handler.go|cmd/repo-updater/repos/testing.go" (for :[[i]], :[[x]] := range :[src.] { :[[dst]][:[i]] = :[[x]] } or if strings.ToLower(:[s1]) == strings.ToLower(:[s2])) type:file` returns no results with `stable:yes`. Why?

- [ ] - `migrateParser` interprets the same, could probably improve this - Very [weird case of regexp failing](https://sourcegraph.com/search?q=repo:%28github%5C.com/sourcegraph/zoekt%40ffff%29%7Cgithub%5C.com/sourcegraph/sourcegraph%24%407c8f6c29948971aface82432744ead4025345aa9+error+fork:yes&patternType=literal) on non-matching parens when they are matched. This is likely a problem with our scanner/parser: I think the parens are not legal values. The query: `repo:(github\.com/sourcegraph/zoekt@ffff)|github\.com/sourcegraph/sourcegraph$@7c8f6c29948971aface82432744ead4025345aa9 error fork:yes`. This will give an error:

<img width="928" alt="Screen Shot 2020-03-14 at 4 57 30 PM" src="https://user-images.githubusercontent.com/888624/76692505-e96f8380-6614-11ea-8290-aa037f304edd.png">

Unlike the usual malformed alert if the `)` is taken away:

<img width="1285" alt="Screen Shot 2020-03-14 at 4 58 04 PM" src="https://user-images.githubusercontent.com/888624/76692523-ff7d4400-6614-11ea-939f-5b8d7e5c53e8.png">

**This one is scary because it will return a nil results value [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@8d35afcc278fbd925d4d4a86913c10a1f0d59af4/-/blob/cmd/frontend/graphqlbackend/search_results.go#L577), but we set an alert if it is, so 'save' it, but it's still scary because I ran into this nil-deref issue [here](https://github.com/sourcegraph/sourcegraph/pull/9027).

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Closing because stale.
