### ISSUE TITLE
Core Services: 3.15 Tracking Issue

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#9116]
### Status

This tracking issue is WIP.

### Availability

Period is the March 21st until April 18th. Please put in the days you won't be working and the number of working days for the period.

- @keegancsmith: 9d. (Public holiday 10th and 13th. Conservatively halving my availability due to childcare + covid)
- @mrnugget: 14d. (Public holiday on 10th and 13th. Additionally probably 4-5d not working)
- @rvantonder: 18d (Not 10th and 13th)
- @ryanslade: 18d (10th and 13th April are holidays)
- @tsenart: 3d (23rd to 27th of March off)
- @unknwon: 19d. Not working April 6th (national holiday)

### Planned work

@keegancsmith: __6.00d__

- [x] Removing intermediate caching on frontend for raw endpoint [#9372](https://github.com/sourcegraph/sourcegraph/issues/9372) 
- [x] simple traces for search [#8655](https://github.com/sourcegraph/sourcegraph/issues/8655) __2d__ 
- [x] Update docs for "Adding repositories already cloned to disk" [#8412](https://github.com/sourcegraph/sourcegraph/issues/8412) __1d__ [👩](https://app.hubspot.com/contacts/2762526/company/554275594)🐛
- [x] Docs page for "using Sourcegraph with a monorepo" [#8411](https://github.com/sourcegraph/sourcegraph/issues/8411) __1d__ [👩](https://app.hubspot.com/contacts/2762526/company/554275594)
- [x] Automatically build zoekt in CI [#5819](https://github.com/sourcegraph/sourcegraph/issues/5819) __0.5d__ 🧶
- [x] No codeintel on go-ethereum [#4401](https://github.com/sourcegraph/sourcegraph/issues/4401) 🐛
- [x] docs: Ensure new arch for repo-updater is reflected in dev docs [#3911](https://github.com/sourcegraph/sourcegraph/issues/3911) __0.5d__ 🧶
- [x] docs: Document using an alternate clone URL for repos [#658](https://github.com/sourcegraph/sourcegraph/issues/658) __0.5d__ 🧶
- [x] Ability to run Sourcegraph Docker Image inside network with proxy [#250](https://github.com/sourcegraph/sourcegraph/issues/250) __0.5d__ 

@mrnugget: __9.00d__

- [x] Major regression in code host syncing / EXTSVC_CONFIG_FILE support? [#9779](https://github.com/sourcegraph/sourcegraph/issues/9779) 🐛
- [x] Merged GitHub changesets are first displayed as closed and, after next sync, as merged [#9396](https://github.com/sourcegraph/sourcegraph/issues/9396) 🐛
- [x] Updating a closed campaign with N already merged changesets creates N new changesets [#9395](https://github.com/sourcegraph/sourcegraph/issues/9395) __0.5d__ 🐛
- [x] Searching repositories with `src action exec` fails if they're being cloned [#9149](https://github.com/sourcegraph/sourcegraph/issues/9149) __0.5d__ 🧶
- [x] Get rid of legacy names and fields [#9106](https://github.com/sourcegraph/sourcegraph/issues/9106) __1.5d__ 🧶
- [x] Add a test for `RunChangesetJobs` [#9103](https://github.com/sourcegraph/sourcegraph/issues/9103) __0.5d__ 🧶
- [x] Burndown chart cannot reliably show past review state of GitHub pull requests [#9010](https://github.com/sourcegraph/sourcegraph/issues/9010) __0.5d__ 🐛
- [x] Existing merged changesets are “closed” and hence removed from the tracking campaign [#8981](https://github.com/sourcegraph/sourcegraph/issues/8981) __1.5d__ 🐛
- [x] campaigns: Improve UX of using the src CLI with Automation [#8479](https://github.com/sourcegraph/sourcegraph/issues/8479) __3d__ 🛠️
- [x] Add support for repository visibility filter in search [#8344](https://github.com/sourcegraph/sourcegraph/issues/8344) __1d__ [👩](https://app.hubspot.com/contacts/2762526/company/557475882)

@rvantonder: __16.50d__

- [x] Activate and/or queries for content search [#9176](https://github.com/sourcegraph/sourcegraph/issues/9176) __1d__ 👩🛠️
- [x] Query validation of literal, regexp, and structural search patterns [#9174](https://github.com/sourcegraph/sourcegraph/issues/9174) __4d__ 👩🛠️
- [x] Query validation of Sourcegraph language parameters [#9173](https://github.com/sourcegraph/sourcegraph/issues/9173) __3d__ 👩🛠️
- [x] Implement concat search pattern semantics for literal, regexp, structural search [#9171](https://github.com/sourcegraph/sourcegraph/issues/9171) __3d__ 👩🛠️
- [x] Add and/or query evaluation [#9169](https://github.com/sourcegraph/sourcegraph/issues/9169) __3d__ 👩🛠️
- [x] Feature flag and/or query code path [#9168](https://github.com/sourcegraph/sourcegraph/issues/9168) __0.5d__ 👩🛠️
- [x] Add and/or query parser scaffolding [#9167](https://github.com/sourcegraph/sourcegraph/issues/9167) __2d__ 👩🛠️
- [x] search: Implement AND / OR for file contents [#8567](https://github.com/sourcegraph/sourcegraph/issues/8567) 👩🛠️

@ryanslade: __9.50d__

- [x] Open changesets of a closed campaign are still being synced [#9402](https://github.com/sourcegraph/sourcegraph/issues/9402) __0.5d__ 🐛
- [x] RFC 132: Spawn changeset syncer per external service [#9198](https://github.com/sourcegraph/sourcegraph/issues/9198) __1d__ 
- [x] Report scheduled time of next changeset sync [#9108](https://github.com/sourcegraph/sourcegraph/issues/9108) __0.5d__ 
- [x] Matching GitHub webhook events by ref might match PRs in wrong repositories [#9009](https://github.com/sourcegraph/sourcegraph/issues/9009) __1d__ 🐛
- [x] Instrument changeset syncing [#8588](https://github.com/sourcegraph/sourcegraph/issues/8588) __1.5d__ 
- [x] RFC 132: Expose configurable rate limiter for external services [#8546](https://github.com/sourcegraph/sourcegraph/issues/8546) __3d__ 
- [x] a8n: Support Bitbucket build status webhooks [#8480](https://github.com/sourcegraph/sourcegraph/issues/8480) __1d__ 
- [x] Move background workers out of frontend [#7647](https://github.com/sourcegraph/sourcegraph/issues/7647) __1d__ 🧶
- [ ] ~RFC 132: Use rate limit data when scheduling changeset syncs~ [#9105](https://github.com/sourcegraph/sourcegraph/issues/9105) __1d__ 

@sqs

- [x] include the license key in pings [#9833](https://github.com/sourcegraph/sourcegraph/pull/9833) :shipit:

@tsenart

- [ ] Core Services: 3.15 Tracking Issue [#9116](https://github.com/sourcegraph/sourcegraph/issues/9116) 
- [x] Document licenses for third party open source projects that we depend on [#8659](https://github.com/sourcegraph/sourcegraph/issues/8659) 
- [x] tracking-issue: Fix top level PRs [#9805](https://github.com/sourcegraph/sourcegraph/pull/9805) :shipit:
- [x] tracking-issue: Fix #9774 [#9803](https://github.com/sourcegraph/sourcegraph/pull/9803) :shipit:
- [x] tracking-issue: Track Pull requests [#9711](https://github.com/sourcegraph/sourcegraph/pull/9711) :shipit:

@unknwon: __6.50d__

- [x] authz: add unit tests for `PermsSyncer` [#9160](https://github.com/sourcegraph/sourcegraph/issues/9160) __0.5d__ 🧶
  - [x] authz: add tests for `PermsSyncer` [#9269](https://github.com/sourcegraph/sourcegraph/pull/9269) :shipit:
- [x] authz: draw high-level design of `PermsSyncer` [#9158](https://github.com/sourcegraph/sourcegraph/issues/9158) __0.5d__ 
- [x] authz: `PermsSyncer` should use partial results when the user/repo has no permissions [#9157](https://github.com/sourcegraph/sourcegraph/issues/9157) __0.5d__ 
- [x] repo-updater: make `repos.Store.ListRepos` support filter by visibility and more efficient ExternalRepos [#9154](https://github.com/sourcegraph/sourcegraph/issues/9154) __0.5d__ 
- [x] search: just repo search fails to find sourcegraph repo [#9146](https://github.com/sourcegraph/sourcegraph/issues/9146) 🐛
- [x] repo-updater: potential data race in `DebugDump` [#9045](https://github.com/sourcegraph/sourcegraph/issues/9045) __0.5d__ 🐛
- [ ] sourcegraph/customer [#38](https://github.com/sourcegraph/customer/issues/38) 👩
- [x] RFC 113: Implement `PermsFetcher` interface for GitHub authz provider [#8890](https://github.com/sourcegraph/sourcegraph/issues/8890) __1d__ 
- [x] Drop `provider` column from perms table [#8842](https://github.com/sourcegraph/sourcegraph/issues/8842) __0.5d__ 🧶
- [x] RFC 113: Instrumenting `PermsSyncer` [#8612](https://github.com/sourcegraph/sourcegraph/issues/8612) __0.5d__ 🛠️
- [x] Forbidden - CSRF token invalid [#7368](https://github.com/sourcegraph/sourcegraph/issues/7368) __2d__ 🐛
- [ ] ~repo-updater: remove the use of `dbconn.Global` for getting external services~ [#9156](https://github.com/sourcegraph/sourcegraph/issues/9156) __0.5d__ 🧶
- [ ] ~authz: better heuristic of `NextSyncAt` by `PermsSyncer`~ [#9098](https://github.com/sourcegraph/sourcegraph/issues/9098) __1d__ 
- [x] docs: GitHub background permissions syncing [#9692](https://github.com/sourcegraph/sourcegraph/pull/9692) :shipit:

@uwedeportivo

- [x] regression e2e search tests: Problems connecting to searcher [#9323](https://github.com/sourcegraph/sourcegraph/issues/9323) 🐛

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by keegancsmith** [comment]
My work for 3.15 looks good. I'll still be focussed on customer issues. Non-customer related issues all have the theme of finishing up things I started/wanted to do earlier this year:
- External communication settings (TLS certs/noverify/SSH)
- Documentation
- Gitserver debt around sharding/rebalancing

Note: I am over my availability. However, my availability is just a very conservative estimate and I am hoping all the docs tasks can be done in a day. I think the task that will most likely slip is the gitserver debt (maybe should just remove from the plan now?)

**Comment by mrnugget** [comment]
My planned work also looks good. Some of the issues I estimated conservatively, but considering that the next few weeks will be bumpy due to childcare and irregular schedule, I think it can work.

**Comment by tsenart** [comment]
> I think the task that will most likely slip is the gitserver debt (maybe should just remove from the plan now?)

@keegancsmith: +1

**Comment by unknwon** [comment]
My planned items are settled.

**Comment by rvantonder** [comment]
I've set my work items. I'm over considering I should allocate customer-related things that crop up, but there's some flexibility taking 3 to 4 days off by doing tasks in #9171, #9173, #9174 partially. I prefer having a complete picture rather than leave things off to get under the quota.

**Comment by tsenart** [comment]
@ryanslade: Any update?

**Comment by ryanslade** [comment]
> @ryanslade: Any update?

I was waiting for RFC 132 to stabilise. I've pulled issues out of that now and it looks like I'm only about 50% utilised this iteration. I assume there might be customer issues coming through but I'd like to get closer to 75% so any issue suggestions welcome.

**Comment by mrnugget** [comment]
@ryanslade I'm assigned to these, but if you want to take them on, I'd be happy:

- https://github.com/sourcegraph/sourcegraph/issues/8344
- https://github.com/sourcegraph/sourcegraph/issues/8480
- https://github.com/sourcegraph/sourcegraph/issues/9008

They're all pretty self-contained and rather small (except the last one, which doesn't have a proposed solution yet).

**Comment by rvantonder** [comment]
**W09 Summary**

Major work this week was figuring out and implementing a code path to support and/or queries while keeping existing parsing and logic as a fallback. The goal is to eventually migrate the current  query handling and the new code needs to make that possible. That process and other items was also part of my planning this week. 

Other than that,
-  I wrapped up improved index search for @commits at HEAD for 3.14 release, 
- worked on improving a structural search UX issue ("no results" would display along with "show more"), and 
- looked into `repohascommitafter` perf issue.

**W10 Plan**

This week I'll implement the functionality to evaluate and/or queries. I prototyped/hacked on this a couple of weeks ago. As a first implementation, the approach will implement intersection/union operations on top of search queries. After that, I'll focus on bringing and/or query validation in line with our current validation steps (because I'll first add `and/or` query evaluation without doing much validation/user-facing concerns, since the former is more important).

**Comment by mrnugget** [comment]
### Last week

The week wasn't as productive as I would've liked, what with the global pandemic and daycares closed and things like that.

But I still managed to finish planning, clean up a lot of now-unneeded code and started to make progress on https://github.com/sourcegraph/sourcegraph/issues/9106

### This week

I'm really looking foward to finishing https://github.com/sourcegraph/sourcegraph/issues/9106. "Renaming" might sound trivial, but it's removing a huge cognitive load for users and/or developers. Besides that I want to make progress on a lot of the other bug-fix/tune tickets we have for Campaigns.

Regarding productivity: I now have fixed "childcare" time slots, so if everything goes according to plan, I should be more productive the rest of the time.

**Comment by unknwon** [comment]
### W10 Summary

Mainly focused on shipping and e2e testing of background permissions syncing for GitLab and Bitbucket Server.

### W11 Plan [2020-03-23]

- Finish adding metrics and Grafana dashboard panels for background permissions syncing.
- Start cleaning up tech debt created for background permissions syncing.
- Draft delivery plans for background permissions syncing.

**Comment by ryanslade** [comment]
## W10 Summary

Fixed some campaign metadata bugs and improved page load time on the campaign page from around 400ms to 250ms (on my laptop). I think we have more room for improvement so would be nice to take another look at some point.

Otherwise spent a lot of time on [RFC 132](https://docs.google.com/document/d/1iS5cr_vI1wEKbQHLLjLyXLaGdci1bt0VAY2_QzbXj5I/edit#) (still under review)

## W11 Plan

Hopefully finalise RFC 132 and start work on its implementation

**Comment by imtommyroberts** [comment]
If you feel as though some input from UX on any of your planned work would be helpful please let me know! No need for design files etc, we can just set up a call and walk me through what it is that you've worked on, and I can give feedback as needed.

**Comment by unknwon** [comment]
### W11 Summary

- Finished adding Grafana dashboard panels for background permissions syncing and cut 3.14.1 patch release for it.
- Added tests for `PermsSyncer`.
- Started working on list view for user and repo permissions.

### W12 Plan [2020-03-30]

- Finish list view for user and repo permissions.
- Gather metrics for `authzFilter` and send over in pings   
- Implement PermsFetcher interface for GitHub authz provider
- Use golden accounts for VCRs in tests

**Comment by rvantonder** [comment]
**W11 Summary**

Implemented a basic evaluator for and/or search queries. I added a flag that activates the (still in development) code path. Things are on track.

**W12 Plan**

I'll be refining query parsing and parentheses handling for each of literal, regex, and structural search on the new and/or code path (#9170). I'll be working on getting feature parity with existing assumptions on search patterns for each kind of search with the new and/or code path (#9171).

**Comment by mrnugget** [comment]
### Last week

Again, not the most productive week, due to childcare duties, an irregular schedule and multiple interviews and meetings in the time I had left.

I did manage to finish The Big Rename of Campaigns-related entities, write tests, add documentation, start [RFC 135](https://docs.google.com/document/d/1z3kzSFA6OApx_6kvAB7j40I1WxHdf3exD8EtEbfPd7I/edit) with @eseliger.

### This week

Hopefully I'll be able to finish up multiple of the smaller tickets assigned to me and to fix some of [the things that @unknwon ran into when trying Campaigns](https://gist.github.com/unknwon/b7c80d23e6b2a624e50e4073454959e0) since I deem those to be higher priority than a lot of other things I had planned.

I'm also realizing that I was too optimistic when planning this iteration, I probably won't be able to finish all my tickets.

Especially not **since I'll be on vacation next week**.

**Comment by ryanslade** [comment]
## W11 Summary

* Finalising RFC 132, background sync rate limiting
* Implementing BitbucketServer webhook support fr build status. (Plugin and backend work)

## W12 Plan

I'll start working through the tickets to implement RFC 132

**Comment by keegancsmith** [comment]
### Last week

Mixed productivity week due to South Africa going into lockdown. But the time I did have I investigated some low hanging fruit w.r.t. performance on Sourcegraph.com. I added some metrics to validate the work I'll ship this week around fixing it. Additionally I dived very deep into git protocol v2 since it is now the default in git. It was technically very interesting and gratifying. Expect a nice write up (and a perf increase in our use of ls-remote).

Overall I didn't follow the planned work I have, and just let my curiosity drive my work. I highly enjoyed it and will do it again this week (while making time for important planned work).

### This week

I have traded internet for child-care. Internet is too bad for VC (better by Wednesday hopefully), but I have childcare now. So my plan is to dive into performance issues on Sourcegraph.com. I'll also spend a day doing docs (large portion of my planned work).

**Comment by keegancsmith** [comment]
### Last week

Was a productive week. Shipped some performance improvements for the raw endpoint. Details here (with graph) <https://github.com/sourcegraph/sourcegraph/issues/9372#issuecomment-608367909>. Also helped fix a few ops issues we had on Sourcegraph.com: Downtime due to pgsql and disk permissions; lang-go OOMing which is still ongoing.

I forgot to mention this last week, but also cleaned up our observability a bunch in production. Details here <https://sourcegraph.slack.com/archives/C89KCDK5J/p1584690177068800>

### This week

Main goal is to ensure all docs related tasks are done. Other theme will be some src-expose work: adding some tests, fixing a bug for a customer and merging into src-cli. Otherwise I will continue to look into sourcegraph.com since it has been so fruitful for guiding work.

**Comment by unknwon** [comment]
### Last week

- Finished implementing background permissions syncing for GitHub. 
- Submitted a mini proposal to collect authorization duration data (ie. `authzFilter` duration) in ping. 
- Participated in design sync to reach agreement on permissions' UI.

### W13 Plan [2020-04-06]

- Finish e2e testing for background permissions syncing from GitHub/
- Start working on permissions' UI.
- Start adding authorization duration data to ping.
- Kick off the work to use golden accounts for VCRs in tests.
- Add a new `full_synced_at` column to permissions table to indicate when was last user-/repo-centric syncing.
- Spike: Refactor our GitHub client to only associate with one token.

**Comment by rvantonder** [comment]
W12 Summary

- 1.5 day surge to search multiple repos at multiple revisions for a customer request, see https://github.com/sourcegraph/sourcegraph/pull/9425. Happy this worked out in time to hopefully help our sales efforts.
- And/or query search validation and special syntax casing. There's lots of detail here on what this is about in #9170 and #9171. I almost completed all the work here but got diverted with the task above.


W13 Plan

- I'll be wrapping up the work for and/or query handling from last week, and then start testing heavily.
- One thing that came up last week was the potential for and/or queries to return results and orderings unpredictably (because we are merging different searches which may independently time out, etc.). I had a call with Stephen to discuss options around using pagination for this and plan to explore those options.

**Comment by ryanslade** [comment]
## Week 13

Refactored the changeset syncer so that we have one syncer per external service. This took longer than expected because each changeset can belong to multiple external services  so we needed to come up with a way to pick just one service given a changeset. This is all needed for when we add rate limiter config to external services.

## This Week

Add configurable rate limters to Bitbucket Server / Cloud, GitHub and GitLab

**Comment by mrnugget** [comment]
### Last week

Vacation.

### This week

Besides work ingon the tickets that are assigned to me, I want to invest some more time into the Campaign docs, since those are missing some high-level explanations that new users are looking for (and that have become self-evident to us developers). And then we also need to plan the next release.

**Comment by unknwon** [comment]
### Last week

Had a tough week with extremely poor sleep quality and low productivity, mostly reading RFCs and reviewing PRs.

Updated docs and tests for GitHub background permissions syncing, also started a conversation with distribution team about a token access problem, i.e. how to better communicate with customers. Little progress on the permissions UI work, most likely won't be able to catch the branch cut.

### W14 Plan [2020-04-13]

- Recover my productivity to the normal level.
- Write an RFC/work plan for addressing e2e tests that can be covered/converted as backend unit and integration tests.
- Add a new `full_synced_at` column to permissions table to indicate when was last user-/repo-centric syncing.
- Continue adding authorization duration data to ping.
- Continue working on using golden accounts for VCRs in tests.

**Comment by rvantonder** [comment]
**Last week**

Lots of work on getting and/or queries ready to ship, especially around accommodating tricky queries (e.g., containing dangling parens, like `foo( and bar(`) and expression grouping, see #9761, #9762.

**This week**

- Add logic that controls when we perform and/or search
- Add a more robust way to process and queries (intersection)
- Test test test and/or queries a lot.

**Comment by keegancsmith** [comment]
### Last week

Main goal was to do all doc related tasks, and I did! I missed one, but will do that soon (so counting it as a win). The mix of forgetting about Easter Weekend and docs taking most of my time meant I didn't get to merging src-expose into src-cli.

### This week

Plan 3.16. Finish up external communication work. Likely start work on indexing multiple branches again.

**Comment by ryanslade** [comment]
## Last Week

Adding configurable rate limits to a number of sources and integrating them into the changeset syncer. 

## This week

Adding instrumentation to the rate limiter / syncer and integrating the state of the rate limiter into scheduler logic. Currently we keep the existing schedule but wait for rate limit availability rather than using it as an input to the scheduler.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
