### ISSUE TITLE
web: 3.15 tracking issue

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#9159]
## Planned work

@Unassigned

- [ ] web: 3.15 tracking issue [#9159](https://github.com/sourcegraph/sourcegraph/issues/9159) 

@attfarhan: __12.00d__

- [x] Icon toggles have misaligned highlights [#9671](https://github.com/sourcegraph/sourcegraph/issues/9671) __0.5d__ 🐛
- [ ] Interactive search doesn't play well with suggestions [#9378](https://github.com/sourcegraph/sourcegraph/issues/9378) __1d__ 
- [x] Onboarding changes for 3.15 [#9240](https://github.com/sourcegraph/sourcegraph/issues/9240) __2d__ 
- [ ] Better tooltip implementation [#9164](https://github.com/sourcegraph/sourcegraph/issues/9164) __2d__ 🧶
- [x] multiple valid values for discrete filters [#8790](https://github.com/sourcegraph/sourcegraph/issues/8790) __0.5d__ 
- [ ] Improve onboarding experience [#8584](https://github.com/sourcegraph/sourcegraph/issues/8584) 
- [x] Interactive mode filters have trouble with double quotes [#8418](https://github.com/sourcegraph/sourcegraph/issues/8418) __1.5d__ 🐛
- [ ] Explore alternatives to Reactstrap [#6443](https://github.com/sourcegraph/sourcegraph/issues/6443) __3d__ 🧶
- [x] Go-to-definition does not select new file in tree [#4710](https://github.com/sourcegraph/sourcegraph/issues/4710) __1.5d__ 🐛
- [x] Onboarding updates [#9628](https://github.com/sourcegraph/sourcegraph/pull/9628) :shipit:

@eseliger: __6.00d__

- [x] Remove feature flag for campaigns in navbar [#9555](https://github.com/sourcegraph/sourcegraph/issues/9555) __0.5d__ 
- [x] List styling is not consistent across features [#9268](https://github.com/sourcegraph/sourcegraph/issues/9268) __0.5d__ 
- [x] Campaigns splash screen [#9140](https://github.com/sourcegraph/sourcegraph/issues/9140) __1.5d__ 
- [x] Make campaign.description nullable in GQL [#9034](https://github.com/sourcegraph/sourcegraph/issues/9034) __0.5d__ 🧶
- [x] Make it clearer how to go from list of changesets to changeset on codehost [#8149](https://github.com/sourcegraph/sourcegraph/issues/8149) __0.5d__ 
- [x] Sprinkle CLI instructions into the campaigns UI [#8070](https://github.com/sourcegraph/sourcegraph/issues/8070) __1.5d__ 
- [x] a8n: Implement code intelligence for external changesets [#6749](https://github.com/sourcegraph/sourcegraph/issues/6749) __1d__ 
- [ ] ~Bitbucket Server webhooks miss needs work => unapproved~ [#9139](https://github.com/sourcegraph/sourcegraph/issues/9139) __2d__ 🐛
- [ ] ~More thorough E2E tests for campaigns~ [#9138](https://github.com/sourcegraph/sourcegraph/issues/9138) __2d__ 
- [ ] ~Provide an easier way to add changesets to manual campaigns~ [#8766](https://github.com/sourcegraph/sourcegraph/issues/8766) __2d__ 
- [ ] ~Campaign progress is "Creating changes" even when updating a Campaign~ [#8438](https://github.com/sourcegraph/sourcegraph/issues/8438) __0.5d__ 🐛

@felixfbecker: __14.00d__

- [x] Diff header on GitHub is broken in 2 lines [#9675](https://github.com/sourcegraph/sourcegraph/issues/9675) 🐛
- [x] Misaligned breadcrumb text in diff view [#9601](https://github.com/sourcegraph/sourcegraph/issues/9601) __0.5d__ 🐛
  - [x] Fix nav item not being centered [#9741](https://github.com/sourcegraph/sourcegraph/pull/9741) :shipit:🐛
- [x] Focus rings barely visible [#9493](https://github.com/sourcegraph/sourcegraph/issues/9493) __1d__ 🐛
- [x] Improving extensions toolbar on code hosts and Sourcegraph [#9462](https://github.com/sourcegraph/sourcegraph/issues/9462) 
  - [x] Dont break GitHub file toolbar [#9517](https://github.com/sourcegraph/sourcegraph/pull/9517) :shipit:
  - [x] Fix action bar design [#9503](https://github.com/sourcegraph/sourcegraph/pull/9503) :shipit:
- [x] Sourcegraph button on repository page does not retain selected branch [#9414](https://github.com/sourcegraph/sourcegraph/issues/9414) __1d__ 🐛
  - [x] Respect the revision when jumping to Sourcegraph from GitHub [#9520](https://github.com/sourcegraph/sourcegraph/pull/9520) :shipit:🐛
- [ ] Find references button doesn't show if token is hovered before provider is registered [#9350](https://github.com/sourcegraph/sourcegraph/issues/9350) __3d__ 🐛
- [ ] Loader is never shown if hover provider is called before providers are registered [#9349](https://github.com/sourcegraph/sourcegraph/issues/9349) 🐛
- [ ] ☂️ Code intel paper cuts [#9346](https://github.com/sourcegraph/sourcegraph/issues/9346) 
- [x] Add sign in buttons on PR views too [#9276](https://github.com/sourcegraph/sourcegraph/issues/9276) __2d__ 👩
  - [x] Display sign in buttons in code view toolbar [#9275](https://github.com/sourcegraph/sourcegraph/pull/9275) :shipit:👩
- [x] Native integrations: show a UI hint that the user should log in to Sourcegraph [#8758](https://github.com/sourcegraph/sourcegraph/issues/8758) __3d__ 👩
  - [x] Native integrations auth flow [#9112](https://github.com/sourcegraph/sourcegraph/pull/9112) :shipit:
- [x] Browser extension silently breaks instead of saying "repo not on your sourcegraph instance" [#7599](https://github.com/sourcegraph/sourcegraph/issues/7599) __0.5d__ 🐛
  - [x] Fix error handling [#9699](https://github.com/sourcegraph/sourcegraph/pull/9699) :shipit:
- [x] Function of extension-contributed buttons is not clear [#5488](https://github.com/sourcegraph/sourcegraph/issues/5488) 🐛
- [x] Too many Sourcegraph extensions wreck GitHub toolbar UI [#4480](https://github.com/sourcegraph/sourcegraph/issues/4480) __1d__ 🐛
  - [x] Dont break GitHub file toolbar [#9517](https://github.com/sourcegraph/sourcegraph/pull/9517) :shipit:
- [x] Browser extension should gracefully handle auth proxies signing users out after inactivity [#3440](https://github.com/sourcegraph/sourcegraph/issues/3440) __2d__ 🐛
- [x] Browser extension stops working when SAML auth token expires [#545](https://github.com/sourcegraph/sourcegraph/issues/545) 
- [ ] ~Incorrect z-indexes in UI~ [#8380](https://github.com/sourcegraph/sourcegraph/issues/8380) __1d__ 🐛
- [x] Fix url being passed as ariaLabel [#9755](https://github.com/sourcegraph/sourcegraph/pull/9755) :shipit:🐛
- [x] Exclude GitHub tree pages from CSS selector [#9714](https://github.com/sourcegraph/sourcegraph/pull/9714) :shipit:🐛

@lguychard: __3.00d__

- [x] Search pattern is duplicated when using a toggle after switching search modes [#9407](https://github.com/sourcegraph/sourcegraph/issues/9407) __0.5d__ 🐛
- [x] Search bar looses focus after whole page is loaded [#9124](https://github.com/sourcegraph/sourcegraph/issues/9124) 🐛
- [x] Search bar no longer updating to show current repo with smartSearchField turned on [#8839](https://github.com/sourcegraph/sourcegraph/issues/8839) __0.5d__ 🐛
- [x] Suggestion icons hard to see in light theme [#8764](https://github.com/sourcegraph/sourcegraph/issues/8764) __0.5d__ 🐛
- [x] Search bar and directory page have different search bars [#8752](https://github.com/sourcegraph/sourcegraph/issues/8752) __0.5d__ 🐛
- [x] MonacoQueryInput theme is broken on pages that have another Monaco editor [#7697](https://github.com/sourcegraph/sourcegraph/issues/7697) __1d__ 🐛
- [x] Enable Git Extras by Default [#3501](https://github.com/sourcegraph/sourcegraph/issues/3501) 
- [ ] ~Intermediate plain text search bar should use same font as Monaco editor~ [#9499](https://github.com/sourcegraph/sourcegraph/issues/9499) __0.5d__ 
- [ ] ~Search bar steals "Cmd+L" keybinding~ [#9125](https://github.com/sourcegraph/sourcegraph/issues/9125) 🐛
- [ ] ~New search autocomplete yields no results in this particular case~ [#8749](https://github.com/sourcegraph/sourcegraph/issues/8749) 
- [ ] ~Missing space when inserting new filter~ [#8740](https://github.com/sourcegraph/sourcegraph/issues/8740) __0.5d__ 🐛
- [ ] ~Cursor is put at the beginning of search field after submitting (instead of staying at end)~ [#8731](https://github.com/sourcegraph/sourcegraph/issues/8731) __0.5d__ 🐛
- [ ] ~Branch/commit/tag selector dropdown is slow on giant monorepo (100K+ branches)~ [#8594](https://github.com/sourcegraph/sourcegraph/issues/8594) 
- [ ] ~MonacoQueryInput does not shrink when the window is resized.~ [#7692](https://github.com/sourcegraph/sourcegraph/issues/7692) __1d__ 🐛
- [ ] ~Clicking "Show more" at end of a result set does not jump you back to the top of the page~ [#7024](https://github.com/sourcegraph/sourcegraph/issues/7024) 🐛
- [x] Remove scoped search bar from TreePage, scope global query to the current tree or file instead [#9225](https://github.com/sourcegraph/sourcegraph/pull/9225) :shipit:
- [x] Use IntersectionObserver in trackViews() [#5541](https://github.com/sourcegraph/sourcegraph/pull/5541) :shipit:

@mrnugget: __0.50d__

- [x] Updating a closed campaign with N already merged changesets creates N new changesets [#9395](https://github.com/sourcegraph/sourcegraph/issues/9395) __0.5d__ 🐛

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by tsenart** [comment]
@lguychard: I added the necessary tags in the issue body for the automation to work.

**Comment by lguychard** [comment]
## W10 summary

- Helped debug Bitbucket Server native integration for https://app.hubspot.com/contacts/2762526/company/1767812339
- Fixed display of activation dropdown confetti https://github.com/sourcegraph/sourcegraph/pull/9077
- Some backlog triage
- Fixed debouncing of smart search suggestions https://github.com/sourcegraph/sourcegraph/pull/9197
- Fixed some UI glitches in the site admin onboarding widget https://github.com/sourcegraph/sourcegraph/pull/9203
- PRs in progress:
    - Removing scoped search bar from `TreePage` and replacing it with a button https://github.com/sourcegraph/sourcegraph/pull/9225 (or removing it altogether, see https://github.com/sourcegraph/sourcegraph/pull/9225#discussion_r396337563)
    - Removing global `queryUpdates` subject https://github.com/sourcegraph/sourcegraph/pull/9233
    - Unifying Monaco themes https://github.com/sourcegraph/sourcegraph/pull/9237

## W11 Plan

- Finalizing this tracking issue
- Wrap up outstanding smart search bugs.

**Comment by attfarhan** [comment]
## W11 Summary
- Fix quotes not being handled in interactive mode https://github.com/sourcegraph/sourcegraph/pull/9315
- Graded two coding exercises 
- Opened PR to handle other `yes`/`no`/`only` values https://github.com/sourcegraph/sourcegraph/pulls

## W12 Plan
- Grade coding exercise
- Onboarding UI updates https://github.com/sourcegraph/sourcegraph/issues/9240
- Fix file tree not updating on code intel actions https://github.com/sourcegraph/sourcegraph/issues/4710
- Fix interactive mode doesn't handle suggestions properly https://github.com/sourcegraph/sourcegraph/issues/9378

**Comment by lguychard** [comment]
## W11 Summary

- Fix `sourcegraph.configuration` in the extension API https://github.com/sourcegraph/sourcegraph/pull/9311
- In progress:
    - Remove scoped search bar from tree page, scope global query to the current tree/file instead https://github.com/sourcegraph/sourcegraph/pull/9225
    - Smart search: place cursor at the end of the field https://github.com/sourcegraph/sourcegraph/pull/9388
    - Smart search: fix suggestions in light theme https://github.com/sourcegraph/sourcegraph/pull/9389

## W12 plan

- I'd like to start thinking about what a project around extensions improvements would look like. Regrouping relevant issues & writing down thoughts in a doc / RFC.

**Comment by felixfbecker** [comment]
### W11 Summary
- Interviews
- Improved e2e docs and fix e2e bugs
- Display sign in buttons in toolbar https://github.com/sourcegraph/sourcegraph/pull/9275
- Debt: Convert components to hooks
- Improve browser extension options menu https://github.com/sourcegraph/sourcegraph/pull/9281
- Fix flaky e2e test https://github.com/sourcegraph/sourcegraph/pull/9232
- Fix user-reported bug https://github.com/sourcegraph/sourcegraph/pull/9313

### W12 Summary
- Plan https://github.com/sourcegraph/sourcegraph/issues/4480 with Tommy
- Interviews
- TBD

**Comment by eseliger** [comment]
### W11 summary
- Interviews and code screens
- Started on [RFC 135](https://docs.google.com/document/d/1z3kzSFA6OApx_6kvAB7j40I1WxHdf3exD8EtEbfPd7I/edit)
- Lot's of debt work on campaigns and small bug fixes after the big rename
	- https://github.com/sourcegraph/sourcegraph/pull/9238
	- https://github.com/sourcegraph/sourcegraph/pull/9291
	- https://github.com/sourcegraph/sourcegraph/pull/9296
	- https://github.com/sourcegraph/sourcegraph/pull/9320
	- https://github.com/sourcegraph/sourcegraph/pull/9209

### W12 plan
- Work on [RFC 135](https://docs.google.com/document/d/1z3kzSFA6OApx_6kvAB7j40I1WxHdf3exD8EtEbfPd7I/edit)
- Campaigns splash screens
- Squeeze in more campaign enhancements if time allows
- One interview so far

**Comment by lguychard** [comment]
## W12 Summary

- Merged some fixes on the smart search field: https://github.com/sourcegraph/sourcegraph/pull/9408, https://github.com/sourcegraph/sourcegraph/pull/9389
- Did some cleanup in the webapp search code: https://github.com/sourcegraph/sourcegraph/pull/9409, https://github.com/sourcegraph/sourcegraph/pull/9412
- Tweaked our job requirements and interview documentation: https://github.com/sourcegraph/careers/pull/82, https://github.com/sourcegraph/careers/pull/83
- Enabled git-extras by default https://github.com/sourcegraph/sourcegraph/pull/9540
- Tweaked hover tooltip loading time as discussed in the previous web sync: https://github.com/sourcegraph/codeintellify/pull/244
- Prototyped UI integration tests following RFC 137: https://github.com/sourcegraph/sourcegraph/pull/9591

## W13 Plan

Q2 Planning

**Comment by eseliger** [comment]
## W12 Summary

- Some improvements and fixes to the E2E pipeline
- Worked on details for RFC135
- Planning for campaign beta pages and delivery plan
- Found some low hanging fruit on our page response times
- Interviews and discussed enhancements to our process

## W13 Plan

- Campaigns open beta preparation work
- Interviews

**Comment by attfarhan** [comment]
## W12 summary
- Graded 3 coding screens
- 1 coding screen follow-up call
- Worked on onboarding changes (https://github.com/sourcegraph/sourcegraph/issues/8584)
- Looked into Reach UI, and beginning to introduce it through the onboarding changes (https://github.com/sourcegraph/sourcegraph/issues/6443)

## W13 Plan
- Wrap up onboarding changes (just need to make tests pass by mocking a Reach UI component)
- Replace remaining Reactstrap components with Reach UI
- https://github.com/sourcegraph/sourcegraph/issues/4710
- stretch: Begin writing RFC for making search bar in interactive mode only take in the search pattern for 3.16

**Comment by eseliger** [comment]
## W13 summary
- 2 Interviews, 2 code screens
- Fixed a customer issue #9656 
- Worked on campaigns splash screens
- Some debt work reducing code smells #9696 

## W14 Plan
- Wrap up campaigns work for 3.16

**Comment by lguychard** [comment]
## W13 Summary

- I ended up spending my time last week between customer inquiries / bugs, the hiring pipeline, and being sick, and was not able to move forward on iteration work 😞

## W14 Plan

- Make progress on my outstanding work for 3.15, triage what will not make the branch cut.
- Q2 planning.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
### W14 Recap
- Fix code intel paper cut issues (#9914, https://github.com/sourcegraph/codeintellify/pull/251)
- Fix "Function of extension-contributed buttons is not clear" (details in https://github.com/sourcegraph/sourcegraph/issues/5488#issuecomment-613288907)
- Add tooling for tracking npm third party licenses (#9823)
- Small fix: #9800
- ESLint and build tooling upgrades in external repos
- Some CI fixes
- Planning of [RFC 144: Code Insights](https://docs.google.com/document/d/1EHzor6I1GhVVIpl70mH-c10b1tNEl_p1xRMJ9qHQfoc/edit)

**Comment by lguychard** [comment]
@felixfbecker can you repost your update in #9915?

See https://sourcegraph.slack.com/archives/CMT39K56Z/p1587366606183100?thread_ts=1587366046.182900&cid=CMT39K56Z

Thanks 🙂

**Comment by felixfbecker** [comment]
But last week was still 3.15 work? I was planning to post my W15 plan on #9915. Am I thinking about this wrong?
