### ISSUE TITLE
3.14.1 patch release

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#9304]
# 3.14.1 Patch Release

**Attention developers:** Add pending changes to this checklist, cherry-pick the relevant commits onto branch `3.14`. **Only check off items if the relevant PR/commits have been cherry-picked into the branch**:

- [x] 6092587fdb2893a9cbeba112b3af5b496273a450 authz: expose metrics for `PermsSyncer` (#9109)
- [x] 5e74f9e2024d70b16913098782a37eb0a3a6cde5 update-check: k8s advertise 3.13.2-1 release (#9182)
- [x] 1f21a2b10f57806b1c6d464c1bcb308eeb05973f authz: expose metrics of `authzFilter` duration (#9264)
- [x] d35b638a7fd411e1e8e17dfd80f7194137e6d76b search: succinct TextPatternInfo for searchFilesInRepos traces (#9151)
- [x] 65b9c8c13d166679dc0bf36ea294dbe6cbe89b63 trace: several tracing improvements (#9153)
- [x] 774cda7d9692673cc3b4d5ab4af8a397e2fdba7e trace: remove ancestors from family name (#9195)
- [x] e6daf55a7b5eb064dbf6c57a3a9385470fcf8da3 frontend: use endpoint port if prometheus.io/port annotation is missing (#9216)

## Release sourcegraph/server

- [x] Push the branch `3.14` with your cherry-picked commit(s) and make sure CI passes.
- [x] Push a release candidate tag:
    ```
    git checkout '3.14'
    git tag -a 'v3.14.1-rc.1' -m 'v3.14.1-rc.1' && git push origin 'v3.14.1-rc.1'
    ```
- [x] If CI passes, push the release tag:
    ```
    git checkout '3.14'
    git tag -a 'v3.14.1' -m 'v3.14.1' && git push origin 'v3.14.1'
    ```
- [x] Wait for the final Docker images to be available at https://hub.docker.com/r/sourcegraph/server/tags.

## Release Kubernetes deployment

In [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph):

- [x] Wait for Renovate to open a PR to update the image tags and merge that PR ([example](https://github.com/sourcegraph/deploy-sourcegraph/pull/199)).
- [x] Cherry-pick the image tag update commits from `master` onto `3.14` branch. Then push the release tag:
    ```
    git checkout 3.14
    git pull
    git cherry-pick <commit0> <commit1> ... # all relevant commits from the master branch
    git push 3.14
    git tag v3.14.1
    git push origin v3.14.1
    ```

## Update the docs

- [x] Open and merge PRs that publish the release (the PRs created by this command must be merged manually):
  ```
  yarn run release release:publish 3.14.1
  ```
- [x] Create a new section for the patch version in the changelog. Verify that all changes that have been cherry picked onto the release branch have been moved to this section of the [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/master/CHANGELOG.md) on `master`.
- [x] Post a reply in the #dev-announce thread to say that the release is complete.
