### ISSUE TITLE
Go language support via extension

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#958]
Sourcegraph's support for Go hovers, go-to-definition, find-references, and find-implementations is built on [sourcegraph/go-langserver](https://github.com/sourcegraph/go-langserver). This has worked well so far to provide those features, but we want to be able to provide code intelligence features and configuration on par with editors, such as more Go guru features, a smoother configuration experience, and other helpful context. To do this, we are moving all language support (including Go) to being built as [Sourcegraph extensions](https://docs.sourcegraph.com/extensions). The initial milestone is to get the current feature set ported to an extension.

## Goals

- Remove Go buildserver dependency on gitserver
- Go langserver that we will be running on sourcegraph.com through extension is built from public go-langserver repo
-  lsp-proxy is not necessary for code intelligence => websockets are used to communicate from extension to langserver
- No Go langserver specific code in sourcegraph/sourcegraph
- No Sourcegraph specific code in Go language server
- Maintain cross repository code intelligence
- Indexer is not necessary for this
- 3.0-preview only support dependencies that are public on GitHub

## Milestones

- [x] Add WebSockets support to go-langserver https://github.com/sourcegraph/go-langserver/pull/339 
- [x] Remove old xfiles/xcontent VFS implementation https://github.com/sourcegraph/sourcegraph/pull/941
- [x] Add support for fetching from a token-authed zip URL specified in `rootUri` for the current repo files (still fall back to gitserver for `git://` URIs) https://github.com/sourcegraph/sourcegraph/pull/987
- [x] Remove usage of xcache and replace with in-memory or on-disk http cache https://github.com/sourcegraph/sourcegraph/pull/989
- [x] Deploy and enable new extension https://sourcegraph.com/extensions/chris/lang-go to Sourcegraph.com, disable langserver/go. Keep the old langserver-http code path.
- [x] Bump version of go-langserver in sourcegraph/sourcegraph and update the buildserver code to reduce conflicts when migrating later https://github.com/sourcegraph/sourcegraph/pull/1028
- [x] Add TLS support to xlang-go https://github.com/sourcegraph/sourcegraph/pull/1041 (and later go-langserver https://github.com/sourcegraph/go-langserver/pull/349)
- [x] Deploy new `xlang-go-websockets` and add a DNS record for `go.sourcegraph.com -> <IP of load balancer for xlang-go-websockets>`. You can try out WebSockets by setting `"lang-go.address": "wss://go.sourcegraph.com"`. https://github.com/sourcegraph/infrastructure/pull/693
- [x] Switch to the new code path by adding `lang-go.address` to global settings. At this point, the LSP gateway will only be used for cross-repo refs.
- [x] Implement cross-repo references in lang-go using search+xreferences (as specced out in the gdoc). Add another references provider that does xrefs, wait for @sqs to come up with a way to explicitly register an external references provider. This means all code intel is provided by lang-go.
- [x] Put all lsp/lspext types in go-lsp https://github.com/sourcegraph/sourcegraph/pull/1058 and https://github.com/sourcegraph/go-lsp/pull/1
- [x] Deploy a gddo proxy to get around CORS https://github.com/sourcegraph/infrastructure/pull/698
- [x] Drop lsp-proxy from xlang-go tests, migrate to go-langserver https://github.com/sourcegraph/sourcegraph/pull/1060
- [x] Reimplement `/go/` links https://github.com/sourcegraph/sourcegraph/pull/1197
- [x] Move the buildserver code to go-langserver https://github.com/sourcegraph/go-langserver/pull/345
- [x] Reimplement the shield and badge endpoints https://github.com/sourcegraph/sourcegraph/pull/1377
- [x] Support private deps https://github.com/sourcegraph/go-langserver/pull/348
- [x] Set up deployments from go-langserver to Sourcegraph.com. At this point, xlang-go is no longer used on Sourcegraph.com https://github.com/sourcegraph/go-langserver/pull/351
- [x] Document how to deploy (see [lang-typescript](https://github.com/sourcegraph/lang-typescript)) and the settings for the lang-go extension in the README then close https://github.com/sourcegraph/sourcegraph/issues/886
- [x] (for 3.0) Add env vars for `noGoGetDomains` and `blacklist` https://github.com/sourcegraph/sourcegraph/issues/1276
- [x] Stream external references WIP branch [stream-external-refs](https://github.com/sourcegraph/sourcegraph/tree/stream-external-refs)
- ~~Do not evict the zip on close (see [the discussion](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/vfsutil/zip.go#L71-72&tab=discussions&threadID=135&commentID=171))~~ It doesn't seem to get evicted even when `evictOnClose: true`

## E2E test checklist

- [Vanity import paths](https://docs.sourcegraph.com/extensions/language_servers/go#vanity-import-paths) TODO construct a test repo for this
- Public code https://sourcegraph.com/github.com/gorilla/mux/-/blob/mux.go
- Private code TODO construct a test repo for this
- Public code with private dependencies TODO construct a test repo for this
- Custom repo name `"repos.list": { "url": "https://github.com/gorilla/csrf.git", "path": "customreponame" }`
- https://github.com/sourcegraph/sourcegraph/issues/139
- https://github.com/sourcegraph/sourcegraph/issues/129
- https://github.com/sourcegraph/sourcegraph/issues/145

**Comment by chrismwendt** [comment]
The raw API is not exposed internally on `/.internal/...`, and exposing it would take more effort than implementing token auth, so I'm planning to do token auth before moving code to go-langserver. (updated description).

**Comment by chrismwendt** [comment]
I abandoned https://github.com/sourcegraph/sourcegraph/pull/943 which was intended to construct the zip URL inside of the Go buildserver in favor of https://github.com/sourcegraph/sourcegraph/pull/987 which adds a `zipURL` field to `initializationOptions` and makes xlang-go fetch from there if present.

I also added token generation and `zipURL` construction to lang-go in https://github.com/sourcegraph/lang-go/commit/280de6bce76b62f52d92821cdad44f6e75122933

lang-go uses langserver-http as a dependency to make requests to the LSP gateway (A.K.A. LSP Proxy HTTP API), and in order to pipe the `zipURL` through, I had to parameterize langserver-http in https://github.com/sourcegraph/sourcegraph-langserver-http/pull/10 More info in the README https://github.com/sourcegraph/lang-go

**Comment by chrismwendt** [comment]
Replacing xcache with an in-memory HTTP cache in xlang-go in https://github.com/sourcegraph/sourcegraph/pull/989

**Comment by chrismwendt** [comment]
For our org on Sourcegraph.com I've disabled the synthesized `langserver/go` extension and enabled `chris/lang-go`.

**Comment by chrismwendt** [comment]
I enabled `chris/lang-go` on prod for all users. Zips are being fetched from the raw API:

https://prometheus.sgdev.org/graph?g0.range_input=1h&g0.expr=xlang_vfs_zip_fetch_total&g0.tab=0&g1.range_input=1h&g1.expr=xlang_vfs_zip_fetch_failed_total&g1.tab=0

![image](https://user-images.githubusercontent.com/1387653/48589232-920db600-e8ef-11e8-899a-8658485c9efe.png)

**Comment by chrismwendt** [comment]
Cross repo refs work on private instances using search. It doesn't work on Sourcegraph.com because there are too many repos. I tried the godoc.org importers API, but it doesn't allow CORS.

I added more docs (usage+docker+k8s+settings) to https://github.com/sourcegraph/lang-go

Operationally speaking, the Go buildserver no longer depends on lsp-proxy :sparkles:, but there are some code dependencies in tests that I'll remove. I plan to move the buildserver code over to go-langserver tomorrow.

**Comment by sqs** [comment]
@chrismwendt When do you think you'll be ready to switch over to the Go extension on Sourcegraph.com for all users (including providing cross-repo refs via the Go extension)? Need help testing?

**Comment by chrismwendt** [comment]
@sqs Probably tomorrow (Thursday). All code intel except for cross-repo refs currently goes through the new `lang-go` extension (see [global-settings](https://sourcegraph.com/site-admin/global-settings)):

![image](https://user-images.githubusercontent.com/1387653/49177038-0ccbcd80-f301-11e8-8937-a4e482a509cc.png)

I remember there was still some UI work to be done for external refs, but I could implement streaming external refs now in the plain refs sidebar (building off of https://github.com/sourcegraph/sourcegraph/pull/1061).

**Comment by chrismwendt** [comment]
Done! New docs and extension homepage: https://github.com/sourcegraph/lang-go
