### ISSUE TITLE
Python language support via extension

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#959]
Sourcegraph currently supports for Python hovers, go-to-definition, find-references, and find-implementations using [sourcegraph/python-langserver](https://github.com/sourcegraph/python-langserver). This has worked so far to provide those features, but we want to be able to provide code intelligence features and configuration on par with editors, such as better dependency support and a smoother configuration experience. To do this, we are moving all language support (including Python) to being built as [Sourcegraph extensions](https://docs.sourcegraph.com/extensions). The initial milestone is to get the current feature set ported to an extension (minus dependency installation + cross-repository definitions/references). This is part of the larger initiative of improving language support in 2019: https://github.com/sourcegraph/sourcegraph/issues/1551

Demo video: https://drive.google.com/open?id=1ZU5LKNGeFYkPmeuG1yFMloB65dEfuMzz

- Language server: https://github.com/Microsoft/python-language-server
- WIP fork: https://github.com/sourcegraph/python-language-server/tree/wip2
- WIP extension
  - Extension https://sourcegraph.com/extensions/sourcegraph/python
  - Repository https://github.com/sourcegraph/sourcegraph-python

For switching to the Python extension on Sourcegraph.com:

- [ ] Ensure that it is cleaning up temp dirs https://sourcegraph.slack.com/archives/C07KZF47K/p1546987357093200?thread_ts=1546986638.092300&cid=C07KZF47K

For 3.0:

- [x] Make a [test plan](https://github.com/sourcegraph/sourcegraph/issues/1719)
- [x] Add WebSocket support https://github.com/Microsoft/python-language-server/commit/79faae45a77e702d46af8068ff2724a39a8c28f1
- [x] Add zip archive fetching support https://github.com/Microsoft/python-language-server/commit/79faae45a77e702d46af8068ff2724a39a8c28f1
- [x] Add support for private Sourcegraph instances (using an access token)
- [ ] Add deploy config (with TLS via ingress) to our infrastructure repo (waiting for https://github.com/sourcegraph/sourcegraph/issues/1682)
- [x] Add deployment instructions
- [x] Document build steps

[Scoped for 3.1](https://github.com/sourcegraph/sourcegraph/issues/1401) (not in scope for 3.0)
- Dependency fetching
- Cross repository code intel
- Upstream the changes to https://github.com/Microsoft/python-language-server

**Comment by sqs** [comment]
@chrismwendt is taking this over

**Comment by nicksnyder** [comment]
If this is release blocking for 3.0, please add the release blocking label (I think it does?).

Otherwise, if this isn't going to get done in the next week, please remove it from the 3.0 milestone.

**Comment by nicksnyder** [comment]
File separate issue for "Ensure that it is cleaning up temp dirs" which can be for 3.1 and then close this as everything else is done or otherwise tracking in a separate issue
