### ISSUE TITLE
distribution: 3.15 tracking issue

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#9605]
## Work

@Unassigned

- [ ] distribution: 3.15 tracking issue [#9605](https://github.com/sourcegraph/sourcegraph/issues/9605) 

@beyang: __3.00d__

- [x] Install Jaeger by default in all Sourcegraph deployment options [#9300](https://github.com/sourcegraph/sourcegraph/issues/9300) __3d__ 

@efritz

- [x] Federate precise-code-intel-worker metrics in pure docker environments [#9552](https://github.com/sourcegraph/sourcegraph/pull/9552) :shipit:

@ggilmore

- [x] Merge deploy-sourcegraph latest into k8s.sgdev.org [#9759](https://github.com/sourcegraph/sourcegraph/issues/9759) 
- [ ] Set ephemeral storage resource requests and limits in deploy-sourcegraph [#9604](https://github.com/sourcegraph/sourcegraph/issues/9604) 
- [ ] Write sourcegraph/server -> docker compose migration guide [#9602](https://github.com/sourcegraph/sourcegraph/issues/9602) 
- [x] k8s: upgrade deprecated apis [#9148](https://github.com/sourcegraph/sourcegraph/issues/9148) 
- [x] ci: add enable-profiling/ branch prefix [#9186](https://github.com/sourcegraph/sourcegraph/pull/9186) :shipit:

@slimsag

- [x] reduce src_graphql_field_seconds cardinality [#9895](https://github.com/sourcegraph/sourcegraph/issues/9895) 🐛
  - [x] monitoring: reduce src_graphql_field_seconds cardinality substantially [#9898](https://github.com/sourcegraph/sourcegraph/pull/9898) :shipit:
- [x] search alerting threshold should be lowered [#9894](https://github.com/sourcegraph/sourcegraph/issues/9894) 
  - [x] observability: relax search latency alerts to match real world [#9901](https://github.com/sourcegraph/sourcegraph/pull/9901) :shipit:
- [x] multiple gitserver alerts need DataMayNotExist=true [#9856](https://github.com/sourcegraph/sourcegraph/issues/9856) 🐛
  - [x] observability: minor improvements + upgrade git (fixes CI) [#9871](https://github.com/sourcegraph/sourcegraph/pull/9871) :shipit:
- [ ] merge and test deploy-sourcegraph-docker#93 [#9839](https://github.com/sourcegraph/sourcegraph/issues/9839) 
- [x] observability: NaN values can leak into alert_count metric [#9832](https://github.com/sourcegraph/sourcegraph/issues/9832) 🐛
  - [x] observability: improved NaN handling [#9835](https://github.com/sourcegraph/sourcegraph/pull/9835) :shipit:
- [x] Remove line color dividing warning/critical threshold [#9830](https://github.com/sourcegraph/sourcegraph/issues/9830) 
  - [x] observability: remove line color dividing warning/critical thresholds [#9831](https://github.com/sourcegraph/sourcegraph/pull/9831) :shipit:
- [x] observability: frontend dashboard: P90/P99 search latency should clarify it covers successful searches only [#9819](https://github.com/sourcegraph/sourcegraph/issues/9819) 🐛
  - [x] observability: minor improvements + upgrade git (fixes CI) [#9871](https://github.com/sourcegraph/sourcegraph/pull/9871) :shipit:
- [x] "resolve_revision_duration_slow" flaky; threshold too aggressive [#9751](https://github.com/sourcegraph/sourcegraph/issues/9751) 🐛
  - [x] observability: convert Zoekt Index Server dashboard into generated form [#9758](https://github.com/sourcegraph/sourcegraph/pull/9758) :shipit:
- [x] Symbols -> frontend-internal connection should be monitored [#9732](https://github.com/sourcegraph/sourcegraph/issues/9732) 🐛
  - [x] observability: convert Symbols dashboard into generated form [#9733](https://github.com/sourcegraph/sourcegraph/pull/9733) :shipit:
- [x] Symbols dashboard "Store fetch queue size" appears to be able to go negative [#9731](https://github.com/sourcegraph/sourcegraph/issues/9731) 🐛
  - [x] observability: convert Symbols dashboard into generated form [#9733](https://github.com/sourcegraph/sourcegraph/pull/9733) :shipit:
- [x] Symbols dashboard cardinality too high to be useful [#9730](https://github.com/sourcegraph/sourcegraph/issues/9730) 🐛
  - [x] observability: convert Symbols dashboard into generated form [#9733](https://github.com/sourcegraph/sourcegraph/pull/9733) :shipit:
- [x] "Search errors on unindexed repositories" cardinality is too high to be useful [#9670](https://github.com/sourcegraph/sourcegraph/issues/9670) 🐛
  - [x] observability: convert Searcher dashboard to generated [#9672](https://github.com/sourcegraph/sourcegraph/pull/9672) :shipit:
- [x] "Non-200 frontend responses over 5m" should have less cardinality [#9668](https://github.com/sourcegraph/sourcegraph/issues/9668) 🐛
  - [x] observability: convert Query Runner dashboard to generated [#9669](https://github.com/sourcegraph/sourcegraph/pull/9669) :shipit:
- [x] Frontend dashboard "Hard search errors" should be uncompacted [#9660](https://github.com/sourcegraph/sourcegraph/issues/9660) 🐛
  - [x] observability: convert frontend dashboard to generated [#9661](https://github.com/sourcegraph/sourcegraph/pull/9661) :shipit:
- [x] Syntect server dashboard should be uncompacted [#9525](https://github.com/sourcegraph/sourcegraph/issues/9525) 🐛
  - [x] generate Grafana dashboards and Prometheus alert rules from single source of truth [#9529](https://github.com/sourcegraph/sourcegraph/pull/9529) :shipit:
- [x] syntect-server dashboard "Worker timeouts" should not show one value per frontend instance [#9524](https://github.com/sourcegraph/sourcegraph/issues/9524) 🐛
  - [x] generate Grafana dashboards and Prometheus alert rules from single source of truth [#9529](https://github.com/sourcegraph/sourcegraph/pull/9529) :shipit:
- [x] syntect-server dashboard "Worker timeouts" can appear to go negative [#9523](https://github.com/sourcegraph/sourcegraph/issues/9523) 🐛
  - [x] generate Grafana dashboards and Prometheus alert rules from single source of truth [#9529](https://github.com/sourcegraph/sourcegraph/pull/9529) :shipit:
- [x] sourcegraph.com searcher errors regularly high, does it include context timeouts? [#9360](https://github.com/sourcegraph/sourcegraph/issues/9360) 🐛
  - [x] observability: convert Searcher dashboard to generated [#9672](https://github.com/sourcegraph/sourcegraph/pull/9672) :shipit:
- [x] saved searches should be excluded from search panels/alerts where possible [#9358](https://github.com/sourcegraph/sourcegraph/issues/9358) 🐛
  - [x] monitoring: distinguish between browser and API requests [#9892](https://github.com/sourcegraph/sourcegraph/pull/9892) :shipit:
- [x] frontend dashboard: "hard errors" can show as two entries due to multiple frontend instances [#9356](https://github.com/sourcegraph/sourcegraph/issues/9356) 🐛
  - [x] observability: convert frontend dashboard to generated [#9661](https://github.com/sourcegraph/sourcegraph/pull/9661) :shipit:
- [x] gitserver dashboard missing panel to show # concurrent execs [#9354](https://github.com/sourcegraph/sourcegraph/issues/9354) 🐛
  - [x] observability: convert Git Server dashboard into generated form [#9781](https://github.com/sourcegraph/sourcegraph/pull/9781) :shipit:
- [x] when alerts are firing, they are over-counted due to # of instances [#9353](https://github.com/sourcegraph/sourcegraph/issues/9353) 🐛
  - [x] observability: do not over-count firing alerts due to number of service replicas [#9826](https://github.com/sourcegraph/sourcegraph/pull/9826) :shipit:
- [x] gitserver dashboard should show total available disk space and percentages [#9352](https://github.com/sourcegraph/sourcegraph/issues/9352) 🐛
  - [x] observability: convert Git Server dashboard into generated form [#9781](https://github.com/sourcegraph/sourcegraph/pull/9781) :shipit:
- [x] gitserver critical disk space alert should be 15% [#9351](https://github.com/sourcegraph/sourcegraph/issues/9351) 🐛
  - [x] observability: convert Git Server dashboard into generated form [#9781](https://github.com/sourcegraph/sourcegraph/pull/9781) :shipit:
- [x] RFC 128: Implement consistent Docker image versioning [#9251](https://github.com/sourcegraph/sourcegraph/issues/9251) 
  - [x] docker-images: republish docker images using Sourcegraph versioning and canonical names [#9847](https://github.com/sourcegraph/sourcegraph/pull/9847) :shipit:
- [x] Improved search monitoring and alerting [#8580](https://github.com/sourcegraph/sourcegraph/issues/8580) 
- [x] Missing prometheus metrics [#6428](https://github.com/sourcegraph/sourcegraph/issues/6428) 
- [ ] ~observability: frontend dashboard: generic GraphQL monitoring~ [#9797](https://github.com/sourcegraph/sourcegraph/issues/9797) 
- [ ] ~observability: searcher: add alerting for archive cache~ [#9796](https://github.com/sourcegraph/sourcegraph/issues/9796) 
- [ ] ~monitoring for container restarts~ [#9793](https://github.com/sourcegraph/sourcegraph/issues/9793) 
- [ ] ~monitoring for containers being down~ [#9792](https://github.com/sourcegraph/sourcegraph/issues/9792) 
- [ ] ~monitoring for CPU and memory usage~ [#9791](https://github.com/sourcegraph/sourcegraph/issues/9791) 
- [ ] ~Alert when search indexing is failing~ [#9783](https://github.com/sourcegraph/sourcegraph/issues/9783) 
- [ ] ~Alert when repository updates are failing~ [#9782](https://github.com/sourcegraph/sourcegraph/issues/9782) 
- [ ] ~observability: canonical wording breakdown~ [#9773](https://github.com/sourcegraph/sourcegraph/issues/9773) 
- [ ] ~Frontend dashboard: "non-200 indexed search responses every 5m" should be by (category,code)~ [#9744](https://github.com/sourcegraph/sourcegraph/issues/9744) 🐛
- [ ] ~syntax highlighting sometimes doesn't work, refreshing causes it to~ [#9557](https://github.com/sourcegraph/sourcegraph/issues/9557) 🐛
- [ ] ~RFC 128: Investigate and propose a solution for how the Slack /release command could be implemented behind the scenes~ [#9252](https://github.com/sourcegraph/sourcegraph/issues/9252) 
- [ ] ~Determine missing alerts between alertmanager and grafana~ [#7528](https://github.com/sourcegraph/sourcegraph/issues/7528) 
- [ ] ~Setup new Grafana alerting on k8s.sgdev.org and sourcegraph.com to go to Slack~ [#7527](https://github.com/sourcegraph/sourcegraph/issues/7527) 
- [ ] ~Identify further inter-service communication metrics missing from new Grafana dashboards + alerts~ [#7525](https://github.com/sourcegraph/sourcegraph/issues/7525) 
- [ ] ~Identify further service-specific metrics missing from new Grafana dashboards + alerts~ [#7524](https://github.com/sourcegraph/sourcegraph/issues/7524) 
- [ ] ~metrics/alerts for gitserver slow execs and fetches/clones~ [#6675](https://github.com/sourcegraph/sourcegraph/issues/6675) 
- [x] observability: add container monitoring in docker-compose / pure docker deployments [#9869](https://github.com/sourcegraph/sourcegraph/pull/9869) :shipit:
- [x] docker-images: fix build script permissions [#9850](https://github.com/sourcegraph/sourcegraph/pull/9850) :shipit:
- [x] enterprise/dev/ci: build republished images [#9848](https://github.com/sourcegraph/sourcegraph/pull/9848) :shipit:
- [x] docker-images: cleanup folder structure, use build scripts when appropriate [#9845](https://github.com/sourcegraph/sourcegraph/pull/9845) :shipit:
- [x] build Grafana and Prometheus images on CI [#9843](https://github.com/sourcegraph/sourcegraph/pull/9843) :shipit:
- [x] observability: do not average histogram quantiles [#9840](https://github.com/sourcegraph/sourcegraph/pull/9840) :shipit:
- [x] observability: use more color-blind friendly threshold colors [#9821](https://github.com/sourcegraph/sourcegraph/pull/9821) :shipit:
- [x] docker-images: fix building and publish new versions of grafana,prometheus [#9801](https://github.com/sourcegraph/sourcegraph/pull/9801) :shipit:
- [x] observability: add support for alerting on values that are LessOrEqual [#9780](https://github.com/sourcegraph/sourcegraph/pull/9780) :shipit:
- [x] observability: searcher: correct query for "unindexed search request errors" [#9772](https://github.com/sourcegraph/sourcegraph/pull/9772) :shipit:
- [x] observability: add better validation of wording [#9771](https://github.com/sourcegraph/sourcegraph/pull/9771) :shipit:
- [x] observability: convert Zoekt Web Server dashboard into generated form [#9770](https://github.com/sourcegraph/sourcegraph/pull/9770) :shipit:
- [x] observability: do not cut off panels at the bottom of home dashboard [#9769](https://github.com/sourcegraph/sourcegraph/pull/9769) :shipit:
- [x] observability: correctly sort firing alerts to the tops of dashboards [#9767](https://github.com/sourcegraph/sourcegraph/pull/9767) :shipit:
- [x] observability: do not mark dashboards as non-editable [#9765](https://github.com/sourcegraph/sourcegraph/pull/9765) :shipit:
- [x] observability: convert Replacer dashboard into generated form [#9749](https://github.com/sourcegraph/sourcegraph/pull/9749) :shipit:
- [x] Distribution tracking issue syncer: include PRs [#9710](https://github.com/sourcegraph/sourcegraph/pull/9710) :shipit:
- [x] observability: convert LSIF Server dashboard into generated form [#9682](https://github.com/sourcegraph/sourcegraph/pull/9682) :shipit:
- [x] observability: convert Repo Updater dashboard to generated [#9667](https://github.com/sourcegraph/sourcegraph/pull/9667) :shipit:
- [ ] ~observability: convert GitHub Proxy dashboard to generated~ [#9666](https://github.com/sourcegraph/sourcegraph/pull/9666) :shipit:
- [x] observability: more clear grouping support [#9642](https://github.com/sourcegraph/sourcegraph/pull/9642) :shipit:
- [x] fix regression in GraphQL field monitoring [#9619](https://github.com/sourcegraph/sourcegraph/pull/9619) :shipit:
- [x] metrics FAQ cleanups [#9618](https://github.com/sourcegraph/sourcegraph/pull/9618) :shipit:
- [x] doc/admin/observability/metrics: add FAQ entries [#9617](https://github.com/sourcegraph/sourcegraph/pull/9617) :shipit:
- [x] observability: add support for specifying unit type of graphs [#9539](https://github.com/sourcegraph/sourcegraph/pull/9539) :shipit:
- [x] observability: remove default values [#9537](https://github.com/sourcegraph/sourcegraph/pull/9537) :shipit:

@uwedeportivo

- [x] jaeger images must be versioned alongside sourcegraph [#9893](https://github.com/sourcegraph/sourcegraph/issues/9893) 
- [ ] Move e2e tests into regression test suite [#9814](https://github.com/sourcegraph/sourcegraph/issues/9814) 
- [ ] Update docs for how to upgrade sourcegraph.com [#9607](https://github.com/sourcegraph/sourcegraph/issues/9607) 
- [x] Enforce pod security policies [#9603](https://github.com/sourcegraph/sourcegraph/issues/9603) 
- [x] regression e2e search tests: Problems connecting to searcher [#9323](https://github.com/sourcegraph/sourcegraph/issues/9323) 🐛
- [ ] 3.15 release tracking issue [#9214](https://github.com/sourcegraph/sourcegraph/issues/9214) 
- [x] grafana admin: editing data source field did not have any effect [#8531](https://github.com/sourcegraph/sourcegraph/issues/8531) 🐛
- [ ] Placeholder: Continuous release process [#7950](https://github.com/sourcegraph/sourcegraph/issues/7950) 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
