### ISSUE TITLE
Search GitHub issues

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#962]
[Draft blog post](https://github.com/sourcegraph/about/pull/53)

Status: 
- I expect [#1275](https://github.com/sourcegraph/sourcegraph/pull/1275) to be merged by EOW, which solves checkboxes 6 + 7.
- I expect the last checkbox to take 3 days of work. 

## Goals
- Implement GitHub issue search through an extension.
- Extension search providers should be on par with search providers in Go. 
  - GraphQL API should be able to return search results from extensions
- This works with the new subquery search.
- The API designed this month should work for invoking extensions in such a way that satisfies the "callable via GraphQL API" requirement next month
  - ie don't throw out the API after this month

## Milestones

- [x] @attfarhan Create a generic search result interface in the GraphQL API, includes all the fields we need to display search results on Sourcegraph.com. Ship this to sourcegraph.com. (PR https://github.com/sourcegraph/sourcegraph/pull/998).
- [x] @vanesa Add dynamic filter that adds `type:issue` so users know about the new GitHub issue search when the [github extras](https://sourcegraph.com/extensions/sourcegraph/github-extras) extension is enabled (Frontend PR: https://github.com/sourcegraph/sourcegraph/pull/999, Extension PR: coming soon)
  - [x] Add new extension API that allows extensions to contribute filter chips
- [x] @attfarhan The web was updated to use the new type in the first bullet point item. Update all the other callers of the search api to use the new interface (browser extensions, src cli, etc). 
  - Take into account how things might break if e.g. a new browser extension version is connected to an old Sourcegraph instance that doesn't have the new generic type.
- [x] @attfarhan Think about how we make this backward compatible for browser extension (and cli, etc.)
- [ ] @attfarhan Write the extension API, `registerSearchResultsProvider` for searching any content
  - This API has to return the same generic search result type as the GraphQL API from the previous step. [WIP PR: #1275](https://github.com/sourcegraph/sourcegraph/pull/1275)
  - Simple diff to sourcegraph.d.ts file and get it reviewed by Quinn and Keegan 
  - Document each field and type well
  -  Will the search result interface work for GitHub issues, google docs, config files, javadoc, etc.?
- [ ] @attfarhan Implement GitHub issue search in an extension, using the above extension API, which directly hits the GitHub API. This is a weird intermediate state. Some results will come from graphql API and some results will be contributed by the extension. [Extension repo](https://github.com/attfarhan/github-issue-search)
  - [ ] “Feature flag” the extension such that it only works if type:issue is included in the query
  - The Sourcegraph frontend will have to fetch results from extensions and our Go backend. @attfarhan has hacked this together already.
- [ ] Update the Sourcegraph UI to display search results from extensions nicely.
  - [ ] Implement match highlights for rendered markdown
  - [ ] Fix any visual bugs when displaying rendered markdown results.

**Comment by vanesa** [comment]
https://cl.ly/61bc34cb408c
Issue Filter WIP

**Comment by attfarhan** [comment]
Update: spent a few hours yesterday and all of today wrestling with marked/highlightjs/our match highlighting to get syntax highlighting, markdown rendering, and match highlighting to work nicely for the generic search result type. I just updated the PR https://github.com/sourcegraph/sourcegraph/pull/998 with the code that makes it work with diff and commit search pretty nicely (there are some UI bugs due to heuristics that I've used/assumptions made).

Will be back on after dinner to clean up the code + do more testing to make sure it actually works with results beyond our diff/commit search.

**Comment by vanesa** [comment]
Update: https://github.com/sourcegraph/sourcegraph/pull/999 was merged so that search filters can be contributed through the github-extras extension. 
Gif on how adding a search filter through the extension would look like: https://cl.ly/add455078e1a

**Comment by francisschmaltz** [comment]
Designs for GitHub search https://zpl.io/VYkQ1dn

**Comment by sqs** [comment]
We will update this tracking issue for 3.1 sometime in the week of 2018-01-28 with @attfarhan 	@nicksnyder 	@keegancsmith 	@sqs.

**Comment by lguychard** [comment]
This is stale.
