### ISSUE TITLE
Run Campaigns user tests with Sourcegraph colleagues

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#9912]
Here is the list of everybody who raised their hand in the Company meeting when we asked for volunteers:

- Quinn
- Tomás
- Asdine
- Ryan Blunden
- Nick
- Aileen
- Beyang
- Garo

We send a script to each of them:

```
Hey <firstname>!

We're happy to hear that you want to help us with testing and polishing Campaigns!

Here's what you need to do:

1. Setup your Sourcegraph instance to have one code host configuration syncing the sourcegraph-testing GitHub org (https://github.com/sourcegraph-testing)
2. Create a campaign that does the following in at least 5 repositories:
  a. Run Comby (https://comby.dev/) to replace `fmt.Sprintf("%d", :[v])` with `strconv.Itoa(:[v])` in Go files (`*.go`)
  b. Run `go fmt ./...` in the repository
3. Write up everything you're bumping into, document whenever you get stuck. Ideally you include screenshots. (Take a look at Joe's report for inspiration: https://gist.github.com/unknwon/b7c80d23e6b2a624e50e4073454959e0)
4. Send us your report! Done!

Here's what you need to get started: https://docs.sourcegraph.com/user/campaigns

Now, we won't give you more detailed steps yet, the idea behind this testing is that you use the documentation to find answers. Where the docs are lacking, we need to fix them.

But as a little tip, this page here should help run your campaign, once you've read the rest of the docs: https://docs.sourcegraph.com/user/campaigns/examples/refactor_go_comby

Have fun!
```

TODOs:

- [x] Make sure that the example campaign generates enough diffs in the `sourcegraph-testing` organization (@mrnugget)
- [ ] Send script to,  assist in case questions come up, collect feedback and turn into tickets:
  - [ ] Quinn (_Status: Script sent._)
  - [x] Tomás (_Status: Script sent._)
  - [x] Asdine (_Status: Feedback received._)
  - [ ] Ryan Blunden (_Status: Script sent._)
  - [ ] Nick (_Status: Script sent._)
  - [ ] Aileen (_Status: Script sent._)
  - [x] Beyang (_Status: Feedback received. Feedback incorporated in multiple fixes to docs._)
  - [x] Garo (_Status: Feedback received._)

---

Feedback:

- Beyang: https://docs.google.com/document/d/1BvNyur-iOAjsM3cn2VzxZd88gPUXnLlgXFxCOAbbWOI/edit?ts=5e9ddccf
- Asdine:

  > this is great, you should push that to production right away, I can’t wait to use on my own stuff and share it to my friends and to give you even more feedbacks

- Tomás: https://github.com/sourcegraph/sourcegraph/issues/9912#issuecomment-621262529
- Garo: https://docs.google.com/document/d/1AtaJ8XvhDskcZOQtynuLKYq8thd727nI7baWNGGuEkU/edit
---

**SPOILER ALERT! CHEAT CODE DETECTED!** The following is a complete action definition that would produce the correct diffs:

<details>

```json
{
  "scopeQuery": "lang:go fmt.Sprintf(\"%d\", fork:yes -repo:sourcegraph-testing/go",
  "steps": [
    {
      "type": "docker",
      "image": "comby/comby",
      "args": [ "-in-place", "fmt.Sprintf(\"%d\", :[v])", "strconv.Itoa(:[v])", ".go", "-matcher", ".go", "-d", "/work", "-exclude-dir", ".,vendor" ]
    },
    {
      "type": "docker",
      "image": "golang:1.14-alpine",
      "args": ["sh", "-c", "cd /work && go fmt ./..."]
    }
  ]
}
```

</details>

**Comment by mrnugget** [comment]
@tsenart's feedback, collected here:

1. The "Get started" on splash page (when the feature flag is disabled) should be improved:
    - Video needs to be replaced with something that actually explains what it is about
    - Doesn't link to "Get started" guide
    - "2. Optional: enable read acces " doesn't have a link
    - Buttons below the steps are confusing
1. Lot of indirection in documentation:
    - Splash pages link to index page of docs, as part of 3 steps. On the index page the user then feels lost.
    - Splash page should probably only link to "Are you a first time user?" in documentation.
    - Tomás wants a clear "checklist" of things to do, no jumping around to other lists (and feeling like you're off the trail)
1. That the feature flag is called "automation" is confusing. We need an alias for "campaigns"/"automation".
1. Suggestion: "Enable Campaigns" quick action in the config editor.
1. 🐛**BUG**: the page needs a reload after updating the settings for the feature flag to take effect.
1. Empty "campaigns list view" (`/campaigns`) has no clear call-to-action besides "+ New campaign", but multiple links to documentation. There should be a single "Click here to learn how to get started" link.
1. The explanation texts on `/campaigns/create` are confusing: "Use the src CLI" in "Create and track changesets" doesn't make sense to the user.
1. When creating a new campaign, on `/campaigns/cli`, it's confusing that there's a call-to-action to documentation ("Take a look at the documentation") right above a checklist. Confusion around "what should I do? Follow steps here or look at docs?"
1. 🐛**BUG**: The URL for the Darwin binary is wrong. It should be "da**r**win" and not "dawin"
1. "Don't you need `chmod +x` after downloading?"
1. `src` needs to print _something_ if the scope query didn't match anything, even in non-verbose mode.
1. The verbose mode of `src action exec` has no indicator of _current_ progress. You don't know what's currently happening and how far along you are. Idea: progress bar at the bottom, like `cargo` has.
1. When creating a new campaign: "Create" button does _not_ have confirmation. This is _scary_. We probably want a "Are you sure that you want to create X pull requests on GitHub?"
1. When creating a new campaign: "Create draft" — Tomás: "I don't know what that does"
1. "Publishing campaign" needs confirmation. When looking at a draft campaign: "The 'Publish campaign' button is too promiment and too dangerous. Does it have a confirmation?"
1. Tomás' feedback regarding campaign creation flow: "I think 'draft mode' should be the default. I probably never want to open _all_ pull requests without taking my time to review them". The "create campaign" form with the patchset preview feels too "ephemeral".
1. Looking at list of patches of a draft campaign: "I expected clicking the repository name expands the diff, instead it opens the repository. I would expect that to be called 'Open repository'."
1. Long diffs are hard to scroll through and keep track of. Tomás' idea: use vertical scrolling for changeset diffs and only show ~50 lines.
1. 🐛**BUG**: a dot (`.`) in a branch name shouldn't be allowed. That's not valid and breaks.
1. 🐛**BUG**: when creation of changeset fails, the errors show up at the top, but the "Publishing" next to a patch set is still a spinner and "Publishing...". It should show that there's an error. Otherwise, if it's a long list of patches, the user misses the errors at the top.

**Comment by mrnugget** [comment]
Garo's feedback: https://docs.google.com/document/d/1AtaJ8XvhDskcZOQtynuLKYq8thd727nI7baWNGGuEkU/edit#

Extracted:

1. **docs**: in "Getting Started" the "Check your code host configuration" doesn't link to the specific section in `/user/campaigns/configuration`.
1. **docs**: it's confusing that the docs call the same thing "External services", "code host configuration" and "code host connection"
1. confusion about token that's used to create PRs: "which GitHub connection the token is being taken from"
1. **docs**: missing explanation of how to run a script file: "My task involves some nested if logic and string templating, so i immediately know i’m going to shell out to an external script file, but it’s not clear how to do this"
1. **docs**: we need to explicitly explain how the `"args"` field is to be used with `"command"` steps. It's a Go-ism that nobody who hasn't run a `Cmd` with Go gets: "Turns out what i need to do is separate the args “python3”, “$HOME/sourcegraph/campaigns-test/lsif-ci.py” (this is not something i’ve had to do before when writing bash lines in script files)"
1. **docs**: we need to more prominently call out that `"command"` is not executed in a shell: "Turns out $HOME isn’t working, i replace with a hardcoded /home/garo"
1. **missing-feature**: we need a confirmation dialog (or a warning/note/explanation/etc.) before creating PRs: "oh boy, it’s sending out 62 PRs. would’ve been nice to have a confirm step!"
1. **missing-feature**: permission errors when creating PRs: "They all fail due to access token issues. The same error message is duplicated 50 times at the top of my screen. I don’t notice for several minutes because they’re in a nondescript blue box" Besides allowing users to specify their own credentials here, I think we need a first, additional validation step when creating a campaign, to check the access rights per repository. Possibly flagging each repository in the UI with a red marker or something, so users can then publish single changesets.
1. **bug**: when creating a changeset fails, the "publish button loops forever" (the spinner doesn't disappear")
1. **bug**: the default burndown chart for a new campaign is confusing. "I eventually get them [the changesets] publishing, and a large graph pops up and takes up half my screen. It’s not currently giving me any useful information, and is not really aesthetically pleasing"
1. **missing-feature**: ability to create changesets as _drafts on code host_ (GitHub): "All the PRs i just opened are failing, and one already has a comment on it. Wish i could run CI on these things before actually notifying the repo owners about them"
1. **bug**: "From blackbox testing, it seems like publish button doesn’t work when the retry button is available?"
1. **bug**: when filtering changesets the browser jumps to top of page: "when i fiddle with the dropdowns my browser jumps back to the top of the page"
1. **missing-feature**: no ability to re-open a campaign.
1. **missing-feature**: changesets can only be published "one at a time" or "all at once". "i wish there were tick boxes."
1. **bug**: unclear that the campaign's title/description are used for the created changesets. We need more explanation of what each form field does ("branch", title, etc.). Can possibly be combined with a better explanation of the "publish" button
1. **missing-feature**: closing the PRs (by closing the campaign) didn't "delete the associated branches". We should offer "close and delete" branches.
1. **missing-feature**: we need to make it clear that setting up webhooks reduces need to manually refresh: "i had to click the “refresh” button next to the repos a lot."
1. **missing-feature**: better guidance for writing `scopeQuery`s. "I wanted to use the scopeQuery to ignore stale repos, but wasn’t sure how to do this". Some of that could be docs, but also UI/src-cli.
1. **missing-feature**: better support in `src-cli` for executing script files: "I wish running a campaign from a script file was better supported"
1. **general**: "so cool!! It makes my dev brain light up with possibilities"
1. **general**: talking about a terminal UI: "could campaigns be developed interactively? It’d be super duper awesome to have a shell prompt, input commands, and have them run over every repo you specified with a scope, and see the output for each (or the first N) repos. You could iteratively make changes, drop/add repos from your scope, etc"
1. **general**: "In general the iteration process for developing a campaign is slow, so any smaller things to make this easier would help (e.g. option to show errors in the output of the command, only rerun on error’d repos, etc)"

**Comment by mrnugget** [comment]
## Bugs

1. ~**🐛bug**: The URL for the Darwin binary is wrong. It should be "da**r**win" and not "dawin"~
    - **STATUS**: Added files with wrong name to releases on GitHub so that the download works for now. Fixed in UI too.
1. ~**🐛bug**: a dot (`.`) in a branch name shouldn't be allowed. That's not valid and breaks.~
    - Fixed with https://github.com/sourcegraph/sourcegraph/pull/10298
1. **🐛bug**: the page needs a reload after updating the settings for the feature flag to take effect.
1. **🐛bug**: when creation of changeset fails, the errors show up at the top, but the "Publishing" next to a patch set is still a spinner and "Publishing...". It should show that there's an error. Otherwise, if it's a long list of patches, the user misses the errors at the top.
1. **🐛bug**: "From blackbox testing, it seems like publish button doesn’t work when the retry button is available?"
1. **🐛bug**: When filtering changesets the browser jumps to top of page: "when i fiddle with the dropdowns my browser jumps back to the top of the page"
1. **🐛bug**: unclear that the campaign's title/description are used for the created changesets. We need more explanation of what each form field does ("branch", title, etc.). Can possibly be combined with a better explanation of the "publish" button

## Documentation

### New user flow

1. **📚docs**: `/campaigns` splash page when feature flag is **off**:
    - Video needs to be replaced with something that actually explains what it is about
    - Doesn't link to "Get started" guide
    - "2. Optional: enable read acces " doesn't have a link
    - Buttons below the steps are confusing
    - Too many calls to actions
1. **📚docs**: Indirection in documentation
    - Splash pages link to index page of docs, as part of 3 steps. On the index page the user then feels lost.
    - Splash page should probably only link to "Are you a first time user?" in documentation.
    - Tomás wants a clear "checklist" of things to do, no jumping around to other lists (and feeling like you're off the trail)
1. **📚docs**: We need a video that explains  _why_ to use Campaigns and for _what_ and how it works.
1. **📚docs**: "Don't you need `chmod +x` after downloading?"
1. **📚docs**: in "Getting Started" the "Check your code host configuration" doesn't link to the specific section in `/user/campaigns/configuration`.

### General

1. **📚docs**: it's confusing that the docs call the same thing "External services", "code host configuration" and "code host connection"

### `src action exec` documentation

1. **📚docs**: Easier way from tutorial to examples in docs? "Now I went back to campaign docs here https://docs.sourcegraph.com/user/campaigns/creating_campaign_from_patches. Would be great if I had an example I could just try out."
1. **📚docs**: missing explanation of how to run a script file: "My task involves some nested if logic and string templating, so i immediately know i’m going to shell out to an external script file, but it’s not clear how to do this"
1. **📚docs**: We need to explicitly explain how the `"args"` field is to be used with `"command"` steps. It's a Go-ism that nobody who hasn't run a `Cmd` with Go gets: "Turns out what i need to do is separate the args “python3”, “$HOME/sourcegraph/campaigns-test/lsif-ci.py” (this is not something i’ve had to do before when writing bash lines in script files)"
1. **📚docs**: We need to more prominently call out that `"command"` is not executed in a shell: "Turns out $HOME isn’t working, i replace with a hardcoded /home/garo"

### src-cli

1. **📚docs**: src-cli docs should suggest how to check that authentication works.

## Needs improvement

### General

1. **🚨improvement**: That the feature flag is called "automation" is confusing. We need an alias for "campaigns"/"automation". Suggestion: "Enable Campaigns" quick action in the config editor.
1. **🚨improvement**: we should allow changing the branch name in case the changesets failed to be created.

### User flow and onboarding new users

1. **🚨improvement**: Empty "campaigns list view" (`/campaigns`) has no clear call-to-action besides "+ New campaign", but multiple links to documentation. There should be a single "Click here to learn how to get started" link.
1. **🚨improvement**: The explanation texts on `/campaigns/create` are confusing: "Use the src CLI" in "Create and track changesets" doesn't make sense to the user.
1. **🚨improvement**: When creating a new campaign, on `/campaigns/cli`, it's confusing that there's a call-to-action to documentation ("Take a look at the documentation") right above a checklist. Confusion around "what should I do? Follow steps here or look at docs?"
1. **🚨improvement**: Confirmation for "Create campaign" and better explanation for what "Create campaign" and "create draft" do
    - When creating a new campaign: "Create" button does _not_ have confirmation. This is _scary_. We probably want a "Are you sure that you want to create X pull requests on GitHub?"
    - When creating a new campaign: "Create draft" — Tomás: "I don't know what that does"
    - "Publishing campaign" needs confirmation. When looking at a draft campaign: "The 'Publish campaign' button is too promiment and too dangerous. Does it have a confirmation?"
    - we need a confirmation dialog (or a warning/note/explanation/etc.) before creating PRs: "oh boy, it’s sending out 62 PRs. would’ve been nice to have a confirm step!"

### Permissions/Authentication

1. **🚨improvement**: about token that's used to create PRs: "which GitHub connection the token is being taken from"
1. **🚨improvement**: permission errors when creating PRs: "They all fail due to access token issues. The same error message is duplicated 50 times at the top of my screen. I don’t notice for several minutes because they’re in a nondescript blue box" Besides allowing users to specify their own credentials here, I think we need a first, additional validation step when creating a campaign, to check the access rights per repository. Possibly flagging each repository in the UI with a red marker or something, so users can then publish single changesets.

### UI

1. **🚨improvement**: we need to make it clear that setting up webhooks reduces need to manually refresh: "i had to click the “refresh” button next to the repos a lot."
1. **🚨improvement**: burndown chart for a new campaign is confusing. "I eventually get them [the changesets] publishing, and a large graph pops up and takes up half my screen. It’s not currently giving me any useful information, and is not really aesthetically pleasing"
1. **🚨improvement**: Looking at list of patches of a draft campaign: "I expected clicking the repository name expands the diff, instead it opens the repository. I would expect that to be called 'Open repository'."
1. **🚨improvement**: Long diffs are hard to scroll through and keep track of. Tomás' idea: use vertical scrolling for changeset diffs and only show ~50 lines.

### src-cli

1. **🚨improvement**: verbose mode of `src action exec` has no indicator of _current_ progress. You don't know what's currently happening and how far along you are. Idea: progress bar at the bottom, like `cargo` has. https://github.com/sourcegraph/src-cli/issues/190 
1. **🚨improvement**: We should probably add some instructions to `src action exec` when everything went well and we print a patch to stdout. Idea: print instructions to STDERR. Original quote: "I got some crazy json output which I assume is the patch. Can we include instructions for those of us who don’t follow docs too closely :) I had no idea what had happened until I read the docs again."
1. **🚨improvement**: `src` needs to print _something_ if the scope query didn't match anything, even in non-verbose mode. https://github.com/sourcegraph/src-cli/issues/189
1. **🚨improvement**: better support in `src-cli` for executing script files: "I wish running a campaign from a script file was better supported"
1. **🚨improvement**: `~/src-config.json` is a yuck location: https://github.com/sourcegraph/src-cli/issues/156
1. **🚨improvement**: Manual pulling of images is not good: "Why did I need to pull comby/comby? docker you normally just pull if missing?"
1. **🚨improvement**: "Maybe strip out = suffix from b64 encoded campaign ids. We don’t need the padding, and = messes up some clients who guess URL boundaries."
1. **🚨improvement**: better guidance for writing `scopeQuery`s. "I wanted to use the scopeQuery to ignore stale repos, but wasn’t sure how to do this". Some of that could be docs, but also UI/src-cli.

## Feature requests

1. **✨feature-request**: create changesets as _drafts on code host_ (GitHub): "All the PRs i just opened are failing, and one already has a comment on it. Wish i could run CI on these things before actually notifying the repo owners about them"
1. **✨feature-request**: ability to re-open a campaign.
1. **✨feature-request**: checkboxes to modify multiple patches/changesets at the same time: patches can only be published "one at a time" or "all at once". "i wish there were tick boxes."
1. **✨feature-request**: ability to delete branches: closing the PRs (by closing the campaign) didn't "delete the associated branches". We should offer "close and delete" branches.
1. **✨feature-request**: YAML support in src-cli

## General feedback

1. **💡general**: "so cool!! It makes my dev brain light up with possibilities"
1. **💡general**: talking about a terminal UI: "could campaigns be developed interactively? It’d be super duper awesome to have a shell prompt, input commands, and have them run over every repo you specified with a scope, and see the output for each (or the first N) repos. You could iteratively make changes, drop/add repos from your scope, etc"
1. **💡general**: "In general the iteration process for developing a campaign is slow, so any smaller things to make this easier would help (e.g. option to show errors in the output of the command, only rerun on error’d repos, etc)"
1. **💡general**: Tomás' feedback regarding campaign creation flow: "I think 'draft mode' should be the default. I probably never want to open _all_ pull requests without taking my time to review them". The "create campaign" form with the patchset preview feels too "ephemeral".
