### ISSUE TITLE
Web: 3.16 tracking issue

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#9915]
## Work

@Unassigned

- [x] Smart search shows no suggestions when filter value is a regex pattern [#10770](https://github.com/sourcegraph/sourcegraph/issues/10770) 🐛

@attfarhan: __5.50d__

- [x] Implement RFC 150: Version contexts UI and frontend work [#10196](https://github.com/sourcegraph/sourcegraph/issues/10196) __4d__ 
- [ ] ~Communicate that `lang:` filter supports languages beyond suggestions~ [#10148](https://github.com/sourcegraph/sourcegraph/issues/10148) __0.5d__ 
- [x] Copy query button [#10020](https://github.com/sourcegraph/sourcegraph/issues/10020) __1d__ 
- [x] Add protocol buffers to our `lang:` search filter [#9750](https://github.com/sourcegraph/sourcegraph/issues/9750) __0.5d__ 
- [ ] ~Interactive search doesn't play well with suggestions~ [#9378](https://github.com/sourcegraph/sourcegraph/issues/9378) __1d__ 
- [ ] ~Try enzyme for cleaner snapshot tests~ [#9040](https://github.com/sourcegraph/sourcegraph/issues/9040) __0.5d__ 🧶
- [x] "/" hotkey to focus search input is broken [#10309](https://github.com/sourcegraph/sourcegraph/issues/10309) 🐛
- [ ] ~Explore alternatives to Reactstrap~ [#6443](https://github.com/sourcegraph/sourcegraph/issues/6443) __3d__ 🧶

@efritz

- [x] Add Cobol support (lang filters, codeintel) [#10154](https://github.com/sourcegraph/sourcegraph/issues/10154) 

@eseliger: __4.50d__

- [x] Add nightly browser extension test runs [#7980](https://github.com/sourcegraph/sourcegraph/issues/7980) __3d__ 🧶
- [x] Syntax highlighting for diff hunks [#9166](https://github.com/sourcegraph/sourcegraph/issues/9166) __1.5d__ 
- [x] Branches in branch switcher cannot be clicked anymore [#10590](https://github.com/sourcegraph/sourcegraph/issues/10590) 🐛

@felixfbecker: __11.00d__

- [x] Prototype graph contributions [#10018](https://github.com/sourcegraph/sourcegraph/issues/10018) __4d__ 
  - [x] Add support for charts to the extension API [#10550](https://github.com/sourcegraph/sourcegraph/pull/10550) :shipit:
- [x] Prototype directory level contributions [#10017](https://github.com/sourcegraph/sourcegraph/issues/10017) __4d__ 
- [x] Update to comlink v4 [#3989](https://github.com/sourcegraph/sourcegraph/issues/3989) __2d__ 🧶
  - [x] Uprade to comlink v4  [#10149](https://github.com/sourcegraph/sourcegraph/pull/10149) :shipit:🧶
- [x] Go-to-def on GitHub appends absolute URL  [#10287](https://github.com/sourcegraph/sourcegraph/issues/10287) 🐛
- [x] Percy should not run on release branches [#4505](https://github.com/sourcegraph/sourcegraph/issues/4505) __0.5d__ 
- [x] Add Percy tests from storybooks [#9565](https://github.com/sourcegraph/sourcegraph/issues/9565) __0.5d__ 
  - [x] Take percy snapshots of storybooks [#10622](https://github.com/sourcegraph/sourcegraph/pull/10622) :shipit:
- [x] Make ActionItems open in new tab if external links [#10345](https://github.com/sourcegraph/sourcegraph/pull/10345) :shipit:👩
- [x] Use browser extension Port objects instead of hacky comlink string channel [#10302](https://github.com/sourcegraph/sourcegraph/pull/10302) :shipit:🐛🧶
- [x] Add directory page extension APIs [#10236](https://github.com/sourcegraph/sourcegraph/pull/10236) :shipit:
- [x] Fix conflicting storybook styles [#10033](https://github.com/sourcegraph/sourcegraph/pull/10033) :shipit:

@keegancsmith

- [x] Proposal: remove discussions code [#9649](https://github.com/sourcegraph/sourcegraph/issues/9649) 🧶

@lguychard: __3.50d__

- [ ] ~Add puppeteer integration tests~ [#10037](https://github.com/sourcegraph/sourcegraph/issues/10037) __4d__ 
- [ ] ~Fix error property propagation from background pages~ [#9693](https://github.com/sourcegraph/sourcegraph/issues/9693) __1d__ 🧶
- [x] Intermediate plain text search bar should use same font as Monaco editor [#9499](https://github.com/sourcegraph/sourcegraph/issues/9499) __0.5d__ 
- [ ] ~OptionsMenu code is a mess~ [#9282](https://github.com/sourcegraph/sourcegraph/issues/9282) __1d__ 🧶
- [x] Search bar steals "Cmd+L" keybinding [#9125](https://github.com/sourcegraph/sourcegraph/issues/9125) 🐛
- [x] New search autocomplete yields no results in this particular case [#8749](https://github.com/sourcegraph/sourcegraph/issues/8749) 
- [x] Cursor is put at the beginning of search field after submitting (instead of staying at end) [#8731](https://github.com/sourcegraph/sourcegraph/issues/8731) __0.5d__ 🐛
- [x] MonacoQueryInput does not shrink when the window is resized. [#7692](https://github.com/sourcegraph/sourcegraph/issues/7692) __1d__ 🐛
- [x] Browser extension not working when sourcegraphURL has a trailing slash [#6521](https://github.com/sourcegraph/sourcegraph/issues/6521) __1d__ 🐛
- [x] Repogroup autocomplete [#10141](https://github.com/sourcegraph/sourcegraph/issues/10141) __0.5d__ 
- [ ] ~Improve documentation on Phabricator development & debugging~ [#10223](https://github.com/sourcegraph/sourcegraph/issues/10223) __1d__ 
- [x] web: pressing CTRL+SPACE with smart search enabled doesn't show filter list [#10441](https://github.com/sourcegraph/sourcegraph/issues/10441) 🐛

@rrhyne: __0.50d__

- [ ] RFC 136: Version context design testing [#10574](https://github.com/sourcegraph/sourcegraph/issues/10574) __0.5d__ 

@twop

- [ ] ~Basic code intel info button is wrong size and color~ [#9065](https://github.com/sourcegraph/sourcegraph/issues/9065) 🐛

### Legend

👩 Customer issue
🐛 Bug
🧶 Technical debt
🛠️ Roadmap
🕵️ Spike
🔒 Security issue
:shipit: Pull Request

**Comment by eseliger** [comment]
## W14 Summary

- Mostly worked on campaigns public beta documentation and splash pages
- Small UI feature to see when a changeset will be resynced https://github.com/sourcegraph/sourcegraph/pull/9891

## W15 Plan

- Q2 planning for web and campaigns

**Comment by felixfbecker** [comment]
### W14 Recap
- Fix code intel paper cut issues (#9914, https://github.com/sourcegraph/codeintellify/pull/251)
- Fix "Function of extension-contributed buttons is not clear" (details in https://github.com/sourcegraph/sourcegraph/issues/5488#issuecomment-613288907)
- Add tooling for tracking npm third party licenses (#9823)
- Small fix: #9800
- ESLint and build tooling upgrades in external repos
- Some CI fixes
- Planning of [RFC 144: Code Insights](https://docs.google.com/document/d/1EHzor6I1GhVVIpl70mH-c10b1tNEl_p1xRMJ9qHQfoc/edit)

### W15 Plan
- Extend TypeScript dev docs
- Fix Percy styling issue
- Fix wrong z-indexes issue
- Work on RFC 144

**Comment by attfarhan** [comment]
## W14 Summary
- Merged onboarding changes
- Fixed file tree not updating on code intel actions
- 4 Coding exercises/interviews

## W15 plan
- Q2 planning 
- Copy button for queries
- Write RFC for search input not parsing filters in interactive mode
- Continue replacing Reactstrap with Reach UI

**Comment by attfarhan** [comment]
## W15 summary
- Q2 planning
  - [3.14 search data writeup](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1587657607062400)
  - Reviewed Q2 OKRs
- [RFC 150: version contexts frontend work](https://docs.google.com/document/d/1G8vxRF5m8mrOvjmYxWSUW3yko0q-jKAMMD7Y-h2CWeY/edit#heading=h.trqab8y0kufp)
- Copy button for queries https://github.com/sourcegraph/sourcegraph/pull/10168
- Revisited old saved searches PR to use namespaceIDs in GQL API https://github.com/sourcegraph/sourcegraph/pull/5327
- 5 coding challenges/follow-up calls

## W16 plan
- Finalize RFC 150
- Start planning and implementing RFC 150: version contexts frontend
- Continue replacing Reactstrap with Reach UI (with any free time from above)

**Comment by lguychard** [comment]
## W15 Summary
- Several smart search fixes: #10024, #10029, #10035, #10080
- Drafted [RFC 149](https://docs.google.com/document/d/1ji4sjqMJGpTUL6FjJcPM6HIdJfFPboSjRJoIfAqvxdc/edit): frontend integration tests


## W16 Plan
- Explore Polly and other hypotheses (FSMs?) for RFC 149
- https://github.com/sourcegraph/sourcegraph/issues/7692

**Comment by felixfbecker** [comment]
### W15 Summary
- Extend our TypeScript dev documentation https://github.com/sourcegraph/sourcegraph/pull/10028
- Add workaround for Caddy issues https://github.com/sourcegraph/sourcegraph/pull/10021
- Solved conflicting storybook styles so we can use them for testing https://github.com/sourcegraph/sourcegraph/pull/10033
- Added GraphQL highlighting https://github.com/sourcegraph/sourcegraph/pull/10043
- Fixed browser extension release (e2e tests) https://github.com/sourcegraph/sourcegraph/pull/10075
- Upstreamed types improvements to comlink v4 and upgraded us  https://github.com/sourcegraph/sourcegraph/pull/10149
- Helped with sqs's view provider API (relevant to code insights) 
- 2 interviews

### W16 Plan
- Work on Code Insights

**Comment by attfarhan** [comment]
## W16 summary
- Finalized [RFC 150: version contexts frontend work](https://docs.google.com/document/d/1G8vxRF5m8mrOvjmYxWSUW3yko0q-jKAMMD7Y-h2CWeY/edit#heading=h.trqab8y0kufp)
- Copy button for queries https://github.com/sourcegraph/sourcegraph/pull/10168
- Merged saved searches PR to use namespaceIDs in GQL API https://github.com/sourcegraph/sourcegraph/pull/5327
- Fixed Safari tabs bug https://github.com/sourcegraph/sourcegraph/commit/e62b6218f61cc1564d6ebcae19f9dafdf1357567
- Updated search team handbook page https://about.sourcegraph.com/handbook/engineering/search

## W17 plan
- Implement version contexts frontend https://github.com/sourcegraph/sourcegraph/issues/10196
- Fix '\' hotkey not working https://github.com/sourcegraph/sourcegraph/issues/10309

**Comment by lguychard** [comment]
## W16 Summary

4-day week.

- Wrote up some thoughts on improving native integration activation: https://github.com/sourcegraph/sourcegraph/issues/10225
- Added repogroup autocompletion: #10286 
- Started exploring Polly for integration tests

## W17 Plan

This week is another 4-day week for me. My main goal is to wrap up prototyping options for integration tests.

**Comment by felixfbecker** [comment]
### W16 Summary

4-day week.
- Fix in-app links within markdown (code insights and also  #10198
  - Also related: Don't hard-reload when clicking search results #10349
- Allow including SVG in MarkupContent (code insights) #10206
- Redirect trees to blobs and vice versa (code insights) #10193
- Remove discussions feature from webapp #10262
- Fix GitHub file path detection on PRs (P1 issue) #10310
- Add directory page extension APIs (code insights) #10236
- Make ActionItems open in new tab if external links (customer request) #10345
- Fix flaky j2d when definition was not loaded yet #10369
- Fix Firefox extension with Sentry #10367
- Fix comlink memory leaks we had for a long time and bext release branch #10302

### W17 Plan

- Work on code insights
  - Create mockup
  - Investigate integration with search
  - Contribute graphs

**Comment by felixfbecker** [comment]
## W17 Summary

- Fixed Firefox release
- Moved TypeScript guide to handbook
- Created code insights mockup in Figma
- Worked on code insights graph contributions and search insights extension
- Helped onboard Simon and Rob

## W18 Plan

- Ship graph contributions and search insights on sourcegraph.com
- Potentially draft RFC for any search features insights need to scale
- Plan general extensions work
- Think about how we can shape a good design process (see [Rob's document](https://docs.google.com/document/d/1LemO13R3f0Ku88WK8tFr7_Qo4teDA0Bebs8Y2TGkS3U/edit#heading=h.fbo2karfxi5d))

**Comment by attfarhan** [comment]
## W17 Summary
- Version contexts work
- Fix https://github.com/sourcegraph/sourcegraph/pull/10390#issuecomment-623519376

## W18 Plan
- Ship version contexts frontend

**Comment by lguychard** [comment]
## W17 Summary

- Fixed https://github.com/sourcegraph/sourcegraph/issues/6521, the Sourcegraph URL can now be specified with or without a trailing slash indifferently in the browser extension and native integrations.
- Spent a lot of time on hiring (reviewing large backlog of applications, intro calls, debriefs).
- Discussed future extensions & code insights work with @felixfbecker and @twop: https://docs.google.com/document/d/1d51V8czyomJBjl269Gm_hwzuYIKZUfsbrS1B4NYSq-E/edit#
- Started experimenting with Polly for integration tests, but I still need a bit more time exploring it to decide whether that's what we should go with.

## W18 Plan

- Marek onboarding :)
- A lot of intro calls (6 today!)
- This week is the week I shall finish my integration test experiments and share findings in the RFC / send up a PR 🙂

**Comment by eseliger** [comment]
## W17 Summary

- Better tooling around GraphQL https://github.com/sourcegraph/sourcegraph/pull/10352
- After all issues with bext e2e tests were fixed, I was able to turn on the nightly DOM change checks in CI https://github.com/sourcegraph/sourcegraph/pull/10406
- Worked on syntax highlighting for diffs and preview diffs https://github.com/sourcegraph/sourcegraph/pull/10437
- Fixed a bug in our diff parser https://github.com/sourcegraph/go-diff/pull/45 that led to files with unicode file names (Chinese for example) to be unescaped and quoted

## W18 Plan

- Bring syntax highlighting across the finish line
- Finish YAML support for actions
- Finish auto docker image pull for src-cli

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
