### ISSUE TITLE
Code intelligence: 3.16 tracking issue

### ISSUE THREAD

**Issue by creachadair** [sourcegraph/sourcegraph#9917]
@Unassigned

- [x] Alert admins if LSIF uploads are too large for DBS_DIR_MAXIMUM_SIZE_BYTES [#9989](https://github.com/sourcegraph/sourcegraph/issues/9989) 
- [x] Request for Tcl basic language support [#9994](https://github.com/sourcegraph/sourcegraph/issues/9994) 

@efritz

- [x] Add metrics (and dashboard) to new precise-code-intel services [#10238](https://github.com/sourcegraph/sourcegraph/issues/10238) 
- [x] Add tracing to new precise-code-intel services [#10237](https://github.com/sourcegraph/sourcegraph/issues/10237) 
- [x] Add Cobol support (lang filters, codeintel) [#10154](https://github.com/sourcegraph/sourcegraph/issues/10154) 
- [x] Fix docs for LSIF option DBS_DIR_MAXIMUM_SIZE_BYTES [#9987](https://github.com/sourcegraph/sourcegraph/issues/9987) `docs` 🐛
- [x] Port precise-code-intel-worker to Go [#9965](https://github.com/sourcegraph/sourcegraph/issues/9965) 
- [x] Port precise-code-intel-bundle-manager to Go [#9964](https://github.com/sourcegraph/sourcegraph/issues/9964) 
- [x] Port precise-code-intel-api-server to Go [#9963](https://github.com/sourcegraph/sourcegraph/issues/9963) 
- [x] Basic code intel definition ranges are off [#9936](https://github.com/sourcegraph/sourcegraph/issues/9936) 🐛
- [x] LSIF upload: 413 Request Entity Too Large [#9739](https://github.com/sourcegraph/sourcegraph/issues/9739) 
- [x] Improve performance of LSIF upload processing [#9593](https://github.com/sourcegraph/sourcegraph/issues/9593) 
- [x] Weird highlighting on multiple go to definition results with basic code intel [#7668](https://github.com/sourcegraph/sourcegraph/issues/7668) 🐛
- [x] Remove LSIF uploads after conversion [#10358](https://github.com/sourcegraph/sourcegraph/issues/10358) 
- [x] No "Go to definition" for Go symbol [#10372](https://github.com/sourcegraph/sourcegraph/issues/10372) 🐛
- [x] Request for Tcl basic language support [#9994](https://github.com/sourcegraph/sourcegraph/issues/9994) 
- [x] Bundle manager does not enforce a limit on moniker results [#10510](https://github.com/sourcegraph/sourcegraph/issues/10510) 
- [ ] ~Document LSIF data expectations~ [#9719](https://github.com/sourcegraph/sourcegraph/issues/9719) `docs` 
- [ ] ~Create docs page for codeintel showcase repos~ [#9609](https://github.com/sourcegraph/sourcegraph/issues/9609) `docs` 
- [x] Finished processing timestamp on LSIF upload details page is wrong [#9596](https://github.com/sourcegraph/sourcegraph/issues/9596) 
- [x] Update codeintel db package for worker [#10227](https://github.com/sourcegraph/sourcegraph/pull/10227) :shipit:
- [x] Add bundle writer abstraction [#10226](https://github.com/sourcegraph/sourcegraph/pull/10226) :shipit:
- [x] Add additional methods to bundle manager client [#10211](https://github.com/sourcegraph/sourcegraph/pull/10211) :shipit:
- [x] Add additional precise-code-intel gitserver behavior [#10209](https://github.com/sourcegraph/sourcegraph/pull/10209) :shipit:
- [x] Add bundle reader abstraction [#10208](https://github.com/sourcegraph/sourcegraph/pull/10208) :shipit:
- [x] Add Package and PackageReference types in bundles/types [#10207](https://github.com/sourcegraph/sourcegraph/pull/10207) :shipit:
- [x] Move precise-code-intel-api-server mock interfaces [#10205](https://github.com/sourcegraph/sourcegraph/pull/10205) :shipit:
- [x] Move bloom filter implementation to internal package [#10202](https://github.com/sourcegraph/sourcegraph/pull/10202) :shipit:
- [x] Add batch inserter util for SQLite [#10201](https://github.com/sourcegraph/sourcegraph/pull/10201) :shipit:
- [x] Rewrite precise-code-intel-worker in Go [#10105](https://github.com/sourcegraph/sourcegraph/pull/10105) :shipit:
- [ ] ~Add variable-entry-size LRU cache implementation in internal/memcache~ [#10005](https://github.com/sourcegraph/sourcegraph/pull/10005) :shipit:
- [x] Extract sqlite setup from cmd/symbols [#10004](https://github.com/sourcegraph/sourcegraph/pull/10004) :shipit:
- [ ] ~Extract disksizer from cmd/gitserver~ [#10003](https://github.com/sourcegraph/sourcegraph/pull/10003) :shipit:
- [x] Rewrite precise-code-intel-api-server in Go [#9703](https://github.com/sourcegraph/sourcegraph/pull/9703) :shipit:
- [x] Rewrite precise-code-intel-bundle-manager in Go [#9586](https://github.com/sourcegraph/sourcegraph/pull/9586) :shipit:

@gbrik

- [ ] ~Improve visual clarity and add CTAs re code intel~ [#10083](https://github.com/sourcegraph/sourcegraph/issues/10083) `planning` 
- [ ] ~Write RFC for precise code intel mono repo support~ [#10087](https://github.com/sourcegraph/sourcegraph/issues/10087) `planning` 
- [ ] ~Prototype a new LSIF indexer for C++ based on clangd-indexer~ [#10175](https://github.com/sourcegraph/sourcegraph/issues/10175) `in progress` 
- [x] doc update: code intel CI guides instructions to pass workflow even if indexing fails [#10452](https://github.com/sourcegraph/sourcegraph/issues/10452) `docs` 
- [x] docs: recommend disabling indexing on forks for public repos [#10576](https://github.com/sourcegraph/sourcegraph/issues/10576) `docs` 
- [ ] ~Minor: Retry lsif index upload when clone is in progress~ [#9700](https://github.com/sourcegraph/sourcegraph/issues/9700) `in progress` 
- [ ] ~Process pending LSIF uploads in reverse-chronological order?~ [#9985](https://github.com/sourcegraph/sourcegraph/issues/9985) 
- [ ] ~Index a super cool Go repo and its transitive dependencies~ [#9746](https://github.com/sourcegraph/sourcegraph/issues/9746) `blocked` 
- [x] No "Go to definition" for Go symbol [#10372](https://github.com/sourcegraph/sourcegraph/issues/10372) 🐛
- [x] Use campaigns to get all of our repositories uploading LSIF indexes to sourcegraph.com [#10137](https://github.com/sourcegraph/sourcegraph/issues/10137) 
  - [x] Update LSIF documentation and associated CI workflows [#10138](https://github.com/sourcegraph/sourcegraph/pull/10138) :shipit:
- [x] Write precise code intel delivery plans [#10081](https://github.com/sourcegraph/sourcegraph/issues/10081) 
- [x] improve our issue tracking process [#10082](https://github.com/sourcegraph/sourcegraph/issues/10082) 
  - [x] Update tracking issue tool to preserve issue order and display whitelisted labels [#10166](https://github.com/sourcegraph/sourcegraph/pull/10166) :shipit:
- [x] RFC 122: Write detailed LSIF integration instructions for Go and TypeScript [#9289](https://github.com/sourcegraph/sourcegraph/issues/9289) 
  - [x] Update LSIF documentation and associated CI workflows [#10138](https://github.com/sourcegraph/sourcegraph/pull/10138) :shipit:

@keegancsmith

- [x] GraphQL code intel doesn't work [#9756](https://github.com/sourcegraph/sourcegraph/issues/9756) 🐛

**Comment by gbrik** [comment]
#### Week 1 Done 20-04-2020
- [x] CI documentation #9289 #10138
- [x] Wrote precise code intel delivery plan #10081 
- [x] Hacked some new features into the tracking issue tool #10166 
- [x] Started delivering precise code intel to one customer
- [x] User communication re language server removals

#### Week 2 Planned 20-11-2020
- [ ] Minor fixes for CI documentation
- [ ] Get precise code intel delivery plan approved #10081 
- [ ] Get tracking issue features merged
- [ ] Use campaigns to enable LSIF indexing in all of our repositories #10137 
- [ ] Work on C++ indexer #10175
- [ ] Stretch: Plan tooling to support mono-repos #10087 
- [ ] Stretch: draft new designs for code intel UI #10083

**Comment by efritz** [comment]
#### Week 1 Done 20-04-2020
- [x] Rewrite api-server and bundle manager in Go

#### Week 2 Planned 20-11-2020
- [ ] Rewrite worker in Go
- [ ] Talk to @slimsag about RFC 152 to deduplicate work (may take on some of this effort in order to meet team OKRs).
- [ ] Write RFC about an auto-indexer architecture (blocked by above)

**Comment by efritz** [comment]
**Week 2 Done 2020-04-27**

- Finished worker rewrite
- Started writing [RFC 153](https://docs.google.com/document/d/1LFwtfIqTgxzyNQDRvKsWbY9pZKiXVhwPyrNB04gnpDQ/edit#) to auto-index Go source.

**Week 3 Planned 2020-05-04**

- [ ] Update tracing and metrics in the new Go services
- [ ] Write a simple integration/load test before deploying new Go services
- [ ] Launch Go services on Sourcegraph.com
- [ ] Write blog post to aid efforts such as https://github.com/sourcegraph/sourcegraph/issues/10385.

**Comment by gbrik** [comment]
#### Week 2 Done 2020-04-27
- [x] Minor fixes for CI documentation
- [x] Get precise code intel delivery plan approved #10081 
- [x] Get tracking issue features merged
- [x] Use campaigns to enable LSIF indexing in all of our repositories #10137 
- [x] lots of campaigns feedback
- [x] lots of code review
- [x] Work on C++ indexer #10175

#### Week 3 Planned 2020-05-04
- [ ] draft new designs for code intel UI #10083 
- [ ] Plan tooling to support mono-repos #10087
- [ ] Work on C++ indexer #10175

**Comment by efritz** [comment]
**Week 2 Done 2020-05-04**

TODO

**Week 3 Planned 2020-05-11**

TODO

**Comment by gbrik** [comment]
#### Week 3 Done 2020-05-04
- [x] draft new designs for code intel UI #10083 
- [x] review lots o' PRs
- [ ] Plan tooling to support mono-repos #10087
- [ ] Work on C++ indexer #10175

#### Week 3 Done 2020-05-11
- [ ] get code intel UI ready to implement #10083 
- [ ] Retry lsif index upload when clone is in progress #9700
- [ ] doc update: code intel CI guides instructions to pass workflow even if indexing fails #10452
- [ ] investigate No "Go to definition" for Go symbol #10372
- [ ] Plan tooling to support mono-repos #10087
- [ ] Work on C++ indexer #10175

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by gbrik** [comment]
#### Week 4 Done 2020-05-11
- [x] write RFC 158: Code Intel UI
- [x] started writing RFC for mono repo indexing
- [x] wrote most of retry on clone in progress #9700 

### Week 5 Planned 2020-05-18
- [ ] doc updates before release
- [ ] file issues for RFC 158 work
- [ ] publish mono repo indexing RFC
- [ ] finish clone in progress issue

**Comment by efritz** [comment]
Next tracking issue: https://github.com/sourcegraph/sourcegraph/issues/10687
